### ISSUE TITLE
[docs] make it easier to understand how to use the self hosted environment API

### ISSUE THREAD

**Issue by nati-levi** [appwrite/appwrite#10]
Tried to used the API from postman.

Searched for the base URL in the settings, with no luck. Eventually, i inferred from the code that it is `http://localhost/v1/`.

Also, no place stated that the key should be sent as header `X-Appwrite-Key`.

**Comment by eldadfux** [comment]
It is a good idea to have the UI indicating the API base endpoint. Maybe we can add it to the project settings and to the new platform dialog window.

The X-Appwrite-Key header is used to pass the secret API key and should only be used when integrating with a server side language. It can be a **MAJOR** security issue when being used directly in your client code and this is why it's not being mentioned anywhere.

**Comment by nati-levi** [comment]
I see.
So what the way to authenticate from postman like requests?

**Comment by eldadfux** [comment]
Well, it is really depends on what you are trying to achieve with postman.

If you are just trying out the API the best way is probably by treating it as a backend and just passing an API key.

If you want to mock real user behaviour, you need to use the entire register-login flow to obtain a user session cookie, and then add it to all other requests.

This might be easier if in some point we will add Appwrite as an OAuth provider on its own, and then auth process will be more straight forward from 3rd parties like postman.

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/64925386-7b2e3d80-d7f8-11e9-8160-4792f7ae9505.png)

Added this just near the project ID to make life a bit easier.

Committed to master branch, will be released in next version.
https://github.com/appwrite/appwrite/commit/20234f6a7c5894cb3ff9447d9210fdebd0eb3840
