### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by rben820** [appwrite/appwrite#1000]
Hey everyone!
I have a few questions about Appwrite that I would be more than happy to ask here:
1. Could I install it on my Raspberry Pi 4? 
2. Is the real-time database available on Android? 
3. I have an app that works with Firebase real-time database, is there a way to transfer the json file from Firebase into AppWrite?

Thank you!

**Comment by kodumbeats** [comment]
Hi @rben820 👋🏻 

1. We're still working on full compatibility with ARM64 - you can follow https://github.com/appwrite/appwrite/issues/465 for updates on that.
2. We're working towards releasing realtime support for Appwrite by `v0.8.0`, which also has an issue for tracking: https://github.com/appwrite/appwrite/issues/265 (also has links for Android-compatible SDKs as well).
3. A migration tool isn't on our short-term roadmap, but that sounds pretty cool - we'll keep it in mind as we continue building! 🚀 

If you don't have any other questions, feel free to close this issue at your leisure. :)

**Comment by eldadfux** [comment]
@rben820 ARM support is now available on Appwrite 0.8. Realtime is in alpha version, available here: https://discord.com/channels/564160730845151244/850401316185309244/850404571007811615
