### ISSUE TITLE
Permissios Bug 0.7.1

### ISSUE THREAD

**Issue by thesmartrenovation** [appwrite/appwrite#1005]
One question, in version 0.7.0 I could create a document with specific permissions and when I updated that document it was not necessary to send the permissions again. 

Something like this:

```
.updateDocument(
collectionId: usersCollection,
documentId: documentID,
data: {
      'carrito': [carritoToJson(carritos)]
         },
read: [],
write: []
);
```
But now in version 0.7.1 I always get an error 401

I was checking and it seems that it is necessary to always send the permissions of each document.

Is this a bug or will it always work this way from now on?

I think that unless an update of the permissions is sent, they should not be modified from their initial values. Am I correct?

**Comment by eldadfux** [comment]
@elreyes this was actually a bug we fixed, please pass the read and write permissions. You can learn more here: https://github.com/appwrite/appwrite/issues/977
