### ISSUE TITLE
[Docker-Compose] not totally working

### ISSUE THREAD

**Issue by DevDorrejo** [appwrite/appwrite#1011]
## 🐛 Bug Report

1- Trying to use the last version 0.7.1 on a clean install sometime is giving error 404 page not found
2- **appwrite-clamav** can't update the database neither have http connection
3- **appwrite-traefik**` time="2021-03-22T17:28:10Z" level=error msg="service \"appwrite-appwrite\" error: unable to find the IP address for the container \"/appwrite\": the server is ignored" providerName=docker container=appwrite-appwrite-5429ff80a58716bce1490b713b94fce2332129f7a9372c9ed8b0c8d295612617`
5- **appwrite-certificates** the browser are showing that is not a secure SSL. (User certbot for generate ssl certs)
6- Allow the user set the volume locations.

## Have you spent some time to check if this issue has been raised before?

Yes

## To Reproduce

Use this config `https://gist.github.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5`
now i have an apache web server so i change the next port:
```
      - --entrypoints.web.address=:82
      - --entrypoints.websecure.address=:445
```
```
   ports:
      - 82:80
      - 445:443
```
## Expected behavior

Run and work

## Actual Behavior

1- The page sometime is not found.
2- Not generate valid ssl cert.
3- clamav cant connect to update database.
4- appwrite-traefik fail to connect to IP
![image](https://user-images.githubusercontent.com/7697566/112034445-de4b0f80-8b14-11eb-99cc-4708ccc88ce9.png)
![image](https://user-images.githubusercontent.com/7697566/112034482-e86d0e00-8b14-11eb-9f25-3fb81d3680e7.png)
![image](https://user-images.githubusercontent.com/7697566/112034588-05a1dc80-8b15-11eb-8006-139605e3b7c8.png)
![image](https://user-images.githubusercontent.com/7697566/112034674-1ce0ca00-8b15-11eb-9d98-5e2972289238.png)

(Write what happened. Add screenshots, if applicable.)

## Your Environment

Opensuse TW last snapshot
docker-compose last version
docker last version
apache last version

(Write Environment, Operating system and version etc.)

**Comment by eldadfux** [comment]
@DevDorrejo the 404 error is probably because you changed `--entrypoints.web.address` and `--entrypoints.websecure.address`. You can leave does with the default ports, changing the Traefik ports should be enough.

We have just submitted a fix for the SSL error introduced in Appwrite 0.7.1, we'll release 0.7.2 with a fix soon. #1001 

ClamAV has network issues that the Clam team is aware of, for now you can disable it, using the tutorial: https://dev.to/appwrite/learn-how-to-disable-clamav-in-your-appwrite-stack-and-reduce-memory-usage-2e37#:~:text=Disable%20ClamAV%20in%20appwrite%20container&text=To%20disable%20it%2C%20in%20your,checking%20during%20new%20file%20uploads.

**Comment by DevDorrejo** [comment]
changed the entrypoints to the default one, but have issue with **404 page not found**
![404 Page Not Found](https://user-images.githubusercontent.com/7697566/112062771-c3899280-8b36-11eb-88bf-66f12caf576f.png)

some logs:
![image](https://user-images.githubusercontent.com/7697566/112062537-760d2580-8b36-11eb-9bbc-8762de93826c.png)

Redis password error:
![image](https://user-images.githubusercontent.com/7697566/112062896-f6338b00-8b36-11eb-9212-d2ed79442b95.png)

Trafeik-logs:
![image](https://user-images.githubusercontent.com/7697566/112062951-0ea3a580-8b37-11eb-8202-8be62498cf41.png)

**Comment by eldadfux** [comment]
Did you recreated the containers after the change?

**Comment by DevDorrejo** [comment]
> Did you recreated the containers after the change?

yes, delete volume and all containers.

```
docker-compose down

docker rmi appwrite/telegraf:1.0.0 appwrite/env-deno-1.2:1.0.0 appwrite/env-deno-1.5:1.0.0 appwrite/env-node-14.5:1.0.0 appwrite/env-php-7.4:1.0.0 appwrite/env-php-8.0:1.0.0 appwrite/env-python-3.8:1.0.0 appwrite/env-ruby-2.7:1.0.2 appwrite/mariadb:1.2.0 traefik:2.3 redis:6.0-alpine3.12 appwrite/env-deno-1.6:1.0.0 appwrite/env-node-15.5:1.0.0 appwrite/env-ruby-3.0:1.0.0 appwrite/env-dart-2.10:1.0.0 appwrite/env-dotnet-3.1:1.0.0 appwrite/env-dotnet-5.0:1.0.0 influxdb:1.8-alpine appwrite/appwrite:0.7.1 

docker network rm appwrite_appwrite appwrite_gateway
```

**Comment by DevDorrejo** [comment]
> Did you recreated the containers after the change?

i will create a video showing how i do the setup

**Comment by Errichamonda** [comment]
The certificates are not correctly issued when not binding port 443

**Comment by eldadfux** [comment]
> The certificates are not correctly issued when not binding port 443

According to this: https://serverfault.com/a/805681 , seems like its not possible with letsencrypt or at least not with the http challenge.

**Comment by DevDorrejo** [comment]
Well, using docker run, better than using the compose directly with the last version everything is working, only left is the cert wont work if you bind ports to the not default (80,443), one solution is link host volume cert directory to the appwrite one, but dont know to which container and folder link /etc/letsencrypt
