### ISSUE TITLE
Cannot install without access to Google Analytics

### ISSUE THREAD

**Issue by TheBird956** [appwrite/appwrite#1018]
## 🐛 Bug Report

While installing, I got the following error: `Error:Failed to connect to www.google-analytics.com port 443: Connection refused`

I am running a PiHole DNS server on my network that is blocking all tracking and ads.

## Have you spent some time to check if this issue has been raised before?

Yes

## To Reproduce

1. Have PiHole (or any other dns-level ad blocker) up and running
2. Try to install AppWrite using the "Get Started" script
3. Fill all required info during installation
4. During `Running "docker-compose -f /usr/src/code/appwrite/docker-compose.yml up -d --remove-orphans --renew-anon-volumes"` the install will fail with the error `Error:Failed to connect to www.google-analytics.com port 443: Connection refused`

## Expected behavior

The software install and starts without problem

## Actual Behavior

The error shown below appears, blocking the installation.

`Error:Failed to connect to www.google-analytics.com port 443: Connection refused`

## Your Environment

OS: Ubuntu 20.10
Docker version: 20.10.5, build 55c4c88
AppWrite docker image: appwrite/appwrite:0.7.1

**Comment by eldadfux** [comment]
@TorstenDittmann I think we should make sure we have a timeout on this request and skip it if it fails for some reason.

**Comment by TorstenDittmann** [comment]
@eldadfux Will add this to utopia/analytics :+1:

**Comment by TorstenDittmann** [comment]
https://github.com/utopia-php/analytics/pull/1

Pending PR, this will not throw error when failing to send actions to Google Analytics 👍🏻

**Comment by eldadfux** [comment]
@TorstenDittmann released a new tag:
https://github.com/utopia-php/analytics/releases/tag/0.2.0

**Comment by TorstenDittmann** [comment]
Will add it to the dev branch tomorrow and will very likely be part of 0.7.2 that will be released soon 👍🏻 

@TheBird956 Sorry for the inconvenience and thank you for your patience.

**Comment by eldadfux** [comment]
This bug was fixed with the release of 0.7.2. We will consider to replace stats provider soon as suggested on some Reddit talks.
