### ISSUE TITLE
[bug] Wrong path /auth/oauth in docs

### ISSUE THREAD

**Issue by BogDAAAMN** [appwrite/appwrite#102]
**Description**
According to the [docs here](https://appwrite.io/docs/auth#oauth) the request for OAuth providers is `/auth/oauth/{provider}`. Even if the the provider is setup correctly, it returns `Error 412: Provider is undefined, configure provider app ID and app secret key to continue`.

Turns out that the route that works as expected is `/auth/oauth/{provider}?project={project_id}&success={link}&failure={link}`. If that is the intended behaviour, then the docs need to be changed and the wrong path should return an error stating the missing parameters, rather than **Error 412** which is confusing for this case.

**Reproduce**
- Setup a provider at `Users/Providers`
- Try to login at the given path `/auth/oauth/{provider}`

**Desktop**
- OS: MacOS Mojave 10.14
- Browser: Firefox 7.0.2 (64-bit) / Chrome 74.0.3729.157
- Appwrite: v0.2.0

I can fix the docs shortly, but I need to know what is the intended behaviour.

**Comment by eldadfux** [comment]
This is the expected behavior. But the docs should improve and state that a project UID is required for these methods.

We treat both 'project UID' and the 'API key' as authentication methods for all requests and should have a better indication in the docs when each one is required or optional.

**Comment by eldadfux** [comment]
A small update, this will probably be better addressed with some of the changes mentioned in #263

**Comment by eldadfux** [comment]
This seems to be OK in newer versions.
