### ISSUE TITLE
Admin Panel/Dashboard on different domain/route

### ISSUE THREAD

**Issue by lovetodream** [appwrite/appwrite#1022]
## 🚀 Feature Admin Panel/Dashboard on different domain/route

It would be nice if it is possible to move the dashboard to a different domain or at least a different base URL (eg. appwrite.domain.com/console).

## Have you spent some time to check if this issue has been raised before?

Yes, #1003 has some similarities but it's about a different topic.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

Having the dashboard directly on the root looks like a bad decision for me.
 - Users might land on the route and think they need to login here, even if they aren't supposed to.
 - If there might be a security risk, it would be quite easy to get to the dashboard.
 - It would be nice if users don't see what's "behind" the app.
 
What I would do is to add a .env variable to set a base URL for the panel.
Or maybe deploy it to a completely different domain and link the Appwrite instance or maybe even multiple instances if possible.
Another approach would be to exclude it from custom domains.

**Comment by eldadfux** [comment]
I think the easiest solution for now can be blocking access to the dashboard from a custom domain.

**Comment by lovetodream** [comment]
This would work for me.

**Comment by EVDOG4LIFE** [comment]
This should now achievable for self-hosted users by setting the `_APP_CONSOLE_WHITELIST_IPS` env variable! 
More info in https://appwrite.io/docs/advanced/self-hosting/production
