### ISSUE TITLE
ship minimal Password reset and Email verification page

### ISSUE THREAD

**Issue by fightforlife** [appwrite/appwrite#1030]
## 🚀 Feature

I think it would really help if appwrite would ship with a minimal/standard email verification and password reset form for each project.
Currently a new user cannot not simply use appwrite, to manage these tasks. He has to spinup a seperate webserver and provide forms which just post the correct json data to the api. (Especially if Appwrite is used for App development without Web involvment)
Since appwrite already has the needed forms and templates I think one could reuse these for the individual projects.

## Have you spent some time to check if this issue has been raised before?

I did only find the following issue which goes in a different direction.
https://github.com/appwrite/appwrite/issues/730

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

This would give new user the opportunity to just start using appwrite without developing a spereate webinterface.
One could even reuse the project logo und name on these templates.

Best regards!

**Comment by TorstenDittmann** [comment]
I think I talked to @eldadfux in the past about this.

The idea might be good, but I don't really think it fits really well into the Appwrite container. Especially in terms of customization.

In my opinion the better approach would be a pre built template for this that can be deployed with one click to Providers like Vercel and Netlify.

This way you have way more control over your pages and can modify it to the fullest 👍🏻

**Comment by eldadfux** [comment]
Have you tried https://www.authui.site/ ? we might consider adding it as a template on the console.
