### ISSUE TITLE
I need a app that I can track geo location via phone number

### ISSUE THREAD

**Issue by BrrShh223** [appwrite/appwrite#1036]
## 🚀 Feature

(A clear and concise description of what the feature is.)

## Have you spent some time to check if this issue has been raised before?

(Have you googled for a similar issue or checked our older issues for a similar bug)

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

(Write your answer here.)

## Pitch

(Please explain why this feature should be implemented and how it would be used. Add examples, if applicable.)

**Comment by BrrShh223** [comment]
This app will be helpful in the sense of monitoring my employees location during work hours being as though I'm managing the business remotely I want to make sure all employees are at the correct location at the appropriate time

**Comment by kodumbeats** [comment]
Hi @BrrShh223,

Our [Locale API](https://appwrite.io/docs/client/locale) provides methods to obtain location-specific data about your users, but as a Backend-as-a-Service product, we don't have any pre-built apps or support for a feature like this.

There are several services that offer phone-based geolocation that will suit your use-case better. I found https://geoloc.mobi/, so I hope you can find a solution that works for you.

I'll close out this issue for now - best of luck!
