### ISSUE TITLE
Connecting Flutter web with Appwrite

### ISSUE THREAD

**Issue by nalashour** [appwrite/appwrite#1039]
I always get this error DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.

can anybody please give me the proper way to connect flutter web with appwrite

from emulator for testing & IIS server for production.

Thanx

---
Appwrite Version: 0.7.2.145

**Comment by AlimFreight** [comment]
> I always get this error DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.
> 
> can anybody please give me the proper way to connect flutter web with appwrite
> 
> from emulator for testing & IIS server for production.
> 
> Thanx
> 
> Appwrite Version: 0.7.2.145

Look here https://github.com/appwrite/sdk-for-flutter/issues/5

**Comment by eldadfux** [comment]
Closing for now. @nalashour please reopen if @AlimFreight reference issue still not helping you.

**Comment by chrislaurie-bs** [comment]
I am getting this same issue on flutter for web. When I use the server admin mode (with api key), using dart_appwrite, I can do most things. But when I try to do a users.list, with an email in the search parameter I get this error. If I search on anything that is not an email I do not get the error. Is there a special way to search by email?
