### ISSUE TITLE
run on ARM

### ISSUE THREAD

**Issue by atabaksahraei** [appwrite/appwrite#1043]
I tried to run the container on a arm pc (raspberrypi).
I get the following error:
standard_init_linux.go:211: exec user process caused "exec format error"
![image](https://user-images.githubusercontent.com/2444540/112803168-4ba9f380-9073-11eb-94ef-34411d36ca64.png)

**Comment by TorstenDittmann** [comment]
We currently don't support ARM right now, but we are working on it over here https://github.com/appwrite/appwrite/pull/726

It is almost done and we are in testing & QA stage right now 👍🏻

**Comment by eldadfux** [comment]
@atabaksahraei You can also check this discussion to learn how to run the dev branch on raspberry pi: https://github.com/appwrite/appwrite/discussions/1041

**Comment by rajdas98** [comment]
Hello Everyone! I have added ARM(multi-arch) support for many OS projects. I am interested to work on this issue. Feel free to assign me.

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/appwrite/releases/tag/0.8.0 👏🏻
