### ISSUE TITLE
Collection Rules Issue - 0.7.2

### ISSUE THREAD

**Issue by thesmartrenovation** [appwrite/appwrite#1047]
Hi, how can I update a collection without updating the rules? 

I am doing it this way but when updating the collection the rules disappear completely.

```
await database.updateCollection(
        collection.id,
        collection.name,
        readPerms,
        writePerms,
        []
      );
```

or 

```
await database.updateCollection(
        collection.id,
        collection.name,
        readPerms,
        writePerms,
      );
```
Is there any way to avoid having to send the rules again at each update?

**Comment by eldadfux** [comment]
When we use the PUT method in Appwrite  we do a full update, unlike PATCH where we update only part of the data. With the current implementation you'll have to keep the collection state by passing your rules on the update operation.

As part of this RFC: https://github.com/appwrite/rfc/blob/910e7e015c7516c643272f3981ee349dc36c5d11/016-database-adapters.md we are planing to split child entities like rules (attributes) & indexes to have their own separate POST GET DELETE methods (https://github.com/appwrite/rfc/blob/910e7e015c7516c643272f3981ee349dc36c5d11/016-database-adapters.md#database-api).
