### ISSUE TITLE
Missing some Norwegian Translations 🇳🇴

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#105]
The Norwegian translation was the first one to be added, and we forgot to mention we needed to translate the 'app/config/locale/en.php' file. This is the only file missing before we can add the 'no' locale in the next version.

**Comment by Niladri24dutta** [comment]
@eldadfux Can I work on this? I assume only the no.php file needs to be added with the translations . other than that the continents and countries file already exists for `no`

**Comment by eldadfux** [comment]
@Niladri24dutta yes only no.php is missing. Thanks for helping! 🙏

**Comment by Niladri24dutta** [comment]
@eldadfux I have created a PR #125 for this. Can you please review?
