### ISSUE TITLE
Set default locale on .env

### ISSUE THREAD

**Issue by simultsop** [appwrite/appwrite#1052]
## 🚀 Feature

To be able to set default locale for Appwrite itself.

## Have you spent some time to check if this issue has been raised before?

Asked maintainers on discord.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

👀

## Pitch

Was trying to launch Appwrite for some local fellas to bring more devs using appwrite initially on rapid prototyping.

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/appwrite/releases/tag/0.8.0 👏🏻
