### ISSUE TITLE
Update user status through cli

### ISSUE THREAD

**Issue by cardosojc** [appwrite/appwrite#1053]
## 🐛 Bug Report

I'm trying to use the cli to update the status of a user. When i do `appwrite users updateStatus --userId="60634021b9e9a" --status="1"`  the response is
```
sh: --userId=60634021b9e9a: unknown operand
message : Invalid status: Value must be one of (1, 2, 0)
code : 400
version : 0.7.2
```

## Your Environment
Os: Ubuntu 20.04 (64bit)
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by eldadfux** [comment]
Hey @cardosojc, thanks for reporting this, this bug is originated in wrong type casting on the CLI side, @christyjacob4 is already working on a fix with me. We'll keep this issue up-to-date with our progress.

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/appwrite/releases/tag/0.8.0 👏🏻
