### ISSUE TITLE
Auto-validate user registration in local mode

### ISSUE THREAD

**Issue by cardosojc** [appwrite/appwrite#1054]
## 🚀 Feature

Auto-validate user registration in local mode

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

When running appwrite locally and we register a user, it would be useful that our user gets automatically validated (for development purposes) so that we can use them in our applications (authentication). Otherwise we would have to setup a local smtp server or run the cli to do a manual step.

**Comment by cardosojc** [comment]
Fully agree with that flag option. Actually i was thinking the same but wasn't explicit

**Comment by eldadfux** [comment]
We are going add an option to change verification status from the console and users API, this should help simulate user verification on dev mode.

**Comment by Emeka212** [comment]
> ## 🚀 Feature
> Auto-validate user registration in local mode
> 
> ## Have you spent some time to check if this issue has been raised before?
> Yes
> 
> ### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?
> Yes
> 
> ## Pitch
> When running appwrite locally and we register a user, it would be useful that our user gets automatically validated (for development purposes) so that we can use them in our applications (authentication). Otherwise we would have to setup a local smtp server or run the cli to do a manual step.

Lolz, i really don't think that will be a nice idea, but since it is your opinion, then who am i to say other wise

**Comment by stnguyen90** [comment]
Closing as it is not possible to toggle the verification status of users in the Appwrite Console.
