### ISSUE TITLE
Document Timestamps

### ISSUE THREAD

**Issue by Errichamonda** [appwrite/appwrite#1057]
## 🚀 Feature

Add timestamps for "created_at", "updated_at" for documents, as Eloquent does by [default](https://laravel.com/docs/4.2/eloquent#timestamps).

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

In Database Collections settings, add a toggle for enabling or disabling timestamps.

**Comment by eldadfux** [comment]
We have this being done internally today an we weren't sure if this is something we should continue doing. Would adding a {{time}} variable to the DB something that would help? DB vars like {{time}}, {{ip}}, and {{userId}} is an idea we have been playing around with.

Would love to get your feedback.

**Comment by Errichamonda** [comment]
Yes, it would be great to have some DB variables to use as default value for the database, like using userId for setting who created that record, etc.

**Comment by eldadfux** [comment]
Thanks for the feedback @Errichamonda closing this issue so the main discussion around this would be on the relevant DB RFC:
https://github.com/appwrite/rfc/pull/21
