### ISSUE TITLE
Nested document permission are not validated

### ISSUE THREAD

**Issue by Errichamonda** [appwrite/appwrite#1058]
## 🐛 Bug Report

As discussed on Discord, it seems that only the parent permissions are validated on nested document field.
For context I have this JSON schema
```
{
    "$id": "606585fd45188",
    "$collection": "606585b4c4663",
    "$permissions": {
        "read": [
            "*"
        ],
        "write": [
            "*"
        ]
    },
    "name": "Candidatura Spontanea",
    "requests": [
        {
            "$id": "606585fd46589",
            "$collection": "6065767bac97c",
            "$permissions": {
                "read": [
                    "606573845dd56"
                ],
                "write": [
                    "606573845dd56"
                ]
            },
            "name": "Name",
            "surname": "Surname",
            "email": "name@email.com",
            "city": "City123",
            "fields": "",
            "read": false,
            "created_at": 1617265365,
            "updated_at": 1617265365,
            "deleted_at": 0
        }
    ]
}
```
The field `requests` have read permission for only one team, while the parent field have `*` read permission. When I try to read the document from other team I can still see the `request` field, even if the permission on the collection or document are setted differently.

## Have you spent some time to check if this issue has been raised before?

Yes

## To Reproduce

Create two collections. Set one collection to be read only from one team, other collection as `*`. Than create in the `*` collection a nested list of documents referencing the restricted collection. Set permission to the team to the document and than read the `*` collection from other team / guest.

## Expected behavior

When I read the collection from other team / guest the `requests` field must not be shown.

## Actual Behavior

`requests` field is shown to everyone.

```
{
    "sum": 1,
    "documents": [
        {
            "$id": "606585fd45188",
            "$collection": "606585b4c4663",
            "$permissions": {
                "read": [
                    "*"
                ],
                "write": [
                    "*"
                ]
            },
            "name": "Candidatura Spontanea",
            "requests": [
                {
                    "$id": "606585fd46589",
                    "$collection": "6065767bac97c",
                    "$permissions": {
                        "read": [
                            "606573845dd56"
                        ],
                        "write": [
                            "606573845dd56"
                        ]
                    },
                    "name": "Name",
                    "surname": "Surname",
                    "email": "name@email.com",
                    "city": "City123",
                    "fields": "",
                    "read": false,
                    "created_at": 1617265365,
                    "updated_at": 1617265365,
                    "deleted_at": 0
                }
            ]
        }
    ]
}
```

## Your Environment

Docker on Ubuntu 20.04 LTS
Appwrite 0.8.x (not sure if the bug is present on 0.7.2)
Tests done using Postman

**Comment by eldadfux** [comment]
This is the expected behavior today. We can't validate nested fields without impacting performance badly. The parent doc is the one we follow, and in this case you would probably prefer to structure the docs in a flat design.
