### ISSUE TITLE
[Feature] Meta data fields for creating a user

### ISSUE THREAD

**Issue by eladcandroid** [appwrite/appwrite#106]
A user can only include email, password and name.. Additional information should also be allowed.

**Comment by eldadfux** [comment]
Hey @eladcandroid, I think this is the feature you are looking for:
https://appwrite.io/docs/account#updatePrefs

The /account/prefs route lets you save a key/value object with any user preferences you like. You can call it right after the registration route result with a 200 response code.

I have already used successfully for storing user specific data like timezone, language and basically anything you want. 

Another option might be to create a DB document with a read & write permissions only for the specific user, but I find the first option I mentioned easier to use for this scenario.

**Comment by eladcandroid** [comment]
Thanks for /account/prefs, but I prefer to save information without the user having to login

**Comment by eldadfux** [comment]
If you're looking to add this information without the user taking action, you can always register to a relevant webhook or background task and use server side SDK to add the metadata to the user account.

We can add the pref method the users API like the 'status' method and allow you to this on server:
https://appwrite.io/docs/users#updateUserStatus

**Comment by eladcandroid** [comment]
> We can add the pref method the users API like the 'status' method and allow you to this on server:
https://appwrite.io/docs/users#updateUserStatus

@eldadfux This would be great and helpful. Thanks!

**Comment by eldadfux** [comment]
Amazing! I am prioritizing it for next version 0.3.0!

**Comment by eldadfux** [comment]
@christyjacob4

**Comment by christyjacob4** [comment]
> @christyjacob4

Yes @eldadfux  Let's work on it!

**Comment by eldadfux** [comment]
Feature ready. will be release in 0.3.0. Thank you @eladcandroid and @christyjacob4
