### ISSUE TITLE
UX Bug - Creating new collections in the console

### ISSUE THREAD

**Issue by trydalch** [appwrite/appwrite#1061]
## 🐛 Bug Report

It's not obvious how to create a new collection in the Appwrite console. I searched all around only to find the small plus button at the bottom right. 

## To Reproduce

1. Log in, go to databases, find the plus buton.

## Expected behavior

I would expect a button somewhere in this frame, especially because I'm using 4k monitors and the button was clear down in the corner, out of sight.

![image](https://user-images.githubusercontent.com/17228930/113375077-e46a9880-932b-11eb-9180-317a6567e288.png)

## Actual Behavior

Button was outside of natural search space.

**Comment by eldadfux** [comment]
Agree, we can change the UI to drop all the round "+" buttons and move to a more consistent look.

**Comment by eldadfux** [comment]
Example of the collections UI with similar bottom controls to the Cloud Functions UI:

![image](https://user-images.githubusercontent.com/1297371/113470255-e122fa00-945c-11eb-93fb-ada5fc5b2113.png)

**Comment by eldadfux** [comment]
Users UI:

![image](https://user-images.githubusercontent.com/1297371/113470442-62c75780-945e-11eb-987c-70a4eec35516.png)

Teams UI:

![image](https://user-images.githubusercontent.com/1297371/113470465-8ee2d880-945e-11eb-98c2-e9b7e953ff00.png)

**Comment by eldadfux** [comment]
Added a PR. If all goes well, this should be released on 0.8.0

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/appwrite/releases/tag/0.8.0 👏🏻
