### ISSUE TITLE
Error on array from child document in console

### ISSUE THREAD

**Issue by damascenaluiz** [appwrite/appwrite#1063]
## 🐛 Bug Report

When I have a collection associated with a rule and this collection has an array, it is not possible to add values to the array directly from the parent collection, via the UI. The Add button when clicking does not display the option to add the name or when clicking nothing happens. 

## Have you spent some time to check if this issue has been raised before?

Yes, the discord was asked to open a ticket as this appears to be an error only in UI.

## To Reproduce

Example:

1 - Create a child Collection:
**Question** (Document)
property: **options** (Text) as array

2 - Create the parent collection
**Form** (Document)
property: **question** (Document) as array

It is not possible to add the array of options directly from a Form document. 

## Expected behavior

Being able to manipulate array properties of child documents directly from a parent document. 

## Actual Behavior

The Add button in an array does not allow me to enter values.
![error](https://user-images.githubusercontent.com/677552/113495075-24b14e80-94c5-11eb-8055-1ea16bfd1868.png)

## Your Environment

Appwrite 0.7.2
Firefox 87.0

**Comment by TorstenDittmann** [comment]
Hey @damascenaluiz 👋🏻 

Thanks for reporting that bug, this is indeed not working in the dashboard.

**Comment by TorstenDittmann** [comment]
Working on this right now 👍🏻

**Comment by eldadfux** [comment]
This issue was fixed and its now available as part of Appwrite 0.12. You can learn more about the new version here: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
