### ISSUE TITLE
Web console: not possible to create multiple parameters of rule type document / collection selection broken

### ISSUE THREAD

**Issue by fightforlife** [appwrite/appwrite#1065]
## 🐛 Bug Report

Hi there, I think I found a bug with the creation of collection rules in the web console:
If you create two parameters of type document and want to link them to different collections, this is not possible because the web interface only allows to choose one collection on the page (for all parameters). Normally it should allow to select one collection per parameter. 

## Have you spent some time to check if this issue has been raised before?

I asked in Discord. Problem was not known.

## To Reproduce

1. create a new collection in the web console
2. create two parameters with rule type "document"
3. try to link the two parameters to two different collections without choosing type array.
4. Try to save the settings.  (the choose"dot" will jump between parameters, it is not possible to choose collections per parameter)

## Expected behavior

It should be possible to choose a collection per parameter of type document

## Actual Behavior

It is not possible to create multiple parameters of rule type document and link them to different collection.
(it is possible if you declare them as arrays).

![2021-04-04 12_17_47-Window](https://user-images.githubusercontent.com/5511687/113505867-b068c080-9541-11eb-8062-9d464f6649a2.jpg)

## Your Environment

v:0.7.2.145 in docker on Ubuntu 20.10

**Comment by TorstenDittmann** [comment]
Hey @fightforlife 👋🏻 

Thanks for reporting that bug, this is a result of the UI being a single form and the checkboxes for the allowed collection having the same underlying values.

**Comment by TorstenDittmann** [comment]
Pending PR fixing this #1069 ✅

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/appwrite/releases/tag/0.8.0 👏🏻
