### ISSUE TITLE
The possibility to edit user preferences from console

### ISSUE THREAD

**Issue by Asored-D** [appwrite/appwrite#1067]
## 🚀 Feature

Do you plan the functionality to be able to edit user preferences from backend? Or to integrate this functionality to the Appwrite CLI? In our case we are using preferences to save specific user data. If an user asks us to change specific content, we have no possibility to do this from backend.

What do you think?

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

You could integrate an edit button on this section. Click on edit button opens a modal dialog with all user preferences and the values as input fields. (See attachment below)

![prefs example](https://user-images.githubusercontent.com/6883050/113615221-e007ed80-9653-11eb-88f9-afc0c461ad64.jpg)

**Comment by TorstenDittmann** [comment]
Hey @drosa88 👋🏻 

Thanks for the idea. 

I think we both agree that this is a reasonable feature request 👍🏻

**Comment by drosa88** [comment]
Thanks @TorstenDittmann for your feedback!
Greetings from Saarbrücken :-)

**Comment by gepd** [comment]
I would likt to see this feature as well

**Comment by niels-hubs** [comment]
One year later....

**Comment by stnguyen90** [comment]
We'll be sure to include this in the redesign of the Appwrite Console that is currently in progress. 🙏

**Comment by ddenev** [comment]
I think this can be closed now as this is now available in the new Console.
