### ISSUE TITLE
[CSS bug] - Docs URL box - change CSS to overflow: auto

### ISSUE THREAD

**Issue by eladcandroid** [appwrite/appwrite#107]
<img width="822" alt="Screen Shot 2019-10-03 at 11 59 40" src="https://user-images.githubusercontent.com/13297000/66113479-8396be80-e5d5-11e9-9b5d-640702f0229c.png">

".home .docs .url" selector

Tested on Chrome 77.0.3865.90, MacOS Mojave v10.14.5

**Comment by eldadfux** [comment]
Thanks for reporting the issue @eladcandroid, What OS are you running?

**Comment by eladcandroid** [comment]
@eldadfux I wrote it - MacOS Mojave v10.14.5. Thanks!

**Comment by eldadfux** [comment]
sorry my bad!

**Comment by utkarsh-raj** [comment]
Hi, I have tested and figured out a possible fix. Could you please guide me as to where can one find the Files for the Website ?

**Comment by christyjacob4** [comment]
Hey @utkarsh-raj Thanks for taking your time on this issue however,  I honestly think we're not yet ready for UI changes since we have much more pressing issues before the next release. We'd request you to wait until further instructions from @eldadfux .  
Cheers!

**Comment by utkarsh-raj** [comment]
I understand @christyjacob4 and will surely check other issues in the meanwhile. Thanks !

**Comment by eldadfux** [comment]
@eladcandroid, I wasn't able to see this issue on any of the MacBooks I had available. Anyway, I did make the CSS change and deployed all changes to appwrite.io. Can you please tell me whether you still see the problem?

**Comment by eldadfux** [comment]
Can anyone who had the issue please confirm whether this issue is solved?

**Comment by utkarsh-raj** [comment]
I am afraid the issue still persists on my Chrome 76.0 running on Linux Mint 19.2 MATE. @eldadfux

**Comment by eldadfux** [comment]
@utkarsh-raj can you tell me what is the version number you get on the site footer?

**Comment by utkarsh-raj** [comment]
All right, I just refreshed and the version changed from 0.1.54.ee to 0.1.56.ee and the issue is resolved. Must be a local cached version for me :)
