### ISSUE TITLE
Axios 0.20.0 dependency Server-Side Request Forgery vulnerability on node-appwrite

### ISSUE THREAD

**Issue by TafadzwaD** [appwrite/appwrite#1079]
## 🐛 Bug Report

Node-AppWrite depends on Axios 0.20.0 which has a Server-Side Request Forgery (SSRF) vulnerability according to "npm audit".

## Have you spent some time to check if this issue has been raised before?

This issue has not been raised before

## To Reproduce
npm init
npm install node-appwrite --save 
npm audit

![Screenshot from 2021-04-09 01-03-47](https://user-images.githubusercontent.com/28431370/114161284-2e550f00-9928-11eb-8038-66461e974f47.png)

## Suggested Fix

Use Axios >= 0.21.1

## My Environment

(node-appwrite:^2.0.0, Ubunutu 20.04)

**Comment by lovetodream** [comment]
I've had a quick look at the sdk generator template and it uses a newer version (0.21.1) of axios already. I think you guys just need to regenerate the Node-SDK and publish a new version to NPM. 😉

**Comment by eldadfux** [comment]
We have just released v2.1.0 of the Node JS SDK with this fix included.
