### ISSUE TITLE
Allow Setting of Access Control Headers

### ISSUE THREAD

**Issue by RayNCooper** [appwrite/appwrite#1082]
## 🚀 Feature

Hey everyone,

I tried to implement Sentry.io (App Monitoring) for my web frontend app that uses appwrite. When trying to send monitored errors from the app to the Sentry dashboard, my app throws a "Cross-Origin Request Blocked" error. This has to do with the fact that the 'sentry-trace' header is not set, as is also described in the stack trace (see attached screenshot). A reference from the official Sentry docs can be found [here](https://docs.sentry.io/platforms/javascript/guides/vue/troubleshooting/#unexpected-options-request).

## Have you spent some time to check if this issue has been raised before?

I checked if the issue appeared in GitHub issues, it did not. Furthermore, I ducked for a solution and came to the conclusion that official support for the given feature would be more user-friendly than changing something in the Compose file.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

## Pitch
I think this feature is important because it allows developers to have an easier integration with monitoring SDKs such as Sentry and other applications that may utilize CORS headers.
Edit: Of course you could configure Traefik in the Compose file accordingly, but appwrite also handles allowed CORS within its dashboard.

## Screenshot
![image](https://user-images.githubusercontent.com/39743711/114280944-ea532e80-9a3b-11eb-9f9e-9e6dfbb5c2dc.png)

**Comment by eldadfux** [comment]
@RayNCooper thanks for opening this issue. I don't see any reason for Appwrite to accept the `sentry-trace` header, this header according to Sentry docs is used to identify the same transaction on both client and server monitoring, but Appwrite don't have any built-in Sentry reporting on the server side. Taking both into consideration I don't see any major value that would be achieved from that feature in that use-case.

From the [Sentry docs](https://docs.sentry.io/platforms/javascript/performance/included-instrumentation/#tracingorigins) it seems you can easily adapt the Sentry SDK to not attach this header to the Appwrite API and avoid the CORS errors.

I would love to rethink this for other use cases, but I am having a hard time to think of use-cases where this feature would be a must or at least very valuable.

**Comment by RayNCooper** [comment]
Hey @eldadfux, thanks for the quick response. I was talking about adding headers to CORS in general, since this would enable Sentry to characterize and push my app's XHR request performance to a dashboard.

Apart from an official implementation, what would your suggestion be regarding manually adding to CORS headers?

**Comment by eldadfux** [comment]
You might be able to user Traefki to add custom header, take a look here: https://doc.traefik.io/traefik/middlewares/headers/

**Comment by RayNCooper** [comment]
> You might be able to user Traefik to add custom header, take a look here: https://doc.traefik.io/traefik/middlewares/headers/

Thanks! I would consider this issue resolved then.

**Comment by benkaiser** [comment]
@eldadfux I seem to be running into a wall with this one. Even if I try and override the docker-compose labels (for both traefik and appwrite), I still get a bad access-control-allow-origin of `localhost`.

It seems to track back to this these lines:
https://github.com/appwrite/appwrite/blob/e9a37e9a53bfdb641159819f8f5a2e496017859b/app/controllers/general.php#L99-L104

When I see an `OPTIONS` request go through, it gives me the right header
```
access-control-allow-origin: https://930cb4ef.musicshare.pages.dev
```
but when it makes the real request, I get back localhost:
```
access-control-allow-origin: https://localhost
```

Can we have an explit CORs allowed origins added to the admin interface?

**Comment by benkaiser** [comment]
Ended up adding all of these under the `appwrite` labels in the docker-compose:

```
      - traefik.http.routers.appwrite.middlewares=testheader
      - traefik.http.routers.appwrite-secure.middlewares=testheader
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://my.domain"
      - "traefik.http.middlewares.testheader.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.testheader.headers.accessControlAllowHeaders=content-type,x-appwrite-project,x-appwrite-response-format,x-fallback-cookies,x-sdk-version"
```

**Comment by tundeajibawo** [comment]
adding this to appwrite label solves it for me: `- traefik.http.middlewares.testheader.headers.customresponseheaders.access-control-allow-origin=https://domain`

**Comment by thevinitgupta** [comment]
What domain are you representing by `https://domain` ? 
The client domain or the server domain where Appwrite is hosted?

**Comment by zwarag** [comment]
I had a similar problem and I actually was because I `setEndpoint` to `http://domain.com` but should have used `https://domain.com`.
