### ISSUE TITLE
oAuth2 Authentication does not work for Android (Missing Redirect URL)

### ISSUE THREAD

**Issue by Asored-D** [appwrite/appwrite#1083]
## 🐛 Bug Report

I'm using Appwrite's oAuth2 authentication system for my Flutter app. In general for Apple devices everything works like a charm. But I found some problems for Android devices. While for apple devices I can authenticate, all my Android devices shows me "Missing redirect URL". I think the problem is the external browser which opens. Apple opens an In App Browser, but Android an external one. 

## Have you spent some time to check if this issue has been raised before?

Yes – I can find nothing about this problem.

## To Reproduce

- Create Flutter App
- Setup Appwrite oAuth2 authentication, for example with provider Google
- Test it on an Android device

## Expected behavior

With Apple devices authentication works very good. So I would expect the same behavior for Android devices.

## Actual Behavior

See above.

Is this a known issue? Or it is my fault maybe?

**Comment by eldadfux** [comment]
Hey @Asored-D,

Have you added this part to your Android manifest file?

![image](https://user-images.githubusercontent.com/1297371/114284443-ab7fa180-9a58-11eb-870b-37033f7a703e.png)

You can also use the Flutter Playground to try and debug if this is an issue with Appwrite or your implementation: https://github.com/appwrite/playground-for-flutter

**Comment by Asored-D** [comment]
Wow. This was a crazy fast answer! 😁 Mans thanks @eldadfux ... I've checked it. And.... yes and no! I've added this part to my AndroidManifest, but...last week I've changed my server environment and I got a new Appwrite project ID...so the ID on appwrite-callback-{id} was wrong! I will change this and try again.

Many thanks!

**Comment by Asored-D** [comment]
Confirmation: It works. Thank you for this good advice. 👍
