### ISSUE TITLE
Filter documents by boolean

### ISSUE THREAD

**Issue by thesmartrenovation** [appwrite/appwrite#1096]
Guys, is there any way to filter documents by a boolean attribute?

I have a document with a boolean attribute to know if the user is active or not. 

I only need to load the documents that have the rule closed in false.

I'm trying this mode

let response = await database.listDocuments(
      collectionID,
      ['closed=false']
    ); 

but it doesn't work properly

**Comment by TorstenDittmann** [comment]
Can you try using `'closed=0'`?

**Comment by thesmartrenovation** [comment]
> Can you try using `'closed=0'`?

'closed=0' did not work. But it works with 'closed!=1' XD

**Comment by TorstenDittmann** [comment]
Ah okay!

I think this needs to be better addressed in the docs 🙏🏻

**Comment by TorstenDittmann** [comment]
Fixed with #1097

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/appwrite/releases/tag/0.8.0 👏🏻
