### ISSUE TITLE
Error During Account Creation

### ISSUE THREAD

**Issue by lohanidamodar** [appwrite/appwrite#1104]
## 🐛 Bug Report

During one of my tests, I received weird error during account creation. Following is the error message
```
[PDO] MySQL connection restarted
appwrite                        | [Error] Timestamp: 2021-04-22T01:05:08+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: PDOException
appwrite                        | [Error] Message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9c8485898d5a4ef24d659ecf024b68fb' for key 'index1'
appwrite                        | [Error] File: /usr/src/code/src/Appwrite/Extend/PDOStatement.php
appwrite                        | [Error] Line: 88
```

## Have you spent some time to check if this issue has been raised before?

YES

## To Reproduce

1. Create account with `email1` and password
2. Update email of the account to `email2`
3. Delete the account and 
4. Finally try again to create the account with `email1` and you should receive this error

## Expected behavior

Once I delete the account/ or even just update email to something else (this might be blocked due to email not being verified and changed email not being verified either not sure) I should be able to create new account with previous account.

## Actual Behavior

I was unable to create new account with previous email.

## Your Environment

OS: Linux
Appwrite Branch: 0.8.x

**Comment by eldadfux** [comment]
I think this happens because of a legacy behavior we had trying to protect account hijacking. Since we have a unique ID per new user and no built-in data is being coupled with an email that should no longer be a concern. @TorstenDittmann got any other thoughts on this?

**Comment by TorstenDittmann** [comment]
> I think this happens because of a legacy behavior we had trying to protect account hijacking. Since we have a unique ID per new user and no built-in data is being coupled with an email that should no longer be a concern. @TorstenDittmann got any other thoughts on this?

Iirc we store the unique `$id`, not the email : 🤔

**Comment by eldadfux** [comment]
We use the email as a unique key to avoid duplications, I'm not sure we clean it up: https://github.com/appwrite/appwrite/blob/0.8.x/app/controllers/api/account.php#L124
