### ISSUE TITLE
No access to Social/OAuth access token for making requests (FB Api for example)

### ISSUE THREAD

**Issue by wess** [appwrite/appwrite#1106]
## 🐛 Bug Report

There is no way to get the access token you need in order to make api calls to services you used for authentication.

## Have you spent some time to check if this issue has been raised before?
I have searched google, and through Appwrite issues

## To Reproduce
Use Facebook to authenticate, then use the access token returned from Facebook to make a request on behalf of the user.

## Expected behavior
When ever I call `await account.get()` a key would be added with access to my user's OAuth token.

## Actual Behavior

No where to be found.

## Your Environment

Flutter/macOS
Appwrite 7.2 on Digital Ocean

**Comment by eldadfux** [comment]
Hey @wess , Thanks for reaching out!

Please take a look at this already **merged** pull-request which will be available in our upcoming v0.8 release: https://github.com/appwrite/appwrite/pull/922

We have decoupled the OAuth access-token from the user object and have attached it to the session object and now we also expose it (under the `providerToken` attribute) for the very same reason you have mentioned in this issue.

**Comment by wess** [comment]
Closed for access coming with PR #922 and release 0.8
