### ISSUE TITLE
Failed to install Appwrite dockers

### ISSUE THREAD

**Issue by prooshani** [appwrite/appwrite#1108]
Hi,
Recently I have faced a weird problem installing AppWrite 0.7.2 on CentOS 7.8 (and Ubuntu 20.4) .
I have successfully installed docker ... and test it running and all but, after trying to install the Appwrite it comes to an error like : toomanyrequests: `You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit `
Even if I pull the appwrite docker, during installation I think it fails at building docker after asking http/https port, API secret, host name, and etc.
it comes to this: 
```
Failed to install Appwrite dockers
Pulling mariadb (appwrite/mariadb:1.2.0)...
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
Even if I pull and install mariadb it is still the same! I think this is not about mariadb because I can pull and install it standalone (out of appwrite installation process).

I am stopped at this stage and really need help.

**Comment by eldadfux** [comment]
This is a Docker limit that was introduced a few months ago. If you will login with your Docker Hub user you should get a higher rate-limit which should solve the issue.

**Comment by prooshani** [comment]
mmmm...
I have docker hub user but I did not know that if I should login with my user over my cloud server too...
let me try and inform you.
Thanks.

**Comment by prooshani** [comment]
OK... 
Logged in successfully using this command:
`docker login --username=<dockerhubusername>`

But the same result after trying to install AppWrite:

```
Failed to install Appwrite dockers
Pulling mariadb (appwrite/mariadb:1.2.0)...
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by prooshani** [comment]
Because it looks immediately kill the installation process with mariadb... when I am trying to run : `docker run appwrite/mariadb` to see if there is an error there and I am receiving this:
```
docker run appwrite/mariadb
2021-04-26 21:55:36+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+maria~focal started.
2021-04-26 21:55:37+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-04-26 21:55:37+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+maria~focal started.
2021-04-26 21:55:37+00:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
	You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

I don't know if it helps you identify the problem roots.

**Comment by prooshani** [comment]
Update:
By manually pulling every single docker image before running AppWrite installation the problem resolved.
for who may see this later:
before running AppWrite installation docker code you need to use `**docker pull <docker images>**` to resolve the problem.
like this: 
```
docker pull appwrite/mariadb:1.2.0
docker pull redis:6.0-alpine3.12
docker pull appwrite/clamav:1.2.0
```
and etc...
Then try to run AppWrite installation through docker run ...

Thanks.

**Comment by SeveHo** [comment]
I had the same issue:
```
2021-04-26 21:55:36+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+maria~focal started.
2021-04-26 21:55:37+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-04-26 21:55:37+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+maria~focal started.
2021-04-26 21:55:37+00:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
	You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

But your suggestion didn't help. Instead after setting the `_APP_DB_ROOT_PASS` env Variable in my `.env` file, the compose environment spun up successfully.

@eldadfux I assume this should be fixed in the gist linked from the docs (https://gist.github.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5)

**Comment by prooshani** [comment]
> I had the same issue:
> 
> ```
> 2021-04-26 21:55:36+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+maria~focal started.
> 2021-04-26 21:55:37+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
> 2021-04-26 21:55:37+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+maria~focal started.
> 2021-04-26 21:55:37+00:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
> 	You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
> ```
> 
> But your suggestion didn't help. Instead after setting the `_APP_DB_ROOT_PASS` env Variable in my `.env` file, the compose environment spun up successfully.
> 
> @eldadfux I assume this should be fixed in the gist linked from the docs (https://gist.github.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5)

That was just the first docker image appwrite pulls for installation.
After resolving the mariadb, pulling the other docker images leads to an ERROR.
I just mentioned mariadb while all others faced the same problems.
But, through pulling them manually, finally the installer finished the installation successfully.
