### ISSUE TITLE
Cannot install cli using powershell; produces error

### ISSUE THREAD

**Issue by cambo2015** [appwrite/appwrite#1114]
## 🐛 Bug Report

(A clear and concise description of what the bug is)I cannot install the CLI via powershell. the commend I used was this:
```powershell
 iwr -useb https://appwrite.io/cli/install.ps1 | iex
```
this is the error it produces:

 ```powershell
iex : At line:54 char:4
+ "@ -ForegroundColor red
+    ~~~~~~~~~~~~~~~~
Unexpected token '-ForegroundColor' in expression or statement.
At line:54 char:21
+ "@ -ForegroundColor red
+                     ~~~
Unexpected token 'red' in expression or statement.
At line:57 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
At line:1 char:49
+ iwr -useb https://appwrite.io/cli/install.ps1 | iex
+                                                 ~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

## Have you spent some time to check if this issue has been raised before? yes

(Have you googled for a similar issue or checked our older issues for a similar bug) yes

## To Reproduce
 just enter
```powershell
 iwr -useb https://appwrite.io/cli/install.ps1 | iex
```
 into powershell. It will produce the error. Looks like error in code.

(Write your steps here:)

## Expected behavior

It is supposed to install Appwrite CLI via POwershell

(Write what you thought would happen.)
It would install appwrite cli
## Actual Behavior

Cli install script produced an error

## Your Environment

(Write Environment, Operating system and version etc.)
windows 10 home, ram 32gb,  intel i7

Thanks!. Please Fix

**Comment by TorstenDittmann** [comment]
Thanks for the report!

Sorry that I couldn't answer earlier, I am moving right now to a new place and this issue popped up while I was gone 😅 

The bug got fixed here: https://github.com/appwrite/sdk-generator/pull/161

Before this gets released, feel free to use this script: https://gist.github.com/TorstenDittmann/6279f63e58af09a6dc9129823ce79c60

**Comment by cambo2015** [comment]
Hey no problem🥳 Thank you! Appwrite is amazing!

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/sdk-for-cli/releases/tag/0.9.0 👏🏻 

Just need to wait for CI to finish 🙂
