### ISSUE TITLE
Custom variables are undefined in process.env with Node.js 14.5 runtime

### ISSUE THREAD

**Issue by browasaki** [appwrite/appwrite#1121]
## 🐛 Bug Report

**Custom variables are undefined in process.env with Node.js 14.5 runtime**

If you create a **Variable** into *Functions > Settings page* its value is always undefined from *process.env* during the runtime.

## Have you spent some time to check if this issue has been raised before?

Yes, I've talked with the support on Discord.

## To Reproduce

- Create a Function for Node.js runtime with a `console.log(process.env.MY_VARIABLE)` and deploy it
- Add *MY_VARIABLE* with a custom value in *Functions > Settings > Variables*
- Test it and check 

## Expected behavior

To see the value of my defined *MY_VARIABLE* but I'm getting `undefined`.

## Your Environment

Appwrite v:0.7.2.145, running on Digital Ocean Droplet (Ubuntu 20.04 LTS) from Docker Container.

**Comment by tibs245** [comment]
Same with NodeJS Runtime and Deno Runtime too

## To Reproduce

    Create a Function for Node.js or Deno runtime with a console.log(process.env.MY_VARIABLE) or (Deno.env.get('MY_VARIABLE') and deploy it
    Add MY_VARIABLE with a custom value in Functions > Settings > Variables
    Test it and check

Expected behavior

To see the value of my defined MY_VARIABLE but I'm getting undefined.

## Your Environment

APPWRITE_FUNCTION_ENV_VERSION=1.6
Appwrite v:0.7.2.145 , running on local Fedora 33 System from Docker Container.

**Comment by lohanidamodar** [comment]
@browasaki @tibs245 We have found and resolved the issue with this PR #1161.
You should be able to fix the issue in your current system by passing the `_APP_OPENSSL_KEY_V1` environment variable to your `appwrite-worker-functions` service in your `docker-compose.yml` file.

**Comment by browasaki** [comment]
@lohanidamodar great news!
