### ISSUE TITLE
Renaming key in document settings breaks the database.

### ISSUE THREAD

**Issue by 2shrestha22** [appwrite/appwrite#1123]
## 🐛 Bug Report

I have documents with label and key `name` renaming `key` makes data in documents to disappear from appwrite dashboard (haven't tried in actual code).

## Have you spent some time to check if this issue has been raised before?

Tried multiple times.

## To Reproduce

Rename `key` of current document to something different.

## Expected behavior

My existing data should be appear in the new label/key.

## Actual Behavior

Column (data) becomes empty after renaming `key`.
before renaming key:
![image](https://user-images.githubusercontent.com/24835256/117309543-3ad67400-aea2-11eb-95ba-f7b1df8fdccd.png)
after renaming key:
![image](https://user-images.githubusercontent.com/24835256/117309638-55105200-aea2-11eb-9cb7-44b1c4e6a05d.png)

## Your Environment

Docker version 20.10.6, build 370c28948e

Appwrite version: v:0.7.2.145

**Comment by TorstenDittmann** [comment]
@eldadfux any thoughts on this?

**Comment by eldadfux** [comment]
We don't really change the data in the DB after the key change in the rule, so this would be expected. This behavior will be changed after we release the new version of the DB, where we won't allow to update the key name.

**Comment by eldadfux** [comment]
Closing this issue as of v0.8 and upcoming 0.9 this is the expected behavior, as part of the DB update we will adapt this logic to be more expectable.
