### ISSUE TITLE
Problems with a zip archive of docx files

### ISSUE THREAD

**Issue by kodumbeats** [appwrite/appwrite#1124]
## 🐛 Bug Report

Something happens during file upload/download to affect certain filetypes. When uploading a ~5MB zip of `.docx` files and redownload, the Word files are corrupted. Could it be an edge case of gzip? https://github.com/appwrite/appwrite/blob/c961382fb7a59ce908b4982a572e02e6e0feacd5/app/controllers/api/storage.php#L110-L120

## Have you spent some time to check if this issue has been raised before?

Yes.

## To Reproduce

- Upload a large zip (~> 5MB) of docx files
- Download from Appwrite
- Unzip and open documents

## Expected behavior

Document opens successfully.

## Actual Behavior

Word document is corrupted.

## Additional Details

- This behavior is not seen when uploading/downloading individual `.docx` files
- This behavior is not seen when uploading/downloading zip archives with other file types

## Your Environment

OS: Arch Linux
Kernel: 5.11.16-arch1-1
Docker: v20.10.6
Appwrite: `dev.145` and `0.7.2.145`

**Comment by lohanidamodar** [comment]
@kodumbeats The problem was actually with large file size not only docs and zips, #1226 should resolve the issue

**Comment by lohanidamodar** [comment]
related to #1226
