### ISSUE TITLE
Incorrect command when Cloud Function deployed with Appwrite CLI

### ISSUE THREAD

**Issue by 2shrestha22** [appwrite/appwrite#1132]
## 🐛 Bug Report

Deploying cloud function using Appwrite CLI creates incorrect command. Command given as `node index.js` is converted to `node%20index.js` and this gives output in logs; `OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "node%20index.js": executable file not found in $PATH: unknown
`

## Have you spent some time to check if this issue has been raised before?

Yes I can confirm it is a bug, deploying tag manually from console creates correct command.

## To Reproduce

Deploy cloud function with Appwrite.
```
appwrite functions createTag \
    --functionId=6012cc93d5a7b \
    --command="node index.js" \
    --code="/myrepo/myfunction"
```

## Expected behavior

Command should not be `node%20index.js` but `node index.js`.

## Actual Behavior

![image](https://user-images.githubusercontent.com/24835256/117569117-c428b900-b0e3-11eb-8415-b18004a7a819.png)

## Your Environment

Appwrite version: v:dev.145

**Comment by lohanidamodar** [comment]
@christyjacob4 This happened to me too. I believed this error was already fixed sometime back.

**Comment by christyjacob4** [comment]
@2shrestha22  Thanks for reporting this. 

@lohanidamodar let me take a closer look 👍

**Comment by christyjacob4** [comment]
@2shrestha22  this PR should fix it 😄  
https://github.com/appwrite/sdk-generator/pull/175

**Comment by TorstenDittmann** [comment]
We released the new CLI now https://github.com/appwrite/sdk-for-cli/releases/tag/0.9.0 👏🏻
