### ISSUE TITLE
SMTP Disconnected - 0.7.2

### ISSUE THREAD

**Issue by thesmartrenovation** [appwrite/appwrite#1136]
Hello, I hope you can help me, my application today does not send emails. I checked the server and the SMTP service appears disconnected.

![image](https://user-images.githubusercontent.com/57076657/117859320-72ec0700-b254-11eb-8223-f23e1bcfd04d.png)
![image](https://user-images.githubusercontent.com/57076657/117859337-77182480-b254-11eb-8cf4-71eaac3cedb8.png)

I am using my own smtp server. Yesterday it was working correctly and today it appears disconnected.

**Comment by kodumbeats** [comment]
Troubleshooted together on Discord. `docker-compose logs appwrite-worker-mails` had the useful error message to debug.

**Comment by Hip2thahoppa** [comment]
Interesting.pull up the logs minutes before the error occurred.


Sent from Yahoo Mail for iPhone


On Tuesday, May 11, 2021, 10:29 AM, thesmartrenovation ***@***.***> wrote:




Hello, I hope you can help me, my application today does not send emails. I checked the server and the SMTP service appears disconnected.




I am using my own smtp server. Yesterday it was working correctly and today it appears disconnected.

**Comment by eldadfux** [comment]
@Hip2thahoppa you can follow this guide: https://dev.to/appwrite/30daysofappwrite-getting-started-with-smtp-1e2e
