### ISSUE TITLE
[WEB] Full list of users is not displayed

### ISSUE THREAD

**Issue by fishmandev** [appwrite/appwrite#1144]
## 🐛 Bug Report

Full list of users is not displayed (broken)

## Have you spent some time to check if this issue has been raised before?

Yes

## To Reproduce

When creating a new user, add a single quote to the field 'Name'

## Expected behavior

![image](https://user-images.githubusercontent.com/29619660/118232078-b9ca3e80-b498-11eb-87b5-996595e058a8.png)

## Actual Behavior

**3 users found**, but only one is displayed

![image](https://user-images.githubusercontent.com/29619660/118232368-1cbbd580-b499-11eb-9739-1c54923fac02.png)

## Your Environment

OS: Ubuntu 20.04.2 LTS
Browser: FF 88.0.1 (64-bit)
Appwrite: v:0.7.2.145

**Comment by eldadfux** [comment]
Added a fix in #1147 - should be released in next version.

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/appwrite/releases/tag/0.8.0 👏🏻
