### ISSUE TITLE
To get a member's team status

### ISSUE THREAD

**Issue by skyycodes** [appwrite/appwrite#1146]
## 🚀 Feature

To make a function which we can use to get a member's team status using his userid or email id.

## Have you spent some time to check if this issue has been raised before?

Yes

## Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

I think it should be implemented because it will help if i wants to execute a function only if user is part of a team or i wants to check that user can not join more than one team(we can change it to any number).

**Comment by TorstenDittmann** [comment]
Hey 👋🏻 

Can you give an example of what the usage should look like?

**Comment by skyycodes** [comment]
Hey,
Example : I am hosting an event and i want that the event can only be joined if you are member of the team. So i want to make a check function from which we can find the if member/user is part of a team using his user id/session.
