### ISSUE TITLE
Removing Collection Rule causes error when updating Document.

### ISSUE THREAD

**Issue by pspierce** [appwrite/appwrite#1152]
## 🐛 Bug Report

Removing a rule from a Collection causes an error when updating a Document within the collection.

## Have you spent some time to check if this issue has been raised before?

Yes.

## To Reproduce

1. Create a Collection giving it a number of Rules.
2. Create a Document and update.
3. Enter Settings on the Collection and "Remove" rules.
4. Attempting to update a document w/in the Collection causes:

## Expected behavior

Document updates w/out error.

## Actual Behavior

"revised_reality" was the rule I removed.

> Message: Bad structure. Invalid document structure: Unknown properties are not allowed (revised_reality) for this collection. Make sure to follow ladder_of_inference collection structure

## Your Environment

Linux with appwrite 0.7.2

**Comment by eldadfux** [comment]
This issue was fixed and its now available as part of Appwrite 0.12. You can learn more about the new version here: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
