### ISSUE TITLE
databaseListDocuments#filters with "OR"

### ISSUE THREAD

**Issue by kutear** [appwrite/appwrite#1174]
## 🚀 Feature

https://appwrite.io/docs/client/database#databaseListDocuments

![image](https://user-images.githubusercontent.com/8605389/119133375-66df2100-ba6e-11eb-8d34-2721176fa6d6.png)

how can i query database with `OR`， such as query by `type=1 OR type=2`

by the way, it's ready to support `IN`? ref: https://github.com/appwrite/appwrite/issues/826

## Have you spent some time to check if this issue has been raised before?

yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

yes

## Pitch

(Please explain why this feature should be implemented and how it would be used. Add examples, if applicable.)

**Comment by TorstenDittmann** [comment]
Hey @kutear 👋🏻 

Currently we do not offer `OR` or `IN` operators for querying our database. We are planning to add this kind of features to our current database refactoring - you can read more about it https://github.com/appwrite/rfc/pull/21 here if you are interested.

Gonna leave this issue open, until we have addressed it 👍🏻

**Comment by eldadfux** [comment]
You'll be able to have or functionality similar to a contains operator as part of Appwrite 0.12. more information is available at: https://warm-tray-285.notion.site/Appwrite-0-12-Alpha-The-Database-Refactor-70f2c1d234394d9ab9d0d548fe5449bc

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b

**Comment by merabtenei** [comment]
Is there any update on this ? This is quite a basic functionnality. Suppose we have a Chat app with 1 to 1 conversations. to list all messages between User A and User B from a collection with sender, receiver, message attributes we'll need to do a listDocument with send = User A or User B and receiver = User A or User B

**Comment by 0xDjole** [comment]
Appwrite sucks. Who is with me?

**Comment by step135** [comment]
Is there any update on this ? This is quite a basic functionality and I don't see it implemented after two years.
