### ISSUE TITLE
Discord OAuth logins do not trigger account.sessions.create events correctly

### ISSUE THREAD

**Issue by PrivateGER** [appwrite/appwrite#1176]
## 🐛 Bug Report

Logging in using the Discord OAuth integration creates a working session and triggers any functions with the account.sessions.create trigger, however the functions do not receive any data in the APPWRITE_FUNCTION_EVENT_DATA environment variable.

However, logging into the same account using email/password authentication results in correct data being passed to the function.

## To Reproduce
- Enable the Discord OAuth provider
- Create a Function with an account.sessions.create trigger
- Log into any account using the Discord OAuth provider

## Expected behavior

The function gets the full session object in the environment variable, as it happens with normal sessions.

## Actual Behavior

The Function is triggered with enviroment variables that look like this:
```
{
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  HOSTNAME: 'a4f7260e2938',
  APPWRITE_FUNCTION_PROJECT_ID: '60a7fe7c9d8c1',
  APPWRITE_FUNCTION_ID: '60a7ff0288b1a',
  APPWRITE_FUNCTION_TAG: '60a7ff724c0f1',
  APPWRITE_FUNCTION_TRIGGER: 'event',
  APPWRITE_FUNCTION_RUNTIME_VERSION: '15.5',
  APPWRITE_FUNCTION_EVENT: 'account.sessions.create',
  APPWRITE_FUNCTION_EVENT_DATA: 'null',
  APPWRITE_FUNCTION_DATA: 'null',
  APPWRITE_FUNCTION_NAME: 'check',
  APPWRITE_FUNCTION_RUNTIME_NAME: 'Node.js',
  APPWRITE_FUNCTION_USER_ID: 'null',
  APPWRITE_FUNCTION_JWT: 'null',
  NODE_VERSION: '15.5.1',
  YARN_VERSION: '1.22.5',
  HOME: '/root'
}
```

## Your Environment

Pop_OS with the latest appwrite version (8.0.0).

**Comment by eldadfux** [comment]
Yep, I can confirm this is a bug, this endpoint returns a 301 response and not a JSON payload and the event handler can't fetch the right data. Seems like we need to pass the payload manually like we do on DELETE requests where the response code is 204 (no content).

Like we do here:
https://github.com/appwrite/appwrite/blob/ed751160de92dcf6f492d45fba3a0e4b4562e7f7/app/controllers/api/account.php#L1683-L1689

**Comment by christyjacob4** [comment]
Hey the fix for this should be ready :)

**Comment by PrivateGER** [comment]
Since the fix was merged, I guess this issue can be closed.
