### ISSUE TITLE
Adding function tag fails with CLI

### ISSUE THREAD

**Issue by didair** [appwrite/appwrite#1177]
## 🐛 Bug Report

appwrite functions createTag --functionId=60a8329772d93 --command='node hello.js' --code='/functions/'

Warning: Invalid argument supplied for foreach() in /usr/local/code/src/Parser.php on line 47

## Your Environment
CLI Version : 0.10.1
Server Version : 0.8.0

**Comment by christyjacob4** [comment]
@didair 
Can you share a bit more about your folder structure ? 
What is the absolute path of your function's folder ?
What are the contents your function's directory ?

**Comment by didair** [comment]
@christyjacob4 Sure! 

The functions folder is located in ~/functions and contains a single file called: hello.js

![bild](https://user-images.githubusercontent.com/2635185/120688112-03f47d80-c4a3-11eb-9d0e-490a572aa50c.png)

**Comment by eldadfux** [comment]
@christyjacob4 I think that if we'll stop assuming the output [here](https://github.com/appwrite/sdk-for-cli/blob/master/src/Parser.php#L45) is 100% an array and handle other types or at least debug them - we'll be one step closer to solve this issue.

**Comment by TorstenDittmann** [comment]
This is fixed with the new functions service now 👍🏻
