### ISSUE TITLE
Upload file from the client with signed url.

### ISSUE THREAD

**Issue by hsequeda** [appwrite/appwrite#1179]
## 🚀 Feature

Allow uploading of files from the client side using a signed URL generated
by a server side (storage) service. This will allow you to integrate the AppWrite 
storage service without using the user service. This is great to uploading some heavy
files like movies or whatever you want.

**That feature exist on the S3 service of AWS.**

 https://aws.amazon.com/es/blogs/compute/uploading-to-amazon-s3-directly-from-a-web-or-mobile-application/

**Comment by TorstenDittmann** [comment]
Hey @hsequeda 👋🏻 

To understand your suggestion correctly - you wan't to be able uploading a file without any permissions?

In short, you want to upload files anonymously?

**Comment by hsequeda** [comment]
Hi @TorstenDittmann

**Comment by TorstenDittmann** [comment]
I think the RFC I started this week will be something that should solve this issue 🙂

https://github.com/appwrite/rfc/pull/25

**Comment by hsequeda** [comment]
Yes, that could solve this issue.

**Comment by EVDOG4LIFE** [comment]
We are quite a few versions ahead and the linked RFC has been merged for a while - please confirm if this is still needed!
