### ISSUE TITLE
Making new document inherit their collection's permissions if no write or read parameters were provided

### ISSUE THREAD

**Issue by Silfalion** [appwrite/appwrite#1180]
## 🚀 Feature

When creating a document through the Flutter SDK providing write and read permissions is necessary even if there was an authenticated session beforehand, it seems little bit repetitive to ask for them again. Another approach would be to automatically make the new documents inherit their collection's permissions.

## Have you spent some time to check if this issue has been raised before?

yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes, kinda.

## Pitch

It would lower the effort(not by much of course) to have to think of which permissions to give a new document.

**Comment by TorstenDittmann** [comment]
Hey 👋🏻 

We are aware of this and have already discussed possible solutions to make this more developer friendly 👍🏻 

I am gonna leave this issue open, as long as we haven't taken care of it.

**Comment by Silfalion** [comment]
Hi 👋🏻

I see, thank you for taking it into consideration.

**Comment by eldadfux** [comment]
We have re-written the permission mechanism to make it much more simple. Appwrite now supports collection and document level permissions models. More can be found here: https://appwrite.io/docs/database#permissions
