### ISSUE TITLE
Install failed on raspberry pi

### ISSUE THREAD

**Issue by Alphapage** [appwrite/appwrite#1181]
Hello, 
I try to install version 0.8 on raspberry pi.
First, I had to use --privileged command with docker run to fix a python error.
But now, I get:
`Pulling mariadb (appwrite/mariadb:1.2.0)...
no matching manifest for linux/arm/v7 in the manifest list entries
`
Thank you in advance for your help.

**Comment by doricci** [comment]
Hello @Alphapage
I had the same issue on my rpi 4 2gb, for me it was because raspian was the 32bit os. 
To solve it I had to install Ubuntu server 20.04 64bit so the os would detect the ARM64/v8. 
I think that it can also work with raspbian 64 bit, but I didn't tested it.

**Comment by christyjacob4** [comment]
@doricci @Alphapage that's correct. Currently it works only in 64bit archs

**Comment by eldadfux** [comment]
Closing for now.

**Comment by Alphapage** [comment]
Running raspberry pi in 64bits solved the problem.
Sorry, but I didn't notice Appwrite was only for 64bits arm.
Thank you very much.
