### ISSUE TITLE
Appwrite functions

### ISSUE THREAD

**Issue by cambo2015** [appwrite/appwrite#1184]
Hey again🎉
I'm trying to upload a function. I want to upload my function using the CLI but I don't want to create the function using the GUI first. I want to only create the function and upload the function using only the  CLI. Is there a way to accomplish this? I have tried but haven't been successful

**Comment by christyjacob4** [comment]
Hey this tutorial was written exactly for that. 
Take a look https://dev.to/appwrite/30daysofappwrite-appwrite-cloud-functions-1pf2
Feel free to close this issue if this answers your question.

**Comment by cambo2015** [comment]
That was fast! Thank you! Yes this should be really helpful.
