### ISSUE TITLE
Team membercount doesn't get updated correctly

### ISSUE THREAD

**Issue by Fabian9799** [appwrite/appwrite#1190]
## 🐛 Bug Report

The team membership count doesn't get updated if a user gets deleted and another account with the same email gets created

## To Reproduce

1. create user
2. add user to team
3. delete user
4. create user with the same email
5. add user to same team

## Expected behavior

The team membercount should be updated to 1 since there is only 1 user on the team

## Actual Behavior

The membercount is updated to 2

[Video](https://cdn.discordapp.com/attachments/713769024613384283/846702663194509333/2021-05-25_12-49-24.mp4)

## Your Environment

Appwrite 0.8 on Docker 19.03.12 and Ubuntu 20.04 ( 2GB droplet from DigitalOcean)

**Comment by christyjacob4** [comment]
Thanks for reporting @Fabian9799. This should be fixed in this PR :+1:

**Comment by eldadfux** [comment]
Fixed and merged to master on #1217 - will be released in the next version

**Comment by eldadfux** [comment]
This is now fixed and available as part of Appwrite 0.9:
https://dev.to/appwrite/announcing-appwrite-0-9-the-open-source-firebase-alternative-53ho 🥳 🎉
