### ISSUE TITLE
Rebinding appwrite-worker-functions tmp mount/volume breaks it

### ISSUE THREAD

**Issue by alexpdr** [appwrite/appwrite#1197]
## 🐛 Bug Report
Rebinding appwrite-worker-functions tmp mount/volume breaks it
![image](https://user-images.githubusercontent.com/49159860/119627134-326fba00-be0c-11eb-8e54-f9a915bedf9b.png) 
_affected service_

## Have you spent some time to check if this issue has been raised before?
- Checked Docs :heavy_check_mark: 
- Checked Google :heavy_check_mark:
- Checked StackOverflow :heavy_check_mark: 
- Checked discord :heavy_check_mark: 
- Checked w/Devs :heavy_check_mark: 

## To Reproduce
1. Rebind the temporary data volume/mount for the `appwrite-worker-functions` to any other location.
2. Upload & Run a `hello_world.py` method
3. Check logs for error output
4. Confirm issue from created & affected function container

## Expected behavior
I expected to be able to change the linked location outside of the container without issue.
f.ex:  `- /tmp:/tmp:rw` :arrow_right: `- ${MY_STORAGE}/appwrite/tmp:/tmp:rw`

## Actual Behavior
1. If the `- /tmp:/tmp:rw` volume/mount is changed any way it breaks the functions containter. 
Specifically it makes the container unable to load functions for execution, resulting in 
`Container {container_hash} is not running` being sent to `stderr`
![image](https://user-images.githubusercontent.com/49159860/119631392-24bc3380-be10-11eb-8b70-5883a5c23d0a.png)

2. The affected container used for function execution produces the logs:
 `mv: can't rename '/tmp/code.tar.gz': No such file or director` 
![image](https://user-images.githubusercontent.com/49159860/119631615-5e8d3a00-be10-11eb-9652-e276be04f971.png)

3. This happens regardless of method of upload ( both CLI + UI ) and whether the method is new or existing and seems to be caused by the command used as entrypoint which might be hardcoded to an out-of-container location.
![image](https://user-images.githubusercontent.com/49159860/119631943-a9a74d00-be10-11eb-808c-dab225c07e4a.png)

## Your Environment
**Versions**
- Host: `Ubuntu 20.04.2 LTS x86_64`
- DC: `docker-compose version 1.25.0`
- Docker: `Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2`
- Python: Tested with both 3.8 and 3.9 versions.

**Files to reproduce**
- Used code -> [code.tar.gz](https://github.com/appwrite/appwrite/files/6545314/code.tar.gz)
- DC + .env -> [stack_appwrite.zip](https://github.com/appwrite/appwrite/files/6545329/stack_appwrite.zip)

**Other**
The [production](https://gist.github.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5) docker-compose file have been updated to allow for a centrally configured traefik proxy instead of the default included one. 

The files required have been added above as the following is subject to change, but full source for the implementation can be found [here](https://github.com/alexpdr/hs) and for the appwrite stack specifically [here](https://github.com/alexpdr/hs/tree/main/stacks/appwrite)

**Comment by alexpdr** [comment]
Might be fixed by updating the pathing in the script used as `entrypoint` for the container!

**Comment by TorstenDittmann** [comment]
This should be fixed now as well with the new Functions service 👍🏻
