### ISSUE TITLE
when adding user without name dashboad did't open this user account info

### ISSUE THREAD

**Issue by abdelrahman-abied** [appwrite/appwrite#1204]

**Comment by eldadfux** [comment]
Can you share more info or maybe some screenshots?
We did push a fix that make the dashboard show anonymous users better, but I'm not sure this is your case.

**Comment by abdelrahman-abied** [comment]
![Screenshot from 2021-05-28 03-15-56](https://user-images.githubusercontent.com/31194055/119943572-7f31cd00-bf93-11eb-92d9-7d6db719c1ba.png)

**Comment by eldadfux** [comment]
@TorstenDittmann Did we fixed this issue with the latest updates to the users UI? Maybe we can add a placeholder for empty names and/or add a link on the email address?

**Comment by TorstenDittmann** [comment]
> @TorstenDittmann Did we fixed this issue with the latest updates to the users UI? Maybe we can add a placeholder for empty names and/or add a link on the email address? 

No, it didn't fix it 🙂

**Comment by abdelrahman-abied** [comment]
i download the last version but did't fix it

**Comment by eldadfux** [comment]
@abdelrahman-abied I have create a PR with a fix that is waiting for review.

**Comment by abdelrahman-abied** [comment]
> @TorstenDittmann Did we fixed this issue with the latest updates to the users UI? Maybe we can add a placeholder for empty names and/or add a link on the email address?
what's the version number ,i installed appwrite version 0.8.0

**Comment by eldadfux** [comment]
This is now fixed and available as part of Appwrite 0.9:
https://dev.to/appwrite/announcing-appwrite-0-9-the-open-source-firebase-alternative-53ho 🥳 🎉
