### ISSUE TITLE
Twitch OAuth not working

### ISSUE THREAD

**Issue by alexweininger** [appwrite/appwrite#1205]
## 🐛 Bug Report

After logging in to Twitch it redirects to Appwrite then gives this error:

## To Reproduce

1. `sdk.account.createOAuth2Session('twitch');`
2. Login with Twitch

## Expected behavior

Should redirect back to the success url with a session.

## Actual Behavior

![Error screen](https://media.discordapp.net/attachments/564160731327758347/847715517216063548/Screen_Shot_2021-05-28_at_12.58.26_AM.png)

## Your Environment

Using the web sdk version 3.0.3

**Comment by eldadfux** [comment]
Fix has been merged to master and will be released with the next Appwrite version.

**Comment by eldadfux** [comment]
This is now fixed and available as part of Appwrite 0.9:
https://dev.to/appwrite/announcing-appwrite-0-9-the-open-source-firebase-alternative-53ho 🥳 🎉
