### ISSUE TITLE
Powershell installation Script is not setting the app correctly for PS/CMD usage

### ISSUE THREAD

**Issue by AdamRussak** [appwrite/appwrite#1210]
tryid to install and it skips the setting path
see pictures:
https://media.discordapp.net/attachments/564161373148414012/847759993272926268/unknown.png

https://media.discordapp.net/attachments/564161373148414012/847760158125064202/unknown.png

**Comment by TorstenDittmann** [comment]
As discussed on Discord - I will look into this and also discover the option to publish the CLI script to https://www.powershellgallery.com/ as a native PowerShell Module 👍🏻

**Comment by TorstenDittmann** [comment]
This should be fixed with the new CLI 👍🏻
