### ISSUE TITLE
Deleting of project "owners" doesn't work

### ISSUE THREAD

**Issue by Fabian9799** [appwrite/appwrite#1212]
## 🐛 Bug Report

If i try to delete a admin user from a project im getting a 404 error

## To Reproduce

1. Add a user to the project
2. Confirm the email
3. Try to delete the user

## Expected behavior

the request to https://api.domain.com/v1/teams/60acd5725a943/memberships/ should be successful and the user should be deleted

## Actual Behavior

a request gets sent to https://api.domain.com/v1/teams/60acd5725a943/memberships/null and returns a 404 error
`{"message":"Invite not found","code":404,"version":"0.8.0"}`

## Your Environment

Appwrite 0.8 on Docker 19.03.12 and Ubuntu 20.04 ( 2GB droplet from DigitalOcean)
Docker doctor also doesn't show any problems

**Comment by eldadfux** [comment]
Fixe has been merged to master and will be released with the next Appwrite version.

**Comment by eldadfux** [comment]
This is now fixed and available as part of Appwrite 0.9:
https://dev.to/appwrite/announcing-appwrite-0-9-the-open-source-firebase-alternative-53ho 🥳 🎉
