### ISSUE TITLE
Document reference will be deleted if parent document deleted

### ISSUE THREAD

**Issue by mediengestadler** [appwrite/appwrite#1215]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

I have a document (collection A) with a reference from Collection B. If I delete the document in collection A, Appwrite delete although the document in collection B. If this is not a bug, that’s not good, because the document in collection B could somewhere else be used, too and I only want to delete the document in collection A but not B.

## Have you spent some time to check if this issue has been raised before?
Yes
(Have you googled for a similar issue or checked our older issues for a similar bug)
Yes
## To Reproduce

(Write your steps here:)
- Create two collection and add in both one document. One of both documents have the reference to the other 
- delete the document which have the reference Link.
- After that in both collections are no documents

## Your Environment
Current version of appwrite

**Comment by eldadfux** [comment]
This issue is probably not relevant with the release of the upgraded database API. You can learn more about the new version here: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
