### ISSUE TITLE
Create tag not working in Node.js SDK

### ISSUE THREAD

**Issue by alexweininger** [appwrite/appwrite#1219]
## 🐛 Bug Report

The `functions.createTag` function is not working in the Node.js SDK.

## To Reproduce

Code causing the bug:

```js
functions.createTag("60b1836a8e5d9", "python ./hello.py", fs.createReadStream(tarFilePath);
```

Using `storage.createFile`, I have verified that the `fs.createReadStream(tarFilePath)` is not causing the issue, since the following code worked fine.

```js
storage.createFile(fs.createReadStream(tarFilePath));
```

## Expected behavior

Tag should be created and the tar file should be uploaded properly.

## Actual Behavior

The tag is created, however the tar file seems to not get uploaded properly. The file size is shown as 0 as pictured below.

![Screenshot of broken tag](https://media.discordapp.net/attachments/564161373148414012/848098420429684796/Screen_Shot_2021-05-29_at_2.20.12_AM.png)

I have verified that manually creating tags via Appwrite console does work properly.

When trying to execute the broken tag, it gets the following error:

```
Error response from daemon: Container 0d7fda13f6f46c092c6fa91fe7290bdedc06762edab0d75d29733fd4628a4658 is not running
```

And the error collected from the Appwrite docker container logs is:

```
Error] Method: GET
[Error] URL: /
[Error] Type: Utopia\Exception
[Error] Message: Not Found
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 686
```

## Your Environment

Client | macOS
-- | --
CPUs | Apple M1 (8 x 24)
Memory (System) | 16.00GB (0.12GB free)

Wow 🤯  the M1 really does get the most out of your available memory 🤣 

Remote | Appwrite virtual machine
-- | --
OS | Linux x64 5.4.0-1043-azure
CPUs | Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 2294)
Memory (System) | 3.84GB (0.19GB free)
VM | 0%

**Comment by lohanidamodar** [comment]
Hey @alexweininger, Thank you for reporting the issue, however I'm unable to reproduce the issue can you please some more details
1. The path used is actual `.tar.gz` file
2. The file size of the `.tar.gz` file
3. does running this `functions.createTag("60b1836a8e5d9", "python ./hello.py", fs.createReadStream(tarFilePath);` command produce any error logs in `appwrite` container
4. Any difference in your scenario for running those codes? (I am creating a simple node script to test it)

**Comment by alexweininger** [comment]
1. The path is correct as the following code works for the storage upload:
2. File size is 165B
3. The only error from the appwrite container is the one mentioned in my original post.
4. No notable differences.

I have verified that the `fs.createReadStream` is not the issue as the following code results in the file being uploaded to storage correctly, but the tag does not.

```
await functions.createTag("60b1836a8e5d9", "python ./hello.py", fs.createReadStream(tarFilePath));
await storage.createFile(fs.createReadStream(tarFilePath));
```

**Comment by alexweininger** [comment]
I found a way to get it to work. If by chance anyone runs into this issue here is the code that worked for me:

```js
// without the following line, upload is always 0B, with this line upload always works
await workspace.fs.readFile(Uri.file(tarFilePath));

const resp = await functions.createTag("60...d9", "py ./hello.py", fs.createReadStream(tarFilePath));
```
