### ISSUE TITLE
docker-compose from documentation is unusable

### ISSUE THREAD

**Issue by dasheck0** [appwrite/appwrite#1224]
## 🐛 Bug Report

I am using the docker-compose as well as the .env file from the documentation (see https://appwrite.io/docs/installation and https://gist.github.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5). The only values I am overriding are 
```
_APP_DB_SCHEMA
_APP_DB_USER
_APP_DB_PASS
```
First of there is a warning that `_APP_DB_ROOT_PASS` is missing. When I access http://localhost I get a `500 Server Error`. In every container that has `mariadb` as dependency I get an error `Base table or view not found: 1146 Table`.

## Have you spent some time to check if this issue has been raised before?
I googled the error along with appwrite, which got me some issues on github in different repos, since this is a PHP mysql error and has nothing to do with appwrite itself. However, it has something to do with appwrite in a sense that it does not setup the tables correctly.

## To Reproduce
* Visit the links at https://gist.github.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5
* Download the .env file and override `_APP_DB_SCHEMA`, `_APP_DB_USER` and `_APP_DB_PASS` with the values of your choice
* Download the `docker-compose.yml` file into the same directory as `.env` file
* Change into directory where both files are located
* Run `docker-compose -f docker-compose.yml --env-file ./.env up -d`

## Expected behavior

Containers start up with errors and I get to the dashboard when accessing http://localhost.

## Actual Behavior

Containers do not start up correctly and when I access http://localhost I get an error
![image](https://user-images.githubusercontent.com/4851711/120112643-f4a9c300-c176-11eb-85ae-b6d7a24faf9f.png)

## Your Environment
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	3,1 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	428.0.0.0.0
  SMC Version (system):	2.45f4
  Serial Number (system):	C02VR0UEHTDH
  Hardware UUID:	6AB07C44-2991-57EC-AFD3-D46DED5AC4B6

macOS Catalina (10.15.7)

```
docker -v // Docker version 20.10.6, build 370c289
docker-compose -v // docker-compose version 1.29.1, build c34c88b2
```

**Comment by TorstenDittmann** [comment]
Hey @dasheck0 👋🏻 

That is definitely a bug! Will push a fix for this 🙇🏻

**Comment by dasheck0** [comment]
Great! Thanks for the reply

**Comment by TorstenDittmann** [comment]
https://gist.github.com/TorstenDittmann/0d63c1aae59036d623b564864715da74

@dasheck0  Can you try this? If its working - we will push it live 🤞🏻

**Comment by dasheck0** [comment]
Unfortunately not. I am currently on vacation and will be back next Tuesday. I will test this as soon as possible and provide you feedback

**Comment by TorstenDittmann** [comment]
> Unfortunately not. I am currently on vacation and will be back next Tuesday. I will test this as soon as possible and provide you feedback

Awesome, no hurry. It fixes it for me at least - so I will make this change live. I am gonna leave this issue open, once it is fixed for you 🙂 

Enjoy your holiday and stay healthy @dasheck0 👍🏻

**Comment by dasheck0** [comment]
Thanks @TorstenDittmann You too :)

**Comment by dasheck0** [comment]
@TorstenDittmann It is working. However, I do not know why. I diffed the files in your gist against my files. The docker-compose.yml files were identical. The env files had differences (mainly in the _APP_DB_* section). So this has to be a configuration issue instead of a bad container configuration. Since this is not live and I will surely user a different configuration I'd like to share my secrets with you in case I did something bad. Can you find any issues with the following .env file (just posting the differences to yours).

```
_APP_DB_SCHEMA=ngappwrite_production
_APP_DB_USER=ngappwriteuser
_APP_DB_PASS=ANi8BwUMRz*-cuZZDX.C4r2K
_APP_DB_ROOT_PASS=ANi8BwUMRz*-cuZZDX.C4r2K
```

**Comment by TorstenDittmann** [comment]
> @TorstenDittmann It is working. However, I do not know why. I diffed the files in your gist against my files. The docker-compose.yml files were identical. The env files had differences (mainly in the _APP_DB_* section). So this has to be a configuration issue instead of a bad container configuration. Since this is not live and I will surely user a different configuration I'd like to share my secrets with you in case I did something bad. Can you find any issues with the following .env file (just posting the differences to yours).
> 
> ```
> _APP_DB_SCHEMA=ngappwrite_production
> _APP_DB_USER=ngappwriteuser
> _APP_DB_PASS=ANi8BwUMRz*-cuZZDX.C4r2K
> _APP_DB_ROOT_PASS=ANi8BwUMRz*-cuZZDX.C4r2K
> ```

That is actually fine. I mean the `.env` file is there for you to configure your containers anyway 👍🏻 

Just keep in mind, that the MariaDB container will be initialized with these variables only on the first run. Meaning you cannot change this afterwards 🙂

**Comment by dasheck0** [comment]
This might be the issue. I remember that I changed the passwords during the process. However, I removed the volumes at some point but got the some error. Weird. It is working now, so I will close this. Thanks for your help!

**Comment by dasheck0** [comment]
@TorstenDittmann  One final remark: I looked into the appwrite/mariadb repository and found that it is just a mariadb image with some files the setup the tables. Didn't know that. The main file seems to be https://github.com/appwrite/docker-mariadb/blob/master/all.sql. Here are the first three lines

```
CREATE DATABASE IF NOT EXISTS `appwrite` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `appwrite`;
```

It seems that the `_APP_DB_SCHEMA` is not used here. It is also not used in the Dockerfile. So either there is another mechanism somewhere else I am not aware of or the parameter is useless and should be removed. As soon as I set the `_APP_DB_SCHEMA` to `appwrite` everything checks out.

**Comment by eldadfux** [comment]
@dasheck0 yes, you're right we ignore that var when initializing the database. The only way to set it up is to also manually change the schema name in the DB. After [this RFC](https://github.com/appwrite/rfc/pull/21) is implemented (WIP right now), we will start creating all the schemas directly from the Appwrite source code, so right now I don't see the point of addressing this issue.

**Comment by dasheck0** [comment]
Got it. So the easiest way to set everything up is to leave the schema at `appwrite` or setup the tables manually right?

Now I have a better feeling about this. When I got this error all this was a black box for me and I was not sure if the error was actually fixed. Thanks for sorting that out with me :)

**Comment by eldadfux** [comment]
> Got it. So the easiest way to set everything up is to leave the schema at `appwrite` or setup the tables manually right?

Yes

> Now I have a better feeling about this. When I got this error all this was a black box for me and I was not sure if the error was actually fixed. Thanks for sorting that out with me :)

Glad I could help :)
