### ISSUE TITLE
Swarm configuration not working on multi node cluster

### ISSUE THREAD

**Issue by doricci** [appwrite/appwrite#1227]
## 🐛 Bug Report

When running appwrite on a multi node swarm cluser, traefik return a 404.
When running the same configuration on a single node swarm cluster, everything is working fine.

## Have you spent some time to check if this issue has been raised before?

I check on internet and on the list of bugs, but I found nothing about swarm issues

## To Reproduce
I followed  the swarm deployement from https://dev.to/appwrite/30daysofappwrite-docker-swarm-integration-2io9 and ended up with the compose-file from step 1

1. Copy the docker-compose.yml & .env file from here: https://gist.github.com/doricci/9131190d78c24dc0c6cb9e4d2ec1fbf9
2. Update in the .env file the domain, email & SMTP configuration
3. comment the `- node.hostname == rpi4-node1` from the `deploy.placement.constraints` of each service
3. Deploy the stack with\
`docker-compose config > stack.nfs.yml && docker stack deploy --compose-file stack.nfs.yml appwrite`
4. Wait for the stack to be deployed
5. Access the url of the appwrite instance
 

## Expected behavior

Seeing the sign up form and be able to use appwrite the same way as I'm doing locally with the command `docker-compose up -d`

## Actual Behavior

Traefik return a 404 page not found when accessing the url of the appwrite instance.

when adding a constraint on the placement of the services, to make them working on the same node of the swarm cluster, everything is working perfectly fine.

## Your Environment

- 1 raspberry pi 3 setup as swarm manager,  with nginx as a reverse proxy
- 4 rasberry pi 4 with ubuntu-20.04/64bits setup as swarm worker
- 1 Nas setup as a NFS server
Everything is working on the same LAN, each server has access to the other servers, the NFS setup is working correctly on each of the 4 rapsberry pi

**Comment by kodumbeats** [comment]
@doricci I'm not sure what the root cause of this is yet, but can you try constraining just `traefik` and the main `appwrite` container to the same host?

**Comment by doricci** [comment]
Hello @kodumbeats, 
Sorry for the delayed answer but I could test it before...

I tryied and indeed, if I'm constraining `traefik` and the main `appwrite` it seems to work like a charm, but I could only test the login, the database & the function execution for now.

**Comment by doricci** [comment]
@kodumbeats  I found the issue, it's because the traefik from the docker-compose wasn't on swarm-mode and the labels of the others services have to be put under de `deploy` key of the stack file.
So the actual docker-compose.yml file can't be used like this to deploy appwrite in a swarm cluster.

If wanted, I can put the stack file to have a working docker-swarm example.

**Comment by eldadfux** [comment]
> @kodumbeats I found the issue, it's because the swarm-mode of the traefik from the docker-compose wasn't enabled and the labels of the others services have to be put under de `deploy` key of the stack file.
> So the actual docker-compose.yml file can't be used like this to deploy appwrite in a swarm cluster.
> 
> If wanted, I can put the stack file to have a working docker-swarm example.

It would be great to have your example available, I would love to check it out :)

**Comment by doricci** [comment]
@eldadfux I've created a gist [here](https://gist.github.com/doricci/4136d18b420c0c842cf0bea992041945) 

Please read the Readme.md first, If any part isn't clear please come back to me (here or on the discord with the same user id as github)

Thank you again for this awesome tool!
