### ISSUE TITLE
database.createDocument() requires permissions to be set

### ISSUE THREAD

**Issue by rdmchr** [appwrite/appwrite#1229]
## 🐛 Bug Report

The docs say, that the permissions part is optional for the createDocument() method, but if you don't add those parameters you'll get an error.

## Have you spent some time to check if this issue has been raised before?

Yeah, I talked to eldadfux on Discord, they told me to create this issue.

## To Reproduce

- Initialize an AppWrite instance (in this case saved as appwrite)
- Create a collection variable containing the collection id
- Make sure your collection has both read/write permissions set to `*`
- Run the code bellow:
```JavaScript
appwrite.database.createDocument(collection, {
        title: this.title
      });
```

## Expected behavior

I was expecting, that a new document with the content mentioned above would be created in my collection.

(Write what you thought would happen.)

## Actual Behavior

I get this error:
```
sdk.ts:16 Uncaught (in promise) AppwriteException: Unauthorized permissions
    at Appwrite.<anonymous> (http://localhost:3000/node_modules/.vite/appwrite.js?v=5b19fbc9:1636:15)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:3000/node_modules/.vite/appwrite.js?v=5b19fbc9:488:24)
AppwriteException @ sdk.ts:16
(anonymous) @ sdk.ts:162
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
(anonymous) @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
createDocument @ sdk.ts:1214
createRecipe @ CreateRecipe.vue:42
callWithErrorHandling @ runtime-core.esm-bundler.js:154
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:163
invoker @ runtime-dom.esm-bundler.js:333
```

(Write what happened. Add screenshots, if applicable.)

## Your Environment

OS: Windows 10
Running VueJS + TypeScript + Vite
Dependencies:
```JSOn
"dependencies": {
    "appwrite": "^3.0.4",
    "vue": "^3.0.5",
    "vue-router": "4",
    "vuex": "^4.0.1"
  },
  "devDependencies": {
    "@types/node": "^15.6.1",
    "@vitejs/plugin-vue": "^1.2.2",
    "@vue/compiler-sfc": "^3.0.5",
    "autoprefixer": "^10.2.6",
    "eslint": "7.2.0",
    "eslint-config-airbnb": "18.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "7.21.5",
    "eslint-plugin-react-hooks": "1.7.0",
    "eslint-plugin-vue": "^7.9.0",
    "postcss": "^8.3.0",
    "prettier": "^2.3.0",
    "tailwindcss": "^2.1.2",
    "typescript": "^4.1.3",
    "vite": "^2.3.4",
    "vue-tsc": "^0.0.24"
  }
```

**Comment by eldadfux** [comment]
Seems like this is a problem in the way we handle the default values on different SDKs. For both read & write params we use an empty array `[]` which is being translated by the server API as no permissions. You can overcome that by setting read and write to `undefined`, that way the SDK will not send them and Appwrite will be able to use proper default values.

@TorstenDittmann is working on a fix for this issue that might be released today.

**Comment by TorstenDittmann** [comment]
This should be fixed now 👍🏻
