### ISSUE TITLE
DioError when running Flutter app for Windows

### ISSUE THREAD

**Issue by getBoolean** [appwrite/appwrite#1230]
## 🐛 Bug Report

Dio exception when the app is run on windows. The character \u0000 seems to be stuck on to the end of the header field value. I searched through my code and didn't find cases of a space or other odd character after "shodana_reader" was mentioned.

The app will still run after reaching the exception but any calls to try log-in (and I assume other calls to the server) also give the same exception.

My code: https://github.com/Shodana-Studio/shodana_reader

## Have you spent some time to check if this issue has been raised before?

Yes

## To Reproduce

(Instructions for VSCode)

1. Turn on "Uncaught Exceptions" option for breakpoints on the "Run and Debug" tab.
2. Run the app for windows.
3. Exception happens sometime after the app screen loads.

## Expected behavior
No exception.

## Actual Behavior
DioError when making calls to the server

```
DioError (DioError [DioErrorType.other]: FormatException: Invalid HTTP header field value: "appwrite-windows://shodana_reader\u0000" (at character 34)

appwrite-windows://shodana_reader
```

## Your Environment
Windows 10, Flutter 2.2.1, VSCode or Android Studio, (package) appwrite 0.6.2

**Comment by lohanidamodar** [comment]
@getBoolean This is actually a bug of the underlying `package_info_plus` that we are using to get the package info for creating the origin header. One of our community member pointed this out and has created relevant issue in the `package_info_plus`
https://github.com/fluttercommunity/plus_plugins/issues/250

We are also working on a fix if possible at the moment. 
Thank you for your patience

**Comment by lohanidamodar** [comment]
@getBoolean they seem to have updated the plugin. Can you please test by overriding the package info plus dependency to the latest version. In your `pubspec.yml` file you can add a section and share the result if it works. Thank you 🙏🏻 

```yaml
dependency_overrides:
    package_info_plus: 1.0.3
```

**Comment by getBoolean** [comment]
The error does still occurs with `package_info_plus: 1.0.3`

**Comment by lohanidamodar** [comment]
> The error does still occur with `package_info_plus: 1.0.3`

Can you try `package_info_plus: 1.0.3` separately in your project and get the value, print in console, to check if the null character still exists? Might just be overriding not working?

**Comment by lohanidamodar** [comment]
@getBoolean This should be resolved by upgrading to latest SDK. If the issue occurs again, feel free to reopen the issue.
