### ISSUE TITLE
access-control-allow-origin * not working

### ISSUE THREAD

**Issue by gorootde** [appwrite/appwrite#1236]
## 🐛 Bug Report

Adding a web platform with hostname `*` does not allow origin `null` to talk to Appwrite. 

## Have you spent some time to check if this issue has been raised before?

Yes

## To Reproduce

Create a static html document and open it directly from the filesystem (in my case a apache Cordova app running in an iOS web view).  The browser will replace the `file:///` prefix with `null`, which doesn't match the ` Access-Control-Allow-Origin` header returned by Appwrite. The request fails.

## Expected behavior

There is a way to configure appwrite web platform to allow files opened from local filesystem to use appwrite backend.

## Actual Behavior

Browser reports `Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin.`

## Your Environment

Appwrite 0.8.0.
Apache Cordova or Safari as Browser
Web SDK ^3.0.1

**Comment by TorstenDittmann** [comment]
Hey @gorootde 

Can you try adding a `scheme` and `hostname` to your config.xml?

```xml
<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />
```

Resource: https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html

**Comment by gorootde** [comment]
Hey @TorstenDittmann,
thanks that solved my issue! However, maybe it would be worth a hint in the appwrite docs somewhere, since it cannot be solved by changing the appwrite config?

**Comment by TorstenDittmann** [comment]
> Hey @TorstenDittmann,
> thanks that solved my issue! However, maybe it would be worth a hint in the appwrite docs somewhere, since it cannot be solved by changing the appwrite config?

True, but this is more of a Cordova related issue then Appwrite 👍🏻
