### ISSUE TITLE
Dynamically Create Rules for Collections from Objects

### ISSUE THREAD

**Issue by Aliyss** [appwrite/appwrite#1238]
## 🚀 Feature

Being able to pass an Object to a function to create the rules for a collection. This would make it easier to work with Collections especially when creating/updating them dynamically.

## Have you spent some time to check if this issue has been raised before?

Issue hasn't been raised before.

However the issue #395 mentions a JSON type (https://github.com/appwrite/appwrite/issues/395#issuecomment-650572618). With the response concerning compatibility with GraphQL (https://github.com/appwrite/appwrite/issues/395#issuecomment-650573724). Depending on the support for JSON data types this feature may not be necessary. Since one could then just pass the object itself without having to create a rule, but instead defining a type as JSON.

Additionally; This mainly depends on what [appwrite.io](https://appwrite.io/) is heading for.
If I compare it to two others:

Firebase:
- No predefined Rules
- JSON can be uploaded directly

PostgreSQL:
- A JSON data type exists

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Overflew the Code of Conduct. I can't really focus on long text.

## Pitch

The main reason for this issue is to add more flexibility on the client side, when creating Collection Rules. Being able to pass a Class/Object to a function, to create Collection Rules.

Example:
```js
class Example {
  myString: ""
  constructor(inputString) {
    this.myString = inputString
  }
}
```
```js
function convertToRule(obj, required=true) {
  // Does a bit of magic checking typeof etc.
  return convertedRule
}
```
```js
let exampleObj = new Example("hello")
let x = convertToRule(exampleObj)

// Output x
[
  {
    type: 'text', // typeof myString
    key: 'myString', // Property Key
    label: 'myString', // Property Key
    default: 'hello', // Property Value
    array: false, // Check if isArray
    required: true // from converToRule parameter
  }
]
```

**Comment by TorstenDittmann** [comment]
Hey 👋🏻 

There are a few concerns - which are mainly about Validation of Data when it comes to this.

Another thing is, this will be super hard to query and filter based on values inside the JSON field. So I doubt, a JSON rules will be much different from a Text rule (except it will check if its valid JSON).

I could think of this as a web tool, where you paste your JSON, the tool will guess how the collection would look like and the tool will generate SDK calls for you. Adding this as a full fledged feature of Appwrite will be more work.

What do you think?

**Comment by Aliyss** [comment]
Hey there.

Thanks for the info. Makes sense to me.
Since this does make more sense as a web tool, I'll close the issue.
