### ISSUE TITLE
APP_CONSOLE_WHITELIST_EMAILS is case sensitive when it shouldn't be

### ISSUE THREAD

**Issue by alexweininger** [appwrite/appwrite#1240]
## 🐛 Bug Report

When signing up for the root user with APP_CONSOLE_WHITELIST_EMAILS set to an email address, the email has to have the same casing.

Email addresses are not case sensitive so this comparison should not be.

## To Reproduce

1. Enter an email in the `_APP_CONSOLE_WHITELIST_EMAILS` .env
2. Attempt to sign up with a root user with the same email, but one character capitalized.

## Expected behavior

Sign up should succeed. 

## Actual Behavior

Sign up fails.

**Comment by eldadfux** [comment]
A fix is available on master and will be released with the next Appwrite version.

**Comment by eldadfux** [comment]
This is now fixed and available as part of Appwrite 0.9:
https://dev.to/appwrite/announcing-appwrite-0-9-the-open-source-firebase-alternative-53ho 🥳 🎉
