### ISSUE TITLE
CLI doctor queue check misleading or wrong

### ISSUE THREAD

**Issue by AmazingTurtle** [appwrite/appwrite#1244]
You're checking the cache to validate if the queue is connected or not. Looks like a minor issue to me. You guys should probably check it.

edit: after looking into it again, seems like you don't have a `queue` entry in the `$register` at all, makes me wonder if you use the cache as queue at the same time. But then again, you could probably rearrange the code because you're essentially doing the same thing twice.

https://github.com/appwrite/appwrite/blob/a8dcd9efe34801a40f01a4f5369b87b629bc1a4a/app/tasks/doctor.php#L101

**Comment by eldadfux** [comment]
This is a probably a case of legacy naming, and the `cache` should probably be called `redis` or we should divide it to both `cache` and `queue`. Anyway, we use redis for both functionalities so the end result is still correct.

**Comment by TorstenDittmann** [comment]
This was improved in the past 👍🏻
