### ISSUE TITLE
Server endpoint to check for user permissions for a given resource

### ISSUE THREAD

**Issue by DiegoBM** [appwrite/appwrite#1249]
## 🚀 Feature

It would be desirable to have a server endpoint that given an user id, a  resource (document, function, etc) id, and one or a list of permissions, that returns if the user is allowed to that resource for those permissions

## Pitch

At the moment in admin mode we have more power than in client mode in terms of user access, and even though there are some requests that can match users with resources if you transfer the JWT token, there are resources that due to the lack of a client endpoint, you can't know if they are allowed for the user. For example, in my own extension backend, I'd like to show a list of functions allowed to the user that made the request, but since we only have permissions the creation of executions, there is no way to know if a user is entitled to execute a given tag before trying to execute it. This might apply to other resources. Therefore it would be desirable to have an authentication endpoint that can match user IDs with resources and permissions, so that in our own backends, while using API tokens, we can still match users with potentially requested resources.

**Comment by TorstenDittmann** [comment]
I think functions might be the only resource where this applies to 🤔 

Maybe we could allow Client Side SDK's to get all the available functions from [functionsList](https://appwrite.io/docs/server/functions?sdk=nodejs#functionsList).

This could return all the functions - where the `execute` permission agree to the user's role.

What do you think? @DiegoBM

**Comment by DiegoBM** [comment]
They might be indeed, I'm only aware of the small part of the SDK that I've needed so far.

That allowed functions list endpoint would definitely solve my specific problem. I suggested something more generic  while trying to look into the future for the things that I haven't seen yet, since that would cover all possible use cases, but always if it makes sense within the view that you guys have of the platform

That would
