### ISSUE TITLE
Import GCS bucket and CSV from Firestore

### ISSUE THREAD

**Issue by stonith404** [appwrite/appwrite#1262]
## 🚀 Feature

I started a project with Firestore. I think it would be really nice to import the Firestore Data (GCS bucket) and the User Data (CSV) to appwrite. 

## Pitch

There sould be a button to import these files like on google cloud console (there is that already possible). [Firebase export/import](https://firebase.google.com/docs/firestore/manage-data/export-import)

**Comment by eldadfux** [comment]
We do plan to have more support for data migrations in the future. For now you can check this project by one of the Appwrite community members: https://github.com/tannermeade/data-migrator
