### ISSUE TITLE
Error when creating OAuth2 session in Flutter sdk

### ISSUE THREAD

**Issue by Maatteogekko** [appwrite/appwrite#1271]
## 🐛 Bug Report

When trying to login with Google from a Flutter application I get an Exception. Creating a standard Session works without issues.

## To Reproduce
This is the app I am using (the server details are removed):
```dart
import 'package:appwrite/appwrite.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() => runApp(ProviderScope(child: MyApp()));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              ElevatedButton(
                onPressed: () async {
                  await context
                      .read(appwriteRepositoryProvider)
                      .account
                      .createOAuth2Session(provider: 'google');
                },
                child: Text('Create oAuth Session'),
              ),
              ElevatedButton(
                onPressed: () async {
                  await context
                      .read(appwriteRepositoryProvider)
                      .account
                      .createSession(email: 'test@gmail.com', password: 'testtest');
                },
                child: Text('Create Session'),
              ),
              ElevatedButton(
                onPressed: () async {
                  final response = await context.read(appwriteRepositoryProvider).account.get();
                  print(response);
                },
                child: Text('Get Account'),
              ),
              ElevatedButton(
                onPressed: () async {
                  final response = await context
                      .read(appwriteRepositoryProvider)
                      .account
                      .deleteSession(sessionId: 'current');
                  print(response);
                },
                child: Text('Delete Session'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

final appwriteRepositoryProvider = Provider<AppwriteRepository>((ref) {
  final Client client =
      Client().setEndpoint('some_address').setProject('id');
  return AppwriteRepository(Account(client));
});

class AppwriteRepository {
  final Account account;

  AppwriteRepository(this.account);
}

```
Press the "Create oAuth Session" button

## Expected behavior

I should see in the appwrite console that I logged in using my Google account.

## Actual Behavior

An exception is thrown: 

I/flutter (10213): type 'Null' is not a subtype of type 'String'
I/flutter (10213): #0      Account.createOAuth2Session.<anonymous closure>
I/flutter (10213): #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
I/flutter (10213): #2      Account.createOAuth2Session
I/flutter (10213): #3      MyApp.build.<anonymous closure>
I/flutter (10213): #4      MyApp.build.<anonymous closure>
I/flutter (10213): #5      _InkResponseState._handleTap
I/flutter (10213): #6      GestureRecognizer.invokeCallback
I/flutter (10213): #7      TapGestureRecognizer.handleTapUp
I/flutter (10213): #8      BaseTapGestureRecognizer._checkUp
I/flutter (10213): #9      BaseTapGestureRecognizer.handlePrimaryPointer
I/flutter (10213): #10     PrimaryPointerGestureRecognizer.handleEvent

## Your Environment

The Appwrite instance is already tested and should be configured correctly, since on another application which uses se same project I can create the oAuth2 session with no issues (actually something funny is going on even in the other app, but it is much bigger and hard to debug, so I isolated the issue in the other app and created this one to recreate it). Regarding the other app, the first time I signed in to appwrite with google a webview appeared to get my credentials. Subsequent times the credentials are obtained automatically and the webview is shown but it doesn't ask for anything, it disappears on its own and logs me in (as expected). In the minimal app the webview is never shown.
I am testing this on Linux in a Pixel 4 XL API 30 emulator, with appwrite 0.8 deployed on a raspberry pi behind a valid domain name. Appwrite flutter sdk is at version 0.6.2.
I added the appwrite activity inside androidManifest

**Comment by JulianBissekkou** [comment]
This might be related to https://github.com/appwrite/sdk-for-flutter/issues/23

**Comment by Maatteogekko** [comment]
Yep it works if I set `success: ""`, `failure: ""`, `scopes: []`

**Comment by lohanidamodar** [comment]
@JulianBissekkou @Maatteogekko Thank you for reporting the issue. closing this in favor of
https://github.com/appwrite/sdk-for-flutter/issues/23
