### ISSUE TITLE
.appwriteignore for Appwrite CLI (functions)

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1279]
## 🚀 Feature

`.appwriteignore` file used by Appwrite CLI while packing folder as a tag. Files and folders defined in this file will be ignored when packing.

## Have you spent some time to check if this issue has been raised before?

Yes, didn't find any records.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

Git has `.gitignore` file so developer can mark files that are not supposed to get into git repository, such as used libraries, secret passwords or temporary folders used by the application.

I would love to have the same functionality inside Appwrite CLI, so I can specify what files it should ignore when packing a folder and sending a new tag to an Appwrite server. This should be useful mostly in bigger projects, when there is an additional build process, such as Typescript in NodeJS - I want to ignore `src` folder as it will never be used by function.

**Comment by alexweininger** [comment]
Related to this, I think it's worth exploring having a general file that holds all the metadata for the Appwrite function. 

Properties in this configuration file could include:

- Start command
- Blob patterns to include or exclude (like the .ignore)
- runtime

This way functions can be easily shared, updated, etc. And the configuration can be included in the function code.

**Comment by Meldiron** [comment]
> Related to this, I think it's worth exploring having a general file that holds all the metadata for the Appwrite function.
> 
> Properties in this configuration file could include:
> 
> * Start command
> * Blob patterns to include or exclude (like the .ignore)
> * runtime
> 
> This way functions can be easily shared, updated, etc. And the configuration can be included in the function code.

Great idea! In this case, what do you think about command `appwrite function-init` that would ask few questions in CLI (just line `ng new`, for example) and generate a folder for you? The folder would include:
- appwrite.json (runtime, start command, .ignore, function name, maybe customID in future)
- package manager file for specific runtime (for example package.json or composer.json)
- build & deploy scripts prepared for specific environments (for example javac)

**Comment by alexweininger** [comment]
> 
> Great idea! In this case, what do you think about command `appwrite function-init` that would ask few questions in CLI (just line `ng new`, for example) and generate a folder for you? The folder would include:
> 
> * appwrite.json (runtime, start command, .ignore, function name, maybe customID in future)
> * package manager file for specific runtime (for example package.json or composer.json)
> * build & deploy scripts prepared for specific environments (for example javac)

That would be great! I was thinking of writing the code myself in the VS Code extension since it manages deploying Appwrite functions and such and I wanted to have commands to create/test functions for different runtimes.
