### ISSUE TITLE
[DISCUSSION] Benchmarking Solution for Appwrite

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#129]
We have a temporary solution for benchmarking the API performance using Apache AB. I want to have a better solution, maybe as part of the CI or a separate repository. Apache AB is nice but requires a lot of manual work to be be done.

Any suggestion for modern **open source** tools that can do this kind of job?

The most important thing for us is to test the API performance for every new release (or every commit?), maybe on different hardware, if possible (not a must), and have an automated flow as much as possible.

Any suggestions and insights will be greatly appreciated.

**Comment by Ishaan28malik** [comment]
I would suggest **Gatling**

https://gatling.io/

**Comment by enudler** [comment]
Hi @eldadfux 

I can recommend [Predator](https://predator.dev)
This is not a cli but a platform that needs to be installed (can run in docker)
It allows running distributed load and manages reports/webhooks/benchmarks/comparisons which is good for the long run. 
Do you have an environment where you deploy appwrite for testing after every commit/release?

If not, it probably won't be a good match, and then I recommend use [artillery](https://artillery.io)
Artillery is written in Node.js and it has cli for running tests, the downside of this is that it won't persist the reports/results for future use and this needs to be done manually.

Disclosure
* I'm one of the developers of Predator
* Predator uses artillery as its engine to create load

**Comment by eldadfux** [comment]
Currently using https://k6.io/ I'll re-open the issue if anyone has interesting suggestions.
