### ISSUE TITLE
Invalid hostname throws ugly error

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1293]
## 🐛 Bug Report

If you put your own reverse proxy in front of appwrite container without passing hostname, it throws ugly error.

## To Reproduce

1. Setup appwrite as usual
2. Expose port of appwrite container itself (so we can ignore traefik)
3. Write a configuration for reverse proxy (for example proxy_pass in nginx)

## Expected behavior

Error could be nicer.

## Actual Behavior

![image](https://user-images.githubusercontent.com/19310830/122187149-0edde380-ce8f-11eb-8504-1c1b2464b184.png)

**Comment by TorstenDittmann** [comment]
This could be related to Appwrite running in `dev`mode instead of `production`. Can you tell me your `_APP_ENV` env variable?

**Comment by eldadfux** [comment]
> This could be related to Appwrite running in `dev`mode instead of `production`. Can you tell me your `_APP_ENV` env variable?

@TorstenDittmann from my chat with @Meldiron on Discord this happens with a custom proxy that didn't properly pass the hostname
