### ISSUE TITLE
Can not create user with email that was changed or deleted

### ISSUE THREAD

**Issue by JulianBissekkou** [appwrite/appwrite#1295]
## 🐛 Bug Report

A changed user email is not available for free if the mail was changed or the user was deleted.

## Have you spent some time to check if this issue has been raised before?
Yes, this could be a duplicate of #1104 , feel free to close this issue if needed.

## Steps to reproduce
- Create a user with a mail like "tester@myapp.com"
- Update the email to "tester@myapp.de"
- Try to create a new user with the email "tester@myapp.com" (which should be free since the mail was changed)

## Expected behavior
User can be created with the previous Email

## Actual Behavior
Throws a 500

## Your Environment
Appwrite v:0.8.0.146

**Comment by JulianBissekkou** [comment]
Looks like this is fixed in #1301 . Will this be part of 0.9x?

**Comment by eldadfux** [comment]
> Looks like this is fixed in #1301 . Will this be part of 0.9x?

Yes.

**Comment by eldadfux** [comment]
This is now fixed and available as part of Appwrite 0.9:
https://dev.to/appwrite/announcing-appwrite-0-9-the-open-source-firebase-alternative-53ho 🥳 🎉
