### ISSUE TITLE
Add expire date to recovery email url

### ISSUE THREAD

**Issue by JulianBissekkou** [appwrite/appwrite#1297]
## 🚀 Feature

When appwrite generates the URL for the password recovery it would be nice to have the expire date as a parameter so that websites can show info if the link is expired.

## Have you spent some time to check if this issue has been raised before?
Yes, no other issue found!

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?
Yes sir!

## Pitch

Having the time stamp in the URL would improve UX because the website could display information about the expired link right away and the user won't get the error after submitting the new password.

**Comment by TorstenDittmann** [comment]
@eldadfux For consistency, do we also want to add this to the URL sent when `Create Email Verification` is called?

**Comment by eldadfux** [comment]
> @eldadfux For consistency, do we also want to add this to the URL sent when `Create Email Verification` is called?

Yes!!

**Comment by eldadfux** [comment]
This is new feature is now available as part of Appwrite 0.9:
https://dev.to/appwrite/announcing-appwrite-0-9-the-open-source-firebase-alternative-53ho 🥳 🎉
