### ISSUE TITLE
Support for dart? (Status inquiry)

### ISSUE THREAD

**Issue by Almoullim** [appwrite/appwrite#13]

**Comment by eldadfux** [comment]
Hi @Almoullim, support for dart in on top of our lists, if you would like to help let me know!

**Comment by Almoullim** [comment]
@eldadfux I am interested but I'm not sure how to go about using your SDK generator. I never took the time to fully learn PHP. I'd probably do it solely in Dart.

**Comment by Almoullim** [comment]
Didn't mean to close it.

**Comment by eldadfux** [comment]
If you could help and make a partial SDK implementation (implementing even just one route!), I could probably convert it to a twig template and then add it into our SDK generation process so it will be auto synced with any API changes.

Just make sure to follow or SDK generation spec checklist as listed in our sdk-generator repo:
https://github.com/appwrite/sdk-generator#sdk-checklist

I thinks it will be easier if you will try to mimic the JS or Node SDK implementation (not sure what's more similar to dart best practices). Consistency across SDKs is really important to us, as we want to create a g̶o̶o̶d̶ **amazing** and consistent developer experience.

You can reach me on our gitter community channel:
https://gitter.im/appwrite/community

**Comment by eldadfux** [comment]
OK, So just an update for does watching this issue.

@Almoullim have forked the SDK generator and started working on adding new dart templates to it.

Anyone wishing to help or give feedback on this one, can contact @Almoullim, me or join us on Appwrite gitter channel:
https://gitter.im/appwrite/community

**Comment by eldadfux** [comment]
@Almoullim would you like to keep working on the dart SDK missing features?

**Comment by Almoullim** [comment]
> @Almoullim would you like to keep working on the dart SDK missing features?

Yes, but I don't have much time so it will probably take me a while.

**Comment by eldadfux** [comment]
Closing this issue in favor of #26
