### ISSUE TITLE
Where can I change my environment variables on a DigitalOcean deploy?

### ISSUE THREAD

**Issue by wottpal** [appwrite/appwrite#1303]
Hey there,
I've deployed Appwrite via the Digital Ocean Marketplace (went smoothly) but not when I log in via SSH it displays the following:

<img width="1037" alt="Screen Shot 2021-06-18 at 13 21 20" src="https://user-images.githubusercontent.com/3930150/122555183-4046e280-d03a-11eb-9105-daa0dd315a28.png">

Where do I find those files?
And in general what are best practices for a Digital Ocean Deploy (e.g. how to restart, how to upgrade, ...). Is it all exactly the same compared to deployed manually? Couldn't find anything in the docs.

Thanks in advance!

**Comment by eldadfux** [comment]
@wottpal all the regular Appwrite best practices apply 1:1 to the DigitalOcean marketplace image. It is exactly the same setup process, but automated. You can find the Appwrite `docker-compose.yml` and `.env` files in `/root/appwrite`

**Comment by TorstenDittmann** [comment]
I am going to close this for now. If this gets relevant again, we can re-open it 👍🏻
