### ISSUE TITLE
Cloud functions can’t connect to appwrite 

### ISSUE THREAD

**Issue by Silfalion** [appwrite/appwrite#1307]
## 🐛 Bug Report

Cloud functions or running in offline mode finish with a timeout after the allocated amount of time. The functions complete normally from another computer hinting to a network problem.

## Have you spent some time to check if this issue has been raised before?

Yep

```
# general imports
import os
from datetime import datetime, timedelta

# dependencies
from appwrite.client import Client
from appwrite.services.locale import Locale

# Setup appwrite client
client = Client()
client.set_endpoint("entrypoint")
client.set_project("project_id") # this is available by default
client.set_key("key")


local = Locale(client)

local.get_continents()

```

## To Reproduce

-Write a cloud functions that calls for the list of continents through the Locale service.
-bundle it and add it as a tag in a cloud function.
-call/execute the function.

## Expected behavior

A list of continents.

(Write what you thought would happen.)

## Actual Behavior

Null.

(Write what happened. Add screenshots, if applicable.)

## Environment

ubuntu 20.04 and Linux mint 21.04.

**Comment by PineappleIOnic** [comment]
I managed to access the parent appwrite installation by using `http://127.17.0.1/v1`. I'm not sure if this is a permanent solution. Chances are we'll try and figure out a better way of dealing with this.

Please try this yourself and let me know if this works. :slightly_smiling_face:

**Comment by Silfalion** [comment]
> I managed to access the parent appwrite installation by using `http://127.17.0.1/v1`. I'm not sure if this is a permanent solution. Chances are we'll try and figure out a better way of dealing with this.
> 
> 
> 
> Please try this yourself and let me know if this works. :slightly_smiling_face: 

Hey! Thanks for the tip, sorry forgot to update the issue, turns out it was a problem with the vultr VM. I selected the pre-made docker one and it must've had some limitations, recreated a normal linux one and it worked like a charm. So the issue should be closed. Thank you again for taking the time to answer.

**Comment by PineappleIOnic** [comment]
No Problem man :+1: Any other issues you have please do not hesitate to open a Pull Request :slightly_smiling_face:
