### ISSUE TITLE
SSL Renew Error 0.8.0

### ISSUE THREAD

**Issue by thesmartrenovation** [appwrite/appwrite#1311]
I am using Appwrite version 0.8.0.

The SSL certificate expired 3 days ago and was not renewed automatically. @eldadfux  indicated that this is because I was using a custom port pair other than 80:443.

I configured the default ports but the certificate is still not renewing correctly.

Attached is the log result of docker-compose logs appwrite-worker-certificates [log.txt](https://github.com/appwrite/appwrite/files/6682690/log.txt)

**Comment by eldadfux** [comment]
Your certificate worker don't seem to be able to connect to your Redis container. Is your Redis up? Do you see any errors in your Redis container logs?

**Comment by thesmartrenovation** [comment]
> Your certificate worker don't seem to be able to connect to your Redis container. Is your Redis up? Do you see any errors in your Redis container logs?

![image](https://user-images.githubusercontent.com/57076657/122682858-7793cb80-d1c1-11eb-9fc5-e19747427cbb.png)

**Comment by thesmartrenovation** [comment]
> Your certificate worker don't seem to be able to connect to your Redis container. Is your Redis up? Do you see any errors in your Redis container logs?

Only show warnings

**Comment by thesmartrenovation** [comment]
Can someone give me a hand to reactivate my application?

**Comment by kodumbeats** [comment]
A couple of thoughts that should help:

- If any worker has issues connecting to Redis, check to make sure the Redis container is good to handle connections and restart the individual worker(s). This usually clears up those errors.
- Certbot error messages may be useful in finding the issue as well. If the `appwrite-worker-certificates` logs indicate the same:
    ```bash
    # shell into the container
    docker-compose exec appwrite-worker-certificates sh
    # Navigate to the default log folder and see what's inside
    cd /var/log/letsencrypt && ls
    # View the log
    less /var/log/letsencrypt/file
    ```
- Lastly, if the renewal still doesn't work, you can remove the `appwrite-certificates` volume and restart the stack, getting a new certificate instead of renewing the old one.

If it helps, here's a link to our debugging guide which may help you navigate around Appwrite to find what you need:
https://appwrite.io/docs/debugging

**Comment by thesmartrenovation** [comment]
> ```shell
> letsencrypt && ls
> ```

When i try to run this `cd /var/log/letsencrypt && ls `  i get  `sh: cd: can't cd to /var/log/letsencrypt: No such file or directory` 

How can I delete the `appwrite-certificates` volume and get a new one without losing my data?

**Comment by thesmartrenovation** [comment]
I fixed with this:

# shell into the mariadb container
$ docker-compose exec mariadb sh

# authenticate with mysql
# do not add whitespace between -p and password
$ mysql -u root -p"$MYSQL_ROOT_PASSWORD"

# use the appwrite database
> use appwrite;

# Find the documentID for your domain in the database:
> SELECT * FROM `app_console.database.properties` p where p.key = "domain";

# note the documentUid - that's what we'll use to query/delete them from the database
# We'll need to remove the document from two tables, here's the other one
> SELECT * FROM `app_console.database.documents` d where d.uid = "thedocumentUID";

# Now we can delete these two rows:
> DELETE FROM `app_console.database.properties` where documentUid = "thedocumentUID";
> DELETE FROM `app_console.database.documents` where uid = "thedocumentUID";
