### ISSUE TITLE
Listening for changes to the current user/session state (Client-side)

### ISSUE THREAD

**Issue by daryllukas** [appwrite/appwrite#1312]
## 🚀 Client-side Auth State Listener

How would one go about implementing an observer that listens for changes to the user's authentication state? Similar to Firebase's [onAuthStateChanged method](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onauthstatechanged)

## Pitch

I am trying to create a React HOC which will be used on components that need to be protected with authentication/authorization. However, I'm not sure how to go about implementing an observer that will listen for changes in auth state. Something like this:

```
const withAuthorization = condition => Component => {
  class WithAuthorization extends React.Component {
    componentDidMount() {
      this.listener = this.props.appwrite.account.onAuthStateChanged(
        authUser => {
          if (!authUser) {
            this.props.history.push(ROUTES.SIGN_IN);
          }
        },
      );
    }
 
    ...
 
    render() {
      return (
        <Component {...this.props} />
      );
    }
  }
 };
```

**Comment by TorstenDittmann** [comment]
With the Realtime feature that we are current working on here #948 will let you do this 👍🏻 

Gonna close this issue in favor of the realtime feature 🙂 

PS: You can test out the realtime feature already [here](https://www.notion.so/Appwrite-Realtime-Sneak-Peek-c4ea0dd20d184701abe06389fc2aea01).
