### ISSUE TITLE
Functions Packaging issue

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1316]
## 🐛 Bug Report

https://github.com/appwrite/appwrite/blob/master/app/workers/functions.php#L426
The `--strip 1` argument when we unpack a tar file uploaded to a tag causes the leading component in the archive path to be removed when unpacking. 

By having `--strip 1` we are making a false assumption that the code files are always present 1 directory deep in the archive like 
`directory/index.js` which is not always true. 

The user could have created an archive from the current directory itself like so 
`tar -zcvf code.tar.gz .` in which case, the archive contains `index.js` in the root of the archive. 

This is a perfect answer that explains this scenario
https://unix.stackexchange.com/questions/535772/what-does-strip-components-c-mean-in-tar

## Have you spent some time to check if this issue has been raised before?
A similar issue has been raised here with more information on steps to reproduce
https://github.com/appwrite/appwrite/issues/1228

## To Reproduce
Explained in the above issue

## Expected behavior
Explained in the above issue

## Actual Behavior
Explained in the above issue

## Your Environment
Explained in the above issue

**Comment by TorstenDittmann** [comment]
This should be solved now with the new functions service 👍🏻
