### ISSUE TITLE
endpoint "/v1/account" and "/v1/account/sessions"

### ISSUE THREAD

**Issue by MsalekM** [appwrite/appwrite#1329]
## 🐛 Bug Report
first :

i have used the endpoint **/v1/account** to create session is wrong.
the result is a new user in the dashboard ==> users.  with no name.
normaly this action can return error !

second :
dashboard ==> users no way to get user page. 
need to remove from html the span **style="visibility: hidden; display: none;"** .

**Comment by eldadfux** [comment]
What was your exact request to `POST /v1/account`? as mentioned on Discord, the empty name bug on the console was fixed here: #1220

**Comment by MsalekM** [comment]
the request is **createSession()** with **POST /v1/account.** need to be with **POST /v1/account/sessions**
I think this point should be locked, createSession() must not create a user !

```
newsession2(String email, String password) async {
  Client client = Client();
  Account users = Account(client);
  client
      .setEndpoint('${Constants.api}/v1/account')
      .setProject("${Constants.projectId}");

  try {
    final response =
        await users.createSession(email: email, password: password);

    print(response.data);
  } on AppwriteException catch (e) {
    print('=====> Eroor');
    print(e.message);
  }
}
```

**Comment by eldadfux** [comment]
Yeh, `createSession` should not create an account, I'm just not sure how you got into this situation. This method translate to: `POST  /v1/account/sessions`

**Comment by TorstenDittmann** [comment]
Gonna close this issue, since it doesn't look like a bug. If you still having troubles, we can re-open this issue 👍🏻
