### ISSUE TITLE
Execution Objects: truncated field length is difficult to configure

### ISSUE THREAD

**Issue by mlucas-NU** [appwrite/appwrite#1334]
## 🚀 Feature

Add a way for developers to configure the truncation length for text fields in the Execution Object (specifically `stdout` and `stderr`).

## Have you spent some time to check if this issue has been raised before?

Yes, and I discussed this briefly with Eldad on Discord.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

## Pitch

Function endpoints respond with an [Execution Object](https://appwrite.io/docs/models/execution). The object's `stdout` and `stderr` fields are truncated to 4000 characters by default, but these values can only be adjusted by modifying the appwrite source.

Is it possible to provide a way for developers to configure this value?

Relevant Code Locations:
* https://github.com/appwrite/appwrite/blob/0d2a4f0cbfc17f9b1e4c431b078a19ac31bb1eaa/app/workers/functions.php#L471-L472

**Comment by PineappleIOnic** [comment]
Update: We are now looking at adding a new environment variable to allow you to configure this variable :+1:

**Comment by mlucas-NU** [comment]
A colleague of mine reminded me of an additional solution that might help functions return huge payloads. When sharing huge files between AWS compute instances, he had the sender upload the file to S3 and only send a signed URL to the receiver. This way, he didn't have to scale up his services to handle all of the transfer bandwidth and maintain long-running connections (these files were generally many gigabytes in size).

In Appwrite terms, a could Function save a huge payload as a file in the Storage service and then share a URL to the file to the calling client. The client could then retrieve the file from Storage when they're ready to use it.

Given that this could fill the Storage service with files that are only used once, I wonder if the function response could include an expiration datetime along with the Storage URL and then schedule a Function to delete the file at that expiration datetime.

**Comment by TorstenDittmann** [comment]
This should be solved now with the new Functions service 👍🏻

**Comment by arcanechimp** [comment]
Is this env variable mentioned in PR #1336 still going to be added?

I would like to use this as a way to access data from a seperate cache and database whilst using Appwrite's authentication, and being able to change the max value would be very helpful to achieving this.
