### ISSUE TITLE
Appwrite SMTP disabled

### ISSUE THREAD

**Issue by LucatonyRaudales** [appwrite/appwrite#1338]
Hello, I have a severe problem.
I have configured the smtp according to this article https://dev.to/appwrite/30daysofappwrite-getting-started-with-smtp-1e2e

I have done it with sendgrid but when I run "appwrite doctor" I keep getting "smtp disabled"
Any idea what happens?
<img width="451" alt="Captura de Pantalla 2021-06-30 a la(s) 16 49 49" src="https://user-images.githubusercontent.com/51138379/124040958-2fe02180-d9c3-11eb-9572-33bb86969801.png">

**Comment by kerrongordon** [comment]
I was having the same problem but this help me out [#880](https://github.com/appwrite/appwrite/issues/880#issuecomment-774510467)

**Comment by eldadfux** [comment]
You can run `docker-compose exec appwrite vars` to make sure your SMTP setting are configured properly. If not, recreating your Appwrite containers can help.

**Comment by LucatonyRaudales** [comment]
I put the data directly into the docker-compose.
apparently couldn't read the data from the .env
