### ISSUE TITLE
Add option to list users by ids

### ISSUE THREAD

**Issue by JulianBissekkou** [appwrite/appwrite#1351]
## 🚀 Feature

As consumer of the server side api, I would like to fetch multiple users with many ids.

## Have you spent some time to check if this issue has been raised before?

Yes.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

## Pitch

As someone who integrated appwrite into another system, I would like to fetch the information of multiple users. For example, we have another system that has a user table that is linked to the users of the appwrite system. If we want to go through all emails of our users, it would be good to have the option to pass a list of IDs to `/v1/users`.

**Comment by eldadfux** [comment]
This might be possible with the new filters mechanism being worked on here: https://github.com/appwrite/rfc/pull/21.

The only thing I'm not sure will work for this use-case is a limit we intend to impose on the number of possible values for each filter (currently 10-15 values per filter).

An example of how this might look:

`id.equal('x', 'y', 'z'...)`

**Comment by JulianBissekkou** [comment]
This would be an improvement, but not a solution that would work for most of our use cases. I think it makes sense to just sync all necessary fields of the user with our database even though this always feels like a little workaround.

But since you guys provide all needed webhooks this should not be a problem 👍🏽

**Comment by TorstenDittmann** [comment]
This should be possible now with the new Database service 👍🏻
