### ISSUE TITLE
Can not search with @ sign in /v1/users

### ISSUE THREAD

**Issue by stefanschaller** [appwrite/appwrite#1352]
## 🐛 Bug Report

It's currently not working to search in this request: 

https://appwrite.io/docs/server/users#usersList

including a @-char since the Appwrite API returns a 500.

The URL for the request looks like: 

https://development.appwrite.tapped.dev/v1/users?limit=25&offset=0&search=surname.lastname%40test.de

So the URL encoding seems to be correct. 

## Have you spent some time to check if this issue has been raised before?

I didn't find any open issue. 

## To Reproduce

- Make a request like described here: https://appwrite.io/docs/server/users#usersList
- Add the search parameter including a @-char

## Expected behavior

Search should work including a @ char 

## Actual Behavior

Throws a 500.

## Your Environment

Appwrite v:0.8.0.146

______________________

Out workaround looks like:

`parameter("search", searchQuery?.replace("@", ""))`

**Comment by TorstenDittmann** [comment]
> InnoDB full-text search does not support the use of the @ symbol in boolean full-text searches. The @ symbol is reserved for use by the @distance proximity search operator.

https://dev.mysql.com/doc/refman/5.7/en/fulltext-boolean.html

Looks like a bug that we don't handle `@` chars properly. This is already fixed in the db refactoring and can be prevented with surrounding the search term with `"` double quotes like `"surname.lastname@test.de"`.

**Comment by eldadfux** [comment]
This issue was fixed and its now available as part of Appwrite 0.12. You can learn more about the new version here: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
