### ISSUE TITLE
Question on the Multi-language Support For the Dashboard

### ISSUE THREAD

**Issue by pkmq24** [appwrite/appwrite#1353]
Is there a plan for support of multi-languge for the dashboard?
If the code is ready and it's waiting for translation, I'm glad to offer some help for it.

**Comment by eldadfux** [comment]
This is something we have started to discuss lately. I'll keep this issue posted when we can get it moving.

**Comment by joeyouss** [comment]
Closing this as of now, we will re-open this if we start working on this 😁
