### ISSUE TITLE
misleading error message while trying to connect to collection without permission

### ISSUE THREAD

**Issue by fetnimohamed** [appwrite/appwrite#1355]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

## Have you spent some time to check if this issue has been raised before?

(Have you googled for a similar issue or checked our older issues for a similar bug)

## To Reproduce

(Write your steps here:)

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

(Write Environment, Operating system and version etc.)

**Comment by fetnimohamed** [comment]
while try to a collection without having the permission i get as error message "{"message":"Collection not found","code":404,"version":"0.7.0"}" which mislead me to think that i have a problem with the collection id . shouldn't the error message be more informative of the error ??

**Comment by eldadfux** [comment]
The original idea behind the 404 was to prevent attackers from trying to scan your collections list. I don't think it's crucial and we can consider converting the 404 error with 401.

I would love to get more community feedback before we tackle this issue.

**Comment by fetnimohamed** [comment]
the problem is in the error message it could be more informative in the case of not having the permmission to write in a collection the error message when trying to create a new document inthe collection should be "acsses to collection is denied "  (for exemple ) instead of "collection not found"  

thank you for your consideration
