### ISSUE TITLE
SSL Certificate expired and not renew automatically

### ISSUE THREAD

**Issue by Asored-D** [appwrite/appwrite#1361]
## 🐛 Bug Report

Hi, there, my Appwrite installation is not reachable actually because of expiration of the certificate.
Restarting the API container with `docker-compose restart appwrite` does not solve the issue. Also upgrading to the newest version 0.8.0 (from 0.7.*) does not renew the certificate.

What could I do to save my project? :-)

## Have you spent some time to check if this issue has been raised before?

Yes, but without success.

## Expected behavior

I think that the expected behavior is that certificates automatically renews after expiration.

## Your Environment

Debian GNU/Linux Environment (SMP Debian 4.19.181-1 (2021-03-19) x86_64)
Appwrite Version: 0.8.0

**Comment by TorstenDittmann** [comment]
Can you share the logs of `docker-compose logs appwrite-worker-certificates`? 🙂

**Comment by Asored-D** [comment]
Sure:

`
root@v2202104145197148388:~/takepart/appwrite# docker-compose logs appwrite-worker-certificates
Attaching to appwrite-worker-certificates
appwrite-worker-certificates    | Appwrite certificates worker v1 has started
appwrite-worker-certificates    | [notice] Starting worker bd361c794216:7:v1-certificates
`

**Comment by TorstenDittmann** [comment]
> Sure:
> 
> ```
> root@v2202104145197148388:~/takepart/appwrite# docker-compose logs appwrite-worker-certificates
> Attaching to appwrite-worker-certificates
> appwrite-worker-certificates    | Appwrite certificates worker v1 has started
> appwrite-worker-certificates    | [notice] Starting worker bd361c794216:7:v1-certificates
> ```

Oh okay, so there are no logs at all 🙃 

When you restart the `appwrite` container, are there any logs in the `appwrite` container related to certificates?

BTW: If this is an urgent problem, feel free to hop on our [Discord](https://appwrite.io/discord) where we can live debug it 👍🏻

**Comment by TorstenDittmann** [comment]
You can also force generating a domain for Appwrite - with adding it as a custom Domain to a project.

**Comment by Asored-D** [comment]
Nope, also after restarting the container the log shows the same as before.
By the way: Also adding a new custom domain does not solves the issue.

I will join later to your discord channel.

Thanks by the way for your assistance :)

**Comment by TorstenDittmann** [comment]
Looks like the renewal had a hiccup.

We solved it by hard restarting the appwrite stack with `docker-compose up -d && docker-compose up -d` and forcing the renewal of the domain configuren in the `.env` file with `docker-compose exec appwrite ssl`.

This issue will very likely be fixed with #1060 so I will close this in favor of the PR 👍🏻
