### ISSUE TITLE
Firebase like Anonymous Login

### ISSUE THREAD

**Issue by MaddinMade** [appwrite/appwrite#1372]
## 🚀 Feature

As I understood the Anonymous Login, an account created with it is valid only for the current session. Is there a way to use an anonymous login like in Firebase or would I have to improvise? Or have I completely misunderstood the current implementation of Anonymous Login (in this case, I'm sorry)? 

## Have you spent some time to check if this issue has been raised before?

I've found no similar issue on GitHub.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes :)

## Pitch
Such a feature could be implemented by always logging in with a token that you get when you register and securely store locally on your device.
With such a login method, you could completely dispense with other login methods and would not need a login screen in an app. Nevertheless, every user could use the app to its full extent as long as he has the same device without his data being "deleted".

**Comment by TorstenDittmann** [comment]
Hey 👋🏻 

basically an Anonymous Account in Appwrite is a normal account, just without and e-mail or password. So when you create a session with it, you can actually use everything as long as the same device/session is used. So you have a user id & co for an anonymous user.

How is the implementation different to Firebase? 🙂

**Comment by MaddinMade** [comment]
Hey :)
Ah ok, then I misunderstood the point of the sessions. I thought they were only valid for a limited time. I apologize for the unnecessary request. I have not been able to test AppWrite yet and must have misunderstood the docs. Thanks for the clarification :)
Ah ok, then I misunderstood the point of the sessions. I thought they were only valid for a limited time. I apologize for the unnecessary request. I have not been able to test AppWrite yet and must have misunderstood the docs.
