### ISSUE TITLE
All runtimes displayed on web UI despite default runtimes not including all runtimes

### ISSUE THREAD

**Issue by GryPr** [appwrite/appwrite#1376]
## 🐛 Bug Report

The web UI will display all runtimes if the _APP_FUNCTIONS_RUNTIMES variable is blank. However, the default value of _APP_FUNCTIONS_RUNTIMES does not include all the runtimes (only a subset). This leads to unexpected behavior when a runtime that isn't part of the default values is used.

## To Reproduce

1.  Set the environment variable _APP_FUNCTIONS_RUNTIMES as blank in the docker-compose environment variables
2. Access the web UI, and create a new function
3. All the runtimes will be displayed instead of just the default runtimes listed here: [https://github.com/appwrite/appwrite/blob/48272e8e5000f40096c873961d06290ae55c2af0/app/config/variables.php#L451](link)

## Expected behavior

To only show the available runtimes when creating a cloud function in the web UI

## Actual Behavior

Currently, it shows every possible runtimes.

![image](https://user-images.githubusercontent.com/51273366/125175449-3710e780-e19a-11eb-9739-8f967f18122a.png)

If the "wrong" runtime is selected and is run, then the function will get stuck, and the docker logs will display the following:

![image](https://user-images.githubusercontent.com/51273366/125175465-6162a500-e19a-11eb-99ec-b5b899bef01e.png)

## Your Environment

v:0.9.0.149 run through docker-compose.yml

**Comment by PineappleIOnic** [comment]
I'm going to start looking into this now. :+1:

**Comment by eldadfux** [comment]
This is now fixed in Appwrite 0.13.
