### ISSUE TITLE
Custom duration of a session

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [appwrite/appwrite#1379]
## 🚀 Feature

It would be awesome if we were able to change the duration of a session on creation. Would add just an optional parameter to the account.createSession function which would be a duration in seconds maybe?

## Have you spent some time to check if this issue has been raised before?

Yes, I did check :) Also @eldadfux told me it would be good to post it here :)

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

In my specific case it would be great for testing purposes, since my app stores the session also in the shared preferences, to reduce the server stress. Setting the expiration of the session would be nice for me to check if my code works and log-outs the user after a certein amount of time.
Another good example would be a banking app, or anything similarly secure, which would have to have shorter session durations.

**Comment by Meldiron** [comment]
If I am not mistaken, we are talking about these 2 values: https://github.com/appwrite/appwrite/blob/f070eb0a3a7a1b3a3b2d60b4c0906d11ef071900/src/Appwrite/Auth/Auth.php#L45-L46

Discussion topic: What would be the best way to implement this customisation?
- ENV variable above the whole Appwrite?
- Setting for every project specifically?
- Configurable when creating a session?

Do we need/want multiple configurations for multiple lengths?

**Comment by dawid-niedzwiecki** [comment]
> If I am not mistaken, we are talking about these 2 values:
> 
> https://github.com/appwrite/appwrite/blob/f070eb0a3a7a1b3a3b2d60b4c0906d11ef071900/src/Appwrite/Auth/Auth.php#L45-L46
> 
> Discussion topic: What would be the best way to implement this customisation?
> 
> * ENV variable above the whole Appwrite?
> * Setting for every project specifically?
> * Configurable when creating a session?
> 
> Do we need/want multiple configurations for multiple lengths?

Oh I think it would be desirable to have control over the duration of the session. It would be great if you could configure the duration of the session when creating it with a default value (that is also configurable in the project) if the parameter is not set. I personally prefer to have more control over something than less.

**Comment by chonsser** [comment]
I agree with @dawid-niedzwiecki – more controls in the session duration would be great.

**Comment by Meldiron** [comment]
The `TOKEN_EXPIRATION_LOGIN_SHORT` is not being used anywhere, that makes things simpler...

`TOKEN_EXPIRATION_LOGIN_LONG` is used at:
- Updating team membership status - I don't think we need to control this duration, default 1year should be fine here:
https://github.com/appwrite/appwrite/blob/a93496bc8c334033eeb609695f6b546ebaf560b8/app/controllers/api/teams.php#L673

- Creating a session - this one is why even need it:
https://github.com/appwrite/appwrite/blob/1186c6a36f495ff292dbd4474f8c1162f90e1552/app/controllers/api/account.php#L204

- Create OAuth session - needs to be implemented as much as a normal session:
https://github.com/appwrite/appwrite/blob/1186c6a36f495ff292dbd4474f8c1162f90e1552/app/controllers/api/account.php#L545

- Create an anonymous session:
https://github.com/appwrite/appwrite/blob/1186c6a36f495ff292dbd4474f8c1162f90e1552/app/controllers/api/account.php#L708

Soo all we need is to add a new parameter to all of these that will be optional and will hold the duration of a session (in seconds?). The problematic one in my opinion is OAuth as this is probably after a redirect so there is some complexity added to move this parameter from place to place.

**Comment by eldadfux** [comment]
I fear that exposing this option to the client API might lead to abuse from users. I'm not sure in which use case the user should have control over the session.

Allowing this on a project level seems to me like the best balance between flexibly and convenience.

Allowing this on the env level as a default option might be good for some use-cases. I don't see it as critical if this is available on the project level.

**Comment by Meldiron** [comment]
Would it be possible to achieve multiple durations? For example "Login" should be 1 month, but "Login with remember me" should be 1 year.

**Comment by stnguyen90** [comment]
@dawid-niedzwiecki as of [1.1.0](https://github.com/appwrite/appwrite/releases/tag/1.1.0), It is now possible to configure the session in the auth settings of your project. As such, can this be closed now?

**Comment by dawid-niedzwiecki** [comment]
> @dawid-niedzwiecki as of [1.1.0](https://github.com/appwrite/appwrite/releases/tag/1.1.0), It is now possible to configure the session in the auth settings of your project. As such, can this be closed now?

Yes, I love appwrite! Thanks!!!
