### ISSUE TITLE
The only member leaves an project there is no warning popup and the project still exists.

### ISSUE THREAD

**Issue by stonith404** [appwrite/appwrite#1382]
## 🐛 Bug Report
When I'm the only member of a project and I leave, then I loose the permission to the project, but the project still exists.

 I have two suggestions:

1. Create a popup that warns, that you loose the permission forever, when you click on the "leave" button.
2. When only one member is in a project, and the member leaves, then it makes more sense when the project will be deleted. I mean why should there exist a project, where nobody has access to it.

## Have you spent some time to check if this issue has been raised before?

yes, there is no similar issue

## To Reproduce

When I'm the only member of a project and I leave, then I loose the permission to the project, but the project still exists.

## Expected behavior

Get an error or delete the project (like my suggestions above).

## Actual Behavior

When the only member leaves, the project still exists but nobody has access to it. Also there should be a warning pop up. 

## Your Environment

Raspberry Pi 4, Raspberry Pi OS Lite.

**Comment by lohanidamodar** [comment]
@stonith404 Thank you for notifying the issue. We will look into it and get back soon.
