### ISSUE TITLE
Document Permissions Team Role does not seem to work

### ISSUE THREAD

**Issue by TheMardy** [appwrite/appwrite#1389]
## 🐛 Bug Report

The role parameter of a permissions entry does not seem to work when trying to retrieve a document.
(I have not tested if the problem also exists for write access)

## Have you spent some time to check if this issue has been raised before?

Yes, Issues, Google and Discord.

## To Reproduce

User A (member of the team) creates a document like this:
`let promise = sdk.database.createDocument(
    '[COLLECTION_ID]',
    {'actorName': 'Chris Evans', 'height': 183},
    ['user:5c1f88b42259e', 'team:5c1f88b87435e/owner'],
    ['user:5c1f88b42259e']);`

User B (with owner role in the team) tries to retrieve all entries, but the one created by user A does not show up.
When user A creates a document without the "/owner" part, the entry does show up for user B.

## Expected behavior

User B would be able to read the document, and unable to write the document.
User A would be able to read and write.
![image](https://user-images.githubusercontent.com/36103454/125423192-eff536c3-7deb-4b9d-918f-a2ac0028796e.png)

## Actual Behavior

User A is able to read and write 
User B is unable to read and write

## Your Environment

Appwrite V0.9.0, Cleanly installed
1CPU, 2GB RAM, 20GB Storage
Production environment

**Comment by s3ppo** [comment]
i have the same issue

**Comment by aggmoulik** [comment]
How can I reproduces this issue, can someone help me so that I can work on the issue ?

**Comment by stnguyen90** [comment]
I believe this should be fixed by the db refactor (at least using collection level permissions).

**Comment by stnguyen90** [comment]
@PineappleIOnic, should this be added to the [DB Refactor project](https://github.com/appwrite/appwrite/projects/13)?

**Comment by TheMardy** [comment]
Closing this issue as it is fixed in 0.12 :)
