### ISSUE TITLE
JWT verification on custom backend

### ISSUE THREAD

**Issue by JakubNeukirch** [appwrite/appwrite#1391]
## 🚀 Feature

Ability to verify appwrite JWT token on custom backend.

## Have you spent some time to check if this issue has been raised before?

I discussed it on discord and I was suggested to post this as issue.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

Custom backend can't verify JWT to check if it is not prepared by malicious person. If it will be added, custom backend will be able to be fully authorized with appwrite.
 It could work similar to [AWS cognito with file jwks.json](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html). For now only reliable way of verifying JWT is by invoking some method from appwrite.

**Comment by eldadfux** [comment]
Right now we're using the instance secret key to generate all JWTs (_APP_OPENSSL_KEY_V1). We should move to a key per project approach, and probably also allow access to it from the console. Using this approach you could use this key to decode the JWT anywhere you'd like.

**Comment by eldadfux** [comment]
Update 15-01-2022

Allowing to access and customize the JWT key per project is expected to land before the 1.0 release.

**Comment by stnguyen90** [comment]
> Update 15-01-2022
> 
> Allowing to access and customize the JWT key per project is expected to land before the 1.0 release.

Does that include being able to use keypair instead of secret?

Reference on JWKS: https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-key-sets

**Comment by eldadfux** [comment]
Closing in favor of https://github.com/appwrite/appwrite/issues/1112
