### ISSUE TITLE
UI for Function creation does not update supported langs

### ISSUE THREAD

**Issue by Solido** [appwrite/appwrite#1392]
## 🐛 Bug Report

Updated .env to remove php, ruby, python and add dart

```
docker-compose exec appwrite env | grep -i "runtimes"
_APP_FUNCTIONS_RUNTIMES=node-16.0,dart-2.13,java-16.0
```

Creating function from the UI did not update the supported langs even after docker compose down

## Expected behavior

Can create a function using Dart

## Actual Behavior

The env list does not display corresponding configuration
Dart is not available
Removed envs are still available

## Your Environment

Windows 10 up to date
Docker compose from user dir and modified .env after first start.

**Comment by eldadfux** [comment]
Try to clean your browser cache and check if this issue persists.

**Comment by Meldiron** [comment]
.env:
```
_APP_FUNCTIONS_RUNTIMES=node-16.0
```

`docker-compose exec appwrite env | grep -i "runtimes"`:
```
_APP_FUNCTIONS_RUNTIMES=node-16.0
```

Latest master, fully wiped appwrite (`docker-compose down -v`) and rebuilt from sources (`docker-compose up -d --build --force-recreate`).

Steps to reproduce:

- I register an account
- I create a project
- I enter functions page
- I try to create new function, see this list:
![image](https://user-images.githubusercontent.com/19310830/125840392-2f5c4f9b-59d1-48e6-9fb4-7b4f69e0d977.png)

- I refresh the page
- I try to create new function and see this list (empty):
![image](https://user-images.githubusercontent.com/19310830/125840408-daef8598-0b17-4b7c-a4ec-701c1381a788.png)

Probably related to https://github.com/appwrite/appwrite/issues/1376

**Comment by Meldiron** [comment]
> Try to clean your browser cache and check if this issue persists.

So, I have 2 chrome windows opened. The first one is what I use, the second one is incognito.

In the one I use normally, when I do:
- Go to `http://localhost/console/home?project=60f080cb7cb98` (home of the project)
- Refresh
- Switch to functions, click the button
I can see a full list of default environments
If I then refresh on this functions page, the list is now empty

If I do the same in incognito, it is always empty.. I never get the default list. Same for firefox and firefox incognito.

---

Removing all cookies, session storage and clearing site data including third-party cookies did not change behaviour.

**Comment by eldadfux** [comment]
@Meldiron are you still facing this issue in latest versions?

**Comment by TorstenDittmann** [comment]
This should be fixed by now 👍🏻
