### ISSUE TITLE
Event_data  for 'event.document.create' when creating child document for parent contains whole parent 

### ISSUE THREAD

**Issue by Miksier** [appwrite/appwrite#1397]
Hello

So lately Im playing with functions, I've stumbled on a problem:

When creating a child document for a parent the 'APPWRITE_FUNCTION_EVENT_DATA' contains the parent document so we have no way to know what actually was created or added to this parent. 

## Have you spent some time to check if this issue has been raised before?

Yup, didnt find anything for this. But I may be blind.

## To Reproduce

Create a documents schema like
profile
{
items: document[]
notifications:  document[]
}
item{whatever}
notification{whatever}

we need cloud function with trigger 'event.document.create'. In function we print to stdout env.var(APPWRITE_FUNCTION_EVENT_DATA). 

now in client code 
db.Create(itemsCollectionId,itemJson,parentDocument: profileId,parentProperty: "items",parentPropertyType: 'append')

check function output

## Expected behavior

I created an "item document" so I'd expect to see and item document json. Maybe a "parent id" somewhere but whatever.

## Actual Behavior

The data outputted is a parent document. Now, what was added to it? No idea if this was item or notification. I only get trigger/event names that it was a 'create'.

## Your Environment

Appwrite 0.8.0

**Comment by TorstenDittmann** [comment]
We are currently refactoring our Database and this will be fixed in one way or another with the next version 👍🏻

**Comment by eldadfux** [comment]
Since version 0.12 nested document support has been dropped. We'll investigate new ways to achieve the similar behavior.
