### ISSUE TITLE
[bug] Project UID Copy to clipboard button is empty

### ISSUE THREAD

**Issue by BogDAAAMN** [appwrite/appwrite#14]
**Description**

Under a project settings, the button that is supposed to copy the Project UID is not working. After pressing it I get an empty string on paste.

**Reproduce**

1. Go to a project settings page
2. Click on _Copy to clipboard_ button

**Desktop**

- OS: MacOS Mojave 10.14
- Browser: Firefox 7.0.2 (64-bit)

**Comment by eldadfux** [comment]
@BogDAAAMN Thanks for the bug report! A fix has been committed to the master branch and will be release in next version.
