### ISSUE TITLE
Ability to change minimum and maximum character limit for a users password

### ISSUE THREAD

**Issue by Emiliaaah** [appwrite/appwrite#1402]
## 🚀 Feature

Some way to change the minimum and maximum character limit.

## Have you spent some time to check if this issue has been raised before?

Yes, I couldn't find any issues mentioning this.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

I personally use a password manager and would like to use password with 128 characters.
Like why use less characters if you don't have to?
I was talking to Meldiron#1111 on discord he also came with the idea of changing the minimum character amount to for example 10 instead of 6 this would improve security dramatically since 6 characters is kind of low.

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
