### ISSUE TITLE
Teams membership parameters

### ISSUE THREAD

**Issue by thesmartrenovation** [appwrite/appwrite#1409]
In the documentation in the Create Team Membership method here: 

https://appwrite.io/docs/client/teams?sdk=web-default#teamsCreateMembership

The name parameter should be at the end of the request and not next to the email parameter.

![image](https://user-images.githubusercontent.com/57076657/126203673-4ff52a35-cdc6-4d8a-831c-7de77912c6ce.png)

**Comment by TorstenDittmann** [comment]
This can be enhanced for sure 👍🏻

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**
