### ISSUE TITLE
Create Membership - Bug

### ISSUE THREAD

**Issue by reyesmfabian** [appwrite/appwrite#1410]
When creating an invitation to a team, the name parameter is not sent along with the invitation, as a result the email template displays a "Hi{{name}}" field instead of the user's name. This field is also not sent as a parameter in the url to be used in the invitation acceptance page, only these parameters are sent: ?membershipId=&teamId=&userId=&secret= the name parameter is not sent with the url.

![image](https://user-images.githubusercontent.com/57076657/126204675-cb5e660e-5eaa-4baf-9b62-45fe1399d690.png)

**Comment by TorstenDittmann** [comment]
Can you check if the name of the team member was set?

**Comment by generalxhd** [comment]
Maybe it's because the user don't have a name (only a email)?

**Comment by TorstenDittmann** [comment]
This got fixed already in the past 👍🏻
