### ISSUE TITLE
501 error not documented on the Error Codes page in the docs

### ISSUE THREAD

**Issue by Fabian9799** [appwrite/appwrite#1424]
## 📚 Documentation

When trying to create a new user even tho the "Max Allowed Users" value is set to 1 (or any number which the new user would surpass) the console gives a 501 error which is not documented on https://appwrite.io/docs/error-codes

The full error message is:
`
code: 501
message: "Project registration is restricted. Contact your administrator for more information."
version: "0.9.2"
`

Its probably not an error that happens for many users but i think it should be documented

## Have you spent some time to check if this issue has been raised before?

Yes. There is not issue that mentions the error code 501

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

**Comment by eldadfux** [comment]
Created a fix here: https://github.com/appwrite/docs/pull/51
