### ISSUE TITLE
Improve sign in with apple docs

### ISSUE THREAD

**Issue by JulianBissekkou** [appwrite/appwrite#1429]
## 📚 Documentation

The Sign-in with apple documentation is not updated. 
I would suggest the following changes to improve this.

- [ ] Mention the redirect configuration that needs to be done. (Configuration to capture the Appwrite OAuth callback) Most people will skip this when they first set up the app because they might not need oAuth in the beginning, but when they do it would be nice to find this information in the oAuth docs again.
- [ ] Provide a step-by-step tutorial for all the configurations done on developer.apple.com
- [ ] Update the information about the Bundle ID and say that this is the "Client Id" which might be different then the bundle id.

## Have you spent some time to check if this issue has been raised before?

Yes.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

**Comment by JulianBissekkou** [comment]
Here is a screenshot of the last point. I think we can improve the information in that tooltip:
<img width="679" alt="Screenshot 2021-07-26 at 14 36 15" src="https://user-images.githubusercontent.com/36447137/126989984-a8ea732c-361e-4dd7-9ef3-2b77834508a6.png">

**Comment by stnguyen90** [comment]
We now have [this](https://dev.to/appwrite/apple-sign-in-with-appwrite-2576) article that can be used as reference for apple sign in.
