### ISSUE TITLE
Request limit is not scoped to one device

### ISSUE THREAD

**Issue by JulianBissekkou** [appwrite/appwrite#1432]
## Have you spent some time to check if this issue has been raised before?

#1085 might be related to this.

## To Reproduce

Run into the limit on the jwt endpoint and then user another device and try to get a jwt token.

## Expected behavior

Other devices are able to get a jwt.

(Write what you thought would happen.)

## Actual Behavior

other devices can't get a jwt because of the limit.

## Your Environment

Appwrite v:0.9.1.149

**Comment by eldadfux** [comment]
This was a bug in the abuse unique key setting for the JWT endpoint. It was fixed in Appwrite 0.9.3
