### ISSUE TITLE
CreatedBy in database items

### ISSUE THREAD

**Issue by benkaiser** [appwrite/appwrite#1441]
## 🚀 Feature

I want to try and show a logged in user a set of documents that they created, however the only was I can do this today is by letting the user pass in their id as part of document creation. Because this is client-provided, another malicious user could set the id to that of other users on the site.

Would be great if we could set this on the backend so we can ensure it's authenticity.

## Have you spent some time to check if this issue has been raised before?

Yes, did a search on the github issues.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

Useful for showing users a set of documents they created.

**Comment by eldadfux** [comment]
You can actually limit this user to only see documents he has read permissions for. A user can add a permission for read or write only if he owns that permission (for example his user ID), this will allow you to avoid any abuse.

**Comment by benkaiser** [comment]
Hey @eldadfux , what would a query like this look like for write perms? (I have the documents set to have read by everyone)

**Comment by eldadfux** [comment]
If you'll set the read permissions only for the user, the db query will automatically show only documents the user can read even with no filter applied.

**Comment by benkaiser** [comment]
What about write perms though?

It just seems like there would still be a solid use case for having some default fields like created by, created time, modified time, modified by

**Comment by stnguyen90** [comment]
@benkaiser, since adding a system createdBy attribute wouldn't be helpful in every use case/collection, this might be better tackled using an Appwrite Function. The function can execute on document creation and set a createdBy attribute to the user. You may also limit editing on the document, use a separate document to store the read only attributes, or expose editing only via functions so that the user can't edit the attribute.

Can this be closed now?

**Comment by benkaiser** [comment]
Yeah I'm happy to close it out, I haven't been using AppWrite since I created this issue last year (I just used it for a hack / learning project). And IIRC functions were async back then and kind of limited, so it's more than likely this can be resolved with functions as you say.
