### ISSUE TITLE
createOAuth2Session completes too early

### ISSUE THREAD

**Issue by JulianBissekkou** [appwrite/appwrite#1442]
## 🐛 Bug Report

`Future createOAuth2Session` completes earlier which causes problems if you directly fetch some resource after this call is done. 

In my case, I am fetching the JWT token right after this call and this fails in an unauthorized error.

I quickly caught the error when looking into the implementation.

```
      return FlutterWebAuth.authenticate(
              url: url.toString(),
              callbackUrlScheme:
                  "appwrite-callback-" + client.config['project']!)
          .then((value) async {
        Uri url = Uri.parse(value);
        Cookie cookie = new Cookie(
            url.queryParameters['key']!, url.queryParameters['secret']!);
        cookie.domain = Uri.parse(client.endPoint).host;
        cookie.httpOnly = true;
        cookie.path = '/';
        List<Cookie> cookies = [cookie];
        await client.init();

        client.cookieJar.saveFromResponse(Uri.parse(client.endPoint), cookies);
      });
```
Change 
`client.cookieJar.saveFromResponse(Uri.parse(client.endPoint), cookies)`
to
`await client.cookieJar.saveFromResponse(Uri.parse(client.endPoint), cookies)`.

Errors like this can be easily caught by installing a linter in the pipeline.
Maybe check out this really strict linter: https://github.com/modulovalue/extra_pedantic
If you don't want to add all these checks you can just add the linter rule "unawaited_futures" to your analyzers options and then run the analyzer step after you generated the code.

Let me know if you need help with this.

## Have you spent some time checking if this issue has been raised before?

Yes.

## Steps to Reproduce

```dart
void _reproduce() {
 account.createOAuth2Session(
        provider: "apple"
        success: "http://domain.de/auth/oauth2/success",
        failure: "http://domain.de/auth/oauth2/failure",
        scopes: <String>["email"],
      );
// some other call
account.get();
}
```

## Expected behavior

Fetching other stuff works immediately after this call.

## Actual Behavior

Fails because of unauthorized error

## Your Environment

Appwrite version: v:0.9.3.150

**Comment by eldadfux** [comment]
Resolved in v 0.7.1
