### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by fayazara** [appwrite/appwrite#145]
The documentation is very unclear on how to init a project and there's not proper difference explained between web and server, for some people it may be the same, I created a project and not sure how to initialise it in my vue project.

**Comment by eldadfux** [comment]
Thanks for reporting this issue! The getting started guide will definitely benefit from a small new section explaining this part in a little bit more depth. I am assigning this issue to myself.

In the meantime, I would recommend anyone having the same difficulties starting using Appwrite in the browser, to begin by adding the Appwrite SDK with the CDN method mentioned in the JS SDK repository.

**Comment by eldadfux** [comment]
Good news, we have updated the JS SDK to support ES6 import statements and updated documentation in both repo and website to explain how you can import the SDK to your project.

The updated repo:
https://github.com/appwrite/sdk-for-js

The updated doc on the website:
https://appwrite.io/docs/getting-started-for-web

![Uploading image.png…]()

**Comment by eldadfux** [comment]
@fayazara
