### ISSUE TITLE
Embeded document removed from parent 

### ISSUE THREAD

**Issue by generalxhd** [appwrite/appwrite#1450]
## 🐛 Bug Report

My Structure looks like this:
USER COLLECTION -->  EMBEDDED DOCUMENT (SEMESTERS) --> EMBEDDED DOCUMENT (SUBJECTS)

If I now make no changes in the USER COLLECTION and click the save button, the SUBJECTS aren't linked anymore to the SEMESTERS.

So "sub embedded documents" will be deleted after I click the save button on the parent-parent document.

## Have you spent some time to check if this issue has been raised before?
yes

## To Reproduce

Create a document (1), embed a document (2) and then once again create a embedded document (Structure should now look like above in my example).
Now click the save button in the document (1).

## Expected behavior
All documents should be linked like before when I don't click the save button.

## Actual Behavior
The embedded document will be removed.

## Your Environment

Raspberry Pi 4, Raspberry Pi OS Lite.

**Comment by TorstenDittmann** [comment]
Hey 👋🏻 

We are very aware of some issues with nested documents and the UI. Since we are refactoring the database right now, this will not be an issue anytime soon 🙂 

As a workaround I would suggest creating these type of documents using a Server SDK 👍🏻 

I don't have a better short-term solution right now :-/

**Comment by loftwah** [comment]
Can I suggest a tooltip from the UI to notify the user before they make the mistake?

**Comment by TorstenDittmann** [comment]
> Can I suggest a tooltip from the UI to notify the user before they make the mistake?

As we are getting closer to releasing the Database refactor anyway, this will be resolved sooner then later 👍🏻
