### ISSUE TITLE
Translate error messages.

### ISSUE THREAD

**Issue by stonith404** [appwrite/appwrite#1478]
## 🚀 Feature
In my opinion it would be really useful to translate also the error messages from appwrite.
It should work like the same as #25, so that the user can set the locale and then the error messages are in the same language as e.g the emails.

## Have you spent some time to check if this issue has been raised before?

yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

yes

## Pitch
As described above, when an error gets thrown, get the translated error, set in the `setLocale`.

**Comment by generalxhd** [comment]
I could help develop this feature if I would get a short instruction. Also I could translate to German and if necessary to French.

**Comment by TorstenDittmann** [comment]
This will be quite a big undertaking, since we also throw error messages that are inside our internal framework https://github.com/utopia-php

This is definitely something we could do in the future, but not a high priority now 👍🏻

**Comment by eldadfux** [comment]
We've been discussing this internally also in the context of allowing translations for the Appwrite console. As of now, our approach would be to recommend on handling errors on the client level and not automatically propagate Appwrite developer-focused errors to end users.
