### ISSUE TITLE
Create a Demo TODO List App Using React TODOMVC as Base

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#149]
We need to create a demo app that will demonstrate how to integrate Appwrite in a basic React JS project.

For this demo, we will use React TODO MVC app as base:
https://github.com/tastejs/todomvc/tree/gh-pages/examples/react

To show off some of the Appwrite capabilities, we will extend the demo app with some Appwrite APIs.

1.  Init Appwrite JS SDK in the TODO MVC source code.
2. Use [Appwrite account service](https://appwrite.io/docs/account#get) to check if the user is logged in or not.
3. If the user is logged out (401 response from the account API), show a modal screen covering the app (and blocking its usage) with a login form. Allow the user to login using 3 of our OAuth providers.
4. After login user should be redirected back to our app.
5. When the user is logged in, he will be able to use the original TODO MVC app.
6. The basic TODO MVC app saves the user changes to the browser localStorage API. Replace the localStorage API with the Appwrite Database service. Each task the user adds should be saved with read & write permissions allowing only the user itself to view or edit his tasks.
7. Add the username at the top right corner of the TODO MVC app to indicate he has logged in successfully.
8. Add a logout button near the username from stage 7 to allow the user to sign out of his project account.

For this task, we will provide a ready to use Appwrite project UID and a list of whitelisted domains for development and production environments. You can also use a self-hosted Appwrite instance and initialize the Appwrite project, allowed domains, and database collection structures.

**Comment by eldadfux** [comment]
@christyjacob4 is the owner of this issue. Once Christy finishes, we'll review the demo, add some design, and ask some help from the community to implement the same demo in combination with other frameworks.

**Comment by christyjacob4** [comment]
On it @eldadfux

**Comment by BogDAAAMN** [comment]
I'm working on something similar right now. But I will be happy to demo a TODO MVC app in other frameworks after @christyjacob4 is done!

**Comment by eldadfux** [comment]
Hey @BogDAAAMN that will be amazing!  Will keep this issue updated as we progress.

**Comment by Naamboon** [comment]
Trying to do it works

**Comment by LorenzHenk** [comment]
Is this still being worked on? 🤔

**Comment by eldadfux** [comment]
@LorenzHenk yeh, actually @christyjacob4 has almost completed this, we only have some final code reviews on it and it will be ready. Once done we'll look for contributors to replicate this demo with other frameworks.

**Comment by lloy0076** [comment]
@eldadfux This would be a great edition; the framework (probably the wrong description for the project) does look good but it's not clear how one could integrate this with customisable data.

**Comment by eldadfux** [comment]
@lloy0076 hope to release this in the coming days. If you have any specific question please feel free to open a new issue or join us on our discord server:
https://discord.gg/GSeTUeA

We would love to help you get started! 🤘

**Comment by eldadfux** [comment]
@christyjacob4 we should probably write something about this and release you work to the world.

**Comment by PineappleIOnic** [comment]
I'll be happy to work on a couple new frameworks with this issue, including Svelte, VueJS and Angular. If that's all good

**Comment by eldadfux** [comment]
We have added TODO list demos for all major frameworks!

Framework | Repo | Live Example
-- | -- | --
Todo App with React JS | https://github.com/appwrite/todo-with-react | https://appwrite-todo-with-react.vercel.app/
Todo App with Vue JS | https://github.com/appwrite/todo-with-vue | https://appwrite-todo-with-vue.vercel.app/
Todo App with Angular.js | https://github.com/appwrite/todo-with-angular | https://appwrite-todo-with-angular.vercel.app/
Todo App with Svelte | https://github.com/appwrite/todo-with-svelte | https://appwrite-todo-with-svelte.vercel.app/
