### ISSUE TITLE
Project gets abandoned when last member left

### ISSUE THREAD

**Issue by iamdineshkumar** [appwrite/appwrite#1494]
## 🐛 Bug Report

Project owner or last member have leave option in Members. If project owner leaves then particular project gets abandoned. 

## Have you spent some time to check if this issue has been raised before?

Yes

## To Reproduce

Just create project and leave from members but still project works through sdk but not able to access it.

## Expected behavior
It should either not allowed last user or owner to leave and ask to delete project instead or leaving last person also delete the project.
## Actual Behavior
It just remove user from access but project exists without anyone to access further.
## Your Environment
Docker container created in [justcloudify.com](https://justcloudify.com/)

**Comment by TorstenDittmann** [comment]
Yeah, we should probably just not show the button to leave the team when you are the only member of that project left.

**Comment by eldadfux** [comment]
This issue was pending for too long! Raised a quick PR! #2615

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻
