### ISSUE TITLE
Create Team Membership arguments are swapped

### ISSUE THREAD

**Issue by rdmchr** [appwrite/appwrite#1505]
## 📚 Documentation

The arguments for the Create Team Membership method are not ordered correctly.
![image](https://user-images.githubusercontent.com/66096031/130335147-a0aa07c9-62c7-4b7a-b52b-8da889f927f6.png)

## Have you spent some time to check if this issue has been raised before?

Yes.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**
