### ISSUE TITLE
Statistics aren't displayed correctly 

### ISSUE THREAD

**Issue by generalxhd** [appwrite/appwrite#1506]
## 🐛 Bug Report

Since version 0.9.4.150 the Documents, Storage, Users and Tasks statistics aren't correctly displayed.

## Have you spent some time to check if this issue has been raised before?

yes

## To Reproduce

Take a look at the statistic and check if they are the same as the number in e.g the users page.
Also you could switch your project and take a look if the statistics are the same.

## Expected behavior
The statistics should be correctly and the same as e.g on the user page

## Actual Behavior

The statistics aren't the same like e.g on the user page.
Also the statistics in every project are the same.

<img width="1078" alt="Screenshot 2021-08-22 at 20 37 21" src="https://user-images.githubusercontent.com/58886915/130366346-11ca1010-ad93-44b8-9d6a-4080fb41b23b.png">
<img width="1066" alt="Screenshot 2021-08-22 at 20 42 07" src="https://user-images.githubusercontent.com/58886915/130366385-c9af537e-b617-4d8c-afa3-79928b693d64.png">

## Your Environment

Raspberry pi, Ubuntu (newest version). Appwrite v 0.9.4.150

**Comment by generalxhd** [comment]
Switching between the time periods does also not work

**Comment by generalxhd** [comment]
I can confirm that this issue only happen in 9.4, I downgraded to 9.3 and there it works.

**Comment by eldadfux** [comment]
This should be fixed in 0.10
