### ISSUE TITLE
An erro in upgrading

### ISSUE THREAD

**Issue by TSCSOftware** [appwrite/appwrite#1507]
i try upgrade 9.3 to 9.4 , and lastly ran 
"cd appwrite/
docker-compose exec appwrite migrate"
 then result is
Migrating project: Appwrite (console)
Migrating: 0 / 30
Fetched 2/2 projects...
Migrating project: Lgm
Migrating: 0 / 334
Migrating: 50 / 334
Migrating: 100 / 334
Migrating: 150 / 334
Migrating: 200 / 334
Migrating: 250 / 334
Migrating: 300 / 334
Migrating project: winscr 
Migrating: 0 / 377
Migrating: 50 / 377
Migrating: 100 / 377
Migrating: 150 / 377
Migrating: 200 / 377
Migrating: 250 / 377
Failed to update document: Invalid document structure: Missing collection attribute $collection
Migrating: 300 / 377
Migrating: 350 / 377
Data Migration Completed

but now my console home is showing only correctly "requests" others are all 0  or n/a
but users,storege,database are working in there tabs
please help me

**Comment by TorstenDittmann** [comment]
We released version 0.10.1 - if you upgrade to that version everything should be back to normal 👍🏻

**Comment by eldadfux** [comment]
Closing for now, will re-open if still relevant.
