### ISSUE TITLE
No possibility to change the domain of appwrite console

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [appwrite/appwrite#1508]
## 🐛 Bug Report

After I edited the `.env` file and changed the `_APP_DOMAIN` and `_APP_DOMAIN_TARGET` variables (in order to change from an old domain to a new domain), I experienced an issue. It didn't show any errors, but it also didn't change the endpoint or the domain. 

## Have you spent some time to check if this issue has been raised before?

I have been told by @kodumbeats to raise an issue here :)

## To Reproduce

1. Create a test appwrite project with a custom domain.
2. Change the `.env` variables `_APP_DOMAIN` and `_APP_DOMAIN_TARGET` to a new domain.
3. Restart appwrite container
4. Try to access appwrite via the new domain.

## Expected behavior

I thought, it would change the domain of my appwrite page to the new domain. 

## Actual Behavior

It didn't change anything, and didn't show any errors.

## Your Environment

I tried it on appwrite 0.9.3 and 0.9.4, which were set up on a:
Static hostname: expirapp
Icon name: computer-vm
Chassis: vm
Machine ID: a9a196fec3b142eabb1667c97a14ded2
Boot ID: bd0d0ba5ba6f4def8386fefd9dc809ed
Virtualization: kvm
Operating System: Ubuntu 21.04
Kernel: Linux 5.11.0-31-generic
Architecture: x86-64
(A DigitalOcean droplet)

**Comment by stnguyen90** [comment]
> Restart appwrite container

How did you restart your appwrite container? If you only did an `docker-compose restart` it may not have picked up the new env vars. Instead, you need to run `docker-compose up -d` to recreate the containers with the new env vars.

**Comment by dawid-niedzwiecki** [comment]
I think I did try using `docker-compose up -d` aswell, if I remember
correctly, but that was a long time ago...

pt., 5 lis 2021 o 01:15 Steven ***@***.***> napisał(a):

**Comment by stnguyen90** [comment]
Are you still having problems or can't this be closed?

**Comment by dawid-niedzwiecki** [comment]
I reinstalled Appwrite completely in order to set it up with a
different domain, but I don't know if the issue remained. I have no idea if
this bug has been patched since then.

pt., 5 lis 2021 o 04:13 Steven ***@***.***> napisał(a):

**Comment by stnguyen90** [comment]
So are you still having problems with the new domain or can this be closed?

**Comment by kodumbeats** [comment]
I haven't tested myself, but I don't think the codebase knows how to handle a change in console domain. I think we should close when either:
- we've tested this functionality and cannot replicate the issue, or
- we add this functionality into the code. There could be others that could benefit from this feature in the future, and I'd like to track the progress.

**Comment by stnguyen90** [comment]
So I followed these steps:

1. updated `_APP_DOMAIN` and `_APP_DOMAIN_TARGET` in my .env file
2. ran `docker-compose up -d`
3. ran `docker-compose exec appwrite ssl`
4. After 30 seconds or so, the appwrite-worker-certificates container outputed:
```
appwrite-worker-certificates    | Appwrite certificates worker v1 has started
appwrite-worker-certificates    | [notice] Starting worker 81cce6808e34:7:v1-certificates
appwrite-worker-certificates    | [notice] Starting work on (Job{v1-certificates} | ID: 4aeea2825539993a43386c9984483f32 | CertificatesV1 | [{"document":[],"domain":"new.domain.com","validateTarget":false,"validateCNAME":false}])
appwrite-worker-certificates    | [notice] (Job{v1-certificates} | ID: 4aeea2825539993a43386c9984483f32 | CertificatesV1 | [{"document":[],"domain":"new.domain.com","validateTarget":false,"validateCNAME":false}]) has finished
```
5. I had to open a new Incognito tab to see the new cert since the old cert was cached on my normal browser session.

**Comment by eldadfux** [comment]
> *Bonus Points: Browsing to my original domain still works with the old cert.

Yes, it should work for 3 months until it will be expired.

**Comment by kodumbeats** [comment]
> So I followed these steps:
> 
>     1. updated `_APP_DOMAIN` and `_APP_DOMAIN_TARGET` in my .env file
> 
>     2. ran `docker-compose up -d`
> 
>     3. ran `docker-compose exec appwrite ssl`
> 
>     4. After 30 seconds or so, the appwrite-worker-certificates container outputed:
> 
> 
> ```
> appwrite-worker-certificates    | Appwrite certificates worker v1 has started
> appwrite-worker-certificates    | [notice] Starting worker 81cce6808e34:7:v1-certificates
> appwrite-worker-certificates    | [notice] Starting work on (Job{v1-certificates} | ID: 4aeea2825539993a43386c9984483f32 | CertificatesV1 | [{"document":[],"domain":"new.domain.com","validateTarget":false,"validateCNAME":false}])
> appwrite-worker-certificates    | [notice] (Job{v1-certificates} | ID: 4aeea2825539993a43386c9984483f32 | CertificatesV1 | [{"document":[],"domain":"new.domain.com","validateTarget":false,"validateCNAME":false}]) has finished
> ```
> 
>     1. I had to open a new Incognito tab to see the new cert since the old cert was cached on my normal browser session.
> 
> 
> *Bonus Points: Browsing to my original domain still works with the old cert.

@stnguyen90 Does the domain update appropriately in the Appwrite console after following your instructions?

**Comment by stnguyen90** [comment]
> @stnguyen90 Does the domain update appropriately in the Appwrite console after following your instructions?

Do you mean like the API Endpoint field in the Settings page of a project? Yes, that shows the updated domain name.

**Comment by kodumbeats** [comment]
> > @stnguyen90 Does the domain update appropriately in the Appwrite console after following your instructions?
> 
> Do you mean like the API Endpoint field in the Settings page of a project? Yes, that shows the updated domain name.

Then yeah, I feel comfortable closing this. Thanks to all who reported and investigated - y'all are the best! ❤️
