### ISSUE TITLE
Database timeout after like a day without use.

### ISSUE THREAD

**Issue by Emiliaaah** [appwrite/appwrite#1509]
## 🐛 Bug Report

After about a day of having appwrite running without using it database connections time out and appwrite becomes unusable.
A restart fixes this issue but if you leave it running again for another day it'll produce the same result.

Logs:
[Appwrite](https://haste.emilia.codes/ihugaxogaz.css)
[Mariadb](https://haste.emilia.codes/ikirihonar.sql)

## Have you spent some time to check if this issue has been raised before?

Yes

## To Reproduce

Don't use appwrite and leave it running for like a day.

## Expected behavior

I expect to be able to connect to appwrite and use it.

## Actual Behavior

I get a 500 internal server error when connecting after not using appwrite for a good while.

## Your Environment

Ubuntu 20.04
Docker version 20.10.8, build 3967b7d
docker-compose version 1.29.2, build 5becea4c
appwrite version 9.0

**Comment by eldadfux** [comment]
Bug fixed! 🥳

This update will be part of the next Appwrite version.

**Comment by eldadfux** [comment]
This fix is now available on Appwrite 0.10! 🥳
