### ISSUE TITLE
Client side User information Change

### ISSUE THREAD

**Issue by fidst** [appwrite/appwrite#1511]
## 🚀 Feature

I feel that an admin on a site, it would be good to be able to manage user information like that without the need to be logged in as the user. Having an implementation into the server-side SDK for admins to change user information? 

like the same way we can verify email?
$result = $users->adminUpdate($userID,$field,$newValue);

Conversation in discord here: https://discord.com/channels/564160730845151244/564161903685795841/879744425524334674

## Have you spent some time checking if this issue has been raised before?

Yes, re the discord thread above.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yup

## Pitch

As a super admin of a website, managing users is key. From troubleshooting to editing or basic user management. This would also prevent the need to login as the user, or impersonate. Allowing for more security, and trust between us as admins and the users on the site.

**Comment by TorstenDittmann** [comment]
This should be released now and allows Server SDK to update name, email and password 👍🏻
