### ISSUE TITLE
Server SDK Teams Create Membership documentation incorrect

### ISSUE THREAD

**Issue by thegamingninja** [appwrite/appwrite#1546]
## 📚 Documentation

https://appwrite.io/docs/server/teams?sdk=nodejs-default#teamsCreateMembership
```
Use this endpoint to invite a new member to join your team. An email with a link to join the team will be sent to the new member email address if the member doesn't exist in the project it will be created automatically.
```
An email invitation is not sent when using the Server SDK, the user is just added to the team without a choice. 
The documentation is incorrect and states that an invitiation email is sent.

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

**Comment by PineappleIOnic** [comment]
This appears to of already been fixed, https://github.com/appwrite/appwrite/blob/cf3ffcdf32bdf4909d53e0de290bd3b9324fb1a4/docs/references/teams/create-team-membership.md the updated description just hasn't been deployed yet.
