### ISSUE TITLE
Appwrite returns 200 when there is MySQL error

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1558]
## 🐛 Bug Report

There is a code that created a document and returns status `Response::STATUS_CODE_CREATED = 201`:

https://github.com/appwrite/appwrite/blob/abfe47787bb2d317884a293963ad641bbda3a9f0/app/controllers/api/projects.php#L953

If I set the length of `secret` in `collections2.php` to 256, everything works as expected.

If I set the length to 10 and run tests, I get:

```
There was 1 failure:

1) Tests\E2E\Services\Projects\ProjectsConsoleClientTest::testCreateProjectKey
Failed asserting that 200 matches expected 201.

/usr/src/code/tests/e2e/Services/Projects/ProjectsConsoleClientTest.php:994
```

The log in the Appwrite console:
```
appwrite                        | [Error] Type: PDOException
appwrite                        | [Error] Message: Data too long for column 'secret' at row 1
appwrite                        | [Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
appwrite                        | [Error] Line: 70
appwrite                        | [Error] Timestamp: 2021-09-01T06:41:34+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/projects/:projectId/platforms
```

## Have you spent some time to check if this issue has been raised before?

No similar issues, it's probably related to database refactoring.

## To Reproduce

It can be easily reproduced on this branch: https://github.com/appwrite/appwrite/tree/feat-db-project-subqueries

Run tests, all good. Change `secret` length to `10`, wipe appwrite, re-run tests and we will have the one showed above.

## Expected behavior

Throw error 500 if there is an MySQL problem and do not continue the code.

## Actual Behavior

Currently, it continues and even tho we set the status to 201, it is 200 for some reason.

## Your Environment

Database refactoring branch

**Comment by eldadfux** [comment]
I'll close this for now as this branch is still a work in progress and its very hard to debug and know if this was a temporary issue.
