### ISSUE TITLE
Session Token Expiration

### ISSUE THREAD

**Issue by TafadzwaD** [appwrite/appwrite#1560]
## 🚀 Feature

Due to the dynamic nature of applications which rely on AppWrite it would be good to have a chance of specifying the Session Expiration Time for user either through the AppWrite dashboard or whichever way the team finds suitable.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch
Ability to manually specify session token expiration time from the AppWrite dashboard so that all SDK's will be in sync with the configuration.

**Comment by eldadfux** [comment]
Wandering if it would be better to have this as another param as part of the session creation endpoint or if this should be a project level setting.🤔

**Comment by TafadzwaD** [comment]
We can have it both ways but with the project level setting having more
preference than the one from session creation endpoint. If the the setting
is done from both the session creation endpoint and at project level then
prioritise project level..If only one setting is specified,  either the
session creation endpoint or the project level then go with that... What do
you think?

**Comment by eldadfux** [comment]
I was actually thinking the project level setting should be considered as default, and the api parameter can overwrite it.

**Comment by TafadzwaD** [comment]
Actually, that would be more ideal.. 😎👏

**Comment by stnguyen90** [comment]
Closing as this should be possible now as of [1.1.0](https://github.com/appwrite/appwrite/releases/tag/1.1.0).
