### ISSUE TITLE
Custom domains TLS status doesn't get updated after creating a SSL certificate

### ISSUE THREAD

**Issue by Fabian9799** [appwrite/appwrite#1581]
## 🐛 Bug Report

After adding a custom domain and verifying it the TLS status still shows "In Progress" after generating a SSL certificate

## Have you spent some time to check if this issue has been raised before?

Yes, could not find any

## To Reproduce

1. got to `console/settings/domains/` and add a custom domain
2. add the required CNAME record in your domains dns settings
3. press on "DNS Settings" in the console and verify the domain
4. wait a couple minutes and check if the SSL certifiacte works
5. The console still shows "In Progress"
6. an empty folder gets created `/var/lib/docker/volumes/appwrite_appwrite-certificates/_data/DOMAIN/`

## Expected behavior

The text should change to a success message after the SSL certificate is created

## Actual Behavior

It still shows "In Progress"

![image](https://user-images.githubusercontent.com/19490891/132023640-53e7dfb5-2afc-4ef2-b68b-2245c8dde903.png)

## Your Environment

Appwrite v:0.10.1.160 on Docker 19.03.13 and Ubuntu 20.04.1 ( 2GB droplet from DigitalOcean)

**Comment by Fabian9799** [comment]
Some more info here: https://discord.com/channels/564160730845151244/564161373148414012/883349688126951514

**Comment by TorstenDittmann** [comment]
This should be fixed now 👍🏻
