### ISSUE TITLE
Failed to create a team and add members

### ISSUE THREAD

**Issue by generalxhd** [appwrite/appwrite#1582]
## 🐛 Bug Report

"Failed to create a team"

## Have you spent some time to check if this issue has been raised before?
yes
## To Reproduce
Try to create a team and add a member

## Expected behavior
I want to create a team and add team members

## Actual Behavior

When I want to create a team I get "Failed to create a team" as an error message. When I look at the response I get a 500 error. 
When you now refresh the page you can see the team but strangely with 1 member. Also adding team members isn't possible:

401: User is not allowed to send invitations for this team

Here a quick video:

https://user-images.githubusercontent.com/58886915/132032265-727c4605-cf20-4d92-b6be-f841da87f9a6.mov

## Your Environment

Appwrite v0.10.1 on Ubuntu

**Comment by s3ppo** [comment]
i have the same issue

**Comment by TorstenDittmann** [comment]
This should be fixed now when using `0.10.2` 👍🏻
