### ISSUE TITLE
Database export  Feature

### ISSUE THREAD

**Issue by TSCSOftware** [appwrite/appwrite#1583]
some times we want to test multiple servers.but i troble with create data base ! becasuse appwrite hasnt option to export database to anither appwrite server

**Comment by rpCal** [comment]
I think you can use simple mysql dump :) oraz use write code that will use api to get list + get each item

**Comment by TSCSOftware** [comment]
ofcause ,i tried backup tool {mongodb) {using docs} but not restore!.i cope sql dta from server A,then i back up to new server{server B} but does not working!

**Comment by TSCSOftware** [comment]
@rpCal thanks.i created dart code to get data and store as json,then send to onother server
@rpCal ;)
