### ISSUE TITLE
Document rule type: Enum

### ISSUE THREAD

**Issue by Kromzem** [appwrite/appwrite#1584]
## 🚀 Feature

Add a new data type to document rules, that let's you choose out of predefined values.

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

I have a use-case where I want to only have these predefined values to choose from, e.g. a country selection. I'm not entirely sure, how to accomplish this, with the current toolset :(

**Comment by eldadfux** [comment]
We might be able to achieve this as part of the upcoming upgrade. I have assigned @kodumbeats to be able to track this issue and provide updates when possible.

**Comment by Kromzem** [comment]
Resolved with v0.12 release
