### ISSUE TITLE
Functions all stucks in waiting status

### ISSUE THREAD

**Issue by dim-apparence** [appwrite/appwrite#1597]
## 🐛 Bug Report

Hello, I found a bug in the function part of Appwrite. All functions executed was "**waiting**" and never gets completed... even when trying to restart the server, all function part is now unusable.

![Preview image](https://i.ibb.co/Hncq0BY/Capture-d-e-cran-2021-09-07-a-10-17-26.png)

All functions worked fine but yesterday, I tried to print in a Dart function a huge JSON stringified string. When I tried to execute this function, the first waiting appear and now all functions are in waiting mode...

_Note: in this image, the first function with the huge JSON print is the 2021-09-03 10:45_

![Preview image 2](https://i.ibb.co/mTqfs1P/Capture-d-e-cran-2021-09-07-a-10-30-08.png)

## Have you spent some time to check if this issue has been raised before?

- Trying to upload a new version of the function: **do nothing**
- Trying to create a completely new function & execute it: **do nothing**, stuck to waiting...
- Trying to restart AppWrite server with docker compose: **do nothing**
- Trying to remove manually docker container of appwrite functions & then restart server: **do nothing**
- Docker log of ```appwrite-functions container```:
```
[critical] (Job{v1-functions} | ID: 53ccbfe0ccd1c520bffa7e691a8f3cfc | FunctionsV1 | [{"projectId":"60c89887512bc","webhooks":[],"functionId":"6137174968950","executionId":"61371d5909388","trigger":"http","data":"","userId":"admin-60c8987f01419","jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhZG1pbi02MGM4OTg3ZjAxNDE5Iiwic2Vzc2lvbklkIjoiNjExMTFhMDZjMWQzMCIsImV4cCI6MTYzMTAwMjg0NX0.trfkp6i7yQ4sXkk_wc7Z0Hn_E8WCYWW_wvUe_kMlKVw"}]) has failed TypeError: Utopia\Orchestration\Orchestration::setCpus(): Argument #1 ($cores) must be of type int, string given, called in /usr/src/code/app/workers/functions.php on line 413 and defined in /usr/src/code/vendor/utopia-php/orchestration/src/Orchestration/Orchestration.php:172
Stack trace:
#0 /usr/src/code/app/workers/functions.php(413): Utopia\Orchestration\Orchestration->setCpus('')
#1 /usr/src/code/app/workers/functions.php(269): FunctionsV1->execute('http', '60c89887512bc', '61371d5909388', Object(Appwrite\Database\Database), Object(Appwrite\Database\Document), '', '', '', Array, 'admin-60c8987f0...', 'eyJ0eXAiOiJKV1Q...')
#2 /usr/src/code/src/Appwrite/Resque/Worker.php(22): FunctionsV1->run()
#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
#4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#5 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#6 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('0.1', false)
#7 {main}
```

## To Reproduce

Create a function with Dart that prints a hudge JSON string in print. Like this:

```dart
print('<huge json stringified string>')
```

## Expected behavior

Functions can be executed or killed when an error occurs (or timeout reached).

## Actual Behavior

All new functions created are in waiting status... even when trying to create a new function.
All appwrite functions are now unusable (new & old).

## Your Environment

Hosted server, linux-gnu Debian x86_64 (sorry can't have much more information)

**Comment by TorstenDittmann** [comment]
Hey @dim-apparence 👋🏻 

This was an issue introduced in 0.10.0 - you can either upgrade to 0.10.2 or you can remove `_APP_FUNCTIONS_CPUS` from your `.env` file 👍🏻
