### ISSUE TITLE
DOCS: Getting Started for Flutter Docs needs refactoring for setting up Android OAuth callback url

### ISSUE THREAD

**Issue by 2002Bishwajeet** [appwrite/appwrite#1599]
## 📚 Documentation

While setting up Appwrite OAuth callback url in Flutter Android app, some activity needs to be added in the `AndroidManifest.xml` file.
Now, according to the snippet given in the docs
```xml
<manifest>
  <application>
    <activity android:name="com.linusu.flutter_web_auth.CallbackActivity" >
      <intent-filter android:label="flutter_web_auth">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="appwrite-callback-[PROJECT_ID]" />
      </intent-filter>
    </activity>
  </application>
</manifest>
```
If we **copy paste**  this entire snippet in `Android/app/src/main/AndroidManifest.xml' after replacing with the current Project ID, it  produces build errors.

### This is the stack trace
```bash

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> Failed to calculate the value of task ':app:generateDebugBuildConfig' property 'buildConfigPackageName'.
> Failed to query the value of property 'packageName'.
> Package Name not found in C:\Users\bishw\Documents\GitHub\no_signal\android\app\src\main\AndroidManifest.xml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

On digging deeper to this issue and after comparing with the[ `AndroidManifest.xml` ](https://github.com/appwrite/playground-for-flutter/blob/master/android/app/src/main/AndroidManifest.xml)file given as a sample, I noticed some differences,
```xml
    <activity android:name="com.linusu.flutter_web_auth.CallbackActivity" >
      <intent-filter android:label="flutter_web_auth">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="appwrite-callback-[PROJECT_ID]" />
      </intent-filter>
    </activity>
 ```

>  We need to place this snippet  under the `<application>` tag. 
The extra `<manifest>` and `<application>` were redudant. Adding those were the main reasons to believe the compiler that this what ends here

This could be pretty confusing for those who haven't worked on native side and for beginners.

### Solution
If somehow it can explain that we need to that you need to add these `<activity>` under the `<application>`  in the `AndroidManifest.xml` file (either by replacing the snippet or making some slight modification by adding comments), this could make their day who would be following these docs for setting up Appwrite.

**Comment by lohanidamodar** [comment]
Work in progress here
https://github.com/appwrite/docs/pull/58
