### ISSUE TITLE
Collections pagination issue on front-end

### ISSUE THREAD

**Issue by marco-martinenghi** [appwrite/appwrite#1600]
Hello guys i think i've found a bug on the front-end. 
There is a problem with collections pagination.  

Go Here : /console/database?project=xxx&offset=0

If you have a large number of collections, max number of pagination is always 3.

**Comment by TorstenDittmann** [comment]
https://user-images.githubusercontent.com/1759475/132658201-7d3ed53b-c8db-4e2e-a7bc-d726c79edc86.mov

Wasn't able to reproduce that bug 🐛

**Comment by marco-martinenghi** [comment]
My mistake sorry!
