### ISSUE TITLE
Option to avoid the creation of a new user when email is unknown using the magic url based login

### ISSUE THREAD

**Issue by teamsolutions-dev** [appwrite/appwrite#1601]
## 🚀 Feature

Provide an option to avoid the creation of a new user when using a magic url based login with an e-mail that doesn't belong to any existing user

## Have you spent some time to check if this issue has been raised before?
Yes, this feature hasn't been requested yet.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

This feature would allow the creation of users using the server side SDK defining only emails and not passwords. Then only users with known emails can login using the magic based url based login and users don't have to deal with passwords.

**Comment by eldadfux** [comment]
Can you share more information about the use-case that caused you to believe this feature is required. I would also love to get more feedback from the community about making the password optional in the createAccount endpoint and whether more devs think this would still be intuitive to the API signature.

**Comment by teamsolutions-dev** [comment]
The mobile app I'm working on is the mobile companion of an ERP system in which users, their emails and their permissions are defined. One of the permission is the access to the mobile app. The ERP system is based on a database system which is partially synchronized with Appwrite for the data that need to be accessed by the mobile app. The users are also synchronized so Appwrite knows which users are allowed. It is not permitted to create an account from the mobile app. So, the fact that an email exists in the Appwrite user database is for me the unique condition to give access to the application. So the magic url login is perfect for this use case IF an unknown email doesn't lead to an account creation.
