### ISSUE TITLE
Add support for mariadb docker image for raspberry pi4 - arm7 arch

### ISSUE THREAD

**Issue by oreazamu** [appwrite/appwrite#1612]
## 🚀 Feature

When trying to install appwrite on raspberry pi4, the installation fails and throws below error.

> Failed to install Appwrite dockers
> The Docker Engine you're using is running in swarm mode.
> 
> Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.
> 
> To deploy your application across the swarm, use `docker stack deploy`.
> 
> Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
> Pulling mariadb (appwrite/mariadb:1.2.0)...
> no matching manifest for linux/arm/v7 in the manifest list entries
> 

Here is output from dmesg

> [    0.000000] Linux version 5.10.52-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1441 SMP Tue Aug 3 18:11:56 BST 2021
> [    0.000000] CPU: ARMv7 Processor [410fd083] revision 3 (ARMv7), cr=30c5383d

I think we don't have mariadb docker images for arm7 arch.

https://hub.docker.com/r/appwrite/mariadb/tags?page=1&ordering=last_updated

Perhaps we can build mariadb from below image for arm7 arch
https://hub.docker.com/r/linuxserver/mariadb/tags?page=1&ordering=last_updated

**Comment by kodumbeats** [comment]
@oreazamu Our upcoming database refactor eliminates the need for us to maintain a MariaDB image of our own (our image simply preloads a schema). Because of this, you'll be able to substitute in any MariaDB image you wish.

We try to only use official images as a part of our stack, and unfortunately MariaDB doesn't distribute an `arm32v7` image:
https://hub.docker.com/_/mariadb?tab=tags&page=1&ordering=last_updated

**Comment by eldadfux** [comment]
@oreazamu you can also use this file to preload the Appwrite schema on your own docker image for now:
https://github.com/appwrite/appwrite/blob/master/app/db/SQL/all.sql

**Comment by christyjacob4** [comment]
@bachrc  what is your environment like ? Which raspberry pi are you on ? And what is the architecture of the machine ?

**Comment by bachrc** [comment]
I have a Raspberry Pi 4B+ with Raspberry Pi OS, 8GB of RAM, which architecture I think is arm/v7

**Comment by stnguyen90** [comment]
Closing as Appwrite should work on a raspberry pi as long as it has enough resources and it is running a 64bit OS (not Rasbian).
