### ISSUE TITLE
Quick reverse pagination can cause removal of memberships instantly without confirmation

### ISSUE THREAD

**Issue by JakeAi** [appwrite/appwrite#1615]
## 🐛 Bug Report

Quick reverse pagination can cause removal of memberships instantly without confirmation if the initial page has less than the 12 row limit.

## Have you spent some time to check if this issue has been raised before?

Yes

## To Reproduce

https://streamable.com/oks76j

## Expected behavior

Clicking remove/delete should have a confirmation dialog.

## Actual Behavior

Membership removed instantly.

## Your Environment

(Write Environment, Operating system and version etc.)

**Comment by hey-nicolasklein** [comment]
How do you reverse paginate the database? Please provide a code sample.

**Comment by stnguyen90** [comment]
Closing as this is no longer a problem in the new Console.
