### ISSUE TITLE
Collection Permission Not Working

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#1617]
## 🐛 Bug Report

When creating a document, the collection permission isn't checked.

## Have you spent some time to check if this issue has been raised before?

Yes, I checked through issues. I also brought this up on discord and was referred to github to create an issue.

## To Reproduce

1. Create a collection with no write permissions
2. Create a document using a client SDK

## Expected behavior

I expected the document to not get created and for there to be some 403 error.

## Actual Behavior

The document was created successfully.

## Your Environment

I'm running AppWrite  v:0.10.2.160

I tested this using a copy of https://github.com/appwrite/playground-for-flutter.

**Comment by stnguyen90** [comment]
Some additional context: since the current collection rules is a little limited, the only way to do data validation is to prevent creates and updates via the database service and, instead, expose a function that will create/update.

**Comment by stnguyen90** [comment]
Any update on this?

**Comment by TorstenDittmann** [comment]
> Any update on this?

This will is already fixed and will be released with the database refactor 🙏🏻 

The refactor will also allow you to choose between Collection and Document based permission 👍🏻

**Comment by stnguyen90** [comment]
I tested this on the db-alpha and it looks like it works. My test:

1. Create Collection with Collection based permission and giving write access to no one.
2. From a client SDK, create a document in the Collection
3. Received 401 error

**Comment by stnguyen90** [comment]
@TorstenDittmann would you like me to close this issue or would you rather keep it open and label it for when the db refactor is released?

**Comment by christyjacob4** [comment]
@stnguyen90  Let's keep it open until we release Appwrite 0.12. I've added the `waiting-for-release` label in the interim

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
