### ISSUE TITLE
Cannot create account or access console

### ISSUE THREAD

**Issue by doyle-mark** [appwrite/appwrite#162]
On attempting to access appwrite.io/console the user is redirected to log in/sign up at https://appwrite.io/auth/signin (assuming they are logged out). On attempting to sign up with Linkedin, Facebook or Github a 412 error is thrown: 

```Error 412
Provider is undefined, configure provider app ID and app secret key to continue

Error ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
```
On attempting to create a user account a JSON error message is thrown:
```
{"message":"Param \"confirm\" is not optional.","code":400,"version":"0.1.55.ee"}
```

Therefore new users are unable to sign up to the service and or access the console

**Comment by eldadfux** [comment]
Appwrite is currently only available as a self-hosted solution. This means that you have to install it on your hardware (local machine, or cloud server) and access it from http://localhost or http://[YOUR-IP-ADDRESS]. You can learn more about how to get started in this tutorial:

https://appwrite.io/docs/getting-started-for-web

In your issue, you mention trying to access: https://appwrite.io, which is the public version of Appwrite, and at the time of writing, these lines not available as a service.
