### ISSUE TITLE
Add limiters on function triggers/events

### ISSUE THREAD

**Issue by Pastajello** [appwrite/appwrite#1625]
Hello

## 🚀 Feature

I'd like to have some limiters on functions - especially in documents 'section' so we can have a dedicated function just for this collection that get triggered only when something in collection gets changed.
![obraz](https://user-images.githubusercontent.com/28345098/133384841-7399140c-a292-4deb-a108-a7d640cbcb3b.png)

## Have you spent some time to check if this issue has been raised before?

Yup

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yup

## Pitch

Currently the event triggers do not consider anything when executing a function.
Lets say we have a chat app, we want to create a PushNotification only on 'new friend request'. Now, with how things are done we must manually check if the collection being updated/added to is 'friends'. As its a chat app most of new documents get added to 'messages' so our function gets triggered every 0.1s because people keep talking instead of 1 per day when they get new 'friend'.

With a 'limiter' we would only trigger a function on a 'friend' collection update.  Considering that people have a lot of small functions that check for some documents creations for notiications the execution hell can be quite big.

**Comment by TorstenDittmann** [comment]
We were thinking about extending the events to the way we are managing channels with realtime.

https://appwrite.io/docs/realtime#channels

This way you would have more control. Not sure if this would fix the create/update problem, but it lets you narrow down when functions are triggered in the first place.

**Comment by stnguyen90** [comment]
Closing as this should be possible now.
