### ISSUE TITLE
Add Okta OAuth2 Provider

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#1668]
## 🚀 Feature

Okta is a very popular authorization provider and it would be great to add support.

## Have you spent some time to check if this issue has been raised before?

Yes, I haven't found anything on Okta. I've also brought it up on [discord](https://discord.com/channels/564160730845151244/636852860709240842/892138688362979408).

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

As mentioned, it would be great to support Okta as an OAuth2 provider. Okta is used very often in enterprises too so it would help with getting Appwrite into large organizations.

The big problem with Okta & Appwrite is Okta doesn't have only 1 domain; each Okta instance/tenant has it's own URL. As such, the configuration settings in Appwrite would need to support additional configuration options.

I've noticed Apple Auth also requires a different configuration, but the form is currently [hardcoded](https://github.com/appwrite/appwrite/blob/master/app/config/providers.php#L20) and the different configuration fields are jammed together into the [secret](https://github.com/appwrite/appwrite/blob/master/src/Appwrite/Auth/OAuth2/Apple.php#L137-L146).

Once configurable fields are added, it should be easy to implement an Okta OAuth2 provider.

**Comment by eldadfux** [comment]
I think this issue would be easier to implement once #926 is ready.
