### ISSUE TITLE
Wrong Order Of Parameters On Teams createMembership API 

### ISSUE THREAD

**Issue by TafadzwaD** [appwrite/appwrite#1669]
## 📚 Documentation

The order of parameteres in the documentation of createMembership on the web SDK has the **name** field as the third parameter.

If you put **name** as the third parameter it results in an error creating a team membership as name is being inteprated as **roles** (roles is the fourth parameter though).

What had it working was using **name** as the last parameter. Kindly rectify the issue as this might inconvenience developers due to wrong documentation

## Have you spent some time to check if this issue has been raised before?

The issue has not been raised before.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes I did

### Reference

https://appwrite.io/docs/client/teams?sdk=web-default#teamsCreateMembership

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**
