### ISSUE TITLE
Feat: Add CRUD operations for Collections on the client side 

### ISSUE THREAD

**Issue by 2002Bishwajeet** [appwrite/appwrite#1670]
## 🚀 Feature

This should allow Create , Read , Update and Delete  operations for Collections on the Client Side.
![image](https://user-images.githubusercontent.com/62933155/135021786-a4e9284c-aa60-4b28-bd09-165af313f15d.png)
We currently have features to perform CRUD operations for Documents on client side, adding the same for collections would be great

## Have you spent some time to check if this issue has been raised before?

Yup, I talked with the maintainers and they suggested me to raise an Issue for it

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

**Yes**

## Pitch

I was working on my new App and I felt the need of getting the list of collections from the client side. On navigating through the docs, I can only see those options in the server side section.

Why I want a list of collections is, I am making a chatting application. so each collection depicts their chats between two users and it can be only accessed by both of them. So when a user stay at home page, he/she can actually see their history with whom they have contacted. I can do this thing on the **Server Side** but I have to make a check internally about the read and write access. That makes it little complicated. For the same I have to create a collection using the server side (which acc to me cannot be feasible in the long run).

Adding these features which we access these collections and modify them from the client side, it would be great

**Comment by prasadsunny1** [comment]
This seems like a nice addition to the client APIs, which client SDK are you using right now?

**Comment by 2002Bishwajeet** [comment]
Closing as this Could be done using Cloud functions now
