### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1776]
# Introduction

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

Appwrite currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). Your task is to create **GitHub issue forms** for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a reference for this PR.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Prepare **bug report** issue form in `.github/ISSUE_TEMPLATE/bug.yaml`
- [ ] Prepare **documentation** issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare **feature request** issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to **master** and test issue forms on your fork
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by AnirbanBall** [comment]
I am interested and I want to work on this

**Comment by abxhr** [comment]
I would love to work on this! 🚀

**Comment by MatteoGheza** [comment]
I'm interested in working on this. I already made Github Issue forms for other open source projects, so I have some experience.

**Comment by Vidushi-Gupta** [comment]
Hi! I hope the assignments for Hacktoberfest have begun. Could you please assign it to me for the hacktoberfest?

**Comment by christyjacob4** [comment]
@AnirbanBall  Assigned it to you! All the best :rocket:

**Comment by christyjacob4** [comment]
@abxhr  We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by christyjacob4** [comment]
@Vidushi-Gupta We would love you to check out some of our other open issues and join us on discord if you need help finding some https://appwrite.io/discord

**Comment by Meldiron** [comment]
I am sorry for creating this issue, it should not be created in this repository. All other Appwrite and Utopia-PHP have this issue created.
