### ISSUE TITLE
📚 Documentation: The issues forms all have the word "Bug", even if it is a feature or documentation request

### ISSUE THREAD

**Issue by Christian-Oleson** [appwrite/appwrite#1828]
### 💭 Description

The github issues forms all have the word "Bug", even if it is a feature or documentation request. This can be confusing to the user who is attempting to report a feature request or documentation request.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct
- 
![10-1-2021 1-41-09 PM](https://user-images.githubusercontent.com/54334220/135671043-e0c45c2d-0c98-4f91-930f-20a80422fb1e.png)

![10-1-2021 1-45-35 PM](https://user-images.githubusercontent.com/54334220/135671432-b9b84f61-24ca-4d29-85d4-d43230d1b4fa.png)

**Comment by Christian-Oleson** [comment]
I could not assign myself by I am glad to take this issue and resolve it on my own.

**Comment by arvinf07** [comment]
So what is the goal here?

**Comment by kkhitesh** [comment]
Can I work on this?

**Comment by Christian-Oleson** [comment]
> So what is the goal here?

To correct the English here for clarity

**Comment by divyanshkul** [comment]
Is this still up for grabs? I can take this up

**Comment by akashchouhan16** [comment]
@stnguyen90 @Christian-Oleson Hey, if this is yet to be worked on, I'm more than willing to take this up! 👨🏻‍💻

**Comment by Haimantika** [comment]
Hi @Christian-Oleson thanks for raising this issue, I have raised a PR. It should be merged soon :)
