### ISSUE TITLE
📚 Documentation: Missing Instructions to Stop the Appwrite Docker Instance

### ISSUE THREAD

**Issue by shadowshot-x** [appwrite/appwrite#1837]
### 💭 Description

It is always a good practice to add the instructions or commands to stop the instance of running software. I could not find the instructions to do a clean kill for appwrite on the documentation page and also by googling.

As Appwrite only uses Docker, so, I killed all the running containers to stop the instance. As docker containers may keep running in the background, appwrite will be up even when a developer is not using it. Adding stopping instructions will help beginners who don't have knowledge of docker to gain more control of the resources of their system.

I used this to stop the running containers on Ubuntu:-
`$ docker kill $(docker ps -q)`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by shadowshot-x** [comment]
Also, I will be happy to contribute to this issue if feasible

**Comment by eldadfux** [comment]
Feel free to add the new section on our installation page: https://appwrite.io/docs/installation. You can add it just before the `Learn More` section. Please use the proper syntax for the code examples as used in the page, and proper English.

The relevant file to update is:
https://github.com/appwrite/docs/blob/main/app/views/docs/installation.phtml

Good luck, we're available on Discord for any questions: https://appwrite.io/discord

**Comment by shadowshot-x** [comment]
Thank You @eldadfux . I will get started on it.

**Comment by shadowshot-x** [comment]
I noticed all the containers started by this process begin with appwrite. So it would be sensible to stop the containers using 
`docker container stop $(docker container ls -q --filter name=appwrite*)`
This stops all the containers cleanly. I will be adding this in the documentation.

**Comment by eldadfux** [comment]
This section as recently added to the docs: https://appwrite.io/docs/installation

**Comment by gustawdaniel** [comment]
I was trying

```
docker container stop `docker container ls -q --filter name=appwrite`
```

but does not work. Finally I uninstalled by

```
docker rmi `docker images appwrite/appwrite -q` -f
```

**Comment by rayanfer32** [comment]
```
sudo docker stop $(sudo docker ps -aqf "name=^appwrite" | tr '\n' ' ')
```
