### ISSUE TITLE
🚀 Feature: UI/UX Flutter for OAuth providers

### ISSUE THREAD

**Issue by AhmedHammad0900** [appwrite/appwrite#1845]
### 🔖 Feature description

Hello Team.
Huge thanks for your efforts and time you are spending on that kind of projects .

I see you support a number of OAuth providers which is great but sadly the Auth is done through Browser which show apps  less professional for example Firebase provide Custom UI in app so you can easly login by just Choosing your Google Account that already used on your device .
![firebase](https://user-images.githubusercontent.com/81931290/135719405-4c3bb965-78f9-4a09-8574-248e087c3228.png)

But if browser is used the user maybe need to reset his password that he didn't used to use along time ago as it's already logged in his device .

I Know it will take a hard effort to do that for Flutter and other Sdks for every oAuth provider but at least you can provide this for most used OAuth methods which for sure Google is the most one maybe Facebook is second one ... you have the statics to decide from where you will start .

So hope You put that in consider in next versions if it's possible .

### 🎤 Pitch

This will increase the community users of Appwrite as no one cares what developer use as back-end but when front-end is touched and become less professional that can force back-end developer to switch for another backend-provier

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by eldadfux** [comment]
This will be a huge effort for all SDKs and create a lot of unwanted dependencies. What we can do is create a new method for providing an already obtained access token for creating an Appwrite session / user.

This way anyone who wants to can use the native provider SDK and still integrate with Appwrite.
