### ISSUE TITLE
🐛 Bug Report: "Feature" issue template tries to add a non-existent label

### ISSUE THREAD

**Issue by DiFronzo** [appwrite/appwrite#1850]
### 👟 Reproduction steps

1. Click on "issues" in this repo
2. Click on "New issue"
3. Click "Get started" on "🚀 Feature"

### 👍 Expected behavior

Adds the label "feature" (maybe "enhancement" had been a better option??)

### 👎 Actual Behavior

Adds the label "feature" that does not exist.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by divyanshkul** [comment]
Is this still up for grabs? Would love to work on this 
CC: @DiFronzo

**Comment by lohanidamodar** [comment]
Should now be fixed.
