### ISSUE TITLE
🚀 Feature: Custom scrollbar

### ISSUE THREAD

**Issue by KarishmaVanwari** [appwrite/appwrite#1870]
### 🔖 Feature description

Custom scrollbar that matches with the website.

### 🎤 Pitch

I think that the custom scrollbar would help enhance the look of the website.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by KarishmaVanwari** [comment]
Hey, I would like to work on this issue as a part of Hacktoberfest 2021, if its seems okay. Please assign me this issue.

**Comment by eldadfux** [comment]
Hey @KarishmaVanwari, thanks for the suggestion, but we would skip any design related issues at this point. Please feel free to suggest other issues or to pick one of the available ones. If you need any help, our team can assist on Discord: https://appwrite.io/discord
