### ISSUE TITLE
Help by improving Appwrite's GitHub topic 📡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1888]
# Introduction

GitHub topics let you create a place to share repositories, issues and pull requests from multiple repositories with the same topic. This helps with building a community focused on a specific tool, technology or programming language. We have [Appwrite topic](https://github.com/topics/appwrite) setup and active, but we forgot to add some information about the topic 🤭 Could you help us?

Your task is to improve Appwrite's GitHub topic by providing additional information about Appwrite. To do this, you need to write a pull request to [github/explore](https://github.com/github/explore) repository and add `topics/appwrite` folder with all of the information. If you ever get stuck, you can read GitHub official [contributing guide](https://github.com/github/explore/blob/main/CONTRIBUTING.md) or take a look at existing configured topics, for example [topics/angular](https://github.com/github/explore/tree/main/topics/angular).

Let's see it in action... This is our current topic page:

![CleanShot 2021-10-05 at 08 53 48](https://user-images.githubusercontent.com/19310830/135974510-fbe726f5-77ba-4079-83c6-7484ed936993.png)

Now let's see what Angular's looks like:

![CleanShot 2021-10-05 at 08 54 04](https://user-images.githubusercontent.com/19310830/135974723-b43ac1bc-7c1b-4958-98f3-77f629b6e0d1.png)

As you can see, there is a bunch of additional information on the Angular GitHub topic and we would love if you implemented these components into our topic 😇

---

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by GunjanDhanuka** [comment]
Hey! Can I work on this? I know I have another issue assigned to me but that is going to take some time to complete 😅. I am good at documentation and would love to take this on and complete this one first! 🎉 @Meldiron

**Comment by Meldiron** [comment]
@GunjanDhanuka Assigned it to you! All the best 🚀

**Comment by eldadfux** [comment]
Good luck @GunjanDhanuka! You can reach out for help here or on Discord if you need something.
https://appwrite.io/discord

**Comment by GunjanDhanuka** [comment]
My PR was merged on the GitHub Explore repo [here](https://github.com/github/explore/pull/2658) :tada: . Now for this to add to one of my submissions for Hacktoberfest and Appwrite Exclusive contributions, I will have to make a PR to this issue! What PR should I make inorder to do that? :thinking:

**Comment by eldadfux** [comment]
Yeh, no need for another PR this will be good enough for your Appwrite count 👌

**Comment by GunjanDhanuka** [comment]
> > This is where you can see the work in action! [appwrite](https://github.com/topics/appwrite) tada rocket
> 
> @GunjanDhanuka  Wow great job. It's looking pretty
> ![image](https://user-images.githubusercontent.com/6360216/136323106-6c46703f-4891-450c-acd9-fef3761cb7f2.png)
> 
> I don't think you will need a separate PR, that PR should count as valid 1 contribution for Appwrite, do keep that PR in record, team might ask you later to submit your list of PRs

Yeah actually the Hacktoberfest dashboard shows the Explore as "Project not participating". And the issue here is tagged "hacktoberfest". So inorder for this to count towards my overall Hacktoberfest contributions I will have to make a PR for this issue on Appwrite's repo and have it merged. 

Only then would Hacktoberfest acknowledge this as a contribution.

**Comment by lohanidamodar** [comment]
@GunjanDhanuka you can submit a PR to our https://github.com/appwrite/awesome-appwrite repository with the link to the topic.

**Comment by GunjanDhanuka** [comment]
> @GunjanDhanuka you can submit a PR to our https://github.com/appwrite/awesome-appwrite repository with the link to the topic.

Done! :heavy_check_mark:

**Comment by eldadfux** [comment]
Thank you @GunjanDhanuka
