### ISSUE TITLE
🚀 Feature: Protect endpoint 

### ISSUE THREAD

**Issue by binhodev** [appwrite/appwrite#1928]
### 🔖 Feature description

Hello everyone!
Would you like to know if it is possible to protect the endpoint(server) from malicious users/scans? Like AppCheck (Firebase) which blocks requests from outside your app.

### 🎤 Pitch

This is interesting to check if the user is running an authentic and unhandled app, if not, backend resources are blocked for invalid apps.

Thanks!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TafadzwaD** [comment]
This is currently available in AppWrite 😀. For your application to be able to interact with the AppWrite endpoint you first need to add the bundle ID of your application under Platforms in the AppWrite console. You can read more on this link https://appwrite.io/docs/getting-started-for-flutter. So requests are blocked from outside your application.

**Comment by binhodev** [comment]
> This is currently available in AppWrite grinning. For your application to be able to interact with the AppWrite endpoint you first need to add the bundle ID of your application under Platforms in the AppWrite console. You can read more on this link https://appwrite.io/docs/getting-started-for-flutter. So requests are blocked from outside your application.

@TafadzwaD Thanks for explantion.

**Comment by leohxj** [comment]
does this supported in web app? how to prevent other request not from my own domain?

**Comment by TafadzwaD** [comment]
@leohxj Yes it is supported in Web App as well. In the console when you add a web platform you specify an IP address or the domain of your web app. Therefore, only the white-listed web application will be able to access your endpoint. Appwrite has you covered!! https://appwrite.io/docs/getting-started-for-web#addPlatform
