### ISSUE TITLE
📚 Documentation: Update the code in https://appwrite.io/docs/getting-started-for-flutter#fullExample

### ISSUE THREAD

**Issue by 1995YogeshSharma** [appwrite/appwrite#1985]
### 💭 Description

The code snippets in [getting started with flutter](https://appwrite.io/docs/getting-started-for-flutter#fullExample) do not enclose the code part in `void main()`.
Because of this, the code does not show expected results when replicated in local setup. Let's update the code part.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
@1995YogeshSharma Added hacktoberfest label 😇

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!
