### ISSUE TITLE
🐛 Bug Report: Unable to see signup screen

### ISSUE THREAD

**Issue by ramdevcm** [appwrite/appwrite#1995]
### 👟 Reproduction steps

After installation : http://localhost/auth/signup/

### 👍 Expected behavior

Signup form

### 👎 Actual Behavior

empty fields

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

![Screenshot from 2021-10-06 15-55-23](https://user-images.githubusercontent.com/68838234/136185890-b81470b2-6ce8-42c7-a74e-56136aeca8f3.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ramdevcm** [comment]
This works on google chrome.

**Comment by lwj1994** [comment]
> This works on google chrome.

no ..   it dosn't work on my chrome and safari  .it is a bug

**Comment by lwj1994** [comment]
![image](https://user-images.githubusercontent.com/10978048/153141798-1795d1a2-ecbf-4e8f-a971-0fb4e59fe151.png)
