### ISSUE TITLE
🚀 Feature:  Translate Appwrite into Shona language

### ISSUE THREAD

**Issue by TafadzwaD** [appwrite/appwrite#2006]
### 🔖 Feature description

**Introduction**

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the X-Appwrite-Locale header? 😮 We already support 56 languages and need your help to push it even further! 💪

The task is to translate Appwrite into Shona language. You can find a complete in-depth tutorial in our official tutorial for adding translations.

Tasks summary:

- [ ]   Fork & clone Appwrite
- [ ]  Generate translations for Shona in app/config/locale/translations/zu.json
- [ ]   Add language as supported into app/config/locale/codes.php, if not already presented
- [ ]   Add language as supported into app/init.php, if not already presented
- [ ]    Test the translations
- [ ]   Push changes and submit a pull request
- [ ]  If you need any help, reach out to us on our Discord server.

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

Happy Appwriting!

### 🎤 Pitch

Shona speakers will be able to use their language on AppWrite..

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by thet3o** [comment]
Can you assign this issue to me?

**Comment by Meldiron** [comment]
PR has been submitted and labelled `hacktoberfest-accepted`, so we can close this issue 👏👏
