### ISSUE TITLE
[DISCUSSION] Discord VS. Gitter

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#201]
I have been approached by a few members of our community and asked to consider moving the community chat from Gitter to Discord.

I wanted to get some of your opinions about the changes and whether we should make it.

In my own opinion, I love the way Gitter integrates with Github. I think Gitter lacks some more advanced features, and the UI doesn't feel as good as it can be. I have also tried installing the Gitter app for iOS but had no success logging in.

Discord seems to the more popular chat tool for communities right now and does offer excellent and cross-platform UI and apps with some cool and advanced features.

I really love to know what you think about this one.

**Comment by RizkyRajitha** [comment]
i've used discod , for more that one year ,  and for that time i had no problem with it . very little server down . and also it is more user friendly than gitter . and you  have voice chat if you want . and share files easily.

**Comment by BogDAAAMN** [comment]
I was also thinking about Slack since they have GitHub integrations.

**Comment by chimon2000** [comment]
I like Discord a lot more than Gitter.  Slack is also an option seeing as how a lot of devs may already be required to use it for work.

**Comment by doyle-mark** [comment]
Please choose Discord, it's by far the best option and most intuitive..

**Comment by Kiy4h** [comment]
@BogDAAAMN The downside in Slack is that they don't save ancient messages (you need to buy the premium version to do that), unlike Discord.
You can also set up a Github integration.

Setting up will take some time, but it'll be worth it!

**Comment by priyank04** [comment]
I would agree with @Kiy4h that Slack lacks the capability of showing the ancient messages and that's where Discord wins. Now as you want to switch platform for chat purposes than Discord is far better than Gitter.
You will have the right to create unlimited channels (not possible in gitter - free), users, and history (wins over slack). At times you require voice chat to have a topic discussed as chatting through text could waste a lot of time, at that instance Discord is the Saviour again.

Haven't used gitter for long but I just remember that it had only basic functionalities and strong Github integration (now all three discussed here have this functionality) and was kinda poor designed but it's counterpart, Discord, has a very mature look. The only cons of Discord I feel is inability to archive channels.

**Comment by eldadfux** [comment]
What channels do you think we should have as a community (regardless of the platform we will use)? @chimon2000 @BogDAAAMN @Kiy4h @RizkyRajitha  @priyank04 @doyle-mark @christyjacob4

**Comment by eldadfux** [comment]
Hey @chimon2000 @RizkyRajitha @priyank04 @doyle-mark - we have just opened our new Discord server and you are welcome to join us!

This is the invite URL:
https://discord.gg/GSeTUeA

![image](https://user-images.githubusercontent.com/1297371/67453395-3edbd180-f62f-11e9-9d44-8f12b3ce7544.png)

**Comment by RizkyRajitha** [comment]
i joined @eldadfux  . thanks for the invite 🙌
