### ISSUE TITLE
Getting annoying error in console 

### ISSUE THREAD

**Issue by vencho-mdp** [appwrite/appwrite#2011]
Whenever I enter the following command in ubuntu

```bash
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.10.4
```

I get this error

```bash
Warning: yaml_parse(): reading error encountered during parsing: control characters are not allowed (line 1, column 1) in /usr/src/code/src/Appwrite/Docker/Compose.php on line 20
```

And I can't figure out why. Could you help me?

**Comment by stnguyen90** [comment]
This indicates there is something malformed in your docker-compose.yml file. Can try to use this [YAML Lint](http://www.yamllint.com/) to check your docker-compose.yml file?

**Comment by eldadfux** [comment]
@TorstenDittmann I think we should add a try-catch block for this warning.
