### ISSUE TITLE
Should we add an eslint for the js part?

### ISSUE THREAD

**Issue by AlphaWong** [appwrite/appwrite#203]
I find that the js part do not have any eslint yet. Can I add an eslint for it ?
If it is ok. I will create a PR

**Comment by eldadfux** [comment]
Sorry for the late reply. We had a big discussion about this (https://github.com/appwrite/appwrite/issues/7) and decided to use prettier for code formatting. I really want to integrate this process into our CI as part of any pull request. If you think you can help with us, please let me know.

You can also reach our on our Discord server:
https://discord.gg/GSeTUeA
