### ISSUE TITLE
🐛 Bug Report: Footer is unresponsive from 531px to 456px

### ISSUE THREAD

**Issue by ORKO06** [appwrite/appwrite#2131]
### 👟 Reproduction steps

When I was inspecting the website I found out that the footer is unresponsive from 531px to 456px .

### 👍 Expected behavior

The logos would have been in a new line.

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/74568847/136482681-3be601d8-a70e-4f9c-9bba-db1246473ca3.png)

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by sapora1** [comment]
![image](https://user-images.githubusercontent.com/59124772/136510971-49109726-5612-4c39-a458-a8e83d83906e.png)
