### ISSUE TITLE
📚 Documentation: Make add-translations.md beginner-friendlier

### ISSUE THREAD

**Issue by RReiso** [appwrite/appwrite#2157]
### 💭 Description

Hello.
I suggest adding the sentence in **bold** in the 'Test the translations section' in [add-translations.md](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md). Like so:

 ## 4. Test the translations
 First of all, we need to start a local instance of Appwrite. Thanks to Docker, this can be done using one command. **Before running the command make sure you have [Docker](https://www.docker.com/products/docker-desktop) installed on your machine:**
 ```
 $ docker-compose up -d
```
......................................................................................
Alternatively, this could be mentioned in prerequisites.

As Appwrites [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md) aims to make the project a welcoming environment, regardless of level of experience, I think this would make it easier for beginners to contribute with their translations.
I am a beginner programmer and a beginner open source contributor myself, this would have helped me a lot. I read the Contributing guide, but, considering my level of experience, it was not clear to me.:heart: 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by DilanAnuruddha** [comment]
Can I work on this?
