### ISSUE TITLE
🐛 Bug Report: /appwrite folder is not created when running docker command

### ISSUE THREAD

**Issue by m1ga** [appwrite/appwrite#2160]
### 👟 Reproduction steps

Running the `get started` script **as user** on my Linux machine:
```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.10.4
```
I'll end up with `Error: statfs /home/tmp/appwrite: no such file or directory`. I have to manually create the `appwrite` folder in order to run the docker image.

### 👍 Expected behavior

folder should be created automatically or it should be mentioned in the guide that it is necessary before running the script.

### 👎 Actual Behavior

The following error appears: `Error: statfs /home/tmp/appwrite: no such file or directory`

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Fedora Linux 34
Kernel 5.14.9
podman version 3.4.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I think this is a problem with your file system or local environment rather than appwrite. When you try to mount a folder that doesn't exist, docker will make that folder for you. 

From the [docker docs](https://docs.docker.com/storage/bind-mounts/):

> The file or directory does not need to exist on the Docker host already. It is created on demand if it does not yet exist.

Additionally, I ran the following:

```shell
docker run --rm --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw hello-world
```

and the appwrite folder was created as expected.
