### ISSUE TITLE
🐛 Bug Report: File preview is stretched when viewing on mobile

### ISSUE THREAD

**Issue by m1ga** [appwrite/appwrite#2164]
### 👟 Reproduction steps

Upload a file and open the preview.
When you open the file preview on a small screen the image is stretched. See screenshot below.

### 👍 Expected behavior

Image shouldn't be stretched:
![Screenshot_20211009_011541](https://user-images.githubusercontent.com/4334997/136633819-01d71407-66d9-454c-8779-543b86a4c993.png)

### 👎 Actual Behavior

![Screenshot_20211009_011518](https://user-images.githubusercontent.com/4334997/136633815-4640d1a9-8856-4f3b-85fa-50906d50e9dc.png)

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Firefox 92

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by m1ga** [comment]
It can be fixed by adding
`object-fit: contain` to
https://github.com/appwrite/appwrite/blob/613684aefa498c5180d659261aae734a5fc83fb0/public/styles/forms.less#L407-L415


If you want me to do it please assign me to this ticket and I'm happy to apply the patch

**Comment by eldadfux** [comment]
@m1ga I have assigned you, feel free to reach out if you need any help 👍
