### ISSUE TITLE
🐛 Bug Report: https://appwrite.io/docs/getting-started-for-web#nextSteps

### ISSUE THREAD

**Issue by heristhesiya** [appwrite/appwrite#2167]
### 👟 Reproduction steps

https://appwrite.io/docs/getting-started-for-web#nextSteps link is not working

### 👍 Expected behavior

https://appwrite.io/docs/getting-started-for-web#nextSteps link is not working 

### 👎 Actual Behavior

https://appwrite.io/docs/getting-started-for-web#nextSteps link is not working because when I click on the next steps but it reloads itself.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

no

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by MOHAMMAD-F** [comment]
Unsubscribe

**Comment by sapora1** [comment]
![image](https://user-images.githubusercontent.com/59124772/136663311-62f3d5b6-8706-468f-88a6-fa20d983485c.png)

I think it is written below that next step is to explore the reference documents. "Next Steps" is a topic.

**Comment by AR10X** [comment]
Shouldn't it be mentioned as 'Learn more' instead of 'Next steps'? It sounds better, Doesn't it?

**Comment by eldadfux** [comment]
@AR10X We can change it to learn more if you're willing to submit a PR and change all the "getting started" tutorials to match this pattern, Otherwise, this anchor link behaves as intended.

**Comment by sapora1** [comment]
Yeah can I do it??

**Comment by AR10X** [comment]
@eldadfux But I just realized there is a section named ```Learn more```
![image](https://user-images.githubusercontent.com/59757602/137575185-53174938-a002-4dd4-961d-88752c67c240.png)
How do I proceed? Would you want all the ```Next steps``` in the getting started tutorial to be changed to ```Learn more``` and link to the learn more section or link to just the section below the heading? 
![image](https://user-images.githubusercontent.com/59757602/137575519-636fe472-95f9-44b7-83c8-17256f64da80.png)
