### ISSUE TITLE
📚 Documentation: Add a Contributor's Wall

### ISSUE THREAD

**Issue by Rutam21** [appwrite/appwrite#2181]
## Description

A contributor's wall is a specific section that can be added to the Readme or any other suited place as deemed appropriate by the maintainers that would show the Github profile pictures along with their names who contribute to this repository. This is a great way to keep in sync with the contributor list and would be treated as a form of recognition as well.

## Suggestion

We can use [contributors-img](https://contrib.rocks/) tool to generate a dynamic image link that shows the above said section. It would look something like this,

<a href="https://github.com/appwrite/appwrite/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=appwrite/appwrite" />
</a>

Made with [contributors-img](https://contrib.rocks).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
We had something like this in the past. The main repo has ~200 contributors which make the readme load extremely slow, and make it very long. We have create https://appwrite.io/community to include top contributors from all repos toghther.
