### ISSUE TITLE
🔄 Refactor suggestion: Norwegian language redundancy/translation duplication

### ISSUE THREAD

**Issue by NeonSpork** [appwrite/appwrite#2195]
### 🔖 Feature description

In the translated languages there is Norwegian *bokmål* and plain Norwegian, represented by `nb.json` and `no.json` respectively. In a separate pull request currently undergoing review I have added Norwegian nynorsk (`nn.json`). The translations in "Norwegian" (`no.json`) and "Norwegian bookmål" (`nb.json`) are virtually identical, and arguably represent the same language/translation.

Without getting too detailed, there are only two forms of Norwegian, bokmål and nynorsk. Bokmål is by _far_ the most popular form, hence it usually being referred to as just "Norwegian" rather than the full name.

### 🎤 Pitch

Since the translation is duplicated and present in both "Norwegian" and "Norwegian bokmål", I humbly propose that `no.json` be removed in addition to removing the `No` country code and translation option in `init.php`, etc., such that `nb.json` remains.

This would be more consistent with conventional ISO coding of the Norwegian language when both forms are present, abbreviated as NB and NN for Norwegian bokmål and nynorsk respectively. Additionally it would remove an unnecessary duplicated translation.

I would be more than willing to work on these changes.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by NeonSpork** [comment]
I would be more than willing to work on these changes, would appreciate being assigned this issue. :)

**Comment by NeonSpork** [comment]
@christyjacob4 Should I remove the reference to the `"code" => "no"` from `languages.php` as well?

**Comment by Meldiron** [comment]
Added Hacktoberfest label so it counts towards Hacktoberfest contributions 😇
