### ISSUE TITLE
SSL Invalid Certificate

### ISSUE THREAD

**Issue by BiswajitKrPaul** [appwrite/appwrite#2196]
I have added a domain and verified it. The SSL certificate also got generated, It was working fine. But today I just restarted the Digital Ocean droplet , after that the certificate is showing issue and SSL is INVALID. 

The below logs are for docker-compose logs appwrite-worker-certificates

appwrite-worker-certificates    | Appwrite certificates worker v1 has started
appwrite-worker-certificates    | [notice] Starting worker ae6f10ed3e34:6:v1-certificates
appwrite-worker-certificates    | [notice] Starting work on (Job{v1-certificates} | ID: 1cb39ead0c6e2dc8fc7b71fdd5c60ba4 | CertificatesV1 | [{"document":[],"domain":"Mydomain","validateTarget":false,"validateCNAME":false}])
appwrite-worker-certificates    | [notice] (Job{v1-certificates} | ID: 1cb39ead0c6e2dc8fc7b71fdd5c60ba4 | CertificatesV1 | [{"document":[],"domain":"Mydomain","validateTarget":false,"validateCNAME":false}]) has finished
root@appwrite-ubuntu-s-1vcpu-1gb-blr1-01:~/appwrite# docker-compose logs appwrite-worker-certificates
Attaching to appwrite-worker-certificates
appwrite-worker-certificates    | Appwrite certificates worker v1 has started
appwrite-worker-certificates    | [notice] Starting worker ae6f10ed3e34:7:v1-certificates
appwrite-worker-certificates    |
appwrite-worker-certificates    | Fatal error: Uncaught RedisException: Connection lost in /usr/src/code/vendor/colinmollenhour/credis/Client.php:1171
appwrite-worker-certificates    | Stack trace:
appwrite-worker-certificates    | #0 /usr/src/code/vendor/colinmollenhour/credis/Client.php(1171): Redis->ping()
appwrite-worker-certificates    | #1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php(265): Credis_Client->__call('ping', Array)
appwrite-worker-certificates    | #2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(180): Resque_Redis->__call('ping', Array)
appwrite-worker-certificates    | #3 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
appwrite-worker-certificates    | #4 {main}
appwrite-worker-certificates    |
appwrite-worker-certificates    | Next CredisException: Connection lost in /usr/src/code/vendor/colinmollenhour/credis/Client.php:1189
appwrite-worker-certificates    | Stack trace:
appwrite-worker-certificates    | #0 /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php(265): Credis_Client->__call('ping', Array)
appwrite-worker-certificates    | #1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(180): Resque_Redis->__call('ping', Array)
appwrite-worker-certificates    | #2 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
appwrite-worker-certificates    | #3 {main}
appwrite-worker-certificates    |
appwrite-worker-certificates    | Next Resque_RedisException: Error communicating with Redis: Connection lost in /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php:268
appwrite-worker-certificates    | Stack trace:
appwrite-worker-certificates    | #0 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(180): Resque_Redis->__call('ping', Array)
appwrite-worker-certificates    | #1 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
appwrite-worker-certificates    | #2 {main}
appwrite-worker-certificates    |   thrown in /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php on line 268

**Comment by kodumbeats** [comment]
These logs don't tell me much - all I can see is that when `appwrite-worker-certificates` started, Redis wasn't ready yet, so the startup is full of stack traces.

I would recommend restarting the individual container, inspect the logs to make sure the Redis errors are gone, and retrigger the SSL creation with:
```
docker-compose exec appwrite ssl
```

**Comment by brianmutiso** [comment]
> These logs don't tell me much - all I can see is that when `appwrite-worker-certificates` started, Redis wasn't ready yet, so the startup is full of stack traces.
> 
> I would recommend restarting the individual container, inspect the logs to make sure the Redis errors are gone, and retrigger the SSL creation with:
> 
> ```
> docker-compose exec appwrite ssl
> ```

thanks, helped resolve my long term problem

**Comment by zdanl** [comment]
I'm still having this issue. It vanished a couple of days ago, but now it's back.

Fresh docker install.l
