### ISSUE TITLE
Some comments from a user

### ISSUE THREAD

**Issue by yossi-eynav** [appwrite/appwrite#22]
@eldadfux great project!

Some notes: 
1. I would like to see some use cases for every feature
2. How would you recommend to deploy it to production? on top of k8? AWS ECS ? 
Maybe some docs on that?
3. How would the uploaded files be persistent?  I would want to upload it to AWS / GCP instead of docker volume.
4. Just an Idea-  maybe you can have some build in integrations with Cloudinary for instance? 
5. Cloud functions & Realtime features?

**Comment by eldadfux** [comment]
1. We are working really hard on improving our documentation all the time. Just last week we added and fixed a lot of things. We will surely get more examples and better knowledge base as time goes. If you have any specific issue just raise it up here, on our gitter community or on 'Appwrite Developers' group on Facebook.

2. Appwrite is trying to be un-opinionated and technology agnostic really hard. Potentially you can deploy it on any cloud with any orchestrator you like. That said, there is a plan to release an article about best practices for production very very soon. In the meantime there is some information on this topic in our gitter community.

3. Currently we only support locally mounted paths. This shouldn't be an issue with any cloud provider. Anyway, if you will take a pick at our source code you will be able to see that we have plans to support more storage adapters other then the default local one.

4. As I mentioned, we are trying really hard to be un-opinionated and technology agnostic about your stack and choices. You can easily integrate Cloudinary in front of our storage endpoint just like you would with any other CDN-like solution and this will actually would work pretty well. But before you do that, take a look at our [file preview endpoint](https://appwrite.io/docs/storage#getFilePreview) that have some very nice Cloudinary-like features.

5. This is definitely something we are looking at as it matches our vision perfectly. I would like us to talk more about this as I would love to gather more feedback on the topic.
