### ISSUE TITLE
🐛 Bug Report: NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by BiswajitKrPaul** [appwrite/appwrite#2203]
### 👟 Reproduction steps

1. I have configured my .env file with my domain.

_APP_DOMAIN=mydomain
_APP_DOMAIN_TARGET=mydomain

2. Restarted the containers.
3. Added the custom domain, but failed to verify the custom domain.
4 I can access my appwrite console by domainaddress , but its showing a NET::ERR_CERT_AUTHORITY_INVALID error.

### 👍 Expected behavior

It should run on https with valid SSL.

### 👎 Actual Behavior

It is throwing a NET::ERR_CERT_AUTHORITY_INVALID error. 

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
How did you add the custom domain in step 3?

Also, please check this steps that might help resolve or debug the issue: https://gist.github.com/eldadfux/eb3ed1c4e5f43b7f7259469dd29312c5

**Comment by stnguyen90** [comment]
> The limit has been reached now.
> 
> appwrite-worker-certificates | Appwrite certificates worker v1 has started appwrite-worker-certificates | [notice] Starting worker 214eeb0573ca:7:v1-certificates appwrite-worker-certificates | [notice] Starting work on (Job{v1-certificates} | ID: a2419d79e0fa9c92c0f78ce3d2757ff6 | CertificatesV1 | [{"document":[],"domain":"biswajitappwrite.site","validateTarget":false,"validateCNAME":false}]) appwrite-worker-certificates | [critical] (Job{v1-certificates} | ID: a2419d79e0fa9c92c0f78ce3d2757ff6 | CertificatesV1 | [{"document":[],"domain":"biswajitappwrite.site","validateTarget":false,"validateCNAME":false}]) has failed Exception: Failed to issue a certificate with message: Saving debug log to /var/log/letsencrypt/letsencrypt.log appwrite-worker-certificates | An unexpected error occurred: appwrite-worker-certificates | There were too many requests of a given type :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: biswajitappwrite.site: see https://letsencrypt.org/docs/rate-limits/ appwrite-worker-certificates | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details. appwrite-worker-certificates | in /usr/src/code/app/workers/certificates.php:131 appwrite-worker-certificates | Stack trace: appwrite-worker-certificates | #0 /usr/src/code/src/Appwrite/Resque/Worker.php(22): CertificatesV1->run() appwrite-worker-certificates | #1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform() appwrite-worker-certificates | #2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform() appwrite-worker-certificates | #3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job)) appwrite-worker-certificates | #4 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false) appwrite-worker-certificates | #5 {main}

What was the custom domain you set in your appwrite console compared to the domain in your env file?

Also, would you please provide the contents of /var/log/letsencrypt/letsencrypt.log in the appwrite-worker-certificates container?
