### ISSUE TITLE
🐛 Bug Report: Setting boolean default value to true does not persist in Admin UI

### ISSUE THREAD

**Issue by JohannesKlauss** [appwrite/appwrite#2223]
### 👟 Reproduction steps

Create a Collection over Admin UI, add a `boolean` field and set the default Value to be `true` (activate switch toggle).
Then the JSON says the default value is set to `true`, but switch toggle is deactivated. Updating it again without touching anything will result in the default value set to be `false`.

### 👍 Expected behavior

The default value toggle switch should be bound to the default value 

### 👎 Actual Behavior

The default value toggle switch is always set to `false` and will override the `true` value on update.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by kodumbeats** [comment]
This should be now fixed with [Appwrite 0.12](https://github.com/appwrite/appwrite/releases) :D
