### ISSUE TITLE
📚 Documentation:  Add a other issues template 

### ISSUE THREAD

**Issue by qwel-exe** [appwrite/appwrite#2247]
### 💭 Description

this helps when someone wants to Conway something which does not go under bug or documentation or a teacher feature

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Closing this for now as unless there is a specific use case we prefer to keep issues structured.
