### ISSUE TITLE
🐛 Bug Report: Rules still exists in existing documents

### ISSUE THREAD

**Issue by generalxhd** [appwrite/appwrite#2265]
### 👟 Reproduction steps

1. Create a rule
2. Create a document
3. Delete the rule
4. Open the document that you have created in step 2 and view the json. You can see the rule still exists in this document and you're unable to update the document

### 👍 Expected behavior

It should remove the rule with the values from the documents when a rule was deleted.

### 👎 Actual Behavior

The rule is hidden in the gui, but is still in the json. Also I'm unable to update the document because it has a bad structure.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This is now fixed as part of the work on Appwrite 0.12 and is waiting for release.

**Comment by eldadfux** [comment]
I'll keep this open to make sure we update the issue when the version is available.

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
