### ISSUE TITLE
📚 Documentation: Page not formatted correctly (Android Docs)

### ISSUE THREAD

**Issue by inomag** [appwrite/appwrite#2314]
### 💭 Description

The [Getting Started for Android](https://appwrite.io/docs/getting-started-for-android) documentation is not formatted correctly.
![screencapture-appwrite-io-docs-getting-started-for-android-2021-10-20-17_29_53](https://user-images.githubusercontent.com/66073063/138089426-3595abc4-5580-43c6-b154-fb990b53c001.jpg)

Tried the page on a different device. The same issue occurred.
![WhatsApp Image 2021-10-20 at 17 57 15](https://user-images.githubusercontent.com/66073063/138092554-1b9cf93d-3a22-4b1e-9d18-684a08c289db.jpeg)

I guess, it is occurring due to ```<p>``` in line 30 & 48 of [Getting started](docs/sdks/android/GETTING_STARTED.md)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by hardiksachan** [comment]
I can take a look. Plz assign this to me
