### ISSUE TITLE
How to restart AppWrite?

### ISSUE THREAD

**Issue by davedawkins** [appwrite/appwrite#2322]
I've edited `/root/.env` and so need to restart AppWrite. `docker ps` shows many containers; do I just need to restart the main one (`AppWrite`), or all of them? Is there a one-liner for a restart?

Sorry to ask via the Issue trcker, but I've searched docs, issues and google

Thank you

**Comment by hardiksachan** [comment]
I use `docker-compose up -d`. You can read more about it in the [docs](https://appwrite.io/docs/environment-variables)

**Comment by davedawkins** [comment]
Thank you. A bit embarrassed I didn't see that.
