### ISSUE TITLE
🐛 Bug Report: Storing Object generated multiple $id & null $collectionfor each level of object tree 

### ISSUE THREAD

**Issue by iamdineshkumar** [appwrite/appwrite#2323]
### 👟 Reproduction steps

When I created a rule of a field with wildcard as type to hold an object. it generated $id,$collection as null & $permission as empty array for each level of object values. This also have impact during upgrading of appwrite when $collection is null.

For an example
If I store following object in a field

`{
    "isReadable": true,
    "appleStock": {
        "price": 10,
        "available": 9,
        "purchasePrice": 5
    },
    "orangeStock": {
        "price": 10,
        "available": 9,
        "purchasePrice": 5
    }
}`

### 👍 Expected behavior

Expected to get field value as 
`{
    "isReadable": true,
    "appleStock": {
        "price": 10,
        "available": 9,
        "purchasePrice": 5
    },
    "orangeStock": {
        "price": 10,
        "available": 9,
        "purchasePrice": 5
    }
}`

### 👎 Actual Behavior

Actual getting field value as
`{
    "$id": "611cc31a91b86",
    "$collection": null,
    "$permissions": [],
    "isReadable": true,
    "appleStock": {
        "$id": "611cc31a922fb",
        "$collection": null,
        "$permissions": [],
        "price": 10,
        "available": 9,
        "purchasePrice": 5
    },
    "orangeStock": {
        "$id": "611cc31a938b0",
        "$collection": null,
        "$permissions": [],
        "price": 10,
        "available": 9,
        "purchasePrice": 5
    }
}`

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Something else

### 🧱 Your Environment

I just [justcloudify.com](https://justcloudify.com) with docker container

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
This should be resolved with the new database service 👍🏻

**Comment by iamdineshkumar** [comment]
Hi @TorstenDittmann  in present version there is no field type to store json object. Can you please share recommended way to store json object in new database service?
