### ISSUE TITLE
🐛 Bug Report: Migrations are very slow

### ISSUE THREAD

**Issue by saibotma** [appwrite/appwrite#2345]
### 👟 Reproduction steps

My appwrite project has around 53000 users. 
The migration from 0.7 to 0.8 took more than an hour. The system was not available during this time and my users could not log in to the app.

### 👍 Expected behavior

Migrations only taskes seconds. Users can use appwrite during the migration.

### 👎 Actual Behavior

Migration takes an hour.

### 🎲 Appwrite version

Version 0.8.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Using an external MySQL database.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
I have submitted a PR to the docs, adding this information.

https://github.com/appwrite/docs/pull/132

**Comment by saibotma** [comment]
Thanks a lot! Nevertheless there is no option to migrate without downtime?

**Comment by eldadfux** [comment]
Nothing built-in yet. I'd suggest to migrate on a separate machine, and handles the data deltas manually or stop writes. This is going to be addressed soon as we also work on a solution for the Appwrite Cloud.

**Comment by TorstenDittmann** [comment]
This should be fixed now with all Migrations following 0.12 and got fixed with the 0.13 release 🙏🏻
