### ISSUE TITLE
📚 Documentation: Have to execute migrations between minor version releases (0.9.0 → 0.9.4)?

### ISSUE THREAD

**Issue by saibotma** [appwrite/appwrite#2349]
### 💭 Description

Hey there, the documentation is not clear about whether I must run migrations between minor version jumps like 0.9.0 → 0.9.4.
Additionally, it remains unclear if I am allowed to jump from 0.9.0 to 0.9.4 directly or have to upgrade from 0.9.0 → 0.9.1 → 0.9.2 → 0.9.3 → 0.9.4.

This is especially important to know as migrations take very long on big datasets as shown in #2345 and should thus only be executed when downtime is communicated to the end-users. However, important hot fix releases that just bump minor versions should be able to be upgraded with no (or just minor) downtime.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Migrations only need to be done when upgrading minor versions (0.8.X -> 0.9.X). A patch update (0.9.0 -> 0.9.4) does not require executing the migration.

The documentation could be improved to clarify this.

**Comment by gewenyu99** [comment]
<img width="972" alt="Screen Shot 2022-05-20 at 11 25 50 AM" src="https://user-images.githubusercontent.com/29069505/169560999-5217b9dc-59ea-4f15-8e77-11743e0f08c9.png">

Hi folks, this has been noted prominently in docs now. Sorry for the delay!
