### ISSUE TITLE
🐛 Bug Report: Filter collections with boolean value

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#2351]
### 👟 Reproduction steps

i tried to filter a boolean value:
```
    bool status = true;
    List<dynamic>? osFilter = [];
    osFilter.add("status=$status");
    DocumentList result =
       await db!.listDocuments(collectionId: collectionId, filters: osFilter);
```
i think appwrite interpretes it as a string.. but due to collection rule it could know that it is a boolean and could handle it :)

### 👍 Expected behavior

all documents from collection with status = true should be returned

### 👎 Actual Behavior

0 documents are returned

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Looks like you can filter for true with `status=1` and false for `status=0`.

**Comment by s3ppo** [comment]
Ah super thanks for the info 👍

**Comment by eldadfux** [comment]
> Ah super thanks for the info 👍
> 
> the question now is: will it stay this way or will i have to refactor it once new appwrite version with new database is released 😉

The new DB refactor will introduce some breaking changes as listed here: https://gist.github.com/kodumbeats/d0f8d8305b28f1b3f3d52f0ada358551

Important to mention that older versions will continue to be supported, and we'll provide a migration process for all data.

**Comment by stnguyen90** [comment]
With the new 0.12.X [Queries](https://appwrite.io/docs/database#querying-documents), you can filter on boolean with `attribute.equal(true)` or `attribute.equal(false)`. 

For SDKs still on 0.11, the old `attribute=1` or `attribute=0` filters no longer work. Appwrite 0.12.0 has a bug in which `attribute=true` or `attribute=false` doesn't work. With Appwrite 0.12.1, `attribute=true` and `attribute=false` should work.

**Comment by kiloki-official** [comment]
Does it mean we can't use attribute=true/false at all in 0.12? How can I upgrade to 0.12.1? Thanks

**Comment by kiloki-official** [comment]
I upgraded to 0.12.1 and I still have the same attribute=false/true problem.

**Comment by stnguyen90** [comment]
> I upgraded to 0.12.1 and I still have the same attribute=false/true problem.

It should be working. Feel free to reach out on discord if you're having trouble still.
