### ISSUE TITLE
🐛 Bug Report: cloud functions with Dart 2.14 runtime not working

### ISSUE THREAD

**Issue by Silfalion** [appwrite/appwrite#2353]
### 👟 Reproduction steps

- Create a small functions that prints hello world in dart.
- push it to the function worker
- execute the function

### 👍 Expected behavior

Prints hello world

### 👎 Actual Behavior

empty stdout and stderr

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

uses 0.11 version

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TafadzwaD** [comment]
@Silfalion under the function's setting there is a `Timeout` field. Dart is quite slow when it comes to cloud functions so you can increase the timeout to prevent the function from being terminated before completion, the default is 15 seconds and the maximum is 900 seconds
<img width="1218" alt="gitboy" src="https://user-images.githubusercontent.com/28431370/139533747-21354dfb-6e7f-4e88-8fad-731a8cb186d3.png">

**Comment by Silfalion** [comment]
@TafadzwaD already increased it to the limit of 900. What did the trick temporarily for now is to add prints to the functions with a future return type. It seems like that the code really awaits until it completes.

**Comment by Silfalion** [comment]
Apparently the issue is dart 2.14 not liking imports of libraries not from pub.dev. deleting the imports makes the code execute. But I can't work without the package. Any idea about this please?

**Comment by TafadzwaD** [comment]
Which version of AppWrite are you on??

**Comment by Silfalion** [comment]
0.11

**Comment by TafadzwaD** [comment]
@lohanidamodar Kindly assist on this one..

**Comment by Silfalion** [comment]
@TafadzwaD I think he may be waiting for the release of version 0.12 to solve everything in one go.

**Comment by TafadzwaD** [comment]
@Silfalion Maybe that might be case.. So hang in there buddie 😅😅😅

**Comment by Silfalion** [comment]
Will do haha Thank you very much for your assistance!

**Comment by TafadzwaD** [comment]
You're most welcome 😀

**Comment by Silfalion** [comment]
:) So did some more testing, tested on a french install of 0.11 and on a fresh install on 0.12 on two different machines. And both give the same result. Thanks to drake we found something. When executing into the function's container and running dart bin/main.dart and it returns Killed. I'm very lost at this behavior.

**Comment by lohanidamodar** [comment]
@Silfalion Here is my test result.
1. Package from local directory works perfectly fine
2. package from git, works fine
3. Your package- gets killed
so my guess is it's issue with trying to take too much of memory. Try working by assigning largest possible memory to test it and then bring it down.

However, I also suggest few things
1. Don't try to do too many things in same function, you should have different functions to handle different things
2. Functions should only work on small short one time tasks, should not take long
3. Dart function is already heavy, boil it down as much as possible
4. May be compile and run compiled output, that should be much faster

**Comment by Silfalion** [comment]
On point recommendations. Was thinking about it since I need quicker responses for this function in particular. Will give them a try and see how it goes. Thank you so much.
