### ISSUE TITLE
[BUG] Database UI doesn't update on click

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#236]
### What's the issue
I came across a minor UI issue while using the appwrite dashboard. The Collection preview doesn't show up automatically when selecting a collection. The page needs to be refreshed for it to show up, as seen in the screenshots.

Also, Once a preview has shown up, when you select another collection, the preview doesn't update and the page needs to be refreshed again.  

### Steps to reproduce
1) Select A project on the appwrite dashboard
2) Click the Database Navbar Option
3) Click on any collection

### Expected Behaviour
![test1](https://user-images.githubusercontent.com/20852629/67614048-61a6eb00-f7d3-11e9-8d2d-e820ffa93b71.png)

### Actual Behaviour
![test](https://user-images.githubusercontent.com/20852629/67614047-6075be00-f7d3-11e9-8990-731417a555a9.png)

### Possible Fix
The onClick Listener must be having some issue

### Configuration
1) Appwrite v0.3.0
2) Chrome Version 76.0.3809.132 (Official Build) (64-bit)

I would like to work on this issue.

**Comment by eldadfux** [comment]
@christyjacob4 I can't seems to reproduce this bug on the master branch, any chance you can give it another look?

![image](https://user-images.githubusercontent.com/1297371/72333434-730dde00-36c4-11ea-8d42-e3f5f64c27ef.png)

**Comment by christyjacob4** [comment]
Okay @eldadfux i will give it another look and update

**Comment by eldadfux** [comment]
@christyjacob4 did you had any chance to take a look at this?

**Comment by eldadfux** [comment]
Closing this issue, 0.6 or 0.7 should have a new DB UI anyway.
