### ISSUE TITLE
🚀 Feature: Include database settings available in "Update Rule" for "Add rule"

### ISSUE THREAD

**Issue by lyqht** [appwrite/appwrite#2363]
### 🔖 Feature description

In an already created Rule, we see the options to make the rule "required" or an "array", and also insert a default value.

![image](https://user-images.githubusercontent.com/35736525/139070871-41cd415f-7f92-43de-9c54-ebc7c78cfe60.png)

However, when we create a property, we don't see these options

![image](https://user-images.githubusercontent.com/35736525/139240578-f6b3d1e0-fc59-4c52-9012-92e62b64a92d.png)

### 🎤 Pitch

I would like the create popup to contain the same options as when we update an existing rule. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
0.12 changed a lot of the DB concepts and replaced rules with attributes. Please feel free to post a new issues if this is still relevant.
