### ISSUE TITLE
Add darkmode to appwrite

### ISSUE THREAD

**Issue by Kolkies** [appwrite/appwrite#237]

**Comment by eldadfux** [comment]
I will add this feature to our roadmap. I guess it will be released shortly after 1.0.0.

**Comment by eldadfux** [comment]
First preview 🎺
![image](https://user-images.githubusercontent.com/1297371/73352988-0e917800-429b-11ea-9903-b4588dd98fee.png)

This feature might be available sooner than 1.0+, 0.6-0.7 might be a realistic timeframe.

**Comment by eldadfux** [comment]
This is ready and available on the master branch. This will be included in the 0.5 release.
