### ISSUE TITLE
🚀 Feature: Please add a Scroll Indicator Progress Bar. It looks quite attractive 😄 

### ISSUE THREAD

**Issue by VanshajPoonia** [appwrite/appwrite#2371]
### 🔖 Feature description

It is like a bar that fills as the user scrolls down the website. It looks quite attractive.

### 🎤 Pitch

This feature has a lot of uses. The first one is that the user knows how big is the website and other things is that it looks quite attractive.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by sarakaandorp** [comment]
Hey @VanshajPoonia,  

UX/UI Designer at Appwrite here :) Thank you for your suggestion, we appreciate it!  

A scroll indicator bar can indeed be an interesting UI pattern, you mostly see it in blogpost articles. It gives you an indication of the length of the article, as some articles can be long and time consuming.

At the moment though, I don’t really see a place on the Appwrite website where this would have enough value for the visitor.  

I’ll definitely keep this UI pattern in mind in case we need it somewhere in the future.

  Thank you again :)
