### ISSUE TITLE
🚀 Feature: Prevent email address harvesting

### ISSUE THREAD

**Issue by ralienpp** [appwrite/appwrite#2372]
### 🔖 Feature description

Appwrite should be more _discrete_ during the password recovery workflow. Currently, it says "password recovery failed" (or that it was successful) making it possible to harvest email addresses.

![image](https://user-images.githubusercontent.com/295338/139534577-fedcc132-b394-472c-82ee-8db2ecbfa831.png)

Though one could argue it is not a major security issue, it is often the first step in a more elaborate attack.

A proposed alternative is to say "We have tried to send the instructions to the address you provided, please check your email". This text neither confirms nor denies the existence of the given address.

### 🎤 Pitch

This is a good security practice, and it will propagate to all the systems built on top of Appwrite.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Hey Alex, thanks for using Appwrite and sending this feedback. I would argue and say this is not a small security issue.
We must have a true/false indication for success or failure on this API to allow proper usage by devs and to allow UIs to have some representation to the state of the operations.

We did limit this endpoint for 10 attempts per hour for each email, which was originally designed to block abuse of a specific user. Obviously this is not bullet proof, and will not stop an harvesting attack. To add extra protection can add an an IP limit alongside the email one. This will make an harvesting attack VERY expensive and not worthwhile.

In this line we can add support for array of abuse keys to check multiple factors for abuse: https://github.com/appwrite/appwrite/blob/master/app/controllers/api/account.php#L1736

We should probably also make sure the documentation site knows to explain multiple abuse rules vs. a single key rule.

**Comment by eldadfux** [comment]
This was fixed and released as part of Appwrite 0.12!
@ralienpp thanks for raising the issue!
