### ISSUE TITLE
Can't Upload Big Files ...

### ISSUE THREAD

**Issue by AhmedHammad0900** [appwrite/appwrite#2378]
I already increased max file size to 500 MB from env .. tested on 67 MB file and worked...  but didn't work on 138 MB File .. 
I built my App for Courses Videos purpose ( Worked for a months on that no way to back ) 

Logs Says that's Out Of memory while server is using 0.5% of it's 16 GB Ram

![image](https://user-images.githubusercontent.com/81931290/139661648-18e9488e-2d0f-45e4-85db-240dc2fab060.png)

The logs : -

`Worker 1 started succefully
Worker 2 started succefully
Worker 4 started succefully
Worker 5 started succefully
Server started succefully (max payload is 500,000,000 bytes)
Master pid 1, manager pid 9
Worker 3 started succefully
Worker 6 started succefully

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 171430024 bytes) in /usr/src/code/src/Appwrite/OpenSSL/OpenSSL.php on line 23
[2021-11-01 10:29:40 *14.0]     ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 171430024 bytes) in /usr/src/code/src/Appwrite/OpenSSL/OpenSSL.php on line 23
[2021-11-01 10:29:40 $9.0]      WARNING Server::check_worker_exit_status(): worker(pid=14, id=0) abnormal exit, status=255, signal=0
Worker 1 started succefully
[Error] Timestamp: 2021-11-01T10:59:53+00:00
[Error] Method: GET
[Error] URL: /
[Error] Type: Utopia\Exception
[Error] Message: Not Found
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 708
`

why there is a limit of memory usage while anyone can hit the limit at any time ? :/ 
is there a way I can increase limits for that ??
---
Appwrite Version: 0.11.0.170

**Comment by ekol-tech** [comment]
How can i am . I am a victim.

Ekrem Yılmaz
iPhone’umdan gönderildi

**Comment by stnguyen90** [comment]
This is a PHP memory limit set here https://github.com/appwrite/appwrite/blob/0e91b67528d10716ea328421577e8a2f71e427b3/app/init.php#L14

The current workaround would be to either modify the file as part of the container startup or mount a file with a bigger limit.

**Comment by eldadfux** [comment]
We do have a work in progress to enable big files upload. You can check it here: https://github.com/appwrite/appwrite/pull/1383 - it should be in a pretty advanced stage, @lohanidamodar has already started adding support for this on multiple SDKs.

**Comment by stnguyen90** [comment]
> We do have a work in progress to enable big files upload. You can check it here: #1383 - it should be in a pretty advanced stage, @lohanidamodar has already started adding support for this on multiple SDKs.

@eldadfux, I don't see that `memory_limit` updated in the PR so the problem might still persist after that PR is megered.

**Comment by lohanidamodar** [comment]
> > We do have a work in progress to enable big files upload. You can check it here: #1383 - it should be in a pretty advanced stage, @lohanidamodar has already started adding support for this on multiple SDKs.
> 
> @eldadfux, I don't see that `memory_limit` updated in the PR so the problem might still persist after that PR is megered.

We don't need to increase memory_limit as we will be handling large files in chunks and reading in stream, so with the upcoming large file support we should be able to support handling file size that storage like S3 support. We will definitely have more updates regarding this soon.

**Comment by AhmedHammad0900** [comment]
> > > We do have a work in progress to enable big files upload. You can check it here: #1383 - it should be in a pretty advanced stage, @lohanidamodar has already started adding support for this on multiple SDKs.
> > 
> > 
> > @eldadfux, I don't see that `memory_limit` updated in the PR so the problem might still persist after that PR is megered.
> 
> We don't need to increase memory_limit as we will be handling large files in chunks and reading in stream, so with the upcoming large file support we should be able to support handling file size that storage like S3 support. We will definitely have more updates regarding this soon.

So excited for this update , hope u a good luck <3

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻
