### ISSUE TITLE
🐛 Bug Report: supporting flutter web OAuth

### ISSUE THREAD

**Issue by Silfalion** [appwrite/appwrite#2384]
### 🔖 Feature description

This feature consists in adding temporarily a modified flutter web auth package to the flutter sdk of appwrite with an implementation that makes OAuth works. 

### 🎤 Pitch

Right now OAuth doesnt work on flutter web, which is caused by the flutter_web_auth package not supporting it the option. A PR has been added to the repo it's been already 6 months. But no signs that it's going to be added. I contacted the dev but no response as well.

Seeing as how this is a huge hindrance I'd like to publish a package that is a direct copy of flutter_web_auth on pub.dev that contains the PR itself. As a temporary solution. My question is would the appwrite team be willing to use it instead of flutter_web_auth? Promise there will not be anyting sneaky with the code lol.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Silfalion** [comment]
This is even more valid considering this is used in production environments as mentioned here:
https://github.com/LinusU/flutter_web_auth/pull/77

**Comment by lohanidamodar** [comment]
@Silfalion Regarding Web auth OAuth for Flutter+Appwrite, it should already be handled by Appwrite, you don't need the support on Web auth package we use. If you provide the proper success and error URL in your call to `createOAauth2Session()` the URL being your Flutter web application, Appwrite should redirect you back to appropriate URL already.
(For Android/iOS this is not required, yet you can provide and handle the redirection to app yourself, so instead you can check if(kIsWeb) and provide success and failure url only then)

You must add your `success` and `failure` URL host as web platform on Appwrite console.

If this doesn't resolve your issue feel free to reopen and provide reproducible code and examples.

Thank you 🙏🏻

**Comment by Silfalion** [comment]
@lohanidamodar Since the creator of flutter_web_auth didn’t answer back I forked both his repo and appwrite sdk for flutter today. The solution worked, just needs some adjustments. Would you be willing to accept a PR once I publish the new package?

**Comment by lohanidamodar** [comment]
@Silfalion my first suggestion will be open a PR also in the flutter_web_auth repository. Rest I'll discuss with team and we can have further discussions. We love the great work you are doing, as well as we should look out for long term solution. Will be back with further information. Do open PRs and let us know.

**Comment by Silfalion** [comment]
Will do so, thank you:) The main advantage of this is that the method calls and everything are still the same, so if I'm able to keep the same package name as the flutter_web_auth when publishing it'll be swappable with the original package in case the creator starts accepting PRs again.

Otherwise it'll be just a small refactor. Either way the package doesn't change almost anything to the issue.

Will go forth with the publishing and let you know.

**Comment by lohanidamodar** [comment]
@Silfalion Good news, we have decided to maintain the official Fork
https://github.com/appwrite/flutter_web_auth to better serve our needs. I would love for you to raise your PRs against our fork so that we can officially serve it. And would love your help in making it better 🙏🏻

**Comment by Silfalion** [comment]
@lohanidamodar Awesome!!!! It'll be my very pleasure to help maintain it. I'm still a little unfamiliar with the repo itself but should get warmed up to it pretty soon. 

I'll submit a PR in a few.

**Comment by lohanidamodar** [comment]
Should be fixed by
https://github.com/appwrite/sdk-generator/pull/325
