### ISSUE TITLE
🚀 Feature: Rotation in Storage preview should support nagive numbers

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2387]
### 🔖 Feature description

Currently, rotation only supports 0 to 360, but it should work with -360 to 360 and Appwrite should do the simple math.

### 🎤 Pitch

Its way more developer-friendly to see -6 instead of 354.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Don't see the harm, could be pretty useful and easy to implement. Any takers for this issue? @Meldiron?

**Comment by codingsamurai-10** [comment]
Can I take this issue?

**Comment by eldadfux** [comment]
@codingsamurai-10 I have assigned you to the issue. This is the line needs to be updated:
https://github.com/appwrite/appwrite/blob/master/app/controllers/api/storage.php#L250

We should also add a test for negative values here after the existing `/preview` tests:
https://github.com/appwrite/appwrite/blob/master/tests/e2e/Services/Storage/StorageBase.php#L42

**Comment by eldadfux** [comment]
Leaving this issue open until the release of Appwrite 0.12 which will include this update.

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
