### ISSUE TITLE
📚 Documentation:  How generate  _APP_OPENSSL_KEY_V1 ? 

### ISSUE THREAD

**Issue by TSCSOftware** [appwrite/appwrite#2391]
### 💭 Description

how generate a unique key and set it as the value of the _APP_OPENSSL_KEY_V1 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This is just an arbitrary string used as a passphrase for the encryption/decryption.

**Comment by TSCSOftware** [comment]
thank you  @stnguyen90
