### ISSUE TITLE
🚀 Feature: Allow user creation with a specific UID.

### ISSUE THREAD

**Issue by sanny-io** [appwrite/appwrite#2396]
### 🔖 Feature description

Firebase allows developers to easily use their own auth service and integrate it with Firebase's own auth system.

https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk

> The Firebase Admin SDK has a built-in method for creating custom tokens. At a minimum, you need to provide a uid, which can be any string but should uniquely identify the user or device you are authenticating.

### 🎤 Pitch

I'm using an auth service that already provides a UID. There is no email or password involved. I want to integrate this with Appwrite, but from what I see, Appwrite requires an email and password. Integrating this with Firebase is easy because it doesn't require anything else.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Hey @sanny-io, we are already working on a custom ID feature that is already in very advanced stages, and could even be released in the next Appwrite version. This will allow you to set a custom ID for any Appwrite resource including a collection, document, file, function and user. 

More info available in this RFC: https://github.com/appwrite/rfc/blob/main/018-custom-id-support.md

Does this help solve your use-case?

**Comment by sanny-io** [comment]
Yes sir that looks perfect. Thank you.

**Comment by sanny-io** [comment]
I'm actually not sure if I should close this or not, haha. Close if appropriate.

**Comment by eldadfux** [comment]
We can leave it open until the feature is released :)

**Comment by eldadfux** [comment]
This feature is ready, and is expected to be released with Appwrite 0.12.

**Comment by cloudoftg** [comment]
any ETA on this release, as I am not able to launch my app just due to lack of custom document id

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b

**Comment by eldadfux** [comment]
@sanny-io have you tried using anonymous login? https://appwrite.io/docs/client/account?sdk=web-default#accountCreateAnonymousSession

**Comment by sanny-io** [comment]
@eldadfux this would not work for me as I need accounts to be permanent and linked to a specific identifier. Are there any plans to support UID authentication?
