### ISSUE TITLE
🐛 Bug Report: Function shows exit status 124 if using Promise.all()

### ISSUE THREAD

**Issue by YaMiSt** [appwrite/appwrite#2399]
### 👟 Reproduction steps

I created a function in appwrite with node.js, which make some requests to appwrite team and database. For that i used a Promise.all(). If I use that I always got an exit code 124 (timeout). Do I have to return something, that appwrite noticed the function is finished, or do I have to solve that on another way? Without I have no problem with the functions, but I have 4 requests, which I want to request at the same time.

```
const client = new sdk.Client();
    client
      .setEndpoint(APPWRITE_ENDPOINT)
      .setProject(APPWRITE_PROJECT)
      .setKey(APPWRITE_API_KEY);
const teams = new sdk.Teams(client);
const users = new sdk.Users(client); 
Promise.all([
      teams.getMemberships(TEAM_1_ID, undefined, 100),
      teams.getMemberships(TEAM_2_ID, undefined, 100),
      users.list(USER_ID)
    ]).then(res => {
        teams.createMembership(TEAM_1_ID, USER_ID, ['role:member'], REDIRECT_TO);
    });
```

### 👍 Expected behavior

A return state for appwrite if the function is finished?

### 👎 Actual Behavior

Always get an timeout after the defined time in the function.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Please edit the Title of the issue to be more descriptive and fix the formatting of our code block to use 3 back ticks for multi line code.

You shouldn't need any sort of return.

A couple of things regarding your code:

1. You don't need the `void` in front of the `Promise.all()`. 
2. Is it timing out because it's taking a while for all the network calls to finish?

**Comment by YaMiSt** [comment]
1. The void comes from our implementation. I removed it for the example
2. No i already tried with the max timeout in settings, but I get the same error. I do'nt think that it's took a while

**Comment by stnguyen90** [comment]
@YaMiSt can you retry with your firewall disabled?

**Comment by YaMiSt** [comment]
@stnguyen90 sorry for my late response. There is no firewall

**Comment by stnguyen90** [comment]
@YaMiSt, where do you have your appwrite instance running? Are you using http:// as the protocol with the redirect to HTTPS set?

Also, it might be easier to troubleshoot this on [discord](https://discord.gg/RHjYtrCA).

**Comment by YaMiSt** [comment]
Hi @stnguyen90, 

I found the bug. We redefined the variable teams, so it couldn't resolved. But in the log were no errors. We found in two other container logs what helped us to solve it.

Maybe it's a good idea to log all messages in the function container and not in other containers. (Yes, I know we have to improve our interfaces ;))
