### ISSUE TITLE
🐛 Bug Report: a wildcard property is serialized to string when the user updates a document from the backend

### ISSUE THREAD

**Issue by browasaki** [appwrite/appwrite#2402]
### 👟 Reproduction steps

1. Create a collection with 2 properties: the first one with a wildcard type and the second one with a boolean type; 
2. Persist a JSON object on the wildcard property;

Everything **works as expected**; the wildcard property is returned as a JSON from the API.

3. Go to the backend (CMS), edit the boolean property's value, and update the document;

Now the wildcard property is returned serialized into a string instead of JSON.

### 👍 Expected behavior

The wildcard property is always returned as a "wildcard" (in this case a JSON object).

### 👎 Actual Behavior

The wildcard property is returned serialized into a string.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Digital Ocean's droplet on Ubuntu.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
@browasaki Our database refactor does not include a wildcard validator - every attribute must have an assignable data type in the underlying database. This bug will be resolved in future versions of Appwrite, for now, please use `string` type and always serialize JSON objects before inserting them into a database. This approach will be the easiest to migrate into our DB refactor and will give you consistent behaviour.

I am keeping the issue open and will double-check if it is resolved once Appwrite version with a new database is released.

**Comment by browasaki** [comment]
Thanks @Meldiron for the quick response; when the database refactoring will be completed?

**Comment by TorstenDittmann** [comment]
This got resolved with the new Database Service 👏🏻
