### ISSUE TITLE
🐛 Bug Report: Delete Membership is not working with own user

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#2405]
### 👟 Reproduction steps

i use method ```await teams.deleteMembership(teamId: teamId, membershipId: membershipId);```
to remove my actually logged in user myself from a team. (if the user is an admin it works correct)

it throws an exception: ```Server error```
but it seems it is doing something -> the membership is deleted but not clean
- the wrong exception breaks coding logic
- overview in appwrite console shows more memberships that are really assigned:
<img width="855" alt="Bildschirmfoto 2021-11-10 um 22 21 49" src="https://user-images.githubusercontent.com/17125438/141195538-c804592c-876e-4215-bb82-f9d88601e259.png">
if you click on the team it finds just 3 memberships:
<img width="631" alt="Bildschirmfoto 2021-11-10 um 22 23 47" src="https://user-images.githubusercontent.com/17125438/141195674-02d99a5c-12ac-4556-9596-ec152ab2d698.png">

i found this in the logs:
```
[Error] Timestamp: 2021-11-10T21:05:56+00:00
[Error] Method: DELETE
[Error] URL: /v1/teams/:teamId/memberships/:membershipId
[Error] Type: Utopia\Exception
[Error] Message: Invite not found
[Error] File: /usr/src/code/app/controllers/api/teams.php
[Error] Line: 752
[Error] Timestamp: 2021-11-10T21:07:40+00:00
[Error] Method: DELETE
[Error] URL: /v1/teams/:teamId/memberships/:membershipId
[Error] Type: Appwrite\Database\Exception\Authorization
[Error] Message: Missing "write" permission for role "team:612c03384d698/owner". Only this scopes "["*","role:member","user:612bfb3f4b559","team:612c03384d698","team:612c03384d698\/member"]" are given and only this are allowed "["team:{self}\/owner"]".
[Error] File: /usr/src/code/src/Appwrite/Database/Database.php
[Error] Line: 279
[Error] Timestamp: 2021-11-10T21:43:24+00:00
[Error] Method: GET
[Error] URL: /v1/account
[Error] Type: Utopia\Exception
[Error] Message: User (role: guest) missing scope (account)
[Error] File: /usr/src/code/app/controllers/general.php
```

### 👍 Expected behavior

- no exception should be thrown
- Memberships from overview and details (Appwrite console -> Users -> Teams) should by synchron

### 👎 Actual Behavior

as described in Reproduction steps

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TheMardy** [comment]
I have the same issue with 0.11. I assumed the delete membership can be used for a member to "leave" the team. Is this not the case?

**Comment by stnguyen90** [comment]
I think this is the problem: https://github.com/appwrite/appwrite/blob/a1a4584095768f25b616ffa53bfee417c866c541/app/controllers/api/teams.php#L771

It tries to update the team, but the user doesn't have rights to update the team

**Comment by stnguyen90** [comment]
I just checked the db-alpha branch and this seems to still be a problem: https://github.com/appwrite/appwrite/blob/0b934c5e1dc52267eb31277c8251c0d93d496d05/app/controllers/api/teams.php#L797-L799

**Comment by s3ppo** [comment]
this problem is in 0.12 still here.
new docker log output is:
```
[Error] Timestamp: 2022-01-08T23:07:01+00:00
[Error] Method: DELETE
[Error] URL: /v1/teams/:teamId/memberships/:membershipId
[Error] Type: Utopia\Database\Exception\Authorization
[Error] Message: Missing "write" permission for role "team:61da10f4ada63ea88749/owner". Only this scopes "["role:all","role:member","user:61d8ae548b64f125c608","team:61da10f4ada63ea88749","team:61da10f4ada63ea88749\/member"]" are given and only this are allowed "["team:61da10f4ada63ea88749\/owner"]".
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 817
```
