### ISSUE TITLE
🐛 Bug Report: Update Account Email from the Account API does not send the new confirmation mail 

### ISSUE THREAD

**Issue by JaviBonilla** [appwrite/appwrite#2412]
### 👟 Reproduction steps

With the `Account API`:

- Update Account Email

### 👍 Expected behavior

According to the Account API [documentation](https://appwrite.io/docs/client/account?sdk=flutter-default#accountUpdateEmail):

- [x] Update email address
- [x] Reset user confirmation status
- [x] Send a new confirmation mail

### 👎 Actual Behavior

- [x] Update email address
- [x] Reset user confirmation status
- [ ] Send a new confirmation mail **(This is not done)**

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

- Flutter Appwrite 2.0.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
The docs here are misleading and should be fixed. The confirmation mail is decoupled from the actual update endpoint to allow each app its own behavior and authentication flows.

**Comment by eldadfux** [comment]
This was fixed and will be updated as part of the Appwrite 0.12 release.

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
