### ISSUE TITLE
🐛 Bug Report: No response from email in SECURITY.md

### ISSUE THREAD

**Issue by Haxatron** [appwrite/appwrite#2413]
### 👟 Reproduction steps

Hi there, I reported a potential security issue to the security@appwrite.io email as listed in the SECURITY.MD but did not receive any response.

In case, you did not receive it, the report is located here https://huntr.dev/bounties/7c1ad9a2-39d9-4e0d-84ff-ee6762066b78.
Only people with write permissions to the repository can review it. 🙂

### 👍 Expected behavior

-

### 👎 Actual Behavior

-

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
We'll check this ASAP. Thanks for reporting.
