### ISSUE TITLE
🐛 Bug Report: UI status does not update

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2415]
### 👟 Reproduction steps

- Create collection with 2 rules
- Save, Refresh website
- Open second rule and toggle required on/off. Text status will change properly
- Close second rule, open first one and delete it
- Open second rule again and try to toggle required on/off. Text status will no longer change

Video:

https://user-images.githubusercontent.com/19310830/141680585-fad9bad4-7846-4e36-bb53-e745187f9163.mp4

### 👍 Expected behavior

UI seems to lose reactivity and when toggling required on/off, it does not update status text.

### 👎 Actual Behavior

Status text should properly update.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite version: v:0.11.0.170
Private demo.appwrite.io hosting

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
I'm pretty sure this would be solved as part of #2103

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
