### ISSUE TITLE
🐛 Bug Report: orderType is switching in Appwrite console

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#2430]
### 👟 Reproduction steps

when viewing collections in appwrite console and you have more then 12 collections you have the option to go to page 2.
when you do that the collections are now ordered DESC... also when you go back to page 1

initialy collections are shown ASC

### 👍 Expected behavior

ordering should always be ASC

improvement idea: please add a field where you can input the number of collections you want to see on the screen... 12 seems now to be a fixed value

### 👎 Actual Behavior

it switches the ordering on pagination

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
Thank you for reporting this 👍🏻

**Comment by s3ppo** [comment]
thank you @TorstenDittmann this works fine now :)
