### ISSUE TITLE
Basic Auth in setEndpoint

### ISSUE THREAD

**Issue by tamaskan** [appwrite/appwrite#2435]
Is Basic Auth (  .setEndpoint( 'https://user:password@appwrite.domain/v1') ) working with Get/Post-Requests ?

**Comment by eldadfux** [comment]
No this is not supported. Feel free to pitch for this idea if you would like the core to consider it.

**Comment by tamaskan** [comment]
It's just that i don't like the idea of a publicly accessible api. Since i am apparently the first one to ask for basic auth, a standard user doesn't need it and i don't want to bother anyone. Thanks for your response and effort.
