### ISSUE TITLE
📚 Documentation:  Python list_documents arguments are incorrect.

### ISSUE THREAD

**Issue by mateusz-bak** [appwrite/appwrite#2443]
### 💭 Description

Arguments for list_documents in Python SDK are wrong.

In Python SDK code [link](https://github.com/appwrite/sdk-for-python/blob/master/appwrite/services/database.py#L122):
`def list_documents(self, collection_id, filters = None, limit = None, offset = None, order_field = None, order_type = None, order_cast = None, search = None):`

In Python SDK documentation they follow camel case:
orderField, orderType, orderCast

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
I see what you mean, I don't think we are generating the payload dynamically at the moment. @eldadfux ?
![image](https://user-images.githubusercontent.com/6360216/143993102-039a63e2-adfe-42c7-89b4-5960b7a1da55.png)

**Comment by eldadfux** [comment]
The params table in the docs represents the REST API param names, not the SDK one. This is true to all SDKs, is python the only one not using camelCase?

**Comment by lohanidamodar** [comment]
> The params table in the docs represents the REST API param names, not the SDK one. This is true to all SDKs, is python the only one not using camelCase?

So it seems at the moment. May be we should make it clear somehow, that these are the actual REST API param names and not SDK params (which i think Request heading should signify as well)

**Comment by eldadfux** [comment]
Maybe we can change the `Request` title to `HTTP Request`? and `Response` to `HTTP Response`?

**Comment by lohanidamodar** [comment]
> Maybe we can change the `Request` title to `HTTP Request`? and `Response` to `HTTP Response`?

Sounds like a plan to me

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
