### ISSUE TITLE
🐛 Bug Report: I cant sign in into google with my private IP ( FLUTTER )

### ISSUE THREAD

**Issue by tananga** [appwrite/appwrite#2444]
### 👟 Reproduction steps

Im using Flutter

This is my endpoint: static const String endpoint = 'https://192.168.0.73/v1';
(192.168.0.73) is my private IP which allows me to login into appwrite.
This is a fragment from documentation: When trying to connect to Appwrite from an emulator or a mobile device, localhost is the hostname for the device or emulator and not your local Appwrite instance. You should replace localhost with your private IP as the Appwrite endpoint's hostname. The problem is when I try to sign-in with google. It shows my an error message: Error 400: invalid_request device_id and device_name are required for private IP: https://192.168.0.73/v1/account/sessions/oauth2/callback/goo....

### 👍 Expected behavior

It should works

### 👎 Actual Behavior

It dont work :(

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by tananga** [comment]
I installed ngrok.com and it works, but It would be great to attach some tutorial how to do it without any 3rd party program. So far Im using free version of "ngrok" but I dont know how good this soulution will be in the future

**Comment by tananga** [comment]
Im used "ngrok" to make some workeround and it looks like Im made a progress. Now after I selected my google account in getting appwrite error: Missing Redirect URL

**Comment by tananga** [comment]
This is my endpoint: static const String endpoint =
      'https://29e9-2a02-...................-996c-588-2097.ngrok.io/v1';

And In google console Authorized redirect URIs I added both: 
https://29e9-...............-2097.ngrok.io/v1/account/sessions/oauth2/callback/google/61a16259aa5ef

and

http://29e9-..............-588-2097.ngrok.io/v1/account/sessions/oauth2/callback/google/61a16259aa5ef

After selecting a google account Im geting: "Missing Redirect URL" error

**Comment by tananga** [comment]
Now I can add user user via "google" but Im not redirected to app but Im landing on webpage with error: This page isnt working. I added activity part into Android Manifest. I need help of someone who is experienced.

**Comment by christyjacob4** [comment]
@tananga thank you for reporting this issue. I think we have some resources to help you out. 

We've written an OAuth Guide for Google which you can refer to. 
https://gist.github.com/christyjacob4/249841263f6cc0beb5b1ce8bf613b7c2

Please follow these steps and the accompanying video clips and let us know if this issue still persists. 🙂

**Comment by tananga** [comment]
Thank you @christyjacob4  :) I will follow your instructions and let you know if I made a progress.

**Comment by tananga** [comment]
@christyjacob4 I still have a problem. Right now I can create a user with my Google account but instead of being redirect to app appwrite.io website is opened with big text "Missing Redirect URL". But most intresting part is logs in ngrok:

GET /v1/account/sessions/oauth2/google/redirect               500 Internal Server Error                       
GET /v1/account/sessions/oauth2/google/redirect               301 Moved Permanently                           
GET /v1/account/sessions/oauth2/callback/google/61......a5ef 301 Moved Permanently                           
GET /v1/account/sessions/oauth2/google                        301 Moved Permanently                           
GET /v1/account/sessions/oauth2/google                        301 Moved Permanently

Of course I copied and pasted https://52b1-2........................7.ngrok.io/v1/account/sessions/oauth2/callback/google/61a16259aa5ef into Authorized redirect URIs in Google Cloud Platform

**Comment by tananga** [comment]
Problem solved thanks to @christyjacob4 and Discord user: Drake. If you follow this tutorial https://www.youtube.com/watch?v=Uds1dTdq2_s&list=PLUiueC0kTFqITusEntt8bjhm20hv30Fsa&index=14
your function oAuthLogin should looks like this:

```
Future oAuthLogin(String provider) {
    return _account.createOAuth2Session(
      provider: provider,
      success: "",
      failure: "",
    );
  }
```

If you dont put success and failure as empty string weird things happens.

Once again thank you @christyjacob4. If anyone have similar issue you can send me a message and I will try to help.

**Comment by christyjacob4** [comment]
Happy to help and thank you for leaving the solution here 🙏
