### ISSUE TITLE
Please invite me to the GitHub Organization

### ISSUE THREAD

**Issue by Jyoti-prakash-rout** [appwrite/appwrite#2446]
I'm a Web Dev enthusiast & a junior pursuing my Bachelors in Computer Science & Engineering. I'm interested in Web Devlopment, Machine Learning & DevOps & I enjoy learning new things & stuff as well as I'm a Frontend Devloper with experience building Dynamic & Static Web pages. I am always interested in learning the answers to how, why, and what relates to the Technologies around me.

I would like to grow my programming skills by doing lots of Open Source contributions. Looking forward to learning, collaborating, and growing as a community.

**Comment by eldadfux** [comment]
Please reach out on Discord. https://appwrite.io/discord
