### ISSUE TITLE
🐛 Bug Report: Discord icon

### ISSUE THREAD

**Issue by marpit19** [appwrite/appwrite#2447]
### 👟 Reproduction steps

Discord has updated its branding guidelines so it would be good to update the icon

![image](https://user-images.githubusercontent.com/54642576/143773817-2a745481-4ffa-40bd-a9ad-201d7ed0593f.png)

I could help with this minor change

### 👍 Expected behaviour

[Current Branding](https://discord.com/branding)

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/54642576/143773775-f6c2f40f-8d4a-42de-b26b-7ab65790da1d.png)

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by kitarp29** [comment]
@eldadfux If no one is working on it. I can do that

**Comment by TorstenDittmann** [comment]
This will be part of next release 👍🏻  Thanks for the report!

**Comment by marpit19** [comment]
> This will be part of next release 👍🏻 Thanks for the report!

can't wait for it!!

**Comment by eldadfux** [comment]
This fix is ready, and will deployed later today to https://appwrite.io. It will be available as part of Appwrite 0.12

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/146508798-2f603e45-a02f-486c-bfc9-97af6c8ea53f.png)

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b

**Comment by marpit19** [comment]
> This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b

will definitely look into the new release!!!
