### ISSUE TITLE
📚 Documentation: listDocuments with filters in PHP

### ISSUE THREAD

**Issue by kiloki-official** [appwrite/appwrite#2454]
### 💭 Description

I love appwrite but documentation is really poor.

Could you please show me a FULL example of how to use listDocuments on a database WITH filters in PHP.

Thanks

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
We are working to improve the DB service and the docs as part of version 0.12. You can see how the filters API will look for PHP in this example: https://warm-tray-285.notion.site/PHP-28916295d4134eb4ab1d222d79038182

More on the DB updates here: https://warm-tray-285.notion.site/Appwrite-0-12-Alpha-The-Database-Refactor-70f2c1d234394d9ab9d0d548fe5449bc

**Comment by jenniestrongbow** [comment]
Thanks for your reply. However, the example you gave does not deal with the  filters element (list elements). And that's what I need to learn to use in PhP. Thanks

**Comment by jenniestrongbow** [comment]
I just read this:

Filters for listDocuments and listCollections have been replaced with a new, more powerful syntax (OR queries, anyone?).

I'll test your demo. 

Thanks

**Comment by jenniestrongbow** [comment]
Does AppWrite offer full-text searches?

**Comment by eldadfux** [comment]
Yes, from 0.12 you can also define your own custom fulltext indexes.

**Comment by jenniestrongbow** [comment]
Good. Could you please give me an example/tutorial on how to do a full-text search in PhP? Thanks

**Comment by eldadfux** [comment]
@jenniestrongbow You can use the `Query::search()` method on attributes with proper fulltext index.

https://github.com/aw-tests/sdk-for-php/blob/e0f7955f8a6e53c774537f58796fa4927b57271c/src/Appwrite/Query.php#L98

**Comment by jenniestrongbow** [comment]
Great, thanks!

**Comment by jenniestrongbow** [comment]
When is version 0.12 public?

**Comment by christyjacob4** [comment]
0.12 will be released as soon as we have addressed the feedback from the community about the alpha release. 
Until then, you can participate in the alpha  🙂 
 https://discord.com/channels/564160730845151244/636818236310159360/917478703133523978

**Comment by kiloki-official** [comment]
Ok, thanks, I will participate in the alpha.
