### ISSUE TITLE
🐛 Bug Report: dart 2.14 not showing up as an env for functions on arm based machines

### ISSUE THREAD

**Issue by Silfalion** [appwrite/appwrite#2457]
### 👟 Reproduction steps

- add dart 2.14 as an environment to the .env file
- Docker-compose up -d in terminal
- Try to create a cloud function with a dart 2.14 env

### 👍 Expected behavior

To see the dart 2.14 env in the drop down list

### 👎 Actual Behavior

The new env doesnt show 

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Something else

### 🧱 Your Environment

Its an arm based machine (Oracle free tier)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I can confirm this is happening on my Raspberry Pi. I believe this is happening because the php-runtimes restricts the dart-2.14 runtime to x86: https://github.com/appwrite/php-runtimes/blob/0.6.0/src/Runtimes/Runtimes.php#L53

**Comment by Silfalion** [comment]
> I can confirm this is happening on my Raspberry Pi. I believe this is happening because the php-runtimes restricts the dart-2.14 runtime to x86: https://github.com/appwrite/php-runtimes/blob/0.6.0/src/Runtimes/Runtimes.php#L53

Yes, on the discord Drake also mentioned that

**Comment by Silfalion** [comment]
As Drake mentioned as well, upgrading appwrite's php runtime to 0.6.1 and appwrite to 0.11.1 would likely solve the problem. Wyt?

**Comment by lohanidamodar** [comment]
@Silfalion Thank you for reporting the issue, We work work on releasing the fixes.

**Comment by Silfalion** [comment]
My pleasure. Thank you for taking it into consideration on a week end. Really appreciate, my eyes went 👀 when I saw the release tag haha. Thanks again!

**Comment by Silfalion** [comment]
Any news as to when it'll be released, please?

**Comment by Silfalion** [comment]
@lohanidamodar sorry to bother you again. Is there any advancement on the branch, please? I can try to work on adding the finishing touches if that's necessary.

**Comment by eldadfux** [comment]
@lohanidamodar maybe we can quickly release v0.11.1, for this?

**Comment by Silfalion** [comment]
That'd be really really fantastic.

**Comment by Silfalion** [comment]
Sorry to be so annoying about though any idea when this will be released please? ^^'. I need it for a project. It's ok if it can't be for now, I can use local instead just, it's just to plan ahead.

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
