### ISSUE TITLE
Updates made with User API do not show up in client Realtime Account channel

### ISSUE THREAD

**Issue by outrelouxhe** [appwrite/appwrite#2469]
### 👟 Reproduction steps

When I update a user preferences using the server side User API, the updated user preferences do not show up in the client realtime account channel.

### 👍 Expected behavior

Account and Users API makes change to same data, so they should result in same realtime channel events.

### 👎 Actual Behavior

Updates made with the User API do not show up in the client realtime account channel

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
@TorstenDittmann  please take a look here

**Comment by stnguyen90** [comment]
@outrelouxhe is this still a problem?

**Comment by stnguyen90** [comment]
Closing as this should be resolved.
