### ISSUE TITLE
🐛 Bug Report: I setup my setup on AWS it follow 6th day to setup ssl but ssl setup did not work

### ISSUE THREAD

**Issue by ajitsinghkaler** [appwrite/appwrite#2479]
### 👟 Reproduction steps

wget https://gist.githubusercontent.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5/raw/44f849a868e748037f0121e5b8b379a2254f9716/.env
wget https://gist.githubusercontent.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5/raw/44f849a868e748037f0121e5b8b379a2254f9716/docker-compose.yml

setup .env
 _APP_DOMAIN=appwrite.ajitblogs.com
_APP_DOMAIN_TARGET=appwrite.ajitblogs.com
_APP_ENV=production
_APP_SYSTEM_SECURITY_EMAIL_ADDRESS=aj********aer0@gmail.com

docker-compose up -d

Logs :
docker-compose logs appwrite-worker-certificates
Attaching to appwrite-worker-certificates
appwrite-worker-certificates    | Appwrite certificates worker v1 has started
appwrite-worker-certificates    | [notice] Starting worker 8bf9c115f429:8:v1-certificates

docker-compose logs appwrite
Attaching to appwrite
appwrite                        | [Static Files] Loadded 109 files
appwrite                        | Worker 1 started succefully
appwrite                        | Server started succefully (max payload is 10,000,000 bytes)
appwrite                        | Master pid 1, manager pid 7
appwrite                        | Worker 2 started succefully
appwrite                        | [Error] Timestamp: 2021-12-10T14:04:56+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:05:04+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/projects
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (projects.read)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:05:04+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/projects
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (projects.read)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:05:05+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /console/version
appwrite                        | [Error] Type: Exception
appwrite                        | [Error] Message: Failed to check for a newer version
appwrite                        | [Error] File: /usr/src/code/app/controllers/web/console.php
appwrite                        | [Error] Line: 423
appwrite                        | [Error] Timestamp: 2021-12-10T14:05:05+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:05:05+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:07+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:12+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:14+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:15+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:16+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:16+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:17+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:17+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:17+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:18+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:18+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:23+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:29+00:00
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/account/sessions
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: Invalid credentials
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/account.php
appwrite                        | [Error] Line: 195
appwrite                        | [Error] Timestamp: 2021-12-10T14:08:35+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /console/version
appwrite                        | [Error] Type: Exception
appwrite                        | [Error] Message: Failed to check for a newer version
appwrite                        | [Error] File: /usr/src/code/app/controllers/web/console.php
appwrite                        | [Error] Line: 423
appwrite                        | [Error] Timestamp: 2021-12-10T14:09:57+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /console/version
appwrite                        | [Error] Type: Exception
appwrite                        | [Error] Message: Failed to check for a newer version
appwrite                        | [Error] File: /usr/src/code/app/controllers/web/console.php
appwrite                        | [Error] Line: 423
appwrite                        | [Error] Timestamp: 2021-12-10T14:10:32+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:20:25+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:20:28+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [2021-12-10 14:20:55 #1.2]	INFO	Server is shutdown now
appwrite                        | [Static Files] Loadded 109 files
appwrite                        | Server started succefully (max payload is 10,000,000 bytes)
appwrite                        | Master pid 1, manager pid 8
appwrite                        | Worker 1 started succefully
appwrite                        | Worker 2 started succefully
appwrite                        | [Error] Timestamp: 2021-12-10T14:21:12+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:21:21+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:21:21+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:21:21+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:21:25+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:21:59+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:23:21+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:23:40+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:24:04+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:25:37+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263
appwrite                        | [Error] Timestamp: 2021-12-10T14:34:27+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/account
appwrite                        | [Error] Type: Utopia\Exception
appwrite                        | [Error] Message: User (role: guest) missing scope (account)
appwrite                        | [Error] File: /usr/src/code/app/controllers/general.php
appwrite                        | [Error] Line: 263

### 👍 Expected behavior

ssl should be setup

### 👎 Actual Behavior

Ssl did ot setup

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 🧱 Your Environment

AWS- Ubuntu 20.04

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
I went ahead and tried to reproduce the problem:

- Buy 10$ DigitalOcean droplet and connect

```
$ ssh root@[IP]
```

- Install Docker

```
$ curl -fsSL https://get.docker.com -o get-docker.sh
$ sh get-docker.sh
$ docker --version
```

- Install Docker compose

```
$ curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
$ sudo chmod +x /usr/local/bin/docker-compose
$ sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
$ docker-compose --version
```

- Install library that fixes Docker in DigitalOceal droplet

```
$ apt-get -y install haveged
```

- Install Appwrite (the was issue was setup)

```
$ mkdir appwrite
$ cd appwrite
$ wget https://gist.githubusercontent.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5/raw/44f849a868e748037f0121e5b8b379a2254f9716/.env
$ wget https://gist.githubusercontent.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5/raw/44f849a868e748037f0121e5b8b379a2254f9716/docker-compose.yml
```

- Setup `.env` (the was issue was setup)

```
$ nano .env
# _APP_DOMAIN=test123.matejbaco.eu
# _APP_DOMAIN_TARGET=test123.matejbaco.eu
# _APP_OPTIONS_FORCE_HTTPS=enabled
# _APP_ENV=production
# _APP_SYSTEM_SECURITY_EMAIL_ADDRESS=matej@appwrite.io
```

- Start Appwrite

```
$ docker-compose up -d
```

- Visit Appwrite in Chrome (`http://test123.matejbaco.eu/`)

- Got `ERR_CERT_AUTHORITY_INVALID` as expected, clicked `Show advanced` and `Proceed to test123.mate...`

- Waited few minutes

- Opened Incognito Chrome and vislited `http://test123.matejbaco.eu/`

- Appwrite is now on HTTPS

![CleanShot 2021-12-10 at 16 14 13](https://user-images.githubusercontent.com/19310830/145596765-632e8512-3b1b-4d34-9f95-b91a198082a2.png)

---

Sadly, I was not able to reproduce the problem. The only difference I did is in `.env` I set `_APP_OPTIONS_FORCE_HTTPS=enabled`, but from our Discord conversation, I believe you tried that too.

Logs:
[logs.txt](https://github.com/appwrite/appwrite/files/7693679/logs.txt)


Key logs:

```
# Appwrite startup success
appwrite                        | [Static Files] Loadded 109 files
appwrite                        | Server started succefully (max payload is 10,000,000 bytes)
appwrite                        | Master pid 1, manager pid 8
appwrite                        | Worker 1 started successfully

# Worker startup success
appwrite-worker-certificates    | Appwrite certificates worker v1 has started
appwrite-worker-certificates    | [notice] Starting worker 2659c17b47f8:7:v1-certificates

# Appwrite fires request to generate certificate
appwrite                        | Issuing a TLS certificate for the master domain (test123.matejbaco.eu) in a few seconds...

# Worker generating certificate
appwrite-worker-certificates    | [notice] Starting work on (Job{v1-certificates} | ID: 50099fd51e1becaecf1ea05afe6e22a1 | CertificatesV1 | [{"document":{"$id":"61b36e9184e28","$permissions":{"read":[],"write":[]},"$collection":"certificates","domain":"test123.matejbaco.eu"},"domain":"test123.matejbaco.eu","validateTarget":false,"validateCNAME":false}])
appwrite-worker-certificates    | [notice] (Job{v1-certificates} | ID: 50099fd51e1becaecf1ea05afe6e22a1 | CertificatesV1 | [{"document":{"$id":"61b36e9184e28","$permissions":{"read":[],"write":[]},"$collection":"certificates","domain":"test123.matejbaco.eu"},"domain":"test123.matejbaco.eu","validateTarget":false,"validateCNAME":false}]) has finished
```

_Note: DigitalOcean droplet destroyed after test_

**Comment by Meldiron** [comment]
Looks like @ajitsinghkaler is using AWS Route 53 for routing and I don't have experience with that. I believe this is the source of the problem because it is a proxy in front of Appwrite. Keeping issue self-assigned and will discuss this setup internally to see if someone from Appwrite core team has experience with this problem.

**Comment by eldadfux** [comment]
Route53 is only handling DNS and should not affect the SSL certificate issuing. @ajitsinghkaler try to hit the server with an HTTP call using the browser or CURL. The SSL certificate will be generated on the first request accepted by the server. After the first call, you will be able to see some new logs on the certificates worker container.

**Comment by ajitsinghkaler** [comment]
It was fixed was happening because of blocked IP's
