### ISSUE TITLE
Rate Limit Question

### ISSUE THREAD

**Issue by malikdoksoz** [appwrite/appwrite#2480]
Can I change rate limits?  I want to increase some limits.

**Comment by eldadfux** [comment]
You can disable the rate-limits by setting the env key `_APP_OPTIONS_ABUSE` to `disabled`. This is not recommended for production apps, and is a feature that was designed for dev testing.

You can learn more about it here: https://appwrite.io/docs/environment-variables#general

**Comment by malikdoksoz** [comment]
Thank you for reply. What I want to say is to increase the limit value.

`This endpoint is limited to 10 requests in every 60 minutes per email address` for example set to 20 reqs

**Comment by eldadfux** [comment]
@malikdoksoz this is not available yet, you could introduce your use case in a new GitHub discussion to help the core team understands if this need to be a new feature.

**Comment by elishasmil3** [comment]
I'm using Vite application, how can I use env without prefix?
