### ISSUE TITLE
Certbot Challenge Failed

### ISSUE THREAD

**Issue by Rajdeep-TG** [appwrite/appwrite#2483]
I have started Appwrite on Port 5500 (non-SSL) and 5501 (SSL). I have added the A record pointing to the IP Address of the Server in my DNS Record and used vHosts to proxy the requests to the Domain and also used the domain in `_APP_DOMAIN` and `_APP_DOMAIN_TARGET` Environmental Variables. In the Project's Settings -> Custom Domain I've added the Domain Name and added the required CNAME records on DNS. But after verifying the TLS is on `In Progress`. When I checked the logs of `appwrite-worker-certificates` I found:
```
Appwrite certificates worker v1 has started
[notice] Starting worker bac01497e4f5:8:v1-certificates
[notice] Starting work on (Job{v1-certificates} | ID: 26d479e337c6582ef8c5f3220291fae6 | CertificatesV1 | [{"document":{"$id":"61b5f294683ed","$collection":"domains","$permissions":{"read":["team:61b5c3f7aa0f6"],"write":["team:61b5c3f7aa0f6\/owner","team:61b5c3f7aa0f6\/developer"]},"updated":1639314068,"domain":"appwrite.electron-store.org","tld":"org","registerable":"electron-store.org","verification":true},"domain":"appwrite.electron-store.org"}])
[critical] (Job{v1-certificates} | ID: 26d479e337c6582ef8c5f3220291fae6 | CertificatesV1 | [{"document":{"$id":"61b5f294683ed","$collection":"domains","$permissions":{"read":["team:61b5c3f7aa0f6"],"write":["team:61b5c3f7aa0f6\/owner","team:61b5c3f7aa0f6\/developer"]},"updated":1639314068,"domain":"appwrite.electron-store.org","tld":"org","registerable":"electron-store.org","verification":true},"domain":"appwrite.electron-store.org"}]) has failed Exception: Failed to issue a certificate with message: Saving debug log to /var/log/letsencrypt/letsencrypt.log
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
 in /usr/src/code/app/workers/certificates.php:131
Stack trace:
#0 /usr/src/code/src/Appwrite/Resque/Worker.php(22): CertificatesV1->run()
#1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
#2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#4 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
#5 {main}
```

**Comment by Rajdeep-TG** [comment]
Server details:
OS: macOS 11.06 (Big Sur)
Processor: M1 (arm64)

I also found that the `/var/lib/docker/volumes/appwrite_appwrite-certificates/_data` is empty (which I found with VM as Docker on Mac uses Linux VM for `/var/lib/docker`).

**Comment by eldadfux** [comment]
Use default ports 80 and 443 as Let'sEncrypt doesn't support non-default ports.

**Comment by Rajdeep-TG** [comment]
Default ports are already used by Apache. I've used vHosts to proxy the requests.

**Comment by eldadfux** [comment]
Awesome, closing this issue for now.

**Comment by Rajdeep-TG** [comment]
Is there any way I can host Appwrite Console on the domain as most links are broken and I can't upload and now I can't even log in? It says Incorrect Credentials while the same password and email works in the Server but does not work when proxied.

**Comment by Rajdeep-TG** [comment]
@eldadfux How I can access the console with Domain?

**Comment by eldadfux** [comment]
> @eldadfux How I can access the console with Domain?

You just need to point the domain to your server IP, you should also set the _APP_DOMAIN env variable. You can learn more about env vars in Appwrite here: https://appwrite.io/docs/environment-variables

**Comment by jenniestrongbow** [comment]
I basically have the same issue as Rajdeep-TG. Appwrite is installed on ports 85/444. I want to use my website on my default ports (80/443) and use appwrite on https://appwrite[domain].com (emphasis on the https). Anyway you can give me steps to follow to achieve this? I wish it was in the documentation. Thanks
