### ISSUE TITLE
🚀 Feature: ability to retrieve an oauth token upon oauth session creation

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2489]
### 🔖 Feature description

It would be nice to be able to retrieve an oauth token once created by API CALL /v1/account/sessions/oauth2/

### 🎤 Pitch

I would use this to allow my users to : 

- login easily on linkedin
- trigger functions to post contents on linkedin on his/her behalf
- refreshing the token would be the function responsability

Thx !

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@superseby2 You should be able to receive the oAuth token in the `providerToken` (https://appwrite.io/docs/models/session)  field when a session is created. You can get the current session by using https://appwrite.io/docs/client/account?sdk=web-default#accountGetSession
