### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by BBurnworth** [appwrite/appwrite#2491]
### 👟 Reproduction steps

The Cloud Function Monitor CPU Time is incorrect. 

![appwrite cpu time bug2](https://user-images.githubusercontent.com/5750537/145892135-baf219f2-e5dc-41ba-b22a-339604a4a6ab.png)

Above, from the Function Logs it shows the function only took **4.830** seconds to run.

Below, the Monitor Page - CPU Time shows **4830** seconds (1.3h).

![appwrite cpu time bug](https://user-images.githubusercontent.com/5750537/145892152-54bab174-7068-4ca5-a007-16d8bb76b9d6.png)

### 👍 Expected behavior

The CPU Monitor should show 4.8 seconds.

### 👎 Actual Behavior

The CPU Monitor shows 4800 seconds.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

v:db-alpha.181

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by PineappleIOnic** [comment]
This appears to be a typo within the code, it should be milliseconds looking at the code which sets this. I'll work on a patch now

**Comment by eldadfux** [comment]
Typo was fixed and merged to master. This will be released with Appwrite 0.12.
