### ISSUE TITLE
🐛 Bug Report: Cannot get user list when searching for an email address.

### ISSUE THREAD

**Issue by chrislaurie-bs** [appwrite/appwrite#2496]
### 👟 Reproduction steps

Using dart_appwrite I call users.list(search: email). Then you get an XMLHttpRequest error.  If you send through a normal string, then you do not get the error.

### 👍 Expected behavior

Return a list of users with that email address. Should be 1, as I know the user exists.

### 👎 Actual Behavior

I get an XMLHttpRequest error.

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by kodumbeats** [comment]
Hi @chrislaurie-bs 👋🏻 Thanks for sending this report.

We'll take a look at what's going on. Could you share a code snippet that we could use to quickly replicate this issue?

**Comment by chrislaurie-bs** [comment]
Using flutter web with the dart_appwrite sdk. Here is a quick test I did (call it from main to test):
`
class BendAdminTest{
  static Client client = Client()
    ..setEndpoint(kAppwriteEndPoint)
    ..setProject(kAppwriteProjectId)
    ..setKey(Secrets.bendApiKey);

  static final Users users = Users(client);

  static Future<void> testIt() async {
    Response<dynamic> resp = Response();
    try {
      resp = await users.list(); 
      log('testIt.noSearch: ${resp.data}'); //<<<<< no error
      resp = await users.list(search: 'benny');  //<<<<< no error
      log('testIt.searchPlain: ${resp.data}'); //<<<<< no error
      resp = await users.list(search: 'benny@benny.com');  //<<<<< XMLHttpRequest erroe
      log('testIt.searchEmail: ${resp.data}'); 
    } catch (e) {
      log('testIt :: ERROR :: $e'); 
    }
//Console output:
// [log] testIt.noSearch: {sum: 7, users: [{$id: 61b08....}]}
// [log] testIt.searchPlain: {sum: 0, users: []}
// [log] testIt :: ERROR :: AppwriteException: XMLHttpRequest error. (0)


  }
`

**Comment by stnguyen90** [comment]
This should be fixed in the next version of appwrite. If you need a workaround, you should wrap the email in double quotes. The message you're showing also has a `#` that can be interfering with the search. 

Also, this might be related to https://github.com/appwrite/appwrite/issues/2394

**Comment by eldadfux** [comment]
Seems like this was already fixed in #1281 and will be released in Appwrite 0.12

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
