### ISSUE TITLE
🐛 Bug Report: Deleted line breaks

### ISSUE THREAD

**Issue by davedawkins** [appwrite/appwrite#2507]
### 👟 Reproduction steps

Using the web console, create a document collection that contains a text rule, say `source : text`. Also, add another numeric rule, say `count : number`.

Upload a document that contains text like the following in the `source` field:
```
This has 
multiple lines
Hello
World
```

You probably can't do this from the console, and you'll need to create a small app to perform this (this is part of the issue being logged).

Now, visit this document in the web console.

You'll see that the `source` field has lost its newlines.

Now edit the `count` field and Apply the changes (Save changes).

### 👍 Expected behavior

I would expect 
1.  `source` field to be shown with a `textarea` HTML element which preserves the newlines, and allows the field to be edited
2. `source` field to be preserved when record is updated

### 👎 Actual Behavior

1. `source` field is shown with `input [type=text]`. Newlines are missing.
2. `source` field is corrupted even though only `count` field was updated (newlines are stripped in persisted data).

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Not customized

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@davedawkins Thank you for reporting this issue, we will look into it and respond soon.

**Comment by lohanidamodar** [comment]
@davedawkins This bug is already fixed and will be released on upcoming 0.12 version

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
