### ISSUE TITLE
[DISCUSSION] Github Bot for Discord

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#251]
Now that we've migrated our communications to Discord, I thought it would be useful to have a github bot that will keep us updated about the changes happening on the appwrite repo. 

This was also suggested by our community member @Kolkies 

I found a video that'll help 

[![Video](https://img.youtube.com/vi/D2LWN_s6cEE/0.jpg)](https://www.youtube.com/watch?v=D2LWN_s6cEE)

Let me know what you think @eldadfux

**Comment by eldadfux** [comment]
Thanks you for opening the issue @christyjacob4. Just tried it out and it's really easy to setup.

There is a huge list of events that can be submitted to Discord: https://developer.github.com/webhooks/#events

Any good idea, what might be useful? I can also navigate different issues to different channels.

**Comment by christyjacob4** [comment]
That's great @eldadfux . I will have a look at the link and let you know

**Comment by Kiy4h** [comment]
A discord bot would be great!

In the meantime, I think we should try out Discord webhooks, it can integrate with Github: https://gist.github.com/eslachance/40ac1c8232a5a019b43ee3f588d637ad

**Comment by eldadfux** [comment]
Hey @Kiy4h that exactly what I am trying to use, but still need to decide which events to trigger, we don't want to get too much notifications.

**Comment by RizkyRajitha** [comment]
@eldadfux , i'd like to give this a shot . since i am not familiar with php . but i am comfortable with nodejs . i think discod bots can be written in nodejs

**Comment by eldadfux** [comment]
@RizkyRajitha actually this is the same thing as @christyjacob4 suggested. I have already "hooked" the service together on a demo channel, just need to figure our what kind of alerts do we want and in which channel.

This is a list of all available events:
https://developer.github.com/webhooks/#events

**Comment by eldadfux** [comment]
I was thinking of creating a new channel in Discord called: 'feed' and have all new push, stargazers and issues events sent to him. Can we create a Discord channel that is 'muted' or something similar by default?

Another idea is to send all issues updated to the support channel.

Tell me what you think about it, and if you have any other ideas.

**Comment by RizkyRajitha** [comment]
i think new channel would be better because support is used frequently ,  this might spam the support channel

**Comment by eldadfux** [comment]
So I tried the Github bot on a private channel and it does seems to be really spamy. Is there anyway to create a channel on your server that is not sending notification? @RizkyRajitha @Kiy4h

**Comment by RizkyRajitha** [comment]
we can mute that channel @eldadfux

**Comment by eldadfux** [comment]
Was just going through the old issues, @RizkyRajitha any idea how to mute it?

**Comment by RizkyRajitha** [comment]
i think it can only done by members themselves  @eldadfux  to mute that channel.

**Comment by eldadfux** [comment]
Thanks for the quick replay @RizkyRajitha, think i'm going to pass on the bot for now.
