### ISSUE TITLE
Issue trying to update record with collection fields that have been previously deleted.  (rest api) 

### ISSUE THREAD

**Issue by joelmagoun** [appwrite/appwrite#2514]
This is my first time reporting an issue.  Please let me know if I am omitting anything.  

I've noticed that I tend to generate errors when the collection structure is changed.  

One common one is if I have a collection, and I have a document in that collection.  If I remove a field or two.  If I go to update a record that was in the database prior to the fields getting removed I get an error.. and the error is complaining about the deleted fields.  

example:
---

    $body = @{
        "data" = @{
            "value" = $value
        }
    }
    $result = Invoke-RestMethod -Method PATCH -uri $url -Headers $headers -Body (convertto-json $body) -ContentType 'application/json'

and I get back

    Invoke-RestMethod: {"message":"Bad structure. Invalid document structure: Unknown properties are not allowed (deleted_field1, deleted_field2) for this collection. Make sure to follow orders collection structure","code":400,"version":"0.11.0"}  

I am only trying to update the record, and my payload only has one item, and it has nothing to do with deleted_field1, or deleted_field2 .. reasonably the system should have forgotten about the deleted fields.  

(these are placeholder names, if that is not clear)

my only fix so far is that if the collection structure changes, i'm best deleting and re-creating all of the records.  

-------------------

steps to reproduce this:  

- create a collection 
- add a document
- delete some fields from the collection
- attempt to update the previously created document via the REST API  

---
Appwrite Version: 0.11.0.170

**Comment by RaminDadou** [comment]
Invoke-RestMethod: {"message":"Bad structure. Invalid document structure: Unknown properties are not allowed (deleted_field1, deleted_field2) for this collection. Make sure to follow orders collection structure","code":400,"version":"0.11.0"}

**Comment by joelmagoun** [comment]
Yes, that is the error message.  Using the REST API, it doesn't seem to be possible to patch documents that were added with fields that are now deleted.

**Comment by joelmagoun** [comment]
If I delete the document and recreate it, and then update it, it works fine.  

It's something to do with the fact that the original records are still holding on to information about the deleted fields.  

Please let me know if this is not clear or if more information is needed.

**Comment by stnguyen90** [comment]
I think this is the same behavior as https://github.com/appwrite/appwrite/issues/2265 and should be fixed in the next release.

**Comment by eldadfux** [comment]
Yep, seems like this might overlap with #2265 and will be fixed soon.

**Comment by joelmagoun** [comment]
Thanks for the reply.  I agree that this is likely the same issue.  

I'm going to mark this issue as closed and will wait for the next release.  Thanks very much! :)
