### ISSUE TITLE
📚 Documentation: How to update a stored file with new content?

### ISSUE THREAD

**Issue by jenniestrongbow** [appwrite/appwrite#2515]
### 💭 Description

Hi, after reading your documentation, I could not figure out how to update a file I created earlier with new content. Please help. Thanks

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
You would use the [Update File](https://appwrite.io/docs/client/storage#storageUpdateFile) API call.

**Comment by eldadfux** [comment]
The update file endpoint only allows you to update permissions. To update the contents you need to delete the old file and create a new one.
