### ISSUE TITLE
📚 Documentation: Database search vs Stored file access

### ISSUE THREAD

**Issue by jenniestrongbow** [appwrite/appwrite#2516]
### 💭 Description

Hi,

What is faster? Querying a database with 100,000+ records (with indexes) or accessing a text file in Storage (let's suppose there's 100,000+ files there?)

Thanks 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Assuming you're fetching both by ID, document could be slower if there's several fields and a lot of data is being passed over the network. File could be slower if it's a big file as the data needs to be decrypted and passed over the network.

**Comment by eldadfux** [comment]
As @stnguyen90 mentioned, very much dependent on your type of data and the exact query.
