### ISSUE TITLE
quickstart doesn't work, at all

### ISSUE THREAD

**Issue by Muphet** [appwrite/appwrite#252]
I have set up completely clean droplet on DO (and locally on docker-windows). Installed docker and followed quickstart command line. everything starts up, and app opens /auth/signin path (live on http://178.62.47.62/auth/signin)
after successful signup, console pops up for fragment of second and returns to auth screen (console is empty). there is no errors and no error logs for any container.

**Comment by eldadfux** [comment]
Hey @Muphet, Thank you for reporting your issue and providing us with important feedback.

Please check if there are any non-200 response codes in your browser console during the signup process. Make sure your developer tools preserve network option is set to 'on' in case there are any bad redirects during the operation.

**Comment by eldadfux** [comment]
Also, please check your Appwrite image version and what browser and browser version you are using.

**Comment by Muphet** [comment]
network log says /v1/account is unauthorized (401) which defaults back to auth page on chrome v78.0.3904.87 64bit. looks like this error persists only on chromum based browsers but works on mozilla. guess this issue can be closed but chrome v78 needs to be investigated regardless
