### ISSUE TITLE
🐛 Bug Report: Function Example  of createdAt for node.js is not working , the function will fail with timeout error

### ISSUE THREAD

**Issue by killkli** [appwrite/appwrite#2524]
### 👟 Reproduction steps

Installed appwrite 0.11.0.
Added collections with rule for createdAt key value.
Implemented the function (including node_modules folder) and tested with the instruction of the example here:
https://github.com/appwrite/demos-for-functions/tree/master/nodejs/add-created-at

The test will fail with exir code 124 no matter how long I extended the run time.
(all env values are properly set and checked to be correct, the func seem to be stuck on this line:
https://github.com/appwrite/demos-for-functions/blob/85e38c7831556ae0f5f7d9f34b4f1b13c1dd3bc2/nodejs/add-created-at/index.js#L20

### 👍 Expected behavior

Should work as the example illustrated.

### 👎 Actual Behavior

failed with timeout error.

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 🧱 Your Environment

No customized, installed with default environment

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
Hey 👋🏻 

Can you share the packaged function you used?

**Comment by killkli** [comment]
Sure :)
[createAt.tar.gz](https://github.com/appwrite/appwrite/files/7782308/createAt.tar.gz)

**Comment by killkli** [comment]
I tried to work another function, which is to delete all documents in certain collection.
It can be done on my local dev node env (with manually set endpoint & api-keys)
But still failed with node functions.
I double checked if the function got env setting correct (without actually running the database funcs, I modify it to just log the ENVs and check the log, all settings were correct, so the env variables are not the problems.)
However, the funcs just stuck on http execution. Maybe there are some problem between function worker container & API endpoint's container?

**Comment by Meldiron** [comment]
I will take a look at this and try to reproduce it.

**Comment by ridwankustanto** [comment]
Any news? I got the same error code too. Is it about RTO? Because I have two functions, and on both of them I hit different API. Function A comes with success and function B is failed, I suspected this because the API process on function B is slower than A. But I don't know.
