### ISSUE TITLE
🐛 Bug Report: No Paths in OpenApi Spec  

### ISSUE THREAD

**Issue by drofwarcs** [appwrite/appwrite#2527]
### 👟 Reproduction steps

Appwrites OpenApi Specs [here](https://appwrite.io/specs/open-api3?platform=client) and [here](https://appwrite.io/specs/open-api3?platform=server) both have an empty array for the paths element. The OpenAPI spec requires valid paths for the services be documented here. This is also causing the OpenApi generators to fail to parse these specs, and provides the following error:

```
Spec is invalid.
Issues:

	attribute paths is not of type `object`
```

### 👍 Expected behavior

Appwrite OpenApi spec to be parsed by OpenApi generator.

### 👎 Actual Behavior

OpenApi generator could not parse Appwrite spec due to invalid paths element.

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Thanks for pointing this out, we will take a closer look at this 👀

In the meantime, you can try to use OpenAPI from your own instance - by replacing `appwrite.io` with your domain, you can see your own OpenAPI file. If you are running on localhost, that would be `https://localhost/specs/open-api3?platform=client`. If that also doesn't work, you can try our demo instance at `demo.appwrite.io` with OpenAPI files at, for example, `https://demo.appwrite.io/specs/open-api3?platform=client`.

**Comment by drofwarcs** [comment]
@Meldiron Awesome. That worked perfectly. Thanks for your help 👍
