### ISSUE TITLE
🐛 Bug Report: Can't create endpoints

### ISSUE THREAD

**Issue by jenniestrongbow** [appwrite/appwrite#2528]
### 👟 Reproduction steps

Hi, I added endpoints in this way:

- set env variables as follows:
     _APP_DOMAIN=[domain].com
     _APP_DOMAIN_TARGET=[domain].com
- added a CNAME for appwrite.[domain].com and aw.[domain].com
- domain validated
- added the following endpoings: https://aw.[domain].com and https://appwrite.[domain].com
- TLS are still "in progress" for both.

### 👍 Expected behavior

Endpoints should be created.

### 👎 Actual Behavior

The console shows a constant "in progress". Nothing else happens.

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey 👋

Could you please share the output of `docker-compose logs appwrite-worker-certificates` with us? Be aware, your domain name is present there, please scrub any personal data from there before sharing.

**Comment by Meldiron** [comment]
I am closing the issue due to inactivity, feel free to reopen if needed 😇
