### ISSUE TITLE
🐛 Bug Report: Can't sign up on https

### ISSUE THREAD

**Issue by jenniestrongbow** [appwrite/appwrite#2533]
### 👟 Reproduction steps

hi, I installed appwrite on my Ubuntu server but I could sign up only once. I removed the user and now I can't sign up again.

### 👍 Expected behavior

I should be able to sign up

### 👎 Actual Behavior

It won't let me. 

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by PineappleIOnic** [comment]
Hey there 👋 
Could you please check the logs of appwrite and appwrite-worker-certificate to ensure no error occoured?
If there are errors could you please send the logs but please make sure to scrub any personal data (Domains, Keys, Usernames, IP's, etc...)

**Comment by eldadfux** [comment]
Closing for now, I'll reopen if needed.
