### ISSUE TITLE
📚 Documentation: Install Appwrite on https

### ISSUE THREAD

**Issue by jenniestrongbow** [appwrite/appwrite#2535]
### 💭 Description

I've wasted 3 days on this. I'm very close to moving to Parse or even going back to Firebase. 

What I want to do should be dead simple, but it's not. And if I follow the docs, it does not work.

What I want to do is simple: 

- I want to dedicate an Ubuntu server to AppWrite.
- I want to be able to use a https://[IP]/v1 endpoint, or a https://appwrite.[domain].com endpoint.

Very simple, and yet nothing I tried worked. Could you please give me a step-by-step method to get this? 

Thanks

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by jenniestrongbow** [comment]
I managed to do it. This page helped. It should be in your main documentation. Thanks

https://gist.github.com/eldadfux/eb3ed1c4e5f43b7f7259469dd29312c5

**Comment by Meldiron** [comment]
Hey there 👋

I am really sorry to hear about your complications with setting up Appwrite, and I am glad you managed to set it up. I would like to follow up on the idea of improving our official docs if you are interested. Could you please share with us which steps were missing in docs, and are present in the gist?

In case of any future complications, please don't hesitate to join our official [Appwrite Discord server](https://appwrite.io/discord), where both the Appwrite core team and community can help you. We are spread all over the world and you usually get answers to your question within a few hours.

**Comment by kiloki-official** [comment]
Hi Meldiron, I'll sign up on Discord. 

I tried so many things to make it work, I don't even remember what worked. But there are so many things missing in the documentation. I'll try to provide more info on what's missing in the documentation because I really like your product.

**Comment by eldadfux** [comment]
@kiloki-official @Meldiron I have submitted this PR to the docs trying to help with this issue.
https://github.com/appwrite/docs/pull/128

**Comment by eldadfux** [comment]
The new page is now available: https://appwrite.io/docs/certificates
![image](https://user-images.githubusercontent.com/1297371/149394202-88960610-ba80-4f25-b9f0-e5085cfe89b1.png)
