### ISSUE TITLE
Adding of Toggles for the social handles in the footer section

### ISSUE THREAD

**Issue by lavakush07** [appwrite/appwrite#2543]
## We can add Toggles to the social handles in the footer section (Github,Discord,Twitter,Linkedin,Youtube)

- If we can move the mouse clicker on the social media , it toggles out 
- It makes the web page more user friendly

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@lavakush07 Thank you for your suggestion. @eldadfux let's see if we can do anything about this.

**Comment by eldadfux** [comment]
@lavakush07 Do you have any examples, i'm not sure I fully understand the suggestion.

**Comment by lavakush07** [comment]
> @lavakush07 Do you have any examples, i'm not sure I fully understand the suggestion.

I was talking about the hoverable buttons for the footer section 
- [Example pic](https://www.w3schools.com/css/tryit.asp?filename=trycss_buttons_hover)

**Comment by eldadfux** [comment]
I have made sure @sarakaandorp is aware of this in case we want to make any changes in the footer design. Thanks for the suggestion!
