### ISSUE TITLE
🐛 Bug Report: Appwrite SMTP disabled (console)

### ISSUE THREAD

**Issue by gigonzalezs** [appwrite/appwrite#2557]
### 👟 Reproduction steps

Hi

I configured SMTP with sendgrid successfully

I test it using password recovery and the email was sent

but, the console still says "SMTP Disabled"

![image](https://user-images.githubusercontent.com/9580277/148137484-ea3c8a60-cf71-4265-b007-530515b18230.png)
 
and here

![image](https://user-images.githubusercontent.com/9580277/148137540-3f3e5ff2-9a43-4955-9099-6ad75c58a755.png)

 

### 👍 Expected behavior

the appwrite console must enable admin users to send invitations or configure "Magic URL" Authentication

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/9580277/148137757-712da4f2-6671-48fc-a64b-8c2138a5d154.png)

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 🧱 Your Environment

nop

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by gigonzalezs** [comment]
I opened the console in another browser and it does allow to send invitations

 I still thinking this is a minor bug. the console is not refreshing the server configuration when changes

**Comment by eldadfux** [comment]
You're probably hitting the browser cache, try to clean or keep your devtools open while using the console to see if the problem goes away.
