### ISSUE TITLE
🐛 Bug Report: Service button toggles state (visually) even after choosing cancel

### ISSUE THREAD

**Issue by Fabian9799** [appwrite/appwrite#2565]
### 👟 Reproduction steps

1. go to appwrite.yourdomain.com/console/settings/services?project=XXX
2. click on one of the toggles
3. select "cancel" on the confirm alert

### 👍 Expected behavior

the toggle should keep the current state

### 👎 Actual Behavior

the toggle changes its state (only visually, doesn't actually toggle the service)

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 0.12 on Docker 19.03.12 and Ubuntu 20.04 ( 2GB droplet from DigitalOcean)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Thanks for reporting this bug. I was able to easily reproduce this error, but can't find a simple solution. @TorstenDittmann can I assign you?

**Comment by TorstenDittmann** [comment]
This should be solved 👍🏻
