### ISSUE TITLE
Change license for python

### ISSUE THREAD

**Issue by PedroCisnerosSantana** [appwrite/appwrite#257]
We need to change the the value of the license for python generator script
For further info refer to [this PR](https://github.com/appwrite/sdk-for-python/pull/8) 
I will work on it

**Comment by PedroCisnerosSantana** [comment]
@eldadfux

**Comment by PedroCisnerosSantana** [comment]
Fixed with PR #259

**Comment by eldadfux** [comment]
Thank you Pedro! Great Work! Keep it up!
