### ISSUE TITLE
🐛 Bug Report: Query not valid: Attribute not found in schema:

### ISSUE THREAD

**Issue by kiloki-official** [appwrite/appwrite#2577]
### 👟 Reproduction steps

I, I upgraded to 0.12. Now the schemas don't recognise some of my attributes. 

### 👍 Expected behavior

After upgrading from 0.11 to 0.12, I should be able to query my documents.

### 👎 Actual Behavior

Creating indexes on simple TEXT fields fails. When querying, some attributes are no "found" even though they exist.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by kodumbeats** [comment]
Hi @kiloki-official, could you provide any error logs of this behavior? The API logs are in `appwrite`, and attributes/indexes are handled by the database worker:

`docker-compose logs appwrite`
`docker-compose logs appwrite-worker-database`
