### ISSUE TITLE
🐛 Bug Report: Creating multiple field indexes fails

### ISSUE THREAD

**Issue by kiloki-official** [appwrite/appwrite#2578]
### 👟 Reproduction steps

I jut upgraded from 0.11 to 0.12, when I create an index with more than one field, it fails. All the time. 

### 👍 Expected behavior

Creating an index with multiple fields should work.

### 👎 Actual Behavior

It fails. All the time. 

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by kiloki-official** [comment]
UPDATE: It seems that indexes with more than one field work, even though the AppWrite interface says its creation failed.

**Comment by s3ppo** [comment]
i have the same issue.. i found this in the logs:
```
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
```

**Comment by kodumbeats** [comment]
Closing this issue in favor of https://github.com/appwrite/appwrite/issues/2596

**Comment by kiloki-official** [comment]
Sometimes, creating indexes fails, but they still work.
