### ISSUE TITLE
🚀 Feature: Custom Endpoints for Security reasons

### ISSUE THREAD

**Issue by AhmedHammad0900** [appwrite/appwrite#2580]
### 🔖 Feature description

Hi Appwrite, I just read your 0.12 relase article , Like used to , always you are in top I see that u added custom IDs it's a great feature but I am interested in adding a feature to modify Static Endpoints like Users, Storage , Database .. ETC for security reasons

if I am using Appwrite as a backend to secure my content for specific people by using permissions for only this people,
Hackers can easly track my Endpoint cause there is a static documention already here for all appwrite projects :
https://appwrite.io/docs

and it's obvious if I am using let's say oAuth login which direct them to my main endpoint as there is no UI for SDks for oAuth so it uses Chrome for mobile apps for example then he can follow documentions . I know there is always IDs which generates randomly which make it harder to reach Storage fil and Database , but still there is static endpoints like Users , so if the hacker already one of my app users ... simply with postman or any another tool + appwrite which uses Cookies .. He put his foot on the beginning of the road to start finding Gaps from my side to reach something he musn't reach by custom endpoints for Users , We will cut his feet from beggining and another steps from programmers side ( our side ) like SSL Pinning which will make Appwrite like Custom powerful CMS Backend and add a high layer of security .

### 🎤 Pitch

Security Always Come first .. it will add a Great layer of security

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by wess** [comment]
I can see the value in this and how it could add a layer of security. Just wondering, if someone could use Postman to make the requests, how does custom endpoints stop them from using something like an HTTP proxy (ie. CharlesProxy) from just finding out the endpoints anyways?

**Comment by AhmedHammad0900** [comment]
> I can see the value in this and how it could add a layer of security. Just wondering, if someone could use Postman to make the requests, how does custom endpoints stop them from using something like an HTTP proxy (ie. CharlesProxy) from just finding out the endpoints anyways?

" SSL Pinning " ..
Proxies softwares that can track endpoint by redirecting the request from the app to the software using custom proxy then send it to the backend like it's normal from the app . by SSL Pinning which is done from my side not from Appwrite side ( not ur side ) I can check if the request is directly going to appwrite backend or there is a proxy asking for it like I am doing in my apps ( that's the meaning of SSL Pinning ).  so if it's not , it means that the request is passing through MITM ( Man in the middle Attack , type of hacking attacks which tracks the requests and endpoints ex. CharlesProxy , MITM Proxy ) so I don't do the request from beginning if  it's not the same SSL of my appwrite , so hacking software which tracks my requests ( ie. CharlesProxy ) won't get the request as it doesn't happen from beginning .. with Static endpoints like now .. I don't need to hack to know ur endpoints and use Postman to access data ..  I already know all ur endpoints from Documention xD .. that's the weakness point of ready made CMS backends like current version of appwrite >> adding this will take appwrite in another field

Note : SSL is automatically changed at appwrite backend every 60 Days so I need to update all my phone apps to put the new SSL Pinning in the env file of my Flutter App .. so if u find a away to stop updating SSL Every 60 days .. or we need to buy Custom SSL .. 

I want to refer to appwrite Storage Permission is a huge protection method as I need to be a user who already have permission to the file that I need to downlaod throgh postman , by changing the endpoint + SSL Pinning .. It will be impossible for users who have access to file to find the file URL As it's not in appwrite documentions endpoints

**Comment by eldadfux** [comment]
I understand the concern here, but I largely think this is an edge scenario. I don't think an implementation of a layer like this should be part of Appwrite, but as mentioned handled by a 4rd party proxy that has exclusive access to the Appwrite backend.

About the comment regarding storage. Unlike S3 or Firebase, Appwrite files are session protected and not token protected (we might add this as well in the future). As long as the files are session protected its not enough to get access to the URL. You should also hijack the session which is much harder than hijacking a URL (when behind a SSL) or a URL token.

**Comment by eldadfux** [comment]
For now our recommendation would be to use a custom proxy to achieve this use case as we fill implementing it in the core API will create added complexity that don't justify the maintenance and debugging challenges it might introduce. Happy to re-open this issue if more opinions around it pop up.
