### ISSUE TITLE
📚 Documentation:  We need chinese!

### ISSUE THREAD

**Issue by JohyC** [appwrite/appwrite#2584]
### 💭 Description

I think appwrite is very exciting! But I need a Chinese document. I am not proficient in English and I need to spend more time reading and understanding.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
We would be more than happy to add different translations to Appwrite. I think it would be great to start with the readme file in the repo and gradually assess how we can add multi-lang support for the docs.

**Comment by EugeneMakita** [comment]
hi @eldadfux do you need help on this ? first time contributor , is it to translate the documentation into chinese or ?

anyways let me know if there is anything i can help do 

thanks

**Comment by eldadfux** [comment]
@EugeneMakita I have assigned you to the issue. All needed is to translate this repo README file.

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! tuned for a lot more amazing issues from the Appwrite team!

**Comment by eldadfux** [comment]
@christyjacob4 this is for the readme, i'm keeping it open :)

**Comment by EugeneMakita** [comment]
Hi @christyjacob4  trying to push my branch
but getting 
```
ERROR: Permission to appwrite/appwrite.git denied to EugeneMakita.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by eldadfux** [comment]
@EugeneMakita you need to create a fork and later submit a PR.

**Comment by gewenyu99** [comment]
@JohyC Here's my attempt at a manual translation, I intend to invite other Chinese developers I know to review this as well. 欢迎您帮我纠错，润色我的译文，我也没多少中文环境的开发经验。谢谢您！

**Comment by eldadfux** [comment]
The new Chinese translation is now available here: https://github.com/appwrite/appwrite/blob/master/README-CN.md
Great work @gewenyu99!
