### ISSUE TITLE
How to use translations?

### ISSUE THREAD

**Issue by binhodev** [appwrite/appwrite#2585]
Hello everyone!

How to change language in Admin Panel and errors exceptions from Appwrite Exceptions?

Thanks!

**Comment by generalxhd** [comment]
The Appwrite exceptions and the dashboard are only available in English (see #1478 and #1353).
At the moment only these strings are translated, see for example https://github.com/appwrite/appwrite/blob/master/app/config/locale/translations/en.json

**Comment by binhodev** [comment]
> The Appwrite exceptions and the dashboard are only available in English (see #1478 and #1353). At the moment only these strings are translated, see for example https://github.com/appwrite/appwrite/blob/master/app/config/locale/translations/en.json

So, thanks!
