### ISSUE TITLE
📚 Documentation: cannot find a way to perform a query between 2 collections (à la JOIN)

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2589]
### 💭 Description

I thought I could use Embedded documents, but since the feature is gone in 0.12 I do not see how to perform a query that would need to user 2 Collections like in a Select with Inner Join.

Anyone to point me in the right direction using the new database query system ?

Thx !

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This is probably very similar to https://github.com/appwrite/appwrite/issues/2597 where I left a few pointers on possible workarounds and future thoughts.

**Comment by superseby2** [comment]
Thanks for taking the time.

I am happy with the solution where you store a list of ids from documents
of another collection. But I cannot figure out how to query the whole thing.
Unless making two calls (one for the parent document and one for the
children)?

**Comment by eldadfux** [comment]
@superseby2 making 2 calls is one options, and in a lot of use cases it also make sense. Another option is to write a cloud functions that will be triggered every x minutes, or every time you create a document. Once triggered the function can make multiple calls to the db for all data required and merged it to a new collection which you can use for fetching data once from your client size.

This is a common solution for DB optimization when you want or need to avoid expensive join operation and provide very fast queries.

**Comment by superseby2** [comment]
I see .. It is not as straight-forward as requesting the whole thing in a single request especially when you are not at the stage where you need optimization right now. Still, it does provide a way to do it. 

thx!

**Comment by locohost** [comment]
> @superseby2 making 2 calls is one options, and in a lot of use cases it also make sense. Another option is to write a cloud functions that will be triggered every x minutes, or every time you create a document. Once triggered the function can make multiple calls to the db for all data required and merged it to a new collection which you can use for fetching data once from your client size.
> 
> This is a common solution for DB optimization when you want or need to avoid expensive join operation and provide very fast queries.

Ok I'm used to sync functions that do all this work. You call the function, it does the queries and aggregation and sends back your Json structure response. However this idea (above) is a very interesting thought. This will be fun... :-)
