### ISSUE TITLE
🐛 Bug Report: Membership verification for the same id possible several times

### ISSUE THREAD

**Issue by Malte2036** [appwrite/appwrite#2593]
### 👟 Reproduction steps

1. Create a team
2. send a [membership invitation to a user](https://appwrite.io/docs/client/teams#teamsCreateMembership)
3. user recieves email with an membership verification link
4. user clicks on the link multiple times and triggers the [verification endpoint](https://appwrite.io/docs/client/teams#teamsUpdateMembershipStatus) multiple times with the same parameters and the same membershipId.

### 👍 Expected behavior

The first time you click on the link, the user will be added to the team and the sum variable will be incremented.

If you click on the link again and start the verification process, the endpoint should return an error because the membershipId is already confirmed. And nothing should change for the team itself.

### 👎 Actual Behavior

The first time you click on the link, the user will be added to the team and the sum variable will be incremented.

If you click on the link again and start the verification process, *no* error occurs and the sum variable of the team is incremented again. 

This means that if, for example, the verification endpoint is triggered 10 times with the same parameters, the sum variable is increased by 10.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

I use appwrite v0.12.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
This got fixed and is released with `0.13.1` 👏🏻
