### ISSUE TITLE
🐛 Bug Report: Function variables don't get saved

### ISSUE THREAD

**Issue by generalxhd** [appwrite/appwrite#2595]
### 👟 Reproduction steps

Create a function with your preferred runtime, create one or multiple variables and save it. 

https://user-images.githubusercontent.com/58886915/149155893-0296a7c9-38ab-45f6-bd35-bcf833ddcba1.mov

### 👍 Expected behavior

Function variables should get saved and be persistent.

### 👎 Actual Behavior

The function variables don't get saved in any runtime.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite v0.12

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by mark-apn** [comment]
Got the exact same problem on v0.12.0.200.

**Comment by bil0ak** [comment]
I have the same problem.

**Comment by mark-apn** [comment]
Upgrading to v0.12.1 fixed the bug for me (if you are using the docker-compose.yml just search and replace 0.12.0 => 0.12.1)

**Comment by generalxhd** [comment]
Thanks @mark-apn it's fixed in v0.12.1 by #2563

**Comment by eldadfux** [comment]
@mark-apn I have now updated the docker-compose.yml to show the latest 0.12.1. Thanks for all the help!
