### ISSUE TITLE
🐛 Bug Report: migrated database attributes (string ) failed to create index

### ISSUE THREAD

**Issue by prooshani** [appwrite/appwrite#2596]
### 👟 Reproduction steps

After upgrading to 0.12 and migrating my databases (collections), string attributes are converting with length of 65535.
If you decide to add index to the collection for queries with type of **KEY** and having more than one attribute then you will face a **failed** index and the index is not gonna work for queries as well.
But, if I define a similar dataTable (collection) with string attributes length 255, it is looking good.
For the first scenario (large string attribute) the database worker having error like this:
`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes`

### 👍 Expected behavior

<img width="989" alt="Screen Shot 2022-01-10 at 10 42 28 PM" src="https://user-images.githubusercontent.com/69037930/148829982-c4791d58-422b-48dc-91d0-f061ae42ebdb.png">

### 👎 Actual Behavior

<img width="944" alt="Screen Shot 2022-01-10 at 10 41 54 PM 1" src="https://user-images.githubusercontent.com/69037930/148830044-e5fb76de-9cc6-4016-90ac-167a798afa63.png">

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Some time ago I wrote a CLI toolset [Appwrite Tools](https://github.com/Meldiron/appwrite-tools) that is capable of solving this issue.

You can follow [README](https://github.com/Meldiron/appwrite-tools/blob/master/README.md) in the repo to see how to use it, but it's pretty much:

1. Clone repo `git clone` (and enter folder)
2. Install dependencies `npm install`
3. Backup documents into a file (command in README with `--action documents-backup`)
4. Make sure your documents are properly downloaded in `backup_[SOME_NUMBER].csv` file
5. Wipe documents in Appwrite (command in README with `--action documents-wipe`)
6. Go into Appwrite Console, and manually delete attributes. Then add them back with the new size you want
7. Restore documents (command in README with `--action documents-restore`)

You should now have exactly the same data in your collection, and your attribute size is now changed. This CLI tool can also allow you to change types or even names of attributes, but you might need to do some manual changes to the document backup (in CSV) to follow new names/types.
