### ISSUE TITLE
Databases supports map object?

### ISSUE THREAD

**Issue by binhodev** [appwrite/appwrite#2597]
Hello everyone, how are you?

Now in version 0.12 there is no way to nest documents.
How do I insert a map of strings into a document? Since in the Attributes option there is no Map.

Or how to make reference to other collection?

Thanks for all!

**Comment by eldadfux** [comment]
Right now there is no native way to support nested objects.

You can do a few things:
1. Store your object as a JSON string and parse it locally
2. Store your object in a second collection and use a key attribute as a reference to it.
3. Cloud Functions can also be useful tool to aggregate all the data you need to a 3rd collections which can be very optimized for fetching the data using a single efficient query.

We're actively working to add more features to support this use cases, but hopefully the above helps.

**Comment by binhodev** [comment]
Hi @eldadfux,

Thank you very much for your time and dedication in responding to me.

I was trying the first option, in this case I will have to write a lot of code.

The second option I don't know how it works, I've never had contact with relational databases, I'm coming from NoSQL database, I didn't find anything about it in the Appwrite documentation.

About Cloud Functions, I'm learning how it works.

Thank you very much.

**Comment by eldadfux** [comment]
Sure thing. Feel free to open another issue if you need more guidance with option 2 or 3.
