### ISSUE TITLE
Help us add support for more SDKs!

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#26]
We use our [SDK generator](https://github.com/appwrite/sdk-generator) project to auto-generate SDKs from our API spec JSON file.

All information on how to add new templates for a new language are in here:
https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md

You can also use one of our existing language templates as a base for a new one.

We currently have support for:
* PHP
* Javascript
* NodeJS (Still needs help for adding file upload requests)
* Ruby (* BETA - Still needs some code review and testing)
* Python (* BETA - Still needs some code review and testing)
* Dart (* BETA - Still needs to add support for strict typing, default values and file upload)

Any new coding language is WELCOMED!

Project Repo:
https://github.com/appwrite/sdk-generator

**Comment by tacoelho** [comment]
I want to do this :)

**Comment by kimuraz** [comment]
@eldadfux Can I get the NodeJS file upload feature?

Also, is there any plans to adopt linting (or whole style guides) for the SDKs? If so, I could work on it for python and/or javascript SDKs.

**Comment by eldadfux** [comment]
@kimuraz yes sure. you can look at the PHP or JS example for how this achieved - the feature scope itself is adding file upload + support for multipart/form-data request.

Please read the contribution guide in the SDK Generator repo and feel free to contact me on Gitter with any question.

**Comment by Ishaan28malik** [comment]
Is it still open ? @eldadfux

**Comment by zoois280562** [comment]
Yes

**Comment by eldadfux** [comment]
Yes @Ishaan28malik

**Comment by Ishaan28malik** [comment]
Ok @eldadfux @zoois280562

**Comment by prkhrv** [comment]
Is file uploading done in Node?

**Comment by eldadfux** [comment]
@kimuraz

**Comment by kimuraz** [comment]
@prkhrv and @eldadfux I'm on it, although I'm not sure how to work on the template and it might take some time, so I guess it's not fair to block it. 
@eldadfux I wouldn't mind if you assign this task to him, but if that's not the case I'll continue on it.

**Comment by PedroCisnerosSantana** [comment]
What about java?
Also I'd like to help to improve python support

**Comment by eldadfux** [comment]
Hey @PedroCisnerosSantana , we could use help both on java and python. Please contact me on Discord for guidance.

and feel free to join us on our Discord server:
https://discordapp.com/invite/GSeTUeA

**Comment by eldadfux** [comment]
Closed in favour of #419
