### ISSUE TITLE
🐛 Bug Report: "appwrite.io" and "appwrite.test" domains are accepted as session verification

### ISSUE THREAD

**Issue by acalatrava** [appwrite/appwrite#2603]
### 👟 Reproduction steps

When you create an email verification or a magic url request, both "appwrite.io" and "appwrite.test" are accepted as valid domains along with "localhost" and your custom domains. This may be a potential security issue.

[@eldadfux Actually, I think it might be left overs, and should be a good idea to remove both. Mind opening a Github issue? I could submit a PR today](https://discord.com/channels/564160730845151244/564160731327758347/931139634577145938)

### 👍 Expected behavior

Only localhost and custom domains should be allowed

### 👎 Actual Behavior

Already described

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite v0.12.0.200

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This was fixed and merged. Will be available in next release (0.13)

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻
