### ISSUE TITLE
🐛 Bug Report: Appwrite Realtime Container Failing to start

### ISSUE THREAD

**Issue by ElectronSz** [appwrite/appwrite#2605]
### 👟 Reproduction steps

`docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.12.0`

### 👍 Expected behavior

On `docker ps` all containers should be running

### 👎 Actual Behavior

https://user-images.githubusercontent.com/32393708/149330035-9e81a6e2-26e7-4d72-acec-65b04b187b05.png

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Nope!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ElectronSz** [comment]
https://user-images.githubusercontent.com/32393708/149330035-9e81a6e2-26e7-4d72-acec-65b04b187b05.png

**Comment by stnguyen90** [comment]
As the error indicates, the container couldn't connect to the database. Can you confirm the database is up and running? Try going into the appwrite folder where the docker-compose.yml file is and run `docker-compose ps -a`.

**Comment by eldadfux** [comment]
@TorstenDittmann do we have retry policy when the db is not ready for connections?

**Comment by ElectronSz** [comment]
I solved it by restarting docker

`sudo docker systemctl docker restart`

And increased Docker timeout. Initially its `60 seconds`
