### ISSUE TITLE
🐛 Bug Report: Oauth2 URL Redirect has ":" in it

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2608]
### 👟 Reproduction steps

- In the Console : Go to Users > Settings
- Select LinkedIN

### 👍 Expected behavior

- The redirect URI has no ":" in the URI  right after the domain name

### 👎 Actual Behavior

- The redirect URI has a ":" in the URI  right after the domain name

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Could you please share a screenshot?

**Comment by superseby2** [comment]
Here you go : that's where I am redirected right after the linkedin page telling I would be redirected to appwrite.

![image](https://user-images.githubusercontent.com/32198925/149452618-590c1767-c3bf-46e2-8e87-90055a8b0dc0.png)

**Comment by superseby2** [comment]
![image](https://user-images.githubusercontent.com/32198925/149453069-5e792c4e-85e6-4ed5-933a-d26d43a9f203.png)

**Comment by stnguyen90** [comment]
@superseby2, is this still a problem? I can't reproduce.
