### ISSUE TITLE
How to create a reference attribute to a or more collections?

### ISSUE THREAD

**Issue by binhodev** [appwrite/appwrite#2609]
Hi, 

What kind of key attribute can I reference one or more collections?
#2597

> 2. Store your object in a second collection and use a key attribute as a reference to it.

Thanks!

**Comment by eldadfux** [comment]
You can just use the string attribute. We'll consider adding a dedicated reference / key attribute for easier validation in the future.

**Comment by binhodev** [comment]
> > You can just use the string attribute. We'll consider adding a dedicated reference / key attribute for easier validation in the future.
> 
> So I'm going to create a collection in App Write Dashboard.
> 
> Collection 1 Name: States id: states attribute: name (String) attribute: city (String) can be array or no?
> 
> Collection 2 Name: City id: city attribute: name (String) attribute: population (integer)
> 
> How do I make this function in Dart? As I get the states and cities respectively in just one reading. That's my question. I can get the data from the States collection, but I can't get the data from the City collection when get States.
> 
> Thanks!

Maybe  be able to do that.

```
Future getDocumentData() async {
    try {
      final DocumentList documentList = await _db.listDocuments(
        collectionId: 'states',
      );

      for (final doc in documentList.documents) {
        final Document document = await _db.getDocument(
            collectionId: 'city', documentId: doc.data['city']);
       debugPrint('Data State: ${doc.data['uf']}');   // BA, SE
       debugPrint('Data City: ${document.data['name']}');   // Salvador, Aracajú
       debugPrint('Data Population: ${document.data['population']}');   // 12000000, 3500000
      }

    } on AppwriteException catch (e) {
      debugPrint('Error: $e');
    }
  }
```

Thanks!

**Comment by binhodev** [comment]
I have updated the code above, more clean. Thanks!
