### ISSUE TITLE
Custom OAuth Scopes

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#261]
Currently, Appwrite's OAuth endpoint is requesting our predefined OAuth scopes from each service. This predefines scopes are usually used for getting the user name and email for allowing us to verify the user identity and successfully completing its registration or login process.

After completing the user authentication, we save the user OAuth token on his user account to allow app developers to interact with the user's OAuth provider API.

If a user has logged with facebook as his OAuth provider, this means we can allow the app developer to send Facebook API requests to get more of the users' data. Of course, this entire process is subjected to user consent.

Currently, Appwrite API is limited to only a few predefined scopes for each OAuth provider. Allowing custom scopes will allow app developers to make requests to OAuth providers with extra permissions on behalf of the user.

To allow custom scopes, we need to introduce a new parameter to the OAuth endpoint (https://appwrite.io/docs/auth#oauth). The new parameter, called 'scopes', will accept an array of strings and will be empty and not required by default.

After accepting and validating the new parameter, we should merge its data with our existing list of scopes. Our current list of scopes is located on each OAuth provider class. An example can be viewed in our Facebook adapter on line 32:
https://github.com/appwrite/appwrite/blob/master/src/Auth/OAuth/Facebook.php#L32

To enforce Appwrite maintainers to manage scopes in an organized and controlled method, we should add two new methods to our OAuth provider's abstract class:
https://github.com/appwrite/appwrite/blob/master/src/Auth/OAuth.php

1. addScope(string $scope)
2. getScopes():array

After adding those two new methods, we should update each OAuth provider to actually use them for parsing the scopes when sending his OAuth request.

**Comment by eldadfux** [comment]
We have made big progress on this thanks to @christyjacob4 fantastic work on this during the weekend. This feature should be ready for the next version release (0.5).

@christyjacob4 do you think you could write a small post about how to use this feature that we could publish on our Medium blog?

**Comment by christyjacob4** [comment]
Yea I can write the blog post. Let me know by when you require it.
I also need some details regarding the same.

**Comment by CodeWithKamal** [comment]
link to blog post if you have one, I need to use Facebook Marketing API and need to custom scopes with Facebook OAuth.
