### ISSUE TITLE
🚀 Feature: "Native" Sign In with Apple

### ISSUE THREAD

**Issue by Lucke0051** [appwrite/appwrite#2611]
### 🔖 Feature description

Currently the Sign In with Apple implementation requires the user to firstly click accept on the prompt to "APPNAME wants to sign in with APP.com", then a blank browser window pops up and shortly after the Sign In prompt shows. This is not a nice user experience.

Instead the Sign In with Apple prompt should open right away when called (button pressed usually) on Apple devices that support it. See Flutter package [sign_in_with_apple](https://pub.dev/packages/sign_in_with_apple). This would provide a much nicer sign in flow. The "native" prompt also shows the app's icon and name without any configuration. I can implement this in the Flutter client SDK but I am not a backend PHP developer.

Current "flow":
![1st step](https://user-images.githubusercontent.com/30857678/149618711-49b253a9-2415-4025-bacc-c0c867d63cec.png)

![2nd step](https://user-images.githubusercontent.com/30857678/149618715-ecd13676-6fe1-4779-be7d-8c053ad7f88d.png)

![3rd step](https://user-images.githubusercontent.com/30857678/149618717-6c437bb2-21d5-4c6a-a359-438ea98f0a37.png)

"Native":
![native](https://user-images.githubusercontent.com/30857678/149618719-95614c00-2308-4904-b7f2-e2c0fa0f3d6e.png)

### 🎤 Pitch

As Apple requires developers to provide Sign In with Apple functionality if they have other third-party auth providers. This means that it's likely many people that will be positively affected by this change. 3 prompts to get to the sign in dialog is not ideal.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Hey @Lucke0051, thanks for submitting this issue. We have been looking at this PR which wasn't completed as a potential solutions: https://github.com/appwrite/appwrite/pull/903. The idea behind it is to allow devs to use native OAuth SDKs for better UX.

We intentionally avoided coupling any of the Appwrite SDKs with 3rd party OAuth integrations. Today we have around 25 OAuth providers and 4 client SDKs. This can result in maintaining ~100 different integration, most of them probably not well maintained. This will also explosively increase the size of the SDKs and will force dependencies that will never be used in many cases.

We're still very open to continue the solution started at #903, if the community picks it up, we can also prioritize it.

**Comment by SirusCodes** [comment]
Is there any progress?

**Comment by KhaleelSH** [comment]
Any news here?

**Comment by zandercodes** [comment]
In one of the first versions of AppWrite it was possible to validate the login using Apple's indentityToken.
But this was removed in AppWrite. So the native login on the device is only possible via very complicated detours, which does not have to be.

**Comment by cd711** [comment]
can I  implement with functions self?

**Comment by stnguyen90** [comment]
I'm pretty sure native login should work now using [custom tokens](https://appwrite.io/docs/products/auth/custom-token).

**Comment by SirusCodes** [comment]
> I'm pretty sure native login should work now using [custom tokens](https://appwrite.io/docs/products/auth/custom-token).

Thanks, this will surely work but it's again a bit of hassle as the dev will need to write code for verifying the tokens and implement a function just for this. I was kind of expectation a much easier way to do it like -

` account.createGoogleAccountUsingToken`  which will do all that for me

**Comment by djimonlee** [comment]
still curious if this is still WIP??

**Comment by pedrio-gh** [comment]
Any news regarding this feature?
