### ISSUE TITLE
🐛 Bug Report: Inaccurate double value can't be saved in float attribute.

### ISSUE THREAD

**Issue by binhodev** [appwrite/appwrite#2614]
### 👟 Reproduction steps

When I try to save a negative double value as a point of longitude I get this error in the Dashboard.

Attribute is a float.

### 👍 Expected behavior

I think I should be saved.

### 👎 Actual Behavior

![double_error](https://user-images.githubusercontent.com/58571495/149621201-e5474252-47aa-4350-a5ba-b4058658bbd6.png)

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite are installed on AWS E2 instance.

Local machine:
Browse: Chrome 97.0
System: Windows 11

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by benceHornyak** [comment]
I've encountered the same problem today. Tried to do some research and it looks like the problem might be somewhere here: https://github.com/utopia-php/framework/blob/master/src/Validator/FloatValidator.php#L86 

I hope this might help a bit

**Comment by Caryntjen** [comment]
If you do not fill in the **min** or **max**, it does set it with default values:
![image](https://user-images.githubusercontent.com/3481691/151718427-450b5287-e5d2-428a-aabb-d86d46c86941.png)

**Comment by TorstenDittmann** [comment]
0.13.3 got released and this is fixed 👏🏻
