### ISSUE TITLE
📚 Documentation: Upgrade Instructions Unclear

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#2616]
### 💭 Description

Despite the [Upgrade docs](https://appwrite.io/docs/upgrade) saying:

> The first step is to install the latest version of Appwrite. Head to the directory where you first installed Appwrite. This is where you will find the **appwrite** directory and the **appwrite/docker-compose.yml** file. Make sure you are at the same level as the **appwrite** directory and then execute the following command

I had 2 instances today where people had confusion about where to run the upgrade command. 

[basatS7T said](https://discord.com/channels/564160730845151244/564160731327758347/931988183074365480):

> Yep, I saw that.  It is not clear to me at this point what that says

[godfather said](https://discord.com/channels/564160730845151244/564161855862603789/932001419349860403):

> ohh cool, one question i have to run update command inside appwrite directory (i.e. which has docker-compose.yml file)?

basatS7T suggested to include example paths to help clarify.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Created a PR here: https://github.com/appwrite/docs/pull/133/files I hope it makes things more clear.

**Comment by stnguyen90** [comment]
I like this change. @eldadfux, what are your thoughts on adding examples to show that `appwrite` should be in the current directory?

**Comment by eldadfux** [comment]
@stnguyen90 did you had any snippet in mind?

**Comment by stnguyen90** [comment]
The user probably wanted to see something like this:

```bash
/path/to/parent/of/appwrite $ docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.12.1
```

but this doesn't match the convention of any of the other example commands so I don't think this should be done.

Perhaps the docs could be updated to:

> Head to the directory where you first installed Appwrite. This is the parent directory, where you will find the **appwrite** directory.
> ```bash
> ls appwrite
> ```
> Verify that shows the **docker-compose.yml** and **.env** files. Then, install the latest version of Appwrite.
> ```bash
> docker run -it --rm \
>     --volume /var/run/docker.sock:/var/run/docker.sock \
>     --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
>     --entrypoint="install" \
>     appwrite/appwrite:0.12.1
> ```

Otherwise, the one-liner can check for the appwrite folder before installing:

> ```bash
> [ -d "appwrite" ] && docker run -it --rm \
>     --volume /var/run/docker.sock:/var/run/docker.sock \
>     --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
>     --entrypoint="install" \
>     appwrite/appwrite:0.12.1
> ```

**Comment by stnguyen90** [comment]
After talking internally, we decided to create a separate upgrade command that would validate the existing installation before proceeding. It could even check to ensure you're [upgrading to the next version of Appwrite rather than skipping versions](https://github.com/appwrite/appwrite/issues/3176).

**Comment by stnguyen90** [comment]
Related PRs:

* https://github.com/appwrite/appwrite/pull/6068
* https://github.com/appwrite/appwrite/pull/5874
