### ISSUE TITLE
user groups and plans

### ISSUE THREAD

**Issue by wentzlau** [appwrite/appwrite#262]
I miss the possibility to create user groups in appwrite. A JWT holds the groups a user is member of. I need them to place users in various plans for my service. 

Maybe there also should be support for plans with features in appwrite. A plan consists of features and a feature is tied to a user group. Users should be able to move between plans and a webhook is calles when a user change plan.

**Comment by eldadfux** [comment]
Hey @wentzlau, I think Appwrite's Team service might be exactly what you are looking for.

Please take a look at the docs:
https://appwrite.io/docs/teams

> The teams' service allows you to group users of your project and will enable them to share read and write access to your project resources, such as database documents or storage files.
> 
> Each user who creates a team becomes the team owner and can delegate the ownership role by inviting a new team member. Only team owners can invite new users to their team.

The teams service also lets you manage different roles within the team and restrict [permissions](https://appwrite.io/docs/permissions) to your project resources by user ID, team membership or team role.

I am not sure exactly what you mean by plan, but each Appwrite user account can save the user preferences. You can use the preferences endpoint to save any key-value data you need for your user.

Take a look here: https://appwrite.io/docs/account#updatePrefs

**Comment by eldadfux** [comment]
We still don't support JWT token for user authentication but it's something that we plan to add in the future.

**Comment by wentzlau** [comment]
> Each user who creates a team becomes the team owner and can delegate the ownership role by inviting a new team member. Only team owners can invite new users to their team.

I read this as a end user feature where end users able to create teams. If a backend server with api-key creates a team who is the owner?

**Comment by eldadfux** [comment]
On [admin mode](https://appwrite.io/docs/admin), no user will be the owner. You can use the server integration to send a new invite to any user you wish. 

I would love to learn more about your use case, this might help us better design & explain the differences between server-to-server vs. server-to-client integrations.

https://github.com/appwrite/appwrite/blob/master/app/controllers/teams.php#L149

**Comment by wentzlau** [comment]
I think there are conceptually differences between teams and groups. In a team you invite members and an invitation is send to the members who is invited. A member can decline the invitation.

I think of user groups as controlling security access. It is the backend system that adds and removes members to user groups. When a new user signs up for my service the user choose a plan. That plan consists of features and each feature is tied to a user group. Depending on group membership it is possible to make a dynamic UI.  It can also be use control what part of the frontend app the user has access to (routing guards).

It is more like active directory or ldap, maybe you should apply a ldap server to the appwrite mix.

**Comment by eldadfux** [comment]
It's really important for us to find a generic enough solution for such cases. It's vital that Appwrite will be a flexible as possible and won't enforce any app-specific flow on app developers.

I was thinking about adding a new feature called 'audiences'. This feature will allow Appwrite admins to mark their users with relevant categories they wish. This will also allow admins to filter users by their audiences. Will this kind of feature help you implement your use case?

~~~
And about the LDAP integration - Its already on our checklist for new authentication methods 👍🏻.

**Comment by eldadfux** [comment]
JWT draft PR is ready: https://github.com/appwrite/appwrite/pull/784/files 🎉

**Comment by TorstenDittmann** [comment]
JWT is merged and released 👍🏻

**Comment by MatiasLGonzalez** [comment]
Hello, what's the status on the LDAP as a authentication method?
