### ISSUE TITLE
🐛 Bug Report: Realtime Events

### ISSUE THREAD

**Issue by TheMardy** [appwrite/appwrite#2626]
### 👟 Reproduction steps

3 unexpected Results with realtime events, unsure if it is expected behavior:

1. Have an active session and realtime subscription to `teams`, create a team.

2. Have an active session and realtime subscription to `memberships`, update team membership status.

3. Have an active session and realtime subscription to `account`, delete all sessions

### 👍 Expected behavior

1. Realtime teams.create event is sent to the owner when he creates a team using the client SDK 

2. Realtime teams.memberships.update.status event is sent to the member updating the status, and the team owner(s) when the member updates his membership status using the client SDK

3. Realtime account.session.delete event is sent to the user when he deletes all sessions using the client sdk (sdk.account.deleteSessions())

### 👎 Actual Behavior

1. Realtime teams.create event is **not** sent to the owner when he creates a team using the client SDK (I could imagine this is expected as the owner is not yet in the team the moment it is created)

2. Realtime teams.memberships.update.status event is **not** sent to the member updating the status, **nor** the team owner when the member updates his membership status using the client SDK

3. Realtime account.session.delete event is **not** sent to the user when he deletes all sessions using the client sdk (sdk.account.deleteSessions()), but it is sent when deleting the single current session.

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I can confirm membership updates and creating a team works:
<img width="1286" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/f4d3a4f6-027a-4a92-af69-8cf427d9a28f">

I can also confirm a session delete occurs:
<img width="1257" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/76f3313c-31a2-4118-b67b-de1510306f03">

That said, there is an [improvement](https://github.com/appwrite/appwrite/pull/7117) in progress to fire multiple events for the delete session endpoint.
