### ISSUE TITLE
Becoming Truly Cross-Platform

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#263]
We have been getting some users' feedback that really helped us better understand more use-cases of Appwrite.

Some of those use-cases include using Appwrite behind an internal network with a custom backend server as a gateway, and the other is integrating Appwrite in non-web client platforms like electron, unity, and others.

Currently, Appwrite can be tweaked for both use-cases, but the integration doesn't feel native or straight forward. 

The main two things that are stopping us from being truly cross-platform are:

1. The open nature of the web and browsers require us for extra security. We need a built-in way to overwrite origin checks for new platforms. A good solution might be adding the new platform trough the Appwrite console and adding a custom & predefined origin headers for each platform like xbox://app-name or electron://app-name and so on.  

2. The other issue is the way we save the session information across a specific platform. Currently, we only handle this for browsers using cookies to store the user session key after login or registration. For a perfect integration, this should be done automatically for any client platform and in an easy and obvious way for the backend server.

I will love to hear more feedback about this before we are writing a spec for this milestone.

**Comment by eldadfux** [comment]
Implementing the custom origin will also be quite useful when aggregating the API usage stats. This will allow us to calculate usage per origin and help developers analyze, improve performance, and reduce their server costs.

**Comment by eldadfux** [comment]
As a start, I have pushed a commit to the master that skips the origin header validation if the client didn't send it. This will allow easier integration for non-web client-based platforms.

**Comment by eldadfux** [comment]
Full support is ready and will be release with version 0.6 and our new flutter integration.

**Comment by fightforlife** [comment]
@eldadfux is the second problem solved somehow? Does appwrite currently still soley depend on cookies for client/user sessions? Thanks!

**Comment by eldadfux** [comment]
@fightforlife we currently rely only on cookies with fallback to localstorage on the web for browsers that don't support 3rd party cookies. If this is the case you can also set a custom domain and ensure you use only first party cookie. We'll also introduce JWT support in the next version.

**Comment by lovetodream** [comment]
JWT Support would be much appreciated, not only for me, but also for many others I guess.
Keep it up 👍
