### ISSUE TITLE
🐛 Bug Report: Account.create is not triggering function when using Google OAuth. (Issue was there in 0.11 too)

### ISSUE THREAD

**Issue by garvitomer** [appwrite/appwrite#2639]
### 👟 Reproduction steps

1. add a function 
2. add trigger event to account.create
3. Login using google OAuth
4. function will not trigger i.e. there will be no logs!

### 👍 Expected behavior

1. add a function 
2. add trigger event to account.create
3. Login using google OAuth
4. function should get triggered! 

### 👎 Actual Behavior

1. add a function 
2. add trigger event to account.create
3. Login using google OAuth
4. function will not trigger i.e. there will be no logs!
5. Issue was there in 0.11 too

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

No

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
PR is pending here: https://github.com/appwrite/appwrite/pull/2421
Duplicated with #2406
