### ISSUE TITLE
🐛 Bug Report: (db) default value field stays greyed out after adding an attribute with required value set to true

### ISSUE THREAD

**Issue by solnem** [appwrite/appwrite#2645]
### 👟 Reproduction steps

1. Open the Appwrite console
2. In the Database context, create a collection or go to an existing one
3. Navigate to the `Attributes` tab
4. Click on `Add Attribute` and choose an attribute (e.g. `New String Attribute`)
5. Fill out all needed fields, set `Required` to true and create the attribute
6. Try adding another attribute through the `Add Attribute` button

### 👍 Expected behavior

The value of `Required` resets, causing the `Default Value` text field to be "unlocked" again.

### 👎 Actual Behavior

The value of `Required` resets in the UI, but isn't reflected in the `Default Value` text field (still greyed out from previously adding a required attribute).

Here is a screenshot of how it looks:
![image](https://user-images.githubusercontent.com/20548409/150026625-f761a903-00f1-48a3-a8fd-514a1a7b85f6.png)

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Locally deployed

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by solnem** [comment]
Note:
From my observation, this only affects the `Default Value` text field. Even if you don't re-toggle the `Required` toggle, upon creation of another attribute, it's `Required` value will be set to `false` (how it should be).
In other words, unless you specifically toggle the `Required` button, the next attributes' `Required` value will have a default value of `false`, regardless of the previously added attributes' `Required` value.

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻
