### ISSUE TITLE
📚 Documentation: is there a way to NOT HAVE any pre-defined values in an Enum attributes?

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2654]
### 💭 Description

I managed to create Enum attribute using 

result = database.create_enum_attribute('[COLLECTION_ID]', 'MYID', [], True)

Doing so, I am unable to add a document unless the attribute is [] aka "empty array". Which is not very useful. 

I must have missed something in the documentation. 

Could you please point me in the right direction ?

Thx !

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by superseby2** [comment]
Right ... I managed to do what I wanted : having one attributes being an array of ids (to be able to reference other documents in another collections). 
I realized I could use a String and set it as "Array". 
Which makes me wonder : what the heck "Enum" is for ? :)

other question : when using a String as array, length does not seem to work : setting it up to 1 I am still allow to insert ["lalalallal","lelelel"], presuming it is a length for each "cell" ???

I know Apprwrite is growing fast, but it is true that the lack of good documentation makes it sometimes super hard to do simple things.

**Comment by stnguyen90** [comment]
> when using a String as array, length does not seem to work : setting it up to 1 I am still allow to insert ["lalalallal","lelelel"],

What do you mean by length? Do you mean size? If so, according to the [documentation](https://appwrite.io/docs/server/database#databaseCreateStringAttribute), that's the max number of characters allowed.

**Comment by superseby2** [comment]
Using the console, the word "length" is being used while in the API, "size" is being used, which indeed, coud be confusing. I guess using "size" in both would be nice.
Having said that, if size is the max number of characters allowed,  inserting a doc with a field containing ["aa"] shoudl be disallowed if size is set to 1 right? (or I am missing something here?)

Thank you

**Comment by stnguyen90** [comment]
What version are you on? I'm on 0.12.1 and it says Size:

![image](https://user-images.githubusercontent.com/1477010/150827766-feaadcd1-2042-48f8-8709-ffb13ea9cfee.png)

**Comment by superseby2** [comment]
Sorry, it does say "size" in the console. 
I got things mixed-up ... The only length reference I could find is in https://github.com/utopia-php/database/blob/ecc143f2cfe16b23675407035c6b5375ba263285/src/Database/Adapter/MariaDB.php#L1085 but there it is legit .. Sorry for the noise. 

I will create an issue regarding the size set for arrays. 

Thx !
