### ISSUE TITLE
Documentation: Kotlin & Java Code Example Issues

### ISSUE THREAD

**Issue by NobilityDeviant** [appwrite/appwrite#2655]
Hello, I am new to AppWrite. As I have been trying to implement it into my Android Application following the docs, I have noticed quite a few issues on the Kotlin and Java code examples.

Kotlin:

First: [https://appwrite.io/docs/client/database#databaseCreateDocument](url)

Trying this method works for the most part, but the return type is definitely not a Response.
It returns a Document and even says it inside the description.
So this piece of code `val json = response.body?.string()` does not actually compile.
Also it warns me to annotate the function with `@DelicateCoroutinesApi`
I have read that using GlobalScope for this is not ideal.

Java: 

First: [https://appwrite.io/docs/client/database#databaseCreateDocument](url)

It also tries to cast the object to a Response which is going to fail.

```
  Response response = (Response) o;
  json = response.body().string();
```

Is going to throw an error because it's expecting `Document document = (Document) o;`

A lot of these code examples do use `Response` as well even if they say the return type is something else.

Second: [https://appwrite.io/docs/client/account#accountCreateAnonymousSession](url)

```
  try {
                    if (o instanceof Result.Failure) {
                        Result.Failure failure = (Result.Failure) o;
                        throw failure.exception;
                    } else {
                            Response response = (Response) o;
                            json = response.body().string();
                        }                    
                    } //There is an extra bracket here
```

See the comment after the //
These also try to get `Respone` but the return type for this is `Session`

If you look through all the code examples, they expect a `Response`, but does not follow the return types.
I am assuming the library is wrong and the API is right. I would love for this issue to be handled. 

---
Appwrite Version: 0.12.1.201

**Comment by eldadfux** [comment]
cc @abnegate @lohanidamodar

**Comment by lohanidamodar** [comment]
@abnegate looks like we forgot to update the code examples after implementing response model.

**Comment by gewenyu99** [comment]
AFAIK both have been fixed.
