### ISSUE TITLE
Trying get CLI to connect to existing project

### ISSUE THREAD

**Issue by locohost** [appwrite/appwrite#2656]
I'm on DigitalOcean. I used the pre-build droplet. 
I'm ssh'd to the droplet
I already have a project setup and working. I can see it and use it in console.
I have the appwrite CLI installed. It works

I'm struggling with the **appwrite init** prompts

I prompts are not clear about what I am to enter. I've searched and searched and read the official appwrite docs on CLI and I can't find help on what to enter at these prompts.

So no matter what command I enter, I get responseCode: 404 and then a bunch of html output.

Am I simply not finding the right docs or a tutorial on this?

Thank you very much for helping :-)

---
Appwrite Version: 0.12.0.200

**Comment by locohost** [comment]
Ok, trial & error, I got past above.
Now I'm trying to use CLI to create a user (per docs)
I'm getting 401 error on this...

root@appwrite0120onubuntu2004-s-2vcpu-2gb-intel-nyc1-01:/home/repo/function# appwrite users create --email="locohost@mymailservice.com" --password="*****" --userId="locohost"                                                                                                                         message : User (role: guest) missing scope (users.write)
code : 401

Does this look familiar to anyone? How do I get past this?


version : 0.12.0

**Comment by locohost** [comment]
Ok so I'm following the CLI instructions here on Github. You can see below that I clearly did run appwrite init, then followed the instructions. Then I get the error, which I don't understand at all...

![image](https://user-images.githubusercontent.com/132458/150440888-8d2b78a6-715a-4431-8033-8855e0181e1e.png)

**Comment by locohost** [comment]
Ok for anyone seeing this later. When running **appwrite init**, put your project "Id" in the first prompt. In the second prompt it needs the **long API secret string**. You have to manually create the API "key" first, then you need the secret for in the **appwrite init** prompt.

**Comment by stnguyen90** [comment]
Since you've figured this out, are you good to close the issue? If you run into any other questions, feel free to ask on discord: https://appwrite.io/discord
