### ISSUE TITLE
I can only find one function JS example in docs

### ISSUE THREAD

**Issue by locohost** [appwrite/appwrite#2662]
I'm reading through the docs and following links to SDK docs and I'm seeing only one example of JS in a function. It's this...

![image](https://user-images.githubusercontent.com/132458/150554762-d3feb47b-2658-48dc-8a7d-7f512616c5ca.png)

Where can I see detailed documentation on the node-appwrite SDK and/or some JS examples of collection/doc CRUD operations?

Thanks for any help :-)

---
Appwrite Version: 0.12.0.200

**Comment by locohost** [comment]
Ok, for anyone finding this later. Here is a very good article on using appwrite SDK for querying. Big thanks to the author!

[](https://dev.to/appwrite/become-a-master-of-the-database-using-appwrites-new-query-api-5ge4)

**Comment by eldadfux** [comment]
Credits to @PineappleIOnic. You can also find code example in the REST spec we have in the docs.

![image](https://user-images.githubusercontent.com/1297371/150733084-0eccf4f3-ab0d-4b7d-b5dc-a3bf178c84ae.png)
