### ISSUE TITLE
🐛 Bug Report: listing documents with Python SDK only first 25 documents being retrieved

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2665]
### 👟 Reproduction steps

- create a api key with all scopes enabled
- run python code configured with that key 
- ```

database = Database(client)
result = database.list_documents('[COLLECTION_ID]')

```

### 👍 Expected behavior

- result should be all documents retrieved because we are in admin mode

### 👎 Actual Behavior

- retrieving only the first 25

### 🎲 Appwrite version

Version 0.12.x
sdk-version': 'appwrite:python:0.6.0',                                                                   



### 💻 Operating system

Linux

### 🧱 Your Environment

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
The default limit for a single API call is 25 documents, you can change the limit with the `limit` param as mentioned here: https://appwrite.io/docs/server/database?sdk=python-default#databaseListDocuments

This limit was designed to protect your Appwrite instance from abuse.

**Comment by superseby2** [comment]
I am using an API key (maybe I did not specify it in the original bug
report) so I should be in admin mode right ? Hence not having the 25
documents restriction. Or am I understanding things not properly ?

**Comment by superseby2** [comment]
Just looking @ https://github.com/appwrite/appwrite/blob/0.12.1/app/controllers/api/database.php and I cannot see any reference to USER_ADMIN_MODE that would make the limit when retrieving documents go away. 

While the doc says "On admin mode, this endpoint will return a list of all of the project's documents."
Maybe I am not in admin mode? Please advise. 

(As a workaround, I am looping over 25 docs and using the cursor to get all the documents. A bit of a pain.)

**Comment by eldadfux** [comment]
This line `On admin mode, this endpoint will return a list of all of the project's documents.` means regardless of any document level permission that might have been set. I'll try to make docs more clear. You can still increase the list limit to 100 if it helps.

That said, this limit is important. Think of a collection with 10k or even a 1m records, trying to get them in a single request would hang your Appwrite API (or any API) and your client. We have designed the API to make sure it stays reliable no matter what user requests are coming in, from both client and server. The server protection is very handy if you're hosting other tenants on your server.

**Comment by eldadfux** [comment]
Updated docs here: https://github.com/appwrite/appwrite/pull/2724

**Comment by superseby2** [comment]
Makes total sense.. Thx !

**Comment by Dosbodoke** [comment]
There are some cases where this behavior is limiting the application.

For example, I created a function `GetAllNotes` where I want to get all documents of the collection `notes` where the attribute `flagId` is on my array. The problem is that a user can have hundreds of flags and get limited by the Appwrite default limit.

The solution that I found was to splice the array in chunks of 100 and then get the related notes.

```
  const notes = {}
  const profileData = {}
  const chunkSize = 100

  // Itarate over the flagIdlist and get the notes of the current chunk.
  // For each note, check if the writer data is stored, if not get and store it
  // to reduce the number of requests.
  for (let i = 0; i < task.flagIdList.length; i += chunkSize) {
    const flagIdChunk = task.flagIdList.slice(i, i + chunkSize)
    const notesChunk = await database.listDocuments(
      req.variables["APPWRITE_DATABASE_ID"],
      "note",
      [sdk.Query.equal("flagId", flagIdChunk), sdk.Query.limit(chunkSize)]
    )
    notesChunk.documents.forEach(async (document) => {
      const writerId = document["writerId"]

      if (!profileData[writerId]) {
        const writer = await users.get(writerId)
        profileData[writerId] = writer.name
      }

      notes[document.flagId] = notes[document.flagId]
        ? [
            ...notes[document.flagId],
            { ...document, writerName: profileData[document.writerId] },
          ]
        : [{ ...document, writerName: profileData[document.writerId] }]
    })
  }
```

This still has some problems. If the first flag has 100 notes associated, the Query will not work as expected.

I wish we had some option to eliminate this limit on the function environment. I understand that is helpful, but it shouldn't be limiting the application.

**Comment by msLinuxNinja** [comment]
I can confirm this is still an issue and it is not properly documented. While in my case I'm using the javascript client, the behavior is the same. Ideally these limits and their workarounds should be properly documented.

**Comment by Dosbodoke** [comment]
> I can confirm this is still an issue and it is not properly documented. While in my case I'm using the javascript client, the behavior is the same. Ideally, these limits and their workarounds should be documented appropriately.

More than being documented, the limit should be configurable per API Key. There are many cases where a Function needs to list more than 25 (100 max) items.

I have repeatedly gotten myself on the pattern of fetching multiple times 100 items, otherwise, I would get the data necessary.

```Typescript
  const data = JSON.parse(req.variables["APPWRITE_FUNCTION_DATA"])

  const flagIdList = data["flagIdList"]

  const chunkSize = 100
  const flags = []

  for (let i = 0; i < flagIdList.length; i += chunkSize) {
    const flagIdChunk = flagIdList.slice(i, i + chunkSize)
    const flagsChunk = await database.listDocuments(
      req.variables["APPWRITE_DATABASE_ID"],
      "flag",
      [sdk.Query.equal("$id", flagIdChunk), sdk.Query.limit(100)]
    )
    flags.push(...flagsChunk.documents)
  }
  ```
  
  There is any issue addressing this? I don't think this should be closed.
