### ISSUE TITLE
📚 Documentation: does not create the index if it is capitalized (Key, Unique, Fulltext)

### ISSUE THREAD

**Issue by rafaelgazani** [appwrite/appwrite#2668]
### 💭 Description

create an index. In the documentation it is capitalized (Key, Unique, Fulltext)
but if I try to create this way, it fails.

the right thing was to use key, unique, fulltext
i am using python sdk and appwrite 0.12

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rafaelgazani** [comment]
https://appwrite.io/docs/database#indexes

**Comment by eldadfux** [comment]
Created a fix here to make things more obvious. 
https://github.com/appwrite/docs/pull/136

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed on the docs 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻
