### ISSUE TITLE
Getting started for web guide clarity for platform URL 

### ISSUE THREAD

**Issue by nzlrhyz** [appwrite/appwrite#267]
Just a little clarity for the URL input during platform selection  as I would of expected it to work fine either way. The trailing slash causes Origin errors.
![unknown](https://user-images.githubusercontent.com/29303391/70684913-b31c2280-1d0c-11ea-957a-0acf687e5d05.png)

**Comment by eldadfux** [comment]
Thanks for your feedback. I guess the best solution will be to make sure the origin validation can work both ways or at least to make sure we validate the input on the dashboard / API.

I'll assign this issue for 0.5.

**Comment by eldadfux** [comment]
Thinking about changing this to a hostname instead of a URL. That way users won't have to add a record for each protocol (https / http) or port number.

**Comment by nzlrhyz** [comment]
I actually think that's a great idea, would make quite simple then

**Comment by eldadfux** [comment]
Done on this commit:
https://github.com/appwrite/appwrite/commit/92babbd21a5b42967ad18918247178cd70c808f9

Will be part of the 0.5 release 🎉

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/77216792-e3523900-6b25-11ea-8bd5-731c2cf83f62.png)
