### ISSUE TITLE
🐛 Bug Report: listDocuments not working correct using readPermissions

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#2674]
### 👟 Reproduction steps

When i create a new collection and add 1000 documents with a readpermission for a teammember (for example team:123) to it, and later query this collection using listDocuments it returns not 1000 documents. - its missing about 50 - 100 documents

expample:
- create new collection
- create new team and add your user to the team
- create 1000 documents in the collection with a readpermission to the newly created team
- query the documents with the user by using listDocuments

-> its returning not 1000 documents

edit: if i query the collection with an admin key its working proberly and returning 1000 documents

### 👍 Expected behavior

if i add 1000 documents it should return 1000 documents when i query them

### 👎 Actual Behavior

there are always missing a couple of documents

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I also tested this and experienced the same problem. Even with document read permission of `role:all` I didn't get all the data in the database (the sum is less than 1000).

**Comment by stnguyen90** [comment]
If I switch it to Collection level permissions with read permission of `role:all`, `sum` changes to 1,000 documents as expected. Switching back to Document level permission makes the `sum` drop down to ~980 again.

**Comment by s3ppo** [comment]
I think this happens not only to large datasets.. i sporadicaly miss single documents in datasets with 10 documents or smaller.. but this is very rare

**Comment by stnguyen90** [comment]
Any update on this?

**Comment by sbergmair** [comment]
In my case:
I added single documents (about one document each 5 minutes), I had 6 documents in my collection and only got 3 documents back. After switching to permissions on collection level, it worked. Switching back, then only the documents with changed permissions were shown, the other are hidden as before changing to permissions on collection level.

**Comment by AhmedHammad0900** [comment]
Want add That

The Api is returning Empty Documents "[]" with Sum : 0 if it's related to document Level
While it's working in Collection Level
=================================
Bug Happening when You use the second attribute before the first one .. use attributes in sequence in Collection Level and it will work greatly for now ..

**Comment by rvndsngwn** [comment]
Same issue with me. Also, you can see the conversation about this issue on [Discord chat](https://discord.com/channels/564160730845151244/564161855862603789/957194924426682419). 

Some other data you can see in the screenshot.



![Screenshot 2022-03-26 at 7 45 09 PM](https://user-images.githubusercontent.com/59143934/160248961-bc4f602c-f31d-401f-86fc-39bbe65c5f2b.png)
![Screenshot 2022-03-26 at 7 45 54 PM](https://user-images.githubusercontent.com/59143934/160248968-7099b20d-d224-445b-a188-2c484fc27bee.png)
![Screenshot 2022-03-26 at 7 46 40 PM](https://user-images.githubusercontent.com/59143934/160248970-a2f9d6a1-d770-4c55-bae6-838959e7a994.png)
![Screenshot 2022-03-26 at 9 13 15 PM](https://user-images.githubusercontent.com/59143934/160248973-df246fe2-b3b7-4788-bee9-d7854d30355b.png)
![Screenshot 2022-03-26 at 9 17 52 PM](https://user-images.githubusercontent.com/59143934/160248974-596dcae1-f6fd-46e5-a7d9-c4c17434dc1d.png)
![Screenshot 2022-03-26 at 10 04 19 PM](https://user-images.githubusercontent.com/59143934/160248977-2cf79e1d-0a9c-492b-b0a5-5d4f8ed3f221.png)
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-03-26 at 20 08 16](https://user-images.githubusercontent.com/59143934/160248979-ef8d517f-faae-4f96-ae73-d08f346bd64f.png)

**Comment by TorstenDittmann** [comment]
This should've been fixed with 0.13 actually. On what version of Appwrite are you? @rvndsngwn

**Comment by rvndsngwn** [comment]
> This should've been fixed with 0.13 actually. On what version of Appwrite are you? @rvndsngwn

I'm using Appwrite v:0.13.4.304

**Comment by rvndsngwn** [comment]
close this issue.

**Comment by barshag** [comment]
happen to me also...i think it didn't fixed..
