### ISSUE TITLE
🐛 Bug Report: I cant create boolean attribute

### ISSUE THREAD

**Issue by tananga** [appwrite/appwrite#2677]
### 👟 Reproduction steps

Im following https://dev.to/appwrite/did-we-just-build-a-netflix-clone-with-appwrite-28ok

I can't create "isOriginal". I see failed next to the attribute name. Please take a look on photos.

![Screenshot 2022-01-24 at 07 33 05](https://user-images.githubusercontent.com/44244477/150737901-fe5370b9-5afc-4ebf-bc75-078ab45efc08.png)
![Screenshot 2022-01-24 at 07 26 44](https://user-images.githubusercontent.com/44244477/150737918-68482e6c-eb6c-4445-860a-5ed6b5cecb9a.png)
![Screenshot 2022-01-24 at 07 26 39](https://user-images.githubusercontent.com/44244477/150737924-1a8ddf0f-7c11-4308-beb4-8f6c9b7c85a8.png)
![Screenshot 2022-01-24 at 07 23 19](https://user-images.githubusercontent.com/44244477/150737927-3706d5cc-8e83-451b-90e7-9894449cebde.png)

### 👍 Expected behavior

Should works

### 👎 Actual Behavior

It doesnt work

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

I use normal macbook

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻
