### ISSUE TITLE
🐛 Bug Report: Long email cut off on user list

### ISSUE THREAD

**Issue by saibotma** [appwrite/appwrite#2678]
### 👟 Reproduction steps

- Add user with long email
- Open user list on appwrite dashboard

### 👍 Expected behavior

Email should not be cut off, when screen is wide enough.

### 👎 Actual Behavior

Email is cut off, even though there is enough horizontal space on screen.
<img width="1467" alt="Screenshot 2022-01-24 at 09 40 16" src="https://user-images.githubusercontent.com/26022902/150749343-71d42850-56bb-4766-9687-69f9003d3973.png">

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Not relevant.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by wess** [comment]
If you hover over the email you will get the full email address, if you click on the user you will get their info page including a full view of the email. What is the use case for this being extended in the UI?

**Comment by saibotma** [comment]
Unfortunately, nothing happens when I hover over the email (I am using Firefox).
Yeah, clicking on the user works, obviously. However, when you have to scan a long list of users for a specific Email-Address by hand, then clicking every user is not expedient.

**Comment by eldadfux** [comment]
Create a PR that add proper text hovering for both users and teams.

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻
