### ISSUE TITLE
🐛 Bug Report: SO。。。。

### ISSUE THREAD

**Issue by AiPacino** [appwrite/appwrite#2686]
### 👟 Reproduction steps

![Jietu20220125-163559](https://user-images.githubusercontent.com/8651400/150941536-1681fe8d-a6a7-42b5-9972-11e88a8472d9.jpg)
![Jietu20220125-163618](https://user-images.githubusercontent.com/8651400/150941549-686e8d02-ef53-488a-9ae0-125b7ca4b0ce.jpg)
![Jietu20220125-163635](https://user-images.githubusercontent.com/8651400/150941563-260dbc8d-3daf-4864-8f94-52201226e2e4.jpg)

### 👍 Expected behavior

so

### 👎 Actual Behavior

so

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

so

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
You're using an old version of the SDK with a new version of Appwrite. Also `*` was deprecated and replaced with `role:all`
