### ISSUE TITLE
CORS issue while calling from a domain

### ISSUE THREAD

**Issue by jithinlal** [appwrite/appwrite#2687]
I have a front end app that is hosted via netlify.
The app calls the appwrite SDK, but receives a cors error in return.

Can anyone please help on this?

**Comment by eldadfux** [comment]
You need to list you new domain as a new web platform for CORS to work.

![image](https://user-images.githubusercontent.com/1297371/150962010-3b13a5b8-8145-4325-8cd1-66c400a73cc5.png)

**Comment by jithinlal** [comment]
Missed that.

But once i add my domain, and i am running my appwrite as a localtunnel. 
Is it possible for me to call the SDK APIs in such a way?
