### ISSUE TITLE
Save IP metadata on documents to minimise DB queries on session requests

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#270]
Improve session request performance by pre-saving the IP metadata. The IP queries can take up to 1-2 seconds which can be really slow for UI operations.

**Comment by PedroCisnerosSantana** [comment]
Hey @eldadfux could you please explain it more?

**Comment by eldadfux** [comment]
Today, when we call the route GET account/sessions the server is live checking the location of the user sessions IP to return the session country name every time we send a request. This action can take up to 2 seconds, which is really slow for a REST API.

The idea here is to check the country name only when the session is first created and save the result to the DB. That way, any call made to get this data will be much faster (just a few ms) as we don't need to look for this data in the Appwrite GEO DB every time again and again.

**Comment by eldadfux** [comment]
Gonna postpone this feature to a future version. Thanks to Swoole, the IP database is now being loaded to memory on the server startup, which has already improved performance of this action dramatically.
