### ISSUE TITLE
🚀 Feature: Add WSO2 Provider

### ISSUE THREAD

**Issue by leonansaraiva** [appwrite/appwrite#2701]
### 🔖 Feature description

Possibility of oauht2 authentication with WSO2
Requirements:
get the acess_token and id_token
configure authorization server end points addresses to get access_token, get user, code_authorization

### 🎤 Pitch

wso2 is an identification platform that makes it possible to create an authorization service, this functionality will allow covering many systems

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Closing for now, happy to re-open if someone would like to make a PR for this.
