### ISSUE TITLE
🐛 Bug Report: Sentry Says Stacktrace is Missing

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#2707]
### 👟 Reproduction steps

1. Configure the logging provider to use Sentry
2. Trigger a 500 error (as of today, if you create/update a document with a text attribute greater than size, it will trigger a 500 error)

### 👍 Expected behavior

Sentry says it received a stacktrace and shows it formatted like:

![Screenshot from 2022-01-27 20-06-50](https://user-images.githubusercontent.com/1477010/151485674-5ab1c3e3-7bc1-42c4-ac04-68e8f0de3f06.png)

Clicking into the details:

![Sample Stacktrace](https://user-images.githubusercontent.com/1477010/151485463-80ec2cc1-4779-4a15-9361-47566ae4138a.png)

### 👎 Actual Behavior

Sentry says there is no stacktrace:

![Sentry Screenshot](https://user-images.githubusercontent.com/1477010/151485474-bdbbbaaa-b5be-411c-9cd5-c70b1c12986c.png)

Detail:

![Screenshot from 2022-01-27 20-09-01](https://user-images.githubusercontent.com/1477010/151485848-9e3e0085-be09-4836-a1d1-74efbc34ec73.png)

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by PineappleIOnic** [comment]
A patch has been merged for this issue at: https://github.com/utopia-php/logger/pull/10 the next version should be released with these fixes. Thank you for reporting this issue! 🎉

**Comment by eldadfux** [comment]
This feature is now released and available as part of Appwrite 0.14. More on the new release here: https://github.com/appwrite/appwrite/discussions/3240
