### ISSUE TITLE
🐛 Bug Report: Logging Sends Duplicate Event

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#2708]
### 👟 Reproduction steps

1. Configure a Logging Provider
2. Trigger a 500 error (as of today, creating/updating a document with size greater than the max size will trigger 500 error)

### 👍 Expected behavior

1 event is sent

### 👎 Actual Behavior

2 events are sent:

![Screenshot from 2022-01-27 20-14-27](https://user-images.githubusercontent.com/1477010/151486282-522bc0e7-9402-46b6-8f2f-08fa004b3b11.png)

![Sentry Duplicate Event](https://user-images.githubusercontent.com/1477010/151486308-fe29d1f8-13ae-4771-a83e-1c5b7d094062.png)

The top event doesn't have the project ID, but the bottom event does.

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by benceHornyak** [comment]
Looks like the same thing occured to me:

![image](https://user-images.githubusercontent.com/12515595/153293703-fdecb994-c65d-40ec-8a04-674e9379b4bf.png)

One event has the projectId correctly and the other one is missing that 🤔

**Comment by PineappleIOnic** [comment]
This issue will be fixed by the PR: https://github.com/appwrite/appwrite/pull/2964. These fixes will be released with the next version of Appwrite. Thank you for reporting this issue! 🎉

**Comment by eldadfux** [comment]
This feature is now released and available as part of Appwrite 0.14. More on the new release here: https://github.com/appwrite/appwrite/discussions/3240
