### ISSUE TITLE
🚀 Feature: Adding scrypt algo

### ISSUE THREAD

**Issue by tannermeade** [appwrite/appwrite#2709]
### 🔖 Feature description

Add support for the scrypt algo.

Comes from a discord conversation between Tanner and Eldadfux: https://discord.com/channels/564160730845151244/564161855862603789/936507537736491091

### 🎤 Pitch

Appwrite currently uses bcrypt because it was the "best" algo at the time. There is another algo that is incrementally better called script. While there can be a discussion about if scrypt is needed or not, what is important is that Firebase and other systems use scrypt. So if anyone from Firebase wants to start using Appwrite, the scrypt hashes are not supported right now.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by tannermeade** [comment]
@Meldiron Firebase uses a modified version of scrypt that AES encrypts the hash. This pull request will be implementing the unmodified version of scrypt (Colin Percival) correct?

If so, that'll work well. When importing hashes, the firebase hashes will need to be unencrypted outside of AES before importing, however that is doable.

**Comment by Meldiron** [comment]
I can proudly share that I have tests passing in my PR regarding MD5 (older systems), BCrypt (many systems), PHPass (WordPress), SCrypt (a bit safer one, not sure who uses it), SCryptModified (Google's fork of scrypt)

**Comment by TorstenDittmann** [comment]
This got implemented and released with Appwrite 1.0.0 🥳 

Thank you for your contribution 🙏🏻  You can read more [here](https://appwrite.io/1.0).
