### ISSUE TITLE
New Features for File Previews

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#271]
Currently, our file preview route (https://appwrite.io/docs/storage#getFilePreview) has some basic features to manipulate preview images. Today we support: cropping image size, changing its quality, changing the background color, and converting the result output format (including WEBP support).

Some of the new features planned are:
* Change scale (or zoom)
* Change image rotation
* Add border (+setting the border color)
* Add gravity param (to force focus position when cutting the image)
* Opacity filter
* Corner Radius

This is planned for v0.6.0. Please add your notes, feedback, and ideas!

**Comment by eldadfux** [comment]
Another thing really important to mention is that some of the new image manipulation features will also reflect on the avatars service (https://appwrite.io/docs/avatars).

**Comment by eldadfux** [comment]
hey @christyjacob4 , do you think you'll be able to work on this for 0.6?

**Comment by christyjacob4** [comment]
Hey @eldad could you tell me the release schedule for 0.6?


Thank you

**Comment by eldadfux** [comment]
Our goal right now is to move to shorter, feature based release cycles. So when you're ready we'll aim to release this. 0.6 is scheduled for the DB UI feature, but if this we'll be ready sooner we can ship the DB UI with 0.7.

**Comment by eldadfux** [comment]
Hey @christyjacob4 please let me know if you can work on this or should we try and find someone else to work on this 🙏🏻

**Comment by christyjacob4** [comment]
@eldadfux I will work on this 👍

**Comment by christyjacob4** [comment]
@eldadfux I feel that I should also add a flag to preserve the aspect ratio of the image

**Comment by eldadfux** [comment]
Hehe cool 👍🏻

**Comment by eldadfux** [comment]
Hey @christyjacob4 , could you please submit a PR with what you’ve done so far? I have some free time this weekend and I’d love to adapt this to the architecture changes in 0.7

**Comment by christyjacob4** [comment]
Hey eldad, I went through my local files but unfortunately they got overwritten or something and I had not pushed it to remote. I will rewrite the functionality I had done and push it by tonight

**Comment by eldadfux** [comment]
Thanks you so much @christyjacob4, please let me know if I can help in anyway. 🙏🏻

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/appwrite/releases/tag/0.8.0 👏🏻
