### ISSUE TITLE
🚀 Feature: Adding Hash Option to Server API

### ISSUE THREAD

**Issue by tannermeade** [appwrite/appwrite#2710]
### 🔖 Feature description

Add an option in the server API to choose a hashing format of the password. For example plain or bcrypt. Plain is default (string converted to bcrypt). If its already in bcrypt we can skip the hashing and just store the string.

Comes from a discord discussion between Eldadfux and Tanner: https://discord.com/channels/564160730845151244/564161855862603789/936504708976234547

![api](https://user-images.githubusercontent.com/46303912/151499817-650dc48c-f4f9-457d-9d0b-e8903f9ab2bf.png)

### 🎤 Pitch

The use case here is migrating data into Appwrite. If someone has user information that they want to import, there currently is no way to store the hashed passwords in the database without circumventing Appwrite.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by tannermeade** [comment]
This plays into the purposes of this feature as well: https://github.com/appwrite/appwrite/issues/2709

**Comment by eldadfux** [comment]
Rethinking this issue, instead of `format`, I think `hash` might be more descriptive. We should also research what popular hashing algos we should support. @tannermeade have any suggestions?

**Comment by Meldiron** [comment]
> Rethinking this issue, instead of `format`, I think `hash` might be more descriptive. We should also research what popular hashing algos we should support. @tannermeade have any suggestions?

MD5 is really common for older applications. It is not considered secure, but if the point is to support importing from existing services, we could consider supporting MD5 too.

**Comment by eldadfux** [comment]
Yeh, I think MD5 should be good as long as we don't offer it as a choice for new users, but only for importing. Maybe we can also warn in the UI, that the user hashing algo is outdated.

**Comment by tannermeade** [comment]
@Meldiron Firebase uses a modified version of scrypt that AES encrypts the hash. This pull request will be implementing the unmodified version of scrypt (Colin Percival) correct?

If so, that'll work well. When importing hashes, the firebase hashes will need to be unencrypted outside of AES before importing, however that is doable.

@eldadfux The only other "feature" around hashing that I can think of would be adding support for AES encrypting the password hashes as Firebase does, but I don't see that has something that is very important. Like maybe down the road, but that gets into changing the default algo which can make things messy.

**Comment by eldadfux** [comment]
> @eldadfux The only other "feature" around hashing that I can think of would be adding support for AES encrypting the password hashes with a pepper as Firebase does, but I don't see that has something that is very important. Like maybe down the road, but that gets into changing the default algo which can make things messy.

I can see how it might make things messy as we already implemented our own encryption for the hashes when stored internally in Appwrite.

**Comment by tannermeade** [comment]
@Meldiron @eldadfux we do need to make sure and add a salt parameter to the API. I'm assuming Appwrite already salts the passwords before hashong them which has been bad practice to not do for a long time.

Without a salt, the hash would be useful.

**Comment by tannermeade** [comment]
I'm looking into adding support for Argon2 (probably Argon2id) to this feature myself. I believe there might be a good amount of people out there with non-firebase systems that use that algo because it is often recommended as "better" than bcrypt since it won the 2015 Password Hashing Competition (although many sources say that is only true when the hashing time is over 1 second).

**Comment by Meldiron** [comment]
Added Argon2 support into my PR 😇

**Comment by TorstenDittmann** [comment]
This got implemented and released with Appwrite 1.0.0 🥳 

Thank you for your contribution 🙏🏻  You can read more [here](https://appwrite.io/1.0).
