### ISSUE TITLE
📚 Documentation: Rules Documentation Still Accessible

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#2714]
### 💭 Description

The old [Rules documentation](https://appwrite.io/docs/rules) is still accessible and shows up as the first result from Google when searching for "Appwrite nested documents":

![image](https://user-images.githubusercontent.com/1477010/151594134-3c61a830-8349-479e-965f-0bce133c1c96.png)

This can be confusing for newcomers to Appwrite since Rules and Nested Documents are no longer available as of 0.12.

It would be best to show some sort of warning to indicate the documentation is for versions older than 0.12 and is no longer applicable for 0.12 (and above).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Removed the template: https://github.com/appwrite/docs/pull/159
