### ISSUE TITLE
🐛 Bug Report: Setting function events from CLI doesn't seem to work

### ISSUE THREAD

**Issue by locohost** [appwrite/appwrite#2715]
### 👟 Reproduction steps

When I run this command in appwrite CLI...

appwrite functions create --functionId=region_on_create_or_update --name=region_on_create_or_update --execute=['role:all'] --events=['database.documents.create', 'database.documents.update'] --runtime=node-16.0 --vars={ 'LT_API_ENDPOINT': 'https://appwrite.myapp.com/v1', 'LT_PROJECT_ID': '61e...7e4ff', 'LT_FUNCTIONS_SECRET': '3b4b478e5a5576cdab8a...fc2261cb8a8b3bfee' }

### 👍 Expected behavior

When I look at the function settings in the console, I expected to see 2 events to checked: **database.documents.create** and **database.documents.update**

NOTE: I tried the --events array both with and without the single quotes. I fails same both ways.

### 👎 Actual Behavior

It actually shows NO events checked when I look at function settings in console.

After running the command in CLI, my terminal shows...

![image](https://user-images.githubusercontent.com/132458/151613389-1e1dad06-c37c-4055-9992-48ca5e5bd2a9.png)

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 🧱 Your Environment

My appwrite is running on Digitial Ocean droplet.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@locohost This should be fixed with the new updated CLI. Please install the latest CLI from https://appwrite.io/docs/command-line

**Comment by stnguyen90** [comment]
@locohost, are you still having a problem with this or can this be closed now?
