### ISSUE TITLE
🚀 Feature: add helm chart

### ISSUE THREAD

**Issue by ivanmissu** [appwrite/appwrite#2717]
### 🔖 Feature description

add helm chart 

### 🎤 Pitch

friendly to k8s install

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Duplicated with #24
