### ISSUE TITLE
The password do not  encrypted in Flutter when create new user

### ISSUE THREAD

**Issue by haohongwei** [appwrite/appwrite#2719]
Hi， I am a new user of appwrite.

When I use it to create a new user in my app, it seems that the password of the user did not encrypted before sending the post request.

**Comment by eldadfux** [comment]
Appwrite arrives with built-in TLS certificates generator using Letsencrypt. This allows Appwrite and your client to perform secure communication over HTTPS. After the password arrives to the Appwrite API, Appwrite is hashing it and stores it securely in the internal database. Every following request will compare between the use password and the stored hash.
