### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#272]
This issue will concentrate all the information regarding the work on the new GraphQL gateway for the Appwrite server. Work on this feature is being actively developed on this branch: https://github.com/appwrite/appwrite/tree/graphql

The new GraphQL is not meant to replace the REST API, but to work alongside it. The goal of this feature is to allow developers to take advantage of the GraphQL capabilities but not force them to work with it. In an ideal setup, developers could integrate with both the GraphQL and the REST API in the same application.

The work on this feature relies heavily on this issue: https://github.com/appwrite/appwrite/issues/266 should allow the implementation of the GraphQL objects to become much easier and 100% consistent with the REST API.

First, the work will concentrate on adding query and mutation action for basic Appwrite entities/resources like database documents and storage files, and later support for all resources.

**Comment by danielxharris** [comment]
This could be a good starting point for implementing the protocol:
https://github.com/webonyx/graphql-php

**Comment by alexweininger** [comment]
This sounds awesome, I can't wait! Keep up the great work

**Comment by christyjacob4** [comment]
@alexweininger you can track our progress here 😊🚀 

https://github.com/appwrite/appwrite/pull/974

**Comment by Parables** [comment]
I learnt that appwrite is written in PHP.

If yes, then give [Lighthouse PHP](https://lighthouse-php.com/) a shot. Works magic. Can work alongside the REST API

**Comment by Parables** [comment]
I would love to take this one on for the love of appwrite 
but I am currently working on so many things at the  moment

I will let you know when I am available

**Comment by TorstenDittmann** [comment]
> I learnt that appwrite is written in PHP.
> 
> If yes, then give [Lighthouse PHP](https://lighthouse-php.com/) a shot. Works magic. Can work alongside the REST API

Interesting, @christyjacob4 has been working on it - maybe he'll find it interesting 👍🏻

**Comment by johannesschobel** [comment]
what is the current state of the GraphQL implementation? Would be very interesting for me and an upcoming project.
The `graphql` branch is stale for nearly 2 years now..

All the best

**Comment by eldadfux** [comment]
Two years later. GraphQL support is now LIVE. We would love your feedback and suggestions as we look into learning how to make this new API even better.

Learn more: 
https://appwrite.io/graphql
