### ISSUE TITLE
🐛 Bug Report: MIN are MAX values do have default values if you do not have them filled in

### ISSUE THREAD

**Issue by Caryntjen** [appwrite/appwrite#2723]
### 👟 Reproduction steps

Create a float through the webserver UI and do not set any MIN or MAX values or only fill in MAX value

### 👍 Expected behavior

The attribute should not have any values in min or max

```
When MIN or MAX are not filled in
        {
            "key": "TEST",
            "type": "double",
            "status": "available",
            "required": false,
            "array": false,
            "min": null,
            "max": null,
            "default": null
        }
With only MIN filled in as 0
        {
            "key": "test",
            "type": "double",
            "status": "available",
            "required": false,
            "array": false,
            "min": 0,
            "max": null,
            "default": null
        }

```
### 👎 Actual Behavior

It does set a default value for min and max
```
Only MIN filled in:
        {
            "key": "TEST",
            "type": "double",
            "status": "available",
            "required": false,
            "array": false,
            "min": 0,
            "max": 1.7976931348623157e+308,
            "default": null
        }
MIN or MAX not filled in:     
        {
            "key": "test2",
            "type": "double",
            "status": "available",
            "required": false,
            "array": false,
            "min": -1.7976931348623157e+308,
            "max": 1.7976931348623157e+308,
            "default": null
        }
```

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite v0.12.1 - sdk-for-kotlin v0.2.5
Java v11
Kotlin v1.6.10

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
These are actually the maximum values PHP can handle, thats why they are set by default.

We show them to give transparency of whats actually possible.

**Comment by Caryntjen** [comment]
@TorstenDittmann thank you for clarifying. Might be useful in the documentation?

**Comment by hey-nicolasklein** [comment]
I would also like to see the default values and scale for the size. The empty fields in the dashboard without any scale are not well suited for beginners.
