### ISSUE TITLE
🚀 Feature: User should be able to delete his own account

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#2734]
### 🔖 Feature description

i found the method account.delete() but it just blocks the account.

### 🎤 Pitch

i think in the EU it is needed to offer your users to delete their own data.. this is not possible at the moment.

maybe a workaround with a cloud function but i think it should be possible without..

here is a TODO for the endpoint in the code ;) 
https://github.com/appwrite/appwrite/blob/efbfbd6f79a261dc24a0b83a4ee50d8337ceb8a5/app/controllers/api/account.php#L1526-L1529

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Swinkid** [comment]
To be honest , I think keeping it a cloud function is probably a good idea to avoid having documents / files being orphaned. 

Keeping it as a cloud function forces the developer to think about what and where things should be deleted.

**Comment by s3ppo** [comment]
> To be honest , I think keeping it a cloud function is probably a good idea to avoid having documents / files being orphaned.
> 
> Keeping it as a cloud function forces the developer to think about what and where things should be deleted.

😂😂 i like the way you think but this is not how a professional product should work: „lets make it dont work to protect them from theirself“ 😉

**Comment by eldadfux** [comment]
We will update the existing `DELETE /account` method to be `PATCH /account/status`. This better reflects the behavior of this route which is actually to block the account and not delete it.

We're still not enabling delete account directly from the client because of the possibility to hijack resources shared with the current user ID after deletion. You can delete user from the console, server API or Functions.

**Comment by s3ppo** [comment]
@eldadfux i think i dont understand it yet, what ressources can be hijacked if the user deletes his account? And what is the difference if i delete the account in a cloud function? 😅

**Comment by TorstenDittmann** [comment]
This should be fixed now 👋🏻
