### ISSUE TITLE
🚀 Feature: Internal sub-queries for sessiions

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2736]
### 🔖 Feature description

Start using sub-queries on sessions, just like we do for `indexes` of `collections`.

### 🎤 Pitch

We currently have duplicate data of sessions. One is in the `sessions` attribute of users, the other one is in separate `sessions` collection. There is no collection between these two, so it makes code a little messy - we need to do changes to both.

Ideally we should have `subQuery` for sessions attribute on users, pointing to sessions collections. This way we don't need to update both on our own, we can simply update `sessions`collection, and wipe the cache of `users` collection for the specific user. This way the code is way mora clear, and easier to update&extend.

Example of duplicate write action:  https://github.com/appwrite/appwrite/blob/50f6c4dd1cacbee94f5e5838edf7c7e186383a14/app/controllers/api/account.php#L206-L212

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Meldiron, this can be closed now, right?

**Comment by Meldiron** [comment]
I believe so 🥳 Released with 0.14
