### ISSUE TITLE
🚀 Feature: relations between collections

### ISSUE THREAD

**Issue by apperside** [appwrite/appwrite#2737]
### 🔖 Feature description

It would be truly amazing if we could create relations between collections, like you would do in a traditional sql database.

### 🎤 Pitch

 I know, and understand, that appwrite is based on a NoSQL engine, but this feature would add a really big added value.
I imagine it as a new field type added to the existing ones, so when you create a new collection attrubute, you can choose "relation", and then you should choose which collection you want to reference

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Closing in favor of #2735
