### ISSUE TITLE
🚀 Feature: Support logical OR in queries

### ISSUE THREAD

**Issue by outrelouxhe** [appwrite/appwrite#2740]
### 🔖 Feature description

You should add `OR` support in queries.

### 🎤 Pitch

In my use-case, I need to download thousands of documents matching a OR condition. This is required as I need to keep in sync a local database with appwrite. At the moment, I have to fire multiple queries (with multiple requests with cursor for each of them) to simulate the OR but the overlap between the queries can be more than 90%, sometimes 100%. So it's a waste of time and server resources to download multiple times the same documents again and again.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Thank you for opening this issue. We have kept this issue open for now to gather community feedback and opinions on this issue.

**Comment by byawitz** [comment]
Also, see this https://github.com/appwrite/appwrite/issues/5491

**Comment by ameerfayiz** [comment]
much required feature as backend developers. this issue makes us feel like the appwrite is not production ready yet

**Comment by eldadfux** [comment]
This feature is on the roadmap and should be released in one of the next versions. @byawitz the syntax you suggested seems to be the leading candidate for implementation. We'll be happy to discuss more relevant feedback or questions here.

**Comment by joeyouss** [comment]
Hey @AidenY69 It's tough to give an exact estimate, but we're actively working on it and aiming to include it in future releases. To stay updated on the progress and any developments, I recommend keeping an eye on the this issue.

**Comment by TechComet** [comment]
It is unfortunate that it is a fundamental thing in applications, but it is not available yet.

**Comment by AidenY69** [comment]
> It is unfortunate that it is a fundamental thing in applications, but it is not available yet.

Agreed. logical OR queries and bulk processing is what really stumps me. Not sure why they haven't been incorporated into the software, or at least feature roadmap.

**Comment by rohankm** [comment]
Can someone update on the progress for this feature... its very basic and important to have logical conditions for queries

**Comment by Megamannen** [comment]
Haha, fairly surprised that this doesn't exist yet, feels like a v1.0 feature 

I want to search data with `Query.search` on multiple fields (filter stuff)
Pretty common use case, riiiight?

**Comment by AidenY69** [comment]
Any update on this yet? @stnguyen90 @eldadfux

**Comment by rohankm** [comment]
any updates?

**Comment by Edijae** [comment]
waiting for updates on this.....

**Comment by rohankm** [comment]
I feel appwrite is not production ready and this basic feature is not implemented since 2years

**Comment by AidenY69** [comment]
> I feel appwrite is not production ready and this basic feature is not implemented since 2years

I somewhat agree but not for the reason you suggest. This is a critical feature, no doubt. But I think that AppWrite hasn't implemented this due to a real reason. The reason AppWrite is not production-ready is because they had over two years to tell us why they haven't implemented it, and they still haven't. I imagine there is some major complexity in implementing this, or something else, but they need to be more upfront with their reasoning and progress. The feature hasn't even officially been assigned to anyone so no idea if they're even working on it. That's how much they're lacking in updates. They said it was on the roadmap two years, ago, but that roadmap isn't publicly available, and we were never given any vague timelines. 

If this is a matter of lack of funds to dedicate an employee to build this feature out, I'm willing to pay to get this feature added, or start a GoFundMe...no joke.


cc: @eldadfux @stnguyen90

**Comment by Aysnine** [comment]
I am looking for information about the availability of `Query.or(...)` functions. I found a mention of it in the documentation here: 

https://github.com/appwrite/website/blob/3d5245a612faccdc36809921002e1b9957532fe7/src/routes/docs/products/databases/queries/%2Bpage.markdoc#L18

However, I have not been able to find any query implementation in the SDK.

**Comment by AidenY69** [comment]
Glad to see this implemented! 

https://appwrite.io/blog/post/introducing-new-database-operators

**Comment by stnguyen90** [comment]
Related https://github.com/utopia-php/database/pull/350
