### ISSUE TITLE
🚀 Feature: Disable public registration 

### ISSUE THREAD

**Issue by Swinkid** [appwrite/appwrite#2744]
### 🔖 Feature description

You should add a toggle or server sdk endpoint to disable public user registration. 

### 🎤 Pitch

I want to be able to disable user registration so that I am able to register users manually / via server SDK since for use cases that are private apps. 

For example, a rewards portal for a company that only certain staff can access.

instead, users can either be manually registered via the console or via the server SDK (I.e in a cloud function)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
You can already disable any auth method you'd like from the Appwrite console. This feature was designed for a use-case like yours.
![image](https://user-images.githubusercontent.com/1297371/152622722-d920b2bf-29da-4279-be79-703720843886.png)

**Comment by Swinkid** [comment]
> You can already disable any auth method you'd like from the Appwrite console. This feature was designed for a use-case like yours.
> 
> ![image](https://user-images.githubusercontent.com/1297371/152622722-d920b2bf-29da-4279-be79-703720843886.png)
> 
> 

I'm guessing this is unaffected by a server register, but would work for a client login?

**Comment by eldadfux** [comment]
Exactly.

**Comment by Swinkid** [comment]
> Exactly.

I Just tried this out and I get the error "Email / Password authentication is disabled for this project" 

For context,  I still want users to be able to login with an email or password, just not register. Technically someone could just register an account via post requests, even if I don't have a register form on my client?

**Comment by Mabenan** [comment]
You could set the max allowed users setting to the user amount you currently have

**Comment by simonjcarr** [comment]
Don't understand why appwrite can't just add a simple button "Disable New Registrations". All these options to being discussed to dance around a serious issue. Security is important to some people and organisations.
