### ISSUE TITLE
🐛 Bug Report: net::ERR_CONTENT_LENGTH_MISMATCH 200(OK)

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2745]
### 👟 Reproduction steps

- get back to your instance's console after "a while" (a day or two?)
- try to login

### 👍 Expected behavior

- enable to login sucessfully
- I need to docker-compose down and up or *sometimes* just waiting a little more  and retrying makes it work (ie I am seeing the login form) ... :(
(I know ... this is not very precise ..  Please let me know where I could gather logs/debug info to try to track down what is going on)

### 👎 Actual Behavior

- the console shows the loading spinner
- ERR_CONTENT_LENGTH_MISMATCH ,yielded by app-all.js, appears in the debug console
- cannot login

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Please share your `docker-compose logs appwrite` & `docker-compose exec appwrite doctor` output.

**Comment by superseby2** [comment]
Here you go :

🔴 Not using a unique secret key for encryption
🟢 App environment is set for production
🟢 Abuse protection is enabled
🟢 Console access limits are enabled
🔴 HTTPS force option is disabled
🔴 Logging adapter is disabled

Checking connectivity...
Database............connected 👍
Queue...............connected 👍
Cache...............connected 👍
SMTP.............disconnected 👎
StatsD..............connected 👍
InfluxDB............connected 👍

Checking volumes...
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

Checking disk space usage...
🟢 Uploads Volume has 54.73GB free space (78.08% used)
🟢 Cache Volume has 54.73GB free space (78.08% used)
🟢 Config Volume has 54.73GB free space (78.08% used)
🟢 Certs Volume has 54.73GB free space (78.08% used)

[debug.txt](https://github.com/appwrite/appwrite/files/8004216/debug.txt)

It happened again today. Nothing spectacular in the logs while it was happening (a part from the UtopiaException but they happens all the time)

![debug](https://user-images.githubusercontent.com/32198925/152556769-eb4355e3-69e8-44b6-be49-ffdc79ec9b7e.png)

Today it took couple of minutes then it passed the spinning screen on its own.

One thing to note as well. I see websocket errors in the debugger.

app-all.js?v=201.0.12.1:10 WebSocket connection to 'wss://xx.xx.com/v1/realtime?project=console&channels%5B%5D=project&channels%5B%5D=console' failed: Error during WebSocket handshake: Unexpected response code: 404
createSocket @ app-all.js?v=201.0.12.1:10
(anonymous) @ app-all.js?v=201.0.12.1:11


Could it be related ? Appwrite is being proxied behind a nginx. My config follows the recommended one for websocket handling. https://nginx.org/en/docs/http/websocket.html

Thanks

**Comment by eldadfux** [comment]
I'm pretty sure it has to do with the proxy. Can you share your config file? Did you take a look at this post: https://dev.to/appwrite/learn-how-to-run-appwrite-with-your-own-custom-proxy-or-load-balancer-28k ?

**Comment by superseby2** [comment]
Thx for the link. I ll have a look and see what could be wrong in my set up.
Thx for your time.

**Comment by superseby2** [comment]
All is fine since I have been using a proper Nginx conf to handle WS. Closing.
