### ISSUE TITLE
🐛 Bug Report:  Cannot View uploaded Files/images 

### ISSUE THREAD

**Issue by 2002Bishwajeet** [appwrite/appwrite#2751]
### 👟 Reproduction steps

I have tested only in Flutter and through Admin Dashboard. So I can share the minimal reproducible code related to Flutter 

```dart
import 'dart:io';

import 'package:appwrite/appwrite.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Appwrite Demo',
      home: const MyHomePage(title: 'Appwrite Storage API Test'),
      debugShowCheckedModeBanner: false,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late AppwriteAPI appwrite;

  XFile? _file;

  void _pickImage() async {
    final file = await ImagePicker().pickImage(source: ImageSource.gallery);
    if (file == null) {
      return;
    }
    setState(() {
      _file = file;
    });
  }

  @override
  void initState() {
    appwrite = AppwriteAPI();
    appwrite.login();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            CircleAvatar(
              radius: 128,
              backgroundImage:
                  _file != null ? FileImage(File(_file!.path)) : null,
            ),
            MaterialButton(
              onPressed: () async {
                await appwrite.uploadImage(_file!.path, _file!.name, context);
                setState(() {
                  _file = null;
                });
              },
              child: Text("Upload Image"),
              height: 70,
              color: Colors.amber,
              textColor: Colors.white,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _pickImage,
        tooltip: 'Pick image',
        child: const Icon(Icons.image),
      ),
    );
  }
}

// APPWRITE CONFIG
class AppwriteAPI {
  Client client = Client();
  late Storage storage;
  late Account account;

  AppwriteAPI() {
    client
        .setEndpoint('http://192.168.1.26:5000/v1')
        .setProject('61eeba1677e1875b202a')
        .setSelfSigned(status: true);

    account = Account(client);
    storage = Storage(client);
  }

  Future<void> login() async {
    try {
      await account.createSession(
          email: 'test@gmail.com', password: '12345678');
    } catch (e) {
      print(e);
    }
  }

  Future<void> uploadImage(
      String filepath, String filename, BuildContext context) async {
    try {
      await storage.createFile(
          fileId: 'unique()',
          file: await MultipartFile.fromPath('file', filepath,
              filename: filename));

      await showDialog(
          context: context,
          builder: (BuildContext context) => AlertDialog(
                title: const Text('Appwrite Storage'),
                content: Text('File Uploaded Successfully'),
                actions: [
                  TextButton(
                      onPressed: () {
                        Navigator.of(context).pop();
                      },
                      child: const Text("Ok"))
                ],
              ));
    } catch (e) {
      print(e);
    }
  }
}
```

Uploading through Admin Dashboard and assigning Read permissions to one of the `user:id` will also give the same error. It does not  show the error for `role:all`

### 👍 Expected behavior

As an admin you should be able to see all the files and access them without any 404 error

### 👎 Actual Behavior

So if I actually  upload any image from client side. The client is able to access the image but accessing from the admin I get the following error:
```json
 {"message":"File not found","code":404,"version":"0.12.1"}
```
Even you can't see the tiny image preview when opening the file
![image](https://user-images.githubusercontent.com/62933155/152672742-d9ad0271-3ddd-4ac8-962b-ac2886a597dd.png)

What's more interesting is if I assign `role:all` permissions or if I open appwrite in incognito(without `role:all`), I am able to see those files perfectly.

@christyjacob4  and @Meldiron  suggested that it must be some cache issues. But even after clearing them, I faced the same issue. I tested it on multiple browsers and the issue was same.

I reported about this incident on Discord
https://discord.com/channels/564160730845151244/564161955963731980/934831681838415932

Then I don't know how but it started working automatically again (maybe restarting docker - I did once it didn't effect but after one more restart it started working so its a vague theory). 

I believed that it would have something to do with my system or something.

Then Today 6/02/2022 one more user reported the same [issue](https://discord.com/channels/564160730845151244/564160731327758347/939765095146332220) . It had the exact same issue as mine.

So creating the bug report for the same.

Also one more thing to notice is that we both have faced the same issue when uploading image from **flutter** and not able to access it from the dashboard. So this could be a possibility.

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Windows

### 🧱 Your Environment

N/A

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@2002Bishwajeet if this existed, this should be fixed with introduction of buckets and new permission model on bucket level vs file level. Leaving it open for now.

**Comment by christyjacob4** [comment]
@YouSour can you try opening this on Incognito ? We've had these issues in the past and all of them turned out to be cache issues.. 
So check it out on Incognito and let us know 👍

**Comment by YouSour** [comment]
@christyjacob4 solved by add extension  jpeg when i upload my file type jpeg

**Comment by YouSour** [comment]
@christyjacob4 it can be a bug or app-write not support type file jpeg, i'm not sure 🤔

**Comment by 2002Bishwajeet** [comment]
Should we close this issue now. I am not facing this in 0.13.4 anymore. Haven't tried yet in 0.14.x

**Comment by YouSour** [comment]
@2002Bishwajeet no problem for me 😄

**Comment by 2002Bishwajeet** [comment]
Closing as users haven't complained about this since the 1.0.0+ release
