### ISSUE TITLE
🐛 Bug Report: Float (doubles) in UI only allows 2 decimal

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2764]
### 👟 Reproduction steps

1. Create float attribute
2. Go into 'New document' UI
3. Try to create document with value with more than 2 decimal places

The same applies to updating an existing document.

### 👍 Expected behavior

No error, create/update document successfully. There could be some limit, but not 2 decimal places.

### 👎 Actual Behavior

Client-side form validation fails:

![image](https://user-images.githubusercontent.com/19310830/153156849-a475c624-0423-47ea-ab51-26cc3285de7f.png)

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by s3ppo** [comment]
one additional info:
when i add a value with 2 digits.. they are gone after the save to db

and the created float is shown as double in the attributes
![image](https://user-images.githubusercontent.com/17125438/156405082-46a683ee-b33a-4a55-84f2-9bdee2365aa7.png)
