### ISSUE TITLE
🐛 Bug Report: Searching for user in user list using the console takes ages

### ISSUE THREAD

**Issue by saibotma** [appwrite/appwrite#2765]
### 👟 Reproduction steps

- Have many users in appwrite (> 70000)
- Search for one by id in appwrite console

### 👍 Expected behavior

Should return result quickly.

### 👎 Actual Behavior

Takes multiple seconds to load, and does not even display a loading animation.

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Running on custom MySQL database.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
There were many database improvements in 0.12.X. Have you had a chance to try this in the latest 0.12 (0.12.4)?

**Comment by TorstenDittmann** [comment]
This is fixed with 0.12.0 - a fix for a 0.11.x without any schema changes is impossible ☹️
