### ISSUE TITLE
🐛 Bug Report: listDocuments with Query.greaterEqual/lesserEqual find no documents if queried attribute value is same as compared value.

### ISSUE THREAD

**Issue by sorinteican** [appwrite/appwrite#2766]
### 👟 Reproduction steps

Using the following query:
```
Future result = database.listDocuments(
    collectionId: '[COLLECTION_ID]',
    queries: [
        Query.greaterEqual('latitude', min_latitude),
        Query.lesserEqual('latitude', max_latitude),
        Query.greaterEqual('longitude', min_longitude),
        Query.lesserEqual('longitude', max_longitude)
    ]
);
```
Finds no document with attributes (latitude, longitude) that have the same values as min_latitude, max_latitude, min_longitude, or max_longitude.

In order to fix the issue I had to increment/decrement min and max values with 0.0001. After, the ```listDocuments``` method finds the documents that reside on the "border" location.

### 👍 Expected behavior

the ```listDocuments``` with Query.lesserEqual | Query.greaterEqual should return documents with attribute values same as queried value (the Equals part in the logic of the query method).

### 👎 Actual Behavior

Finds no document with attributes (latitude, longitude) that have the same values as min_latitude, max_latitude, min_longitude, or max_longitude.

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@sorinteican Thank you for reporting the issue. We will look into it and provide update soon.

**Comment by anandsubbu007** [comment]
search and equal query is not working

how to index attribute for search and equal query?

**Comment by TorstenDittmann** [comment]
@anandsubbu007 This issue is caused due to float precision, we are currently looking into possible solutions 👍🏻

**Comment by stnguyen90** [comment]
Any update on this? I think I just ran across this. I have a document where `f` is `13.13`:

```
{
    "defaultTest": 0,
    "f": 13.13,
    "$read": [],
    "$write": [],
    "$id": "629a34764b268f911dc1",
    "$collection": "float"
}
```

Queries in the db result in:

```
MariaDB [appwrite]> select * from _delete_collection_3 where f = 13.13;
Empty set (0.001 sec)

MariaDB [appwrite]> select * from _delete_collection_3 where f >= 13.13;
+-----+----------------------+-------------+-------+
| _id | _uid                 | defaultTest | f     |
+-----+----------------------+-------------+-------+
|   4 | 629a34764b268f911dc1 |           0 | 13.13 |
+-----+----------------------+-------------+-------+
1 row in set (0.001 sec)

MariaDB [appwrite]> select * from _delete_collection_3 where f <= 13.13;
+-----+----------------------+-------------+------+
| _id | _uid                 | defaultTest | f    |
+-----+----------------------+-------------+------+
|   5 | 629a360141aea5ae10dd |           0 |    0 |
+-----+----------------------+-------------+------+
1 row in set (0.001 sec)
```

**Comment by stnguyen90** [comment]
@TorstenDittmann, can `DOUBLE PRECISION` be used instead of `FLOAT` for the column type? That seems to work out better:

```
MariaDB [appwrite]> describe _delete_collection_3;
+-------------+------------------+------+-----+---------+----------------+
| Field       | Type             | Null | Key | Default | Extra          |
+-------------+------------------+------+-----+---------+----------------+
| _id         | int(11) unsigned | NO   | PRI | NULL    | auto_increment |
| _uid        | char(255)        | NO   | UNI | NULL    |                |
| defaultTest | bigint(20)       | YES  | MUL | NULL    |                |
| f           | double           | YES  | MUL | NULL    |                |
+-------------+------------------+------+-----+---------+----------------+
4 rows in set (0.002 sec)

MariaDB [appwrite]> select * from _delete_collection_3 where f <= 13.13;
+-----+----------------------+-------------+-------+
| _id | _uid                 | defaultTest | f     |
+-----+----------------------+-------------+-------+
|   5 | 629a360141aea5ae10dd |           0 |     0 |
|   4 | 629a34764b268f911dc1 |           0 | 13.13 |
+-----+----------------------+-------------+-------+
2 rows in set (0.001 sec)

MariaDB [appwrite]> select * from _delete_collection_3 where f = 13.13;
+-----+----------------------+-------------+-------+
| _id | _uid                 | defaultTest | f     |
+-----+----------------------+-------------+-------+
|   4 | 629a34764b268f911dc1 |           0 | 13.13 |
+-----+----------------------+-------------+-------+
1 row in set (0.001 sec)

MariaDB [appwrite]> select * from _delete_collection_3 where f >= 13.13;
+-----+----------------------+-------------+-------+
| _id | _uid                 | defaultTest | f     |
+-----+----------------------+-------------+-------+
|   4 | 629a34764b268f911dc1 |           0 | 13.13 |
+-----+----------------------+-------------+-------+
1 row in set (0.001 sec)
```

Perhaps it works better because [this](https://mariadb.com/kb/en/float/):

> Using FLOAT might give you some unexpected problems because all calculations in MariaDB are done with double precision. See [Floating Point Accuracy](https://mariadb.com/kb/en/floating-point-accuracy/).

**Comment by TorstenDittmann** [comment]
Yeah we have a general problem with float precision right now which is hard to explain and predict.

We have to reconsider what data type we have to use internally 🤔

**Comment by TorstenDittmann** [comment]
Especially considering that we want to support geo location at some point.
