### ISSUE TITLE
🐛 Bug Report:  add required bool attribute to document fails 

### ISSUE THREAD

**Issue by ivenprillwitz** [appwrite/appwrite#2767]
### 👟 Reproduction steps

1. Create Collection
2. Create Attribute 'myBoolean', bool, required

Failed

### 👍 Expected behavior

Should not fail

### 👎 Actual Behavior

Fail

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

local docker instance on my mac

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ivenprillwitz** [comment]
Possible dublicate?

#2677

**Comment by lost-RD** [comment]
+1 for this, it has never worked for me either

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻
