### ISSUE TITLE
bug: when uploaded image is missing the extension, now showing the preview and thumbnail

### ISSUE THREAD

**Issue by YahalomsGuy** [appwrite/appwrite#2770]
### 👟 Reproduction steps

Following discussion with @eldadfux 
Upload an image file to the server without the file extension.

go to the console, 
The thumbnail and the preview of the image are not shown, although it recognizes the file and "image" 
press the "New Window" link, it opens.

try to "storage.getFilePreview" through the API in the front end , does not render the image

### 👍 Expected behavior

since the console recognizes the file as image although it does not have extension, should be able to render and show the preview and the thumbnail

### 👎 Actual Behavior

Does not show.

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This was fixed, merged and will be released in Appwrite 0.14
