### ISSUE TITLE
🚀 Feature: Support GO Lang for Appwrite Functions

### ISSUE THREAD

**Issue by AdamRussak** [appwrite/appwrite#2784]
### 🔖 Feature description

Add support go lang 1.16 <

### 🎤 Pitch

Go lang is a big language in Cloud/  SaaS world.
supporting this language should be pretty obvious :)
 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by maltegrosse** [comment]
Go lang support would be great!

**Comment by stnguyen90** [comment]
We have the [go runtime](https://github.com/open-runtimes/open-runtimes/tree/main/runtimes/go-1.19) ready, but it still needs to be added to Appwrite.

**Comment by nimit2801** [comment]
> We have the [go runtime](https://github.com/open-runtimes/open-runtimes/tree/main/runtimes/go-1.19) ready, but it still needs to be added to Appwrite.

Hey @stnguyen90 is there a way we can use it without it being enabled with Appwrite? Because I saw appwrite already has support for GoLang in its [open runtime](https://github.com/open-runtimes/open-runtimes/tree/main/runtimes/go-1.19).

**Comment by CORCTON** [comment]
Any updates?

**Comment by byawitz** [comment]
As of version `1.6`, Appwrite supports `Go` functions.

Check the official [announcement ](https://appwrite.io/blog/post/announcing-go-support)
