### ISSUE TITLE
🐛 Bug Report: updateMembershipRoles

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#2794]
### 👟 Reproduction steps

i have a team: ABC
i have 2 users: user1(owner) and user2(member)

if user1 uses method updateMembershipRoles and set user2 to owner, on the first look it seems to work.. in the appwrite console user2 is now also an owner of the team

BUT

if user2 trys now to write a document with team:ABC/owner an exception occurs with the message of possible roles.. but ABC/owner is not within

sidenote:
if i set the role by admin SDK its working fine

### 👍 Expected behavior

the new assigned owner of the team should be able to write documents with team:ABC/owner

### 👎 Actual Behavior

the new assigned owner(with updateMembershipRoles) of the team is not allowed to write documents with team:ABC/owner

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
This got fixed with 0.12.3 👏🏻
