### ISSUE TITLE
🐛 Bug Report: Data loss during migration from 0.11.x to 0.12.x

### ISSUE THREAD

**Issue by JakeAi** [appwrite/appwrite#2800]
### 👟 Reproduction steps

When I migrate from 0.11.x to 0.12.x, some documents that include HTML end up missing data. This could be an issue in future migrations.

https://imgur.com/uHjqgvY

### 👍 Expected behavior

Data should be migrated

### 👎 Actual Behavior

Some documents lost data

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
What is the rule/attribute type for Content?

**Comment by JakeAi** [comment]
The rule on 0.11 is
```JSON
        {
            "$id": "60d52173ccecc",
            "$collection": "rules",
            "type": "text",
            "key": "content",
            "label": "Content",
            "default": "",
            "array": false,
            "required": false,
            "list": []
        },
```

The migrated attribute ends up as 
```JSON
        {
            "key": "content",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 65535,
            "default": ""
        },

```

**Comment by TorstenDittmann** [comment]
Is it possible that the previous data exceeded `65535` chars?

**Comment by JakeAi** [comment]
> Is it possible that the previous data exceeded `65535` chars?

For example. Prior to migration, the console says `310 words and 2819 chars`. So it is lower than 65535

**Comment by JakeAi** [comment]
> Any logs during migration?
> 
> Btw, with this migration all your 0.11 data still exists. So there is an easy way to recover by just using your old docker-compose file 👍🏻

I have a Production 0.11 instance, a dev 0.11 instance and a dev 0.12 instance. So I'm not losing anything technically, but I have to run a separate script to fix the data loss using an older instance.

https://pastebin.com/DHmiF2T7

**Comment by JakeAi** [comment]
> Let me guess, `60cd3c5478fe9` is the collection with data loss right?

No, it is `60f985e5cde85`

**Comment by JakeAi** [comment]
@TorstenDittmann This issue might be able to be closed as I found my order of operations is may have what caused it. 

What I was doing was restoring the 0.11.x DB over the 0.12.2 DB, then running `docker-compose exec appwrite migrate` while running the 0.12 compose file (the script I was running is at the bottom).

If I completely revert back to 0.11.x env and compose file, and do the following command over 0.11. I do not get data loss. I thought that if I restore 0.11 DB and run the migrate command, that it would work just fine...

```SH
sudo docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.12.2
```

```SH
sudo docker-compose down
sudo docker volume prune -f
sudo docker-compose create
sudo docker run --rm --volumes-from "$(sudo docker-compose ps -q appwrite)" -v $PWD/backup:/restore ubuntu bash -c "cd /storage/functions && tar xvf /restore/functions.tar --strip 1"
sudo docker run --rm --volumes-from "$(sudo docker-compose ps -q appwrite)" -v $PWD/backup:/restore ubuntu bash -c "cd /storage/uploads && tar xvf /restore/uploads.tar --strip 1"
sudo docker-compose up -d mariadb
sleep 10
sudo docker-compose exec -T mariadb sh -c 'exec mysql -uroot -p"$MYSQL_ROOT_PASSWORD"' < ./backup/dump.sql
sudo docker-compose up -d
sudo docker-compose exec appwrite migrate
```
