### ISSUE TITLE
🚀 Feature: Support of SVG files view with file storage

### ISSUE THREAD

**Issue by kamal951** [appwrite/appwrite#2811]
### 🔖 Feature description

You should add the possibility to be able to see SVG files when we do the "view file" request. 

For now, it works great for other types like png or jpeg but when we try to see an svg, we have plain text.

### 🎤 Pitch

This feature should be implemented because SVG files are generally lighter than other types so we could store more images and the perfomances would be better. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by MarvinJWendt** [comment]
If this gets implemented, it should be made sure that there aren't any XSS vulnerabilities, since user uploaded SVGs could potentially execute any JavaScript and steal the appwrite session token, which would grant access to the admin interface.

[Reference](https://research.securitum.com/do-you-allow-to-load-svg-files-you-have-xss/)

And yes, this works with modern browsers too 😉

**Comment by SkypLabs** [comment]
> If this gets implemented, it should be made sure that there aren't any XSS vulnerabilities, since user uploaded SVGs could potentially execute any JavaScript and steal the appwrite session token, which would grant access to the admin interface.

Precisely. I actually stumbled upon this issue while doing research on the way AppWrite handles uploaded files' content type in responses, in particular about SVG files to avoid potential XSS problems.

One way to deal with it is to use a different hostname for accessing uploaded files. This way, the AppWrite's session cookie would not be accessible via JavaScript even if an XSS is triggered.

**Comment by eldadfux** [comment]
As of now, we do not allow this for the above mentioned security concerns.
