### ISSUE TITLE
🚀 Feature: ACL (Access Control List) Prevent team members from being able to see other members

### ISSUE THREAD

**Issue by JakeAi** [appwrite/appwrite#2817]
### 🔖 Feature description

The teams and roles feature is great but could be even better. By using single page applications or even flutter apps, you can make a call to `getMemberships()` and view the permissions to the app. For example. You could have a team called `Mobile App`  and add the role `Debug` to certain members and they would get debug permissions in the app.

However, `getMemberships()` gets all the memberships. With a simple toggle, you could only return memberships for the current user, thus effectively creating an ACL system. Certain teams could be labeled `ACL` and others not.

#2789 Bug Report: Can no longer search through memberships

### 🎤 Pitch

See above

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Related discussion: https://github.com/appwrite/appwrite/discussions/2317

**Comment by stnguyen90** [comment]
In 1.4, we added something that might be perfect for this use-case: [User Labels](https://appwrite.io/docs/authentication-management#labels). With user labels, you can grant access without using a team that may expose emails. Would this solve the problem?
