### ISSUE TITLE
Bug : Query an Array attribute with an array of values does not work

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2838]
### 👟 Reproduction steps

I am trying to query a Collection where one attribute is an Array of string

Trying this syntax fails to retrieve anything (and it feels normal)
```
database.list_documents('collection',                                                                       
       [                                                                                                               
           Query.equal("array_attribute, ["value1","value2"])                             
       ]                                                                                                               
))
```
Trying this syntax fails also while it feels like it could work ;)
```
database.list_documents('collection',                                                                       
       [                                                                                                               
           Query.equal("array_attribute, '["value1","value2"]')                             
       ]                                                                                                               
))

```
What I am trying to do is basically an "Array IN Array" comparison. Going the "equal" way seems hackish but I thought as the attribute is stored in a String it might work (and could be a work-around until a proprer "in" or "contains" operator exists. ?)

My only other option to make this work is use a function to "explode" the values contained  in array_attribute  in a new collection and then I can do a OR comparaison. It works but is not as straighforward + it generates a big collection.

### 👍 Expected behavior

some content is being retrieved

### 👎 Actual Behavior

Nothing is retrieved.

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by superseby2** [comment]
Just tried using a fulltext index and it *seems* to work. Would it be the route to follow ?

**Comment by superseby2** [comment]
Fulltext option works great until I want to use multiple attributes in the fulltext index. Creating the inndex works in the console (no error) but when querying using this index an error is raised

```
    raise AppwriteException(response.text, response.status_code)
appwrite.exception.AppwriteException: {"message":"Error: Can't find FULLTEXT index matching the column list"

```

**Comment by superseby2** [comment]
Creating one single fulltext index for each attribute works though and I can query using a Search Query for each attributes defined in the index.

**Comment by anandsubbu007** [comment]
how to implement search for matching document with array attribute which match and of the data in the list

**Comment by stnguyen90** [comment]
@meepeek, @superseby2, for this type of functionality, are you expecting for documents to return if they have any least one of the values in the query? For example, let's say the document has `["flutter", "dart"]` for attribute `tags`. `Query.contains("tags", ["flutter", "react"])` would return the document because `flutter` is in the `tags`. Is this the functionality you need?

**Comment by meepeek** [comment]
@stnguyen90 I think making the single param called exact match make more sense as we can overloaded the function for partial matching. I propose sample use cases and syntax representation as follow.

1. Partial matching (contains 'a' or 'b') - use case, tag filter where user may uncheck unwanted tags
```
[ Query.contains('tags', ['a'], ['b']) ]
```
2. All matching (have both 'a' and 'b') - site admin query for counts or batch operation
```
[ Query.contains('tags', ['a', 'b']) ]
```
3. All matching strictly (have both 'a' and 'b' and no others) - also site admin query
```
[ Query.arrayLength('tags', 2), Query.contains('tags', ['a', 'b']) ]
```
4. Invert operation - if there are fewer unwanted tags, it would be more efficient to do the invert
```
[ Query.notContains('tags', ['a', 'b']) ]
```

Also, tag use case will need distinct query so we will know all available tag list before the query. I didn't see query distinct in the doc but it can be temporary fixed by having a unique list updated as each record created or updated. However, I think distinct query should be available for every attribute types.

**Comment by netapy** [comment]
Are there any news on this issue ? This would be very useful

**Comment by Ota-Prokopec** [comment]
I dont know if it is helpful, but i found out that you can use Query.search to looking for items in array.

**Comment by moydz** [comment]
yo pude obtener el array con Query.greaterThan me funciono bien

Future<List<anime>> listbygenero(String generoc) async {
    List<generos> _generox = [];
    generos gen=generos(genero: generoc);
    _generox.add(gen);
    var result =
    await AppWriteApi.database.listDocuments(
        databaseId: _databaseId,
        collectionId: _collectionId,
        queries: [
          **Query.greaterThan("genero", _generox)**
        ]
    );

**Comment by feschaffa** [comment]
Any plans on implementing this? Using the search method for now, but feels a bit hacky. Thanks!

**Comment by 0xDjole** [comment]
This is a useless product.

**Comment by johnschatner** [comment]
Would also love this feature! Search is a hit or miss with foreign characters.

**Comment by Edijae** [comment]
Query.contains not available in node-appwrite 11.1.0 @stnguyen90

**Comment by stnguyen90** [comment]
Related:

* https://github.com/utopia-php/database/pull/335
* https://github.com/utopia-php/database/pull/377

**Comment by SimonMaluleka** [comment]
@oussamachah2020 here's an example to push into or add values to an array type attribute
```
export const likePost = async(userId, postId)=>{
    try {
        const currentLikes = await databases.listDocuments(
            databaseId,
            videosCollectionId,
            [Query.equal('$id', postId)]
        )

        if(!currentLikes.documents[0].likedBy.includes(userId)){
            const updatedLikes = [...currentLikes.documents[0].likedBy]
            updatedLikes.push(userId)
            const documentId = currentLikes.documents[0].$id
            const updateData = {            
                "likedBy": updatedLikes
            };
            const response = await databases.updateDocument(
                databaseId,
                videosCollectionId,
                documentId,
                updateData
            )
        }      

    } catch (error) {
        throw new Error(error)
    }
}
```

**Comment by SimonMaluleka** [comment]
@superseby2 I had a similar  requirement and opted to retrieve the documents first and then filtered the results in my application code.

**Comment by SimonMaluleka** [comment]
For some reason this code also worked for querying the array attribute and suddenly stopped working

```
export const getlikedPosts = async(userId)=>{
    try {
        const posts = await databases.listDocuments(
            databaseId,
            videosCollectionId,
            [Query.search('likedBy', `${userId}"`)]
        )
    
        return posts.documents
    } catch (error) {
        throw new Error(error)
    }
}
```
