### ISSUE TITLE
🚀 Feature: An easier way to just update document permissions

### ISSUE THREAD

**Issue by rdmchr** [appwrite/appwrite#2850]
### 🔖 Feature description

Currently, to update the permission of a document, you also have to update some kind of data, or at least pass some kind of data.
This does not work:
```TS
await database.updateDocument(listCollection, list, {}, [`user:${user.$id}`]);
```
So to update permissions I have to pass some data, even if the data is the same as the current one:
```TS
await database.updateDocument(listCollection, list, {name: "test"}, [`user:${user.$id}`]);
```

### 🎤 Pitch

It would be simple to remove the requirement of data, by removing [this check](https://github.com/appwrite/appwrite/blob/619ff84f016c72d43da19fa1a9622188ac79ddd1/app/controllers/api/database.php#L1995) or you could check if some permissions are passed and then do the check. 
This would make it much more simple to update permissions.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by gepd** [comment]
Today I'm facing this, would be good to have a solution for this.

Would be acceptable for you remove the check? or maybe only throw the error when no permission are updated, what do you think? @eldadfux 

I'll you accept a PR?
