### ISSUE TITLE
Appwrite compliance

### ISSUE THREAD

**Issue by novidtech** [appwrite/appwrite#286]
Hi, I was told to lodge a ticket to find out about appwrites compliance and privacy policies as I work with high enterprise corporations that only allow data to be hosted in sure, regular code review etc.... In other words, very strict management of everything we use. I want to use appwrite but would it suite these types of Customers?

I look forward to hearing from you soon

Kind regards,
Rohan

**Comment by eldadfux** [comment]
Hey @novidtech, I would love to follow up on this if you could provide more information about your clients' specific requests and needs. You can email me at team@appwrite.io, and I'll get back to you with more details.
