### ISSUE TITLE
🐛 Bug Report: Can not use "Query" option at ListDocument to search database at Appwrite CLI

### ISSUE THREAD

**Issue by DuaneDuan** [appwrite/appwrite#2875]
### 👟 Reproduction steps

``` bash
[root@localhost ~]# appwrite version
CLI Version : 0.13.0
Server Version : 0.12.0 

[root@localhost ~]# appwrite database listDocuments collectionId=621d7bf5b9fac7a86ff2 queries=[Query.equal('Email','t@t.com')]
-bash: syntax error near unexpected token `('

```

### 👍 Expected behavior

Can use "queries" option to search database.

### 👎 Actual Behavior

Cant not execute CLI command when use queries option.

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 🧱 Your Environment

CentOS 8

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I believe that’s that CLI you’re using is a little buggy and will soon be replaced with a rewritten CLI. I would suggest checking out the [repo](https://github.com/appwrite/sdk-for-cli) or waiting for the official release.

**Comment by christyjacob4** [comment]
@DuaneDuan  , we just released a new version of the Appwrite CLI. 
Please check it out and let us know if this is still an issue 
https://github.com/appwrite/sdk-for-cli

**Comment by DuaneDuan** [comment]
Same issue, I did not read any sample command for ”queries“ option with database list documents, please advise.
 
https://github.com/appwrite/sdk-for-cli/blob/master/docs/examples/database/list-documents.md 

> @DuaneDuan , we just released a new version of the Appwrite CLI. Please check it out and let us know if this is still an issue https://github.com/appwrite/sdk-for-cli

**Comment by stnguyen90** [comment]
Looking at the [source](https://github.com/appwrite/sdk-for-cli/blob/master/lib/commands/database.js#L1099-L1110) and [README](https://github.com/appwrite/sdk-for-cli#usage), how about:

```bash
appwrite database listDocuments --collectionId 621d7bf5b9fac7a86ff2 --queries "Email.equal('t@t.com')"
```

**Comment by DuaneDuan** [comment]
Thanks @stnguyen90, the full usage for `queries` option: 
```
appwrite database listDocuments --collectionId=621d7bf5b9fac7a86ff2 --queries="username.equal('abc')";"desc.equal('def')"
```
