### ISSUE TITLE
🐛 Bug Report: After upgrade to 0.13.0 ->   Failed to save data for project 61d9932a0eda26b103b0 and metric executions: SQLSTATE[42S02]: Base table or view not found: 

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2888]
### 👟 Reproduction steps

- docker-compose down
- change 0.12.4 to 0.13.0 in docker-compose.yml
- docker-compose up

### 👍 Expected behavior

- app is up and running

### 👎 Actual Behavior

- App does not start . Trying to go to directly to my project  
"message":"Project not found","code":404,"type":"project_not_found","version":"0.13.0","file":"\/usr\/src\/code\/app\/controllers\/general.php","line":114,"trace":[{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":560,"function":"{closure}","args":[{},{},{},{"$id":"console","name":"Appwrite","$collection":"projects","description":"Appwrite core engine","logo":"","teamId":-1,"webhooks":[],"keys":[],"platforms":[{"$collection":"platforms","name":"Localhost","type":"web","hostname":"localhost"},{"$collection":"platforms","name":"Current Host","type":"web","hostname":"be.beta.thumbup.tech"}],"legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","auths":{"limit":1},"authWhitelistEmails":[],"authWhitelistIPs":[]},{"$collection":"projects"},{},{"$id":"","$collection":"users"},{"default":"en"},["localhost","be.beta.thumbup.tech"]]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":694,"function":"execute","class":"Utopia\\App","type":"->","args":[{},{}]},{"file":"\/usr\/src\/code\/app\/http.php","line":249,"function":"run","class":"Utopia\\App","type":"->","args":[{},{}]}]}
`
and going to /console, I am asked to signup.

In the logs 

"message":"Project not found","code":404,"type":"project_not_found","version":"0.13.0","file":"\/usr\/src\/code\/app\/controllers\/general.php","line":114,"trace":[{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":560,"function":"{closure}","args":[{},{},{},{"$id":"console","name":"Appwrite","$collection":"projects","description":"Appwrite core engine","logo":"","teamId":-1,"webhooks":[],"keys":[],"platforms":[{"$collection":"platforms","name":"Localhost","type":"web","hostname":"localhost"},{"$collection":"platforms","name":"Current Host","type":"web","hostname":"be.beta.thumbup.tech"}],"legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","auths":{"limit":1},"authWhitelistEmails":[],"authWhitelistIPs":[]},{"$collection":"projects"},{},{"$id":"","$collection":"users"},{"default":"en"},["localhost","be.beta.thumbup.tech"]]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":694,"function":"execute","class":"Utopia\\App","type":"->","args":[{},{}]},{"file":"\/usr\/src\/code\/app\/http.php","line":249,"function":"run","class":"Utopia\\App","type":"->","args":[{},{}]}]}
`

- Errors are as follow 
`

appwrite-usage                  | Failed to save data for project 61d9932a0eda26b103b0 and metric executions: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._61d9932a0eda26b103b0__metadata' doesn't exist
appwrite-usage                  | #0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
appwrite-usage                  | #1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(372): Appwrite\Extend\PDOStatement->execute()
appwrite-usage                  | #2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(772): Utopia\Database\Adapter\MariaDB->getDocument('_metadata', 'stats')
appwrite-usage                  | #3 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(379): Utopia\Database\Database->getDocument(Object(Utopia\Database\Document), 'stats')
appwrite-usage                  | #4 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(756): Utopia\Database\Database->getCollection('stats')
appwrite-usage                  | #5 /usr/src/code/app/tasks/usage.php(344): Utopia\Database\Database->getDocument('stats', '6cf06f9338013e7...')
appwrite-usage                  | #6 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(203): {closure}()
appwrite-usage                  | #7 /usr/src/code/app/tasks/usage.php(771): Utopia\CLI\Console::loop(Object(Closure), 30)
appwrite-usage                  | #8 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()
appwrite-usage                  | #9 /usr/src/code/app/cli.php(28): Utopia\CLI\CLI->run()
appwrite-usage                  | #10 {main}
appwrite-usage                  | [PDO] MySQL connection restarted

`

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by superseby2** [comment]
I hadn't run the migration procedure .. my mistake !

**Comment by dokind** [comment]
I have a same issue but I did that migration process
