### ISSUE TITLE
🐛 Bug Report: Invalid Origin for iOS Flutter App

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#2898]
### 👟 Reproduction steps

1. Create a Flutter app using the [flutter sdk](https://github.com/appwrite/sdk-for-flutter)
2. Create an iOS build
3. Add a Platform via the Appwrite console
   1. Add Platform
   2. New Apple App
   3.  Under iOS, add a Name and the Bundle ID of your app
5. Run the iOS build

### 👍 Expected behavior

API calls made from the app should work because the app is an iOS app, even if it's made with Flutter.

### 👎 Actual Behavior

API calls result in Invalid Origin error

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This happens because the Platform type for an Apple iOS app is [`apple-ios`](https://github.com/appwrite/appwrite/blob/0.13.0/app/controllers/api/projects.php#L1005):

<img width="235" alt="image" src="https://user-images.githubusercontent.com/1477010/156797126-87d3aefe-ecd0-48ca-ba4b-8cb6946dfc82.png">

but when Appwrite validates the origin, [it doesn't use the platform](https://github.com/appwrite/appwrite/blob/0.13.x/src/Appwrite/Network/Validator/Origin.php#L76) because [`CLIENT_TYPE_IOS` is `ios`](https://github.com/appwrite/appwrite/blob/0.13.x/src/Appwrite/Network/Validator/Origin.php#L17) rather than `apple-ios`.

Surprisingly, this isn't a problem when building an iOS app using the [apple sdk](https://github.com/appwrite/sdk-for-apple). This is because the apple sdk doesn't send the origin header so no origin validation occurs. The [flutter](https://github.com/appwrite/sdk-for-flutter/blob/4.0.1/lib/src/client_io.dart#L138) and [android](https://github.com/appwrite/sdk-for-android/blob/0.4.0/library/src/main/java/io/appwrite/Client.kt#L84) sdks, however, do.

**Comment by AhmedHammad0900** [comment]
same for flutter android

**Comment by stnguyen90** [comment]
> same for flutter android 13.1

There is no mismatch for android client type so if you’re having an origin problem, it’s unrelated to this.

**Comment by AhmedHammad0900** [comment]
> > same for flutter android 13.1
> 
> There is no mismatch for android client type so if you’re having an origin problem, it’s unrelated to this.

Worked for me when back to 13.0 without changing anything .. don't know the reason

**Comment by TorstenDittmann** [comment]
We just released [0.13.2](https://github.com/appwrite/appwrite/releases/tag/0.13.2) where this got fixed by @stnguyen90 💪🏻
