### ISSUE TITLE
🐛 Bug Report: Installed latest Appwrite CLI, cannot login

### ISSUE THREAD

**Issue by locohost** [appwrite/appwrite#2899]
### 👟 Reproduction steps

I'm in my console
I enter: appwrite login
I enter my correct email and password

### 👍 Expected behavior

Something other than the red error to continue login process

### 👎 Actual Behavior

I see...

**x Error Not Found**

in red.

I've tried my member email/pass and I've tried the only user email/pass. I get same for both.

No I haven't forgotten my passwords :-)

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

No. I just installed Appwrite 0.13 then upgraded the Appwrite CLI to latest via the script.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by locohost** [comment]
I can still login to the web console fine.

**Comment by stnguyen90** [comment]
You should be logging in with your admin console email and password. 

Also, what did you put for your endpoint?

**Comment by s3ppo** [comment]
i had no issues with login

**Comment by Meldiron** [comment]
Your endpoint might be miss-configured. Please set your endpoint using following command:

```
appwrite client --selfSigned true --endpoint http://localhost/v1
```

You can omit selfSigned if it's not relevant to your instance. Make sure to replace the endpoint URL with yours.

After that, let's try `appwrite login` again and see if it works.

**Comment by locohost** [comment]
Ok, this works: changed above to...

appwrite client --selfSigned false --endpoint https://[my-domain-name.com]/v1

I can login to CLI after doing above
