### ISSUE TITLE
🐛 Bug Report: deleting a collection does not delete its attributes nor its indexes

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2902]
### 👟 Reproduction steps

- create a collection  with specific id and name
- add attributes / indexes
- delete collection
 re-create a collection with same id and name as the first creation
-

### 👍 Expected behavior

- the collection is brand new with no indexes and attributes

### 👎 Actual Behavior

- attributes & indexes are already there and from the previous creation

Note : Deleting the rows in _<projectid>_indexes  & _<projectid>_attributes for this collection allow to have a clean start when creating the new collection

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Version is 0.13.0 (not available in the list)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by superseby2** [comment]
Hello @TorstenDittmann Have you got any leads? I recently needed to remove some collections and this bug make that simple task painful ;)

**Comment by Towerful** [comment]
> Hello @TorstenDittmann Have you got any leads? I recently needed to remove some collections and this bug make that simple task painful ;)

I ran into this issue.  
I just wrote a node script that lists the attributes and indexes for the collection, deletes them with a 1s delay between each attribute and 1s delay between each index, then waits 5s and deletes the collection.  
Not sure if the delays are required, but I didn't want to deal with the potential of stuck attributes or things not being deleted.

**Comment by ameerfayiz** [comment]
> > Hello @TorstenDittmann Have you got any leads? I recently needed to remove some collections and this bug make that simple task painful ;)
> 
> I ran into this issue. I just wrote a node script that lists the attributes and indexes for the collection, deletes them with a 1s delay between each attribute and 1s delay between each index, then waits 5s and deletes the collection. Not sure if the delays are required, but I didn't want to deal with the potential of stuck attributes or things not being deleted.

I tried to delete the attributes from console. but deleting attribute was not working either for me, attribute successfully deleted snackbar was coming, but attribute was not getting deleted.

**Comment by CEOSiyris** [comment]
I haven't found a way to delete it either. Using console and CLI both didn't work for me. Restarting also didn't have an effect.

**Comment by superseby2** [comment]
The way I am doing it until there is a fix : 
- Using the console, I delete the collection then
- Login to MySql directly
- Location  [UUID]__indexes & [UUID]__attributes specific to your project (UUID being your project's unique ID)
- delete from  [UUID]__indexes where collectionId = [your collectionid ]
- delete from  [UUID]__attributes where collectionId = [your collectionid ]

**Comment by ameerfayiz** [comment]
> The way I am doing it until there is a fix :
> 
> * Using the console, I delete the collection then
> * Login to MySql directly
> * Location  [UUID]__indexes & [UUID]__attributes specific to your project (UUID being your project's unique ID)
> * delete from  [UUID]__indexes where collectionId = [your collectionid ]
> * delete from  [UUID]__attributes where collectionId = [your collectionid ]

in which database , the commands have to executed ?

**Comment by ameerfayiz** [comment]
> The way I am doing it until there is a fix :
> 
> * Using the console, I delete the collection then
> * Login to MySql directly
> * Location  [UUID]__indexes & [UUID]__attributes specific to your project (UUID being your project's unique ID)
> * delete from  [UUID]__indexes where collectionId = [your collectionid ]
> * delete from  [UUID]__attributes where collectionId = [your collectionid ]

thanks , it worked 👍 
but there was a little correction is appwrite is 0.13.2 
`delete from _[UUID]_indexes where collectionId = '[your collectionid]'`
`delete from _[UUID]_attributes where collectionId = '[your collectionid]'`

**Comment by ameerfayiz** [comment]
> > The way I am doing it until there is a fix :
> > 
> > * Using the console, I delete the collection then
> > * Login to MySql directly
> > * Location  [UUID]__indexes & [UUID]__attributes specific to your project (UUID being your project's unique ID)
> > * delete from  [UUID]__indexes where collectionId = [your collectionid ]
> > * delete from  [UUID]__attributes where collectionId = [your collectionid ]
> 
> thanks , it worked 👍 but there was a little correction in table name for appwrite is 0.13.2 `delete from _[UUID]_indexes where collectionId = '[your collectionid]'` `delete from _[UUID]_attributes where collectionId = '[your collectionid]'`

TEMPORARY FIX for attributes getting stuck

RUN:
docker exec -it appwrite-mariadb bash

IN BASH ,RUN:
mysql -u root -p
nb : for password, open .env file and use _APP_DB_ROOT_PASS

THEN, inside mariabc cli, run :
delete from _[uuid]_indexes where collectionId = '[collection id]';
delete from _[uuid]_attributes where collectionId = '[collection id]';

where [uuid] is project id and [collection id] is your collection id

**Comment by stnguyen90** [comment]
On 0.13.4, it seems like Appwrite doesn't find the attributes when trying to delete:

```
appwrite-worker-deletes  | [notice] Starting work on (Job{v1-deletes} | ID: 97c38b5050fb7b674c51cb5955763d81 | DeletesV1 | [{"projectId":"delete","type":"document","document":{"name":"Delete","dateCreated":1651512475,"dateUpdated":1651512475,"enabled":true,"permission":"collection","attributes":[{"key":"test","type":"string","status":"available","required":false,"array":false,"size":255,"default":null}],"indexes":[],"search":"delete Delete","$read":[],"$write":[],"$id":"delete","$internalId":"1","$collection":"collections"}}])
appwrite-worker-deletes  | [PDO] MySQL connection restarted
appwrite-worker-deletes  | Deleting chunk #1. Found 0 documents
appwrite-worker-deletes  | Deleted 0 document by group in 0.0025320053100586 seconds
appwrite-worker-deletes  | Deleting chunk #1. Found 0 documents
appwrite-worker-deletes  | Deleted 0 document by group in 0.0035481452941895 seconds
appwrite-worker-deletes  | Deleting chunk #1. Found 0 documents
appwrite-worker-deletes  | Deleted 0 document by group in 0.0034821033477783 seconds
```

I believe this is the query that is done to fetch the attributes that should be deleted:

```sql
SELECT
    table_main.*,
    (
        SELECT JSON_ARRAYAGG(DISTINCT _permission)
        FROM `appwrite`.`_delete_attributes_perms`
        WHERE
            _document = table_main._uid
            AND _type = 'read'
    ) as _read,
    (
        SELECT JSON_ARRAYAGG(DISTINCT _permission)
        FROM `appwrite`.`_delete_attributes_perms`
        WHERE
            _document = table_main._uid
            AND _type = 'write'
    ) as _write
FROM
    `appwrite`.`_delete_attributes` table_main
WHERE 1=1 AND (table_main.collectionId = 'delete') AND table_main._uid IN
    (
        SELECT * FROM
        (
            SELECT _document
            FROM `appwrite`.`_delete_attributes_perms`
            WHERE _permission IN ('role:all')
            AND _type = 'read'
        ) as subquery
    )
GROUP BY table_main._uid
ORDER BY table_main._id ASC
LIMIT 0, 50
```

but the subquery:

```sql
SELECT * FROM
(
    SELECT _document
    FROM `appwrite`.`_delete_attributes_perms`
    WHERE _permission IN ('role:all')
    AND _type = 'read'
) as subquery
```

makes the query return 0 results so no attributes are deleted. In my case, the `_delete_attributes_perms` is empty.

**Comment by stnguyen90** [comment]
FYI, my collection:

```json
{
    "$id": "float",
    "$read": [],
    "$write": [],
    "name": "Float",
    "enabled": true,
    "permission": "collection",
    "attributes": [
        {
            "key": "num",
            "type": "double",
            "status": "available",
            "required": false,
            "array": false,
            "min": -1.7976931348623157e+308,
            "max": 1.7976931348623157e+308,
            "default": null
        }
    ],
    "indexes": []
}
```

**Comment by TorstenDittmann** [comment]
> On 0.13.4, it seems like Appwrite doesn't find the attributes when trying to delete:
> 
> ```
> appwrite-worker-deletes  | [notice] Starting work on (Job{v1-deletes} | ID: 97c38b5050fb7b674c51cb5955763d81 | DeletesV1 | [{"projectId":"delete","type":"document","document":{"name":"Delete","dateCreated":1651512475,"dateUpdated":1651512475,"enabled":true,"permission":"collection","attributes":[{"key":"test","type":"string","status":"available","required":false,"array":false,"size":255,"default":null}],"indexes":[],"search":"delete Delete","$read":[],"$write":[],"$id":"delete","$internalId":"1","$collection":"collections"}}])
> appwrite-worker-deletes  | [PDO] MySQL connection restarted
> appwrite-worker-deletes  | Deleting chunk #1. Found 0 documents
> appwrite-worker-deletes  | Deleted 0 document by group in 0.0025320053100586 seconds
> appwrite-worker-deletes  | Deleting chunk #1. Found 0 documents
> appwrite-worker-deletes  | Deleted 0 document by group in 0.0035481452941895 seconds
> appwrite-worker-deletes  | Deleting chunk #1. Found 0 documents
> appwrite-worker-deletes  | Deleted 0 document by group in 0.0034821033477783 seconds
> ```
> 
> I believe this is the query that is done to fetch the attributes that should be deleted:
> 
> ```sql
> SELECT
>     table_main.*,
>     (
>         SELECT JSON_ARRAYAGG(DISTINCT _permission)
>         FROM `appwrite`.`_delete_attributes_perms`
>         WHERE
>             _document = table_main._uid
>             AND _type = 'read'
>     ) as _read,
>     (
>         SELECT JSON_ARRAYAGG(DISTINCT _permission)
>         FROM `appwrite`.`_delete_attributes_perms`
>         WHERE
>             _document = table_main._uid
>             AND _type = 'write'
>     ) as _write
> FROM
>     `appwrite`.`_delete_attributes` table_main
> WHERE 1=1 AND (table_main.collectionId = 'delete') AND table_main._uid IN
>     (
>         SELECT * FROM
>         (
>             SELECT _document
>             FROM `appwrite`.`_delete_attributes_perms`
>             WHERE _permission IN ('role:all')
>             AND _type = 'read'
>         ) as subquery
>     )
> GROUP BY table_main._uid
> ORDER BY table_main._id ASC
> LIMIT 0, 50
> ```
> 
> but the subquery:
> 
> ```sql
> SELECT * FROM
> (
>     SELECT _document
>     FROM `appwrite`.`_delete_attributes_perms`
>     WHERE _permission IN ('role:all')
>     AND _type = 'read'
> ) as subquery
> ```
> 
> makes the query return 0 results so no attributes are deleted. In my case, the `_delete_attributes_perms` is empty.

I tried to re-produce it multiple times without success and thanks to your query I now know whats going on.

The query actually shouldn't check for permissions in the first place! 

I am 99% confident, that this will fix it https://github.com/utopia-php/database/pull/130

**Comment by superseby2** [comment]
Thx guys!
