### ISSUE TITLE
🐛 Bug Report: Buckets not working proberly

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#2905]
### 👟 Reproduction steps

i found the issue that flutter sdk throws ```Bucket not found``` for new created Buckets.
(default is working)

so first i thought its a sdk problem, but after i debug it i found that it uses the path
```https://mydomain/v1/storage/buckets/6220dae06cfa2587ce29/files```
which is not working but
```https://mydomain/v1/storage/buckets/default/files```
is working fine.
![unknown](https://user-images.githubusercontent.com/17125438/156876998-f56ac8d3-4b32-4558-bd56-fdf18f7c952e.png)

### 👍 Expected behavior

all buckets should work, not only the default one

### 👎 Actual Behavior

only default bucket is working

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

0.13

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Please share your code snippet with us 🙏 I suspect a permission issue here. This could be either on our, or your side.

Also, if possible, please include your configuration by clicking on `view as JSON` (from your screenshot).

**Comment by s3ppo** [comment]
> Please share your code snippet with us 🙏 I suspect a permission issue here. This could be either on our, or your side.
> 
> Also, if possible, please include your configuration by clicking on `view as JSON` (from your screenshot).

Hey matej, i think a code snippet should not be needed, just enter the provided urls in chrome 😉

**Comment by s3ppo** [comment]
working fine in 0.13.2 now :)

**Comment by rodgav** [comment]
> funcionando bien en 0.13.2 ahora :)

![image](https://user-images.githubusercontent.com/30939186/157688826-52055a32-946c-461c-9a50-dd4c9e6f6195.png)
![image](https://user-images.githubusercontent.com/30939186/157688881-5122c7cb-525c-4cd2-aed8-3b25b54ed907.png)

**Comment by s3ppo** [comment]
sorry i have to reopen it, because with another new bucket its still not working

**Comment by s3ppo** [comment]
i think i found the culprit:

the bucket level permissions are still there, if you dont change the permission input fields, before you switch to file level

**Comment by s3ppo** [comment]
if i have this values in the input fields before switching to file level it works:
![image](https://user-images.githubusercontent.com/17125438/158031677-ee99ed17-744c-47c5-9ea3-845aa39469aa.png)

with empty fields before switching to file level it works not
![image](https://user-images.githubusercontent.com/17125438/158031711-6f78cb03-984f-47a5-8c75-9ae5219329bc.png)

**Comment by rodgav** [comment]
use file level
![image](https://user-images.githubusercontent.com/30939186/158032740-5fcbd825-949a-4cfd-a804-66045a15d254.png)
in my file 
![image](https://user-images.githubusercontent.com/30939186/158032788-dccab98d-46e1-4dc9-816b-5ba5dbaae65a.png)

**Comment by s3ppo** [comment]
> use file level
> ![image](https://user-images.githubusercontent.com/30939186/158032740-5fcbd825-949a-4cfd-a804-66045a15d254.png)
> in my file
> ![image](https://user-images.githubusercontent.com/30939186/158032788-dccab98d-46e1-4dc9-816b-5ba5dbaae65a.png)

Mhhh okay… but is it working for you or not? And what are the values in the hidden input fields of bucket level?

**Comment by rodgav** [comment]
> > use file level
> > ![image](https://user-images.githubusercontent.com/30939186/158032740-5fcbd825-949a-4cfd-a804-66045a15d254.png)
> > in my file
> > ![image](https://user-images.githubusercontent.com/30939186/158032788-dccab98d-46e1-4dc9-816b-5ba5dbaae65a.png)
> 
> Mhhh okay… but is it working for you or not? And what are the values in the hidden input fields of bucket level?
bucked level none, why do i use file level.
Not work. only in default.

**Comment by rodgav** [comment]
> > > use file level
> > > ![image](https://user-images.githubusercontent.com/30939186/158032740-5fcbd825-949a-4cfd-a804-66045a15d254.png)
> > > in my file
> > > ![image](https://user-images.githubusercontent.com/30939186/158032788-dccab98d-46e1-4dc9-816b-5ba5dbaae65a.png)
> > 
> > 
> > Mhhh okay… but is it working for you or not? And what are the values in the hidden input fields of bucket level?
> > bucked level none, why do i use file level.
> > Not work. only in default.
> > **add role all in bucked level and work.........? Is this normal or unusual behavior?**

in database the configuration is not like that.........??????

**Comment by lohanidamodar** [comment]
@s3ppo So if I understand correctly. To reproduce this problem
1. create a bucket set bucket level permission and add some permission
2. without removing the bucket permissions, switch to file level permission and update
When we do this the bucket level permission is still in effect?

**Comment by s3ppo** [comment]
> @s3ppo So if I understand correctly. To reproduce this problem
> 
> 1. create a bucket set bucket level permission and add some permission
> 2. without removing the bucket permissions, switch to file level permission and update
>    When we do this the bucket level permission is still in effect?

Yes i think so 👍

**Comment by s3ppo** [comment]
Please let me now if you could reproduce it 😉

**Comment by TorstenDittmann** [comment]
0.13.3 got released and should be fixed now 👏🏻

**Comment by MaddinMade** [comment]
I have the same problem with version 0.13.3. With a custom bucket with file level permissions I get a 404 back, but as soon as I do the same with 'default' everything works.

**Comment by Swinkid** [comment]
@TorstenDittmann Also have an issue with this in 0.13.3. If i set file level permissions, I'm unable to create a new file and get a 404 response.

**Comment by s3ppo** [comment]
> @TorstenDittmann Also have an issue with this in 0.13.3. If i set file level permissions, I'm unable to create a new file and get a 404 response.

Please try to set bucket level permissions to role:all before you switch to file level

**Comment by Swinkid** [comment]
> role:all

Have now done that but now unable to view image in console and getting a 404 when getFileView or getFileDownlaod in SDK.

**Comment by MaddinMade** [comment]
I don't know if this is related, but when my Functions are triggered by `storage.files.create`, a `general_route_not_found` error always flies before my Function is even executed. Could it be a migration issue from 0.12 so that the error doesn't occur for everyone?

**Comment by christyjacob4** [comment]
@s3ppo Could you try the same steps on an incognito window and let us know if this is an issue ?

**Comment by christyjacob4** [comment]
@s3ppo  Assigning it back to @Meldiron

**Comment by Meldiron** [comment]
@lohanidamodar has a PR that I can confirm solves this problem. Tested from his branch on Gitpod, and was not able to reproduce the problem: https://github.com/appwrite/appwrite/pull/2973

Also tested from master and can confirm it is still an issue.

**Comment by MaddinMade** [comment]
When is 0.13.4 expected to be released so that #2973 is included?

**Comment by s3ppo** [comment]
i can confirmed that its solved in 0.13.4 🥳

**Comment by jeffersonest** [comment]
> ### 👟 Reproduction steps
> 
> i found the issue that flutter sdk throws `Bucket not found` for new created Buckets. (default is working)
> 
> so first i thought its a sdk problem, but after i debug it i found that it uses the path `https://mydomain/v1/storage/buckets/6220dae06cfa2587ce29/files` which is not working but `https://mydomain/v1/storage/buckets/default/files` is working fine. ![unknown](https://user-images.githubusercontent.com/17125438/156876998-f56ac8d3-4b32-4558-bd56-fdf18f7c952e.png)
> ### 👍 Expected behavior
> 
> all buckets should work, not only the default one
> ### 👎 Actual Behavior
> 
> only default bucket is working
> ### 🎲 Appwrite version
> 
> Different version (specify in environment)
> ### 💻 Operating system
> 
> Linux
> ### 🧱 Your Environment
> 
> 0.13
> ### 👀 Have you spent some time to check if this issue has been raised before?
> 
>     * [x]  I checked and didn't find similar issue
> 
> 
> ### 🏢 Have you read the Code of Conduct?
> 
>     * [x]  I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

Try to use "project" param, like this:
https://api.sunsy.io/v1/storage/buckets/62c2524526f92f853b07/files/62c252a412f63c7585c0/view?project=62c23e8c21a24f5b5a1a

**Comment by conradbekondo** [comment]
This problem still is still present in [Version 1.4.3](https://github.com/appwrite/appwrite/releases)
