### ISSUE TITLE
🐛 Bug Report: Permissions Error in Collection 0.13.1

### ISSUE THREAD

**Issue by AhmedHammad0900** [appwrite/appwrite#2906]
### 👟 Reproduction steps

Create a Collection
- Setting Collection Level Permissions
- Set the Read Permission to a team
- Set the Write Permission to a user
- It forces me to set the twice to the team the read and write
- When try to change the write to the user: Server Error and most of appwrite functions dropsdown 

![image](https://user-images.githubusercontent.com/81931290/156879851-49ed4a9e-5ad1-41ec-90ea-1b1eac32aa84.png)

- Reinstalled Appwrite with clean install problem remains .

### 👍 Expected behavior

Can Control Access of Collection as I want like previous Versions set the write and read permissions seperatly

### 👎 Actual Behavior

Errors and drop down of all services and can't do anything to the collection again as function still in back causing UI Problems

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

0.13.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by AhmedHammad0900** [comment]
Happens too when try to set multiple permissions on doucment level ( ex . set read permission for a user:1 and team:2 ) need to do a docker-compose up -d and recreating appwrite to back to normal function

**Comment by TorstenDittmann** [comment]
Okay, thats a weird one. I am on it 😄

**Comment by TorstenDittmann** [comment]
We just released [0.13.2](https://github.com/appwrite/appwrite/releases/tag/0.13.2) where this is fixed 🙏🏻 

Thanks a lot for reporting this 👍🏻
