### ISSUE TITLE
🚀 Feature: Add docker (container) health check

### ISSUE THREAD

**Issue by MarvinJWendt** [appwrite/appwrite#2908]
### 🔖 Feature description

Adding a [`HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#healthcheck) command to the `Dockerfile`, for all the appwrite containers.

For example, to check every five minutes that a web-server is able to serve the main page within three seconds: 
`HEALTHCHECK CMD curl --fail http://localhost || exit 1`

### 🎤 Pitch

Adding a `HEALTHCHECK` to the `Dockerfile` would provide the users a better overview of the containers. Docker will execute the `HEALTHCHECK` command when the container spins up, and report "starting" until the `HEALTHCHECK` succeeds, or fails. If the `HEALTHCHECK` passes, the container will report "healthy". 

Appwrite already provides some health check API endpoints, so I think it would make sense to include those.

Also, this would make it very easy to spot "faulty" behaviour. I think it would also make the development of appwrite a little easier. 

**Screenshot of portainer with containers that have a healthcheck and containers that don't**
![image](https://user-images.githubusercontent.com/31022056/156903871-24e5996d-56ea-42ea-b689-3cf853e2325e.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Might be a bit complex as we use the same Dockerfile for all internal containers for easier maintenance. @TorstenDittmann, @lohanidamodar got any ideas what would be the best approach?

**Comment by lohanidamodar** [comment]
`docker run` does seem to support overriding healthcheck command https://docs.docker.com/engine/reference/run/#healthcheck

and `docker-compose` reference seems to have this as well 
https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

So @eldadfux I think we should be add it to each of our containers in compose stack

**Comment by eldadfux** [comment]
I'll close this know as it's not a priority. Happy to reopen if someone would like to make a PR and update the compose file.

**Comment by SkypLabs** [comment]
Wouldn't it be better to keep it open with a label like `help wanted`? Otherwise no one will pick this up.
