### ISSUE TITLE
🐛 Bug Report: 404 Can't get session

### ISSUE THREAD

**Issue by uclnj** [appwrite/appwrite#2911]
### 👟 Reproduction steps

Using appwrite CLI to view current sessions, does not ever clear out terminated connections and is not able to query active connections.

### 👍 Expected behavior

Used browser to create a session for a logged in user and can query documents/data:

![image](https://user-images.githubusercontent.com/835685/156926164-b925c8ee-2781-4895-aeeb-ea812e49675f.png)

From the CLI, logged in as administrator, I attempt to get all sessions which does not include the sessionId shown in the browser and I cannot query that sessionId.

![image](https://user-images.githubusercontent.com/835685/156925815-b6ed624c-e52c-4e11-a839-468c61504550.png)

Can you only query your sessionId even as the admin?

### 👎 Actual Behavior

Should get all sessions for all users.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

v:0.13.0.300 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey there 👋
`account` refers to `mine`, while `users` means to `others`.

`account` API is there to see stuff about **my** account, while `users` API provides information about `all accounts`.

With AppwriteCLI, the `account` API shows information about your Appwrite Console account, so you can see your log in sessions there.

To see sessions of users inside your project, you need to use `users` API.

Lets try this command: `appwrite users getSessions --userId [USER_ID]`. Please let me know if this gives you the information you were looking for.

**Comment by stnguyen90** [comment]
Closing as no further action required.
