### ISSUE TITLE
🐛 Bug Report: Function stdout limited to 8000

### ISSUE THREAD

**Issue by JakeAi** [appwrite/appwrite#2917]
### 👟 Reproduction steps

Returned length for function results is capped at 8000 bytes/characters.

https://discord.com/channels/564160730845151244/564161373148414012/948999806905360467

### 👍 Expected behavior

Return all data

### 👎 Actual Behavior

Returns data truncated to 8000.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
I increased the limit to 16k as a quick patch. In future, we should not apply the limit on sync executions.

**Comment by JakeAi** [comment]
> I increased the limit to 16k as a quick patch. In future, we should not apply the limit on sync executions.

What was it before? 8k?

**Comment by TorstenDittmann** [comment]
We just released [0.13.2](https://github.com/appwrite/appwrite/releases/tag/0.13.2) where we increased this to 16384 chars. For the next releases we are able to increase it even more - this was the highest we can go without internal schema changes 👍🏻

**Comment by JakeAi** [comment]
> We just released [0.13.2](https://github.com/appwrite/appwrite/releases/tag/0.13.2) where we increased this to 16384 chars. For the next releases we are able to increase it even more - this was the highest we can go without internal schema changes 👍🏻

Great to hear, however I won't be able to take advantage of sync functions where a hard cap truncates the result exists. I look forward to the next release where the limit is removed.

**Comment by JakeAi** [comment]
> 

Sync functions were a huge leap for my use case on getting rid of what's left of my backend API. Appwrite has removed almost all of my backend API code. All that was left was SQL queries for a front end shop communicating with our ERP software. However the queries are coming back truncated. So I will need to continue using my backend api.

**Comment by JakeAi** [comment]
> > > We just released [0.13.2](https://github.com/appwrite/appwrite/releases/tag/0.13.2) where we increased this to 16384 chars. For the next releases we are able to increase it even more - this was the highest we can go without internal schema changes 👍🏻
> > 
> > 
> > Great to hear, however I won't be able to take advantage of sync functions where a hard cap truncates the result exists. I look forward to the next release where the limit is removed.
> 
> May you share your use case so we can understand why that limitation is blocking you? 🙂

Is this hard limit going to be removed? I just don't want to get my hopes up.

**Comment by christyjacob4** [comment]
@JakeAi  What would be a reasonable limit according to you? We need to keep in mind that moving large payloads across a network is not a optimal way to handle things.. That is why we decided to truncate the output to a reasonable length and suggest that developers store the output in a text file in the Appwrite storage for anything longer

**Comment by JakeAi** [comment]
> @JakeAi What would be a reasonable limit according to you? We need to keep in mind that moving large payloads across a network is not a optimal way to handle things.. That is why we decided to truncate the output to a reasonable length and suggest that developers store the output in a text file in the Appwrite storage for anything longer

When I first heard about the sync functions, I never saw the result being stored in the DB, so in my mind, there would be no limit and the result would be discarded. However, I don't know what a reasonable limit would be? I saw you guys had a PR for 1mb which is probably more than enough.
