### ISSUE TITLE
🐛 Bug Report: File preview capped at 8-10mb without an ENV variable

### ISSUE THREAD

**Issue by JakeAi** [appwrite/appwrite#2918]
### 👟 Reproduction steps

In the recent update, appwrite disabled image preview for files over a certain threshold (the threshold is also bugged according to the thread). However, there is no backwards compatibility (an env variable or setting) for disabling the threshold.

https://discord.com/channels/564160730845151244/564161955963731980/948976720470491146

### 👍 Expected behavior

I should still get image previews for large files after updating.

### 👎 Actual Behavior

I get a placeholder image for images over 8mb

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
We just released [0.13.2](https://github.com/appwrite/appwrite/releases/tag/0.13.2) where we increased this limit to 20mb 👍🏻 

For the next release we will make it configurable over a env variable 🙂

**Comment by JakeAi** [comment]
> We just released [0.13.2](https://github.com/appwrite/appwrite/releases/tag/0.13.2) where we increased this limit to 20mb 👍🏻
> 
> For the next release we will make it configurable over a env variable 🙂

Great to hear, thanks! I look forward to the next release.
