### ISSUE TITLE
Improve optional arguments

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#292]
Let's say I wanna use `getFilePreview('[FILE_ID]')` and change the output format. Since the argument for output is at the end after 4 different optional arguments, the method call can look quite confusing.

My suggestion would be to have a single object to achieve flexible and readable optional arguments!

Like: `sdk.storage.getFilePreview('[FILE_ID]', { output: 'jpeg' } );`

Since I would love to have this feature, I could work on this.

**Comment by eldadfux** [comment]
Yeh this a nice idea 💡 

I was looking into something like this lately:
https://simonsmith.io/destructuring-objects-as-function-parameters-in-es6

This might allow us to support multiple ways to pass arguments and handle default and required values easily. I'll assign this for deeper review in 0.6.

**Comment by TorstenDittmann** [comment]
I like the idea of having required and optional arguments divided like I said, if you have all arguments in an object, you have to check for for the required arguments inside the object.

I think it is more easy to have the required parameters as single arguments and all the optional ones as a single object.

Like this you can directly see inside the IDE whats required.

But with something like this the spirits divide and it depends on the taste :D
