### ISSUE TITLE
🐛 Bug Report: migrating from 12 to 13.1 

### ISSUE THREAD

**Issue by pspierce** [appwrite/appwrite#2920]
### 👟 Reproduction steps

Follow upgrade steps:
```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.13.1
```
Then:
docker-compose exec appwrite migrate

### 👍 Expected behavior

Succesful upgrade from 12 to 13.1

### 👎 Actual Behavior

```
Migrating Collection projects:

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php:158
Stack trace:
#0 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(158): array_key_exists('$id', NULL)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1261): Utopia\Database\Database->Utopia\Database\{closure}(NULL, Object(Utopia\Database\Document), Object(Utopia\Database\Database))
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1153): Utopia\Database\Database->decodeAttribute('json', '', Object(Utopia\Database\Document))
#3 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(961): Utopia\Database\Database->decode(Object(Utopia\Database\Document), Object(Utopia\Database\Document))
#4 /usr/src/code/src/Appwrite/Migration/Migration.php(98): Utopia\Database\Database->find(Object(Utopia\Database\Document), Array, 100, 0, Array, Array, Array)
#5 /usr/src/code/src/Appwrite/Migration/Version/V12.php(43): Appwrite\Migration\Migration->forEachDocument(Array)
#6 /usr/src/code/app/tasks/migrate.php(65): Appwrite\Migration\Version\V12->execute()
#7 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}('0.13.1')
#8 /usr/src/code/app/cli.php(28): Utopia\CLI\CLI->run()
#9 {main}
  thrown in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 158
```

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Local docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by pspierce** [comment]
I should note I had the same occurrence on two different projects, one personal and one work.  They were in similar environments.  My personal project, I just started over with a new project.

**Comment by lexxyungcarter** [comment]
Any luck?

**Comment by lohanidamodar** [comment]
@TorstenDittmann We should be able to migrate from 0.12.x to 0.13.x without issues right?

**Comment by TorstenDittmann** [comment]
> @TorstenDittmann We should be able to migrate from 0.12.x to 0.13.x without issues right? 

Yes, this bug should be fixed in the latest 13.x.

**Comment by TorstenDittmann** [comment]
> > @TorstenDittmann We should be able to migrate from 0.12.x to 0.13.x without issues right? 
> 
> Yes, this bug should be fixed in the latest 13.x.

Actually no, this was not merged for release. Will be part of the next one: https://github.com/utopia-php/database/pull/111

**Comment by pspierce** [comment]
Do we know what data is missing that is causing this issue?  If I could update mariadb manually, that would save me having to tear down the project, delete the mariadb container, and starting over.  Anyway to "fix" this?

**Comment by pspierce** [comment]
I am getting a similar error when attempting to init the project with the cli or when I open the console via the web
(HTTP://localhost/console)
[Error] Line: 158
[Error] Timestamp: 2022-03-28T20:05:29+00:00
[Error] Method: GET
[Error] URL: /v1/projects
[Error] Type: TypeError
[Error] Message: array_key_exists(): Argument #2 ($array) must be of type array, null given
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 158

**Comment by stnguyen90** [comment]
@pspierce, is this still a problem or can the issue be closed?

**Comment by eldadfux** [comment]
Closing as this issue seems stalled.
