### ISSUE TITLE
🐛 Bug Report: Flutter: getFileView not work. 

### ISSUE THREAD

**Issue by rodgav** [appwrite/appwrite#2922]
### 👟 Reproduction steps

  dependency:   appwrite: ^4.0.1
  server: appwrite 0.13
  image in server:
![image](https://user-images.githubusercontent.com/30939186/157048441-c5c76ff3-6437-4bd5-93b2-ff839d792ecf.png)

  code:
`FutureBuilder<Uint8List>(
        future: _viewModel.storage.getFileView(
               bucketId: Constant.buckedId,
                fileId: '622575ab54668469f82f',
        ),
        builder: (context, snapshot) {
                     return snapshot.hasData &&
                     snapshot.data != null
                     ? Image.memory(snapshot.data!)
                        :const SizedBox();
         },
)`
  code initialize:
` ProductsDetailsViewModel(
      this._productDetailsUseCase, this._localDataSource, Client _client)
      : storage = Storage(_client);`

### 👍 Expected behavior

view image in my app

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/30939186/157049389-98db94b0-eee3-4330-846a-f180dcadb61f.png)

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

yes

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by s3ppo** [comment]
Do you use the „default“ bucket or a new created one?

**Comment by rodgav** [comment]
> Do you use the „default“ bucket or a new created one?

one created
