### ISSUE TITLE
🚀 Feature: Ability of add parameters inside vars key in appwrite.json.

### ISSUE THREAD

**Issue by arturgoms** [appwrite/appwrite#2924]
### 🔖 Feature description

Ability of add parameters inside vars key of functions.

### 🎤 Pitch

Today we have the appwrite.json files that stores information about functions. Some information about then need to be insert from Appwrite frontend, I think we can add the ability to save some of that information like the variables, the crontab inside that json before the deployment step. This will automate the process of the deployment a lot, besides that, if someone like me has a repository to store the functions, we can have sensitive information stored has a secret, so we can control the version without care too much about the security. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@arturgoms Thank you for the request. We had a discussion regarding this, and are still looking for best approach.

the environment variables (env) can contain sensitive data and as `appwrite.json` is something that gets committed to git, users might unknowingly share their secrets. At Appwrite's we want things to be secure by default, so we are looking for a better approach for example may be including and parsing a .env file for each functions or so. Please share your suggestions as well.

**Comment by radvansky-tomas** [comment]
Which you can easily avoid, by not requiring stuff such as endpoint & apikey for CF. Those are running from server itself, why we have to manually generate API key and manually add them as ENV variables, when we only want to access admin SDK from server itself. 

This is not "service account" situation, where you want to access third party server and obtain admin privileges.

**Comment by stnguyen90** [comment]
Closing as it's now possible to include variables, CRON, execute permissions, etc. in the appwrite.json. For more info, refer to our [docs](http://localhost:2080/docs/command-line-deployment#appwriteJSON).
