### ISSUE TITLE
🚀 Feature: Option To Select What Document a Functions Event listens to

### ISSUE THREAD

**Issue by rlee1990** [appwrite/appwrite#2925]
### 🔖 Feature description

What we should be able to do in functions is when we select an event to trigger a function say a document or collection event we should be able to also select which document or collect that will trigger this so that we are not calling the function all the time when it's not needed.

### 🎤 Pitch

In my case, I want to listen to when a document is created in one collection but in the current setup, I have to check which collection the document is coming from then perform my task. This also creates more calls to the function which is not needed and could have performance impacts down the line.

You could take 2 routes one of which is the way firebase handles this. In the function, we can write the path in the function.
In the second option, when we select the event depending on the event it could give a drop-down option to select what location the event needs to be on.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by JakeAi** [comment]
> ### 🔖 Feature description
> What we should be able to do in functions is when we select an event to trigger a function say a document or collection event we should be able to also select which document or collect that will trigger this so that we are not calling the function all the time when it's not needed.
> 
> ### 🎤 Pitch
> In my case, I want to listen to when a document is created in one collection but in the current setup, I have to check which collection the document is coming from then perform my task. This also creates more calls to the function which is not needed and could have performance impacts down the line.
> 
> You could take 2 routes one of which is the way firebase handles this. In the function, we can write the path in the function. In the second option, when we select the event depending on the event it could give a drop-down option to select what location the event needs to be on.
> 
> ### 👀 Have you spent some time to check if this issue has been raised before?
> * [x]  I checked and didn't find similar issue
> 
> ### 🏢 Have you read the Code of Conduct?
> * [x]  I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

I also would like this. Implementing it in the functions code is very tedious when you have a lot of functions.

**Comment by stnguyen90** [comment]
@rlee1990, @JakeAi, this should be possible now. Have you tried the latest version of Appwrite?

**Comment by rlee1990** [comment]
@stnguyen90 Yes I seen it was added
