### ISSUE TITLE
🚀 Feature: Make .NET SDK and code examples feel more authentic and remove anti-patterns.

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/appwrite#2926]
### 🔖 Feature description

The .NET SDK has issues with code examples and SDK generated. Code use is not authentic to the language and contains anti-patterns. Here are some example:

`string path = "/database/collections/{collectionId}".Replace("{collectionId}", collectionId);` 
Should be:
`string path = $"/database/collections/{collectionId}";`

And

```c#
client
    .setEndpoint('http://[HOSTNAME_OR_IP]/v1') // Make sure your endpoint is accessible
    .setProject('5ff3379a01d25') // Your project ID
    .setKey('cd868c7af8bdc893b4...93b7535db89')
    .setSelfSigned() // Use only on dev mode with a self-signed SSL cert
```

Uses "Java-esque setXXX() idioms in C#." This is considered an anti-pattern.

use proper properties instead. For reference see ASP.NET's startup and Options code examples.

**We could use our community's help here, to suggest similar issues with good code practice in the examples and generated SDK we provide.**

### 🎤 Pitch

As mentioned by Reddit user [f-berasategui](https://www.reddit.com/user/f-berasategui/), our .NET SDK feels like it's "written by a Java person." We should strive to have each SDK feel authentic to it's user base, and we should try to make changes to examples and SDK generator to make this happen. We need to avoid `anti-patterns`.

https://www.reddit.com/r/programming/comments/t9gmn1/comment/hzugo45/?utm_source=share&utm_medium=web2x&context=3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
I think this is an issue worthy of discussion, would love to hear what other C# users in our community think.

**Comment by thdev-sync** [comment]
Regarding the `Client` example you gave above (similar to https://github.com/appwrite/sdk-for-dotnet#initialize--make-api-request ):

I see two viable options here. The first one is using a `ClientBuilder` that then 'builds' the client:

(1) Using the builder pattern (nothing specific to C#), note the capitalized method names (this is C# specific):
```cs
  var cb= new ClientBuilder();

  var client = cb
    .SetEndpoint('http://[HOSTNAME_OR_IP]/v1') 
    .SetProject('5ff3379a01d25')
    .SetKey('cd868c7af8bdc893b4...93b7535db89')
    .setSelfSigned()
    .Build() // note the call to build, which 'finalizes' the builder and generates a valid instance of Client
  ;
```


(2) Using [C# properties](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties):
```cs
  var client = new Client(); // using the Client constructor

  client.Endpoint = "http://[HOSTNAME_OR_IP]/v1";
  client.Project = "5ff3379a01d25";
  // etc
```

Properties are basically syntactic sugar and avoid us having to add all the clunky getter/setter methods you would see in e.g. Java.

Also note that im creating a new instance of Client using the constructor. Static methods are only useful as 'factories' but in the example above, there is nothing special (eg arguments) about the call. The constructor can (should) be used for simple initialization and dependencies or mandatory parameters can be declared on it.
@gewenyu99

**Comment by adityaoberai** [comment]
With C#, I personally prefer using properties as well. But I don't think the example shown above will be the best way forward for us considering that aside from the Endpoint, other properties like Project, Key, or JWT are not independent primitive properties but a part of the `headers` and `config` dictionary, which can be seen in the [Client.cs file](https://github.com/appwrite/sdk-for-dotnet/blob/main/io/appwrite/src/Appwrite/Client.cs) in the SDK. In this scenario, I do believe that the abstraction provided by the setXXX functions makes life a little easier for the developer. That being said, I am relatively a novice developer and would love more thoughts on this too.

**Comment by myThorsten** [comment]
May I ask where I can find the .net SDK? It isn't mentioned in the docs under https://appwrite.io/docs/.
Or does this issue refer to https://github.com/appwrite/sdk-for-dotnet. In that case, is there a roadmap as to when an updated SDK for appwrite 1.0 is expected?
Thanks :)

**Comment by adityaoberai** [comment]
> May I ask where I can find the .NET SDK? It isn't mentioned in the docs under https://appwrite.io/docs/. Or does this issue refer to https://github.com/appwrite/sdk-for-dotnet. In that case, is there a roadmap as to when an updated SDK for appwrite 1.0 is expected? Thanks :)

The issue does refer to the [sdk-for-dotnet](https://github.com/appwrite/sdk-for-dotnet) repo, which is currently out of date. A .NET server-side SDK is under the works, however, and you can track progress on this [PR](https://github.com/appwrite/sdk-generator/pull/320) here in our [SDK Generator](https://github.com/appwrite/sdk-generator) repo.

**Comment by joeyouss** [comment]
Closing this issue since the PR : https://github.com/appwrite/sdk-generator/pull/320 is now merged 🎉
