### ISSUE TITLE
🐛 Bug Report: Storage Bucket image upload error

### ISSUE THREAD

**Issue by xuala69** [appwrite/appwrite#2927]
### 👟 Reproduction steps

I installed appwrite 0.13 on an AWS EC2 instance and completed successfully but when creating a new bucket and adding/uploading an image from the appwrite console (as admin), the image is not uploaded, so I inspected the page and retried uploading the image again and get the error on the console log 

ERROR-EVENT: wirte is not defined ReferenceError: wirte is not defined
    at Proxy.uploadFile (https://console.darbu.in/dist/scripts/app-all.js?v=301.0.13.1:3744:60)
    at eval (eval at safeAsyncFunction (https://console.darbu.in/dist/scripts/app-all.js?v=301.0.13.1:3267:255), <anonymous>:3:48)
    at https://console.darbu.in/dist/scripts/app-all.js?v=301.0.13.1:3268:297
    at tryCatch (https://console.darbu.in/dist/scripts/app-all.js?v=301.0.13.1:3256:62)
    at https://console.darbu.in/dist/scripts/app-all.js?v=301.0.13.1:3546:394
    at handler3 (https://console.darbu.in/dist/scripts/app-all.js?v=301.0.13.1:3468:82)
    at https://console.darbu.in/dist/scripts/app-all.js?v=301.0.13.1:3475:61
    at https://console.darbu.in/dist/scripts/app-all.js?v=301.0.13.1:3468:151
    at https://console.darbu.in/dist/scripts/app-all.js?v=301.0.13.1:3482:1

Uncaught ReferenceError: wirte is not defined
    at Proxy.uploadFile (app-all.js?v=301.0.13.1:3744:60)
    at eval (eval at safeAsyncFunction (app-all.js?v=301.0.13.1:3267:255), <anonymous>:3:48)
    at app-all.js?v=301.0.13.1:3268:297
    at tryCatch (app-all.js?v=301.0.13.1:3256:62)
    at app-all.js?v=301.0.13.1:3546:394
    at handler3 (app-all.js?v=301.0.13.1:3468:82)
    at app-all.js?v=301.0.13.1:3475:61
    at app-all.js?v=301.0.13.1:3468:151
    at app-all.js?v=301.0.13.1:3482:1
    at HTMLFormElement.<anonymous> (app-all.js?v=301.0.13.1:3468:151)

### 👍 Expected behavior

New image to be added without error and show up on console

### 👎 Actual Behavior

[https://i.postimg.cc/DzntjYyt/Screenshot-from-2022-03-09-11-51-25.png](url)

No error message is shown to the screen but when inspecting the page and retrying to upload the image, error is thrown as shown in the image

![Screenshot from 2022-03-09 11-51-25](https://user-images.githubusercontent.com/25664508/157384606-674a3c04-ae4f-4d49-83a6-0afdd7690723.png)

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Swinkid** [comment]
Have raised a PR fixing this #2931

**Comment by eldadfux** [comment]
Fixed, and will be released on the next Appwrite version, thank for sharing the report!

**Comment by matigumma** [comment]
thanks

**Comment by TorstenDittmann** [comment]
0.13.3 got released and should be fixed now 👏🏻
