### ISSUE TITLE
🐛 Bug Report: appwrite-executor doesn't start properly after reboot

### ISSUE THREAD

**Issue by chuiizeet** [appwrite/appwrite#2932]
### 👟 Reproduction steps

reboot server.

### 👍 Expected behavior

appwrite-executor start correctly after reboot.

### 👎 Actual Behavior

After reboot:
`docker ps`
![Screen Shot 2022-03-09 at 17 28 57](https://user-images.githubusercontent.com/23518097/157570784-b97a20d7-88fa-41d9-a5dd-d822f0dea31f.png)

`docker-compose ps`
![Screen Shot 2022-03-09 at 17 34 01](https://user-images.githubusercontent.com/23518097/157570828-5c2c719c-dfd1-4d97-8f47-cfe83e6bcb5d.png)

`docker-compose logs appwrite-executor`
![Screen Shot 2022-03-09 at 15 58 22](https://user-images.githubusercontent.com/23518097/157570877-5a6398cd-9dd0-4efe-a66f-3444528b65c1.png)

For solution this i run `docker-compose up -d` and then works correctly.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
As a workaround, I believe you can try adding `restart: unless-stopped` under `container_name: appwrite-executor` in your `docker-compose.yml`.

**Comment by chuiizeet** [comment]
> As a workaround, I believe you can try adding `restart: unless-stopped` under `container_name: appwrite-executor` in your `docker-compose.yml`.

Yes, after add `restart: unless-stopped` the container start without problems.

**Comment by eldadfux** [comment]
@chuiizeet if you could the logs for the `appwrite-executor` container they might shed some light on why the container stopped working. You can use `docker-compose logs appwrite-executor`

**Comment by christyjacob4** [comment]
@chuiizeet , the logs you shared for the executor are fine. They do not indicate any crash . The only clue Im able to get from the details you've shared is the `Exit code 137` .
Docker uses this code to indicate a termination by a SIGTERM signal arising when the host system runs out of resources. ( memory or disk space usually ) 
Do you have any details you can provide on that front ?

**Comment by stnguyen90** [comment]
> @chuiizeet if you could the logs for the `appwrite-executor` container they might shed some light on why the container stopped working. You can use `docker-compose logs appwrite-executor`

appwrite-executor logs are shown in the last screenshot

> @chuiizeet , the logs you shared for the executor are fine. They do not indicate any crash . The only clue Im able to get from the details you've shared is the `Exit code 137` .
> Docker uses this code to indicate a termination by a SIGTERM signal arising when the host system runs out of resources. ( memory or disk space usually )
> Do you have any details you can provide on that front ?

I believe the 137 is from the server reboot.

**Comment by chuiizeet** [comment]
> @chuiizeet , the logs you shared for the executor are fine. They do not indicate any crash . The only clue Im able to get from the details you've shared is the `Exit code 137` . Docker uses this code to indicate a termination by a SIGTERM signal arising when the host system runs out of resources. ( memory or disk space usually ) Do you have any details you can provide on that front ?

After add restart: unless-stopped the container start without problems.
I've only a one python function.
My server has 2gb ram 2vcpu.

**Comment by TorstenDittmann** [comment]
This got merged and fixed with 0.13.3 👏🏻
