### ISSUE TITLE
Distributed Appwrite Server

### ISSUE THREAD

**Issue by komorebi-san** [appwrite/appwrite#294]
I have two different servers running. One locally and another in a remote server.

Is it possible to sync the Appwrite, including the Account and Authentication services?

Means that, if I register an account via the remote server, locally it will sync from the remote host to have the account locally as well, vice versa.

**Comment by eldadfux** [comment]
Not sure about your exact use-case and what you are ultimately trying to achieve, but you can try a few paths to reach your sync goal.

1. Use Appwrite webhooks to register an HTTP endpoint on every event you would like to achieve, and use it to sync your local DB. (v0.5 will include a lot more event than current 0.4) 
2. Sync Appwrite DB. Appwrite uses MySQL/MariaDB to store all data. You can use any MySQL script available online or even your own to sync both DBs and keep data synced.
3. You can use your own custom proxy in-front of your Appwrite setups and call both your local and remote endpoints on users requests for that proxy.

Let me know if this helps. @komorebi-san
