### ISSUE TITLE
🐛 Bug Report: collection attribute getting stuck

### ISSUE THREAD

**Issue by ameerfayiz** [appwrite/appwrite#2945]
### 👟 Reproduction steps

delete collection and make a collection with same collection id, all the old attributes are returning like ghost without adding them. but the real issue is when i try to delete those ghost attributes, it gets "stuck" status. after that i cannot delete that attribute or create document with that attribute.. 

PS : issue is not always reproducing, but coming randomly, but restarting container is not working

![image](https://user-images.githubusercontent.com/41417646/158193912-e8edd376-7d3e-48d3-adfd-03be2c60a916.png)

### 👍 Expected behavior

when deleting a collection and recreating that collection, all data's in that collection along with all attributes should be gone. and no old attributes should come as ghost

### 👎 Actual Behavior

 all the old attributes are returning like ghost without adding them. but the real issue is when i try to delete those ghost attributes, it gets "stuck" status. after that i cannot delete that attribute or create document with that attribute.. 

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ameerfayiz** [comment]
related issue : https://github.com/appwrite/appwrite/issues/2902

**Comment by ameerfayiz** [comment]
TEMPORARY FIX for attributes getting stuck

- RUN:

`docker exec -it appwrite-mariadb bash`

- IN BASH ,RUN:
`mysql -u root -p `

nb : for password, open .env file and use _APP_DB_ROOT_PASS

- THEN, inside mariabc cli, run :

`delete from _[uuid]_indexes where collectionId = '[collection id]';`
`delete from _[uuid]_attributes where collectionId = '[collection id]';`

where [uuid] is project id and [collection id] is your collection id

**Comment by tripolskypetr** [comment]
The only question why do you hide THE REMOVE BUTTON if this issue is not fixed for more when a year. By toggling it manually several times it worked but right not i am receiving test: true on each collection document
