### ISSUE TITLE
🐛 Bug Report: Read permission for [role:member] doesn't work on custom storage buckets

### ISSUE THREAD

**Issue by anelad** [appwrite/appwrite#2958]
### 👟 Reproduction steps

1. Create a new storage bucket
2. Set bucket read permissions to `role:member` which is explained as **Access to any logged in user. A logged in user is a user with a valid session.** in the docs.
3. Upload a file.
4. You will see that even Appwrite admin panel is not able to preview the file.
5. Try to view file via any SDK which will fail (of course you need a valid session)

_Possibly_ other permission types are also failing.

### 👍 Expected behavior

Since `role:member` is explained as **Access to any logged in user. A logged in user is a user with a valid session.** in the docs Appwrite Admin console and any valid session should fetch the file correctly.

Problem doesn't exist on default bucket.

### 👎 Actual Behavior

It gives `404 Not Found` error, instead of a 200 with data.  AppwriteException says bucket cannot found, but actually it exsists but access is restricted in a buggy way.

Also I think code 403 is a better fit for the situation, instead of 404. 

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Related issue: https://github.com/appwrite/appwrite/issues/2905

**Comment by lohanidamodar** [comment]
This should be fixed in 0.13.3, apart from a bug in createFile which is fixed by #2973
