### ISSUE TITLE
🐛 Bug Report: Old cached document data is getting returned instead of latest data when document ID is uppercased and original ID was in lowercase

### ISSUE THREAD

**Issue by ameerfayiz** [appwrite/appwrite#2959]
### 👟 Reproduction steps

Created a document from console with any lowercased ID
Called getDocument from dart server sdk using uppercased ID , got the correct data.
Then, i updated same document from console.
Again, called getDocument from dart server sdk using uppercased ID , i got old unmodified data.

### 👍 Expected behavior

document id should be either case sensitive or not case sensitive. 

### 👎 Actual Behavior

old cached data is returning from server when document id is given as uppercased and the original document id was lower cased instead of NO document found or with latest data
but, the updated data is returning from server if lowercased document id is given.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
The problem is easily reproducible. Ill discuss case sensitivity internally and create a PR for this problem.

**Comment by stnguyen90** [comment]
Related PR: https://github.com/utopia-php/cache/pull/17

**Comment by Meldiron** [comment]
This issue came from Redis not being case-insensitive. Once PR above is marked and released, Appwrite can be upgraded to a new version and mark cache as case-insensitive. That will solve the problem.

I'll keep PR posted about the progress.

**Comment by eldadfux** [comment]
This feature is now released and available as part of Appwrite 0.14. More on the new release here: https://github.com/appwrite/appwrite/discussions/3240
