### ISSUE TITLE
How to write a complex query and return result to cloent

### ISSUE THREAD

**Issue by ndphuong** [appwrite/appwrite#2965]
Hi,

I want to joining two collections ( like join two tables) and return the result to client.

How can I do it?

**Comment by stnguyen90** [comment]
Currently, you'll have to make an api call for each collection.

**Comment by ndphuong** [comment]
@stnguyen90 
How about if I have two big collections like Students and Class.
I want to return a list of students with the class name.

Supabase seem support something like: "Deeply nested joins, allowing you to fetch data from multiple tables in a single fetch"

**Comment by stnguyen90** [comment]
> @stnguyen90 How about if I have two big collections like Students and Class. I want to return a list of students with the class name.
> 
> Supabase seem support something like: "Deeply nested joins, allowing you to fetch data from multiple tables in a single fetch"

Appwrite is more like relational database so you would probably have a collection of assignments that has class ID and student ID. You could then query that for the student IDs and then query for the students. If you want to move computation off of the client, you could do this with a cloud function.

**Comment by anandsubbu007** [comment]
> 
> Appwrite is more like relational database so you would probably have a collection of assignments that has class ID and student ID. You could then query that for the student IDs and then query for the students. If you want to move computation off of the client, you could do this with a cloud function.

how to write cloud function in server side? please share any example

**Comment by pspierce** [comment]
My concern with this approach is that I am responsible for enforcing the integrity of the join tables, not to mention having to create a LOT of functions.  It is making me rethink using Appwrite unless I can think of an easier way.  The promise of graphQL in the future would alleviate this, so I'll likely hold on.

**Comment by stnguyen90** [comment]
> how to write cloud function in server side? please share any example

https://appwrite.io/docs/functions

**Comment by tanifort** [comment]
What about calling custom database functions from Appwrite SDK??

**Comment by stnguyen90** [comment]
@tanifort, what do you mean by "custom database functions"?

**Comment by tanifort** [comment]
A function that is executed on the database or stored procedure.

**Comment by stnguyen90** [comment]
@tanifort. Appwrite is designed to abstract away all of the underlying details of the database so we probably won't be exposing a way to execute stored procedures.

**Comment by stnguyen90** [comment]
Closing as no further action is required.

**Comment by Express-router** [comment]
> Closing as no further action is required.





https://event-binding.github.io/comely592/
