### ISSUE TITLE
🐛 Bug Report: [console UI issue] console pages are less reactive  which restricts the utility value of available space

### ISSUE THREAD

**Issue by ameerfayiz** [appwrite/appwrite#2966]
### 👟 Reproduction steps

Hugely wasted spaces in  the pages, especially in "Database" page is making the page less usable when lots of row and columns are there. the pages should be more reactive to window resize and available spaces. utility should be given priority.

![image](https://user-images.githubusercontent.com/41417646/159080765-f8e99799-f3d1-416b-b142-0db7a2b35a0c.png)

### 👍 Expected behavior

the page should take up available space when browser window size is increased and try to avoid horizontal scrollbars.

### 👎 Actual Behavior

page contents are taking a constant width which is not increasing even browser window size is increased

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by mustansirgodhrawala** [comment]
@eldadfux Could I tackle this issue?

**Comment by eldadfux** [comment]
We've completely redesigned the console to better utilize the screen size. 
<img width="1440" alt="image" src="https://github.com/appwrite/appwrite/assets/1297371/edc47d66-1522-48be-9bcc-899fbec466b8">
