### ISSUE TITLE
🐛 Bug Report: for integer and double nullable attributes, without giving any defaults, its getting default value of '0' instead of null while adding any document

### ISSUE THREAD

**Issue by ameerfayiz** [appwrite/appwrite#2972]
### 👟 Reproduction steps

Made a nullable integer (or double) attribute without any default value specified, and added a document without giving any value for that integer attribute. but appwrite is giving value '0' to that field. for string attribute it is setting as 'null' as expected if no value is specified in createDocument() api or from console.

### 👍 Expected behavior

integer or double field should be given null value if no default is specified and no value is supplied via createDocument api or via console

### 👎 Actual Behavior

 but appwrite is giving value '0' to that field.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@ameerfayiz Thank you for notifying this issue, we will look int this p🙏

**Comment by stnguyen90** [comment]
This should no longer be the case. If an integer attribute does not have a default value, the new document will have null as the value.
