### ISSUE TITLE
🐛 Bug Report: Users not searchable using updated email and/or updated name

### ISSUE THREAD

**Issue by ameerfayiz** [appwrite/appwrite#2974]
### 👟 Reproduction steps

Create a user with foo@foo.com , then search for "foo" , you will get results as expected. 
Then, change email to bar@bar.com , then search for "bar", you get no result. 
after that , for "foo", you get "bar@bar.com" result.. seems like the index is not getting updated while updating email or name
can reproduce this issue from console itself or from SDK.

### 👍 Expected behavior

users should be searchable using updated email or updated name after updating either or both of it.

### 👎 Actual Behavior

users are not searchable (not getting expected results) once email or name or both are updated., only searchable using initial email and or name.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@ameerfayiz thank you for notifying us regarding the issue. We will look int it and provide update soon.

**Comment by stnguyen90** [comment]
Closing as this should be resolved as of 0.15.2:

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/1477010/180869062-80712bb5-8feb-4b3d-9713-c44a99423906.png">
