### ISSUE TITLE
🐛 Bug Report: [UI] update "open an issue" url in console

### ISSUE THREAD

**Issue by ameerfayiz** [appwrite/appwrite#2976]
### 👟 Reproduction steps

clicking "open an issue" from appwrite console is opening "https://github.com/appwrite/appwrite/issues/new" instead of "https://github.com/appwrite/appwrite/issues/new/choose"

### 👍 Expected behavior

would be more suitable if redirected to "https://github.com/appwrite/appwrite/issues/new/choose"

### 👎 Actual Behavior

its redirecting to "https://github.com/appwrite/appwrite/issues/new"

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@ameerfayiz Thank you for notifying us. We will look into it.

**Comment by eldadfux** [comment]
This feature is now released and available as part of Appwrite 0.14. More on the new release here: https://github.com/appwrite/appwrite/discussions/3240
