### ISSUE TITLE
🐛 Bug Report:  Not able to combine Querys lesserEqual with Search

### ISSUE THREAD

**Issue by Invisibleshroud** [appwrite/appwrite#2988]
### 👟 Reproduction steps

**Used Querys:**
`Query.lesserEqual('dateOfBirth', myMaxAgeDate),`
`Query.greaterEqual('dateOfBirth', myMinAgeDate),`
`Query.search('largeTextString', partialSearchString),`

**Used Index:**
Type: fulltext
Attributes: [dateOfBirth] & [largeTextString]

### 👍 Expected behavior

The documents that meet the query filters.

### 👎 Actual Behavior

Error
`{"message":"Error: Server Error","code":500,"version":"0.13.3"}`

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Invisibleshroud thanks for raising this issue! 🙏🏼 A couple of questions:

1. What's the type for the `dateOfBirth` attribute?
2. Would you please check the docker logs for the appwrite container for details on the 500 error?

**Comment by TorstenDittmann** [comment]
I am happy to announce that [1.3.0](https://github.com/appwrite/appwrite/releases/tag/1.3.0) is now less strict with indexes and should solve this issue 👏🏻 

You can find more informations in [this blog post](https://dev.to/appwrite/join-celebrations-appwrite-13-ships-relationships-57fc) and [our docs](https://appwrite.io/docs/databases-relationships).
