### ISSUE TITLE
🚀 Feature: React Native Support

### ISSUE THREAD

**Issue by CristianFigueredo** [appwrite/appwrite#2993]
### 🔖 Feature description

React Native is a Framework created by Instagram, and now maintained by Facebook.

which is the pioneer in cross-platform native development (iOS, Android, Web, MacOS, Windows among others).

It is widely used and in demand, and now improving quite fast, thanks to the strong competition from Flutter.

Thousands of Facebook screens (in production are made with React Native).
The support of this framework will attract a number of developers who are able to see the productive potential of using both tools together.

### 🎤 Pitch

Besides, the hard part is already done.

support for iOS (Objective-C or/and Swift) and Android (Kotlin or/and Java) as well as Web (javascript).

The only thing needed is to make the bridges, to make it compatible with React Native.

thank you very much for taking the time to read this, if you have any question I am at your disposal, nice community.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Swinkid** [comment]
Quick google suggest most of the regular JavaScript SDK should work. Would be useful to know what doesn't work.

https://dev.to/fernandoamz/appwrite-react-native-48cn

**Comment by CristianFigueredo** [comment]
@Swinkid  you are right, with the  [SDK for Web](https://github.com/appwrite/sdk-for-web "SDK for Web") , 95% of the work is done.

[OAuth](https://github.com/appwrite/sdk-for-web/blob/master/src/sdk.ts#L1775 "OAuth")  is not compatible in my opinion.

A solution would be to use a WebView, or use OAuth libraries that are already available for React Native (recommended).

**Comment by CristianFigueredo** [comment]
also APIs that are browser-specific will have to be replaced by their React Native equivalents.

**Comment by ammarfaris** [comment]
Congrats on the 1.0 release! Would like to ask for the 1.0 release, **has OAuth support for React Native (RN) developers been improved?**

This work-around / package is no longer maintained and is not working, unfortunately: 
https://github.com/DiegoBM/react-native-appwrite-oauth/issues/1

The slightly less support for React Native has forced me to opt for other alternatives out there. Don't get me wrong, u guys are awesome! keep it up..!  just hope that the OAuth issue support for RN is built-in into the backend/ JS SDK.

**Comment by stnguyen90** [comment]
@CristianFigueredo, thanks for raising this issue! 🙏 It would be helpful to narrow down specifically what doesn't work with the SDK for web in react native so we can work on adding support. Perhaps you can provide reproduction steps and actual behavior of oauth authentication in https://github.com/appwrite/sdk-for-web/issues/29

**Comment by stnguyen90** [comment]
In order to add support, we really need to know what exactly doesn't work so we can work on adding support. Please create an issue in https://github.com/appwrite/sdk-for-web for each problem and include as much detail as possible (like error logs).

**Comment by stnguyen90** [comment]
Closing as we have https://github.com/appwrite/sdk-for-react-native now
