### ISSUE TITLE
🐛 Bug Report:  General error: 1283 Column 'COLUMNNAME' cannot be part of FULLTEXT index

### ISSUE THREAD

**Issue by Invisibleshroud** [appwrite/appwrite#2995]
### 👟 Reproduction steps

Creating an index with multiple fields including Integer and String fields.
Because i am using the search method in the Query option i need to use a FULLTEXT index.

### 👍 Expected behavior

Correct creation of the index.

### 👎 Actual Behavior

The index gives a Failed messages when i am trying to create it with the following message in the log:
SQLSTATE[HY000]: General error: 1283 Column 'agePreferenceMin' cannot be part of FULLTEXT index

This field is a integer.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
@TorstenDittmann can I get your eyes on this? 👀

**Comment by TorstenDittmann** [comment]
Hey :)

can you share some informations on the attributes structure? You can view the JSON of the collection on the dashboard 👍🏻

**Comment by badmark** [comment]
I am also experiencing this issue when trying to create a Fulltext index with a boolean field and a text field.

Error:

"SQLSTATE[HY000]: General error: 1283 Column 'Deleted' cannot be part of FULLTEXT index"

Database schema:

`{
    "$id": "61fda5201f21ac28c9d4",
    "$read": [
        "role:all"
    ],
    "$write": [
        "role:all"
    ],
    "name": "DankPost",
    "enabled": true,
    "permission": "collection",
    "attributes": [
        {
            "key": "PostTitle",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 300,
            "default": null
        },
        {
            "key": "PostText",
            "type": "string",
            "status": "available",
            "required": true,
            "array": false,
            "size": 5000,
            "default": null
        },
        {
            "key": "PostMedia",
            "type": "string",
            "status": "available",
            "required": false,
            "array": true,
            "size": 255,
            "default": null
        },
        {
            "key": "PostTags",
            "type": "string",
            "status": "available",
            "required": false,
            "array": true,
            "size": 255,
            "default": null
        },
        {
            "key": "PostOwnerId",
            "type": "string",
            "status": "available",
            "required": true,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "PostPosterIP",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "PostSessionId",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "PostColor",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "PostTypeId",
            "type": "integer",
            "status": "available",
            "required": true,
            "array": false,
            "min": 0,
            "max": 500,
            "default": null
        },
        {
            "key": "PostType",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "Owner",
            "type": "string",
            "status": "available",
            "required": true,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "RemovedDate",
            "type": "integer",
            "status": "available",
            "required": false,
            "array": false,
            "min": 0,
            "max": 2564013268,
            "default": null
        },
        {
            "key": "RemovedById",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "size": 255,
            "default": null
        },
        {
            "key": "PostURL",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "format": "url",
            "default": null
        },
        {
            "key": "PostScore",
            "type": "integer",
            "status": "available",
            "required": false,
            "array": false,
            "min": -500,
            "max": 2500000,
            "default": null
        },
        {
            "key": "PostShortURL",
            "type": "string",
            "status": "available",
            "required": false,
            "array": false,
            "format": "url",
            "default": null
        },
        {
            "key": "Deleted",
            "type": "boolean",
            "status": "available",
            "required": false,
            "array": false,
            "default": false
        },
        {
            "key": "PostDate",
            "type": "double",
            "status": "available",
            "required": true,
            "array": false,
            "min": 0,
            "max": 2564014156293,
            "default": null
        }
    ],
    "indexes": [
        {
            "key": "RemovedDate",
            "type": "key",
            "status": "available",
            "attributes": [
                "RemovedDate"
            ],
            "orders": [
                "ASC"
            ]
        },
        {
            "key": "Deleted",
            "type": "key",
            "status": "available",
            "attributes": [
                "Deleted"
            ],
            "orders": [
                "ASC"
            ]
        },
        {
            "key": "PostOwnerId",
            "type": "key",
            "status": "available",
            "attributes": [
                "PostOwnerId"
            ],
            "orders": [
                "ASC"
            ]
        },
        {
            "key": "PostTypeId",
            "type": "key",
            "status": "available",
            "attributes": [
                "PostTypeId"
            ],
            "orders": [
                "ASC"
            ]
        },
        {
            "key": "Tags",
            "type": "fulltext",
            "status": "available",
            "attributes": [
                "PostTags"
            ],
            "orders": [
                "ASC"
            ]
        },
        {
            "key": "PostDate",
            "type": "key",
            "status": "available",
            "attributes": [
                "PostDate"
            ],
            "orders": [
                "DESC"
            ]
        },
        {
            "key": "PostStream",
            "type": "key",
            "status": "available",
            "attributes": [
                "PostTypeId",
                "Deleted"
            ],
            "orders": [
                "ASC",
                "ASC"
            ]
        },
        {
            "key": "PostTagStream",
            "type": "key",
            "status": "available",
            "attributes": [
                "PostTags",
                "Deleted"
            ],
            "orders": [
                "ASC",
                "ASC"
            ]
        },
        {
            "key": "tagsNotDeleted",
            "type": "fulltext",
            "status": "failed",
            "attributes": [
                "Deleted",
                "PostTags"
            ],
            "orders": [
                "ASC",
                "ASC"
            ]
        },
        {
            "key": "tagstream",
            "type": "fulltext",
            "status": "failed",
            "attributes": [
                "PostTypeId",
                "PostTags",
                "Deleted"
            ],
            "orders": [
                "ASC",
                "ASC",
                "ASC"
            ]
        },
        {
            "key": "tagstreamnotdeleted",
            "type": "fulltext",
            "status": "failed",
            "attributes": [
                "PostTags",
                "Deleted"
            ],
            "orders": [
                "ASC",
                "ASC"
            ]
        },
        {
            "key": "tagsnotremoved",
            "type": "fulltext",
            "status": "failed",
            "attributes": [
                "PostTags",
                "RemovedDate"
            ],
            "orders": [
                "ASC",
                "ASC"
            ]
        },
        {
            "key": "posttagsindex",
            "type": "fulltext",
            "status": "failed",
            "attributes": [
                "PostTags"
            ],
            "orders": [
                "ASC"
            ]
        },
        {
            "key": "posttagsnotdeletedkeyindex",
            "type": "key",
            "status": "available",
            "attributes": [
                "PostTags",
                "Deleted"
            ],
            "orders": [
                "ASC",
                "ASC"
            ]
        }
    ]
}`

**Comment by fogelito** [comment]
The reason this happens is because fulltext index can not involve different charsets on a single index.
fulltext + integer.

**Comment by badmark** [comment]
So there is no way to make a query with an ID and a text array?

**Comment by fogelito** [comment]
There is no problem to make a query, but creating a fulltext index that contains an integer attributes will trigger a MySQL Exception

**Comment by stnguyen90** [comment]
@fogelito, @TorstenDittmann so what would the solution be or how can we add support for queries like:

```javascript
[
   Query.greaterThan("age", 21),
   Query.search("name", "John")
]
```

or 

```javascript
[
   Query.equal("draft", false),
   Query.search("title", "appwrite")
]
```

**Comment by fogelito** [comment]
Is it possible to add an Index **only** on the Fulltext attribute, or this will trigger an exception? If it does we must loosen the strict validation for Fulltext index

**Comment by stnguyen90** [comment]
@fogelito, yes it's possible to add a full text index only on the 1 attribute. So, sounds like the plan might be to not require a strict index match if the queries contains a search, right? @TorstenDittmann, are you good with this approach?

**Comment by fogelito** [comment]
@stnguyen90 That's is a good approch , mariaDb will executes the fulltext operation before other conditions in the where

**Comment by tannermeade** [comment]
I ran into this issue when trying to query for documents with 4 attribute queries.

2 bool and 1 string attributes equals()
1 string fulltext

**Comment by stnguyen90** [comment]
Starting in 1.3.0, you won't need to create a full-text index on multiple attributes, so you shouldn't run into this issue anymore.
