### ISSUE TITLE
🐛 Bug Report: Can no longer validate token in order to reset user's password

### ISSUE THREAD

**Issue by badmark** [appwrite/appwrite#2999]
### 👟 Reproduction steps

Using this sample, setup a Password recovery workflow: https://dev.to/appwrite/30daysofappwrite-email-verification-and-forgot-password-420o

### 👍 Expected behavior

That the token is validated allowing the user to change their password

### 👎 Actual Behavior

An error from the server stating that the token is invalid.

```
[Error] Line: 2174

[Error] Timestamp: 2022-03-23T15:38:29+00:00

[Error] Method: PUT

[Error] URL: /v1/account/verification

[Error] Type: Appwrite\Extend\Exception

[Error] Message: Invalid verification token
```

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Docker on a single bare metal host.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Is this still a problem?

**Comment by badmark** [comment]
No, this was an issue because I was running an old version of the SDK which was hitting the wrong API URL (V1)
