### ISSUE TITLE
[Feature] - Set console port by parameter

### ISSUE THREAD

**Issue by eladcandroid** [appwrite/appwrite#3]
Now when port 80 is busy, there's an error and we need to set it manually on the docker-compose file..

**Comment by eldadfux** [comment]
Hi Elad, Thanks for the feedback, I will definitely make a priority to try and release this feature ASAP.

**Comment by eldadfux** [comment]
I am working on creating a simple generator in the Appwrite home page to help users generate a quick installation using their own custom docker-compose env vars.

In the new form I want to allow users to change the server port, encryption key, SMTP credentials and probably more things along the way.

The result of the form will be a simple one-line installation command which will pass query string params to the https://appwrite.test/docker-compose.yml file.

Another thing might worth changing is to make the docker-compose URL use POST request to avoid any sensitive data (like encryption key or SMTP password) being recorded to any kind of server or client logs.

**Comment by eldadfux** [comment]
Until the advanced setup generator will be ready, I have added an option to change the installation docker-compose.yml port by passing a query string param to the endpoint URL.

Example:
[https://appwrite.io/docker-compose.yml?port=2000](https://appwrite.io/docker-compose.yml?port=2000)

I have also added a section in the docs explaining hot to setup the server using a different port number.
