### ISSUE TITLE
🚀 Feature: App Template YAML Files

### ISSUE THREAD

**Issue by mrufsvold** [appwrite/appwrite#3002]
### 🔖 Feature description

Build the appwrite.json file from a YAML file that can serve as infrastructure-as-code. The build process would handle creating and destroying services in the presently deployed project to accurately reflect the YAML file. I'm of course thinking of [serverless](https://www.serverless.com/) here.

### 🎤 Pitch

Instead of interacting directly with the GUI or CLI interfaces to create services, it would be awesome to write a YAML file that outlines the functions, db document schemas, buckets, etc. and all of the various configurations for those services. Then have a deploy/build step that reads the YAML file, compares it to what is already deployed and then resolves the differences by deleting or creating services. 

The YAML file would be a very light wrapper around the existing appwrite.json structure. The biggest lift would be performing the diff and deciding what behaviors should happen to protect against inadvertent destruction of critical services.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Swinkid** [comment]
I like this idea. You can already do it some what with collections and functions (though, it would be nice if the vars would override, or a flag for it).. but it would be awesome to be able to extend this into all other areas like buckets, teams etc..

**Comment by mrufsvold** [comment]
I don't have the bandwidth right now to take this on, but I wanted to put it out there in case some else does. I'll have more mental space in the summer if it doesn't get picked up. 

I'm glad to hear you're on board, @Swinkid !

**Comment by stnguyen90** [comment]
Personally, I prefer YAML over JSON, but we already have the appwrite.json and I don't think it's worth it to introduce some YAML wrapper on the appwrite.json. 

As for some sort of diff, I don't think this issue is specific enough to be actionable. To improve the CLI, we will work on incrementally improving various aspects with smaller issues.

Would it be okay to close this issue while we work on our improvements?

**Comment by mrufsvold** [comment]
Hey, thanks for circling back on this! I think it's fine to close this. Thanks for pointing out appwrite.json!
