### ISSUE TITLE
🐛 Bug Report: Windows CLI install powershell script installs in wrong location

### ISSUE THREAD

**Issue by benjaminSchilling33** [appwrite/appwrite#3007]
### 👟 Reproduction steps

I raised the issue here, since https://github.com/appwrite/sdk-for-cli is marked as read only.

When I execute 

```
iwr -useb https://appwrite.io/cli/install.ps1 | iex
```

The appwrite CLI binary is stored in 
`%LOCALAPPDATA%`
instead of 
`%LOCALAPPDATA%/Appwrite/`
as desired in
`https://appwrite.io/cli/install.ps1` line 73.

### 👍 Expected behavior

Windows Appwrite CLI is correctly installed to %LOCALAPPDATA%/Appwrite/

### 👎 Actual Behavior

Windows Appwrite CLI is incorrectly installed to %LOCALAPPDATA%/

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Only relevant for Appwrite CLI installation on windows.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by benjaminSchilling33** [comment]
I already have a patch for this issue (see below).
Where should I post it?

```diff
diff --git a/install.ps1 b/install-fixed.ps1
index a1ccdf2..02b158c 100644
--- a/install.ps1
+++ b/install-fixed.ps1
@@ -16,11 +16,14 @@
 $GITHUB_x64_URL = "https://github.com/appwrite/sdk-for-cli/releases/download/0.15.0/appwrite-cli-win-x64.exe"
 $GITHUB_arm64_URL = "https://github.com/appwrite/sdk-for-cli/releases/download/0.15.0/appwrite-cli-win-arm64.exe"

+$APPWRITE_BINRARY_NAME = "appwrite.exe"
+
 # Appwrite download directory
-$APPWRITE_DOWNLOAD_DIR = Join-Path -Path $env:TEMP -ChildPath "appwrite.exe"
+$APPWRITE_DOWNLOAD_DIR = Join-Path -Path $env:TEMP -ChildPath "$APPWRITE_BINRARY_NAME"

 # Appwrite CLI location
 $APPWRITE_INSTALL_DIR = Join-Path -Path $env:LOCALAPPDATA -ChildPath "Appwrite"
+$APPWRITE_INSTALL_PATH = Join-Path -Path "$APPWRITE_INSTALL_DIR" -ChildPath "$APPWRITE_BINRARY_NAME"

 $USER_PATH_ENV_VAR = [Environment]::GetEnvironmentVariable("PATH", "User")

@@ -59,9 +62,9 @@ function DownloadBinary {
     else {
         Invoke-WebRequest -Uri $GITHUB_x64_URL -OutFile $APPWRITE_DOWNLOAD_DIR
     }
-

-    Move-Item $APPWRITE_DOWNLOAD_DIR $APPWRITE_INSTALL_DIR
+    New-Item -ItemType Directory -Path $APPWRITE_INSTALL_DIR
+    Move-Item $APPWRITE_DOWNLOAD_DIR $APPWRITE_INSTALL_PATH
 }

```

**Comment by christyjacob4** [comment]
@benjaminSchilling33 it would be awesome if you could create a PR for this in our SDK Generator
https://github.com/appwrite/sdk-generator/blob/master/templates/cli/install.ps1.twig

Thank you for reporting this

**Comment by benjaminSchilling33** [comment]
in progress
