### ISSUE TITLE
🐛 Bug Report: appwrite CLI init function ... ✗ Error ENOENT: no such file or directory

### ISSUE THREAD

**Issue by drmilde** [appwrite/appwrite#3009]
### 👟 Reproduction steps

When I try to call "appwrite init function" the script fails with the following error

✗ Error ENOENT: no such file or directory, open 'C:\Users\Android\appwrite\functions\dart\template\functions\fxx\README.md'

The function in Appwrite is created indeed, but the system fails to generate the template code (in my case dart code)

### 👍 Expected behavior

It should generate the dart template code.

### 👎 Actual Behavior

It created the function but no template code, which can later be deployed.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by namevisor** [comment]
I'm getting the same error.

**Comment by drmilde** [comment]
I think, it is an issue related to Windows.  My workaround: install a node image on docker, install appwrite, and generate the code. Works perfectly. 

Next issue: it doesn't build ... fixed this error by increasing the the swap function memory in .env

_APP_FUNCTIONS_MEMORY_SWAP=2048

Now everything is fine.

**Comment by christyjacob4** [comment]
@drmilde @namevisor 
Thanks for raising this. we are aware of this issue on windows and are working on a fix. 
Meanwhile, you can refer to this issue for a workaround 
https://github.com/appwrite/sdk-for-cli/issues/30

**Comment by anandsubbu007** [comment]
any update?

**Comment by Meldiron** [comment]
Addressed in PR: https://github.com/appwrite/sdk-generator/pull/406
