### ISSUE TITLE
Duplicate User Accounts

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#301]
Due to an error where my account creation fired twice at the same time, I was able to create two identical Accounts in my Appwrite project :)

Easy reproducible by just creating a user twice right after each other.

<img width="918" alt="Screenshot 2020-03-21 at 15 59 16" src="https://user-images.githubusercontent.com/1759475/77229240-f4826080-6b8c-11ea-9f09-4ffac2cbe046.png">

using 0.5.0

**Comment by eldadfux** [comment]
Is this happening for you only when sending both requests at the exact same time? is this OK when there is a delay between both?

**Comment by TorstenDittmann** [comment]
Fixed my bug right away that would fire the function twice. It was because in the register form I had the function in the form action and in the button click. So it got called twice without any delay. I can look into that and call it twice with delay!

**Comment by eldadfux** [comment]
That is still a bug that must be fixed at the API level as well, I just wanted to know about the delay issue to make sure I am seeing the same thing on my env.

**Comment by eldadfux** [comment]
This is fixed in 0.5.3. Please mind to run the upgrade script again after setting up the new Docker container version.
