### ISSUE TITLE
🐛 Bug Report: Significant performance impact with document level permissions

### ISSUE THREAD

**Issue by runionke** [appwrite/appwrite#3010]
### 👟 Reproduction steps

1. Create collection with document level permissions
2. Insert 100k? records with same team permission for each record.
3. query on indexed attribute.
4. compare with collection level permissions.

### 👍 Expected behavior

The ability to add team level permissions, without a breaking impact on performance.

### 👎 Actual Behavior

Query times out when set to document level permissions, but returns instantly when set to collection level.

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Can you please try the same test on the newer version? I believe we addressed this in 0.13.3.
Previously, permissions were an array column in attribute, making it pretty slow to look for specific permission.

Now, permissions are their own table that is properly indexed and should be way more performant.

Either way, from your example, I would suggest dynamically creating collections for teams (from Appwrite Function). This way you can keep collection-level permission and have the best performance possible.

**Comment by runionke** [comment]
Unfortunately I am unable to migrate and test on the newest version until issue: https://github.com/appwrite/appwrite/issues/2920 is resolved.

**Comment by runionke** [comment]
I can now confirm that the issue is fixed in 13.4.
