### ISSUE TITLE
🐛 Bug Report: Invalid email: Value must be a valid email address

### ISSUE THREAD

**Issue by AliGharian** [appwrite/appwrite#3015]
### 👟 Reproduction steps

when I want to make a new user the appwrite returns 400 bad request with this message: "Invalid email: Value must be a valid email address", the email that I pass is a valid email like example@gmail.com but it return above Error, I'm using Vscode as editor and try to connect my React app to appwrite.

### 👍 Expected behavior

should register user and make a new user in database.

### 👎 Actual Behavior

appwrite returns a 400 bad request "Invalid email: Value must be a valid email address"

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

editor: vscode
frontend: reactjs

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by AliGharian** [comment]
Oh sorry it was a mistake in my javascript code not from appwrite, it works well now.
I close this issue.

**Comment by tony83033** [comment]
@AliGharian  I am also getting the same error can you pls tell me how did you fix it pls

**Comment by AliGharian** [comment]
In this case, It was my mistake, just make sure you are passing the email address from the input form to the appwrite SDK properly.
Here is my code base for registering a user with reactjs, 
`const registerUser = () => {
        account.create('unique()', email, password, username)
            .then(res => {
                account.createSession(email, password)
                    .then(res1 => {
                        //Navigate to home page
                    }).catch(err => {
                        console.log("error in creating session", err)
                    })
            }).catch(err => {
                console.log("error in creating user", err)
            })
    }`

**Comment by Sstanley45** [comment]
I also faced the same error. Solved it by ensuring the credentials follow this order -  ({email , password, username}). In that order. 
I think the order matters.

**Comment by Jitenmohanty** [comment]
> I also faced the same error. Solved it by ensuring the credentials follow this order - ({email , password, username}). In that order. I think the order matters.

Yes the order was matter

**Comment by Sstanley45** [comment]
Thank you.

**Comment by Krijestorac** [comment]
> I done it in corrct error but still get this same error. Here is my code
> 
> export async function createUser(email, password, userName) { try {
> 
> ```
> const newAccount = await account.create(
>   ID.unique(),
>   email,
>   password,
>   userName
> );
> // .catch((error) => console.log(error));
> 
> console.log(newAccount);
> if (!newAccount) throw Error;
> 
> const avatarUrl = avatar.getInitials(userName);
> 
> await signIn(email, password);
> 
> const newUser = await databases.createDocument(
>   appwriteConfig.databaseId,
>   appwriteConfig.userCollectionId,
>   ID.unique(),
>   {
>     accountId: newAccount.$id,
>     email: email,
>     userName: userName,
>     avatar: avatarUrl,
>   }
> );
> return newUser;
> ```
> 
> } catch (error) { console.log(error); throw new Error(error); } }

I got the same error for the same code. Have you managed to solve it?
