### ISSUE TITLE
🐛 Bug Report: Appwrite Installation Script Issues on x86-based VPS

### ISSUE THREAD

**Issue by SebastianTDev** [appwrite/appwrite#3017]
### 👟 Reproduction steps

Installation of appwrite on a fresh Ubuntu 20.04 LTS 64bit or CentOS 7 64bit OS always fails using either the [Docker Script](https://appwrite.io/docs/installation#unix) or manual via [Docker Compose](https://appwrite.io/docs/installation#manual).

Tried a few clean OS installs + only installing docker as per the official guidelines, result is always the same.

### 👍 Expected behavior

Proper installation process / all containers up and running.

### 👎 Actual Behavior

Unfortunately the installation script runs on several errors, error messages below. Only a few containers are started, others fail to start up properly:

Under  CentOS 7 64bit:
https://pastebin.com/v5743Mv0

Under Ubuntu 20.04 LTS 64bit:
https://pastebin.com/vxCNAB7k

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Strato VPS - Linux V10
https://www.strato.de/server/linux-vserver/

Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
CPU vCores 4
RAM 8 GB
SSD 300 GB

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by phaus** [comment]
I don't know this specific strato setup, but there seem to be a strange thread limit per binary in place.
You might try to increase the limit for docker:

https://www.strato.de/faq/server/prozesse-vs-threads-bei-linux-v-servern/

Otherwise switch to another provider. 

I am using the smallest hetzner cloud tier without any problems (had to disable clamav for performance reasons though)

**Comment by Meldiron** [comment]
Can you please try Phaus suggestion of increasing the limit for Docker? Did it solve problem for you?

**Comment by SebastianTDev** [comment]
Hey both,

thank you very much for your input. The VPS with Strato was limited to 400 Threads max, which was not enough to run Appwrite.
I just changed my provider today to another VPS Provider in Germany (less power, more expensive - but without the weird numproc limitation) and now its working like a charm first try.

So for me this problem is solved,
Thank you very much for your support.
