### ISSUE TITLE
🐛 Bug Report: Function compiles and executes successfully despite code that doesn't compile. 

### ISSUE THREAD

**Issue by Radther** [appwrite/appwrite#3019]
### 👟 Reproduction steps

Create a new Swift function that has a single `.swift` file with the following code:
```swift
func main(req: RequestValue, res: RequestResponse) throws -> RequestResponse {
    return res.json(data: {"hello": "world"})
}
```

This shouldn't work as Swift dictionaries use `[]` not `{}` as shown in the code above. 

### 👍 Expected behavior

This should fail to deploy the function. 

### 👎 Actual Behavior

It deploys and successfully executes the function. 

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Added the swift runtime to the functions available. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Adding note from Discord:

> Interestingly the logs also complain about importing PackageDescription in the package.swift file.

**Comment by christyjacob4** [comment]
@abnegate please take a look here

**Comment by abnegate** [comment]
Please check using the latest version and re-open if the issue persists
