### ISSUE TITLE
🐛 Bug Report: Storage Size Limit Error 

### ISSUE THREAD

**Issue by rlee1990** [appwrite/appwrite#3036]
### 👟 Reproduction steps

Add a file larger than the storage limit size.
I am using flutter.

### 👍 Expected behavior

An error should be sent back to the client with a proper error.

### 👎 Actual Behavior

I just receive the below error:
`AppwriteException: general_server_error, Server Error (500)`
The on appwriteexception does not even get called.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

None

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
@lohanidamodar Can you take this one? It's flutter-related.

**Comment by lohanidamodar** [comment]
@rlee1990 there might be other errors that causing the 500 error. Can you check docker console logs for appwrite?
by running `docker-compose logs appwrite` right after you make a request to upload a large file,  from your terminal where appwrite is installed. You will be able to see the actual error on the console and that will help us figure out the issue

**Comment by rlee1990** [comment]
@lohanidamodar I did this was the issue. I even have the information in the storage discord channel. Was raising this issue so it could be looked into.

**Comment by lohanidamodar** [comment]
@rlee1990 Thanks, that does make sense, when your `_APP_STORAGE_LIMIT` is less than your **Bucket File Size limit**, you do get 500. We will explore more what error code and status might make sense here, without exposing much information to the client. Thank you for the issue.

**Comment by rlee1990** [comment]
@lohanidamodar Let me test that later today and I will let you know.

**Comment by stnguyen90** [comment]
@rlee1990, is this still a problem or can it be closed now?
