### ISSUE TITLE
🚀 Feature: Clean up executions

### ISSUE THREAD

**Issue by JakeAi** [appwrite/appwrite#3042]
### 🔖 Feature description

Create an endpoint / internal functionality to clean up executions. Currently there is no way to purge old executions. If the execution stdout gets increased to 1mb, I think it would be a good idea to purge these.

### 🎤 Pitch

Above

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
We do have a maintenance task in place to ensure this logic.

First, there is a loop that runs every 1 day (by default), configured by environment variable `_APP_MAINTENANCE_INTERVAL` in `.env`.

This loop initializes a task using yet another variable, `_APP_MAINTENANCE_RETENTION_EXECUTION`, defaults at 14 days. The task then checks all executions and deletes ones that are over the time of retention.

Both of these variables can be changed in case you need a different behaviour.

---

Refferences:
Maintanance task: https://github.com/appwrite/appwrite/blob/master/app/tasks/maintenance.php#L68
Delete executions after retention job: https://github.com/appwrite/appwrite/blob/master/app/workers/deletes.php#L240-L249

**Comment by JakeAi** [comment]
> 



> We do have a maintenance task in place to ensure this logic.
> 
> First, there is a loop that runs every 1 day (by default), configured by environment variable `_APP_MAINTENANCE_INTERVAL` in `.env`.
> 
> This loop initializes a task using yet another variable, `_APP_MAINTENANCE_RETENTION_EXECUTION`, defaults at 14 days. The task then checks all executions and deletes ones that are over the time of retention.
> 
> Both of these variables can be changed in case you need a different behaviour.
> 
> Refferences: Maintanance task: https://github.com/appwrite/appwrite/blob/master/app/tasks/maintenance.php#L68 Delete executions after retention job: https://github.com/appwrite/appwrite/blob/master/app/workers/deletes.php#L240-L249

Good to know! :)
