### ISSUE TITLE
🚀 Feature: Admin UI plugins 

### ISSUE THREAD

**Issue by vasani-arpit** [appwrite/appwrite#3045]
### 🔖 Feature description

![image](https://user-images.githubusercontent.com/6497827/161035996-cf36696f-b554-4457-ba89-0fc991cc8816.png)

### Custom features on admin side 

You can call it extensions or plugins. at certain point, just like every other IT projects code scalability will be an issue. Instead of writing all the integrations in our natively we should expose some APIs which allows developer to extend feature of appwite admin side in their own language (this might be far fetched but it is possible. Not all developers knows PHP 🤷‍♂️)

### 🎤 Pitch

I have been looking into [directus](directus.io) and [strapi](https://strapi.io/) lately. both are low-code(kinda) backend tools where you can define your DB schema and after that all rest of the things are already laid out for you like SDK, REST API, Graph API and admin interface for CRUD operation. 

I think it would be nice if appwrite will also have this feature. after all these platforms are solving same kind of problem as appwrite. 

### What this could be for users

- Users(developers) can create their own custom pages which can help them show the available data in a nice way instead of looking into each collections. 
- There could be some use case where agent will manually view the profile of the user and approves it. in this case developer can create custom UI right inside the app write which will remove the hassle of making their own entire backend UI
- Custom endpoints, developers might want to add custom endpoint which will fetch the data from several sources along with appwrite db and serve it as response

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
I saw a similar (more security-oriented) issue, talking about giving specific permissions to Console Users. In that scenario, the exact opposite was needed - to hide specific tabs of specific services from some users.

I am not sure if I like either one of these, as Appwrite is a developer tool at its core. Compared to Directus or Strapi, they are CMS systems at their core, which means, tools for humans (editors) to interact with data developers use. If we look deeper at these products, we should also implement custom attribute types (for custom input designs), add visual relations between collections, or allow custom components, such as a map picker. All of these features are great for CMS, but in my opinion not required for developer tools.

A few months ago I worked on a project to address such a problem, [Appwrite CMS](https://github.com/meldiron/appwrite-cms). (unofficial project, just free-time thingy)
The idea was to build a CMS (website) that under the hood uses ServerSDK, and can easily show, manipulate and delete data from Appwrite content - database. In such a project, your idea of custom websites (modules) would make sense.

---

What do you think after reading my comment? I would love to hear more feedback.

**Comment by vasani-arpit** [comment]
That actually makes sense. I might have chosen wrong examples to convey my point. 
The core point which I want to convey is appwrite should have some mechanism for developers which can extend appwrite without fiddling with appwrite's internal code. 

Small things like combining two collections into one, middleware to modify endpoint responses before sending it to front-end/SDK, server side validations etc...

I am sorry if some of these feature is already available in the code. I just checked the appwrite version which I am using and it looks like I haven't updated since 0.9

**Comment by Meldiron** [comment]
All of that should be possible using Appwrite Functions, which got even more powerful and faster with 0.13.
We are working on improving event system for triggering functions automatically.

What I can see here as a cool idea is to pre-insert/pre-update event for server-side validation before applying change on a document. Its currently possible to do it after, and revert changes, but response to user is not as informative as it would be with pre-update event.

**Comment by eldadfux** [comment]
Most of the stuff mentioned here as @Meldiron mentioned are available using the Appwrite Database or Appwrite Functions. As Appwrite is a backend and designed for developers and not content editors we avoid implementing content specific features directly in Appwrite. We did add new role based accessed to make the Appwrite console more suitable for content editors, but we do recommend building your own custom dashboard where the Appwrite Console is no longer a perfect fit.
