### ISSUE TITLE
🚀 Feature: API user endpoint to get list of memberships

### ISSUE THREAD

**Issue by outrelouxhe** [appwrite/appwrite#3046]
### 🔖 Feature description

An API endpoint to get a list of memberships for a user. 

### 🎤 Pitch

 At the moment, I need to get all teams and check for each one of them if the user is present in the memberships. This becomes an issue when the number of teams becomes large.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
As far as I am concerned, this is not possible 🤔 @christyjacob4 @TorstenDittmann @eldadfux should we implement this? Sounds reasonable to me.

**Comment by rafaelgazani** [comment]
@outrelouxhe I'm thinking of triggering a function to feed a collection that has the user id, team id or association id. How did you resolve?

**Comment by TorstenDittmann** [comment]
I am not a 100% sure it makes sense to get all memberships, without the context of the team itself 🤔

**Comment by outrelouxhe** [comment]
It makes sense for use cases where users, teams and team memberships are managed by a remote server through server api. At the moment I deal with a few hundreds of users but with thousands of teams which are used to filter the data within collections based on different categories : accessible customers, accessible geographic zones...   In order to avoid scanning all teams to get the memberships of a given user, it would be a lot easier to just get a list of team memberships for one user. This is more a user centric approach than a team centric approach like you're referring to, because the starting point is the user, not the team. Does it make sense to you ? Thank you.

**Comment by outrelouxhe** [comment]
Thank you @rafaelgazani for sharing your solution which could also work for my use case.
However, I really hope that this feature request will be accepted because I would like to avoid to add and maintain a collection when everything is already present in the internal database and could be retrieved with a new API endpoint.

**Comment by rafaelgazani** [comment]
I also hope @outrelouxhe . If this endpoint comes out in a future release, it will be easy to replace my solution.

**Comment by christyjacob4** [comment]
@outrelouxhe , this looks reasonable and looks like you have a valid use case. But I'm going to have to wait with the decision of implementing it until we have more consensus

**Comment by eldadfux** [comment]
I think it makes sense. From the client API you can only fetch the teams the user has access to, but from the server you will get ALL the teams. I think adding this feature works well with the product philosophy, enabling Appwrite for both client and servers. I think we can start by adding a new server route `/v1/users/[USER_ID]/memberships`.

**Comment by Cowtail1** [comment]
#3211

**Comment by TorstenDittmann** [comment]
Btw this should be available with the latest release of 0.14 👌
