### ISSUE TITLE
🚀 Feature: Database export/import option on a project

### ISSUE THREAD

**Issue by lexxyungcarter** [appwrite/appwrite#3050]
### 🔖 Feature description

A simple way of importing and exporting a project's database, or even the entire database straight from the UI (without having to ssh into the server every time). 

### 🎤 Pitch

Sometimes, or most times, one would want a quick way of dumping a project's database (or even all projects) without having to ssh intoo a server. Other times I'd like to import my database from the test environment to the production environment for a fresh project, without having to re-create all attributes and any other data I may have (e.g. enums, supporting tables, e.t.c).

It would be a really nice feature if there cuold be such an ability to have in appwrite. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
If you're referring to being able to quickly create collections, the Appwrite CLI can solve that. 

For actual data, a community member has started to tackle this with https://github.com/tannermeade/data-migrator

**Comment by stnguyen90** [comment]
@lexxyungcarter, can this be closed now?

**Comment by tripolskypetr** [comment]
This feature is a blocker for a stable release of appwrite cloud service. Without json data export I am definitely going to use supabase.

P.S. [data-migrator](https://github.com/tannermeade/data-migrator) is pre-alpha and It will corrupt your data

**Comment by brudex** [comment]
This is a very important feature lacking you should be able to export data from a staging environment of appwrite to a production environment

**Comment by tripolskypetr** [comment]
If someone is building CI/CD for their AppWrite applications, [this tool will be quite useful](https://github.com/react-declarative/appwrite-backup-tool). It is a set of scripts which will help you automatically deploy `appwrite.json` schema to Docker container and reupload all buckets and databases
