### ISSUE TITLE
Create collection and attributes then create document produces error

### ISSUE THREAD

**Issue by patrickclark1964** [appwrite/appwrite#3052]
See also #3049 which is a related issue

**Issue:**
This issue was identified using Dart sdk, unsure about other sdk's.

Creating a collection and attributes then immediately adding a document produces error.
`AppwriteException: document_invalid_structure, Invalid document structure: Unknown attribute: "<attribute>" (400)`

Forcing a delay after creation allows the code to run as expected.

**Expected behaviour**

When a collection/attribute is created with the Dart sdk using await, the call should not return until the operation is complete.

**Steps to reproduce:**
```
        final collection= await _appwrite.svrDatabase.createCollection(
          collectionId: 'unique()',
          name: 'Title',
          permission: 'collection',
          read: ['role:all'],
          write: ['role:all'],
        );

        await _appwrite.svrDatabase.createStringAttribute(collectionId: collection.$id, key: 'title', size: 50, xrequired: true);

        await _appwrite.svrDatabase.createDocument(
          collectionId: collection.$id,
          documentId: 'unique()',
          data: {
            'title': 'Title',
          },
        );
```

If I add await `Future.delayed(const Duration(milliseconds: 500));` after the attribute creation it works.

**Comment by Meldiron** [comment]
Hey there 👋
This is server-related behaviour, so all SDKs would share the same results. We encountered this when writing Appwrite CLI, there we set up attributes, and indexes for them right after.

To explain the problem, even tho you `await` attribute creation, you are only awaiting an HTTP response. The response is sent as soon as a job for workers is scheduled. This means even tho you have the response, a worker might not have been quick enough to do the work. Imagine a huge database, adding attributes could take seconds, if not minutes to affect all of the rows.

A solution is to write a logic to check attribute status from time to time (like every second), and if the status changes to available, then you can start creating indexes (or documents).

You can see an example of such logic in the source code of our CLI: 
Definition: https://github.com/appwrite/sdk-for-cli/blob/master/lib/commands/deploy.js#L67-L97
Usage: https://github.com/appwrite/sdk-for-cli/blob/master/lib/commands/deploy.js#L386-L391

**Comment by patrickclark1964** [comment]
Thank you  @Meldiron, 

I understood the cause but didn't know how to work around it. 

Obviously my delay might not always work.

Thanks for the code example, it helps greatly.

**Comment by stnguyen90** [comment]
Closing as no further action required

**Comment by akashgreninja** [comment]
I got this error today and i came to know that we have to compulsory create an attribute before we have to add a document with the attribute name same as that of the key in the object we pass as data

**Comment by fsmdeveloper** [comment]
> I got this error today and i came to know that we have to compulsory create an attribute before we have to add a document with the attribute name same as that of the key in the object we pass as data

Bro your comment fixed my issues!! I was facing the same issues!!
