### ISSUE TITLE
🐛 Bug Report: 'Add Index' modal cant see new attributes

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#3058]
### 👟 Reproduction steps

1. Create collection (col1)
2. Create string attribute (a1), and wait for it to be `available`
3. Create integer attribute (a2), and wait for it to be `available`
4. Click `indexes` tab
5. Add index, and open attributes dropdown

![CleanShot 2022-04-04 at 13 26 06](https://user-images.githubusercontent.com/19310830/161534735-33bb16ac-b105-4c87-b668-f2a220888659.png)

### 👍 Expected behavior

See both a1 and a2 attributes, as both are available

### 👎 Actual Behavior

Can only see a1. a2 is missing, even tho it's as ready as a1. Refreshing websites fix the issue.

Looks like realtime update does not apply new status into state that controls dropdown options.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Gitpod

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

---

To follow-up on the issue, if an attribute fails, you can still see it in the dropdown when creating an index. Could be an easy-fix.

**Comment by stnguyen90** [comment]
This should be resolved as part of the new Console.
