### ISSUE TITLE
Too many request on localhost at account.create

### ISSUE THREAD

**Issue by j2l** [appwrite/appwrite#3059]
### 👟 Reproduction steps

1. add a appwrite server
2. create a frontend
3. learn slowly like me: testing each possible error at user creation (same user, wrong password length, no symbol, not an email, ...)
4. reach `Too many request` in your error message

### 👍 Expected behavior

expose the limit per 60' to tweak, reset it.

And at least show that 10 was achieved somewhere, overall I only created 3 users:
![image](https://user-images.githubusercontent.com/65325/161540032-38e871af-257f-4f61-a67d-d13a863a8069.png)
BTW, it should deduct deleted users :smile: 

### 👎 Actual Behavior

`AppwriteException: Too many requests`
no logs in container or backend UI to know how long I should wait.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Nothing special

I've read https://github.com/appwrite/appwrite/issues/1085 about testing password trial abuse
but happening at user creation was a surprise.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey there 👋 The limit you are hitting is abuse control which is a part of our security layer at multiple endpoints, one of them is creating an account. As all other rate-limited endpoints require a logged-in user, it also makes sense to rate-limit account creation to finalise the loop.

In development what you can do is switch the environment variable in your `.env` to `_APP_OPTIONS_ABUSE=disabled`. This will disable all abuse limit checks, and you will be allowed to fire as many requests as you want. You can keep this disabled on a development server, but we highly recommend keeping it enabled on production.

To answer concerns about why the number doesn't add up with what you see in the dashboard: All requests are abuse-limited, even those with invalid payload.

**Comment by j2l** [comment]
Makes sense.
Thank you very much @Meldiron !
