### ISSUE TITLE
[DISCUSSION] Code Examples Font

### ISSUE THREAD

**Issue by shivansh54kol** [appwrite/appwrite#306]
The container/div containing the code in the documentation has its font very different from what programmers are used to. You guys can change it to something different like "Consolas" or "Ubuntu Mono".

**Comment by eldadfux** [comment]
Would be great to get more font suggestions, so we'll be able to pick the best font that also matches the Appwrite brand design, look and feel.

Please note, that we'll only use an open-sourced font.

**Comment by TorstenDittmann** [comment]
Might be a bit overkill:
https://www.jetbrains.com/lp/mono/

But fits all the requirements :)

**Comment by eldadfux** [comment]
Used the open-source 'Source Code Pro' font:
![image](https://user-images.githubusercontent.com/1297371/80509423-120fca80-8982-11ea-8777-d53d3aaee41d.png)


https://fonts.google.com/specimen/Source+Code+Pro

**Comment by eldadfux** [comment]
Does it look better?

**Comment by eldadfux** [comment]
Deployed on the latest version of appwrite.io
