### ISSUE TITLE
🐛 Bug Report: Appwrite Functions - Python 3.9 Runtime - response.send is not working properly when using a custom status code

### ISSUE THREAD

**Issue by SebastianTDev** [appwrite/appwrite#3064]
### 👟 Reproduction steps

When using the Python 3.9 runtime to run a function try to add a status code (as described [here](https://appwrite.io/docs/functions#writingYourOwnFunction)) to the send function (e.g. 400).
`return response.send("Your Error Message", 400)`

### 👍 Expected behavior

Properly sending the error message and the status code to the client.

### 👎 Actual Behavior

Error Log will return something like this:
```
Traceback (most recent call last):
File "/usr/local/src/server.py", line 64, in handler
    return userModule.main(req, resp);
File "/usr/local/src/userlib/function.py", line 46, in main
    return response.send("Document does not exist", 400)
TypeError: send() takes 2 positional arguments but 3 were given
```

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Addressed issue in a PR. Looks like our Python implementation was inconsistent with the rest of the runtimes we support. With changes from PR, status should be accepted and `return` should not be required.
