### ISSUE TITLE
🚀 Feature: Router for functions

### ISSUE THREAD

**Issue by watzon** [appwrite/appwrite#3069]
### 🔖 Feature description

Similar to the HTTP API from AWS, it would be nice to have a way to make functions accessible from the outside world (without using the appwrite API). This could potentially include the ability to assign a function to a specific route (using DNS), apply rate limits, and utilize the built in user management for authentication.

### 🎤 Pitch

I would like to build out a public facing API on top of appwrite using functions. I know I could build out an external service to do this and just route requests to a given function, but this approach has added latency.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Shadowfita** [comment]
Have you seen this add-on? 

https://github.com/Meldiron/appwrite-webhook-proxy/tree/master/appwrite-function

I had a similar desire and stumbled upon this, which allows you to achieve what you've layed out. It's allowed me to utilise webhooks from other services and a function as a middle-man.

**Comment by christyjacob4** [comment]
@watzon Thank you for creating this. We have been thinking about something similar but will take some time for us to get there.

**Comment by stnguyen90** [comment]
FYI, this is planned for the next version of Appwrite. See https://github.com/appwrite/appwrite/discussions/5016.

**Comment by stnguyen90** [comment]
Closing as this is now available since Appwrite 1.4.
