### ISSUE TITLE
🚀 Feature: Functions KeepAlive

### ISSUE THREAD

**Issue by talshimoni** [appwrite/appwrite#3072]
### 🔖 Feature description

add an option to set important functions with keepalive (executor don't remove the container when it is not used to allow fast execution)

right now I am using corn job, the function returns true if the source is scheduled since there is no other solution

### 🎤 Pitch

Creating a container can take time and the clients wait a long time on the main page on the init time until the container started, 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
You can configure it using the `_APP_FUNCTIONS_INACTIVE_THRESHOLD` env variable.

https://appwrite.io/docs/environment-variables#functions

**Comment by talshimoni** [comment]
how can i set _APP_FUNCTIONS_INACTIVE_THRESHOLD to never for some functions,
I recommend to allow set option like this per function and global if it is not set
