### ISSUE TITLE
🚀 Feature: Custom host for Executor service.

### ISSUE THREAD

**Issue by sjke** [appwrite/appwrite#3077]
### 🔖 Feature description

For flexible infrastructure configuration, I propose to add the ability to configure a custom host for the Executor service.

### 🎤 Pitch

Issue: At the moment, there is no way to deploy the service on a separate machine at all

Personal pain: When deploying the infrastructure, I ran into the "issue" with the host for the Executor service, which does not allow me to use custom names for the container (the same problem can occur we have when trying to deploy the infrastructure through docker swarm)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
Hey :)

That is actually a good point you are making!

This will probably be solved when we are introducing a way of scaling functions, since as of right now there can only be a single container per function.
