### ISSUE TITLE
🐛 Bug Report: Functions executed by HTTP request don't store metrics

### ISSUE THREAD

**Issue by Shadowfita** [appwrite/appwrite#3078]
### 👟 Reproduction steps

Execute a function via http requests.

![image](https://user-images.githubusercontent.com/11067520/162655374-b1717bf4-c42e-4b2c-a896-0b335a71814a.png)

### 👍 Expected behavior

Record it's executions and CPU time in the monitor tab as expected

### 👎 Actual Behavior

Doesn't store any metrics

![image](https://user-images.githubusercontent.com/11067520/162655423-6a568507-8cfd-4a87-becc-7dec0d913a10.png)

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
Can you share the logs of the usage worker ? 

`docker-compose logs -g appwrite-worker-usage`

**Comment by Shadowfita** [comment]
> Can you share the logs of the usage worker ?
> 
> `docker-compose logs -g appwrite-worker-usage`

I don't receive any output when including the "-g" option. Just FYI, the metrics are stored correctly if run by an event, or through the console manually.

Thanks.

**Comment by christyjacob4** [comment]
@Shadowfita so sorry I meant 
`docker-compose logs -f appwrite-worker-usage`

The usage worker captures and stores the usage data in the database so it should have some clues to what might be going wrong.

**Comment by Shadowfita** [comment]
@christyjacob4 thanks for your help with this.

Logs from execution times recently, and a repeated error that I've noticed:

`appwrite-usage                  | [34m[17-04-2022 10:30:33] Aggregating usage data every 30 seconds[0m
appwrite-usage                  | [34m[17-04-2022 10:30:33] Aggregation took 0.0919508934021 seconds[0m
appwrite-usage                  | [34m[17-04-2022 10:31:03] Aggregating usage data every 30 seconds[0m
appwrite-usage                  | [34m[17-04-2022 10:31:03] Aggregating database counters.[0m
appwrite-usage                  | [PDO] MySQL connection restarted
appwrite-usage                  | [1;33mFailed to save database counters data for project collections: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._6242e1a3eb20bd0b0e7d_collection_6242e1f68074c39eb08d' doesn't exist[0m
appwrite-usage                  | [1;33m#0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
appwrite-usage                  | #1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(895): Appwrite\Extend\PDOStatement->execute()
appwrite-usage                  | #2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(998): Utopia\Database\Adapter\MariaDB->count('collection_6242...', Array, 0)
appwrite-usage                  | #3 /usr/src/code/app/tasks/usage.php(568): Utopia\Database\Database->count('collection_6242...')
appwrite-usage                  | #4 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(203): {closure}()
appwrite-usage                  | #5 /usr/src/code/app/tasks/usage.php(771): Utopia\CLI\Console::loop(Object(Closure), 30)
appwrite-usage                  | #6 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()
appwrite-usage                  | #7 /usr/src/code/app/cli.php(28): Utopia\CLI\CLI->run()
appwrite-usage                  | #8 {main}[0m
appwrite-usage                  | [PDO] MySQL connection restarted
appwrite-usage                  | [1;33mFailed to save database counters data for project buckets: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._6242e1a3eb20bd0b0e7d_bucket_6242e1b6988438ac6e64' doesn't exist[0m
appwrite-usage                  | [1;33m#0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
appwrite-usage                  | #1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(895): Appwrite\Extend\PDOStatement->execute()
appwrite-usage                  | #2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(998): Utopia\Database\Adapter\MariaDB->count('bucket_6242e1b6...', Array, 0)
appwrite-usage                  | #3 /usr/src/code/app/tasks/usage.php(568): Utopia\Database\Database->count('bucket_6242e1b6...')
appwrite-usage                  | #4 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(203): {closure}()
appwrite-usage                  | #5 /usr/src/code/app/tasks/usage.php(771): Utopia\CLI\Console::loop(Object(Closure), 30)
appwrite-usage                  | #6 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()
appwrite-usage                  | #7 /usr/src/code/app/cli.php(28): Utopia\CLI\CLI->run()
appwrite-usage                  | #8 {main}[0m
appwrite-usage                  | [PDO] MySQL connection restarted
appwrite-usage                  | [1;33mFailed to save database counters data for project collections: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._62440d45b672be648df9_collection_6244764101e9f6d841de' doesn't exist[0m
appwrite-usage                  | [1;33m#0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
appwrite-usage                  | #1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(895): Appwrite\Extend\PDOStatement->execute()
appwrite-usage                  | #2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(998): Utopia\Database\Adapter\MariaDB->count('collection_6244...', Array, 0)
appwrite-usage                  | #3 /usr/src/code/app/tasks/usage.php(568): Utopia\Database\Database->count('collection_6244...')
appwrite-usage                  | #4 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(203): {closure}()
appwrite-usage                  | #5 /usr/src/code/app/tasks/usage.php(771): Utopia\CLI\Console::loop(Object(Closure), 30)
appwrite-usage                  | #6 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()
appwrite-usage                  | #7 /usr/src/code/app/cli.php(28): Utopia\CLI\CLI->run()
appwrite-usage                  | #8 {main}[0m
appwrite-usage                  | [PDO] MySQL connection restarted
appwrite-usage                  | [1;33mFailed to save database counters data for project buckets: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._62440d45b672be648df9_bucket_6246841484d26490615e' doesn't exist[0m
appwrite-usage                  | [1;33m#0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
appwrite-usage                  | #1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(895): Appwrite\Extend\PDOStatement->execute()
appwrite-usage                  | #2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(998): Utopia\Database\Adapter\MariaDB->count('bucket_62468414...', Array, 0)
appwrite-usage                  | #3 /usr/src/code/app/tasks/usage.php(568): Utopia\Database\Database->count('bucket_62468414...')
appwrite-usage                  | #4 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(203): {closure}()
appwrite-usage                  | #5 /usr/src/code/app/tasks/usage.php(771): Utopia\CLI\Console::loop(Object(Closure), 30)
appwrite-usage                  | #6 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()
appwrite-usage                  | #7 /usr/src/code/app/cli.php(28): Utopia\CLI\CLI->run()
appwrite-usage                  | #8 {main}[0m
appwrite-usage                  | [34m[17-04-2022 10:31:04] Aggregation took 0.14938497543335 seconds[0m
appwrite-usage                  | [34m[17-04-2022 10:31:34] Aggregating usage data every 30 seconds[0m
appwrite-usage                  | [34m[17-04-2022 10:31:34] Aggregation took 0.091359853744507 seconds[0m`

This is being executed synchronously,
