### ISSUE TITLE
API health check endpoint

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#308]
What would you think about adding an API endpoint for a health check?

The API endpoint `/health`could perform various checks such as:
- The status of the connection to Database, Storage, Redis and Influx
- The status of hosting machine’s disk storage
- ...

This can be handy to monitor the API uptime & status.

**Comment by eldadfux** [comment]
😮We actually have an Health API! It's just not documented or available from the SDKs yet.

Let's make it public for 0.6 🎉

@TorstenDittmann do you think we should add it to the docs as well?

You can check available methods from the source code:
https://github.com/appwrite/appwrite/blob/master/app/controllers/api/health.php

let me know what you think...

**Comment by TorstenDittmann** [comment]
Well looks good to me 👍

**Comment by eldadfux** [comment]
Ready to use: https://appwrite.io/docs/server/health 🎉
