### ISSUE TITLE
🐛 Bug Report: HTTPS Session Cookie only lasts for browser session

### ISSUE THREAD

**Issue by TheMardy** [appwrite/appwrite#3080]
### 👟 Reproduction steps

This issue is not present when using localhost, as it uses LocalStorage as fallback for the session.

On a production environment: 
- Client is https
- Appwrite using production and force https
- Client is beta.dev.domain.com
- Appwrite is dev.domain.com 

Authenticate a user using `sdk.account.createSession(email, password)`

### 👍 Expected behavior

I would expect the header to contain the expires parameter so that the cookie persists for the session length (a year).

This used to work in 0.11 and earlier, but stopped working since 0.12.

### 👎 Actual Behavior

Two set-cookie header are returned, but they do not contain the expires parameter:
`set-cookie: a_session_{SESSIONID}_legacy={SESSION}; path=/; domain=.dev.domain.com; secure; httponly`
`set-cookie: a_session_{SESSIONID={SESSION}; path=/; domain=.dev.domain.com; secure; httponly; samesite=None`

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
@TheMardy Thanks for raising this, we'll look into this.

**Comment by Meldiron** [comment]
PR created to resolve address this issue: https://github.com/utopia-php/framework/pull/55

**Comment by eldadfux** [comment]
This feature is now released and available as part of Appwrite 0.14. More on the new release here: https://github.com/appwrite/appwrite/discussions/3240
