### ISSUE TITLE
🐛 Bug Report: getFlag aspect ratio / wrong rendering

### ISSUE THREAD

**Issue by XeroxDev** [appwrite/appwrite#3082]
### 👟 Reproduction steps

I used the `/v1/avatars/flags/` endpoint and got not expected results. See results below:

### 👍 Expected behavior

Return the right aspect ratio of the flag like in the files itself (https://github.com/appwrite/appwrite/blob/master/app/config/avatars/flags/de.png)

How to fix it: calculate the right (missing) width / height, especially because they're optional.

### 👎 Actual Behavior

`/v1/avatars/flags/de`
![image](https://user-images.githubusercontent.com/10864620/162791065-32a0a670-5d9d-43eb-b4ba-00f5f710c169.png)

`/v1/avatars/flags/de?height=25`
![image](https://user-images.githubusercontent.com/10864620/162791166-f19c2ab5-4d52-4942-8913-cc2fb3e015a4.png)

`/v1/avatars/flags/de?width=50`
![image](https://user-images.githubusercontent.com/10864620/162791246-d4109052-9d90-4295-99d6-110196c9045e.png)

`/v1/avatars/flags/de?width=200`
![image](https://user-images.githubusercontent.com/10864620/162791315-28492402-7588-4193-9e16-83d4744e8cf8.png)

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use nginx as a reverse proxy.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
@XeroxDev  thanks for raising this issue. 
@Meldiron Please take a look at the image library

**Comment by Meldiron** [comment]
Issue resolved with PR mentioned above.

**Comment by eldadfux** [comment]
Actually this is the expected behavior. By default, the API crop the image and both default values for width and height are set to 100. To get the automatically calculate relative value, you just need to set `0` for one of the params.

**Comment by XeroxDev** [comment]
> Actually this is the expected behavior. By default, the API crop the image and both default values for width and height are set to 100. To get the automatically calculate relative value, you just need to set `0` for one of the params.

Interesting, thanks. That works! But I'm curious, shouldn't this be the default behavior?

**Comment by eldadfux** [comment]
If we set both values to 0, you will get the original images size by default which in most cases is far from the optimized resolution for your app or website. By setting the default to 100x100 we make developers aware of this feature to better use it and have better performance.

**Comment by XeroxDev** [comment]
> If we set both values to 0, you will get the original images size by default which in most cases is far from the optimized resolution for your app or website. By setting the default to 100x100 we make developers aware of this feature to better use it and have better performance.

Wouldn't it be better to just set the height to 100 as default and width to 0?

**Comment by eldadfux** [comment]
That said, @Meldiron is updating the docs to make it more clear.

**Comment by XeroxDev** [comment]
Okay. That's a good idea.

**Comment by eldadfux** [comment]
This feature is now released and available as part of Appwrite 0.14. More on the new release here: https://github.com/appwrite/appwrite/discussions/3240
