### ISSUE TITLE
Multitenancy?

### ISSUE THREAD

**Issue by cweagans** [appwrite/appwrite#309]
Does appwrite support multitenancy? I don't see anything about it on the website, but if it does, it's pretty much the perfect platform for my needs.

If it does not support multitenancy, are there plans to do so?

**Comment by cweagans** [comment]
Actually, it looks like it does -- I can just create new projects for each app I want to work on. This could probably be explicitly called out in the documentation. I only noticed it in the screenshots.

**Comment by eldadfux** [comment]
Hey, @cweagans. Appwrite does support multitenancy. You can create an unlimited number of multiple projects and apps and invite any number of team members to manage your project from a single Appwrite setup.

This does seem to be missing from the docs, where would you expect to find such information? Where do you think would be the best place to add this to the docs?

**Comment by cweagans** [comment]
I'd put it front and center on the home page with the other features under "Power, Security, and Flexibility". I was looking at the appwrite stack thinking "man, all of this for one app? maybe i should just write my own backend".

**Comment by eldadfux** [comment]
This is definitely something we can improve on our homepage.
Please feel welcome to join our Discord community if you have more feedback or in need of support: https://discord.gg/GSeTUeA

**Comment by monlasan** [comment]
We had custom backend implementation of multitenancy at a company I worked at (we use laravel). The prospect who wants to buy our SaaS product pay and an account is created. The generation of the database is done programmatically, no manual project/database creation (impliying support intervention). He just buy a license and get the link for his paid instance. My question is, wouldn't it be nice if we could programmatically create appwrite projects, or databases and their base schema ? I'm a frontend dev, maybe I don't really understand the architecturals concerns and implementations. What do you think about that?
