### ISSUE TITLE
🚀 Feature: Can you please implement support for Wasabi cloud Storage https://wasabi.com/

### ISSUE THREAD

**Issue by vijedich** [appwrite/appwrite#3098]
### 🔖 Feature description

Wasabi offers S3 compatible Cloud Storage for a reasonable price and for most use cases their pricing model works like a flatrate.
https://wasabi.com/

### 🎤 Pitch

If you are working with S3 you may have an advantage if your project is in the beginning stages. So there is not much traffic and costs for storage are quite low. But if the project ever scales up you may find yourself in pitfall of costs. With Wasabi (https://wasabi.com) they offer a flatrate for 1TB storage without counting API-calls or egress traffic. So there is no need to regularly look into the storage backend to check if the costs are exploding.
I would rather pay 6 bucks a month and can be sure that costs won't explode.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by 99hats** [comment]
I think this might already be possible. [Wasabi is S3 compatible](https://wasabi.com/wp-content/themes/wasabi/docs/API_Guide/index.html#t=topics%2Fapidiff-compat-lib-app.htm) and [Appwrite has adapters for S3](https://dev.to/appwrite/appwrite-storage-meets-limitless-s3-1g89).

**Comment by stnguyen90** [comment]
In progress: https://github.com/utopia-php/storage/pull/40

**Comment by stnguyen90** [comment]
@vijedich, this should be available as of [0.14.2](https://github.com/appwrite/appwrite/releases/tag/0.14.2). For a detailed tutorial, see [Appwrite Storage Meets Wasabi Cloud Storage](https://dev.to/appwrite/appwrite-storage-meets-wasabi-cloud-storage-g4p).

**Comment by everly-gif** [comment]
Thanks @stnguyen90 , @vijedich Wasabi cloud storage is now supported with the latest release. I'm closing this issue hence.
