### ISSUE TITLE
Add Brotli support to Appwrite Nginx Server

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#310]
> Brotli is a generic-purpose lossless compression algorithm that compresses data using a combination of a modern variant of the LZ77 algorithm, Huffman coding and 2nd order context modeling, with a compression ratio comparable to the best currently available general-purpose compression methods. It is similar in speed with deflate but offers more dense compression.
https://github.com/google/brotli

This integration should improve Appwrite HTTP performance on supported clients. Currently Traefik doesn't support this (https://github.com/containous/traefik/pull/6011) so our Nginx container is our only option.

This should be added on our main Dockerfile located here:
https://github.com/appwrite/appwrite/blob/master/Dockerfile

**Comment by Rohitub222** [comment]
Hi eldadfux, would love to work on this. Is anyone working on this? If not, want to do so.

**Comment by eldadfux** [comment]
Hey @Rohitub222, no-one is working on this yet, it will be great if you could help with this.

You can also join our Discord channel if you'd like: https://discord.gg/GSeTUeA

Let me know if you need any help

**Comment by Rohitub222** [comment]
If I could be of any help to you then the pleasure is mine.
Thank you for letting me in.

**Comment by eldadfux** [comment]
@Rohitub222 Any news? let me know if I can help

**Comment by Rohitub222** [comment]
Hi Eldad,
Was in touch with traefix team to get update on when they would have brotli
support. I felt it would be better to go traefix with brotli support than
with nginx. So waiting for traefix team response will wait for a couple of
days. Positive feedback well and good if negative feedback would go with
nginx. Any suggestions?

Thanks and Regards,
Rohit B

**Comment by eldadfux** [comment]
Thinking about it more, I think it would be better to go with Nginx for multiple reasons.

* Traefik + Brotli has been in talk from 2018 and still not clear if this is actually going to happen.
* Our Traefik server is completely decoupled from the app, while the nginx is very well aware and coupled to it. Nginx support will not introduce new complexity.
* It probably be better to leave the hard workload to the Nginx (which acts as our http server) as it's always easier to scale the app server rather than the load balancer.
* Even if Traefik will release support for this, it will take more time for it to be stable.

**Comment by Rohitub222** [comment]
Yes, I gave it a thorough thought which also required to go through the
code base. So finally agreeing to your reasons will be going ahead with
nginx and will start implementation by end of the week and might be around
28th will be completing it.

**Comment by eldadfux** [comment]
Hey @Rohitub222 , any updates? let me know if you could use any help...

**Comment by Rohitub222** [comment]
Hi there, Yes I have been working on it. Give me some more time probably a
couple of days. Yes will contact you if I have any questions.

Thank you,
Rohit B

**Comment by Rohitub222** [comment]
Hi Eldad,
I am done with the development/changes not sure about how create pull
request and push changes since I don't have permission to push. Can you
please help.

**Comment by christyjacob4** [comment]
@Rohitub222 You can create a fork of the repo, push your changes to your fork and then raise a PR against the main repo

**Comment by eldadfux** [comment]
Exactly what @christyjacob4 said ⏫👍

**Comment by eldadfux** [comment]
Brotli compression is now available on Appwrite 0.7! Start boosting your APIs! Thanks to everyone who helped on this issue ❤️
