### ISSUE TITLE
🚀 Feature: Create multiple documents in one time function call

### ISSUE THREAD

**Issue by zcoderr** [appwrite/appwrite#3100]
### 🔖 Feature description

Thanks for appwrite,it's a awesome project.But after I read the documents and weird why don't have a function like `create_documents(list)` in any sdk? It is  frequently-used in my case.

### 🎤 Pitch

It is frequently-used.For example: If I need import some data from other source into appwrite database,I need a function write many rows of data in one time.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Duplicated with #3051
