### ISSUE TITLE
🐛 Bug Report: Function with crontab runs multiple times

### ISSUE THREAD

**Issue by ozoromo** [appwrite/appwrite#3102]
### 👟 Reproduction steps

I created a simple nodejs script that posts a message to discord and gave it a cron job to run once a day at 20:30: `30 20 * * *`

### 👍 Expected behavior

The function should run once at the selected time and then again the next day and so on.

### 👎 Actual Behavior

The function ran three times in the span of the one minute in which it was 20:30
![cronjob](https://user-images.githubusercontent.com/36481318/163678236-661cc6bf-a1fd-4f10-8954-b5739b02ccea.png)
(It also ran at 22:30 instead of 20:30 but that is a different problem and might just have to do with a wrongly set timezone)

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Cloudflare as a proxy and appwrite is a docker install (the official one).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
I have encountered this issue myself, and was pretty confused. Looks like the way we schedule stuff currently can make multiple executions if schedule was changed too often. Here is an example:

- Set cron to 5 * * * *
- Set to to 10 * * * *
- Set to 5 * * * *

This will create 2 schedulers at :05, and one at :10. The one at :10 will not occur because it will see the schedule value is different, so we know it was rescheduled to different time. Problem is, both :05 will pass this check and will result in 2 executions happening every hour.

Currently this can be solved by manually entering Redis database and removing schedules, so you only have one in there.

**Comment by kazkis** [comment]
> I have encountered this issue myself, and was pretty confused. Looks like the way we schedule stuff currently can make multiple executions if schedule was changed too often. Here is an example:
> 
> * Set cron to 5 * * * *
> * Set to to 10 * * * *
> * Set to 5 * * * *
> 
> This will create 2 schedulers at :05, and one at :10. The one at :10 will not occur because it will see the schedule value is different, so we know it was rescheduled to different time. Problem is, both :05 will pass this check and will result in 2 executions happening every hour.
> 
> Currently this can be solved by manually entering Redis database and removing schedules, so you only have one in there.

Hi @Meldiron thanks for looking into this. 
I'm currently facing the same problem and I'm having some difficulties solving it.
Can you please better explain how to remove the duplicated schedulers since I have never used Redis before and I'm not familiar with the AppWrite structure?

**Comment by canbrkkyGit** [comment]
I also have similar problem @kazkis , when i change with a new cron schedule from admin panel, previous cron schedules still proceeds to execute. It should automatically delete previous ones and use only the one that is displayed on admin panel.

Could you explain how can we edit redis database from command line @Meldiron , using nano editor or something like this?

**Comment by Meldiron** [comment]
We will be working towards resolving this issue, but sadly, it requires us to replace one of our current libraries with a new one that we will be making on our own, to prevent a similar problem in the future.

With that said, a solution will most likely not be coming as a patch version. There is a manual way of solving the issue, the following are the steps:

---


**:bomb: Problem**
With CRONs inside Appwrite Functions, there is an edge case when the cron ends up executing multiple times. We are aware and are working towards a custom Redis library to properly solve this issue.

**:syringe: Prevention**
Before fixing it, `How do we prevent it?` If you update your CRON time too often (back and forth) without proper pauses in between cycles, Appwrite will end up keeping two schedules at the same time. The same can occur triple or even more times. The best prevention is to wait for CRON to run before updating it again.

**:wrench: Solution**
Steps to solve the issue, once it is already there:
1. Stop Appwrite: `docker-compose down`
2. Backup. Of course. Just to be safe. You can use: https://gist.github.com/Meldiron/47b5851663668102a676aff43c6341f7
3. Update you `docker-compose.yml`, so the `services` includes this new service:
```yml
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    networks:
    - appwrite
    environment:
    - REDIS_HOSTS=redis
    ports:
    - "8081:8081"
```
4. Start specific parts of Appwrite: `docker-compose up -d redis redis-commander`
Notice this will publicly expose Redis on port `8081`. If you want to be extra secure, set up a firewall on your server and disable this port. Then you can use SSH tunnel to connect to the RedisCommander
5. Visit `http://[YOUR_HOSTNAME]:8081/`
6. On the website, there is a folder tree on the left side. Open up `resque:*` , then `delayed:*`. Inside that, there will be multiple keys (big numbers)
7. Notice alongside each key, there is number in `()`. The number should ALWAYS be 1. If it's not, that's causing double/triple executions
8. For each key that has number 2 or bigger in `()`, do the following:
8.1 Click on the key in the tree on left
8.2 In the center, key data will display. There will be multiple lines. Do the following for all lines, EXCEPT ONE! Keep just one
8.2.1. Double-click the line (anywhere, pretty much). It opens modal
8.2.2 Click the red button `Remove element`
9. When done, stop Appwrite: `docker-compose down`
10. Start Appwrite `docker-compose up -d`
Tadaaa :partying_face: Double-execution should now be fixed.

Some screenshots? 🤔

This is what a good one looks like:

![image](https://user-images.githubusercontent.com/19310830/170952871-b2bdb4ee-b9f1-4373-9480-b28571a0a2b3.png)

This is what a problematic one looks like (double execution):

![image](https://user-images.githubusercontent.com/19310830/170952908-1d763768-57ed-41d8-b6f0-d88ffa2784eb.png)

**Comment by s3ppo** [comment]
i have the same problem.. its a bit frustrating.. it seems this appears everytime i change my cron value in my cloud function

**Comment by stnguyen90** [comment]
I don't think we are clearing the old execution schedule when a new schedule is created.

https://github.com/appwrite/appwrite/blob/c5dde7c2f56f56544e8e0a512622ae25860e7b7a/app/workers/functions.php#L124-L147

It seems like `execution` is `null` when on schedule updates.

https://github.com/appwrite/appwrite/blob/c5dde7c2f56f56544e8e0a512622ae25860e7b7a/app/workers/functions.php#L100

**Comment by fballan93** [comment]
I came to report this . Im glad that it is slated for a fix in .4 release

**Comment by Maxbrt18** [comment]
Do you have any idea when the update will be released? I have not been able to connect to redis-commander to change the schedules.

**Comment by stnguyen90** [comment]
@Maxbrt18, this has been [released](https://github.com/appwrite/appwrite/releases/tag/1.0.1)!
