### ISSUE TITLE
🐛 Bug Report: SMTP not work for me 

### ISSUE THREAD

**Issue by rodgav** [appwrite/appwrite#3103]
### 👟 Reproduction steps

`- _APP_SMTP_HOST=smtp.hostinger.com
- _APP_SMTP_PORT=465
- _APP_SMTP_SECURE=tls
- _APP_SMTP_USERNAME=support@********.com
- _APP_SMTP_PASSWORD=*********`

`Attaching to appwrite-worker-mails
appwrite-worker-mails           | Appwrite mails worker v1 has started
appwrite-worker-mails           | 
appwrite-worker-mails           | [notice] Starting worker 211803452e5f:8:v1-mails
appwrite-worker-mails           | 
appwrite-worker-mails           | Fatal error: Uncaught RedisException: socket error on read socket in /usr/src/code/vendor/colinmollenhour/credis/Client.php:1171
appwrite-worker-mails           | Stack trace:
appwrite-worker-mails           | #0 /usr/src/code/vendor/colinmollenhour/credis/Client.php(1171): Redis->ping()
appwrite-worker-mails           | #1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php(265): Credis_Client->__call('ping', Array)
appwrite-worker-mails           | #2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(180): Resque_Redis->__call('ping', Array)
appwrite-worker-mails           | #3 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
appwrite-worker-mails           | #4 {main}
appwrite-worker-mails           | 
appwrite-worker-mails           | Next CredisException: socket error on read socket in /usr/src/code/vendor/colinmollenhour/credis/Client.php:1189
appwrite-worker-mails           | Stack trace:
appwrite-worker-mails           | #0 /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php(265): Credis_Client->__call('ping', Array)
appwrite-worker-mails           | #1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(180): Resque_Redis->__call('ping', Array)
appwrite-worker-mails           | #2 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
appwrite-worker-mails           | #3 {main}
appwrite-worker-mails           | 
appwrite-worker-mails           | Next Resque_RedisException: Error communicating with Redis: socket error on read socket in /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php:268
appwrite-worker-mails           | Stack trace:
appwrite-worker-mails           | #0 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(180): Resque_Redis->__call('ping', Array)
appwrite-worker-mails           | #1 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
appwrite-worker-mails           | #2 {main}
appwrite-worker-mails           |   thrown in /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php on line 268
appwrite-worker-mails           | Appwrite mails worker v1 has started
appwrite-worker-mails           | 
appwrite-worker-mails           | [notice] Starting worker 211803452e5f:7:v1-mails
appwrite-worker-mails           | 
appwrite-worker-mails           | Fatal error: Uncaught CredisException: LOADING Redis is loading the dataset in memory in /usr/src/code/vendor/colinmollenhour/credis/Client.php:1242
appwrite-worker-mails           | Stack trace:
appwrite-worker-mails           | #0 /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php(265): Credis_Client->__call('smembers', Array)
appwrite-worker-mails           | #1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(104): Resque_Redis->__call('smembers', Array)
appwrite-worker-mails           | #2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(517): Resque_Worker::all()
appwrite-worker-mails           | #3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(391): Resque_Worker->pruneDeadWorkers()
appwrite-worker-mails           | #4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(167): Resque_Worker->startup()
appwrite-worker-mails           | #5 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
appwrite-worker-mails           | #6 {main}
appwrite-worker-mails           | 
appwrite-worker-mails           | Next Resque_RedisException: Error communicating with Redis: LOADING Redis is loading the dataset in memory in /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php:268
appwrite-worker-mails           | Stack trace:
appwrite-worker-mails           | #0 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(104): Resque_Redis->__call('smembers', Array)
appwrite-worker-mails           | #1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(517): Resque_Worker::all()
appwrite-worker-mails           | #2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(391): Resque_Worker->pruneDeadWorkers()
appwrite-worker-mails           | #3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(167): Resque_Worker->startup()
appwrite-worker-mails           | #4 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
appwrite-worker-mails           | #5 {main}
appwrite-worker-mails           |   thrown in /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php on line 268
appwrite-worker-mails           | Appwrite mails worker v1 has started
appwrite-worker-mails           | 
appwrite-worker-mails           | [notice] Starting worker 211803452e5f:7:v1-mails`

### 👍 Expected behavior

Send email.

### 👎 Actual Behavior

Not send emails.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

yes use Cloudflare

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
It might best to troubleshoot this ok the discord server since we may need to go back and forth to diagnose. 

Anyways, the logs don't say anything about sending of the email. It indicates there's something wrong with redis. Are all your containers online and healthy?

To test your SMTP, you can try running `docker-compose exec appwrite doctor`.

**Comment by rodgav** [comment]
`docker-compose exec appwrite doctor
  __   ____  ____  _  _  ____  __  ____  ____     __  __  
 / _\ (  _ \(  _ \/ )( \(  _ \(  )(_  _)(  __)   (  )/  \ 
/    \ ) __/ ) __/\ /\ / )   / )(   )(   ) _)  _  )((  O )
\_/\_/(__)  (__)  (_/\_)(__\_)(__) (__) (____)(_)(__)\__/ 

👩‍⚕️ Running Appwrite Doctor for version 0.13.4 ...

Checking for production best practices...
🟢 Hostname has a public suffix (appwrite.rsgmsolutions.com)
🟢 CNAME target has a public suffix (appwrite.rsgmsolutions.com)
🟢 Using a unique secret key for encryption
🟢 App environment is set for production
🟢 Abuse protection is enabled
🟢 Console access limits are enabled
🟢 HTTPS force option is enabled
🔴 Logging adapter is disabled

Checking connectivity...
Database............connected 👍
Queue...............connected 👍
Cache...............connected 👍
SMTP.............disconnected 👎
StatsD..............connected 👍
InfluxDB............connected 👍

Checking volumes...
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

Checking disk space usage...
🟢 Uploads Volume has 68.82GB free space (17.16% used)
🟢 Cache Volume has 68.82GB free space (17.16% used)
🟢 Config Volume has 68.82GB free space (17.16% used)
🟢 Certs Volume has 68.82GB free space (17.16% used)

You are running the latest version of Appwrite! 🥳`

**Comment by stnguyen90** [comment]
Try changing `_APP_SMTP_SECURE` to `ssl`.

**Comment by rodgav** [comment]
> Try changing `_APP_SMTP_SECURE` to `ssl`.

SMTP.............disconnected 👎
smtp secure is tls 

what active smtp ??

**Comment by stnguyen90** [comment]
Have you tried what I suggested? Also, did you run `docker-compose up -d` after changing the environment variables to apply the changes?

**Comment by rodgav** [comment]
> Have you tried what I suggested? Also, did you run `docker-compose up -d` after changing the environment variables to apply the changes?

yes

**Comment by stnguyen90** [comment]
Would you please try to reset your admin console password and see what error shows up in the worker mail container?

**Comment by rodgav** [comment]
> Would you please try to reset your admin console password and see what error shows up in the worker mail container?
![image](https://user-images.githubusercontent.com/30939186/163694072-a62de1fd-3d01-4785-bea2-499fad9ab105.png)
work.......?

**Comment by rodgav** [comment]
> > Would you please try to reset your admin console password and see what error shows up in the worker mail container?
> > ![image](https://user-images.githubusercontent.com/30939186/163694072-a62de1fd-3d01-4785-bea2-499fad9ab105.png)
> > work.......?

not send invitation team.....

**Comment by eldadfux** [comment]
You can follow this docs: https://appwrite.io/docs/email-delivery or this video created by a community member: https://www.youtube.com/watch?v=cCWlYAO192I

**Comment by rodgav** [comment]
> You can follow this docs: https://appwrite.io/docs/email-delivery or this video created by a community member: https://www.youtube.com/watch?v=cCWlYAO192I

Add user a team, not send email….. 
Forgot password in console. Yes send email…..

**Comment by stnguyen90** [comment]
> Add user a team, not send email….. Forgot password in console. Yes send email…..

Are you adding a user to a team in the admin console? If so, that doesn't send any email.

**Comment by rodgav** [comment]
> > Add user a team, not send email….. Forgot password in console. Yes send email…..
> 
> Are you adding a user to a team in the admin console? If so, that doesn't send any email.

😱😱😱 but in the console a message appears that an email was sent.
So in what cases do you send an email?

**Comment by stnguyen90** [comment]
Emails are sent when the Create Team Membership API call is made from a client SDK. Using Admin console (admin mode) or Server SDK, the user is automatically added so there's no need for an email for the user to accept the invitation.

**Comment by stnguyen90** [comment]
If anything, it might be good to update this issue to be for the incorrect message in the admin console saying an email was sent.

**Comment by rodgav** [comment]
I spent all day configuring, rebooting, adding DNS for a confusing message.😅😅😅
 
thanks for the clarification.

**Comment by jomuji** [comment]
i finally got it to work, if it could help somebody:

i made changes to appwrite-worker-mails
i changed _APP_SMTP_SECURE from SSL to ssl
and it started working, i was using smtp.gmail.com with user and app password

**Comment by felipeavilis** [comment]
Its a good ideia to change the documentation OR change make it works with TSL value.
![image](https://user-images.githubusercontent.com/97637336/224833728-96f9eca9-4191-4088-bbab-f304560fa7d6.png)

I changed _APP_SMTP_SECURE from **tls** to **ssl** an it works!

**Comment by slimpotatoboy** [comment]
> Try changing `_APP_SMTP_SECURE` to `ssl`.

This worked for me using the Cpanel Webmail
