### ISSUE TITLE
[0.13.4.304] 🐛 Bug Report: Function events gets unchecked after function deployment.

### ISSUE THREAD

**Issue by Vishnuxx** [appwrite/appwrite#3106]
### 👟 Reproduction steps

Initially i have enabled event some function events in the function settings after first function deployment. 
But after updating the deployment via
`appwrite deploy functions` , all the checked function events became unchecked

<img width="965" alt="Screenshot 2022-04-18 at 1 12 45 AM" src="https://user-images.githubusercontent.com/74808440/163761902-7a6f3598-ac61-477f-8c50-cbe0b2b7eb33.png">
.

### 👍 Expected behavior

Function events should not be unchecked until explicitly unchecked.

### 👎 Actual Behavior

Function events got unchecked automatically after next deployment.
`appwrite deploy functions` , all the checked function events became unchecked

<img width="965" alt="Screenshot 2022-04-18 at 1 12 45 AM" src="https://user-images.githubusercontent.com/74808440/163761902-7a6f3598-ac61-477f-8c50-cbe0b2b7eb33.png">

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

NodeJs 

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
What's in your appwrite.json? If you don't have anything in there regarding events, the deploy may be clearing the events.
