### ISSUE TITLE
🐛 Bug Report: Incorrect Error Message Given

### ISSUE THREAD

**Issue by rlee1990** [appwrite/appwrite#3107]
### 👟 Reproduction steps

Try to create a document in the Flutter SDK with 2 users set to read access.

### 👍 Expected behavior

Either if it was allowed to just create the document or to provide a valid error message.

### 👎 Actual Behavior

When trying to set 2 users to have read access to a new document in Flutter we receive the following error:
`Unhandled Exception: AppwriteException: document_already_exists, Document already exists (409)`
This is misleading as the document does not exist due to using the unique document ids.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Please share a code example.

**Comment by rlee1990** [comment]
@eldadfux Here is the code I tried
```
await database.createDocument(
        collectionId: blockedCollectionId,
        documentId: unique,
        data: {
          'blockedUser': blocked,
          'blocked': true,
          'blocker': blocker,
          'comboID': '${blocked}_$blocker',
        },
        read: ['user:${sp1[0]}', 'user:${sp2[0]}'],
        write: ['user:${sp1[0]}'],
      );
```

The returns this error `Unhandled Exception: AppwriteException: document_already_exists, Document already exists (409)`
but if I do this 
```
await database.createDocument(
        collectionId: blockedCollectionId,
        documentId: unique,
        data: {
          'blockedUser': blocked,
          'blocked': true,
          'blocker': blocker,
          'comboID': '${blocked}_$blocker',
        },
        read: ['role:member'],
        write: ['user:${sp1[0]}'],
      );
```
I do not get any error. hence it appears that the wrong error is given. I was informed in the discord group that we can only set one user with permissions via the client.

**Comment by abnegate** [comment]
Closing as this should not occur in version 1.2.0, please open a new issue if the issue persists
