### ISSUE TITLE
🚀 Feature: Activity tab for teams

### ISSUE THREAD

**Issue by chenparnasa** [appwrite/appwrite#3108]
### 🔖 Feature description

Hey team 👋 there is a new feature we should add. Screens related: Users

After clicking a user name from users table, we have tabs for overview, sessions, and activity. For consistency and to be intuitive, there should also be a team activity screen.

### 🎤 Pitch

When working on new screens for the console and during the console design sync, Eldad suggested to add activity for a team in the same way we have activity for a user (document all details in a table).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This feature is now released and available as part of Appwrite 0.14. More on the new release here: https://github.com/appwrite/appwrite/discussions/3240
