### ISSUE TITLE
🐛 Bug Report: Deleted user's email can not be reused

### ISSUE THREAD

**Issue by hansbinderup** [appwrite/appwrite#3109]
### 👟 Reproduction steps

1. Create a user with given email
2. Delete the user with given email
3. Create a new user with given email
4. Error: "Account already exists"

I'm aware that the user record is not deleted to preserve the `USER ID` and avoid creating a user with such. But it should definitely be possible to login again (as a new user) with the same email after deletion.

### 👍 Expected behavior

Create a new user with given email

### 👎 Actual Behavior

User can't be created with given email.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
I was not able to reproduce the problem:

https://user-images.githubusercontent.com/19310830/164253316-4ddf1948-c0af-4b18-ae6b-7055b6bccedb.mp4

Can you please share your code? As far as I am concerned, we only preserve user_id for security reasons. Email, name, password, and a bunch of other user data are removed. Only ID is kept.

Can you double-check you are deleting user, not just blocking him? Client SDK only allows account BLOCK, not account DELETE. To fully delete it, you need Appwrite Function and use server-sdk method: https://appwrite.io/docs/server/users?sdk=nodejs-default#usersDelete

Regarding clientSDK method being called "delete", we have a PR to rename that to "block": https://github.com/appwrite/appwrite/pull/2775

**Comment by hansbinderup** [comment]
Thanks for the reply @Meldiron! 

I was using the AppWrite console "User" GUI pressing the "delete" button, so it must have been the client SDK. Anyways, the button explicitly states that the user is deleted and not blocked. 
Is there a way to unblock a user then?

**Comment by hansbinderup** [comment]
I actually "deleted" (read: blocked) the user from my own client (flutter SDK). Also read the documentation stating that delete actually blocks the user. Maybe it should be changed? 
I see that there is an "unblock" attribute as well. 

Gonna close this. But maybe the methods should be renamed to actually reflect the action :wink:
