### ISSUE TITLE
🐛 Bug Report: Array Enums not displaying on the console

### ISSUE THREAD

**Issue by whyte50** [appwrite/appwrite#3125]
### 👟 Reproduction steps

After creating attributes in the collection, whilst having Enum as an Array, accessing the Enum field when creating a document doesn't function properly.
![image](https://user-images.githubusercontent.com/94902401/164236733-7c2cf9c7-d867-4726-844e-e4d8dc03dd1a.png)
the **details** field is the enum array attribute

### 👍 Expected behavior

After clicking **add attribute**, it should show a container with all the required fields, with the placeholder as the field name, clicking the **add attribute** again should repeat the same action, as it is an array.
![image](https://user-images.githubusercontent.com/94902401/164237422-8ea55c8e-cf73-4f51-b4cd-38c73c3fe4d5.png)

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/94902401/164237470-1458f8ed-e2e8-473d-975d-aa80d4e93558.png)
it doesn't display anything, just stays that way without clicking anything.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Digitalocean Appwrite droplet

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by brandonroberts** [comment]
Fixed via https://github.com/appwrite/appwrite/pull/3126
