### ISSUE TITLE
🚀 Feature: Automatically verify email as part of magic url session confirmation flow

### ISSUE THREAD

**Issue by ikumen** [appwrite/appwrite#3130]
### 🔖 Feature description

Have the account `update magic url session` flow also verify the email of user the session is being created for.

### 🎤 Pitch

Currently the create magic url session flow will, for a given email address and redirect url:

* create a user if none exists for the address
* send an email to the address with the redirect url and the `userId` of the user and a temporary `secret` parameters attached to the redirect url
* clients are to handle the redirect url, taking the `userId` and `secret` and calling `update magic url session` to confirm the userId and secret for a Session object 

The process of the client confirming the `userId` and `secret` does not automatically verify the email of the associated user and an additional step is explicitly required to verify the user, even though the user is implicitly verified and given a Session.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This feature is now released and available as part of Appwrite 0.14. More on the new release here: https://github.com/appwrite/appwrite/discussions/3240

**Comment by nithishjipmer** [comment]
In my case even when the user is redirected from mail, accounts.get() is returning null
