### ISSUE TITLE
🐛 Bug Report: Can not upload file to Storage Bucket

### ISSUE THREAD

**Issue by quanganh206** [appwrite/appwrite#3131]
### 👟 Reproduction steps

- Create new Bucket
- Set permission Bucket level with role:all
- Upload file

### 👍 Expected behavior

- uploaded

### 👎 Actual Behavior

- Upload Error
<img width="1790" alt="Screen Shot 2022-04-21 at 17 00 49" src="https://user-images.githubusercontent.com/12064619/164431290-35a7ffbd-2523-4805-bce7-5915fdfabb5d.png">

<img width="887" alt="Screen Shot 2022-04-21 at 16 59 27" src="https://user-images.githubusercontent.com/12064619/164431478-f62b37e7-b530-4fb0-a5ea-f589de1a0a8a.png">

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

No, just do local test with docker-compose

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
How big is your file and what is the maximum file size allowed by your bucket? I was able to upload a 3.8MB file fine.

**Comment by quanganh206** [comment]
@stnguyen90  The file isn't big, just nearly 1MB.

**Comment by stnguyen90** [comment]
Something could be wrong with the build you're on. It might be good to use a clean install of 0.13.4.

**Comment by quanganh206** [comment]
@stnguyen90 yes, you are right. I did clean my docker and then start with a fresh one in 0.13.4 tag and it works like a charm.
