### ISSUE TITLE
🐛 Bug Report: Param is not optional code 400

### ISSUE THREAD

**Issue by adrianstoker** [appwrite/appwrite#3135]
### 👟 Reproduction steps

Create a HTTPS REST API Call to create a user.

- https://api.domain.com/v1/account
- X-Appwrite-Project: myprojectid
- Content-type: application/json
- Payload:
`{"email":"test@email.com","password":"123456789","userId":"unique()","name":"Test User"}`

### 👍 Expected behavior

An account would be created with the following:
email: test@email.com
password: 123456789
name: Test User
userId: Unique user id

### 👎 Actual Behavior

`{message: "Param "email" is not optional.", code: 400, type: "general_argument_invalid",…}`
code: 400
message: "Param \"email\" is not optional."
type: "general_argument_invalid"
version: "0.13.0"

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Ubuntu
Docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Could you please update the issue title to be a bit more descriptive as well as provide the code you're running?

**Comment by adrianstoker** [comment]
Oh, nevermind.
It's not Appwrite that seems to be the problem.
The application is sending the payload as {email:"test@test.com"} when appwrite expects it to be {"email":"test@test.com"}.
The sending app is missing "" from the payload key.
