### ISSUE TITLE
🐛 Bug Report: 404 logs

### ISSUE THREAD

**Issue by iurygdeoliveira** [appwrite/appwrite#3137]
### 👟 Reproduction steps

My appwrite constantly returns the following error from the docker console:

appwrite | [Error] Timestamp: 2022-04-21T20:15:23+00:00
appwrite | [Error] Method: GET
appwrite | [Error] URL: /
appwrite | [Error] Type: UtopiaException
appwrite | [Error] Message: Not Found
appwrite | [Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
appwrite | [Error] Line: 719

What is the reason?

### 👍 Expected behavior

It shouldn't show this error, right?

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/30157522/164545848-e5f0045f-14a4-46e1-ae00-25a33274e917.png)

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I am using appwrite on my local machine. I am not using traefik, just ngnix

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I've seen this for a couple versions now, but they don't seem to cause any problems. I checked my traefik logs, but found no 404 response for GET / requests, so it seems like these are coming from inside the appwrite network. I just can't tell from where exactly yet...

**Comment by eldadfux** [comment]
Might be some internal health checks. Shouldn’t be concerning.
