### ISSUE TITLE
HTTP docs

### ISSUE THREAD

**Issue by Joe118** [appwrite/appwrite#314]
Per suggestion from Eldad, I'm adding this issue (a docs feature request) in the hope that a plain HTTP REST documentation will be added to the excellent appwrite docs. This will allow developers to more easily create an SDK in an as-yet unsupported programming language or environment.

Some examples of excellent HTTP REST API documentation:

DropBox: https://www.dropbox.com/developers/documentation/http/overview
Twilio (under the curl docs): https://www.twilio.com/docs/usage/api
Stripe: https://stripe.com/docs/api
Github: https://developer.github.com/v3/guides/getting-started/

**Comment by eldadfux** [comment]
We'll aim to add this with the 0.7 release. We can use the Appwrite [SDK Generator](https://github.com/appwrite/sdk-generator) to auto generate all CURL code examples just like we do with all the other SDK examples.

**Comment by eldadfux** [comment]
This was actually merged, but we need to enable it in Appwrite itself: https://github.com/appwrite/sdk-generator/pull/157

**Comment by eldadfux** [comment]
@PineappleIOnic let try and add this to Appwrite, I think it should be pretty simple.

**Comment by Haimantika** [comment]
Since this was already merged in: https://github.com/appwrite/sdk-generator/pull/157

Is it good to be closed? @PineappleIOnic
