### ISSUE TITLE
Appwrite Functions ? how... ? 

### ISSUE THREAD

**Issue by unripper** [appwrite/appwrite#3141]
So recently I'm trying to build a blogging app with AppWrite.

These are my collections..
|  Name  | Data | Implementation |
|---|---|---|
| Likes | an object with userId & Id of post which user liked | create a new document when user likes the post |
| Notification | an object with notification text & to which user it belongs | user will be listening to this collection real time |

My goal is to create a function which will listen to `Likes` collection, whenever document is created (someone like a post),I want to notify the post author (create a document in `Notifications` collection).

How can I do that ? 

AppWrite function docs doesn't make sense to me.

**Comment by gepd** [comment]
You should add a function with the event ` database.documents.create`

`req.payload` will have the information of the event including the data sent with the `likes` collection, this will be usefull as when you create the notification document inside the function, it will trigger this function again, but you should check the collection and stop the execution if it's not the `likes` one

Here you have the function template to start with: https://github.com/appwrite/functions-starter/blob/main/node-16.0/src/index.js

**Comment by brandonroberts** [comment]
Thanks @gepd!
