### ISSUE TITLE
🚀 Feature: Each Project Specific SMTP Feature

### ISSUE THREAD

**Issue by obzc** [appwrite/appwrite#3147]
### 🔖 Feature description

Currently, only 1 SMTP is added for Appwrite. For projects working in different domains, mails (activation mails, etc.) are sent through a single domain.

### 🎤 Pitch

If a separate domain can be added for each project, there must be an SMTP setting for each domain.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Hi @obzc yet again, thank you for the request. After discussions with the team, we have come to the decision that this is something we plan to incorporate in the near future, as of now there is no definite timeline for this feature. :)

**Comment by obzc** [comment]
thank u :)

**Comment by eldadfux** [comment]
UPDATE: 06-03-2023

We've just added a new RFC to a highly requested feature! 

**The new Custom SMTP and Email/SMS Templates RFC is now available and waiting for feedback!**

The RFC by @lohanidamodar is available here:
https://github.com/appwrite/rfc/blob/b2b9e3a8ae23cd2511d36f883b26adb3152d8842/022-custom-smtp-and-email-templates.md

Let us know what you think on the PR:
https://github.com/appwrite/rfc/pull/53

**Comment by pietrodicaprio** [comment]
Is this confirmed for 1.4 planned for tomorrow?

**Comment by eldadfux** [comment]
Starting Appwrite 1.4 this feature is now available 🎉
<img width="1438" alt="image" src="https://github.com/appwrite/appwrite/assets/1297371/9e0769e5-ec39-48f6-99f4-8cc0f2f73f42">
