### ISSUE TITLE
Windows One-Liner Installation

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#315]
Our installation command for getting started with Appwrite quickly doesn't work on Windows terminal.

I don't have any Windows machine to test or fix this, but this has been reported by a few users.

We need help converting this line to something that can also work for Windows users:

```bash
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/install/appwrite:rw \
    -e version=0.5.3 \
    appwrite/install
```

**Comment by eldadfux** [comment]
I was googling around for a Windows alternative command for our installation script, would be great if someone with a windows machine could help validate the attempted solution:

```bash
docker run -it --rm ^
    --volume //var/run/docker.sock:/var/run/docker.sock ^
    --volume "%cd%"/appwrite:/install/appwrite:rw ^
    -e version=0.5.3 ^
    appwrite/install
```

**Comment by TorstenDittmann** [comment]
I can try this on Monday 👍

**Comment by eldadfux** [comment]
@TorstenDittmann 👌🏻

**Comment by TorstenDittmann** [comment]
Seems like I can't use Docker on my Windows Machine due to having Windows 10 Home and that's why I am lacking Hyper-V support...

**Comment by dor272** [comment]
Hi,
It still seems to not work:

```
> docker run -it --rm ^
>>     --volume //var/run/docker.sock:/var/run/docker.sock ^
>>     --volume "%cd%"/appwrite:/install/appwrite:rw ^
>>     -e version=0.5.3 ^
>>     appwrite/install
At line:2 char:7
+     --volume //var/run/docker.sock:/var/run/docker.sock ^
+       ~
Missing expression after unary operator '--'.
At line:2 char:7
+     --volume //var/run/docker.sock:/var/run/docker.sock ^
+       ~~~~~~
Unexpected token 'volume' in expression or statement.
At line:3 char:7
+     --volume "%cd%"/appwrite:/install/appwrite:rw ^
+       ~
Missing expression after unary operator '--'.
At line:3 char:7
+     --volume "%cd%"/appwrite:/install/appwrite:rw ^
+       ~~~~~~
Unexpected token 'volume' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator
```

**Comment by RizkyRajitha** [comment]
i think replacing backslash with back tick will work in windows powershell
and for windows cmd replacing  / with  ^ works

for powershell 

docker run -it --rm `
    --volume /var/run/docker.sock:/var/run/docker.sock `
    --volume "$(pwd)"/appwrite:/install/appwrite:rw `
    -e version=0.5.3 `
    appwrite/install


![appwritepowershell](https://user-images.githubusercontent.com/38534289/82160228-75ba5300-98b1-11ea-9330-72cf4047ab35.PNG)


https://stackoverflow.com/questions/3235850/how-to-enter-a-multi-line-command


for windows cmd

docker run -it --rm ^
    --volume //var/run/docker.sock:/var/run/docker.sock ^
    --volume "%cd%"/appwrite:/install/appwrite:rw ^
    -e version=0.5.3 ^
    appwrite/install

![appwritewcmd](https://user-images.githubusercontent.com/38534289/82160237-89fe5000-98b1-11ea-9921-877c14179b34.PNG)


https://stackoverflow.com/questions/605686/windows-how-to-specify-multiline-command-on-command-prompt

**Comment by eldadfux** [comment]
@RizkyRajitha can you confirm both syntax work before I can update our docs? In your screenshot it seems the powershell command throws an error.

@dor272 could you test the updated syntax @RizkyRajitha posted?

**Comment by RizkyRajitha** [comment]
@eldadfux i think error is because docker was not running at that time . 
i will confirm both and let you know . 
@eldadfux  how to update docs ,  i went through https://github.com/appwrite/appwrite/tree/master/docs
but there was no installation docs

**Comment by eldadfux** [comment]
You can update the main README.md file of this repo. We need to split the installation snippet to unix and windows based setups.

The docs of https://appwrite.io/docs/installation page are (currently) located on the private homepage repo, I'll make sure to update there once the syntax is confirmed.

**Comment by RizkyRajitha** [comment]
@eldadfux i will let you know and make a pr once once confirmed

**Comment by RizkyRajitha** [comment]
@eldadfux 
i am using docker toolbox for windows in my machine . 
and in that the bash script work out of the box

![appwirtedockertoolbox](https://user-images.githubusercontent.com/38534289/82250821-ce4d2700-9969-11ea-90bf-6e10da4dc982.PNG)

but in windows cmd it throws a error 

![appwritewincmd](https://user-images.githubusercontent.com/38534289/82250906-efae1300-9969-11ea-95a4-4a53f71161c5.PNG)

i think the problem is with paths in windows . 

can you explain this path so i can understand the problem 

`--volume "%cd%"/appwrite:/install/appwrite:rw `

is it have to be this path or can we tweak it because `:` is also messing things up

**Comment by eldadfux** [comment]
What happens in the installation process is as follow:
1. We run the appwrite/install Docker image
2. The docker stream volume (/var/run/docker.sock) allows the container to execute Docker command on behalf of the host machine
3. The "$(pwd)"/%cd% volume allows the appwrite/install container to save Appwrite's docker-compose file on the host current directory to allow the user to edit the docker-compose.yml file if he needs to in a later stage.
4. The container (appwrite/install) downloads https://appwrite.io/docker-compose.yml to the user "$(pwd)"/%cd% directory and run docker-comopse up -d to start Appwrite

**Comment by mc-drizzle** [comment]
> i think replacing backslash with back tick will work in windows powershell
> and for windows cmd replacing / with ^ works
> 
> for powershell
> 
> ```
> docker run -it --rm `
>     --volume /var/run/docker.sock:/var/run/docker.sock `
>     --volume "$(pwd)"/appwrite:/install/appwrite:rw `
>     -e version=0.5.3 `
>     appwrite/install
> ```
> 
> ![appwritepowershell](https://user-images.githubusercontent.com/38534289/82160228-75ba5300-98b1-11ea-9330-72cf4047ab35.PNG)
> 
> https://stackoverflow.com/questions/3235850/how-to-enter-a-multi-line-command
> 
> for windows cmd
> 
> ```
> docker run -it --rm ^
>     --volume //var/run/docker.sock:/var/run/docker.sock ^
>     --volume "%cd%"/appwrite:/install/appwrite:rw ^
>     -e version=0.5.3 ^
>     appwrite/install
> ```
> 
> ![appwritewcmd](https://user-images.githubusercontent.com/38534289/82160237-89fe5000-98b1-11ea-9921-877c14179b34.PNG)
> 
> https://stackoverflow.com/questions/605686/windows-how-to-specify-multiline-command-on-command-prompt

The code that worked for me was the one for Windows CMD (Command Prompt). Thanks a lot @RizkyRajitha 

Just ensure you replace the version number with the latest version, but you can always update it later anyway.

**Comment by SpajicM** [comment]
> 
> 
> for windows cmd
> 
> ```
> docker run -it --rm ^
>     --volume //var/run/docker.sock:/var/run/docker.sock ^
>     --volume "%cd%"/appwrite:/install/appwrite:rw ^
>     -e version=0.5.3 ^
>     appwrite/install
> ```

Works fine on Windows with Docker Desktop and CMD!

**Comment by Almoullim** [comment]
With windows powershell
```powershell
docker run -it --rm --volume /var/run/docker.sock:/var/run/docker.sock --volume ${pwd}/appwrite:/install/appwrite:rw -e version=0.6.1 appwrite/install
```

**Comment by Almoullim** [comment]
> Seems like I can't use Docker on my Windows Machine due to having Windows 10 Home and that's why I am lacking Hyper-V support...

I think you can use Virtualbox if you don't have access to Hyper-V

**Comment by eldadfux** [comment]
Ready for deployment:
![image](https://user-images.githubusercontent.com/1297371/82739113-a1bc5500-9d45-11ea-8eb3-ac7cf6fe4840.png)

**Comment by eldadfux** [comment]
Updated README.md file:
![image](https://user-images.githubusercontent.com/1297371/82739197-56567680-9d46-11ea-8d89-465f92be8930.png)

**Comment by eldadfux** [comment]
New docs are live! Thank you for all your help!!

**Comment by vimode** [comment]
> Ready for deployment: ![image](https://user-images.githubusercontent.com/1297371/82739113-a1bc5500-9d45-11ea-8eb3-ac7cf6fe4840.png)

Huge oversight! 
This deployment page screenshot does not reflect the correct format so the website's  `[installation guide](https://appwrite.io/docs/installation#windows) still has the old instructions with ,(comma) instead of `(back ticks) for powershell commands. 

The documentation of the repo was properly updated with `(back tick) as indicated by your subsequent screenshot.
