### ISSUE TITLE
🚀 Feature: Encypted database fields

### ISSUE THREAD

**Issue by maeddin** [appwrite/appwrite#3150]
### 🔖 Feature description

It would be very handy especially for string fields if you could have AppWrite encrypt them natively.

### 🎤 Pitch

Here I think of the use-case for keys that are stored directly in the database, which should not be readable for everyone with database access. Of course, there are other examples of sensitive data that should not be stored as plain text in the database. Of course you would lose some queries and indexes for such fields, but "equal" would still work without problems. As key for these fields you could either take the already existing `_APP_OPENSSL_KEY_V1` or create an own ENV variable for it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by MaddinMade** [comment]
Of course, you could also include the option for deterministically encrypted and randomly encrypted attributes. Randomly encrypted attributes could of course not be used in queries at all.

**Comment by DH-555** [comment]
Related: https://appwrite.io/blog/post/announcing-encrypted-string-attributes
