### ISSUE TITLE
🚀 Feature: Do not require emails and passwords for accounts.

### ISSUE THREAD

**Issue by sanny-io** [appwrite/appwrite#3151]
### 🔖 Feature description

Emails and passwords are required to create and use accounts with Appwrite. However, this is not appropriate for all websites. The server should be able to create and log users in using only a UID.

This issue is related to #2396, which was finished, but didn't address the underlying reason the issue was opened.

### 🎤 Pitch

Taken from the previous issue:

> [Firebase allows developers to easily use their own auth service and integrate it with Firebase's own auth system.](https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk)

> I'm using an auth service that already provides a UID. There is no email or password involved. I want to integrate this with Appwrite, but from what I see, Appwrite requires an email and password. Integrating this with Firebase is easy because it doesn't require anything else.

My website has no use for emails or passwords. It doesn't make sense that Appwrite forces me to ask users for an email and password considering we use neither of those things.

Additionally, any website that values total privacy of its users, or any website that users reasonably would not want associated with their identity would benefit from this. It's true that users could create an email specifically for any particular website, but in practice, most people don't bother with this, which means users are less likely to sign up for these kinds of websites.

As an example, I'm using a VPN service in which the only method of authentication is a long series of numbers that the service provides me. It is a UID. There is no email. In this specific example, technically the UID also serves as the password, but the issue remains that an email would be required if this VPN service used Appwrite, which means a major benefit of the service (total privacy) would not apply.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
I personally like this feature.

You can already create new users from Server SDK.. You could use email like `user123@appwrite.internal` and random password.. But the problem is you cant really sign in.

I like the idea of server being able to generate token `appwrite.users.createToken(userId)` and client being able to sign in with token `appwrite.account.createTokenSession(token)`. This way you can use your own logic logic for verifying sign in (custom serial numbers), as well as control channels you share token over (sms, Discord bot, ...).

What do you think about this specific implementation?

**Comment by sanny-io** [comment]
> You can already create new users from Server SDK.. You could use email like user123@appwrite.internal and random password.. But the problem is you cant really sign in.

Yes, for creation, this could work, but it also feels like a hacky workaround.

> I like the idea of server being able to generate token `appwrite.users.createToken(userId)` and client being able to sign in with token `appwrite.account.createTokenSession(token)`. This way you can use your own logic logic for verifying sign in (custom serial numbers), as well as control channels you share token over (sms, Discord bot, ...).
> 
> What do you think about this specific implementation?

This would be a fine implementation 👍 

I wonder if the server could also have the option of creating the session directly. That would cut down on network requests, but I'm not sure if it would be feasible. This is something Firebase doesn't support.

firebase/firebase-admin-node/issues/945

**Comment by jpcaram** [comment]
I support the token approach idea too. This is rather critical in a scenario where the users want to have scripts to automate tasks but they don't want (shouldn't want) to have their passwords hard-coded or be prompted.

I also couldn't find a way to "impersonate" a users from "server" code. Therefore I could not even implement this feature myself using "functions" if I wanted to.

**Comment by gepd** [comment]
I would love to see this feature too! 
as @jpcaram said, currently there no way to implement this

**Comment by TechComet** [comment]
+1

**Comment by eldadfux** [comment]
Custom tokens are at work, and are expected as part of Appwrite 1.5

**Comment by abnegate** [comment]
This is now available in Appwrite 1.5 🥳
