### ISSUE TITLE
🐛 Bug Report: node_modules dev_dependencies counted towards function size

### ISSUE THREAD

**Issue by r-dev-limited** [appwrite/appwrite#3161]
### 👟 Reproduction steps

Add basic things such as jest testing framework to dev dependencies

### 👍 Expected behavior

it should not even look into dev dependencies

### 👎 Actual Behavior

it actually count everything towards container size.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

no

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by voodee** [comment]
I had a similar problem. I noticed it when the size of the arhive triggered a upload error.

Temporary solution: build all code with `esbuild`. `Webpack` and `rollup` can also be used.
Example: `esbuild src/index.ts --bundle --outfile=dist/index.js`

Then deploy code without `node_modules` and `package.json`.
Example: `appwrite functions createDeployment --functionId=... --activate=true --entrypoint='index.js' --code='/dist' --verbose`

This is not good solution, but it is work now. No unnecessary code will get into production thanks to treeshaking.

**Comment by Meldiron** [comment]
We have a PR to address this problem: https://github.com/appwrite/sdk-generator/pull/418

You will be able to control what isn't deployed either in `appwrite.json` or by having `.gitignore` file.

Related PR with docs: https://github.com/appwrite/docs/pull/177

**Comment by Meldiron** [comment]
Released with 0.14 🥳 Feel free to re-open issue if there are any more concerns. With 0.14, you can add `ignores` array into `appwrite.json`. Whatever you define there will be excluded from the deployment.
