### ISSUE TITLE
🐛 Bug Report: sdk-for-apple

### ISSUE THREAD

**Issue by EmileRy** [appwrite/appwrite#3163]
### 👟 Reproduction steps

I try to get a list of all documents with a specitif query: **name = "Paris"**
This code works perfectly if I remove the `queries` attribute from the `listDocuments` function.
```
print("DEBUG: 1")
do {
    let documentList = try await AppwriteVM.instance.database.listDocuments(
        collectionId: "626b97104b392350d53e",
        queries: [
            Query.equal("name", value: "Paris")
        ]
    )
    print("DEBUG: nbResults: " + String(documentList.total))
    
    locations = []
    for document in documentList.documents {
        let location = document.convertTo(fromJson: locationConverter)
        locations.append(location)
    }
} catch { print(error.localizedDescription) }
```

### 👍 Expected behavior

It should print `DEBUG: nbResults: 1`

### 👎 Actual Behavior

I got an error in the logs:
```
DEBUG: 1
The operation couldn’t be completed. (Appwrite.AppwriteError error 1.)
```
And there is no `DEBUG: nbResults` in the logs

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Something else

### 🧱 Your Environment

I use Swift (iOS **15.4**) and `appwrite/sdk-for-apple` version **0.4.0**

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by abnegate** [comment]
@EmileRy Could you please try catching `AppwriteError` specifically and checking the message:

```swift
catch let error as AppwriteError { print(error.message) }
```

There should be more information there. I suspect in this case there is no index created for your `name` attribute, but the error is being masked; I will take a look and see if we can provide some extensions to make `AppwriteError` work directly with `localizedDescription` 🙂

**Comment by EmileRy** [comment]
Oops, you're right, sorry for my mistake and thanks for your help!
