### ISSUE TITLE
🚀 Feature: Collection creating Api

### ISSUE THREAD

**Issue by Dennis-ug** [appwrite/appwrite#3164]
### 🔖 Feature description

Just like the create document api..... think also there should be a create create api s

### 🎤 Pitch

this will help in scalability where user can create a collection where his or her documents can be stored ..... with out using the console to create a collection

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Dennis-ug** [comment]
Hope this will be worked upon soon

**Comment by Meldiron** [comment]
Hey there 👋
This is already possible using Server SDK: [https://appwrite.io/docs/server/database?sdk=nodejs-default#databaseCreateCollection](https://appwrite.io/docs/server/database?sdk=nodejs-default#databaseCreateCollection)

It would be really insecure to expose this to ClientSDK. If a client tries to create a document, there is `write` permission check. But if he tried to create a collection there would be no check, meaning there would be no secure way to do this from client side.

With that said, you can expose collection creation from ServerSDK to the client using the Appwrite Function. You can create Appwrite Function that would receive some input (like collection name and ID), and create new collection from inside the function (using ServerSDK). This way you have full control over what permissions you set on the collection, and can also reject to do it.

**Comment by stnguyen90** [comment]
Closing as no further action required. Feel free to comment if additional discussion is required.
