### ISSUE TITLE
🐛 Bug Report: .webm format not supported properly

### ISSUE THREAD

**Issue by chuongtang** [appwrite/appwrite#3178]
### 👟 Reproduction steps

When a `.webm` type video got send to storage via `storage,createFile()` the mimeType was recorded correctly on the returned JSON from appwrite.

However, when viewing file from the appwrite console (storage then `new window` to preview, the response header returned mimeType as 'text/plain` which cause the improper display of the video.

I did a similar test with .mp4 video and all work well

Here is the screenshot of the returned JSON from storage api
![mimeType](https://user-images.githubusercontent.com/75117692/166862814-c1f5083f-bdf2-45f6-a5a8-2614664c2312.jpg)

### 👍 Expected behavior

It should preview the `.webm` video properly such as with `.mp4` file.

With help from fellows from discord, I realize there's a missing video type in the appwrite  storage config : https://github.com/appwrite/appwrite/blob/master/app/config/storage/mimes.php

A quick fix would be adding one single line with "video/webm" in the return.
![addwebm](https://user-images.githubusercontent.com/75117692/166862988-580e3cca-1cce-4d97-b59c-507166402017.jpg)

### 👎 Actual Behavior

![appwriteFileView](https://user-images.githubusercontent.com/75117692/166862762-a1527cca-52c4-4397-95ac-cf9a004d0e08.jpg)

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I deployed my appwrite onto Vultr for production testing

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Great catch! 🎣  You are breathtaking for creating a PR too! 🤩
