### ISSUE TITLE
Use enum for supported auth provider values

### ISSUE THREAD

**Issue by pedromassango** [appwrite/appwrite#318]
I want to propose a change for the Flutter SDK, right now it seems that we are using String for the provider (in `createOAuth2Session()`) My suggestion is to use enum instead of string to prevent the user for entering invalid inputs.

**Comment by eldadfux** [comment]
@bartektartanus would be great to get your view on this.

**Comment by bartektartanus** [comment]
Great idea. Are those values available during code generation (like all the methods in API) or we need to hard-code them?

**Comment by eldadfux** [comment]
I think I can make them available as twig params. I'll check this in a few days..

**Comment by TorstenDittmann** [comment]
Gonna close this issue in favor of #426
