### ISSUE TITLE
📚 Documentation: Make a few example around teams feature

### ISSUE THREAD

**Issue by SirusCodes** [appwrite/appwrite#3192]
### 💭 Description

I find documentation of teams feature a bit confusing. It would be great if we can have aa example app that will go through creating, adding members, and removing them.

https://dev.to/appwrite/30daysofappwrite-appwrite-teams-2fjd
Above one is the only article I found regarding this but I feel it's inadequate for this big feature. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by SirusCodes** [comment]
Thanks @gewenyu99 for your response.
An example app and blog would be great!

**Comment by gewenyu99** [comment]
@SirusCodes I'm trying to scope the example app. What exactly do you want to see from this app?

30 Days of Appwrite covers both creating a team in this article:
https://dev.to/appwrite/30daysofappwrite-appwrite-teams-2fjd

And the following features in this article.
- [Create Teams](https://appwrite.io/docs/client/teams?sdk=web#teamsCreate)
- [List User's Teams](https://appwrite.io/docs/client/teams?sdk=web#teamsList)
- [Delete Team](https://appwrite.io/docs/client/teams?sdk=web#teamsDelete)
- [Get Team by ID](https://appwrite.io/docs/client/teams?sdk=web#teamsGet)
- [Get members of a team](https://appwrite.io/docs/client/teams#teamsGetMemberships)
- [Add a new team member](https://appwrite.io/docs/client/teams#teamsCreateMembership)
- [Update Membership status](https://appwrite.io/docs/client/teams#teamsUpdateMembershipStatus)
- [Remove a user from a team](https://appwrite.io/docs/client/teams#teamsDeleteMembership)
https://dev.to/appwrite/30daysofappwrite-using-team-invites-gk1

Preferably, I would amend 30 days of Appwrite to include the examples you're looking for, so we don't rewrite the same content multiple times.

**Comment by SirusCodes** [comment]
That works👍

I would like to see the flow like how the user creates a team and then add a membership then the other person would accept from mail (it would be great if you also say that how to handle this in mobile apps)
Listing and removing the memberships and deleting the teams would complete it.

Also a graph for the flow will be helpful to get a gist.

**Comment by gewenyu99** [comment]
@SirusCodes I'm back with a blog post and sample app!

https://dev.to/gewenyu99/exploring-teams-and-smtp-with-appwrite-8fn

I can see why you'd be confused about how to use teams. I decided to struggle through it myself and write about my thoughts.

Rest assured, the docs need some improvements, and I'll implement them so y'all won't be as confused down the road. For now, there's my post :)

**Comment by SirusCodes** [comment]
Looks great!!

**Comment by gewenyu99** [comment]
@SirusCodes Closing
