### ISSUE TITLE
🚀 Feature: multiple user deletion from the console

### ISSUE THREAD

**Issue by Vishnuxx** [appwrite/appwrite#3196]
### 🔖 Feature description

User deletion from the console in current appwrite version is only possible by opening the specific user and deleting using delete button.

<img width="713" alt="Screenshot 2022-05-08 at 11 30 34 PM" src="https://user-images.githubusercontent.com/74808440/167309188-9a8e2256-691e-4276-8b69-3123b26c5d45.png">

Adding MultiSelect feature in the users list panel would make it easier to delete multiple users at a time.

<img width="389" alt="Screenshot 2022-05-08 at 11 31 59 PM" src="https://user-images.githubusercontent.com/74808440/167309358-e0452641-4ffc-4df8-89da-cfb28e64787b.png">

### 🎤 Pitch

This feature would be useful for development purposes so that test mails can be deleted easily.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
I have shared the issue with our designing team and they liked the idea 😇 As soon as the proper design is ready (which might take some time as designers might need to collect some more feedback), engineers will jump in to implement it.

**Comment by Vishnuxx** [comment]
Thank you Meldiron! I'm closing this issue. Waiting for the updates...
