### ISSUE TITLE
🚀 Feature: Scala SDK for Play Framework, Akka and Kafka

### ISSUE THREAD

**Issue by VakinduPhilliam** [appwrite/appwrite#3199]
### 🔖 Feature description

An Appwrite Scala SDK implementation built with SBT for the Play framework, but can also work with Akka and Kafka.

### 🎤 Pitch

An Appwrite Scala SDK implementation built with SBT for the Play framework, but can also work with Akka and Kafka.

Check it out:

Here's a sample Scala code on how to capture the health, locale and currency of an appwrite server.

```scala

package example
import appwrite._ 

object Appwrite extends App {
    appwrite()

    @JSExport
    def appwrite(): Unit = {
        val health = new Health().get()
        println(s"Health Report: $health")

        val db = new Health().getDB()
        println(s"Database: $db")

        val time = new Health().getTime()
        println(s"Time: $time")

        val locate = new Locale().get()
        println(s"Location: $locale")

        val countries = new Locale().getCountries()
        println(s"Countries: $countries")

        val currencies = new Locale().getCurrencies()
        println(s"Currencies: $currencies")
    }
}

```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@VakinduPhilliam, can the [Kotlin SDK](https://github.com/appwrite/sdk-for-kotlin) be used in the Play Framework?

**Comment by VakinduPhilliam** [comment]
No. I'm using Scala.js for conversion. https://www.scala-js.org/

**Comment by stnguyen90** [comment]
@VakinduPhilliam, that library says it can use any JS library so can't it use our sdk-for-node or sdk-for-web?

**Comment by VakinduPhilliam** [comment]
@stnguyen90 Got it! The aim was to smoothen the ability to build Play Scala apps using appwrite without the hustle of type conversion.
But yes I see your point.
