### ISSUE TITLE
https://appwrite.io/ star count is incorrect

### ISSUE THREAD

**Issue by RizkyRajitha** [appwrite/appwrite#320]
![appwriteweb (2)](https://user-images.githubusercontent.com/38534289/82207682-dd12ea00-9927-11ea-8c3c-1bd2738f075b.PNG)

in the website it shows 2.5k stars but github shows 2.6k stars
is there a way to make it dynamic to tally with github.

**Comment by eldadfux** [comment]
Yes, actually when we first introduced the new community page (https://appwrite.io/community) we created a GitHub integration that updates hourly, and aggregate data from all our org repositories. I just need to change this with a var. Should take 5 minutes now.

**Comment by RizkyRajitha** [comment]
awesome
