### ISSUE TITLE
📚 Documentation: Ordering in listing document is not clearly documented

### ISSUE THREAD

**Issue by SirusCodes** [appwrite/appwrite#3200]
### 💭 Description

We can get to know about the presence of these attributes from [database rest docs](https://appwrite.io/docs/client/database?sdk=web-default#databaseListDocuments) but it's not clear how we can use it.

I would suggest to add it over there itself or add it in [database docs](https://appwrite.io/docs/database)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
Hi there~ 

Are you talking about concrete examples of `orderAttributes` and `orderTypes`?

I can see why this might be confusing. I'll assign this to myself and find an appropriate place for a description.

Thanks! I'll link a PR here when I'm ready.

**Comment by SirusCodes** [comment]
Yes, need a few examples for it.
Maybe a better API would be to return a Map instead of 2 lists but let's not change the API now...😅

**Comment by gewenyu99** [comment]
There's now a dedicated ordering result section + we have a new query sorting system :) https://appwrite.io/docs/databases#ordering
