### ISSUE TITLE
🚀 Feature: add verification code to log in?

### ISSUE THREAD

**Issue by paintingStyle** [appwrite/appwrite#3203]
### 🔖 Feature description

Can you add verification code to log in? The product needs this function

### 🎤 Pitch

The user can use the mobile phone number and verification code to complete the login, which is faster than email verification

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by everly-gif** [comment]
Closing this issue as Appwrite supports phone authentication 🥳 from the latest relase[ 0.15](https://dev.to/appwrite/announcing-appwrite-015-with-phone-authentication-more-5cjj). 
Here are some resources to get started with : 
[Appwrite Phone Authentication with Flutter](https://dev.to/appwrite/appwrite-phone-authentication-with-flutter-3jii)
[Phone Authentication with Appwrite and Twilio](https://dev.to/appwrite/phone-authentication-with-appwrite-and-twilio-26ek)

**Comment by everly-gif** [comment]
#3357
