### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by Paul-005** [appwrite/appwrite#3206]
### 💭 Description

<h1>Please add details of how to stop this AppWrite Container.</h1>

<li>It seems that it's very difficult to stop this all docker container and hope you would do the necessary to stop container without much difficult.</li>

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey there 👋
As part of our installation instruction were have sections for both [Stop](https://appwrite.io/docs/installation#stop) and [Uninstall](https://appwrite.io/docs/installation#uninstall) instruction. Please let me know if these aren't clear and we can try to improve them together 😇
