### ISSUE TITLE
🚀 Feature: Add Appwrite exception if FileList instead of File is given as input to storage.createFile Web SDK

### ISSUE THREAD

**Issue by Dakicka** [appwrite/appwrite#3209]
### 🔖 Feature description

This problem might be unique to a junior programmer like me :)
I didn't know that the HTML5 <input type="file"> always returns a FileList, even if it is a single file picker (not using multiple).
I used React and Typescript and typed the form field as File which didn't cause any problems (this was the root cause I guess).

Calling the createFile Method of the Web SDK with a FileList instead of File input did not cause any error, message, log, response or anything else to let me know that something is not working. After stepping through the createFile function I saw that it just walks through the function normally but when needing to assign the file size it just assigns undefined which than leads to eventually skipping the part of the function where the API call is done. It then just continues to the return point and returns undefined (the initial response value) without telling me anything.

### 🎤 Pitch

Adding a very simple check at the beginning of the createFile method to check if the input file is indeed just a single file.
Something like

`if(inputFile instanceof File === false)` 

would do the job I think.
Returning an error or AppwriteException with a meaningful message.

Again, maybe this is just an issue that I ran into because of my juniority but any error or message would have saved me some time debugging :)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey there 👋
Thanks for a really informative issue! Appwrite is beginner-friendly and your concern is 100% valid 😇

As this sounds like a web-only issue, I agree with you that the solution should be on the client-side - in webSDK. I also like the way of checking it (looking for File instance), as it can solve issues like providing string path, or some weird buffer/base64.

I addressed this in a PR: https://github.com/appwrite/sdk-generator/pull/443

If you are interested, please review the PR and drop your comments if you have any.

**Comment by Meldiron** [comment]
Merged, and released with `8.0.1` 🥳

**Comment by stnguyen90** [comment]
@Dakicka , @gepd , were y'all using TypeScript? I think TypeScript would show a warning/error that the expected input is File rather than File[].

**Comment by gepd** [comment]
I was using typescript but I didn't get any warning or error 🤔

**Comment by stnguyen90** [comment]
> I was using typescript but I didn't get any warning or error thinking

Here's what I get:

![image](https://user-images.githubusercontent.com/1477010/169740093-9a8a5712-89aa-4112-9acf-78a5efeb7dbd.png)

**Comment by Dakicka** [comment]
Yes that is correct. So the issue was on the dev/user side. I wrongly typed the FileList as File. Hence, Typescript was happy with that. The function got called but returned nothing/undefined. So the fix here takes care that if you accidentally type the file picker input field as a File instead of a FileList, the createFile function will still get called and returns an error.

Again, I think it is more like a junior thing to not know that, but the fix now helps a ton with finding that mistake/bug.
