### ISSUE TITLE
🐛 Bug Report: Collection attributes/indexes not deleted 

### ISSUE THREAD

**Issue by tiures** [appwrite/appwrite#3238]
### 👟 Reproduction steps

Delete a collection which has attributes and/or indexes. The attributes and/or indexes do not get deleted from the maria db _travy_attributes and _travy_indexes tables. 

### 👍 Expected behavior

I would expect the attributes/indexes to be deleted from their tables.

### 👎 Actual Behavior

The attributes/indexes are not deleted.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I don't have a custom environment.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey there 👋 Are there specific steps to reproduce?

I tried to create collection with 2 attributes and 2 indexes.
<img width="511" alt="CleanShot 2022-05-18 at 16 29 16@2x" src="https://user-images.githubusercontent.com/19310830/169066412-75e5f695-fc95-4018-b9ac-e10011647b1a.png">

Then I deleted everything one by one. All were removed properly.

<img width="536" alt="CleanShot 2022-05-18 at 16 29 44@2x" src="https://user-images.githubusercontent.com/19310830/169066421-dd6e63de-a858-4470-9817-0b9fea0e528c.png">

Could you also please share your log in `docker-compose logs appwrite-worker-database`? If it has not been removed properly, the error should be in this log.

**Comment by stnguyen90** [comment]
Possibly related to https://github.com/appwrite/appwrite/issues/2902.

**Comment by stnguyen90** [comment]
@Meldiron, I think the user is referring to the `_<project id>_attributes` and `_<project id>_indexes` tables. In your case, it would be `_dev_attributes` and `_dev_indexes`.

**Comment by tiures** [comment]
Hello! Yes I am referring to the _<project id>_attributes and _<project id>_indexes table. It is also indeed the same as #2902, sorry, missed it.

**Comment by stnguyen90** [comment]
@tiures maybe this can be closed as duplicate then?

**Comment by TorstenDittmann** [comment]
Closing in favor of #2902
