### ISSUE TITLE
🐛 Bug Report: CRON Schedule Does Not Trigger Function

### ISSUE THREAD

**Issue by JamesKai** [appwrite/appwrite#3239]
### 👟 Reproduction steps

1. Clean installation of Appwrite using the following command `docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.14.0`
2. Deploy Node.js 16.0 function manually
3. Manually trigger the function using Appwrite Console UI and confirm the function has been executed without issues from Logs. Also, this function does exactly what I expect it to do.   
4. Set up CRON syntax: * * * * ? to trigger the function every minute (not using Events for function triggering) and expect the function to be triggered at a scheduled time.
5. Function is not executed at scheduled time. In fact, not a single function has been executed for the next hour according to the Log. I can also verify this behavior as the scheduled function has no effect on my front-end app. 

I think this is probably a bug specific to version 0.14 as it works without issues in 0.13 

### 👍 Expected behavior

function should be triggered at a scheduled time.

### 👎 Actual Behavior

function is not triggered at a scheduled time.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

- Appwrite Version: 0.14
- Appwrite is a docker install.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
@JamesKai Version 0.14.1 is out!

Once you upgrade everything should be working as expected 👍🏻

**Comment by JamesKai** [comment]
@TorstenDittmann I can verify that this bug is fixed. Thank you for solving this issue.
