### ISSUE TITLE
CRON Templates/Dropdown in Appwrite console

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#324]
Add CRON ready to use syntax templates in new (or existing) tasks modal windows

**Comment by eldadfux** [comment]
So the idea here is to replace the default cron text box with a drop down list that will include some common CRON combinations, like: 
* run every minute
* run every 5 minutes
* run every hour
* run once a month

Below that drop down will have a switch button to go back to the current CRON text box where developer will be able to add any custom CRON they want.

The idea is to have a simpler approach by default and hide the complexity for advanced developers.

What do you think the common CRON drop list should include beside the ones I mentioned above?

**Comment by HelixHEX** [comment]
You should also add every 30 minutes and every 24 hours
