### ISSUE TITLE
🐛 Bug Report: Rapid execution of sync function when container is not running returns docker errors

### ISSUE THREAD

**Issue by JakeAi** [appwrite/appwrite#3243]
### 👟 Reproduction steps

Remove function container or let the function/container go to sleep.
Execute the function multiple times. In my case, I refresh the page and 3 executions to the same container run.
After container is running, executions run as normal

[https://discord.com/channels/564160730845151244/564161373148414012/976209869323513926](https://discord.com/channels/564160730845151244/564161373148414012/976209869323513926)

### 👍 Expected behavior

All executions should wait until container starts.

### 👎 Actual Behavior

Executions failed with different errors. One was successful. Errors received are below.

`Code file not found.`

```Docker Error: docker: Error response from daemon: Conflict. The container name "/60ba41c8937c5-6283e126c0e02eafda5a" is already in use by container "52e4be76cdc4b88b67f5ead5ecf9b988fac130b163b318ceaba5a2138822a45a". You have to remove (or rename) that container to be able to reuse that name.```

`An internal curl error has occurred within the executor! Error Msg: Could not resolve host: 60ba41c8937c5-6283e126c0e02eafda5a`

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

0.14

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by PineappleIOnic** [comment]
This issue should be solved with #3361. Which will be released with 0.15, closing this issue for now.
