### ISSUE TITLE
Collection Creation - No Documents being shown when Collection is selected.

### ISSUE THREAD

**Issue by punitdiwan** [appwrite/appwrite#325]
**Problem:**
While testing the Collection Creation Feature latest master after merging 0.6 branch, I noticed that after adding  documents to the collection,, when we click database from the side bar and select the collection, the documents is not being displayed, however total count is being shown. Though refreshing the URL, it displays as expected.
 
**Steps to Replicate**

1. Run Fresh Instance and create a project f your choce from GUI.
2. Click Database in the sidebar and click + sign to create Collection
3. Enter the name and click Create, assign Rules 
4. Enter the data and click Update
5. Click Database on Sidebar and select Collection

You will See the Document Count but not Document(s). Here is the Screenshot reflecting the same.
![AppWrite](https://user-images.githubusercontent.com/49054503/82355613-4f7edb00-99b7-11ea-963b-e108aa6a1b8a.png)

Am I doing something wrong, Please guide me.
Thanks,
Punit Diwan

**Comment by eldadfux** [comment]
Do you get any errors in your developers tools?

**Comment by punitdiwan** [comment]
No Errors received. 
![No_dev_tool_error](https://user-images.githubusercontent.com/49054503/82360873-e13e1680-99be-11ea-90be-5014a080a329.png)

However refresh the URL, the data will be displayed.

**Comment by eldadfux** [comment]
I'll try to recreate the bug on my env, seems like a missing update event

**Comment by punitdiwan** [comment]
OK

**Comment by eldadfux** [comment]
@punitdiwan what browser and browser version are you using?

**Comment by punitdiwan** [comment]
@eldadfux  I am using Chrome Browser  81.0.4044.138 on Window 10. Were you able to replicate the issue?

**Comment by punitdiwan** [comment]
@eldadfux Could you replicate the issue? Did it happen at your end? I tired using mobile device and it works fine. Then I I tried with my another internet connection on desktop, it works better. I am under the impression is that my internet was the culprit.  If noone else report the bug, I will close this issue by tomorrow.

**Comment by eldadfux** [comment]
Tried on a clean setup, but worked fine :/

**Comment by punitdiwan** [comment]
@eldadfux Great, just give one more day to me. I will close the issue by tomorrow. Request you to remove the Label **Bug** for now.

**Comment by eldadfux** [comment]
Done 👌🏻

**Comment by punitdiwan** [comment]
I am not able to replicate the issue. It could be my flaky internet connection. Cloning the issue. Let you know  if it pops again.
