### ISSUE TITLE
Failed migration from 0.11.0 to 0.12.x

### ISSUE THREAD

**Issue by MaddPenguin** [appwrite/appwrite#3260]
Appwrite version: 0.11.0
Environment: Ubuntu  20.04 droplet

Upgrade command:
```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.12
```

<details>
  <summary>docker ps | grep appwrite/appwrite</summary>
  
```
995bed56bfb8   appwrite/appwrite:0.12.3   "worker-certificates"    44 seconds ago       Up 42 seconds   80/tcp                                                                     appwrite-worker-certificates
035fe202afd4   appwrite/appwrite:0.12.3   "worker-webhooks"        44 seconds ago       Up 42 seconds   80/tcp                                                                     appwrite-worker-webhooks
40abea59c60f   appwrite/appwrite:0.12.3   "worker-functions"       44 seconds ago       Up 42 seconds   80/tcp                                                                     appwrite-worker-functions
ce0c4c442c23   appwrite/appwrite:0.12.3   "schedule"               44 seconds ago       Up 42 seconds   80/tcp                                                                     appwrite-schedule
244bba8acdfa   appwrite/appwrite:0.12.3   "worker-audits"          45 seconds ago       Up 42 seconds   80/tcp                                                                     appwrite-worker-audits
a66c2598cb18   appwrite/appwrite:0.12.3   "worker-deletes"         45 seconds ago       Up 43 seconds   80/tcp                                                                     appwrite-worker-deletes
d47ef55d1793   appwrite/appwrite:0.12.3   "worker-mails"           46 seconds ago       Up 45 seconds   80/tcp                                                                     appwrite-worker-mails
a320cd85f224   appwrite/appwrite:0.12.3   "realtime"               46 seconds ago       Up 45 seconds   80/tcp                                                                     appwrite-realtime
79de84e98baa   appwrite/appwrite:0.12.3   "maintenance"            47 seconds ago       Up 45 seconds   80/tcp                                                                     appwrite-maintenance
9dac6c27db86   appwrite/appwrite:0.12.3   "docker-php-entrypoi…"   56 seconds ago       Up 54 seconds   80/tcp                                                                     appwrite
38959ac6ad0d   appwrite/appwrite:0.12.3   "worker-database"        57 seconds ago       Up 54 seconds   80/tcp                                                                     appwrite-worker-database
0662666f57ca   appwrite/appwrite:0.12.3   "usage"                  About a minute ago   Up 57 seconds   80/tcp                                                                     appwrite-usage
```
</details>

<details>
  <summary>docker-compose exec appwrite migrate</summary>
  
--------------------
WARNING
--------------------
Migrating to Version 0.12.x introduces a major breaking change within the Database Service!
Before migrating, please read about the breaking changes here:
https://dev.to/appwrite/appwrite-012-migration-post-3cha
If you want to proceed, type 'yes':
yes

Collections
--------------------
Be aware that following actions will happen during the migration:
- Nested Document rules will be migrated to String attributes
- Numeric rules will be migrated to float attributes
- Wildcard and Markdown rules will be converted to string attributes
Do you want to migrate your Database Collections?
Type 'yes' or 'no':
yes

Documents
------------------
Be aware that following actions will happen during the migration:
- Nested Documents will be stored as JSON values
- All Numeric values will be converted to float
- All Wildcard and Markdown values will be converted to string
Do you want to migrate your Database Documents?
Type 'yes' or 'no':
yes
Starting Data Migration to version 0.12.3

------------------------------------
Migrating project Appwrite
------------------------------------
Skipped console project migration.
Migrating Internal Documents: 0 / 86
Migrated 86 Internal Documents.
Fetched 1/1 projects...

------------------------------------
Migrating project rokcompanion.com
------------------------------------
Created project document: rokcompanion.com (61911c2512bea)
Created internal tables for : rokcompanion.com (61911c2512bea)
Created audit tables for : rokcompanion.com (61911c2512bea)
Created abuse tables for : rokcompanion.com (61911c2512bea)
Migrating Collections: 0 / 2
Created "imageId" attribute in collection: talent_trees
Created "constant" attribute in collection: talent_trees
Created "date" attribute in collection: talent_trees
Created "likedBy" attribute in collection: talent_trees
Created "op" attribute in collection: talent_trees
Created "opId" attribute in collection: talent_trees
Created "tags" attribute in collection: talent_trees
Created "desc" attribute in collection: talent_trees
Created "identifier" attribute in collection: talent_trees
Migrating External Documents for Collection 61937d52596ec: 0 / 32

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1069

Warning: foreach() argument must be of type array|object, string given in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 1108
Created "title" attribute in collection: patch_notes
Created "url" attribute in collection: patch_notes
Created "imgURL" attribute in collection: patch_notes
Migrating External Documents for Collection 61937c67b61a6: 0 / 21
Migrating Internal Documents: 0 / 133760
Migrating Internal Documents: 500 / 133760
Migrating Internal Documents: 1000 / 133760
Migrating Internal Documents: 1500 / 133760
Migrating Internal Documents: 2000 / 133760
Migrating Internal Documents: 2500 / 133760
Migrating Internal Documents: 3000 / 133760
Migrating Internal Documents: 3500 / 133760
Migrating Internal Documents: 4000 / 133760
Migrating Internal Documents: 4500 / 133760
Migrating Internal Documents: 5000 / 133760
Migrating Internal Documents: 5500 / 133760
Migrating Internal Documents: 6000 / 133760
Migrating Internal Documents: 6500 / 133760
Migrating Internal Documents: 7000 / 133760
Migrating Internal Documents: 7500 / 133760
Migrating Internal Documents: 8000 / 133760
Migrating Internal Documents: 8500 / 133760
Migrating Internal Documents: 9000 / 133760
Migrating Internal Documents: 9500 / 133760
Migrating Internal Documents: 10000 / 133760
Migrating Internal Documents: 10500 / 133760
Migrating Internal Documents: 11000 / 133760
Migrating Internal Documents: 11500 / 133760
Migrating Internal Documents: 12000 / 133760
Migrating Internal Documents: 12500 / 133760
Migrating Internal Documents: 13000 / 133760
Migrating Internal Documents: 13500 / 133760
Migrating Internal Documents: 14000 / 133760
Migrating Internal Documents: 14500 / 133760
Migrating Internal Documents: 15000 / 133760
Migrating Internal Documents: 15500 / 133760
Migrating Internal Documents: 16000 / 133760
Migrating Internal Documents: 16500 / 133760
Migrating Internal Documents: 17000 / 133760
Migrating Internal Documents: 17500 / 133760
Migrating Internal Documents: 18000 / 133760
Migrating Internal Documents: 18500 / 133760
Migrating Internal Documents: 19000 / 133760
Migrating Internal Documents: 19500 / 133760
Migrating Internal Documents: 20000 / 133760
Migrating Internal Documents: 20500 / 133760
Migrating Internal Documents: 21000 / 133760
Migrating Internal Documents: 21500 / 133760
Migrating Internal Documents: 22000 / 133760
Migrating Internal Documents: 22500 / 133760
Migrating Internal Documents: 23000 / 133760
Migrating Internal Documents: 23500 / 133760
Migrating Internal Documents: 24000 / 133760
Migrating Internal Documents: 24500 / 133760
Migrating Internal Documents: 25000 / 133760
Migrating Internal Documents: 25500 / 133760
Migrating Internal Documents: 26000 / 133760
Migrating Internal Documents: 26500 / 133760
Migrating Internal Documents: 27000 / 133760
Migrating Internal Documents: 27500 / 133760
Migrating Internal Documents: 28000 / 133760
Migrating Internal Documents: 28500 / 133760
Migrating Internal Documents: 29000 / 133760
Migrating Internal Documents: 29500 / 133760
Migrating Internal Documents: 30000 / 133760
Migrating Internal Documents: 30500 / 133760
Migrating Internal Documents: 31000 / 133760
Migrating Internal Documents: 31500 / 133760
Migrating Internal Documents: 32000 / 133760
Migrating Internal Documents: 32500 / 133760
Migrating Internal Documents: 33000 / 133760
Migrating Internal Documents: 33500 / 133760
Migrating Internal Documents: 34000 / 133760
Migrating Internal Documents: 34500 / 133760
Migrating Internal Documents: 35000 / 133760
Migrating Internal Documents: 35500 / 133760
Migrating Internal Documents: 36000 / 133760
Migrating Internal Documents: 36500 / 133760
Migrating Internal Documents: 37000 / 133760
Migrating Internal Documents: 37500 / 133760
Migrating Internal Documents: 38000 / 133760
Migrating Internal Documents: 38500 / 133760
Migrating Internal Documents: 39000 / 133760
Migrating Internal Documents: 39500 / 133760
Migrating Internal Documents: 40000 / 133760
Migrating Internal Documents: 40500 / 133760
Migrating Internal Documents: 41000 / 133760
Migrating Internal Documents: 41500 / 133760
Migrating Internal Documents: 42000 / 133760
Migrating Internal Documents: 42500 / 133760
Migrating Internal Documents: 43000 / 133760
Migrating Internal Documents: 43500 / 133760
Migrating Internal Documents: 44000 / 133760
Migrating Internal Documents: 44500 / 133760
Migrating Internal Documents: 45000 / 133760
Migrating Internal Documents: 45500 / 133760
Migrating Internal Documents: 46000 / 133760
Migrating Internal Documents: 46500 / 133760
Migrating Internal Documents: 47000 / 133760
Migrating Internal Documents: 47500 / 133760
Migrating Internal Documents: 48000 / 133760
Migrating Internal Documents: 48500 / 133760
Migrating Internal Documents: 49000 / 133760
Migrating Internal Documents: 49500 / 133760
Migrating Internal Documents: 50000 / 133760
Migrating Internal Documents: 50500 / 133760
Migrating Internal Documents: 51000 / 133760
Migrating Internal Documents: 51500 / 133760
Migrating Internal Documents: 52000 / 133760
Migrating Internal Documents: 52500 / 133760
Migrating Internal Documents: 53000 / 133760
Migrating Internal Documents: 53500 / 133760
Migrating Internal Documents: 54000 / 133760
Migrating Internal Documents: 54500 / 133760
Migrating Internal Documents: 55000 / 133760
Migrating Internal Documents: 55500 / 133760
Migrating Internal Documents: 56000 / 133760
Migrating Internal Documents: 56500 / 133760
Migrating Internal Documents: 57000 / 133760
Migrating Internal Documents: 57500 / 133760
Migrating Internal Documents: 58000 / 133760
Migrating Internal Documents: 58500 / 133760
Migrating Internal Documents: 59000 / 133760
Migrating Internal Documents: 59500 / 133760
Migrating Internal Documents: 60000 / 133760
Migrating Internal Documents: 60500 / 133760
Migrating Internal Documents: 61000 / 133760
Migrating Internal Documents: 61500 / 133760
Migrating Internal Documents: 62000 / 133760
Migrating Internal Documents: 62500 / 133760
Migrating Internal Documents: 63000 / 133760
Migrating Internal Documents: 63500 / 133760
Migrating Internal Documents: 64000 / 133760
Migrating Internal Documents: 64500 / 133760
Migrating Internal Documents: 65000 / 133760
Migrating Internal Documents: 65500 / 133760
Migrating Internal Documents: 66000 / 133760
Migrating Internal Documents: 66500 / 133760
Migrating Internal Documents: 67000 / 133760
Migrating Internal Documents: 67500 / 133760
Migrating Internal Documents: 68000 / 133760
Migrating Internal Documents: 68500 / 133760
Migrating Internal Documents: 69000 / 133760
Migrating Internal Documents: 69500 / 133760
Migrating Internal Documents: 70000 / 133760
Migrating Internal Documents: 70500 / 133760
Migrating Internal Documents: 71000 / 133760
Migrating Internal Documents: 71500 / 133760
Migrating Internal Documents: 72000 / 133760
Migrating Internal Documents: 72500 / 133760
Migrating Internal Documents: 73000 / 133760
Migrating Internal Documents: 73500 / 133760
Migrating Internal Documents: 74000 / 133760
Migrating Internal Documents: 74500 / 133760
Migrating Internal Documents: 75000 / 133760
Migrating Internal Documents: 75500 / 133760
Migrating Internal Documents: 76000 / 133760
Migrating Internal Documents: 76500 / 133760
Migrating Internal Documents: 77000 / 133760
Migrating Internal Documents: 77500 / 133760
Migrating Internal Documents: 78000 / 133760
Migrating Internal Documents: 78500 / 133760
Migrating Internal Documents: 79000 / 133760
Migrating Internal Documents: 79500 / 133760
Migrating Internal Documents: 80000 / 133760
Migrating Internal Documents: 80500 / 133760
Migrating Internal Documents: 81000 / 133760
Migrating Internal Documents: 81500 / 133760
Migrating Internal Documents: 82000 / 133760
Migrating Internal Documents: 82500 / 133760
Migrating Internal Documents: 83000 / 133760
Migrating Internal Documents: 83500 / 133760

Fatal error: Uncaught TypeError: Appwrite\Database\Database::decode(): Argument #1 ($document) must be of type Appwrite\Database\Document, array given, called in /usr/src/code/src/Appwrite/Database/Database.php on line 554 and defined in /usr/src/code/src/Appwrite/Database/Database.php:533
Stack trace:
#0 /usr/src/code/src/Appwrite/Database/Database.php(554): Appwrite\Database\Database->decode(Array)
#1 /usr/src/code/src/Appwrite/Database/Database.php(171): Appwrite\Database\Database->decode(Object(Appwrite\Database\Document))
#2 /usr/src/code/src/Appwrite/Migration/Version/V11.php(180): Appwrite\Database\Database->getCollection(Array)
#3 /usr/src/code/app/tasks/migrate.php(110): Appwrite\Migration\Version\V11->execute()
#4 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}('0.12.3')
#5 /usr/src/code/app/cli.php(28): Utopia\CLI\CLI->run()
#6 {main}
  thrown in /usr/src/code/src/Appwrite/Database/Database.php on line 533

</details>

**Comment by stnguyen90** [comment]
Would you please provide more info like the output of the executed commands and what makes you think your migration failed?

**Comment by stnguyen90** [comment]
Something may be malformed in your database. Can you try to find out what that is? Maybe you can modify the source code to dump the info. Or you can turn on the general log for mariadb to see what queries are being executed and then you can execute it yourself to see what's in the database. If you want to try the general log, this [gist](https://gist.github.com/stnguyen90/afbeb9586a638cd3ae2f561c7bf250d7) might help.

**Comment by MaddPenguin** [comment]
@stnguyen90 I will try. Thanks for the suggestion. I am very new to this

**Comment by joeyouss** [comment]
Hi @MaddPenguin checking in to see if this is now fixed?

**Comment by eldadfux** [comment]
Closing as this issue seems stalled.
