### ISSUE TITLE
🚀 Feature: Allow larger filesize than 30mb in storage

### ISSUE THREAD

**Issue by rosenberg-c** [appwrite/appwrite#3263]
### 🔖 Feature description

It is not unreasonamble that someone would like to have support for large filesizes.
30mb is not eunough for example, uncompressed audio files.

### 🎤 Pitch

In my case, as someone that often handle large audio files and or video, 30mb is not nearly enough when wanting to work with high quality files.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
The limit is configurable via an environment variable. See https://appwrite.io/docs/environment-variables#storage

**Comment by rosenberg-c** [comment]
> The limit is configurable via an environment variable. See https://appwrite.io/docs/environment-variables#storage

Yes! Sorry, I knew this, but it slipped my mind at the moment.

**Comment by stnguyen90** [comment]
If there's nothing else, would you please close the issue?
