### ISSUE TITLE
dotnet runners not showing up

### ISSUE THREAD

**Issue by Alumniminium** [appwrite/appwrite#3265]
I've enabled all runtimes in my .env file as:

`node-14.5,node-15.5,node-16.0,node-17.0,php-8.0,php-8.1,ruby-3.0,ruby-3.1,python-3.8,python-3.9,python-3.10,deno-1.12,deno-1.13,deno-1.14,dart-2.12,dart-2.13,dart-2.14,dart-2.15,dart-2.16,dotnet-3.1,dotnet-6.0,java-8.0,java-11.0,java-17.0,swift-5.5,kotlin-1.6,cpp-17.0`

However, the only runtimes I'm able to select are

- Node.js 14.5
- Node.js 15.5
- Node.js 16.0
- Node.js 17.0
- PHP 8.0
- PHP 8.1
- Ruby 3.0
- Ruby 3.1
- Python 3.8
- Python 3.9
- Python 3.10
- Deno 1.12
- Deno 1.13
- Deno 1.14
- Dart 2.12
- Dart 2.13
- Dart 2.14
- Dart 2.15
- Dart 2.16
- Swift 5.5

Whats going on here? 
No Java, No dotnet, no cpp, no kotlin?
---
Appwrite Version: 0.13.0.300

**Comment by stnguyen90** [comment]
You need to upgrade to Appwrite 0.14.2 to have dotnet runtime

**Comment by Alumniminium** [comment]
you need to update the manual docker-compose.yml link in your docs
