### ISSUE TITLE
New database fields are not being saved

### ISSUE THREAD

**Issue by nonereally** [appwrite/appwrite#327]
When creating NEW "fields" in a database, only ONE can be added at a time.
An "Update" is required after each field is added, or all "new" fields will be lost.

---
Appwrite Version: UNKNOWN.0.6.0

**Comment by eldadfux** [comment]
1. Do you get any console errors?
2. What browser are you using?
3. Any chance you can add a gif or a short video to better visualise the issue?

**Comment by nonereally** [comment]
Will do a bit later...

**Comment by eldadfux** [comment]
Great 👍🏻

**Comment by eldadfux** [comment]
@nonereally please let me if this still happen in 0.6.1 so we could farther investigate.
