### ISSUE TITLE
🐛 Bug Report: https://appwrite.io/docs/models/preferences is empty

### ISSUE THREAD

**Issue by baas-enjoyer** [appwrite/appwrite#3271]
### 👟 Reproduction steps

Open https://appwrite.io/docs/models/preferences

In my case its empty. Take a look on this screenshot

![Uploading Screenshot 2022-05-22 at 11.28.34.png…]()

### 👍 Expected behavior

Something should be there

### 👎 Actual Behavior

Nothings there

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This is because preferences can be any json object including empty.
