### ISSUE TITLE
🐛 Bug Report: deleting attribute still used as index doesn't free up its index name

### ISSUE THREAD

**Issue by solnem** [appwrite/appwrite#3274]
### 👟 Reproduction steps

1. Open the Appwrite console
2. In the Database context, create a collection and open it
3. Navigate to the `Attributes` tab and create a new attribute (tested with string attribute, naming is not relevant)
4. Navigate to the `Indexes` tab and create a new index (remember the name of the index)
5. Add the index as is (should have the created attribute filled in already)
6. Navigate back to the `Attributes` tab and delete the attribute referenced in the index
6.1. (optional) Take not of the previously created index having been deleted
7. Re-create the attribute (tested with string attribute, naming is not relevant)
8. Navigate to the `Indexes` tab and re-create the index (use the same index name as before)
9. Add the index as is again (might need to refresh the page to update the list of attributes)
10. Notice the index status saying `failed`

https://user-images.githubusercontent.com/20548409/169799356-20fc4f67-1b35-442d-b5e4-c0f0f66edc01.mp4

### 👍 Expected behavior

The index with the same name as before gets created and the status becomes `available`.

### 👎 Actual Behavior

The index with the same name as before gets created and the status becomes `failed`.

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Locally deployed

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Probably related to https://github.com/appwrite/appwrite/issues/2902

**Comment by Meldiron** [comment]
We will investigate the underlying indexes logic before implementing a solution for this problem. The main question I currently have is "If there is an index with multiple attributes, and you delete one attribute, what should happen?". Once we know how exactly these indexes behave, we could either automatically delete it, or throw error to force developer to first do adjustments to the indexes.

**Comment by stnguyen90** [comment]
FYI, this is still occurring on 1.2.0. The appwrite-worker-databases log says:

```
Index already exists
```

**Comment by TorstenDittmann** [comment]
This should be fixed with 1.3.0 right? @abnegate

**Comment by abnegate** [comment]
@TorstenDittmann Yep, closing :+1:
