### ISSUE TITLE
🚀 Feature: deno open runtime support for arm

### ISSUE THREAD

**Issue by meepeek** [appwrite/appwrite#3278]
### 🔖 Feature description

I discussed with Drake in discord support channel and he advise me to open this request.

I use mac m1 and I cannot add deno function runtime for it is unsupported for arm. After searching web, I came across deno arm docker image as the following url which I then came to Drake as mentioned.

https://github.com/LukeChannings/deno-arm64

### 🎤 Pitch

It will make deno functions available for arm (pi and m1)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
At this point we prefer to support only official images.

Closing in favor of #6026.
