### ISSUE TITLE
[docs] Upgrade command is missing an /

### ISSUE THREAD

**Issue by didair** [appwrite/appwrite#329]
In the "Upgrade From an Older Version" the provided command is missing an `/` before `upgrade`.

Current: `docker exec appwrite upgrade`
Should be: `docker exec appwrite /upgrade`

For version `0.6.0`

https://appwrite.io/docs/installation

**Comment by eldadfux** [comment]
Gonna change the name of this action in 0.6.1 from upgrade to migrate, the name upgrade is really confusing and is not what actually being done behind the scenes.

**Comment by eldadfux** [comment]
We have just released version 0.6.1 🥳

Changed upgrade script name to ‘migrate’ to better reflect what it actually does (no slash now for real 😅) - also improved docs on appwrite.io to make sure everything is more clear.

If you need to upgrade from 0.6.0, all you need to do is change the Appwrite container image version number in your docker-compose.yml file and run `docker-compose up -d` in your terminal. No data migration is required.
