### ISSUE TITLE
🚀 Feature: gitlab oauth for other instances

### ISSUE THREAD

**Issue by omia** [appwrite/appwrite#3292]
### 🔖 Feature description

GitLab oauth asks for an serveraddress. So any (selfhostet) gitlab instant can be used.

### 🎤 Pitch

GitLab is often selfhostet and with this change any gitlab instant can be used for oauth.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Closing as this should be available as of 0.15.0
