### ISSUE TITLE
🐛 Bug Report: type 'Null' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by nmharmon8** [appwrite/appwrite#3293]
### 👟 Reproduction steps

Attempting to create a session from dart/flutter on version 5.0.0 throws ```type 'Null' is not a subtype of type 'int'```

```account.createSession(email: email, password: password);```

However the create call works fine. 

```account.create(email: email, password: password, userId: 'unique()');```

If I down grade to 3.0.1 both call work fine.

I am new to appwrite and dart, so this may just be me not knowing what I am doing.

Thanks.

### 👍 Expected behavior

Create a sesstion

### 👎 Actual Behavior

Throws exception

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Could you provide a stacktrace and the response that was returned from the server?

**Comment by nmharmon8** [comment]
I think I mismatched version. Working now. Thanks.
