### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Maxbrt18** [appwrite/appwrite#3300]
### 👟 Reproduction steps

When I want to deploy my nodejs appwrite function via CLI.

### 👍 Expected behavior

This should publish a NodeJS function on my server.

### 👎 Actual Behavior

I have an error : `✗ Error Request body larger than maxBodyLength limit`

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

I use Ubuntu 20 to host Appwrite. I had no problem deploying functions in python.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Do you have any reverse proxy like nginx?

Did you make sure node_modules was excluded from your deployment?

**Comment by Maxbrt18** [comment]
Thanks a lot, I didn't see that you have to exclude node_modules.

**Comment by Maxbrt18** [comment]
Thanks a lot, I didn't see that you have to exclude node_modules.
