### ISSUE TITLE
create project in one line command

### ISSUE THREAD

**Issue by haditabarzad** [appwrite/appwrite#3304]
### 👟 Reproduction steps

Hi
I'm writing some APIs for my panel to create user and project. both these two tasks have some challenges. 
In Appwrite CLI I did not find a way to create a member and project as easy as write one-line command. 
I will be happy to help me
Thanks

### 👍 Expected behavior

appwrite create member --email EMAIL --password PASS 
and
appwrite create project --email EMAIL --password PASS --projectname PROJ_NAME

### 👎 Actual Behavior

appwrite init project 
send arguments in input 

I did not find a way to create user(member)

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use VM

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by codercatdev** [comment]
Hi @haditabarzad, we have made some updates to the CLI. If you have upgraded you can use these commands.

```
appwrite client --projectId 12345
appwrite users create --userId "unique()" --email test@you.dev --password test1234!
```
Please let me know if that was what you were thinking

**Comment by stnguyen90** [comment]
@haditabarzad is there anything else you need or can this be closed? Please be advised, we'll need to close this due to inactivity soon.

**Comment by haditabarzad** [comment]
Thank you
you can close it
