### ISSUE TITLE
AppWrite puts the read and writes permissions of the database on the client-side. How does it prevent it from being attacked?

### ISSUE THREAD

**Issue by Aaron009** [appwrite/appwrite#3305]
### 💭 Description

I really can't find the relevant documentation. It is highly recommended to write an article about the security issues.

The following is my understanding of AppWrite, please correct me if there is any misunderstanding. Increase the read and write permissions of the database, and then add, delete, modify and query the database through the REST API, and the socket can monitor the changed data.

If I want to implement currency transactions between users, what should I do? AppWrite function?
As long as the server needs to validate the data in some scenarios, I'm at a loss. I don't know how to implement server-side data verification under AppWrite?

How can server attacks be prevented if the client can directly control database modifications?
For example, how to realize that an IP address can only register an account once a day? This judgment logic cannot be placed on the client, because the client can easily view and modify the code.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
> I don't know how to implement server-side data verification under AppWrite?

If any field level validation is required, you can make the document read only and expose a cloud function for updates. For example, see how [this](https://levelup.gitconnected.com/building-a-location-based-app-with-appwrite-48a2e2b6d4c2#8e5c) app was built.

> How can server attacks be prevented if the client can directly control database modifications?

For protecting documents, you would make them read only.

> For example, how to realize that an IP address can only register an account once a day?

Appwrite has rate limits enforced on various API endpoints and that's done by IP.

**Comment by Aaron009** [comment]
> If any field-level validation is required, you can make the document read-only and expose a cloud function for updates. For example, see how [this](https://levelup.gitconnected.com/building-a-location-based-app-with-appwrite-48a2e2b6d4c2#8e5c) app was built.
`cloud functions` can put client-side insecure code into `cloud functions`, the client makes requests through the REST API, and then `cloud functions` and the server performs additions, deletions, changes, and queries, and can also receive data changes in real-time. is this right?

> Appwrite has rate limits enforced on various API endpoints and that's done by IP.
If I want to add more conditional constraints, then I do it via "cloud functions", right?
For example, when requesting "REST API", can "Cloud Function" get some client-side "HTTP header" information? Such as IP, browser version, Referer, etc. 
If you can get it, can you give a relevant API document address?

**Comment by stnguyen90** [comment]
Yes and yes. The[functions](https://appwrite.io/docs/functions#writingYourOwnFunction) documentation has info about what's in the request parameter passed into the function.

**Comment by stnguyen90** [comment]
Is there anything else you need? If not, can you close this issue?
