### ISSUE TITLE
When add a custom domain, ignore domain you enter and use domain user to enter in console

### ISSUE THREAD

**Issue by jansenarruda** [appwrite/appwrite#331]
Hi, 

Add a custom domain don´t work

enter in console using https:\\xyz.com.br\console

them go to a project, setting, custom domain

Click add domain button

enter apw.xyz.com.br, and click Create

the screen display :

unverified       xyz.com.br             pending verification             verify domain

the domain is the same used to enter in console

if I try to create another domain with add domain button and enter ap1.xyz.com.br and click create, get a error.

If I enter wiht https:www.xyz.com.br, and try to make same proccess the domain add will be www.xyz.com.br (whatever I enter)

**Comment by eldadfux** [comment]
@jansenarruda thanks for reporting this. I found the issue and fixed it.

Will be released in 0.6.2.

**Comment by eldadfux** [comment]
Version 0.6.2 is out 🚀🎉

https://dev.to/eldadfux/announcing-the-release-of-the-appwrite-backend-server-v0-6-2-with-support-for-sign-in-with-apple-27cc

Full change log:  https://github.com/appwrite/appwrite/releases/tag/0.6.2
