### ISSUE TITLE
🐛 Bug Report: Can't createFile via n8n flow

### ISSUE THREAD

**Issue by theMeysam** [appwrite/appwrite#3313]
### 👟 Reproduction steps

When I try to add file to my appwrite storage by "create file" via API (Curl) it show bellow error:
`{
"status": "rejected",
"reason": {
"message": "500 - {"message":"Server Error","code":500,"type":"general_unknown","version":"0.14.2"}",
"name": "Error",
"stack": "Error: Request failed with status code 500 at createError 
REDACTED"
}
}`

### 👍 Expected behavior

It should add my image to storage

### 👎 Actual Behavior

ERROR: UNKNOWN ERROR - check the detailed error for more information
Server Error

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by theMeysam** [comment]
> 

Hi dear Meldiron

At first:
![Uploading Screenshot_20220602_021627.jpg…]()
About exact CURL:
I use API 3 json file from here on swaggerhub.com, my test app from Android, from som no code platform like n8n.io and other things.

**Comment by theMeysam** [comment]
![Uploading Screenshot_20220602_021627.jpg…]()

**Comment by stnguyen90** [comment]
> At first: https://i.ibb.co/C9hSL1y/Screenshot-20220602-021627.jpg 

Based on this screenshot, it doesn't seem like the request format is correct. The content type should be `multipart/form-data`, the name should be `file`, and the bytes should be the value.

Could you perhaps share your code?

**Comment by theMeysam** [comment]
@stnguyen90 
Thanks for your advice.

In fact I'm low coder person.
I use n8n (n8n.io) for my automation service.
I try to add some screenshots.
I also open issue on n8n community (n8n community).

After your advice I correct some options but I want to know what 8the correct format that I should send to my appwrite server.
fileId: unique(),
file:?

I also attached my new error from my docker compose logs.

appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/storage/buckets/:bucketId/files
appwrite                        | [Error] Type: TypeError
appwrite                        | [Error] Message: {closure}(): Argument #3 ($file) must be of type array, string given, called in /usr/src/cod
e/vendor/utopia-php/framework/src/App.php on line 593
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/storage.php
appwrite                        | [Error] Line: 360

**Comment by theMeysam** [comment]
![Screenshot_20220604_163003](https://user-images.githubusercontent.com/42879302/172025557-1bff7119-f0fc-45e0-9061-2a85e97ce9ae.jpg)

**Comment by stnguyen90** [comment]
It looks your sending "data" string for the file rather than sending the actual file. Maybe this will give you some insight into sending file data: https://community.n8n.io/t/trying-to-upload-a-file-to-an-http-endpoint/4459/2

Otherwise, things look fine on the Appwrite side.

**Comment by theMeysam** [comment]
Thanks your comment I could set data for file (I think).
The problem now is that appwrite server need "fileId" and I don't know how to send it to my appwrite server. :-(
![Screenshot_20220605_121322](https://user-images.githubusercontent.com/42879302/172040873-082e1ffe-f849-4054-847c-bda37e006b0d.jpg)

**Comment by stnguyen90** [comment]
> ![Screenshot_20220604_163003](https://user-images.githubusercontent.com/42879302/172025557-1bff7119-f0fc-45e0-9061-2a85e97ce9ae.jpg)

Do you still have the fileId body parameter and headers?

**Comment by theMeysam** [comment]
> > ![Screenshot_20220604_163003](https://user-images.githubusercontent.com/42879302/172025557-1bff7119-f0fc-45e0-9061-2a85e97ce9ae.jpg)
> 
> Do you still have the fileId body parameter and headers?

Yes, I have header properties that I cut from mentioned screenshot.
In http request node (on n8n) when I set "send binary data" true, there isn't any options to add another field that I add (for example) "fileId" value. :-(

**Comment by stnguyen90** [comment]
Ah sounds like it's [unsupported by  n8n](https://community.n8n.io/t/can-i-submit-mixed-data-using-form-for-example-multiple-files-and-text-field-data/13753). 

Someone did create an [Appwrite package for n8n](https://www.npmjs.com/package/n8n-nodes-appwrite) but it doesn't look like it supports file uploads yet. Perhaps you can submit a feature request.

**Comment by Meldiron** [comment]
Hey there 👋

As @stnguyen90 suggested, this is not natively supported by n8n. But there is a way! 😎

We can use Functions node to do this:

![CleanShot 2022-06-15 at 13 53 37](https://user-images.githubusercontent.com/19310830/173820998-320bd674-08f7-4f51-bc0e-9ab46b9c0c37.png)

In there, we will need to use `request-promise-native` so make sure to install that on your n8n device and specify it in the environment variables definition:

```sh
NODE_FUNCTION_ALLOW_EXTERNAL=request-promise-native
NODE_FUNCTION_ALLOW_BUILTIN=request-promise-native

# Not sure which one did it. One of them, maybe both 😅
```

Whith that ready, enter following code into your function node:

```js
const request = require('request-promise-native');

const binaryData = items[0].binary.data;

try {

  const data = await request({
  uri: "[YOUR_ENDPOINT]/v1/storage/buckets/[YOUR_BUCKET_ID]/files",
  method: "POST",
  headers: {
    'content-type': 'multipart/form-data',
    'x-appwrite-key': '[YOUR_API_KEY]',
    'x-appwrite-project': '[YOUR_PROJECT_ID]'
  },
  formData: {
    file: {
      value: Buffer.from(binaryData.data, 'base64'),
      options: {
        filename: binaryData.fileName,
        contentType: binaryData.mimeType,
      },
     },
     fileId: 'unique()'
  },
});
 
} catch(err) {
  return {ok: false, err: err};
}

return {ok:true};
```

> Make sure to enter your endpoint, project ID, bucket ID and API key in the code example.


With that, make sure you have a `file` defined before this node (in my case it was defined by another HTTP request node that was fetching file from an URL), and you are ready to execute the workflow.

In the end, you should see a successful execution and a file uploaded to your Appwrite Bucket:

![CleanShot 2022-06-15 at 13 57 30](https://user-images.githubusercontent.com/19310830/173821692-ea5f3619-b190-46b0-8865-76af201b5fdd.png)

![CleanShot 2022-06-15 at 13 52 56](https://user-images.githubusercontent.com/19310830/173821710-40c2ea35-7706-4572-bd15-80e50b3fe580.png)

I am attaching the whole workflow as a file. If you use it, make sure to replace all `XXXXX...` placeholders with your information.


[appwrite-storage-workflow.json.zip](https://github.com/appwrite/appwrite/files/8909035/appwrite-storage-workflow.json.zip)

**Comment by stnguyen90** [comment]
@theMeysam have you had a chance to test @Meldiron's suggestion? Is there anything else you need or can this be closed?

**Comment by stnguyen90** [comment]
Closing as no further action required.

**Comment by theMeysam** [comment]
Thank you @Meldiron 
It work as a charm for me.
Best regards;
