### ISSUE TITLE
🐛 Bug Report: Can't use my own domain in url for email validation process

### ISSUE THREAD

**Issue by squallsama** [appwrite/appwrite#3317]
### 👟 Reproduction steps

- Deploy appwrite on https://appwrite.mydomain.com
- Use await _account.createVerification(url: "https://mydomain.com/emailVerification");

### 👍 Expected behavior

Verification email sent

### 👎 Actual Behavior

AppwriteException: general_argument_invalid, Invalid url: URL host must be one of: localhost, appwrite.mydomain.com (400)

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by squallsama** [comment]
> Hey there 👋
> 
> I believe this could be a case of not having a hostname added as a platform in a project. Can we check that? When inside Appwrite Web Console, open your project and go to `Home` in the left menu. There, right under the graph, you should see the `Platforms` section.
> 
> Can you see `mydomain.com` there? If not, please click the `Add Platform` button, and add a web platform with this exact hostname. Now please retry sending the verification email - it should work this time.
> 
> If there is anything going wrong, don't hesitate to let me know.

I'll definitely check it. Thanks for the suggestion ! Will post update after that.

**Comment by rnconnected** [comment]
Hello, please I need help with this error "Invalid url: URL host must be one of: localhost, cloud.appwrite.io"

**Comment by prakashUXtech** [comment]
It was working fine till a few days back I guess, suddenly stoped working, I have added a wildcard domain in the platform hostname as well.

**Comment by durosly** [comment]
I am having similar issue too

**Comment by vishalchaurasia10** [comment]
yeah i am also having the same issue

**Comment by ShivamBhasin2002** [comment]
was this bug fixed I am still able to reproduce it

**Comment by optionedge** [comment]
I am also having the similar issue. I tried everything mentioned here still getting the following message:

I have added wildcard host, also specific host name but nothing is working.
It only worked when I added the subdomain where AppWrite is hosted (self-host) eg appwrite.mydomain.in

```
{
    "message": "Invalid `url` param: URL host must be one of: localhost, mydomain.in, *",
    "code": 400,
    "type": "general_argument_invalid",
    "version": "1.4.9"
}
```


@Meldiron Please help me here.  I can not deploy my app to production with this issue.
