### ISSUE TITLE
🐛 Bug Report: infinite loop on worker-deletes causes high redis memory use and frequent restarts

### ISSUE THREAD

**Issue by BrendanLester** [appwrite/appwrite#3320]
### 👟 Reproduction steps

I'm not sure exactly how it happened, but my project consists of 7 php functions and 3 collections and very, very little data.

It may or may not be related to the createAnonymousSession calls I was attempting for the first time (sorting svelte, CORS etc).
No browsers were open as this was occurring. 
Appwrite restarts did not resolve

I'm recording this information if it could be of use. Ultimately I wasn't able to resolve, so removed appwrite server and reinstalled.

The new install works and noticeably, the 'normal' calls to DeletesV1 don't loop.

I will update if I reproduce it.

### 👍 Expected behavior

**WORKER-DELETES** ( does not repeat & redis does not consume memory and restart)

A normal worker-deletes log after my reinstall.  I have bolded a bit below that differs to the actual behavior (the project details are populated below)

Executing delete function for chunk #1. Found 1 projects
Deleting chunk #1. Found 0 documents
Deleted 0 document by group in 0.0064218044281006 seconds
Deleting chunk #1. Found 0 documents
Deleted 0 document by group in 0.0037329196929932 seconds
Found 1 projects 0.018432855606079 seconds
[notice] (Job{v1-deletes} | ID: 108ff2c8e8b796c01ed69c174bf1f729 | DeletesV1 | [{"project":null,"type":"usage","document":null,"timestamp":null,"timestamp1d":1645442956,"timestamp30m":1653953356}]) has finished
[notice] Starting work on (Job{v1-deletes} | ID: 75b31c39e43e99c03ce23972b96726f5 | DeletesV1 | [{"project":null,"type":"realtime","document":null,"timestamp":1654082896,"timestamp1d":null,"timestamp30m":null}])
Executing delete function for chunk #1. Found 1 projects
Deleting chunk #1. Found 0 documents
Deleted 0 document by group in 0.0058891773223877 seconds
Found 1 projects 0.016784191131592 seconds
[notice] (Job{v1-deletes} | ID: 75b31c39e43e99c03ce23972b96726f5 | DeletesV1 | [{"project":null,"type":"realtime","document":null,"timestamp":1654082896,"timestamp1d":null,"timestamp30m":null}]) has finished
[notice] **Starting work on (Job{v1-deletes} | ID: 7075ed5eb93f9ad8e0a23d744c3d0209 | DeletesV1 | [{"project":{"teamId":"62974b98bd5221a671ab","name":"project**-1","description":"","logo":"","url":"","version":"0.14.2","legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","services":[],"auths":{"limit":0,"emailPassword":true,"usersAuthMagicURL":true,"anonymous":true,"invites":true,"JWT":true,"phone":true},"authProviders":[],"platforms":[],"webhooks":[],"keys":[{"projectId":"62974b98c2f4249d3c59","name":"Server API Key","scopes":["users.read","users.write","teams.read","teams.write","collections.read","collections.write","attributes.read","attributes.write","indexes.read","indexes.write","documents.read","documents.write","files.read","files.write","buckets.read","buckets.write","functions.read","functions.write","execution.read","execution.write","locale.read","avatars.read","health.read"],"secret":"2051bcbca2791701cbbd0cee6d7f48fffa08bdb271e9760d2cb9f9768d9d416598c44d67cf9a32cd2472f6df24b92e57669144a652b5f5d9e323574ae0eaf9050d2c569f849b48e7e37a51c8c3d2d0ea907c8992cc6c2e3d23232132faf19ed2558cf0df0e19905a2d26270278120354f413a3c1db8fecee3efb80df45d4fe41","$id":"62974c4b9a34a8f7b20f","$internalId":"1","$read":["role:all"],"$write":["role:all"],"$collection":"keys"}],"domains":[],"search":"62974b98c2f4249d3c59 project-1","$read":["team:62974b98bd5221a671ab"],"$write":["team:62974b98bd5221a671ab\/developer","team:62974b98bd5221a671ab\/owner"],"$id":"62974b98c2f4249d3c59","$internalId":"1","$collection":"projects"},"type":"document","document":{"name":"Green Inc.","email":"percey@green.com","status":false,"password":"$2y$08$ICQ4RGBDv6Jwqs0K9tmatuFFbpiDRgAeGQxjbz3J\/OIDsYQhhrERi","passwordUpdate":1654082778,"prefs":[],"registration":1654082778,"emailVerification":false,"reset":false,"sessions":[],"tokens":[],"memberships":[],"search":"62974cdac5d005bf00ae percey@green.com Green Inc.","$read":["role:all"],"$write":["user:62974cdac5d005bf00ae"],"$id":"62974cdac5d005bf00ae","$internalId":"1","$collection":"users"},"timestamp":null,"timestamp1d":null,"timestamp30m":null}])
Deleting chunk #1. Found 0 documents
Deleted 0 document by group in 0.0018579959869385 seconds

### 👎 Actual Behavior

Snippets below of the very busy logs as Redis memory went high and the redis container would restart every few minutes and repeat. 

I have bolded a bit below that differs to potentially normal behavior (the project details are missing below)

**WORKER-DELETES** (repeats continuously)
[notice] (Job{v1-deletes} | ID: ec1c99093cc5be3fa478d97648ecea78 | DeletesV1 | [{"project":null,"type":"usage","document":null,"timestamp":null,"timestamp1d":1645270399,"timestamp30m":1653780799}]) has finished
[notice] Starting work on (Job{v1-deletes} | ID: 82e53bf1a846080354b6da0e45c1c0b8 | DeletesV1 | [{"project":null,"type":"realtime","document":null,"timestamp":1653910339,"timestamp1d":null,"timestamp30m":null}])
Executing delete function for chunk #1. Found 1 projects
Deleting chunk #1. Found 0 documents
Deleted 0 document by group in 0.00063300132751465 seconds
Found 1 projects 0.0062370300292969 seconds
[notice] (Job{v1-deletes} | ID: 82e53bf1a846080354b6da0e45c1c0b8 | DeletesV1 | [{"project":null,"type":"realtime","document":null,"timestamp":1653910339,"timestamp1d":null,"timestamp30m":null}]) has finished
[notice] **Starting work on (Job{v1-deletes} | ID: 09b2a0fbf85f06285e5456f6a06fb0ea | DeletesV1 | [{"project":null,"**type":"executions","document":null,"timestamp":1653910399,"timestamp1d":null,"timestamp30m":null}])

**REDIS container** (repeats continuously - as seen via  'docker exec -it <containerid> redis-cli monitor', not docker logs)
1654081494.605789 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"audit\",\"document\":null,\"timestamp\":1654081494,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"15ea12ec5db6467cb1acf9f526a6ce3a\",\"prefix\":\"\",\"queue_time\":1654081494.604748}"
1654081494.605841 [0 172.24.0.12:51032] "SET" "resque:job:6093c3b1a3c37ca7fac21154f7fda173:pid" "7"
1654081494.606260 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.606273 [0 172.24.0.12:51034] "GET" "cache-_console:_metadata:projects"
1654081494.606894 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"usage\",\"document\":null,\"timestamp\":null,\"timestamp1d\":1645441494,\"timestamp30m\":1653951894}],\"id\":\"db7f3ab434953e2ccfea996c06eaf224\",\"prefix\":\"\",\"queue_time\":1654081494.606024}"
1654081494.607316 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.607328 [0 172.24.0.12:51034] "GET" "cache-_console:_metadata:platforms"
1654081494.607719 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"realtime\",\"document\":null,\"timestamp\":1654081434,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"156dd33f4a3b0d280b461a8490d99878\",\"prefix\":\"\",\"queue_time\":1654081494.607071}"
1654081494.608006 [0 172.24.0.20:59928] "GET" "cache-_console:_metadata:certificates"
1654081494.609365 [0 172.24.0.12:51034] "GET" "cache-_console:_metadata:webhooks"
1654081494.609379 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.609610 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"executions\",\"document\":null,\"timestamp\":1654081494,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"57621fa379eef0e5ef9f5603083da117\",\"prefix\":\"\",\"queue_time\":1654081494.609259}"
1654081494.610248 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.610668 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"abuse\",\"document\":null,\"timestamp\":1653995094,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"50e4ad7a8e011a49cbcc31ad22ba0f44\",\"prefix\":\"\",\"queue_time\":1654081494.610001}"
1654081494.610719 [0 172.24.0.12:51034] "GET" "cache-_console:_metadata:keys"
1654081494.611108 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.611469 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"audit\",\"document\":null,\"timestamp\":1654081494,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"08fdb4850d489e4caef890757e653033\",\"prefix\":\"\",\"queue_time\":1654081494.61088}"
1654081494.611895 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.612102 [0 172.24.0.12:51034] "GET" "cache-_console:_metadata:domains"
1654081494.612725 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"usage\",\"document\":null,\"timestamp\":null,\"timestamp1d\":1645441494,\"timestamp30m\":1653951894}],\"id\":\"2775404c08995a65a1e5ff5511315c62\",\"prefix\":\"\",\"queue_time\":1654081494.611656}"
1654081494.613514 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.613526 [0 172.24.0.12:51034] "GET" "cache-_62836b7ab01379c3a012:_metadata:projects"
1654081494.614094 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"realtime\",\"document\":null,\"timestamp\":1654081434,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"6f9e0a8f955f3f0591b06560ede8b058\",\"prefix\":\"\",\"queue_time\":1654081494.61346}"
1654081494.614146 [0 172.24.0.12:51034] "GET" "cache-_62836b7ab01379c3a012:projects:62836b7ab01379c3a012"
1654081494.614376 [0 172.24.0.20:59928] "GET" "cache-_console:_metadata:certificates"
1654081494.615902 [0 172.24.0.12:51034] "GET" "cache-_62836b7ab01379c3a012:_metadata:realtime"
1654081494.615932 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.616103 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"executions\",\"document\":null,\"timestamp\":1654081494,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"9bff2ba7cf42ede1f77b1020d96441d7\",\"prefix\":\"\",\"queue_time\":1654081494.61566}"
1654081494.616454 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.616587 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"abuse\",\"document\":null,\"timestamp\":1653995094,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"e3da412079404ae827ba64ab39d3bcf2\",\"prefix\":\"\",\"queue_time\":1654081494.616397}"
1654081494.616955 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.617084 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"audit\",\"document\":null,\"timestamp\":1654081494,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"ace4ddac14eb93c9f5137f7a0580b6c7\",\"prefix\":\"\",\"queue_time\":1654081494.616885}"
1654081494.617454 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.617797 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"usage\",\"document\":null,\"timestamp\":null,\"timestamp1d\":1645441494,\"timestamp30m\":1653951894}],\"id\":\"ca82c5ff63125765a9acea5aada2f8e9\",\"prefix\":\"\",\"queue_time\":1654081494.617386}"
1654081494.617877 [0 172.24.0.12:51032] "EXISTS" "resque:job:6093c3b1a3c37ca7fac21154f7fda173:status"
1654081494.618199 [0 172.24.0.12:51032] "DEL" "resque:job:6093c3b1a3c37ca7fac21154f7fda173:pid"
1654081494.618215 [0 172.24.0.20:59930] "SADD" "resque:queues" "v1-deletes"
1654081494.618351 [0 172.24.0.20:59930] "RPUSH" "resque:queue:v1-deletes" "{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"realtime\",\"document\":null,\"timestamp\":1654081434,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"d921caea7c1b1fae67709f7d07ff6895\",\"prefix\":\"\",\"queue_time\":1654081494.617968}"
1654081494.618419 [0 172.24.0.12:51032] "INCRBY" "resque:stat:processed" "1"
1654081494.618652 [0 172.24.0.12:51032] "INCRBY" "resque:stat:processed:4382db1d07b0:7:v1-deletes" "1"
1654081494.618773 [0 172.24.0.12:51032] "DEL" "resque:worker:4382db1d07b0:7:v1-deletes"
1654081494.618788 [0 172.24.0.20:59928] "GET" "cache-_console:_metadata:certificates"
1654081494.619020 [0 172.24.0.12:51032] "PING"
1654081494.619127 [0 172.24.0.12:51032] "LPOP" "resque:queue:v1-deletes"
1654081494.619259 [0 172.24.0.12:51032] "EXISTS" "resque:job:a76436484cf4264ef659304072ce61e7:status"
1654081494.619373 [0 172.24.0.12:51032] "SET" "resque:worker:4382db1d07b0:7:v1-deletes" "{\"queue\":\"v1-deletes\",\"run_at\":\"2022-06-01T11:04:54+00:00\",\"payload\":{\"class\":\"DeletesV1\",\"args\":[{\"project\":null,\"type\":\"executions\",\"document\":null,\"timestamp\":1653910398,\"timestamp1d\":null,\"timestamp30m\":null}],\"id\":\"a76436484cf4264ef659304072ce61e7\",\"prefix\":\"\",\"queue_time\":1653910398.391676}}"

**INFLUXDB**  (lots and lots of this)
ts=2022-06-01T10:46:08.453586Z lvl=info msg="Executing query" log_id=0aohpVBl000 service=query query="SELECT sum(value) AS value FROM telegraf.autogen.appwrite_usage_executions_all WHERE time > '2022-06-01T00:00:00+00:00' AND time < '2022-06-01T10:46:08+00:00' AND metric_type = 'counter' GROUP BY time(1d), projectId"
[httpd] 172.24.0.17 - - [01/Jun/2022:10:46:08 +0000] "GET /query?db=telegraf&q=SELECT+sum%28value%29+AS+%22value%22+FROM+%22appwrite_usage_executions_all%22+WHERE+%22time%22+%3E+%272022-06-01T00%3A00%3A00%2B00%3A00%27+AND+%22time%22+%3C+%272022-06-01T10%3A46%3A08%2B00%3A00%27+AND+%22metric_type%22%3D%27counter%27++GROUP+BY+time%281d%29%2C+%22projectId%22++FILL%28null%29 HTTP/1.1" 200 33 "-" "-" 0b6bc3ae-e198-11ec-87f4-0242ac180002 665
ts=2022-06-01T10:46:08.455476Z lvl=info msg="Executing query" log_id=0aohpVBl000 service=query query="SELECT sum(value) AS value FROM telegraf.autogen.appwrite_usage_database_collections_create WHERE time > '2022-05-31T10:46:08+00:00' AND time < '2022-06-01T10:46:08+00:00' AND metric_type = 'counter' GROUP BY time(30m), projectId"
[httpd] 172.24.0.17 - - [01/Jun/2022:10:46:08 +0000] "GET /query?db=telegraf&q=SELECT+sum%28value%29+AS+%22value%22+FROM+%22appwrite_usage_database_collections_create%22+WHERE+%22time%22+%3E+%272022-05-31T10%3A46%3A08%2B00%3A00%27+AND+%22time%22+%3C+%272022-06-01T10%3A46%3A08%2B00%3A00%27+AND+%22metric_type%22%3D%27counter%27++GROUP+BY+time%2830m%29%2C+%22projectId%22++FILL%28null%29 HTTP/1.1" 200 33 "-" "-" 0b6c0a06-e198-11ec-87f5-0242ac180002 620
ts=2022-06-01T10:46:08.457242Z lvl=info msg="Executing query" log_id=0aohpVBl000 service=query query="SELECT sum(value) AS value FROM telegraf.autogen.appwrite_usage_database_collections_create WHERE time > '2022-03-03T10:46:08+00:00' AND time < '2022-06-01T10:46:08+00:00' AND metric_type = 'counter' GROUP BY time(1d), projectId"
[httpd] 172.24.0.17 - - [01/Jun/2022:10:46:08 +0000] "GET /query?db=telegraf&q=SELECT+sum%28value%29+AS+%22value%22+FROM+%22appwrite_usage_database_collections_create%22+WHERE+%22time%22+%3E+%272022-03-03T10%3A46%3A08%2B00%3A00%27+AND+%22time%22+%3C+%272022-06-01T10%3A46%3A08%2B00%3A00%27+AND+%22metric_type%22%3D%27counter%27++GROUP+BY+time%281d%29%2C+%22projectId%22++FILL%28null%29 HTTP/1.1" 200 33 "-" "-" 0b6c5248-e198-11ec-87f6-0242ac180002 543
ts=2022-06-01T10:46:08.459586Z lvl=info msg="Executing query" log_id=0aohpVBl000 service=query query="SELECT sum(value) AS value FROM telegraf.autogen.appwrite_usage_database_collections_read WHERE time > '2022-05-31T10:46:08+00:00' AND time < '2022-06-01T10:46:08+00:00' AND metric_type = 'counter' GROUP BY time(30m), projectId"

**MAINTENANCE Container**  (repeats continuously)
[01-06-2022 10:45:30] Notifying workers with maintenance tasks every 0 seconds
[01-06-2022 10:45:30] No certificates for renewal.
[01-06-2022 10:45:30] Notifying workers with maintenance tasks every 0 seconds
[01-06-2022 10:45:30] No certificates for renewal.
[01-06-2022 10:45:30] Notifying workers with maintenance tasks every 0 seconds
[01-06-2022 10:45:30] No certificates for renewal.

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by highoctanehosting** [comment]
I also am experiencing this issue. There seems to be many flaws in how Appwrite utilizes Redis at the moment. I discussed some with the team via Discord and I saw that they are testing my suggestions to limit memory and CPU usage in the docker-compose.yml file. I see that this issue is already 27 days old and no one has been assigned to look at it yet. I hope this issue is resolved for you soon.

**Comment by stnguyen90** [comment]
@BrendanLester, do you have the following env vars set in your .env file?

```
_APP_MAINTENANCE_INTERVAL=86400
_APP_MAINTENANCE_RETENTION_EXECUTION=1209600
_APP_MAINTENANCE_RETENTION_ABUSE=86400
_APP_MAINTENANCE_RETENTION_AUDIT=1209600
```

**Comment by highoctanehosting** [comment]
@stnguyen90 I'm not sure about Brendan but I added those to my .env file and it seems to have resolved the memory issue. In process monitor I can see that the redis server has reserved 1G of RAM.

**Comment by BrendanLester** [comment]
@stnguyen90 I didn't set any of those deliberately on either that problematic instance or subsequent. They would have been whatever the defaults were at the time (on 0.14.x). I had removed that instance shortly after, so can't check.

**Comment by stnguyen90** [comment]
Closing as this should no longer be a problem.
