### ISSUE TITLE
🐛 Bug Report: Cron triggered jobs does not execute after migration

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#3321]
### 👟 Reproduction steps

when i start migration to new version my cron triggered jobs does not execute.

after i went to appwrite console and change one of the values in cloud function definition its starting.
but if i make a mistake and save the form again, its excuting twice

### 👍 Expected behavior

it should not be possible that a cloud function is executing twice when its triggered by cron

### 👎 Actual Behavior

its not executing or twice after i updated the function

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This is probably due to redis being wiped after upgrade/migration. The workaround right now is to update the schedule to something else and change it back to kickstart it again.

**Comment by stnguyen90** [comment]
https://github.com/appwrite/appwrite/pull/4704 has updated the migrate script to no longer flush all of redis: https://github.com/appwrite/appwrite/pull/4704/files#diff-a112f48e271868e93847561a2ef11f1ec93a6f2dbae4c6dd326c7e3620a4540d
