### ISSUE TITLE
DEPLOYING A FUNCTION : Automatic Dart main file has a little mistake in it

### ISSUE THREAD

**Issue by sylvainjack** [appwrite/appwrite#3322]
When we want to create an appwrite function using DART. The main.dart that is "prepared" for us has a small mistake. It checks twice if "API KEY" is null.

**Comment by stnguyen90** [comment]
The user is referring to the functions-starter code: https://github.com/appwrite/functions-starter/blob/93e23292bf209bc2db59633cba58963cfc1fb64c/dart-2.16/lib/main.dart#L33

**Comment by Meldiron** [comment]
Thanks for reporting this 😇 I created a PR to fix this.

PR reviews are highly appreciated.

**Comment by stnguyen90** [comment]
Closing as PR was merged.
