### ISSUE TITLE
🚀 Feature: Appwrite Query Character Limit Changeable

### ISSUE THREAD

**Issue by Infinil** [appwrite/appwrite#3329]
### 🔖 Feature description

Query Character Limit should be above 128 characters or there should be an option to remove this limit for URL attributes atleast.

### 🎤 Pitch

Recently in Appwrite 0.14 an update was pushed which limits the size of query to 128 characters for an attribute. Let's say my database has URL attribute and I want to list the documents with that URL [key index] then it can very easily surpass the character limit and can result in error while listing the documents. Hence I think this change is important. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
FYI, the limit in question here is the `new Text(128)` as part of the `queries` [validation](https://github.com/appwrite/appwrite/blob/f1afc45ae2007bc49a9a0509ed25109c8c11705c/app/controllers/api/database.php#L1605).

**Comment by Infinil** [comment]
> FYI, the limit in question here is the `new Text(128)` as part of the `queries` [validation](https://github.com/appwrite/appwrite/blob/f1afc45ae2007bc49a9a0509ed25109c8c11705c/app/controllers/api/database.php#L1605).

Yes but it wasn't like that before 0.14 update right?

**Comment by stnguyen90** [comment]
@Meldiron, would you be able to comment on this? This looks like the related commit: https://github.com/appwrite/appwrite/commit/d36a2602ed22843dad78ded063ae477956934619.

**Comment by superseby2** [comment]
Just adding to the thread. I am encountering the pb with a simple query which goes like this Query.equal("id",[<an rray of 20 items>]) (so no need to have a query using URLs)
Quite an issue for us at the moment as the whole service works for some and not for others. Thx!

**Comment by stnguyen90** [comment]
@superseby2, what version of Appwrite are you on? This should have actually been released. 🧐

**Comment by superseby2** [comment]
Oh I see. Thx @stnguyen90  I am a version behind (I had just finished migrating our functions when 0.15 went out and could do it again :)) . 
Thx!

**Comment by superseby2** [comment]
Could not find the info in the releases changes but is there still a limit we should be aware of or the limit is gone ?

Thx again.

**Comment by stnguyen90** [comment]
> Could not find the info in the releases changes but is there still a limit we should be aware of or the limit is gone ?

@superseby2, yes there is a limit:

https://github.com/appwrite/appwrite/blob/7ea8c3d1732e9f049d682d073e5371e39782a621/app/controllers/api/databases.php#L1945

Each query value is limited to `APP_LIMIT_ARRAY_ELEMENT_SIZE` (which is [4096](https://github.com/appwrite/appwrite/blob/7ea8c3d1732e9f049d682d073e5371e39782a621/app/init.php#L89)). There is a limit of `APP_LIMIT_ARRAY_PARAMS_SIZE` values (which is [100](https://github.com/appwrite/appwrite/blob/7ea8c3d1732e9f049d682d073e5371e39782a621/app/init.php#L88)).

It's also documented in the description of the queries parameter of the [List Documents](https://appwrite.io/docs/client/databases?sdk=web-default#databasesListDocuments) API.

Closing as this should be resolved now.
