### ISSUE TITLE
UNKNOWN version

### ISSUE THREAD

**Issue by FathiQ** [appwrite/appwrite#333]
---
Appwrite Version: UNKNOWN.125

**Comment by luiscruzurvenue** [comment]
@eldadfux this should be repaired too.

**Comment by eldadfux** [comment]
@FathiQ would be great to get more info on this one:
* Screenshots?
* Whats env are you running?
* Did you install Appwrite from source?

Any info will be helpful

**Comment by luiscruzurvenue** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/55716036/82622724-19eb1500-9ba4-11ea-9583-a14a60d2c96e.png)

I'm running Appwrite for server (i don't know if that answers your question).

I have installed Appwrite with Docker, following the docks instructions.

**Comment by eldadfux** [comment]
Whats is your OS? Do you get any other errors? Please share your local docker-compose.yml (note to hide any secrets you might be using before pasting)

**Comment by FathiQ** [comment]
Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by eldadfux** [comment]
Darwin 19.4.0 should be fine. I think the docker-compose.yml file Appwrite has downloaded to your host during installation should give us a hint of the problem. It should be located in an 'appwrite' directory where you executed the installation command.

**Comment by FathiQ** [comment]
`version: '3'

services:
    traefik:
        image: traefik:v2.1.4
        command:
            - --providers.file.directory=/storage/config
            - --providers.file.watch=true
            - --providers.docker=true
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - appwrite-config:/storage/config:ro
            - appwrite-certificates:/storage/certificates:ro
        depends_on:
            - appwrite
        networks:
            - gateway
            - appwrite
    
    appwrite:
        image: appwrite/appwrite:0.6.0
        restart: unless-stopped
        networks:
            - appwrite
        labels:
            - traefik.http.routers.appwrite.rule=PathPrefix(`/`)
            - traefik.http.routers.appwrite-secure.rule=PathPrefix(`/`)
            - traefik.http.routers.appwrite-secure.tls=true
        volumes:
            - appwrite-uploads:/storage/uploads:rw
            - appwrite-cache:/storage/cache:rw
            - appwrite-config:/storage/config:rw
            - appwrite-certificates:/storage/certificates:rw
        depends_on:
            - mariadb
            - redis
            - smtp
            - clamav
            - influxdb
            - telegraf
        environment:
            - _APP_ENV=production
            - _APP_OPENSSL_KEY_V1=your-secret-key
            - _APP_DOMAIN=localhost
            - _APP_DOMAIN_TARGET=localhost
            - _APP_REDIS_HOST=redis
            - _APP_REDIS_PORT=6379
            - _APP_DB_HOST=mariadb
            - _APP_DB_PORT=3306
            - _APP_DB_SCHEMA=appwrite
            - _APP_DB_USER=user
            - _APP_DB_PASS=password
            - _APP_INFLUXDB_HOST=influxdb
            - _APP_INFLUXDB_PORT=8086
            - _APP_STATSD_HOST=telegraf
            - _APP_STATSD_PORT=8125
            - _APP_SMTP_HOST=smtp
            - _APP_SMTP_PORT=25

    mariadb:
        image: appwrite/mariadb:1.0.3
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-mariadb:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=rootsecretpassword
            - MYSQL_DATABASE=appwrite
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        command: 'mysqld --innodb-flush-method=fsync'

    smtp:
        image: appwrite/smtp:1.0.1
        restart: unless-stopped
        networks:
            - appwrite
        environment:
            - MAILNAME=appwrite
            - RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16

    redis:
        image: redis:5.0
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-redis:/data:rw

    clamav:
        image: appwrite/clamav:1.0.8
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-uploads:/storage/uploads

    influxdb:
        image: influxdb:1.6
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-influxdb:/var/lib/influxdb:rw

    telegraf:
        image: appwrite/telegraf:1.0.0
        restart: unless-stopped
        networks:
            - appwrite

networks:
    gateway:
    appwrite:

volumes:
    appwrite-mariadb:
    appwrite-redis:
    appwrite-cache:
    appwrite-uploads:
    appwrite-certificates:
    appwrite-influxdb:
    appwrite-config:
`

**Comment by eldadfux** [comment]
Found the problem. Created a fix. Will be release in 0.6.1.

Thank you for reporting this!

**Comment by eldadfux** [comment]
We have just released version 0.6.1 🥳

If you need to upgrade from 0.6.0, all you need to do is change the Appwrite container image version number in your docker-compose.yml file and run `docker-compose up -d` in your terminal. No data migration is required.
