### ISSUE TITLE
🐛 Bug Report: First execution unnecessarily slow

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#3332]
### 👟 Reproduction steps

If you don't execute the function for too long, it stops the runtime. This means, the next execution will take extra time, as it also needs to start.
That is all good, but the problem is, that there seems to be an extra delay after execution successfully finishes.

As seen in this video:

https://user-images.githubusercontent.com/19310830/172016645-c4094da0-f8b5-47e5-a7a6-9a1aba7b1810.mp4

(notice real-time balance gets updated, and like 1 second later the alert appears. This 1s is a delay between execution finishing, and getting execution response)

To reproduce:

1. Make a client app that has a real-time subscription to a document, and a button to execute the function
2. Make a function that updates a document
3. Deploy function (to ensure there is no runtime prepared for this deployment)
4. Click the button to execute a function in the client app

### 👍 Expected behavior

As soon as the document updates, I get an execution response. This is a case for executions after the first one.

Video of how fast execution responses are after the first one:

https://user-images.githubusercontent.com/19310830/172016688-fc14768d-d669-4485-9341-4a42fef9631f.mp4

### 👎 Actual Behavior

After the function finishes (updates document), there is still like 1s delay before getting a response.

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
I believe it comes down to this like of the code: https://github.com/appwrite/appwrite/blob/master/src/Executor/Executor.php#L200

It can create up to 2 seconds delay between when the function is done executing, and when the client receives a response of the `async=false` execution.

**Comment by Meldiron** [comment]
Addressed in a PT aabove. delay is necessary, but it was running in cases when it shouldn't. PR solves it.

**Comment by joeyouss** [comment]
Closing since the PR is merged
