### ISSUE TITLE
[docs] broken tag links

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#334]
When clicking on a hash/tag link on the Server API docs the URL becomes broken.

`https://appwrite.io/docs/server/users`
becomes
`https://appwrite.io/docs/users#create`
instead of
`https://appwrite.io/docs/server/users#create`

**Comment by eldadfux** [comment]
Thanks for reporting this @TorstenDittmann ! just fixed in the homepage repo. I will push the change with 0.6.1

**Comment by eldadfux** [comment]
We have just released version 0.6.1 🥳

If you need to upgrade from 0.6.0, all you need to do is change the Appwrite container image version number in your docker-compose.yml file and run `docker-compose up -d` in your terminal. No data migration is required.
