### ISSUE TITLE
🐛 Bug Report: Index not removed properly

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#3342]
### 👟 Reproduction steps

When I delete attribute, indexes related to the attribute are properly deleted from UI, but probably not from the backend.

1. Create project, collection
2. Create FLOAT attribute `createdAt`
3. Create index `createdAt`, using attribute `createdAt`
4. Delete attribute `createdAt` (notice index is also gone, as expected)
5. Create INTEGER attribute `createdAt`
6. Create index `createdAt` using attribute `createdAt`

Index will now have status `failed`

### 👍 Expected behavior

Create an index without a problem. The problem could be in the metadata or the underlying table. Either way, I believe it starts in the deletes worker - not deleting something properly.

### 👎 Actual Behavior

Index creation on the step 6 fails with a simple log in database worker:

```
appwrite-worker-database  | Index already exists
```

No logs in `worker-deletes`.

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
If anyone is looking for solutions, as of right now these work:

- Delete the collection, and create it from scratch
- Name index differently when creating it the second time

**Comment by stnguyen90** [comment]
This seems like a duplicate of https://github.com/appwrite/appwrite/issues/3274 and possibly related to https://github.com/appwrite/appwrite/issues/2902

**Comment by fogelito** [comment]
I saw this issue as well, I would say or to throw an exception "Please delete index first.." or delete the index as well, which can be a problem if the index is created from a several attributes.

**Comment by Meldiron** [comment]
> This seems like a duplicate of #3274 and possibly related to #2902

Great catch! Closing this issue in favour of https://github.com/appwrite/appwrite/issues/3274
