### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by luiscruzurvenue** [appwrite/appwrite#335]
There's a minor syntax error when viewing documents, the title says 'Documnets' instead of 'Documents':

![image](https://user-images.githubusercontent.com/55716036/82621280-4ac94b00-9ba0-11ea-9786-42064f3b73c9.png)

**Comment by eldadfux** [comment]
@luiscruzurvenue thanks for reporting this. Just fixed it, will be release in 0.6.1

**Comment by eldadfux** [comment]
We have just released version 0.6.1 🥳

If you need to upgrade from 0.6.0, all you need to do is change the Appwrite container image version number in your docker-compose.yml file and run `docker-compose up -d` in your terminal. No data migration is required.
