### ISSUE TITLE
🐛 Bug Report: Missing default client icon

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#3353]
### 👟 Reproduction steps

Not exactly sure, I just noticed this on a production server.

Screenshots show that visitor probably used Instagram in-app browser, and now Appwrite can't show proper icon:

![CleanShot 2022-06-08 at 13 46 59](https://user-images.githubusercontent.com/19310830/172609290-e27b7443-6269-4815-a55c-e1b24b0a711d.png)

![CleanShot 2022-06-08 at 13 46 42](https://user-images.githubusercontent.com/19310830/172609297-f32999a1-435a-4109-aad6-024516858ea4.png)

### 👍 Expected behavior

- Let's try to have as many clients supported as possible. Maybe there is some list we can use?
- If client doesn't properly provide all information, or is not supported, let's have question mark (or similar) instead of client icon

### 👎 Actual Behavior

Shows missing icon, as seen on image above.

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Closed this issue as of now. This can be reopened if the problem persists in newer versions of console.
