### ISSUE TITLE
How i can get url of uploaded file after uploading?

### ISSUE THREAD

**Issue by hopheylalaley84** [appwrite/appwrite#3355]
### 👟 Reproduction steps

How i can get url of uploaded file after uploading?

### 👍 Expected behavior

How i can get url of uploaded file after uploading?

### 👎 Actual Behavior

How i can get url of uploaded file after uploading?

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
The id of the file should be returned after successfully uploading. The URL of the file is in the [docs](https://appwrite.io/docs/client/storage). For example, to view the file, use the [view API]( https://appwrite.io/docs/client/storage?sdk=web-default#storageGetFileView).

**Comment by hopheylalaley84** [comment]
I use flutter. There are many plugins working with URL. To show PDF for example. In Firebase, after uploading file, i got back URL, and write it to table. But in appwrite i get only File ID. How i can get file url for Flutter SDK?

**Comment by stnguyen90** [comment]
I would save the file id to the database. As it shows on the docs, the URL for viewing is `/v1/storage/buckets/{bucketId}/files/{fileId}/view`.

**Comment by Meldiron** [comment]
Hey there 👋 Let me also use this moment to invite you to our [Discord server](https://appwrite.io/discord), where thousands of Apwrite developers chat together and help each other.
To be honest, you got pretty lucky to get an answer on GitHub within 15 minutes 😅

I am not a Flutter expert, but I can see there is some language-specific logic regarding saving files and previewing the file - as seen in the example: https://appwrite.io/docs/client/storage?sdk=flutter-default#storageGetFileDownload

If you still need a string URL to solve your problem, you can build one when you know bucketID and fileID. The URL looks like `https://YOUR_ENDPOINT/v1/storage/buckets/YOUR_BUCKET_ID/files/YOUR_FILE_ID/preview?project=trackmaniaDailyStats&width=500&height=200`

You can commit width, height, or both. I would recommend storing only fileId (and bucketId if needed), and doing this conversion into an URL after fetching it from database. That way you can still control configuration such as width&height.

**Comment by stnguyen90** [comment]
> No! Get url of uploaded file is imposable. I can get only full file in Flutter SDK. 

You can create the string yourself using the endpoint, bucket ID, and file ID. What part of that are you having trouble with? Feel free to join us on discord as Matej suggested.

**Comment by TechnoDD** [comment]
We need a request that returns the URL of the resource, not a request that returns the content of the resource or the download of the resource. For example if I upload a .glt resource, with the Web SDK I cannot use this

`<babylon model="https://server.appwrite/v1/storage/buckets/{bucketId}/files/{fileId}/model.gltf"></babylon>`

**Comment by Meldiron** [comment]
> https://doc.babylonjs.com/extensions/babylonViewer

If I am not mistaken, the preview URL should work with Babylon.js. Can you check and get back to me on this one? For example, it should be this URL:
```
https://server.appwrite/v1/storage/buckets/{bucketId}/files/{fileId}/preview?project={projectId}
```

**Comment by TechnoDD** [comment]
No, it doesn't work!

**Comment by stnguyen90** [comment]
> No, it doesn't work!

Would you please provide more information about what doesn't work? Maybe console logs or network logs?

**Comment by TechnoDD** [comment]
> > https://doc.babylonjs.com/extensions/babylonViewer
> 
> If I am not mistaken, the preview URL should work with Babylon.js. Can you check and get back to me on this one? For example, it should be this URL:
> 
> ```
> https://server.appwrite/v1/storage/buckets/{bucketId}/files/{fileId}/preview?project={projectId}
> ```

This doesn't work!!

**Comment by stnguyen90** [comment]
Please provide more detail about how it doesn't work. Some sort of log or error message would really help.

**Comment by hopheylalaley84** [comment]
it would be nice if, after uploading file, a link to the file came in the response

**Comment by stnguyen90** [comment]
After uploading, the file ID is returned. That, the bucket ID, and the endpoint are all that's needed to build the URL.

**Comment by stnguyen90** [comment]
Is there anything else you need? Can this be closed?

**Comment by hopheylalaley84** [comment]
Oh. nothing helps. There are many plugins in flutter that work with the link. Like video_player. But it need URL link to file. AppWrite do not give me it. 
this do not work
http://localhost/v1/storage/buckets/123/files/1234/view?project=629f129fe12f9cd18d70&mode=admin
this do not work
http://localhost/v1/storage/buckets/123/files/1234/view?project=629f129fe12f9cd18d70
this do not work
http://192.168.31.50/v1/storage/buckets/123/files/1234/view?project=629f129fe12f9cd18d70
this do not work
http://localhost/v1/storage/buckets/123/files/1234/download?project=629f129fe12f9cd18d70
this do not work
http://192.168.31.50/v1/storage/buckets/123/files/1234/download?project=629f129fe12f9cd18d70

How i can get just simple file URL like in Firebase?  WTF?

**Comment by binhodev** [comment]
> > https://doc.babylonjs.com/extensions/babylonViewer
> 
> If I am not mistaken, the preview URL should work with Babylon.js. Can you check and get back to me on this one? For example, it should be this URL:
> 
> ```
> https://server.appwrite/v1/storage/buckets/{bucketId}/files/{fileId}/preview?project={projectId}
> ```

Its works if Read Access is set to 'role:all', but member, user, etc don't work and appears error 404 code bucket not found.

`{"message":"Bucket not found","code":404,"type":"storage_bucket_not_found","version":"0.15.1"}`

**Comment by stnguyen90** [comment]
> from app (Android/iOS)

In this case, it depends on the library you're using and how it lets you manipulate the HTTP request. If you can pass HTTP headers, you can [generate a JWT token](https://appwrite.io/docs/client/account?sdk=android-kotlin#accountCreateJWT) and pass that in the `X-Appwrite-JWT` header.

**Comment by binhodev** [comment]
> `X-Appwrite-JWT` header.
Where do I get the list of headers?

**Comment by binhodev** [comment]
> > from app (Android/iOS)
> 
> In this case, it depends on the library you're using and how it lets you manipulate the HTTP request. If you can pass HTTP headers, you can [generate a JWT token](https://appwrite.io/docs/client/account?sdk=android-kotlin#accountCreateJWT) and pass that in the `X-Appwrite-JWT` header.

Well done!! Working with successfully, passing the JWT.
But, the JWT is valid per 15 minutes, can extends this duration?

**Comment by stnguyen90** [comment]
As of now, the lifepsan of the JWT token is not configurable without modifying the source code and there is no way to refresh the token. 

Closing this issue as there is no other change needed. Feel free to join us on [Discord](https://appwrite.io/discord) if you have any other questions.

**Comment by itsfuad** [comment]
Isn't it a bad choice to expose project id, bucket id and file id to the outside world just to download a single file? I would make a unique url to download the file instead.

**Comment by sonicviz** [comment]
> Isn't it a bad choice to expose project id, bucket id and file id to the outside world just to download a single file? I would make a unique url to download the file instead.

Yes, this worries me. There should be an option to generate random urls to hide this instead. 
I'd also prefer being able to send the base64 image directly to an Appwrite function to avoid having to send it to storage in the first place, but still can't get it working doing this. There are viable use cases for sending images (below a certain size obviously) direct to a function rather than have to upload to storage and then expose it via url's with data like projectid etc.

**Comment by Mingu113** [comment]
After getting the id, you can try hardcoding the url 
For example, assumming you're trying to display using `NetworkImage`
`NetworkImage("https://cloud.appwrite.io/v1/storage/buckets/$bucketId/files/$id/preview?project=$projectId");`
with `bucketId` is the id of file's bucket, `id` is the file's id, and `projectId` is the project's id
Then, make your bucket public for everyone to see by setting `Role: Any` with `Read` permission in Console. With that, you can display the image with the url. I assumming this is not safe and you should only do this with public files.
you can replace the `preview` in the URL with `view` or `download ` for what you want.
