### ISSUE TITLE
📚 Documentation: 0.14 requires Docker Compose V2

### ISSUE THREAD

**Issue by davedawkins** [appwrite/appwrite#3358]
### 💭 Description

As of v0.14, documentation should indicate that docker compose V2 is required.

In addition, it's unclear that "docker-compose" is available - if it isn't, then `docker compose` will work instead. Depending on your platform, you might like to create an alias for 'docker-compose' or a symbolic link. 

See https://discord.com/channels/564160730845151244/564175629663076372/984102332121886810 for context to this issue

Related issue
https://github.com/appwrite/appwrite/issues/1049

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Good point. Perhaps the [installation instructions](https://appwrite.io/docs/installation) should be updated to indicate docker compose v2 is required.

**Comment by christyjacob4** [comment]
@davedawkins there are two `docker-compose.yml` files we mainly use
1. The [development docker-compose](https://github.com/appwrite/appwrite/blob/master/docker-compose.yml) &
2. The production [docker-compose](https://github.com/appwrite/appwrite/blob/master/app/views/install/compose.phtml)

As of 0.14 only the development docker-compose file requires `docker compose` to be installed on your system.

If you are installing appwrite using the instructions on our homepage, you do not need `docker compose`. The older `docker-compose` should be sufficient.

**Comment by stnguyen90** [comment]
> If you are installing appwrite using the instructions on our homepage, you do not need docker compose. The older docker-compose should be sufficient.

@christyjacob4, installing may not require it but users will eventually need to run docker compose to manage Appwrite and update env variables. We've had multiple users come on discord with problems running `docker-compose` so it might be worth it to add something on the installation page about compose V2.

**Comment by gewenyu99** [comment]
Self-assigning :)

**Comment by stnguyen90** [comment]
Closing as docs have been updated.
