### ISSUE TITLE
🐛 Bug Report: From Flutter Client cannot create document with multiple users have read permission

### ISSUE THREAD

**Issue by nmharmon8** [appwrite/appwrite#3369]
### 👟 Reproduction steps

I have a collection with document level permissions. I wish the document to only be read by two users. One of the two users is the creator of the document. This is using the Flutter appwrite 5.0.0 and appwrite 0.14.2

```dart
await database.createDocument(
          collectionId: collectionId,
          documentId: documentId,
          data: data,
          read: [
             "user:${user.$id}"
            "user:${clientId}",
          ],
          write: [
            "user:${user.$id}"
          ]);
```
```Unhandled Exception: AppwriteException: user_unauthorized, Read permissions must be one of: (role:all, role:member, user:629fbbf2224f6121ee2f) (400)```

user.$id is 629fbbf2224f6121ee2f.

Using the python SDK this works fine. 

### 👍 Expected behavior

It should create a document with read permission for the two users.

### 👎 Actual Behavior

Unhandled Exception: AppwriteException: user_unauthorized, Read permissions must be one of: (role:all, role:member, user:629fbbf2224f6121ee2f) (400)

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Yes, this is the intended behavior. A user cannot use a permission they don't have. 

To share something, you must use a team with the other user in the team or invite the user to the team. 

Another option is to use an Appwrite function to create the document with the 2 users in the permission. 

It's probably best to close this issue and you can add your thoughts to https://github.com/appwrite/appwrite/discussions/2689#discussioncomment-2111773.

**Comment by nmharmon8** [comment]
Perfect. Thank you.
