### ISSUE TITLE
Email when signing up for newsletter at appwrite.io

### ISSUE THREAD

**Issue by MrTarantula** [appwrite/appwrite#339]
The email address is shown as `team@localhost.test` when confirming newsletter subscription at appwrite.io.

![image](https://user-images.githubusercontent.com/11617455/82674241-9a436180-9c08-11ea-8b36-5944f491e413.png)

**Comment by eldadfux** [comment]
Thanks for reporting this! Did this issue denied you from signing in?

**Comment by MrTarantula** [comment]
I was able to register successfully. The email and link in the email were fine. The only problem was the sender email address.

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/82711210-60686e80-9c8d-11ea-8de6-b63b5b137027.png)

Fixed on dev mode, will probably be deployed tomorrow.

**Comment by eldadfux** [comment]
NVM Just deployed the new version...
