### ISSUE TITLE
🐛 Bug Report: Migration fails to create table

### ISSUE THREAD

**Issue by Mabenan** [appwrite/appwrite#3394]
### 👟 Reproduction steps

Create Project in old Appwrite version with custom project name with dots.
for example:
com.appwrite.test

Update Appwrite

Execute Migration

### 👍 Expected behavior

Appwrite should migrate the tables with the correct name which is 

'appwrite._com.appwrite.test__metadata'

### 👎 Actual Behavior

Migration fails because project tables cannot be found with error  message
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._comappwritetest__metadata' doesn't exist

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey there 👋 Sounds like a bug to me. Can you please tell us from which version did you migrate?

**Comment by Mabenan** [comment]
13.4 if i remember correct

**Comment by Mabenan** [comment]
Some additional Informations for this case.

Here are some screenshots from the Database of my actual project.

![image](https://user-images.githubusercontent.com/4959465/174545802-67acb3c7-6d7e-44b2-bd9b-43604019bf65.png)
first project works fine second throws error from bug report.
Tables of project all looks like this
![image](https://user-images.githubusercontent.com/4959465/174545889-71f6bcd9-1ee7-4f28-8270-3bf2f602bb25.png)
![image](https://user-images.githubusercontent.com/4959465/174546014-bddb5313-8341-4f21-b85d-2e5bbdc82083.png)
For the failing project these two tables are created
![image](https://user-images.githubusercontent.com/4959465/174546099-3971091e-abab-4068-a2b2-f56a9708545f.png)
Propably some new tables introtuced with the new version

**Comment by Mabenan** [comment]
Ok i found the breaking change between 14.0 and 13.4. The Utopia Framework was upgraded from 15.x to 17.x which leads to a change in this source code line from 
this
https://github.com/utopia-php/database/blob/166365d9c39c4d70b1267af4562f4327e8930f79/src/Database/Adapter.php#L441
to this
https://github.com/utopia-php/database/blob/a4d001452b78b85335ffbd34176cd45d2b13c1ca/src/Database/Adapter.php#L464

In the old version dots where allowed in the new one not.

So as i can see why this change was made appwrite needs to react on this.

I see two options here:

1) Easy one disallow dots in project names and write a migration for it.

2) Much more complicate:
 1. Write a migration to migrate the dots out of the table names (thats the same like above)
 2. Write a check in the project creation if a project exists with the  same name only with or without dots (otherwise there can be two projects with different ids and the same tables)

**Comment by abnegate** [comment]
Closing as this should no longer be an issue in version 1.2.0, please open a new issue if the problem persists

**Comment by dokind** [comment]
I experiencing same error how to fix it in 12.3->0.13.4
