### ISSUE TITLE
🐛 Bug Report: The color of the message shown when creating a new project shouldn't be gray 

### ISSUE THREAD

**Issue by Munaikh** [appwrite/appwrite#3395]
### 👟 Reproduction steps

When I create a new project from the console page a message appears at the bottom of the screen 

### 👍 Expected behavior

It should be a different color. For example, we can apply the primary Appwrite brand color (#f02e65) as shown here:
![SCR-20220618-ltt](https://user-images.githubusercontent.com/66527073/174438453-74686b42-9b8f-4e5e-a6dd-8c1d6ea1c3ee.png)

### 👎 Actual Behavior

It actually appears with a grey color that's hard to detect
![SCR-20220618-lhe](https://user-images.githubusercontent.com/66527073/174438490-2d2e2b08-3f85-436c-a9cd-448a036ec123.png)

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rksingh2001** [comment]
Can I take up this issue?

**Comment by stnguyen90** [comment]
@rksingh2001, we're actually in the process of a rewrite of the Appwrite Console. Would you still like to work on this even though it will be replaced by the new Appwrite Console?

**Comment by rksingh2001** [comment]
@stnguyen90 No thanks, what will be the point if it will be replaced.

**Comment by stnguyen90** [comment]
Closing since the Console will be replaced entirely.
