### ISSUE TITLE
🚀 Feature: Web UI Endpoints verify, forgot password

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#3396]
### 🔖 Feature description

Please add some endpoints to verify users and reset passwords.

### 🎤 Pitch

Similar to restore password for the web admin console.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey there 👋
On client-side there is:

**Email verification**
Start: https://appwrite.io/docs/client/account?sdk=web-default#accountCreateVerification
Finish: https://appwrite.io/docs/client/account?sdk=web-default#accountUpdateVerification

**Password recovery**
Start: https://appwrite.io/docs/client/account?sdk=web-default#accountCreateRecovery
Finish: https://appwrite.io/docs/client/account?sdk=web-default#accountUpdateRecovery

On server-side, you can do that directly without user interaction.

**Email verification**
https://appwrite.io/docs/server/account?sdk=nodejs-default#accountUpdateStatus

**Password recovery**
https://appwrite.io/docs/server/account?sdk=nodejs-default#accountUpdatePassword

---

Are these endpoints you were looking for, or were you addressing a different problem?

**Comment by s3ppo** [comment]
Hey @Meldiron,

sorry for the missunterdtanding i mean a web frontend endpoint.

**Comment by Meldiron** [comment]
From frontend, it's not secure to allow the user to simply update password, not verify email.

As shown in message above, the steps for both are on client-side:
1. Initiate the process - server will send an email
2. User clicks the button in the email
3. User gets redirected to your web app, where there are secrets in query params
4. You take query params to run the confirmation function, and finish the process

**Comment by s3ppo** [comment]
@Meldiron 
Why is it not secure for my users, and for web console users it is?

my app is not a webapp, its a flutter mobile app.. i dont want to do it in the app, a web endpoint would be better 😉

**Comment by Meldiron** [comment]
It's considered to be insecure to only protect all user management by a password. As soon as I know someone's password (and can sign in), I would be able to change their password and steal their account. That's the reason why mail is used, to keep this process as secure as possible.

If you strongly want to avoid this process, you can make yourself an Appwrite Function in which you do this without the remain verification. You then run the function from the client-side easily.

**Comment by s3ppo** [comment]
hmm i am not sure if i understood it correctly but what i mean is that i missinterpreted this file:
https://github.com/appwrite/appwrite/blob/a8dcd9efe34801a40f01a4f5369b87b629bc1a4a/app/views/home/auth/recovery.phtml

and was sending them to this url.. the ui looks good and everything seems to work ( for me, because i have a project and admin user with the same mail adress)
but for my normal users it wasnt working, because this file is only to reset console web passwords.

so what i was requesting is this file, but for project app users ;)

**Comment by stnguyen90** [comment]
It sounds like you want Appwrite to provide a UI for reset password and verify email for your project. Is that right? If so, wouldn't it be better for you to build the UI yourself so it matches the theme and style of your app?

**Comment by s3ppo** [comment]
> It sounds like you want Appwrite to provide a UI for reset password and verify email for your project. Is that right? If so, wouldn't it be better for you to build the UI yourself so it matches the theme and style of your app?

yeah that would also be a possibility.. but then i would need a hosting module in appwrite ;-)

**Comment by stnguyen90** [comment]
@s3ppo can this be closed in favor of https://github.com/appwrite/appwrite/issues/1030? If so, please make sure to 👍🏼 that issue.
