### ISSUE TITLE
Fails to create a user account on a new setup

### ISSUE THREAD

**Issue by LuisCruz-23** [appwrite/appwrite#341]
Hi.

After a fresh install, i was getting a 500 error when trying to create a new account.

I'll leave the solution.

Machine description:
- Cent0s 8 x86_64 Linux 

The problem was related with MariaDB, so after changing my app environment to development i could see what the problem was.

`"message":"SQLSTATE[HY000] [2006] MySQL server has gone away"`

So i ran:

`docker ps`

That returned me the mariadb-container-id.

I ran `docker logs [mariadb-container-id]`

The output was:

![image](https://user-images.githubusercontent.com/55716036/82707540-e1017d80-9c41-11ea-8735-7a1b2ba1176a.png)

So to solved it i ran this 2 commands:
`docker-compose down -v`
`docker-compose up -d`

Just wait a minute, refresh the browser, try again and it should be working now.

Thanks @eldadfux for helping me.

---
Appwrite Version: 0.6.1.125

**Comment by eldadfux** [comment]
@LuisCruz-23 Thanks for reporting this and sharing the solution for others to see. As this is now solved, I'm closing the issue.
