### ISSUE TITLE
🐛 Bug Report: Pressing cancel when enabling or disabling a service doesn’t work

### ISSUE THREAD

**Issue by Munaikh** [appwrite/appwrite#3412]
### 👟 Reproduction steps

open a project then go into Settings -> Services then try to enable or disable a service and press cancel after the alert dialog shows up

### 👍 Expected behavior

It should stay the same without changing the state of the switch next to the service name

### 👎 Actual Behavior

It actually changes the state of the switch:
![Jun-21-2022 15-54-56](https://user-images.githubusercontent.com/66527073/174804460-6368d28b-f1f5-4fd7-be1d-0fa5a953a715.gif)

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by manishkumar-dsi** [comment]
I would like to work on this can someone assign to me

**Comment by stnguyen90** [comment]
No longer an issue with the new console
