### ISSUE TITLE
AppWrite for Flutter Web Apps?

### ISSUE THREAD

**Issue by KevinMalm** [appwrite/appwrite#342]
I've noticed that when working with AppWrite on Flutter. The Projects work great under the iOS and Android devices as the project specifies, I am just curious if there are any plans to support Flutter Web apps, or any workarounds I could do?

Thank you and all the best.

**Comment by eldadfux** [comment]
Well as far as I can tell Appwrite should work just find with Flutter web. The only exception is the OAuth session creation method (https://appwrite.io/docs/client/account?sdk=flutter#createOAuth2Session).

We use **[flutter_web_auth](https://pub.dev/packages/flutter_web_auth)** plugin for this action and it's not yet supported for web. There is an open issue for it: https://github.com/LinusU/flutter_web_auth/issues/16 

Anyway you could easily workaround this by calling the OAuth create session method directly using a get request equivalent to:
```js
window.location = 'https://appwrite-server.com/v1/account/sessions/oauth2/{provider}?project=[PROJECT-ID]&success=https://link-to-my-app/good&failure=https://link-to-my-app/bad';

```

**Comment by mmcdon20** [comment]
The flutter_web_auth plugin is not the only issue regarding flutter web support. [dart:io](https://api.dart.dev/stable/2.8.2/dart-io/dart-io-library.html) is also not supported on flutter web. And dart:io is used directly in the appwrite sdk-for-flutter, as well as the cookie_jar dependency.

I got the following error when building for flutter web:
```
Error: Unsupported operation: Platform._operatingSystem
```

**Comment by eldadfux** [comment]
Hey @mmcdon20 thanks for the feedback, are there any best practice in dart community for making this dependencies conditional for non-web builds? Is there any alternative for dart.io that can work on iOS, Android and Web?

**Comment by bartektartanus** [comment]
There is one package that might help:
https://pub.dev/packages/universal_io

**Comment by eldadfux** [comment]
* We can try and use universal_io instead of dart.io.
* Can we make cookie_jar and flutter_web_auth conditional? Found this,  https://twitter.com/aloisdeniel/status/1148598679454048256 but not too sure yet how it would work for us

**Comment by mmcdon20** [comment]
It seems that cookie_jar is possibly the only reason you are using dart_io, and it appears to be creating files on the local file system in order to store information about cookies. This is a problem, because within the browser you cannot simply create files and folders on the user's computer. I don't think the universal_io package will help you in this scenario.

Just to throw out an idea, perhaps this information could instead be stored using [shared_preferences](https://pub.dev/packages/shared_preferences), it is compatible with the web if you also include [shared_preferences_web](https://pub.dev/packages/shared_preferences_web).

**Comment by eldadfux** [comment]
# MAJOR UPDATE

We have been working on adding web support to the Flutter SDK. We have ALREADY published a dev version available on pub dev: https://pub.dev/packages/appwrite/versions/0.3.0-dev.2

We would appreciate any feedback and help testing it. You can follow more updates here: https://github.com/appwrite/sdk-for-flutter/issues/5

**Comment by TorstenDittmann** [comment]
This got implemented by @lohanidamodar 🎉
