### ISSUE TITLE
Missing docs for running in production

### ISSUE THREAD

**Issue by luis-cruzt** [appwrite/appwrite#343]
There are missing docs for running Appwrite in production.

**Comment by eldadfux** [comment]
Currently there are some docs on the repo and on the blog:
- https://github.com/appwrite/appwrite/blob/master/docs/tutorials/running-in-production.md
- https://github.com/appwrite/appwrite/blob/master/docs/tutorials/environment-variables.md
- https://medium.com/appwrite-io/you-can-now-restrict-access-to-your-appwrite-console-b8b447885289
- https://medium.com/@eldadfux/learn-how-to-run-your-appwrite-backend-server-with-any-smtp-provider-for-max-email-deliverability-c6ab2c3efec8

It will be better to unify all this content (and more) under a submenu in the installation section of the main docs site.

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/82709947-6a3ca280-9c8a-11ea-8d30-c303adc7aa9f.png)

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/83952938-40b47700-a845-11ea-8506-1bed49b0844d.png)

Added all the docs into the main docs site. They will be deployed in next version release of appwrite.io.

**Comment by TorstenDittmann** [comment]
@eldadfux We might want to add some information on how to prepare the already existing SMTP server to keep the emails from the spam folder.

For example explaining the need of:

- Sender Policy Framework (SPF)
- Domain Message Authentication Reporting and Conformance (DMARC)
- DomainKeys Identified Mail (DKIM)

**Comment by eldadfux** [comment]
@TorstenDittmann, got any good resources that we can use to summarize this info? I want to add it here: https://appwrite.io/docs/email-delivery

**Comment by TorstenDittmann** [comment]
Found this some time ago: https://www.digitalshadows.com/blog-and-research/security-practitioners-guide-to-email-spoofing-and-risk-reduction/
