### ISSUE TITLE
🐛 Bug Report: Create session doesn't sign in user if he has too many sessions

### ISSUE THREAD

**Issue by stonith404** [appwrite/appwrite#3432]
### 👟 Reproduction steps

I'm not sure how many sessions the user had because I deleted them. But to be safe create 100 sessions for a user and try to create a session. The session gets automatically created but when you want to get the user it returns a `401` error.

This could be related to #3276 unlike as in the related issue the error does not occur in the console but for the account API.

### 👍 Expected behavior

The user should be able to sign in no matter how many sessions he has.

### 👎 Actual Behavior

The user can create a session but he isn't signed in.

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Yes, this is probably the same problem as https://github.com/appwrite/appwrite/issues/3276

**Comment by stnguyen90** [comment]
Closing as this should be resolved.
