### ISSUE TITLE
🐛 Bug Report: File not uploading in linode object storage

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#3433]
### 👟 Reproduction steps

I read this blog https://dev.to/appwrite/appwrite-storage-meets-linode-object-storage-e03
to setting linode object storage in appwrite .env file.

_APP_STORAGE_DEVICE=Linode
_APP_STORAGE_LINODE_ACCESS_KEY=xxxxx
_APP_STORAGE_LINODE_SECRET=xxxxxx
_APP_STORAGE_LINODE_REGION=xxxxxx
_APP_STORAGE_LINODE_BUCKET=xxxxxx

When i upload file this error show up.

![Screenshot 2022-06-25 at 3 55 26 AM](https://user-images.githubusercontent.com/18592683/175721633-294984e2-83a8-4359-b8dd-6edea9274abd.png)

### 👍 Expected behavior

I will able to upload files in linode object storage.

### 👎 Actual Behavior

I can't upload files in linode object storage.

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ElectraPort** [comment]
I'll second this. we are experiencing this as well. There doesn't appear to be much to configure. 

Research indicates that Linode has issues with http 100 continue messages; setting http_continue_timeout: 0 seems to be a resolution but I've no idea where to find setting that in Appwrite.

See also: [https://www.linode.com/community/questions/19536/object-storage-upload-problem#answer-71570](https://www.linode.com/community/questions/19536/object-storage-upload-problem#answer-71570)

Thanks!

**Comment by stnguyen90** [comment]
Might be fixed as part of https://github.com/utopia-php/storage/pull/54/
