### ISSUE TITLE
🚀 Feature: Function to return complete execution response

### ISSUE THREAD

**Issue by iamdineshkumar** [appwrite/appwrite#3434]
### 🔖 Feature description

Hi In present function execution response which received has character limit of 4000 as per document which says as "The script response output string. Logs the last 4,000 characters of the execution response output.".  This character limit can be lifted to give entire response. In certain cases we might require to use cloud function to generate on call based details such as consolidated/computed response through functions. For an example day wise sales report for given range of period time. In present case its not possible to achieve due to character limitation.

### 🎤 Pitch

Provide Environemental Varaiable to control this limit so based on use case users can modify this as well as this complete response is required for synchronously calling method and for logging purpose can be logged after truncketing

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by iamdineshkumar** [comment]
In this [line](https://github.com/appwrite/appwrite/blob/f9056d1dcae27563b40b80f5c65908260f17d39e/app/executor.php#L306) its hard coded as 1MB. This feature can be acheived by  modifing as below
Existing code:
`'response' => \mb_strcut($stdout, 0, 1000000), // Limit to 1MB`
modifyied As:

`'response' => \mb_strcut($stdout, 0, App::getEnv('APP_FUNCTIONS_RESPONSE_SIZE_LIMIT', 1000000)), // Limit to 1MB`
so we can introduce APP_FUNCTIONS_RESPONSE_SIZE_LIMIT as new environmental variable. 

@tomer  @eldadfux Kindly provide your view on this. This will give flexibility to user to control it based on requirement.

**Comment by Meldiron** [comment]
Hey there 👋 In my opinion the limit makes sense, as it “protects” developer from returning big payloads and potentially worsing experience of users with slow connection.

With that said, I can see this limit increasing to 5MB. After-all 5MB, is already a limit for Appwrite Storage - files above 5MB are chunked. Actually, Appwrite Storage can be used for responses above 5MB (create file, respond with fileID, download file on client).

**Comment by iamdineshkumar** [comment]
@Meldiron You are right limit should be there for sure... But in usual case 1 MB limit might be fine but based on use case if it needed to be increased means then we can do it by changing environmental variable above which if we changing it as 5 MB then again we are hard coding it. Most of the users will not change it and if they need then we are providing an option which will be feasible as well as flexible I believe. 
As you said developers need to do best practices to handle big payloads but this will give an option to developers based on use cases.

**Comment by stnguyen90** [comment]
I would agree with @Meldiron on this. An API request should not return a payload bigger than 5MB. I would even say 1MB is too big.

**Comment by stnguyen90** [comment]
Thanks for creating a PR! :pray: 

We decided to use 1MB for both stderr and response to ensure the max total HTTP response size stays under limits set by our framework and PHP. Increasing this limit will potentially cause the entire HTTP layer to not perform properly and open the server to multiple edge cases. Unfortunately, we can't merge something like that as we'd later have to support all the undesired outcomes. 

I highly recommend making use of Appwrite Storage instead as it was designed to handle big files (includes chunking and caching). Otherwise, you can use a fork of Appwrite, mount in modified source code, or tweak the source code at runtime.

**Comment by 50l3r** [comment]
Good evening,

I feel like re-opening the post but I have the doubt that there is some way today to increase the response size without fork.

I understand that the variable APP_FUNCTIONS_RESPONSE_SIZE_LIMIT is not ready to implement.
