### ISSUE TITLE
🐛 Bug Report: Error 400 with Okta oauth

### ISSUE THREAD

**Issue by nefejames** [appwrite/appwrite#3436]
### 👟 Reproduction steps

I followed the steps in [this article](https://dev.to/appwrite/okta-authentication-with-appwrite-3jh6) on how to authenticate a Next.js app with Appwrite and Okta

I handled the necessary configurations for both ends, Appwrite and Okta

Also, here's [a link to my repo](https://github.com/nefejames/hackmamba-okta-next-auth) - if it will help

### 👍 Expected behavior

It should Authenticate my Next.js app 

### 👎 Actual Behavior

It doesn't authenticate. Rather, when I try to log in, Okta is not recognizing the Appwrite redirect_uri I passed to the config

To ensure I was doing the right thing, I followed the same steps but for GitHub OAuth, and it worked perfectly.
![Screenshot_22](https://user-images.githubusercontent.com/34649282/175831752-bf79937c-3177-41ad-b67f-ed3faef0e7fa.png)
![Screenshot_23](https://user-images.githubusercontent.com/34649282/175831755-310fa4d9-6633-47bc-9a3d-5c9b5ef09554.png)
![Screenshot_24](https://user-images.githubusercontent.com/34649282/175831756-c928620e-286b-4c1b-8b44-e7531dca9741.png)
![Screenshot_17](https://user-images.githubusercontent.com/34649282/175831757-3f077763-fad9-4c6b-9683-53dbe3d438b3.png)
![Screenshot_21](https://user-images.githubusercontent.com/34649282/175831759-9e80a908-92cb-42eb-9971-45b85171fcd3.png)
 

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Plain localhost

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Would you please copy and paste the following here? 

1. url of the okta login page or the 400 error page if you don't get a login page
2. Appwrite okta callback here
3. sign in redirect URI from omta here

**Comment by nefejames** [comment]
Sure thing @stnguyen90. Here they are:
1. The error page. I don't get to the login page. https://dev-80131892.okta.com/oauth2//v1/authorize?client_id=0oa5jh573076foLSk5d7&redirect_uri=http%3A%2F%2Flocalhost%2Fv1%2Faccount%2Fsessions%2Foauth2%2Fcallback%2Fokta%2F62b1f4a6ea47ac03584f&state=%7B%22success%22%3A%22http%3A%5C%2F%5C%2Flocalhost%3A3000%5C%2F%22%2C%22failure%22%3A%22http%3A%5C%2F%5C%2Flocalhost%5C%2Fv1%5C%2Fauth%5C%2Foauth2%5C%2Ffailure%22%7D&scope=openid+profile+email+offline_access&response_type=code

2. http://localhost:4000/v1/account/sessions/oauth2/callback/okta/62b1f4a6ea47ac03584f
3. http://localhost:8080/authorization-code/callback

**Comment by nefejames** [comment]
Hi. I tried updating 3 to match 2, but it did;t work. Technically, I added both URLs to the **Sign-in redirect URIs** config right from the beginning, but none of them ever worked.

I also tried setting the authorization server id in Appwrite to `default`, but that didn't work also.

I also tried removing the `http://localhost:8080/authorization-code/callback` link and leaving only Appwrite's Okta to redirect URI, but I got the same error.

Any idea why this is happening? I followed the same process and it worked for GitHub.

![Screenshot_30](https://user-images.githubusercontent.com/34649282/176412746-d49f8c68-a747-4bef-a7b8-5a045e27de1c.png)

![Screenshot_29](https://user-images.githubusercontent.com/34649282/176412731-1a5bc311-3ce8-4f01-999c-a5b5fce17b1a.png)

**Comment by nefejames** [comment]
I can confirm that I used `http://localhost:4000/v1/account/sessions/oauth2/callback/github/62b1f4a6ea47ac03584f` in both my Okta and Appwrite configurations.

Seems like the error page removes the 4000 from the localhost.

https://dev-80131892.okta.com/oauth2/default/v1/authorize?client_id=0oa5jh573076foLSk5d7&redirect_uri=http%3A%2F%2Flocalhost%2Fv1%2Faccount%2Fsessions%2Foauth2%2Fcallback%2Fokta%2F62b1f4a6ea47ac03584f&state=%7B%22success%22%3A%22http%3A%5C%2F%5C%2Flocalhost%5C%2Fv1%5C%2Fauth%5C%2Foauth2%5C%2Fsuccess%22%2C%22failure%22%3A%22http%3A%5C%2F%5C%2Flocalhost%5C%2Fv1%5C%2Fauth%5C%2Foauth2%5C%2Ffailure%22%7D&scope=openid+profile+email+offline_access&response_type=code

**Comment by nefejames** [comment]
Default ports? Alright

Please how do I do that? I'm not familiar with Docker.

last time Iran the powershell command to reinstall appwrite, the 4000 ports I initially selected was still showing

If you can tell me the command to update to the default port

**Comment by stnguyen90** [comment]
1. Stop and remove the current containers with `docker compose down`
2. Open the docker-compose.yml file
3. Under services > traefik > ports there are port mappings. Update the two values to `80:80` and `443:443`
4. Recreate the containers with `docker compose up -d`

**Comment by nefejames** [comment]
It's working now. Thanks for the steps

Apparently, not using the default port was the problem. I'll take note of that going forward.

Thank you for your assistance.
