### ISSUE TITLE
Not loading Document after creating them (Cache Issue)

### ISSUE THREAD

**Issue by FathiQ** [appwrite/appwrite#344]
Hi,

After clicking on "+" to create Document and filling the input texts. and back to Document will show you 1 documents found but you can see it. until you refresh the page and even if you go to Databases -> then your collection -> you will not see any Documents

<img width="1256" alt="Screen Shot 2020-05-23 at 1 12 14 AM" src="https://user-images.githubusercontent.com/13282594/82713129-8fcdaa00-9c92-11ea-9e3f-5f1d3a75d5bf.png">
---
Appwrite Version: 0.6.1.125

**Comment by LuisCruz-23** [comment]
Yeah, same issue here.

**Comment by eldadfux** [comment]
@FathiQ @LuisCruz-23 any possibility to record the flow for getting this issue?

I can't seem to make it happen on my env 😔

**Comment by eldadfux** [comment]
+ do you get any errors in your devtools console?
+ what your collections rules look like?

**Comment by punitdiwan** [comment]
It looks like the same issue which I reported.  Please refer Issue #325  I tried it on Version 6,0,0. I closed this issue considering the slow internet connection but now others are also receiving it. So, its genuine issue. I reinstalled the fresh instance, but did not get such issue. So, this issue is not consistent

**Comment by FathiQ** [comment]
@eldadfux https://www.screencast.com/t/J91gg2SIy

**Comment by eldadfux** [comment]
@FathiQ This makes me thing this might be a html cache issue (not updating your collection templates).

Could you try doing the same action with your browser devtools open and your cache disabled like this:
![image](https://user-images.githubusercontent.com/1297371/82734549-43cb4580-9d24-11ea-86b8-1515367bdf5a.png)

**Comment by FathiQ** [comment]
@eldadfux it seems cache was the problem

https://www.screencast.com/t/KGbDoLv6gld0

**Comment by eldadfux** [comment]
OK. Fix should be pretty easy. I will target this for 0.6.2 release

**Comment by eldadfux** [comment]
Pushed update to fix the UI cache issue. Will be out with 0.6.2.

**Comment by eldadfux** [comment]
Version 0.6.2 is out 🚀🎉

https://dev.to/eldadfux/announcing-the-release-of-the-appwrite-backend-server-v0-6-2-with-support-for-sign-in-with-apple-27cc

Full change log:  https://github.com/appwrite/appwrite/releases/tag/0.6.2
