### ISSUE TITLE
Add REST requests example

### ISSUE THREAD

**Issue by LuisCruz-23** [appwrite/appwrite#345]
I think we should be able to see an example of a REST API request in this dropdown:

![image](https://user-images.githubusercontent.com/55716036/82718747-0ace9a80-9c6a-11ea-92c2-0745f57de809.png)

**Comment by eldadfux** [comment]
Thanks for the feedback @LuisCruz-23! We do have plan to add this to the docs as suggested in this issue: #314 .

I have also opened an issue to generate CURL examples in our SDK Generator:
https://github.com/appwrite/sdk-generator/issues/37

Closing this in favour of #314.
