### ISSUE TITLE
{"message":"Error: Server Error","code":500,"version":"0.15.0"}

### ISSUE THREAD

**Issue by Maxbrt18** [appwrite/appwrite#3451]
### 👟 Reproduction steps

Since I updated to 0.15.0, I can’t connect to Appwrite and nothing is working. I have the error : `{"message":"Error: Server Error","code":500,"version":"0.15.0"}`

### 👍 Expected behavior

It should connect me to the console.

### 👎 Actual Behavior

An error appears that tells : `{"message":"Error: Server Error","code":500,"version":"0.15.0"}`, I tried to reboot my server, to update it but nothing helped.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use the latest version of Ubuntu running on a Oracle Cloud machine.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
Have you run the migration?

You can find all the information here => https://appwrite.io/docs/upgrade

**Comment by Maxbrt18** [comment]
> Have you run the migration?
> 
> 
> 
> You can find all the information here => https://appwrite.io/docs/upgrade

Thanks, that was the problem.
