### ISSUE TITLE
🐛 Bug Report: 0.15 UI Problems

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#3452]
### 👟 Reproduction steps

![image](https://user-images.githubusercontent.com/17125438/176270315-4226c9a5-8c3e-443c-9bb7-6ab0fc313e0c.png)
no execution dates in function logs

![image](https://user-images.githubusercontent.com/17125438/176270443-6ecd2c54-90c1-43bc-8cd4-35063e89af28.png)
no deployment times

browser cache is refreshed and showing 0.15... in the footer

### 👍 Expected behavior

pls see reproduction steps

### 👎 Actual Behavior

pls see reproduction steps

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
Should be fixed with https://github.com/appwrite/appwrite/pull/3461

Release is in the next hours 👍🏻

**Comment by stnguyen90** [comment]
This should be fixed as part of [0.15.1](https://github.com/appwrite/appwrite/releases/tag/0.15.1). Please feel free to create an issue if it's still a problem.
