### ISSUE TITLE
🚀 Feature: Automate Creation of Manual Installation Files

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#3453]
### 🔖 Feature description

With every release, the manual installation [files](https://gist.github.com/eldadfux/977869ff6bdd7312adfd4e629ee15cc5) need to be updated manually. The files should be automatically created with every release.

### 🎤 Pitch

Automatically creating the release will make sure the files are kept in sync to prevent people from updating/installing the wrong version.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
We actually added following endpoints to our homepage, which are generated from our internal templates:
- https://appwrite.io/install/compose
- https://appwrite.io/install/env

We just need to fix the links 👍🏻

**Comment by stnguyen90** [comment]
This is awesome! I was planning on adding a GitHub workflow to make the files but I guess there's no need anymore. 

One thing, though...the installation kind of expects the files to be in a folder named appwrite. Otherwise, a future upgrade using the install command won't work and the executor won't be on the appwrite_runtimes network. Will that just be mentioned in the installation docs?

**Comment by stnguyen90** [comment]
Fixed as part of https://github.com/appwrite/docs/pull/214. Thanks @TorstenDittmann!
