### ISSUE TITLE
🐛 Bug Report: The database link is not working on your official website

### ISSUE THREAD

**Issue by PranavThampi** [appwrite/appwrite#3457]
### 👟 Reproduction steps

Navigate to this [link](https://appwrite.io/docs/client/database). You'll get the following error.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/57982907/176360738-c53fe9c7-3783-4d4b-8e63-109031123c31.png">

### 👍 Expected behavior

Ideally we should get the information about the databases right?

### 👎 Actual Behavior

Got a server error.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/57982907/176360924-46433e7b-4f05-46af-bf70-108ae6a19272.png">

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by usamashafiqs** [comment]
Use this link instead https://appwrite.io/docs/client/databases

**Comment by TorstenDittmann** [comment]
> Thank you. Could you please make the changes in your website as well?

I am struggling to find where you found that link 👀 For me all of them are using the new one 👍🏻

**Comment by TorstenDittmann** [comment]
> I think I found the issue. If you scroll to the bottom of the page, you'll see `Features` > `Database`. It seems like in the url, the `database` is missing an `s`. If you click on database, the url changes to https://appwrite.io/docs/client/database instead of https://appwrite.io/docs/client/databases <img alt="image" width="1077" src="https://user-images.githubusercontent.com/57982907/176425798-d5d72801-f853-4b2f-a160-b0280944392d.png">

Awesome, good catch!

**Comment by stnguyen90** [comment]
@PranavThampi, thanks for bringing this up! This should be fixed now. Would you please confirm and close the issue?

**Comment by PranavThampi** [comment]
Yup its working now. Thanks!
