### ISSUE TITLE
🐛 Bug Report: If i toggle switch for multiple databases for one project error occurred.

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#3459]
### 👟 Reproduction steps

After install of appwrite v0.15 database disable by default if i toggle switch for multiple databases this error occurred.

<img width="800" src="https://user-images.githubusercontent.com/18592683/176396319-3bb458c4-11f6-4c0a-b58f-e3caaff866d0.png" >

### 👍 Expected behavior

I should be able to turn on multiple databases for project.

### 👎 Actual Behavior

If i toggle switch for multiple databases for one project error occurred.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
Might be a cache issue, can you try it after a hard refresh?

**Comment by usamashafiqs** [comment]
Yeah it was cache issue, Thanks!
