### ISSUE TITLE
🐛 Bug Report: Invalid databaseId

### ISSUE THREAD

**Issue by rvndsngwn** [appwrite/appwrite#3460]
### 👟 Reproduction steps

When I open the document for edit from the default database in the console.

### 👍 Expected behavior

It should be open as usual.

### 👎 Actual Behavior

It shows an error:
```
Error 400
Invalid databaseId: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore

Error ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
![Screenshot 2022-06-29 at 2 20 14 PM](https://user-images.githubusercontent.com/59143934/176397625-84b633b9-65a2-46b5-ace2-80fa3a4ff5e1.png)

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use digitalocean droplet.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/appwrite/pull/3461

You can expect a release in the next hours 👍🏻
