### ISSUE TITLE
[0.15.0.400] 🐛 Bug Report: If i try to delete document form collection error occurred

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#3462]
### 👟 Reproduction steps

If i try to delete document form collection this error occurred.

<img width="800" src="https://user-images.githubusercontent.com/18592683/176422244-ceb0a93c-1c22-496d-ac93-ce0138b2ed1b.png" />

### 👍 Expected behavior

I should be able to delete document form collection.

### 👎 Actual Behavior

If i try to delete document form collection error occurred.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
Good catch!

We will release `0.15.1` in a few hours 👍🏻
