### ISSUE TITLE
🚀 Feature: New Environment Variable to disable IP tracking in Collection Activity

### ISSUE THREAD

**Issue by groschi24** [appwrite/appwrite#3468]
### 🔖 Feature description

Currently in the Collection Activity the IP is showed, but it should be possible to tell appwrite to not track the IP of users.

### 🎤 Pitch

When you from Europe you have to pass the GDPR and the IP is a personal data.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This feature is ready and will be available in Appwrite 1.4.
