### ISSUE TITLE
Can anyone help explain why Appwrite can't find the collection? 

### ISSUE THREAD

**Issue by KevinMalm** [appwrite/appwrite#347]
I'm having trouble uploading a file to an AppWrite database in Flutter. I am sure there is a very small thing that I have missed but any help would be much appreciated. Also I apologies that the code is in quote format, I couldn't get the code format to work. 

This is my collection ID that I created in the AppWrite console. 

![Screen Shot 2020-05-23 at 10 16 53 AM](https://user-images.githubusercontent.com/33231167/82734160-8c601000-9cde-11ea-97e2-f88da1dd7e48.png)

Here is my setup Code: 

> Client client = Client();
    Database log_database = Database(client);
    Account account = Account(client);
client.setProject(APPWRITE_CONSTANTS.project_id);
    client.setEndpoint(APPWRITE_CONSTANTS.project_endpoint);

Variables

>  this.log_cnter_data = {"count": 0};
this._collection_address = '5ec93d7725352';

Here's where the Map<String, dynamic> is attempted to be saved

> Future log_result = log_database.createDocument(collectionId: this._collection_address, data: this.log_cnter_data, read: ['*'], write: ['*']);
    log_result.then(
      (response){
        print(response);
      }
    ).catchError((error){
      print(error);
    });

This is the error I keep on receiving:
<img width="519" alt="Screen Shot 2020-05-23 at 10 26 29 AM" src="https://user-images.githubusercontent.com/33231167/82734325-ef9e7200-9cdf-11ea-82c7-d5c225deb36e.png">
And this is the path that is trying to post to (which looks correct to me, but what do I know)
<img width="358" alt="Screen Shot 2020-05-23 at 10 26 11 AM" src="https://user-images.githubusercontent.com/33231167/82734331-00e77e80-9ce0-11ea-81fe-c57dbac2941e.png">

Thank you and All the Best, 

---
Appwrite Version: UNKNOWN.125

**Comment by christyjacob4** [comment]
Hey @KevinMalm Looks like you haven't passed any permissions to create a collection. 
Could you do this and let me know what happens?
```dart
Future log_result = log_database.createDocument(collectionId: this._collection_address, data: this.log_cnter_data, read: ['*'], write: ['*']);
log_result.then(
(response){
print(response);
}
).catchError((error){
print(error);
});
```

**Comment by KevinMalm** [comment]
My apologies, that seems to have been formatted incorrectly when I put it in as quotes, here's what's actually ran

`Future log_result = log_database.createDocument(collectionId: this._collection_address, data: this.log_cnter_data, read: ['*'], write: ['*']);`
    `log_result.then(
      (response){
        print(response);
      }
    ).catchError((error){
      print(error);
    });`
<img width="1177" alt="Screen Shot 2020-05-23 at 12 07 07 PM" src="https://user-images.githubusercontent.com/33231167/82736271-01871180-9cee-11ea-9ed4-b8b0078767c6.png">

**Comment by eldadfux** [comment]
@KevinMalm add '*' permission to your collection read permission.

![image](https://user-images.githubusercontent.com/1297371/82736567-6f096100-9d33-11ea-979b-a41bc02d9a8a.png)

**Comment by KevinMalm** [comment]
That fixed it! Thank you much.
