### ISSUE TITLE
🐛 Bug Report: Attribute not found

### ISSUE THREAD

**Issue by rvndsngwn** [appwrite/appwrite#3472]
### 👟 Reproduction steps

When I delete attribute getting error: `Attribute not found`.

### 👍 Expected behavior

Attribute delete successfully.

### 👎 Actual Behavior

`Attribute not found`

![Screenshot 2022-06-30 at 12 32 13 AM](https://user-images.githubusercontent.com/59143934/176517988-8a702301-0d54-4fad-9de9-42d075b6cbca.png)

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Digitalocean droplet.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
What version of Appwrite are you on? 0.15.0 or 0.15.1? If you're on 0.15.0, would you please try upgrading to 0.15.1 and doing a hard refresh in the Appwrite console?

**Comment by rvndsngwn** [comment]
> What version of Appwrite are you on? 0.15.0 or 0.15.1? If you're on 0.15.0, would you please try upgrading to 0.15.1 and doing a hard refresh in the Appwrite console?

Appwrite v: 0.15.1

I'm tried this in the different browsers and with different attributes.

**Comment by stnguyen90** [comment]
Did you have any errors when you were creating the attributes? Would you please provide your appwrite and appwrite-worker-databases docker container logs?

**Comment by rvndsngwn** [comment]
Hi @stnguyen90, after an update on 0.15.2, this error was gone.
