### ISSUE TITLE
🐛 Bug Report: Dont show the form sign up/ create account and redirect to console url. 

### ISSUE THREAD

**Issue by Sebastiangperez** [appwrite/appwrite#3477]
### 👟 Reproduction steps

After install from docker, go to [localhost. ](http://localhost:8080)

### 👍 Expected behavior

Sign up form the first time loading app 

### 👎 Actual Behavior

Spining cicrcle appear and the url is [Console. ](http://localhost:8080/console)

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

VM on virtual box, ubuntu 21.10 distro. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
So, are you saying, you installed Appwrite, browsed to the console, but you were logged in to show your projects? This is probably because you had volume from an existing installation of Appwrite. If you had no existing volume, installed Appwrite, and browsed to the Appwrite console, you should be presented with the sign up page.

**Comment by Sebastiangperez** [comment]
> So, are you saying, you installed Appwrite, browsed to the console, but you were logged in to show your projects? This is probably because you had volume from an existing installation of Appwrite. If you had no existing volume, installed Appwrite, and browsed to the Appwrite console, you should be presented with the sign up page.

No , i installed Appwrite running just the docker install command that its shown in the docs , then, go to localhost:5050 ( port that i choose ) , and no sign up form appear and redirect to console url and the spinning wheel is stuck.

**Comment by stnguyen90** [comment]
What version did you install and have you ever accessed Appwrite console on localhost before?

**Comment by Sebastiangperez** [comment]
> What version did you install and have you ever accessed Appwrite console on localhost before?

the latest , 0.15.1 and never access, my first time testing the app.

**Comment by stnguyen90** [comment]
Glad it's working now! :tada: Would you be able to close this issue then?

**Comment by Sebastiangperez** [comment]
Donde
