### ISSUE TITLE
Change "Appwrite Team" on the invitation email

### ISSUE THREAD

**Issue by luis-cruzt** [appwrite/appwrite#348]
I've found a bug where after making the setup of the SMTP server and the env variables with:

![image](https://user-images.githubusercontent.com/55716036/82746588-26fc3580-9d57-11ea-8855-7e717e53f24b.png)

The "Appwrite Team" is not been replaced by `_APP_SYSTEM_EMAIL_NAME` at the end of the email:

![image](https://user-images.githubusercontent.com/55716036/82746601-472bf480-9d57-11ea-826f-44203f9d9d21.png)

**Comment by eldadfux** [comment]
@LuisCruz-23 I was double checking this. Is this the mail you get when you signup for the console or for your project? If this is the email you get when you sign for the Appwrite console, it's shouldn't be an issue.

We take the name of the project and add the 'team' string to it when we send emails. When you signup for the Appwrite console, the console has its own kind of internal 'project' object and its name is 'Appwrite'. If you open a new project named 'Netflix' your project users should get mails signed as 'Netflix Team', please let me know if this is the case.

**Comment by LuisCruz-23** [comment]
This issue is when you invite a member to your project.

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/82836773-e70c8e00-9ecf-11ea-84c9-ea33f84030bc.png)

Is this the mail you refer to? how would you expect it to look like?

**Comment by LuisCruz-23** [comment]
Yes, that's the email i am referring to.

I think the "Thanks, Appwrite Team" should be changed to "Thanks, YOURPROJECT_TEAM"

**Comment by TorstenDittmann** [comment]
This got fixed at some point 🎉
