### ISSUE TITLE
🐛 Bug Report: Storage createFile allows creating file with existing $id (v:0.15.1.401)

### ISSUE THREAD

**Issue by basatS7T** [appwrite/appwrite#3483]
### 👟 Reproduction steps

This concerns Appwrite v:0.15.1.401

I came across this accidentally as I was developing a simple user registration form with file attachment (file type input in form for attaching/uploading profile picture).  In the course of developing the form and performing tests and debugging, I noticed I was trying to upload files with an id ($id) that was already taken in storage/bucket.  I noticed I did not receive any error messages of any kind. The response was a standard/valid File Object without any extraordinary attributes or values.  One would not be able to notice the failed operation unless accidentally, the way I did.

To recap:  I can call createFile repeatedly with an $id value (e.g., "ABC1") that already exists in the storage bucket.  It does not matter what file I pick to upload.  The response is always a standard/normal-looking File object, for example:

`{"$id":"ZCB2_EXP_DICT","bucketId":"62b9bcae7a6702fa1c1a","$createdAt":1656712010,"$updatedAt":1656713692,"$read":["user:626d65a2c8c8b1d2a6ee"],"$write":"user:626d65a2c8c8b1d2a6ee"],"name":"23099281778.pdf","signature":"29cc671140f83d8571a1f02035ca65dd","mimeType":"text/plain","sizeOriginal":182522,"chunksTotal":1,"chunksUploaded":1}`

### 👍 Expected behavior

The desired behavior is an error message whenever the createFile operation is called with a id that is already assigned to a file in the targeted storage bucket.  The file in storage that has the same id would remain unchanged -- content and meta data would be unaltered.

### 👎 Actual Behavior

The response is always a standard/normal-looking File object, for example:

`{"$id":"ZCB2_EXP_DICT","bucketId":"62b9bcae7a6702fa1c1a","$createdAt":1656712010,"$updatedAt":1656713692,"$read":["user:626d65a2c8c8b1d2a6ee"],"$write":"user:626d65a2c8c8b1d2a6ee"],"name":"23099281778.pdf","signature":"29cc671140f83d8571a1f02035ca65dd","mimeType":"text/plain","sizeOriginal":182522,"chunksTotal":1,"chunksUploaded":1}`

It appears that a few of the file meta data are altered even though **the file already in the bucket/storage is not physically altered in any way**.  The file appears to have the same 1s and 0s it had before the operation.  However, some of the meta data changes, potentially messing up downstream functionality when it comes time to download or view the pre-existing file:
- mimeType:  Takes the type of the last file attempted for creation -- if the mimeType of the last attempted file is different from the one in storage, this will break preview and download functions.  For example, if the file in storage is PDF (and was tagged as such when first created) and an attempt is made with a text file, the file in storage will be tagged as a text file, breaking (default) preview and download operations;
- signature:  A new signature is generated even if the last attempted file is the exact same as the file already in storage -- as if the file changed (when it probably didn't);
- updatedAt:  Takes the time of the last creation attempt, i.e., it records 'last attempted createFile time', not the first time the file was created or the last time it was truly changed.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

standard docker image and environment, nothing special.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by abnegate** [comment]
Thanks @basatS7T, this is [now fixed](https://github.com/appwrite/appwrite/pull/6029) and will included in the next release.
