### ISSUE TITLE
Add support for changing response locale 

### ISSUE THREAD

**Issue by luis-cruzt** [appwrite/appwrite#349]
Would be great if we could choose on which language the response is returned.

For example:
```
{
    "message": "Invalid id: Parameter must be a valid number",
    "code": 400
}
```

And in spanish would be:

```
{    
     "message": "Id inválido: El parámetro debe ser un número válido",
     "code": 400
}
```

**Comment by eldadfux** [comment]
This is possible as we already have support for changing locales using the API or SDKs (currently supported for email templates and https://appwrite.io/docs/client/locale service).

To fully support this we would need to create a better workflow with the translation contributors. Currently we have 46 languages to support and it will be very hard to make sure all string are translated.

Any suggestions?

**Comment by TorstenDittmann** [comment]
This seems doable I guess, depends on how we maintain languages for these response strings.

Even if we don't have all the languages covered, it seems to be fair falling back to English.

**Comment by thesmartrenovation** [comment]
@eldadfux  How does this work for E-mail templates?

**Comment by TorstenDittmann** [comment]
> @eldadfux How does this work for E-mail templates?

Using the SDK you can set the locale like you set the project endpoint. For JS you can add it like this:

```js
client.setEndpoint("....").setLocale("de");
```

**Comment by TorstenDittmann** [comment]
Gonna close this for now, can be re-opened if necessary.

**Comment by merabtenei** [comment]
Is there any update on this ? Calling client.setLocale('languageCode') doesn't seem to affect the response message.
