### ISSUE TITLE
🐛 Bug Report: Manually deployment of JAR files does not work.

### ISSUE THREAD

**Issue by dv8888** [appwrite/appwrite#3490]
### 👟 Reproduction steps

When I try to deploy a java function manually and upload a jar file, the entrypoint "java -jar WelcomeEmail-1.0-SNAPSHOT.jar" does not work. There is always the error "Docker Error: cat: 'java -jar WelcomeEmail-1.0-SNAPSHOT.jar': No such file or directory".

### 👍 Expected behavior

The jar file should be installed and used for function.

### 👎 Actual Behavior

The error "Docker Error: cat: 'java -jar WelcomeEmail-1.0-SNAPSHOT.jar': No such file or directory" appears.

### 🎲 Appwrite version

Version 0.14.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Hmm...ya, you can't put `java ...` as the entrypoint. You might be able to include a jar with your code has a dependency and then use the jar in your function, though. Please make sure the code is formatted as described in the [docs](https://appwrite.io/docs/functions#writingYourOwnFunction).

FYI, [this](https://github.com/open-runtimes/open-runtimes/blob/main/runtimes/java-18.0/build.sh) is how your uploaded code is compiled when deployed.

**Comment by dv8888** [comment]
Hi @stnguyen90, 

I need to deploy functions manually, as described in several tutorials like this:
https://hardiksachan.hashnode.dev/introduction-to-appwrite-cloud-functions-with-android-and-kotlin

All of them are saying, that I need to enter "java -jar ...." instead of entrypoint. Interestingly in the screenshots this field is called "Command" instead of "Entrypoint" (just above code file picker). Did something change in the latest versions of appwrite?

Thanks!

**Comment by stnguyen90** [comment]
> Did something change in the latest versions of appwrite?

Yes, version 0.13.0 was released 2022-03-02 which had big breaking changes to functions. That article you're referencing looks like it was published before 0.13.0. I would recommend using our official docs or [this](https://dev.to/appwrite/cloud-functions-using-the-new-java-runtime-39j0) article.

**Comment by dv8888** [comment]
Hi @stnguyen90, yes thank you. As I understood, it is not possible to upload jar files manually an I need to use CLI for deploying functions.
