### ISSUE TITLE
POST https://appwrite.io/newsletter/verify 500🐛 Bug Report: 

### ISSUE THREAD

**Issue by baas-enjoyer** [appwrite/appwrite#3494]
### 👟 Reproduction steps

When I try to signup for newsletter Im getting 500. Please take a look on the attached image.

![Screenshot 2022-07-04 at 06 17 33](https://user-images.githubusercontent.com/44244477/177081109-fd8b6d0e-032c-46c4-a483-77601a80afff.png)

### 👍 Expected behavior

Should Works

### 👎 Actual Behavior

Dont work

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

Website

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This usually occurs if you're already subscribed. Well work to improve the error message though.

**Comment by Appwrite-Guru** [comment]
@stnguyen90  Thats right. I already subscribed.
