### ISSUE TITLE
Can we make Clamav Container (appwrite_clamav) Optional

### ISSUE THREAD

**Issue by punitdiwan** [appwrite/appwrite#350]
I have install Appwrite Docker Containers on windows. I checked the resource being used by each container. I noticed that Clamav container (appwrite_clamav) is using lot of memory, Here is the image shown resource utilization for clamav container on my window PC with docker.

![clamav](https://user-images.githubusercontent.com/49054503/82748413-80179980-9d56-11ea-9c35-d96660999ed4.png)

       However, its only purpose is to scan file upload like images, docs etc  for viruses. Since most of the Back end as a Serivice (BaaS) uses external service for file upload like AWS S3, or Digitalocean Spaces etc. We can make it an optional container by passing an environment variable to the Appwrite install container to enable/disable  clamav container.

Share your thoughts.
Regards,
Punit

**Comment by eldadfux** [comment]
ClamAV is loading the entire virus DB into his memory (and updates it periodically) for better performance. This is the highest resource consuming memory and we been thinking for some time to make an env var that will make him optional.

**This feature will allow us to reduce minimum hardware requirements required to run Appwrite and potentially save server costs for developers.**

Will attempt to push this issue for 0.7 release.

**Comment by eldadfux** [comment]
Done! 🥳ready to release with 0.6.2

**Comment by punitdiwan** [comment]
@eldadfux  Thanks for the same. Waiting for 0.6.2 release as I wanna give a try. I will also give a shot to new migrate command to upgrade the version as currently 0.6.1 release is installed.

**Comment by eldadfux** [comment]
Version 0.6.2 is out 🚀🎉

https://dev.to/eldadfux/announcing-the-release-of-the-appwrite-backend-server-v0-6-2-with-support-for-sign-in-with-apple-27cc

Full change log:  https://github.com/appwrite/appwrite/releases/tag/0.6.2
