### ISSUE TITLE
🐛 Bug Report: OAuth2 incorrect redirect urls 

### ISSUE THREAD

**Issue by 2002Bishwajeet** [appwrite/appwrite#3501]
### 👟 Reproduction steps

When I use any OAuth2 providers ( I tested with Dailymotion and Discord), in discord after login - it shows an **incorrect redirect URL**. And in the Dailymotion it directly shows **incorrect redirect url**

Also no user gets registered in the console.

This issue wasn't there in previous appwrite versions

### 👍 Expected behavior

It should login properly

### 👎 Actual Behavior

It shows  either this (reported by @noga-dev)
![image](https://user-images.githubusercontent.com/62933155/177397986-2f4244a1-c830-46d0-b9bf-818ae833d7a0.png)

Or this
![image](https://user-images.githubusercontent.com/62933155/177398311-fdefe067-2a91-4c99-bd41-f3e5299f01ef.png)

But I believe its both related to same cause

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by noga-dev** [comment]
So per Steven's suggestion in the Discord server, removing the optional success and failure parameters got rid of this issue. Although a more helpful error message could be there instead of the "Error 400 Invalid success" which is a bit misleading.

**Comment by stnguyen90** [comment]
@2002Bishwajeet, your problem seems to be different. Are you sure the Redirect URI is configured correctly in Discord?

**Comment by 2002Bishwajeet** [comment]
Closing this issue as Solved
