### ISSUE TITLE
🐛 Bug Report: Database -> GET/UPDATE Database return Collection object instead of Database object

### ISSUE THREAD

**Issue by jbdujardin** [appwrite/appwrite#3521]
### 👟 Reproduction steps

Go on the documentation at this page : https://appwrite.io/docs/server/databases?sdk=nodejs-default#databasesGet

Or use one of the SDKs.

Example with dart sdk : 
`Databases(client, databaseId: 'test').get()` return **Collection** object instead of **Database** object.

### 👍 Expected behavior

GET and UPDATE method return **`Database`** object.

### 👎 Actual Behavior

GET and UPDATE method return **`Collection`** object.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rohan-kulkarni-25** [comment]
Hey !! Will like to work on this issue !! Can I know from where I can get started

**Comment by stnguyen90** [comment]
> Hey !! Will like to work on this issue !! Can I know from where I can get started 

Yes! Be sure to:

1. read our [contributing guide](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)
2. fix the problem in [databases.php](https://github.com/appwrite/appwrite/blob/master/app/controllers/api/databases.php)
3. test by running `docker compose exec appwrite specs` to generate the specs and confirm the change

**Comment by rohan-kulkarni-25** [comment]
Ook !! Will try and let you know if need some help.
