### ISSUE TITLE
🚀 Feature: Vonage adapter for Phone Auth

### ISSUE THREAD

**Issue by adityaoberai** [appwrite/appwrite#3524]
### 🔖 Feature description

An adapter to use Vonage for Phone Authentication, just like Twilio, TextMagic, and Telesign.

### 🎤 Pitch

[Vonage (formerly Nexmo)](https://www.vonage.com/) is a highly used communications-as-a-service platform, especially when we talk about platforms similar to Twilio, and it would definitely be great to have support for the same.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by adityaoberai** [comment]
@Meldiron if this is a good idea, I'd like to work on this adapter myself.

**Comment by abdullahranginwala** [comment]
@adityaoberai I'm exploring the appwrite codebase and I think this'll be a great opportunity for me to start. Any chance I could tag along or shadow you?

**Comment by adityaoberai** [comment]
@abdullahranginwala I have created a PR (#3540) for the adapter. You can check it out in the meantime.
