### ISSUE TITLE
 OAuth Provider without refresh Token method ?

### ISSUE THREAD

**Issue by 2002Bishwajeet** [appwrite/appwrite#3527]
I recently started working on adding support for Evernote OAuth Provider. 
According to Appwrite's rules for OAuth providers as of right now are:
- Provider must follow the OAuth2 protocol
- Provider must expose user email on /me endpoint (when getting info about authorized user)

[Evernote](https://dev.evernote.com/doc/articles/authentication.php) fulfilled those requirements.  It follows OAuth protocol as well as exposes user email.

But upon further digging, it does not have an endpoint for Refreshing Token.  We can set the expiry of those tokens (max 1 year).
It has a guide only for handling revoked or expired [tokens](https://dev.evernote.com/doc/articles/revoked_expired_auth.php).

### So my question is 

Can an OAuth provider be implemented without completing the refresh Token function for appwrite?  I have seen a [PR](https://github.com/appwrite/appwrite/pull/3387) which was closed related to this issue.

**Comment by 2002Bishwajeet** [comment]
Update: Evernote does not support OAuth2. But I still have a question regarding the title?

**Comment by Meldiron** [comment]
I believe the refresh token comes from Oauth 2 (two being the important part).

As long as we document it properly, I think we could also support OAuth (not 2) providers. Everything else should work, just the refresh endpoints are not there.

@eldadfux WDYT?

**Comment by Meldiron** [comment]
Regarding https://github.com/appwrite/appwrite/pull/3387 I think we closed it because it didn't expose email. But we only noticed it during debugging (since docs said they have email)

**Comment by eldadfux** [comment]
@Meldiron @2002Bishwajeet I recall we had the same issue with Twitter. They support only OAuth1 for user authentication (they have OAuth2, but only to authenticate as an application). We couldn't make the OAuth1 protocol with our OAuth2 API.
