### ISSUE TITLE
🐛 Bug Report: Cannot add empty values in a array of type not required

### ISSUE THREAD

**Issue by aadarshadhakalg** [appwrite/appwrite#3528]
### 👟 Reproduction steps

From Appwrite Dashboard, try to create a document with a few empty values in an optional array. No message is shown. The document is not created and in the console, this error is thrown.

![image](https://user-images.githubusercontent.com/19362725/178108171-89afc557-2997-4f44-997e-60b05cc183f0.png)
The document

### 👍 Expected behavior

When adding null values in array, error message should be shown.

### 👎 Actual Behavior

But, the process throws an error in the console. 

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Local environment. Everything default.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for raising this! We'll look into it!

**Comment by stnguyen90** [comment]
FYI for Appwrite team: the API call is not made due to the error in the UI.

**Comment by manishkumar-dsi** [comment]
@stnguyen90 could you please assign it to me? I would like to work on this issue.

**Comment by stnguyen90** [comment]
Assigned! Thanks for your help! :pray:
