### ISSUE TITLE
🐛 Bug Report: appwrite-usage container keeps restarting

### ISSUE THREAD

**Issue by aadarshadhakalg** [appwrite/appwrite#3529]
### 👟 Reproduction steps

I just upgraded my appwrite to latest version 0.15.2. Then I noticed that the appwrite-usage container is stuck in infinite restart loop.

Here is my appwrite doctor output:

```
[aadarshadhakalg@fedora ~]$ docker exec appwrite doctor
  __   ____  ____  _  _  ____  __  ____  ____     __  __  
 / _\ (  _ \(  _ \/ )( \(  _ \(  )(_  _)(  __)   (  )/  \ 
/    \ ) __/ ) __/\ /\ / )   / )(   )(   ) _)  _  )((  O )
\_/\_/(__)  (__)  (_/\_)(__\_)(__) (__) (____)(_)(__)\__/ 

👩‍⚕️ Running Appwrite Doctor for version 0.15.2 ...

Checking for production best practices...
🔴 Hostname has no public suffix (localhost)
🔴 CNAME target has no public suffix (localhost)
🔴 Not using a unique secret key for encryption
🟢 App environment is set for production
🟢 Abuse protection is enabled
🟢 Console access limits are enabled
🔴 HTTPS force option is disabled
🔴 Logging adapter is disabled

Checking connectivity...
Database............connected 👍
Queue...............connected 👍
Cache...............connected 👍
SMTP.............disconnected 👎
StatsD..............connected 👍
InfluxDB............connected 👍

Checking volumes...
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

Checking disk space usage...
🟢 Uploads Volume has 195.54GB free space (23.12% used)
🟢 Cache Volume has 195.54GB free space (23.12% used)
🟢 Config Volume has 195.54GB free space (23.12% used)
🟢 Certs Volume has 195.54GB free space (23.12% used)

You are running the latest version of Appwrite! 🥳
```

Here is the log for appwrite-usage container.

https://unelmacloud.com/drive/s/PwbQ2iZgz2OPuiWaoyZA2KlC5koe7Q

### 👍 Expected behavior

Should not restart

### 👎 Actual Behavior

Is restarting infinitely

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Everything is default

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
A few questions for you

1. How did you upgrade?
2. What version did you upgrade from?
3. Did you run the migrate command?
4. What's in your appwrite folder?

**Comment by aadarshadhakalg** [comment]
I followed this docs to upgrade my appwrite from 0.15.0 to 0.15.2. Yes, I ran the migrate command.

appwrite/
├── docker-compose.yml
├── docker-compose.yml.1656504427.backup
└── docker-compose.yml.1657372991.backup

0 directories, 3 files

**Comment by stnguyen90** [comment]
> Yes, I ran the migrate command

Since you were upgrading between patch versions, you didn't need to run the migrate command. I wonder if that's what's causing the problem...any chance you have a backup of 0.15.0 you can restore to?

**Comment by Abdallah-al-hallak** [comment]
same issue facing

**Comment by aadarshadhakalg** [comment]
> > Yes, I ran the migrate command
> 
> Since you were upgrading between patch versions, you didn't need to run the migrate command. I wonder if that's what's causing the problem...any chance you have a backup of 0.15.0 you can restore to?

I have two docker-compose backup files. But, that's not what you're talking about right?

**Comment by stnguyen90** [comment]
> I have two docker-compose backup files. But, that's not what you're talking about right?

Correct. I mean a database backup as well.

**Comment by aadarshadhakalg** [comment]
I don't have a database backup. Are there other ways to solve this issue?

**Comment by stnguyen90** [comment]
> I don't have a database backup. Are there other ways to solve this issue?

We would need to figure out the root cause...Anything in your appwrite docker container logs? Can you check your database and share what tables you have?

**Comment by aadarshadhakalg** [comment]
Hey, I figured out the issue. 
After I upgraded to 0.15.2, I could see a 'Default' collection in my database which was auto-generated during migration. I deleted that collection. Now it's working fine. 

What was the purpose of the 'Default' Collection?

**Comment by stnguyen90** [comment]
Interesting...what exactly did you delete? Which table or which record from what table?

I know when migrating from 0.14.X to 0.15.Y, a default database is created for existing collections. Multiple databases was one of the big changes in 0.15.
