### ISSUE TITLE
Cannot access to Appwrite's console if not use 80 port

### ISSUE THREAD

**Issue by netfirms** [appwrite/appwrite#353]
I've tried to install Appwrite on custom port (ex. 8888). Once installation completed, I can signup new server but cannot login to console.

**Comment by netfirms** [comment]
I've went to Appwrite's support discord channel and got the answer. The problem is because Appwrite not able to save cookie since the combination of IP address and custom port. So I map my subdomain to the server and now I can access Appwrite console.

<img width="1459" alt="Screen Shot 2563-05-24 at 21 04 16" src="https://user-images.githubusercontent.com/466386/82756264-5ff1e400-9e03-11ea-8935-18219c1aaf5d.png">

**Comment by eldadfux** [comment]
I think this might be the line causing this issue, will take a deeper dive a bit later:
https://github.com/appwrite/appwrite/blob/e6c06040ff1402266d771e75d3466af8f6cb3c67/app/init.php#L78

**Comment by eldadfux** [comment]
Fixed. Patch will be released with 0.6.2...

**Comment by eldadfux** [comment]
Version 0.6.2 is out 🚀🎉

https://dev.to/eldadfux/announcing-the-release-of-the-appwrite-backend-server-v0-6-2-with-support-for-sign-in-with-apple-27cc

Full change log:  https://github.com/appwrite/appwrite/releases/tag/0.6.2
