### ISSUE TITLE
🚀 Feature: Gobal Environment Variables in Functions

### ISSUE THREAD

**Issue by gepd** [appwrite/appwrite#3530]
### 🔖 Feature description

Add an option to have global variables in functions

### 🎤 Pitch

If you have one or two functions in your appwrite instance maybe this dosn't have much sense, but as soon as you start to have more functions, you start to note you need to add the same Env vars to all your functions, for example endpoint, projectId and api key.

Would be good to have global and local variables, so you can add the variable to all your functions once

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This one should be fun.

**Comment by stnguyen90** [comment]
Related PR: https://github.com/appwrite/appwrite/pull/3563

**Comment by eldadfux** [comment]
This feature has been implemented and will be available in Appwrite 1.4.
