### ISSUE TITLE
[0.15.2.402] 🐛 Bug Report: 

### ISSUE THREAD

**Issue by Abdallah-al-hallak** [appwrite/appwrite#3531]
### 👟 Reproduction steps

When I upgraded my current version from 0.14 to 0.15.2 I lost my data

### 👍 Expected behavior

return the same data as always

### 👎 Actual Behavior

all my projects have gone

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Abdallah-al-hallak** [comment]
![fa](https://user-images.githubusercontent.com/57962596/178134473-625e9bb2-b803-4987-a771-74c412459c11.PNG)

**Comment by stnguyen90** [comment]
A few questions for you:

1. How did you yogrzde?
2. Did you run the migrate command?
3. What's in your appwrite folder?
