### ISSUE TITLE
🐛 Bug Report: Missing timestamps in Database view in Console

### ISSUE THREAD

**Issue by karniv00l** [appwrite/appwrite#3533]
### 👟 Reproduction steps

- create database
- go to database's Settings tab in Console
- See empty timestamps:

<img width="318" alt="Screenshot 2022-07-11 at 00 37 15" src="https://user-images.githubusercontent.com/3144291/178164667-3554ae55-d67e-4c5f-8dc5-4a9eb5cb6e2d.png">

### 👍 Expected behavior

To see database's timestamps

### 👎 Actual Behavior

Empty timestamps

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by karniv00l** [comment]
I believe this is here: https://github.com/appwrite/appwrite/blob/master/app/views/console/databases/database.phtml#L295-L296

it uses old attribute names, but I couldn't get this to work, I have no idea how this JS framework works and how is this populated here

**Comment by stnguyen90** [comment]
Thanks for raising this! We'll look into this as soon as we can!

**Comment by TorstenDittmann** [comment]
btw, I had to bump this to 0.16 Milestone.

I don't wanna modify an API for a patch release 👍🏻

**Comment by TorstenDittmann** [comment]
This got implemented and released with Appwrite 1.0.0 🥳 

Thank you for your contribution 🙏🏻  You can read more [here](https://appwrite.io/1.0).
