### ISSUE TITLE
🐛 Bug Report: Event trigger resets on each function deployment

### ISSUE THREAD

**Issue by hey-nicolasklein** [appwrite/appwrite#3536]
### 👟 Reproduction steps

* Initially deploy a function created via appwrite init function
* Define any event trigger like collections.*.documents.*.delete
* Save with update button
* Change anything on your cloud function
* deploy new version to appwrite

The trigger events are cleared and have to be set again.

### 👍 Expected behavior

The trigger should stay the same as before the deployment.

### 👎 Actual Behavior

The trigger is cleared, and I have to set it again after each deployment.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Docker locally

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by hey-nicolasklein** [comment]
> There isn't a bi-directional sync between the appwrite.json file and the Appwrite instance. The typical workflow for Infrastructure as Code is to make changes to your config file and then deploy.

This makes sense. I probably have to think about appwrite more like a little AWS than to think about it like a web server.

> `execute` corresponds to the "Execute Access" field in the Appwrite Console. You would have an array of [permissions](https://appwrite.io/docs/permissions) there.

This hasn't been at all clear to me from the get go. I think there should be an own docs page about the appwrite.json. Like there is one for the env variables.

**Comment by stnguyen90** [comment]
> This hasn't been at all clear to me from the get go. I think there should be an own docs page about the appwrite.json. Like there is one for the env variables.

@gewenyu99, thoughts on this?

**Comment by gewenyu99** [comment]
> > This hasn't been at all clear to me from the get go. I think there should be an own docs page about the appwrite.json. Like there is one for the env variables.
> 
> @gewenyu99, thoughts on this?

Planned. We should at the very least have it as a part of the CLI docs. Going to speak with @eldadfux if we can have a separate doc page. The config file is certainly not self-explanatory.

**Comment by hey-nicolasklein** [comment]
I would also like to add my indexes to the appwrite.json file. But I cannot find any docs on how to define them in the appwrite.json file. Any help would be appreciated :)

**Comment by stnguyen90** [comment]
Hey @hey-nicolasklein,

> I would also like to add my indexes to the appwrite.json file. But I cannot find any docs on how to define them in the appwrite.json file. Any help would be appreciated :)

Here's a sample:

https://github.com/stnguyen90/places/blob/main/appwrite.json.default#L36-L50

> I read on Discord that I can run `appwrite init collection` to copy my current remote configuration to my local appwrite.json file. This was not at all obvious to me, and the --help direct does not reference this feature.

That command is documented here: https://appwrite.io/docs/command-line#initializeProject. Help should also give you info:

<details><summary>appwrite --help</summary>

```bash
Usage: appwrite [options] [command]

    _                            _ _           ___   __   _____ 
   /_\  _ __  _ ____      ___ __(_) |_ ___    / __\ / /   \_   \
  //_\\| '_ \| '_ \ \ /\ / / '__| | __/ _ \  / /   / /     / /\/
 /  _  \ |_) | |_) \ V  V /| |  | | ||  __/ / /___/ /___/\/ /_  
 \_/ \_/ .__/| .__/ \_/\_/ |_|  |_|\__\___| \____/\____/\____/  
       |_|   |_|                                                

Appwrite is an open-source self-hosted backend server that abstract and simplify complex and repetitive development tasks behind a very simple REST API

Options:
  -v, --version     output the version number
  --verbose         Show complete error log
  --json            Output in JSON format
  -h, --help        display help for command

Commands:
  login             The login command allows you to authenticate and manage a user account.
  init              The init command helps you initialize your Appwrite project, functions and collections
  deploy            The deploy command provides a convenient wrapper for deploying your functions and collections.
  logout            The logout command allows you to logout of your Appwrite account.
  account           The account command allows you to authenticate and manage a user account.
  avatars           The avatars command aims to help you complete everyday tasks related to your app image, icons, and avatars.
  databases         The databases command allows you to create structured collections of documents, query and filter lists of documents.
  functions         The functions command allows you view, create and manage your Cloud Functions.
  health            The health command allows you to both validate and monitor your Appwrite server's health.
  locale            The locale command allows you to customize your app based on your users' location.
  projects          The projects command allows you to view, create and manage your Appwrite projects.
  storage           The storage command allows you to manage your project files.
  teams             The teams command allows you to group users of your project and to enable them to share read and write access to your project resources
  users             The users command allows you to manage your project users.
  client [options]  The client command allows you to configure your CLI
  help [command]    display help for command
```
</details>

<details><summary>appwrite init --help</summary>

```bash
Usage: appwrite init [options] [command]

The init command helps you initialize your Appwrite project, functions and collections

Options:
  -h, --help            display help for command

Commands:
  project               Initialise your Appwrite project
  function              Initialise your Appwrite cloud function
  collection [options]  Initialise your Appwrite collections
```
</details>

<details><summary>appwrite init collection --help</summary>

```bash
Usage: appwrite init collection [options]

Initialise your Appwrite collections

Options:
  --databaseId <databaseId>  Database ID
  --all                      Flag to initialize all databases
  -h, --help                 display help for command
```
</details>

> Other features of the appwrite CLI do not support that. For example, appwrite init function does not fetch my remote function settings to my appwrite.json file.

Yes, `appwrite init function` allows you to create a new function from scratch. There is no API to pull down the files at the moment.

**Comment by stnguyen90** [comment]
I'm actually going to close this since the initial problem is resolved.
