### ISSUE TITLE
[0.15.2.402] 🐛 Bug Report: Invalid URL on createEmailSession()

### ISSUE THREAD

**Issue by SaabirMohamed** [appwrite/appwrite#3537]
### 👟 Reproduction steps

Good Day Team 

using flutter (android) can't login with "createEmailSession" (but registers the user fine)
using pub package  v^6.0.0 
api version  v:0.15.2.402 
Exception is code : 400 and message "Invalid url: URL host must be one of: localhost, x.x.x.x, domain.com"
my domain settings are all set fine ...was working well with ssl logins etc on 0.14.x
i just had to change createsession to createEmailSession and the above occurs i checked my env file APP_DOMAIN etc all same as before.
I checked the params all ok. even passing in manually my own string for user 
name and pass. still catches this exception.
the docs say params are invalid ...what am I missing or is this a bug.
![Screenshot 2022-07-11 at 19 15 03](https://user-images.githubusercontent.com/8688378/178323433-19797c02-0bb3-4fa2-9a1f-c55d5c2c888d.png)

is this a bug in the new version ...I really don't wana go back to 0.14 :( 

### 👍 Expected behavior

give back a session 

### 👎 Actual Behavior

It just gives this exception ...not sure what I'm am missing here 

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

ubuntu backend , macos with flutter sdk 

### 🧱 Your Environment

Im using and existing server dns records in place  (nginx proxies the connection points to the a custom localhost:port )
this all working fine with ssl etc. with my custom domain (linode ubuntu 20.04)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
"Invalid url: URL host must be one of: localhost, x.x.x.x, domain.com" is an odd error for this API call...Can you check the appwrite container's docker logs for the log that matches this login attempt?

**Comment by SaabirMohamed** [comment]
> "Invalid url: URL host must be one of: localhost, x.x.x.x, domain.com" is an odd error for this API call...Can you check the appwrite container's docker logs for the log that matches this login attempt?

Thanks for your  prompt reply , yes , i will check the docker logs ... i also find it strange that's its mentioning the url, i peeked into the underlying code found nothing i was about to do a postman attempt to the end point and see...ill get back to you without the session i'm stuck.

**Comment by stnguyen90** [comment]
> 1 more thing i forgot to mention is that if i pass invalid credentials ,,, it first logs the error like invalid credentials for email malformed or passwrd etc...then a few moments later this exception

Perhaps another piece of code is throwing this error and not `account.createEmailSession()`? :raised_eyebrow:

**Comment by SaabirMohamed** [comment]
> > 1 more thing i forgot to mention is that if i pass invalid credentials ,,, it first logs the error like invalid credentials for email malformed or passwrd etc...then a few moments later this exception
> 
> Perhaps another piece of code is throwing this error and not `account.createEmailSession()`? 🤨

ok feedback...I DID find errors in 2 containers ....not being able to access the mariadb the php and realtime containers
even if restart with the default env file....something seems to be wrong with my local docker images...anyways Im gona remove all the local images and re-run the install to pull again and see...
it was saying cant connect to sql with [username] using password yes. [all other containers logs fine]
I got the same messages in the logs even when i run new install with the defaults...[docker compose down & up etc]
this is why i decided to delete images ...and try fresh again .
Thanks for the help ! , much appreciated ! 
I think you pointed me in the right direction.

**Comment by SaabirMohamed** [comment]
> > 1 more thing i forgot to mention is that if i pass invalid credentials ,,, it first logs the error like invalid credentials for email malformed or passwrd etc...then a few moments later this exception
> 
> Perhaps another piece of code is throwing this error and not `account.createEmailSession()`? 🤨

NOT A BUG 
ok i finally found the issue as per your clue above cos logs were looking clean ...
but immediately also the same exact error appeared the the appwrite container log(when i try to login)

problem was the function immediately after login 
It actually was logging in successfully  BUT after that 1st login I check emailVerification bool ...and that's were the "URL" issue was clearly telling me my url was wrong that i was passing to sendEmailVerification function ...typo in my constants file.!!!!!!!!  my breakpoint set tooo early 

Thanks again ! I'm up and running

**Comment by SaabirMohamed** [comment]
RESOLVED
