### ISSUE TITLE
🚀 Feature: Bun Support?

### ISSUE THREAD

**Issue by codercatdev** [appwrite/appwrite#3538]
### 🔖 Feature description

Include https://bun.sh runtime into Appwrite's SDK list for servers.

### 🎤 Pitch

I believe that Appwrite's platform should be running the fastest possible JavaScript runtime available.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
With this we could also introduce Bun to Appwrite Functions 🤯 I heard a community member was interested in implementing this. No PR has been submitted yet.

**Comment by gepd** [comment]
Have bun will be even better than deno, not only for the speed, but because we can use typescript and npm packages

**Comment by Meldiron** [comment]
Good news, Bun support is on the way! 🥳 https://github.com/open-runtimes/open-runtimes/pull/85

Sadly there are bugs inside Bun, and we are waiting for them to be addressed before we release it as experimental runtime in Appwrite.

**Comment by gepd** [comment]
With the release of bun 1.0 it would be good to try integrating it again
