### ISSUE TITLE
[Webhooks] account.sessions.create / account.sessions.delete missing in Dashboard

### ISSUE THREAD

**Issue by mehmet-hakan-yazkan** [appwrite/appwrite#355]
Hi, 
in the Documentation the Webhooks **account.sessions.create** and **account.sessions.delete** are mentioned. They are missing in the Webhooks Dashboard.

**Comment by eldadfux** [comment]
Looking at this deeper, seems this issue was already detected by the team and a fix was ready for version 0.7. Don't see any reason why we should wait with this, so I moved the patch to the master branch for the release of 0.6.2.

**Comment by eldadfux** [comment]
Version 0.6.2 is out 🚀🎉

https://dev.to/eldadfux/announcing-the-release-of-the-appwrite-backend-server-v0-6-2-with-support-for-sign-in-with-apple-27cc

Full change log:  https://github.com/appwrite/appwrite/releases/tag/0.6.2
