### ISSUE TITLE
🚀 Feature: Retry mechanism for asynchronous functions 

### ISSUE THREAD

**Issue by karniv00l** [appwrite/appwrite#3555]
### 🔖 Feature description

Provide a mechanism to auto retry failed asynchronous function executions with exponential backoff, like:

- https://firebase.google.com/docs/functions/retries
- https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry

### 🎤 Pitch

This is important for any system to allow self-healing and make it more robust.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
@TorstenDittmann I think we discussed this with refactor of the queue library. Any insights?

**Comment by troykelly** [comment]
+1 for this - it's a critical missing feature.
If we were at least able to purposefully requeue a function, that would be a start.
Without pubsub access, at the moment the only work around is to create a new trigger for the function and track failures.

**Comment by stnguyen90** [comment]
@karniv00l, thanks for creating this issue! 🙏🏼 This is the same as https://github.com/appwrite/appwrite/issues/6369, but it looks like the other issue has more 👍🏼 so I'm going to close this one instead.

It would be best if you and @troykelly added a 👍🏼 to https://github.com/appwrite/appwrite/issues/6369.
