### ISSUE TITLE
📚 Documentation: Some Event Payloads are Incorrect

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#3560]
### 💭 Description

They payload for some `[Events](https://appwrite.io/docs/webhooks#events)` in our docs are incorrect. For example, the following should be Document, rather than Collection.

![image](https://user-images.githubusercontent.com/1477010/179581764-43179db1-a201-46bf-a364-db3937dd200a.png)

I believe [this](https://github.com/appwrite/appwrite/blob/master/app/config/events.php) file needs to be updated.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
> Can I take this up @stnguyen90?

@gewenyu99, have you started this? If not, can @imrishabh18 take this on?

**Comment by Albert-Debbarma** [comment]
@stnguyen90 cani work on thi issue?

**Comment by gewenyu99** [comment]
> > Can I take this up @stnguyen90?
> 
> @gewenyu99, have you started this? If not, can @imrishabh18 take this on?

Yeah, I haven't got to this one yet. I think this would be a great first issue for them!

**Comment by stnguyen90** [comment]
Assigning to @imrishabh18! Thanks for the help! :pray: 

@Albert-Debbarma, If @imrishabh18 isn't able to complete this, you can take over.
