### ISSUE TITLE
🐛 Bug Report: create account restful api does not need API key

### ISSUE THREAD

**Issue by tony21177** [appwrite/appwrite#3564]
### 👟 Reproduction steps

1. I setup My appwrite server based on the instruction of docker command in the official website
2. Create a project on the create project page of appwrite console and get the project ID for the next step
3. Make a http request `POST /v1/account` only with X-Appwrite-Project: XXXXXX
4. the api response give me 201 status code and account info

### 👍 Expected behavior

The `POST /account` API should return 4XX status code and not having permission info...

### 👎 Actual Behavior

But the `POST /v1/account` API return 201 status code and the successfully created account information
![image](https://user-images.githubusercontent.com/38462595/179925554-5828c2f4-e52b-47bc-a51b-7f70eb30662b.png)

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Install in Windows Desktop Docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Hi, thanks for creating an issue! :pray: However, this is the expected behavior and is what allows new users to sign up. :monocle_face:

**Comment by tony21177** [comment]
thank you,I see.
I will close this issue
