### ISSUE TITLE
🐛 Bug Report: users.*.create does not trigger when the user is created using OAuth

### ISSUE THREAD

**Issue by rdmchr** [appwrite/appwrite#3565]
### 👟 Reproduction steps

1. Set up a function that triggers on the event `users.*.create`
2. Create a user using OAuth (I used Discord)
3. The function should not trigger
4. Set the event to `users.*.sessions.*.create`
5. Create another user
6. The function should trigger

### 👍 Expected behavior

I expect the function to trigger even if the user is created using OAuth.

### 👎 Actual Behavior

The function does not get triggered.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I'm using Cloudflare and I think the only thing I changed from the default config is the SMTP env variables.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by PineappleIOnic** [comment]
This issue appears to be caused by the same problem as https://github.com/appwrite/appwrite/issues/2406
