### ISSUE TITLE
Event/Error Monitoring feature

### ISSUE THREAD

**Issue by vincentnacar02** [appwrite/appwrite#357]
It's good to have an error/event monitoring dashboard in this app, something like Sentry.

**Comment by eldadfux** [comment]
Sounds cool, let's keep this issue open for more community feedback. 

Do you see this as something that logs all the Appwrite API errors (4**, 5**) or as a service that allow developers to report projects errors?

**Comment by vincentnacar02** [comment]
I see it as a service that we can call from our projects, but it is also good to have internal error reporting for Appwrite API :)

**Comment by TorstenDittmann** [comment]
This would become essential in my opinion with the upcoming Cloud Functions 👍

**Comment by int-20h** [comment]
It would be great to have a way to see all the events/error in some centralized place in AppWrite with stats and graphs.  Also, there should be a way to get to those logs so that I can ship them to some centralized logging system: ElasticSearch, Loggly, etc...
Pub/Sub by Redis can help on this as well!

**Comment by eldadfux** [comment]
We plan to have an API endpoint, webhooks and functions event for all logs, that way you could just write a function that will be execute any time a log is created (or periodically) and transmit the logs to any service you like.

Having ready-made integrations for elastic, loggly, and others can also be a great feature, new integrations could also be easily contributed by the community, so the offering here could be pretty huge.

**Comment by eldadfux** [comment]
Version 0.7/0.8 will also improve the way we use stdout and stderr in Appwrite Docker containers, so you could easily integrate with any service that has support for collecting docker logs. In future versions each process (api, workers, scheduler) will run in an independent container which will allow a much easier monitoring.

**Comment by TorstenDittmann** [comment]
We have added support for third party error logging providers. This should allow users to achieve what is discussed here 👍🏻 

Closing this for now.
