### ISSUE TITLE
🚀 Feature: teams: adding new members without email id

### ISSUE THREAD

**Issue by gandhimaulik** [appwrite/appwrite#3570]
### 🔖 Feature description

- As of now Adding new members(existing or new) to a team requires email as input. 
- There should be a way for adding existing or new members using Phone number. 
- Invites can be sent using phone sms providers instead of email in that case.

### 🎤 Pitch

Since Phone Auth is supported, Users signing up with phone auth will not have valid email id. 
We are not able to add those users to Team as of now.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thank you for raising this issue! 🙏 We’ll dig into this and get back to you as soon as we can. 😊

**Comment by stnguyen90** [comment]
For backward compatibility on the API, how about we make email optional and add userId and phone as optional:

```php
App::post('/v1/teams/:teamId/memberships')
    ->desc('Create Team Membership')
    // ...
    ->param('teamId', '', new UID(), 'Team ID.')
    ->param('userId', '', new UID(), 'User ID.', true)
    ->param('email', '', new Email(), 'Email of the new team member.', true)
    ->param('phone', '', new Phone(), 'Phone number. Format this number with a leading \'+\' and a country code, e.g., +16175551212.', true)
    ->param('roles', [], new ArrayList(new Key(), APP_LIMIT_ARRAY_PARAMS_SIZE), 'Array of strings. Use this param to set the user roles in the team. A role can be any string. Learn more about [roles and permissions](/docs/permissions). Maximum of ' . APP_LIMIT_ARRAY_PARAMS_SIZE . ' roles are allowed, each 32 characters long.')
    ->param('url', '', fn($clients) => new Host($clients), 'URL to redirect the user back to your app from the invitation email.  Only URLs from hostnames in your project platform list are allowed. This requirement helps to prevent an [open redirect](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html) attack against your project API.', false, ['clients']) // TODO add our own built-in confirm page
    ->param('name', '', new Text(128), 'Name of the new team member. Max length: 128 chars.', true)
```

and in the body check to make sure only one of the values are non-empty.

**Comment by stnguyen90** [comment]
> @stnguyen90 What if user fills both email and phone, but there are already 2 accounts with these 2 information? What if they fill all 3 - including userID?

I'd say we return a bad request response. Either that or we can have some order of precedence.

**Comment by gandhimaulik** [comment]
Any plan to intercept this sooner? 
I see lot of updates to appwrite recently but
without this, teams feature and phone auth does not work together meaningfully.

**Comment by eldadfux** [comment]
> For backward compatibility on the API, how about we make email optional and add userId and phone as optional:
> 
> ```
> App::post('/v1/teams/:teamId/memberships')
>     ->desc('Create Team Membership')
>     // ...
>     ->param('teamId', '', new UID(), 'Team ID.')
>     ->param('userId', '', new UID(), 'User ID.', true)
>     ->param('email', '', new Email(), 'Email of the new team member.', true)
>     ->param('phone', '', new Phone(), 'Phone number. Format this number with a leading \'+\' and a country code, e.g., +16175551212.', true)
>     ->param('roles', [], new ArrayList(new Key(), APP_LIMIT_ARRAY_PARAMS_SIZE), 'Array of strings. Use this param to set the user roles in the team. A role can be any string. Learn more about [roles and permissions](/docs/permissions). Maximum of ' . APP_LIMIT_ARRAY_PARAMS_SIZE . ' roles are allowed, each 32 characters long.')
>     ->param('url', '', fn($clients) => new Host($clients), 'URL to redirect the user back to your app from the invitation email.  Only URLs from hostnames in your project platform list are allowed. This requirement helps to prevent an [open redirect](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html) attack against your project API.', false, ['clients']) // TODO add our own built-in confirm page
>     ->param('name', '', new Text(128), 'Name of the new team member. Max length: 128 chars.', true)
> ```
> 
> and in the body check to make sure only one of the values are non-empty.

I think we can move forward with this and as @stnguyen90 mentioned, we can throw an 409 conflict exception order of precedence `ID > EMAIL > PHONE`.
