### ISSUE TITLE
🚀 Feature: [OAuth2] once a user login using ```OAuth2``` should grab the default profile ```avatar_url``` and add it to the ```User``` object. 

### ISSUE THREAD

**Issue by Shiba-Kar** [appwrite/appwrite#3574]
### 🔖 Feature description

Once a user login using any OAuth providers , grab the avatar Url and add to the User object as appwrite response.

## The current respose payload is.. ##

```json
{
  "$id": "62d8138dcfb0d22c2824",
  "$createdAt": 1658327949,
  "$updatedAt": 1658345166,
  "name": "Shiva Kar",
  "registration": 1658327949,
  "status": true,
  "passwordUpdate": 0,
  "email": "shibaprasadkar50@gmail.com",
  "phone": "",
  "emailVerification": true,
  "phoneVerification": false,
  "prefs": {
    "data": {}
  }
}
```
## Proposing a "avatar_url" in the payload. ##

```json
{
  "$id": "62d8138dcfb0d22c2824",
  "$createdAt": 1658327949,
  "$updatedAt": 1658345166,
  "name": "Shiva Kar",
  "registration": 1658327949,
  "status": true,
  "passwordUpdate": 0,
  "email": "shibaprasadkar50@gmail.com",
  "phone": "",
  "emailVerification": true,
  "phoneVerification": false,
  "avatar_url":""
  "prefs": {
    "data": {}
  }
}
```

### 🎤 Pitch

Supabase is doing this.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I'm not really sure how much value this will bring as users data isn't publicly available. In addition, it's hard to tell if there is even an avatar URL.

I could see this being implemented as an Appwrite Function. On new OAuth2 session, try to get the avatar URL and put it in a custom Profiles collection. What do you think?

**Comment by Shiba-Kar** [comment]
@stnguyen90 function is a way.

**Comment by zaynOm** [comment]
@stnguyen90 I totally agree with this,  im using `node-appwrite` there is no way to get the profile picture, I can't even access the `providerAccessToken` since there is only `createOAuth2Token` on the nodejs package
