### ISSUE TITLE
🐛 Bug Report: Team Membership Create returns wrong membership

### ISSUE THREAD

**Issue by TheMardy** [appwrite/appwrite#3583]
### 👟 Reproduction steps

Create a team membership, I get my membership as response instead of the newly created membership.

### 👍 Expected behavior

Get the newly created membership as response.

### 👎 Actual Behavior

I get my own membership.

I think
`$email and $name
`
should be used instead of the `$user`.

Take a look at this, as this worked fine in v0.13.4 :
https://github.com/appwrite/appwrite/blob/master/app/controllers/api/teams.php#L422

https://github.com/appwrite/appwrite/blob/cc1ddc87d919d1d167ddb219f42cb75be1b3ea68/app/controllers/api/teams.php#L426

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
From the [docs](https://appwrite.io/docs/models/membership), a Membership object should be returned:

```json
{
    "$id": "5e5ea5c16897e",
    "$createdAt": 1592981250,
    "$updatedAt": 1592981250,
    "userId": "5e5ea5c16897e",
    "userName": "John Doe",
    "userEmail": "john@appwrite.io",
    "teamId": "5e5ea5c16897e",
    "teamName": "VIP",
    "invited": 1592981250,
    "joined": 1592981250,
    "confirm": false,
    "roles": [
        "admin"
    ]
}
```

Are you saying `userId`, `userName`, and `userEmail` should be of the person being added, but right now, it returns the info of the person creating the membership?

Can you clarify what's incorrect about team?

**Comment by TheMardy** [comment]
Indeed, userId, userName, and userEmail should be of the person being added, but right now, it returns the info of the person creating the membership. 
Nothing is wrong with the Team.

**Comment by stnguyen90** [comment]
Closing as should be resolved in next release.
