### ISSUE TITLE
🚀 Feature: Add/Show $createdAt and $updatedAt column along with other attributes column.

### ISSUE THREAD

**Issue by garvitomer** [appwrite/appwrite#3592]
### 🔖 Feature description

Add $createdAt and $updatedAt column along with other attributes column so that I can easily see the time at which a particular row is created/updated. 

### 🎤 Pitch

As it will be much easier compared to clicking a particular row and then see all the data for that.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by garvitomer** [comment]
*In appwrite console

**Comment by p4-k4** [comment]
Then the ability to sort ASC/DESC on top :)

**Comment by fogelito** [comment]
Hey guys,
This feature is live and ticking today on Appwrite or perhaps you can give more information about what data you are trying to achieve or filter. On Document Model these two attributes are available and you have the ability to sort them

**Comment by stnguyen90** [comment]
@garvitomer would you please clarify this is for collection page that shows the list of documents like below?

<img width="1427" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/069083e2-a561-4f7a-bb76-0de9293ca10f">

**Comment by eldadfux** [comment]
This is now available on the Appwrite console. ![Image](https://github.com/user-attachments/assets/6de42908-2112-4ab8-ac23-7e51187f2124)
