### ISSUE TITLE
📚 Documentation: Update in Python SDK -> Storage section -> create_file

### ISSUE THREAD

**Issue by garvitomer** [appwrite/appwrite#3593]
### 💭 Description

In Python SDK -> Storage section -> create_file, please add this line to make it more user-friendly:
'from appwrite.input_file import InputFile'
---------------------------------------------------------
currently there is no mention of InputFile in this:
------------------------------------------------------
''
from appwrite.client import Client
from appwrite.services.storage import Storage

client = Client()

(client
  .set_endpoint('https://[HOSTNAME_OR_IP]/v1') # Your API Endpoint
  .set_project('5df5acd0d48c2') # Your project ID
  .set_key('919c2d18fb5d4...a2ae413da83346ad2') # Your secret API key
)

storage = Storage(client)

result = storage.create_file('[BUCKET_ID]', '[FILE_ID]', InputFile.from_path('file.png'))
'''

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Related issue: https://github.com/appwrite/sdk-generator/pull/496

**Comment by gewenyu99** [comment]
It turns out we're missing this in quite a few SDKs. Good catch.

**Comment by gewenyu99** [comment]
This should be fixed :) already. Closing

https://appwrite.io/docs/server/functions?sdk=python-default#functionsCreateDeployment
