### ISSUE TITLE
📚 Documentation: external managed database

### ISSUE THREAD

**Issue by mmayora-effect** [appwrite/appwrite#3601]
### 💭 Description

is there any possibility to use an external database? i have tried with an external database service (MariaDB: example https://azure.microsoft.com/en-us/services/mariadb/ ) configuring the environment variables but appwrite does not work, i have not seen any documentation or related issues, and i would like to know if there is any configuration i need to make it work?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by mmayora-effect** [comment]
![image](https://user-images.githubusercontent.com/108844965/180892225-7804d57b-5c2a-4757-9243-3de14a129189.png)

**Comment by stnguyen90** [comment]
Yes, it's possible to use an external database. It should be a matter of updating the [environment variables](https://appwrite.io/docs/environment-variables#mariadb). 

The error you're seeing seems to indicate Appwrite can't connect to your external MariaDB instance. Are you sure firewalls  are open and the database is accessible?

**Comment by mmayora-effect** [comment]
i try with mysql client in the server

![image](https://user-images.githubusercontent.com/108844965/180898334-dd9db7ad-ddac-4fe7-9ac2-1ee56dfe914e.png)

**Comment by stnguyen90** [comment]
Did you run `docker compose up -d` to apply the changes? Does running `docker compose exec Appwrite vars` show the correct values?

**Comment by mmayora** [comment]
show this

![image](https://user-images.githubusercontent.com/64213149/181066058-0a299fc8-faf2-4959-903d-deb46e509e83.png)

**Comment by mmayora-effect** [comment]
![181066058-0a299fc8-faf2-4959-903d-deb46e509e83](https://user-images.githubusercontent.com/108844965/181082711-b6dfaa5d-6534-46b0-83a4-9e0dd9b707f9.png)

**Comment by stnguyen90** [comment]
You can check the appwrite container logs again, but "Operation timed out" means the server can't connect to the database server.

**Comment by mmayora-effect** [comment]
hi @stnguyen90 i found a solution, (imagen below) you need to map the host in all services that use DB

![image](https://user-images.githubusercontent.com/108844965/181404265-d2e2ca06-8aab-45df-857e-55b4c64d270f.png)


For use external database the steps to follow

1. change default hostname in .env file
2. remove mariadb service(and depends_on from all services) from docker-compose.yml 
3. add external host to every service that use el DB

is it possible to make a tutorial or add it to the documentation? i did not find an example of how to do it online.

**Comment by stnguyen90** [comment]
I'm glad you got it working 🎉 ! I'll keep this in mind, but this may have been something specific to your environment. Typically, as long as the host machine can resolve the hostname, the docker container should be able to as well.

FYI, I highly recommend you try to minimize changes to your docker-compose.yml file and use a [docker-compose.override.yml](https://docs.docker.com/compose/extends/#understanding-multiple-compose-files) file for any changes. This will make upgrades easier in the future as upgrading will wipe away your customization in the docker-compose.yml file.

Closing as no further action required.
