### ISSUE TITLE
🐛 Bug Report: Attribute Object Model not generated in specifications

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/appwrite#3608]
### 👟 Reproduction steps

When a new specification is generated, no Attribute schema is found in the swagger specs. This causes the page: http://localhost:2080/docs/models/attribute to be missing. the attribute schema is needed for attribute-related realtime events.

### 👍 Expected behavior

Attribute schema is found in the swagger specs.

### 👎 Actual Behavior

Attribute schema is **not** found in the swagger specs.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Fix has been merged.
