### ISSUE TITLE
🐛 Bug Report: Docs website breaks when clicking on the learn more link

### ISSUE THREAD

**Issue by gigili** [appwrite/appwrite#3609]
### 👟 Reproduction steps

* Open the docs website at https://appwrite.io/docs/client/databases
* Scroll down to [List Documents](https://appwrite.io/docs/client/databases?sdk=web-default#databasesListDocuments=) section
* Click on the `Learn more about queries` link

From some minor testing around, it only seems to affect the `Learn more about queries` link, other such as `Learn more about pagination` etc work fine. 

The documentation version is set to `0.15.x` and it doesn't matter which client sdk is selected in the dropdown 

I've tried this on both Google Chrome and Firefox

### 👍 Expected behavior

Expected behavior would be that the documentation page explaining more about queries gets loaded

### 👎 Actual Behavior

The page break and the content doesn't load, only after you force a refresh does the content load properly, see images attached below

![appwrite-docs-bug](https://user-images.githubusercontent.com/2153382/181119230-b98fd7a2-7dae-4e11-b493-b144cd8d275a.jpg)
![appwrite-docs-bug-firefox](https://user-images.githubusercontent.com/2153382/181119234-744afa73-6835-4c13-9e81-bdbef04a6e23.jpg)

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Windows

### 🧱 Your Environment

My setup:

* Windows 10 Pro
* Google Chrome  - Version 103.0.5060.134 (Official Build) (64-bit)
* Firefox - 103.0 (64-bit)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thank you for raising this issue! 🙏 We'll try to resolve this ASAP!

**Comment by stnguyen90** [comment]
This has been fixed and deployed! Thanks again! 🙏
