### ISSUE TITLE
[Bug] text overflow - amount of requests

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#361]
![Anmerkung 2020-05-29 091602](https://user-images.githubusercontent.com/1759475/83233085-78a92380-a18e-11ea-80ff-0371063ba33c.png)

Part of the Label is hidden when the amount is large.

**Comment by eldadfux** [comment]
Fixed 🥳

**Comment by eldadfux** [comment]
Version 0.6.2 is out 🚀🎉

https://dev.to/eldadfux/announcing-the-release-of-the-appwrite-backend-server-v0-6-2-with-support-for-sign-in-with-apple-27cc

Full change log:  https://github.com/appwrite/appwrite/releases/tag/0.6.2
