### ISSUE TITLE
🚀 Feature: Phone identity (user create and account create)

### ISSUE THREAD

**Issue by XanManZA** [appwrite/appwrite#3614]
### 🔖 Feature description

It would be very useful to be able to create a user and account by phone OR email instead of email being exclusively required.

### 🎤 Pitch

In our use case, the user that interacts with the Appwrite BaaS has a default phone-based identity. Prompting a user to sign up with email even though we have the info we need from them (phone) adds a level of unnecessary friction.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thank you for raising this issue! 🙏 

The [Create Phone Session](https://appwrite.io/docs/client/account?sdk=web-default#accountCreatePhoneSession) API will create a user/account if one does not exist. Can you expand further on why you would need to create an account/user before this API is called? 🧐

**Comment by XanManZA** [comment]
> Thank you for raising this issue! pray
> 
> The [Create Phone Session](https://appwrite.io/docs/client/account?sdk=web-default#accountCreatePhoneSession) API will create a user/account if one does not exist. Can you expand further on why you would need to create an account/user before this API is called? monocle_face

Hey Steven! Thanks.
Yes, our solution is server-based right now and proxies through a chat system and webhooks. So it's never a user that is authenticated to Appwrite, it is the server API key.

Here is the flow of the data:
`Chat Program API -> Automation Platform Webhook -> Appwrite Function -> Send Reply to User on Chat Program`

**Comment by eldadfux** [comment]
This is actually already IN WORK before we’ve seen this issue 😅

Learn more at: #2747

**Comment by TorstenDittmann** [comment]
This got implemented and released with Appwrite 1.0.0 🥳 

Thank you for your contribution 🙏🏻  You can read more [here](https://appwrite.io/1.0).
