### ISSUE TITLE
📚 Documentation: Clarify migrations are not always required

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#3624]
### 💭 Description

Even though the upgrade docs state:

> You do not need to run migration when upgrading to a minor version. For example, going from 0.13.0 to 0.13.2 would not require running migration.

When following along with the instructions, the "Running the Migration" just says:

> We can now start the migration. Navigate to the appwrite directory where your docker-compose.yml is present and run the following command

It would be clearer to emphasize, again, to run the migration only if required.

Also, the link on the "Running the Migration" header doesn't work.

Quote from discord:

> I get confused, since it does say not to do it, then below it lays it out as the next step.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by arth2002** [comment]
Please Assign me this issue

**Comment by stnguyen90** [comment]
@arth2002, assigned! Thanks for your help! 🙏

**Comment by arth2002** [comment]
@stnguyen90 Sir,
sorry to bother you
but I can't find the file which needs to be changed 
I find the "running the migration" page which is [https://appwrite.io/docs/upgrade](url)
but I couldn't find it in the docs folder of the project.

Can you please help me with this?

**Comment by stnguyen90** [comment]
@arth2002, here you go! https://github.com/appwrite/docs/blob/main/app/views/docs/upgrade.phtml

**Comment by arth2002** [comment]
Sir, I'm a little confused 
so do I need to create a pull request on the appwrite/docs repository for this issue?

**Comment by 2002Bishwajeet** [comment]
Hey @arth2002 ,
Yes, you need to create a PR on the `appwrite/docs` repo. You can refer to this issue in the PR

**Comment by arth2002** [comment]
@stnguyen90 sir
I've made PR
Please check here--> https://github.com/appwrite/docs/pull/230
Let me know if there is some change to it
Thank You :smile:

**Comment by 09139835182** [comment]
Hi

**Comment by arth2002** [comment]
@stnguyen90 Sir, You can close this issue
It has been solved [here](https://github.com/appwrite/docs/pull/230)
Thanks for your help :smile:

**Comment by stnguyen90** [comment]
@arth2002, thanks for your contribution! 🙏
