### ISSUE TITLE
🐛 Bug Report: Stuck at startup

### ISSUE THREAD

**Issue by mbazs** [appwrite/appwrite#3636]
### 👟 Reproduction steps

When I started appwrite with the docker command mentioned on the homepage it worked for the first time, but after `docker system prune --all --volumes` and rerunning it is completely stuck. It throws such errors:

appwrite-worker-mails         | Next Resque_RedisException: Error communicating with Redis: Connection to Redis tcp://redis:6379 failed after 1 failures.Last Error : (1) Operation timed out in /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php:152
appwrite-worker-mails         | Stack trace:
appwrite-worker-mails         | #0 /usr/src/code/vendor/resque/php-resque/lib/Resque.php(69): Resque_Redis->__construct('redis:6379', 0)
appwrite-worker-mails         | #1 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(104): Resque::redis()
appwrite-worker-mails         | #2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(517): Resque_Worker::all()
appwrite-worker-mails         | #3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(391): Resque_Worker->pruneDeadWorkers()
appwrite-worker-mails         | #4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(167): Resque_Worker->startup()
appwrite-worker-mails         | #5 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
appwrite-worker-mails         | #6 {main}
appwrite-worker-mails         |   thrown in /usr/src/code/vendor/resque/php-resque/lib/Resque/Redis.php on line 152
appwrite-worker-mails         | Appwrite mails worker v1 has started
appwrite-worker-mails         | 
appwrite-worker-mails         | [notice] Starting worker 1ecd472d530c:7:v1-mails
appwrite-maintenance          | Database not ready. Retrying connection (2)...
appwrite-traefik              | time="2022-08-02T17:08:01Z" level=error msg="service \"appwrite_realtime\" error: unable to find the IP address for the container \"/appwrite-realtime\": the server is ignored" providerName=docker container=appwrite-realtime-appwrite-eb6d8f68f4ef3154df6f11275c5625ff9152e266810e9e0733c8bee31c433f45
appwrite-traefik              | time="2022-08-02T17:08:04Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
appwrite-traefik              | time="2022-08-02T17:08:12Z" level=error msg="service \"appwrite_api\" error: unable to find the IP address for the container \"/appwrite\": the server is ignored" providerName=docker container=appwrite-appwrite-5f472a432b893439c68d10be318b1cda44802125d98e9c0a57c47abfca9ddf1f
appwrite-traefik              | time="2022-08-02T17:08:13Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
appwrite-traefik              | time="2022-08-02T17:08:14Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"

...

appwrite                      | Fatal error: Uncaught Exception: Failed to connect to database: SQLSTATE[HY000] [2002] Operation timed out in /usr/src/code/app/http.php:75
appwrite                      | Stack trace:
appwrite                      | #0 {main}
appwrite                      |   thrown in /usr/src/code/app/http.php on line 75
appwrite                      | [2022-08-02 17:15:33 #1.4]      ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Exception: Failed to connect to database: SQLSTATE[HY000] [2002] Operation timed out in /usr/src/code/app/http.php:75
appwrite                      | Stack trace:
appwrite                      | #0 {main}
appwrite                      |   thrown in /usr/src/code/app/http.php on line 75
appwrite                      | [Static Files] Loadded 137 files
appwrite                      | Worker 1 started successfully
appwrite                      | Worker 2 started successfully
appwrite                      | Worker 3 started successfully
appwrite                      | Worker 4 started successfully
appwrite                      | Worker 5 started successfully
appwrite                      | Worker 6 started successfully
appwrite                      | Worker 7 started successfully
appwrite                      | Worker 8 started successfully
appwrite                      | Worker 9 started successfully
appwrite                      | Worker 10 started successfully
appwrite                      | Worker 11 started successfully
appwrite                      | Worker 12 started successfully
appwrite                      | Worker 13 started successfully
appwrite                      | Worker 14 started successfully
appwrite                      | Worker 15 started successfully
appwrite                      | Worker 16 started successfully
appwrite                      | Worker 17 started successfully
appwrite                      | Worker 18 started successfully
appwrite                      | Worker 19 started successfully
appwrite                      | Worker 20 started successfully
appwrite                      | Worker 21 started successfully
appwrite                      | Worker 22 started successfully
appwrite                      | Worker 23 started successfully
appwrite                      | Worker 24 started successfully
appwrite                      | Database not ready. Retrying connection (1)...
appwrite                      | Database not ready. Retrying connection (2)...
appwrite                      | Database not ready. Retrying connection (3)...
appwrite                      | Database not ready. Retrying connection (4)...
appwrite-realtime             | Database not ready. Retrying connection (7)...
appwrite                      | Database not ready. Retrying connection (5)...
appwrite-usage                | Database not ready. Retrying connection (2)...

### 👍 Expected behavior

Appwrite starts without problems.

### 👎 Actual Behavior

Startup stuck, various containers are restarting all the time:

CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS              PORTS                                                                      NAMES
906c7531a28d   appwrite/appwrite:0.15.3   "worker-functions"       10 minutes ago   Up About a minute   80/tcp                                                                     appwrite-worker-functions
fab229798bc0   appwrite/appwrite:0.15.3   "executor"               10 minutes ago   Up 10 minutes       80/tcp                                                                     appwrite-executor
c5ed2bbb5343   traefik:2.7                "/entrypoint.sh --pr…"   10 minutes ago   Up 10 minutes       0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   appwrite-traefik
5f472a432b89   appwrite/appwrite:0.15.3   "docker-php-entrypoi…"   10 minutes ago   **Up 6 seconds**        80/tcp                                                                     appwrite
42ce8620fd25   appwrite/appwrite:0.15.3   "usage"                  10 minutes ago   Up 20 seconds       80/tcp                                                                     appwrite-usage
d136762e9841   appwrite/appwrite:0.15.3   "worker-audits"          10 minutes ago   Up About a minute   80/tcp                                                                     appwrite-worker-audits
6ff4312d10aa   appwrite/appwrite:0.15.3   "worker-databases"       10 minutes ago   Up About a minute   80/tcp                                                                     appwrite-worker-databases
ac69cb725f71   appwrite/appwrite:0.15.3   "worker-builds"          10 minutes ago   Up About a minute   80/tcp                                                                     appwrite-worker-builds
2d008dfe9edc   appwrite/appwrite:0.15.3   "worker-certificates"    10 minutes ago   Up About a minute   80/tcp                                                                     appwrite-worker-certificates
eb6d8f68f4ef   appwrite/appwrite:0.15.3   "realtime"               10 minutes ago   **Up 13 seconds**       80/tcp                                                                     appwrite-realtime
0e98cf2d810b   appwrite/appwrite:0.15.3   "worker-webhooks"        10 minutes ago   Up About a minute   80/tcp                                                                     appwrite-worker-webhooks
708ddcec51ca   appwrite/appwrite:0.15.3   "worker-deletes"         10 minutes ago   Up About a minute   80/tcp                                                                     appwrite-worker-deletes
1ecd472d530c   appwrite/appwrite:0.15.3   "worker-mails"           10 minutes ago   Up About a minute   80/tcp                                                                     appwrite-worker-mails
479d7ef0e80d   appwrite/appwrite:0.15.3   "maintenance"            10 minutes ago   Up 10 minutes       80/tcp                                                                     appwrite-maintenance
f400bd394123   appwrite/appwrite:0.15.3   "schedule"               10 minutes ago   Up About a minute   80/tcp                                                                     appwrite-schedule
4a7b7816454f   mariadb:10.7               "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes       3306/tcp                                                                   appwrite-mariadb
c3d6e22898f2   appwrite/influxdb:1.5.0    "/entrypoint.sh infl…"   10 minutes ago   Up 10 minutes       8086/tcp                                                                   appwrite-influxdb
fcb565109e2b   redis:6.2-alpine           "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes       6379/tcp                                                                   appwrite-redis
8dcd4876a49a   appwrite/telegraf:1.4.0    "/entrypoint.sh tele…"   10 minutes ago   Up 10 minutes       8092/udp, 8125/udp, 8094/tcp                                               appwrite-telegraf

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Tried on Debian 10 first then purged the whole server and reinstalled Debian 11 but the same happens. Tried everything, tried with custom ports in the first place: 2080, 2443, then changed to 80, 443 to no avail.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@mbazs it seems something is wrong with mariadb and redis. Would you please check the logs?

```
docker compose logs mariadb
docker compose logs redis
```

Also, can you check what's running with `docker ps`?

**Comment by mbazs** [comment]
Hi @stnguyen90,

Thank you. Mariadb and redis logs seem ok, attaching the entire log (however lines are mixed a bit) if not a problem.
[logs_no_color.txt](https://github.com/appwrite/appwrite/files/9245851/logs_no_color.txt)

**Comment by stnguyen90** [comment]
@mbazs it looks like mariadb and redis took some time but did spin up properly. I agree this might be a docker network corruption or something. I would try to remove the containers and volumes and prune docker before trying again.

**Comment by mbazs** [comment]
Trying further

**Comment by mbazs** [comment]
Thank you @stnguyen90 for checking this, trying further to fix my installation.

**Comment by mbazs** [comment]
Hi @stnguyen90 ,

I am an idiot. Forward chain was set to DROP in nftables ... now appwrite is working perfectly 👍 
Sorry for this and thank you for your time.

**Comment by jabedzaman** [comment]
I am facing the same isse can you explain it a bit more how you resolved it

**Comment by mbazs** [comment]
> I am facing the same isse can you explain it a bit more how you resolved it
> 
> 

I just failed to enable my firewall's FORWARD chain. Check your firewall settings.
