### ISSUE TITLE
🚀 Feature: authentication without javascript

### ISSUE THREAD

**Issue by 1994benc** [appwrite/appwrite#3647]
### 🔖 Feature description

Based on the documentation, currently user account creation is done on the front end. So, in the case of "web" platform, the front end would need javascript. I'm proposing support for initiating and completing account creation entirely without the need to enable javascript. 

Example 
- user submits email & password via a post request 
- our server (not appwrite server) then handles creating the user's account and sets our own cookie

Interactions with AppWrite would only happen on our server

### 🎤 Pitch

For some web apps, we don't want to ship javascript to the client. So, a way to authenticate users in a more traditional way without the use of javascript would be very beneficial. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by gepd** [comment]
Currently, you can make http requests without javascript

check this article: https://medium.com/appwrite-io/how-to-connect-with-the-appwrite-backend-server-directly-using-only-the-appwrite-http-api-1e720b567395

**Comment by stnguyen90** [comment]
@1994benc, thanks for creating this issue! 🙏 The web SDK is meant for javascript based apps. If you're building an app with your own back end server, you would typically manage users, sessions, permissions yourself and use a server SDK to interact with Appwrite. If you really want to make use of Appwrite authentication, you could manually make the [Create Account Session with Email](https://appwrite.io/docs/client/account?sdk=web-default#accountCreateEmailSession) API call in your back end server, but you'l have to manage the users' sessions yourself. For example, one thing you'd do is grab the Appwrite session cookie and store it in your servers session management. Hope that helps!

**Comment by 1994benc** [comment]
@stnguyen90 thank you for the clarification. I asked partly also because i tried the web sdk in a node environment and got no errors. I successfully created a user and got a session. How do I grab the appwrite cookie you mentioned so that i can pass it to my client as a secure cookie. I haven't found a proper guide around doing this. Thank you in advance! Love appwrite so far and excited to use it in my project.

**Comment by stnguyen90** [comment]
@1994benc, the easiest thing to do would be to manually make the create session API call rather than using the SDK so that you can get the Response object and grab the session from the set cookie header.
