### ISSUE TITLE
Disable the registration in appwrite panel.

### ISSUE THREAD

**Issue by therhenals** [appwrite/appwrite#365]
Hello good, I installed appwrite, I want to know if it is possible to disable the registration in appwrite, ie not allow the creation of new projects from unknown users, because when I install I realize that is free for anyone to register in the panel, there is no admin account.

---
Appwrite Version: 0.6.1.125

**Comment by eldadfux** [comment]
Yes you can. Check this out: https://medium.com/appwrite-io/you-can-now-restrict-access-to-your-appwrite-console-b8b447885289

We do have a plan to create an improved admin flow and dashboard in the near future.

**Comment by therhenals** [comment]
Thank you very much for the answer, I have another question, it is possible to deactivate the registration by email on the client side of a project, which only allows the login.

**Comment by eldadfux** [comment]
Please open a separate issue about this idea, I can see how this can be beneficial, but please provide more information about your use-case and thoughts. This will also allow us to get more feedback from other community members before thinking of implementation.

**Comment by eldadfux** [comment]
Closing current issue. @therhenals please raise a new issue with more info about your idea to block registration.
