### ISSUE TITLE
📚 Documentation: ask appwrite if the data in a collections have changed

### ISSUE THREAD

**Issue by paulFlow33** [appwrite/appwrite#3650]
### 💭 Description

Hi guys, in your error codes there is the 304 which is provided by the server if the data has not changed. I searched all the documentation but couldn't figure out how to ask if the data in a collection has changed or not. In that case I wanted to ask the server if the data has changed in a collectio even with a query addition.
For example I search the collection for id with a query, it answers me with x data, after a period of time I would like to check with the same query if the y data of the answer are equal to x, that is, the data has not changed. Can it be done somehow?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@paulFlow33, thanks for creating this issue! 🙏 

> For example I search the collection for id with a query, it answers me with x data, after a period of time I would like to check with the same query if the y data of the answer are equal to x, that is, the data has not changed. Can it be done somehow?

I would suggest storing the `$updatedAt` timestamp from the [Document](https://appwrite.io/docs/models/document) locally and then comparing it with the Document's `$updatedAt` timestamp in subsequent queries.

**Comment by paulFlow33** [comment]
Hi, thanks for the reply. Yes, I have thought about it but the band is not reduced anyway. We can ask the database to create documents, provide us with a list, directly give a document and finally delete it. We all know this. The updatedAt data is provided by the listDocument method, but the data is also hooked into that method. So would it be useless or am I missing something ??

**Comment by paulFlow33** [comment]
However I can make a cloud function that allows me to receive only an integer (updateAt), and thus decrease the bandwidth. I link here with another question but if you want then I can open another question. Calling the listDocument function as we all know the maximum number of documents returned is 100. Well, if we have more than 100 documents in the db, the variable total will be 100 or will it tell us how many documents it found with the query? Why should I use it to understand whether to make the layout.

**Comment by paulFlow33** [comment]
I did some tests, it seems that the total of the documents actually corresponds to the documents found so we can use the variable total to understand if we have to make the pagination. If you too had imagined such a thing, I recommend writing this example of use in the docuement list object.

![image](https://user-images.githubusercontent.com/110695830/184497443-c15d8a4d-2881-4f74-92d2-67a8de1518d4.png)
