### ISSUE TITLE
🚀 Feature: Get current server timestamp.

### ISSUE THREAD

**Issue by binhodev** [appwrite/appwrite#3655]
### 🔖 Feature description

As with Firestore, you can get the current timestamp and date.
`serverTimestamp()`

Here in the Appwrite SDKs there is no method of getting the timestamp from the server.

### 🎤 Pitch

This method is useful for making comparisons with the current server time.
For example, the user has a time limit to create a new post, for which he would consult the time from the server if it is possible or not.
By doing this locally there is the possibility for the user to bypass the time on his device and create a new post.

It's possible to do it through Cloud Functions, but having to write the whole method in the Cloud to get the timestamp is unnecessary.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Hi @binhodev! Thanks for raising this issue! 🙏 

> For example, the user has a time limit to create a new post, for which he would consult the time from the server if it is possible or not.

Could you give more details about the use case in which you need the server timestamp? I'm still trying to understand what instances where you would need the server's timestamp client side. If you wanted to make this type of validation, you would use an Appwrite Function which could get the server time.

**Comment by binhodev** [comment]
> Hi @binhodev! Thanks for raising this issue! 🙏
> 
> > For example, the user has a time limit to create a new post, for which he would consult the time from the server if it is possible or not.
> 
> Could you give more details about the use case in which you need the server timestamp? I'm still trying to understand what instances where you would need the server's timestamp client side. If you wanted to make this type of validation, you would use an Appwrite Function which could get the server time.

Yes, as I mentioned above, it is possible using Functions, but creating one for this is kind of unnecessary. Well thanks!
