### ISSUE TITLE
unable to update a file with same id.🐛 Bug Report: 

### ISSUE THREAD

**Issue by bliyscom** [appwrite/appwrite#3657]
### 👟 Reproduction steps

I wish to be able to change a profile picture. Ideally, it would be nice to just use the update file api to that but this api does not 
support upload of a new file to replace the old file.
when i create or upload a file to storage with a certain id
if i delete that file and upload a different file with the same Id as the previous file, 
it loads the same previous file.
Now does it mean appwrite stores the previous file although deleted in some kind of cache?

### 👍 Expected behavior

I wish to be able to change the profile picture. 
if its possible, i would like to know how to update a file with the possibility of changing the file itself.
Otherwise, i would love to be able to delete a file and upload a new file with the same id as the previous file
and have a new file displayed.

### 👎 Actual Behavior

if i delete that file and upload a different file with the same Id as the previous file, 
it loads the same previous file.
Now does it mean appwrite stores the previous file although deleted in some kind of cache?

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@bliyscom, thanks for raising this issue! 🙏 

> if i delete that file and upload a different file with the same Id as the previous file,
> it loads the same previous file.
> Now does it mean appwrite stores the previous file although deleted in some kind of cache?

This is probably happening because the browser is caching the image. For this reason, I suggest creating a new file and updating your reference to that file.

**Comment by bliyscom** [comment]
Hello and thanks for chiming in again. I appreciate your response.
That said, I am doing these operations through api calls and not directly on the browser.
So I am not sure how the browsers cache is affecting it. Nonetheless, I will perform more tests and revert with
feedback.

**Comment by bliyscom** [comment]
you were right. After disabling network and memory cache in the browsers, the real image shows up. Thanks
