### ISSUE TITLE
Cookies not working in iOS OAuth2 app

### ISSUE THREAD

**Issue by mbazs** [appwrite/appwrite#3669]
### 👟 Reproduction steps

Making an OAuth2 auth call with

`createOAuth2Session(provider: "apple")`

This is a SwiftUI app and the callback URL is captured by this root view modifier:

```
var body: some Scene {
        WindowGroup {
            ContentView()
                .onOpenURL { url in
                    guard (url.absoluteString.contains("appwrite-callback")) else { return }
                    print("got url: \(url)")
                    WebAuthComponent.handleIncomingCookie(from: url)
                }
      }
}
```
This prints the callback URL properly:

`got url: appwrite-callback-62ed3f94ebe1d06d8ac8://?project=62ed3f94ebe1d06d8ac8&domain=.aw.hjkl.hu&key=a_session_62ed3f94ebe1d06d8ac8&secret=eyJpZCI6IjYyZjViMDk3NWRjMDA2NzMzZmQ5Iiwic2VjcmV0IjoiYjE1MDQ1NTZjNjAxY2EwMGI1ZDMxNjIyZGY1OTI0M2JjYTBhODRlYWU5ZWFkMDYyYjg2OWY5NTZkZWFkMjI0YmJjMjE2ODdkOTRjMzUyNGNhMzNjYjNhYWU0YzIwZjZiMmZhMDk5NjZhYmM5OTg0ZmFjYWU0NmY3OGNjMzg3ODM4NDhlOGMxZWJkMjAxNzRjNmY3NTNmYTRiMTg5NWY4NDU0MGQ5MzFlNWI1MjljOTlkMWEwNzE3MmEwNTg0YmIwMTBiZTlkYjMwYmE4YjFlZTdjNmQwMTk5YjJhYzRjNDg4M2E0NmFhNzllM2E5ZWRiNzE5ODYxYzc4MTM0YTYxMSJ9`

... and the app opens up nicely.
But then the app says when executing a new call:

`User (role: guest) missing scope (account)`

It seems cookies don't work. Inspected UserDefaults with dump():

```
▿ (2 elements)
    - key: "aw.hjkl.hu-cookies"
    ▿ value: {"path":"\/","value":"eyJpZCI6IjYyZjViMDk3NWRjMDA2NzMzZmQ5Iiwic2VjcmV0IjoiYjE1MDQ1NTZjNjAxY2EwMGI1ZDMxNjIyZGY1OTI0M2JjYTBhODRlYWU5ZWFkMDYyYjg2OWY5NTZkZWFkMjI0YmJjMjE2ODdkOTRjMzUyNGNhMzNjYjNhYWU0YzIwZjZiMmZhMDk5NjZhYmM5OTg0ZmFjYWU0NmY3OGNjMzg3ODM4NDhlOGMxZWJkMjAxNzRjNmY3NTNmYTRiMTg5NWY4NDU0MGQ5MzFlNWI1MjljOTlkMWEwNzE3MmEwNTg0YmIwMTBiZTlkYjMwYmE4YjFlZTdjNmQwMTk5YjJhYzRjNDg4M2E0NmFhNzllM2E5ZWRiNzE5ODYxYzc4MTM0YTYxMSJ9","httpOnly":false,"name":"a_session_62ed3f94ebe1d06d8ac8","secure":false} #3
```

It goes weird looking at this code in **HTTPClientRequest+Cookies.swift**:

```
extension HTTPHeaders {
    public mutating func addDomainCookies(for domain: String) {
        guard let cookies = UserDefaults.standard.stringArray(forKey: "\(domain)-cookies") else {
            return
        }
        for cookie in cookies {
            add(name: "Cookie", value: cookie)
        }
    }
}
```

because it's not even a string array in UserDefaults (instead it's a JSON string) and the guard fails, so no cookies are sent.

So I'm quite confused about this whole stuff because as I can see no cookies go back to the webserver. I have inspected Apache2 cookie log and no cookies are sent back at all. Any ideas or am I missing something?

### 👍 Expected behavior

Cookies work in iOS app

### 👎 Actual Behavior

Authentication OK, Appwrite server is called back by Apple ID, Appwrite is successfully authenticated and I can see the user's session in the console correctly, but when getting back to the app by the callbackscheme URL (which seems good) the app doesn't seem to store the cookies properly, i.e. the session in the app is not authenticated.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by mbazs** [comment]
Now it works, copied out `WebAuthComponent.handleIncomingCookie(from: url)` source and modified so now it saves the session cookie properly:


```
    ....
    var body: some Scene {
        WindowGroup {
            ContentView()
                .onOpenURL { url in
                    guard (url.absoluteString.contains("appwrite-callback")) else { return }
                    print("got url: \(url)")
                    //WebAuthComponent.handleIncomingCookie(from: url)
                    parseCallbackUrlToCookies(url: url)
                }
                .environment(\.managedObjectContext, persistenceController.container.viewContext)
        }
    }
}

func parseCallbackUrlToCookies(url: URL) {
    let components = URLComponents(string: url.absoluteString)!
    let cookieParts = [String: String](uniqueKeysWithValues: components.queryItems!.map {
        ($0.name, $0.value!)
    })
    var domain = cookieParts["domain"]!
    domain.remove(at: domain.startIndex)
    let cookie: String = "\(cookieParts["key"]!)=\(cookieParts["secret"]!)"
    UserDefaults.standard.set([cookie], forKey: "\(domain)-cookies")
    WebAuthComponent.onCallback(
        scheme: components.scheme!,
        url: components.url!
    )
}
```


I suspect it didn't work because Apple client is beta?

**Comment by stnguyen90** [comment]
@mbazs, thanks for raising this issue! 🙏 . Which Appwrite SDK are you using and what version? Also, what version of Appwrite are you on?

**Comment by mbazs** [comment]
> @mbazs, thanks for raising this issue! 🙏 . Which Appwrite SDK are you using and what version? Also, what version of Appwrite are you on?

Appwrite 0.15.3
Appwrite Apple SDK 0.6.0

As I mentioned it works now with above modification, just asking am I missing something or Apple SDK is buggy / not updated? Because as I said above the cookies from incoming callback are stored as JSON string into UserDefaults (this is a simple iOS key-value persistent store) but the readout looks for a string array, that's why the `addDomainCookies` function doesn't find it so the session cookie is not set up for the iOS app.

**Comment by abnegate** [comment]
@mbazs Thank you for the report, this was indeed a bug in the OAuth flow. It has been addressed [here](https://github.com/appwrite/sdk-generator/pull/520/files) and the next release will include the fix!

**Comment by mbazs** [comment]
> @mbazs Thank you for the report, this was indeed a bug in the OAuth flow. It has been addressed [here](https://github.com/appwrite/sdk-generator/pull/520/files) and the next release will include the fix!

Thank you !!
