### ISSUE TITLE
Suggestion Profile Avatars

### ISSUE THREAD

**Issue by FernandoSini** [appwrite/appwrite#367]
I think would be interesting upload my avatars from pc to use on profile, leaving gravatar as an extra option to add avatars to the profile.

**Comment by eldadfux** [comment]
I was thinking of adding a new initials route to the current avatars service, and maybe add a redirect URL for Gravatar (or even a proxy).

You can currently add an avatar using the storage file (https://appwrite.io/docs/client/storage?sdk=web#createFile) and save a reference to the file in the preferences endpoint (https://appwrite.io/docs/client/account?sdk=web#updatePrefs). This should be pretty much the same thing as a dedicated API endpoint.

**Comment by FernandoSini** [comment]
Nice, Good to know. It will be very useful. Thanks.

**Comment by eldadfux** [comment]
New initials avatar is ready and will be released in version 0.7: https://github.com/appwrite/appwrite/issues/386
