### ISSUE TITLE
🐛 Bug Report: Document creation failed when using url attribute

### ISSUE THREAD

**Issue by Rinma** [appwrite/appwrite#3670]
### 👟 Reproduction steps

When I create a new collection with an url attribute and try to create a new document in it, on the web editor or as api request, with this url: 

https://www.amazon.de/AMAZONAS-Hängemattengestell-RockStone-größenverstellbar-270-330/dp/B005HGW6A4

I get an error message: `Invalid document structure: Attribute "buy_url" has invalid format. Value must be a valid URL`

### 👍 Expected behavior

It should create the document with the url attribute

### 👎 Actual Behavior

It can't create the document when I use an url attribute.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I have a Hetzner root Server with debian Linux and run appwrite with docker-compose instead of the docker command.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by bliyscom** [comment]
Kindly share your code.

**Comment by Rinma** [comment]
Sure, here the error in the web editor and the minimal code:

![image](https://user-images.githubusercontent.com/1405824/184499025-92acb82d-7c57-44d6-a479-2a6d3c73d8d0.png)


```
const db = new Databases(
      this.client,
      "62f7b51b49389fe3a0a6"
    );

db.createDocument(
      "62f7b5201284ef2ef2f7",
      "NewDocumentId",
      {
        url: 'https://www.amazon.de/AMAZONAS-Hängemattengestell-RockStone-größenverstellbar-270-330/dp/B005HGW6A4'
      },
      ['role:all'],
      [`user:62f3eb06921b14c925a7`]
    );
```
And this code gives this error

```
{
    "message": "Invalid document structure: Attribute \"url\" has invalid format. Value must be a valid URL",
    "code": 400,
    "type": "document_invalid_structure",
    "version": "0.15.3"
}
```

The collection attributes are these:

![image](https://user-images.githubusercontent.com/1405824/184499678-5a0ea2de-c91e-4c46-87c5-4d05855f9fa7.png)

**Comment by Rinma** [comment]
I had a thought and tried it `https://www.amazon.de/AMAZONAS-Hngemattengestell-RockStone-grenverstellbar-270-330/dp/B005HGW6A4` <- this would be a valid URL. So, the regex or whatever checks in appwrite if it is a valid URL, seams to have problems with handling German Umlaute "äöüß" in the path part of the URL.

**Comment by bliyscom** [comment]
Good guess. Although, it would be difficult to create a regex rule that supports all languages. So i suggest you keep sanitizing the url for special letters for now. You can equally just paste the url into the browser address bar, then copy paste it back into the field. It should already be translated.

**Comment by stnguyen90** [comment]
@Rinma, thank you for raising this issue! 🙏 . We use PHP's [`filter_var()`](https://www.php.net/manual/en/function.filter-var.php) to validate URLs:

https://github.com/appwrite/appwrite/blob/5b4a3805bf7a1ee54cb562fd525dd471069a4cdd/src/Appwrite/Network/Validator/URL.php#L52

It looks like it [doesn't handle some special characters](https://www.php.net/manual/en/function.filter-var.php#104160). I'll talk to the team about how we can improve this!

**Comment by aakash-kumar-gorai** [comment]
hey @Rinma I want to contribute to this issue . Can you please allow me ?

**Comment by stnguyen90** [comment]
@aakash-kumar-gorai, go for it! Please make sure to add test cases and validate the URL is correct when inserted into the Database **and** when it is retrieved. 🙏

**Comment by MahendraBishnoi29** [comment]
@stnguyen90 there's no update from @aakash-kumar-gorai can you assign it to me?

**Comment by stnguyen90** [comment]
Sure, @MahendraBishnoi29!

**Comment by MahendraBishnoi29** [comment]
also @stnguyen90 can guide me where to make changes because it's my first contribution here :)

**Comment by stnguyen90** [comment]
@MahendraBishnoi29, see my previous [comment](https://github.com/appwrite/appwrite/issues/3670#issuecomment-1214220260).

**Comment by MahendraBishnoi29** [comment]
> @Rinma, thank you for raising this issue! 🙏 . We use PHP's [`filter_var()`](https://www.php.net/manual/en/function.filter-var.php) to validate URLs:
> 
> https://github.com/appwrite/appwrite/blob/5b4a3805bf7a1ee54cb562fd525dd471069a4cdd/src/Appwrite/Network/Validator/URL.php#L52
> 
> It looks like it [doesn't handle some special characters](https://www.php.net/manual/en/function.filter-var.php#104160). I'll talk to the team about how we can improve this!


@stnguyen90 are you talking about this one? 🤔

**Comment by stnguyen90** [comment]
> @stnguyen90 are you talking about this one? 🤔

Yes, @MahendraBishnoi29.

**Comment by MahendraBishnoi29** [comment]
> > @stnguyen90 are you talking about this one? 🤔
> 
> Yes, @MahendraBishnoi29.

sorry, I'm not much familiar with PHP so still didn't get it? 😔

**Comment by stnguyen90** [comment]
@MahendraBishnoi29, sounds like you'll need to find some resources on PHP. If this is too difficult, let me know and I'll unassign you from this issue.

**Comment by MahendraBishnoi29** [comment]
@stnguyen90 ok

**Comment by stnguyen90** [comment]
@MahendraBishnoi29, any progress on this or should I unassign you?

**Comment by MahendraBishnoi29** [comment]
> @MahendraBishnoi29, any progress on this or should I unassign you?

yes go ahead.

**Comment by Sooraj-s-98** [comment]
@stnguyen90 can you assign it to me ?

**Comment by 2002Bishwajeet** [comment]
@Sooraj-s-98  Since this is an Hacktoberfest labeled issue, please ask for reassignment when the hacktoberfest starts officially😄

**Comment by SaurabhNandy** [comment]
Hey @Rinma @stnguyen90, I would like to work on this if its not yet done!

**Comment by Sooraj-s-98** [comment]
@stnguyen90 can you assign me ? Please check PR

**Comment by stnguyen90** [comment]
@SaurabhNandy, thanks for your interest! 🙏 Happy hacking!

@Sooraj-s-98, we're assigning people on a first come first serve basis after hacktoberfest starts. If @SaurabhNandy isn't able to complete the issue, we're reassign accordingly. I'm the meantime, you can look for another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Sooraj-s-98** [comment]
@stnguyen90 can you check my PR ?
