### ISSUE TITLE
ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Exception: Failed to connect to database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again in /usr/src/code/app/http.php:75

### ISSUE THREAD

**Issue by sabitdos** [appwrite/appwrite#3676]
When trying to start docker container, showing message below:
ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Exception: Failed to connect to database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again in /usr/src/code/app/http.php:75
Ubuntu 22.04 LTS, Docker Engine
v20.10.17
Not first time this problems exists.
Hyper-V, VM with Ubuntu image - was same problem. in Jelastic droplet also.

**Comment by sabitdos** [comment]
Solved problem by my self, it was in permissions of folders, because i used Docker Desktop on Windows 10, 1st was problem with WSL 2-nd version, and after that, the installation of Appwrite was made by Windows Powershell begin to be able, and after script command: docker run -it --rm ,
    --volume /var/run/docker.sock:/var/run/docker.sock ,
    --volume ${pwd}/appwrite:/usr/src/code/appwrite:rw ,
    --entrypoint="install" ,
    appwrite/appwrite:0.15.3 
    it's start running, but everytime don't giving docker-compose.yml file to save at folder C:/Windows/system32/Appwrite which i was created by myself before, it's need to be solved thru permissions to all user to have delete, write, copy, create permissions and only after that i restarted installation and its now start working
P/S: Peace in peace, money for Qazaq's
![image](https://user-images.githubusercontent.com/27610965/184496762-2c0c97a0-0c61-4801-bd68-224a2a695c97.png)
![image](https://user-images.githubusercontent.com/27610965/184496790-6b337ff7-16d7-49c2-b7e5-446046389058.png)

**Comment by stnguyen90** [comment]
I'm glad you got things working! 🎉 Anything else needed for this or can the issue be closed?

**Comment by sabitdos** [comment]
> 

Yes
