### ISSUE TITLE
🐛 Bug Report: unable to connect appwrite server to cloudflare dns

### ISSUE THREAD

**Issue by bliyscom** [appwrite/appwrite#3677]
### 👟 Reproduction steps

I have followed the official docs.
- i created a cloudflare cname and it can be pinged.
- installed appwrite and set my cloudflare domain
- I have visited the appwrite console settings and tried to link the domain but it keeps failing.
- not sure how to proceed.

### 👍 Expected behavior

it should connect just fine

### 👎 Actual Behavior

it reports with "Failed to verify domain"

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

centos 7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
> I have visited the appwrite console settings and tried to link the domain but it keeps failing.

What do you mean by this? Would you try to take a look at [this](https://medium.com/geekculture/appwrite-frequently-asked-questions-374ce81513fe#0e85)?

**Comment by stnguyen90** [comment]
Also, you could be facing a problem due to Cloudflare's proxy or the SSL/TLS encryption mode. For the encryption mode, try Full instead of Full (strict).

**Comment by bliyscom** [comment]
> > I have visited the appwrite console settings and tried to link the domain but it keeps failing.
> 
> What do you mean by this? Would you try to take a look at [this](https://medium.com/geekculture/appwrite-frequently-asked-questions-374ce81513fe#0e85)?

Thanks for your contribution Stephen.  What I mean is that i am unable to access the appwrite instance from the subdomain. Only via IP address. I have looked at your FAQs, great job but still unable to solve my issue. I will keep trying. Thanks

**Comment by stnguyen90** [comment]
@bliyscom, I'm pretty sure this is a problem on the Cloudflare side. Feel free to reach out on [Discord](https://appwrite.io/discord) for additional assistance. It would be much easier to troubleshoot there.

**Comment by fbartels** [comment]
Yes, I agree with Stevens conclusion. If the connection works with the IP, but gets confused over the domain name then something must be wrong with the DNS setup. Without knowing the actual domain name this is hard to troubleshoot.

**Comment by stnguyen90** [comment]
@bliyscom, are you still having a problem, or can this be closed?

**Comment by bliyscom** [comment]
Still working on it but will close the issue for now.

**Comment by bliyscom** [comment]
Issue resolved and appwrite instance now accessible through URL.
However, I have installed SSL with certbot as per the instructions, rebooted appwrite and updated the config in docker-compose.yml yet, I still get a certificate warning in browser.
Now is that normal or is there something I can do to eliminate certificate warning? Thank you

**Comment by stnguyen90** [comment]
@bliyscom, no it is not normal. How many domains do you need for your Appwrite instance? If it's only 1, you don't need to add a custom domain in the Appwrite Console. Please go through [these](https://appwrite.io/docs/certificates) docs to try and resolve your problem. Be sure to run `docker compose up -d` to apply changes to your .env file. Feel free to share the appwrite-worker-certificates logs for help troubleshooting.

Feel free to reach out on [Discord](https://appwrite.io/discord) for help as it may be easier to troubleshoot on there.

**Comment by bliyscom** [comment]
Hi
I have read the docs once more, not sure if its because i am not using the default ports 80/443 on my main OS however, its mapped to 80/443 on the docker proxy side.

this is the message from the logs. I tried to cd into the logs for letencrypt but the directory seems to be absent.
[root@s107541 appwrite]# docker compose logs appwrite-worker-certificates
appwrite-worker-certificates  | Appwrite certificates worker v1 has started
appwrite-worker-certificates  | [notice] Starting worker 4831408359d7:7:v1-certificates
appwrite-worker-certificates  | [notice] Starting work on (Job{v1-certificates} | ID: daff5895f71e147303216c3ad4b0c8ec | CertificatesV1 | [{"project":null,"domain":{"domain":"appwrite.landcoins.org"},"skipRenewCheck":true}])
appwrite-worker-certificates  | Cannot renew domain (appwrite.landcoins.org) on attempt no. 2 certificate: Failed to issue a certificate with message: Saving debug log to /var/log/letsencrypt/letsencrypt.log
appwrite-worker-certificates  | Some challenges have failed.
appwrite-worker-certificates  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
appwrite-worker-certificates  |
appwrite-worker-certificates  | [notice] (Job{v1-certificates} | ID: daff5895f71e147303216c3ad4b0c8ec | CertificatesV1 | [{"project":null,"domain":{"domain":"appwrite.landcoins.org"},"skipRenewCheck":true}]) has finished
[root@s107541 appwrite]# vi /var/log/letsencrypt/letsencrypt.log
[root@s107541 appwrite]# cd /var/log/letsencrypt/
-bash: cd: /var/log/letsencrypt/: No such file or directory
[root@s107541 appwrite]#

**Comment by stnguyen90** [comment]
@bliyscom, 

> I have read the docs once more, not sure if its because i am not using the default ports 80/443 on my main OS however, its mapped to 80/443 on the docker proxy side.

Yes, this could be the problem. Is your reverse proxy automatically redirecting HTTP traffic to HTTPS? What are you using for your reverse proxy and how is it configured?

> I tried to cd into the logs for letencrypt but the directory seems to be absent.

you need to check that folder inside the docker container, not on your host machine.

**Comment by bliyscom** [comment]
I haven't setup any reverse proxy, if there's any, it probably came from openlightspeed default configs. I will look into that and if I am unable to set it up, I will try installing lets encrypt manually. Thanks

**Comment by bliyscom** [comment]
I have been able to get it to work with cloudflare even in proxy mode. I had to change the appwrite installation port to one supported by cloudflare and that did the trick. Thanks for your helpful contributions.
