### ISSUE TITLE
Enable Force HTTPS Option in Appwrite

### ISSUE THREAD

**Issue by Vaytrex** [appwrite/appwrite#368]
I found that there's no any option I am allowed to force HTTPS in Appwrite.
I think this is somewhat a must feature. Maybe someone can make this?
Thanks

**Comment by eldadfux** [comment]
This is something we used to have but was removed mistakingly instead of being optional. I'll add an env var to enable the server to add a 'Strict-Transport-Security' header that will force the HTTPS connection.

**Comment by eldadfux** [comment]
Fixed, will be released in next version.

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.7:
![image](https://user-images.githubusercontent.com/1297371/107742123-23f70a00-6d17-11eb-9852-5d35eddf5a63.png)
https://appwrite.io/docs/environment-variables

**Comment by generalxhd** [comment]
currently it's only available for the default ports(80,443). I think, it would be nice if that also works when we don't use the default ports.
