### ISSUE TITLE
🚀 Feature: arduino

### ISSUE THREAD

**Issue by soldat1989** [appwrite/appwrite#3695]
### 🔖 Feature description

Greetings, please tell me how you can connect a microcontroller to appwrite, for example esp8266, is it possible to update data in the database?

### 🎤 Pitch

!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by gepd** [comment]
I think you shoud make a HTTP call like this:



```php
int    HTTP_PORT   = 80;
String HTTP_METHOD = "PATCH";
char   HOST_NAME[] = "yourappwriteserver.com";
String PATH_NAME   = "/v1/databases/{databaseId}/collections/{collectionId}/documents/{documentId}";
String PROJECT_ID = "yourprojectid";
String APPWRITE_KEY = "yourkey";
String queryString = String("?temperature=") + String(temp) + String("&humidity=") + String(humi); // data to update


if(client.connect(HOST_NAME, HTTP_PORT)) {
  Serial.println("Connected to server");
} else {
  Serial.println("connection failed");
}

// Header
client.println(HTTP_METHOD + " " + PATH_NAME + " HTTP/1.1");
client.println("Host: " + String(HOST_NAME));
client.println("X-Appwrite-Project: " + String(PROJECT_ID));
client.println("X-Appwrite-key: " + String(APPWRITE_KEY));
client.println("Content-type: application/json";
client.println("Connection: close");
client.println(); // end HTTP request header

// Body
client.println(queryString);

while(client.available()) {
  // read an incoming byte from the server and print them to serial monitor:
  char c = client.read();
  Serial.print(c);
}

if(!client.connected()) {
  // if the server's disconnected, stop the client:
  Serial.println("disconnected");
  client.stop();
}
```

references:

https://medium.com/appwrite-io/how-to-connect-with-the-appwrite-backend-server-directly-using-only-the-appwrite-http-api-1e720b567395

https://arduinogetstarted.com/tutorials/arduino-http-request

**Comment by soldat1989** [comment]
> I think you shoud make a HTTP call like this:
> 
> ```
> int    HTTP_PORT   = 80;
> String HTTP_METHOD = "PATCH";
> char   HOST_NAME[] = "yourappwriteserver.com";
> String PATH_NAME   = "/v1/databases/{databaseId}/collections/{collectionId}/documents/{documentId}";
> String PROJECT_ID = "yourprojectid";
> String APPWRITE_KEY = "yourkey";
> String queryString = String("?temperature=") + String(temp) + String("&humidity=") + String(humi); // data to update
> 
> 
> if(client.connect(HOST_NAME, HTTP_PORT)) {
>   Serial.println("Connected to server");
> } else {
>   Serial.println("connection failed");
> }
> 
> // Header
> client.println(HTTP_METHOD + " " + PATH_NAME + " HTTP/1.1");
> client.println("Host: " + String(HOST_NAME));
> client.println("X-Appwrite-Project: " + String(PROJECT_ID));
> client.println("X-Appwrite-key: " + String(APPWRITE_KEY));
> client.println("Content-type: application/json";
> client.println("Connection: close");
> client.println(); // end HTTP request header
> 
> // Body
> client.println(queryString);
> 
> while(client.available()) {
>   // read an incoming byte from the server and print them to serial monitor:
>   char c = client.read();
>   Serial.print(c);
> }
> 
> if(!client.connected()) {
>   // if the server's disconnected, stop the client:
>   Serial.println("disconnected");
>   client.stop();
> }
> ```
> 
> references:
> 
> https://medium.com/appwrite-io/how-to-connect-with-the-appwrite-backend-server-directly-using-only-the-appwrite-http-api-1e720b567395
> 
> https://arduinogetstarted.com/tutorials/arduino-http-request

Thank you very much for your help, I apologize for my English
