### ISSUE TITLE
Could not open input file: /install/bin/installer

### ISSUE THREAD

**Issue by AnatoleLucet** [appwrite/appwrite#370]
Appwrite seems great, but unfortunately I'm unable to install it on my local machine.

When running (from the doc):
```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/install/appwrite:rw \
    -e version=0.6.2 \
    appwrite/install
```

I get this error: `Could not open input file: /install/bin/installer` (there's literally nothing else, Docker only returns this message).

I'm on Ubuntu 20.04:
```
$ lsb_release -a
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

And I'm on Docker v18.09.9:
```
$ docker -v
Docker version 18.09.9, build 1752eb3
```

Maybe I'm missing something?
Don't hesitate if you need more info.

**Comment by punitdiwan** [comment]
@AnatoleLucet Its Docker related issue. I have faced this issue before. How did you installed Docker at your VPS? I suggest to uninstall Docker and install docker-ce. Please refer this DigitalOcean link for installation [How To Install and Use Docker on Ubuntu 20.04](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04)

Then install AppWrite, hopefully it will fix the issue.

**Comment by AnatoleLucet** [comment]
Yes that worked. I've removed Docker with the help of [this Askubuntu post](https://askubuntu.com/questions/935569/how-to-completely-uninstall-docker) and re-installed it via the DigitalOcean article you sent. Thank you!
