### ISSUE TITLE
📚 Documentation: Make documentation clearer about Functions

### ISSUE THREAD

**Issue by binhodev** [appwrite/appwrite#3709]
### 💭 Description

Hello everyone, I was looking at the documentation about Cloud Functions using Dart.
I think there is a lack of information.
When creating a function in Dart using Appwrite its scope says the following:
```
/*
  'req' variable has:
    'headers' - object with request headers
    'payload' - object with request body data
    'env' - object with environment variables

  'res' variable has:
    'send(text, status)' - function to return text response. Status code defaults to 200
    'json(obj, status)' - function to return JSON response. Status code defaults to 200
  
  If an error is thrown, a response with code 500 will be returned.
*/
```

> 'payload' - object with request body data

It clearly says that this object receives a body, it means it is a JSON, but reading the documentation of creating an execution of a function, the data property is a string.

![Captura de Tela 2022-08-22 às 12 50 33](https://user-images.githubusercontent.com/58571495/185964166-75724dd1-e1a6-43f0-8ed0-cb39f11bc180.png)
If I pass a String, it returns the error:

> Unable to properly load request body

Can't send a map object in data property.
Please fix this issue, or this method to receive a json. To send data payload I need convert to JSON strings and this works. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey there 👋 Thanks for pointing this out 🙏

The payload you send from `createExecution, and receive in the request payload property is always supposed to be a string indeed. We will make sure to update our starter codes to describe the payload property as a string.
