### ISSUE TITLE
Default collection permission to user that inserted the collection

### ISSUE THREAD

**Issue by int-20h** [appwrite/appwrite#371]
Currently we can set permissions to the collection and also to the document. However, if we want to keep documents to the respective user that created them, the application would have to do that in code. Rather than relying on the application to set the read/write to the user creating the document, AppWrite could have a configuration flag/toggle button that sets the Read / Write to the user that inserted the document.

The UI might look as follow.  I couldn't think of a better name for the toggle button

![image](https://user-images.githubusercontent.com/66054280/83467924-28e98700-a430-11ea-980e-5f4145004448.png)

The impact is outlined as follow:
- UI to display the toggle button
- DB attribute to hold the flag
- Collection API for create and update to set the flag
- Document API onInsert to add the user as part of the read and write permission if the flag is set

**Comment by eldadfux** [comment]
This issue resembles to #246, but I think your idea might be a good solution or at least a good direction to follow.

I'm not sure it's verbose enough for a developer to understand by himself, but if we could think of some terms that will be more obvious it might work well.

@christyjacob4 what do you think?

**Comment by int-20h** [comment]
Yes, #246 outlines the same need/want as this issue.  I'm providing a possible solution for this ask.  The name should either be more descriptive or add more info at the "i" icon hover.

**Comment by eldadfux** [comment]
We are going to introduce new permission models as part of #1281 - closing this issue for now
