### ISSUE TITLE
🐛 Bug Report: Flutter use function error

### ISSUE THREAD

**Issue by xypmhxy** [appwrite/appwrite#3715]
### 👟 Reproduction steps

When I use flutter functions I get general_unknown_origin, Invalid Origin. Register your new client as a new Android platform on your project console dashboard (403) I don't know why. I have set role:all for all functions.

### 👍 Expected behavior

it's should work

### 👎 Actual Behavior

no work

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@xypmhxy thanks for raising this issue! 🙏 Perhaps this will help you: https://appwrite.io/docs/getting-started-for-flutter#addYourPlatform

**Comment by xypmhxy** [comment]
> @xypmhxy感谢您提出这个问题！🙏也许这会对您有所帮助：[https ://appwrite.io/docs/getting-started-for-flutter#addYourPlatform](https://appwrite.io/docs/getting-started-for-flutter#addYourPlatform)

Thank you very much but this doesn't solve my problem, I have set the corresponding code in AndroidManifest of Android but it doesn't work

**Comment by xypmhxy** [comment]
> 

thanks i see it Thank you very much

**Comment by xypmhxy** [comment]
> @xypmhxy Sorry, I wasn't referring to the Android Manifest. You need to [add a platform](https://appwrite.io/docs/getting-started-for-flutter#addYourPlatform) in your Appwrite Console that matches the package name of your app.

But now new error Unhandled Exception: AppwriteException: general_unauthorized_scope, User (role: guest) missing scope (execution.write) (401)

**Comment by stnguyen90** [comment]
@xypmhxy, to perform any write operations like creating a document, uploading a file, or executing a function, a session is required. If you don't want to require the user to log in, you can create an anonymous session before executing the function.

**Comment by xypmhxy** [comment]
> @xypmhxy, to perform any write operations like creating a document, uploading a file, or executing a function, a session is required. If you don't want to require the user to log in, you can create an anonymous session before executing the function.

Thank you very much. The problems have been solved. Appwrite has many powerful functions. Many places are unknown. It is a very good project. Thank you again
