### ISSUE TITLE
📚 Documentation: function createExecution

### ISSUE THREAD

**Issue by xypmhxy** [appwrite/appwrite#3716]
### 💭 Description

I use the server version of dart, I need to execute createExecution and then get the id and execute getExecution to get the parameters returned by the function? I don't think it should be, is there something wrong with me?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@xypmhxy thanks for raising this issue! 🙏 Perhaps this will help you: https://appwrite.io/docs/getting-started-for-flutter#addYourPlatform

**Comment by xypmhxy** [comment]
> 

thanks i solved this problem，just set xasync false it work，But I don't know if there is a problem

**Comment by stnguyen90** [comment]
@xypmhxy, oops. My response was actually meant to be for another issue. Yes, if you want to wait for the function to complete to get the result, you need to set the async parameter to false.
