### ISSUE TITLE
Console/ ULR path doesn't display list of projects

### ISSUE THREAD

**Issue by frasza** [appwrite/appwrite#372]
Hey,

While http://localhost/console displays list of projects, http://localhost/console/ doesn't.

**localhost/console/ result (while having active project):**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22049682/83537587-0a998f00-a4f5-11ea-88e4-e5daffc20c39.png">

**Comment by eldadfux** [comment]
Thanks for reporting this, seems like a routing issue on the client side. We'll push thin to version 0.7.0 queue.

**Comment by eldadfux** [comment]
Issue fixed on master, waiting for next version to be released.

**Comment by eldadfux** [comment]
This fix is now available on the new Appwrite 0.7 🚀
