### ISSUE TITLE
🐛 Bug Report: I can't login with my admin account

### ISSUE THREAD

**Issue by truongphamit** [appwrite/appwrite#3731]
### 👟 Reproduction steps

I recently upgraded from 14.2 to 15.3, latest version and i can't login

[Error] Timestamp: 2022-08-29T15:17:10+00:00
[Error] Method: GET
[Error] URL: /v1/account
[Error] Type: Appwrite\Extend\Exception
[Error] Message: User (role: guest) missing scope (account)
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 319

{
    "message": "User (role: guest) missing scope (account)",
    "code": 401,
    "type": "general_unauthorized_scope",
    "version": "0.15.3"
}

### 👍 Expected behavior

I should be able to login

### 👎 Actual Behavior

When i hit login, the page just refreshes but i am still not logged in

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@truongphamit, thanks for raising this issue! 🙏 Would you please check the network requests to confirm the login is successful, but the following GET /account fails? If so, your problem might be related to [this](https://github.com/appwrite/appwrite/issues/3276) issue and a workaround is to [delete the user's sessions](https://github.com/appwrite/appwrite/issues/3276#issuecomment-1140130800).

**Comment by truongphamit** [comment]
@stnguyen90 I clear all user'sessions

![Screen Shot 2022-08-30 at 17 01 00](https://user-images.githubusercontent.com/9319905/187408892-24fd69e7-8a8a-4cec-91d1-426bc4169e33.png)

![Screen Shot 2022-08-30 at 17 01 33](https://user-images.githubusercontent.com/9319905/187408991-521516c8-a1b6-432a-9b86-fe5ef8506478.png)

**Comment by truongphamit** [comment]
@stnguyen90, I have the same error when I try logging in with a private/incognito window.

**Comment by stnguyen90** [comment]
@truongphamit, would you please clarify what you did when you cleared user sessions?

**Comment by truongphamit** [comment]
@stnguyen90, I remove all of the rows from the sessions table.

**Comment by stnguyen90** [comment]
@truongphamit, which sessions table?

**Comment by truongphamit** [comment]
@stnguyen90, I remove all the rows from _console_sessions tables

**Comment by stnguyen90** [comment]
@truongphamit, would you please try accessing your console via HTTPS and also share the response status and headers from the /account/sessions/email API call?

**Comment by truongphamit** [comment]
@stnguyen90, This is response status and headers.
![Screen Shot 2022-09-07 at 07 17 21](https://user-images.githubusercontent.com/9319905/188761784-c1fb4c64-533e-4a62-bb95-5d9fc85bf129.png)

**Comment by stnguyen90** [comment]
@truongphamit, after upgrading, did you run the migrate command?

**Comment by stnguyen90** [comment]
@truongphamit, sounds like you missed running the migrate after upgrading to 0.14.x. if you can, I'd suggest restoring to before you upgraded to 0.14.x and then:

1. upgrade to 0.14.x
2. Run the migrate command
3. Upgrade to 0.15.x
4. Run the migrate command

If you don't have a backup, you can try downgrading to 0.14.x and then continuing from step 2.

**Comment by truongphamit** [comment]
@stnguyen90,
I tried downgrading to 0.14.x and running the migrate command but got errors.

Failed to update document: Invalid document structure: Unknown attribute: "_createdAt"

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._626aa94ac3b438473675__metadata' doesn't exist

**Comment by stnguyen90** [comment]
@truongphamit, it might be difficult to try and fix things now. Would it be okay to clear data and start with a fresh 0.15.3 instance?

**Comment by truongphamit** [comment]
@stnguyen90, Is there a way to keep document data and collection ID? I upgraded on production. :(

**Comment by stnguyen90** [comment]
@truongphamit, but you don't have a backup from before you upgraded?

**Comment by truongphamit** [comment]
@stnguyen90,Thanks for your support. I reinstalled the appwrite and restored the data, and everything worked fine.

great project!
