### ISSUE TITLE
Add Password Field in accept invitation Page

### ISSUE THREAD

**Issue by punitdiwan** [appwrite/appwrite#375]
We need to add Password and Confirm Password fields in the Accept Invitation Page. 
![AcceptLink](https://user-images.githubusercontent.com/49054503/83667722-b093da80-a583-11ea-82f9-ff1782d21bac.png)

When I added new project member, after accepting the invitation link,, sent on mail, I directly went into the Console. From there if I logs out, I don’t know my password for the next login.  Moreover while I am logged in and try to change password from **Your Account** area, it asks for current password which is mandatory field. So I cannot change the password this way.
![ChangePassword](https://user-images.githubusercontent.com/49054503/83667766-c6a19b00-a583-11ea-9321-285265dbf752.png)

The only solution left is to use forget password feature. That is hard for new starters. So please add Password and Confirm Password fields in the Accept Invitation Page.

Regards,
Punit

**Comment by eldadfux** [comment]
Two situation where this might create some conflicts:
1. what should we do if a user already has an account and he is logged in?
2. what should we do if a user already has an account and he is not logged in?

Should we limit invite confirmation to only logged in users and require login/registration before showing invite confirmation?

**Comment by eldadfux** [comment]
After discussing more on Discord this flow should work better, allow the user to be fully aware to his account and password, and no major API change is required.

1. User gets an invite email -> User click the invite URL -> Invite page opens -> Check if user is logged
1.1. Yes -> Show confirmation form -> User click 'accept' button -> User joins the team
1.2 No -> Redirect user to login / registration page -> User create account or login -> Redirect back to the original invite url -> User click 'accept' -> User joins the team

**Comment by Haimantika** [comment]
Hi @punitdiwan, thank you for bringing this issue up. We have been improving our product and trying to implement every request. I hope we could do the same with you. Closing this issue for now, if you feel there is a need to re-open this, feel free to drop a comment. :)
