### ISSUE TITLE
🐛 Bug Report: 100-150% cpu usage caused by appwrite-usage container for 30-40 seconds after every 30 seconds.

### ISSUE THREAD

**Issue by garvitomer** [appwrite/appwrite#3750]
### 👟 Reproduction steps

created a hetzner server with 4gb RAM, 2CPU, 40 GB 
Install appwrite 0.15.3.
Added flutter andoird app to appwrite
Added google OAuth
Added dart sdk to .env file
Added appwrite-webhook-proxy container (Mentioned in article of stripe payment)
Run python scripts on my mac to create12 collections, 8-10 cloud functions (using CLI) , 1-2 indexes on average in every collection
 Added CRON schedule in 1 cloud function manually in the server not from CLI in order to avoid muilple instances as there is bug
Every collection is empty and no function is running just deployed. And no user and no data

### 👍 Expected behavior

Should run normally with ~5-10% cpu usage. (Normal)

### 👎 Actual Behavior

Now after creating all this the issue starts and my cloud server will keep on running at cycle with 150% cpu usage for 45 seconds   at every minute. 
After stopping appwrite-usage container using 'docker stop appwrite-usage' it runs normally

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

no

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rvndsngwn** [comment]
After update Appwrite `v:0.15.2` to `v:0.15.3` CPU usage has gone from `23%` to `93%`

`CPU usage graphs`
![Screenshot 2022-09-07 at 2 21 46 PM](https://user-images.githubusercontent.com/59143934/188918667-c24055bc-2bcb-41ff-9b7f-53b9d46c22cc.png)

`docker stats` Output 
![Screenshot 2022-09-07 at 2 33 00 PM](https://user-images.githubusercontent.com/59143934/188918849-31ea3a4e-60d9-484a-946f-e9c9bef49581.png)

`docker logs -f appwrite-usage` Output
https://cdn.discordapp.com/attachments/564175629663076372/1016999009207988244/Screen_Recording_2022-09-07_at_2.37.16_PM.mov

`Discord chat link`
https://discord.com/channels/564160730845151244/564175629663076372/1016996465354223646

**Comment by lokhmakov** [comment]
1.0.1 the same

**Comment by DankMemeGuy** [comment]
Was this ever fixed?

**Comment by garvitomer** [comment]
I don't know about the current status of this error, but I ran this command to stop appwrite usage and erroe was solved.

```
docker compose stop appwrite-usage
```

**Comment by greendesertsnow** [comment]
why is this issue still open? can we get an update on it please?

**Comment by EVDOG4LIFE** [comment]
Resolving due to age, if this continues to happen on hardware meeting the minimum requirements on a later version of Appwrite, please open a new issue with the details so we can take a further look.
