### ISSUE TITLE
[BUG] Console graph cuts off on mobile view

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#376]
The monthly amount of requests cuts off on a mobile viewport (>1200px width).

![Unbenannt](https://user-images.githubusercontent.com/1759475/83872057-8a13a200-a731-11ea-98a1-7dae384fe8e8.PNG)

**Comment by eldadfux** [comment]
Should be better now:
![image](https://user-images.githubusercontent.com/1297371/83965858-523a6500-a8bf-11ea-8e88-ad2d7c9690b7.png)

**Comment by eldadfux** [comment]
Fix is now available on the new Appwrite 0.7 🚀
