### ISSUE TITLE
🚀 Feature: Bash runtime

### ISSUE THREAD

**Issue by binaryfire** [appwrite/appwrite#3760]
### 🔖 Feature description

Hi guys

Would it be possible to add support for a bash runtime / functions ?

### 🎤 Pitch

I’m a devops engineer. I’d love to use Appwrite to create functions to run my bash scripts. Being able to wrap them in an API and pass variables to them would open up a lot of possibilities.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Theoretically this should be possible. I'm marking this as a good first issue, if anyone would like to pick it up, the team would love to assits.

More information on how to contribute new runtimes is available here: 
https://github.com/open-runtimes/open-runtimes/blob/main/docs/add-runtime.md

**Comment by MahendraBishnoi29** [comment]
hey @eldadfux this is my first contribution to appwrite can you please guide me how to solve this issue? 🚀

**Comment by rakshitgondwal** [comment]
Hey @eldadfux and @binaryfire !!! I would like to work on this. Can you please brief me a little bit more about this issue?

**Comment by binaryfire** [comment]
Hi @rakshitgondwal. I’ve realised I’d need to use custom images to achieve what I need (because most scripts use cli tools that need to be installed).

So I’d suggest leaving this until custom runtime images are a thing

**Comment by stnguyen90** [comment]
@binaryfire, each one of our runtimes is a custom image. So, what's the limitation?

**Comment by binaryfire** [comment]
@stnguyen90 Has something changed with this issue? It’s still marked as open: https://github.com/appwrite/appwrite/issues/1037

I was pointed to that when I opened this: https://github.com/appwrite/appwrite/issues/3796

**Comment by stnguyen90** [comment]
@binaryfire, no, nothing has changed with #1037. You cannot run arbitrary docker images in Appwrite, but we can add additional runtimes. For example, a contributor added a [perl runtime](https://github.com/open-runtimes/open-runtimes/pull/95). In a similar fashion, we can add a bash runtime.

**Comment by binaryfire** [comment]
@stnguyen90 That’s what I meant by my earlier reply. A bash runtime won’t be much use for me if I can’t install the packages/tools I’m calling in my scripts.

I imagine it’d be the same for most. It’s rarely used as a standalone programming language.

**Comment by stnguyen90** [comment]
@binaryfire ahhh I get it now. Sorry! That makes sense...however, you might be able to install packages as part of the function execution. it's going to be pretty slow since it has to do all the downloads during execution, though...

**Comment by binaryfire** [comment]
@stnguyen90 No worries! Yeah that’d be too slow unfortunately. My current setup is a custom docker image + Java REST API, so there’s no additional latency.

Appwrite’s warm start latency would be fine but anything over that wouldn’t work for me. 

I’m closing this in favour of https://github.com/appwrite/appwrite/issues/4013 since it seems to be the same thing.
