### ISSUE TITLE
Appwrite installation Failed on Windows 10 using Docker Desktop

### ISSUE THREAD

**Issue by cshubhamdhanetia** [appwrite/appwrite#377]
There is an issue installing traefik service.
![image](https://user-images.githubusercontent.com/14253195/83881322-11770a80-a75e-11ea-9172-aeabef6eab60.png)

![image](https://user-images.githubusercontent.com/14253195/83881458-51d68880-a75e-11ea-9f06-a7d15fcfc19f.png)

**Comment by punitdiwan** [comment]
I am currently using Docker Desktop on Windows. It works fine on mine. Here is my Docker Version:
**Docker version 19.03.8, build afacb8b**

What is yours? Check your Docker Version with:
**docker -v**

**Comment by cshubhamdhanetia** [comment]
I too have an updated docker version.
Docker version 19.03.8, build afacb8b

**Comment by cshubhamdhanetia** [comment]
I am getting now service mapping errors after using your docker file.

I have installed docker like an year ago. I don't remember it exactly. Would you like to come to my PC using TeamViewer or any desk?

You can contact me on shubham.dhanetia@gmail.com as well

**Comment by punitdiwan** [comment]
@cshubhamdhanetia Since you have installed docker a year ago, I suggest that you uninstall docker and download fresh docker  desktop setup and install, You can download docker desktop from this link: https://download.docker.com/win/stable/Docker%20Desktop%20Installer.exe. 

Then run the docker-compse.yml file. Hope it will fix the issue.

**Comment by cshubhamdhanetia** [comment]
@punitdiwan Hi, I have reinstalled again the stable version. And it works now !! But, this time error is different.

![image](https://user-images.githubusercontent.com/14253195/83915516-05f10700-a791-11ea-9e35-2f64e91dd280.png)

**Comment by cshubhamdhanetia** [comment]
@punitdiwan  It works !! I have reinstalled the stable version and it works perfectly. Thanks! :-D 
Finally, I am able to the app write console !!

**Comment by omar6260** [comment]
![APPWRIT](https://user-images.githubusercontent.com/82382673/164566131-1e609b9d-175b-474b-a640-61d0efa7fc4d.PNG)
Hi, I was installing Appwrite but here are the errors that appear

**Comment by omar6260** [comment]
if anyone has a solution

**Comment by owooza** [comment]
> if anyone has a solution
Add nameservers & restart Docker

https://stackoverflow.com/questions/47580528/error-response-from-daemon-get-https-registry-1-docker-io-v2-dial-tcp-look
