### ISSUE TITLE
🐛 Bug Report: Runtime Container Doesn't Exist but Executor Thinks it Does

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#3776]
### 👟 Reproduction steps

A few users have reported this problem, but I'm not sure why it happens. One can reproduce this by removing the container via the Docker CLI and then try to execute the function.

### 👍 Expected behavior

Container state and Executor are in sync

### 👎 Actual Behavior

It seems it's possible for the Appwrite Executor's table of active runtimes and the actual running runtime containers to go out of sync. When the executor thinks the container is still active, but it actually isn't, it won't spin up the container and executing the function will result in:

> Message: An internal curl error has occurred within the executor! Error Msg: Could not resolve host: [container name]

From the logs, it seems the executor tries to remove the inactive runtime container, but fails:

```
appwrite-executor  | Executing Runtime: 62e95cd16f29990cd1ce-630f3976572d929432b8
appwrite-executor  | Function executed in 0.32679891586304 seconds, status: completed
appwrite-executor  | Running maintenance task ...
appwrite-executor  | Inactive Runtime deletion failed: Docker Error: 
appwrite-executor  | Executing Runtime: 62e95cd16f29990cd1ce-630f3976572d929432b8
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: An internal curl error has occurred within the executor! Error Msg: Could not resolve host: 62e95cd16f29990cd1ce-630f3976572d929432b8
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 536
```

Although there was an error, it seems the container does successfully get removed. So, subsequent attempts to remove the runtime container result in:

```
appwrite-executor  | Inactive Runtime deletion failed: Docker Error: Error: No such container: 62e95cd16f29990cd1ce-630f3976572d929432b8
```

Restarting the appwrite-executor or re-deploying the function usually gets things working again.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by andoidam** [comment]
Getting same error on [appwrite](appwrite:0.15.3) 

An internal curl error has occurred within the executor! Error Msg: Could not resolve host: netflox-63172032e71340266614

**Comment by rafagazani** [comment]
Versão [0.14.205](v:0.14.2.305) também apresenta esse erro:
An internal curl error has occurred within the executor! Error Msg: Could not resolve host: ....

**Comment by rafagazani** [comment]
I managed to reproduce. after changing one of the variables the function fails and it is necessary to deploy.
The function was triggered by collections.name-collection.documents.*.create
@stnguyen90

**Comment by stnguyen90** [comment]
@rafagazani, are you saying the container crashes after changing the variable and the function gets triggered? And you see the "Error Msg: Could not resolve host:" error?

**Comment by rafagazani** [comment]
Yes

**Comment by rafagazani** [comment]
> @rafagazani, are you saying the container crashes after changing the variable and the function gets triggered? And you see the "Error Msg: Could not resolve host:" error?

yes

**Comment by merabtenei** [comment]
This just happened with us on the latest version 1.1.2, the function executions were running just fine and at a moment function executions failed for an unknown reason the reported error was : ```An internal curl error has occurred within the executor! Error Msg: Could not resolve host: xxxxx-6381fb92f3a7f1d6566c```
After restarting the server everything was running fine again.

Is there any news regarding this issue ?

**Comment by stnguyen90** [comment]
@rafagazani, are you only updating the variables or are you redeploying? if you're still experiencing this problem, please make sure to provide the executor logs.

**Comment by rafagazani** [comment]
I'm using version 1.1.2 and it hasn't happened yet, if it happens I'll add the logs

**Comment by rafagazani** [comment]
The problem happened again. The function had not been used for a few weeks, when it was activated it was in processing status. At that time the other cloud functions did not respond. I had to delete the function and deploy it again. All functions became responsive. I'm waiting for authorization to share the logs

**Comment by garvitomer** [comment]
Hi, Is there a way to temporary solve it? I have appwrite server (0.15.3) in production and now it is causing issue out of nowhere!

**Comment by garvitomer** [comment]
Sorry, I missed your reply.

`appwrite-executor  | Warming up Node.js 16.0 environment...
appwrite-executor  | Warming up PHP 8.0 environment...
appwrite-executor  | Warming up Ruby 3.0 environment...
appwrite-executor  | Warming up Python 3.9 environment...
appwrite-executor  | Warming up Dart 2.17 environment...
appwrite-executor  | Removing orphan runtimes...
appwrite-executor  | Successfully Warmed up Node.js 16.0!
appwrite-executor  | Successfully Warmed up Ruby 3.0!
appwrite-executor  | Successfully Warmed up Python 3.9!
appwrite-executor  | Orphan runtime deletion failed: Docker Error: 
appwrite-executor  | Successfully Warmed up PHP 8.0!
appwrite-executor  | Successfully Warmed up Dart 2.17!
appwrite-executor  | Successfully removed 630ffeafdee98bacd072-63db6e0e1a9eb90aab91
appwrite-executor  | Successfully removed 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Successfully removed 630ffeafdee98bacd072-63dc140decd3266c1206
appwrite-executor  | Successfully removed 630ffeafdee98bacd072-63dc13ed8f28af91c75e
appwrite-executor  | Successfully removed 630ffeafdee98bacd072-63db8a871922fd1595e8
appwrite-executor  | Successfully removed 630ffeafdee98bacd072-63db869aac2bd38461e5
appwrite-executor  | Successfully removed 630ffeafdee98bacd072-63db8353481046094bb8
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: Runtime not found. Please create the runtime.
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 463
appwrite-executor  | Building container : 630ffeafdee98bacd072-63dc13ed8f28af91c75e
appwrite-executor  | Build Stage completed in 1 seconds
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63dc13ed8f28af91c75e
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection refused
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 533
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63dc13ed8f28af91c75e
appwrite-executor  | Function executed in 0.25702691078186 seconds, status: completed
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: Runtime not found. Please create the runtime.
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 463
appwrite-executor  | Building container : 630ffeafdee98bacd072-63dc140decd3266c1206
appwrite-executor  | Build Stage completed in 1 seconds
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63dc140decd3266c1206
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection refused
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 533
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63dc140decd3266c1206
appwrite-executor  | Function executed in 0.22095680236816 seconds, status: completed
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: Runtime not found. Please create the runtime.
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 463
appwrite-executor  | Building container : 630ffeafdee98bacd072-63dc0f8d5996bf3a9c99
appwrite-executor  | Build Stage completed in 1 seconds
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63dc0f8d5996bf3a9c99
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection refused
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 533
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63dc0f8d5996bf3a9c99
appwrite-executor  | Function executed in 0.31474208831787 seconds, status: completed
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: Runtime not found. Please create the runtime.
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 463
appwrite-executor  | Building container : 630ffeafdee98bacd072-63dbd7dc39d0cc675ed4
appwrite-executor  | Build Stage completed in 1 seconds
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63dbd7dc39d0cc675ed4
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection refused
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 533
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63dbd7dc39d0cc675ed4
appwrite-executor  | Function executed in 0.94317698478699 seconds, status: completed
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: Runtime not found. Please create the runtime.
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 463
appwrite-executor  | Building container : 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63dbd7dc39d0cc675ed4
appwrite-executor  | Build Stage completed in 1 seconds
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection refused
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 533
appwrite-executor  | Function executed in 0.79822301864624 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.26215505599976 seconds, status: completed
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: Runtime not found. Please create the runtime.
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 463
appwrite-executor  | Building container : 630ffeafdee98bacd072-63db6e0e1a9eb90aab91
appwrite-executor  | Build Stage completed in 1 seconds
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db6e0e1a9eb90aab91
appwrite-executor  | Function executed in 0.49697709083557 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.27415299415588 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.29162502288818 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.16517496109009 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.26479816436768 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.17138600349426 seconds, status: completed
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: Runtime not found. Please create the runtime.
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 463
appwrite-executor  | Building container : 630ffeafdee98bacd072-63db89d4ab94edddd8f5
appwrite-executor  | Build Stage completed in 0 seconds
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db89d4ab94edddd8f5
appwrite-executor  | Function executed in 0.094188928604126 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db6e0e1a9eb90aab91
appwrite-executor  | Function executed in 0.22454285621643 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.1833930015564 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db89d4ab94edddd8f5
appwrite-executor  | Function executed in 0.050708055496216 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db6e0e1a9eb90aab91
appwrite-executor  | Function executed in 0.90158891677856 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.24620580673218 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.23972105979919 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.15076017379761 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.16833305358887 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db83a0c86f3dd60164
appwrite-executor  | Function executed in 0.26019406318665 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db89d4ab94edddd8f5
appwrite-executor  | Function executed in 0.073920965194702 seconds, status: completed
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: Runtime not found. Please create the runtime.
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 463
appwrite-executor  | Building container : 630ffeafdee98bacd072-63db8353481046094bb8
appwrite-executor  | Build Stage completed in 2 seconds
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db8353481046094bb8
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection refused
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 533
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db8353481046094bb8
appwrite-executor  | Function executed in 0.32430505752563 seconds, status: completed
appwrite-executor  | Executing Runtime: 630ffeafdee98bacd072-63db8353481046094bb8
appwrite-executor  | Function executed in 0.077126026153564 seconds, status: completed`

**Comment by stnguyen90** [comment]
@garvitomer, some of the error messages here may not actually be a problem because Appwrite will try to create a runtime if it doesn't find the runtime or it may retry executing if connection refused. Which one of these actually resulted from an error in the front end or Appwrite Console?

In addition, would you please provide additional context:

1. What runtime are you using?
2. How long does your execution generally take to complete?
3. How is the problematic function being executed?

**Comment by garvitomer** [comment]
'Message: An internal curl error has occurred within the executor! Error Msg: Connection refused'
Above line is causing the error.
Appwrite version - 0.15.3 (0.15.3.402 to be exact)
1. Python runtime 3.9  and also in dart runtime too
2. It hardly takes 0.1 seconds
3. Payload is send from user device (flutter sdk), One fucntion is schedule and another one is triggered when a docuemnt is added. So no pattern in this, as far as I have seen it.

**Comment by lucasbstn** [comment]
Same happens to me when the function is not used for some time.
Using Dart-2.17, few ms execution time, payload is sent via flutter sdk or document added/updated event.
Very annoying to have some features break all of a sudden but usually redeploying the function fixes it for a while.

**Comment by garvitomer** [comment]
Yeah, mine whole app in production is getting destroyed just by this stupid error. Is there any way I can solve it by my self?

One more thing which maybe helpful:
So i delete dan old fucniton (~150 days old) which was working fine and now when I deployed it again. Same issue start in that function too!!
It is very critical function for my app to work, now I am f*cked! 

Can someone please help me?

**Comment by garvitomer** [comment]
When the error occured for you guys are you making the function with same id as previously i.e. is your id same after your recreated the function?

**Comment by rafagazani** [comment]
> Quando o erro ocorreu para vocês, vocês estavam fazendo a função com o mesmo id anterior, ou seja, seu id é o mesmo depois de recriar a função?
> 
> Uma possível conclusão a que estou chegando é que: se você excluir uma função e criá-la novamente com o mesmo id, isso está causando esse erro de curl. Houve algum problema semelhante há muito tempo (6 a 12 meses atrás nas funções da nuvem), não me lembro exatamente, mas estava relacionado à função da nuvem que não foi excluída corretamente.

Yes. I always use the same id

**Comment by garvitomer** [comment]
Then this must be the issue. As yesterday I deleted the function which was working fine since last 6 months but suddenly same error starts again today. SO this is the only possible reason.Also, 2 fucntions which are ~6months old have no such error yet!

**Comment by rafagazani** [comment]
If the function is called on the client side, the only output I see is sending the id

**Comment by garvitomer** [comment]
I don't get it. Can you please explain more? 
Maybe that is due to async or sync and await issue?

**Comment by garvitomer** [comment]
It didn't worked. So I tried changing name to something else, and till now it is working without any error.
Maybe there is some check based on 'name' not 'id'. I checked the code of executor.php and this line seems not right (I am not sure just a guess, I don't understand php much)

Line: 734
/**
     * Run a maintenance worker every MAINTENANCE_INTERVAL seconds to remove inactive runtimes
     */
    Timer::tick(MAINTENANCE_INTERVAL * 1000, function () use ($orchestrationPool, $activeRuntimes) {
        Console::warning("Running maintenance task ...");
        foreach ($activeRuntimes as $runtime) {
            $inactiveThreshold = \time() - App::getEnv('_APP_FUNCTIONS_INACTIVE_THRESHOLD', 60);
            if ($runtime['updated'] < $inactiveThreshold) {
                go(function () use ($runtime, $orchestrationPool, $activeRuntimes) {
                    try {
                        $orchestration = $orchestrationPool->get();
                        $orchestration->remove($runtime['name'], true);
                        $activeRuntimes->del($runtime['name']);
                        Console::success("Successfully removed {$runtime['name']}");
                    } catch (\Throwable $th) {
                        Console::error('Inactive Runtime deletion failed: ' . $th->getMessage());
                    } finally {
                        $orchestrationPool->put($orchestration);
                    }
                });
            }
        }
    });

**Comment by garvitomer** [comment]
It didn't worked, still same curl error. It is very frustrating to see whole app getting break due to this bug.
Someone please solve it 🙏🏻

**Comment by rafagazani** [comment]
@garvitomer do you have access to cloud.appwrite.io? if you have an automated script to upload your structure, you could put it, maybe it would be easier for the core to find the cause. does this help @stnguyen90 ?

**Comment by garvitomer** [comment]
No. I don't have access to cloud. I got the mail but somehow not able to login into cloud neither password is changing. 
I can share all the logs from docker and mine code (on my mac) too.

**Comment by garvitomer** [comment]
Is it possible that appwrite is not able to delete fucntion properly or the folder/id of it. And when I am deleting and redeploying it with same name, id, foldername etc.. from cli. It is causing the issue?

check last few fucntions or whole code here:
https://github.com/appwrite/appwrite/blob/8d99860c55cff4ab1291a51ee5b6c7900641e1eb/app/executor.php#L200

**Comment by koyapo** [comment]
i do have the same probleme, the most frustrating part of the problem is that the crashes prevent you and users from accessing your instance, so you have to restart it every time it crashes.
i'm thinking about using other alternative to function like firebase or amazon

**Comment by garvitomer** [comment]
Yeah. It is very frustrating. And I don't know why appwrite team is not paying much attention to such a critical issue in the cloud function. I have raised it so many times in discord. It makes appwrite cloud fucntions completely useless for production.
I am restarting docker every day just to minimize the impact🥲

**Comment by koyapo** [comment]
no i dont delete and recreate function using the same name and id, but i will try to change both to see if it change something what are the specs of your server ? im thinking abt taking a bigger one and do like ur are doing restart once a days and manage to grab some time to change my infrastructure

**Comment by garvitomer** [comment]
I use 4gb ram with 2 cores in hetzner server. And appwrite server version is 0.15.3

**Comment by sergioponguta** [comment]
> I use 4gb ram with 2 cores in hetzner server. And appwrite server version is 0.15.3

I have made a workaroud using an external python docker container that can reboot executor container or even do a systemctl reboot to the host.

I think it could be made even with pure shell using CURL.

I just look for docker error on appwrite function logs, and if It finds one, do a reboot

**Comment by garvitomer** [comment]
Seems fair but can't try your method in production as it will stop the whole server. So, I do docker restart every night and error has reduced a lot.

But why the error is happening anyway? Is it so difficult to find this bug? (I don't have much idea about server and all, just have very basic idea about docker)

**Comment by rafagazani** [comment]
here it happened again. It goes a few days without calling the function. When triggered by the databases.default.collections.my_collection.documents.*.create event:
"An internal curl error has occurred within the executor! Error Msg: Connection reset by peer"

**Comment by rafagazani** [comment]
@stnguyen90 did you manage to reproduce something in this sense?

**Comment by rafagazani** [comment]
@sergioponguta @garvitomer @koyapo if you can join the conversation
https://discord.com/channels/564160730845151244/1078437335844266085

**Comment by stnguyen90** [comment]
We have a [big change to functions coming soon](https://github.com/appwrite/appwrite/discussions/5016) so that might resolve this problem.

**Comment by rafagazani** [comment]
@sergioponguta @garvitomer @koyapo @andoidam Could you let me know which cloud provider you are using?
I am using contabo.com and it seems to me that there is some blockage in my case. When I try to deploy it, it fails to download the necessary files, even restarting the error continues

**Comment by koyapo** [comment]
sorry for the late reply, i'm using scaleway i did take a bigger instance the worry still happen but less often, i recommande u to use function from another provider other than appwrite like amazon or firebase u will have to implement all the logic but i'm pretty sure that it will be much more stable i did some charge test like calling my function 400 seconds with appwrite function it did crash but not with scaleway function

**Comment by garvitomer** [comment]
> @sergioponguta @garvitomer @koyapo @andoidam Could you let me know which cloud provider you are using?
> I am using contabo.com and it seems to me that there is some blockage in my case. When I try to deploy it, it fails to download the necessary files, even restarting the error continues

Hi, I am using Hetzner server. 

I don't think it is cloud provider/server issue as lots of us are facing this critical issue, it has to be appwrite bug

**Comment by andoidam** [comment]
@garvitomer linode

**Comment by rafagazani** [comment]
I changed my cloud provider contabo for digital ocean (8gb ram, 6 core, 160 ssd). Functions are working again.
With @Steven  explanations and testing the behavior of appwrite, I verified that each execution of the appwrite functions should not be executed for more than 30 seconds, DO NOT USE the appwrite cloud functions, as there is a risk that the maintenance task will kill the execution that will generate the error: "An internal curl error has occurred within..."
It was suggested to break the function into several functions. It works but there are points to be considered:
For example, I have a collection with 600,000 documents, just scrolling through these documents takes 3 minutes: So, the maintenance task runs the risk of killing the execution. If there is a risk, you can't trust it. 
I did confirm Meldiron recommendation, (here is my implementation https://gist.github.com/rafagazani/687f64c21e0a28cdc7731ea2e633e052) For each document call another function to create the document in the other project (created_document.py)
And it worked, not one run failed (over 45k runs and rising)each function takes no more than 1 second. it has been running for over 9 hours without errors, the documents are being replicated to a project on cloud.appwrite.io. The conclusion I come to is that it can be done but it is not feasible. Not to mention that if you have other functions on the server, you will have to wait for this entire process for them to be executed. I believe that if the safe limit respected the timeout that we defined in the function, all this work would not take 20 minutes. (like all other cloud functions providers, example: in google cloud functions it allows a timeout of up to 3,600 seconds)
Despite the lack of documentation on how this maintenance task works and influences the cloud function, it shouldn't kill an execution if it doesn't reach the timeout, this should be reviewed and the documentation should also be improved so as not to create wrong expectations.

**Comment by luethis** [comment]
Hi! Are there any news on this issue?

**Comment by rafagazani** [comment]
> https://discord.com/channels/564160730845151244/1078437335844266085

https://discord.com/channels/564160730845151244/1078437335844266085

**Comment by rafagazani** [comment]
> Hi! Are there any news on this issue?

https://discord.com/channels/564160730845151244/1078437335844266085

**Comment by stnguyen90** [comment]
> Message: An internal curl error has occurred within the executor! Error Msg: Could not resolve host: [container name]

We're currently working on improving functions to prevent this error. If you're seeing a different error, it is unrelated to this issue.

For now, there are some things you can do to mitigate this and they all involve preventing the runtime container from being removed.

First, make sure your function doesn't take too long to execute. The longer it takes to execute, the more likely it will be treated as inactive (because it hasn't completed successfully).

In addition, you can have your function execute regularly (but don't do anything) so that it doesn't get considered as inactive.

If you're self hosting, you can also try to increase the inactivity threshold (there's an environment variable for it) to a value where the runtime container won't be removed.



You can do both of these too
