### ISSUE TITLE
📚 Documentation: Clean up mention of Nested Documents 

### ISSUE THREAD

**Issue by coldino** [appwrite/appwrite#3791]
### 💭 Description

I got very excited by the mention of Nested Documents on https://appwrite.io/docs/realtime but sadly after hunting through the rest of the docs and the issues here it seems this essential feature has been removed :( Should clean up the docs to match the sad reality.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by pyagnik1** [comment]
Hello coldino, I would like to help clean up the nested documentation if this task is still open.

**Comment by stnguyen90** [comment]
@pyagnik1, assigned! Thanks for you help!

**Comment by pyagnik1** [comment]
@stnguyen90 , This is my first time contributing to an open-source project. Thanks for the opportunity😊. Can you tell me which folder contains documentation for nested documentation? Thanks

**Comment by stnguyen90** [comment]
@pyagnik1, looks like someone already took care of the change: https://github.com/appwrite/docs/pull/247/files#diff-8a5f72a5c6ce07ea3ca566582c24d0206c87c02c826b083d729fd18d0c8fecef. Thanks, though!
