### ISSUE TITLE
🚀 Feature: Custom images for runtimes

### ISSUE THREAD

**Issue by binaryfire** [appwrite/appwrite#3796]
### 🔖 Feature description

Allow the use of custom docker images for runtimes 

### 🎤 Pitch

This would allow users to add their own packages to images to cover almost any use case. For example, additional PHP extensions: https://github.com/appwrite/appwrite/discussions/1490. Or CLI utilities like Ansible.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This looks like a duplicate of https://github.com/appwrite/appwrite/issues/1037. Is it okay if you close this issue and 👍 https://github.com/appwrite/appwrite/issues/1037?

**Comment by binaryfire** [comment]
Done :)
