### ISSUE TITLE
🐛 Bug Report: Error Passing Integer for Double Attribute

### ISSUE THREAD

**Issue by Kings-Samuel** [appwrite/appwrite#3806]
### 👟 Reproduction steps

I have a collection that has some of its attributes as double types, but I noticed that whenever I pass in a number that doesn't have a decimal point, it returns an error while trying to get the doc from the database. 

### 👍 Expected behavior

I thought doubles are supposed to be able to hold integers as well. Is there a way to fix this? I'm using the latest version of appwrite and dart.

### 👎 Actual Behavior

It returns an error. 
The error returned is: type 'int' is not a subtype of type 'double?'

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Digital Ocean

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Kings-Samuel, thanks for raising this issue! 🙏 Would you please clarify which API calls you make that result in this problem?

**Comment by stnguyen90** [comment]
@Kings-Samuel are you still facing this issue on the latest version of Appwrite? Fyi, I'll need to close this soon due to inactivity
