### ISSUE TITLE
Add API response payload structure info and examples to the docs site

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#381]
This is the one major things the API spec docs are still missing. I have started working on creating a code layer to define all the API endpoint result objects and verify them. This will also come very handy for the GraphQL support issue (#272)

**Comment by eldadfux** [comment]
@christyjacob4 We'll need to work on this together, because the homepage code is still not open-source.

The idea is to use the new Response object we introduced with Cloud Functions (branch: `swoole-and-functions`) and use it to parse the different response models inside our open-api spec route (https://localhost/v1/open-api-2.json?extensions=1&platform=console). Later we use the response of this route to parse appwrite.io docs.

Resources:
* The new response object: https://github.com/appwrite/appwrite/blob/swoole-and-functions/src/Appwrite/Utopia/Response.php
* List of all new response models: https://github.com/appwrite/appwrite/tree/swoole-and-functions/src/Appwrite/Utopia/Response/Model

**Comment by christyjacob4** [comment]
Sure @eldadfux just let me know a time and we can connect 👍

**Comment by eldadfux** [comment]
This PR is a major step to get this issue resolved: https://github.com/appwrite/appwrite/pull/734

**Comment by eldadfux** [comment]
This issue is now ready for deployment when v0.7 is available!

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/99301394-9494a480-2856-11eb-8284-d9eb0725a338.png)

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/99301452-b0984600-2856-11eb-8b89-df21d8e2ba9b.png)

**Comment by eldadfux** [comment]
Ready and available on https://appwrite.io/docs
