### ISSUE TITLE
🐛 Bug Report: Function build fails when default bridge is disabled

### ISSUE THREAD

**Issue by FallingSnow** [appwrite/appwrite#3812]
### 👟 Reproduction steps

Build a function with the following in your `/etc/docker/daemon.json`.
```
{
        "bridge": "none"
}
```

### 👍 Expected behavior

Build succeeds.

### 👎 Actual Behavior

```
Docker Error: npm ERR! code EAI_AGAIN
npm ERR! syscall getaddrinfo
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/node-appwrite/-/node-appwrite-7.0.3.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-11T21_45_06_201Z-debug.log
```

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

```
$ docker --version
Docker version 20.10.17, build 100c70180f
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by mrarticuno** [comment]
Same happening here, MacOsX.

Looks like the DNS can't resolve when executing functions localhost.

Happening for NodeJS and Pyhton so I'm assuming that's a problem beteween the docker pods.

**Comment by eldadfux** [comment]
Hey @FallingSnow, thanks for reporting this issue. Can you share what is your use case for disabling `bridge`?

**Comment by FallingSnow** [comment]
My IP addresses are defined on the router side using IP reservations based on MAC address. Docker's default bridge causes the mac address of the bridge to be submitted to the router. The MAC address of the bridge can randomly change between docker version updates, thus causing my server not to get the correct IP. That and I don't need the default bridge so I just disable it.

**Comment by stnguyen90** [comment]
@FallingSnow, the bridge network is the default network for containers, but since it's disabled, the runtime container can't connect to the internet to install dependencies. Maybe you can change some docker settings so that the runtime containers use some other default network that has access to the internet. 

Another workaround is to make sure the node_modules folder is in the uploaded code so that the runtime container doesn't need to download any other dependencies.

**Comment by FallingSnow** [comment]
Is there a way to configure which network appwrite runtime containers use?

Also, is there `.env` documentation? Because I found this but it doesn't seem to change which network the runtimes use.
```env
...
OPEN_RUNTIMES_NETWORK=appwrite_runtimes
...
```

I also tried changing `_APP_EXECUTOR_RUNTIME_NETWORK=appwrite_runtimes` but no dice.

**Comment by stnguyen90** [comment]
@FallingSnow, our environment variables are documented [here](https://appwrite.io/docs/environment-variables). That network is just for some of the containers to talk to each other. You'll probably need to tweak it a bit (I recommend using a docker-compose.override.yml file) to somehow expose it to the internet.

**Comment by FallingSnow** [comment]
@stnguyen90 Thanks for the doc link. There doesn't seem to be any env variables that can change the default network for function builders. I ran the build again and looked at the container it created. The only network the container had was `bridge`. Likewise `docker-compose.yml` doesn't have any definitions for a "function builder" container.

Is there any way to change the default network/add a network or are we stuck with `bridge`?

**Comment by stnguyen90** [comment]
@FallingSnow, I think changing the default network would be a docker setting rather than Appwrite-specific. Unfortunately, I don't know docker enough to help with this 😕 .

**Comment by stnguyen90** [comment]
@FallingSnow, can this be closed now as this is a little outside of our scope?

**Comment by FallingSnow** [comment]
Yes. I moved away form Appwrite after being unable to fix this.

As a side note, I think this is a Appwrite issue. The Appwrite system creates the function builder container. It defines which network the container connects to.
