### ISSUE TITLE
🐛 Bug Report: remix.run + appwrite

### ISSUE THREAD

**Issue by 729902288** [appwrite/appwrite#3813]
### 👟 Reproduction steps

remix.run + appwrite:
1、So "remix.run" is SSR，I don't know to use "npm i appwrite" or "npm i node-appwrite". 
2、logined and "token: jwt" how to append to a new appwrite's instance ?
3、It's fine if a example (remix + appwrite)!

thanks!

### 👍 Expected behavior

Is there a example(remix + appwrite)?

### 👎 Actual Behavior

none

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by alibekissakul** [comment]
Can this repository add some clarity?
https://github.com/brandonroberts/demo-todo-with-remix

I think that it rather depends on your application, if it is a purely front part, then of course client sdk is better, if something like Back-Office can be used server side sdk, as there may be a need to manage users/teams

**Comment by eldadfux** [comment]
Now with improved SSR support working with Appwrite and Remix should be a lot easier. Learn more at: https://appwrite.io/blog/post/introducing-support-for-server-side-rendering
