### ISSUE TITLE
[Discussion] Adding static hosting and nodejs

### ISSUE THREAD

**Issue by therhenalsdev** [appwrite/appwrite#383]
It would be great if you could deploy a static app for example developed with angular, react, ... etc. On the other hand that you can also deploy a backend developed with express, nestjs, or any other library on the server side.

And make all this easy to deploy, with a command line (CLI).

**Comment by eldadfux** [comment]
We are working on a cloud functions service that will allow you to extend Appwrite easily with multiple language support (including Node). You can learn more about that at: #307 . A CLI is also something that @christyjacob4 is going to work on very soon.

I would love to get more of your feedback about static hosting, feel free to share your view on how this kind of feature should be implemented in Appwrite, we can also chat about it on Discord if that something you like (https://discord.gg/GSeTUeA).

**Comment by eldadfux** [comment]
And as usual with new features, if anyone from the community has something to add here this is the time and the place 😃

**Comment by therhenals** [comment]
About the static hosting, it could be something like firebase hosting, using nginx.

**Comment by TorstenDittmann** [comment]
Sounds like a good idea at first, but comes with a lot of work to adapt everything.

Just a few things that come to mind:
- Custom Domains
- Deployment
- Security
- Optimization (like prevent hotlinks)

**Comment by eldadfux** [comment]
> Sounds like a good idea at first, but comes with a lot of work to adapt everything.
> 
> Just a few things that come to mind:
> 
> * Custom Domains
> * Deployment
> * Security
> * Optimization (like prevent hotlinks)
> 
> So probably with something out of the box, you are better of using the upcoming cloud functions.

@TorstenDittmann 

* Custom Domains - We already done most of the hard work for supporting custom domains for the API endpoint + we support the SSL auto-generation which is definitely the hardest thing here (maybe we can add a target property to each domain?)
* Me & @christyjacob4 are already working on something like this for cloud functions.
* Any specific concerns here? Not allowing any site to run from the master domain will probably be my main thought (XSS & cookie hijacking)
* What were you thinking about? I guess we could provide some boosting, but anything in mind?

**Comment by punitdiwan** [comment]
@eldadfux My questions and concerns are regarding deployments. Will we use separate containers  for static site deployment. I checked now.sh (now Versel.com) and netlify. Both of them use docker containers wit static site deployment.

For deployment, I am sure that we have to use a CLI for pushing the site. I checked the whole now.sh API and cli system. We can create deployments of same site multiple time using both cli and API. We can switch to the previous deployment as well.

If someone is interested, I will be happy to share more now.sh CLI Features.

**Comment by eldadfux** [comment]
@punitdiwan I'm not sure a separate container is required because this are just static files. Maybe we can just build a small proxy for them. This will also allow us to calculate traffic, add stats and do other cool stuff (auto webp, compressions).

We could also benefit from other Appwrite built-in features HTTP/2, Brotli compression (soon) and others.

**Comment by eldadfux** [comment]
Seems to be duplicated with #520 please continue discussion there 👍
