### ISSUE TITLE
🚀 Feature: Global maintenance endpoint

### ISSUE THREAD

**Issue by stonith404** [appwrite/appwrite#3837]
### 🔖 Feature description

A global maintenance endpoint that can be enabled globally for every project and gets automatically enabled if Appwrite gets upgraded. Maybe this must be a different micro service, running completely individually on another port. 

### 🎤 Pitch

While I was upgrading to the newest Appwrite version, I noticed how long it takes to migrate my data. While the migration script was running, the most projects didn't work. 
It would be awesome to check on the frontend if the Appwrite instance is in maintenance mode. So you could return a maintenance screen instead of a application that doesn't work because Appwrite is upgrading.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Data migrations are complex and at the moment we do not have an ability to control how the instance behave during version update. We do consider to put more effort into this a part of a future enterprise version for orgs that need zero-downtime upgrades.
