### ISSUE TITLE
[flutter] Why dio over http?

### ISSUE THREAD

**Issue by rubensdemelo** [appwrite/appwrite#384]
Why appwrite uses dio over native http package ?

**Comment by eldadfux** [comment]
@bartektartanus or @Almoullim you guys could probably give a better answer than me here.

**Comment by Almoullim** [comment]
The decision was largely made by me to use the Dio package. It had support for interceptors, it had a plugin (dio_cookie_manager) that made it easier to deal with cookies and at the time there wasn't a reason for me to use dart HTTP package and not use Dio.

**Comment by rubensdemelo** [comment]
@Almoullim thanks for clarification
