### ISSUE TITLE
🐛 Bug Report: SMTP SETUP ERROR

### ISSUE THREAD

**Issue by bliyscom** [appwrite/appwrite#3849]
### 👟 Reproduction steps

I have followed all the steps listed in documentation to setup smtp with sendgrid. Everything works fine on the sendgrid side and domain and sender are also verified. However, appwrite does not send emails. Email logs say no smtp server set but i have set it up and restarted appwrite
  __   ____  ____  _  _  ____  __  ____  ____     __  __
 / _\ (  _ \(  _ \/ )( \(  _ \(  )(_  _)(  __)   (  )/  \
/    \ ) __/ ) __/\ /\ / )   / )(   )(   ) _)  _  )((  O )
\_/\_/(__)  (__)  (_/\_)(__\_)(__) (__) (____)(_)(__)\__/

👩‍⚕️ Running Appwrite Doctor for version 0.15.3 ...

Checking for production best practices...
🟢 Hostname has a public suffix (domain)
🟢 CNAME target has a public suffix (domain)
🟢 Using a unique secret key for encryption
🟢 App environment is set for production
🟢 Abuse protection is enabled
🟢 Console access limits are enabled
🔴 HTTPS force option is disabled
🔴 Logging adapter is disabled

Checking connectivity...
Database............connected 👍
Queue...............connected 👍
Cache...............connected 👍
SMTP................connected 👍
StatsD..............connected 👍
InfluxDB............connected 👍

Checking volumes...
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

Checking disk space usage...
🟢 Uploads Volume has 903.28GB free space (7.34% used)
🟢 Cache Volume has 903.28GB free space (7.34% used)
🟢 Config Volume has 903.28GB free space (7.34% used)
🟢 Certs Volume has 903.28GB free space (7.34% used)

compose setup
- _APP_SYSTEM_EMAIL_NAME=[company name]
      - _APP_SYSTEM_EMAIL_ADDRESS=[company email]
      - _APP_SYSTEM_SECURITY_EMAIL_ADDRESS=[company email]
      - _APP_SYSTEM_RESPONSE_FORMAT
      - _APP_OPTIONS_ABUSE
      - _APP_OPTIONS_FORCE_HTTPS
      - _APP_OPENSSL_KEY_V1
      - _APP_DOMAIN=[domain]
      - _APP_DOMAIN_TARGET=[domain]
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_SMTP_HOST=smtp.sendgrid.net
      - _APP_SMTP_PORT=587
      - _APP_SMTP_SECURE=tls
      - _APP_SMTP_USERNAME=apikey
      - _APP_SMTP_PASSWORD=[sendgrid api key]
//email worker log error
 Skipped mail processing. No SMTP server hostname has been set.

### 👍 Expected behavior

emails should be sent 

### 👎 Actual Behavior

emails are not being sent

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

cloudflare

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@bliyscom, is the SMTP host set in the output of `docker compose exec appwrite-worker-mails vars`?

**Comment by bliyscom** [comment]
no its not but i have not been able to set that up. I have run the command below several times but no changes. The file just refuses to update:
docker compose up -d --build --force-recreate

//////////////////
[root@s107541 appwrite]# docker compose exec appwrite-worker-mails vars
- _APP_ENV=production
- _APP_LOCALE=en
- _APP_OPTIONS_ABUSE=enabled
- _APP_OPTIONS_FORCE_HTTPS=disabled
- _APP_OPENSSL_KEY_V1=landcoins@2035
- _APP_DOMAIN=localhost
- _APP_DOMAIN_TARGET=localhost
- _APP_CONSOLE_WHITELIST_ROOT=enabled
- _APP_CONSOLE_WHITELIST_EMAILS=
- _APP_CONSOLE_WHITELIST_IPS=
- _APP_SYSTEM_EMAIL_NAME=Appwrite
- _APP_SYSTEM_EMAIL_ADDRESS=team@appwrite.io
- _APP_SYSTEM_RESPONSE_FORMAT=
- _APP_SYSTEM_SECURITY_EMAIL_ADDRESS=
- _APP_USAGE_STATS=enabled
- _APP_LOGGING_PROVIDER=
- _APP_LOGGING_CONFIG=
- _APP_USAGE_AGGREGATION_INTERVAL=
- _APP_WORKER_PER_CORE=
- _APP_REDIS_HOST=redis
- _APP_REDIS_PORT=6379
- _APP_REDIS_USER=
- _APP_REDIS_PASS=
- _APP_DB_HOST=mariadb
- _APP_DB_PORT=3306
- _APP_DB_SCHEMA=appwrite
- _APP_DB_USER=root
- _APP_DB_PASS=password
- _APP_DB_ROOT_PASS=
- _APP_INFLUXDB_HOST=influxdb
- _APP_INFLUXDB_PORT=8086
- _APP_STATSD_HOST=telegraf
- _APP_STATSD_PORT=8125
- _APP_SMTP_HOST=
- _APP_SMTP_PORT=
- _APP_SMTP_SECURE=
- _APP_SMTP_USERNAME=
- _APP_SMTP_PASSWORD=
- _APP_PHONE_PROVIDER=
- _APP_PHONE_FROM=
- _APP_STORAGE_LIMIT=10000000
- _APP_STORAGE_PREVIEW_LIMIT=
- _APP_STORAGE_ANTIVIRUS=enabled
- _APP_STORAGE_ANTIVIRUS_HOST=clamav
- _APP_STORAGE_ANTIVIRUS_PORT=3310
- _APP_STORAGE_DEVICE=Local
- _APP_STORAGE_S3_ACCESS_KEY=
- _APP_STORAGE_S3_SECRET=
- _APP_STORAGE_S3_REGION=
- _APP_STORAGE_S3_BUCKET=
- _APP_STORAGE_DO_SPACES_ACCESS_KEY=
- _APP_STORAGE_DO_SPACES_SECRET=
- _APP_STORAGE_DO_SPACES_REGION=
- _APP_STORAGE_DO_SPACES_BUCKET=
- _APP_STORAGE_BACKBLAZE_ACCESS_KEY=
- _APP_STORAGE_BACKBLAZE_SECRET=
- _APP_STORAGE_BACKBLAZE_REGION=
- _APP_STORAGE_BACKBLAZE_BUCKET=
- _APP_STORAGE_LINODE_ACCESS_KEY=
- _APP_STORAGE_LINODE_SECRET=
- _APP_STORAGE_LINODE_REGION=
- _APP_STORAGE_LINODE_BUCKET=
- _APP_STORAGE_WASABI_ACCESS_KEY=
- _APP_STORAGE_WASABI_SECRET=
- _APP_STORAGE_WASABI_REGION=
- _APP_STORAGE_WASABI_BUCKET=
- _APP_FUNCTIONS_SIZE_LIMIT=30000000
- _APP_FUNCTIONS_TIMEOUT=900
- _APP_FUNCTIONS_BUILD_TIMEOUT=
- _APP_FUNCTIONS_CONTAINERS=10
- _APP_FUNCTIONS_CPUS=1
- _APP_FUNCTIONS_MEMORY=128
- _APP_FUNCTIONS_MEMORY_SWAP=128
- _APP_FUNCTIONS_RUNTIMES=
- _APP_EXECUTOR_SECRET=a-random-secret
- _APP_EXECUTOR_HOST=http://appwrite-executor/v1
- _APP_EXECUTOR_RUNTIME_NETWORK=appwrite_runtimes
- _APP_FUNCTIONS_ENVS=
- _APP_FUNCTIONS_INACTIVE_THRESHOLD=
- DOCKERHUB_PULL_USERNAME=
- DOCKERHUB_PULL_PASSWORD=
- DOCKERHUB_PULL_EMAIL=
- OPEN_RUNTIMES_NETWORK=
- _APP_MAINTENANCE_INTERVAL=86400
- _APP_MAINTENANCE_RETENTION_EXECUTION=1209600
- _APP_MAINTENANCE_RETENTION_AUDIT=1209600
- _APP_MAINTENANCE_RETENTION_ABUSE=86400

**Comment by bliyscom** [comment]
I set it up in the docker-compose.yml, Now that you mentioned it, I just realized that .env was hidden. Let me set it up and fry again. Thanks very much for the tip
