### ISSUE TITLE
[DISCUSSION] Disable email registration on client

### ISSUE THREAD

**Issue by therhenals** [appwrite/appwrite#385]
It is possible to disable email registration on the client side of a project, which only allows access. This feature would be useful, for example, I have a delivery app, customers register with google, restaurants/businesses cannot register, I am the one who registers them in the system with an email and password. So I would like to avoid that anyone can register with an email and password, that only the login is enabled.

**Comment by eldadfux** [comment]
I would love to get more community feedback on this and other options that might be useful for the users API and where is the best place to show this options in the Appwrite Console.
