### ISSUE TITLE
📚 Documentation: Update the "One-click setup" for DigitalOcean to the latest version of Appwrite.

### ISSUE THREAD

**Issue by Clemens05** [appwrite/appwrite#3857]
### 💭 Description

The One-click setup for DigitalOcean should setup should include the latest version (1.0.1).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Clemens05, thanks for raising this issue! 🙏 We've submitted the new [image](https://github.com/appwrite/integration-for-digitalocean/releases/tag/1.0.1), but are waiting for DO to approve it.

**Comment by shintaii** [comment]
It is updated now. The DO button needs to be re-linked i guess:

https://marketplace.digitalocean.com/apps/appwrite

**Comment by gewenyu99** [comment]
@shintaii I think the link is updated. might be a cache issue?
<img width="374" alt="Screen Shot 2022-09-16 at 2 12 34 PM" src="https://user-images.githubusercontent.com/29069505/190704949-48479f5e-695d-4396-bdf2-1caa26a8ee6c.png">

**Comment by gewenyu99** [comment]
AFAIK, this can be closed?

**Comment by Clemens05** [comment]
Thanks!
