### ISSUE TITLE
🐛 Bug:`_APP_SMS_PROVIDER` not working.

### ISSUE THREAD

**Issue by Faizan-Pasha** [appwrite/appwrite#3859]
### 💭 Description

What is the format for `_APP_SMS_PROVIDER`?

I was using `_APP_PHONE_PROVIDER=phone://<Account SID>:<Auth Token>@twilio` on `v0.15.3`. It was working fine.
I updated to `v1.0.1` and using `_APP_SMS_PROVIDER=sms://<Account SID>:<Auth Token>@twilio` as shown in the new docs. Appwrite is returning `Instance of 'Token'` but the request is not being sent to the `twilio`.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@DynamiteFP, any errors in the `appwrite-worker-messaging` container?

**Comment by DynamiteFP** [comment]
@stnguyen90 
`appwrite-worker-messaging  | [critical] (Job{v1-messaging} | ID: 22cad4fb7ef4db28808cdf24806cb446 | MessagingV1 | [{"project":null,"user":null,"payload":[],"recipient":"[MY_NUMBER]","message":"692495","events":["."]}]) has failed TypeError: Cannot assign Appwrite\SMS\Adapter\Twilio to property MessagingV1::$sms of type ?Appwrite\Auth\SMS in /usr/src/code/app/workers/messaging.php:36`

**Comment by stnguyen90** [comment]
@DynamiteFP, thanks so much for this! Looks like worker used to reference a [Phone](https://github.com/appwrite/appwrite/blob/8d99860c55cff4ab1291a51ee5b6c7900641e1eb/app/workers/messaging.php#L20) class and it was changed to [SMS](https://github.com/appwrite/appwrite/blob/939b5a00f5a87c3a16a70adb201d5d1c4b9a013e/app/workers/messaging.php#L22), but that class doesn't exist. Probably because [Phone](https://github.com/appwrite/appwrite/blob/8d99860c55cff4ab1291a51ee5b6c7900641e1eb/src/Appwrite/Auth/Phone.php#L7) was changed to [Adapter](https://github.com/appwrite/appwrite/blob/939b5a00f5a87c3a16a70adb201d5d1c4b9a013e/src/Appwrite/SMS/Adapter.php#L5).

**Comment by DynamiteFP** [comment]
@stnguyen90 
Did you had a look at [this](https://github.com/appwrite/appwrite/pull/3862)?

**Comment by Mr-Malomz** [comment]
Any update on this issue?

`_APP_PHONE_PROVIDER=phone://<Account SID>:<Auth Token>@twilio` for Appwrite version  `v1.0.1` keeps throwing `AppwriteException: Phone provider not configured`

**Comment by DynamiteFP** [comment]
@Mr-Malomz I have fixed the issue and raised a [pull request ](https://github.com/appwrite/appwrite/pull/3862)

**Comment by Mr-Malomz** [comment]
@DynamiteFP Nice! Well done.
 I'm guessing the PR is not merged yet. right?
 
 Just to confirm, does it mean that the updated reference class from `phone` to `sms` also changes the environment variable name from `_APP_PHONE_PROVIDER` to `_APP_SMS_PROVIDER`?

**Comment by DynamiteFP** [comment]
@Mr-Malomz yes the PR has not been merged yet.

> Format for version <= 0.15
`_APP_PHONE_PROVIDER=phone://<Account SID>:<Auth Token>@twilio`

>Format for version >= 0.15
`_APP_SMS_PROVIDER=sms://<Account SID>:<Auth Token>@twilio`

**Comment by Mr-Malomz** [comment]
@DynamiteFP Nice!

Thank you

**Comment by Mr-Malomz** [comment]
Hi @DynamiteFP 
Sorry to disturb :)


I'm currently trying out the `createPhoneSession` using version `0.15.0` in a Next.js application. I have configured the environment variables and synced the settings with the running container.

However, it keeps returning an empty secret, and twilio doesn’t send any SMS

Here is a sample of the returned response
`{$id: '632a51d1a85a59467429', $createdAt: 1663717841, userId: '632a48b510ac7fddece1', secret: '', expire: 1663718741}`.

Not sure if, I'm missing something or the operation cannot be performed from a client app.

**Comment by DynamiteFP** [comment]
Hello @Mr-Malomz 
The secret is the OTP you will get on your mobile number.
In `createPhoneSession` it doesn't return secret. After you get a response from the `createPhoneSession` method store the `userId` on the device . You will recieve the secret througth the sms on your mobile. and then with `updatePhoneSession` verify the user by sending the `secret` and `userId` to appwrite.

**Comment by Mr-Malomz** [comment]
Thanks @DynamiteFP 

Yea, this is the way I envisioned it to work. However, it doesn’t. For some weird reason, it didn't.

I am using this article [phone auth with appwrite and twilio](https://dev.to/appwrite/phone-authentication-with-appwrite-and-twilio-26ek)

My codebase [here](https://github.com/Mr-Malomz/twilio-auth)

**Comment by DynamiteFP** [comment]
@Mr-Malomz You have to verify you mobile number to get sms on twilio trail account

**Comment by Mr-Malomz** [comment]
Yea @DynamiteFP , did this already. In fact, I verified two phone numbers

**Comment by DynamiteFP** [comment]
@Mr-Malomz Did you check the twilio log!

**Comment by Mr-Malomz** [comment]
@DynamiteFP Just did! The log is empty. I guess my request from Appwrite is not hitting Twilio

**Comment by DynamiteFP** [comment]
@Mr-Malomz Exactly.
Can I have a look at the code please?
And what version of appwrite npm dependency are you using?

**Comment by Mr-Malomz** [comment]
@DynamiteFP 

Code [here](https://github.com/Mr-Malomz/twilio-auth)

Appwrite version is `0.15.0` and npm Appwrite package is ` "appwrite": "~9.0.0"`

**Comment by DynamiteFP** [comment]
@Mr-Malomz 
Go to `helper/utils` in `phoneAuth` use `unique()` as `userId`

**Comment by Mr-Malomz** [comment]
@DynamiteFP 
Thanks. Unfortunately, I have tried that earlier and it didn’t reflect on twilio nor did I get an SMS.

I have even tried creating a user on Appwrite and use the `userId` but still not working.

Just curios, Did it work for you on earlier version and which framework did you try it with?

**Comment by DynamiteFP** [comment]
@Mr-Malomz 
It wasn't working before but after I changed it to `'unique()'` it worked
![image](https://user-images.githubusercontent.com/32414659/191490105-78777c1f-7e98-4955-aad2-830b15077c0c.png)
Make sure to add country code.

**Comment by Mr-Malomz** [comment]
@DynamiteFP 
Wow!

Your env setup looks like this right

`_APP_PHONE_PROVIDER=phone://AC6f76b2552c4AccountID47beed:691f6ca1acbcAuthToken6bbacdfca7@twilio
_APP_PHONE_FROM=+12566854594`

**Comment by DynamiteFP** [comment]
@Mr-Malomz Delete that rn

**Comment by Mr-Malomz** [comment]
Not really. I scrambled it  so it's not the right format. Yea but I can delete it

**Comment by DynamiteFP** [comment]
@Mr-Malomz ok. Your setup is fine. Are you using your country code with the mobile number?

**Comment by Mr-Malomz** [comment]
@DynamiteFP 
yea

**Comment by DynamiteFP** [comment]
@Mr-Malomz run `docker logs appwrite-worker-messaging` in the terminal to see any errors thrown by the phone adaptor.

**Comment by Mr-Malomz** [comment]
I got this error. Which is strange becuase I enabled **SMS Geagraphical Permission**

`{"code": 21408, "message": "Permission to send an SMS has not been enabled for the region indicated by the 'To' number: +2348********.", "more_info": "https://www.twilio.com/docs/errors/21408", "status": 400}`

**Comment by Mr-Malomz** [comment]
@DynamiteFP 

Whoops!!! FInally it works.

For some weird reason, this service `appwrite-worker-messaging` was not running and I needed to start it manually
