### ISSUE TITLE
🐛 Bug Report: Message: Invalid document structure: Attribute "time" has invalid type. Value must be a valid integer

### ISSUE THREAD

**Issue by shintaii** [appwrite/appwrite#3860]
### 👟 Reproduction steps

I followed installation instructions here https://appwrite.io/docs/installation for Windows + powershell. 
After boot up of all docker images and i connect to localhost:8080 
(chosen port & chosen host)

When prompted to create the ROOT account on http://localhost:8080/auth/signup i get an error:

[Error] Timestamp: 2022-09-16T17:50:30+00:00
[Error] Method: POST
[Error] URL: /v1/account
[Error] Type: Utopia\Database\Exception\Structure
[Error] Message: Invalid document structure: Attribute "time" has invalid type. Value must be a valid integer
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 1334

### 👍 Expected behavior

It should create the ROOT user and move to next step of the wizard

### 👎 Actual Behavior

[Error] Timestamp: 2022-09-16T17:50:30+00:00
[Error] Method: POST
[Error] URL: /v1/account
[Error] Type: Utopia\Database\Exception\Structure
[Error] Message: Invalid document structure: Attribute "time" has invalid type. Value must be a valid integer
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 1334

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by shintaii** [comment]
Appearantly there where old volumes/images around on my PC screwing thing up. By removing all images and volumes, and doing a reboot it works again..

**Comment by uahic** [comment]
Had the same issue, after removing selectively all appwrite related images/containers and volumes it really took a restart + repull too to  get it working again

**Comment by Snowsdy** [comment]
Same here, but my problem is that I migrate my database with 'docker exec appwrite migrate', and when I try to log in I had the same issue.
My previous version of Appwrite was 0.15.3. I followed installation instructions for Unix and upgrade to the 1.0.0 version. After that i make the migration of my database. Did I miss something ?
