### ISSUE TITLE
🐛 Bug Report: Return Type of getMemberships and getMembership are the same

### ISSUE THREAD

**Issue by AhmedHammad0900** [appwrite/appwrite#3868]
### 👟 Reproduction steps

Hi there , I was doing some developing and I found that the "getMemberships" and "getMembership" end points return the same return type

For example :-
listDocuments ==> retrun DoucmentList object
getDocument ==> return Document Object

for getMemberships and getMembership that's not working like it's produced for
getMemberships ==> return Memberships List Object
getMemebership ==> return Memberships List Object ( like the previous endpoint but with always a list of 1 member which + total : 1 )

https://appwrite.io/docs/client/teams?sdk=flutter-default#teamsGetMembership 

it must return Membership object only . Not a list always containing 1 membership object and a Total : 1
https://appwrite.io/docs/models/membership

until it's edited both endpoints can be used for the same result  . with sdks it's handleded in objects with easy way ( for oop langs as I tried for flutter ) but with http requests u will need to handle total and a List of single object .

### 👍 Expected behavior

getMemebership must return Membership object

### 👎 Actual Behavior

getMembership return List of a single Membership object and total :1

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Custom VPS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by cavallefano** [comment]
if is it possibile i'd like to contribute
