### ISSUE TITLE
📚 Documentation: https://appwrite.io/docs/error-codes returns 404 Page not found

### ISSUE THREAD

**Issue by Clemens05** [appwrite/appwrite#3869]
### 💭 Description

When you visit https://appwrite.io/docs/error-codes it returns a 404 Page not found error with the Error ID `xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Clemens05, yes, this was actually changed to /response-codes. Where did you see the /error-codes link?

**Comment by Clemens05** [comment]
I saw the link on https://appwrite.io/docs/debugging#statusCodes when clicking on "Learn more about Appwrite status codes" and on google when searching for "appwrite error codes" and "appwrite response codes".

**Comment by christyjacob4** [comment]
@Clemens05 if you'd like, you can create a PR to the docs repo here
https://github.com/appwrite/docs/blob/main/app/views/docs/debugging.phtml#L32

Just change  `error-codes` to `response-codes`

**Comment by codercatdev** [comment]
Resolved
https://github.com/appwrite/docs/pull/251
