### ISSUE TITLE
🐛 Bug Report: New storage bucket creation sometimes fails

### ISSUE THREAD

**Issue by sanny-io** [appwrite/appwrite#3875]
### 👟 Reproduction steps

I couldn't create a new bucket at all until I click around some of the buttons on the page for a bit and it went through. Some weird stuff is being sent with the permissions.

### 👍 Expected behavior

![](https://i.imgur.com/7ucvLkr.png)

### 👎 Actual Behavior

![](https://i.imgur.com/9Th3cTD.png)

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Windows 11 21H2 Build 22000.978
Docker Desktop 4.12.0 85629
Ubuntu 20.04
Appwrite JavaScript SDK 10.0.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This should be resolved as part of 1.0.2, please let us know if it's still a problem and we can re-open the issue.
