### ISSUE TITLE
🐛 Bug Report: Can't set cloud function variables

### ISSUE THREAD

**Issue by artuk99** [appwrite/appwrite#3877]
### 👟 Reproduction steps

Create a function with the following in `appwrite.json` and try set variables in console
```
{
    "projectId": "62e99be40fadac0be13c",
    "projectName": "GIRI",
    "functions": [
        {
            "$id": "test",
            "name": "test",
            "runtime": "dart-2.17",
            "path": "functions/test",
            "entrypoint": "lib/main.dart",
            "ignore": [
                ".packages",
                ".dart_tool"
            ],
            "execute": [],
            "events": [
                "users.*.create"
            ],
            "schedule": "",
            "timeout": 15
        }
    ]
}
```

### 👍 Expected behavior

Variables should be saved and displayed in the console

### 👎 Actual Behavior

I get the message "Registered new variable successfully" when I try to set a variable. Variables are saved but not displayed in the console and cannot be accessed during the execution of the function. Trying to set a variable with the same name will result in the error "Variable with the same ID already exists in your project."

https://user-images.githubusercontent.com/55256343/190923956-3f8831dc-cb81-45e7-bfeb-dd899333ebc0.mp4

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 🧱 Your Environment

```
$ docker --version
Docker version 20.10.17, build 100c701
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by artuk99** [comment]
Apparently something went wrong during the appwrite version upgrade. I just created a new project and the functions work there.

**Comment by germanllop** [comment]
> Apparently something went wrong during the appwrite version upgrade. I just created a new project and the functions work there.

Indeed it works on a new project, but the projects that we already have running, any workarround?

**Comment by stnguyen90** [comment]
> Indeed it works on a new project, but the projects that we already have running, any workarround?

@germanllop, something may have gone wrong during the migration. Can you share the output in a new Q&A Discussion? Also, you can try running the migration again.

**Comment by germanllop** [comment]
> 

I will try to do this again to reproduce and open a new one if encounter with it again. Thanks.
