### ISSUE TITLE
🚀 Feature: Add Mastodon as an authentication method

### ISSUE THREAD

**Issue by grahhnt** [appwrite/appwrite#3878]
### 🔖 Feature description

Add authentication via Mastodon using their [OAuth2 API](https://docs.joinmastodon.org/spec/oauth/)

Mastodon is a federated service, so it would require the Mastodon instance you want to allow people to login under

### 🎤 Pitch

Allowing people to use Mastodon as an authentication method would allow for communities to have one account to login under everything

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by aashimawadhwa** [comment]
Hey can you assign this issue to me ?

**Comment by christyjacob4** [comment]
@grahhnt is this something you'd like to pick up ?

**Comment by grahhnt** [comment]
@christyjacob4 yeah I could pick this up

**Comment by christyjacob4** [comment]
@grahhnt  please go ahead with the implementation . I will assign this issue to you 👍

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
