### ISSUE TITLE
🚀 Feature: Add Email Verification with a verification code instead of a URL

### ISSUE THREAD

**Issue by timurbutt** [appwrite/appwrite#3893]
### 🔖 Feature description

A User wants to create an account and needs to verify his email address. He will receive a 4-6 digit code inside that mail and can then enter that code inside the app. This could be done by linking a randomly generated number to the UserID that is created at signup and also adding a timestamp so the app knows how old the code. This would also make it possible to give the code an expiration time.

### 🎤 Pitch

The main reason why this feature would be great is because I could imagine that its way easier to implement, and also it would be a cool way to verify the User with a code instead of an URL. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
We have a draft PR ready. Few more things to fix and it should be out in the next Appwrite version 😉

**Comment by FaisalMohammadi** [comment]
is their any update to this issue?

**Comment by christyjacob4** [comment]
@FaisalMohammadi @timurbutt sorry for the delay but this issue was deprioritised during the previous releases.

We plan to release it alongside the next Appwrite version.

**Comment by FaisalMohammadi** [comment]
Thats perfect thank you. Is their any fixed date, when would be the next version released?

**Comment by cddqssc** [comment]
Email OTP is very very good, I can’t wait to use it

**Comment by alangautham** [comment]
Please release OTP email verification... the present implementation URL verification is definitely the way to irritate users

**Comment by FaisalMohammadi** [comment]
is their any update to this?

**Comment by Vedsaga** [comment]
is there any update...?
