### ISSUE TITLE
Chinese developers

### ISSUE THREAD

**Issue by sunnycat1991** [appwrite/appwrite#3894]
### 💭 Description

There are million developers in china，Whether to consider opening a Chinese website for them. VPN and En glinsh Doc are difficult for me

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This is something we'd love to achieve. In the next few weeks will start working on migrating the docs repo to markdown files to make it easier for other to contribute translations.
