### ISSUE TITLE
🐛 Bug Report: Operation timed out on cloud function after loading Authentication page in Console

### ISSUE THREAD

**Issue by ddenev** [appwrite/appwrite#3899]
### 👟 Reproduction steps

This is a very strange issue but here it goes...

In summary - a cloud function that usually runs without a problem starts timing out after I load/reload the Authentication page in the Appwrite Console.

I have the following function that creates a user:
```js
const sdk = require('node-appwrite')

module.exports = async function (req, res) {
  const client = new sdk.Client()
  const users = new sdk.Users(client)
  if (!req.variables.APPWRITE_FUNCTION_ENDPOINT || !req.variables.APPWRITE_FUNCTION_API_KEY) {
    throw new Error('Environment variables are not set. Function cannot use Appwrite SDK.')
  }
  client
    .setEndpoint(req.variables.APPWRITE_FUNCTION_ENDPOINT)
    .setProject(req.variables.APPWRITE_FUNCTION_PROJECT_ID)
    .setKey(req.variables.APPWRITE_FUNCTION_API_KEY)
    .setSelfSigned(true)

  const payload = JSON.parse(req.payload)

  try {
    await users.create('unique()', payload.email, undefined, payload.password)
  } catch (e) {
    res.json({ status: 'error', error: e })
    return
  }

  res.json({ status: 'success' })
}
```
Here is the function configuration in `appwrite.json`:
```json
{
    "$id": "createAccount",
    "name": "createAccount",
    "runtime": "node-16.0",
    "path": "functions/createAccount",
    "entrypoint": "src/index.js",
    "ignore": [
        "node_modules",
        ".npm"
    ],
    "execute": ["guests"],
    "events": [],
    "schedule": "",
    "timeout": 15
}
```
I am executing the function with the client SDK:
```js
const execution = await appwrite.functions.createExecution('createAccount',
  JSON.stringify({ email, password })
)
```

### 👍 Expected behavior

The function runs without errors.

### 👎 Actual Behavior

The function usually runs without a problem.

But if I open/load/reload the Authentication page (`/console/users?project=[my-project-id]`) in the Appwrite Console and then run the function I get the following error:
`An internal curl error has occurred within the executor! Error Msg: Operation timed out`

I am not changing anything between the executions, only loading the Authentication page.

After waiting for around 3 minutes, if not reloading the Authentication page, the function starts to run without a timeout.
As long as I reload the Authentication page, the function timeouts again.

Here is the execution object as a result of the timeouting execution:
```json
[
  {
    "$id": "632c120727a828322729",
    "$createdAt": "2022-09-22T07:43:03.162+00:00",
    "$updatedAt": "2022-09-22T07:43:18.167+00:00",
    "$permissions": [],
    "functionId": "createAccount",
    "trigger": "http",
    "status": "failed",
    "statusCode": 500,
    "response": "",
    "stdout": "",
    "stderr": "An internal curl error has occurred within the executor! Error Msg: Operation timed out",
    "duration": 15.5406
  },
]
```

Usually the function runs in about 0.2s so there is no need to increase the timeout duration.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ddenev** [comment]
Another observation - if I comment out the call to:
```js
await users.create('unique()', payload.email, undefined, payload.password)
```
in my cloud function, then it runs OK even after loading the Authenticaion page in the Console.

So it seems that loading the Authentication page somehow messes with the `users.create()` server SDK function call.

**Comment by Meldiron** [comment]
My initial thought is that `APPWRITE_FUNCTION_ENDPOINT` doesn't work properly. No idea how that is related to UI yet.
What is the value of your `APPWRITE_FUNCTION_ENDPOINT`?

**Comment by ddenev** [comment]
Thank you, @Meldiron but as I mentioned above, the function is working just fine unless I visit the Authentication page. Since I do not change anything between executions (except the loading of the Authentication page) I think the endpoint is working just fine.

Just for the record, the value of my `APPWRITE_FUNCTION_ENDPOINT` is `https://appwrite.impulseout.com/v1` and it resolves to a local IP address (192.168.88.1). I have been using it for several months now without any issues.

If you also check my last comment you will see that removing the call to `users.create()` in my cloud function stops it from timing out even after visiting the Authentication page. That again proves the endpoint is just fine.

For me the culprit is somewhere in the Console - loading the Authentication page somehow messes with the call to `users.create()`.

**Comment by stnguyen90** [comment]
@ddenev, is there anything in the appwrite docker logs around the user creation? Also, how many users do you have?

**Comment by ddenev** [comment]
Nothing in the PM2 container - as far as I know logging is disabled there by Appwrite team due to some bug.

I checked the `appwrite` container and here is the message that is logged when I run the function after visiting the Authentication page:
```
[Error] Timestamp: 2022-09-23T19:21:31+00:00
[Error] Method: GET
[Error] URL: /v1/account/sessions/:sessionId
[Error] Type: Appwrite\Extend\Exception
[Error] Message: User (role: guests) missing scope (account)
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 363
An internal curl error has occurred within the executor! Error Msg: Operation timed out
[Error] Timestamp: 2022-09-23T19:21:56+00:00
[Error] Method: POST
[Error] URL: /v1/users
[Error] Type: Appwrite\Extend\Exception
[Error] Message: A user with the same email already exists in your project.
[Error] File: /usr/src/code/app/controllers/api/users.php
[Error] Line: 78
```
The 2nd error  is fine - it's because I'm testing creating a user with the same email/password.

In fact both errors seem fine since here is the log when the function runs without the timeout problem:
```
[Error] Timestamp: 2022-09-23T19:28:07+00:00
[Error] Method: GET
[Error] URL: /v1/account/sessions/:sessionId
[Error] Type: Appwrite\Extend\Exception
[Error] Message: User (role: guests) missing scope (account)
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 363
[Error] Timestamp: 2022-09-23T19:28:10+00:00
[Error] Method: POST
[Error] URL: /v1/users
[Error] Type: Appwrite\Extend\Exception
[Error] Message: A user with the same email already exists in your project.
[Error] File: /usr/src/code/app/controllers/api/users.php
[Error] Line: 78
```
The only difference I see is the `An internal curl error has occurred within the executor! Error Msg: Operation timed out` line in the timeouting execution.

I have only 2 users - one that I login to the Appwrite Console and one in my project.

**Comment by stnguyen90** [comment]
@ddenev I wonder if there's a problem with:

```
    res.json({ status: 'error', error: e })
```

Can you try to remove the `e` or maybe to `e.toString()`?

**Comment by pomarec** [comment]
I also wonder if it has anything to do with server file descriptiors limit or network configuration
