### ISSUE TITLE
Backup and migration system

### ISSUE THREAD

**Issue by therhenals** [appwrite/appwrite#390]
It would be great to implement a backup system and allow migrating appwrite from one server to another, all from the console.

**Comment by gewenyu99** [comment]
👋 Hi there @therhenals 

We now have a migration guide and script in our docs: https://appwrite.io/docs/upgrade

We also have a suggested way to back up Appwrite: https://gist.github.com/Meldiron/47b5851663668102a676aff43c6341f7

Does this address your request?

**Comment by tripolskypetr** [comment]
If someone is building CI/CD for their AppWrite applications, [this tool will be quite useful](https://github.com/react-declarative/appwrite-backup-tool). It is a set of scripts which will help you automatically deploy `appwrite.json` schema to Docker container and reupload all buckets and databases

**Comment by gewenyu99** [comment]
@tripolskypetr This is great! Thanks for sharing. 

I think the backup process is going to be different setup to setup. Infrastructure is not within the scope of our software, so community tools like this will be vital！

**Comment by eldadfux** [comment]
Both backups and migrations are now available in both Cloud and the self-hosted edition.

For more information:
https://appwrite.io/docs/advanced/migrations
https://appwrite.io/docs/products/databases/backups

**Comment by Nebula-Developer** [comment]
> available in both Cloud and the self-hosted edition.

I couldn't find any reference to the backup features being available on a self-hosted appwrite instance on [this page](https://appwrite.io/docs/products/databases/backups), am I looking in the wrong place?

**Comment by Kgym-Hina** [comment]
> > available in both Cloud and the self-hosted edition.
> 
> I couldn't find any reference to the backup features being available on a self-hosted appwrite instance on [this page](https://appwrite.io/docs/products/databases/backups), am I looking in the wrong place?

+1, found only "Backups are available on Appwrite Cloud for all Pro, Scale, and Enterprise customers." on the documentation

**Comment by MuscledGeek** [comment]
I haven't tried this but, isn't it the database just a mariaDB instance where you can connect, create a backup, save it, then restore it in your new instalation?
