### ISSUE TITLE
🐛 Bug Report: Function execution queues fill up and just disappear

### ISSUE THREAD

**Issue by alibekissakul** [appwrite/appwrite#3903]
### 👟 Reproduction steps

Make a function with 30-40 document update/create operations in one execution.
Run this function multiple times, for example 30 times in a loop.

### 👍 Expected behavior

All created executions must be executed.

### 👎 Actual Behavior

After a while, all pending execution gets stuck in the pending status. And before that, the queue named: `v1-functions` will disappear from the tab workers in the resque-web interface. I am using version 0.15.3.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

I use with my local machine: macbook pro m1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by alibekissakul** [comment]
![image](https://user-images.githubusercontent.com/8822731/191738386-310611c2-b53f-4db8-8a2f-117e4037d72a.png)

**Comment by stnguyen90** [comment]
@alibekissakul, thanks for raising this issue! 🙏 Could you please provide the `appwrite-worker-functions` and `redis` logs after this incident? In addition, would you please provide the status of the docker containers (`docker ps`) after this incident?

**Comment by alibekissakul** [comment]
Unfortunately, the logs are very large and there by the keywords: `error, fail, stop` does not find anything

And no dosker containers crash either, I checked for several functions the same thing all the time, it crashes due to a larger number of tasks in the queue: v1-functions

**Comment by alibekissakul** [comment]
![image](https://user-images.githubusercontent.com/8822731/191890167-50548493-135f-4c92-80ad-521ff1e1d5fc.png)
My docker settings
