### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID On Console Login

### ISSUE THREAD

**Issue by eladcandroid** [appwrite/appwrite#391]
AppWrite version 0.6.2

![Screen Shot 2020-06-08 at 14 58 14](https://user-images.githubusercontent.com/13297000/84027966-89c91000-a998-11ea-84f1-72d20e40523a.png)

**Comment by TorstenDittmann** [comment]
I doubt that SSL is supported on localhost.

Try replacing `https://` with `http://`.

**Comment by eldadfux** [comment]
Hey Elad, on localhost you can't have a valid SSL certificate. We use a default self-signed cert to allow you to use HTTPS when in dev mode. You can **safely** click 'Proceed to localhost (unsafe)' when in dev mode.

When using Appwrite in production with a valid public domain, a valid SSL certificates will be auto-generated 30 seconds from startup. (and will renew automatically every 60 days).

**Comment by eladcandroid** [comment]
Thanks for the quickly response!
