### ISSUE TITLE
🐛 Bug Report: Invalid Queries Causes 500 Error

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#3914]
### 👟 Reproduction steps

1. Make an API call with an invalid queries like: `GET v1/users?queries=100`.

### 👍 Expected behavior

400 error response with some helpful message

### 👎 Actual Behavior

500 server error

appwrite logs:

```
appwrite                        | Warning: foreach() argument must be of type array|object, string given in /usr/src/code/src/Appwrite/Utopia/Database/Validator/Queries.php on line 56
appwrite                        | [Error] Timestamp: 2022-09-23T16:09:33+00:00
appwrite                        | [Error] Method: GET
appwrite                        | [Error] URL: /v1/users
appwrite                        | [Error] Type: TypeError
appwrite                        | [Error] Message: {closure}(): Argument #1 ($queries) must be of type array, string given, called in /usr/src/code/vendor/utopia-php/framework/src/App.php on line 558
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/users.php
appwrite                        | [Error] Line: 366
```

It would be good to check `$value` before iterating over it:

https://github.com/appwrite/appwrite/blob/384543c553f01ac889790042693136b4bfbd80f7/src/Appwrite/Utopia/Database/Validator/Queries.php#L56

We should also have test cases to cover this scenario:

https://github.com/appwrite/appwrite/blob/384543c553f01ac889790042693136b4bfbd80f7/tests/unit/Utopia/Database/Validator/QueriesTest.php#L54

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite Version 1.0.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rahmat-st** [comment]
can I try to fix this issue?

**Comment by techytushar** [comment]
Hey @stnguyen90 @gewenyu99,
I would like to fix this, please can you assign this to me

**Comment by stnguyen90** [comment]
@techytushar, thanks for your interest in contributing! 🙏 Because this issue is a https://github.com/appwrite/appwrite/labels/hacktoberfest issue, we won't be assigning this yet; it will be assigned to the first to comment once Hacktoberfest starts.

**Comment by KKVANONYMOUS** [comment]
@stnguyen90 @gewenyu99  I would like to work on this issue. Please assign it to me.

**Comment by stnguyen90** [comment]
@KKVANONYMOUS, thanks for your interest! 🙏 Good luck!

**Comment by himanshu007-creator** [comment]
Hey!, if @KKVANONYMOUS  is not working on this, i would liek to take this up

**Comment by stnguyen90** [comment]
@KKVANONYMOUS, how's your progress on this? Would you like to continue working on this?

**Comment by KKVANONYMOUS** [comment]
Hey @stnguyen90 
Currently, I am involved in some other work and thus will not be able to go forward with it. 
Sorry for the delay
You can assign it to @himanshu007-creator

**Comment by stnguyen90** [comment]
@KKVANONYMOUS, thanks for the update!

@himanshu007-creator, I'll assign the issue to you. Thanks!

**Comment by stnguyen90** [comment]
@himanshu007-creator, what's your progress? FYI, I'll need to unassign you due to inactivity soon.

**Comment by nick2432** [comment]
can i work on this issue

**Comment by stgeer** [comment]
Keen to contribute and learn if you want to assign this to me 👍

**Comment by Vishalk91-4** [comment]
@Haimantika, could you please assign this issue to me

**Comment by Haimantika** [comment]
> @Haimantika, could you please assign this issue to me



> can i work on this issue

Hi, are you still interested to contribute?

**Comment by Vishalk91-4** [comment]
> > @Haimantika, could you please assign this issue to me
> 
> Hi, are you still interested to contribute?

Yes, I am

**Comment by Haimantika** [comment]
> > > @Haimantika, could you please assign this issue to me
> > 
> > 
> > Hi, are you still interested to contribute?
> 
> Yes, I am

Hi, we assign first-come first-serve basis.

**Comment by tessamero** [comment]
hi @nick2432, I have recently assigned you to 2 other issues, once you've completed at least one of those, I'm happy to assign you to another issue

hi @stgeer , you've been assigned to the issue. You may now start working on this. :-) Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by 0xchikku** [comment]
If it gets unassigned, can i take it up?

**Comment by gewenyu99** [comment]
> If it gets unassigned, can i take it up?

The issues are assigned first come, first serve. If the other contributors become idle, it will go to you!

**Comment by utsavbhattarai007** [comment]
Hi, would it get pass to me? If others cobtributors are idle

**Comment by RohanSharma4792** [comment]
Hey..i would like to contribute to this one

**Comment by Haimantika** [comment]
Hi @utsavbhattarai007 @RohanSharma4792  we are assigning issues on a first-come, first-serve basis, if @stgeer decides to drop , we will assign it to you.

**Comment by aoamusat** [comment]
Kindly assign to me when anyone decides to drop it

**Comment by Abhi132004** [comment]
Hii appwrite team, I would like to work on this task

**Comment by Haimantika** [comment]
Hi @stgeer is there an update? It has been 4 days since we assigned this issue to you, we will assign it to the next person in queue in a few hours if you are not working on it.

**Comment by RahulmalhotraXGIT** [comment]
Hey @Haimantika I would like to work on this,Can you assign this to me?

**Comment by Haimantika** [comment]
Hi @0xchikku assigning the issue to you now. Please remember to share update every 3 days

**Comment by 0xchikku** [comment]
@Haimantika Can you please re-assign to someone else, as am working on other things. Thanks

**Comment by aoamusat** [comment]
I'd like to work on this. Kindly assign to me

**Comment by gewenyu99** [comment]
@Abhi132004 you're next in line, are you still interested?

**Comment by Abhi132004** [comment]
@gewenyu99 , yes you can assign to me.
Basically, the issue is from line 54 to 64 right?https://github.com/appwrite/appwrite/blob/384543c553f01ac889790042693136b4bfbd80f7/tests/unit/Utopia/Database/Validator/QueriesTest.php#L54

**Comment by gewenyu99** [comment]
@Abhi132004 There are two parts. 1 to fixed the invalid query error causing a 500 (invalid user input is a 400), and 2 to add a test to Appwrite to test for this scenario in the future.

**Comment by Smartmind12** [comment]
Can I work on this issue if there is no current activity on it!?

**Comment by ShivamBisen** [comment]
hey i would like to work on this issue

**Comment by AnanyaJindal1145** [comment]
Hi! Can I be assigned this issue?

**Comment by JAkrish29** [comment]
Hi! Can I be assigned with this issue ??

**Comment by tessamero** [comment]
I removed the hacktoberfest label but keeping this issue open since it's a bug. Thank you to everyone who participated this year :) 

If anyone wants to work on this issue, you can reply after this message since hacktoberfest is now over. :)

**Comment by jaysomani** [comment]
Hello,

I've reviewed the issue and noticed that the error is occurring when attempting to iterate over a non-array or non-object value in the `Queries.php` file. To address this, I propose adding a check at the beginning of the `foreach` loop to ensure that the given query is an array or object. If it's not, we can return a 400 error response with a meaningful message.

Am I correct ?

**Comment by jaysomani** [comment]
can i work on this ? @Haimantika

**Comment by stnguyen90** [comment]
Looks like this has already been fixed:

<img width="993" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/4459f0e9-48a7-4af0-9bc8-679a25124dd1">
