### ISSUE TITLE
🐛 Bug Report: Incorrect Realtime Payload when Deleting Session from Console

### ISSUE THREAD

**Issue by IsaiChristian** [appwrite/appwrite#3916]
### 👟 Reproduction steps
0. Start a windows app with flutter and appwrite.
1. Subscribe to account channel
2. Close session from the console.     

### 👍 Expected behavior

recieve an event similar to this: 
`RealtimeMessage(events: [users.632c04c86d545378bf29.update, users.*.update, users.632c04c86d545378bf29.update.name, users.*.update.name, users.632c04c86d545378bf29, users.*], payload: {$id: 632c04c86d545378bf29, $createdAt: 2022-09-22T06:46:33.091+00:00, $updatedAt: 2022-09-22T20:21:58.993+00:00, name: usuario pruebas, password: $argon2id$v=19$m=65536,t=4,p=3$Unl6aS9xTWcyQ1hKSWs4Tg$qJrXxeTc+OzSHX86i7gfLkdbCzSRHixAh7RGSaI6IpQ, hash: argon2, hashOptions: {memoryCost: 2048, timeCost: 4, threads: 3}, registration: 2022-09-22T06:46:33.090+00:00, status: true, passwordUpdate: 2022-09-22T06:46:33.090+00:00, email: usuario@prueba.com, phone: +1231231231, emailVerification: false, phoneVerification: false, prefs: []}, channels: [account, account.632c04c86d545378bf29], timestamp: 2022-09-22 20:21:59.020)
`

### 👎 Actual Behavior

Breaks :( 

` [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>' `

Error is in this File : from this : this file package:appwrite/src/realtime_message.dart:42.
![unknown](https://user-images.githubusercontent.com/2268156/192039684-e102eaa8-cec3-4302-8254-e5e04edc543b.png)
This is the response from the server:
![unknown](https://user-images.githubusercontent.com/2268156/192039835-aff3e342-64fe-4991-a0ac-00c36dcb69e0.png)

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I have it behind an Nginx Proxy Manager.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks, @IsaiChristian, for creating this issue! 🙏 It seems like the empty payload is being sent from the server as an empty array rather than empty object. We'll look into this as soon as we can!

**Comment by geisterfurz007** [comment]
This sounds interesting; would you mind if I had a look at this? And if I may, could you give me a rough pointer as to where to look for this?

**Comment by stnguyen90** [comment]
@geisterfurz007, thanks for the interest! 🙏 Assigned!
