### ISSUE TITLE
📚 Documentation: Bug in switching version for Database documentations

### ISSUE THREAD

**Issue by AhmedHammad0900** [appwrite/appwrite#3919]
### 💭 Description

When u try to choose older version in Database documention then try to change the Sdk type from web to another one , it forces u to back to 1.0 again , there is a small video shows excatly the problem 

- Tried another explorer than chrome , deleted cookies , the problem from current site version , Works well for other documentations only Databases

https://user-images.githubusercontent.com/81931290/192092767-0a82da77-3273-48b9-9f73-e29330c0f195.mp4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
Hey @AhmedHammad0900 Thanks for raising this. @PineappleIOnic will take a look at this
