### ISSUE TITLE
🚀 Feature: Improve Missing Redirect URL Page for Mobile

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#3930]
### 🔖 Feature description

For mobile apps, the default [oauth2](https://github.com/appwrite/appwrite/blob/master/app/views/home/auth/oauth2.phtml) page is used to redirect the user back to the mobile app via the `appwrite-callback-[PROJECT-ID]` URL scheme. The only problem is the Missing Redirect URL page is still shown and visible which can be confusing/annoying to users. It would be nice if the page closes automatically.

### 🎤 Pitch

Closing the page automatically would make the flow less confusing and clean up tabs/windows no longer needed. Either that or show a page that says "You may close this page now"

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by FernandoUFS** [comment]
For me, not only the page is still open as it redirects back to do a new login on google, even after the log has been executed.
```
final account = Account(_client); 
await account.createOAuth2Session(
  provider: 'google',      
);
final accountInfo = await account.get();
log('Login done: ' + accountInfo.toMap().toString()); // this code executes right after a successfully login. But the web page is still open
```

My AndroidManifest.xml has already the setup:
```
<activity android:name="com.linusu.flutter_web_auth_2.CallbackActivity" android:exported="true">
            <intent-filter android:label="flutter_web_auth_2">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="appwrite-callback-63f..............0" />
            </intent-filter>
        </activity>        
```

**Comment by stnguyen90** [comment]
> For me, not only the page is still open as it redirects back to do a new login on google, even after the log has been executed.

@FernandoUFS, it seems you're facing a different problem. Please join us on [Discord](https://appwrite.io/discord) if you need help troubleshooting.

**Comment by Kings-Samuel** [comment]
Any updates to this issue here yet? Just checking

**Comment by leonardodincalci** [comment]
I also have the problem of missing url error like a flash. Besides this, Can anyone tell me why the value of the variable **_session_** is null? The code works, I can log in but the variable remains null.

```
    @override
  FutureEither<model.Session> loginWithGoogle(
  ) async {
    try {
      final session = await _account.createOAuth2Session(
        provider: 'google',
        success: "",
        failure: "",
      );
      debugPrint(session);
      return right(session);
    } on AppwriteException catch (e, stackTrace) {
      return left(
        Failure(e.message ?? 'Some unexpected error occurred', stackTrace),
      );
    } catch (e, stackTrace) {
      return left(
        Failure(e.toString(), stackTrace),
      );
    }
  }
```

**Comment by stnguyen90** [comment]
I've been doing some testing and I'm slightly concerned about auto-closing the window/tab because it would trigger a user-canceled exception.
