### ISSUE TITLE
🚀 Feature: STDOUT function logging

### ISSUE THREAD

**Issue by maikeriva** [appwrite/appwrite#3934]
### 🔖 Feature description

You should add STDOUT logs in the web console function log pages. Not having it makes hard if not impossible to troubleshoot more complicated functions, as there is no way to observe the actual logic execution path. 

### 🎤 Pitch

In my use case, I have a function which builds images according to a "recipe" it receives as input. Recipes can be fairly complicated, and I often need to carefully observe the build logic is executed correctly. To do this, I print log statements when the logic branches, but I have no way to read them when executing the function into the appwrite executor.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
Hey @maikeriva We will enable the logs soon as part of a patch release to 1.0

In the meantime, you can check the `stdout` from the developer console in the response to the `listExecutions` request as shown in the attached image

![image](https://user-images.githubusercontent.com/20852629/192526188-1ffba8e3-aa31-49a7-a74e-0660e0fd81bc.png)
