### ISSUE TITLE
[1.0.1.500] 🐛 Bug Report: Error on Query.equal("feature_type", 0)

### ISSUE THREAD

**Issue by kobeumut** [appwrite/appwrite#3942]
### 👟 Reproduction steps

Make an db call with an python sdk like;
<img width="867" alt="image" src="https://user-images.githubusercontent.com/5182289/192852651-643da2d4-7dd5-45f0-876b-089b5b2841f5.png">
It's related with 0 in Query.equal("feature_type", 0)
When I changed the 0 to 1 or 2 the response came or when I create query with notEqual
```
query = Query.notEqual("feature_type", 1)
query1 = Query.notEqual('feature_type', 2)
```
it's running. But I want to get feature type which is 0

### 👍 Expected behavior

Successfull response with query's value equal to 0

### 👎 Actual Behavior

I got an exception
```{"message":"Error: Server Error","code":500,"version":"1.0.1"}```
and docker log is below
```
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 610
```

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use digitalocean 8x4 server. My python sdk is 1.0.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Hi @kobeumut! Thanks for raising this issue! 🙏 This looks like a duplicate of https://github.com/appwrite/appwrite/issues/3926. Can we close this and you can 👍 the previous issue?

As a workaround before we push out the release, you can try using this string instead:

```python
'equal("feature_type", 0)'
```

**Comment by kobeumut** [comment]
Hi @stnguyen90. Sorry about duplicate, I searched but overlooked.

But I can't understand using it with the string you mentioned?

**Comment by stnguyen90** [comment]
@kobeumut for example:

```python
queries = ['equal("feature_type", 0)', Query.limit(limit), Query.offset(limit * self.page)]
```

or

```python
queries = [f'equal("feature_type", {feature_type})', Query.limit(limit), Query.offset(limit * self.page)]
```

**Comment by kobeumut** [comment]
oh, I got it. I don't now this kind of usage. Thank you.
