### ISSUE TITLE
📚 Documentation: List JSON Examples Are Incorrect

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#3943]
### 💭 Description

Lists like Documents List or Memberships List should have an array of data, but the examples don't show that. For example:

Teams List:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/1477010/192867361-bf2be143-054d-40b5-b919-d379a38c6baf.png">

Documents List:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/1477010/192867404-c5b3f039-bc87-4983-8be4-7258bf26198f.png">

Memberships List:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/1477010/192867452-c002817b-9eee-4ac5-b856-1a9505f86c61.png">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by michizhou** [comment]
Hi @stnguyen90, would it be alright if I take on this issue?

**Comment by stnguyen90** [comment]
@michizhou, have you looked into how to fix this?

**Comment by michizhou** [comment]
@stnguyen90 I have not and have decided to not get involved with this issue. Instead I'll leave it to the core team to handle given that there's no way for me to validate changes on my end.

**Comment by gewenyu99** [comment]
@stnguyen90 Are these autogenerated?

**Comment by stnguyen90** [comment]
@gewenyu99, yes I believe so based on the specs probably?
