### ISSUE TITLE
🐛 Bug Report: `0Auth` not working with `Safari`

### ISSUE THREAD

**Issue by Faizan-Pasha** [appwrite/appwrite#3946]
### 👟 Reproduction steps

Hi, I am using `React` to build a web app.
 `Authentication` returns `status code 200` but while getting the user with `account.get()` method it returns `AppwriteException: User (role: guests) missing scope (account)`. I think `APPWRITE` is having some errors storing the `login` values in `Local Storage`.
This is only with `Safari`, I tested the same code with `Chrome` and it works fine.
On my mobile, I had the same issue with safari.
 
`NPM` package version `"appwrite": "^10.1.0"`

### My code
```
const handleGoogleLogin = async (e: any) => {
		e.preventDefault();
		try {
			const promise = account.createOAuth2Session(
				'google',
				'http://localhost:3000/account',
				'http://localhost:3000/login',
			);
			console.log(promise);
		} catch (e) {
			console.log(e);
		}
	};
```

In the `APPWRITE` console it is showing that the user is loggedin
![Screenshot 2022-09-29 at 8 00 29 AM](https://user-images.githubusercontent.com/32414659/192925264-c72a8657-7b66-4f3b-9fa1-c289b8396171.png)

### 👍 Expected behavior

It should have stored the user details in `Local Storage`.

### 👎 Actual Behavior

returned `AppwriteException: User (role: guests) missing scope (account)`.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Faizan-Pasha, thanks for raising this issue! 🙏 

Would you please clarify where you are calling `account.get()`?

As for why this happens, OAuth session cannot be stored in local storage. It must be done with cookies and some browsers are stricter with 3rd party cookies than others. For OAuth, it is best to ensure you're using 1st party cookies by having your app and the Appwrite endpoint have the same base URL. In addition, cookies may not work properly when using localhost.

**Comment by Faizan-Pasha** [comment]
@stnguyen90 
Sorry to bother you.
I was using Apple's private relay(VPN service for safari browser) and my web platform host was configured only for my IP.😅
