### ISSUE TITLE
🐛 Bug Report: missing activity data in authentication

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#3949]
### 👟 Reproduction steps

it seems in new "Authentication" screen of appwrite console there are missing activity timestamps.

i think data from before migration is missing at all, and data after migration is wrong:
![image](https://user-images.githubusercontent.com/17125438/193008436-6b708ae2-ea11-443d-8f57-627531e89cc0.png)
(all timestamps are from 1970)

same with activity log of "Teams".

### 👍 Expected behavior

should show correct values

### 👎 Actual Behavior

shows nothing or shows timestamps from 1970

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@s3ppo, could these have been from before the timestamp was introduced? Do you know what these should have looked like before the upgrade? Also, what's the API return?

**Comment by s3ppo** [comment]
![image](https://user-images.githubusercontent.com/17125438/193041860-4fbc671b-94df-47b3-9a1d-40ad96a515ca.png)

**Comment by s3ppo** [comment]
Do i have to run migration again when 1.0.2 is released?

**Comment by stnguyen90** [comment]
> Do i have to run migration again when 1.0.2 is released?

@s3ppo, yes, you will have to run the migration again.
