### ISSUE TITLE
New database rule types

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#395]
We want to support more rule types to allow more flexibly, security, convenience and data integrity when using Appwrite Database API. Please add any rules date you might find general enough for being implemented the Appwrite Database.

For start

- [ ] Integer Rule - Rule for attributes that only accept integers
- [ ] Float Rule - Rule for attributes that only accept floats
- [ ] File ID - Validates a file ID is a valid project file, shows file preview + search window in the Database UI
- [ ] User ID - Validates a user ID is a valid project user, shows user preview + search window in the Database UI
- [ ] Date - Validated date as a unix timestamp, add a nice UI for selecting dates directly in the console, filtering and ordering should work the same as for integers
- [ ] Datetime - Validated date as a unix timestamp, add a nice UI for selecting dates directly in the console, filtering and ordering should work the same as for integers
- [ ] GeoPoint / GeoJSON - Validate GEO data and allow to query/sort data by radius/distance - maybe have a nice map UI to show the data inside the Appwrite console.

**Comment by eldadfux** [comment]
File preview example:
![image](https://user-images.githubusercontent.com/1297371/84223873-bfc6db00-aae3-11ea-8c1c-bbef3b79bb2b.png)

**Comment by eldadfux** [comment]
File search examples:
![image](https://user-images.githubusercontent.com/1297371/84223916-dec56d00-aae3-11ea-9987-03ad1b322464.png)

**Comment by drandell** [comment]
@eldadfux would float and integer then deprecate the current numeric rule type? I cant think of any reason to keep after introducing those new types

**Comment by punitdiwan** [comment]
@eldadfux and all team members, I would like to suggest a JSON Rule type which accepts valid JSON document. It will have text area which allows to enter JSON. On getting out of focus, it should validates JSON, if valid, will show a message that "**JSON is Valid**" with Green Color and if invalid, will show error message with red color. Valid JSON document can be saved.

This will be different from Nested Document Rule type as Nested Document is actually refers to document from other collection.

What do you say guys? What is the opinion of others. It may have some use cases and above all, will bring lot of flexibility. 

Regards,
Punit Diwan

**Comment by eldadfux** [comment]
> @eldadfux would float and integer then deprecate the current numeric rule type? I cant think of any reason to keep after introducing those new types

I think you have a good point there, what should we do in that case with existing data during upgrade/data migration? convert it to a wildcard? disable it for new collections?

**Comment by eldadfux** [comment]
> @eldadfux and all team members, I would like to suggest a JSON Rule type which accepts valid JSON document. It will have text area which allows to enter JSON. On getting out of focus, it should validates JSON, if valid, will show a message that "**JSON is Valid**" with Green Color and if invalid, will show error message with red color. Valid JSON document can be saved.
> 
> This will be different from Nested Document Rule type as Nested Document is actually refers to document from other collection.
> 
> What do you say guys? What is the opinion of others. It may have some use cases and above all, will bring lot of flexibility.
> 
> Regards,
> Punit Diwan

This would add a lot of flexibility, but might not allow us to add GraphQL support, because GraphQL only accept type safe and predefined structured data both for request and response.

**Comment by drandell** [comment]
> > @eldadfux would float and integer then deprecate the current numeric rule type? I cant think of any reason to keep after introducing those new types
> 
> I think you have a good point there, what should we do in that case with existing data during upgrade/data migration? convert it to a wildcard? disable it for new collections?

I think convert to a wildcard with information on the release (when it goes live) is a good shout.

**Comment by peopledrivemecrazy** [comment]
Auto increment ID - Sets unique field `id` and discovery by `id` inside a collection.

**Comment by danibjor** [comment]
GeoPoint (lat,long)

**Comment by peopledrivemecrazy** [comment]
> GeoPoint (lat,long)

Do you mean GeoJSON?

**Comment by danibjor** [comment]
> > GeoPoint (lat,long)
> 
> Do you mean GeoJSON?

Didn’t, but that’s probably even better.

**Comment by eldadfux** [comment]
@danibjor, @peopledrivemecrazy, I have updated the list :)

**Comment by auliabismar** [comment]
I suggest unique column constraint if not already in other open issue post

**Comment by Harpune** [comment]
It would be good to have a recursive structure, so documents can contain documents of the same collection-type. There is only the possiblity to select different collections.

_Note_: I already needed this feature and created a workaround by using wildcards. And to my surprise, the created documents where listed in the collection overview as documents. The json of the wildcard contained the collection-id so maybe thats how it got mapped to the collection.

**Comment by mlucas-NU** [comment]
Has there been any discussion on special handling for common "meta" rules? There was a brief discussion this week on the Appwrite discord about how to manage `created_at` and `updated_at` rules in a collection. From what I can tell, there are two options:
* Allow the client to set/update these values with the standard document POST/PATCH endpoints. This works well if the application doesn't rely on the accuracy of these fields and users don't gain any benefit by manipulating them.
* Create two functions, one for document creation and one for document updates. These functions would accept all fields except `created_at` and `updated_at` as parameters and the function would take care of these two fields server-side. This is useful when we need these fields to be accurate or when users have incentives to manipulate them.

These two specific fields are frequently added to database schemas, so this led me to wonder if Appwrite could have a special way of handling them without having to add 2 Functions to every Database. For example, it would be cool to have a checkbox for each "meta" rule on the Database Settings page. If you toggle `created_at` on, it adds the rule to the collection and manages it exactly as we expect it to (set the value to the current time when a document is added and never let the value be manipulated).

**Comment by TorstenDittmann** [comment]
Considering the new Database Service this issue looks obsolete - closing this for now in favor of single issues for potential attribute.
