### ISSUE TITLE
[Bug] German Umlaute encoding in email subject

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#404]
German Umlaute like ä,ö,ü are not encoded correctly in the email subjects.

Result
`Passwort zurÃ¼cksetzen`
Expected
`Passwort zurücksetzen`

I can make a fix as part of #402

**Comment by TorstenDittmann** [comment]
Is fixed with #402 👍

**Comment by eldadfux** [comment]
This fix is now available on Appwrite 0.7! 🥳
