### ISSUE TITLE
🚀 Feature: 

### ISSUE THREAD

**Issue by dafavio** [appwrite/appwrite#4049]
### 🔖 Feature description

บทบาทสำหรับผู้ใช้ทั่วโลก

### 🎤 Pitch

ตรวจสอบรหัส

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@dafavio, could you please update the issue title and use English to make it easier for others to read?
