### ISSUE TITLE
Reference Private Package in Functions

### ISSUE THREAD

**Issue by r-dev-limited** [appwrite/appwrite#4054]
How to reference private packages in functions. This is generic question, even though I am interested in dart packages, I think this issue is related to all runtimes. 

As I dont see way of passing credentials (SSH) or install custom plugins and pass ENV variables to function containers.
Even if I update docker-compose for appwrite itself, it does not affect functions.

As those spins their own containers from open runtime repo.

So whats the plan for this ? 

https://github.com/appwrite/appwrite/issues/3207

**Comment by stnguyen90** [comment]
@r-dev-limited whats the difference between this issue and https://github.com/appwrite/appwrite/issues/3207? Can this be closed and you can 👍 the previous issue?

**Comment by r-dev-limited** [comment]
That one is feature request, after release of 1.0, thats is more like a bug now. I dont see it being even mentioned, I can partially understand it for dart functions, its not as common. But node, there are plenty private packages / private forks.

**Comment by stnguyen90** [comment]
@r-dev-limited I think the idea is to support private dependencies in general. Can this be closed and you can 👍 the previous issue?
