### ISSUE TITLE
🐛 Bug Report: Please help me debugging why realtime is not triggering

### ISSUE THREAD

**Issue by myThorsten** [appwrite/appwrite#4059]
### 👟 Reproduction steps

I am building a Flutter-app. User authentication is working fine. However, realtime-subscription is not. As far as I can tell I have set up my project according to the docs. 

Here is the realtime:
![image](https://user-images.githubusercontent.com/9773490/193529438-2b957bfe-1cd8-44b7-8cba-eb65d34a475e.png)
which is not triggering on any of these channels in my tests. I modify documents as the owner of the project.

The Realtime gets injected using riverpod:
![image](https://user-images.githubusercontent.com/9773490/193529667-294ea50a-d37f-4cc7-a487-f35ed1b2054d.png)
Since authentication is working the apiEndpoint and projectId should be fine.

I get this when starting the subscription:
![image](https://user-images.githubusercontent.com/9773490/193530907-6ffbcbc9-f115-4801-b641-c79f027af8f7.png)

The collections have these permissions:
![image](https://user-images.githubusercontent.com/9773490/193530533-71f77600-09bf-41d2-bfc8-068e2686a493.png)

I want to mention that I do get strange exceptions when I set **selfSigned of client to false** which I find odd. Here is my appwrite installation:
https://treffer-technologies-backend.feste-ip.net/
which has, as you can see, a certificate from lets-encrypt. The server is in my home behind a DS-Lite connection. I use feste-ip.net to map through that and afaik feste-ip.net uses their own letsencrypt which might be a problem.

The strange exception I get when setting selfSigned to false:
![image](https://user-images.githubusercontent.com/9773490/193531678-e6c0c225-bc57-4061-b1a5-6aa967a7d6e8.png)

I have set appwrite to development-mode but couldn't find eye-catching errors in the logs. Here is **docker logs appwrite-realtime**
![image](https://user-images.githubusercontent.com/9773490/193532258-7e96c23e-5329-4d32-8b0c-56a79e8f7580.png)
Here is **docker logs appwrite**:
![image](https://user-images.githubusercontent.com/9773490/193532383-857616d6-c59f-4916-a8bc-0261b27e6fec.png)

### 👍 Expected behavior

Subscription gets notified

### 👎 Actual Behavior

No reaction inside Flutter whatsoever

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Server not on a cloud-provider but at home behind DS-Lite. Accesible by the internet via IPv6 Portmapper from feste-ip.net.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@myThorsten, a few questions:

1. Do you have a reverse proxy in front of Appwrite?
2. Is your Appwrite instance still online? I get a 502 error trying to hit the URL you shared
3. Anything in the appwrite-realtime container logs?
4. If you call `databases.listDocuments()` do documents get returned? When you update one of those documents that gets returned, does the subscription output anything?
5. Are you subscribing after creating a session?

**Comment by myThorsten** [comment]
@stnguyen90 , thank you for your time.

1. I do not, but I am pretty sure that feste-ip.net has one, which I have no controll over.
2. My little mini-pc isn't running 24/7, I turn it off over night (I'm located in Germany). Since you commented 5 hours ago, I and my server were sound asleep :)
3. Just a bunch of **Connection close**.
![image](https://user-images.githubusercontent.com/9773490/194011750-14d830f8-2903-4633-ba88-232dbf7aa3c9.png)
I noticed that the number keeps growing unexpectedly with no correlation to my app. As if I am watching the wrong log. Is this correct?: **docker logs appwrite-realtime --follow**
4. Yes, databases.listDocuments() works flawlessly. Updating one of those documents does not trigger the subscription. Neither my breakpoint nor the print() inside the subscription.stream.listen().
5. Yes, after createEmailSession().

**Comment by myThorsten** [comment]
As a side note, I am glad to leave my server running over night if that helps. Just let me know. 
I would appreciate any tipps.

**Comment by stnguyen90** [comment]
@myThorsten, you should check with feste-ip.net to see if web sockets are enabled on their reverse proxy. Another thing to make sure is that traffic gets to Appwrite as https rather than http.

**Comment by myThorsten** [comment]
I can no longer reproduce the problem. Don't ask me what the problem was :(
