### ISSUE TITLE
[HELP-WANTED] Adding Support for More OAuth Providers

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#410]
New issue to replace #5 . Help us add new OAuth providers for Appwrite authentication. Adding a new OAuth provider is pretty simple and can be a great way to start adding contributions to the project. We have created a step by step guide to add a new adapter, and you can ask for support here or on our Discord server #maintainers channel (https://discord.gg/GSeTUeA).

Tutorial available here:
https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-oauth2-provider.md

- [x] Amazon
- [x] Apple
- [x] Bitbucket
- [x] Bitly
- [x] Discord
- [x] Dropbox
- [x] Facebook
- [x] GitHub
- [x] GitLab
- [x] Google
- [x] Linkedin
- [x] Microsoft
- [x] PayPal
- [x] SalesForce
- [x] Slack
- [x] Spotify
- [x] Twitch
- [x] VK
- [x] Yahoo
- [x] Yandex
- [ ] Baidu
- [x] Box
- [ ] Evernote
- [ ] Fitbit - **in progress (@NidhxGupta)**
- [x] PayPal Sandbox (Should extend the current PayPal provider...)
- [x] Wordpress (@rsneh)
- [ ] Weibo
- [x] Yammer
- [ ] Mail.ru
- [ ] Reddit (Reddit has some technical difficulties since their API doesn't return an email ID or a UUID or a full name, which we require) 
- [ ] Twitter (Not supporting OAuth2 yet)
- [ ] Instagram (Instagram has some technical difficulties since their API doesn't return an email ID, which we require) 
- [ ] Steam
- [ ] Zoho
- [x] Stripe
- [ ] Imgur
- [ ] Disqus
- [ ] Netflix
- [ ] Telegram

**Comment by komemi** [comment]
@eldadfux is someone assigned to wordpress api?

**Comment by eldadfux** [comment]
@komemi you are :) congratz 😅

**Comment by eldadfux** [comment]
Box OAuth adapter has been merged! Great work @armino-dev #467

**Comment by armino-dev** [comment]
Thanks @eldadfux, you guys are moving fast. I see a lot of improvements every day. 😄

**Comment by eldadfux** [comment]
@armino-dev a lot thanks to amazing contributors like you ❤️

**Comment by eldadfux** [comment]
I have added a new 'name' attributes in the providers config file to have better representation of providers names inside the Appwrite console.

![image](https://user-images.githubusercontent.com/1297371/86637609-85673580-bfde-11ea-876c-23352f7d2589.png)

**Comment by PineappleIOnic** [comment]
Any chance we could add steam to the list? As I've got quite alot of experience with the steam web API from previous projects and will be happy to add it.

**Comment by eldadfux** [comment]
@PineappleIOnic I have added Steam to the list, all the info on adding a new OAuth adapter is listed in the tutorial linked in the first message. Feel free to reach out if you have any question.

**Comment by PineappleIOnic** [comment]
After looking into it it seems that steam removed the OAuth authentication for some reason they only seem to have OpenID authentication open now.

**Comment by NidhxGupta** [comment]
Hey @eldadfux, I would like to work on the Fitbit OAuth provider, could you please assign the same to me? Thanks!

**Comment by eldadfux** [comment]
@NidhxGupta you have been assigned to the Fitbit provider. Please feel free to reach out on our #maintainers channel on https://appwrite.io/discord if you need any help.

You can also use previous PR by other members on this issue as a reference point.

**Comment by rsneh** [comment]
Hi @eldadfux, I saw that the WordPress provider was missing.

**Comment by rsneh** [comment]
And regarding Twitter, it looks like they are supporting OAuth2
https://developer.twitter.com/en/docs/authentication/oauth-2-0

I'll check that out tomorrow.

**Comment by eldadfux** [comment]
@rsneh last time we checked Twitter only supported OAuth2 for app and not user scope. Please let me know if that isn't the case anymore.

**Comment by rsneh** [comment]
@eldadfux I know what you mean... I've played with that a bit today.
I do think this is still the case with Twitter.
"Sign in with Twitter" is still supporting only OAuth1.

From https://developer.twitter.com/en/docs/authentication/guides/log-in-with-twitter
> This page assumes that the reader knows how to sign requests using the OAuth 1.0a protocol. If you want to know how to sign a request, read the Authorizing a request page.

**Comment by aloks98** [comment]
@eldadfux I have checked fitbit docs and it doesn't return email. I am looking into other solutions if I can implement something!

**Comment by payne8** [comment]
I think it would make sense to have a generic OAuth2 implementation, or an OpenID Connect implementation (a superset of OAuth2 that includes standardized user info). Once you have the standard ones in place the provider specific ones take way less time because you just have to add their endpoints (assuming the provider follows the standard).

**Comment by SoftCreatR** [comment]
I'll add my own OAuth provider. The service/provider itself is currently in progress, but it works already and integrations for other systems (Laravel Socialite, Xenforo & WoltLab Suite) already exist, so why not add Appwrite to the list :)

**Comment by hack3r-0m** [comment]
please assign me Evernote if it is still left

**Comment by Glide7** [comment]
@hack3r-0m assigned you :) Please let me know if you need help!

**Comment by hack3r-0m** [comment]
since Evernote uses Thrift-based API (and not REST, so they have only SDKs and no endpoints) and doesn't support Oauth2 at the time of writing, it is not feasible to integrate (unless using sdk)

**Comment by hack3r-0m** [comment]
Ouath2 support for Zoho, stripe, Imgur, Disqus, Netflix can also be added, please update the list and assign it to me. I am currently working on adding the remaining ones that are feasible (yammer, mail.ru). Fitbit is assigned to someone for a long time, I would like to know if I can take it.

**Comment by Glide7** [comment]
Thanks @hack3r-0m - Since you're already assigned, go ahead! @eldadfux will edit the post so it will add those OAuth providers.
@NidhxGupta - are you still working on FitBit?

**Comment by eldadfux** [comment]
@hack3r-0m added all new providers to the list, looking forward to this PRs 🤩

**Comment by eldadfux** [comment]
After we release v0.8 we will be able to support providers not returning an email or ID (reddit, instagram) and treat them similarly to how we treat anonymous authentication.

**Comment by eldadfux** [comment]
Hey @hack3r-0m are you still interested in working on the Zoho, Stripe, Imgur, Disqus, and Netflix adapters?

**Comment by wemiprog** [comment]
What about the telegram login?
Its not really oauth2 afaik, but not very different to implement I think. Would this be possible?

**Comment by eldadfux** [comment]
> What about the telegram login?
> https://core.telegram.org/widgets/login
> 
> Its not really oauth2 afaik, but not very different to implement I think. Would this be possible?

I'll add it to the list.

**Comment by eldadfux** [comment]
@hack3r-0m are you still interested in working on all those OAuth adapters?

**Comment by hack3r-0m** [comment]
@eldadfux feel free to unassign me from this issue

**Comment by Meldiron** [comment]
Is anyone working on Steam provider? I made multiple CS:GO-related sites, so this shouldn't be a problem for me.

**Comment by TorstenDittmann** [comment]
> Is anyone working on Steam provider? I made multiple CS:GO-related sites, so this shouldn't be a problem for me.

Sadly Steam OAuth doesn't expose the e-mail address, which is needed for our current Authentication Flow right now.

**Comment by Reflex-Gravity** [comment]
Can I take imgur integration?

**Comment by wemiprog** [comment]
Would it be possible for you to make the possibility of a "custom oauth-provider"?
I think would be very helpful, for example  for an own oauth-provider (business-internal, service-internal, or maybe even "fake-oauth" needed for things like steam, telegram, ....

So each could code his oauth provider, and point to his domains instead of third-party.

Needed fields are "redirect to ..."-domain, "checking"-domain, maybe codesnippet-editor, ...

thx for considering

**Comment by liehart** [comment]
Hello, may I add Line Login (it support OAuth2) and try to implement that? Reference https://developers.line.biz/en/reference/line-login/

**Comment by christyjacob4** [comment]
> Would it be possible for you to make the possibility of a "custom oauth-provider"?
> I think would be very helpful, for example for an own oauth-provider (business-internal, service-internal, or maybe even "fake-oauth" needed for things like steam, telegram, ....
> 
> So each could code his oauth provider, and point to his domains instead of third-party.
> 
> Needed fields are "redirect to ..."-domain, "checking"-domain, maybe codesnippet-editor, ...
> 
> thx for considering

@wemiprog  Would be great if you could add your idea as a new issue so that it doesn't get lost in this thread? Please share your thoughts with an example use case as an issue

**Comment by christyjacob4** [comment]
> Hello, may I add Line Login (it support OAuth2) and try to implement that? Reference https://developers.line.biz/en/reference/line-login/

@liehart  Looks like Line doesnt return an email ID in the user profile. This might be a small issue currently as we require email IDs to be returned along with the user profile. We are working on changing this soon. But you can start working on it :+1:

**Comment by nadavl** [comment]
Is possible to add a non-OAuth 2.0 provider such as twitter or are only OAuth 2.0 providers supported?

**Comment by TorstenDittmann** [comment]
> Is possible to add a non-OAuth 2.0 provider such as twitter or are only OAuth 2.0 providers supported?

Right now we are required to obtain an E-Mail from the OAuth Provider to verify a user. We have plans to improve that in the future.

As far as I can remember, Twitter didn't allow or only allows certain apps to obtain it right?

**Comment by nadavl** [comment]
@TorstenDittmann Thanks, got it on the email requirement.
In case I implement the Twitter auth on the client-side (Let's say with React Native), can I create a user and attach the Twitter token as one of the user's properties? (I guess I'll need to somehow generate an email for that user in this case).

**Comment by bigfish258** [comment]
plz add weibo wechat ..

**Comment by upta** [comment]
Just an FYI to those that might be interested, it seems that Twitter finally supports OAuth 2.0 as of mid December.

https://developer.twitter.com/en/docs/authentication/oauth-2-0

**Comment by eldadfux** [comment]
> Just an FYI to those that might be interested, it seems that Twitter finally supports OAuth 2.0 as of mid December.
> 
> https://developer.twitter.com/en/docs/authentication/oauth-2-0

Twitter OAuth 2.0 still supports app-only scope and not the user one, which is the one we need @ Appwrite.

**Comment by matfire** [comment]
if nobody is working on it, I could try and tackle the Imgur provider

**Comment by watzon** [comment]
For telegram one might be able to make use of https://telepass.me and use the same workflow that was used in [passport-telegram](https://www.passportjs.org/packages/passport-telegram/). I'll look into it, because Telegram login is something I really want.

**Comment by watzon** [comment]
With Telegram unfortunately you have to use their "login widget", so I don't know how possible it would be since it isn't using your typical OAuth2 flow. If anyone thinks of something though I would be more than happy to implement it.

**Comment by christyjacob4** [comment]
@matfire , Sure you can go ahead and try Imgur. Please be aware we currently only support OAuth 2 providers that can return an email ID . If the email ID is available on a separate endpoint, that is perfectly fine.

**Comment by christyjacob4** [comment]
@watzon  you're not limited to the list here. The list here is pretty old. So feel free to suggest new OAuth 2.0 providers which you'd be interested to work on :)

**Comment by omia** [comment]
Is it possible to change the GitLab OAuth so it asks for the server address? I need to use a self-hosted GitLab.

**Comment by devcydo** [comment]
Hi! Is anyone working on Zoho provider? If not, can you assign it to me?

**Comment by omia** [comment]
> @omia Heyyy wave Sounds like a reasonable requirement thinking Can you please create GitHub issue (feature request)? I will make sure to pass the issue along, and get it implemented muscle
done: #3292

**Comment by thevinitgupta** [comment]
Is anyone working on the Telegram Authentication? 
I would like to implement that.

**Comment by petteremil** [comment]
Could you add Vipps to the list once you support anything other than email? 
I believe they use phone number as the unique id (you can get the email associated to the account, but I'm unsure if it's guaranteed)

https://github.com/vippsas/vipps-login-api

**Comment by stnguyen90** [comment]
@eldadfux can we close this and use individual issues for specific OAuth providers?

**Comment by stnguyen90** [comment]
Closing this for now. If anyone wants support for a particular provider, please create an issue for that provider.

**Comment by DeveloperVirusly** [comment]
Hello, I would like to work on this. Thank you! :D

**Comment by peter100u** [comment]
Can the community access some China-related social logins? , if WeChat, QQ, Weibo
