### ISSUE TITLE
Clamav_1 Download Failed

### ISSUE THREAD

**Issue by drandell** [appwrite/appwrite#412]
Quite simple to re-create, just take the current docker-compose file and up that without the detach and see the logs consistently spammed with these messages, screenshot below of my git bash. 

![image](https://user-images.githubusercontent.com/393945/84591444-540fa580-ae36-11ea-85cf-1c0b53a2c0e2.png)

**Comment by eldadfux** [comment]
Happens on my instance as well, I'm checking if a new ClamAV version solves this.

**Comment by drandell** [comment]
https://forum.efa-project.org/viewtopic.php?t=4257

I found this. Maybe doing the instructions will fix?

**Comment by eldadfux** [comment]
I'll take a look at that, anyway building a new ClamAV image doesn't seem to help.

**Comment by eldadfux** [comment]
Seems that the container is still working, anyway until we find a solution you can use `_APP_STORAGE_ANTIVIRUS ` env var to disable the virus scanning.

More info available here: https://appwrite.io/docs/environment-variables#general

**Comment by eldadfux** [comment]
@drandell I think I have managed to fix this issue in this commit: https://github.com/appwrite/docker-clamav/commit/ac15834550d1c7f606c02da530ea0b311e52fd32

I have release a new Docker image: appwrite/clamav:1.0.11 - would be great if you could test it out.

**Comment by drandell** [comment]
@eldadfux 
seems to be a permissions issue in that container
![image](https://user-images.githubusercontent.com/393945/86151989-6f95d400-baf7-11ea-8774-f6c8c07485d9.png)

**Comment by eldadfux** [comment]
@drandell Can you try 1.0.12 version?

This is what I'm getting:
![image](https://user-images.githubusercontent.com/1297371/86163553-1343ac00-bb19-11ea-8c98-29c7a44820cf.png)

**Comment by eldadfux** [comment]
After using it for a few weeks, the latest appwrite/clamav:1.0.12 seems to be pretty stable.

I'll reopen the issue if new problems occur.
