### ISSUE TITLE
Add support for new Platforms

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#419]
Appwrite was designed to be cross-platform and technology agnostic. Help us to add support for more platform by adding new SDK templates to the [Appwrite SDK Generator](https://github.com/appwrite/sdk-generator) and improve our current templates.

# Dev Status

| Platform           | Client / Server | Templates   | File Uploads | Tests | Playground | Repository | Status
|----------------|---------------|---------------|----------------|-----------|-----------|-----------|-----------|
| Web | Client  | Ready | Supported | No¹ | [Link](https://github.com/appwrite/playground-for-js) | [Link](https://github.com/appwrite/sdk-for-js) | **Ready**
| Flutter | Client  | Ready | Supported | Yes | [Link](https://github.com/appwrite/playground-for-flutter) | [Link](https://github.com/appwrite/sdk-for-flutter) | **Ready**
| Node.js | Server  | Ready | Supported | Yes | [Link](https://github.com/appwrite/playground-for-node) | [Link](https://github.com/appwrite/sdk-for-node)  | **Ready**
| PHP | Server  | Ready | Supported | Yes | [Link](https://github.com/appwrite/playground-for-php) | [Link](https://github.com/appwrite/sdk-for-php) | **Ready**
| Ruby | Server  | Ready | Missing | Yes | Missing | [Link](https://github.com/appwrite/sdk-for-ruby) | **Ready**
| Python | Server  | Ready | Supported | Yes | [Link](https://github.com/appwrite/playground-for-python) | [Link](https://github.com/appwrite/sdk-for-python) | **Ready**
| Deno | Server  | Ready | Supported | Yes | [Link](https://github.com/appwrite/playground-for-deno) | [Link](https://github.com/appwrite/sdk-for-deno) | Beta
| .NET | Server  | Ready | Supported | Yes | [Link](https://github.com/appwrite/playground-for-dotnet) | [Link](https://github.com/appwrite/sdk-for-dotnet) | Beta
| Dart | Server  | Ready | Supported | Yes | [Link](https://github.com/appwrite/playground-for-dart) | [Link](https://github.com/appwrite/sdk-for-dart) | Beta
| Go | Server  | Ready | Missing | Missing | Missing | Pending | Pending
| Java | Server  | Ready³ | Supported | Yes⁴ | Missing | Pending | Pending
| Swift | Client  | Ready⁵ | Supported | Missing | Missing | Pending | Pending

**Currently in progress:**

.NET - @komemi, @TorstenDittmann  - DONE 
Rust - @Almoullim 
Deno - @Almoullim - DONE
ReactNative - @maherzaidoune (with help from @mosamlife and his team)
CLI - @christyjacob4  
Kotlin - Pending
Unity - Pending (should extend .NET SDK)
Dart - @lohanidamodar - DONE

¹ Missing Docker based env to run browser tests on Travis CI, currently tested manually.
³ Missing example docs that we use to generate for example on https://appwrite.io/docs
⁴ Missing test for file upload
⁵ Missing support for OAuth login (integration with browser / web auth)

**Comment by eldadfux** [comment]
C# templates has been mereged! Thanks @komemi !
https://github.com/appwrite/sdk-generator/pull/45/files

**Comment by eldadfux** [comment]
@bartektartanus I have split the Flutter and Dart templates in preparation to have a clean Dart SDK for the server API.

**Comment by bartektartanus** [comment]
@eldadfux thats great news, good job! 👍

**Comment by eldadfux** [comment]
@Almoullim Deno file uploads seems to be working as expected in Deno 1.1.3 🎊

**Comment by marcglasberg** [comment]
@eldadfux Hey, Dart is not listed but you talked about it in a comment. Are you working in a Dart server SDK? It's not clear to me.

**Comment by eldadfux** [comment]
@marcglasberg yes, I'll add it to the list.

I actually did some work last week to separate the Dart SDK templates from the Flutter SDK templates, hope we could have it ready for the next Appwrite version.

**Comment by eldadfux** [comment]
Just released version 0.0.6 of our Python SDK with support for file uploading, minor bug fixes and improved docs. Please report if you find any issues: https://pypi.org/project/appwrite/#history

I have updated the status table.

**Comment by eldadfux** [comment]
We have a new playground repo thanks to @punitdiwan :)

https://github.com/appwrite/playground-for-deno

Updated status table.

**Comment by eldadfux** [comment]
First version of our .NET SDK is available: https://github.com/appwrite/sdk-for-dotnet 🎉

Credit to @komemi and @TorstenDittmann for all the hard work!

The SDK is also available using NuGet: https://www.nuget.org/packages/Appwrite

**Comment by TorstenDittmann** [comment]
@eldadfux This also needs an update now 😉

**Comment by eldadfux** [comment]
> @eldadfux This also needs an update now 😉

Done :)

**Comment by bachrc** [comment]
What are the news for Rust ? :)

**Comment by guru1413** [comment]
@eldadfux Is there any support for Xamarin/MAUI client sdk?

**Comment by stnguyen90** [comment]
Closing this as it's outdated. For any new SDKs, we can create an individual issue for that SDK.
