### ISSUE TITLE
[Feature]  Please Make Order Type as Array in List Document API

### ISSUE THREAD

**Issue by punitdiwan** [appwrite/appwrite#420]
As of now, the orderField in List Document API is of type String. Please make it Array so that multiple column sorting can be done. Sometimes the requirements is like this.

	**View all student details and can sort them based on fields, can also use multiple sorting.**

This requirement may be accomplished if multiple OrderField Parameter is available. Here is an example.

Suppose the students collection has name, age and weight fields. Now student needs to be sorted sorted age wise age and then from age wise sorted students, they needs to be further sorted by weight wise. 

Hope this is valid use case.
Rggards
Punit

**Comment by TorstenDittmann** [comment]
This should be available since 0.12.0 now 👍🏻
