### ISSUE TITLE
OAuth provider String to Enum

### ISSUE THREAD

**Issue by drandell** [appwrite/appwrite#426]
Current 0Auth providers are strings. 
Appwrite should define an enum with all the allowed providers for each of use. 

Existing flutter example;
```
return await account.createOAuth2Session(provider: 'facebook');
```

Proposed improvment;
```
return await account.createOAuth2Session(provider: Provider.Facebook);
```

**Comment by eldadfux** [comment]
Actually this could be useful to any of the API params that are using the `Whitelist` validator:
https://appwrite.io/docs/client/avatars?sdk=web#getCreditCard
https://appwrite.io/docs/client/avatars#getBrowser
https://appwrite.io/docs/client/avatars#getFlag
and more...

**Comment by drandell** [comment]
Agree 100%, didn't know about those other endpoints. I find strings are so easily misspelled / small typo from an accidental elbow on the keyboard etc. :D

**Comment by tanmoy27112000** [comment]
@eldadfux  @TorstenDittmann I would like to work on this

**Comment by eldadfux** [comment]
4 years in and we got some EXCITING news! This feature is going to make it for Appwrite 1.5!
