### ISSUE TITLE
[Feature] Avatar icon for OAuth providers

### ISSUE THREAD

**Issue by delaneyj** [appwrite/appwrite#428]
GET `/avatars/providers/{code}`  for google,amazon,email or possibly `/avatars/providers` for an []string of enabled providers' resource URLs.

**Comment by eldadfux** [comment]
@delaneyj would this help?
https://github.com/appwrite/appwrite/tree/master/public/images/oauth2

https://localhost/images/oauth2/facebook.png
https://localhost/images/oauth2/google.png
https://localhost/images/oauth2/github.png
