### ISSUE TITLE
HOW TO MAKE YOUR FIRST PR IN APPWRITE REPO???

### ISSUE THREAD

**Issue by Ayushsingh07** [appwrite/appwrite#4283]
### 💭 Description

HOW TO MAKE YOUR FIRST PR IN APPWRITE REPO???

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hey there 👋 Please check out our [website](https://hacktoberfest.appwrite.io/) to find an issue you would like to work on.
Regarding making a PR, the process is as follows:
- Fork a repository
- Clone the fork
- Create a new branch on the fork
- Commit changes to the branch
- Push branch
- Create pull request

There are many resources online for beginners as well as experienced developers.

**Comment by KIET7UKE** [comment]
Hey, @Ayushsingh07 I want to work on this issue. Would appreciate it if you assign me.
