### ISSUE TITLE
🚀 Feature: Almost Instagram

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/appwrite#4286]
### 🔖 Feature description

This Hacktoberfest, we're taking demo app submissions to Awesome Appwrite!

This issue is for a demo app that allows users to post photos and descriptions, similar to Instagram.

- [ ] Create an account
- [ ] Browse uploads by other users
- [ ] (Optional) post comments
- [ ] Upload photos with descriptions
- [ ] (Optional) a user profile page

Be creative 🤓 ! The outline above is a suggestion. We hope it inspires your ✨ creativity ✨. Most importantly, happy hacking!

This submission requires a proposed addition under the [Showcase Section](https://github.com/appwrite/awesome-appwrite#showcase-built-with-appwrite-) of the Awesome Appwrite readme. 

The submission can be a public GitHub repository of an application created with Appwrite, written in any language. The integration can be with REST APIs or any Appwrite SDKs.

### 🎤 Pitch

Demo apps submitted will be featured in the Awesome Appwrite catalog.

We refer new Appwrite users here to get inspired or get help when they get started with Appwrite.

This means you and your repo get recognition on GitHub, which helps you build a portfolio. Appwrite users also benefit from your skills and creativity!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by Rinshin-Jalal** [comment]
This issue is open for everyone and we want as many quality PRs as our community can create

@anushagupta1312

**Comment by stnguyen90** [comment]
@anushagupta1312, thanks for your interest! 🙏 Go ahead, you can start work on this issue 😊
