### ISSUE TITLE
🚀 Feature: Card Game Clone

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/appwrite#4287]
### 🔖 Feature description

This is a 👾 Hacktoberfest issue.

This Hacktoberfest, we're taking demo app submissions to Awesome Appwrite!

This issue is for a demo app that is a clone of a card game. It can be Poker, Apples to Apples, Uno, Cards Against Humanity, or your original idea.

Here are some suggested features

- [ ] Create an account (or anonymous sessions are okay, too)
- [ ] Different game rooms
- [ ] Invitation system
- [ ] Realtime subscription for UI updates
- [ ] (Optional) A chat system

Be creative 🤓 ! The outline above is a suggestion. We hope it inspires your ✨ creativity ✨. Most importantly, happy hacking!

This submission requires a proposed addition under the [Showcase Section](https://github.com/appwrite/awesome-appwrite#showcase-built-with-appwrite-) of the Awesome Appwrite readme. 

The submission can be a public GitHub repository of an application created with Appwrite, written in any language. The integration can be with REST APIs or any Appwrite SDKs.

Take a look at our [Contributing Guide](https://github.com/appwrite/awesome-appwrite/blob/master/CONTRIBUTING.md) first.

### 🎤 Pitch

Demo apps submitted will be featured in the Awesome Appwrite catalog.

We refer new Appwrite users here to get inspired or get help when they get started with Appwrite.

This means you and your repo get recognition on GitHub, which helps you build a portfolio. Appwrite users also benefit from your skills and creativity!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Animesht1008** [comment]
hi @gewenyu99 can you please assign me this issue as a part of hacktoberfest?

**Comment by codercatdev** [comment]
@Animesht1008  go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.

You will still get credit for Hacktoberfest when we mark the PR.
