### ISSUE TITLE
🐛 Bug Report: Not Responsive on Galaxy Fold

### ISSUE THREAD

**Issue by Anurag30112003** [appwrite/appwrite#4293]
### 👟 Reproduction steps

Steps -
- Right click 
- Inspect element
- Galaxy fold viewport

### 👍 Expected behavior

The website should be responsive.

### 👎 Actual Behavior

Not responsive on galaxy fold viewport
![image](https://user-images.githubusercontent.com/79055093/193934013-56e30d49-0dac-4ec3-9ae4-81168436d30b.png)

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Brave browser.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by D3nn7** [comment]
When I test it on my end, the page is responsive😅 
![image](https://user-images.githubusercontent.com/79147263/194332274-8e0667a1-d6bf-454d-a9a8-503fa964896a.png)

**Comment by Anurag30112003** [comment]
@D3nn7 Its fixed now.
