### ISSUE TITLE
🐛 Bug Report: Upgrade incorrectly handles = in from env file values

### ISSUE THREAD

**Issue by germanllop** [appwrite/appwrite#4294]
### 👟 Reproduction steps

Have an older version fo appwrite and will upgrade:

Have a _APP_OPENSSL_KEY_V1, _APP_DB_PASS or _APP_DB_ROOT_PASS with a special character at the end ('=' in my case)

Run the Upgrade (installation):
`docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.0.1`

Run the Database Migration:
`cd appwrite/
docker compose exec appwrite migrate`

### 👍 Expected behavior

Data Migration Completed

### 👎 Actual Behavior

Starting Data Migration to version 1.0.1
SQLSTATE[HY000] [1045] Access denied for user 'databaseUser'@'IP_ADDRESS' (using password: YES)

Checked the differences between the .env file backup and the new one and some variables that ended with '=', that character was stripped, causing the migration to fail, in my case just added the missing character to the variable, but checking the install script found that file_get_contents() was stripping that last character, coudn't find much on that function behavior.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

VPS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@germanllop, thanks for raising this issue! 🙏 Looks like this is caused by:

https://github.com/appwrite/appwrite/blob/676709e70623b667ac9da6dae7e5da6ece87591e/src/Appwrite/Docker/Env.php#L22

`explode()` is the devil 😑

**Comment by Rutam21** [comment]
@stnguyen90 Please point me out what needs to be done and I can complete a PR for this issue. `explode()` needs to be removed from the Env file or you would suggest another alternative. Thanks.

**Comment by stnguyen90** [comment]
@Rutam21, do you understand the problem? Have you tried to reproduce the bug?

**Comment by germanllop** [comment]
I can suggest:

`explode('=',$row, 2)`

**Comment by stnguyen90** [comment]
@germanllop, that's a great suggestion!

**Comment by amit-ksh** [comment]
Can I work on this issue?

**Comment by dsuarezlogans** [comment]
Hello, can I work on this issue?

**Comment by stnguyen90** [comment]
@dsuarezlogans, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by stnguyen90** [comment]
@dsuarezlogans, are you still working on this?

**Comment by dsuarezlogans** [comment]
sorry @stnguyen90 had an accident, so I won't be able to help

**Comment by stnguyen90** [comment]
@dsuarezlogans, thanks for the update! Hope you're okay! 🙏

**Comment by stnguyen90** [comment]
@megatank58, would you like to be assigned on this?

**Comment by megatank58** [comment]
Hello there, i have already made a PR #4391, feel free to contribute there
