### ISSUE TITLE
🚀 Feature: Made scroll back to top button smooth

### ISSUE THREAD

**Issue by AnshuPathak-88825** [appwrite/appwrite#4296]
### 🔖 Feature description

![Screenshot (35)](https://user-images.githubusercontent.com/78332454/193983227-4b1815d8-3db2-4225-80e5-f8682cd9e368.png)
made this scroll smooth

### 🎤 Pitch

because when we add this feature it  made better user experience

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by devXprite** [comment]
Hey @AnshuPathak-88825 I first Open this Issue (#4295) 🙄

**Comment by AnshuPathak-88825** [comment]
sorry I didn't see that I'm closing it now

**Comment by fidato818** [comment]
If this task is still pending then kindly assign me this issue / task
