### ISSUE TITLE
[BUG] Doctor fails check when ClamAV is disabled and not running

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#430]
Doctor fails on `Unable to connect to ClamAV server` without further checks.

Appwrite config:
```
...
_APP_STORAGE_ANTIVIRUS=disabled
...
```
and commented out ClamAV container so it is not running.

Expected behaviour:
- Warning that ClamAV is disabled
- Error that ClamAV is not running when it is configured enabled
- Warning that ClamAV is running when it is configured disabled

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/85183536-bdf3d900-b294-11ea-9239-005e2f225a23.png)

I was able to recreate the issue when turning ClamAV off and setting it as enabled. When it's disabled the doctor CLI completely skips the check.

**Comment by eldadfux** [comment]
Added a try/catch block for cases where an exception is thrown from the Network constructor:
![image](https://user-images.githubusercontent.com/1297371/85183819-d3b5ce00-b295-11ea-9975-afbde5a43c01.png)
