### ISSUE TITLE
🐛 Bug Report: Appwrite PyPI page missing description

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#4304]
⚠️ Issue reserved to chinmayayy based on dream contribution ⚠️

### 👟 Reproduction steps

Visit: https://pypi.org/project/appwrite/

### 👍 Expected behavior

There should be some description regarding this Appwrite SDK. For example, this is what Node (NPM) has: https://www.npmjs.com/package/node-appwrite

### 👎 Actual Behavior

You can see description says `The author of this package has not provided a project description`.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
A few notes that might be useful:
- Source code of Python Appwrite CLI is hosted at: https://github.com/appwrite/sdk-for-python
- All of our SDKs are generated from: https://github.com/appwrite/sdk-generator

**Comment by Nibba2018** [comment]
Hello @Meldiron , I would like to work on this issue if it isn't already assigned to someone else.

**Comment by Meldiron** [comment]
@Nibba2018 Hey there 👋 This issue was created as a dream contribution of @chinmayayy . We will allow him a few days to let us know if he is still interested in this issue. If we don't get a response from him within the next week, I will assign this to you.

With that said, you could request your very own dream contribution 😎 Check out this issue: https://github.com/appwrite/appwrite/issues/4024

**Comment by chinmayayy** [comment]
Hello @Meldiron thanks for the opportunity! I'll make sure to complete the task soon.

**Comment by Meldiron** [comment]
@chinmayayy Thanks for letting me know 🥰 I have assigned the issue to you.

**Comment by chinmayayy** [comment]
Could you help me with a few queries @Meldiron. What format (doc/blog etc.) do I submit the documentation in and do I create the PR in this very repository itself?

**Comment by stnguyen90** [comment]
@chinmayayy, for this change, I don't think we'll need a blog; the goal would just be to update the Project Description on https://pypi.org/project/appwrite/ to show our readme.

**Comment by chinmayayy** [comment]
Yes, my question was can I access and make changes to the targeted project description directly?

**Comment by stnguyen90** [comment]
> Yes, my question was can I access and make changes to the targeted project description on PyPi page directly?

@chinmayayy, what do you mean? I assume the data is in here: https://github.com/appwrite/sdk-generator/tree/master/templates/python. Do you know how/where the project description comes from?

**Comment by chinmayayy** [comment]
I figured, thanks!

**Comment by shaishav06** [comment]
I'm interested for work this Bug Can assign me? @Meldiron

**Comment by shaishav06** [comment]
What is problem of this but please tell me in some brief level so I can work on it @Meldiron

**Comment by abnegate** [comment]
@shaishav06 This issue was created as a dream contribution of @chinmayayy. If there are any issues with completion, I will assign this to you.

With that said, you could request your very own dream contribution 😎 Check out this issue: https://github.com/appwrite/appwrite/issues/4024
