### ISSUE TITLE
📚 Documentation: Add Nepali README version

### ISSUE THREAD

**Issue by sidbelbase** [appwrite/appwrite#4318]
### 💭 Description

I have seen that there is a `Chinese` version of `README.md` and people are asking for another language, I would really love to work on the `Nepali` version for fellow `Nepali` people. Can you please assign me this task as soon as this documentation request is confirmed?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by krishshah920** [comment]
Assign this to me . I will be completing it.

**Comment by sidbelbase** [comment]
> Assign this to me . I will be completing it.

I have already requested to assign this task to me under the description section.

**Comment by sidbelbase** [comment]
> Assign this to me . I will be completing it.

I have already requested to assign this task for myself under the description section.

**Comment by stnguyen90** [comment]
@sidbelbase Thanks for raising this issue! 🙏 Unfortunately, this is not something we want to move forward at the moment as it would be difficult for us to maintain. We'll be sure to revisit this in the future when appropriate. For now, I'm going to close this to avoid attention during Hacktoberfest.
