### ISSUE TITLE
📚 Documentation: Add Bengali README version

### ISSUE THREAD

**Issue by PRATYUSHPAHARI** [appwrite/appwrite#4320]
### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by sarkartanmay393** [comment]
Hello @PRATYUSHPAHARI, If there is anything to help, I would love to contribute to Bengali language.

**Comment by PRATYUSHPAHARI** [comment]
Hey @sarkartanmay393, thanks for your request. I would like to make PR on this issue as I have created it.  But don't worry, you can check other issues.

**Comment by stnguyen90** [comment]
@PRATYUSHPAHARI Thanks for raising this issue! 🙏 Unfortunately, this is not something we want to move forward at the moment as it would be difficult for us to maintain. We'll be sure to revisit this in the future when appropriate. For now, I'm going to close this to avoid attention during Hacktoberfest.

**Comment by Prajna-Pahari** [comment]
Sure Sir.
