### ISSUE TITLE
📚 Documentation: Add French Readme version

### ISSUE THREAD

**Issue by BajajAyush** [appwrite/appwrite#4333]
### 💭 Description

I have seen that there is now a Chinese version of the README.md.

Since I am fluent in French, I would like to suggest to create a French README version. I would also like to offer myself for the implementation.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Satakshijain** [comment]
Hi , I would like to contribute to this . Please assign this issue to me
