### ISSUE TITLE
📚 Documentation: Add Hindi Readme Version

### ISSUE THREAD

**Issue by SiddheshKukade** [appwrite/appwrite#4334]
### 💭 Description

> ### I have seen that there is a Chinese version of README.md and people are asking for another language. I would like to suggest to create a Hindi README version for fellow Hindi Speaking people. If my documentation request is confirmed, I would also like to offer myself the implementation. I would do it within 1 day and would be very happy if assigned
#### Sources / References : 
https://en.wikipedia.org/wiki/Hindi
https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers_in_India

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by nooras** [comment]
Hi can you please assign it to me if you r not working on it ? thanks

**Comment by AnkitV-Git** [comment]
I want to work on this. I am new to open source and hence want to start with this. Please assign it to me.

**Comment by SiddheshKukade** [comment]
@AnkitV-Git No you can't I've requested for it first .Dear Maintainers, please  assign me

**Comment by stnguyen90** [comment]
@SiddheshKukade Thanks for raising this issue/PR! 🙏 Unfortunately, this is not something we want to move forward at the moment as it would be difficult for us to maintain. We'll be sure to revisit this in the future when appropriate. For now, I'm going to close this to avoid attention during Hacktoberfest.
