### ISSUE TITLE
📚 Documentation: Add Arabic Readme Version

### ISSUE THREAD

**Issue by Ray0Emma** [appwrite/appwrite#4335]
### 💭 Description

I have seen no Arabic version of README.md and people ask for another language. I would like to suggest creating an Arabic README version for fellow Arabic Speaking people. If my documentation request is confirmed, I would also like to offer the implementation. I would do it within 1 day and would be very happy if assigned.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Ray0Emma Thanks for raising this issue! 🙏 Unfortunately, this is not something we want to move forward at the moment as it would be difficult for us to maintain. We'll be sure to revisit this in the future when appropriate. For now, I'm going to close this to avoid attention during Hacktoberfest.
