### ISSUE TITLE
📚 Documentation:  Add Brazilian Portuguese Readme Version

### ISSUE THREAD

**Issue by StPfeffer** [appwrite/appwrite#4338]
### 💭 Description

I have seen that there is now a Chinese version of the README.md.

Since I am fluent in Portuguese, I created a Portuguese README.pt-BR version.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@StPfeffer Thanks for raising this issue/PR! 🙏 Unfortunately, this is not something we want to move forward at the moment as it would be difficult for us to maintain. We'll be sure to revisit this in the future when appropriate. For now, I'm going to close this to avoid attention during Hacktoberfest.
