### ISSUE TITLE
📚 Documentation: Improve Apprite docs for Web

### ISSUE THREAD

**Issue by Susmita-Dey** [appwrite/appwrite#4344]
### 💭 Description

I want to improve the docs for [this page](https://appwrite.io/docs/getting-started-for-web) and the following pages based on Web.

There are some grammatical errors which can be fixed and also other improvements that can be made.

I'm willing to make a PR. Kindly assign it to me.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Bennykillua** [comment]
@Susmita-Dey  Can I work on this?

**Comment by Susmita-Dey** [comment]
@Bennykillua You can check other issues as I'll make a PR for this.

**Comment by stnguyen90** [comment]
@Susmita-Dey, thanks for raising this issue! 🙏 We're already working on cleaning up our docs so I don't think there's a need for anyone else to pick this up. I'm going to close this issue as it seems to be attracting unnecessary attention during Hacktoberfest.
