### ISSUE TITLE
🚀 Feature: Add a created_by attribute to documents that were created using the Appwrite client side SDK

### ISSUE THREAD

**Issue by yaakov123** [appwrite/appwrite#4345]
### 🔖 Feature description

I'd like to have a created_by attribute on each document that is created using the client side sdk.

### 🎤 Pitch

When creating documents that belong to a specific user, I find myself doing one of 2 things.

1) Adding the user_id to the document on the client side (which is bad practice)
2) Needing to create an Appwrite function to create all documents and use the APPWRITE_USER_ID env variable to set the user_id

I'd like Appwrite to handle that part of the document creation and have a special meta property $user_id OR $created_by on each document to help with this use case

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by netapy** [comment]
I could really use this feature and was actually about to post about it. 
Would be amazing to have this.

**Comment by stnguyen90** [comment]
@yaakov123, @netapy, this looks like a duplicate of https://github.com/appwrite/appwrite/issues/3623. If so, can you 👍 that issue and close this issue?

**Comment by yaakov123** [comment]
Thanks! I'll do that.
