### ISSUE TITLE
[BUG] Unable to delete a project logo

### ISSUE THREAD

**Issue by dlutton** [appwrite/appwrite#435]
I followed the steps in the screen shot and when you click on save, the image is gone, however when you refresh the screen, the logo reappears.

Version: 0.6.2

![image](https://user-images.githubusercontent.com/14303235/85184445-ac82e080-b244-11ea-9a3d-27310641ce54.png)

**Comment by eldadfux** [comment]
Fixed in #437 will be released in next version

**Comment by eldadfux** [comment]
With a minor delay 😉, v0.7 is out and this fix is now available ✅
