### ISSUE TITLE
📚 Documentation: Grammatical Errors on README.md

### ISSUE THREAD

**Issue by AshwinSatyawan** [appwrite/appwrite#4420]
### 💭 Description

Observe the following issues in README.MD:
1.   **Installation :** 
 improper grammar at "Appwrite backend server" which should be "The Appwrite backend server"

2. **Services  -> Account :**
  "...Track and manage the user sessions" should be "...Track and manage user sessions"

3. **Services  -> Databases:**
"Manage databases, collections and" should be "Manage databases, collections, and"

4. **Services  -> Realtime:**
"functions, databases and more." should be "functions, databases, and more."

5. **Services  -> Avatars:**
"flags, browser icons, credit card symbols" should be "flags, browser icons and credit card symbols"

6. **Architecture :**
"control your compute capacity" should be "control your computing capacity"

7. **Follow Us :**
"[Facebook Group](https://www.facebook.com/groups/appwrite.developers/) , [Dev Community](https://dev.to/appwrite)" should be [Facebook Group](https://www.facebook.com/groups/appwrite.developers/), [Dev Community](https://dev.to/appwrite)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by AshwinSatyawan** [comment]
Resolved in PR #4421

**Comment by rishabhrathore055** [comment]
@AshwinSatyawan I want to work on this. Could you please give me a chance?

**Comment by AshwinSatyawan** [comment]
> 

already Resolved

**Comment by rishabhrathore055** [comment]
@AshwinSatyawan Sir, if you have any other beginner issues that I can work on, please assign them to me.

**Comment by iamAditya01** [comment]
assign me this one

**Comment by stnguyen90** [comment]
@AshwinSatyawan, thanks for raising this issue! 🙏🏼 We'll be sure to address these, but I'm going to close this for now because we'd rather people focus on the [issues we've created for Hacktoberfest](https://hacktoberfest.appwrite.io/).
