### ISSUE TITLE
🐛 Bug Report [CRITICAL]: Deleting a database deletes attributes/indexes in other databases

### ISSUE THREAD

**Issue by ddenev** [appwrite/appwrite#4427]
### 👟 Reproduction steps

Using the Appwrite Console I have created 2 databases:

- `TestDB1`
- `TestDB2`

I have added a collection with the same name to each database:

- `TestDB1` -> `TestCollection`
- `TestDB2` -> `TestCollection`

I have added a string attribute with the same name to each collection:

- `TestDB1` -> `TestCollection` -> `name`
- `TestDB2` -> `TestCollection` -> `name`

Then I deleted `TestDB2` from the Appwrite Console. Without any other actions/changes done - checking the attributes for `TestDB1` -> `TestCollection` (after flushing the Redis cache) shows an empty page. The `name` attribute for the `TestDB1` -> `TestCollection` is also missing in the `_1_attributes` table in the MariaDB.

Same happens with indexes that have the same key in both collections - they are removed as well.

This was done after a clean install of Appwrite v1.0.2.

This is a critical issue that needs to be fixed asap. I found this b/c I was implementing multitenancy by creating databases upon creating new users, using a server function.

I hope nobody still uses multiple databases in production as with this bug this is a recipe for a disaster.

Dear Appwrite team, please fix this with priority!

### 👍 Expected behavior

The attributes in `TestDB1` should not be deleted.

### 👎 Actual Behavior

The `name` attribute in `TestDB` was deleted as well and is no longer visible in the Console as well as no longer available in the `_1_attributes` table in the MariaDB.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ddenev thanks for raising this PR! 🙏 We'll work on fixing this ASAP!

**Comment by TorstenDittmann** [comment]
@ddenev thank you very much for bringing this up 💪🏻 

This is fixed now with [1.0.3](https://github.com/appwrite/appwrite/releases/tag/1.0.3) 👏🏻

**Comment by ddenev** [comment]
@stnguyen90 @TorstenDittmann - thank you for the quick fix!
