### ISSUE TITLE
📚 Documentation: Backup step unclear

### ISSUE THREAD

**Issue by silberGuy** [appwrite/appwrite#4431]
### 💭 Description

Hi :)
I am now backing up my Appwrite server, and following the steps I found in the [docs](https://appwrite.io/docs/production#backups).
As the third step indicates, I should backup the `storage volume`, which is an entity that i cannot find.
Is this a name to represent all the different volumes listed in the docker-compose.yml? or am I missing the specific volume to backup?

thank you

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@silberGuy, perhaps [this](https://github.com/appwrite/appwrite/discussions/3722#discussioncomment-3487928) answers your question. If so, can this be closed?

Also, FYI, the volumes are defined at the bottom of your docker-compose.yml file.

**Comment by silberGuy** [comment]
Thank you, the video helps.
I did know where to find the list of the volumes, but that's the issue - this list includes all volumes, and it is not a source to find which should be backed-up.
I think the docs could be more explicit on this, or maybe just point to the video that you added?
