### ISSUE TITLE
🐛 Bug Report: Incorrect Audit Activity on Document Create

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4436]
### 👟 Reproduction steps

1. Create a Document

### 👍 Expected behavior

New audit activity is added for the document

### 👎 Actual Behavior

New audit activity is added for the **Collection** instead.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/1477010/195416008-02348469-fe28-4eb2-87a7-0f8a6aeb7ed2.png">

It seems the incorrect `audits.resource` is specified:

https://github.com/appwrite/appwrite/blob/b6eef3a88659bac99d262530c77223590b933b85/app/controllers/api/databases.php#L1844

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Tested on Appwrite version 1.0.2.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by akarsh-jain-790** [comment]
Hey, can u assign this issue to me ?

**Comment by stnguyen90** [comment]
@akarsh-jain-790 Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by neelshah2409** [comment]
Hey can I work on it !

**Comment by Meldiron** [comment]
@neelshah2409 , we're assigning people on a first come first serve basis. If @akarsh-jain-790  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by stnguyen90** [comment]
@akarsh-jain-790, how's your progress on this? Please let us know within 24 hours so we can reassign it accordingly.

**Comment by stnguyen90** [comment]
Assigning to @neelshah2409 due to inactivity. Would you please confirm you're still interested in working on this?

**Comment by neelshah2409** [comment]
> Assigning to @neelshah2409 due to inactivity. Would you please confirm you're still interested in working on this?

Yes I would work on this issue

**Comment by stnguyen90** [comment]
@neelshah2409 are you still working on this or should we unassign you?
