### ISSUE TITLE
Add Validation in Permission Section of Collection and Document in Console. 

### ISSUE THREAD

**Issue by punitdiwan** [appwrite/appwrite#444]
In the permission section of Collection Settings and Create and Update Document in console, we enter the user ID, team ID to grant read and write permission. 

However, the user ID and team ID must be prefixed with the word **user** or **team** as the case may be to make permission work properly. For example if the user id is **5eeb1d97ba0dd**, then it should be written **user:5eeb1d97ba0dd** or **team:5eeb1d97ba0dd** in both read and write text boxes.

Please add validation to ensure that the read and write access permission should be in the above format. We can add this validation at the press of update button collection and update/create button of document..

Regards,
Punit

**Comment by eldadfux** [comment]
This relates to #445. We need to add better validations with verbose errors both on the console and on the API sides.

**Comment by abhee4** [comment]
@eldadfux 

It would be great if instead of typing that in, there are two sections which autoappend the necessary suffix just by selecting a drop down. I made a UI on XD, please take a look.

![image](https://user-images.githubusercontent.com/2958671/88657720-fc7c7f00-d0ef-11ea-8a84-c7da22447982.png)

**Comment by abhee4** [comment]
On the second thought, @eldadfux , two more ideas. 
Which looks better according to you?

![image](https://user-images.githubusercontent.com/2958671/88659934-79f5be80-d0f3-11ea-9d25-44accddbb9ca.png)
![image](https://user-images.githubusercontent.com/2958671/88660235-fab4ba80-d0f3-11ea-88e8-a3c8cade649d.png)

**Comment by eldadfux** [comment]
I think the second design one is more user friendly. Maybe we can add a 'view source' button on the top rght to help users understand how this will actually be saved as in the API?

**Comment by abhee4** [comment]
> I think the second design one is more user friendly. Maybe we can add a 'view source' button on the top rght to help users understand how this will actually be saved as in the API?

Exactly !!

The Source has actually helped me a lot to convert the json to dart to make my models, it would be super useful.

Again, many thanks for appwrite. I'll try to be as engaged as possible to help getting it better for me and for my fellow coders.

Kudos !

**Comment by PineappleIOnic** [comment]
Hey there 👋 I wouldn't mind taking this on 😄

**Comment by eldadfux** [comment]
@PineappleIOnic great, I have assigned you to this issue, feel free to reach out if you have any questions or if you need any help setting the dev environment.

**Comment by PineappleIOnic** [comment]
I've created a PR here: https://github.com/appwrite/appwrite/pull/522 please let me know your thoughts

**Comment by PineappleIOnic** [comment]
To give an update about this issue, it's quite an old one and the PR that was created for it no longer works with the current version of Appwrite. So I'm releasing it if someone else would like to take it up.

**Comment by christyjacob4** [comment]
With Appwrite 1.0 and the introduction of the permissions matrix this should no longer be an issue as it comes with the requested validation.
