### ISSUE TITLE
🚀 Feature: function version control

### ISSUE THREAD

**Issue by alexander-potemkin** [appwrite/appwrite#4442]
### 🔖 Feature description

Ability to version control functions code (like git does)

### 🎤 Pitch

Guess the use case is obvious, as I post it on GitHub issues, guess it might be even on the roadmap?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@alexander-potemkin, thanks for raising this issue! 🙏 Could you expand more on this request? I typically use the Appwrite CLI and version control the appwrite.json and the functions I create with git. What else did you have in mind?

**Comment by alexander-potemkin** [comment]
Hi @stnguyen90 and thanks for the prompt response!
My understanding was that I can edit functions via the web GUI, isn't it right?

**Comment by stnguyen90** [comment]
@alexander-potemkin, you can upload additional code and edit function settings. You can't modify lines of code, if that's what you're asking.

**Comment by alexander-potemkin** [comment]
Right, thank you, @stnguyen90 .
Is there any plans to create a web based environment to create, edit and maintain those functions?

**Comment by stnguyen90** [comment]
@alexander-potemkin, probably not. Definitely not anytime soon.

**Comment by alexander-potemkin** [comment]
I see, thank you, @stnguyen90. I was somehow under impression, that AppWrite is more of a low-code instrument, that tends to minimize command line things - could you please, help me to better understand it's goal and target audience, please?

**Comment by stnguyen90** [comment]
@alexander-potemkin, Appwrite isn't really a low-code tool. It's a back-end server that simplifies things for app developers so they can focus on building their app rather than their app AND a backend. Does that answer your question? If so, can this be closed?

**Comment by alexander-potemkin** [comment]
@stnguyen90 , it does, partially, thank you.

I see that AppWrite could be used in pair with no-/low-code tools, but for this it's missing an ability to easily create and edit functions from the web.

Do you have some ideas how it could be done - the most easy and quick to implement way possibly?

**Comment by stnguyen90** [comment]
@alexander-potemkin, I'm not sure if there's a quick and easy way to do this in a browser. Some hurdles would be:

* How to manage files?
* How to create a gzip file with the code?

Eventually, you'd need to create a gzip file with the code and call the [Create Deployment API](https://appwrite.io/docs/server/functions?sdk=nodejs-default#functionsCreateDeployment).

**Comment by alexander-potemkin** [comment]
Thank you!

Something like a working folder with the files; once 'commit' button clicked, folder `gzip`-ed and send via [the API](https://appwrite.io/docs/server/functions?sdk=nodejs-default#functionsCreateDeployment) ?

Output is displayed somewhere for example, at the bottom?

**Comment by eldadfux** [comment]
@alexander-potemkin next version of Appwrite 1.4 will allow you to connect Appwrite with your git and automatically deploy your code on commit/merge. Closing this issue for now.
