### ISSUE TITLE
🚀 Feature: Database migration per project through code

### ISSUE THREAD

**Issue by jessielaf** [appwrite/appwrite#4444]
### 🔖 Feature description

Hi,

I really love the tool. But I have not been able to find (maybe that's me) a tool in which I can migrate my local changes to my demo environment and production. For example, how the [Django migration](https://docs.djangoproject.com/en/4.1/topics/migrations/)  system works.

I think it would be nice if you can automatically apply migrations when deploying a new application or maybe programmatically move the changes in the database (without the data) to another environment.

I have found two issues that are similar https://github.com/appwrite/appwrite/issues/390 and https://github.com/appwrite/appwrite/issues/2971

### 🎤 Pitch

This would create a easy way to integrate it into your CI/CD. Also making the use of DTAP (or something similar) possible through the CLI. Right now (I think) you can only move through environments by manually changing the database in the UI which is pretty error prone.

Please let me know if I maybe missed this functionality. I just started using appwrite.

I see there is also an API that facilitates this. What would be really good is a terraform module but I get that this is out of scope.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@jessielaf, thanks for raising this PR! 🙏 The [Appwrite CLI](https://appwrite.io/docs/command-line#gettingStarted) can be used to deploy collections and were working on adding support for buckets and services. Would that suffice?
