### ISSUE TITLE
Refine Appwrite Storage with zopfli Compression

### ISSUE THREAD

**Issue by toukirkhan** [appwrite/appwrite#4447]
I want to add zopfli compression for php to appwrite storage and I have the extension to do the same please assign me this issue or generate a new one for me.

Tasks:

- [ ] Update utopia-php/storage to include the new adapter
- [ ] Update [appwrite/docker-base](https://github.com/appwrite/docker-base/blob/main/Dockerfile) to install the necessary dependencies
- [ ] Update appwrite/appwrite to support the new adapter
- [ ] Update appwrite/console to show the compression method

**Comment by stnguyen90** [comment]
@toukirkhan are you still interested in adding support for zopfli compression?

**Comment by toukirkhan** [comment]
@stnguyen90 hi yes, I can give it a try!

**Comment by stnguyen90** [comment]
@toukirkhan assigned! thanks for your interest! 🙏🏼

**Comment by toukirkhan** [comment]
Update: am working on this issue @stnguyen90

**Comment by stnguyen90** [comment]
@toukirkhan how's your progress on this? FYI, I'll need to unassign you from this issue due to inactivity soon

**Comment by toukirkhan** [comment]
Hey! Am working on this just left with the docker file. I could need some help in the same I will raise a PR soon.

**Comment by toukirkhan** [comment]
@stnguyen90 am facing issues with the docker file. Can you help me?

**Comment by stnguyen90** [comment]
@toukirkhan what's the issue?

**Comment by toukirkhan** [comment]
I have raised a PR, please suggest if any changes are needed.

**Comment by stnguyen90** [comment]
@toukirkhan would you please make sure the PR is linked to this issue?

**Comment by toukirkhan** [comment]
Hey! Really sorry! I just forgot to link the PR will do ASAP.

**Comment by toukirkhan** [comment]
@stnguyen90 I have linked the PR!
