### ISSUE TITLE
Adding & Updating Rules Discussion

### ISSUE THREAD

**Issue by drandell** [appwrite/appwrite#447]
Currently there is a bit of disconnect between adding and updating rules. As seen below;

Adding *(Dialog);
![image](https://user-images.githubusercontent.com/393945/85620304-7f2a9e00-b65b-11ea-94b3-72f8e2826cdb.png)

Updating *(Dropdown expanded list);
![image](https://user-images.githubusercontent.com/393945/85620380-9c5f6c80-b65b-11ea-856a-32c20c578f8f.png)

I feel these two should be consistent and both made as dialogs. 
The expanded drop-down list could for me be easily lost to users if they had multiple rules. Especially since i can currently expand and open up multiple rules at once which could further confuse users (i would imaging it would be rather easy to make an optional field required if you had multiple rules open and scrolled too far for example).

The other item to note is that the addition dialog is missing the required/array toggles which i feel should be present on the addition dialog. 

Open to community feedback on this and everyone's thoughts :D

**Comment by eldadfux** [comment]
With Appwrite 0.12 we have introduced the database attributes that are replacing the database rules. You can learn more about the new version here: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
