### ISSUE TITLE
🚀 Feature: Add a custom Scroll Bar

### ISSUE THREAD

**Issue by devXprite** [appwrite/appwrite#4514]
### 🔖 Feature description

https://user-images.githubusercontent.com/80192140/196314924-44953dda-4228-4f5b-9018-c9a43f12d75e.mp4

### 🎤 Pitch

I think it can enhance website look.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@devXprite, thanks for your suggestion! 🙏 We're actually in the process of rewriting the Appwrite Console and the new Console will have a custom scrollbar. As such, I don't think it is worth it to add the scrollbar to the old Console when it is going to be scrapped.

**Comment by devXprite** [comment]
Thanks @stnguyen90 for your response.
I think it may work until new console is ready and if the new console has same color palette then there will be no need to scrap the old scroll bar.

**Comment by stnguyen90** [comment]
@devXprite, the new console is already being developed and it is a complete rewrite. We are not using anything from the old console.
