### ISSUE TITLE
🚀 Feature: Single command installer script

### ISSUE THREAD

**Issue by diamondzxd** [appwrite/appwrite#4518]
### 🔖 Feature description

Adding a single command installer script so that the people who have a little idea about Docker, may not get stuck in installing docker and the dependencies for the same.

We can wrap it up into a bash script, which will take care of installing Docker and then installing the Appwrite container. The script will take care of installing the available updates and all the dependencies.

### 🎤 Pitch

After talking with @adityaoberai in a breakout room yesterday, the current installation process was criticized as AppWrite uses docker and there were many beginners in the room, who were not familiar with Docker, and often ran into issues installing it on servers.

I pitched about a single command installer script as available in several self hosted projects, and was asked to Open a Detailed Issue, so here it is! :)

The idea is inspired from the one click installers available on Projects like CyberPanel (https://community.cyberpanel.net/docs?topic=82), VestaCP (https://vestacp.com/install/) and AzuraCast (https://docs.azuracast.com/en/getting-started/installation/docker).

Point to note is, Azuracast is also docker based behind the scenes, but its installation process is incredibly simple for even the self hosting beginners. They do not have to be familiar with the Docker's environment.

This feature can open the doors for making the installation process smooth, and provider agnostic. A user will just have to rent a VPS / Cloud VM, and run the script to get things rolling. Thus, easing the process for developers until Appwrite collaborates with more cloud providers for the Image.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by varadkarpe** [comment]
Hey, can I contribute to this?

**Comment by Meldiron** [comment]
@eldadfux I think we wanted to do something like this looong time ago.

It was supposed to be something simple just like Deno or Docker has.

Deno: `curl -fsSL https://deno.land/install.sh | sh`
Docker: `curl -fsSL https://get.docker.com | sh`

> Notice docker has this cool subdomain `get.docker.com` that is easy to remember and you can copy&paste command from there.

**Comment by diamondzxd** [comment]
We could make a proper bash script then..
Which would allow to see the current upstream version, install, or uninstall the appwrite instance.

Would also love some helper scripts to easily backup and restore the data, or a couple more usecases, as currently used in Mailcow*

*Reference : https://github.com/mailcow/mailcow-dockerized/tree/master/helper-scripts

**Comment by eldadfux** [comment]
We did use to have something similar but it created a lot of security concerns as it was harder for devs to understand what is happening under the hood. For now, due to lack of activity- I will close this issue. Happy to reopen if there’s more demand.
