### ISSUE TITLE
🐛 Bug Report: Build failed: Docker Error: tar: can't open '/tmp/code.tar.gz': No such file or directory

### ISSUE THREAD

**Issue by timsedev** [appwrite/appwrite#4522]
### 👟 Reproduction steps

I init a new function. And when I tried to deploy the function, it failed with the error : 
`Build failed: Docker Error: tar: can't open '/tmp/code.tar.gz': No such file or directory`

I tried to deploy manually, but it had the same result.

I tried to create a new function and deploy it, it had the same result too.

I am a beginner, I tried to find answers online, but I cant find anything related.

### 👍 Expected behavior

It should build and deploy successfully

### 👎 Actual Behavior

Failed with the error : 
`Build failed: Docker Error: tar: can't open '/tmp/code.tar.gz': No such file or directory`

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
What runtime and version? Did you modify the code or did you deploy the starter code? Did you deploy via `appwrite deploy function`?

**Comment by timsedev** [comment]
> What runtime and version? Did you modify the code or did you deploy the starter code? Did you deploy via `appwrite deploy function`?

Thank you for replying. 

Appwrite version: 1.0.3
Deploy runtime: Node.js 16, Python 3.9

At first I deployed with my modified code. But after several attempts, I did try to init a new function and deploy the starter code.

I tried to deploy via `appwrite deploy function` as well as manually. Both failed with the same error.

**Comment by timsedev** [comment]
In my opinion, I think there is a problem with my docker container.
Out of desperate, I clean and purge data. then reinstall appwrite.

And now I can deploy functions successfully.

Thank you for your help @stnguyen90

**Comment by pomarec** [comment]
Same issue here, reproducible, with more context. I'm using docker compose to deploy appwrite.

Working config :

```
appwrite-executor:
  volumes:
   - /tmp:/tmp:rw
```

Non working config :

```
appwrite-executor:
  volumes:
   - appwrite-builds-tmp:/tmp:rw
```

Note : `appwrite-builds-tmp` is also defined in `volumes` section

Should we re open this issue ?
