### ISSUE TITLE
🐛 Bug Report: Add or Delete attribute with appwrite.json file not working properly

### ISSUE THREAD

**Issue by akago-dev** [appwrite/appwrite#4527]
### 👟 Reproduction steps

With existing collection, add or delete attribute from your collection schema in appwrite.json then deploy with cli.

### 👍 Expected behavior

Should add or delete attributes from existing collection and set defaults values if applicable.

### 👎 Actual Behavior

Attributes are added or deleted, but all the data for all documents is erased. Only documents ids remains.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

local env

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@akago-dev, thanks for raising this issue! 🙏 This is actually working as expected since deploying a collection wipes the existing indexes and attributes and, then, deploys the attributes and indexes defined in the appwrite.json.
