### ISSUE TITLE
Broken device image when login is from unknown user agent

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#453]
Should add a condition to avoid a broken image in user sessions list. We should also add detection for Appwrite native/server SDKs user agents.

![image](https://user-images.githubusercontent.com/1297371/85926240-b04ade80-b8a6-11ea-8e95-706851cc2864.png)

**Comment by punitdiwan** [comment]
@eldadfux Yes I noted it when I was working on Android Playground as I was passing java as sdk header. I didn't report at that time thinking its in testing phase.
)

**Comment by eldadfux** [comment]
We need help adding new and parsable custom user-agent strings in our auto-generated SDK templates on the https://github.com/appwrite/sdk-generator.

This patch should be added to SDKs in all languages, except for the web SDK (we can't change user-agent inside a browser). Once done we could easily detect our own clients and show them properly on the Appwrite sessions dashboard.

**Comment by PineappleIOnic** [comment]
For user agents, we can't recognise we could have an "?" graphic, are the images in the panel done in the JS?

**Comment by PineappleIOnic** [comment]
Looking in the code I could implement an "?" graphic for all missing images with the avatar class, which will help not just the user-agent image when it's not found but also the avatar images when they go missing or are otherwise inaccessible.

**Comment by eldadfux** [comment]
@PineappleIOnic Yeh, that can be a good enough solution for the Appwrite console.

Anyway I think it would be great if we'll add a way for the API to recognise the Appwrite SDKs, so both Appwrite developers and app users could have a better visualisation of the sessions list.

**Comment by PineappleIOnic** [comment]
I've been testing using the "onerror" attribute to change the image if it can't be found to an error one

**Comment by PineappleIOnic** [comment]
PR Created. #537

**Comment by PineappleIOnic** [comment]
Should this issue be closed due to #537 being merged?

**Comment by eldadfux** [comment]
@PineappleIOnic marked it as: `waiting for release`

**Comment by PineappleIOnic** [comment]
👌

**Comment by eldadfux** [comment]
v0.7 is out and this fix is now available ✅
