### ISSUE TITLE
Want to add 'Back to Top' button

### ISSUE THREAD

**Issue by Rancho2002** [appwrite/appwrite#4531]
### 🔖 Feature description

I want to add <b>BACK TO TOP</b> button in https://hacktoberfest.appwrite.io/ this website. Please assign it to me @stnguyen90 

### 🎤 Pitch

This feature modifies the website a lot. Because this website is quite long and if user wants to move to the top of the website reaching at the end, it is a bad experience if he/she scrolls again and again. So a <b>BACK TO TOP</b> button will make sense a lot.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Samkit-shah** [comment]
Can you assign me this?

**Comment by stnguyen90** [comment]
@Rancho2002 thanks for raising this issue! 🙏 This isn't needed at the moment and we would prefer if people focus on hacktoberfest-labeled issues. I'm going to close this so that it doesn't attract extra attention during Hacktoberfest.
