### ISSUE TITLE
🐛 Bug Report:  Search multiple attributes causes error

### ISSUE THREAD

**Issue by xuala69** [appwrite/appwrite#4532]
### 👟 Reproduction steps

I have a collection with two string attributes (in this case name and content) and both have been indexed as Fulltext. When i search from my flutter app, i use the below code to search through the collection.

```
var snapshot = await aw.databases.listDocuments(
          databaseId: AWConstants.dbGlobal,
          collectionId: AWConstants.collectionGroups,
          queries: [
            Query.search("name", query),
            Query.search("content", query),
          ],
        );
log(snapshot.docs.length.toString());
```

This gives an error as below:
```
AppwriteException: null, {"message":"Error: Error handler had an error","code":500,"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":610,"trace":[{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":718,"function":"execute","class":"Utopia\\App","type":"->","args":[{},{}]},{"file":"\/usr\/src\/code\/app\/http.php","line":266,"function":"run","class":"Utopia\\App","type":"->","args":[{},{}]}],"version":"1.0.1"} (0)
```

The appwrite version on my server is 1.0.1. I have tried using version 1.0.3 on localhost to try out but still gives the same error. Flutter appwrite package version I am using is ^8.0.0

### 👍 Expected behavior

Return documents which contains the searched term

### 👎 Actual Behavior

Throws an error given below

```
AppwriteException: null, {"message":"Error: Error handler had an error","code":500,"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":610,"trace":[{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":718,"function":"execute","class":"Utopia\\App","type":"->","args":[{},{}]},{"file":"\/usr\/src\/code\/app\/http.php","line":266,"function":"run","class":"Utopia\\App","type":"->","args":[{},{}]}],"version":"1.0.1"} (0)
```

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

No. I followed the installation guides on the documentation and nothing more

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
After digging into the error a bit more, I found the underlying error was:

```
PDOException: Can't find FULLTEXT index matching the column list in @swoole-src/library/core/Database/PDOStatementProxy.php:64
```

Would you please try creating additional indexes? 1 for each attribute should do it.

**Comment by xuala69** [comment]
I did and it doesn't throw an error anymore. However, it doesn't return the expected result, just an empty list of documents.

**Comment by stnguyen90** [comment]
@xuala69, when you pass multiple queries like you did, it does an AND on them. Is that what you were expecting?

**Comment by stnguyen90** [comment]
@xuala69 for full text search, I would recommend creating an attribute that has all the content, index that attribute, and then query that attribute. You can use an Appwrite Function to make the new attribute is updated automatically if the document is updated.
