### ISSUE TITLE
Missing redirect error on redirect from OAuth when using the self-hosted instance success URL

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#454]
Trying to use Appwrite default OAuth page on your on Appwrite instance (http://appwrite.mydomain.com/auth/oauth2/success) and not on appwrite.io results in a redirect URL with no query params to complete the login.

A quick workaround would be to add the following env var with your Appwrite URL like this:
![image](https://user-images.githubusercontent.com/1297371/85932368-46492e00-b8d4-11ea-92bd-c01ac210ea87.png)

To fix this in future versions without needing to change server setting we need to make sure the check if against the request host and not the _APP_HOME env var.

**Comment by eldadfux** [comment]
Fixed, will be released in version 0.7.0

**Comment by eldadfux** [comment]
v0.7 is out and this fix is now available ✅

**Comment by tananga** [comment]
Im still having the same issue in 0.11

**Comment by tananga** [comment]
@eldadfux I have the same problem in version 0.11

This is my endpoint: static const String endpoint =
      'https://29e9-2a02-...................-996c-588-2097.ngrok.io/v1';

And In google console Authorized redirect URIs I added both: 
https://29e9-...............-2097.ngrok.io/v1/account/sessions/oauth2/callback/google/61a16259aa5ef

and

http://29e9-..............-588-2097.ngrok.io/v1/account/sessions/oauth2/callback/google/61a16259aa5ef

After selecting a google account Im geting: "Missing Redirect URL" error

**Comment by solt9029** [comment]
I'm having the same issue above. I tried it with GitHub OAuth App.

**Comment by tananga** [comment]
I solved my problem. I was using old library version. @eldadfux  You can close this issue

**Comment by gewenyu99** [comment]
@tananga Closing!

**Comment by zdanl** [comment]
I just installed the newest version 1.2.0 of Appwrite over Digitalocean and am still running this issue, although I set a custom domain in .env

See screenshot

![Screenshot from 2023-01-25 01-31-09](https://user-images.githubusercontent.com/114028070/214453076-683d54f1-e441-47db-b5f1-67ce0381db13.png)
