### ISSUE TITLE
📚 Documentation: Dashboard interface - Resource permissions

### ISSUE THREAD

**Issue by davisloper** [appwrite/appwrite#4544]
### 💭 Description

Hello. I think the collection permissions (and maybe from others services) are not well documented.

For example:

<img width="594" alt="Captura de Pantalla 2022-10-20 a la(s) 12 59 34" src="https://user-images.githubusercontent.com/48936504/197023639-7c93afa9-187f-4f91-8134-70f1567b97cf.png">

I can't grant access to a **team** with a specific **role**. The "only" thing I can do is just give access to a team.

I watched an old video and it seems that what I have to type is: team:[team_id]/[role_name], that is adding the suffix "/[role_name]". But that isn't documented in the AppWrite docs (or didn't find in my research).

Another issue is that I can't find a way to set the permission: member:[member_id]:

- Where can I find that member id? I tried to put team id, user id and simple roles like "friends" and doesn't work
- The docs says I can find the member id when retrieving the Team list through the API, but I'm only receiving the team id, user id and roles again

Where could I find some Dashboard UI docs?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@davisloper, thanks for creating the issue! 🙏 

You are correct. The Console may not autocomplete `team:[team_id]/[role_name]`, but you can still type it. Our new Console will hopefully help with autocomplete the role.

The `[member_id]` in `member:[member_id]` is a membership ID (the ID for a particular user's membership in a team). You can use the [List Team Memberships](https://appwrite.io/docs/client/teams?sdk=web-default#teamsListMemberships) API to get the membership ID.

**Comment by jordonedavidson** [comment]
Also the documentation page https://appwrite.io/docs/permissions/ which should explain this is broken. It loads, then immediately forwards to an error page at https://appwrite.io/console

**Comment by stnguyen90** [comment]
> Also the documentation page https://appwrite.io/docs/permissions/ which should explain this is broken. 

Where did you see that link? The correct link doesn't have the trailing slash: https://appwrite.io/docs/permissions

**Comment by jordonedavidson** [comment]
> > Also the documentation page https://appwrite.io/docs/permissions/ which should explain this is broken.
> 
> Where did you see that link? The correct link doesn't have the trailing slash: https://appwrite.io/docs/permissions

The link is in the paragraph text here: https://appwrite.io/docs/databases#permissions

**Comment by stnguyen90** [comment]
This should hopefully be clearer in [1.1.0](https://github.com/appwrite/appwrite/releases/tag/1.1.0):

<img width="741" alt="image" src="https://user-images.githubusercontent.com/1477010/202525654-a4bc597b-5b83-4b5c-a1e8-5997f5710a44.png">
