### ISSUE TITLE
🐛 Bug Report: Incorrect Issues Count 

### ISSUE THREAD

**Issue by motasimmakki** [appwrite/appwrite#4547]
### 👟 Reproduction steps

The issue count popping at the corner of the 'View all Hacktoberfest issues' button is not rounding off the correct total_count.

### 👍 Expected behavior

It should be:

![Screenshot (253)](https://user-images.githubusercontent.com/44056349/197187163-0f854615-b8f4-4b30-b5de-820004ee6130.png)

As of:

![Screenshot (255)](https://user-images.githubusercontent.com/44056349/197187664-c58ea7d4-5344-47b5-88fb-30d3a5b6833b.png)

### 👎 Actual Behavior

![Screenshot (254)](https://user-images.githubusercontent.com/44056349/197187124-6a5cd375-9b7f-4935-b77c-93647cf2f274.png)

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by nikzayn** [comment]
@motasimmakki I would like to take this up

**Comment by stnguyen90** [comment]
@motasimmakki thanks for raising this issue! 🙏 The count has been updated.
