### ISSUE TITLE
🐛 Bug Report: Access to data possible but no platform is registered in project

### ISSUE THREAD

**Issue by Schrolli91** [appwrite/appwrite#4548]
### 👟 Reproduction steps

- Fresh installed Appwrite instance on Linux Server with docker.
- Flutter app using the dart appwrite package (Web & Android).

Read permission for the collection is to `guests -> read`.

### 👍 Expected behavior

Access will be blocked, because no platform is configured in project.

The docs say:
> Only API requests initiated from platforms added to your Appwrite project will be accepted. This prevents unauthorized apps from accessing your Appwrite project.

![image](https://user-images.githubusercontent.com/6043382/197204239-787e49f7-c2c9-44b9-9444-914a2651dd8a.png)

### 👎 Actual Behavior

I can read the data from Appwrite

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Schrolli91, are you using the [dart_appwrite](https://pub.dev/packages/dart_appwrite) package with an API key? If so, switch to the [appwrite](https://pub.dev/packages/appwrite) because the dart_appwrite package is meant for server side code and has full access from the API key. 

How are you running your app? Are you using flutter web on localhost? If so, localhost is allowed by default.

**Comment by stnguyen90** [comment]
@Schrolli91 

> App is running on my local machine (flutter web), but the appwrite server is in the "www".

For flutter web, your client app runs on localhost. localhost is allowed to access Appwrite without adding a platform.

> Currently checked native android app - also with access to the data.

Sorry, what do you mean by this? 🧐 You're using the Appwrite Flutter SDK and running on an Android device/emulator?

**Comment by Schrolli91** [comment]
> For flutter web, your client app runs on localhost. localhost is allowed to access Appwrite without adding a platform.

Ahhh, okay. So if its running on ANY localhost, this mechanism is bypassed?
Also, if the appwrite instance runs on a dedicated server in the internet?



> Sorry, what do you mean by this?  You're using the Appwrite Flutter SDK and running on an Android device/emulator?

I run the same flutter app native compiled for android on this phone (debugging via ADB).

**Comment by stnguyen90** [comment]
@Schrolli91 

> Ahhh, okay. So if its running on ANY localhost, this mechanism is bypassed?
> Also, if the appwrite instance runs on a dedicated server in the internet?

Yes, correct.

> I run the same flutter app native compiled for android on this phone (debugging via ADB).

This is a little odd...I've definitely had problems before with an app receiving errors without a platform registered matching the bundle id of the app.

> I just find it a bit strange that you can get access with an execution on any local computer without being able to block it.
If someone gets the projectid through reverse engineering, they can easily access it

This platform check is a simple step to help stop spoofing a client app, but it does not stop people from accessing a project. See [this](https://github.com/appwrite/appwrite/issues/1649#issuecomment-925718317) related discussion. The project id is considered public data. The only way to lock down the data is to apply the appropriate permissions.

**Comment by Schrolli91** [comment]
Ok, I understand - for the web app.
But I will do some further tests with the android app tomorrow because that's still a little bit strange.

**Comment by Schrolli91** [comment]
@stnguyen90 
Have tested now. The android app in release mode on the real device can still get data without any platform configured.

**Comment by stnguyen90** [comment]
@Schrolli91, would you please check if you can make a POST request (ie. create a session, account, or document)?

**Comment by Schrolli91** [comment]
Tried to create a document.
Permission is changed - guests can do anything.
Now I see:
`AppwriteException: general_unknown_origin, Invalid Origin. Register your new client (de.schrollit.kaerwaplaner) as a new Android platform on your project console dashboard (403)`

Thats what i expect. But why this doesn't happen on reading?

**Comment by stnguyen90** [comment]
CORS is typically not applied on some requests like GET requests. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests

**Comment by Schrolli91** [comment]
Ok - thanks for explanation.
Now i think all "problems" are cleared ;-)
No Bug in sight :D
