### ISSUE TITLE
📚 Documentation: GitHub contribution badge 

### ISSUE THREAD

**Issue by Vanshiii203** [appwrite/appwrite#4559]
### 💭 Description

I would like to add the GitHub contribution badges to display the contributors of repository in README file.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Chetnagupta27** [comment]
can you assign this issue to me?

**Comment by sarthaknerd** [comment]
@Vanshiii203 Please assign it yo me

**Comment by Vanshiii203** [comment]
@stnguyen90 @christyjacob4 Please assign this to me

> ### 💭 Description
> I would like to add the GitHub contribution badges to display the contributors of repository in README file.
> 
> ### 👀 Have you spent some time to check if this issue has been raised before?
> * [x]  I checked and didn't find similar issue
> 
> ### 🏢 Have you read the Code of Conduct?
> * [x]  I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)
@stnguyen90 @christyjacob4 Please assign it to me
