### ISSUE TITLE
🚀 Feature: Pull functions code from CLI

### ISSUE THREAD

**Issue by Rjuilliot** [appwrite/appwrite#4565]
### 🔖 Feature description

Being able to pull functions code from CLI / download code from a specific deployment

### 🎤 Pitch

I think being able to pull / access deployed functions code from an appwrite project could add a lot of flexibility.

As an example, I took back an appwrite project from another developer, who didn't push his code on a git repo, and found myself stuck and unable to access code and update functions in a simple way.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Aarush-Acharya** [comment]
Hey I would like to take this up
