### ISSUE TITLE
📚 Documentation:  Retry Build omittance in Client Docs

### ISSUE THREAD

**Issue by 2002Bishwajeet** [appwrite/appwrite#4566]
### 💭 Description

Seems the appwrite docs have `Retry Build` Method inside the client docs which should work only for server SDK.

Refer [here](https://appwrite.io/docs/client/functions?sdk=web-default#functionsRetryBuild)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by 2002Bishwajeet** [comment]
cc @gewenyu99

**Comment by MistaZidane** [comment]
Hello @2002Bishwajeet  Please can you assign the task to me? I would love to work on it. Thanks

**Comment by 2002Bishwajeet** [comment]
Hey @MistaZidane , building appwrite docs are still not public yet, and as discussed with the maintainers it's mostly a spec issue as mentioned [here](https://discord.com/channels/564160730845151244/636852860709240842/1034103168755310673). I believe  they are actively working on it and would be fixed after the hacktoberfest

**Comment by MistaZidane** [comment]
okay thanks.
