### ISSUE TITLE
📚 Documentation: Typos and Grammar fixes

### ISSUE THREAD

**Issue by lakshay-nasa** [appwrite/appwrite#4567]
### 💭 Description

Found some typos and grammar fixes in some files.
1. README.md
2. CONTRIBUTING.md

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@lakshay-nasa, thanks for raising this issue! 🙏 We're already working through cleaning up our docs. If you'd like to contribute for Hacktoberfest, you can try exploring hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/). If you have any problems or need help, please join our [Discord community](https://appwrite.io/discord) and use the `#hacktoberfest` channel.

**Comment by lakshay-nasa** [comment]
@stnguyen90 That's great but I opened a PR for the same.
