### ISSUE TITLE
Able to create a collection type with two params of Same name

### ISSUE THREAD

**Issue by gkathir15** [appwrite/appwrite#458]
Hi team, 
I was just creating a DB Collection, but I was able to create two params of same name, 
I believe its an issue.
![image](https://user-images.githubusercontent.com/9741561/85944496-bd260b80-b954-11ea-9c07-ca66b9451df7.png)

**Comment by eldadfux** [comment]
This issue was fixed and its now available as part of Appwrite 0.12. You can learn more about the new version here: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
