### ISSUE TITLE
🐛 Bug Report: datetime array Attribute in documents does not display correctly in the GUI

### ISSUE THREAD

**Issue by MrWael** [appwrite/appwrite#4580]
### 👟 Reproduction steps

datetime array Attribute in documents does not display correctly in the GUI, but when viewed in JSON the values appears fine.
because of that i am unable to edit the values from the GUI.
![appwrite_arraybug](https://user-images.githubusercontent.com/45597179/198009355-922aa5f3-10f4-4e5a-98d6-6117497b1d14.gif)

### 👍 Expected behavior

The datetime array values should appear correctly in GUI similar to JSON view.

### 👎 Actual Behavior

The datetime array values does not show up in GUI. Instead it shows rows of blank values, and i am unable to edit the values in GUI.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@MrWael, thanks for raising this issue! 🙏🏼 We're working on a rewrite of the Appwrite Console and will make sure this is addressed as part of that.

**Comment by stnguyen90** [comment]
This should be resolved in the new Console (version 1.1.0):

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/1477010/202522700-77ee422d-27db-4c64-91c9-7e7c09de8e36.png">
