### ISSUE TITLE
🐛 Bug Report: No Response when Function Status 500

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4594]
### 👟 Reproduction steps

1. Deploy a function that returns a 500 status code. For example, a node function like:

```javascript
module.exports = async function (req, res) {
  res.json({
    areDevelopersAwesome: true,
  }, 500);
};
```

2. Execute the function

### 👍 Expected behavior

```
{"areDevelopersAwesome": true}
```

is somewhere in the response.

### 👎 Actual Behavior

Response, Stdout, and Stderr are blank.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ks129** [comment]
I'd like to get assigned to it.
