### ISSUE TITLE
🐛 Bug Report: getting Cannot find module 'node-appwrite'

### ISSUE THREAD

**Issue by scshiv29-dev** [appwrite/appwrite#4600]
### 👟 Reproduction steps

make a function and upload using tarball

### 👍 Expected behavior

The function should execute

### 👎 Actual Behavior

 Cannot find module 'node-appwrite' is thrown 

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

the folder structure is main/src/index.js
and package.json is in main/

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@scshiv29-dev thanks for raising this issue! 🙏🏼 A few questions:

1. Did you include node-appwrite in your package.json?
2. What folder were you in when you executed the tar command and what was the exact tar command?

**Comment by stnguyen90** [comment]
@scshiv29-dev if you used the CLI to init the function, I highly suggest using it to deploy the function. The problem you're facing is probably a mismatch in the folder structure of what was archived. Ideally, you should be in the folder with your code and tar it like:

```shell
$ tar -czvf code.tar.gz *
a README.md
a package.json
a src
a src/index.js
```

This will create the proper structure like:

```shell
$ tar -ztvf code.tar.gz
-rw-r--r--  0 steven staff    2174 Aug 24 10:03 README.md
-rw-r--r--  0 steven staff     290 Aug 24 10:03 package.json
drwxr-xr-x  0 steven staff       0 Aug 24 10:03 src/
-rw-r--r--  0 steven staff    1451 Aug 24 10:03 src/index.js
```

**Comment by stnguyen90** [comment]
@scshiv29-dev What version of the CLI do you have? What says that error?

**Comment by scshiv29-dev** [comment]
Error is in the console where the appwrite is hosted there inside the project and inside functions and down there where it shows all the deployments there it says build error and when i click logs it says docker error: killed 
I installed appwrite cli 5 days ago i could tell you exact version in sometime I'm away from my pc .

**Comment by stnguyen90** [comment]
@scshiv29-dev, after the runtime container is killed, would you please run `docker ps -a` and share the output?

The typical reason why a docker container is killed is due to low memory. If you run, `docker compose exec appwrite vars`, what's the value for the following:

```
_APP_FUNCTIONS_MEMORY
_APP_FUNCTIONS_MEMORY_SWAP
```

**Comment by scshiv29-dev** [comment]
this is the command output for docker ps -a
![image](https://user-images.githubusercontent.com/68141773/198815233-7c162719-287c-408a-8343-1c13a72de886.png)


i tried running docker compose exec appwrite vars does not give me an output  ,
![image](https://user-images.githubusercontent.com/68141773/198815249-6334db71-995f-47aa-8cc7-68c3b599dc1a.png)

**Comment by scshiv29-dev** [comment]
@stnguyen90  any update regarding this?

**Comment by stnguyen90** [comment]
@scshiv29-dev oh...you're running via coolify...in order to use docker compose, you need to run it in the directory with the docker-compose.yml, but I'm not really sure where the docker-compose.yml file is on coolify...

Were you able to deploy and execute the default sample code from `appwrite init function`?

Can you check the executor logs?

**Comment by scshiv29-dev** [comment]
no i cant see executor  logs although the logs in coolify do not mention anything

**Comment by stnguyen90** [comment]
@scshiv29-dev, what do you mean you can't see the executor logs?

**Comment by scshiv29-dev** [comment]
@stnguyen90  was finally able to see executor logs with the new coolify update 
![image](https://user-images.githubusercontent.com/68141773/200767567-b8abf43e-f167-4d57-b343-405d55144df5.png)
 this is what i, getting when i push function from cli

**Comment by andrasbacsai** [comment]
I tried to replicate the problem but I could not. Most probably your server ran out of memory and Docker killed Appwrite's docker container.

> @scshiv29-dev, after the runtime container is killed, would you please run `docker ps -a` and share the output?
> 
> The typical reason why a docker container is killed is due to low memory. If you run, `docker compose exec appwrite vars`, what's the value for the following:
> 
> ```
> _APP_FUNCTIONS_MEMORY
> _APP_FUNCTIONS_MEMORY_SWAP
> ```


By default, there is no memory limitation (both variables are empty). Everyone can modify it on their needs in the configuration menu of Coolify.

**Comment by stnguyen90** [comment]
@scshiv29-dev are you still having problems or can this be closed?

**Comment by scshiv29-dev** [comment]
> @scshiv29-dev are you still having problems or can this be closed?

Will try tomorrow and let you know, didn't use appwrite for that project shifted to supabase.

**Comment by stnguyen90** [comment]
@scshiv29-dev, are you still facing this issue or can this be closed now?

Please be advised, we'll need to close this due to inactivity soon.

**Comment by scshiv29-dev** [comment]
> @scshiv29-dev, are you still facing this issue or can this be closed now?
> 
> Please be advised, we'll need to close this due to inactivity soon.

I am not facing the issue now so you can close it
