### ISSUE TITLE
🐛 Bug Report: createFile , Flutter Web

### ISSUE THREAD

**Issue by AhmedHammad0900** [appwrite/appwrite#4608]
### 👟 Reproduction steps

I am using Flutter Sdk (web) to createFiles as it handles large files in chunks ( 5 mb then 5 mb ) .
for Flutter web u can't give the file path , u give bytes so I use FilePicker package to pick the file then get all his bytes ready in memory to upload it ,

when I upload upload around 15 MB File , ( it works well with less than 5 mb file ) it doesn't upload full all bytes , I saw the Metadata of uploaded file after re-downloading it , it contains "IsTruncated": "Yes" , with less bytes size , which mean it's not fully uploaded , it's a video file , so I face alot of problems , I can't seek to in video , so I can't get the benifit of Content-Length header which was added 0.13 , the Content-Length header api call is done well , but cause the file is damaged ( video is damaged ) it doesn't seek to forward or backward and the video is restarted , 

my video file has no problems , cause when I upload it directly through console , it works fine without loss of bytes 

I Hope I can get fast fixing if it's possible as I built my project for months , and now I can't upload videos to my mobile app cause the sdk had a small bug and I wasn't able to fix the error

### 👍 Expected behavior

Upload full file size ( bytes )

### 👎 Actual Behavior

damaged uploading 

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

0.15

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@lohanidamodar, would you be able to help with this?

**Comment by lohanidamodar** [comment]
@stnguyen90 Will do thank you

**Comment by lohanidamodar** [comment]
@AhmedHammad0900 can you share the code you are using to upload file?

**Comment by lohanidamodar** [comment]
@AhmedHammad0900 can you test from this branch?
https://github.com/appwrite/sdk-for-flutter/tree/fix-flutter-web-chunked-upload

**Comment by AhmedHammad0900** [comment]
> @AhmedHammad0900 can you test from this branch? https://github.com/appwrite/sdk-for-flutter/tree/fix-flutter-web-chunked-upload

sorry for being late for reply , I use normal sdk code the upload is done but the metadata for the uploaded file is :
"IsTruncated": "Yes"
it upload full file but for last kbs , they aren't uploaded , for now I Use Dio to upload , with incresing ram limit to can push big files without running out of memory , I am using 0.15 so can't test new sdk which supports only 1.0

**Comment by stnguyen90** [comment]
Closing as this should be fixed now. Feel free to comment if you're still experiencing the problem with the new SDK.
