### ISSUE TITLE
🐛 Bug Report: In Email/Password Authentication, User with the Name 'www' or 'com' will not show in search results when using search by name query.

### ISSUE THREAD

**Issue by MrWael** [appwrite/appwrite#4623]
### 👟 Reproduction steps

In Email/Password Authentication, User with the Name "www" or "com" will not show from search by name query.

Using "dart_appwrite.dart"
`_users.list(search: Query.equal('name', name));`

If name = "www" or "com" _users will be null, even if there are users with that name available.

This user will not show in the search result (List):
![image](https://user-images.githubusercontent.com/45597179/199441611-c51af047-4cd0-4d0e-8480-e4e65ad992e3.png)

This user or any other user will show in the search result (List) normally:
![image](https://user-images.githubusercontent.com/45597179/199437642-f0c79d68-34c2-4332-b2fb-70aa527c51d3.png)

### 👍 Expected behavior

In Email/Password Authentication, Any User with any Name should show in search by name query results, if it match.

### 👎 Actual Behavior

In Email/Password Authentication, If the User have "www" or "com" as name, it will not show in search results even if the search by name query do match the given name.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 🧱 Your Environment

using server API (dart_appwrite.dart)

`dart_appwrite: ^7.1.0`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@MrWael thanks for raising this issue! 🙏

Btw, the search value should just be the value itself rather than a query:

```dart
_users.list(search: name);
```

As for the search results, the behavior you described is expected because the search uses MariaDB's full text search feature which only indexes words greater than 3 characters.

**Comment by MrWael** [comment]
@stnguyen90 thank you for the search information, i could not find that in the Docs.

For the search results as you described, if the Mariadb only allow 4 or greater text to be searchable. Appwrite should not allow values under 4 characters, right?
Or it's just up to the developers to decide.

**Comment by MrWael** [comment]
Thank you
