### ISSUE TITLE
i cant strat server on VPS. How i need to work with CERTIFICATE?

### ISSUE THREAD

**Issue by hopheylalaley84** [appwrite/appwrite#4625]
### 👟 Reproduction steps

AppwriteException: null, HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393)) (0)

### 👍 Expected behavior

AppwriteException: null, HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393)) (0)

### 👎 Actual Behavior

AppwriteException: null, HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393)) (0)

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@hopheylalaley84, Appwrite should generate an SSL certificate automatically assuming you have a domain and you've set `_APP_DOMAIN` and `_APP_DOMAIN_TARGET` to your domain. Please refer to the [Certificates](https://appwrite.io/docs/certificates) docs for some troubleshooting steps. If you're still having problems, please share the Appwrite certificates worker logs.

**Comment by hopheylalaley84** [comment]
root@ivanov:~/appwrite# docker compose logs appwrite-worker-certificates
appwrite-worker-certificates  | Appwrite certificates worker v1 has started
appwrite-worker-certificates  | [notice] Starting worker f00981886434:6:v1-certificates
appwrite-worker-certificates  | [notice] Starting work on (Job{v1-certificates} | ID: d4312471f245cd1d5ed8a73375228672 | CertificatesV1 | [{"project":null,"domain":{"domain":"ivanov.ap84.fvds.ru"},"skipRenewCheck":false}])
appwrite-worker-certificates  | Cannot renew domain (ivanov.ap84.fvds.ru) on attempt no. 5 certificate: Failed to issue a certificate with message: Saving debug log to /var/log/letsencrypt/letsencrypt.log
appwrite-worker-certificates  | An unexpected error occurred:
appwrite-worker-certificates  | There were too many requests of a given type :: Error creating new order :: too many certificates already issued for: fvds.ru: see https://letsencrypt.org/docs/rate-limits/
appwrite-worker-certificates  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
appwrite-worker-certificates  | 
appwrite-worker-certificates  | [notice] (Job{v1-certificates} | ID: d4312471f245cd1d5ed8a73375228672 | CertificatesV1 | [{"project":null,"domain":{"domain":"ivanov.ap84.fvds.ru"},"skipRenewCheck":false}]) has finished
root@ivanov:~/appwrite#

**Comment by hopheylalaley84** [comment]
![image](https://user-images.githubusercontent.com/25245678/199529705-5dc3a80c-36f0-4b3e-a252-e674e0715ef3.png)

**Comment by stnguyen90** [comment]
@hopheylalaley84, Do you have older logs? As the error message says, there's been too many attempts. You'll have to wait and try again later. Feel free to share the new logs once you have them.

**Comment by hopheylalaley84** [comment]
i install apwrite on new hostng but stilд have sertificate probem
<img width="966" alt="image" src="https://user-images.githubusercontent.com/25245678/199611479-7bb5d3ee-1ab9-400c-b40d-9c155fb80861.png">

**Comment by stnguyen90** [comment]
> i install apwrite on new hostng but still have sertificate probem <img alt="image" width="966" src="https://user-images.githubusercontent.com/25245678/199611479-7bb5d3ee-1ab9-400c-b40d-9c155fb80861.png">

This error occurs when you're trying to add a Custom Domain. How many domains do you need for your Appwrite instance? If you only need 1, you shouldn't be adding a Custom Domain in your Appwrite Console and it should only be configured in your .env file. If you really need multiple, you need to add a CNAME record for your Custom Domain to point it to your main domain to resolve this error.

**Comment by hopheylalaley84** [comment]
I don't understand anything. What do I need to do to get it right. The documentation describes work with env and certificates very poorly. I am new in development. 3 days can't install

**Comment by stnguyen90** [comment]
@hopheylalaley84, are you trying to add a Custom Domain via the Appwrite Console?

It might help if you joined our [Discord](https://appwrite.io/discord). Troubleshooting this asynchronously over GitHub is very difficult.

**Comment by stnguyen90** [comment]
Thanks for hopping on our Discord server! As discussed, make sure to set `_APP_DOMAIN` and `_APP_DOMAIN_TARGET` to your domain in your `.env` file.
