### ISSUE TITLE
error when create auth in flutter

### ISSUE THREAD

**Issue by khalifa007** [appwrite/appwrite#463]
the error come when I create account: 

I/flutter ( 9212): Error : DioError [DioErrorType.RESPONSE]: Http status error [403]

**Comment by eldadfux** [comment]
Hey @khalifa007, 403 error (https://appwrite.io/docs/error-codes) usually mean that your app is not listed in your project platforms. Make sure to add it with your correct bundle or package ID from your project dashboard.

![image](https://user-images.githubusercontent.com/1297371/86135257-3c514600-baf3-11ea-8674-3cfc20610d0d.png)
