### ISSUE TITLE
🐛 Bug Report: Can't authenticate with any user after blocking one the users

### ISSUE THREAD

**Issue by merabtenei** [appwrite/appwrite#4637]
### 👟 Reproduction steps

Have 3 users in console userA, userB, admin.
Block userA.
I'm using flutter so what I did is try to connect with the blocked user userA using :
```dart
await account.deleteSessions();
final session =
    await account.createEmailSession(email: 'userA@gmail.com', password: password);
final user = await account.get();
```
This results in a 401 unauthorized error as expected.
Now try to login with admin or userB using the same code, and it still returns 401 unauthorized.

EDIT: Things seem to work as expected after I removed the line:
```dart
//await account.deleteSessions();
```
I can reproduce it with that line but without it things seem to work as expected.
### 👍 Expected behavior

Ability to login with the non blocked users (status=true).

### 👎 Actual Behavior

After first 401 unauthorized we can't login with any other user.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by merabtenei** [comment]
EDIT: Things seem to work as expected after I removed the line:
```dart
//await account.deleteSessions();
```
I can reproduce it with that line but without it things seem to work as expected.

**Comment by stnguyen90** [comment]
@merabtenei thanks for creating this issue! 🙏 Is the `account.deleteSessions()` line throwing an exception preventing the rest of the code to execute?

**Comment by merabtenei** [comment]
You are right, trying to logout when no account is logged in throw an Exception with the message :
```
User (role: guests) missing scope (account)
```

**Comment by stnguyen90** [comment]
Anything else you need it can this be closed?
