### ISSUE TITLE
🐛 Bug Report: Urgent, Bug in File permissions

### ISSUE THREAD

**Issue by merabtenei** [appwrite/appwrite#4640]
### 👟 Reproduction steps

- Create a bucket with File Level Security with no permissions.
- Add a file with no permissions.
- Login as UserA from SDK
- Call File Preview from SDK all good userA can't see preview.
- Add read permission to UserA, all good userA can now see preview.
- Remove read permission for UserA.
- Call File Preview from SDK and now userA can still see the preview.

### 👍 Expected behavior

UserA should not be able to see the preview anymore

### 👎 Actual Behavior

UserA can successfully get the preview.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@merabtenei thanks for raising this issue! 🙏 Would you please check if the file preview is cached or is it actually fetched from the server?

**Comment by merabtenei** [comment]
I'm using the Flutter SDK, I didn't do any caching on my side, and following the code of SDK, it seems it doesn't cache the preview either.
Waiting to see if anyone can confirm this on Flutter SDK or any other SDK.

**Comment by stnguyen90** [comment]
I can confirm I see this problem. It looks like we cache the preview:

https://github.com/appwrite/appwrite/blob/master/app/controllers/api/storage.php#L785

but we don't check the permissions after something has been added to the cache:

https://github.com/appwrite/appwrite/blob/6c220467b8cb33e3784dc99a580cc322b370f9f1/app/controllers/shared/api.php#L161-L184
