### ISSUE TITLE
🐛 Bug Report: Duplicated Document Error When Updating a Document Multiple Times Fast

### ISSUE THREAD

**Issue by nmcbins** [appwrite/appwrite#4642]
### 👟 Reproduction steps

On web page, I click a button, which causes TWO update_document() requests being sent to TWO different collections in the SAME database. This causes sporadic Appwrite server 500 internal errors - "sporadic" means if I repeatedly click the same button, the error usually goes away after a few clicks. 

### 👍 Expected behavior

Even if there is an error, I did expect the error to be triggered consistently if certain conditions are met. 

This error started happening after updating to Appwrite 1.0.3 from 0.15, and only on windows 10 -- where I have the dev server running.

I updated a production server running on Ubuntu to 1.0.3 and it's running exactly the same configuration, this error never occurs there.

This implies the code / logic works fine. The error has to do with timing of both requests reaching the Appwrite server.

### 👎 Actual Behavior

I worked around the problem, by sequencing the two update_document() requests: sending the 2nd one AFTER receiving the response of the 1st one (inside the then() of response.then())

Appwrite error log shows:
{appwrite  | [Error] Method: PATCH
appwrite  | [Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
appwrite  | [Error] Type: Utopia\Database\Exception\Duplicate
appwrite  | [Error] Message: Duplicated document: Duplicate entry 'ip:172.18.0.1,method:PATCH,url:admin.esn.com/v1/databases/:da...' for key 'unique1'
appwrite  | [Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php
appwrite  | [Error] Line: 533

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for creating this issue! Seems like it has something to do with abuse. We'll look into it and see what's going on

**Comment by stnguyen90** [comment]
Related PR: https://github.com/utopia-php/abuse/pull/37
