### ISSUE TITLE
🐛 Bug Report: Custom Domain fails to verify

### ISSUE THREAD

**Issue by SingHar** [appwrite/appwrite#4651]
### 👟 Reproduction steps

Adding custom domain with Cloudflare managed domains and proxy bypassed CNAME (Grey Cloud), fails at verification.

The documentation states that CNAME should point to `https://subdomain.domain.tld` but CNAME can only contain destination domain WITHOUT schema [Wikipedia](https://en.wikipedia.org/wiki/CNAME_record).

Other DNS providers may also have the same issue but I have not tested with any other provider.

### 👍 Expected behavior

Custom Domain should verify and issue a letsencrypt certificate.

### 👎 Actual Behavior

Custom Domain fails to verify

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Cloudflare for DNS management.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@SingHar thanks for raising this issue! Would you please provide the domains and the exact error you get?

Also, I recommend joining our [Discord](https://appwrite.io/discord) server as it would be much easier to troubleshoot this synchronously rather than asynchronously on GitHub.

**Comment by SingHar** [comment]
Sorry I forgot to mention that I am using a self-hosted instance of AppWrite.

Thanks for Discord invite.

**Comment by stnguyen90** [comment]
@SingHar, would you please provide the domains and the exact error you get?

> Sorry I forgot to mention that I am using a self-hosted instance of AppWrite.

Appwrite is only available self-hosted at the moment 😉 

> The documentation states that CNAME should point to https://subdomain.domain.tld but CNAME can only contain destination domain WITHOUT schema [Wikipedia](https://en.wikipedia.org/wiki/CNAME_record).

What documentation are you referring to?

**Comment by SingHar** [comment]
> would you please provide the domains and the exact error you get?
So, I was trying to add opt.akaal.pw and my appwrite is hosted on db.akaal.biz

> What documentation are you referring to?
I am referring to on-page documentation that pops-up when verifying the domain. Please see the screenshot.

When I click Confirm and Verify, it shows this message

`Domain verification for the requested domain has failed.`

![Documenation Screenshot](https://user-images.githubusercontent.com/7950574/201367965-3b5df77b-aae6-45b8-b4fc-8a0bb2db70e3.png)

> Appwrite is only available self-hosted at the moment
I though that specific domain name(s) must be irrelevant.

**Comment by SingHar** [comment]
Looks like I figured it out.

`_APP_DOMAIN_TARGET` should be hostname only but I was using URL.

Suggestion: You should include small examples with documentation.
![image](https://user-images.githubusercontent.com/7950574/201373925-1f69958d-12c3-4412-919f-f50b4e4b44f9.png)
