### ISSUE TITLE
🚀 Feature: Keycloak OAuth Provider

### ISSUE THREAD

**Issue by Mabenan** [appwrite/appwrite#4653]
### 🔖 Feature description

A new OAuth Provider for the self hosted OAuth Provider Keycloak https://www.keycloak.org/

### 🎤 Pitch

As discussed in https://github.com/appwrite/appwrite/issues/4299 a generic OIDC Provider would be better but takes more time to implement. So I would create an OAuth provider for Keycloak.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Closing for now, happy to reopen if someone is willing to submit a PR.
