### ISSUE TITLE
🚀 Feature: Define columns wanted on SELECT queries

### ISSUE THREAD

**Issue by fliitor** [appwrite/appwrite#4657]
### 🔖 Feature description

Add [Query](https://appwrite.io/docs/databases#querying-documents).select(['colA', 'colB'])

### 🎤 Pitch

To gain some performance & not load useless data

Usecase

- I want a HTML table with 10 of 150 attributes from collections
- I want to check value of only one attribute of document
- I want to join data, but without get all attributes of them

EDIT: Other usecase

[This code](https://github.com/stnguyen90/places/blob/main/appwrite-functions/create-comment/src/index.ts#L53) is used only to check if document exist, no need to push all attributes on network, mariadb cache, etc.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by vedant-z** [comment]
@fliitor May I work on this?
 If so then can you please guide me on how should I proceed?

**Comment by stnguyen90** [comment]
@vedant-z , thanks but this is something the core team will need to discuss and plan.
