### ISSUE TITLE
Count of memberships becomes a negative number

### ISSUE THREAD

**Issue by EricLoi898** [appwrite/appwrite#466]
Hi team,
I was trying to add a new membership, I sent a wrong redirect URL for accepting invitation so I deleted the membership but the count of memberships gets minus by 1 on every deletion, even the membership has not been confirmed

![image](https://user-images.githubusercontent.com/32095513/86433670-f2a06f80-bd2d-11ea-8533-6cd30fddc5d8.png)

**Comment by eldadfux** [comment]
Hey @EricLoi898, thanks for reporting this. We have already created a fix that is waiting for the release of version 0.7

![image](https://user-images.githubusercontent.com/1297371/86433875-83faec00-bd04-11ea-8690-dea622713e19.png)

You can check the full change log here:
https://github.com/appwrite/appwrite/blob/master/CHANGES.md

**Comment by eldadfux** [comment]
v0.7 is out and this fix is now available ✅
