### ISSUE TITLE
Importing test data

### ISSUE THREAD

**Issue by TJMusiitwa** [appwrite/appwrite#468]
If say I finally have my Appwrite instance up and running but for say demo purposes or learning purposes, I would like to import some test data to work with, Is this possible right now or is there a sort of go-around if not currently available that I could work with?

**Comment by eldadfux** [comment]
Currently your Appwrite setup comes completely clean. You can import data to any of your projects by using the Appwrite API itself, nothing built-in for that.

**Comment by TJMusiitwa** [comment]
Oh alrighty then.
