### ISSUE TITLE
🐛 Bug Report: Console 2.0 Param "name" is not optional

### ISSUE THREAD

**Issue by xcashy** [appwrite/appwrite#4689]
### 👟 Reproduction steps

When trying to create a function or a new document in Console 2.0. The error message `Param "name" is not optional` appears although a name is entered.

### 👍 Expected behavior

It should create the Function/Document

### 👎 Actual Behavior

It shows the Error message

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite:1.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@xcashy thanks for raising this issue! 🙏🏼 I was able to successfully create a document. Would you please provide more detail on how to reproduce the problem?

**Comment by xcashy** [comment]
@stnguyen90 I can't explain why, but all of a sudden it works for me. Both documents and functions can be created again.

I tested this directly after updating a test server from 1.0.3 to 1.1.0. For this I followed the instructions from https://appwrite.io/docs/upgrade and also did the migration after the installation was done. After that I created a test database, a collection in it, an attribute of type string (without default value and not required) and tried to create a document. Of course I did not leave the attribute empty.

I was able to find the error logs with `docker logs appwrite`. Maybe these will help:
```
[Error] Timestamp: 2022-11-16T10:53:10+00:00
[Error] Method: POST
[Error] URL: /v1/projects/:projectId/platforms
[Error] Type: Utopia\Exception
[Error] Message: Param "name" is not optional.
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 804
```

**Comment by stnguyen90** [comment]
@xcashy weird...can we close this since it's working now?

**Comment by xcashy** [comment]
I tested a bit more and can't repoduce the problem again. So yes I will close this issue. Thanks.

**Comment by mscottford** [comment]
I just ran into this problem with version 1.2.1. I "fixed it" by refreshing the page and then trying to create the document again. Perhaps this is only an issue in the session where the collection has been first created?

**Comment by stnguyen90** [comment]
@mscottford this should have been fixed, but if you can reproduce the problem, please create a new issue with the exact steps to reproduce.
