### ISSUE TITLE
Custom domain validation regex is invalid

### ISSUE THREAD

**Issue by shemhazai** [appwrite/appwrite#470]
When adding a new custom domain to a project the entered string is validated in the browser against this pattern: **^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9](?:\.[a-zA-Z]{2,})+$** which fails on domains such as **appwrite.sub-domain.com** (with a dash in the middle).

## Dialog

<img width="682" alt="Screenshot 2020-07-07 at 22 42 55" src="https://user-images.githubusercontent.com/13630257/86840755-67173d80-c0a3-11ea-96c6-a7078d3427e1.png">

## Console

<img width="671" alt="Screenshot 2020-07-07 at 22 44 53" src="https://user-images.githubusercontent.com/13630257/86840916-9037ce00-c0a3-11ea-9a30-b304c39ef5a8.png">

**Comment by eldadfux** [comment]
Yeh, I can validate this issue is a legit bug. This Regex seems to be working better: https://regexr.com/581g6 for validating domains.

Unless any other feedbacks, I'll push this to the master for next version (0.7).

**Comment by shemhazai** [comment]
Thx for quick answer - I did some research and regex from https://regexr.com/581g6 seems to fail on domains with underscores. I don't know yet possible consequences but maybe it would be more beneficial to allow less strict rules (even if some invalid domains would pass validation), e.g. regex from here: https://www.regextester.com/98069 (at least) doesn't fail on valid domains.

**Comment by eldadfux** [comment]
Had to make some adjustments on the server validation as well, but managed to submit a PR:
https://github.com/appwrite/appwrite/pull/471/files
