### ISSUE TITLE
🐛 Bug Report: output of running appwrite prints /usr/src/code/

### ISSUE THREAD

**Issue by loftwah** [appwrite/appwrite#4700]
### 👟 Reproduction steps

When I run the initial steps to run Appwrite

```bash
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.1.0
```

### 👍 Expected behavior

It should print out a relative path to the `docker-compose.yml` file, or the current working directory. I only raise this because when I went to run `docker compose down` I looked for the file there, which didn't exist.

### 👎 Actual Behavior

It prints out

```bash
Running "docker compose -f /usr/src/code/appwrite/docker-compose.yml up -d --remove-orphans --renew-anon-volumes"
```

The point of the issue is that `/usr/src/code/` probably shouldn't be printed here.

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

No.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for raising this issue! 🙏🏼 

> It should print out a relative path to the docker-compose.yml file, or the current working directory

That's going to be tough to do considering the entire execution happens in a docker container that doesn't have any idea about the host machines folders... 🧐

**Comment by loftwah** [comment]
> Thanks for raising this issue! 🙏🏼
> 
> > It should print out a relative path to the docker-compose.yml file, or the current working directory
> 
> That's going to be tough to do, considering the entire execution happens in a docker container that doesn't have any idea about the host machines folders... 🧐

I'd go with a relative path because if you remove `/usr/src/code/` from the output, it prints a valid command that can be entered in the same directory they launched Appwrite from.
