### ISSUE TITLE
🐛 Bug Report: Missing 'Create' from bucket permission settings

### ISSUE THREAD

**Issue by MaddPenguin** [appwrite/appwrite#4708]
### 👟 Reproduction steps

Fresh install v1.1.0

### 👍 Expected behavior

Be able to tick on 'Create'

### 👎 Actual Behavior

No 'Create' option for permission and not able to upload file to the bucket

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.1.0
Linode ubuntu 22.04

![Screenshot from 2022-11-16 22-09-34](https://user-images.githubusercontent.com/60058928/202343782-8b10b2b4-3610-49f5-9226-5102d06bfcd0.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This should be fixed in [1.1.1](https://github.com/appwrite/appwrite/releases/tag/1.1.1):

![image](https://user-images.githubusercontent.com/1477010/202813886-62aaf2ca-c7ae-4ccf-9d02-01a8f84ec812.png)
