### ISSUE TITLE
🐛 Bug Report: Query.search on array gives unwanted results (with space or hyphen)

### ISSUE THREAD

**Issue by Gustl22** [appwrite/appwrite#4717]
### 👟 Reproduction steps

Create a collection with an array attribute
Do a fulltext index on that attribute.
E.g. the attribute `characteristics` | string[]
With its possible string values: `characteristics-one`, `characteristics-two`, ...

Now if I do a query on client (flutter): 
```
await databases.listDocuments(
        databaseId: 'default',
        collectionId: myCollectionId,
        queries: [
          Query.search('characteristics', 'characteristics-one'),
        ]);
```
I get the results below....

I think the hyphen is replaced as a space and then it simply searches for the whole prefixed word which gives more results, which should't be included.

May relevant: #3033
May implementing #2838 can better handle this case.

### 👍 Expected behavior

I should get the result:
```
{
  $id: "61bf31c49afbd",
  ...,
  data: {
    "titleIDs": ["some-id-1"],
    "characteristics": ["characteristics-one"],
   },
}
```

### 👎 Actual Behavior

I get the results:
```
{
  $id: "61bf31c49afbd",
  ...,
  data: {
    "titleIDs": ["some-id-1"],
    "characteristics": ["characteristics-one"],
   },
},
{
  $id: "61bf31c04d56c",
  ...,
  data: {
    "titleIDs": ["some-id-2"],
    "characteristics": ["characteristics-two"],
   },
},
```

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite: v:1.0.3.501
I disabled the protection / antivirus containers, but nothing special.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Gustl22, thanks for raising this issue! 🙏🏼 Would you please try replacing the value with: `Query.search('characteristics', '"characteristics-one"')` and see what the result is?

**Comment by Gustl22** [comment]
Nice, with quotes it works as expected. Thx ;D
