### ISSUE TITLE
🐛 Bug Report: OAuth2 Settings URI in the console is incorrect

### ISSUE THREAD

**Issue by RazorRSD** [appwrite/appwrite#4721]
### 👟 Reproduction steps

goto appwrite console
add auth2 provider 
call it from a web SDK
when I was using URI on the console for discord auth it returned an invalid URI error.

### 👍 Expected behavior

It needs to redirect back to the website called the auth provider.

### 👎 Actual Behavior

when I was using URI on the console for discord auth it returned an invalid URI error.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

i'm using web sdk with next js

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@RazorRSD thanks for raising this issue! 🙏🏼 

Looks like the URI in the Console shows:

```
https://localhost/v1/account/session/oauth2/callback/amazon/test
```

but it should be `sessions` like:

```
https://localhost/v1/account/sessions/oauth2/callback/amazon/test
```

![image](https://user-images.githubusercontent.com/1477010/202776309-75f87746-f8ff-4cde-9b66-bc6e81eef198.png)

**Comment by jatinmark** [comment]
I want to work on this issue can you assign it to me .

**Comment by stnguyen90** [comment]
@jatinmark assigned! Thanks for your interest!

**Comment by jatinmark** [comment]
Ok
