### ISSUE TITLE
🐛 Bug Report: Console Trimmed ID is Reversed

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4722]
### 👟 Reproduction steps

1. Create a document with Document ID `2022.11.12__11.33.35__451812`

### 👍 Expected behavior

The Document ID shows as `...11.33.35__451812`

### 👎 Actual Behavior

The Document ID shows as `...11.33.35__2022.11.12`.

![image](https://user-images.githubusercontent.com/1477010/202783297-50b810d3-e314-4819-aac3-6a4b6af19629.png)

It looks like the `direction:rtl` in [`[u-trim-start]`](https://github.com/appwrite/ui/blob/style-level-4/packages/ui/src/_9-utilities.scss#L24) causes the text to reverse.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Tested on Appwrite 1.1.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by vyomaaverse** [comment]
I would like to work on this issue. Can this be assigned to me?

**Comment by stnguyen90** [comment]
@vyomaaverse assigned! Thanks for your interest! 🙏🏼 

FYI, I think the best approach would be to :

1. remove the `u-trim-start` class [here](https://github.com/appwrite/console/blob/d0c5079332c0c5016cbc3e4e45c49babdd6f7a01/src/routes/console/project-%5Bproject%5D/databases/database-%5Bdatabase%5D/collection-%5Bcollection%5D/%5B%5Bpage%5D%5D/%2Bpage.svelte#L68).
2. Add the `trim` flag to the `Pill` [here](https://github.com/appwrite/console/blob/d0c5079332c0c5016cbc3e4e45c49babdd6f7a01/src/routes/console/project-%5Bproject%5D/databases/database-%5Bdatabase%5D/collection-%5Bcollection%5D/%5B%5Bpage%5D%5D/%2Bpage.svelte#L66).

When making your PR, please make sure to include a screenshot of how it looks! 🙏🏼

**Comment by vyomaaverse** [comment]
got it, thanks @stnguyen90

**Comment by stnguyen90** [comment]
@vyomaaverse, how's your progress on this?

**Comment by stnguyen90** [comment]
@vyomaaverse, how's your progress on this?

**Comment by stnguyen90** [comment]
Unassigning due to inactivity.

**Comment by imtushardave** [comment]
@stnguyen90  is this still open?

**Comment by stnguyen90** [comment]
@imtushardave, yes, would you like to work on it?

**Comment by BelferMan** [comment]
@stnguyen90 
If its still unassigned, I will glad to take it.

**Comment by imtushardave** [comment]
Thanks @stnguyen90, I am on it

**Comment by imtushardave** [comment]
> @vyomaaverse assigned! Thanks for your interest! 🙏🏼
> 
> FYI, I think the best approach would be to :
> 
> 1. remove the `u-trim-start` class [here](https://github.com/appwrite/console/blob/d0c5079332c0c5016cbc3e4e45c49babdd6f7a01/src/routes/console/project-%5Bproject%5D/databases/database-%5Bdatabase%5D/collection-%5Bcollection%5D/%5B%5Bpage%5D%5D/%2Bpage.svelte#L68).
> 2. Add the `trim` flag to the `Pill` [here](https://github.com/appwrite/console/blob/d0c5079332c0c5016cbc3e4e45c49babdd6f7a01/src/routes/console/project-%5Bproject%5D/databases/database-%5Bdatabase%5D/collection-%5Bcollection%5D/%5B%5Bpage%5D%5D/%2Bpage.svelte#L66).
> 
> When making your PR, please make sure to include a screenshot of how it looks! 🙏🏼

Hi @stnguyen90  , I tried to follow the changes that you pointed out. But seems like it is not producing the expected result.

<img width="550" alt="Screenshot 2023-03-19 at 10 19 09 AM" src="https://user-images.githubusercontent.com/31912898/226154438-1b1798ea-b93c-4018-b1ef-c07d536fad0a.png">

As you can see the document id **order is fixed** but it is not trimming from the start. 
Is there any flag in the `Pill` component to trim from the start? any hint would be helpful.

**Comment by stnguyen90** [comment]
@imtushardave, please make sure you're using the latest Console code. It also might be best to submit a PR to see the actual code.
