### ISSUE TITLE
🚀 Feature: Console - "Execute now" in the "Executions" tab

### ISSUE THREAD

**Issue by ddenev** [appwrite/appwrite#4726]
### 🔖 Feature description

Please add the "Execute now" button to the "Executions" tab as well.
![image](https://user-images.githubusercontent.com/1393766/202799683-a9a20c42-0007-4fcb-b31e-c71809de933c.png)

### 🎤 Pitch

Currently in order to execute a function I have go to the "Deployments" tab and then in order to check the logs I need to switch to the "Executions" tab. When I do this often during testing, this is a lot of clicking and tab-switching.
If you bring the "Execute now" button to the "Executions" tab (also keep it in "Deployments") it would be much easier to do all of this.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by vyomaaverse** [comment]
I would like to work on this issue, can this be assigned to me?

**Comment by jamesqquick** [comment]
Same request on my end. Would be much more convenient to trigger from the Executions page!
