### ISSUE TITLE
🐛 Bug Report: Get User Returns 500 if User Does Not Exist

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4727]
### 👟 Reproduction steps

1. Execute the [Get User](https://appwrite.io/docs/server/users?sdk=nodejs-default#usersGet) API with a User ID that does not exist.

### 👍 Expected behavior

404 error

### 👎 Actual Behavior

500 error.

Appwrite logs:

```
appwrite  | [Error] Timestamp: 2022-11-18T22:01:43+00:00
appwrite  | [Error] Method: GET
appwrite  | [Error] URL: /v1/users/:userId
appwrite  | [Error] Type: TypeError
appwrite  | [Error] Message: Appwrite\Extend\Exception::__construct(): Argument #3 ($code) must be of type ?int, string given, called in /usr/src/code/app/controllers/api/users.php on line 417
appwrite  | [Error] File: /usr/src/code/src/Appwrite/Extend/Exception.php
appwrite  | [Error] Line: 182
```

It looks like we're using the incorrect constructor for the Exception here:

https://github.com/appwrite/appwrite/blob/673b0bb083a5d7e955860bb99766f83a98a5a4f2/app/controllers/api/users.php#L417

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Tested on Appwrite 1.1.1.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by dipakp2726** [comment]
i would like to take on this

**Comment by AnvaySingh** [comment]
Hi, I have generated a pull request for this issue

**Comment by salmantec** [comment]
Hi @stnguyen90 , I could see two PRs for this one issue. Please check and verify it 

[PR-1](https://github.com/appwrite/appwrite/pull/4506) from @karniv00l
[PR-2](https://github.com/appwrite/appwrite/pull/4733) from  @AnvaySingh

**Comment by stnguyen90** [comment]
@AnvaySingh sorry, I forgot about https://github.com/appwrite/appwrite/pull/4506. I think we'll be merging that one over yours since it was submitted first and yours still has a minor problem. So sorry for the hassle! 🫣
