### ISSUE TITLE
🐛 Bug Report: Incorrect Code Samples in Adding Web App Wizard 

### ISSUE THREAD

**Issue by DriedSponge** [appwrite/appwrite#4732]
### 👟 Reproduction steps

Open a project in the Appwrite console then go to Overview > Add Platform > Web App > Get the SDK (step 2) and Let's get coding (step 3)

### 👍 Expected behavior

It should show
```ts
import { Client } from 'appwrite';
```
and on step 3
```ts
const client = new Client()
    .setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2');               // Your project ID
```

### 👎 Actual Behavior

It shows
```ts
import { Appwrite } from 'appwrite';
```
and on step 3
```ts
const appwrite = new Appwrite();

appwrite
    .setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2');               // Your project ID
```

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Windows

### 🧱 Your Environment

N/A

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for raising this issue! 🙏 We'll look into this ASAP!
