### ISSUE TITLE
[HELP-WANTED] Use Maxmind native C extension

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#474]
https://github.com/maxmind/libmaxminddb -> Maxmind native C extension for PHP should introduce improved performance. 

This change should be merged to the `swoole` [branch](https://github.com/appwrite/appwrite/tree/swoole) which contains the most up-to-date versions of our Dockerfiles. This changes should be made for both the [Nginx Dockerfile](https://github.com/appwrite/appwrite/blob/swoole/Dockerfile.nginx) and the [Swoole Dockerfile](https://github.com/appwrite/appwrite/blob/swoole/Dockerfile.swoole) (including the [default Dockerfile](https://github.com/appwrite/appwrite/blob/swoole/Dockerfile) in that branch).

The C extension should replace the [geoip2/geoip2](https://github.com/appwrite/appwrite/blob/swoole/composer.json#L47) package.

Would be great to get some benchmark results for this change.

**Comment by snehal199** [comment]
Can I pick this up @eldadfux ?

**Comment by eldadfux** [comment]
@snehal199 yes sure. Please submit the PR against branch `0.7.x`.

**Comment by adi-mohan** [comment]
Hi! Is this issue still open? Can you give me some guidance on how to do this. Most of the links provided here are broken. I saw geoip2 listed in composer.json. Am still a beginner in open-source. Thanks!

**Comment by hack3r-0m** [comment]
I would like to work on this issue

**Comment by eldadfux** [comment]
Hey @adi-mohan, I have just spoke with @hack3r-0m about this issue minutes before you message. Would love to assign you any other issue you might be able to help with. Feel free to reach me out on Discord: https://appwrite.io/discord

**Comment by adi-mohan** [comment]
Ok. Np. I would like to work on #547 if it is still open.

**Comment by eldadfux** [comment]
@adi-mohan checking for you on the issue page...

**Comment by eldadfux** [comment]
Changes merged, thanks to @hack3r-0m for the amazing work on this. This update will be included in the next 0.7 release 🥳

**Comment by eldadfux** [comment]
@hack3r-0m awesome work on this one! This upgrade is now available as part of v0.7 🥳

❤️
