### ISSUE TITLE
🐛 Bug Report: Editing of function variables does not work

### ISSUE THREAD

**Issue by gorootde** [appwrite/appwrite#4743]
### 👟 Reproduction steps

1. Go to a function's settings
2. Create a variable `XYZ`
3. Save the variable
4. Create new variable
5. Bug! The variable name and value of `XYZ` are still displayed in the dialog
6. Cancel dialog
7. Refresh page
8. Click three dots next to `XYZ` and choose edit
9. Bug! The text fields are empty

### 👍 Expected behavior

1. The dialog box is empty when creating new variables
1. The context of the variable edit dialog matches the variable that is edited

### 👎 Actual Behavior

See reproduction steps

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Local appwrite instance deployed via docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for raising this issue! 🙏🏼 We'll look into it ASAP!
