### ISSUE TITLE
📚 Documentation: Describe how appwrite API can be invoked directly

### ISSUE THREAD

**Issue by gorootde** [appwrite/appwrite#4744]
### 💭 Description

The documentation should contain a description on how to invoke appwrite APIs without using the appwrite client SDK. e.g. using `curl`.

This would enable one to quickly debug using tools like postman or thunderclient.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gorootde btw, this is partially covered [here](https://appwrite.io/docs/sdks#noSDK). Our REST API docs also documents the HTTP method, URL, and parameters. Lastly, we are working on [REST API docs](https://github.com/appwrite/docs/pull/297/files) to further clarify how to prepare HTTP requests.

**Comment by stnguyen90** [comment]
Closing as this is now available: https://appwrite.io/docs/rest

**Comment by gorootde** [comment]
Super cool @stnguyen90 , thanks a lot!
