### ISSUE TITLE
[HELP-WANTED] Replace our QR code generator library

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#475]
We are currently using: https://github.com/Bacon/BaconQrCode for generating QR codes. This library is great but introduces a lot of 3rd party dependencies we would like to reduce, and don't seemed to be actively maintained anymore. We want to replace it with this lib: https://github.com/chillerlan/php-qrcode which seems a lot lighter and more active.

**Comment by PedroCisnerosSantana** [comment]
Hello @eldadfux I think this issue could be good for me to make some real php code :P 
Could you please assign it to me?

Thanks

**Comment by eldadfux** [comment]
Sure @PedroCisnerosSantana that will be very helpful. Please work on the 0.7 branch, and let me know if you have any question :)

**Comment by PedroCisnerosSantana** [comment]
Thanks @eldadfux I'd love to be your young padawan :P

**Comment by eldadfux** [comment]
@PedroCisnerosSantana Got any chance to work on this? let me know if you need help

**Comment by PedroCisnerosSantana** [comment]
@eldadfux will contact you in private later

**Comment by anuragagarwal561994** [comment]
Is this issue being worked upon, or up for grab? I was thinking to take this up if possible.

**Comment by PedroCisnerosSantana** [comment]
Hello @anuragagarwal561994 I'm working on it, if you want to help you can reach me out on our discord server :D

**Comment by ealvarez968** [comment]
@PedroCisnerosSantana whats your discord server I would like to help

**Comment by eldadfux** [comment]
Hey @PedroCisnerosSantana, any updates? Would you like me to re-assign this?

**Comment by PedroCisnerosSantana** [comment]
Hello @eldadfux I think it's completed, I just need your help to test it out :D

**Comment by eldadfux** [comment]
@PedroCisnerosSantana No problem, submit a PR and lets check it out together.

**Comment by PedroCisnerosSantana** [comment]
Hello @ealvarez968 the link is on the README, but here you have it https://discord.gg/GSeTUeA :)

**Comment by PedroCisnerosSantana** [comment]
@eldadfux As soon as I arrive home will make a PR, do you want me to make the PR to a specific branch?

**Comment by eldadfux** [comment]
@PedroCisnerosSantana awesome work on this one!! this fix is now available with the release of Appwrite 0.7! 🚀
