### ISSUE TITLE
🚀 Feature: Go language support for SDK

### ISSUE THREAD

**Issue by NimishKashyap** [appwrite/appwrite#4750]
### 🔖 Feature description

Currently, SDK support for Golang is missing. I'm not sure if it is currently in development, but it is not available in the docs. 

### 🎤 Pitch

Go is one of the best server-side languages for building microservice applications and writing servers. With the support of Appwrite, Golang's service creation will become much more streamlined.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for opening this issue! 🙏 This looks like a duplicate of https://github.com/appwrite/sdk-generator/issues/8. If so, would you please 👍 that issue and close this issue?

**Comment by NimishKashyap** [comment]
Okay thanks!
