### ISSUE TITLE
🐛 Bug Report: Missing Usage

### ISSUE THREAD

**Issue by Shiba-Kar** [appwrite/appwrite#4751]
### 👟 Reproduction steps

Followed https://appwrite.io/docs/upgrade to migrate from 1.0.0 ---> 1.1.1

### 👍 Expected behavior

No errors

### 👎 Actual Behavior

```
[PDO] MySQL connection restarted
[PDO] MySQL connection restarted
Failed: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'value' at row 1
#0 /usr/src/code/src/Appwrite/Extend/PDOStatement.php(88): PDOStatement->execute(NULL)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(532): Appwrite\Extend\PDOStatement->execute()
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1367): Utopia\Database\Adapter\MariaDB->createDocument('stats', Object(Utopia\Database\Document))
#3 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(421): Utopia\Database\Database->createDocument(Object(Utopia\Database\Document), Object(Utopia\Database\Document))
#4 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(503): Appwrite\Usage\Calculators\TimeSeries->createOrUpdateMetric('1', '2022-11-22T00:0...', '1d', 'files.635186b3b...', -1083011, 0)
#5 /usr/src/code/src/Appwrite/Usage/Calculators/TimeSeries.php(528): Appwrite\Usage\Calculators\TimeSeries->syncFromInfluxDB('files.bucketId....', Array, Array)
#6 /usr/src/code/app/tasks/usage.php(132): Appwrite\Usage\Calculators\TimeSeries->collect()
#7 /usr/src/code/vendor/utopia-php/cli/src/CLI/Console.php(208): {closure}()
#8 /usr/src/code/app/tasks/usage.php(137): Utopia\CLI\Console::loop(Object(Closure), 30)
#9 /usr/src/code/vendor/utopia-php/cli/src/CLI/CLI.php(233): {closure}()
#10 /usr/src/code/app/cli.php(32): Utopia\CLI\CLI->run()
#11 {main}
```

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Shiba-Kar did you run the migrate command after upgrading?

**Comment by Shiba-Kar** [comment]
yes

**Comment by netapy** [comment]
Same issue here. Occurs even after the migrate command.

**Comment by stnguyen90** [comment]
I think this error occurs when value is a negative number. The odd thing, is it shouldn't be negative because it's a sum...

**Comment by netapy** [comment]
Are there any quick fixes or scripts we could execute to maybe reset all the stats ? 
I'm still stuck with the wrong info.

**Comment by johnfidel98** [comment]
same here... got the same error

**Comment by Monzim** [comment]
Same issue

**Comment by stnguyen90** [comment]
No workaround at the moment. We have a rewrite underway to improve the usage stats.

**Comment by fliitor** [comment]
Quick fix, if you've access to mariaDB

```
ALTER TABLE _1_stats
	CHANGE COLUMN value value BIGINT(20) NULL DEFAULT NULL AFTER region;
```

=> Need to remove UNSIGNED on value column
NB: `_1_stats` table name can change, here it's mean "stats table of database 1"

For debug purppose @stnguyen90, here negative stats. Error happend after deleted some documents

![image](https://github.com/appwrite/appwrite/assets/117680686/c84836c7-0c27-4ac8-bdde-a3965609e317)
