### ISSUE TITLE
🐛 Bug Report: redirect to the failure url instead of throwing an error in OAuth2

### ISSUE THREAD

**Issue by gepd** [appwrite/appwrite#4753]
### 👟 Reproduction steps

1. Login with any OAuth2 Provider
2. Block the user in the console
3. Login with the OAuth2 provider again

### 👍 Expected behavior

I would expect to be redirected to the failure url. I have some doubt about if the failure url should have any extra information as for example, we have `USER_BLOCKED`, `USER_MISSING_ID`, `GENERAL_SERVER_ERROR` and many other errors, and go to the failure url without any other data will be too generic

### 👎 Actual Behavior

Currently if we block a user and this user try to login with any OAuth2 provider, you will get a scarry 401 error.
The current implementation makes imposible to catch this error

I have also noted that the error trace shows a lot of information, and some of them could be sensitive.

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/7091609/203394630-06b2ca6c-c4c0-46bb-8431-3f7d34d64b62.png">

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gepd, thanks for raising this issue! 🙏🏼 Let me discuss this with the team

**Comment by stnguyen90** [comment]
Related issue: https://github.com/appwrite/appwrite/issues/2591
