### ISSUE TITLE
🐛 Bug Report: Index creation. All previews values changed to the value of the last attribute which was added

### ISSUE THREAD

**Issue by AlimFreight** [appwrite/appwrite#4762]
### 👟 Reproduction steps

When creating this index I encountered a strange behaviour of the new console. When I added the second attribute, the value of the first one changed to the value of the second one, and when I created the third one, both the first and the second one changed their names to the third one and so on.
![image](https://user-images.githubusercontent.com/54543689/203445038-28209262-1daf-4349-9fbc-87bbb342d26b.png)

### 👍 Expected behavior

attribute value stayed as it was chosen

### 👎 Actual Behavior

All previews values changed to the value of the last attribute which was added

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

web console

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@AlimFreight, thanks for creating this issue! 🙏🏼 We'll look into this soon!

**Comment by AlimFreight** [comment]
I just want to mention one thought that I had about the creation of the index in general. I think it is not very convenient that we cannot edit the already created index.
