### ISSUE TITLE
🐛 Bug Report: Console - Databases - Impossible to set NULL as value for attribute

### ISSUE THREAD

**Issue by ddenev** [appwrite/appwrite#4768]
### 👟 Reproduction steps

1. Create a collection with 2 attributes:
1.1. a boolean and
1.2. a string that is NOT required and does not have a default value
3. Appwrite creates the string attribute with NULL as default, e.g. this is how a `notes` attribute is created in the `_1_attributes` table by Appwrite (refer to the `default` column):
```sql
INSERT INTO `_1_attributes` (`_id`, `_uid`, `_createdAt`, `_updatedAt`, `_permissions`, `databaseInternalId`, `databaseId`, `collectionInternalId`, `collectionId`, `key`, `type`, `status`, `size`, `required`, `default`, `signed`, `array`, `format`, `formatOptions`, `filters`)
VALUES (18, '2_3_notes', '2022-11-13 15:15:14.337', '2022-11-13 15:15:14.472', '[]', '2', '63710a002df062dcf112', '3', 'accounts', 'notes', 'string', 'available', 4000, 0, NULL, 1, 0, '', '[]', '[]');
```
and this is how the related collection table is created by Appwrite:
```sql
CREATE TABLE IF NOT EXISTS `_1_database_2_collection_3` (
  ...
  `notes` varchar(255) DEFAULT NULL,
  ...
  PRIMARY KEY (`_id`),
  UNIQUE KEY `_index1` (`_uid`),
  UNIQUE KEY `name` (`name`),
  KEY `_created_at` (`_createdAt`),
  KEY `_updated_at` (`_updatedAt`),
  KEY `budget_id` (`budget_id`),
  KEY `next_id` (`next_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4;
```
3. Go to the Console and create a document without entering any value for the attributes (use defaults) => the value for the `notes` attribute is stored as NULL in the DB
4. In the Console update the document and set a value for the `notes` attribute => the value is stored in the DB
5. In the Console update the document and set an empty value for the `notes` attribute => the value `''` (empty string) is stored in the DB

### 👍 Expected behavior

I would expect to be able to store a NULL value for the attribute, following the fact that it was possible to create it with a NULL in the first place.

It is important to be able to store NULLs for attributes as there is a big difference between an empty string and a NULL value.

Idea: maybe you could add a checkbox (with label 'NULL') next to the input box that would allow us to enter NULL values. Checking the checkbox would disable the input field.

### 👎 Actual Behavior

Currently it is not possible to update an attribute with a NULL value after it was updated with a non-NULL and non-empty-string value.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
I am happy to announce that [1.3.0](https://github.com/appwrite/appwrite/releases/tag/1.3.0) is now released with support for NULL values 👏🏻 

You can find more informations in [this blog post](https://dev.to/appwrite/join-celebrations-appwrite-13-ships-relationships-57fc) and [our docs](https://appwrite.io/docs/databases-relationships).
