### ISSUE TITLE
Add Select All Checkbox for on Console API key Scopes Screen.

### ISSUE THREAD

**Issue by punitdiwan** [appwrite/appwrite#477]
Please add Select All Checkbox for on API key Scopes Screen. We have now 13 scopes and will definitely increase in near future. It will be good to have **Select All Checkbox**  
for API key Scopes Screen in Console.

Thanks
Punit

**Comment by eldadfux** [comment]
Work in progress:
![image](https://user-images.githubusercontent.com/1297371/88369815-80a1d000-cd99-11ea-8cd4-72265a92faac.png)

**Comment by eldadfux** [comment]
@punitdiwan thanks for the idea, this feature is now available on v0.7 🥳

**Comment by punitdiwan** [comment]
@eldadfux You are always Welcome
