### ISSUE TITLE
🚀 Feature: Team permission for the whole database

### ISSUE THREAD

**Issue by mbos2** [appwrite/appwrite#4772]
### 🔖 Feature description

Regarding permissions for collections and documents. 

Currently, in the appwrite console, when we create a collection, we have to assign a team(s) or user(s) to update permissions for it, and also set what kind of permissions they need for that collection. 

Since you implemented a support for multiple databases, there could be an option to assign permissions for a team or a user on a database level. 

### 🎤 Pitch

For example, let's say I have team called "Workers" and 2 databases, "Database A" and "Database B". I could just start making collections and attributes, and then go back to the team view, and in the team view choose to set permissions to everything inside "Database A" to Read, and then for everything in "Database B" to Read, Write, Update, Delete.

Or, do that inside a database view.
For example, I open Database A view, there would be permission section, I would go to permissions, pick Team A and set Read and Write, so that permission will automatically be applied to any collection or document that is created inside that database.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hey @mbos2 

Thanks for taking the time to suggest this.

One of our core focuses is to keep things as straightforward as possible, especially when it comes to Permissions. The idea of setting Permissions on Collections as they are created is to ensure that every setting is correctly chosen, and there's less room for errors or misunderstandings.

While the feature you're suggesting isn't a bad idea by any means, it could introduce a new layer of complexity that might confuse developers. Hence, I am closing the issue for now.

Thanks again for opening this and looking forward to read more suggestions and feedbacks from you in future!
