### ISSUE TITLE
🐛 Bug Report: Invalid Origin. Register your new client (com.example.appwritetest) as a new Android platform on your project console dashboard

### ISSUE THREAD

**Issue by kunduarnab** [appwrite/appwrite#4774]
### 👟 Reproduction steps

Code snippet - 
```kotlin
val client = Client(this)
      .setEndpoint(AppwriteConst.API_ENDPOINT)
      .setProject(AppwriteConst.PROJECT_ID)
      .setSelfSigned(true)
val account = Account(client)
Coroutines.io {
    try {
       val response = account.create(
                userId = "unique()",
                email = "arnab@example.com",
                password = "12345678",
                name = "Arnab Kundu"
            )
       Log.d(TAG, response.toMap().toString())
    } catch (e: Exception) {
        e.printStackTrace()
    }
}
```

Error Output - Invalid Origin. Register your new client (com.example.appwritetest) as a new Android platform on your project console dashboard

Note: same code snippet works on older versions of appwrite

### 👍 Expected behavior

It should create an user 

### 👎 Actual Behavior

Throws an error

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Version - 1.1.1
SDK - Android => implementation "io.appwrite:sdk-for-android:1.1.0"
I have just changed the port to 8080

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@kunduarnab please double check to make sure you have the correct project id. In addition have you added your platform as described here: https://appwrite.io/docs/getting-started-for-android#addProject?

**Comment by kunduarnab** [comment]
@stnguyen90 Yes I double checked, added platform. Same code works for me in previous versions but now its not.

**Comment by stnguyen90** [comment]
@kunduarnab hmm, you're right. I think there might be something wrong with the Console for the Android platform. As a workaround, can you try adding a flutter android platform?

**Comment by stnguyen90** [comment]
I think the problem is the console is looking at the wrong property:

https://github.com/appwrite/console/blob/55a6508d2b261faee8400f20a1647d2b3acc998f/src/routes/console/project-%5Bproject%5D/overview/platforms/%5Bplatform%5D/android.svelte#L16

**Comment by kunduarnab** [comment]
@stnguyen90 ok let me try .. I'll let you know if it works

**Comment by kunduarnab** [comment]
@stnguyen90 is there any solution for this problem?... Add flutter platform also not wokring

**Comment by 7216** [comment]
As a workaround adding a web platform with the hostname of "*" seems to fix it?

**Comment by stnguyen90** [comment]
> @stnguyen90 is there any solution for this problem?... Add flutter platform also not wokring

When you update the flutter platform, do you see the value? If not, set it and update it.

**Comment by kunduarnab** [comment]
adding web platform "*" did the trick for me

**Comment by alperenbabagil** [comment]
> @kunduarnab hmm, you're right. I think there might be something wrong with the Console for the Android platform. As a workaround, can you try adding a flutter android platform?

It worked for me too. IOS is working correctly, Flutter platform with Android's package name is also working.

**Comment by wahid-star** [comment]
> adding a web platform with the hostname of "*" seems to fix it

Hello Sir, I'm a beginner and I didn't get this point can you explain me

**Comment by kunduarnab** [comment]
> > adding a web platform with the hostname of "*" seems to fix it
> 
> Hello Sir, I'm a beginner and I didn't get this point can you explain me

Add a new web platform from your project dashboard. and put * in the host name field.

**Comment by chinmaynawkar** [comment]
i am facing same issue for iOS platform any help with this ?
