### ISSUE TITLE
🐛 Bug Report: Create deployment from CLI fails due to extra spacing

### ISSUE THREAD

**Issue by InfiniteVerma** [appwrite/appwrite#4778]
### 👟 Reproduction steps

When deploying a function by copying UNIX code in cmd, the command copied has extra spaces after ```\``` which fails in terminal.

![image](https://user-images.githubusercontent.com/45547198/203827521-c20edda4-1d74-4a18-8215-aa7e6bce862a.png)

### 👍 Expected behavior

Note: After removing spaces:

![image](https://user-images.githubusercontent.com/45547198/203827989-d2b10545-1a9b-40b1-bdd2-614441b16daa.png)

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/45547198/203828049-c789d8f1-f79d-43bc-8ace-207551619fc5.png)

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by arsh-anwr** [comment]
Hey @stnguyen90 can i work on this issue ?

**Comment by TakshPanchal** [comment]
Hey, May I work on this issues?

**Comment by stnguyen90** [comment]
@TakshPanchal sure! Assigned!

**Comment by stnguyen90** [comment]
Actually, @arsh-anwr requested first, so I'm assigning to @arsh-anwr

**Comment by stnguyen90** [comment]
@arsh-anwr, are you still working on this issue? I'll need to unassign you due to inactivity soon.

@TakshPanchal, are you still interested in working on this?

**Comment by arsh-anwr** [comment]
@stnguyen90 I didn't realised that it was assigned to me as there was some confusion in comments.

Sure I can start working on this.

**Comment by arsh-anwr** [comment]
[https://github.com/appwrite/console/pull/432](url)

**Comment by arsh-anwr** [comment]
Hey @stnguyen90 I have raised a PR. Please review it and if you've some more open issues you can assign them to me.

**Comment by Suven-p** [comment]
@arsh-anwr You need to put the `fixes <issue URL>` bit in the first message of the PR
@stnguyen90 shall I close my PR?
