### ISSUE TITLE
🐛 Bug Report: API Keys Update Expiration Date - Incorrect description

### ISSUE THREAD

**Issue by CordMemescape** [appwrite/appwrite#4786]
### 👟 Reproduction steps

1. Select an Appwrite project
2. Click Settings and then View API Keys
3. Click on an API key or create a new one
4. Scroll down to Update Expiration Date

### 👍 Expected behavior

The description of **Update Expiration Date** should reflect a description of the field

### 👎 Actual Behavior

The description of **Update Expiration Date** has the same description as **Update Name**

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/100955529/204027374-727c3bae-8b3f-4845-8570-1118eac2b978.png">
description

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.1.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for catching this! The text should read:

> Set a date after which your API Key will expire.

**Comment by ritiksaxena124** [comment]
Hey, can I work on this issue?

**Comment by stnguyen90** [comment]
@ritiksaxena124, assigned! Thanks for your interest! 🙏

**Comment by ritiksaxena124** [comment]
Made a PR: #4793 to this issue

**Comment by stnguyen90** [comment]
@ritiksaxena124 have you had a chance to create a PR in the [console](https://github.com/appwrite/console) repo?

**Comment by ritiksaxena124** [comment]
I have created a PR in console #250
