### ISSUE TITLE
🐛 Bug Report: Incorrect Origin Created for Non-Web via Wizard

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4787]
### 👟 Reproduction steps

1. Open Appwrite Console
2. Open a Project
3. Scroll down to Integrations > Platforms
4. Click "+ Add platform"
5. Click "Flutter App" (Problem also exists for any non-web platform)
6. Select any platform other than "Web"
7. Fill out "Name" and "Package Name"
8. Click Next

### 👍 Expected behavior

A platform with `key` is created

### 👎 Actual Behavior

A platform with `hostname` is created:

```json
{
  "$id": "6380fe9eab4d20c58b8d",
  "$createdAt": "2022-11-25T17:42:54.701+00:00",
  "$updatedAt": "2022-11-25T17:42:54.701+00:00",
  "name": "Playground for Flutter",
  "type": "flutter-android",
  "key": "",
  "store": "",
  "hostname": "com.example.playground_for_flutter",
  "httpUser": "",
  "httpPass": ""
}
```

This is important because `hostname` is only used when the client is a `web` client:

https://github.com/appwrite/appwrite/blob/a983630e0e6a38e88e5738801057dec5a9ad6c43/src/Appwrite/Network/Validator/Origin.php#L70-L85

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Tested on 1.1.2.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by sulthanalihsan** [comment]
any update for this issue?, or is there any way to solve this problem?

**Comment by TGlide** [comment]
> any update for this issue?, or is there any way to solve this problem?

There's an open PR on the console that aims to solve this issue 🙂
