### ISSUE TITLE
🐛 Bug Report: v1.1.0 appwrite-realtime using all CPU for no reason on a fresh install on debian

### ISSUE THREAD

**Issue by merabtenei** [appwrite/appwrite#4790]
### 👟 Reproduction steps

Installed docker and Appwrite on a fresh VPS instance with 2vCPU and 4GB of RAM.

### 👍 Expected behavior

Minimal CPU  usage

### 👎 Actual Behavior

appwrite-realtime stays at more than 80% CPU usage for an unlimited period of time.
Edit: I reproduced the same scenario two times, but it seems this happens only on the first docker compose up. After doing a docker compose down, and up again the appwrite-realtime service seems to work normally.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for raising this issue! 🙏 Was there a anything in the logs for the realtime container during this high CPU usage?

**Comment by merabtenei** [comment]
I think this can be closed. I might have some misconfiguration on the .env settings that caused that issue. Apologies for any inconvenience.
