### ISSUE TITLE
🚀 Feature: Separate Read and List permissions

### ISSUE THREAD

**Issue by merabtenei** [appwrite/appwrite#4794]
### 🔖 Feature description

Create a separate Permission for listing documents or files. Read will only allow a user to read a file if he knows and provides the ID of that resource.

### 🎤 Pitch

Let's take an example of a chat app like Facebook's messenger I want to be able to forward a file to other users and the user receiving the file can forward it to other users (like emails also). Adding a specific Permission.read(Role(user:ID)) for each user can be tricky and hard to implement. as this should be done using a cloud function to attribute this new Permission.

I suggest to create a separate Permission to allow listing files or documents, while read will only allow reading a document or file if an ID is provided.

What are your thoughts about this ?

Edit: This sounds like a breaking change, but it could be solved by introducing a permission called "RestrictedRead" or something like this that will only allow Read providing an ID (No listing) and keep the Read permission as is without any change.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @merabtenei 

First and foremost, thank you for taking the time to present your suggestion. 

However, I have some concerns regarding its implementation. The example you presented with the chat app might not be directly addressed with the proposed solution. From a design perspective, adding a distinct permission for "RestrictedRead" could introduce additional complexity to the system. My worry is that such a change might bring about potential confusion among developers and users.

I understand the idea behind this feature but the potential complexities and ambiguities might outweigh the benefits. So, it is better to close this for now. If in future, this comes across, we would be more than happy to open the issue again.

Thank you so much once again!
