### ISSUE TITLE
🐛 Bug Report: Verified user can still receive email verifications

### ISSUE THREAD

**Issue by AlexMeesters** [appwrite/appwrite#4797]
### 👟 Reproduction steps

Send a [verification post request](https://appwrite.io/docs/client/account?sdk=web-default#accountCreateVerification ) with a user session that has a verified email.

### 👍 Expected behavior

I expect the service to give a 200 response, and not send any emails. Indicating that verification is already done.
Although the front-end could hide this from the user, its best to never trust the client and let the server do any unnecessary actions.

### 👎 Actual Behavior

It will send a 201 even though the user has been verified, sending another email through SMTP.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

VPS with Debian and Docker. Standard setup

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by tony83033** [comment]
Hi  @AlexMeesters  I am new to open source and appwrite seems a good start to me , can you pls assign this to me

**Comment by yatharth1706** [comment]
Hy, @stnguyen90, Can you assign this to me? Approach for this can be to fetch the user profile from users document and then check if emailVerification is true or false. If its true we can throw error that this user is already verified. If its false we can proceed with the already existing flow.

Also we can do this same in phoneVerification api.

**Comment by stnguyen90** [comment]
Let's create a new 409 error and return that if the user is already verified.

@tony83033, are you still interested in working on this?

**Comment by yatharth1706** [comment]
Hy @stnguyen90 , i wasn't assigned and I made the pull request. Sorry for that. I thought no one was assigned so I made a pull request. Is it a bad ettiquette in open source?

**Comment by yatharth1706** [comment]
Sure @stnguyen90 got your point. Thanks

**Comment by pranjalg13** [comment]
Is this bug closed @stnguyen90 ? (if not let me know if i can work on this, as there is already an open-pr for this)

**Comment by stnguyen90** [comment]
@yatharth1706, I've assigned this to you since there was no response from the previous user.

**Comment by zero-commit** [comment]
is this still open ??

**Comment by stnguyen90** [comment]
Related issue: https://github.com/appwrite/appwrite/issues/6251

**Comment by prashant226** [comment]
can i work on this issue

**Comment by zach28attack** [comment]
@stnguyen90 I commented on that related issue to be assigned. I would like to be assigned to either of these issues if possible. Thank you!

**Comment by meakashdash** [comment]
This issue is still open?

**Comment by guthal** [comment]
Hi, @stnguyen90 is this issue still open i'm willing to contribute for good first issues.
