### ISSUE TITLE
🐛 Bug Report: Endless spinner on auth page

### ISSUE THREAD

**Issue by nadavl** [appwrite/appwrite#4799]
### 👟 Reproduction steps

Install Appwrite `1.1.1` on a Digital Ocean machine which was installed with `1.0.3` before:

```
docker-compose down -v
```
(then remove docker-compose.yml)

```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.1.1
```

### 👍 Expected behavior

I'll get a fresh installation of appwrite.

### 👎 Actual Behavior

Endless spinner on auth page.

![image](https://user-images.githubusercontent.com/5332234/204159237-7b1ee5a9-f760-4aa7-9190-056119fd711c.png)

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

![image](https://user-images.githubusercontent.com/5332234/204159317-25d7ed3c-397a-4ec3-8115-377fa6fb2d0a.png)

![image](https://user-images.githubusercontent.com/5332234/204167899-41fd27e3-560c-41b5-a4dc-a8964ee8c5fc.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@nadavl what was the output of `docker-compose down -v`? what's the output of `docker compose logs appwrite`?

**Comment by nadavl** [comment]
> @nadavl what was the output of `docker-compose down -v`? what's the output of `docker compose logs appwrite`?

Sorry, I have taken the machine down by now as I had to move forward.
I'll close the issue for now.
