### ISSUE TITLE
Installing Appwrite on windows 10 pro

### ISSUE THREAD

**Issue by Shaho87** [appwrite/appwrite#480]
I have installed docker on windows the version is 
 Docker version 19.03.8, build afacb8b

now when I copy paste below command for CMD or power shell I got below error 

PS C:\Users\click> docker run -it --rm ,
>>     --volume /var/run/docker.sock:/var/run/docker.sock ,
>>     --volume ${pwd}/appwrite:/install/appwrite:rw ,
>>     -e version=0.6.2 ,
>>     appwrite/install
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled","StackTrace":"   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__6.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__4.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:line 47\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.HttpApi\\Controllers\\FilesharingController.cs:line 21\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"}.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.
PS C:\Users\click>

Need your kind support .

**Comment by punitdiwan** [comment]
Are u using latest version of Docker Desktop? If not, please install docker desktop for windows.

**Comment by Shaho87** [comment]
Hello, 
Yes its latest version I have installed Yesterday .

**Comment by punitdiwan** [comment]
Try running the docker container as an Administrator by searching cmd in start menu search and right clicking  cmd and choose **Run as Administrator**.

Also pay attention on your system tray, it may give a pop up to allow sharing files. If you get  some thing like this, click **share  button.**

**Comment by Shaho87** [comment]
What I have done was through Admin by using both CMD and Power shell. but
still same error is persist

**Comment by punitdiwan** [comment]
I am using the same docker and able to run 0,6,2 on windows without any problems. Try this steps :

1) Get the 0.6.2  docker-compose.yml content by copying from this link and save it as docker-compose.yml: https://raw.githubusercontent.com/appwrite/appwrite/0.6.2/docker-compose.yml 

2) Run docker-compose up being in same directory where this file is copied.

If it does not work, uninstall docker and reinstall again and try. May be docker was not installed properly.

**Comment by eldadfux** [comment]
Try this docker-compose.yml:
https://appwrite.io/docker-compose.yml?version=0.6.2

The previous one mentioned by @punitdiwan  is for building from source, and requires cloning the Appwrite repo.

**Comment by eldadfux** [comment]
@Shaho87 you can also take a look here: https://stackoverflow.com/questions/60754297/docker-compose-failed-to-build-filesharing-has-been-cancelled seems to be the same error you're getting.

**Comment by eldadfux** [comment]
@Shaho87 still need help on this?
