### ISSUE TITLE
🐛 Bug Report: Apple sign in doesn't work

### ISSUE THREAD

**Issue by netapy** [appwrite/appwrite#4806]
### 👟 Reproduction steps

When I set up Apple Sign In following this Appwrite tutorial ([https://dev.to/appwrite/apple-sign-in-with-appwrite-2576](url)), and I try to log in with Apple with a flutter client on both web and iOS, using : 
```
import 'package:appwrite/appwrite.dart';

void main() async {
    final client = new Client();

    client
    .setEndpoint('YOUR_END_POINT')
    .setProject('YOUR_PROJECT_ID');

    final account = Account(client);

    try {
        await account.createOAuth2Session(
            provider: "apple",
            success: "[YOUR_END_POINT]/auth/oauth2/success",
            failure: "[YOUR_END_POINT]/auth/oauth2/failure",
        );
    } catch (error) {
        throw error;
    }
}
```

I am redirected to an apple sign-in page showing the following error : 
<img width="500" alt="image" src="https://user-images.githubusercontent.com/39877685/204849469-7bcad5b6-ac06-49a9-8e88-fa14de1498ad.png">

The url is : `https://appleid.apple.com/auth/authorize?client_id=[[BUNDLE ID]]&redirect_uri=https%3A%2F%2F[[YOUR END POINT]]%2Fv1%2Faccount%2Fsessions%2Foauth2%2Fcallback%2Fapple%2F62e0fcfca3b3c5124f16&state=%7B%22success%22%3A%22https%3A%5C%2F%5C%2F[[SUCCESS URL DOMAIN]]%5C%2F%22%2C%22failure%22%3A%22https%3A%5C%2F%5C%2F[[FAILURE URL DOMAIN]]%5C%2F%23%5C%2Flogin%22%7D&response_type=code&response_mode=form_post&scope=name+email`

AND

When I disable the Apple Sign OAuth2 in from the console, I still get redirected to this page, as if it was still active.

### 👍 Expected behavior

It should sign me in using Apple when the Apple Sign OAuth2 is ON, and not redirect me to Apple Sign In when the Apple Sign OAuth2 is OFF.

### 👎 Actual Behavior

It presents an error described above..

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.1.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@netapy the most common reason why this happens is a mismatch between configured settings in Apple vs Appwrite. You can refer to [this](https://dev.to/appwrite/apple-sign-in-with-appwrite-2576) article for detailed instructions. If you're still having problems, please make sure the Bundle ID you set in Appwrite matches the Identifier of your Service created in Apple.

**Comment by netapy** [comment]
It seems that time fixed it !! 
I didn't touch my configuration for those 2 days and now it doesn't display the error anymore.
Thanks !
