### ISSUE TITLE
🐛 Bug Report: Unable to upload spreadsheets generated by google docs to storage.

### ISSUE THREAD

**Issue by rafagazani** [appwrite/appwrite#4808]
### 👟 Reproduction steps

Create a spreadsheet or doc at https://docs.google.com/
Upload via console or flutter
example:
[test doc appwrite.docx](https://github.com/appwrite/appwrite/files/10138695/test.doc.appwrite.docx)
[test appwrite.xlsx](https://github.com/appwrite/appwrite/files/10138701/test.appwrite.xlsx)

### 👍 Expected behavior

That the file is in storage

### 👎 Actual Behavior

AppwriteException: document_invalid_structure, Invalid document structure: Attribute "mimeType" has invalid type. Value must be a valid string and no longer than 127 chars (400)

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

v:1.0.3.501
Flutter:
appwrite: ^8.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Closing as this should have been fixed in [1.2.0](https://github.com/appwrite/appwrite/releases/tag/1.2.0)
