### ISSUE TITLE
🐛 Bug Report: Wrong toast message

### ISSUE THREAD

**Issue by Rainnny7** [appwrite/appwrite#4810]
### 👟 Reproduction steps

Navigate to a user and click the block/unblock button, and look at the toast notification in the corner, it will show the opposite of the action performed:

Blocking an account will show unblocked in the notif, and vise-versa

### 👍 Expected behavior

It should display blocked when blocked, and unblocked when unblocked

### 👎 Actual Behavior

Explained in reproduction steps

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite and Appwrite SDK are on 1.1.2 and the env is not customized

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by CoderMayhem** [comment]
This issue has already been fixed, as discussed in the closed [PR](https://github.com/appwrite/console/pull/202) thread above. See [here](https://github.com/appwrite/console/commit/f29d619506e4bdc49aa1ee607271b06f12377ccb#diff-3608cdb09684e30fd934b2610413569a1a91f64219d6028e2842d23b735e6c57). This issue can be closed if no further work is required on this. cc:  @stnguyen90
