### ISSUE TITLE
🐛 Bug Report: disk quota exceeded

### ISSUE THREAD

**Issue by Pranavprana** [appwrite/appwrite#4811]
### 👟 Reproduction steps

after editing .env
and executing this command
docker compose up -d

### 👍 Expected behavior

it's should recreate and start docker 

### 👎 Actual Behavior

Error response from daemon: disk quota exceeded

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

am using webdock.io 5thread 5GB ram 50GB SSD
Linux LXD vps ubuntu 22.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Pranavprana perhaps docker is at its limit. Can you try `docker system prune` to clean out some unused data?

**Comment by stnguyen90** [comment]
@Pranavprana has your problem been resolved? Please note, I'll need to close this due to inactivity soon.

**Comment by Pranavprana** [comment]
yess
