### ISSUE TITLE
🚀 Feature: Function enviroment vars global to project

### ISSUE THREAD

**Issue by dcowan-london** [appwrite/appwrite#4812]
### 🔖 Feature description

Function variables available for all functions in a project. And possibly across all projects in an organisation?

### 🎤 Pitch

I currently need to set the APPWRITE_FUNCTION_ENDPOINT and APPWRITE_FUNCTION_API_KEY for every function individually to allow the function to talk to Appwrite. There are many other variables that may be the same for all (or most) functions in a project, for example I often set a database ID.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@dcowan-london, this looks like a duplicate of https://github.com/appwrite/appwrite/issues/3530. If so, would you please close this issue and 👍🏼 https://github.com/appwrite/appwrite/issues/3530?

**Comment by dcowan-london** [comment]
Yes, sorry - duplicate of #3530 - not sure how I didn't catch that one!
