### ISSUE TITLE
🐛 Bug Report: Creating an api key results in "param name is not optional"

### ISSUE THREAD

**Issue by donnyroufs** [appwrite/appwrite#4817]
### 👟 Reproduction steps

1. Go to integrate with your server
2. Click API key
3. Fill in a name 

### 👍 Expected behavior

It should continue to the next step.

### 👎 Actual Behavior

it tells me "param name is not optional"

![image](https://user-images.githubusercontent.com/48981403/205714924-63a61b99-626c-4f2a-9c7c-5dffc78e83a3.png)

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@donnyroufs, thanks for creating this issue! 🙏🏼 

I tried to recreate your error, but I was able to proceed to the App Scopes step on Chrome. Are you on Appwrite 1.1.2? What browser are you on? Can you provide any more details?

**Comment by donnyroufs** [comment]
> @donnyroufs, thanks for creating this issue! 🙏🏼
> 
> I tried to recreate your error, but I was able to proceed to the App Scopes step on Chrome. Are you on Appwrite 1.1.2? What browser are you on? Can you provide any more details?

Hey 👋

I am running Chrome (Version 108.0.5359.94 (Official Build) (64-bit)) and Appwrite on version 1.1.2. The network tab doesn't show a request so I would assume the error happens during form validation.

**Comment by donnyroufs** [comment]
> Hey @donnyroufs 👋 thank you for bringing this up :)
> 
> Frontend validation is displayed as an error under the input. Errors coming from Appwrite are displayed as a toast notification.
> 
> Can you recheck the network tab and make sure there is nothing there? 🙏


Not sure what happened but it looks like it seems to be working fine right now... Didn't change a thing except for a system reboot. I wonder if another container did interfere somehow. Nonetheless thanks for your time! :)

**Comment by Pranavprana** [comment]
![image](https://user-images.githubusercontent.com/91969851/206852002-99993ff9-5625-4a38-82bc-4231f66f69da.png)
![image](https://user-images.githubusercontent.com/91969851/206852012-61140871-9c54-4e0e-a8c1-587c25a1ecac.png)

**Comment by Mohammad-Ali-Rauf** [comment]
> ![image](https://user-images.githubusercontent.com/91969851/206852002-99993ff9-5625-4a38-82bc-4231f66f69da.png) ![image](https://user-images.githubusercontent.com/91969851/206852012-61140871-9c54-4e0e-a8c1-587c25a1ecac.png)

i got exact same issue
