### ISSUE TITLE
Error when trying to copy an ID in the Console

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4824]
### Discussed in https://github.com/appwrite/appwrite/discussions/4792

<div type='discussions-op-text'>

<sup>Originally posted by **randomloops** November 25, 2022</sup>
### 👟 Reproduction steps

create a new project on a new appwrite instance and try to copy project id

### 👍 Expected behavior

copy project id

### 👎 Actual Behavior

returns error

> Cannot read properties of undefined (reading 'writeText')

![image](https://user-images.githubusercontent.com/41739275/204006512-b972dff2-59c9-4f29-a144-8be562954a51.png)

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)</div>

**Comment by MananShah9** [comment]
Same error... I understand there is a PR for this but how do I get the ID for now?

**Comment by TGlide** [comment]
> Same error... I understand there is a PR for this but how do I get the ID for now?

You can get it from the URL, for example:
If your URL is `https://yourinstance.com/console/project-637331b376ca5e2d0ab0/overview/platforms`, 
then the project ID is `637331b376ca5e2d0ab0`. 

You can similarly find the ID for functions, documents, databases, and collections in the same way:

For an URL `https://yourinstance.com/console/project-639331a476ca5e2d0ab0/databases/database-63215cd1876844f8311e/collection-63415ce7a6a6b5cbac60/document-63a32c569845a3cec616`

You'll have the following IDs:
Project ID is `639331a476ca5e2d0ab0`
Database ID is `63215cd1876844f8311e`
Collection ID is `63215cd1876844f8311e`
Document ID is `63215cd1876844f8311e`

I hope this helps! 😄

**Comment by MananShah9** [comment]
Thanks a lot! I already got it from CLI.
