### ISSUE TITLE
🐛 Bug Report: CORS error running appwrite from GITPOD  

### ISSUE THREAD

**Issue by pinale** [appwrite/appwrite#4835]
### 👟 Reproduction steps

running appwrite from gitpod: https://gitpod.io/#https://github.com/appwrite/integration-for-gitpod
and running my client from a local machine `http://localhost:3000`

### 👍 Expected behavior

i should be able to connect  

### 👎 Actual Behavior

but i get CORS error:
```
Access to XMLHttpRequest at 'http://8080-appwrite-integrationfor-aw81xaz2frd.ws-eu78.gitpod.io/v1/databases/6393396f4e8f0f73436f/collections/63933a1f932c0919674f/documents?queries%5B0%5D=offset%280%29&queries%5B1%5D=limit%2810%29' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

When i setup the enviroment and i've added a `web platform` i've specified as doman:
- \*
- localhost
- localhost\*
- \*localhost\*

tried `http://localhost:3000` as well but the UI doesn't permit me to save  port and schema

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Something else

### 🧱 Your Environment

gitpod: https://gitpod.io/#https://github.com/appwrite/integration-for-gitpod

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@pinale would you please try using HTTPS for the connection to gitpod (ie. https://8080-appwrite-integrationfor-aw81xaz2frd.ws-eu78.gitpod.io/v1)?

**Comment by pinale** [comment]
Yesss, you're right, HTTPS and it works! thanks

**Comment by sunilkush** [comment]
Access to XMLHttpRequest at 'https://cloud.appwrite.io/v1/account' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by sunilkush** [comment]
any one give solution

**Comment by Samrudh713** [comment]
> any one give solution

found solution yet ?
