### ISSUE TITLE
password with "!" fails nginx

### ISSUE THREAD

**Issue by thereapsz** [appwrite/appwrite#484]
as far as i have tested passwords in the docker-compose file that include "!" will make nginx throw errors

**Comment by eldadfux** [comment]
@thereapsz It would be great if you could share an example of problematic docker-compose.yml file.

**Comment by eldadfux** [comment]
@thereapsz is this still relevant?

**Comment by eldadfux** [comment]
After getting report on our Discord server from David Lin, its seems the problematic env var is the SMTP password. Now we can finally confirm this is an active bug. 

We'll probably attempt to fix this by next version.

**Comment by hack3r-0m** [comment]
what is the difficulty level on this issue?

**Comment by eldadfux** [comment]
@hack3r-0m as with all bugs, always hard to tell :)

**Comment by TheNerdyHamster** [comment]
Is anyone currently working on this issue?
I might be interested but gonna do some more research before I take the challange.

**Comment by eldadfux** [comment]
@TheNerdyHamster this issue seems to be the same as this one: https://github.com/appwrite/appwrite/issues/732 which means v0.7 should solve it because we don't use nginx anymore.

**Comment by eldadfux** [comment]
v0.7 is out and this fix is now available ✅
