### ISSUE TITLE
🚀 Feature: Allow Retrying Failed Builds

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4840]
### 🔖 Feature description

Add a way to retry a failed build. In the previous Console, if a build failed, you were able to retry it:

![image](https://user-images.githubusercontent.com/1477010/206788262-c23dbd6e-506a-427d-b7f1-b18911c7841e.png)

In the new Console, there is no Retry Build button. There's even an Activate button, which shouldn't be there if the build failed:

![image](https://user-images.githubusercontent.com/1477010/206788395-eb3c029c-4f2b-4054-b690-7e6de7968b3a.png)

### 🎤 Pitch

The retry build is helpful for cases where the code is correct, but maybe there wasn't enough memory and the build failed.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by therajatrai** [comment]
hey @stnguyen90 Can I work on this issue ?

**Comment by stnguyen90** [comment]
@therajatrai, sure, go for it! For this, if the build failed, we would want to show "Retry Build" and clicking it would call the [Create Build](https://appwrite.io/docs/server/functions?sdk=nodejs-default#functionsCreateBuild) API.

**Comment by therajatrai** [comment]
Okay @stnguyen90. Will push a PR for this asap.

**Comment by stnguyen90** [comment]
@therajatrai, oh also, please use the "Refresh" icon like https://github.com/appwrite/console/blob/f29d619506e4bdc49aa1ee607271b06f12377ccb/src/routes/console/project-%5Bproject%5D/settings/domains/%5B%5Bpage%5D%5D/%2Bpage.svelte#L112 for the Retry Build Icon.

**Comment by therajatrai** [comment]
okay

**Comment by therajatrai** [comment]
@stnguyen90, I was trying t setup the repo over my local machine got the following error

when tried to run 
``` 
docker compose build`
```

```
> [node 4/5] RUN npm ci:
#0 1.922 npm ERR! The `npm ci` command can only install with an existing package-lock.json or
#0 1.923 npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
#0 1.923 npm ERR! later to generate a package-lock.json file, then try again.
#0 1.927
#0 1.927 npm ERR! A complete log of this run can be found in:
#0 1.928 npm ERR!     /root/.npm/_logs/2022-12-17T18_29_47_898Z-debug-0.log
------
failed to solve: executor failed running [/bin/sh -c npm ci]: exit code: 1

```

**Comment by iamr-kumar** [comment]
Hey @therajatrai, are you still working on it?

**Comment by therajatrai** [comment]
@iamr-kumar yes I am working on it. its mostly done

**Comment by stnguyen90** [comment]
@therajatrai, how's your progress on this?

**Comment by therajatrai** [comment]
hey I wasnot well, I am done  with the UI, currently figuring out how to call the backend thing to retry

**Comment by stnguyen90** [comment]
@therajatrai shouldn't this only be a change to the Console repo? 🧐 Have you submitted the PR in that repo?

**Comment by stnguyen90** [comment]
@therajatrai, how's your progress on this? Should I unassign you from this so that someone else can pick it up?

**Comment by stnguyen90** [comment]
Unassigning due to inactivity.

**Comment by singhbhaskar** [comment]
Hi @stnguyen90 ,
If this ticket is unassigned then can I work on this?

**Comment by stnguyen90** [comment]
@singhbhaskar, assigned! Thanks for your interest! 🙏🏼

**Comment by singhbhaskar** [comment]
Hey @stnguyen90 ,
The PR for this issue is merged so we can close this issue.

**Comment by stnguyen90** [comment]
This is pending a console release, which will probably be in Appwrite 1.4

**Comment by magic-peach** [comment]
Hey @stnguyen90 , I’m participating in Hacktoberfest! and I'm new to open source contributions. Can I work on this issue?
