### ISSUE TITLE
🐛 Bug Report: Web Platform Wildcard Behavior

### ISSUE THREAD

**Issue by zdanl** [appwrite/appwrite#4845]
### 👟 Reproduction steps

When I update Hostname of allowed Domains to a Project, I can use *.domain.tld to allow www. but it won't allow domain.tld without www. *domain.tld would scope a security issue. 

### 👍 Expected behavior

Array [domain.tld, *.domain.tld]

### 👎 Actual Behavior

Single Value { *.domain.tld } exclusive of domain.tld

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Scaleway for the newest Appwrite Docker instance.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@zdanl thanks for raising this issue! 🙏🏼 Do you have an example from some other system where you configure 1 rule and it would apply to domain.tld and its subdomains?

**Comment by zdanl** [comment]
Fair point, no. Although it makes sense. Maybe support *.domain.tld, domain.tld instead, if you dislike the idea of 1 rule?

**Comment by stnguyen90** [comment]
> Maybe support *.domain.tld, domain.tld instead

Sorry, what do you mean? You should be able to add a web platform with `*.domain.tld` and another with `domain.tld`.

**Comment by zdanl** [comment]
what if i want a single web platform to support both `*.domain.tld` and `domain.tld`

**Comment by zdanl** [comment]
Not supporting this breaks Appwrite-OAuth2 Callbacks, I think.

**Comment by Meldiron** [comment]
Hey there 👋

Regarding OAuth and other security layers (CORS, secure cookies, ..), they all consider list of all of your hostnames. As long as one of your hostnames allows that specific domain, it will be allowed and configured corectly.

Using multiple platforms for the same domain should not cause any trouble. I understand why you are suggesting this change (simplicity), but similarly to @stnguyen90 , I would be a bit afraid to introduce this until we are confident it is a standard - other providers use the same logic. Appwrite always try to leverage existing developer's knowledge and creating a new (not known wildly) concept would be against it.

**Comment by zdanl** [comment]
We were marketed into the idea that www. is a good idea, and I'm not playing along. I like my corporate and monetary domains, as well as my private ones, https://FQDN.tld not https://www.FQDN.tld - but I prefer to give people the choice, thus my nginx configurations usually allow both, or do a friendly redirect. Such as with HTTPs. 

A new platform for a massively scaling application, in production, is ridiculous.  I'm patching AppWrite locally, and will open a branch with a Changelog. It's 4 significant changes meanwhile.

I would be *very* happy if you could guide me through the source code architecture. I can grep through the code and get an idea, but you see the big picture and have historical context.

**Comment by stnguyen90** [comment]
> A new platform for a massively scaling application, in production, is ridiculous.

Hmm...I'm not sure I understand 🧐 We were suggesting adding another Web Platform to your Appwrite Project in the Appwrite Console:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/1477010/207923268-fd585510-5bca-43ad-a902-648840878ed9.png">

There's only 1 required step for this 👀 

> I would be very happy if you could guide me through the source code architecture. 

Our architecture is documented in our [CONTRIBUTING.md](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md#architecture-1). In addition, the APIs can be found [here](https://github.com/appwrite/appwrite/tree/master/app/controllers/api) and workers can be found [here](https://github.com/appwrite/appwrite/tree/master/app/workers).

**Comment by zdanl** [comment]
That is a very beautiful CONTRIBUTING.md file. I might not have realized what I'm looking at opening it in vi. My bad. 

About a mitigation rather than a inclusive input handling, idk. Thank you.

**Comment by nachoverdon** [comment]
I suggest changing the hostname field so that it accepts multiple urls as well (or maybe just change that, actually). 

I'm currently working on a project that has several domains, and the list of domains keep growing every some time, but all of them point to the same Appwrite project, and I have to add 2 new platforms for each domain.

It'd be great if we could do something like:
Name: My project
Hostnames: [myproject.com, *.myproject.com, myproject.info, *.myproject.info]

or even better
Name: My project
Hostnames: [*.myproject.com, *.myproject.info]

**Comment by gewenyu99** [comment]
> I suggest changing the hostname field so that it accepts multiple urls as well (or maybe just change that, actually).
> 
> I'm currently working on a project that has several domains, and the list of domains keep growing every some time, but all of them point to the same Appwrite project, and I have to add 2 new platforms for each domain.
> 
> It'd be great if we could do something like: Name: My project Hostnames: [myproject.com, *.myproject.com, myproject.info, *.myproject.info]
> 
> or even better Name: My project Hostnames: [*.myproject.com, *.myproject.info]

Add multiple platforms for this.

**Comment by EVDOG4LIFE** [comment]
Marking as stale due to age. 

If this is still valid, I recommend reopening this as a feature request with the use case so we can take a look and potentially open it up for community contributions.
