### ISSUE TITLE
🐛 Bug Report: `expire` is empty from `account.listSessions()`

### ISSUE THREAD

**Issue by devcat-net** [appwrite/appwrite#4846]
### 👟 Reproduction steps

I am implementing a Vue.js application in which I am using the appwrite SDK v. 10.1.0. The appwrite version is 1.1.2. I updated both the SDK and the appwrite version together, and now I am facing the problem that when I send a `listSessions` request to the backend, I don't get a value for the `expire` field. As you can see in the screenshot, I receive data, but the `expire` field is an empty string.

![grafik](https://user-images.githubusercontent.com/36440352/207112927-ddb3e28e-7aa4-4b26-b5ba-fe406e351668.png)

### 👍 Expected behavior

I expect an ISO-formatted Date string

### 👎 Actual Behavior

I receive an empty string.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite v. 1.1.2
Web SDK v 10.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@devcat-net, thanks for creating this issue! 🙏🏼 We changed how we handled the expiration and now calculate it at runtime like:

https://github.com/appwrite/appwrite/blob/8dfdef6006fa5851ffaba0345c33b3c31d6bb3c0/app/controllers/api/account.php#L1449

Looks like we forgot to add that calculation in List Sessions:

https://github.com/appwrite/appwrite/blob/8dfdef6006fa5851ffaba0345c33b3c31d6bb3c0/app/controllers/api/account.php#L1340-L1347

**Comment by CoderMayhem** [comment]
Hey @stnguyen90, I've implemented the suggested change, but can't figure out a way to test it locally. Any help would be much appreciated on the PR.

**Comment by stnguyen90** [comment]
> Hey @stnguyen90, I've implemented the suggested change, but can't figure out a way to test it locally. Any help would be much appreciated on the PR.

You should be able to manually make the API call to test. In addition, you should add a test case to make sure we don't run into the problem again.

**Comment by fanatic75** [comment]
@stnguyen90, I guess the assignee wasn't working. I have fixed the bug and added the assertion in the test case. Please review

**Comment by stnguyen90** [comment]
@CoderMayhem, are you still working on this or can I unassign you?
