### ISSUE TITLE
🐛 Bug Report: Create an API Key: Param "name" is not optional

### ISSUE THREAD

**Issue by schniggie** [appwrite/appwrite#4847]
### 👟 Reproduction steps

When I create a new project and try to add an API key to integrate a server sdk

### 👍 Expected behavior

It should give me an API key.

### 👎 Actual Behavior

It actually fails to process the first step with an Error: Param "name" is not optional. Name field is set and expiration is set to never.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use the docker-compose stack.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@schniggie thanks for creating this issue! 🙏🏼 What version of Appwrite are you on? It seems to work fine for me on Appwrite version 1.1.1.

**Comment by schniggie** [comment]
image: appwrite/appwrite:1.1.2

**Comment by schniggie** [comment]
Ok just realised it works with Safari. Will try to replicate the issue later on the system I encountered it yesterday.

**Comment by gepd** [comment]
This is not a recurrent bug, it seeps to happen when you create a new attribute or in other cases if you refresh the console it will start to work as expected. I'm looking the way to reproduce the error

**Comment by schniggie** [comment]
Yeah I can confirm that. I could not reproduce it.

**Comment by stnguyen90** [comment]
@schniggie, can this be closed since it's no longer a problem?

**Comment by stnguyen90** [comment]
Re-opening because I think it's still a problem. I can reproduce by:

1. Start to create a Web Platform
2. Cancel rather than submitting the platform
3. Try to create a document. 

It looks like this is happening because the [`beforeSubmit` is added as an interceptor to the Wizard](https://github.com/appwrite/console/blob/e31853cea2361658c015a937ca924a5ce1214082/src/routes/console/project-%5Bproject%5D/overview/platforms/wizard/web/step1.svelte#L50), but it doesn't get cleared properly. 

I need to talk to the team about our approach on solving this.

**Comment by Suven-p** [comment]
> I can reproduce by:
> 
> 1. Start to create a Web Platform
> 2. Cancel rather than submitting the platform
> 3. Try to create a document.
> 
This also happens if you replace 3 with trying to create API key or webhook.
![Screenshot from 2023-04-16 19-47-13](https://user-images.githubusercontent.com/47393058/232319010-7185a601-2d29-4116-8bba-7b9c6c8265d8.png)
Apparently it sets name to null.

**Comment by m-thomson** [comment]
Can confirm the exact same behaviour(s) as the previous two commenters.
