### ISSUE TITLE
📚 Documentation: Function Service events same as Storage Service

### ISSUE THREAD

**Issue by TGlide** [appwrite/appwrite#4862]
### 💭 Description

In the [event docs page](https://appwrite.io/docs/events), the table with possible events for the Functions service is currently the same as the one for the Storage service.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by dhruv-solanki** [comment]
Hello there,
Can I work on this issue?

**Comment by TGlide** [comment]
> Hello there, Can I work on this issue?

@dhruv-solanki Sure! Just assigned it to you 😄

**Comment by gewenyu99** [comment]
@TGlide https://github.com/appwrite/docs/pull/314

**Comment by stnguyen90** [comment]
@dhruv-solanki sorry, but we ended up fixing since we haven't heard from you in a while.
