### ISSUE TITLE
🐛 Bug Report: Enter "delete" to continue label on Delete Project Modal

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4863]
### 👟 Reproduction steps

1. Open a Project
2. Open Project Settings
3. Click on Delete in Delete Project section
4. Hover over 'Enter "delete" to continue"
5. Click on 'Enter "delete" to continue'

## Click

The input should focus

## Hover

When hovering over the label, the input should highlight like the Password input:

![image](https://user-images.githubusercontent.com/1477010/207656216-12e13c60-ddb5-4531-b892-1a9a4200c5c7.png)

## Click

The input doesn't focus

## Hover

No highlight effect:

![image](https://user-images.githubusercontent.com/1477010/207656273-d97f5faa-da16-4a4b-b3c2-af6c922538dc.png)

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by MoskalykA** [comment]
I take care of it  👍🏻

**Comment by iswarmondal** [comment]
A suggestion: Can we change the placeholder for `Enter "delete" to continue` input as the label itself

**Comment by pratik-codes** [comment]
is anyone working on it ?

**Comment by Lalman888** [comment]
is this task done?

**Comment by jalajcodes** [comment]
As no one has picked it up, I am working on it.

**Comment by MoskalykA** [comment]
Sorry for not responding, I didn't see the messages, good work jalajcodes!
