### ISSUE TITLE
🐛 Bug Report: (node.js) cloud functions crashing when returning custom status code 

### ISSUE THREAD

**Issue by davidviziteu** [appwrite/appwrite#4879]
### 👟 Reproduction steps

When I try to return status 500 from a cloud function using Node.js, the function crashes.
The following code snippet will crash the function: 
``` javascript
res.json({
      status: 'error',
      error: 'not all env variables are set. check logs for more details'
    }, 500)
```

### 👍 Expected behavior

The following code snipped should return status 400:
``` javascript
console.log('function meant to be triggered only by db create events (before res.json)');
    res.json({
      status: 'error',
      error: 'function meant to be triggered only by db create events'
    }, 400)
    console.log('function meant to be triggered only by db create events (after res.json)');
```

### 👎 Actual Behavior

function finishes with status "error". 
logs:
`function meant to be triggered only by db create events (before res.json)`

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@davidviziteu thanks for raising this issue! 🙏🏼 . The [Create Execution](https://appwrite.io/docs/client/functions?sdk=web-default#functionsCreateExecution) API returns an [Execution Object](https://appwrite.io/docs/models/execution) like:

```json
{
    "$id": "5e5ea5c16897e",
    "$createdAt": "2020-10-15T06:38:00.000+00:00",
    "$updatedAt": "2020-10-15T06:38:00.000+00:00",
    "$permissions": [
        "any"
    ],
    "functionId": "5e5ea6g16897e",
    "trigger": "http",
    "status": "processing",
    "statusCode": 0,
    "response": "",
    "stdout": "",
    "stderr": "",
    "duration": 0.4
}
```

What was the `statusCode`, `response`, `stdout`, and `stderr` for your snippet:

```javascript
console.log('function meant to be triggered only by db create events (before res.json)');
    res.json({
      status: 'error',
      error: 'function meant to be triggered only by db create events'
    }, 400)
    console.log('function meant to be triggered only by db create events (after res.json)');
```

Also you said:

> When I try to return status 500 from a cloud function using Node.js, the function crashes.

Can you explain more? What was the Execution object response?

**Comment by Meldiron** [comment]
Hey there 👋 Calling `res.json` in many (if not all) runtimes results in the HTTP request being responded and ended. Since logs are part of request, all logs done after `res.json` will be missing.

I think we should either force `return` on `json.jsend()` or simply allow `return { ...yourData }`. That way it's clear that there should not be any code after responding to request.

**Comment by stnguyen90** [comment]
@davidviziteu have you had a chance to see my questions? So that you know, we'll need to close this due to inactivity soon.

**Comment by davidviziteu** [comment]
hi! just I managed to look at your question, re-run the tests and the issue (among other front-end issues) is no longer present.
