### ISSUE TITLE
🚀 Feature: Ability to move already exist project into another organization

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#4892]
### 🔖 Feature description

Ability to move already exist project into another another organization.

### 🎤 Pitch

After migrate to version 1.1.0 all already exist project has their own organization.
I can create new project in same organization but can't move already exist projects in to one organization and vice versa.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@usamashafiqs thanks for raising this issue! 🙏🏼 We did notice this was something that would be helpful after the Console 2.0 release! Let me check with the team to see where we are with this.

**Comment by stnguyen90** [comment]
Related PR: https://github.com/appwrite/appwrite/pull/4935

**Comment by felipeavilis** [comment]
Up! This would be a great feature.

**Comment by stnguyen90** [comment]
Closing as this has been added in 1.4
