### ISSUE TITLE
🐛 Bug Report: query works but Index are showing failed

### ISSUE THREAD

**Issue by rohankm** [appwrite/appwrite#4903]
### 👟 Reproduction steps

Hi,
When I create an index for two or more attributes I'm getting "failed" in the dashboard but the index is working fine in queries.

![image](https://user-images.githubusercontent.com/23615452/209406139-c550bb61-b5aa-45e9-8ea2-9de9b3b2be4d.png)

I checked the `appwrite-worker-databases` and here is the output `Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes`

### 👍 Expected behavior

The index should be created successfully.

### 👎 Actual Behavior

The dashboard shows "failed".

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by learnwithalex** [comment]
Delete cache and try again it worked for me

**Comment by stnguyen90** [comment]
@rohankm thanks for creating this issue! 🙏🏼 It seems we aren't filtering out failed indexes here:

https://github.com/appwrite/appwrite/blob/bc2d8c44c5c753926c26d94614aab9e6f2faad8e/src/Appwrite/Utopia/Database/Validator/IndexedQueries.php#L52

**Comment by Ankitchaudharyy** [comment]
I want to work on this issue. Please assign it to me.

**Comment by stnguyen90** [comment]
@Ankitchaudharyy assigned! Thanks for your interest!

**Comment by stnguyen90** [comment]
@Ankitchaudharyy, how's your progress on this? Just so you know, I'll have to unassign you due to inactivity if I don't hear back.

**Comment by BelferMan** [comment]
@stnguyen90 
Will be glad to take it.

**Comment by stnguyen90** [comment]
Unassigning due to inactivity.

@BelferMan, I've assigned it to you. Thanks for your interest! 🙏🏼

**Comment by asmitrai** [comment]
hey, anyone can work on this issue or it needs to be assigned?

**Comment by stnguyen90** [comment]
@asmitrai it's best to be assigned so that we don't have multiple people working on the same thing leading to wasted effort. Would you like to work on this?

**Comment by asmitrai** [comment]
> @asmitrai it's best to be assigned so that we don't have multiple people working on the same thing leading to wasted effort. Would you like to work on this?

Yes, would love to try :)

**Comment by stnguyen90** [comment]
@asmitrai, assigned! Thanks for your interest! 🙏🏼

**Comment by stnguyen90** [comment]
@asmitrai, how's your progress on this? Or should I unassign you from this issue?

**Comment by stnguyen90** [comment]
We probably don't need this since we don't require indexes anymore.
