### ISSUE TITLE
🚀 Feature: Shared organisation accounts

### ISSUE THREAD

**Issue by CodeDoctorDE** [appwrite/appwrite#4905]
### 🔖 Feature description

An option to have a "global" (organisation level) user database.
Every project can use this account type (like the oauth services) and can use it to be authorized on it.

### 🎤 Pitch

For example you want to do something like Google.
You have one account for every service on their website.
You have a project "docs", "maps", ... and want to have the same account for all projects.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This seems very related to https://github.com/appwrite/appwrite/issues/4645. Can we use that instead of this and you can 👍🏼 that issue?

**Comment by eldadfux** [comment]
Closing in favor of https://github.com/appwrite/appwrite/issues/4645
