### ISSUE TITLE
Function events are not completely visible, even in 2k Screen

### ISSUE THREAD

**Issue by lohanidamodar** [appwrite/appwrite#492]
![Screenshot from 2020-07-29 20-47-19](https://user-images.githubusercontent.com/6360216/88817173-eac4d580-d1dc-11ea-9199-b44d2e26faca.png)

## Problem
As you can see in the screenshot above, the function event names are not completely visible, even in 2k Screen.

## Possible solutions
- Expand middle sections in large screens, making responsive, however this will affect all other views
- At least provide tooltip with the complete event name

**Comment by eldadfux** [comment]
Does changing the font size to 14px work better?

![image](https://user-images.githubusercontent.com/1297371/88820183-a3811980-d1c9-11ea-9bb3-ccd765330b2a.png)

**Comment by lohanidamodar** [comment]
@eldadfux Where do I change that? I am using the Google chrome in Ubuntu.

**Comment by eldadfux** [comment]
I have committed a fix to the `swoole-and-functions` branch, you can sync and rebuild the Appwrite container to get the updated version.

**Comment by lohanidamodar** [comment]
@eldadfux great

**Comment by lohanidamodar** [comment]
@eldadfux It's fixed in the latest pull, however i believe, it's still best to add the tooltip, to be safe :+1:

**Comment by eldadfux** [comment]
@lohanidamodar agree. I'll add an HTML title attribute, which will add the browser native tooltip for backup.

**Comment by eldadfux** [comment]
Added the tooltips in my latest commit:
![image](https://user-images.githubusercontent.com/1297371/88961227-61310880-d2ad-11ea-9723-175948eb6204.png)

**Comment by eldadfux** [comment]
v0.7 is out and this fix is now available ✅
