### ISSUE TITLE
Account webhook doesn't trigger through the console

### ISSUE THREAD

**Issue by shimmy-96** [appwrite/appwrite#493]
I'm using appwrite for flutter.. and when I try to trigger a webhook through the console it doesn't work.. but when I create a user through flutter's SDK it does work.

**Comment by TorstenDittmann** [comment]
I haven't been able to reproduce this.

Do you mind providing additional information?

Like: 
- Appwrite version?
- local environment?
- Logs (access them with `docker-compose exec appwrite cat /var/log/appwrite.log`)

**Comment by eldadfux** [comment]
I can confirm that the users API is not triggering the account.create event

**Comment by eldadfux** [comment]
Created a PR to fix this issue.

I added 4 new webhooks events for the users API (also available as functions events). The users API is the API used when managing users from the Appwrite dashboard.

The new events:
* **users.create** - This event triggers when a user is created from the users API.
* **users.update.status** - This event triggers when a user status is updated from the users API.
* **users.delete** - This event triggers when a user is deleted from users API.
* **users.sessions.delete** - This event triggers when a user session is deleted from users API.

**Comment by eldadfux** [comment]
The fix is now available with lots of new upgrades to the webhooks mechanism and system events in general!
