### ISSUE TITLE
🐛 Bug Report: LetsEncrypt failing

### ISSUE THREAD

**Issue by tannermeade** [appwrite/appwrite#4938]
### 👟 Reproduction steps

I'm getting emails from my appwrite instance saying the letsencrypt cert is failing.

I've tracked it down to app/workers/certifications.php on lines 106 and 283.

There are no logs found in the folder it mentions.

![PNG image](https://user-images.githubusercontent.com/46303912/210115016-13dadec1-89ee-4d52-99d3-a7a8ba211ac1.png)

### 👍 Expected behavior

It should work as it has worked in the past for the instance.

### 👎 Actual Behavior

When I try running the actual certbot command in the certifications docker container I get this:

![PNG image](https://user-images.githubusercontent.com/46303912/210115137-8d18afe0-5e00-46fd-9995-6109cc2ee3d3.png)

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by tannermeade** [comment]
May be connected to this commit: https://github.com/appwrite/appwrite/commit/e23752d4f3f37f9f8d006c62c73c1d68e42c1bba

**Comment by tannermeade** [comment]
Discord conversation: https://discord.com/channels/564160730845151244/564160731327758347/1058505478411403354

**Comment by tannermeade** [comment]
@gewenyu99 mentioned on discord that the is used for the folder looks not correct:
![PNG image](https://user-images.githubusercontent.com/46303912/210115547-7c724353-a485-4852-abf0-a619bfcf190d.png)

![PNG image](https://user-images.githubusercontent.com/46303912/210115555-53d77017-c09b-44de-8b7e-5eb6593a14dc.png)

**Comment by stnguyen90** [comment]
@tannermeade have you tried this without Cloudflare proxy enabled?

**Comment by tannermeade** [comment]
> @tannermeade have you tried this without Cloudflare proxy enabled?

Sunday I got a "Failed to rename certificate cert.pem" email. Haven't got emails since then. It was the 5th error. So I don't know if something has changed for sure or not.

Trying a few things and waiting a couple days to see what happens.

**Comment by stnguyen90** [comment]
@tannermeade, are you still having issues or can this be closed now?

**Comment by tannermeade** [comment]
Ya we can close it. I must have adjusted the Cloudflare settings.
