### ISSUE TITLE
🐛 Bug Report: Properties in example custom data needs to be double quoted when executing cloud function via console 

### ISSUE THREAD

**Issue by dan91** [appwrite/appwrite#4940]
### 👟 Reproduction steps

When I add custom data to test a cloud function in the Appwrite Console as demonstrated in the "Show example JSON", the double quotes for the properties are missing  
![image](https://user-images.githubusercontent.com/6041000/210211254-e7beca0b-9304-401b-8565-a7641041b457.png)

### 👍 Expected behavior

the example json properties should have double quotes

### 👎 Actual Behavior

the double quotes are missing which causes a JSON.parse error

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Node 16.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Ajan62001** [comment]
@stnguyen90 can I pick this one? I want to start my open-source contribution. this looks like an easy opportunity to start.

**Comment by stnguyen90** [comment]
@Ajan62001, assigned! Thanks for your interest! FYI, make sure to create your PR in the [console](https://github.com/appwrite/console) repo.

**Comment by stnguyen90** [comment]
@Ajan62001, how's your progress on this?

**Comment by stnguyen90** [comment]
Unassigning due to inactivity.

**Comment by kabhamo** [comment]
Hi @stnguyen90
I hope you are doing great,

After reviewing the code I figure out the bug and I have a solution for it.
Please, assign to me the issue, so I can make a **PR** to **console repo** as needed. 🚀

**Comment by rinkuhasija** [comment]
@stnguyen90 Can you assign this issue to me please ?

**Comment by kabhamo** [comment]
A PR was created, waiting for merging 🚀
https://github.com/appwrite/console/pull/333
