### ISSUE TITLE
🚀 Feature: Add LDAP sync events

### ISSUE THREAD

**Issue by noriakisana** [appwrite/appwrite#4947]
### 🔖 Feature description

You should have the ability to sync the appwrite project users and teams with a ldap server directly (instead of using authentik, co.)

### 🎤 Pitch

In my use case, i am writing an app for my software company. For easier administration I dont like the idea of having multiple locations for user managment. The ability for sync my ldap server and allow appwrite to "migrate" the groups and users would be much easier.

An alternativly way would be to use an oauth server and use the jwts, or authenticate the stuff via cloud functions, which seems not elegant to me.

What do you think?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Noriakisana** [comment]
just was thinking about it and didnt see any contra arguments, so i am excited to hear some other opinions.

**Comment by stnguyen90** [comment]
@Noriakisana thanks for creating this issue! 🙏🏼 

OAuth would be the typical approach for this. If you need any other attributes from LDAP, I would suggest creating a custom users/profiles collection and using an Appwrite Function to sync the data.
