### ISSUE TITLE
Cross-Server/SDK data interop. ?

### ISSUE THREAD

**Issue by sshyran** [appwrite/appwrite#495]
Hi,  Is there cross-language/Server/SDK data interop. natively built in appwrite ? Maybe some gRPC implementation? So that I could run one Appwrite server (lets say Go dev) in one datacenter and  another Appwrite server (Dart test) somewhere else... and pull data into each its microservice and each instance separately in live mode...  ? Thanks...

**Comment by eldadfux** [comment]
Hey @sshyran currently the only option to communicate between server is using the REST API or using one of Appwrite server SDKs (https://appwrite.io/docs/sdks#server).

We do plan to add a GraphQL endpoint alongside the REST API in v0.8, that will also allow us to add more API protocols and we have been talking about GRPC support, but nothing official yet.

**Comment by eldadfux** [comment]
Closing this issue. GRPC and Protobuf are already on the internal roadmap. I'll open new dedicated issues for this when we'll start designing this features.
