### ISSUE TITLE
📚 Documentation: 'get()' link under Login section on Authentication docs - Fails to Load Resource

### ISSUE THREAD

**Issue by swagataroy30** [appwrite/appwrite#4954]
### Reproducing The Error

https://user-images.githubusercontent.com/116095538/210807659-6aa6eaf8-bc8a-461e-87e8-8e93128b47d9.mp4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by swagataroy30** [comment]
Hey, can I work on this? I would really like to contribute ... could you please guide me?

**Comment by AliJafriETH** [comment]
hey @stnguyen90, is the issue still open, i'd love to work on this issue?

**Comment by stnguyen90** [comment]
@swagataroy30, @AliJafriETH, sorry, looks like someone already submitted a PR.
