### ISSUE TITLE
🐛 Bug Report: CRON functions do not resume the CRON schedule

### ISSUE THREAD

**Issue by JakeAi** [appwrite/appwrite#4958]
### 👟 Reproduction steps

When I upgrade appwrite, CRON functions do not resume the CRON schedule. I have a CRON set for every 5 minutes to process orders. Updated appwrite on Dec 8 and functions stopped executing the schedule. Have to remove CRON schedule, update, add CRON back in, update after each update. Ended up costing us quite a bit of money.

### 👍 Expected behavior

Run CRON scheduled functions

### 👎 Actual Behavior

Doesn't run. Have to remove CRON schedule, update, add CRON back in, update.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.1.2 and 1.2.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@JakeAi thanks for raising this! 🙏🏼 I thought we fixed this as part of https://github.com/appwrite/appwrite/pull/4704, but I guess not...We've also been working on a rewrite of the function schedule, so I think the next release that includes that will also fix this problem.

Is that right, @Meldiron?

**Comment by DocBrown101** [comment]
I just ran into the same problem. Is there anything new yet?

**Comment by outrelouxhe** [comment]
Same issue here - version 1.2.1
This is a very annoying issue that didn't exist before (I was using 0.13 just before).
Thank you.

**Comment by outrelouxhe** [comment]
Additional comment : I have to remove CRON settings and put it back again everytime I restart Appwrite

**Comment by s3ppo** [comment]
i have the same issue, is this fixed now in 1.3.0?

**Comment by stnguyen90** [comment]
@s3ppo yes, this should be fixed in 1.3.0
