### ISSUE TITLE
📚 Documentation: ID.unique() -> unique() - documentId

### ISSUE THREAD

**Issue by WebtronHammerHaering** [appwrite/appwrite#4959]
### 💭 Description

# Database API - Node ( Server SDK ) 
### Current Description: 
Document ID. Choose your own unique ID or pass the string `ID.unique()` to auto generate it. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can't start with a special char. Max length is 36 chars.

### Recommended Description:
Document ID. Choose your own unique ID or pass the string ~ID.unique()~ `unique()` to auto generate it. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can't start with a special char. Max length is 36 chars.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Here's where this text is:

https://github.com/search?q=repo%3Aappwrite%2Fappwrite+%22Choose+your+own+unique+ID+or+pass+the+string%22&type=code

**Comment by stnguyen90** [comment]
@WebtronHammerHaering, FYI, we do recommend using `ID.unqiue()` rather than using a magic string like `"unique()"`. I think a better description would be:

> Document ID. Choose your own unique ID or pass ~the string~ `ID.unique()` to auto generate it. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can't start with a special char. Max length is 36 chars.

**Comment by WebtronHammerHaering** [comment]
@stnguyen90  Thanks for adding the label and text resource location.
The reason i raised the issue is that i could not get it ( node sdk ) to work with the string `ID.unique()` . 
On all recent appwrite installations ( DigitalOcean + Local , version 1.2.0 and 0.15.3 ) appwrite throws an arrow when prefixed with `ID`  -> just `unique()` works fine though.

**Comment by stnguyen90** [comment]
@WebtronHammerHaering were you importing and using the function like [this](https://github.com/appwrite/playground-for-node/blob/e83cdea610211ae77be024c3591db95be82c0bb5/src/app.js#L32)?

**Comment by stnguyen90** [comment]
FYI, the `ID` helper was introduced in Appwrite 1.0.0 (so the SDK version for 1.0.0 is [8.0.0](https://github.com/appwrite/sdk-for-node/blob/8.0.0/lib/id.js)).

**Comment by WebtronHammerHaering** [comment]
The way of import seems to be the problem.
As you would need to import the named module "ID" from e.g "node-appwrite" for the usage like in [this](https://github.com/appwrite/playground-for-node/blob/e83cdea610211ae77be024c3591db95be82c0bb5/src/app.js#L32) example.

Which, for me, is a bit counter intuitive since the docs describe this as a String. For me this would indicate to put a literal String in there which is handled by the backend and not to use the imported module ID, which probably does the magic part on the client site of things ( with connection to the backend obviously ).

So there are two ways of doing so ( node sdk ) :
1. Import the named module ID, and use it as a javascript object/module 
2. Transmit the literal String "unique()" as ID.

**Comment by stnguyen90** [comment]
> Which, for me, is a bit counter intuitive since the docs describe this as a String

@WebtronHammerHaering, which is why i suggest to remove the string reference: https://github.com/appwrite/appwrite/issues/4959#issuecomment-1374235024
