### ISSUE TITLE
🐛 Bug Report: Database usage screen shows 500 error when `_APP_USAGE_STATS` is `disabled`

### ISSUE THREAD

**Issue by gigili** [appwrite/appwrite#4960]
### 👟 Reproduction steps

* Select a project
* Click on the `Databases` in the sidebar
* Click on the `Usage` tab or try to go into a specific database and/or collection and clicking on the same tab

### 👍 Expected behavior

To be able to see the database usage information

### 👎 Actual Behavior

I just upgraded from version 1.1.2 to 1.2.0 and when opening the database usage pages:

  * `https://my-domain.com/console/project-[project-id]/databases/usage`
  * `https://my-domain.com/console/project-[project-id]/databases/database-[database-id]/usage`
  * `https://my-domain.com/console/project-[project-id]/databases/database-[database-id]/collection-[collection-id]/usage`
  
  They all show a 500 internal error page and looking at the `appwrite` container logs I can see this: 
  
  ```
  [Error] Method: GET
[Error] URL: /v1/databases/:databaseId/usage
[Error] Type: TypeError
[Error] Message: Appwrite\Utopia\Response::dynamic(): Argument #1 ($document) must be of type Utopia\Database\Document, array given, called in /usr/src/code/app/controllers/api/databases.php on line 2673
[Error] File: /usr/src/code/src/Appwrite/Utopia/Response.php
[Error] Line: 411
[Error] Timestamp: 2023-01-06T11:02:27+00:00
[Error] Method: GET
[Error] URL: /v1/databases/usage
[Error] Type: TypeError
[Error] Message: Appwrite\Utopia\Response::dynamic(): Argument #1 ($document) must be of type Utopia\Database\Document, array given, called in /usr/src/code/app/controllers/api/databases.php on line 2564
[Error] File: /usr/src/code/src/Appwrite/Utopia/Response.php
[Error] Line: 411
[Error] Timestamp: 2023-01-06T11:02:58+00:00
[Error] Method: GET
[Error] URL: /v1/databases/:databaseId/usage
[Error] Type: TypeError
[Error] Message: Appwrite\Utopia\Response::dynamic(): Argument #1 ($document) must be of type Utopia\Database\Document, array given, called in /usr/src/code/app/controllers/api/databases.php on line 2673
[Error] File: /usr/src/code/src/Appwrite/Utopia/Response.php
[Error] Line: 411
```

Other pages such as `Collections` and/or `Settings` open just fine. 

![appwrite-db-usage-error](https://user-images.githubusercontent.com/2153382/211000831-6e97a0ab-e0d9-4383-bf69-4e269aeed8a4.jpg)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

* Docker version 20.10.22, build 3a2c30b
* docker-compose version 1.25.0, build unknown 
* Linux 5.4.0-135-generic
* Ubuntu 20.04.5 LTS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gigili thanks for raising this issue! 🙏🏼 You said you just upgraded. Did you run the [migrate](https://appwrite.io/docs/upgrade#migration) command after upgrading?

**Comment by gigili** [comment]
Hey @stnguyen90, yeah I was following the official upgrade guide and did run the migration command after upgrading all the containers to 1.2 version.

**Comment by stnguyen90** [comment]
> yeah I was following the official upgrade guide and did run the migration command after upgrading all the containers to 1.2 version.

Any errors? What's in your `appwrite` folder now?

> Hey, I did some checking around my appwrite instance and noticed this issue is not only linked to that database screens but every service that has the Usage tab in it shows the same error page and the same thing in the logs.

It really looks like there was a migration step missing so anything related to usage will error out. 

> I've also tried to deploy a separate clean instance of appwrite and it has the same problem, so it doesn't seem to be related to just upgraded version.

Clean instance? so did you wipe the old volumes and install again or did you use a different server?

**Comment by gigili** [comment]
> Any errors? What's in your appwrite folder now?

Everything looked normal  (I say looked, because I deleted everything and tried from scratch to install appwrite). During the upgrade process there were no errors and everything went smoothly.  

> Clean instance? so did you wipe the old volumes and install again or did you use a different server?

Yeah I wiped everything (containers, volumes, networks, images) and did a brand new install of appwrite from scratch on that same server. The only thing I didn't do from scratch was the `.env` file (I used one left behind by migration) and the `docker-compose.yml` file as well. But I could try using "clean" versions of those as well if you think it might make a difference.

I can share the `yml` and `.env` file if that would help out.

**Comment by stnguyen90** [comment]
> Yeah I wiped everything

@gigili how did you wipe everything exactly?

**Comment by gigili** [comment]
I've used Portainer and it's UI to delete the containers, than I removed all the leftover volumes and than the networks, than run the `docker compose up -d  --remove-orphans` to create everything

**Comment by stnguyen90** [comment]
> I can share the yml and .env file if that would help out.

@gigili, sure, you can share the files with me and I can try to spin them up to see if I see the error.

**Comment by gigili** [comment]
I've attached the files below, I had to strip out all the sensitive info from the `.env` file and replace it with `demo` and `example`, if you need more info or access to the instance it self, we can move this conversation over to discord and add conclusions here when done. 

[appwrite.zip](https://github.com/appwrite/appwrite/files/10386605/appwrite.zip)

**Comment by stnguyen90** [comment]
@gigili, thanks! Would you please try updating `_APP_USAGE_STATS` to `enabled`?

**Comment by gigili** [comment]
Hi, after setting `_APP_USAGE_STATS` to `enabled` (by mistake set it to just `enable` first and it didn't work), now the usage screen shows normally. Do you want me to close this issue ?

**Comment by stnguyen90** [comment]
> 



> Hi, after setting `_APP_USAGE_STATS` to `enabled` (by mistake set it to just `enable` first and it didn't work), now the usage screen shows normally. Do you want me to close this issue ?

Nah, the Console should handle this gracefully and show no stats or something rather than throwing a 500 error

**Comment by singhbhaskar** [comment]
Hi @stnguyen90 ,
Can I work on this bug?
For the following endpoints:
```
https://my-domain.com/console/project-[project-id]/databases/usage
https://my-domain.com/console/project-[project-id]/databases/database-[database-id]/usage
https://my-domain.com/console/project-[project-id]/databases/database-[database-id]/collection-[collection-id]/usage
```
We can check if `_APP_USAGE_STATS` is enabled or not. If it's not enabled we can change the response to not send 500 and instead send 501 directing the user to enable `_APP_USAGE_STATS`

**Comment by stnguyen90** [comment]
@singhbhaskar, returning 501 sounds like a good idea. Please make sure to add a new error with a description like:

https://github.com/appwrite/appwrite/blob/e8c74d7204258133a61db09ed518211170e751d9/app/config/errors.php#L53

Please, share what happens in the console after this change.

**Comment by singhbhaskar** [comment]
Thanks @stnguyen90. Sure will do that.

**Comment by singhbhaskar** [comment]
Hey @stnguyen90 ,
To fix this bug We need to make change to both backend and console front end. So for front end do I need to raise a new PR for appwrite/console repo?

**Comment by singhbhaskar** [comment]
Hey @stnguyen90 ,
Raised the PR for this kindly review it.

Thanks
Bhaskar

**Comment by stnguyen90** [comment]
Looks like we have a regression in 1.4
