### ISSUE TITLE
🚀 Feature: Push Notifications

### ISSUE THREAD

**Issue by usmandilmeer** [appwrite/appwrite#4968]
### 🔖 Feature description

Push Notifications like google firbase.

### 🎤 Pitch

Hi,
I am unable to find push notifications in appwrite docs like firbase.
Can you please add push notifications feature?
I want to use this in my app.

### 👀 Have you spent some time to check if this issue has been raised before?

- [ ] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [ ] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for raising this! 🙏🏼 FYI, there are some related discussions on this already:

* https://github.com/appwrite/appwrite/discussions/1623
* https://github.com/appwrite/appwrite/discussions/905
