### ISSUE TITLE
🚀 Feature: Appwrite's SMTP 

### ISSUE THREAD

**Issue by usmandilmeer** [appwrite/appwrite#4969]
### 🔖 Feature description

Build or improve appwrite own smtp server so that we don't require 3rd party smtp provide.
Or add the add documentation in appwrite docs to create own smtp in vps and configure with appwrite.

### 🎤 Pitch

Build or improve appwrite own smtp server so that we don't require 3rd party smtp provide.
Or add the add documentation in appwrite docs to create own smtp in vps and configure with appwrite.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@usmandilmeer thanks for raising this issue! 🙏🏼 

I don't think we would move toward building an SMTP server or anything like that as managing your own SMTP server is very tricky and you're likely to be blocked by spam filters. It's pretty standard to use some SMTP provider and configure using SMTP settings.

**Comment by stnguyen90** [comment]
Closing as no further action required.
