### ISSUE TITLE
Feature Request : Asking users to pay for subscription

### ISSUE THREAD

**Issue by Shubhampratapsingh** [appwrite/appwrite#4970]
It will be helpful if we can ask users to pay one time or recurring payment to access certain feature from our app.
Something like this: "https://userbase.com/docs/sdk/purchase-subscription/". 
If we can also have client sdk for subscription, it will be helpful.

**Comment by stnguyen90** [comment]
@Shubhampratapsingh thanks for raising this issue! 🙏🏼 Is this a duplicate of https://github.com/appwrite/appwrite/issues/4834? If so, I'd recommend 👍🏼 that issue to upvote it.

**Comment by stnguyen90** [comment]
@Shubhampratapsingh please make sure you 👍🏼 issue https://github.com/appwrite/appwrite/issues/4834.
