### ISSUE TITLE
🐛 Bug Report: When creating a function with CLI : Error 500

### ISSUE THREAD

**Issue by Maxbrt18** [appwrite/appwrite#4971]
### 👟 Reproduction steps

When I try to init a function with CLI using :  `appwrite init function` with Appwrite 1.2.0.
Even with other commands like :  `appwrite deploy function` it doesn't work and send me a Server Error (500).

### 👍 Expected behavior

It should deploy, or init the function successfully with the latest version of Appwrite CLI and latest version of Appwrite.

### 👎 Actual Behavior

Using verbose flag, I can see this message :
```
AppwriteException [Error]: Server Error
    at Client.call (/usr/local/lib/node_modules/appwrite-cli/lib/client.js:209:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async functionsCreate (/usr/local/lib/node_modules/appwrite-cli/lib/commands/functions.js:90:16)
    at async initFunction (/usr/local/lib/node_modules/appwrite-cli/lib/commands/init.js:71:18) {
  code: 500,
  response: [Object: null prototype] {
    message: 'Server Error',
    code: 500,
    type: 'general_protocol_unsupported',
    version: '1.2.0'
  }
}
✗ Error Server Error
```

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use latest version of Ubuntu, running on an Oracle Cloud Server.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Maxbrt18 thanks for raising this issue! 🙏🏼 

Would you please check the docker logs for the `appwrite` container to see what the details are for the 500 error?

Also, what version of the Appwrite CLI do you have? You can check by running `appwrite -v`.

**Comment by Maxbrt18** [comment]
I had the following error : 

```
[Error] Timestamp: 2023-01-09T20:11:03+00:00
[Error] Method: POST
[Error] URL: /v1/functions
[Error] Type: Appwrite\Extend\Exception
[Error] Message: Method unsupported over HTTP.
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 221
```

but I finally resolved by completly uninstalling appwrite CLI (which was on 1.1.1) and reinstalling it with npm.
Thanks for your help.
