### ISSUE TITLE
🐛 Bug Report: Failed storage download through console on files bigger then 100MB

### ISSUE THREAD

**Issue by AlexMeesters** [appwrite/appwrite#4976]
### 👟 Reproduction steps

* Log into the console.
* Create a new bucket.
* Upload a file through the console that is 100+ MB.
* In my case I used a zipfile for my own game, but it can also be reproduced by any zip file larger then 100mb it seems.
[Here is an example file to quickly test.](https://l4m0s.itch.io/low-poly-city-pack/download/eyJpZCI6MTUzODQwNCwiZXhwaXJlcyI6MTY3MzI3NzkyOX0%3d%2etB5NaZaYIOnzUsPm2KzLvBD1zhA%3d)
* After upload, try to download it by pressing the download button in the console
* The download will stop and give a failed response

### 👍 Expected behavior

It should fully download the file, not fail around 85.8 MB.

### 👎 Actual Behavior

Gives an error when the file is downloaded for about 85.8 mb's.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Debian 11 on a VPS. Installed using Docker.

.env configuration:
_APP_STORAGE_LIMIT=300000000
_APP_STORAGE_PREVIEW_LIMIT=20000000
_APP_STORAGE_ANTIVIRUS=disabled

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@AlexMeesters thanks for creating this issue! 🙏🏼 

So, I updated my environment variables to match yours:

```
_APP_STORAGE_LIMIT=300000000
_APP_STORAGE_PREVIEW_LIMIT=20000000
_APP_STORAGE_ANTIVIRUS=disabled
```

My bucket settings are:

```json
{
    "$id": "default",
    "$createdAt": "2023-01-09T16:43:21.036+00:00",
    "$updatedAt": "2023-01-09T16:49:53.225+00:00",
    "$permissions": [],
    "fileSecurity": false,
    "name": "Default",
    "enabled": true,
    "maximumFileSize": 300000000,
    "allowedFileExtensions": [],
    "compression": "none",
    "encryption": true,
    "antivirus": true
}
```

I uploaded the sample file you provided and it looks like it uploaded fine:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/1477010/211363277-c367dbe4-5d76-4a98-86e9-e48f501b1346.png">

Here's the file as JSON:

```json
{
    "$id": "63bc462552f42fc08f9f",
    "bucketId": "default",
    "$createdAt": "2023-01-09T16:51:49.344+00:00",
    "$updatedAt": "2023-01-09T16:53:28.649+00:00",
    "$permissions": [
        "read(\"user:63bc4386f363ea47e13a\")",
        "update(\"user:63bc4386f363ea47e13a\")",
        "delete(\"user:63bc4386f363ea47e13a\")"
    ],
    "name": "low-poly-city-pack.zip",
    "signature": "45c6c9091ae6a730a75a9d3c23642d6e",
    "mimeType": "application/zip",
    "sizeOriginal": 164442245,
    "chunksTotal": 32,
    "chunksUploaded": 32
}
```

The downloaded file also seems fine:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/1477010/211363565-1852a59f-1964-42f0-bc76-90bc430d351d.png">

and MD5 check:

```shell
$ md5 low-poly-city-pack.zip
MD5 (low-poly-city-pack.zip) = 45c6c9091ae6a730a75a9d3c23642d6e
$ md5 low-poly-city-pack\ \(downloaded\).zip
MD5 (low-poly-city-pack (downloaded).zip) = 45c6c9091ae6a730a75a9d3c23642d6e
```

I'm not sure what could have happened for your instance 🧐 Does it happen consistently? Maybe insufficient memory?

**Comment by AlexMeesters** [comment]
Based on further tests it most likely breaks because of hardware issues. Not enough ram.
Every new request reserves memory according to the file size, so the VPS runs out of memory rather quickly.

For now I will close the issue, as its because of hardware constraints, although preferably some optimizations are done in the future to lower memory consumption of large downloads.
