### ISSUE TITLE
Documentation on appwrite.json configuration

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4978]
### Discussed in https://github.com/appwrite/appwrite/discussions/4962

<div type='discussions-op-text'>

<sup>Originally posted by **LDY681** January  6, 2023</sup>
Can we have a documentation on appwrite.json.
I know appwrite console is great, but I would like to keep my data structure local for easy migration.
</div>

**Comment by gewenyu99** [comment]
@stnguyen90 Actively working on this as of now :)
