### ISSUE TITLE
🚀 Feature: Ability to filter documents in a collection 

### ISSUE THREAD

**Issue by gigili** [appwrite/appwrite#4979]
### 🔖 Feature description

When viewing documents in a collection, it would be nice if we had the ability to filter them in some way so that finding a specific document is easier than just manually search trough the list of all the documents and relaying on browsers search box. 

### 🎤 Pitch

When having a large set of documents finding a specific one for what ever purpose in the console UI is almost impossible or makes it unnecessarily hard to do so. Having the ability to filter them either by one or more attributes would mean that you as a developer can easily find the document that might be causing some problems or that requires you to manually updated it or remove it from your collection would be a great help. 

Otherwise it would mean that you need to build an additional UI in your own apps that would allow you to manage documents when some apps don't have the need to have such UI present in them or worse you would have to build a second app just to do some modification to existing document

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gigili thanks for raising this! We do have this in your backlog for improvements to the Console. Stay tuned!

**Comment by rafagazani** [comment]
could use the indexes of the collection itself to make the filters available

**Comment by detunjiSamuel** [comment]
@stnguyen90 . I would love to work on this feature.

**Comment by stnguyen90** [comment]
@detunjiSamuel, our design team needs to design the solution first. I recommend looking for an issue labeled `good first issue` if you're looking for something to work on.
