### ISSUE TITLE
🐛 Bug Report: DateTime Attribute Unexpectedly Updates

### ISSUE THREAD

**Issue by myThorsten** [appwrite/appwrite#4981]
### 👟 Reproduction steps

When I update a document via the appwrite-ui it also updates fields I didn't touch. I have seen this with datetime and int-arrays. There may be others.

![image](https://user-images.githubusercontent.com/9773490/211652627-f37d4f89-0b8f-4636-8262-cd063703b389.png)
Screenshot 1 shows an minimal example. I have a collection with one string and one datetime field. both are not required and have no default value. When I create a new document, both fields are empty, as expected.

![image](https://user-images.githubusercontent.com/9773490/211652697-a1ccc6b5-68f7-4be8-a4e8-71a1b8cb058f.png)
Screenshot 2: However, when I update ONLY the string-field in the document via the appwrite-UI, the datetime ALSO gets set to the current time. This is totally unexpected and not at all what I want. The correspondig POST shows that the datetime-field is present and filled with "" which I also didn't expect.

![image](https://user-images.githubusercontent.com/9773490/211652825-9c4e9f95-7846-4e9a-8868-8f79302b7417.png)
Screenshot 3: the response to the POST

For 'operating system' I can only select one, but I tested it on windows and unix.

### 👍 Expected behavior

It should only update fields where I set a value.

### 👎 Actual Behavior

It actually sets values for other fields.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use appwrite as backend for an app. I tested this on unix and windows.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@myThorsten thanks for creating this issue! 🙏🏼 it definitely looks like the Console is passing the current time when it shouldn't.
