### ISSUE TITLE
🐛 Bug Report: `expire` is not formatted the same as other datetimes

### ISSUE THREAD

**Issue by myThorsten** [appwrite/appwrite#4982]
### 👟 Reproduction steps

Today I upgraded AppWrite to 1.2.0. The migration went fine. But my client could no longer log in. I traced the problem back to a changed 'expire' format. The screenshots show the result of **/v1/account/sessions/email/**

The first screenshot shows the result of Version 1.2.0: "expire": "2024-01-09 21:32:12.004"
The second screenshot shows the result of Version 1.0.1: "expire": "2024-01-09T21:22:23.290+00:00"
Notice the missing 'T' and missing trailing '+00:00' which cause my parser to fail. I did not find anything in the release notes. 

![image](https://user-images.githubusercontent.com/9773490/211654074-759e4283-55a1-4753-80d4-35dafd86982e.png)

'$createdAt' has the correct format
![image](https://user-images.githubusercontent.com/9773490/211653952-45758bcc-9c28-4384-9685-ffb7ad5dae79.png)

### 👍 Expected behavior

**expire** should have standard format.

### 👎 Actual Behavior

**expire** does not have the standard format, breaking the parser

Other affected APIs:

- [x] #5428
- [ ] Create Phone Session (confirmation)
- [ ] Create Anonymous Session
- [x] #5429
- [ ] Update OAuth Session (Refresh Tokens)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Backend to my app

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Related issue: https://github.com/appwrite/appwrite/issues/4846

**Comment by stnguyen90** [comment]
To ensure the correct formatting, we should be using `DateTime::formatTz()` like:

https://github.com/appwrite/appwrite/blob/514b42bea2116444082553ea758eeb9f256421dc/app/controllers/general.php#L320

**Comment by munyoudoum** [comment]
Can I work on this?

**Comment by wharl** [comment]
I would like to work on this issue!

**Comment by stnguyen90** [comment]
@wharl thanks for your interest, but I've assigned it to @munyoudoum since they asked first.

**Comment by knight-95** [comment]
I would like to work on this issue, I am familiar with this type of issue

**Comment by stnguyen90** [comment]
Other affected APIs:

1. Create Magic URL session (confirmation)
2. Create Phone Session (confirmation)
3. Create Anonymous Session
4. Get Session
5. Update OAuth Session (Refresh Tokens)

**Comment by stnguyen90** [comment]
This has been resolved for email session:

![image](https://user-images.githubusercontent.com/1477010/234144913-2a19fc65-2517-443f-88d2-f2fb9afec9f0.png)

**Comment by fanatic75** [comment]
@stnguyen90  
if there is no separate ticket for anonymous, phone and oauth sessions bug
Should I put them in this ticket itself and in one PR? 
let me know I have the PR ready
