### ISSUE TITLE
🐛 Bug Report: `appwrite-worker-messaging` container is missing the restart policy in installation compose file

### ISSUE THREAD

**Issue by aayushbisen** [appwrite/appwrite#4986]
### 👟 Reproduction steps

1. Install appwrite on a Virtual Machine
2. Restart the Virtual Machine
3. Run `docker ps -a` command after restart
4. Check the status of `appwrite-worker-messaging` container

### 👍 Expected behavior

The `appwrite-worker-messaging` container should successfully restart after VM restart.

### 👎 Actual Behavior

The `appwrite-worker-messaging` container goes to exited state after VM restart

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Ubuntu 20.04 LTS on Azure VM

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@aayushbisen assigned as requested on Discord! Thanks for your interest! 🙏🏼
