### ISSUE TITLE
🐛 Bug Report: Not required attribute (format url) has invalid validation in console 2.0

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#4989]
### 👟 Reproduction steps

On update not required attribute (format url), I got this validation message.

![Screenshot 2023-01-12 005615](https://user-images.githubusercontent.com/18592683/211905590-0d5091da-9d87-4595-8cd8-4c3f9cbe092c.png)

Attribute info
![Screenshot 2023-01-12 005640](https://user-images.githubusercontent.com/18592683/211905569-54d2d6ed-1f74-4f9e-8dfd-1007c8dd365e.png)

### 👍 Expected behavior

It should update and save null on this filed.

### 👎 Actual Behavior

It actually showing invalid format message.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@usamashafiqs thanks for raising this issue! 🙏🏼 Would you be able to share the payload for the create document API call from the network logs?

**Comment by stnguyen90** [comment]
@usamashafiqs you should be able to open your browser dev tools and capture the network logs.

**Comment by stnguyen90** [comment]
Thanks, @usamashafiqs! Seems like the API doesn't like the empty string. It's probably created with `null`.

**Comment by Ritzy-NCode** [comment]
@stnguyen90 , 
Greetings!!
Looks like this issue is resolved with https://github.com/appwrite/console/pull/235 
i was trying to find the next issue to resolve and came acrosee this
