### ISSUE TITLE
Need to add Fields param in ListDocument and GetDocument APIs

### ISSUE THREAD

**Issue by punitdiwan** [appwrite/appwrite#499]
We need to add fieldList parameter of type array in List Documents and Get Document API in database service. It will allow users to fetch only necessary attributes of collection in the response. 

This will be only useful for REST based APIs as GraphQL has implicit and native support for this. We can do something like this in the REST APIs   **/{collectionID}/documents?fieldList=song,title,length,singer**. ID and Collection Fields ( CollectionID ) field will be mandatory and can not be removed.

  In the case of nested collections response, if the passed fields in FIledList array duplicates in inner collections, it will occur in both collection responses as the fieldList will apply on final response after all queries.

Hope it will help.

Regards
Punit

**Comment by eldadfux** [comment]
@punitdiwan I'm not sure if we'll manage to add this to 0.7 or 0.8 yet. Let me know if maybe you want us to work on this together. It should be pretty simple for getting started with the Appwrite codebase.

**Comment by ng29** [comment]
hey @eldadfux can i help in this ? ? if some more info can be provided 👍

**Comment by TorstenDittmann** [comment]
Not sure if this is still relevant, there are some factors in terms of OpenAPI and REST specs that somehow speak against this implementation 🤔
