### ISSUE TITLE
🐛 Bug Report: Cannot create document in first collection after adding data to the second collection 

### ISSUE THREAD

**Issue by divyansh-kumar** [appwrite/appwrite#4993]
### 👟 Reproduction steps

In the database section in the console i have a new database called "Data" with two collections "Products" and "Users" the thing is that i cannot add data to those collection one after another for example in i create some document in the "Users" collections and then try to create document in "Products" collection it will give an error saying 'Invalid document structure: Unknown attribute: "First" '. and this attribute belongs to the "Users" collection not the "Product" and hence i can't create the document
<img width="1440" alt="Screenshot 2023-01-12 at 2 07 27 AM" src="https://user-images.githubusercontent.com/48374529/211990361-fd3f2fbe-9d7a-4330-9d12-3e5d3cbc5b11.png">

<img width="1440" alt="Screenshot 2023-01-12 at 11 23 12 AM" src="https://user-images.githubusercontent.com/48374529/211990415-35a86ea4-31aa-4080-ba5a-d7c2620c4820.png">

<img width="1440" alt="Screenshot 2023-01-12 at 11 23 20 AM" src="https://user-images.githubusercontent.com/48374529/211990510-ac09cadf-dfb3-4587-9d0f-8c283b71aefd.png">

### 👍 Expected behavior

After creating document it should be stored successfully 

### 👎 Actual Behavior

gives an error "Invalid document structure: Unknown attribute:  "
<img width="523" alt="Screenshot 2023-01-12 at 11 15 21 AM" src="https://user-images.githubusercontent.com/48374529/211987210-ef822b39-f19d-4f19-a3e2-b4409f478e15.png">

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

My appwrite server is installed in a ubuntu 22.04 machine. I also use Cloudflare for tunneling, however i do everything via local IP and console. Using appwrite:1.2.0 and i have not customized my environment in any way or form 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@divyansh-kumar thanks for creating this issue! 🙏🏼 It definitely seems like something is leftover from the previous wizard.
