### ISSUE TITLE
create an Appwrite Function add custom collection to user

### ISSUE THREAD

**Issue by MojtabaDelshad** [appwrite/appwrite#5007]
When a user is created, only the email, password and name can be saved for it.
I need other fields to be automatically created with default values when a user is created (I don't want this information to be sent from the client side).
This should be done through Appwrite Function.
Can someone guide me on creating it or sample code

**Comment by stnguyen90** [comment]
This is definitely doable with an Appwrite Function! I would suggest looking at our [Function Docs](https://appwrite.io/docs/functions) for how to create a function. If you're having troubles, feel free to join us on [Discord](https://appwrite.io/discord).

**Comment by rafagazani** [comment]
@stnguyen90 can we close this issue?
