### ISSUE TITLE
🐛 Bug Report: Enum Attribute Overview has editable Elements

### ISSUE THREAD

**Issue by divyansh-kumar** [appwrite/appwrite#5009]
### 👟 Reproduction steps

Made an attribute with Format "Enum" and added some items in the list and set Required as True and after saving that attribute...... when i clicked overview to check the elements that i added. I noticed that i can remove/delete the elements but cant add elements 
<img width="1440" alt="Screenshot 2023-01-14 at 11 40 38 PM" src="https://user-images.githubusercontent.com/48374529/212488862-d8a3b3a5-987a-4674-bd0e-652283dc0310.png">

https://user-images.githubusercontent.com/48374529/212488931-6750f298-fd65-45b5-8b10-6aac1f397e01.mov

### 👍 Expected behavior

I think it would be better to give the option to add elements just like right now..... i forgot to add one element and now to do so i have to delete the whole attribute and create a new one then add all the elements again

I can successfully Delete elements so it should let me add elements too

### 👎 Actual Behavior

It doesn't let me add elements but i can delete

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

No customized environment  and i have installed the Appwrite 1.2.0 on a ubuntu machine version 22.04

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@divyansh-kumar, thanks for raising this issue! 🙏🏼 Actually, it's not possible to modify attributes at the moment. Be sure to 👍🏼 [this issue](https://github.com/appwrite/appwrite/issues/3328) to upvote that feature request.

This looks like a UI bug where you can update the input, but it won't change the attribute.

**Comment by stnguyen90** [comment]
readonly probably needs to be used somewhere else here: https://github.com/appwrite/console/blob/37c45aa11fc5ead964132a09f591bc0f48d8c5e6/src/lib/elements/forms/inputTags.svelte

**Comment by aakashraj01** [comment]
Hey, @stnguyen90 Can I pick this issue ? Looks like I can solve this bug :)

**Comment by yatharth1706** [comment]
Hy, @stnguyen90 can i work on this?
