### ISSUE TITLE
My First Demo Issue

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#501]
This is a demo issue to help new contributors make their pull-request to Appwrite.

**Comment by ronfybish** [comment]
Hi this my first PR on Appwrite, can I assign to this issue?

**Comment by Wittty-Panda** [comment]
Hello sir @eldadfux ,
This is my first issue for appwrite repo,
Can you please explain what i will have to do and Assign this to me ?
I will do my level best to contribute.

**Comment by Angelfirenze01** [comment]
Hi, I'm really glad I finally found this file.  I'm a part of the Appwrite Discord, but I've only lurked before.  I did notice that the **Windows and CMD** sections of the installation information is unclear.  Do they follow the same protocol?  If so, it'd be a great help to know that the two distros can be approached in the same way.  If they're different, can you please specify what steps to take for each installation process?
