### ISSUE TITLE
🚀 Feature: Add custom domain without SSL cert

### ISSUE THREAD

**Issue by binaryfire** [appwrite/appwrite#5010]
### 🔖 Feature description

Many companies run all services through a load balancer and/or external reverse proxy like Cloudflare or AWS Cloudfront. While this is possible with Appwrite (https://dev.to/appwrite/learn-how-to-run-appwrite-with-your-own-custom-proxy-or-load-balancer-28k), the CSRF / XSS protection that comes with adding a custom domain isn't there.

There should be an option to add domains without generating a SSL cert or using Traefik.

### 🎤 Pitch

Many organizations use NGINX for SSL termination and Cloudflare / AWS Cloudfront as a reverse proxy.

Larger apps often heavily integrate with Cloudflare's security features (Zero Access, WAF, rate limiting, bot detection etc). To make the most of these security features the server's firewall is set to only allow Cloudflare IPs (or a Cloudflare Tunnel is used). This prevent's the server's IP from being directly accessible via the internet.

For this kind of setup, SSL termination is done at the load balancer and Cloudflare certificates (or in the case of Cloudflare Tunnels, no certs) are used.

Currently there's no way to use this setup and have the XSS protection that comes with adding a custom domain in Appwrite. There should be an option to add domains without using Appwrite's SSL cert service.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@binaryfire, thanks for opening this issue! 🙏 So, I'm not sure what you're looking to achieve by "add domains without generating a SSL certificate." The only thing adding a custom domain does is generate a SSL certificate 🧐

**Comment by binaryfire** [comment]
@stnguyen90 That's odd, it's been falling back to saving sessions in localstorage even though my reverse-proxied Appwrite instance is on the same domain as my app... Maybe something else is going on. I'll investigate further

**Comment by stnguyen90** [comment]
@binaryfire is your reverse proxy configured to pass the host header? What are you using for your reverse proxy?

**Comment by binaryfire** [comment]
@stnguyen90 I’m using NGINX and yes, the host header is being passed through.

For some reason everything started working after the last update. Not sure why, I didn’t change a thing! Weird.

Closing as it seems to have resolved itself
