### ISSUE TITLE
🐛 Bug Report: `ip change on restarting docker stack`

### ISSUE THREAD

**Issue by hemangjoshi37a** [appwrite/appwrite#5011]
### 👟 Reproduction steps

When I restart the docker stack for `appwrite` it gives new ip address every time so I have to  change the api endpoint ip addess in my code every time.

### 👍 Expected behavior

It should have static IP for the `appwrite` container.

### 👎 Actual Behavior

When I restart the docker stack for `appwrite` it gives new ip address every time so I have to  change the api endpoint ip addess in my code every time.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I dont have any environment customizations. I am using stock ubuntu 22 and everything else stock.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by hemangjoshi37a** [comment]
![Screenshot from 2023-01-16 23-19-41](https://user-images.githubusercontent.com/12392345/212739623-c7bc6d6a-c105-40db-8ca9-3e40bdcb0303.png)
Here is the screenshot from my portainer configuration that is runnig appwrite stack. here you can see the ip of appwrite contianer that is `172.24.0.18` which changes whenever i restart my laptop. I am not using any VPS so my system restarts very often whenver i commute and sleep or goto break and shutdown my laptop.

Also as you told that appwrite is available on the localhost but it is not available on the localhost and only available on the given ip that is giving it's service that is here given in my upper message and the scrrenshot. 

I want to make th ip `172.24.0.18` static that you can see in the screenshot but i dont know how to configure docker compose yaml file to give  a container static ip. I tried searching online sollution for this and found some but they didnt seem to work for me, I also asked chatGPT to resolve this but I also didnt got any working answer for this.

**Comment by stnguyen90** [comment]
@hemangjoshi37a interesting...it's really common for container IPs to change. As Christy mentioned, you typically access the container via the IP of the server. In your case, it should be localhost. Perhaps portainer is doing something weird.

What does running `docker compose ps` in the folder with the Appwrite docker-compose.yml show?

**Comment by hemangjoshi37a** [comment]
![Screenshot from 2023-01-17 11-59-36](https://user-images.githubusercontent.com/12392345/212826137-cf833bfb-c5f9-42d9-88e5-013dc69094ce.png)
![Screenshot from 2023-01-17 12-03-24](https://user-images.githubusercontent.com/12392345/212826277-9d540a58-5198-46bd-b26f-e9efb90d1011.png)

@stnguyen90 @christyjacob4 
Here is a screenshot from my appwrite admin panel and portainer as now. As you can see that the api endpoint is the IP address of the container and not the localhost. although i tried changing ip to localhost in flutter app to access the appwrite backend but it doesnt seem to work, only workable method is using the container ip which quite frustratingly changes everytime when the laptop or the container or the stack is restarted. Please help me give this container a static ip.

**Comment by stnguyen90** [comment]
@hemangjoshi37, 

> As you can see that the api endpoint is the IP address of the container and not the localhost.

That endpoint input will show whatever you're browsing to. Since you're accessing the Appwrite Console at 172.24.0.11, that's what shows. Are you able to to browse to the Appwrite Console using localhost?

> although i tried changing ip to localhost in flutter app to access the appwrite backend but it doesnt seem to work

This is a common problem with mobile development. If you try to use localhost in a mobile app, it will connect to itself rather than the server you want to connect to. I suggest using the LAN IP of your machine instead of localhost. Some people using an [Android emulator use 10.0.2.2](https://stackoverflow.com/questions/5528850/how-do-you-connect-localhost-in-the-android-emulator). Apparently, you can use [localhost with the iPhone simulator](https://stackoverflow.com/questions/6077888/how-do-i-access-the-host-machine-itself-from-the-iphone-simulator).

**Comment by hemangjoshi37a** [comment]
No I cant access it using `localhost`

I am developing the app for the `web` and not for `android` or `iOS`.

In very short term. `Isnt there any way to give appwrite container a static IP?` It is a docker stack type of question but that's what we need to acheive .

**Comment by hemangjoshi37a** [comment]
I dont know man. If this remains unsolved unfortunately I have to go back to firebase. I just thought this is a good alternative but if it doesnt work for me then it doesnt make any sense. It has to run on a predefined static IP or any predefined hostname. If it Keeps changing then it is not useful in anyway. Quite unfortunate that such a good software has to be replaced because of some silly reasons.

**Comment by stnguyen90** [comment]
@hemangjoshi37a 

> No I cant access it using localhost

Appwrite should be accessible using localhost. Would you please share the output of `docker ps`? Or maybe details on the port forwarding for the traefik container?

> In very short term. Isnt there any way to give appwrite container a static IP? It is a docker stack type of question but that's what we need to achieve .

You're right your question is a docker stack question. I searched online and found [this](https://www.baeldung.com/ops/docker-assign-static-ip-container#1-assign-a-static-ip). Refer to the docker compose example.

**Comment by hemangjoshi37a** [comment]
Here is what `sudo docker ps` gives me >>>

<pre>sudo docker p(base) <span style="color:#26A269"><b>hemang@hemang-HP-Pavilion-g6-Notebook-PC</b></span>:<span style="color:#12488B"><b>~</b></span>$ sudo docker ps
[sudo] password for hemang: 
CONTAINER ID   IMAGE                     COMMAND                  CREATED        STATUS                 PORTS                                                                                            NAMES
5a4d360a2037   appwrite/appwrite:1.2.0   &quot;worker-functions&quot;       4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-functions
f6f2fb888ba9   appwrite/appwrite:1.2.0   &quot;executor&quot;               4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-executor
a5e2a3e4f7fa   appwrite/appwrite:1.2.0   &quot;usage&quot;                  4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-usage
e4dc256f2d36   appwrite/appwrite:1.2.0   &quot;docker-php-entrypoi…&quot;   4 days ago     Up 2 hours             80/tcp                                                                                           appwrite
bbfed92689ec   appwrite/appwrite:1.2.0   &quot;worker-audits&quot;          4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-audits
affc636c80a3   appwrite/appwrite:1.2.0   &quot;realtime&quot;               4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-realtime
37918f2f4361   appwrite/appwrite:1.2.0   &quot;worker-databases&quot;       4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-databases
c18027e55c00   appwrite/appwrite:1.2.0   &quot;worker-deletes&quot;         4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-deletes
ba473834807c   appwrite/appwrite:1.2.0   &quot;worker-mails&quot;           4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-mails
039a4af5a834   appwrite/appwrite:1.2.0   &quot;maintenance&quot;            4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-maintenance
502fdc76211e   appwrite/appwrite:1.2.0   &quot;schedule&quot;               4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-schedule
45f2777b6817   appwrite/appwrite:1.2.0   &quot;worker-webhooks&quot;        4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-webhooks
1f00c25eaf21   appwrite/appwrite:1.2.0   &quot;worker-certificates&quot;    4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-certificates
79b545842cb3   appwrite/appwrite:1.2.0   &quot;worker-builds&quot;          4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-builds
546f28b7e3de   mariadb:10.7              &quot;docker-entrypoint.s…&quot;   4 days ago     Up 2 hours             3306/tcp                                                                                         appwrite-mariadb
3510cf2dbe13   appwrite/telegraf:1.4.0   &quot;/entrypoint.sh tele…&quot;   4 days ago     Up 2 hours             8092/udp, 8125/udp, 8094/tcp                                                                     appwrite-telegraf
5356307607f6   appwrite/influxdb:1.5.0   &quot;/entrypoint.sh infl…&quot;   4 days ago     Up 2 hours             8086/tcp                                                                                         appwrite-influxdb
615f9f3e366a   redis:7.0.4-alpine        &quot;docker-entrypoint.s…&quot;   4 days ago     Up 2 hours             6379/tcp                                                                                         appwrite-redis
0cabb3b301ee   appwrite/appwrite:1.2.0   &quot;docker-php-entrypoi…&quot;   5 days ago     Up 51 seconds          80/tcp                                                                                           pedantic_gagarin
26d2b6959e77   redis                     &quot;docker-entrypoint.s…&quot;   13 days ago    Up 2 hours (healthy)   0.0.0.0:6379-&gt;6379/tcp, :::6379-&gt;6379/tcp                                                        open-assistant-redis-1
0b522712e6b1   adminer                   &quot;entrypoint.sh php -…&quot;   2 weeks ago    Up 2 hours             0.0.0.0:8089-&gt;8080/tcp, :::8089-&gt;8080/tcp                                                        open-assistant-adminer-1
336ada8fb9d5   postgres                  &quot;docker-entrypoint.s…&quot;   2 weeks ago    Up 2 hours (healthy)   0.0.0.0:5433-&gt;5432/tcp, :::5433-&gt;5432/tcp                                                        open-assistant-webdb-1
fd21868944e1   maildev/maildev           &quot;bin/maildev&quot;            2 weeks ago    Up 2 hours (healthy)   0.0.0.0:1025-&gt;1025/tcp, :::1025-&gt;1025/tcp, 0.0.0.0:1080-&gt;1080/tcp, :::1080-&gt;1080/tcp             open-assistant-maildev-1
03508214b4e7   postgres                  &quot;docker-entrypoint.s…&quot;   2 weeks ago    Up 2 hours (healthy)   0.0.0.0:5432-&gt;5432/tcp, :::5432-&gt;5432/tcp                                                        open-assistant-db-1
c046a45eabc6   500504ac663a              &quot;/portainer&quot;             3 months ago   Up 2 hours             0.0.0.0:8000-&gt;8000/tcp, :::8000-&gt;8000/tcp, 0.0.0.0:9443-&gt;9443/tcp, :::9443-&gt;9443/tcp, 9000/tcp   portainer
</pre>

**Comment by hemangjoshi37a** [comment]
I have opted out to use orbitDB instead of appwrite as it is decentralized and free and doesnt require hosting resources .
https://github.com/orbitdb/orbit-db

**Comment by stnguyen90** [comment]
> ```
> sudo docker p(base) hemang@hemang-HP-Pavilion-g6-Notebook-PC:~$ sudo docker ps
> [sudo] password for hemang: 
> CONTAINER ID   IMAGE                     COMMAND                  CREATED        STATUS                 PORTS                                                                                            NAMES
> 5a4d360a2037   appwrite/appwrite:1.2.0   "worker-functions"       4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-functions
> f6f2fb888ba9   appwrite/appwrite:1.2.0   "executor"               4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-executor
> a5e2a3e4f7fa   appwrite/appwrite:1.2.0   "usage"                  4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-usage
> e4dc256f2d36   appwrite/appwrite:1.2.0   "docker-php-entrypoi…"   4 days ago     Up 2 hours             80/tcp                                                                                           appwrite
> bbfed92689ec   appwrite/appwrite:1.2.0   "worker-audits"          4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-audits
> affc636c80a3   appwrite/appwrite:1.2.0   "realtime"               4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-realtime
> 37918f2f4361   appwrite/appwrite:1.2.0   "worker-databases"       4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-databases
> c18027e55c00   appwrite/appwrite:1.2.0   "worker-deletes"         4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-deletes
> ba473834807c   appwrite/appwrite:1.2.0   "worker-mails"           4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-mails
> 039a4af5a834   appwrite/appwrite:1.2.0   "maintenance"            4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-maintenance
> 502fdc76211e   appwrite/appwrite:1.2.0   "schedule"               4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-schedule
> 45f2777b6817   appwrite/appwrite:1.2.0   "worker-webhooks"        4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-webhooks
> 1f00c25eaf21   appwrite/appwrite:1.2.0   "worker-certificates"    4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-certificates
> 79b545842cb3   appwrite/appwrite:1.2.0   "worker-builds"          4 days ago     Up 2 hours             80/tcp                                                                                           appwrite-worker-builds
> 546f28b7e3de   mariadb:10.7              "docker-entrypoint.s…"   4 days ago     Up 2 hours             3306/tcp                                                                                         appwrite-mariadb
> 3510cf2dbe13   appwrite/telegraf:1.4.0   "/entrypoint.sh tele…"   4 days ago     Up 2 hours             8092/udp, 8125/udp, 8094/tcp                                                                     appwrite-telegraf
> 5356307607f6   appwrite/influxdb:1.5.0   "/entrypoint.sh infl…"   4 days ago     Up 2 hours             8086/tcp                                                                                         appwrite-influxdb
> 615f9f3e366a   redis:7.0.4-alpine        "docker-entrypoint.s…"   4 days ago     Up 2 hours             6379/tcp                                                                                         appwrite-redis
> 0cabb3b301ee   appwrite/appwrite:1.2.0   "docker-php-entrypoi…"   5 days ago     Up 51 seconds          80/tcp                                                                                           pedantic_gagarin
> 26d2b6959e77   redis                     "docker-entrypoint.s…"   13 days ago    Up 2 hours (healthy)   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp                                                        open-assistant-redis-1
> 0b522712e6b1   adminer                   "entrypoint.sh php -…"   2 weeks ago    Up 2 hours             0.0.0.0:8089->8080/tcp, :::8089->8080/tcp                                                        open-assistant-adminer-1
> 336ada8fb9d5   postgres                  "docker-entrypoint.s…"   2 weeks ago    Up 2 hours (healthy)   0.0.0.0:5433->5432/tcp, :::5433->5432/tcp                                                        open-assistant-webdb-1
> fd21868944e1   maildev/maildev           "bin/maildev"            2 weeks ago    Up 2 hours (healthy)   0.0.0.0:1025->1025/tcp, :::1025->1025/tcp, 0.0.0.0:1080->1080/tcp, :::1080->1080/tcp             open-assistant-maildev-1
> 03508214b4e7   postgres                  "docker-entrypoint.s…"   2 weeks ago    Up 2 hours (healthy)   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                        open-assistant-db-1
> c046a45eabc6   500504ac663a              "/portainer"             3 months ago   Up 2 hours             0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:9443->9443/tcp, :::9443->9443/tcp, 9000/tcp   portainer
> ```

Interesting...it looks like the problem is you're missing traefik and appwrite isn't published/exposed on any port.
