### ISSUE TITLE
🐛 Bug Report: No Error when Creating a Document with value 0 for array attribute

### ISSUE THREAD

**Issue by apoorvdwi** [appwrite/appwrite#5013]
### 👟 Reproduction steps

1. Create an array attribute
2. Create a document passing `0` for the value rather than an array (by calling the API directly rather than using the Appwrite Console)
3. Open the document in the Appwrite Console

https://user-images.githubusercontent.com/56197821/212864215-26931b99-4229-436e-ad70-6c2b3e0c5e09.mp4

### 👍 Expected behavior

The document details should open

### 👎 Actual Behavior

Document details does not open and goes blank instead.

The Appwrite API should return an error when trying to create a document with value 0 for an array attribute.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
@apoorvdwi to try and reproduce the problem could you please share the attributes in your document ?

**Comment by apoorvdwi** [comment]
I have attached a screenshot below with the list of attributes
<img width="1512" alt="Screenshot 2023-01-17 at 7 19 18 PM" src="https://user-images.githubusercontent.com/56197821/212915807-d41dd011-ff09-47c8-87ed-4faac56d60ff.png">

**Comment by apoorvdwi** [comment]
I solved the issue, I was actually adding a string value in an array field so that is why the error was happening

A check would probably be good, or if a single value is passed in the array field, then automatically creating an array and adding the input value as the first element could also be a solution.

**Comment by stnguyen90** [comment]
@apoorvdwi hmm...I tried to create a document passing a string for an array attribute, but i got an error as expected. Are you saying you were able to create the document and then when you went to view the document, you saw this problem in the Console?

**Comment by apoorvdwi** [comment]
I created the document using web SDK and went on to view the document in the appwrite UI, that's when I saw this behavior.

**Comment by stnguyen90** [comment]
@apoorvdwi can you share the web SDK code? Also, can you share the JSON for the bad document?

**Comment by apoorvdwi** [comment]
<img width="545" alt="Screenshot 2023-01-18 at 1 08 44 AM" src="https://user-images.githubusercontent.com/56197821/212995770-9b4929a7-4864-4693-9312-73bfc722ce3d.png">

upvotes, downvotes and pay fields are array fields but I was passing 0 to them

**Comment by stnguyen90** [comment]
@apoorvdwi, thanks! I was able to reproduce it with that info! The API should definitely fail if you pass 0 rather than executing successfully.

**Comment by stnguyen90** [comment]
The problem is probably around here: https://github.com/utopia-php/database/blob/3872565c94641b9580054454330f418abb85debc/src/Database/Validator/Structure.php#L281
