### ISSUE TITLE
🐛 Bug Report:  Cron validation not working properly for advanced values

### ISSUE THREAD

**Issue by Inovvia** [appwrite/appwrite#5021]
### 👟 Reproduction steps

When i try to create a cron schedule using the web console the validation doesn't seem to work properly

I used https://crontab.guru/#0_20_*_*_1-5

### 👍 Expected behavior

It should be able to accept my cron schedule

### 👎 Actual Behavior

Please enter a valid CRON expression

![image](https://user-images.githubusercontent.com/70137651/213503897-38d9e793-62dd-44b8-b1a7-ba581cb928fc.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Windows 11 with WSL for docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Inovvia thanks for creating this issue! 🙏🏼

**Comment by stnguyen90** [comment]
This should be a Console-specific problem, so as a workaround, I would suggest maintaining your function using the [Appwrite CLI](https://appwrite.io/docs/command-line) and updating the schedule via the appwrite.json and `appwrite deploy function`.

**Comment by ashu8912** [comment]
Hey @stnguyen90 can I pick this one?? I really wanted to play around with appwrite a bit and this looks like a good opportunity for me to start/learn more about the codebase.

**Comment by stnguyen90** [comment]
@ashu8912 assigned! Thanks for your interest! 🙏 Make sure to join us on [discord](https://appwrite.io/discord) if you have any questions!

**Comment by yatharth1706** [comment]
@ashu8912 are you working on this? If not @stnguyen90 can i pick this one? I think we just need to fix the regex pattern in the client side that will solve this issue. As api is fine. So its only a regex pattern issue.

**Comment by vontdeux** [comment]
I suppose  this is fixed on 1.3.8?
i entered 0 17 * * 0 (taken from [https://crontab.guru/#0_17_*_*_0](https://crontab.guru/#0_17_*_*_0))

but i got "Please enter a valid Cron expression"

**Comment by xsa-dev** [comment]
I had on last cloud version:
```
*/15 * * * *
Please enter a valid Cron expression
```
![image](https://github.com/appwrite/appwrite/assets/16959353/4961674a-d6c9-4af5-bea3-8d5fc93b34e7)
