### ISSUE TITLE
Appwrite installation Failed on Windows 11

### ISSUE THREAD

**Issue by MojtabaDelshad** [appwrite/appwrite#5026]
I tried several times to install it, but in the end it gives this error
```
...
a5d7708e2667: Pull complete
773dcb17f062: Pull complete
852ba6c80727: Pull complete
80bf4f238350: Pull complete
ecdd44da0c6b: Pull complete
aa5b7cdb073a: Pull complete
003f50d42a27: Pull complete
9d749083d268: Pull complete
Digest: sha256:da762701f81fffd843f1eaf6d701373c2b6a4375a6174d0750f1893b1a78f9d9
Status: Downloaded newer image for appwrite/appwrite:1.2.0
docker: Error response from daemon: invalid volume specification: 'C:\Users\Awms/appwrite:/usr/src/code/appwrite:rw': invalid mount config for type "bind": bind source path does not exist: c:\users\awms\appwrite.
See 'docker run --help'.
```
Docker version 20.10.22

**Comment by stnguyen90** [comment]
@awminux thanks for creating this issue! 🙏🏼 

Odd...Docker is supposed to create folders if they don't exist...If you create the folder first (`mkdir appwrite`), does the same command run successfully?

**Comment by awminux** [comment]
> @awminux thanks for creating this issue! 🙏🏼
> 
> Odd...Docker is supposed to create folders if they don't exist...If you create the folder first (`mkdir appwrite`), does the same command run successfully?



now this error returned
```
docker: Error response from daemon: invalid volume specification: '//var/run/docker.sock:/var/run/docker.sock'.
See 'docker run --help'
```

**Comment by awminux** [comment]
@stnguyen90 now this error returned

docker: Error response from daemon: invalid volume specification: '//var/run/docker.sock:/var/run/docker.sock'.
See 'docker run --help'

**Comment by srivarshithdaladuli** [comment]
docker run -it -v (your path)

**Comment by stnguyen90** [comment]
@awminux would you please also clarify the following?

1. Were using PowerShell or CMD?
2. Where did you run the command?
3. What command did you run?

**Comment by KevalTank** [comment]
Having same issue, Not able to figure out what is going wrong?

![image](https://user-images.githubusercontent.com/70793545/215282974-b8dce8d5-c8b5-4b3f-baef-62907f498b68.png)

**Comment by MojtabaDelshad** [comment]
> Having same issue, Not able to figure out what is going wrong? I'm having this issue on windows 10
> 
> ![image](https://user-images.githubusercontent.com/70793545/215282974-b8dce8d5-c8b5-4b3f-baef-62907f498b68.png)

My problem was solved by installing wsl
Do you have it installed?
