### ISSUE TITLE
[HELP-WANTED] Add new Appwrite Playgrounds

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#503]
Appwrite playgrounds are a set of repositories with language/platform-specific Appwrite integration code samples. Each playground is composed of a readme file and a single code file with examples of different API calls to demonstrate how to initialize and use Appwrite SDK. 

We have playgrounds for a few platforms, and we would love to get the community help with adding new ones and improve the existing ones.

Current Status:

- [x] [Web](https://github.com/appwrite/playground-for-js)
- [x] [Flutter](https://github.com/appwrite/playground-for-flutter)
- [x] [Deno](https://github.com/appwrite/playground-for-deno)
- [x] [Node.js](https://github.com/appwrite/playground-for-node) (DONE - @PineappleIOnic)
- [x] [Python](https://github.com/appwrite/playground-for-python)  (DONE - @Nibba2018)
- [x] Ruby (DONE - @avinashupadhya99 https://github.com/appwrite/playground-for-ruby/pull/4)
- [x] [PHP](https://github.com/appwrite/playground-for-python) (DONE - @sparkingdark)

We'll update the list above when more SDKs will become available (#419). You can use any of the existing playgrounds as a template for new playgrounds. If you wish to help with this issue, please let me know, and I'll assign you and create a new repo for you to submit your PR.

**Comment by eldadfux** [comment]
First PR to the Node.js playground by @PineappleIOnic was just merged. 👌🏻

https://github.com/appwrite/playground-for-node/pull/1

**Comment by Nibba2018** [comment]
Hello @eldadfux , I would like to contribute for Python.

**Comment by eldadfux** [comment]
Hey @Nibba2018, I assigned you to the issue and opened a new repo in the Appwrite namespace where you can submit the PR: https://github.com/appwrite/playground-for-python.

**Comment by divyake** [comment]
Hey @eldadfux , I would like to contribute for Node.js .

**Comment by sid071999** [comment]
Hey @eldadfux I would like to work on flutter playground. Should I create a new example or make changes to the existing one.

**Comment by adithyaakrishna** [comment]
Hey @eldadfux Would developing a new playground in react-native be good? If so, Would like to work on it :)

**Comment by sparkingdark** [comment]
Hey @eldadfux  assign it to me in Ruby or php any of these.

**Comment by eldadfux** [comment]
> Hey @eldadfux I would like to work on flutter playground. Should I create a new example or make changes to the existing one.

We already have a Flutter playground. If you have any meaningful improvement please open an issue before submitting a PR.
https://github.com/appwrite/playground-for-flutter

**Comment by eldadfux** [comment]
> Hey @eldadfux Would developing a new playground in react-native be good? If so, Would like to work on it :)

Our general idea for playground is keep them very simple, that's why all of our playground use vanilla code and no language specific frameworks.

**Comment by eldadfux** [comment]
> Hey @eldadfux assign it to me in Ruby or php any of these.

I will assign you to both, please update this issue if you have any problems or issue not allowing you to complete any of the playgrounds so we could ask someone else for help.

Please use best practices and coding-standards for each language playground, and make sure to follow other playgrounds work as reference. This will help make sure all of our playground are consistent and helpful.

**Comment by sparkingdark** [comment]
Thanks for assigning me.Can I use some formatter to make the code neat and clean?

**Comment by PineappleIOnic** [comment]
@sparkingdark Feel free to use formatter in your playground, We all normally use it anyway 👍

**Comment by sparkingdark** [comment]
Thank you. I am starting to work on it.

**Comment by sparkingdark** [comment]
Hey @eldadfux can you open a repository for playground-for-php  and playground-for-rubyI don't find one.

**Comment by eldadfux** [comment]
PHP and Python playgrounds are ready, @sparkingdark do you still want to work on the Ruby one?

**Comment by sparkingdark** [comment]
Yes man I will do it

**Comment by eldadfux** [comment]
Update: Ruby Playground was merged here: https://github.com/appwrite/playground-for-ruby/pull/4 - as we completed all missing playground for now, I'm finally closing this issue 🎊

Thanks to everyone who helped!
