### ISSUE TITLE
📚 Documentation: In  Appwrite for flutter section,  clicking on `Next Step` doesn't do anything

### ISSUE THREAD

**Issue by Vedsaga** [appwrite/appwrite#5031]
### 💭 Description

Going to Appwrite for flutter... And, clicking on `Next Step` doesn't do anything...
![image](https://user-images.githubusercontent.com/59083528/213904618-b9b4f485-8ee7-4395-b90e-d62890c4f271.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by BhuvaneshPatil** [comment]
Hello @Vedsaga,  I think the current behavior is as expected. If we observe, the URL is https://appwrite.io/docs/getting-started-for-flutter#nextSteps which points to `#next-section` of the same page.

The reason for creating a URL is for SEO purposes. If anyone searches for the same it will be easier.

Let's see what core team says on this.

**Comment by Xazin** [comment]
I agree, this looks like correct behavior.

Instead, we could add some links to these alleged "different API references docs" - At least some of "them".

**Comment by stnguyen90** [comment]
As @BhuvaneshPatil said, it's behaving as expected.

> Instead, we could add some links to these alleged "different API references docs" - 

@Xazin, the References are listed in the sidebar:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/1477010/214955610-7e256bee-cdb2-4849-b14c-4fac428d730d.png">

> At least some of "them".

That's a conundrum...It might be odd only to show some of them. And adding all of them means duplicating a list which we would need to make sure is updated....🤔

**Comment by Xazin** [comment]
> As @BhuvaneshPatil said, it's behaving as expected.
> 
> > Instead, we could add some links to these alleged "different API references docs" - 
> 
> @Xazin, the References are listed in the sidebar:
> 
> <img width="220" alt="image" src="https://user-images.githubusercontent.com/1477010/214955610-7e256bee-cdb2-4849-b14c-4fac428d730d.png">
> 
> > At least some of "them".
> 
> That's a conundrum...It might be odd only to show some of them. And adding all of them means duplicating a list which we would need to make sure is updated....🤔

Makes sense, I guess as I was on the phone I didn't see the sidebar menu at the same time.

It still feels either redundant or a bit ambiguous.

The next steps coming from a Getting Started perspective would most likely be setting up some data structure (database + collections) before using the References to integrate.

Taking it from yet another perspective, the next step for most projects would most likely be Authentication (the Guide)

And neither of those two are found in References.

Some of the other Getting Started X does not have this Next Steps section. And all it does is say that there are a References section somewhere.

But as it all can be found in the sidebar menu, whether or not that next steps is there is irrelevant in its current form IMO.

**Comment by stnguyen90** [comment]
> Makes sense, I guess as I was on the phone I didn't see the sidebar menu at the same time.
> 
> It still feels either redundant or a bit ambiguous.
> 
> The next steps coming from a Getting Started perspective would most likely be setting up some data structure (database + collections) before using the References to integrate.
> 
> Taking it from yet another perspective, the next step for most projects would most likely be Authentication (the Guide)
> 
> And neither of those two is found in References.
> 
> Some of the other Getting Started X does not have this Next Steps section. And all it does is say that there is a References section somewhere.
> 
> But as it all can be found in the sidebar menu, whether or not the next steps is there is irrelevant in its current form IMO.

@gewenyu99, thoughts on this?

**Comment by gewenyu99** [comment]
> > Makes sense, I guess as I was on the phone I didn't see the sidebar menu at the same time.
> > It still feels either redundant or a bit ambiguous.
> > The next steps coming from a Getting Started perspective would most likely be setting up some data structure (database + collections) before using the References to integrate.
> > Taking it from yet another perspective, the next step for most projects would most likely be Authentication (the Guide)
> > And neither of those two is found in References.
> > Some of the other Getting Started X does not have this Next Steps section. And all it does is say that there is a References section somewhere.
> > But as it all can be found in the sidebar menu, whether or not the next steps is there is irrelevant in its current form IMO.
> 
> @gewenyu99, thoughts on this?

We're gonna rework the flow here a bit. Still planning, leave this open and assign it to me. It'll be fixed by related fixes.

**Comment by gewenyu99** [comment]
> @gewenyu99, thoughts on this?

Another thought on this... We might wanna have a landing page for the references section so we can link to "API References" in general :/

**Comment by eldadfux** [comment]
Closing as this is not relevant in the new docs site.
