### ISSUE TITLE
🐛 Bug Report: Scrollbar is Missing on Safari

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#5037]
### 👟 Reproduction steps

1. Open a long page like the Auth > Settings

### 👍 Expected behavior

The scrollbar appears on the right.

### 👎 Actual Behavior

No scrollbar appears. The problem occurs with both dark and light theme.

Safari:

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1477010/214406081-35fef7c9-2e25-4c38-b04a-c94989163e8f.png">

Chrome:

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/1477010/214406171-cbfdc509-a9ea-4757-a0f3-f1d10f644d32.png">

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Safari Version 15.6.1 (17613.3.9.1.16)
MacOS Version 12.6.2 (21G320)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by elad2412** [comment]
Add fix in branch: style-level-6.

Next week, I hope, we are going to add adaptations for all new things from Pink Design to Console 2.0 and we will publish release with this fix
