### ISSUE TITLE
New operators for listDocuments

### ISSUE THREAD

**Issue by marcelinhov2** [appwrite/appwrite#504]
Hey, as we spoke at Discord channel it would be great if appwrite team add new operators for startwith, endwith, contains and like for the listDocuments method.

Thanks.

- [ ] startwith
- [ ] endwith
- [ ] contains
- [ ] not contains
- [ ] like
- [ ] not like
- [ ] is null
- [ ] is not null

**Comment by eldadfux** [comment]
@marcelinhov2 I have added to your original message more operators that might be useful for this endpoint.

We might also use this issue to add `and` and `or` operators for more complex queries.

**Comment by fightforlife** [comment]
Would love to see AND or OR connections.
This would be really helpful in a relationship database where you just want to store 1 row per relationship. Then you could query for a user in key1 OR key2
(e.g. friendships)

**Comment by eldadfux** [comment]
@fightforlife please check our RFC discussing this issue, we're still trying to figure our the best format to support this: https://github.com/appwrite/rfc/pull/21

**Comment by eldadfux** [comment]
We have upgraded and improved the database operators in version 0.12. Closing this in favor of #2201

**Comment by eldadfux** [comment]
You can learn more about the new version here: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
