### ISSUE TITLE
🐛 Bug Report: SMS Verfification Code not send via Text-magic

### ISSUE THREAD

**Issue by nbehler13** [appwrite/appwrite#5040]
### 👟 Reproduction steps

When I setup my flutter app with appwrite locally, I implemented a phone auth as login method just like in the docs. Since I am running appwrite in docker, I changed the .env file in the appwrite folder like the docs say with text-magics username and API-key. 
To reproduce the exception, simply try to start a phone session like in the docs or my code below.
```
startPhoneSession(String phone) async {
    try {
      _user ??= User();
      if (account == null) {
        _init();
      }
      var token =
          await account!.createPhoneSession(userId: ID.unique(), phone: phone);
      _user!.id = token.userId;
      _storeUserId();
    } catch (error) {
      //Do something with the error...
      print(error);
    }
  }
```

### 👍 Expected behavior

It should send a SMS via Text-magic with the verification code for the given phone number.

### 👎 Actual Behavior

It actually throws the following exception in the messaging worker.
```
[notice] Starting work on (Job{v1-messaging} | ID: e8dbb2e55c8e618a1e31179d42f9a22f | MessagingV1 | [{"project":null,"user":null,"payload":[],"recipient":"+123456789","message":"123456","events":["."]}])
[critical] (Job{v1-messaging} | ID: e8dbb2e55c8e618a1e31179d42f9a22f | MessagingV1 | [{"project":null,"user":null,"payload":[],"recipient":"+123456789","message":"123456","events":["."]}]) has failed TypeError: strlen(): Argument #1 ($str) must be of type string, array given in /usr/src/code/vendor/utopia-php/messaging/src/Utopia/Messaging/Adapter.php:59
Stack trace:
#0 /usr/src/code/vendor/utopia-php/messaging/src/Utopia/Messaging/Adapters/SMS/TextMagic.php(54): Utopia\Messaging\Adapter->request('POST', 'https://rest.te...', Array, Array)
#1 /usr/src/code/vendor/utopia-php/messaging/src/Utopia/Messaging/Adapters/SMS.php(33): Utopia\Messaging\Adapters\SMS\TextMagic->process(Object(Utopia\Messaging\Messages\SMS))
#2 /usr/src/code/app/workers/messaging.php(69): Utopia\Messaging\Adapters\SMS->send(Object(Utopia\Messaging\Messages\SMS))
#3 /usr/src/code/src/Appwrite/Resque/Worker.php(121): MessagingV1->run()
#4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
#5 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#6 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#7 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)
#8 {main}
```

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I use docker desktop with no other customizations. Appwrite version is 1.2.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@nbehler13, thanks for creating this issue! 🙏🏼 We'll look into it soon!

**Comment by stnguyen90** [comment]
This looks odd...[`Adapter`'s definition of `request()` says `$body` is `mixed`](https://github.com/utopia-php/messaging/blob/3a0d6b91ec75e3378655af64f895deb8dae23d1e/src/Utopia/Messaging/Adapter.php#L58), but it's used like a string [here](https://github.com/utopia-php/messaging/blob/3a0d6b91ec75e3378655af64f895deb8dae23d1e/src/Utopia/Messaging/Adapter.php#LL60C56-L60C56).

**Comment by nbehler13** [comment]
Hi @stnguyen90, I see the problem was merged any idea when it will be included in the upcomming releases? 😄

**Comment by nbehler13** [comment]
Thanks! 👍🏼
