### ISSUE TITLE
📚 Documentation: Accountability / Revision History / Tracking

### ISSUE THREAD

**Issue by MentalGear** [appwrite/appwrite#5048]
### 💭 Description

Thank you for this awesome BAAS and the great documentation (only a search function would even further improve it )!

To use AppWrite as production ready though, I was wondering if there are modules for Account Change Tracking (Accountability) and a revision history?

Also, are Graph DB as well supported (e.g. Surreal DB) ?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@MentalGear thanks for creating this issue! 🙏🏼 

> only a search function would even further improve it 

You might want to 👍🏼 [this](https://github.com/appwrite/docs/issues/300) issue.

> I was wondering if there are modules for Account Change Tracking (Accountability) and a revision history?

Appwrite has some audit logs. In the Console, you can see this in the "Activity" tabs for a Collection or Document. It looks like they're only accessible with an Admin account (i.e. not via server SDK). More details on the API can be found here: 

https://github.com/appwrite/appwrite/blob/81b08de407a4dbcde70ad591ca9015f18e1e8a4c/app/controllers/api/databases.php#L632

> Also, are Graph DB as well supported (e.g. Surreal DB) ?

The only supported database right now is MariaDB. Other databases are coming soon, but most of Appwrite's functionality won't change based on the underlying database.

**Comment by MentalGear** [comment]
Thx for the reply!

>Appwrite has some audit logs. In the Console, you can see this in the "Activity" tabs for a Collection or Document. It looks like they're only accessible with an Admin account (i.e. not via server SDK). More details on the API can be found here:

Ah, so no multi dimensional graph queries any time soon even if other db adapters are available.

Re: audit
https://github.com/appwrite/appwrite/discussions/4901

**Comment by stnguyen90** [comment]
> Ah, so no multi dimensional graph queries any time soon even if other db adapters are available.

Not in the near future. We've discussed the possibility of database-specific queries, but that's still TBD.

Can this be closed now?

**Comment by MentalGear** [comment]
Yes, thank you ! Will return to appwrite when a proper audit / document revision system is available.
