### ISSUE TITLE
Cant Register on a new installation 

### ISSUE THREAD

**Issue by redamakarem** [appwrite/appwrite#5059]
Hello,
I installed Appwrite v1.20 on ubuntu 20.04 using the bash scripts
The install went smooth but when I attempted to sign up, I just get a toast message that says: "Server Error"
Just to be clear, I am referring to creating the admin account after a fresh install

 Can someone please help me with fixing this issue?
 Thanks

**Comment by hashem78** [comment]
+1

**Comment by Nandini99-git** [comment]
hey , I got some videos on installation . watch this and try installing again, I hope this will help.
https://youtu.be/jlhXQFFn0oc
https://youtu.be/aO4mw8smXkI

**Comment by redamakarem** [comment]
Thank you for the videos. I did come across these. I did a clean re-install but nothing worked

**Comment by Nandini99-git** [comment]
can you send me the screen shot of that error.

**Comment by Nandini99-git** [comment]
It looks like you are sign in for the first time. Follow this step

click to sign-in now
accept the certificate
and now try to sign up
I hope this will help.

**Comment by redamakarem** [comment]
Hello,
Could you please explain where I can accept the  certificate?
Below is a screenshot of the error
![image](https://user-images.githubusercontent.com/9447486/215335738-143f9166-8b23-4e07-b501-16eb26ed13fa.png)
Thank you

**Comment by stnguyen90** [comment]
@redamakarem would you please check the docker logs for your appwrite container and find the related log for the 500 error?

Also, did you ever install Appwrite before?

**Comment by redamakarem** [comment]
hello, yes I did install Appwrite before

below is the log output for appwrite container:

Worker 150 started successfully
Worker 153 started successfully
Worker 152 started successfully
Worker 155 started successfully
Worker 154 started successfully
Worker 157 started successfully
Worker 156 started successfully
Worker 158 started successfully
Worker 160 started successfully
Worker 159 started successfully
Worker 162 started successfully
Worker 161 started successfully
Worker 164 started successfully
Worker 163 started successfully
Worker 165 started successfully
Worker 166 started successfully
Worker 169 started successfully
Worker 167 started successfully
Worker 168 started successfully
Worker 170 started successfully
Worker 172 started successfully
Worker 171 started successfully
Worker 174 started successfully
Worker 173 started successfully
Worker 176 started successfully
Worker 175 started successfully
Worker 177 started successfully
Worker 180 started successfully
Worker 178 started successfully
Worker 179 started successfully
Worker 181 started successfully
Worker 182 started successfully
Worker 185 started successfully
Worker 183 started successfully
Worker 184 started successfully
Worker 187 started successfully
Worker 186 started successfully
Worker 189 started successfully
Worker 188 started successfully
Worker 191 started successfully
Worker 190 started successfully
Worker 193 started successfully
Worker 192 started successfully
Worker 195 started successfully
Worker 194 started successfully
Worker 197 started successfully
Worker 196 started successfully
Worker 198 started successfully
Worker 199 started successfully
Worker 200 started successfully
Worker 201 started successfully
Worker 202 started successfully
Worker 203 started successfully
Worker 204 started successfully
Worker 206 started successfully
Worker 205 started successfully
Worker 207 started successfully
Worker 208 started successfully
Worker 209 started successfully
Worker 211 started successfully
Worker 210 started successfully
Worker 212 started successfully
Worker 214 started successfully
Worker 213 started successfully
Worker 215 started successfully
Worker 216 started successfully
[Setup] - Server database init started...
[Setup] - Creating database: appwrite...
[Setup] - Server database init completed...
Server started successfully (max payload is 6,291,456 bytes)
Master pid 1, manager pid 8
0.0.0.0 is not a publicly accessible domain. Skipping SSL certificate generation.
[Error] Timestamp: 2023-01-29T15:56:58+00:00
[Error] Method: GET
[Error] URL: /v1/account
[Error] Type: Appwrite\Extend\Exception
[Error] Message: User (role: guests) missing scope (account)
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 365
[Error] Timestamp: 2023-01-29T15:56:58+00:00
[Error] Method: GET
[Error] URL: /v1/account
[Error] Type: Appwrite\Extend\Exception
[Error] Message: User (role: guests) missing scope (account)
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 365
[Error] Timestamp: 2023-01-29T15:57:01+00:00
[Error] Method: GET
[Error] URL: /v1/account
[Error] Type: Appwrite\Extend\Exception
[Error] Message: User (role: guests) missing scope (account)
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 365
[Error] Timestamp: 2023-01-29T15:57:12+00:00
[Error] Method: POST
[Error] URL: /v1/account
[Error] Type: Utopia\Database\Exception\Structure
[Error] Message: Invalid document structure: Attribute "time" has invalid type. Value must be a valid integer
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 1364

Thank you

**Comment by RiVerSZ** [comment]
Hi wanted also to say I have the same problem. I'm installing appwrite over docker compose file + .env with Portainer. I deleted all volumes all folders. 

If I do a fresh install, the first "sign up setup" flow is not happening. Instead, I go directly to the login page.

**Comment by redamakarem** [comment]
I also tried portainer but no success either. Hoping to hear some good news cz I suggested to use appwrite for a startup lol

**Comment by rvlaskamp** [comment]
I have also the same problem. With version 1.2, clean install, I cannot register my root account

**Comment by stnguyen90** [comment]
@redamakarem, would you please try accessing your Appwrite instance at localhost rather than 0.0.0.0?

Also, fyi, Appwrite works best when accessed on the standard ports.

**Comment by redamakarem** [comment]
Thank you for the response, still getting same error
I tried localhost but no change
and just FYI, I had a previous version of Appwrite (which I removed) that worked fine on the same ports

**Comment by redamakarem** [comment]
Thanks to @stnguyen90  I was able to get things working
Using Portainer, I removed all containers, volumes and networks and then ran the installation script

**Comment by RiVerSZ** [comment]
so you could register your admin account?

**Comment by stnguyen90** [comment]
> If I do a fresh install, the first "sign up setup" flow is not happening. Instead, I go directly to the login page.

@RiVerSZ there is no sign up flow in the new console at the moment. You should be able to click on sign up and then create your admin account.

**Comment by redamakarem** [comment]
> so you could register your admin account?

yes I was able to create an admin account after deleting all containers and volumes to make sure I started clean
