### ISSUE TITLE
🐛 Bug Report: dashboard Appwrite crash when i click on a document

### ISSUE THREAD

**Issue by elio1fiore** [appwrite/appwrite#5063]
### 👟 Reproduction steps

I'm on a VM(e2) on GCP.
The version of Appwrite is 1.2.0
When I click on any document in a collection from the dashboard, the Appwrite dashboard completely freezes.

I show the network at the moment of the click.

![](https://cdn.discordapp.com/attachments/1062482819567341648/1069682558524215306/Screenshot_2023-01-30_alle_19.16.00.png)

The most interesting matter comes from the console logs

![](https://cdn.discordapp.com/attachments/1062482819567341648/1069683644924444823/Screenshot_2023-01-30_alle_19.20.46.png)

### 👍 Expected behavior

I expect the red loading line to finish and show me the data in the document

### 👎 Actual Behavior

<img width="563" alt="Screenshot 2023-01-30 alle 19 57 53" src="https://user-images.githubusercontent.com/54111358/215569725-ff90a070-98de-4757-b45b-47ccbf7ee7ba.png">

After the click it blocks without showing data and the loading bar remains fixed in that position.

Although I click on the logo to return to the "home" screen, it doesn't work. So no command either. The only way to unlock the dashboard is to edit the url

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@elio1fiore, thanks for creating this issue! 🙏🏼 A couple more questions/requests:

1. Does this happen with every collection?
2. Would you please provide the schema for the collection (appwrite.json would be the best way to share this)
3. Would you please also share the HTTP response body for the document?

**Comment by stnguyen90** [comment]
After troubleshooting this a bit further, we determined the problem was malformed permissions caused by [this related issue](https://github.com/appwrite/appwrite/issues/4543). If a document's permissions attribute is an object rather than an array, the console will break.
