### ISSUE TITLE
Changing Port is not working

### ISSUE THREAD

**Issue by Blacktoviche** [appwrite/appwrite#507]
I'm installing Appwrite on my own VPS . I already use 80 and 443 ports so I have to change Appwrite ports
I used the default installation method but it's not working it's always produce 
`Failed to fetch Docker Compose file`
It worked on my virtual maching but never on my online VPS.

So I downloaded https://appwrite.io/docker-compose.yml and run docker-compose up -d
after I edited the port like this : 
`ports:
            - 7000:80
            - 7443:443`
Things went smooth but
When I open my VPS on port 7000 it redirect me to my website on port 80
Also the same when open my VPS on port 7443 it direct me to 443

What the right way to change Appwrite ports?

**Comment by eldadfux** [comment]
Did you customised any other env vars like _APP_OPTIONS_FORCE_HTTPS? Please share your complete docker compose file (please hide any secrets if you use any)

**Comment by Blacktoviche** [comment]
It seems I have only changed _APP_DOMAIN and _APP_DOMAIN_TARGET to  my online domain.
I reset its values to localhost but now when I open the page on port 7443 nothing appear.

> env vars like _APP_OPTIONS_FORCE_HTTPS?

There is no such an option in the docker file!
Here is the complete file:

`version: '3'

services:
    traefik:
        image: traefik:v2.1.4
        command:
            - --providers.file.directory=/storage/config
            - --providers.file.watch=true
            - --providers.docker=true
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
        restart: unless-stopped
        ports:
            - 7000:80
            - 7443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - appwrite-config:/storage/config:ro
            - appwrite-certificates:/storage/certificates:ro
        depends_on:
            - appwrite
        networks:
            - gateway
            - appwrite
    
    appwrite:
        image: appwrite/appwrite:latest
        restart: unless-stopped
        networks:
            - appwrite
        labels:
            - traefik.http.routers.appwrite.rule=PathPrefix(`/`)
            - traefik.http.routers.appwrite-secure.rule=PathPrefix(`/`)
            - traefik.http.routers.appwrite-secure.tls=true
        volumes:
            - appwrite-uploads:/storage/uploads:rw
            - appwrite-cache:/storage/cache:rw
            - appwrite-config:/storage/config:rw
            - appwrite-certificates:/storage/certificates:rw
        depends_on:
            - mariadb
            - redis
            - smtp
            - clamav
            - influxdb
            - telegraf
        environment:
            - _APP_ENV=production
            - _APP_OPENSSL_KEY_V1=your-secret-key
            - _APP_DOMAIN=localhost
            - _APP_DOMAIN_TARGET=localhost
            - _APP_REDIS_HOST=redis
            - _APP_REDIS_PORT=6379
            - _APP_DB_HOST=mariadb
            - _APP_DB_PORT=3306
            - _APP_DB_SCHEMA=appwrite
            - _APP_DB_USER=user
            - _APP_DB_PASS=password
            - _APP_INFLUXDB_HOST=influxdb
            - _APP_INFLUXDB_PORT=8086
            - _APP_STATSD_HOST=telegraf
            - _APP_STATSD_PORT=8125
            - _APP_SMTP_HOST=smtp
            - _APP_SMTP_PORT=25

    mariadb:
        image: appwrite/mariadb:1.0.3
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-mariadb:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=rootsecretpassword
            - MYSQL_DATABASE=appwrite
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        command: 'mysqld --innodb-flush-method=fsync'

    smtp:
        image: appwrite/smtp:1.0.1
        restart: unless-stopped
        networks:
            - appwrite
        environment:
            - MAILNAME=appwrite
            - RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16

    redis:
        image: redis:5.0
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-redis:/data:rw

    clamav:
        image: appwrite/clamav:1.0.9
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-uploads:/storage/uploads

    influxdb:
        image: influxdb:1.6
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-influxdb:/var/lib/influxdb:rw

    telegraf:
        image: appwrite/telegraf:1.0.0
        restart: unless-stopped
        networks:
            - appwrite

networks:
    gateway:
    appwrite:

volumes:
    appwrite-mariadb:
    appwrite-redis:
    appwrite-cache:
    appwrite-uploads:
    appwrite-certificates:
    appwrite-influxdb:
    appwrite-config:`

**Comment by eldadfux** [comment]
What is your terminal output for `docker ps`?

**Comment by Blacktoviche** [comment]
Here it is: 


`CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                         NAMES
a36e03cd482e        traefik:v2.1.4             "/entrypoint.sh --pr…"   17 minutes ago      Up 17 minutes       0.0.0.0:7000->80/tcp, 0.0.0.0:7443->443/tcp   appwrite_traefik_1
42dd3b4c4dee        appwrite/appwrite:latest   "/bin/bash /usr/loca…"   17 minutes ago      Up 17 minutes       80/tcp                                        appwrite_appwrite_1
f0fa676a5bbd        influxdb:1.6               "/entrypoint.sh infl…"   9 hours ago         Up 9 hours          8086/tcp                                      appwrite_influxdb_1
2473c91ab8aa        appwrite/smtp:1.0.1        "/bin/entrypoint.sh …"   9 hours ago         Up 9 hours          25/tcp                                        appwrite_smtp_1
9328bbaf51f7        appwrite/mariadb:1.0.3     "docker-entrypoint.s…"   9 hours ago         Up 9 hours          3306/tcp                                      appwrite_mariadb_1
57d9c6f24e52        appwrite/telegraf:1.0.0    "/entrypoint.sh tele…"   9 hours ago         Up 9 hours          8092/udp, 8125/udp, 8094/tcp                  appwrite_telegraf_1
86d9baa33053        redis:5.0                  "docker-entrypoint.s…"   9 hours ago         Up 9 hours          6379/tcp                                      appwrite_redis_1
bd72731ec0fc        appwrite/clamav:1.0.9      "/bin/bash /entrypoi…"   9 hours ago         Up 9 hours          3310/tcp                                      appwrite_clamav_1`

**Comment by eldadfux** [comment]
Your docker-compose seems to work fine on my env. What exactly is the response your'e getting when trying to access the console?

Plus, it might be worth the shot, to try and access the console from both incognito mode, or with cache disabled on your devtools.

**Comment by Blacktoviche** [comment]
I tried to open the console but nothing , it seems like nothing is listening on the port.
I checked the port it's open

**Comment by eldadfux** [comment]
Are you accessing it directly from your domain or server IP? does your server has any firewall rules preventing access to ports 7000/7443?

**Comment by Blacktoviche** [comment]
I use a firewall but I opened 7000/7433. I also checked it using free port check tool
I deleted everything and start again but it's redirecting me to port 80/443 when im trying to open console on 700/7443.
Would you like to see it yourself? I can give you access to the VPS?

**Comment by eldadfux** [comment]
Yeh sure, you can email me at: eldad@appwrite.io or send me a DM at https://appwrite.io/discord

**Comment by Blacktoviche** [comment]
I sent you an email with the VPS info.
Thankx

**Comment by eldadfux** [comment]
It seems like the app you run on port 80 is listening to all other ports as well. This is not an HTTP redirect. Do you run any proxy or something similar that might affect this?

What happens when you run Appwrite standalone?

**Comment by Blacktoviche** [comment]
Nothing is listening on port 80 . I redirect my app from X port to 80,

Here is the ports listening log:

` 7000 * (docker-proxy)
   [15] allow 7000
   [17] allow 7000/tcp

  7443 * (docker-proxy)
   [16] allow 7443
   [18] allow 7443/tcp`

Docker is listening on 7000/7443

> What happens when you run Appwrite standalone? 

What do you mean by that?  How can I run it standalone ?

**Comment by eldadfux** [comment]
It seems like your port redirection is affecting more ports than just port 80. By standalone, I mean running it with no other apps on a server or on your desktop.

**Comment by Blacktoviche** [comment]
I run it locally on Virtual Machine it works perfect.
I'm gonna make an exact copy of the VPS locally and try to change ports. because I can't do so much online
and will get back here when I solve the problem.

Thankx

**Comment by eldadfux** [comment]
👌🏻

**Comment by Blacktoviche** [comment]
After five hours of work the problem is with the r"edirect port" in my system.
Using iptables to redirect port is a bad idea. I used nginx.
Appwrite is working now.

Thanks @eldadfux for your time

**Comment by eldadfux** [comment]
🥳 your'e welcome to join us on Discord and share your work when it's ready 👍 https://appwrite.io/discord

**Comment by Blacktoviche** [comment]
I did join you on discord . and Sure will share it when it's ready
