### ISSUE TITLE
🐛 Bug Report: session create event doesn't show in Appwrite Console user activity for OAuth Sessions

### ISSUE THREAD

**Issue by kstuhr** [appwrite/appwrite#5070]
### 👟 Reproduction steps

When I in a Flutter SDK use the account.createOAuth2Session() with provider set to either 'facebook' or 'google' (only ones I use so others might also have the challenge) to sign in with OAuth2 in my app.

### 👍 Expected behavior

It should log my user in and the "user.*.sessions.*.create" events should be created and in the Appwrite console I should under Auth -> Users -> Activity see "session.create" event.

### 👎 Actual Behavior

I see the events being generated as I have a function that is triggered by "user.*.sessions.*.create" events so that is fine and the user is logged into my app. But the "session.create" event never shows in the console. 

![image](https://user-images.githubusercontent.com/1477010/216110480-47c314f1-2edd-4420-81f5-b2a01a6790bc.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use DigitalOcean  and there is no special configurations on the 1-click-droplet installed

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@kstuhr thanks for creating this issue! 🙏🏼 Perhaps we're missing some audit labels for OAuth 🧐 

Labels for Create Email Session:

https://github.com/appwrite/appwrite/blob/6a26d9db39f50b29055583ff18688f1c56121c32/app/controllers/api/account.php#L142-L150

Versus OAuth2 Redirect:

https://github.com/appwrite/appwrite/blob/6a26d9db39f50b29055583ff18688f1c56121c32/app/controllers/api/account.php#L367-L374

**Comment by singhbhaskar** [comment]
Hey @stnguyen90 ,

I have worked on this issue and raised a PR. Please review the PR: https://github.com/appwrite/appwrite/pull/5083

I had ran the unit test case and e2e test on my local system. However, as this is my first issue I was not able to find any document which included information about testing other than running the tests. Please let me know if I missed anything.

**Comment by singhbhaskar** [comment]
Hey  @stnguyen90,

I am adding the screenshot kindly check it once.
<img width="1417" alt="Screenshot 2023-02-19 at 8 47 06 PM" src="https://user-images.githubusercontent.com/20492520/219957255-5d28f5b7-7b17-4e71-9800-5ee4a28e424a.png">
