### ISSUE TITLE
Not Able To Sign Up

### ISSUE THREAD

**Issue by anujagr11** [appwrite/appwrite#508]
I have installed appwrite on my windows and after the installation when I open my localhost i am not able to sign up it says "Registration Failed please try later" it has been 2 days till now it says the same .

**Comment by eldadfux** [comment]
@anujagr11 the same issue has just been resolved in our Discord channel by removing all the setup volumes and containers and recreating them.

Try to run this command from the location of your `docker-compose.yml` file:

```
docker-compose down -v && docker-compose up -d
```

Note that this will reset all your Appwrite data and files if you have any!

The original solution was suggested here:
https://stackoverflow.com/questions/57431413/connection-error-mariadb-wordpress-with-docker
