### ISSUE TITLE
📚 Documentation: Missing example for accountCreateOauth2Session (GraphQL)

### ISSUE THREAD

**Issue by NobleUpFront** [appwrite/appwrite#5082]
### 💭 Description

Graphql documentation is missing an example for "accountCreateOAuth2Session"

https://appwrite.io/docs/client/account?sdk=graphql-default#accountCreateOAuth2Session

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by NobleUpFront** [comment]
I might not be looking into it correectly. 
But from the schema fetched from postman, it does not look like its implemented.

![image](https://user-images.githubusercontent.com/20728089/216819735-7c4fe3ec-0e89-45e2-9644-f1df8753ea45.png)

Is this on purpose?

**Comment by NobleUpFront** [comment]
Update:

Its not supported, leaving the issue open, such that the documentation can be updated.

**Comment by stnguyen90** [comment]
> Its not supported, leaving the issue open, such that the documentation can be updated.

@gewenyu99, what do you think about adding some sort of documentation to mention it's not supported?

**Comment by gewenyu99** [comment]
> > Its not supported, leaving the issue open, such that the documentation can be updated.
> 
> @gewenyu99, what do you think about adding some sort of documentation to mention it's not supported?

 Sure， I can add in the tab and mention that it's not supported.

**Comment by abnegate** [comment]
@stnguyen90 @gewenyu99 We do mention that oauth isn't available at the top of the page here: https://appwrite.io/docs/graphql, but the confusion is that there's no example here in the references here: https://appwrite.io/docs/client/account?sdk=graphql-default#accountCreateOAuth2Session. The linked PR is only updating the auth guide (which we should still do as well)

**Comment by gewenyu99** [comment]
> @stnguyen90 @gewenyu99 We do mention that oauth isn't available at the top of the page here: https://appwrite.io/docs/graphql, but the confusion is that there's no example here in the references here: https://appwrite.io/docs/client/account?sdk=graphql-default#accountCreateOAuth2Session. The linked PR is only updating the auth guide (which we should still do as well)

😬 I see, maybe we should default empty templates to something that says this endpoint is not available with the selected version and SDK combination. Let me take a looksies

**Comment by gewenyu99** [comment]
I'm going to close this. We've added a notice saying that OAuth2 isn't supported for GraphQL.
