### ISSUE TITLE
Python 3.11 Support for Functions

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#5088]
### Discussed in https://github.com/appwrite/appwrite/discussions/5077

<div type='discussions-op-text'>

<sup>Originally posted by **greendesertsnow** February  3, 2023</sup>
Hey!
3.11 is 60% faster. Does Appwrite support it?</div>

**Comment by stnguyen90** [comment]
Appwrite does not currently support Python 3.11, but there is work being done to add support here: https://github.com/open-runtimes/open-runtimes/issues/110

**Comment by sheecegardezi** [comment]
It python core is being updated, its definitely becoming faster and using less memory:
https://docs.python.org/3/whatsnew/3.11.html#:~:text=Python%203.11%20is%20between%2010,on%20the%20standard%20benchmark%20suite.
