### ISSUE TITLE
[FEATURE] Add MQTT communication 

### ISSUE THREAD

**Issue by raul-parada** [appwrite/appwrite#509]
Communication with IoT devices using MQTT will provide an additional attention to use Appwrite.

**Comment by eldadfux** [comment]
Hey Raul, this sounds extremely interesting. I would love to get some other use cases that you might have in mind and how would you see that kind of feature interacting with Appwrite's APIs (auth, storage, database).

Appwrite already has plans to create more network based protocol for interacting with stuff like GraphQL, GRPC and Protobuf. MQTT sounds interesting, but we could definitely use more community feedback to  better understand how this could be implemented and work well for Appwrite developers.

**Comment by raul-parada** [comment]
Yes, it is a powerful feature. One use case is the connected car: collect, process and display data directly from the on-board unit of a vehicle.

**Comment by codeagencybe** [comment]
Another general use case is to use mqtt or similar like Kafka as a message broker queue. 
Basically it can catch workloads and process them at a later time and return back. 

Typically use cases can be eg request reports that require big data/processing and you don't want to another process to keep waiting for it. So instead you shove it in a queue and return it at a later time. Banking eg that generate financial reports. You can request a report from a dashboard and you receive it a later time by email   
This prevents overloading the system by having too many parallel jobs running. 

Other uses cases: big import / export tasks

**Comment by eldadfux** [comment]
@codeagencybe I'm finding it a little bit difficult to understand how you view this as part of the current Appwrite architecture. Currently we are using Redis to achieve queueing or pub/sub capabilities.

I think cloud functions feature can be an easier solution to the use cases you mentioned. Would be great if you could visualize this over the current architecture diagram, to help me better understand this:
https://github.com/appwrite/appwrite/blob/master/docs/specs/overview.drawio.svg

![image](https://user-images.githubusercontent.com/1297371/90654943-a2339180-e249-11ea-8327-c3e2fc5c40cd.png)

**Comment by brandonroberts** [comment]
Thanks @raul-parada. Our functions have come a long way since this conversation. Let us know if this is still relevant and feel free to reopen if needed.
