### ISSUE TITLE
🐛 Bug Report: Python function does not display execution errors

### ISSUE THREAD

**Issue by 0niel** [appwrite/appwrite#5094]
### 👟 Reproduction steps

1. Upload an archive with an executable Python script without `__init__.py`
2. Try to execute the script

### 👍 Expected behavior
It is necessary to display all errors from the output stream of the executing environment

### 👎 Actual Behavior
Now, when errors occur when executing a function (for example Python), the Errors window displays the message:
> Internal Runtime error!

At the same time, **appwrite-executor** contains the following logs:

> [Error] Type: Exception
> [Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection refused
> [Error] File: /usr/src/code/app/executor.php
> [Error] Line: 541

This does not give me any idea of what kind of error has occurred and how to fix it. I thought that the error was related specifically to the Runtime environment, and not to my script. It turned out that my deployment archive was missing `__init__.py` file, which is why the execution module was not detected.

![image](https://user-images.githubusercontent.com/51058739/217521471-7188ae1c-25d0-4eb3-bae2-4f1b8bda7bdf.png)
![image](https://user-images.githubusercontent.com/51058739/217521403-2a59136f-fb4d-48b5-9b34-944358a72bb0.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@0niel, thanks for creating this issue! 🙏🏼 I think this is actually related to https://github.com/appwrite/appwrite/issues/4594. If the entry point is incorrect, [the function runtime will throw a 500 error](https://github.com/open-runtimes/open-runtimes/blob/a3c6187191dfe48950f6f1de6b9c23839cabd087/runtimes/python-3.10/server.py#L74). When Appwrite receives a 500 error, it sets `stderr` and `stdout` to "Internal Runtime error."

https://github.com/appwrite/appwrite/blob/661581a7f362f7aa26ba8e243b8542a3f2c9a9b4/app/executor.php#L548-L551

As such, would you please 👍🏼 issue https://github.com/appwrite/appwrite/issues/4594 and close this issue?
