### ISSUE TITLE
🐛 Bug Report: Error popups are not coming properly in small screen sizes

### ISSUE THREAD

**Issue by yatharth1706** [appwrite/appwrite#5098]
### 👟 Reproduction steps

Go to functions > Create deployment > Manual and enter any wrong file of unsupported file type or don't enter any file and press create button, the error popup which comes in the right top comes below the modal if window screen is small or browser screen size is increased to more than 100%.

### 👍 Expected behavior

Error popup should come above the modal so that user will be able to see it properly

### 👎 Actual Behavior

Error pop up is coming below the modal
![Screenshot 2023-02-09 223722](https://user-images.githubusercontent.com/32243289/217887293-404045b2-aa21-4b04-8bec-fb17803428ed.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@yatharth1706, thanks for creating this issue! 🙏🏼 Looks like we're using [`addNotification()`](https://github.com/appwrite/console/blob/3c84356c765dc144a2320cb4c2d29e5b8e100f7b/src/routes/console/project-%5Bproject%5D/functions/function-%5Bfunction%5D/create.svelte#L106-L109) to display the error, but we should be [capturing the error](https://github.com/appwrite/console/blob/3c84356c765dc144a2320cb4c2d29e5b8e100f7b/src/routes/console/project-%5Bproject%5D/auth/createUser.svelte#L44) and [binding it to the modal](https://github.com/appwrite/console/blob/3c84356c765dc144a2320cb4c2d29e5b8e100f7b/src/routes/console/project-%5Bproject%5D/auth/createUser.svelte#L57) line in the [createUser modal](https://github.com/appwrite/console/blob/3c84356c765dc144a2320cb4c2d29e5b8e100f7b/src/routes/console/project-%5Bproject%5D/auth/createUser.svelte#L23-L57).

**Comment by martianshaan** [comment]
I would like to take this issue ?

**Comment by stnguyen90** [comment]
@martianshaan, assigned! Thanks for your interest! 🙏🏼

**Comment by stnguyen90** [comment]
@martianshaan, actually, sorry, it looks like we already have a PR for the fix.

**Comment by martianshaan** [comment]
Ok @stnguyen90  Thanks .
