### ISSUE TITLE
While accessing database in dashboard, pagination is very slow and painful when data count is large.

### ISSUE THREAD

**Issue by aishvergil** [appwrite/appwrite#510]
When my database has more than significant amount of items like getting to next page on database list in dashboard is very slow and unresponsive. The browser completely hangs. I am on windows 10 and using the website on Chrome. I have 24 GB Ram and i5 7th generation so that should not be an issue.
This really makes viewing and editing documents inside dashboard very very painful.

**Comment by eldadfux** [comment]
Hey @aishvergil, thanks for reporting this issue. This is a known issue that can happen on specific large datasets.

We are working on a fix that will hopefully be available as soon as next version (this has become a top priority right now).

We are also going to add more capabilities for custom indexing that will allow you to optimize and tune your data queries x time better than in the current version.

You can follow more update on this issue in the coming days: #506

**Comment by eldadfux** [comment]
This issue was fixed and its now available as part of Appwrite 0.12. You can learn more about the new version here: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
