### ISSUE TITLE
🐛 Bug Report: Inappropriate message will uploading the functions

### ISSUE THREAD

**Issue by sannanansari** [appwrite/appwrite#5104]
### 👟 Reproduction steps

![217887293-404045b2-aa21-4b04-8bec-fb17803428ed](https://user-images.githubusercontent.com/30230441/218261462-c8358769-0ad3-449d-86fb-3d8e1d31b53c.png)

While uploading the function I come across this message. 

> cannot read the properties of null (reading '0')

### 👍 Expected behavior

Should have appropriate message.

### 👎 Actual Behavior

> cannot read the properties of null (reading '0')

**Comment by stnguyen90** [comment]
@sannanansari, thanks for creating this issue! 🙏🏼 To clarify, this happens when you don't select a file to upload, right?

**Comment by ArmanNik** [comment]
@sananansaritriarq we already have a PR merged for this https://github.com/appwrite/console/pull/284
