### ISSUE TITLE
Support For Verifying JWT Token using the Server API

### ISSUE THREAD

**Issue by ereio** [appwrite/appwrite#511]
I can extract the token from the x-fallback-cookie in headers for the client, but there's no way to validate these access tokens in the node sdk. If you allow the node-appwrite getSessions query to include each sessions access token, one could authenticate custom endpoints through our own backends and still use the same authentication platform through appwrite. 

A common pattern I use when developing backends is to create a proxy graphql server as an abstraction for every service available. When doing this, I don't want to roll my own authentication each time as it's a liability, but I want to abstract it in case I need to switch auth providers in the future. Firebase allows you to verify tokens using their node sdk and thus check the token being passed by the user in the headers.

Let me know if this makes sense, if you want further clarification, or if I'm missing something here.

Thanks for all your hard work!

**Comment by eldadfux** [comment]
@ereio Would a JWT implementation (https://jwt.io/) in the Appwrite users/account APIs help you accomplish this use case?

**Comment by ereio** [comment]
yes, that would be great

**Comment by eldadfux** [comment]
Added this feature request to our roadmap

**Comment by punitdiwan** [comment]
I always wanted to have this JWT auth in addition to cookie based auth. Its way easier to manage the JWT token from Local Storage. I am excited to learn that it is being implemented. Moreover, its equally secure as cookie based auth.

**Comment by eldadfux** [comment]
JWT draft PR is ready: https://github.com/appwrite/appwrite/pull/784/files 🎉

**Comment by eldadfux** [comment]
JWT is available in a closed beta, if anyone wants to try it please reach me on Discord.

**Comment by TorstenDittmann** [comment]
This got fixed with https://github.com/appwrite/appwrite/releases/tag/0.8.0 👏🏻

**Comment by jdub113113** [comment]
Help me

**Comment by jdub113113** [comment]
Jdizzle11383@gmail.com
