### ISSUE TITLE
🐛 Bug Report: `sudo docker-compose up` gives error : `services.appwrite.build.args contains false, which is an invalid type, it should be a string, number, or a null`

### ISSUE THREAD

**Issue by hemangjoshi37a** [appwrite/appwrite#5120]
### 👟 Reproduction steps

🐛 Bug Report: `sudo docker-compose up` gives error : `services.appwrite.build.args contains false, which is an invalid type, it should be a string, number, or a null`

### 👍 Expected behavior

🐛 Bug Report: `sudo docker-compose up` gives error : `services.appwrite.build.args contains false, which is an invalid type, it should be a string, number, or a null`

### 👎 Actual Behavior

🐛 Bug Report: `sudo docker-compose up` gives error : `services.appwrite.build.args contains false, which is an invalid type, it should be a string, number, or a null`

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

🐛 Bug Report: `sudo docker-compose up` gives error : `services.appwrite.build.args contains false, which is an invalid type, it should be a string, number, or a null`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@hemangjoshi37a, thanks for creating this issue! 🙏🏼 

Would you please provide some more information? Are you trying to spin up Appwrite from source? Would you please also check what version of Docker Compose you have?

**Comment by stnguyen90** [comment]
@hemangjoshi37a, are you still facing this problem? If so, please provide the info requested:

> Would you please provide some more information? Are you trying to spin up Appwrite from source? Would you please also check what version of Docker Compose you have?

Please keep in mind, I'll need to close this due to inactivity soon if there's no response.
