### ISSUE TITLE
🐛 Bug Report: createMagicURLSession without url in mobile

### ISSUE THREAD

**Issue by eroo36** [appwrite/appwrite#5128]
### 👟 Reproduction steps

In project, I set up my package name for the flutter app, I use createMagicURLSession without passing a redirect URL.

### 👍 Expected behavior

When I click to the URL in the email from my phone, it should open the app.

### 👎 Actual Behavior

When I go to the URL in the email from my simulator and from my real android phone, it does not open the app instead, in the web browser, it says missing redirect URL. In the docs, it is mentioned that if you will be using this link from a mobile phone, you don't need to pass a redirect URL.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I self-hosted using [docker compose](https://appwrite.io/install/compose) v1.2.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@eroo36, thanks for creating this issue! 🙏🏼 Would you please confirm you've followed the setup instructions for [iOS](https://github.com/appwrite/sdk-for-flutter#ios) and [Android](https://github.com/appwrite/sdk-for-flutter#android), and replaced `[PROJECT_ID]` with your actual project ID?

**Comment by stnguyen90** [comment]
@eroo36 are you still facing this problem? If so, please provide the info requested:

> Would you please confirm you've followed the setup instructions for [iOS](https://github.com/appwrite/sdk-for-flutter#ios) and [Android](https://github.com/appwrite/sdk-for-flutter#android), and replaced `[PROJECT_ID]` with your actual project ID?
> 
> If the project ID is all correct, would you please try clicking on a fresh link in your desktop browser with the browser dev tools open to see if there are any Console or Network logs?

Please keep in mind I'll need to close this due to inactivity soon if there's no response.

**Comment by eroo36** [comment]
hello again, i will provide the console and network logs

**Comment by eroo36** [comment]
I was able to reproduce the same issue using oauth2 client, in [docs](https://appwrite.io/docs/client/account?sdk=web#accountCreateOAuth2Session) it is mentioned that success url is optional but it guess it is required?
<img width="1260" alt="Screenshot 2023-03-09 at 12 46 42" src="https://user-images.githubusercontent.com/13486466/223983824-f2456809-936c-4c97-927c-93f91c87b7c5.png">

**Comment by eroo36** [comment]
Also when i try to add success url in query param i get:
<img width="1195" alt="Screenshot 2023-03-09 at 12 49 51" src="https://user-images.githubusercontent.com/13486466/223984779-e39d68f1-fd9a-4c08-b89b-599bd64f92c3.png">
Even thought i set the hostname in a web platform from the project:
![Uploading Screenshot 2023-03-09 at 12.50.54.png…]()

**Comment by eroo36** [comment]
I will close this issue and create a new one if i cannot figure the problem with my <data android:scheme="appwrite-callback-[PROJECT_ID]" /> part
