### ISSUE TITLE
🐛 Bug Report: After upgrading to v1.2.1 console UI bugged

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#5132]
### After upgrading to v1.2.1 console UI bugged
I try to clear the cache and check same issue occurs.

Browsers:
- Google Chrome: Version 110.0.5481.100 (Official Build) (64-bit)
- Google Chrome: Version 110.0.5481.100 (Official Build) (arm64) 
- Microsoft Edge: Version 110.0.1587.46 (Official build) (64-bit)

![Screenshot 2023-02-16 222639](https://user-images.githubusercontent.com/18592683/219441769-1f364eca-8635-431a-a415-1839b6f1720e.png)

![Screenshot 2023-02-16 144027](https://user-images.githubusercontent.com/18592683/219328114-a926fb67-2904-477d-8eca-a9564ca39854.png)

### 👍 Expected behavior

It should be working fine after upgrade.

### 👎 Actual Behavior

After upgrading to v1.2.1 console UI bugged.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@usamashafiqs, thanks for creating this issue! 🙏🏼 Would you please try to clear your cache? If the problem persists, please open the browser dev tools and refresh the page so that Console and Network logs are captured and then share those logs.

**Comment by stnguyen90** [comment]
@usamashafiqs did you clear your browser's cache? Please share the logs as I mentioned in my previous message if the problem still persists.
