### ISSUE TITLE
🐛 Bug Report: Create file in bucket: Plural instead of Singular used

### ISSUE THREAD

**Issue by felix-d1strict** [appwrite/appwrite#5139]
### 👟 Reproduction steps

1. Create Project
2. Go to “Storage”
3. Create Bucket
4. Click on “Create file”, in order to upload a file.

### 👍 Expected behavior

Here, the singular of files should be applied as long as only single upload is available.
It should say “Drag and drop a file here to upload”.

### 👎 Actual Behavior

Currently, the plural of file is used. “Drag and drop file**s** here to upload”

![image](https://user-images.githubusercontent.com/68828301/219883626-5dc30473-c478-49d3-9c5a-ccc6471ee80e.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@felix-d1strict, thanks for creating this issue! 🙏🏼 Great catch!

**Comment by Devraj5032** [comment]
I would like to fix this issue can you assign me.

**Comment by Ankur1493** [comment]
can I work on this issue?

**Comment by stnguyen90** [comment]
@Ankur1493 thanks for your interest but it looks like @felix-d1strict has already submitted a PR for this.
