### ISSUE TITLE
[BUG] Creating documents fails for parent documents

### ISSUE THREAD

**Issue by jackstefansky** [appwrite/appwrite#514]
Creating parent documents does not work. In my case, I could not create a document that has a parent that was an array of embedded documents. The return 

Executing POST request in postman with following json body 
`
{
    "parentDocument": "5f466be4c5505",
    "parentProperty": "travels",
    "parentPropertyType": "append",
    "data": {
        "locations": []
    }
}
`

resulted in 

`{
    "message": "Bad structure. Invalid document structure: Unknown property \"locations\" type. Make sure to follow users collection structure",
    "code": 400,
    "version": "0.6.2"
}
`

**Comment by eldadfux** [comment]
After testing on my own local env, I can confirm this is a bug. I'll post a PR with a fix later today.

**Comment by eldadfux** [comment]
Seems like the parent document was validated using the collection rules of the child document. I have added a check to overwrite the rules when a parent document is being used.

**Comment by eldadfux** [comment]
v0.7 is out with the fix available 🥳
