### ISSUE TITLE
Creating auth entry with same number results in "email already exists" error

### ISSUE THREAD

**Issue by davidviziteu** [appwrite/appwrite#5147]
### 👟 Reproduction steps

Call twice the following snippet using the same phone number and different mails: 

```javascript
const sdk = require('node-appwrite');

// Init SDK
const client = new sdk.Client();

const users = new sdk.Users(client);

client
    .setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2') // Your project ID
    .setKey('919c2d18fb5d4...a2ae413da83346ad2') // Your secret API key
;

const promise = users.create('unique()', 'randomemail@gmail.com' , '+440000000000' ,'random passwords', 'Different user names');

promise.then(function (response) {
    console.log(response);
}, function (error) {
    console.log(error);
});
```

### 👍 Expected behavior

It should give me an error that the phone number already exists in auth db

### 👎 Actual Behavior

It tells me that the mail already exists in auth db:

```json
{"code":409,"type":"user_already_exists","response":{"message":"A user with the same email already exists in your project.","code":409,"type":"user_already_exists","version":"1.2.1","file":"/usr/src/code/app/controllers/api/users.php","line":78,"trace":[{"file":"/usr/src/code/app/controllers/api/users.php","line":110,"function":"createUser","args":["plaintext","{}","63f47840b0decd7204f7","a@a.com","Da2XENtLN","+440000000000","david viziteu",{},{}]},{"file":"/usr/src/code/vendor/utopia-php/framework/src/App.php","line":577,"function":"{closure}","args":["unique()","a@a.com","+440000000000","Da2XENtLN","david viziteu",{},{},{}]},{"file":"/usr/src/code/vendor/utopia-php/framework/src/App.php","line":743,"function":"execute","class":"Utopia\\App","type":"->","args":[{},{}]},{"file":"/usr/src/code/app/http.php","line":259,"function":"run","class":"Utopia\\App","type":"->","args":[{},{}]}]}}
```

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@davidviziteu, thanks for creating this issue! 🙏🏼 It looks like we have a misleading error message that indicates the email is a duplicate when the phone number is the duplicate.

**Comment by stnguyen90** [comment]
For reference, this is the error message: 

https://github.com/appwrite/appwrite/blob/5d1ada46523a649f4c057d4c2ec1ad52fae60104/app/config/errors.php#L105

**Comment by yatharth1706** [comment]
I think we should change this error description in such a way that it says: 'A user with the same email / name / phone already exists in your project'. @stnguyen90

**Comment by stnguyen90** [comment]
@yatharth1706 let's.go with:

> A user with the same id, email, or phone already exists in your project.

**Comment by Danish-Belal** [comment]
Hey @stnguyen90  can you assign me this issue ? i want to fix this bug .

**Comment by abhijain2003** [comment]
i think we should make error message dynamic, like for phone numbers it should reflect phone numbers and for email case, it should reflect email

I want to solve this, can I ?

**Comment by joan8ruth** [comment]
Hello @stnguyen90 
I would really like to work on this issue!

Regards,
Joanna
