### ISSUE TITLE
🐛 Bug Report: Some Falsy values show as "n/a" 

### ISSUE THREAD

**Issue by 3IMAD69** [appwrite/appwrite#5150]
### 👟 Reproduction steps

1. create attribute using type boolean (integer or float)
2. add a document set value to false (or 0) and save it 
3. return to document page

### 👍 Expected behavior

it should show false as value 

### 👎 Actual Behavior

it actually shows 'n/a' insteand of false
both vide and adult value here are false
![image](https://user-images.githubusercontent.com/83024321/220438719-d096ce90-0336-473d-be1d-67c8523c8661.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@3IMAD69, thanks for creating this issue! 🙏🏼 

It looks like this is a problem for integers and floats as well.

**Comment by stnguyen90** [comment]
This is probably the problem: https://github.com/appwrite/console/blob/ca08b538c90b088551a7c0a2c3403b6514c1a94a/src/routes/console/project-%5Bproject%5D/databases/database-%5Bdatabase%5D/collection-%5Bcollection%5D/%5B%5Bpage%5D%5D/%2Bpage.svelte#L60
