### ISSUE TITLE
🐛 Bug Report: Duplicate key error in MariaDB

### ISSUE THREAD

**Issue by ftp27** [appwrite/appwrite#5157]
### 👟 Reproduction steps

I store push-tokens in Appwrite database along with other data I need and use a function to add and update push tokens in the database. This configuration worked for a month then Appwrite container start logging an error:
```
[Error] Method: GET
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
[Error] Type: PDOException
[Error] Message: MySQL server has gone away
[Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
[Error] Line: 64
```
At this time MariaDB continually restarted with the error:
```
(Duplicate key) writing word node to FTS auxiliary index table `appwrite._2_database_3_collection_1`
```
I found mention of the same issue in Discord and found the link with a possible solution - [dba.stackexchange.com](https://dba.stackexchange.com/questions/195310/how-to-resolve-innodb-error-duplicate-key-writing-word-node-to-fts-auxiliary). Yes it solved my problem for a while, but in the next day it happened again but with the table which store function executions, I just wiped the whole table. It seems like your logic with unique `_uid` is not as good as supposed to be and It causes collisions. I think in my tokens database I have around 10000-15000 rows and over 20000 executions for the last month. 

### 👍 Expected behavior

Don't duplicate `_uid` at least

### 👎 Actual Behavior

MariaDB container is restarting

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ftp27, thanks for creating this issue! 🙏🏼 Do you have a full text index on this collection?

**Comment by ftp27** [comment]
@stnguyen90 Thank you for the answer! No. I had to fix the issue fast because it's in production. But if it happened again could you give me an SQL request to find the index you're asking for?

**Comment by stnguyen90** [comment]
@ftp27, that sounds kind of odd that you got an error regarding full text indexes, but your collection doesn't have a full text index 🧐 . To show indexes on your collection, you can run the following while in the same folder as your appwrite docker-compose.yml file:

```bash
docker compose exec mariadb sh -c 'mysql -uroot -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE -e "show indexes from _2_database_3_collection_1"'
```

Also, what are the specs on your server and is your database on the same server or hosted externally?

**Comment by ftp27** [comment]
@stnguyen90 I used the default configuration from Digital Ocean to create a droplet. 

Here is the output:
```
+----------------------------+------------+-------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+
| Table                      | Non_unique | Key_name    | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Ignored |
+----------------------------+------------+-------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+
| _2_database_3_collection_1 |          0 | PRIMARY     |            1 | _id         | A         |        9233 |     NULL | NULL   |      | BTREE      |         |               | NO      |
| _2_database_3_collection_1 |          0 | _uid        |            1 | _uid        | A         |        9233 |     NULL | NULL   |      | BTREE      |         |               | NO      |
| _2_database_3_collection_1 |          1 | _created_at |            1 | _createdAt  | A         |        9233 |     NULL | NULL   | YES  | BTREE      |         |               | NO      |
| _2_database_3_collection_1 |          1 | _updated_at |            1 | _updatedAt  | A         |        9233 |     NULL | NULL   | YES  | BTREE      |         |               | NO      |
| _2_database_3_collection_1 |          1 | user_id     |            1 | user_id     | NULL      |        NULL |     NULL | NULL   | YES  | FULLTEXT   |         |               | NO      |
| _2_database_3_collection_1 |          1 | platform    |            1 | platform    | NULL      |        NULL |     NULL | NULL   | YES  | FULLTEXT   |         |               | NO      |
| _2_database_3_collection_1 |          1 | token       |            1 | token       | NULL      |        NULL |     NULL | NULL   | YES  | FULLTEXT   |         |               | NO      |
+----------------------------+------------+-------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+
```

**Comment by stnguyen90** [comment]
@ftp27, it looks like you created 3 full text indexes on `_2_database_3_collection_1`. The `_2_executions` table has the standard `search` full text index.

What are the specs on your server and is your database on the same server or hosted externally?

**Comment by ftp27** [comment]
@stnguyen90 Yep. It's all on the same server. With that fat docker-compose file - https://appwrite.io/install/compose. It may be a little bit different. But basically the same

<details>
  <summary>/proc/cpuinfo</summary>
<pre>
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: DO-Regular
stepping	: 2
microcode	: 0x1
cpu MHz		: 2294.608
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_stale_data
bogomips	: 4589.21
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
</pre>
</details >
<details>
  <summary>/proc/meminfo</summary>
<pre>
MemTotal:        2030916 kB
MemFree:          122936 kB
MemAvailable:     898960 kB
Buffers:           73256 kB
Cached:           795044 kB
SwapCached:         7608 kB
Active:           731116 kB
Inactive:         907944 kB
Active(anon):     347444 kB
Inactive(anon):   432312 kB
Active(file):     383672 kB
Inactive(file):   475632 kB
Unevictable:       18536 kB
Mlocked:           18536 kB
SwapTotal:       2097148 kB
SwapFree:        1709664 kB
Dirty:               616 kB
Writeback:             0 kB
AnonPages:        785988 kB
Mapped:           291036 kB
Shmem:            115532 kB
KReclaimable:      96672 kB
Slab:             186552 kB
SReclaimable:      96672 kB
SUnreclaim:        89880 kB
KernelStack:        9964 kB
PageTables:        13280 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     3112604 kB
Committed_AS:    8379220 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       19480 kB
VmallocChunk:          0 kB
Percpu:              892 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      724832 kB
DirectMap2M:     1372160 kB
</pre>
</details >

**Comment by stnguyen90** [comment]
@ftp27 is that 1CPU and 2GB memory? You might need more resources to handle the load you're processing.

**Comment by ftp27** [comment]
@stnguyen90 Why not. What specs are preferable? Do you think it's connected with the DB error?

**Comment by stnguyen90** [comment]
> Why not

**Comment by stnguyen90** [comment]
@ftp27,

> Why not.

Because you're having problems with the database.

> What specs are preferable?

Ideally, your CPU and memory usage should stay under 70%. How high is your CPU and memory usage when Appwrite processes requests?

> Do you think it's connected with the DB error?

Yes. It takes resources for MariaDB to index data; if there are frequent updates, it could take more resources to update the indexes or indexing can take longer. I can see the indexes getting corrupted if multiple attempts are processed simultaneously.

**Comment by ftp27** [comment]
@stnguyen90 I've taken 2 CPUs and 4GB memory and a control panel started working significantly faster. Hope it'll fix the problem.
