### ISSUE TITLE
🚀 Feature: Improve Error When Creating Custom Domain

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#5159]
### 🔖 Feature description

If you don't have the `_APP_DOMAIN_TARGET` environment variable set correctly when you create a Custom Domain for your project, you'll get an error like:

![image](https://user-images.githubusercontent.com/1477010/221278479-360b78e7-6adf-425a-afda-6b269ea97a09.png)

### 🎤 Pitch

It would be really helpful if there was an error response that could guide the admin on how to fix the problem.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
For now, please refer to https://github.com/appwrite/appwrite/discussions/4997#discussioncomment-4670681 for how to fix the problem.

**Comment by eldadfux** [comment]
The problem is the all 500 errors are hidden from the client and the error you get from the API is useless. A reasonable solution would be to change the status code returned from 500 to [501](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501).

**Comment by singhbhaskar** [comment]
Hey @stnguyen90,
Can I pick this issue and work on it?

**Comment by stnguyen90** [comment]
@singhbhaskar assigned! Thanks for your interest!

**Comment by singhbhaskar** [comment]
Hey @stnguyen90,

I have created a PR for this issue: https://github.com/appwrite/appwrite/pull/5188

Kindly review it. Let me know if we want to change the error message if it's not point the user to update the environment variables or do we require to create a document for troubleshooting this issue.
