### ISSUE TITLE
Docker based hot-reload solution for dev environment 

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#516]
From version 0.7 the Appwrite containers requires a reload  for any changes to get applied. This is due to the fact that most of the codebase is loaded into memory for performance boosting.

We need help setting up a hot reload solution to our code when making changes during development.

From my short research this looks like a nice idea for a Docker based solution:
https://github.com/apogiatzis/docker-compose-livereloader
https://medium.com/better-programming/live-reloading-with-docker-compose-for-efficient-development-356d50e91e39

Any similar Docker based solution that gets the job done and is language agnostic can be considered for this issue.

**Comment by lightlace** [comment]
I'd like to tackle this issue.

**Comment by eldadfux** [comment]
Please do 🙏🏻

**Comment by eldadfux** [comment]
Hey @lightlace are you still working on this issue?

**Comment by Glide7** [comment]
Hey @lightlace , are you still working on this?

**Comment by eldadfux** [comment]
If anyone wants to help with this issue please let us know.

**Comment by KShivendu** [comment]
Hey @eldadfux, I would like to give it a try. Can you assign it to me :)

**Comment by Emiliaaah** [comment]
I'd like to take on this issue. @eldadfux feel free to assign me to this issue.

**Comment by Emiliaaah** [comment]
Kind of messed up the first one since I thought I did something wrong, but this should be good.
