### ISSUE TITLE
Server Error when running search query on DateTime array

### ISSUE THREAD

**Issue by SaurabhJamadagni** [appwrite/appwrite#5168]
- 'dates' attribute in my collection is a `DateTime[]` array. Thus, the values inside it are stored in ISO8601 format.
- I want to run a query to see if there's any date that matches the date on a particular day.
  - I cannot run an `equal` query as the year and time in the values can be different when expressed in ISO8601 format.
- The date attribute has a `fulltext` index to run the search query.
- So I ran a search query where I search for "MM-DD" for a particular day in the database. Here's the swift function:

```swift
func checkForEventToday() async {
        let todayComponents = Calendar.current.dateComponents([.day, .month], from: Date.now)
        
        do {
            let q = "\(todayComponents.month ?? 1)-\(todayComponents.day ?? 1)"
            let documentsList = try await appwrite.databases.listDocuments(
                databaseId: Secrets.dbKey ?? "",
                collectionId: Secrets.contactsCollection ?? "",
                queries: [
                    Query.search("dates", value: q)
                ]
            )
            
            if documentsList.total > 0 {
                DispatchQueue.main.async {
                    self.hasEvent.toggle()
                }
            }
        } catch {
            print("Could not run query to check event")
            print(error)
        }
    }

```

This is printing 'Server Error' in the console. 

<img width="432" alt="image" src="https://user-images.githubusercontent.com/68957712/221573787-10acd527-8f9c-4e92-bc62-6b58ea7fef88.png">

Can anyone please help me with this issue or point me in the direction to solve it?

**Comment by stnguyen90** [comment]
@SaurabhJamadagni, thanks for raising this issue! 🙏🏼 

Unfortunately, searching on dates will not work because searching works on words and MM and DD are too short of words, so they aren't indexed. For more information on how the search works, refer to [this](https://github.com/appwrite/appwrite/discussions/5005#discussioncomment-4681079) discussion.

I recommend using a datetime attribute rather than an array to store your dates. Then, you can use greater than and less than queries to find something for a particular day (assuming you need documents for a certain day and not a date for any year 🧐).

**Comment by SaurabhJamadagni** [comment]
I see @stnguyen90. Thank you for your response. The reason I clubbed the date values in an array is because each user can have multiple contacts and each contact can have multiple dates that they can add. The problem with having individual DateTime attributes is that would require a different collection. This would translate into another async function call. Thus the array to keep it in the same document.


> assuming you need documents for a certain day and not a date for any year 🧐

My use case is that if a contact has their birth date as '01-05-2002', and if the date today is '01-05-2023' it should return this document as they have a matching event irrespective of the year.

Thank you for your clarification. I'll figure out a solution in that case. Maybe a brute force approach of processing the data on device by loading all the documents haha. Please let me know if you have any other suggestions as well 😊

**Comment by stnguyen90** [comment]
@SaurabhJamadagni, for now, it might be necessary to have a separate collection with:

1. User id - the user that has the contacts
2. Contact ID - the user's contact
3. Contact birth month - 1-12
4. Contact birth day - 1-31

**Comment by stnguyen90** [comment]
@SaurabhJamadagni I can close it for you. Thanks, again!
