### ISSUE TITLE
🐛 Bug Report: The Assets on the Appwrite Homepage are Outdated

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#5170]
### 👟 Reproduction steps

1. Browse to https://appwrite.io/assets

### 👍 Expected behavior

The Product Photos are up to date.

### 👎 Actual Behavior

The Product Photos are outdated.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by hindu-muppala** [comment]
I am interested in fixing this issue. I am not unable to find where to start. Can anyone refer some links to solve this issue?

**Comment by stnguyen90** [comment]
@hindu-muppala, thanks, but I don't think you'll be able to help with this as our website source code is closed source.

**Comment by ArmanNik** [comment]
@stnguyen90 can this be closed?
