### ISSUE TITLE
🐛 Bug Report: Wrong message when trying to create an account using phone number

### ISSUE THREAD

**Issue by silvinhofranca** [appwrite/appwrite#5176]
### 👟 Reproduction steps

When creating a user with the same phone number, an error is shown where it says that there is already a user with the registered email.

### 👍 Expected behavior

It was expected that an error message advising that there is already a user with the registered phone number.

### 👎 Actual Behavior

```
{
	"message": "A user with the same email already exists in your project.",
	"code": 409,
	"type": "user_already_exists",
	"version": "1.2.1"
}
```

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

GCP

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by yatharth1706** [comment]
This issue has already been raised here https://github.com/appwrite/appwrite/issues/5147
