### ISSUE TITLE
🐛 Bug Report: impossibe to open document from Appwrite console

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [appwrite/appwrite#5178]
### 👟 Reproduction steps

1. enter Appwrite console
2. select database, collection, document

### 👍 Expected behavior

Open document

### 👎 Actual Behavior

Stay in collection without any interface

<img width="1440" alt="Снимок экрана 2023-03-01 в 10 02 27" src="https://user-images.githubusercontent.com/70258211/222068359-94c7f29c-c5d0-41b0-aeb6-dc5b507ac898.png">

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Selfhosted in Docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ValeryVerkhoturov thanks for opening this issue! 🙏🏼 Would you please look in the network tab (instead of console) of the browser dev tools and look for the network log for the get document API and share the payload?

**Comment by ValeryVerkhoturov** [comment]
I got correct document. This bug happens with every the last document only in this collection

<img width="1440" alt="Снимок экрана 2023-03-07 в 20 54 19" src="https://user-images.githubusercontent.com/70258211/223508156-69ddc325-1d82-4b5d-89c2-f8775611de67.png">

**Comment by stnguyen90** [comment]
@ValeryVerkhoturov, thanks for checking this. I can't quite see the full payload in your screenshot. Would you please try to maybe copy and paste the entire payload on GitHub?

**Comment by ValeryVerkhoturov** [comment]
> @ValeryVerkhoturov, thanks for checking this. I can't quite see the full payload in your screenshot. Would you please try to maybe copy and paste the entire payload on GitHub?

Appwrite was rebuilded and I cannot repeat this bug again
