### ISSUE TITLE
can I change or custom logo on navbar in appwrite?

### ISSUE THREAD

**Issue by Ruttanachote** [appwrite/appwrite#5180]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/43434203/222165155-5361a48f-7e1c-4b0e-b99c-c3bd82ed3cf9.png">

**Comment by akashgreninja** [comment]
change the logo??

**Comment by stnguyen90** [comment]
@Ruttanachote, there is no configuration exposed to change the logo. That said, the [source code](https://github.com/appwrite/console) is open source so you are free to tweak it and rebuild the source.

**Comment by rafagazani** [comment]
does it make sense to leave this issue open?

**Comment by antonrejoe** [comment]
@rafagazani I can see people with op patience

**Comment by rafagazani** [comment]
> @rafagazani I can see people with op patience

is that there are issues that have already been resolved or that there are no more pending questions, I think the best thing would be to close it just to leave everything organized

**Comment by joeyouss** [comment]
Closing this as of now since we are not working on this
