### ISSUE TITLE
📚 Documentation: CRON syntax information is not added in documentation

### ISSUE THREAD

**Issue by yatharth1706** [appwrite/appwrite#5181]
### 💭 Description

In console, when we create functions and add the CRON syntax. It shows one link to know more about cron syntax. Attaching screenshot below

![Screenshot 2023-03-02 224509](https://user-images.githubusercontent.com/32243289/222503160-151931e7-339c-44b5-824f-43f88410086c.png)

And when this link is clicked, it leads to this link:
https://appwrite.io/docs/functions#createFunction

Here no cron syntax related information is present

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by tanmoy27112000** [comment]
++

**Comment by stnguyen90** [comment]
@yatharth1706 thanks for creating this issue! 🙏🏼 Along the same lines, the cron link on the update function page is more about cron in general rather than the cron expression so it could be confusing.

**Comment by tanmoy27112000** [comment]
@stnguyen90 I would like to add the documentation for corn. I think adding few example and link to cron docs would make it much easier for user to understand.

**Comment by stnguyen90** [comment]
@gewenyu99, what are your thoughts on this?

**Comment by gewenyu99** [comment]
> https://appwrite.io/docs/functions#createFunction

🤔 Yeah, we can do this. It wouldn't hurt. Show some common examples, like every minute, every hour, every day.

Would also be nice to consider adding some quick selectable options in this UI, right?

**Comment by Vedsaga** [comment]
> Would also be nice to consider adding some quick selectable options in this UI, right?

Yap agree, such as every timing from 1 to 60 and phase, from second, min and hour something like that

**Comment by stnguyen90** [comment]
@gewenyu99, should we update the Console to link to our docs now?

**Comment by gewenyu99** [comment]
> @gewenyu99, should we update the Console to link to our docs now?

I thought I had a PR, I'll open one if there isn't

**Comment by adityaoberai** [comment]
@stnguyen90 @gewenyu99 it would be really nice to have a little CRON syntax generator within the Console itself :)

**Comment by gewenyu99** [comment]
> @stnguyen90 @gewenyu99 it would be really nice to have a little CRON syntax generator within the Console itself :)

Yeah I raised this with design. Would be a separate issue though

**Comment by gewenyu99** [comment]
This has been resolved by https://github.com/appwrite/console/pull/456
