### ISSUE TITLE
📚 Documentation: https or http

### ISSUE THREAD

**Issue by VenkataBhaskarr** [appwrite/appwrite#5182]
### 💭 Description

in documentation it is mentioned that to use 
<img width="782" alt="Screenshot 2023-03-03 at 8 36 57 AM" src="https://user-images.githubusercontent.com/111889155/222621874-929ddd9e-09b6-421b-9c44-285da97c4774.png">

but when we use  .setEndpoint('https://[HOSTNAME_OR_IP]/v1') we are getting an error as
<img width="606" alt="Screenshot 2023-03-03 at 8 42 16 AM" src="https://user-images.githubusercontent.com/111889155/222622072-a5734acb-d1d6-4d35-a2e7-224ca099908f.png">

where as if we use .setEndpoint('http://[HOSTNAME_OR_IP]/v1') it is perfectly fine with no error.

The main difference in the above two code lines is http / https !

Is it a mistake in the documentation?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by akashgreninja** [comment]
https works perfectly maybe there is some issue with your web browser??
the docs are perfect

**Comment by VenkataBhaskarr** [comment]
I am using chrome version 110.0.5481.77 !

**Comment by VenkataBhaskarr** [comment]
thank you @markusleh and @akashgreninja
