### ISSUE TITLE
🐛 Bug Report: CORS issue when using custom domain

### ISSUE THREAD

**Issue by CaptainDonut** [appwrite/appwrite#5184]
### 👟 Reproduction steps

I try to login or create a user from a React web app (www.donut.zone) with an Appwrite backend. The domain uses Azure DNS.

I get a CORS 403 error when using the Domain, but it works fine when running locally. I can signup and login.

I'm ok with sharing all code and domains/other info/history :) Could you help me out?

### 👍 Expected behavior

When typing in username/password, Appwrite should return that they're incorrect like this:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/14174727/222906370-4a9a5af3-6da0-4a92-8c54-09b50b099c00.png">

### 👎 Actual Behavior

When I type anything in the username/password I get a CORS 403 error and I won't be redirected.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/14174727/222906330-d4ad2e17-aaec-485d-81df-0c29226562dd.png">

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Using Appwrite 1.2.1 running on Ubuntu 20.04 in a docker instance on a VPS.

In the .env file I have changed these parameters:
_APP_ENV=production
_APP_DOMAIN=appwrite.donut.zone
_APP_DOMAIN_TARGET=appwrite.donut.zone

The domain uses Azure DNS and the A record is the IP of the host and "appwrite.donut.zone" as the value

**The source code is here** https://github.com/CaptainDonut/donut-zone

I have googled and found similar issues... The solution in most cases is to add a web platform and add the hostname appwrite.donut.zone which I've already done.

https://github.com/appwrite/appwrite/issues/2687
https://stackoverflow.com/questions/75000025/appwrite-return-500-error-when-trying-to-add-custom-domain
https://dev.to/georgeisiguzo/devspaceforum-x-appwrite-part-3-cors-challenges-with-appwrite-backend-2kii

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by hemangjoshi37a** [comment]
This has nothing to do with appwrite but you website itself. you have to make the appwreite service availabe on subdomain of your website and then use that   subdomain to access the appwrite functionalities.

For example if your website is [hjlabs.in](https://hjlabs.in) then you would have to make a subdomain named [appwrite.hjlabs.in](https://appwrite.hjlabs.in)

**Comment by CaptainDonut** [comment]
> This has nothing to do with appwrite but you website itself. you have to make the appwreite service availabe on subdomain of your website and then use that subdomain to access the appwrite functionalities.
> 
> For example if your website is [hjlabs.in](https://hjlabs.in) then you would have to make a subdomain named [appwrite.hjlabs.in](https://appwrite.hjlabs.in)

Thank you for the reply,
I already created an appwrite A record on my DNS provider pointing to the appwrite host IP address and can access appwrite.donut.zone without issues. Is that all I need to do or are there more to it?

**Comment by hemangjoshi37a** [comment]
yes that's all. 👍

**Comment by CaptainDonut** [comment]
Alright, can I check any logs somewhere to rule out that Appwrite isn't wrongfully configured? Is there anything in the code..? Kinda stumped atm :/

**Comment by stnguyen90** [comment]
@CaptainDonut, would you please run `docker compose exec appwrite vars` and verify the domain environment variables are set correctly?

**Comment by stnguyen90** [comment]
@CaptainDonut, also, did you create a web platform for your project as described [here](https://appwrite.io/docs/getting-started-for-web#addPlatform)?

**Comment by CaptainDonut** [comment]
Yo, sorry been a little busy getting this to work..

I have been working on getting Nginx reverse proxy in place so I can use other ports than the default ones right now. I'll get back once I get that running, maybe it'll solve the issue.

I have created a web platform for appwrite.donut.zone. It was the solution for many who had this problem.

**Comment by stnguyen90** [comment]
> I have been working on getting Nginx reverse proxy in place

If you have a reverse proxy, make sure the `Host` header is propagated to Appwrite. See [this](https://github.com/appwrite/appwrite/discussions/4329#discussioncomment-3831341) discussion.

**Comment by stnguyen90** [comment]
@CaptainDonut, are you still facing this problem or can this be closed?

**Comment by stnguyen90** [comment]
@CaptainDonut, any updates? Just so you know, I'll have to close this due to inactivity soon.

**Comment by CaptainDonut** [comment]
Yo,

I got the reverse proxy to work for appwrite.donut.zone but the CORS issue remain... I have to try something else.

I am going to double check everything is correct with nginx in this guide [](https://medium.com/@stnguyen90/how-to-run-appwrite-behind-nginx-19348ed34243)

**Comment by stnguyen90** [comment]
@CaptainDonut, please share the latest error message from the browser console logs. Also, please ensure you're sending the right project ID in the request.

**Comment by hemangjoshi37a** [comment]
@stnguyen90 bro you close the issues so fast even it is not resolved. If the issue is not resolved you should not close it. Otherwise people will not see in the issue section. Keep it open until it solved even for longer period of time.

**Comment by CaptainDonut** [comment]
Yeah sorry I'm a little slow on the progress of this. Here's the output of "docker compose exec appwrite vars"

- _APP_ENV=production
- _APP_LOCALE=en
- _APP_OPTIONS_ABUSE=enabled
- _APP_OPTIONS_FORCE_HTTPS=disabled
- _APP_OPENSSL_KEY_V1=your-secret-key
- _APP_DOMAIN=appwrite.donut.zone
- _APP_DOMAIN_TARGET=appwrite.donut.zone
- _APP_CONSOLE_WHITELIST_ROOT=enabled
- _APP_CONSOLE_WHITELIST_EMAILS=
- _APP_CONSOLE_WHITELIST_IPS=
- _APP_SYSTEM_EMAIL_NAME=Appwrite
- _APP_SYSTEM_EMAIL_ADDRESS=team@appwrite.io
- _APP_SYSTEM_RESPONSE_FORMAT=
- _APP_SYSTEM_SECURITY_EMAIL_ADDRESS=donut@donut.zone
- _APP_USAGE_STATS=enabled
- _APP_LOGGING_PROVIDER=
- _APP_LOGGING_CONFIG=
- _APP_USAGE_AGGREGATION_INTERVAL=30
- _APP_USAGE_TIMESERIES_INTERVAL=
- _APP_USAGE_DATABASE_INTERVAL=
- _APP_WORKER_PER_CORE=6
- _APP_REDIS_HOST=redis
- _APP_REDIS_PORT=6379
- _APP_REDIS_USER=
- _APP_REDIS_PASS=
- _APP_DB_HOST=mariadb
- _APP_DB_PORT=3306
- _APP_DB_SCHEMA=appwrite
- _APP_DB_USER=user
- _APP_DB_PASS=password
- _APP_DB_ROOT_PASS=
- _APP_INFLUXDB_HOST=influxdb
- _APP_INFLUXDB_PORT=8086
- _APP_STATSD_HOST=telegraf
- _APP_STATSD_PORT=8125
- _APP_SMTP_HOST=
- _APP_SMTP_PORT=
- _APP_SMTP_SECURE=
- _APP_SMTP_USERNAME=
- _APP_SMTP_PASSWORD=
- _APP_SMS_PROVIDER=
- _APP_SMS_FROM=
- _APP_STORAGE_LIMIT=30000000
- _APP_STORAGE_PREVIEW_LIMIT=20000000
- _APP_STORAGE_ANTIVIRUS=disabled
- _APP_STORAGE_ANTIVIRUS_HOST=clamav
- _APP_STORAGE_ANTIVIRUS_PORT=3310
- _APP_STORAGE_DEVICE=local
- _APP_STORAGE_S3_ACCESS_KEY=
- _APP_STORAGE_S3_SECRET=
- _APP_STORAGE_S3_REGION=us-east-1
- _APP_STORAGE_S3_BUCKET=
- _APP_STORAGE_DO_SPACES_ACCESS_KEY=
- _APP_STORAGE_DO_SPACES_SECRET=
- _APP_STORAGE_DO_SPACES_REGION=us-east-1
- _APP_STORAGE_DO_SPACES_BUCKET=
- _APP_STORAGE_BACKBLAZE_ACCESS_KEY=
- _APP_STORAGE_BACKBLAZE_SECRET=
- _APP_STORAGE_BACKBLAZE_REGION=us-west-004
- _APP_STORAGE_BACKBLAZE_BUCKET=
- _APP_STORAGE_LINODE_ACCESS_KEY=
- _APP_STORAGE_LINODE_SECRET=
- _APP_STORAGE_LINODE_REGION=eu-central-1
- _APP_STORAGE_LINODE_BUCKET=
- _APP_STORAGE_WASABI_ACCESS_KEY=
- _APP_STORAGE_WASABI_SECRET=
- _APP_STORAGE_WASABI_REGION=eu-central-1
- _APP_STORAGE_WASABI_BUCKET=
- _APP_FUNCTIONS_SIZE_LIMIT=30000000
- _APP_FUNCTIONS_TIMEOUT=900
- _APP_FUNCTIONS_BUILD_TIMEOUT=900
- _APP_FUNCTIONS_CONTAINERS=10
- _APP_FUNCTIONS_CPUS=0
- _APP_FUNCTIONS_MEMORY=0
- _APP_FUNCTIONS_MEMORY_SWAP=0
- _APP_FUNCTIONS_RUNTIMES=node-16.0,php-8.0,python-3.9,ruby-3.0
- _APP_EXECUTOR_SECRET=your-secret-key
- _APP_EXECUTOR_HOST=http://appwrite-executor/v1
- _APP_EXECUTOR_RUNTIME_NETWORK=appwrite_runtimes
- _APP_FUNCTIONS_ENVS=
- _APP_FUNCTIONS_INACTIVE_THRESHOLD=
- DOCKERHUB_PULL_USERNAME=
- DOCKERHUB_PULL_PASSWORD=
- DOCKERHUB_PULL_EMAIL=
- OPEN_RUNTIMES_NETWORK=
- _APP_MAINTENANCE_INTERVAL=86400
- _APP_MAINTENANCE_RETENTION_CACHE=2592000
- _APP_MAINTENANCE_RETENTION_EXECUTION=1209600
- _APP_MAINTENANCE_RETENTION_AUDIT=1209600
- _APP_MAINTENANCE_RETENTION_ABUSE=86400
- _APP_MAINTENANCE_RETENTION_USAGE_HOURLY=8640000
- _APP_GRAPHQL_MAX_BATCH_SIZE=10
- _APP_GRAPHQL_MAX_COMPLEXITY=250
- _APP_GRAPHQL_MAX_DEPTH=3

**Comment by stnguyen90** [comment]
@CaptainDonut the variables look fine. 

Did you add a web platform (`www.donut.zone`) to your project in the Appwrite Console?

Also, are you using Nginx Proxy Manager or just Nginx?

**Comment by CaptainDonut** [comment]
Yo, that's good to hear. I am using Nginx Proxy manager and follwing the guide. I'm unsure if the changes in the override file is taking effect. Is it enough to run "docker compose up -d" or do I need to specify the override file?

**Comment by stnguyen90** [comment]
@CaptainDonut,

> Is it enough to run "docker compose up -d"

It's enough as long as you're in the folder with `docker-compose.yml` and `docker-compose.override.yml`.

> The web platform is added as appwrite.donut.zone. Does it need to be [www.donut.zone](http://www.donut.zone/)?

The web platform should be your client app so it should be `www.donut.zone`.

**Comment by CaptainDonut** [comment]
yep I can close it and open a new one if I need more help, thank you :)
