### ISSUE TITLE
🐛 Bug Report: `Documentation` link on Auth > Sessions is broken

### ISSUE THREAD

**Issue by Pranav2612000** [appwrite/appwrite#5189]
### 👟 Reproduction steps

- Create a new account
- Navigate to the auth section
- Navigate to Sessions
- Click on Documentation

You will be redirected to a 404 page 

### 👍 Expected behavior

It should redirect to the correct documentation page

### 👎 Actual Behavior

It redirects to an invalid page

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Development environment using docker compose

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
To clarify, this is shown if you open a user, switch to the sessions tab, and they don't have any sessions yet.

**Comment by Pranav2612000** [comment]
What page should this redirect to? Seems like a simple issue. I'll fix this and have a PR ready

**Comment by stnguyen90** [comment]
@gewenyu99, what do you think the "Documentation" button should link to?

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/1477010/223823925-870c8f2f-f994-43e5-86a6-c2341c2d2a81.png">

Right now, it goes to https://appwrite.io/docs/server/auth?sdk=nodejs-default#usersGetSessions

**Comment by gewenyu99** [comment]
@stnguyen90 Should probably go somewhere to create sessions rather than get sessions, which is pretty useless :P

**Comment by stnguyen90** [comment]
> Should probably go somewhere to create sessions rather than get sessions, which is pretty useless :P

Good point!

@Pranav2612000 I think this might be good: https://appwrite.io/docs/client/account#accountCreateEmailSession. I'll assign this issue to you. Thank you! 🙏🏼

**Comment by Pranav2612000** [comment]
Thank you. I'll have a PR ready in the next couple of days

**Comment by Pranav2612000** [comment]
Have a PR ready here - https://github.com/appwrite/console/pull/337

Also observed the same hyperlink on the `/console/accounts/page` Have updated that as well.
