### ISSUE TITLE
🐛 Bug Report: Domain verification for the requested domain has failed in AWS

### ISSUE THREAD

**Issue by markusleh** [appwrite/appwrite#5190]
### 👟 Reproduction steps

Trying to use set up Appwrite with my own domain and the domain verification fails.

I've replaced my actual domain name with `my-domain.com`. This is my configuration:
```
_APP_ENV=production
_APP_OPTIONS_FORCE_HTTPS=disabled
_APP_DOMAIN=api-dev.my-domain.com
_APP_DOMAIN_TARGET=api-dev.my-domain.com
_APP_SYSTEM_SECURITY_EMAIL_ADDRESS=contact@my-domain.com
```

Possibly related to #1259.

https://letsdebug.net/ says all is ok with the domain itself.

### 👍 Expected behavior

Verify domain and create working certificate

### 👎 Actual Behavior

An error message "Domain verification for the requested domain has failed" pops up in the Web UI. In docker (`appwrite`) logs the following message shows up:
```
appwrite                        | [Error] Timestamp: 2023-03-05T11:52:17+00:00
appwrite                        | [Error] Method: PATCH
appwrite                        | [Error] URL: /v1/projects/:projectId/domains/:domainId/verification
appwrite                        | [Error] Type: Appwrite\Extend\Exception
appwrite                        | [Error] Message: Domain verification for the requested domain has failed.
appwrite                        | [Error] File: /usr/src/code/app/controllers/api/projects.php
appwrite                        | [Error] Line: 1485
```

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite/appwrite:1.2 -docker images
EC2 (Amazon Linux 2)
Route 53 DNS
Subdomain (api-dev) has CAA record `0 issue "letsencrypt.org"`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
> Should the certificate be autogenerated on start using the _APP_DOMAIN configuration variable? 

@markusleh, the certificate generation is kicked off by browsing to Appwrite using a particular domain (usually self signed to begin with). The env variable is way for Appwrite to restrict what it will generate a certificate for.
