### ISSUE TITLE
🐛 Bug Report: Trigger a function `users.*.create` when an Anonymous user is created

### ISSUE THREAD

**Issue by chuiizeet** [appwrite/appwrite#5198]
### 👟 Reproduction steps

Try to use `users.*.create` when an anonymous user is created but does not works.

### 👍 Expected behavior

The function must be triggered

### 👎 Actual Behavior

The function does not triggered

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@chuiizeet, thanks for opening this issue! 🙏🏼 It looks like the [Create Anonymous Session](https://appwrite.io/docs/client/account?sdk=web-default#accountCreateAnonymousSession) endpoint only triggers a `users.[userId].sessions.[sessionId].create` event:

https://github.com/appwrite/appwrite/blob/e8c74d7204258133a61db09ed518211170e751d9/app/controllers/api/account.php#L1134

We definitely need to also trigger the `users.[userId].create` event. The big challenge right now is our event mechanism only supports 1 event per endpoint, so we've been discussing rewriting the system to support multiple events.

Related issue: https://github.com/appwrite/appwrite/issues/2406
