### ISSUE TITLE
Cannot login into the panel

### ISSUE THREAD

**Issue by dawidpx** [appwrite/appwrite#5200]
### 👟 Reproduction steps

I have a separate computer in local network where I run docker.
I followed "Get started" short instruction.
The containers are running but I cannot log in into the panel - I got "404 page not found".

### 👍 Expected behavior

Login panel screen.

### 👎 Actual Behavior

404 page not found

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Doctor says:

Checking for production best practices...
🔴 Hostname has no public suffix (localhost)
🔴 CNAME target has no public suffix (appwrite)
🟢 Using a unique secret key for encryption
🟢 App environment is set for production
🟢 Abuse protection is enabled
🟢 Console access limits are enabled
🔴 HTTPS force option is disabled
🔴 Logging adapter is disabled

Checking connectivity...
Database............connected 👍
Queue...............connected 👍
Cache...............connected 👍
SMTP.............disconnected 👎
StatsD..............connected 👍
InfluxDB............connected 👍

Checking volumes...
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

Checking disk space usage...
🟢 Uploads Volume has 59.83GB free space (42.78% used)
🟢 Cache Volume has 59.83GB free space (42.78% used)
🟢 Config Volume has 59.83GB free space (42.78% used)
🟢 Certs Volume has 59.83GB free space (42.78% used)

You are running the latest version of Appwrite! 🥳

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@dawidpx, thanks for creating this issue! 🙏🏼 Are you browsing to your server's IP using the port specified during installation? Maybe you can also share the screenshot of the error page you're seeing?

**Comment by dawidpx** [comment]
Hi, thank you for response.
OK, I already found human error in my doing - I am using ports 84 (http) and 7443 (https). On port 84 I was getting TLS error and on 7443 I was getting "404" (enclosed screenshot). 
But fortunately the panel started working on 84 port so I can start to learn Appwrite!

<img width="450" alt="Zrzut ekranu 2023-03-9 o 17 48 05" src="https://user-images.githubusercontent.com/63444844/224095137-e0c8552b-b920-474c-88bd-661ac2fef62d.png">
