### ISSUE TITLE
🐛 Bug Report: Web code sample uses self-closing syntax for script tag

### ISSUE THREAD

**Issue by spontaneouscombustion** [appwrite/appwrite#5204]
### 👟 Reproduction steps

create a new web project and choose the cdn for installation

### 👍 Expected behavior

the sample web code should use the standard syntax  when loading the script
```javascript
<script src="https://cdn.jsdelivr.net/npm/appwrite@${$versions['client-web']}"></script>
```

### 👎 Actual Behavior

the script tag uses self-closing syntax which some browser may not recognize and fails to load the script. 
```javascript
<script src="https://cdn.jsdelivr.net/npm/appwrite@${$versions['client-web']}"/>
```

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@spontaneouscombustion, thanks for raising this issue! 🙏🏼 Would you be interested in submitting a PR for this?

**Comment by spontaneouscombustion** [comment]
hello @stnguyen90 .
sorry, my english is broken.
I hope the PR is descriptive enough.

**Comment by Snach13** [comment]
this issue still open ?

**Comment by stnguyen90** [comment]
@Snach13, are you still interested in working on this?

**Comment by Snach13** [comment]
@stnguyen90 But you close this issue, right what happened?

**Comment by Snach13** [comment]
@stnguyen90 Can you provide some description to me ?

**Comment by stnguyen90** [comment]
@Snach13, 

> But you close this issue, right what happened?

I closed the previous PR because it was stale, and there were changes requested that needed to be addressed.

> Can you provide some description to me ?

What description? The required change is in the description of the issue. 

Would you like to work on this?

**Comment by Snach13** [comment]
@stnguyen90 yeah sure assign it to me I'll take look into it

**Comment by Snach13** [comment]
@stnguyen90  sure assigned this issue to me I'll give a look

**Comment by Snach13** [comment]
@stnguyen90 I'm getting some build errors can you help me with it 
![appwrite](https://github.com/appwrite/appwrite/assets/97365258/e6e9246b-d0d0-4656-aa04-60a47daa70ac)

**Comment by stnguyen90** [comment]
> @stnguyen90 I'm getting some build errors can you help me with it ![appwrite](https://user-images.githubusercontent.com/97365258/253555076-e6e9246b-d0d0-4656-aa04-60a47daa70ac.png)

@Snach13, it seems you are running out of memory:

> JavaScript heap out of memory

**Comment by KaranJagtiani** [comment]
@stnguyen90 is this issue still open?

**Comment by stnguyen90** [comment]
@KaranJagtiani, yes it is. Would you like to work on this?
