### ISSUE TITLE
🚀 Feature: Migration Between Appwrite Instances

### ISSUE THREAD

**Issue by iamdineshkumar** [appwrite/appwrite#5208]
### 🔖 Feature description

Right now migrating project between appwrite instance not have straight forward methods.
Based on discussion with @Meldiron This can be achieved by his [tool](https://github.com/meldiron/appwrite-tools) to download as json using API and then should sync back to new instance while strucure and cloud codes should be handled using appwrite cli. Still handling files is Hard.
If there is a solution for migration between appwrite instance atlease will helpful. Even for users to migrate from self hosted version to cloud as well as cloud to self hosted version even between self hosted version servers.

### 🎤 Pitch

We have a procedure in appwrite console itself for this. For explaination I consider two appwrite servers as source and destination.

1. User can login into destination server and create new project
2. In new project go to settings and there we can implement new migration in option where user need to input source server domain to generate a transfer key
3. Then user need to navigate to respective project in source server
4. In source server project settings, there we can implement option to migrate out where user need to enter destination api end point as well as project id and transfer key to initiate migration

Then appwrite can use existing API to transfer its collection schema, documents, teams, storage, files etc. Transfer key can be act as master key to generate all details in destination server.

Transfer Key & Source Server Configuration:
This configuration will help destination server to decide authenticity as well as given key can act similar to server side key

Since this mode of migration uses appwrite existing API which is easy to implement and there is no need of any physical download and upload process. Apart from that its server to server communication so we can transfer request faster. To implement that we need should not consider rate limit in API in case request is transfer key based. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This is a great suggestion, and we've already made some internal progress on a new RFC for a `Transfer API`. We'd love to share more soon and get more feedback on the suggested process, but its very close to what mentioned here.

**Comment by iamdineshkumar** [comment]
@eldadfux Is there any feature planned for backup and restore? If auto backup option is there and it will be helpful.

**Comment by stnguyen90** [comment]
Closing as we have [added this as part of 1.4](https://appwrite.io/docs/migrations). If you're running into any problems, please create new issues for those specific problems
