### ISSUE TITLE
🐛 Bug Report: Uploading an XML file to an S3 provider Returns 500 Error

### ISSUE THREAD

**Issue by troykelly** [appwrite/appwrite#5213]
### 👟 Reproduction steps

1. Configure Appwrite to use an S3 storage provider
1. Upload an XML file 

### 👍 Expected behavior

Store the file and return the file object

### 👎 Actual Behavior

Generates a 500 Error.

Server logs:

```
appwrite                      | [Error] Timestamp: 2023-03-10T10:29:12+00:00
appwrite                      | [Error] Method: POST
appwrite                      | [Error] URL: /v1/storage/buckets/:bucketId/files
appwrite                      | [Error] Type: TypeError
appwrite                      | [Error] Message: Utopia\Storage\Device\S3::read(): Return value must be of type string, array returned
appwrite                      | [Error] File: /usr/src/code/vendor/utopia-php/storage/src/Storage/Device/S3.php
appwrite                      | [Error] Line: 328
```

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Reference Code: [Github Gist](https://gist.github.com/troykelly/b5075d650112f900b33f6ae27813aea8)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@troykelly, thanks for raising this! I was able to reproduce this by uploading a simple XML file like:

```xml
<?xml version="1.0"?>
<customers>
   <customer id="55000">
      <name>Charter Group</name>
      <address>
         <street>100 Main</street>
         <city>Framingham</city>
         <state>MA</state>
         <zip>01701</zip>
      </address>
      <address>
         <street>720 Prospect</street>
         <city>Framingham</city>
         <state>MA</state>
         <zip>01701</zip>
      </address>
      <address>
         <street>120 Ridge</street>
         <state>MA</state>
         <zip>01760</zip>
      </address>
   </customer>
</customers>
```

via the Console.

It seems like the problem is caused by [this](https://github.com/utopia-php/storage/blob/0b3d0e635edc560744216b3dee40de779e5b04b9/src/Storage/Device/S3.php#L813-L816) section of `S3->call()` in utopia-php/storage:

```php
        // Parse body into XML
        if ((isset($response->headers['content-type']) && $response->headers['content-type'] == 'application/xml') || (str_starts_with($response->body, '<?xml') && ($response->headers['content-type'] ?? '') !== 'image/svg+xml')) {
            $response->body = \simplexml_load_string($response->body);
            $response->body = json_decode(json_encode($response->body), true);
        }
```

This converts the response body to an Array and causes `S3->read()` to throw an error [here](https://github.com/utopia-php/storage/blob/0b3d0e635edc560744216b3dee40de779e5b04b9/src/Storage/Device/S3.php#L369):

```php
    public function read(string $path, int $offset = 0, int $length = null): string
    {
        unset($this->amzHeaders['x-amz-acl']);
        unset($this->amzHeaders['x-amz-content-sha256']);
        unset($this->headers['content-type']);
        $this->headers['content-md5'] = \base64_encode(md5('', true));
        $uri = ($path !== '') ? '/'.\str_replace('%2F', '/', \rawurlencode($path)) : '/';
        if ($length !== null) {
            $end = $offset + $length - 1;
            $this->headers['range'] = "bytes=$offset-$end";
        }
        $response = $this->call(self::METHOD_GET, $uri);

        return $response->body;
    }
```

**Comment by troykelly** [comment]
@stnguyen90 This may be an edge case.

It seems that the distributor we are trying to download this from _might_ have a misconfiguration in their IIS server.

The file is being downloaded as base64 encapsulated data in an XML file.

I've not seen this before - maybe it's common? I don't know.

```xml
<?xml version="1.0" encoding="utf-8"?>
<string xmlns="http://tempuri.org/">BASE64_ENCODED_XLS_FILE</string>
```

It seems browsers detect this, and convert the file automagically.

If I try and send that content to appwrite, the error is generated.

If I retrieve the string, base64 decode it, and send the bytes - appwrite works perfectly.

**Comment by lohanidamodar** [comment]
@troykelly Thanks for the information. @stnguyen90 Thanks for the diagnosis. I'll work on the solution.
