### ISSUE TITLE
Populate data from multiple databases

### ISSUE THREAD

**Issue by Sayantan102002** [appwrite/appwrite#5214]
I have used databases and have loved them a lot since. But I think populating data using ObjectId is similar to the mongoose library function used to populate data in MongoDB I guess it would be the best update😊🙂. Looking forward to using app write extensively in my all upcoming projects.

**Comment by stnguyen90** [comment]
@Sayantan102002, sorry I don't quite follow what you're requesting. Could you provide some more details?

**Comment by Sayantan102002** [comment]
![image](https://user-images.githubusercontent.com/62782051/224523939-f1d668fb-9f84-456e-af93-7cda6cdc9244.png)
https://www.geeksforgeeks.org/mongoose-populate-method/

The above link and photo might give more clarity to what I am requesting.

**Comment by gepd** [comment]
Pupulate doesn't work across multiples databases, but across multiples collections. Appwrite is working in a relationships feature, you can see the RFC [here](https://github.com/appwrite/rfc/blob/0ab31760035f5c312a89aafd281a7e97370ffd72/021-%20database-relationships.md) and to let them your opinion or request go to [this discussion](https://github.com/appwrite/appwrite/discussions/5179) there is a PR too https://github.com/appwrite/appwrite/pull/5216

**Comment by stnguyen90** [comment]
As @gepd said, it looks like you're looking for relationships which is covered by https://github.com/appwrite/appwrite/issues/2735. As such, I'm going to close this issue.
