### ISSUE TITLE
🐛 Bug Report: Error 500 when invoking account.createVerification on previously anonymous users

### ISSUE THREAD

**Issue by hosnipogi** [appwrite/appwrite#5220]
### 👟 Reproduction steps

1. Create an anonymous session
```js
await appwrite.account.createAnonymousSession();
```
2. Anonymous user decides to sign up/create an account
```js
const user = await appwrite.account.updateEmail(email, password); 
```
3. Login the previously anonymous user
```js
await appwrite.account.createEmailSession(user.email, val.password);
```
4. Send a verification email to the newly signed up user
```js
await appwrite.account.createVerification(
  `${window.location.origin}/account-verify`
); 
```
5. Response from server is an Error 500

### 👍 Expected behavior

Show a much more meaningful error message or make user `name` field optional or default to an empty string instead of `null`

### 👎 Actual Behavior

500 error response, upon inspecting appwrite docker logs, the error is due to assigning `null` to the user's `name` field:

```sh
[Error] Message: Appwrite\Event\Mail::setName(): Argument #1 ($name) must be of type string, null given, called in /usr/src/code/app/controllers/api/account.php on line 2159
```

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

NodeJS Server: `node-appwrite ^8.2.0`
Browser Client: `appwrite ^10.1.0`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue
- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@hosnipogi, thanks for creating this issue! 🙏🏼 I think we should have a default for the name, but let me check what that should be.

**Comment by divinenaman** [comment]
@stnguyen90  can I take this up ?

**Comment by pechtelt1** [comment]
https://github.com/appwrite/appwrite/pull/5495

**Comment by stnguyen90** [comment]
@divinenaman, are you still interested in working on this?

**Comment by vaibhavagarwal220** [comment]
Can I be assigned to this, @stnguyen90
