### ISSUE TITLE
🚀 Feature: Button in Project setting to download & upload `appwrite.json`

### ISSUE THREAD

**Issue by Vedsaga** [appwrite/appwrite#5221]
### 🔖 Feature description

To access `appwrite.json`  we need to use cli it would nice and easy to let user download `.json` file in just one click.

And then let user upload that `.json` file and Yuuu-Hooo deployment is done, new collections, attributes & indexes is created... instead of doing it manually via Console.

### 🎤 Pitch

As, I have 40+ collections,  300+ atrributes in total  & 50+ indexes and I don't want to manually create these collections, attributes & index. 

And again if in-future some more collection or attributes to be added or deleted then again have to do. 
So, it right now we do have access to `appwrite.json` however we need to use CLI which is kinda not that efficent because right now when I try to fetch latest changes in collection it doesn't do it for some reason but in the console it's clearly visible. So, having a button to download and upload `appwrite.json` in few click would help alot. Because if someone what to add collection or attribute they have to simply download the `.json` file modify it and upload it and it's automatically get's deployed. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Vedsaga, thanks for creating this issue! 🙏🏼 You should be able to fetch your collections by running:

```
appwrite init collection
```

Also, I don't think it's a good idea to couple the Console with the `appwrite.json` specs, but I'll leave this open in case there's any other interest.

**Comment by eldadfux** [comment]
Closing this issue do to lack of activity, we can reopen if this becomes more relevant in the future.
