### ISSUE TITLE
🐛 Bug Report: Sign-up button redirects to "Thanks for submission" page without checking if email input field is empty.

### ISSUE THREAD

**Issue by nitin-787** [appwrite/appwrite#5222]
### 👟 Reproduction steps

Currently, when a user clicks on the sign-up button without entering their email address, they are redirected to a "Thanks for submission" page. This behavior is not ideal since the user may not have intended to submit their information yet or may have accidentally clicked the button.

### 👍 Expected behavior

When a user clicks on the sign-up button without entering their email address, the system should display an error message that prompts the user to enter their email address before submitting the form. This would prevent unintentional submissions and ensure that the user's information is captured accurately.

### 👎 Actual Behavior

https://user-images.githubusercontent.com/76255199/224892469-e835f978-72f5-44da-a099-a035a4123995.mp4

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ShatilKhan** [comment]
Hi, can I work on this?
@nitin-787?

**Comment by nitin-787** [comment]
@ShatilKhan this in not my repo, you can ask the maintainers, I just found the bug and reported it here

**Comment by joan8ruth** [comment]
Hello,
I would really like to work on this issue!

Regards,
Joanna

**Comment by stnguyen90** [comment]
This should be resolved now.
