### ISSUE TITLE
🚀 Feature: Design an error 404

### ISSUE THREAD

**Issue by khareyash05** [appwrite/appwrite#5229]
### 🔖 Feature description

An error 404 page can be added to the appwrite's page

### 🎤 Pitch

![image](https://user-images.githubusercontent.com/60147732/225202315-356efd69-fe25-474b-bab7-dd3739558839.png)
The current error 404 is not looking good. I would like to design the same.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by shaikahmadnawaz** [comment]
I started working on this, please assign me for this issue

**Comment by khareyash05** [comment]
@shaikahmadnawaz I have self made this issue . Thank you

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz I have self made this issue . Thank you

Are you working on this?

**Comment by shaikahmadnawaz** [comment]
> > > @shaikahmadnawaz I have self made this issue . Thank you
> > 
> > Are you working on this?
> 
> Yes

Great 👍🏻

**Comment by joeyouss** [comment]
Hi @khareyash05 , are you working on this? Wanted to check in to know the status since it has been few months.
