### ISSUE TITLE
🐛 Bug Report: Function stop working after first excution

### ISSUE THREAD

**Issue by felipeavilis** [appwrite/appwrite#5234]
### 👟 Reproduction steps

I created a function called sms-function in NodeJS that uses Twilio to send a SMS. After execute it for the first time, the SMS is sent, but Appwrite logs this error:

    TypeError: userFunction is not a function
        at /usr/local/src/server.js:68:19
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

Then i cannot execute the function anymore. I have to re-deploy it to execute.

Here is the code:

    // Twilio vars
    const accountSid = process.env.TWILIO_ACCOUNT_SID;
    const authToken = process.env.TWILIO_AUTH_TOKEN;
    const senderPhone = process.env.TWILIO_NUMBER;

    // Import Twilio
    const client = require('twilio') (accountSid, authToken);

    // Fech input data
    const payload = JSON.parse(process.env.APPWRITE_FUNCTION_DATA);
    const receiver = payload["receiver"];
    const message = payload["message"];

    if (!receiver) console.error("Receiver number is required!");
    if (!message) console.error("Message is required!");

    // Send message to the receiver
    client.messages.create({
        body: message,
        from: senderPhone,
        to: receiver
    })
    .then(res => {
        console.log(res);
    })
    .catch(err => {
        console.log(err);
    });

And here is package.json:

    {
      "name": "sms-twilio",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "keywords": [],
      "author": "",
      "license": "ISC",
      "dependencies": {
        "twilio": "^4.8.0"
      }
    }

Build is OK, Status **green**. Build logs:

    added 31 packages, and audited 32 packages in 3s

    8 packages are looking for funding
      run `npm fund` for details

    found 0 vulnerabilities

Error logs: 

    npm notice 
    npm notice New major version of npm available! 7.10.0 -> 9.6.2
    npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.2>
    npm notice Run `npm install -g npm@9.6.2` to update!
    npm notice

Execute Access Role is set to **Any**.
Variables are set: 
![image](https://user-images.githubusercontent.com/97637336/225446293-ab13f528-6e09-48ea-81b9-f437a68df795.png)

But look at Executions:
![image](https://user-images.githubusercontent.com/97637336/225447496-88f5dc58-f585-4e54-a4e5-6519e7c372ce.png)

This is a test that i run on my computer, it works fine! No errors....
![image](https://user-images.githubusercontent.com/97637336/225447387-9e36d825-c767-4e75-9310-bb04b829c8c2.png)

### 👍 Expected behavior

Run the function, SMS sent and Status **OK**.

### 👎 Actual Behavior

Run the function, SMS sent and Status **Failed**.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Cloud Provider: Azure
Appwrite Version: {"version":"1.2.1"}
Im using NodeJS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@felipeavilis, thanks for creating this issue! 🙏🏼 It doesn't look like your function is structured properly. Please either:

1. follow our [docs](https://appwrite.io/docs/functions#writingYourOwnFunction) for how to manually write a function
2. use the [Appwrite CLI](https://appwrite.io/docs/command-line-deployment#deployFunctions) to create a starter template and then deploy

I highly recommend using the Appwrite CLI to manage your functions.

**Comment by felipeavilis** [comment]
GREEN, COMPLETED!
![image](https://user-images.githubusercontent.com/97637336/225469102-2601ca6c-e576-4e1a-94d1-9328d9d1a0a0.png)

@stnguyen90 Thank you for the attention. I followed a [this youtube video](https://youtu.be/D-D6j7X9KRc) and forgot to check the documentation. I changed my code and now it woks fine!

    module.exports = async (req, res) => {
        // Twilio vars
        const accountSid = process.env.TWILIO_ACCOUNT_SID;
        const authToken = process.env.TWILIO_AUTH_TOKEN;
        const senderPhone = process.env.TWILIO_NUMBER;

        console.log("Import Twilio")
        // Import Twilio
        const client = require('twilio')(accountSid, authToken);

        console.log("Fech Data")
        // Fech input data
        const payload = JSON.parse(process.env.APPWRITE_FUNCTION_DATA);
        const receiver = payload["receiver"];
        const message = payload["message"];

        if (!receiver) console.error("Receiver number is required!");
        if (!message) console.error("Message is required!");

        // Send message to the receiver
        client.messages.create({
            body: message,
            from: senderPhone,
            to: receiver
        })
            .then(msg => {
                res.json(msg);
            })
            .catch(err => {
                res.json(msg);
            });
    };
