### ISSUE TITLE
🐛 Bug Report: Error Invalid endpoint or your Appwrite server is not running as expected

### ISSUE THREAD

**Issue by felipeavilis** [appwrite/appwrite#5237]
### 👟 Reproduction steps

When i try to login using Appwrite CLI and Server Name (FQDN), i get this error message:

    ✗ Error Invalid endpoint or your Appwrite server is not running as expected.

I have a Nginx as reverse proxy and already did a lot of configurations.
A simple curl is ok:

    curl https://appwrite.domain.com/v1/health/version
    {"version":"1.2.1"}

Login with IP address, fine!

    $ appwrite login
    ? Enter your email [felipe@domain.com](mailto:felipe@domain.com)
    ? Enter your password *******
    ? Enter the endpoint of your Appwrite server http://10.0.0.1/v1
    ✓ Success

Login with FQDN, fail...

    $ appwrite login
    ? Enter your email [felipe@domain.com](mailto:felipe@domain.com)
    ? Enter your password *******
    ? Enter the endpoint of your Appwrite server https://appwrite.domain.com/v1
    ✗ Error Invalid endpoint or your Appwrite server is not running as expected.

Testing CLI with --verbose

    > appwrite client --endpoint https://appwrite.domain.com/v1 --verbose
    Error: Invalid endpoint or your Appwrite server is not running as expected.
        at C:\snapshot\sdk-for-cli\lib\commands\generic.js:90:23
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

**OBS:** Could not find `C:\snapshot\sdk-for-cli\` im my computer. Is it normal?

This is the Nginx server config /etc/nginx/sites-enabled/appwrite.conf :

    server{
           listen 80;
           server_name appwrite.domain.com;
           return 301 https://appwrite.domain.com$request_uri;
    }
    server{
           listen 443 ssl;
           server_name appwrite.domain.com;
           location / {
                  proxy_set_header Upgrade    $http_upgrade;
                  proxy_set_header Connection $http_connection;
                  proxy_http_version 1.1;
                  add_header       X-Served-By        $host;
                  proxy_set_header X-Forwarded-Scheme $scheme;
                  proxy_set_header X-Forwarded-Proto  $scheme;
                  proxy_set_header X-Forwarded-Host   $host;
                  proxy_set_header X-Forwarded-For    $remote_addr;
                  proxy_set_header Host       $host;
                  proxy_set_header X-Real-IP  $remote_addr;
                  proxy_pass http://10.0.0.1;
           }
    }

SSL settings are in nginx.conf

### 👍 Expected behavior

$ appwrite login
? Enter your email [felipe@domain.com](mailto:felipe@domain.com)
? Enter your password *******
? Enter the endpoint of your Appwrite server https://appwrite.domain.com/v1
✓ Success

### 👎 Actual Behavior

$ appwrite login
? Enter your email [felipe@domain.com](mailto:felipe@domain.com)
? Enter your password *******
? Enter the endpoint of your Appwrite server https://appwrite.domain.com/v1
✗ Error Invalid endpoint or your Appwrite server is not running as expected.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Cloud Provider: Azure
Appwrite Version: 1.2.1
Nginx - Reverse Proxy

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@felipeavilis, thanks for creating this issue! 🙏🏼 What's the output of this?

```
curl http://appwrite.domain.com/v1/health/version
```

**Comment by felipeavilis** [comment]
> @felipeavilis, thanks for creating this issue! 🙏🏼 What's the output of this?
> 
> ```
> curl http://appwrite.domain.com/v1/health/version
> ```

Hi, thanks for the reply. I'v already tested it.

![image](https://user-images.githubusercontent.com/97637336/225891803-a5993b01-d39d-42a3-ac44-fa9488b0dbc7.png)

{"version":"1.2.1"}

**Comment by stnguyen90** [comment]
@felipeavilis, something is weird with the redirect 🧐 Would you please try:

```
curl -v -L http://appwrite.domain.com/v1/health/version
```

**Comment by felipeavilis** [comment]
HTTP
     > curl -l -v http://domain.com/v1/health/version
     *   Trying 10.0.0.1:80...
     * Connected to domain.com (10.0.0.1) port 80 (#0)
     > GET /v1/health/version HTTP/1.1
     > Host: domain.com
     > User-Agent: curl/7.83.1
     > Accept: */*
     >
     * Mark bundle as not supporting multiuse
     < HTTP/1.1 301 Moved Permanently
     < Server: nginx
     < Date: Fri, 17 Mar 2023 17:48:45 GMT
     < Content-Type: text/html
     < Content-Length: 162
     < Connection: keep-alive
     < Location: https://domain.com/v1/health/version
     < Strict-Transport-Security: max-age=63072000
     <
     <html>
     <head><title>301 Moved Permanently</title></head>
     <body>
     <center><h1>301 Moved Permanently</h1></center>
     <hr><center>nginx</center>
     </body>
     </html>
     * Connection #0 to host domain.com left intact




HTTPS
     > curl -l -v https://domain.com/v1/health/version
     *   Trying 10.0.0.1:443...
     * Connected to domain.com (10.0.0.1) port 443 (#0)
     * schannel: disabled automatic use of client certificate
     * ALPN: offers http/1.1
     * ALPN: server accepted http/1.1
     > GET /v1/health/version HTTP/1.1
     > Host: domain.com
     > User-Agent: curl/7.83.1
     > Accept: */*
     >
     * Mark bundle as not supporting multiuse
     < HTTP/1.1 200 OK
     < Server: nginx
     < Date: Fri, 17 Mar 2023 17:49:31 GMT
     < Content-Type: application/json; charset=UTF-8
     < Content-Length: 19
     < Connection: keep-alive
     < Access-Control-Allow-Credentials: true
     < Access-Control-Allow-Headers: Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, 
     X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-SDK-GraphQL, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma
     < Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE
     < Access-Control-Allow-Origin: http://localhost
     < Access-Control-Expose-Headers: X-Fallback-Cookies
     < X-Content-Type-Options: nosniff
     < X-Debug-Fallback: true
     < X-Debug-Speed: 0.0014669895172119
     < X-Served-By: domain.com
     <
     {"version":"1.2.1"}* Connection #0 to host domain.com left intact

**Comment by stnguyen90** [comment]
@felipeavilis, would you please try again but with `-L` instead of `-l`. `-l` is equivalent to `--list-only` while `-L` is `--location` to follow redirects.

**Comment by felipeavilis** [comment]
I think that's what you were looking for....

    curl --location -v http://domain.com/v1/health/version -k
    *   Trying 10.0.0.1:80...
    * TCP_NODELAY set
    * Connected to domain.com (10.0.0.1) port 80 (#0)
    > GET /v1/health/version HTTP/1.1
    > Host: domain.com
    > User-Agent: curl/7.65.0
    > Accept: */*
    >
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 301 Moved Permanently
    < Server: nginx
    < Date: Fri, 17 Mar 2023 21:48:58 GMT
    < Content-Type: text/html
    < Content-Length: 162
    < Connection: keep-alive
    < Location: https://domain.com/v1/health/version
    < Strict-Transport-Security: max-age=63072000
    <
    * Ignoring the response-body
    * Connection #0 to host domain.com left intact
    * Issue another request to this URL: 'https://domain.com/v1/health/version'
    *   Trying 10.0.0.1:443...
    * TCP_NODELAY set
    * Connected to domain.com (10.0.0.1) port 443 (#1)
    * ALPN, offering http/1.1
    * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    * successfully set certificate verify locations:
    *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
      CApath: none
    * TLSv1.2 (OUT), TLS header, Certificate Status (22):
    * TLSv1.2 (OUT), TLS handshake, Client hello (1):
    * TLSv1.2 (IN), TLS handshake, Server hello (2):
    * TLSv1.2 (IN), TLS handshake, Certificate (11):
    * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
    * TLSv1.2 (IN), TLS handshake, Server finished (14):
    * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
    * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
    * TLSv1.2 (OUT), TLS handshake, Finished (20):
    * TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
    * TLSv1.2 (IN), TLS handshake, Finished (20):
    * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
    * ALPN, server accepted to use http/1.1
    * Server certificate:
    *  subject: CN=*.domain.com
    *  start date: Jan 31 00:00:00 2023 GMT
    *  expire date: Jan 31 23:59:59 2024 GMT
    *  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
    *  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
    > GET /v1/health/version HTTP/1.1
    > Host: domain.com
    > User-Agent: curl/7.65.0
    > Accept: */*
    >
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 200 OK
    < Server: nginx
    < Date: Fri, 17 Mar 2023 21:48:58 GMT
    < Content-Type: application/json; charset=UTF-8
    < Content-Length: 19
    < Connection: keep-alive
    < Access-Control-Allow-Credentials: true
    < Access-Control-Allow-Headers: Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-SDK-GraphQL, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma
    < Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE
    < Access-Control-Allow-Origin: http://localhost
    < Access-Control-Expose-Headers: X-Fallback-Cookies
    < X-Content-Type-Options: nosniff
    < X-Debug-Fallback: true
    < X-Debug-Speed: 0.0014111995697021
    < X-Served-By: domain.com
    <
    * Connection #1 to host domain.com left intact
    {"version":"1.2.1"}

**Comment by stnguyen90** [comment]
@felipeavilis interesting...your redirect seems to be working fine...

What's your Appwrite CLI version? (`appwrite --version`) and what version of node do you have?

**Comment by stnguyen90** [comment]
That said, I definitely recommend using https instead of http because the redirect for POST requests will result in GET requests and not complete properly

**Comment by felipeavilis** [comment]
> That said, I definitely recommend using https instead of http because the redirect for POST requests will result in GET requests and not complete properly

HTTPS is getting the same error:

    > appwrite client --endpoint https://appwrite.domain.com/v1 --verbose 
    Error: Invalid endpoint or your Appwrite server is not running as expected.
        at C:\snapshot\sdk-for-cli\lib\commands\generic.js:90:23
        at processTicksAndRejections (node:internal/process/task_queues:96:5)  
    ✗ Error Invalid endpoint or your Appwrite server is not running as expected.

**Comment by felipeavilis** [comment]
Ok, lets try again...

    > appwrite client --endpoint http://10.0.0.1/v1 --verbose                 
    ✓ Success 
    > appwrite client --endpoint https://appwrite>domain.com/v1 --verbose                  
    Error: Invalid endpoint or your Appwrite server is not running as expected.
        at C:\snapshot\sdk-for-cli\lib\commands\generic.js:90:23
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ✗ Error Invalid endpoint or your Appwrite server is not running as expected.
    > appwrite client --endpoint http://appwrite.domain.com/v1 --verbose 
    Error: Invalid endpoint or your Appwrite server is not running as expected.
        at C:\snapshot\sdk-for-cli\lib\commands\generic.js:90:23
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ✗ Error Invalid endpoint or your Appwrite server is not running as expected.

**Comment by stnguyen90** [comment]
> I think that CLI is showing its own version, not Appwrite server version

What do you mean?

> Any alternative?

Would you be willing to DM me your domain on [Discord](https://appwrite.io/discord)?

**Comment by stnguyen90** [comment]
@felipeavilis do you still need help with this? Otherwise, I'll need to close this soon due to inactivity.

**Comment by felipeavilis** [comment]
I'll send you my domain on Discord.

**Comment by stnguyen90** [comment]
Thanks for reaching out on Discord! 🙏🏼 

After modifying the [error handler](https://github.com/appwrite/sdk-for-cli/blob/79876b66f5d641d47d361daad0ec702dc1cbf587/lib/commands/generic.js#L89-L91) to log the exception, I saw the error was:

```shell
$ appwrite client --endpoint https://appwrite.domain.com/v1    
AppwriteException [Error]: unable to verify the first certificate
    at Client.call (/Users/steven/.nvm/versions/node/v16.16.0/lib/node_modules/appwrite-cli/lib/client.js:223:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/steven/.nvm/versions/node/v16.16.0/lib/node_modules/appwrite-cli/lib/commands/generic.js:74:32 {
  code: undefined,
  response: undefined
}
✗ Error Invalid endpoint or your Appwrite server is not running as expected.
```

It seems the certificate on your server didn't have the full certificate chain so node wasn't able to fully verify the certificate. The workaround is either to:

1. Update the server to use an SSL certificate with the full chain
2. Force the Appwrite CLI to ignore the SSL error by manually updating `~/.appwrite/prefs.json` to set the `endpoint` to your endpoint and `selfSigned` to `true`.

**Comment by felipeavilis** [comment]
Thank you Steven! I updated the server cert to a full chain an it worked.
