### ISSUE TITLE
🐛 Bug Report: OAuth2 failed - redirect URI does not match

### ISSUE THREAD

**Issue by HannesPaa** [appwrite/appwrite#5239]
### 👟 Reproduction steps

I wanted to create an OAuth2 Session with Microsoft. So i configured it in the Appwrite Settings and in MS Azure with the URI that are given from Appwrite. And then i tried to login.

### 👍 Expected behavior

It schould direct me to to Microsoft-Authentication-Page, where i login into my Microsoft Account and then it redirect me to the site, from where i want to log in.

### 👎 Actual Behavior

It directed me to the Microsoft-Authentication-Page and i could login with my MS-Account. But before it redirect me back this error happend:

> The redirect URI 'http://appwrite.******.de/v1/account/sessions/oauth2/callback/microsoft/*************' specified in the request does not match the redirect URIs configured for the application '***************'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

I think it is because the URI beginns with "http" and not "https". The URI that is given from Appwrite beginns with "https" so in the Azure configuration the URI is also with "https". The rest of the URI matches.
My Appwrite is reachable with "https://appwrite.******.de", so i dont know why Appwrite sends Microsoft the false URI. 

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Appwrite in a Docker container. I use the proxy-manager nginx from the image "jwilder/nginx-proxy".

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@HannesPaa, thanks for raising this issue! 🙏🏼 Do you have a reverse proxy in front of Appwrite? If you do, are you proxying to Appwrite via HTTPS or HTTP? If you're proxying to HTTP, would you please switch to HTTPS?

**Comment by HannesPaa** [comment]
Yes, i have a reverse proxy, but even if i disable http (HTTPS_METHOD: nohttp) it does not work.
Now and bevor, when i go to appwrite.****.de or http://appwrite.****.de i am landing on https://appwrite.****.de, so i think the proxy https should work correctly.

**Comment by stnguyen90** [comment]
@HannesPaa, please try to proxy to Appwrite using HTTPS. The redirect is not the problem. The important thing is communication between Appwrite and your reverse proxy should be through HTTPS.

**Comment by HannesPaa** [comment]
Sorry, you are absolutely right. I had to add this to the docker-compose.yml for the traefik-service:
```
VIRTUAL_PROTO: "https"
VIRTUAL_PORT: 443
```

**Comment by stnguyen90** [comment]
@HannesPaa so is it working now? If so, feel free to close this issue.
