### ISSUE TITLE
🚀 Feature: 2FA to the dashboard login

### ISSUE THREAD

**Issue by nimos-dev** [appwrite/appwrite#5240]
### 🔖 Feature description

Add 2FA to the appwrite dashboard login

1: Authenticator Apps
2: Email
3: Phone ?

### 🎤 Pitch

For increased security when logging in to the dashboard!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@nimos-dev, thanks for raising this issue! 🙏🏼 This is definitely on our roadmap! We'll share more when something is available.

**Comment by Deliana90** [comment]
looking forward ^_^ subscribed

**Comment by abnegate** [comment]
This is now available in Appwrite 1.5 🥳
