### ISSUE TITLE
🐛 Bug Report: Updating Environment Variables

### ISSUE THREAD

**Issue by thedevmanek** [appwrite/appwrite#5251]
### 👟 Reproduction steps

When i run 
```
docker run -it --rm \
--env-file appwrite/dock.env \
--volume /var/run/docker.sock:/var/run/docker.sock \
--volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
--entrypoint="install" \
appwrite/appwrite:1.2.1
```
with 
dock.env as
```
_APP_OPTIONS_ABUSE=disabled
```

### 👍 Expected behavior

stop rate limiting

### 👎 Actual Behavior

but it does not stop it
![image](https://user-images.githubusercontent.com/58616961/226197699-fd665629-300b-4473-8124-582ed66d69cb.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite: ^8.3.0 in flutter

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@thedevmanek, thanks for creating this issue! 🙏🏼 

Unfortunately, passing an env file in like you're doing is not supported. Please review our [Environment Variables docs](https://appwrite.io/docs/environment-variables) for how to update environment variables.

**Comment by stnguyen90** [comment]
@thedevmanek, do you still need clarification? FYI, I'll need to close this soon due to inactivity.
