### ISSUE TITLE
[BUG] case sensitive country flag code

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#526]
`GET /avatars/flags/{code}` only works wither lower-case letters.

That is not really convenient, since the country codes from `GET /locale/countries` are capitalized.

My suggestion would be, to make `GET /avatars/flags/{code}` case-insensitive.

**Comment by eldadfux** [comment]
Would it be a good idea to lowercase all the codes returned in the JSON response as well for better consistency?

**Comment by muehlt** [comment]
I think most other APIs use the uppercase version, so this may be the better option.

**Comment by TorstenDittmann** [comment]
Don't know. Upper case is actually fine imo.

It is very likely to work with some libraries that return different capitalization any, so I think we shouldnt care about casing there 👍

**Comment by eldadfux** [comment]
I created a quick fix, gonna submit a PR in a few moments
![image](https://user-images.githubusercontent.com/1297371/92649781-38f8e880-f2f4-11ea-8bfb-327c9c03526e.png)

**Comment by eldadfux** [comment]
Fix has been merged to 0.7.x branch.

**Comment by eldadfux** [comment]
v0.7 is finally out with all the updates available 🥳
