### ISSUE TITLE
🐛 Bug Report: Documentation Models Attribute Datetime

### ISSUE THREAD

**Issue by YaMiSt** [appwrite/appwrite#5272]
### 👟 Reproduction steps

Go to: https://appwrite.io/docs/models/attributeDatetime 

I think the example on the website is wrong, because I got an error from appwlite cli:

`{
    "key": "birthDay",
    "type": "2020-10-15T06:38:00.000+00:00",
    "status": "available",
    "required": true,
    "array": false,
    "format": "datetime",
    "default": "2020-10-15T06:38:00.000+00:00"
}`

### 👍 Expected behavior

It should be (is there a format possible?):

`{
    "key": "birthDay",
    "type": "datetime",
    "status": "available",
    "required": true,
    "array": false,
    "default": "2020-10-15T06:38:00.000+00:00"
}`

### 👎 Actual Behavior

Actually i got an error from the console.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rinkuhasija** [comment]
I want to work on this Issue. Please assign it to me.

**Comment by imtushardave** [comment]
@stnguyen90 raised PR as per the suggested changes

**Comment by stnguyen90** [comment]
@rinkuhasija, assigned! Thanks for your interest! 🙏🏼 

@imtushardave, to be considerate of others, we try to assign on a first-come, first-serve basis. If @rinkuhasija isn't able to submit a PR, I'll reassign this issue to you.

**Comment by imtushardave** [comment]
No issues @stnguyen90, I really appreciate your consideration for each contributer.

**Comment by rinkuhasija** [comment]
@stnguyen90 raised a PR that fixes this Issue.

**Comment by imtushardave** [comment]
> @stnguyen90 raised PR as per the suggested changes

I am closing this PR as @rinkuhasija has raised PR for the same. Happy contributing!

**Comment by gewenyu99** [comment]
@Haimantika Closing. Thanks @rinkuhasija for the PR
