### ISSUE TITLE
🚀 Feature: Add a markdown attribute with editor

### ISSUE THREAD

**Issue by sanny-io** [appwrite/appwrite#5275]
### 🔖 Feature description

Add a markdown attribute to the database that basically acts like a string attribute, but renders the attribute's form input as a markdown editor.

It's worth noting multiline inputs aren't currently supported with Appwrite.

### 🎤 Pitch

Markdown is a very popular syntax for publishing content. A dedicated markdown editor would greatly improve the user experience for many of us.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rafagazani** [comment]
> mas renderiza a entrada do formulário do atributo como um editor markdown.

@sanny-io Está se referindo a visualizar no console?

**Comment by sanny-io** [comment]
@rafagazani Yes

**Comment by joeyouss** [comment]
Hi @sanny-io 

Thank you for the suggestion. As of now, we haven't incorporated this feature and, given the current direction and demand, it's unlikely that we'll add this in the immediate future. It seems this would cater specifically to the console, and the demand for such a feature seems limited at the moment.

However, we genuinely appreciate the feedback and always encourage developers to share their thoughts. I'll be closing this issue for the time being, but we'll definitely consider reopening it should the need or demand arise in the future.

Thanks for understanding!
