### ISSUE TITLE
📚 Documentation: Flutter installation: pub get instead of pub add

### ISSUE THREAD

**Issue by DHsoftw** [appwrite/appwrite#5277]
### 💭 Description

In the appwrite main dashboard quickstart (when creating a new flutter application) and [pub.dev](https://pub.dev/packages/appwrite) for flutter, it seem to suggest that the command to install appwrite is:

pub get appwrite

Such command doesn't works since what's correct to install a dependency (automatically) in flutter is:

pub add appwrite

It appears correctly in the [installation section at pub.get](https://pub.dev/packages/appwrite/install) 
Probably it's referring to run this command after adding previously the pubsec.yaml code, being very confusing and thinking that's the pub add command to install appwrite.

What I suggest is making an additional section for both methods of installing it like it's in the [installation section at pub.get](https://pub.dev/packages/appwrite/install) 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@DHsoftw, thanks for catching this! 🙏🏼 Looks like we need to fix this in:

1. [docs](https://github.com/appwrite/docs/blob/ef19d6ecdd32e98993de21484a822ed4885af91c/app/views/docs/getting-started-for-flutter.phtml#L124)
2. [console](https://github.com/appwrite/console/blob/5aed7003622fe151eeed8f2761f733c4a65e96c0/src/routes/console/project-%5Bproject%5D/overview/platforms/wizard/flutter/step2.svelte#L8)
3. sdk-generator
   1. [dart](https://github.com/appwrite/sdk-generator/blob/7e2456a1e912ad7eeb45762bec2fcf3fd92b0a3f/templates/dart/README.md.twig#L38)
   2. [flutter](https://github.com/appwrite/sdk-generator/blob/7e2456a1e912ad7eeb45762bec2fcf3fd92b0a3f/templates/flutter/README.md.twig#L38)

**Comment by DHsoftw** [comment]
Yes, that's correct. 

I think the most correct explanation it could appear is:
Add appwrite SDK to your package's pubspec.yaml file:

dependencies:
  appwrite: ^<?php echo $this->escape($version);

Then run in your terminal:
  Flutter pub get appwrite



You can also install it using the dart/flutter package manager from your terminal:

  Flutter pub add appwrite

It will add automatically the dependencies to your pubsec.yaml file

**Comment by DHsoftw** [comment]
I honestly think most people just installs almost every dependencies with the flutter pub add appwrite command and done, since it's faster

**Comment by Om-Gujarathi** [comment]
Hi there, I noticed the open issue and I would be happy to work on it if no one else has taken it up yet.

**Comment by imtushardave** [comment]
@stnguyen90 Hi Steven, raised PR as per the suggested changes

**Comment by DHsoftw** [comment]
It see

**Comment by DHsoftw** [comment]
Sorry, clicked accidentally the button. The changes looks being correctly

**Comment by hajajmaor** [comment]
does this issue still open to PR?
