### ISSUE TITLE
Bad redaction and misspellings in Spanish email translations

### ISSUE THREAD

**Issue by DHsoftw** [appwrite/appwrite#5288]
The Spanish translations have serious misspellings.

- Email recovery:
**_Current message:_**

Hola [yourName]

Haz clic en este enlace para restablecer la contraseña de Appwrite.

[Link]
Si no has solicitado restablecer la contraseña, puedes ignorar este mensaje.

Gracias Equipo de Appwrite

**_What's correct:_**

Hola [yourName] **.**

Haz clic en este enlace para restablecer la contraseña de Appwrite **:**

[Link]
Si no has solicitado restablecer la contraseña, puedes ignorar este mensaje.

Gracias **.** **El** equipo de Appwrite**.**

- Invitation link:

_**Current email:**_

Hola

Este correo ha sido enviado a petición de [sender name] quien quiere invitarte a formar parte del equipo [team name] en Appwrite.

[Invitation link]
Si no estas interesado, puedes ignorar este mensaje.

Gracias Equipo de Appwrite

**_What it should be_**:

Hola **,** este correo ha sido enviado a petición de [sender name] qui **é** n quiere invitarte a formar parte del equipo [team name] en Appwrite.

[Invitation link]
Si no est **á**s interesado, puedes ignorar este mensaje.

Gracias **.** **El** equipo de Appwrite **.**

- Magic link:
"ingresar" is incorrect in such context. It should be replaced to "iniciar sesión", who is the real equivalent to login in Spanish

- Sender name should have "El" before "equipo" (the before team) and "de" after equipo (El equipo de [team name])

(Obviously dots and comas are together with the other words. Separated them to bold them)
Other messages are probably containing misspellings too. I will edit this to add them.

**Comment by stnguyen90** [comment]
@DHsoftw would you like to work on a PR? The translation file can be found [here](https://github.com/appwrite/appwrite/blob/master/app/config/locale/translations/es.json). General contributing guidance can be found [here](https://github.com/appwrite/appwrite/discussions/4899).

**Comment by DHsoftw** [comment]
> @DHsoftw would you like to work on a PR? The translation file can be found [here](https://github.com/appwrite/appwrite/blob/master/app/config/locale/translations/es.json). General contributing guidance can be found [here](https://github.com/appwrite/appwrite/discussions/4899).

Ok

**Comment by DHsoftw** [comment]
Done, PR created
