### ISSUE TITLE
🐛 Bug Report: Easy UI fix when hovering over Users

### ISSUE THREAD

**Issue by Maettis** [appwrite/appwrite#5291]
### 👟 Reproduction steps

![image](https://user-images.githubusercontent.com/59470689/228372304-a89af0ea-5161-4cc0-97ce-fc1784228e25.png)
![image](https://user-images.githubusercontent.com/59470689/228372713-868c8dbf-4b2a-4c05-9090-c25e94d55e90.png)

When hovering over the last user, the hover effect is going out of the container and overlapping with the border. Looks not pleasing.

### 👍 Expected behavior

Just change background color

### 👎 Actual Behavior

It overlaps with the border

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Maettis** [comment]
![image](https://user-images.githubusercontent.com/59470689/228372713-868c8dbf-4b2a-4c05-9090-c25e94d55e90.png)

**Comment by joeyouss** [comment]
Hi, thank you for bringing this up.

**Comment by sara-k-48** [comment]
@Maettis Thanks for reporting this! I was wondering if you could let us know your browser version? I'm not able to reproduce it myself, so perhaps it's a browser-specific issue.

**Comment by Maettis** [comment]
@sara-k-48 
Version 111.0.1 (64-bit)
Mozilla Firefox for Ubuntu

**Comment by Snach13** [comment]
@Maettis Try with chrome

**Comment by Maettis** [comment]
@Snach13  I think you don' undersstand the thought behind this issue. I know, that I could just use another browser, but this isn't a issue that is braking the product or affecting my experience with Appwrite. It's just a little problem that isn't intended by the developers and I reported it. Your contribution does not help this issue and is just unnecessary.
