### ISSUE TITLE
Hello, I want to get all users that are logged in my Appwrite to show up in my Flutter page

### ISSUE THREAD

**Issue by Hariswar8018** [appwrite/appwrite#5293]
Hello, I am completely new to flutter and i want an help to show all users that are in the Appwrite console to show in my Futter page for chatting. Somebody please help.

**Comment by rafagazani** [comment]
If you are working with teams, you can use the
https://appwrite.io/docs/client/teams?sdk=web-default#teamsListMemberships
Will list all users that are part of that team

**Comment by rafagazani** [comment]
for questions like this I recommend you to join the discord community

**Comment by Hariswar8018** [comment]
No dear, It's not about Team. I build a whatsapp like App and want to show a Logged in users the list of all users that are logged in

**Comment by rafagazani** [comment]
is that list all users is only available in server sdk. I made a sample chat project for you.
In this project my strategy was to create a collection with data from all users. Whenever a user is registered, a function is triggered to feed this collection and then display the list in the application. I hope it's useful:
https://github.com/rafagazani/farol_chat_example

**Comment by rafagazani** [comment]
I made use of realtime to list the collection in real time

**Comment by rafagazani** [comment]
You will be very welcome in the discord community. there the answers are usually faster. The github issues we leave more for issues, features.
For doubts the best channel is discord

**Comment by Hariswar8018** [comment]
Oh, I am sorry. I am checking your project. But Is there not any sample project/code of appwrite and flutter that make a app like Whatsapp. It would greatly help ?

**Comment by Hariswar8018** [comment]
Hello :( The project you gave me is not in flutter:(

**Comment by rafagazani** [comment]
> Desculpe. Estou verificando seu projeto. Mas não há nenhum projeto/código de exemplo de appwrite e flutter que crie um aplicativo como o Whatsapp. Ajudaria muito?

Now I don't remember a quasar whatsapp. Here is a good first contribution

**Comment by rafagazani** [comment]
> Olá :( O projeto que você me deu não está em flutter :(

and yes. There are two projects inside, Faro_chat_servidor is for the server, the others are for the flutter project

**Comment by Hariswar8018** [comment]
Actually, I just wants to known wether it is possible or not. Creating a Whatsapp like apk but backend with Appwrite instead of Firebase?

**Comment by Hariswar8018** [comment]
What is server here?

**Comment by rafagazani** [comment]
> Na verdade, eu só quero saber se é possível ou não. Criando um Whatsapp como apk, mas back-end com Appwrite em vez de Firebase?

Yes it is possible, I have already implemented it in a commercial project. back appwrite, front flutter android, web and windows

**Comment by rafagazani** [comment]
> What is server here?

farol_chat_servidor

**Comment by Hariswar8018** [comment]
farol_chat_servidor??? 
I mean there is only Flutter and Appwrite involved? So, What is server here?

**Comment by Hariswar8018** [comment]
Can i literally see any example of a code that search users, and chat with other user in realtime?

**Comment by rafagazani** [comment]
> farol_chat_servidor??? Quero dizer, há apenas Flutter e Appwrite envolvidos? Então, o que é servidor aqui?

Farol_chat_servidor: It's just a few python scripts to create the collection in appwrite without having to add it manually in the console. but you can ignore

**Comment by rafagazani** [comment]
@joeyouss I think we can close this issue.

**Comment by rafagazani** [comment]
@stnguyen90 I think we can close this issue.
