### ISSUE TITLE
🐛 Bug Report: unnecessary scrollbars 

### ISSUE THREAD

**Issue by Ananya2001-an** [appwrite/appwrite#5295]
### 👟 Reproduction steps

1. create new project
2. create new platform
3. click next till you reach the "Let's coding" step

### 👍 Expected behavior

The copy to clipboard icon is hidden behind the scrollbar. It just looks very messy.
![Console-Appwrite](https://user-images.githubusercontent.com/55504616/228593524-5451f40c-3337-4600-bcc6-50c9e7378cc0.png)

### 👎 Actual Behavior

 Maybe we can increase the height a bit or just hide the scrollbar. A little bit of padding can also do the work IMO.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by kabhamo** [comment]
Hi @stnguyen90 I hope you are doing well,
Can you please review the issue? 
If you need to make changes, please assign the issue to me, I have a ready PR for it.

**Comment by Janaki4** [comment]
Hey @Ananya2001-an  , I would like to work on this. Can you please assign it to me . ? Thanks

**Comment by Ananya2001-an** [comment]
> Hey @Ananya2001-an  , I would like to work on this. Can you please assign it to me . ? Thanks

Hey @Janaki4 I am not a maintainer. Someone from the team will come and assign the issue to you if it gets approved.
