### ISSUE TITLE
Broken website links

### ISSUE THREAD

**Issue by muehlt** [appwrite/appwrite#530]
The **retirement process** links on [the release lifecycle page](https://appwrite.io/docs/release-lifecycle) seem to be broken. @eldadfux (since the website is not open-source yet)

**Comment by Gajesh2007** [comment]
Which links are broken? @muehlt @eldadfux

**Comment by eldadfux** [comment]
This will be fixed in the next deployment of https://appwrite.io

**Comment by muehlt** [comment]
> Which links are broken? @muehlt @eldadfux 

_The **retirement process** links on [the release lifecycle page](https://appwrite.io/docs/release-lifecycle)_.

@eldadfux fixed it because the website is not open source yet 👍

**Comment by eldadfux** [comment]
Fixed
