### ISSUE TITLE
🐛 Bug Report: Session delete modal is not closing 

### ISSUE THREAD

**Issue by rohan220217** [appwrite/appwrite#5303]
### 👟 Reproduction steps

1. Go to Auth tab
2. Select any user
3. Go to Sessions tab
4. Delete any session
5. After deletion popup is not closing

### 👍 Expected behavior

Popup should close after the success of deletion

### 👎 Actual Behavior

The popup persists and after clicking again it shows the session is not found because ultimately session is being deleted.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I have used the docker container to pull the image appwrite/appwrite:1.2.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rohan220217** [comment]
I am trying to fix it but unfortunately i can't find the particular file

**Comment by probablyArth** [comment]
> I am trying to fix it but unfortunately i can't find the particular file

This is related to [appwrite/console](https://github.com/appwrite/console/issues)

**Comment by rohan220217** [comment]
ooh I didn't know about it. Thanks

**Comment by probablyArth** [comment]
yea but you can contribute in this repo 👌
https://github.com/appwrite/sdk-generator
