### ISSUE TITLE
🐛 Bug Report: storage.createFile doesn't work in serverside

### ISSUE THREAD

**Issue by RoxDevvv** [appwrite/appwrite#5305]
### 👟 Reproduction steps

```
const sdk = require("node-appwrite");
const fs = require('fs');
const { generateCsv, isJsonString } = require('./utils');

module.exports = async function (req, res) {
  const client = new sdk.Client();

  const database = new sdk.Databases(client);
  const storage = new sdk.Storage(client);
  console.log('Database Backup Action Started');
  const payload = req.payload;
 
  if (!isJsonString(payload) || !JSON.parse(payload).hasOwnProperty('databaseId')) {
    res.json({
      Error: 'Wrong payload when executing function.'
    });
    return;
  }


  if (
    !req.variables['APPWRITE_FUNCTION_ENDPOINT'] ||
    !req.variables['APPWRITE_FUNCTION_API_KEY']
  ) {
    console.log("Environment variables are not set. Function cannot use Appwrite SDK.");
  } else {
    console.log("project id");
    console.log(req.variables['APPWRITE_FUNCTION_PROJECT_ID']);
    client
      .setEndpoint(req.variables['APPWRITE_FUNCTION_ENDPOINT'])
      .setProject(req.variables['APPWRITE_FUNCTION_PROJECT_ID'])
      .setKey(req.variables['APPWRITE_FUNCTION_API_KEY'])
      .setSelfSigned(true);
  }



  const { databaseId } = JSON.parse(payload);
  console.log("databaseId: " + databaseId);

  try {
    const response = await storage.createFile("642537ff276d1ead7839", sdk.ID.unique(), sdk.InputFile.fromPlainText("hi", "test.txt"), [
      sdk.Permission.read(sdk.Role.any),
      sdk.Permission.update(sdk.Role.any),
      sdk.Permission.delete(sdk.Role.any)
    ]);
    console.log(response);
  } catch (error) {
    console.error(error);
  }
  
  console.log('backup created!');
  res.json({ 'Success': true })
};

```

### 👍 Expected behavior

i should find the files in the storage

### 👎 Actual Behavior

when use await
i get error An internal curl error has occurred within the executor! Error Msg: Connection reset by peer
without await no error appear also no files created 

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

i installed it from digitalocean
https://marketplace.digitalocean.com/apps/appwrite

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by RoxDevvv** [comment]
if i execute the function without payload it work 
is there anyone knows why storage.createFile doesn't work when executed with payload

**Comment by freefreeP** [comment]
@RoxDevvv with no payload you mean like sdk.InputFile.fromPlainText("", "test.txt") ? And then it gets succesfully created in the storage, right ?

**Comment by RoxDevvv** [comment]
No the` storage.createFile` parameter stays as it is now what I removed is this ` const payload = req.payload;`

it looks like when `req.payload` not empty `storage.createFile` behave differently

**Comment by RoxDevvv** [comment]
after farther testing i found the problem in this line `InputFile.fromStream(fileStream, `${DataBase.name}.json`);`
it have nothing to do with `const payload = req.payload;`
