### ISSUE TITLE
Killer features for your platform : off-line database support

### ISSUE THREAD

**Issue by davoutuk** [appwrite/appwrite#5306]
I really like your platform, but at the moment there isn't a lot of significant advantage to moving away from Firebase.

To provide a more distinct market advantage you may want to think about...

- Adding a 'Postgres' database option to the service mix.  No SQL stores have there limitations. 
- Adding 'off line database' support for mobile apps,  with the sync'ing of data from local mobile database to the server database

**Comment by rafagazani** [comment]
All these points are in the script, here is an example
https://github.com/appwrite/appwrite/issues/1168

**Comment by joeyouss** [comment]
Hi,
Both these features are in progress - as pointed out by @rafagazani. That being said, we appreciate your patience while we work on these features 😊

**Comment by rafagazani** [comment]
I think it would be better to close this question since these features have their own issues
