### ISSUE TITLE
🐛 Bug Report: Server sdk for node deleteFile api delete storage bucket instead of file.

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#5310]
### 👟 Reproduction steps

Server sdk for node ```deleteFile``` api delete storage bucket if file ID had empty string as parameter.
It should throw exception if file ID had empty string.

```ts
try {
    const res = await SDK.storage.deleteFile('BucketID', '');
    console.log(res);
} catch (e) {
    if (e instanceof AppwriteException) {
        console.log(e.message);
    }
    console.log(e);
}
```

### 👍 Expected behavior

It should throw exception if file ID had empty string provided instead of file ID.

### 👎 Actual Behavior

Server sdk for node ```deleteFile``` api delete storage bucket if file ID had empty string as parameter.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by NewtonFernandis** [comment]
@usamashafiqs Could you please assign this issue to me?

**Comment by probablyArth** [comment]
you should probably raise this issue on sdk-generator or sdk-node

**Comment by freefreeP** [comment]
Hi All,

I have worked on this and raised a PR. Please review the [PR](https://github.com/appwrite/sdk-for-node/pull/54).

Thank you

**Comment by joeyouss** [comment]
Hi @freefreeP , thank you for raising the PR, our team will review it soon!

**Comment by stnguyen90** [comment]
Btw, this is a problem in utopia-php framework due to how were matching routes. This PR should fix this problem: https://github.com/utopia-php/framework/pull/92
