### ISSUE TITLE
🐛 Bug Report: Country tld for .np is not supported

### ISSUE THREAD

**Issue by Suven-p** [appwrite/appwrite#5317]
### 👟 Reproduction steps

1. Setup appwrite at a custom port say 81 for HTTP and 82 for HTTPS.
1. Setup apache reverse proxy with host forwarding according to https://github.com/appwrite/appwrite/discussions/4056.
Assume the domain name is appwrite.suven.com.np (using ccTLD).
1. Set variables `_APP_DOMAIN` and `_APP_DOMAIN_TARGET` to appwrite.suven.com.np. 
1. For DNS add an A record pointing to the IP of the server. 
1. Host a page at the root ie suven.com.np
1. Using account API logs warning to the console:

   ```
   Appwrite is using localStorage for session management. Increase your security by adding a custom domain as your API endpoint. to the console.
   ``` 
1. Trying to add custom domain for example from the project settings returns 500 errors. The logs from docker is:

   ```
   appwrite  | [Error] Method: POST
   appwrite  | [Error] URL: /v1/projects/:projectId/domains
   appwrite  | [Error] Type: Appwrite\Extend\Exception
   appwrite  | [Error] Message: Unreachable CNAME target (appwrite.suven.com.np), please use a domain with a public suffix.
   appwrite  | [Error] File: /usr/src/code/app/controllers/api/projects.php
   appwrite  | [Error] Line: 1344
   ```

According to discord server support, this is because the tld isn't supported.

### 👍 Expected behavior

Support .com.np tld.

### 👎 Actual Behavior

.com.np tld is not supported.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite version 1.2.1
Cloudflare for dns
Apache for proxy
Web SDK for the frontend

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @Suven-p,  thank you for sharing this. Seems like the domain is not supported as of yet - we can add it, however not sure about the timeline

**Comment by Suven-p** [comment]
Could you point me towards what's required to add support for it? Or any past PR for adding support for other tld.
