### ISSUE TITLE
📚 Documentation: Static files changes revamp

### ISSUE THREAD

**Issue by pranjalg13** [appwrite/appwrite#5318]
### 💭 Description

For changing static files in the repo, it is written to use the `gulp build` command which is no more applicable. We must replace it with the appropriate command to reload static files in the local build.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by pranjalg13** [comment]
![](https://cdn.discordapp.com/attachments/636852860709240842/1092357771971805184/Screenshot_2023-04-03_at_1.29.10_PM.png)

**Comment by pranjalg13** [comment]
Assign this to me if possible

Thanks in advance

**Comment by joeyouss** [comment]
Hi @pranjalg13, I will have a check with the team to confirm about this and if okay, will assign it to you!

**Comment by joeyouss** [comment]
@pranjalg13 go ahead, the issue is yours!

**Comment by pranjalg13** [comment]
@joeyouss check the pr once

Thanks
