### ISSUE TITLE
[Feature Request] Add pref object directly into the user object

### ISSUE THREAD

**Issue by lstephensca** [appwrite/appwrite#532]
It would be nice to add the pref object directly into the user object. Currently, I am working on admin app and listing all the users out in a table. It is nice being able to display all of the defined user data, but the the pref object is not returned in the call.  Currently, the pref object can only be used for a specific user providing their uid which means I now have to find a way of joining separate requests.

**Comment by TorstenDittmann** [comment]
This got implemented afaik 👍🏻
