### ISSUE TITLE
📚 Documentation: Update bcrypt password

### ISSUE THREAD

**Issue by RoxDevvv** [appwrite/appwrite#5321]
### 💭 Description

How to Update bcrypt password

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by RoxDevvv** [comment]
what i did is that and am not sure if that correct 
```
const hash = await bcrypt.hash(userData.password, 10);
await users.updatePassword(User.$id, hash);
```

**Comment by joeyouss** [comment]
Hi, can you elaborate a bit more please?

**Comment by RoxDevvv** [comment]
i registred user using this function 
```
        const hash = await bcrypt.hash(UserInfo.password, 10);
        User = await users.createBcryptUser(SDK.ID.unique(), UserInfo.email, hash, UserInfo.firstname);
```

now I want update the password using with bcrypt
```
const hash = await bcrypt.hash(userData.password, 10);
await users.updatePassword(User.$id, hash);
```
so is that correct or updatePassword method work only with normal password

**Comment by stnguyen90** [comment]
@RoxDevvv, are you still facing a problem, or can this be closed now? FYI, I'll need to close this due to inactivity soon.

**Comment by RoxDevvv** [comment]
What am trying to say when i create bcrypt password what is the right way to update it incase user want to change his password
```
 const hash = await bcrypt.hash(UserInfo.password, 10);
 User = await users.createBcryptUser(SDK.ID.unique(), UserInfo.email, hash, UserInfo.firstname);
```

should update password like that
```
const hash = await bcrypt.hash(userData.password, 10);
await users.updatePassword(User.$id, hash);
```

or simply call 
`await users.updatePassword(User.$id, password);`

**Comment by stnguyen90** [comment]
simply call `await users.updatePassword(User.$id, password);`
