### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Khalilsqu** [appwrite/appwrite#5328]
### 👟 Reproduction steps

![image](https://user-images.githubusercontent.com/22060413/230733869-b0ac61e4-4b45-40ea-8ec6-34b4e84e249f.png)

```
import { Client, Account } from "appwrite";

const client = new Client();

 client
      .setEndpoint(process.env.APPWRITE_ENDPOINT)
      .setProject(process.env.APPWRITE_PROJECT_ID);
```

```
    setEndpoint(endpoint) {
        this.config.endpoint = endpoint;
        this.config.endpointRealtime = this.config.endpointRealtime || this.config.endpoint.replace('https://', 'wss://').replace('http://', 'ws://');
        return this;
```

using nextjs and appwrite cloud

### 👍 Expected behavior

!!

### 👎 Actual Behavior

!!

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 🧱 Your Environment

latest 
web

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by HexiDev** [comment]
How did you fix this?
