### ISSUE TITLE
Hide/Show secret keys and passwords inside the dashboard

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#535]
Currently all secret keys or http password used for OAuth apps, webhooks and background tasks are visible in the Appwrite console by default. This is not the best practice when taking screenshots, video recording or sharing your screen with other people.

We need to create a new UI components that will add a small show/hide button above relevant input fields and will toggle them between <input type="text" /> and <input type="password" /> when the default option should be password view.

![image](https://user-images.githubusercontent.com/1297371/92997545-c74fb300-f51c-11ea-8314-43a7cea635fe.png)

**Comment by gagandeepp** [comment]
can you assign this issue to me?

**Comment by eldadfux** [comment]
@gagandeepp sure. please reach out on Discord if you need any help. Note that we're using vanilla JS for most of our UI, and please avoid any un-required dependencies. More info is available on Appwrite's [contribution guide](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md).

**Comment by mitchell-frost** [comment]
If this issue is still open, can I take it up?

**Comment by AbhishekTiwari07** [comment]
@eldadfux can i work on this issue?

**Comment by Aarush-Goyal** [comment]
If the issue is open can I work on it?

**Comment by SubashMuruganDev** [comment]
is this issue still open if so can i work on it ?

**Comment by Glide7** [comment]
Hey @SubashMuruganDev , do you want to take it?

**Comment by Aarush-Goyal** [comment]
If this issue is still open then I would like to take it

**Comment by Glide7** [comment]
Sounds good @Aarush-Goyal - i've assigned you on it!

**Comment by Aarush-Goyal** [comment]
Cool

**Comment by Aarush-Goyal** [comment]
@Glide7 I didn't knew the code was in PHP and I haven't worked with it pls unassign the issue from me. 
Sorry for the inconvenience

**Comment by kodumbeats** [comment]
I'd like to work on this one, if you please.

**Comment by Glide7** [comment]
That's ok @Aarush-Goyal - thanks for trying to help!

@kodumbeats sure! assigned you!

**Comment by kodumbeats** [comment]
Just to clarify - should this feature be developed from `master` or `0.7.x`? `CONTRIBUTING.md` says `master`, but I've seen other issues specify the starting branch.

**Comment by eldadfux** [comment]
@kodumbeats you should use the `0.7.x` branch 👍🏻

**Comment by Akshit42-hue** [comment]
@eldadfux  @Glide7  Can i work on this issue

**Comment by Glide7** [comment]
Hey @Akshit42-hue - it's currently being worked on by @kodumbeats . we'll let you know if something changes! thanks for helping!

**Comment by Akshit42-hue** [comment]
@Glide7 ok

**Comment by kodumbeats** [comment]
Should we leave this issue open for potential style changes? Or is #791 sufficient to close?

**Comment by Glide7** [comment]
@eldadfux What do you think?

**Comment by eldadfux** [comment]
@kodumbeats awesome work, this feature is now available on Appwrite 0.7 🚀
