### ISSUE TITLE
🐛 Bug Report: 500 internal error when clicking on a database collection in Appwrite Web ui

### ISSUE THREAD

**Issue by trashcoder** [appwrite/appwrite#5354]
### 👟 Reproduction steps

I just upgraded from 1.2 to Appwrite 1.3. 

- Open the appwrite web ui
- Click on databases 
- click on a random collection -> 500 internal error appears

Downgrading back to 1.2 and clicking on a database collection works.

### 👍 Expected behavior

It should show the collection's documents.

### 👎 Actual Behavior

It shows a 500 internal error.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Appwrite in a docker environment in a Alpine Linux Proxmox Container

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Maxbrt18** [comment]
Same problem for me using the 1.3 version.

**Comment by trashcoder** [comment]
Ah, ok. I didn't run the migration command.

After the migration and clearing the browser cache appwrite shows the documents.

**Comment by trashcoder** [comment]
Sorry, error still appears.

**Comment by Maxbrt18** [comment]
I was just wondering why it worked for you and not for me

**Comment by Musta-Pollo** [comment]
I need to open the link twice to it to appear.

**Comment by ftp27** [comment]
Some appwrite container logs to clarify the error

```[Error] Timestamp: 2023-04-12T12:00:18+00:00
[Error] Method: GET
[Error] URL: /v1/teams/:teamId/prefs
[Error] Type: TypeError
[Error] Message: Utopia\Database\Document::__construct(): Argument #1 ($input) must be of type array, stdClass given, called in /usr/src/code/app/controllers/api/teams.php on line 228
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Document.php
[Error] Line: 29```

**Comment by trashcoder** [comment]
I get the same error messages as @ftp27.

**Comment by maperz** [comment]
Hello everyone!
Congrats on the version update! We just installed `v1.3.0`  are also experiencing this issue in the appwrite web console.
Refreshing the page works and leads to the correct collection page.

**Comment by squallsama** [comment]
Same for me. Refresh helps, but when you go back to page - errors appears again.

**Comment by hortigado** [comment]
> I'm on v1.3, do I need to run migration for v1.3.1?

Yes

**Comment by gepd** [comment]
Migrations are only necessary with mayor versions, you shouldn't need to run migrations again, I didn't run it and I have all working as expected in v1.3.1

**Comment by amazingnerd** [comment]
Appwrite Cloud has this error too, kinda weird, I'm considering use other way for authenticating.

<img width="603" alt="image" src="https://github.com/appwrite/appwrite/assets/87475722/a1a22b6e-cd4c-40be-b4b9-7de6c6a9b7cf">

**Comment by Depender-Sethi** [comment]
> Appwrite Cloud has this error too, kinda weird, I'm considering use other way for authenticating.
> 
> <img alt="image" width="603" src="https://user-images.githubusercontent.com/87475722/276843828-a1a22b6e-cd4c-40be-b4b9-7de6c6a9b7cf.png">

Solved it by clearing the site's data and signing in afresh. Give it a shot.

**Comment by Depender-Sethi** [comment]
> Appwrite Cloud has this error too, kinda weird, I'm considering use other way for authenticating.
> 
> <img alt="image" width="603" src="https://user-images.githubusercontent.com/87475722/276843828-a1a22b6e-cd4c-40be-b4b9-7de6c6a9b7cf.png">

After a couple of hours troubleshooting, I fixed it by creating a new project in a fresh organization, clearing the cache, and signing in again. Give it a try
