### ISSUE TITLE
documentaion : wrong links in getting started for web

### ISSUE THREAD

**Issue by Atsurak** [appwrite/appwrite#5359]
bringing this up again [ref](https://github.com/appwrite/sdk-for-web/pull/48) 

https://github.com/appwrite/appwrite/blob/e5fa4883b2a8b7233998dda8e9fe40c385855e8a/docs/sdks/web/GETTING_STARTED.md?plain=1#L60

https://github.com/appwrite/appwrite/blob/e5fa4883b2a8b7233998dda8e9fe40c385855e8a/docs/sdks/web/GETTING_STARTED.md?plain=1#L63

**Comment by stnguyen90** [comment]
Thanks for raising this! 🙏🏼
