### ISSUE TITLE
🐛 Bug Report: `teams.create` crash using swift sdk

### ISSUE THREAD

**Issue by jeremybenabu** [appwrite/appwrite#5365]
### 👟 Reproduction steps

When I use `teams.create` using the swift sdk on client side.

### 👍 Expected behavior

The function success without crash

### 👎 Actual Behavior

Since release 2.0.0 this call crash.
It seems that `prefs` is returned as empty array and the swift sdk is expecting a dictionary.

Network call:
<img width="962" alt="Capture d’écran 2023-04-12 à 21 27 16" src="https://user-images.githubusercontent.com/123162133/231676749-e68e43ca-99a4-4643-b403-68fd0820b267.png">

Crash thread
<img width="1154" alt="Capture d’écran 2023-04-12 à 18 42 53" src="https://user-images.githubusercontent.com/123162133/231676757-f64f514d-0fcd-4b00-91b0-78f7495a689f.png">

Logs
```
Could not cast value of type '__NSArray0' (0x7fd1f98ce158) to 'NSDictionary' (0x7ff863f59f00).
2023-04-12 20:42:54.790689+0200 babybottle[92246:22609523] Could not cast value of type '__NSArray0' (0x7fd1f98ce158) to 'NSDictionary' (0x7ff863f59f00).
Could not cast value of type '__NSArray0' (0x7fd1f98ce158) to 'NSDictionary' (0x7ff863f59f00).
CoreSimulator 857.14 - Device: iPhone 14 Pro Max (3ADF35A1-3B88-4DA6-A4BF-830833E2194F) - Runtime: iOS 16.2 (20C52) - DeviceType: iPhone 14 Pro Max
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite server 1.3.1 and swift sdk 2.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@jeremybenabu, thanks for creating this issue! 🙏 This should be fixed in our next patch release!

**Comment by jeremybenabu** [comment]
Hey @stnguyen90 any date on when 1.3.2 will be released? This bug is blocking my projects release
