### ISSUE TITLE
🐛 Bug Report: Scroll issue with Console in Mobile Browser after `1.3.0` 

### ISSUE THREAD

**Issue by Vedsaga** [appwrite/appwrite#5369]
### 👟 Reproduction steps

1. Deploy `1.3.1` Appwrite version. 
2. Create Project, DB, Collections & Documents
3. Open the Console Endpoint in any Mobile Browser ( Chrome, Firebase, Safari, Brave, Edge etc...)
4. Login in the console
5. Select any project

### 👍 Expected behavior

Scrolling, Navigation & Pinch Zooming in & out  should work normally.

### 👎 Actual Behavior

Scrolling, Navigation & Pinch Zooming in & out is not work normally.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use AWS EC2 instance.

https://user-images.githubusercontent.com/59083528/231830508-07206ee5-925e-4475-afdc-1593622df0c7.mp4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Vedsaga, thanks for raising this issue! 🙏🏼 We'll look into this soon!

**Comment by stnguyen90** [comment]
This was fixed in 1.3.3.
