### ISSUE TITLE
API key update error

### ISSUE THREAD

**Issue by danilo73r** [appwrite/appwrite#5370]
I have created an API key with expiration date = never.

After, I want to update the scopes or name, when I click update an error appear:
Invalid expire date: Date is not valid

**Comment by stnguyen90** [comment]
@daniaremon thanks for raising this! 🙏 Would you please clarify what version of Appwrite you're on?

**Comment by daniaremon** [comment]
Yeah, I'm using the last version 1.3.1

**Comment by stnguyen90** [comment]
Thanks for clarifying! It looks like the Console is sending an empty string for `expire`:

```json
{
    "name": "asdf",
    "scopes": [
        "users.read",
        "users.write",
        "teams.read",
        "teams.write"
    ],
    "expire": ""
}
```

which the API does not support. We probably need to make sure to leave it out of the payload when updating scopes or name

**Comment by danilo73r** [comment]
Yes it would be a good approach
