### ISSUE TITLE
🐛 Bug Report: No Data After Upgrading

### ISSUE THREAD

**Issue by highlife22** [appwrite/appwrite#5373]
### 👟 Reproduction steps

Hello,

I upgrade from appwrite 1.2.1 to 1.3.1, following the step in https://appwrite.io/docs/upgrade and the logic of https://github.com/appwrite/appwrite/issues/850 for more clear step by step.

So in the folder of appwrite on my server:

1. I shutdown the Appwrite instance

2.  I run 
`docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.3.1`

3. I answer at the question for the port and domain, it take my old config so all good for this.
4. I do : `docker compose exec appwrite migrate`
5. It fail first because too soon mariadb was not running, i wait and retry and all finish.
6. I go to my login page of appwrite console ... and i can't log-in
7. I try to reset my password but can't send mail, because no SMTP config (in my .env of 1.2.1 i have setup my SMTP config)
8. I redo my .env 
9.  I launch `docker compose up --force-recreate -d` to apply my new .env config
10. I try reseting my password again, but it fail because not found user.
11. I recreate my user like for the first time.

It's a almost fresh appwrite instance so i don't lost much data and i'm pretty new in using appwrite, **i probably made a mistake in the migration process**.

### 👍 Expected behavior

The migration process don't wipe my data

### 👎 Actual Behavior

The migration process wipe my data or i don't have acces anymore

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Archlinux kernel 6.1.8
Docker 20.10.23
Appwrite 1.2.1 to Appwrite 1.3.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@highlife22 Thanks for opening this issue! 🙏🏼 Did you run the install/upgrade command *inside* your appwrite folder? If so, that might have been the problem. The command needs to be run in the folder above appwrite:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1477010/232099325-3f8f745d-2049-4ad1-b1a0-58c0708583a6.png">

**Comment by highlife22** [comment]
I did run in the appwrite diretory .... not in the parent directory
So i made a mistake.
Thank you for your time !

Best regard
