### ISSUE TITLE
🚀 Feature: Make MAINTENANCE_INTERVAL and env variable

### ISSUE THREAD

**Issue by danilo73r** [appwrite/appwrite#5378]
### 🔖 Feature description

Allow MAINTENANCE_INTERVAL to be an environment variable to get more control and customization over the container execution. Considering a min  value to avoid overload errors (maybe 15 min as min) and a max value to avoid let the server without maintenance for a long time (maybe 1 day as max).

### 🎤 Pitch

I understand that 1 function will have 1 runtime container.

This will allow to have better control over the number of idle containers and server resources. Specially if I have a lot of functions, maybe 20% will be frequently functions, the other not. So it will be helpful to avoid having 80% of containers in an idle state by an hour (MAINTENANCE_INTERVAL = 3600) in the worst case. 

The other case if 80% or more functions are frequently used, maybe run maintenance will be better each 8 hours or more.
 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi - thank you for raising this.

We do have a timeout env for functions: https://appwrite.io/docs/environment-variables#functions

This supposedly could be useful. Let me have a chat about this with my team and get back!

**Comment by stnguyen90** [comment]
`_APP_FUNCTIONS_MAINTENANCE_INTERVAL` has now been added. See https://appwrite.io/docs/advanced/self-hosting/environment-variables#functions.
