### ISSUE TITLE
[Feature Request] Delete user option in console

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#538]
Since #378 is waiting for release, we can add an option to the console.

My suggestion would be, to have an account to be blocked, as a requirement.
So, that accidents are less likely to happen.

**Comment by eldadfux** [comment]
Would it help if we just add a confirmation dialog before deleting the user?

**Comment by TorstenDittmann** [comment]
Sure, I still think that it is dangerous 👍 

Having the button only appear when a user is blocked would add more steps. But maybe it is only my paranoia speaking there 😉

**Comment by eldadfux** [comment]
My concern about this, is that it might not be very clear that the option is available in case the button is completly hidden or how to enable it in case its just disabled.

**Comment by eldadfux** [comment]
Maybe we can imitate the project deletion UI instead of having both button one above the other (block & delete buttons):
![image](https://user-images.githubusercontent.com/1297371/93360455-5b3abb00-f84c-11ea-9d8e-1589d3d251c1.png)

**Comment by TorstenDittmann** [comment]
> Maybe we can imitate the project deletion UI instead of having both button one above the other (block & delete buttons):
> ![image](https://user-images.githubusercontent.com/1297371/93360455-5b3abb00-f84c-11ea-9d8e-1589d3d251c1.png)

This is perfect I guess! I agree 100% 👍

**Comment by PineappleIOnic** [comment]
I could create the frontend implementation for this once the backend and the SDK is ready for this to be implemented, shouldn't be that hard 👍

**Comment by eldadfux** [comment]
@PineappleIOnic That will be great 👌🏻

Let me work on this during the weekend, and i'll update here when its ready for you to follow up. I think I only need to make sure the console SDK has the new delete method using the SDK generator.

**Comment by eldadfux** [comment]
@PineappleIOnic I have added the user deletion method to the console SDK:
https://github.com/appwrite/appwrite/commit/626d0d7281cdf0c5617d972618c571b31a42fc74

You can now implement the UI functionality in the user management page just as it work in the project settings page.
Please work against 0.7.x branch, and add some screenshot in the PR.

**Comment by eldadfux** [comment]
All changes by @PineappleIOnic has been merged to branch `0.7.x` 🥳

**Comment by eldadfux** [comment]
v0.7 is finally out with all the updates available 🥳
