### ISSUE TITLE
🐛 Bug Report: Github auth not working

### ISSUE THREAD

**Issue by codingmickey** [appwrite/appwrite#5388]
### 👟 Reproduction steps

1. I deployed the appwrite docker image on githpod.io
2. I am using github codespaces for the development of the website
3. I've configured everything properly like the redirect URLs in the Github App is matching with the one given in the appwrite github auth
4. The success and failure URLs are also set properly

### 👍 Expected behavior

Should've at least shown the Github login page ui, here I think there is a problem with the Appwrite connection but I can't figure out how

### 👎 Actual Behavior

![Capture](https://user-images.githubusercontent.com/42518907/232400483-b151d324-8799-41fc-90cb-7bd282253273.PNG)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

- I used gitpod to deploy Appwrite docker image
- I'm using the web-sdk in appwrite
-     "appwrite": "^11.0.0",
- I'm using next.js in the frontend

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@codingmickey, thanks for raising this issue! 🙏🏼 Would you please provide the full URL when you get to this page? There might be something in the URL that indicates what went wrong.

**Comment by codingmickey** [comment]
https://8080-appwrite-integrationfor-ft726yi2ow1.ws-us94.gitpod.io/v1/account/sessions/oauth2/callback/github/643cd8907ad228d9e2af?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=%7B%22success%22%3A%22https%3A%5C%2F%5C%2Fcodingmickey-laughing-robot-7p9vxq6vg9w2ww7v-3000.preview.app.github.dev%5C%2Fwelcome%22%2C%22failure%22%3A%22https%3A%5C%2F%5C%2Fcodingmickey-laughing-robot-7p9vxq6vg9w2ww7v-3000.preview.app.github.dev%5C%2F%22%7D

Here it is

**Comment by codingmickey** [comment]
![image](https://user-images.githubusercontent.com/42518907/232558284-0b4d42df-aad1-4b74-b8cb-1544c3c50590.png)
Like mentioned in the URL there is a URL mismatch in the redirect URL, but I've put the exact URL from the appwrite console of github int the Github app (double checked it)

**Comment by codingmickey** [comment]
update: also not working locally :( same error I feel it's the appwrite server that I'm running on gitpod

**Comment by daniromome** [comment]
I have this same issue while using discord as oauth2 provider

**Comment by stnguyen90** [comment]
> ![image](https://user-images.githubusercontent.com/42518907/232558284-0b4d42df-aad1-4b74-b8cb-1544c3c50590.png) Like mentioned in the URL there is a URL mismatch in the redirect URL, but I've put the exact URL from the appwrite console of github int the Github app (double checked it)

Thanks for providing this! Would you please share the URL that is sent to github? You should be able to get this by enabling and preserving the network logs and checking for the 1st request that is sent to github. 

Would you please also share the redirect uri that you put into github?

**Comment by codingmickey** [comment]
### 1st request sent to Github:
```
Request URL: https://8080-appwrite-integrationfor-ft726yi2ow1.ws-us95.gitpod.io/v1/account/sessions/oauth2/github?success=https%3A%2F%2Fcodingmickey-laughing-robot-7p9vxq6vg9w2ww7v-3000.preview.app.github.dev%2Fwelcome&failure=https%3A%2F%2Fcodingmickey-laughing-robot-7p9vxq6vg9w2ww7v-3000.preview.app.github.dev%2F&project=643cd8907ad228d9e2af
Request Method: GET
Status Code: 302  (from service worker)
Referrer Policy: strict-origin-when-cross-origin
```

### Redirect URL in github app
```
https://8080-appwrite-integrationfor-ft726yi2ow1.ws-us95.gitpod.io/v1/account/sessions/oauth2/callback/github/643cd8907ad228d9e2af
```

**Comment by stnguyen90** [comment]
> ### 1st request sent to Github:
> ```
> Request URL: https://8080-appwrite-integrationfor-ft726yi2ow1.ws-us95.gitpod.io/v1/account/sessions/oauth2/github?success=https%3A%2F%2Fcodingmickey-laughing-robot-7p9vxq6vg9w2ww7v-3000.preview.app.github.dev%2Fwelcome&failure=https%3A%2F%2Fcodingmickey-laughing-robot-7p9vxq6vg9w2ww7v-3000.preview.app.github.dev%2F&project=643cd8907ad228d9e2af
> Request Method: GET
> Status Code: 302  (from service worker)
> Referrer Policy: strict-origin-when-cross-origin
> ```

@codingmickey, this isn't actually the first request sent to GitHub. This was sent to gitpod. The next request should be the one that goes to GitHub.

**Comment by Haimantika** [comment]
> > ### 1st request sent to Github:
> > ```
> > Request URL: https://8080-appwrite-integrationfor-ft726yi2ow1.ws-us95.gitpod.io/v1/account/sessions/oauth2/github?success=https%3A%2F%2Fcodingmickey-laughing-robot-7p9vxq6vg9w2ww7v-3000.preview.app.github.dev%2Fwelcome&failure=https%3A%2F%2Fcodingmickey-laughing-robot-7p9vxq6vg9w2ww7v-3000.preview.app.github.dev%2F&project=643cd8907ad228d9e2af
> > Request Method: GET
> > Status Code: 302  (from service worker)
> > Referrer Policy: strict-origin-when-cross-origin
> > ```
> 
> @codingmickey, this isn't actually the first request sent to GitHub. This was sent to gitpod. The next request should be the one that goes to GitHub.

Hi @codingmickey , did this solve your issue?

**Comment by codingmickey** [comment]
Hi @Haimantika Sorry I'm not using this now.. for the personal project that I was building .. switched to nextjs and made my own API 😢
