### ISSUE TITLE
🐛 Bug Report: Incorrect handling of content-range header

### ISSUE THREAD

**Issue by Suven-p** [appwrite/appwrite#5392]
### 👟 Reproduction steps

Try uploading a file to appwrite storage using "Create File" endpoint whose size is not a multiple of chunk size. For example create a file of size `10*1024*1024` bytes then add 5 more bytes and use a chunk size of `5*1024*1024` bytes.

### 👍 Expected behavior

Handle requests where range-end value is one less than total length. I am not asking for requests with range-end = total length to be considered invalid since it may break stuff but the current implementation rejects correct value while handling incorrect value.

### 👎 Actual Behavior

Appwrite requires the range-end parameter of content-range to be equal to total size of file.

```
5*1024*1024=5242880
10*1024*1024=10485760
```
Scenario 1:
Uploading 10MiB file with a chunk size of 5MiB.
The headers for 2 requests:
content-range: bytes 0-5242879/10485765
content-range: bytes 5242880-10485759/10485760
This works as intended.

Scenario 2:
Replacing the second range of Scenario 1 with `5242880-10485760/10485760` also works although it is an invalid range

Scenario 3:
Add 5 more characters so that a third chunk is required. The ranges would be:

content-range: bytes 0-5242879/10485765
content-range: bytes 5242880-10485759/10485765
content-range: bytes 10485760-10485764/10485765

This returns status code of 500 and server log of:
Warning: file_get_contents(/storage/uploads/app-testsdk/testBucket/tmp_berrwrwerfgd.txt/berrwrwerfgd.part.3): Failed to open stream: No such file or directory in /usr/src/code/vendor/utopia-php/storage/src/Storage/Device/Local.php on line 124
[Error] Timestamp: 2023-04-17T18:28:26+00:00
[Error] Method: POST
[Error] URL: /v1/storage/buckets/:bucketId/files
[Error] Type: Exception
[Error] Message: Failed to read chunk /storage/uploads/app-testsdk/testBucket/tmp_berrwrwerfgd.txt/berrwrwerfgd.part.3
[Error] File: /usr/src/code/vendor/utopia-php/storage/src/Storage/Device/Local.php
[Error] Line: 126

Opening a shell to docker container and looking at `/storage/uploads/app-testsdk/testBucket/tmp_berrwrwerfgd.txt//berrwrwerfgd.txt_chunks.log`:
1
2
2097153

Trying scenario 3 with cloud version of appwrite (1.1.2) works fine.
Appwrite console works fine and uses Scenario 2 for both versions.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.3.1 locally and on oracle server
Appwrite Cloud

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Suven-p** [comment]
Expanding more on scenario 2:
This seems to be wrong because:
1. According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range
> Content-Range: `<unit> <range-start>-<range-end>/<size>`
> `<range-end>`:  An integer in the given unit indicating the end position (zero-indexed & inclusive) of the requested range.  

Range end should be inclusive.

2. According to https://httpwg.org/specs/rfc9110.html#field.content-range
> A Content-Range field value is invalid if it contains a range-resp that has a last-pos value less than its first-pos value, or a complete-length value less than or equal to its last-pos value. The recipient of an invalid Content-Range MUST NOT attempt to recombine the received content with a stored representation.
range-end must be less than complete-length

**Comment by Suven-p** [comment]
The chunk number in chunk log (`/storage/uploads/app-testsdk/testBucket/tmp_berrwrwerfgd.txt//berrwrwerfgd.txt_chunks.log` of scenario 3) changes with number of additional characters added to the file and remains consistent between local installation and remote installation.

**Comment by stnguyen90** [comment]
@Suven-p thanks for creating this isssue! 🙏🏼 We'll look into this soon!

**Comment by lohanidamodar** [comment]
@Suven-p Thank you for reporting. As a matter of fact, I'm currently working to fix the issue and will have an update soon.
