### ISSUE TITLE
🚀 Feature: Attributes Organization (UX)

### ISSUE THREAD

**Issue by nev-21** [appwrite/appwrite#5396]
### 🔖 Feature description

In the console frontend, allow to organize attributes in custom order or grouping.  

### 🎤 Pitch

This allow the developers to have better undestanding of the table fields. Some fields have a strength relation with others (cohesion) and it is useful to visualize them together.

Example:
vendor_id <----- better together
product_id
qty
price
...
tags
vendor_discount <----- better together

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by nev-21** [comment]
Maybe it would be useful for many lists in appwrite console (like databases, teams)

**Comment by stnguyen90** [comment]
@nev-21, thanks for creating this issue! 🙏🏼 Is this a duplicate of https://github.com/appwrite/appwrite/issues/2787? If so, would you please 👍🏼 the other issue and close this as a duplicate?

**Comment by nev-21** [comment]
yes it is the same issue, thanks
