### ISSUE TITLE
Appwrite CLI

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#540]
Appwrite CLI should include all standard backend SDKs functionality and allow Appwriters to interact with the Appwrite HTTP API directly from their terminals.

The CLI should rely on common Appwrite CLI FW for consistency and easy maintenance. We should package the CLI as a Docker image for ease of use across different platforms or operating systems.

General file structure:
* Dockerfile
* composer.json
* app/
  * client.php
  * services/
    * users.php
    * storage.php
    * ...

For stage A, we can skip any input validation in the CLI layer and rely on the HTTP validations and status codes. All user input for the HTTP client settings (API Keys, Project ID, Endpoint URL) should be saved locally on the container for persistency.

Usage Examples:
```bash
docker run appwrite/cli:1.0.0 client setProject --value=5e63e0a61d9c2
```

```bash
docker run appwrite/cli:1.0.0 users createUser --email=test@appwrite.io --password=secret --name=Demo User
```

**References**:
PHP-SDK: https://github.com/appwrite/sdk-for-php/blob/master/src/Appwrite/Client.php
Node-SDK: https://github.com/appwrite/sdk-for-node
Utopia CLI: https://github.com/utopia-php/cli

**Steps / Progress**

- [x] Working prototype
- [x] Response Parsing
- [x] Dockerizing
- [x] Convert to SDK-Generator templates
- [x] Handle file uploads (+code package gzip)
- [x] Handle images in response type
- [x] Usage example docs
- [x] Publish on Docker Hub (appwrite/cli)

**Comment by TorstenDittmann** [comment]
@eldadfux I think this needs an update now 😉

**Comment by eldadfux** [comment]
The Appwrite CLI is out and available! Learn more here: https://appwrite.io/docs/command-line
