### ISSUE TITLE
🐛 Bug Report: Document ID is cut off on console after creation

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#5406]
### 👟 Reproduction steps

This is not something major but the differences are quite noticeable.

1. When you create a document from console, 
the Document ID in the first column is cut-off after some characters which is quite visible.

3. The behaviour is quite different when you refresh the page containing the document,
the format is now `{initialChacters}...{endCharacters}`.

### 👍 Expected behavior

Either use `{initialChacters}...{endCharacters}` format or use `{initialChacters}...` consistently across both states i.e after creation and a refresh.

### 👎 Actual Behavior

Different format after document creation & after a page refresh.

See attached screenshots.
1. After creating the document.
<img width="500" alt="Screenshot 2023-04-19 at 8 59 02 PM" src="https://user-images.githubusercontent.com/20625965/233126904-f0a7d37e-84ab-464b-bbbb-dab8edc978de.png">

2. After refreshing the page.
<img width="500" alt="Screenshot 2023-04-19 at 8 59 12 PM" src="https://user-images.githubusercontent.com/20625965/233126931-07749a79-9839-4319-9632-227180b6da0e.png">

3. Adding a new document to show the differences.
<img width="500" alt="Screenshot 2023-04-19 at 9 02 20 PM" src="https://user-images.githubusercontent.com/20625965/233126945-4bc27b23-a7b7-4724-b74e-6bf5635cba85.png">

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Localhost.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by yatharth1706** [comment]
Would love to work on this issue

**Comment by stnguyen90** [comment]
@yatharth1706, assigned! Thanks for your interest!
