### ISSUE TITLE
🐛 Bug Report: Console UI Issues on Safari [Function]

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#5407]
### 👟 Reproduction steps

Safari Version: `16.4 (18615.1.26.11.22)`

The Console UI is pretty much broken here and there on the dashboard.
I've added the ones I found in the Functions part of the dashboard.

Please the screenshots below for more info:

**Onscreen form dialogs**
<br/>
<img width="500" height="180" alt="Event_creation_for_Functions" src="https://user-images.githubusercontent.com/20625965/233135324-ffbfab44-e354-455b-a465-57e05ff60c84.png">
<br/>
<img width="500" height="180" alt="Permission_dialog_in_Functions" src="https://user-images.githubusercontent.com/20625965/233135296-1c3fb653-c074-4c5d-971e-d1e0699e4acf.png">
<br/>
<img width="500" height="180" alt="Variable_creation_for_Functions" src="https://user-images.githubusercontent.com/20625965/233135017-0fbf0a1b-c184-47cd-85d6-a2188851e213.png">
<br/>

**Buttons**

<img width="125" height="75" alt="Button CutOff 1" src="https://user-images.githubusercontent.com/20625965/233135231-a31d9e74-6cf7-4651-8762-88a459ea180e.png"> <img width="125" height="75"  alt="Button CutOff 2" src="https://user-images.githubusercontent.com/20625965/233135202-15aae51d-8201-4e7c-8205-1d64726cd7fe.png"> <img width="125" height="75" alt="Button CutOff 3" src="https://user-images.githubusercontent.com/20625965/233135155-d1b22b81-a910-4b34-bf91-3c7ad34ff88c.png">

As shared on [Discord](https://discord.com/channels/564160730845151244/564160731327758347/1098274956074307655).

### 👍 Expected behavior

Forms should be full-screen, buttons shouldn't have some border-cutting overlay/line on them.

### 👎 Actual Behavior

See above attached screenshots.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Localhost.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Another observation is that this happens on mobile & is not limited to safari.
Tested on Chrome, DuckDuckGo & the same thing happens.

Chrome: `112.0.5615.70`
DuckDuckGo: `7.72.11.0`
Safari: `Well, whatever shipped with 16.3`.

**Comment by joeyouss** [comment]
Thank you for raising this issue. Have conveyed this to my team.

**Comment by joeyouss** [comment]
Hi @ItzNotABug , wanted to leave an update: our team has put this in backlog to work on in future. Thanks!

**Comment by EVDOG4LIFE** [comment]
@ItzNotABug - given that this is a pretty old issue and we are a few versions ahead - can you verify if this is still a valid request?

**Comment by ItzNotABug** [comment]
@EVDOG4LIFE The flow for function creation has changed. Hence these seem fixed because these modals don't really show up and are configurable in settings now.
