### ISSUE TITLE
🐛 Bug Report: Cannot able to create attribute on Project->Database->Collections [AFTER Upgrade 1.2 TO 1.3.1]

### ISSUE THREAD

**Issue by D-Raj-Grg** [appwrite/appwrite#5409]
### 👟 Reproduction steps

**Be on the old version like I was on 1.2**
1. Have Project -> Database -> Collection -> Attribute -> Documents
2. Upgrade your appwrite version to 1.3.1 latest, Follow https://appwrite.io/docs/upgrade guide.
3. After successfully upgrade, go to same Project->Database -> Collection -> 
4. Try to create new attributes like String, Relation, integer
5. You will get a Server Error

**But it will work if you create new Project**

### 👍 Expected behavior

It should create the attribute.

### 👎 Actual Behavior

It throws a Server error. Check Screenshot  [https://prnt.sc/h7TP8QTMkfGx](https://prnt.sc/h7TP8QTMkfGx)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Digital Ocean Droplet

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by AriDevC** [comment]
Please run this in the directory where your appwrite's docker-compose.yaml file is located 
```docker compose exec appwrite migrate```
For more details https://appwrite.io/docs/upgrade
