### ISSUE TITLE
#PREPTEMBER - Getting Ready for Hacktoberfest

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#541]
Some stuff we need TODO to make sure all of [Appwrite repos](https://github.com/appwrite) are ready for new code contributors.

- [x] Review Appwrite contributors guide and check for potential improvements. (@ronfybish)
- [x] Add `Submit a Pull Request` section to the contribution guide (just after `How to Start?` section) (@ronfybish)
- [x] Make sure to add **simple** naming convention for branches and PR titles (@ronfybish)
- [x] Add links to resources that can help first time contributors (@ronfybish)
- [x] Label all relevant issues with the `hacktoberfest`, `good first issue`, and `help wanted` labels (@eldadfux)
- [x] Add blog post about Appwrite swag liability on the Appwrite blog (@eldadfux)
- [ ] Open new issues for future versions (@eldadfux)
- [x] Open issues that can be a good fit for the `good first issue` label. (@eldadfux)
- [x] List Appwrite on different Hacktoberfest resources and awesome lists
- [x] Schedule a global contribution meetup on Hangouts / Zoom?

Please feel free to add any other ideas and help make this Hacktoberfest at least as awesome as it was last year.

**Comment by brainless** [comment]
Hi Eldad, thanks for this effort. Like I mentioned in DEV, I want to look into the Docker images migration to Alpine. I will look around the project first, trying it out etc. Then take the tickets that I can tackle.

**Comment by eldadfux** [comment]
@brainless, take a look at our repos that are prefixed with `docker-*`. One member has already been assigned to work on our docker-telegraf image, but I can assign you to any of the other repos.

**Comment by eldadfux** [comment]
The CONTRIBUTING doc has been updated by @ronfybish with the new `Submit a Pull Request` section and new naming conventions for branches and PRs.

**Comment by ronfybish** [comment]
@eldadfux Thank you very much appreciate it! 
Continues to work hard in preparations for the Hacktoberfest 🎯 👩‍🔧

**Comment by ashawe** [comment]
Please add "assigned" label to issues that have been assigned for easier sorting of issues

**Comment by eldadfux** [comment]
@ashawe thanks for the heads up. Actually this issue can be closed now. I will try to add more open issues as we progress with Hacktoberfest.
