### ISSUE TITLE
🚀 Feature: More compact (database) table lists inside UI

### ISSUE THREAD

**Issue by mbos2** [appwrite/appwrite#5410]
### 🔖 Feature description

Documents list inside the collection seems a bit large. 
Even on large screens scrolling is required to scroll 1-2 items to get to the next button.
It looks really big.

![image](https://user-images.githubusercontent.com/56090587/233163904-a7ecc5dc-ed2d-4678-aa20-9d4410a77de3.png)

Number of total result is hidden on the bottom, which i don't find as appropriate place to put imporant piece of information.

---

**Same thing goes for all other tables in the appwrite console as they all use the same styles**

### 🎤 Pitch

By turning off this CSS property called block-size on the table-col class, we get more compact table.
![image](https://user-images.githubusercontent.com/56090587/233164387-93224c7d-ee16-4b2f-85ba-58150cd25b93.png)

![image](https://user-images.githubusercontent.com/56090587/233164478-808e4aca-d390-4d10-b2d7-a65bd44590a6.png)
That way I can imidiatelly see total results. 
Even more compact than this would be nice. 
**More data we can instantly see, the better**

Also, UX wise, might be good to put total results on top, above the table. Since it is important piece of information, no reason to hide it on the bottom. 

Display-per-page number would also be helpful since there's a pagination in place.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by fliitor** [comment]
It's more about "Override console css" so

**Comment by mbos2** [comment]
No, it's about what I wrote. 
I added the CSS part just so I can show the example.

**Comment by eldadfux** [comment]
Closing this issue for now as this is referring the old console. We've since released v2 of the console which is a complete rewrite/redesign. If this is still relevant please open a new issues on https://github.com/appwrite/console
