### ISSUE TITLE
🐛 Bug Report: Using falsy values for optional parameters

### ISSUE THREAD

**Issue by Suven-p** [appwrite/appwrite#5416]
### 👟 Reproduction steps

When I make a request to
`path := r.Replace("/databases/{databaseId}/collections/{collectionId}/attributes/string")`
with parameters
```
params := map[string]interface{}{
        "key": Key,
        "size": Size,
        "required": Required,
        "default": Default,
        "array": Array,
}
```
and value of default is an empty string.

### 👍 Expected behavior

Handle empty strings as parameter not being sent.
https://discord.com/channels/564160730845151244/1099033836731519006

### 👎 Actual Behavior

It throws an error in appwrite 1.3.1 but not in older versions of appwrite.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Suven-p, thanks for creating this issue! 🙏🏼 It makes perfect sense to allow an empty string as the default. I'll bring this up to the team to see how we can proceed.

**Comment by joeyouss** [comment]
This has been fixed here: https://github.com/appwrite/appwrite/pull/5602

Thank you again for bringing this up @Suven-p , we have implemented it.
