### ISSUE TITLE
🐛 Bug Report: Optional OAuth Setting isn't Optional

### ISSUE THREAD

**Issue by lancetipton** [appwrite/appwrite#5421]
### 👟 Reproduction steps

I'm currently using the cloud beta version. I was trying to setup gitlab auth within the dashboard @ `Auth -> settings -> Gitlab` 
Within the modal where I need to add my Gitlab OAuth settings, there's a input field labeled **Endpoint (optional)**.
When I entered the information into the required fields, I could not click the `update` button.

Even though the **Endpoint** says it is optional, I had to fill it out with a url before I could click the update button.

Basically, the field is **not** _'optional'_ even though it says that it is.

![auth-gitlab](https://user-images.githubusercontent.com/8345382/233798803-74a1692b-efda-4cc2-837f-0f01aa0d4884.png)

### 👍 Expected behavior

I should be able to click the `Update` button, without having to fill in the optional form fields.

### 👎 Actual Behavior

I had to fill in the optional form fields before I could hit the `Update` button

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Something else

### 🧱 Your Environment

I'm using the cloud platform currently in beta. It says the version is 1.1.2, but that's all I know.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by yatharth1706** [comment]
@stnguyen90 , can i pick this one ?

**Comment by stnguyen90** [comment]
@yatharth1706, assigned! Thanks for your interest! 🙏🏼

**Comment by stnguyen90** [comment]
Looks like https://github.com/appwrite/console/pull/418 has been merged, so this will be in the next release.
