### ISSUE TITLE
🐛 Bug Report: Function execution failed.

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#5423]
### 👟 Reproduction steps
On localhost this is running fine but not on ec2 instance.

Executions Logs
```
An internal curl error has occurred within the executor! Error Msg: Operation timed out
```

Appwrite-executor Logs
```
Executing Runtime: 6359c5064e8969d821a8-6446621b0787a4b581b4
Function executed in 0.38529300689697 seconds, status: failed
Executing Runtime: 6359c5064e8969d821a8-6446621b0787a4b581b4
[Error] Type: Exception
[Error] Message: An internal curl error has occurred within the executor! Error Msg: Operation timed out
[Error] File: /usr/src/code/app/executor.php
[Error] Line: 544
Executing Runtime: 6359c5064e8969d821a8-6446621b0787a4b581b4
Function executed in 120.00923085213 seconds, status: failed
```
Code
```js
const nodemailer = require('nodemailer');

module.exports = async function (req, res) {
  const transporter = nodemailer.createTransport({
    host: req.variables.HOST,
    port: req.variables.PORT,
    secure: req.variables.SECURE,
    auth: {
      user: req.variables.USER,
      pass: req.variables.PASS,
    },
  });

  const payload = JSON.parse(req.payload);
  const name = payload['name'];
  const email = payload['email'];
  const subject = payload['subject'];
  const text = payload['text'];

  const info = await transporter.sendMail({
    from: `"Sender" <${req.variables.USER}>,`,
    to: `"${name}" <${email}>,`,
    subject: subject,
    text: text,
  });

  res.json({
    message: 'Email sent successfully',
    emailId: info.messageId,
  });
};
```

### 👍 Expected behavior

Function execution should be fine.

### 👎 Actual Behavior

Function execution failed.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
> I wrap my code with try/catch and increase the timeout as well still getting the same error.

@usamashafiqs, what is the new code and how long does the execution run for before erroring out?

**Comment by stnguyen90** [comment]
@usamashafiqs this could be a true timeout and because it times out, Appwrite isn't able to capture the logs. Would you please increase the timeout? In addition, instead of calling `res.send(e)`, would you please change it to `res.send(e.toString()`?

**Comment by Hu-Wentao** [comment]
see #4594 , try return `res.send()` with  `4xx` code, not `5xx`

**Comment by 50l3r** [comment]
I have the same problem with a function who execute node-fetch call.

I avoid exceptions and use res.json but problem persists.

**Comment by 50l3r** [comment]
Oh my god, after searching a lot in the documentation and github I have seen that each function has a time limit that is specified in its configuration: https://appwrite.io/docs/functions#:~:text=Each%20execution%20has%20a%20default,for%20up%20to%20900%20seconds.

![](https://drive.google.com/uc?id=1WSJKTCP9yRMAMQKYXkKXLfM0JRNjM0et)

**Comment by stnguyen90** [comment]
@usamashafiqs, 

> [nodemail.tar.gz](https://github.com/appwrite/appwrite/files/11642033/nodemail.tar.gz) @stnguyen90 This is the full code of the function.

The `console.error(e);` could be a problem. It would be best to do `console.error(e.toString());`. 

In addition, it's odd the stack trace doesn't quite line up with the code. The stack trace says the error occurred on line 55, but your file is less than 55 lines.

**Comment by stnguyen90** [comment]
@usamashafiqs, 

> I try to execute a simple fetch request within a function got this stack trace.
> 
> ```
> ReferenceError: e is not defined
>     at module.exports (/usr/code-start/index.js:55:19)
>     at /usr/local/src/server.js:68:19
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> They both are different, but they are doing async tasks.

Would you please share your latest full code for this function so I can see what's on line 55 that's throwing the error?

> I think the problem is that Function is not doing async tasks.

Async code works fine in Appwrite functions.

**Comment by MACTEPyc** [comment]
If you are using Appwrite locally on your computer, you may have problems connecting to the API. In my case, replacing the localhost address in the endpoint with the IP address of my computer helped.

Do not use "http://localhost/v1" or "http://127.0.0.1/v1" when calling Appwrite API functions if the server is running locally. Instead, specify the actual IP address of your machine in the endpoint.

I spent two days figuring out this problem. I hope my experience will help someone save time and avoid headaches due to the wrong endpoint.
