### ISSUE TITLE
🐛 Bug Report: Auth Methods Web UI

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#5424]
### 👟 Reproduction steps

When I try to remove/update the Auth methods on the UI
![image](https://user-images.githubusercontent.com/17125438/233995990-4cdd3129-adda-42b6-ae0c-fd7ddb39eac2.png)

a toast appears that says that the settings got saved, but after refreshing the UI, all options are still checked

### 👍 Expected behavior

if i remove a option it should be unchecked after a refresh

### 👎 Actual Behavior

all options are checked after refresh

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi - thank you for opening this. I tried reproducing this and it works fine for me:
Before refresh:
<img width="1075" alt="Screenshot 2023-04-25 at 7 56 55 PM" src="https://user-images.githubusercontent.com/72690202/234308803-fd165f51-d5d8-4c4e-99c9-17bb70f5a9a2.png">


After refresh:
<img width="1072" alt="Screenshot 2023-04-25 at 7 57 09 PM" src="https://user-images.githubusercontent.com/72690202/234308892-b59d0111-231e-4a20-a6b4-4be71227d9df.png">

Can you try re-running Appwrite once and see if this error exists?

**Comment by s3ppo** [comment]
seems to be a refresh problem with my browser

if i update settings and click in menu on other menu point and then back to auth settings, its not updated, but if i refresh the page with F5 its updated
