### ISSUE TITLE
🚀 Feature: Local functions server

### ISSUE THREAD

**Issue by byawitz** [appwrite/appwrite#5425]
### 🔖 Feature description

An easy way to build and test functions locally. 

Currently, when developing a function, it is necessary to deploy and upload it to the server to fully test it.

Although in the last step of a function development process, I'll probably deploy it and test it on the Appwrite instance a few times, It would be much easier to try it locally. 

What I thought could be a good solution is to add a **local server** script to each one of the [function-starter](https://github.com/appwrite/functions-starter) templates.

For example, in the Node template, we can add a file named `local-server.js`:
```bash
├── node-18.0
│   ├── src
│   │   ├── index.js
│   ├── .gitignore
│   ├── package.json
│   ├── README.md
│   ├── local-server.js  !New file
```

Then this could be the format of `package.json`:
```json
{
  "name"        : "appwrite-function",
  "version"     : "1.0.0",
  "description" : "",
  "type"        : "commonjs",
  "main"        : "src/index.js",
  "scripts"     : {
    "dev" : "node local-server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords"    : [],
  "author"      : "",
  "license"     : "ISC",
  "dependencies": {
    "node-appwrite": "^8.0.0"
  }
}
```

And this would be the code of `local-server.js` (a suggestion):
```javascript
const func = require('./src/index.js');

const req = {
	headers  : {},
	payload  : {},
	variables: {
		APPWRITE_FUNCTION_ID             : '',
		APPWRITE_FUNCTION_NAME           : '',
		APPWRITE_FUNCTION_DEPLOYMENT     : '',
		APPWRITE_FUNCTION_TRIGGER        : '',
		APPWRITE_FUNCTION_RUNTIME_NAME   : '',
		APPWRITE_FUNCTION_RUNTIME_VERSION: '',
		APPWRITE_FUNCTION_EVENT          : '',
		APPWRITE_FUNCTION_EVENT_DATA     : '',
		APPWRITE_FUNCTION_DATA           : '',
		APPWRITE_FUNCTION_PROJECT_ID     : '',
		APPWRITE_FUNCTION_USER_ID        : '',
		APPWRITE_FUNCTION_JWT            : '',
	},
};

const res = {
	send(text, status) {
		console.log(text, status);
	},
	json(obj, status) {
		console.log(obj, status);
	},
};


func(req, res).then();
```

Then it is just a matter of running the `local-server.js` file in one of these ways.
```bash
#: npm run dev
#: node local-server.js
```

Being able to quickly mock any of the Appwrite variables in a local environment sounds like something that can make the development process of functions much fast.

P.s. in the future it's also open the option to support HMR whenever possible.

### 🎤 Pitch

A lot of times, the process of developing a function can be one time task.

But, from my experience, it usually requires many test execution. Using the previous solution will make it much easier to develop any function in almost no time.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @byawitz - thank you for opening this. We do realise that this method of testing a function has scope of improvement. Leaving this issue open for now to gather community feedback and suggestions.

**Comment by byawitz** [comment]
You can look [here](https://github.com/byawitz/roadmapper/blob/main/functions/getGitFeatures/local-server.js) for a real-use example.

**Comment by Emeka212** [comment]
> ### 🔖 Feature description
> An easy way to build and test functions locally.
> 
> Currently, when developing a function, it is necessary to deploy and upload it to the server to fully test it.
> 
> Although in the last step of a function development process, I'll probably deploy it and test it on the Appwrite instance a few times, It would be much easier to try it locally.
> 
> What I thought could be a good solution is to add a **local server** script to each one of the [function-starter](https://github.com/appwrite/functions-starter) templates.
> 
> For example, in the Node template, we can add a file named `local-server.js`:
> 
> ```shell
> ├── node-18.0
> │   ├── src
> │   │   ├── index.js
> │   ├── .gitignore
> │   ├── package.json
> │   ├── README.md
> │   ├── local-server.js  !New file
> ```
> 
> Then this could be the format of `package.json`:
> 
> ```json
> {
>   "name"        : "appwrite-function",
>   "version"     : "1.0.0",
>   "description" : "",
>   "type"        : "commonjs",
>   "main"        : "src/index.js",
>   "scripts"     : {
>     "dev" : "node local-server.js",
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "keywords"    : [],
>   "author"      : "",
>   "license"     : "ISC",
>   "dependencies": {
>     "node-appwrite": "^8.0.0"
>   }
> }
> ```
> 
> And this would be the code of `local-server.js` (a suggestion):
> 
> ```js
> const func = require('./src/index.js');
> 
> const req = {
> 	headers  : {},
> 	payload  : {},
> 	variables: {
> 		APPWRITE_FUNCTION_ID             : '',
> 		APPWRITE_FUNCTION_NAME           : '',
> 		APPWRITE_FUNCTION_DEPLOYMENT     : '',
> 		APPWRITE_FUNCTION_TRIGGER        : '',
> 		APPWRITE_FUNCTION_RUNTIME_NAME   : '',
> 		APPWRITE_FUNCTION_RUNTIME_VERSION: '',
> 		APPWRITE_FUNCTION_EVENT          : '',
> 		APPWRITE_FUNCTION_EVENT_DATA     : '',
> 		APPWRITE_FUNCTION_DATA           : '',
> 		APPWRITE_FUNCTION_PROJECT_ID     : '',
> 		APPWRITE_FUNCTION_USER_ID        : '',
> 		APPWRITE_FUNCTION_JWT            : '',
> 	},
> };
> 
> const res = {
> 	send(text, status) {
> 		console.log(text, status);
> 	},
> 	json(obj, status) {
> 		console.log(obj, status);
> 	},
> };
> 
> 
> func(req, res).then();
> ```
> 
> Then it is just a matter of running the `local-server.js` file in one of these ways.
> 
> ```shell
> #: npm run dev
> #: node local-server.js
> ```
> 
> Being able to quickly mock any of the Appwrite variables in a local environment sounds like something that can make the development process of functions much fast.
> 
> P.s. in the future it's also open the option to support HMR whenever possible.
> 
> ### 🎤 Pitch
> A lot of times, the process of developing a function can be one time task.
> 
> But, from my experience, it usually requires many test execution. Using the previous solution will make it much easier to develop any function in almost no time.
> 
> ### 👀 Have you spent some time to check if this issue has been raised before?
> * [x]  I checked and didn't find similar issue
> 
> ### 🏢 Have you read the Code of Conduct?
> * [x]  I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

Hello @byawitz 
I just wanna say a very big thank you for this idea of testing locally before pushing to the appwrite console,
pushing to the appwrite console every time i want to test my code in case of any errors is kinda really tireing and not pleasing at all, i have been looking for a fix, but after encounting this post from you, things have been going smothly when it comes to testing, thanks once again for this greate idea.
💓💓💓💯💯💯

**Comment by byawitz** [comment]
@Emeka212 Thanks

**Comment by harshsinghvi** [comment]
Thanks for the workaround,  I have modified it a little for handling multiple functions and variables for them separately

## Instructions

- create a function using `appwrite init function `
- place `local-server.js` in the root of your folder
- If needed create a file `./function/<function-name>/req.js` to over `req` object  in the `local-server.js` file to store variables for each function
- add `"aw-function": "node local-server.js",` script in your `package.json` file

## usage 
- `node local-server.js ./function/<function-name>`
- or `yarn run aw-function ./function/<function-name>`
- or `yarn run aw-function <function-name>`

> You can specify the function name in the command or specify the complete function path

```
./functions
├── clean-up
│   ├── README.md
│   ├── package.json
│   ├── req.js
│   └── src
│       └── index.js
└── device-crud
    ├── README.md
    ├── package.json
    └── src
        └── index.js
```

```javascript
if (process.argv.length < 2) {
  process.exit();
}
const fs = require('fs');

let path = process.argv[2].split('/');

if (path[path.length - 1] === 'index.js') path = path.join('/');
if (path[path.length - 1] === 'src') path = path.join('/');
if (path.length > 1) path = `${path.join('/')}`;
if (path.length === 1) path = `./functions/${path}/src`;

// eslint-disable-next-line import/no-dynamic-require
const func = require(path);

// eslint-disable-next-line import/no-dynamic-require
const customReq = fs.existsSync(`${path}/../req.js`) ? require(`${path}/../req.js`) : {};

const req = {
  headers: {},
  payload: {},
  variables: {

                APPWRITE_FUNCTION_ID             : '',
		APPWRITE_FUNCTION_NAME           : '',
		APPWRITE_FUNCTION_DEPLOYMENT     : '',
		APPWRITE_FUNCTION_TRIGGER        : '',
		APPWRITE_FUNCTION_RUNTIME_NAME   : '',
		APPWRITE_FUNCTION_RUNTIME_VERSION: '',
		APPWRITE_FUNCTION_EVENT          : '',
		APPWRITE_FUNCTION_EVENT_DATA     : '',
		APPWRITE_FUNCTION_DATA           : '',
		APPWRITE_FUNCTION_PROJECT_ID     : '',
		APPWRITE_FUNCTION_USER_ID        : '',
		APPWRITE_FUNCTION_JWT            : '',
  },
  ...customReq,
};

const res = {
  send(text, status) {
    console.log(text, status);
  },
  json(obj, status) {
    console.log(obj, status);
  },
};

func(req, res).then();
```

**Comment by harshsinghvi** [comment]
@byawitz I spent some time to make this functionality work, and they updated the functions

https://appwrite.io/docs/functions-develop#upgrade

**Comment by byawitz** [comment]
@harshsinghvi  Oops, Yes they just did, and also in the cloud. 
But I think it will be fast to adjust it to the new [Context](<https://appwrite.io/docs/functions-develop#context>)

**Comment by harshsinghvi** [comment]
I followed the mentioned guidelines, but it still doesn't work. The [functions-starter](https://github.com/appwrite/functions-starter) is not updated with the new syntax

![Screenshot 2023-09-23 at 1 25 13 AM](https://github.com/appwrite/appwrite/assets/19868581/724cbd76-c6cc-4e37-8123-e76959951c66)


> @harshsinghvi Oops, Yes they just did, and also in the cloud. But I think it will be fast to adjust it to the new [Context](https://appwrite.io/docs/functions-develop#context)

**Comment by harshsinghvi** [comment]
Finally, my code works, there was an issue with `req.body` It was supposed to be an Object but it was a String, so it has to be parsed manually, 


new `local-server.js` with env support
```javascript

const main = async () => {
  if (process.argv.length < 3) {
    console.log('Invalid Usage');
    return;
  }

  let path = process.argv[2].split('/');

  if (path[path.length - 1] === 'index.js') path = path.join('/');
  if (path[path.length - 1] === 'src') path = path.join('/');
  if (path.length > 1) path = `${path.join('/')}`;
  if (path.length === 1) path = `./functions/${path}/src`;

  // eslint-disable-next-line global-require
  require('dotenv').config({ path: `${path}/../.env` });

  // eslint-disable-next-line import/no-dynamic-require
  const func = await import(`${path}/main.js`);

  const req = {
    method: 'POST',
    body: {
      name: 'test',
      status: 'unregistered',
      owner: null,
      model: null,
      delete: false,
      battery: null,
      carrierName: null,
      signalStrength: null,
      lastSeen: null,
      $id: '',
      $permissions: [],
      $createdAt: '2023-09-22T20:34:32.293+00:00',
      $updatedAt: '2023-09-22T20:34:32.293+00:00',
      $databaseId: '',
      $collectionId: '',
    },
    headers: {
      host: ':3000',
      'user-agent': 'Appwrite/1.4.3',
      'x-appwrite-trigger': 'event',
      'x-appwrite-event': 'databases.sms-api.*.*.documents.*.create',
      'x-appwrite-user-id': '',
      'content-type': 'application/x-www-form-urlencoded',
      connection: 'keep-alive',
      'content-length': '339',
    },
  };

  const res = {
    send(text, status) {
      console.log('[SEND] ', text, status);
    },
    json(obj, status) {
      console.log('[JSON] ', obj, status);
    },
  };

  const log = (...args) => console.log('[LOG] ', ...args);
  const error = (...args) => console.error('[ERR] ', ...args);

  func.default({ req, res, log, error }).then();
};

main();

```
