### ISSUE TITLE
🐛 Bug Report: `expire` Format is Wrong in Create Magic URL session (confirmation)

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#5428]
See https://github.com/appwrite/appwrite/issues/4982

**Comment by ashutosh887** [comment]
I would like to work on this @stnguyen90

**Comment by stnguyen90** [comment]
@ashutosh887 assigned! Thanks for your interest! 🙏🏼

**Comment by Pranavtej** [comment]
I would like to work on this @stnguyen90

**Comment by fanatic75** [comment]
@stnguyen90, have raised a PR since the assignee didn't raise any. Please assign it to me and review.

**Comment by stnguyen90** [comment]
@ashutosh887, I'm also going to move forward with @fanatic75's PR on this one.

**Comment by ashutosh887** [comment]
Can you suggest me some other issues to work on @stnguyen90
