### ISSUE TITLE
📚 Documentation: Missing $ sign in appwrite.json Collection Options

### ISSUE THREAD

**Issue by PaulDotterer** [appwrite/appwrite#5433]
### 💭 Description

Hello all!
Im currently exploring appwrite and loving it so far.
Whilst messing around with the appwrite CLI, editing appwrite.json, i stumbeld upon a missing $ sign inside the documentation that had me stumped for half an hour.

Its missing inside the section "Collection Options". It currently says "permissions" but i believe it should say "$permissions".
Once i added the $ sign inside my appwrite.json it worked like a charm.

[Collection Options](https://appwrite.io/docs/command-line-deployment#collection-options)

![missing_$_screenshot](https://user-images.githubusercontent.com/44400894/234577824-2d2b9fbb-76e4-40ee-a50f-db831cea62fc.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
@PaulDotterer Looks like you're right!

The docs for this page are here:
https://github.com/appwrite/docs/blob/d89496dcf447bc174c83f7cc34437a3271ff5de9/app/views/docs/command-line-deployment.phtml#L256

I think we may have multiple instances of this. 

LMK if you'd like the honors of adding the `$` yourself ;)

Get some more green boxes on your commit history 😆

**Comment by PaulDotterer** [comment]
@gewenyu99 sure would like to take a crack at it.
Never contributed before tho, will give it a try :)

**Comment by PaulDotterer** [comment]
@gewenyu99 i submitted the PR, hopefully done everything right.
Did not find a way to assign you, so i did @ you at the bottom of the PR.

**Comment by akashchouhan16** [comment]
Since it has been resolved **✅ [#362](https://github.com/appwrite/docs/pull/362 "View PR")**. This issue could be closed now, I guess @gewenyu99?
