### ISSUE TITLE
🐛 Bug Report: Bucket Permission not performs properly

### ISSUE THREAD

**Issue by nexmoe** [appwrite/appwrite#5450]
### 👟 Reproduction steps

Set a bucket like this
![image](https://user-images.githubusercontent.com/16796652/235052375-e6a29d72-fc6d-423c-8d7f-19363a98756d.png)
![image](https://user-images.githubusercontent.com/16796652/235052396-44d8305d-fd22-4b97-95cf-091b84ec2fe9.png)

### 👍 Expected behavior

Those who have permission can read their own files, and every user can create

### 👎 Actual Behavior

Every user can read all files, rather than read files they have permission

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.3.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi - when you refresh the page, does it show the same values ticked as before? like does it resemble no changes made at all?

**Comment by nexmoe** [comment]
> 



> Hi - when you refresh the page, does it show the same values ticked as before? like does it resemble no changes made at all?

yes
