### ISSUE TITLE
🐛 Bug Report: Can't Search Relationship

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#5454]
### 👟 Reproduction steps

1. Create collections A and B w/ relationships (e.g. 1 to 1 from A to B)
2. Create a document in collection A and copy the ID
3. Try to create a document in collection B and try to search for the ID from collection A

### 👍 Expected behavior

The search should find the document

### 👎 Actual Behavior

The search doesn't:

![image](https://user-images.githubusercontent.com/1477010/235203858-c0b7ab49-a62c-4328-9fd0-54d72f27789a.png)

Appwrite logs:

```
appwrite  | [Error] Timestamp: 2023-04-28T16:33:26+00:00
appwrite  | [Error] Method: GET
appwrite  | [Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
appwrite  | [Error] Type: Appwrite\Extend\Exception
appwrite  | [Error] Message: Searching by attribute "$id" requires a fulltext index.
appwrite  | [Error] File: /usr/src/code/app/controllers/api/databases.php
appwrite  | [Error] Line: 2906
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by abnegate** [comment]
@stnguyen90 You can't use a `search` query (`MATCH AGAINST`) on a column that doesn't have a full-text index, this is a limitation of the database itself. The console will need to do something else here: 

https://github.com/appwrite/console/blob/main/src/routes/console/project-%5Bproject%5D/databases/database-%5Bdatabase%5D/collection-%5Bcollection%5D/document-%5Bdocument%5D/attributes/relationship.svelte#L64

cc @TorstenDittmann
