### ISSUE TITLE
🚀 Feature: Allow updation of `size` parameter in string attribute

### ISSUE THREAD

**Issue by chinmoy12c** [appwrite/appwrite#5458]
### 🔖 Feature description

The string attribute does not support updating the `size` parameter, similar to how Integer and Float attributes provide support for changing `max` and `min`. It would be helpful if string attribute update also supports this feature similar to Float and Integer.

### 🎤 Pitch

There are scenarios where the need may arise to change the size of the string attribute, for example, if that field is used to store some kind of hash or encoding which may change in size in the future.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi - we do have this planned for upcoming versions.

We had it planned for earlier but we want to be 200% sure that it indeed is safe and would not cause any damage to the data, hence it is postponed. Thanks for the suggestion!

**Comment by Sun3** [comment]
Any updates to allow the attribute size to increase? Without it, once in production, and you need to increase size of the attributed and you cannot, this makes your production application in peril. 

Thanks.

**Comment by bonaparten** [comment]
I already needed to create new attributes because I could not update the size of attributes.

Please consider adding the feature.

**Comment by Shiba-Kar** [comment]
Any work around for now  need to just run this ```ALTER TABLE table_name MODIFY COLUMN column_name VARCHAR(new_length)```
