### ISSUE TITLE
🐛 Bug Report: Modal is misaligned 

### ISSUE THREAD

**Issue by sanathusk** [appwrite/appwrite#5459]
### 👟 Reproduction steps

Try to delete a existng project by navigation through settings for the project, click on delete project,a modal requesting you to enter the name for the project & password is shown, the modal is displayed at the bottom left corner of the window, will password field, submit button not visible.the only way to see the filed is by lower the zoom let to 50%.

![image](https://user-images.githubusercontent.com/19380158/235278505-812a66b5-bf0d-42a8-b238-06cea540cfe9.png)

### 👍 Expected behavior

The modal requesting you to enter the name for the project & password is should be  displayed at the center of the page. 

### 👎 Actual Behavior

The modal requesting you to enter the name for the project & password is shown, the modal is displayed at the bottom left corner and also not all fields are visible.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

The issue occurred in Appwrite Cloud (beta) Environment.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
@sanathusk thanks for raising this. Can you share your browser version ?

**Comment by eldadfux** [comment]
Closing in favor of https://github.com/appwrite/console/issues/1454
