### ISSUE TITLE
*Appwrite Content* - Help us create & improve docs, examples & tutorials

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#546]
We have started deploying multiple examples repos for different platforms to the Appwrite org namespace. This repos contain different Appwrite demos, examples and tutorials for getting started with Appwrite.

Currently the main focus for this repos is around examples for platforms like: Angular, Vue.JS, React, Svelte & Flutter, tutorials for using different Appwrite features (OAuth) and different deployment methods.

This is a great way to both start playing around with Appwrite and to contribute to our open-source project.

**Feel free to suggest ideas for more types of content as a comment to this issue.**

## General Notes
* Use valid markdown for all content
* Markdown file name should be in this format: `my-new-appwrite-tutorials/README.md`
* Add markdown alt attribute for all images
* Include only images with specific size (1200x800px) in PNG format
* Include all images in the same directory as your markdown file For example: `my-new-appwrite-tutorials/image-1.png`

## Vue.js

> Add all tutorials in this repo: https://github.com/appwrite/demos-for-vue at root directory

TODO List:

- [x] Simple login example and tutorial (@PineappleIOnic)
- [x] Simple Database examples and tutorial (@PineappleIOnic)
- [x] Simple storage file upload example and tutorial (@PineappleIOnic)
- [ ] Simple image cropping examples and tutorial (@PineappleIOnic)
- [x] Simple usage examples for the [Appwrite Locale API](https://appwrite.io/docs/client/locale)
- [ ] Simple usage examples for the [Appwrite Avatars API](https://appwrite.io/docs/client/avatars)

## Svelte

> Add all tutorials in this repo: https://github.com/appwrite/demos-for-svelte at root directory

TODO List:

- [x] Simple login example and tutorial (@PineappleIOnic)
- [ ] Simple Database examples and tutorial (@drcoolsanjeev)
- [ ] Simple storage file upload example and tutorial
- [ ] Simple image cropping examples and tutorial
- [ ] Simple usage examples for the [Appwrite Locale API](https://appwrite.io/docs/client/locale)
- [ ] Simple usage examples for the [Appwrite Avatars API](https://appwrite.io/docs/client/avatars)

## Angular

> Add all tutorials in this repo: https://github.com/appwrite/demos-for-angular at root directory

TODO List:

- [ ] Simple login example and tutorial (@benceHornyak)
- [ ] Simple Database examples and tutorial (@jagdishjadeja)
- [ ] Simple storage file upload example and tutorial (@benceHornyak)
- [ ] Simple image cropping examples and tutorial
- [ ] Simple usage examples for the [Appwrite Locale API](https://appwrite.io/docs/client/locale)
- [ ] Simple usage examples for the [Appwrite Avatars API](https://appwrite.io/docs/client/avatars)

## React

> Add all tutorials in this repo: https://github.com/appwrite/demos-for-react at root directory

TODO List:

- [x] Simple login example and tutorial (@PineappleIOnic)
- [ ] Simple Database examples and tutorial (@Niweera)
- [ ] Simple storage file upload example and tutorial (@divyake)
- [ ] Simple image cropping examples and tutorial (@spiritbro1)
- [ ] Simple usage examples for the [Appwrite Locale API](https://appwrite.io/docs/client/locale) (@k-guy-dev)
- [ ] Simple usage examples for the [Appwrite Avatars API](https://appwrite.io/docs/client/avatars)(@naman360)

## Features

> Add all tutorials in this repo: https://github.com/appwrite/appwrite at this location: `docs/oauth`

- [ ] Login with Facebook + Appwrite OAuth API (@ShubhamSood1406)
- [ ] Login with Github + Appwrite OAuth API (@nitch193)
- [ ] Login with Google + Appwrite OAuth API (@relaxxpls)
- [ ] Monitor your Appwrite server with the [Health API](https://appwrite.io/docs/server/health)

## Deployment

> Add all tutorials in this repo: https://github.com/appwrite/appwrite at this location: `docs/deployment`

- [ ] Deploy Appwrite on AWS (@dannylwe)
- [ ] Deploy Appwrite on GCP (@Sameerkash)
- [ ] Deploy Appwrite on Azure (@seongwon-kang)
- [ ] Deploy Appwrite on IBMCloud (@avats-dev)
- [ ] Deploy Appwrite on DigitalOcean (@spiritbro1)
- [ ] Deploy Appwrite on Linode (@kodumbeats)
- [ ] Deploy Appwrite on Vultr (@hack3r-0m)
- [ ] Deploy Appwrite on K8 (@Sameerkash)
- [ ] Deploy Appwrite on Docker Swarm
- [ ] Connect Appwrite with a managed DB solution
- [ ] Deploy Appwrite without ClamAV
- [ ] Deploy Appwrite with Sendgrid as an SMTP server (@hack3r-0m)
- [ ] Deploy Appwrite with MailGun as an SMTP server

**Comment by Niweera** [comment]
@eldadfux I would like to contribute to `Simple Database examples and tutorial` in **React**.

**Comment by jagdishjadeja** [comment]
@eldadfux I would like to contribute to  `Simple Database examples and tutorial` in **angular**

**Comment by eldadfux** [comment]
@jagdishjadeja got you assigned

**Comment by benceHornyak** [comment]
@eldadfux Angular and AngularJS can be very confusing, they are two completely different framework.  If you want I can contribute with Angular (2+, not JS).

**Comment by eldadfux** [comment]
@benceHornyak, I fixed the FW name in the issue. Feel free to send any Angular PRs at: https://github.com/appwrite/demos-for-angular

**Comment by benceHornyak** [comment]
@eldadfux I'd love to contribute to `Simple storage file upload example and tutorial` in __angular__ for hacktoberfest

**Comment by eldadfux** [comment]
@benceHornyak that's great, I assigned you to the issue.

**Comment by eldadfux** [comment]
Just added 2 new tutorials on the checklist:
- [ ] Deploy Appwrite with Sendgrid as an SMTP server
- [ ] Deploy Appwrite with MailGun as an SMTP server

**Comment by divyake** [comment]
@eldadfux I would like to contribute to `Simple storage file upload example and tutorial` in react for hacktoberfest

**Comment by eldadfux** [comment]
@divyake, I got you assigned.

**Comment by Ninjavin** [comment]
@eldadfux I would like to contribute to `Simple image cropping examples and tutorial` in React for Hacktoberfest

**Comment by spiritbro1** [comment]
@eldadfux I would like to contribute to ``` Simple image cropping examples and tutorial``` in React

**Comment by eldadfux** [comment]
@spiritbro1 you have been assigned to `Simple image cropping examples and tutorial` in React

**Comment by dannylwe** [comment]
Hi, I'd like to contribute to `Deploy Appwrite on AWS`

**Comment by eldadfux** [comment]
@dannylwe got you assigned to it 👌🏻

**Comment by Sameerkash** [comment]
@eldadfux  I would like to work on Deploying to k8 and GCP

**Comment by eldadfux** [comment]
@Sameerkash 👌🏻

Assigned you to both:
* Deploy Appwrite on GCP
* Deploy Appwrite on K8

**Comment by KarenEfereyan** [comment]
@eldafux I am still trying to understand this issue and how I can make contributions? Mind explaining it further?

**Comment by iamsaquib8** [comment]
@eldadfux I would like to contribute to Simple Database examples and tutorial in Svelte

**Comment by PineappleIOnic** [comment]
Hey, 👋 I'm currently working on a Database Example and a File Upload example for VueJS, Could I please be assigned to those tasks if they are still available?

**Comment by PineappleIOnic** [comment]
and I would also like to be removed from Simple login example and tutorial on Angular, Since I would prefer to devote more attention to VueJS, Svelte and React.

**Comment by relaxxpls** [comment]
Could I add tutorials on Logging in with various services, I'm almost done with the documentation for google.

**Comment by eldadfux** [comment]
@PineappleIOnic I added you to the Vue.js tutorials, removed the Angular one.

@relaxxpls I added you to the Google login tutorial, let me know if you want to add more OAuth tutorials, we can also extend the list.

**Comment by drcoolsanjeev** [comment]
@eldadfux I would like to contribute to Simple Database examples and tutorial in React

**Comment by spiritbro1** [comment]
> @eldadfux I would like to contribute to Simple Database examples and tutorial in React

![image](https://user-images.githubusercontent.com/62529025/94771363-3c5a2e00-03e1-11eb-93e7-ba8f03aff4d4.png)

there is already somebody assigned to do that please pick another issue pick some issue that doesnt have @ in it

**Comment by Hard-Coder05** [comment]
@eldadfux Just wanted to know if there is anything related to flutter that I can help in?

**Comment by ShubhamSood1406** [comment]
@eldadfux Can I work on Login with Facebook + Appwrite OAuth API

**Comment by benceHornyak** [comment]
hey :wave: @eldadfux I'll happily take over ` Simple login example and tutorial` for Angular.

**Comment by k-guy-dev** [comment]
Hey @eldadfux I would really like to take a shot at React Locale API example,

**Comment by PineappleIOnic** [comment]
Could I get assigned to: `Simple image cropping examples and tutorial` for Vue? I have completed the previous two tasks and just awaiting a merge for them 👍

**Comment by naman360** [comment]
I want to work on `Simple usage examples for the Appwrite Avatars API`.

**Comment by abhi14nexu** [comment]
I want to work on ### Simple login example and tutorial for Angular and I have also created a PR for the same.

**Comment by abhi14nexu** [comment]
I want to work on ### **Simple login example and tutorial for Angular** and I have also created a PR for the same.

**Comment by abhi14nexu** [comment]
I want to work on `Simple login example and tutorial for Angular` and I have also created a PR for the same.

**Comment by spiritbro1** [comment]
@eldadfux i want to get assigned into ```Deploy Appwrite on DigitalOcean```

**Comment by BalgopalPatro** [comment]
@eldadfux I want to create a one-to-one Chat Application in React

**Comment by spielers** [comment]
> @eldadfux I would like to contribute to Simple Database examples and tutorial in Svelte

hey, @drcoolsanjeev Go for it I am assigning you That

**Comment by spielers** [comment]
> @eldadfux I want to create a one-to-one Chat Application in React

@BalgopalPatro that would be great but make proper documentation of start-to-end process of it .

Best,
spielers

**Comment by spielers** [comment]
> @eldadfux I want to get assigned to `Deploy Appwrite on DigitalOcean`

Hey, @spiritbro1 You can work on this let me know when you're done!

**Comment by spielers** [comment]
> hey 👋 @eldadfux I'll happily take over ` Simple login example and tutorial` for Angular.

@benceHornyak Go for it I will assign your name to that

**Comment by spielers** [comment]
> Hey @eldadfux I would really like to take a shot at Appwrite Locale API example for React.

Hey, @k-guy-dev  Go for it I will assign your name

**Comment by KarenEfereyan** [comment]
@spielers for us who have submitted PRS have they been reviewed?

**Comment by spielers** [comment]
@KarenEfereyan  Yeah definitely it would be reviewed! :)

Best,
spielers

**Comment by spiritbro1** [comment]
@spielers https://github.com/appwrite/appwrite/issues/546#issuecomment-703476889 done https://github.com/appwrite/appwrite/pull/622

**Comment by Kolkies** [comment]
> for us who have submitted PRS have they been reviewed?
@KarenEfereyan I can't find any PR from you in the appwrite repo?

**Comment by avats-dev** [comment]
@spielers @Kolkies Can I add deployment docs for `heroku` and `IBMCloud`, but these two are not mentioned in the above TODO? Thanks, let me know.

**Comment by seongwon-kang** [comment]
@eldadfux Hi, I want to get assigned to `Deploy Appwrite on Azure`

**Comment by spielers** [comment]
Hey, @seongwon-kang Go for it. I will assign your name there 

best,
spielers

**Comment by vj-codes** [comment]
@spielers @eldadfux I would like to` Simple usage examples for the Appwrite Locale API` as a part of hacktoberfest . What needs to be done exactly ?
Also after that one is done I would proceed to `Simple usage examples for the Avatars API`

**Comment by vj-codes** [comment]
@spiritbro1 are you working on  `Simple image cropping examples and tutorial ` ?? If not can I work on it?

**Comment by spiritbro1** [comment]
@vj-codes which one react?

**Comment by vj-codes** [comment]
@spiritbro1 yes the react one

**Comment by spiritbro1** [comment]
![image](https://user-images.githubusercontent.com/62529025/95569496-dbb99980-0a4f-11eb-9bb5-99cce8a461e4.png)

@vj-codes https://github.com/appwrite/demos-for-react/pull/4 i've already done it just need review sorry please pick something else

**Comment by PineappleIOnic** [comment]
`Simple Database examples and tutorial` and `Simple storage file upload example` and tutorial for vueJS have both been finished

**Comment by eldadfux** [comment]
I updated the main issue, and assigned everyone who asked for an issue where the issue was still up for grabs. We'll do an effort to review all open PR as soon as possible. We'll also add some more ideas for new content in the next few days.

* @ShubhamSood1406 I assigned you to `Facebook OAuth tutorial`
* @benceHornyak I assigned you to `Angular login tutorial`
* @k-guy-dev I assigned you to `Appwrite Locale API example for React`
* @PineappleIOnic I assigned you to `Simple image cropping examples and tutorial for Vue`
* @naman360 I assigned you to `Simple usage examples for the Appwrite Avatars API for React`
* @spiritbro1 I assigned you to `Deploy Appwrite on DigitalOcean`
* @drcoolsanjeev I assigned you to `Simple Database examples and tutorial` for Svelte
* @avats-dev I assigned you to Deploy Appwrite on IBMCloud
* @seongwon-kang I assigned you to Deploy Appwrite on Azure

**Comment by k-guy-dev** [comment]
@eldadfux , I've made a PR for the react example and I think @christyjacob4 hasn't responded. Please can you assign it to another reviewer? Thanks 😄

**Comment by vj-codes** [comment]
> @spielers @eldadfux I would like to` Simple usage examples for the Appwrite Locale API` as a part of hacktoberfest . What needs to be done exactly ?
> Also after that one is done I would proceed to `Simple usage examples for the Avatars API`

@eldadfux can I get assigned to this

**Comment by spielers** [comment]
Hey, @vj-codes `Simple usage examples for the Appwrite Locale API` with react is already done You can proceed with any others that are remaining.

**Comment by nitch193** [comment]
Would like to work on Login with `Github+Appwrite OAuth API`

**Comment by Preetpalkaur3701** [comment]
Hi! I would like to work on this issue: Login with Github + Appwrite OAuth API
Can you assign it to me!

**Comment by hack3r-0m** [comment]
please assign me **Deploy Appwrite with Sendgrid as an SMTP server** and **Deploy Appwrite on vultr**

**Comment by eldadfux** [comment]
> Would like to work on Login with `Github+Appwrite OAuth API`

Got you assigned 👍🏻

**Comment by eldadfux** [comment]
> Hi! I would like to work on this issue: Login with Github + Appwrite OAuth API
> Can you assign it to me!

@nitch193 has been assigned, @Preetpalkaur3701 would you like to create one for another OAuth provider?

**Comment by eldadfux** [comment]
> please assign me **Deploy Appwrite with Sendgrid as an SMTP server** and **Deploy Appwrite on vultr**

@hack3r-0m you got it 👌🏻

**Comment by aloks98** [comment]
@eldadfux if there's no development on Deploy appwrite on GCP tutorial, I can make a PR today!

**Comment by Sameerkash** [comment]
> @eldadfux if there's no development on Deploy appwrite on GCP tutorial, I can make a PR today! 

@eldadfux you can unassign me and give it to @aloks98 I don't think I'll be able to make the PR for GCP anytime soon as I'm still trying to figure it out. 


I would still like to make the PR for k8s docs with some time. 

@aloks98 it'd be great if you could help me with some pointers to k8s if you're aware. As I'm halfway through and researching more on where I'm stuck.

**Comment by anushkrishnav** [comment]
I am a python developer is there anything I can work on ?

**Comment by kodumbeats** [comment]
Can I be assigned `Deploy Appwrite on Linode`? I used to work there and can publish the guide to the [Linode Community](https://www.linode.com/community/questions/) for more visibility.

**Comment by eldadfux** [comment]
@kodumbeats this would be great, and adding it to the Linode community will be AWESOME!

**Comment by vilsi12** [comment]
can I work on this issue i am good flutter developer

**Comment by themotu** [comment]
> I am a python developer is there anything I can work on ?

I'd like to see a django implementation for auth

**Comment by PineappleIOnic** [comment]
@eldadfux The `Simple Database example and tutorial` and `Simple storage file upload example and tutorial` were completed and commited a while ago in the [demos-for-vue repository](https://github.com/appwrite/demos-for-vue)

**Comment by ignertic** [comment]
Thought I would run into a Flutter TODO as well

**Comment by DonnC** [comment]
Anything for flutter on the TODO list
That would be great

**Comment by loftwah** [comment]
Booyah, I am going to get stuck into a couple of these.

**Comment by dkp1903** [comment]
Hi, @eldadfux . I'd like to work on `Connect Appwrite to a managed DB solution` . I trust MongoDB Atlas is a common, simple and complete example of a managed cloud DB solution?

Thanks!

**Comment by eldadfux** [comment]
> Hi, @eldadfux . I'd like to work on `Connect Appwrite to a managed DB solution` . I trust MongoDB Atlas is a common, simple and complete example of a managed cloud DB solution?
> 
> Thanks!

You can feel free to pick this issue and submit a PR, please note that our MongoDB integration is still not ready. You can feel free to write the same on MariaDB or MySQL.

**Comment by dkp1903** [comment]
Thanks, @eldadfux ! I'll evaluate if I can get my MySQL installation up and running locally. If so, will do the MySQL thing. If it's too much pain, I'll update here by the weekend so that someone else can pick this up and it doesn't remain blocked with me

**Comment by Ritzy-NCode** [comment]
Hi!
I am a full stack developer. Anything that I can take up.
Do suggest something.

**Comment by Meldiron** [comment]
> Hi! I am a full stack developer. Anything that I can take up. Do suggest something.

Hey there 👋 With 0.13 we upgraded our Appwrite Functions. On one hand, they are now MUCH faster, on the other, the syntax is now a bit different, making all examples outdated.

We would highly appreciate contributions to [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository. This is a repository of demo Appwrite functions. There are already some examples that you can take inspiration from. Feel free to implement any cool function that people could use, or look at to see Appwrite Functions in action.

**Comment by Ritzy-NCode** [comment]
> > Hi! I am a full stack developer. Anything that I can take up. Do suggest something.
> 
> Hey there 👋 With 0.13 we upgraded our Appwrite Functions. On one hand, they are now MUCH faster, on the other, the syntax is now a bit different, making all examples outdated.
> 
> We would highly appreciate contributions to [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository. This is a repository of demo Appwrite functions. There are already some examples that you can take inspiration from. Feel free to implement any cool function that people could use, or look at to see Appwrite Functions in action.

Sure @Meldiron let me take a look at the project and I will update. 
Thanks :)

**Comment by fballan93** [comment]
> @eldadfux Hi, I want to get assigned to `Deploy Appwrite on Azure`

any update on this . i've been struggling with azure . since azure docker compose doesn't support .env file im struggling to deploy it

**Comment by loftwah** [comment]
That makes sense because environmental variables are very unsafe to store secrets. I found [this](https://www.howtogeek.com/devops/how-to-secure-sensitive-data-with-docker-compose-secrets/) article that shows how you can do this, and another one [here](https://devops.stackexchange.com/questions/4859/docker-compose-azure-key-vault-passing-secrets-to-a-container-on-startup) that explains the same problem at Stack Exchange.

**Comment by loftwah** [comment]
You could also hard-code any values inside your Docker-Compose files instead of relying on the `.env` file.

**Comment by thevinitgupta** [comment]
@eldadfux Is any one working on `Simple storage file upload example and tutorial` in React ?

**Comment by SaiHtetMyatHtut** [comment]
@eldadfux I would like to contribute to Simple storage file upload example and tutorial in Svelte.

**Comment by mohakgupt** [comment]
@eldadfux I want to contribute to `Simple storage file upload example and tutorial` in React

**Comment by eldadfux** [comment]
This issue is no longer relevant, we have opened many other issues for contributing content to Appwrite for Hacktoberfest 22.

**Comment by khashashin** [comment]
> > I am a python developer is there anything I can work on ?
> 
> I'd like to see a django implementation for auth

I've created a package, maybe it would be helpful [https://pypi.org/project/django-appwrite/](https://pypi.org/project/django-appwrite/)
