### ISSUE TITLE
🐛 Bug Report: Improper filter in Create user  

### ISSUE THREAD

**Issue by InTruder-Sec** [appwrite/appwrite#5466]
### 👟 Reproduction steps

The create user API takes an optional parameter "name" while registration of user. The input parameter can take a URL as a username. While verifying the account through email the user name is treated as an external URL inside the mail.

![Screenshot from 2023-04-30 15-35-38](https://user-images.githubusercontent.com/75447837/235347389-42063513-514f-4ac2-845f-df97827143b1.png)

### 👍 Expected behavior

The username must be a valid string and should through an error while registration. 

### 👎 Actual Behavior

The username accepts a URL without blocking.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite version: 1.1.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by InTruder-Sec** [comment]
Similar to gitlab issue: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/22076

**Comment by christyjacob4** [comment]
Hey I took a look at your PR and the methodology used is not right for the following reasons

1/ The regex misses out on all the characters other than a-z, A-Z and 0-9.

![Screenshot 2023-05-01 at 9 12 19 AM](https://user-images.githubusercontent.com/20852629/235403409-acb835f9-7eee-42fb-87d6-6c73c2f0dc8a.png)

2/ We use validators to validate params 
https://github.com/appwrite/appwrite/tree/master/src/Appwrite/Auth/Validator

**Comment by InTruder-Sec** [comment]
Thanks, trying to fix it

**Comment by Shiva953** [comment]
any updates?

**Comment by christyjacob4** [comment]
Thanks a lot for raising the issue but we now sanitise all links before rendering them in emails. So this should no longer be an issue. Feel free to reopen the Issue / PR if its still a problem
