### ISSUE TITLE
🐛 Bug Report: Deleting a document with relationship of cascade delete fails if relationship is empty

### ISSUE THREAD

**Issue by SilverMira** [appwrite/appwrite#5467]
### 👟 Reproduction steps

When I have the following collection structure
```
users
  - display_picture (one way, one-to-one relationship to storage_references, cascade delete)
storage_references
  - bucket_id
  - file_id
```

Trying to delete a document from `users` collection if the document has `display_picture == null` results in the following response
```
{"message":"Server Error","code":500,"type":"general_unknown","version":"1.3.1"}
```

`docker compose logs appwrite` reveals the following

```
appwrite  | [Error] Timestamp: 2023-04-30T10:26:23+00:00
appwrite  | [Error] Method: DELETE
appwrite  | [Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
appwrite  | [Error] Type: Error
appwrite  | [Error] Message: Call to a member function getId() on null
appwrite  | [Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
appwrite  | [Error] Line: 3478
```

Temporarily creating an empty `storage_references` document and assigning `user.display_picture` to this document will allow the `users` document to delete as expected

### 👍 Expected behavior

It should delete the `users` document with `display_picture == null`

### 👎 Actual Behavior

`users` document with `display_picture == null` cannot be deleted

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
@SilverMira thanks for raising this issue. 

@abnegate could you take a look here ?

**Comment by abnegate** [comment]
Hey @SilverMira could you please update to version 1.3.3 and give it another try, this issue should be fixed there. Lets us know if you are still having problems 🙏

**Comment by SilverMira** [comment]
Hi, just updated and it works as expected 👍 thanks for the help!
