### ISSUE TITLE
🐛 Bug Report: The lack of error messages in Appwrite functions.

### ISSUE THREAD

**Issue by michaldev** [appwrite/appwrite#5472]
### 👟 Reproduction steps

The problem is that AppWrite Functions does not return any error messages, except for the word 'failed'.

I have described everything along with an example here:
https://github.com/appwrite/appwrite/discussions/5463

### 👍 Expected behavior

I would like to see logs and errors for the AppWrite functions.

### 👎 Actual Behavior

I don't see any error messages.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Something else

### 🧱 Your Environment

AppWrite Cloud

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi, thank you for opening this
This will be improved with Functions G4 https://github.com/appwrite/appwrite/discussions/5016

**Comment by stnguyen90** [comment]
@michaldev, this seems like a duplicate of https://github.com/appwrite/appwrite/issues/3295. Would it be okay to close this and you can 👍🏼 the other issue?

**Comment by joeyouss** [comment]
Closing this issue since it is a duplicate
