### ISSUE TITLE
🐛 Bug Report: Unknown PDO Type for object

### ISSUE THREAD

**Issue by gepd** [appwrite/appwrite#5481]
### 👟 Reproduction steps

I have two collections warehouse and shelf

shelf have two attributes warehouse_id and location_id

warehouse_id
- Two way relationship
- Many to one relationship
- On delete: Set NULL

location_id
- Two way relationship
- Many to one relationship
- On delete: Set NULL

### 👍 Expected behavior

Delete the document

### 👎 Actual Behavior

When I try to delete a document I got the error: "Server error"

In the docker log I got

```
[Error] Method: DELETE
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
[Error] Type: Exception
[Error] Message: Unknown PDO Type for object
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php
[Error] Line: 1347
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gepd, thanks for creating this issue! 🙏🏼 I can't seem to reproduce this on 1.3.4. Would you maybe clarify the steps to reproduce?

**Comment by gepd** [comment]
Today I got this error again in `1.3.4` after I update to `1.3.7` the problem seems to be solved.

I'll reopen it if got this again with the steps to reproduce it

**Comment by Emilien-Lambert** [comment]
Sorry to bring up a closed issue, but I have exactly the same configuration and when I try to delete a document I get : 

```
[Error] Timestamp: 2023-08-18T13:26:18+00:00
[Error] Method: DELETE
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents/:documentId
[Error] Type: Exception
[Error] Message: Unknown PDO Type for object
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php
[Error] Line: 1347
```

I am using Appwrite version `1.3.8`.

Do you have a solution to help me please?

**Comment by gepd** [comment]
As workaround try to restart appwrite, if you get to reproduce this issue, post it here to reopen it and try to solve it

**Comment by gepd** [comment]
Have you tried first deleting the parent document and then the childs? I think that worked for me

**Comment by Emilien-Lambert** [comment]
With me, it's simply impossible to delete a document that has a relationship. Whether it's a single or a double, whether it has children or not, DELETE never works. 

This is so blocking for my project that I hope a solution will be found soon. 😔
