### ISSUE TITLE
🐛 Bug Report: LT symbol inside choices

### ISSUE THREAD

**Issue by yersskit** [appwrite/appwrite#5482]
### 👟 Reproduction steps

when i see any choice selector, i can see an unexpected less than character inside:
![image](https://user-images.githubusercontent.com/47761665/235573734-78684bcc-48c7-4a52-be37-c068b3270955.png)
![image](https://user-images.githubusercontent.com/47761665/235573758-cb892494-eb2b-4cfd-800b-42433448107d.png)

this happens in all the choices.

### 👍 Expected behavior

it should show the element without the "<" character.

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/47761665/235573734-78684bcc-48c7-4a52-be37-c068b3270955.png)
![image](https://user-images.githubusercontent.com/47761665/235573758-cb892494-eb2b-4cfd-800b-42433448107d.png)

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Windows

### 🧱 Your Environment

i'm using appwrite cloud in edge browser latest version

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rushikeshsuryawanshi** [comment]
Hey, I'd like to work on this issue !

**Comment by rvlaskamp** [comment]
When a "switch" is deselected. This is getting added to the content of the :before pseudo selector:

`[type=checkbox]:where(:checked):before {
    content: "\ea38";
} `

**Comment by joeyouss** [comment]
I tried reproducing this and:
<img width="1069" alt="Screenshot 2023-05-05 at 9 33 22 PM" src="https://user-images.githubusercontent.com/72690202/236509334-df7c0b2d-b9e1-43a1-93a2-f93a1d9f795c.png">


I will check with the team and get back if this is frequent

**Comment by joeyouss** [comment]
It seems like this bug is being worked on as of now, so it will get fixed soon.
I would request you to close this issue for now @rvlaskamp and wait till it's fixed by our team

**Comment by rvlaskamp** [comment]
Ok. It can be closed if it is fixed. On AppWrite Cloud it still exist. So maybe you can update the UI on AppWrite Cloud?

**Comment by karthiknadar1204** [comment]
I would like to work on this issue, please assign t to me

**Comment by joeyouss** [comment]
@rvlaskamp Cloud is not yet on 1.3.x - it is on 1.1.2 and will be updated soon. Once updated, this bug will go away.
