### ISSUE TITLE
🚀 feature : ci: add dependabot gh action 

### ISSUE THREAD

**Issue by priyankarpal** [appwrite/appwrite#5486]
### 🔖 Feature description

We can add dependabot gh action to update all packages & gh actions if there are any updates needed. 

### 🎤 Pitch

Currently, we are using a few gh actions. we don't know when there will be a new version. so to solve the problem we can add a gh action(dependabot) it will create a PR if there are any updates needed. 

## Existing GitHub Actions  

![image](https://user-images.githubusercontent.com/88102392/235611161-390eae1b-6fcd-44c8-9af0-c92b0357f955.png)

I want to work on this issue. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi - thank you for the suggestion. We want to have full control over our dependencies, and we update them during each Appwrite release. We prefer to do it all at once that time.

Hence, we do not add a dependabot. Hope this helps. Please close the issue if no extra feedback is needed!
