### ISSUE TITLE
🐛 Bug Report: "User has been blocked" error on creating account on Appwrite

### ISSUE THREAD

**Issue by rapid-killer-9** [appwrite/appwrite#5490]
After Creating an account on [Appwrite](https://t.co/CrxNdOjteN) l.
I have noticed that my details are incorrect. so, I deleted the account to recreate but after that whenever I click on signup or singing it gives me the same error again and again

![image](https://user-images.githubusercontent.com/83023263/235745461-a7d8fcfc-961c-4a70-9a4d-343596112654.png)

**Comment by Hi-ImKyle** [comment]
+1, is there not a default admin account that can be used?

**Comment by stnguyen90** [comment]
We've updated the console such that deleting will actually delete the account rather than block it.
