### ISSUE TITLE
🚀 Feature: Database  - Add OR operation for Multiple queries 

### ISSUE THREAD

**Issue by byawitz** [appwrite/appwrite#5491]
### 🔖 Feature description

Add the ability to query a bunch of queries with **OR** logic.

The queries can be gathered into a single `Query.or()` like this:
```javascript
databases.listDocuments(
  '[DATABASE_ID]',
  '[COLLECTION_ID]',
  [
    Query.or(
      [
        Query.equal('title', ['Avatar', 'Lord of the Rings']),
        Query.greaterThan('year', 1999)
      ]
    )
  ]
);
```

### 🎤 Pitch

As of today when we want to filter any Appwrite collection data we can either filter it using **And** logic, Or as **Or** logic on a single attribute as follow:
```javascript
databases.listDocuments(
    '[DATABASE_ID]',
    '[COLLECTION_ID]',
    [
        Query.equal('title', ['Avatar', 'Lord of the Rings']),
        Query.greaterThan('year', 1999)
    ]
);
```
In this example any results from the year **1999** with a title equal to either **Avatar** or **Lord of the Rings** will be sent back.

But if there is a need for example to get all the movies that are **either** from the year *1999* or the title equals **Avatar** or **Lord of the Rings** then we have to run two queries for that, and the aggregate the results somehow, like that:
```javascript
databases.listDocuments(
  '[DATABASE_ID]',
  '[COLLECTION_ID]',
  [
    Query.equal('title', ['Avatar', 'Lord of the Rings']),
  ]
);

databases.listDocuments(
  '[DATABASE_ID]',
  '[COLLECTION_ID]',
  [
    Query.greaterThan('year', 1999)
  ]
);
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Thank you for backlinking the issue #2740 - we will keep this open for now for gathering community feedback.

**Comment by stnguyen90** [comment]
What's the difference between this and https://github.com/appwrite/appwrite/issues/2740? If they're the same, it would be good to close this so that there's only one issue with upvotes.
