### ISSUE TITLE
Help: Send the data of function only in body of request, not in "data" field

### ISSUE THREAD

**Issue by Poowerllz** [appwrite/appwrite#5499]
### 💭 Description

Its possible parse function data without send the body in "data" field of object? 

example:
I wanna parse my data only in the body of request, I can't customize my sender to send the request with data inside "data" field.

Thanks all!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Poowerllz** [comment]
Hey everyone, anyone have updates for this, please?

**Comment by joeyouss** [comment]
Hi - In next versions, we plan to add support to read HTTP request body directly. Right now, it is not possible

**Comment by Poowerllz** [comment]
Yeah, of course. Thanks!
