### ISSUE TITLE
📚 Documentation: Website UI in Dark mode makes function dropdown invisible in Firefox

### ISSUE THREAD

**Issue by Vedsaga** [appwrite/appwrite#5505]
### 💭 Description

![image](https://user-images.githubusercontent.com/59083528/236378188-827b25bf-bb84-4f56-8084-cda38690c649.png)

In the dropdown menu thing is not visible clearly

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi,
I tried checking it and:
<img width="1130" alt="Screenshot 2023-05-05 at 2 40 47 PM" src="https://user-images.githubusercontent.com/72690202/236419695-3fade08d-89f5-451d-aba7-7088a76a7049.png">

I am using Brave Browser and testing on safari too yields the same.

Can you specify your browser once?

**Comment by Vedsaga** [comment]
@joeyouss as usual the suspect is FireFox

**Comment by karthiknadar1204** [comment]
If this issue is up for grabs,i would like to work on it

**Comment by joeyouss** [comment]
@Vedsaga in firefox in my system:
![Uploading Screenshot 2023-05-09 at 4.17.41 PM.png…]()

**Comment by Vedsaga** [comment]
@joeyouss btw, it's happening in windows firefox

**Comment by joeyouss** [comment]
Ok, would have been great if you mentioned it earlier 😅

**Comment by joeyouss** [comment]
Hi @noobyogi0010 
Thank you for expressing your interest. We appreciate your enthusiasm. However, I want to inform you that our team is already working on resolving the issue you mentioned, and we have it under control internally.

That being said, we encourage you to explore other opportunities to contribute. Our Appwrite repository has a list of good first issues that you can consider working on. These issues are a great way to get involved with the project and make a meaningful impact. We value contributions from the community, and we believe your skills and expertise would be valuable in addressing other areas of the project.

Please feel free to explore the repository and find an issue that aligns with your interests and expertise. We look forward to your continued involvement with Appwrite. Find our good first issues here: https://github.com/appwrite/appwrite/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
