### ISSUE TITLE
Conversational AI support for Appwrite

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#551]
I think it would be a really cool feature to have out of the box chat bot support in Appwrite. This would be a great addition once we have our web sockets API ready. I was browsing through some and found an open source chat-bot that is very promising. [Rasa](https://rasa.com/)

Here's what my proposed ideal state would look like. 
* The chat-bot runs in its own container 
* These don't have to be a part of the normal appwrite install ,but can be add-ons that users can install any time (Like Clam-AV). 
* We should have a gallery / browser on appwrite.io that lists all the add-ons you can install with appwrite.
* These add-on containers would be plug and play. Just a single command must spin them up and they must easily talk to the main appwrite containers.  

Let me know your thoughts on this.

**Comment by eldadfux** [comment]
@TorstenDittmann has just talked with me about creating a spec for Appwrite plugins & marketplace. It would be interesting to see how this could fit into the new spec.

**Comment by christyjacob4** [comment]
That's great @eldadfux @TorstenDittmann. Would love to hear more about it 😊

**Comment by TorstenDittmann** [comment]
Any need to keep this open? @christyjacob4
