### ISSUE TITLE
🐛 Bug Report: with Users limited to 1, creating team membership in console gives restricted error

### ISSUE THREAD

**Issue by jhooper04** [appwrite/appwrite#5516]
### 👟 Reproduction steps

1. Auth -> Security, set Users limit to 1.
2. Auth -> Teams, Create a new team
3. Select the new team and select Members tab
4. Press the create membership button
5. Add a new unregistered user email address with any roles/name

### 👍 Expected behavior

It should create the new user for that email address if it doesn't exist (ideally with a confirmation?) even though the user limit is exceeded since it is being created through the console or via an API key.

### 👎 Actual Behavior

It returns an error message "Project registration is restricted. Contact your administrator for more information."
It works as expected if the user/email already exists.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I am using 1.3.4 through the console on a self hosted localhost linux development environment with _APP_ENV=development

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@jhooper04 thanks for creating this issue! 🙏🏼 Let me double check with the team we want this type of behavior.

**Comment by stnguyen90** [comment]
I checked with the team and we agreed this is something we should have.

**Comment by lucifer-Hell** [comment]
hi @stnguyen90  I would be really happy to fix this issue . If possible can you please assign this to me  ?

**Comment by stnguyen90** [comment]
@lucifer-Hell assigned! Thanks for your interest! 🙏

**Comment by lucifer-Hell** [comment]
Hi team just a quick update . It seems that whenever the create event is called for a member to be created the project id which is passed to the register function is not console. Hence it throws the error. Below is the line code which checks the project id : - 
`            if ($limit !== 0 && $project->getId() !== 'console') { // check users limit, console invites are always allowed.
`
I am trying to find out what would be the possible reason for the same.

**Comment by stnguyen90** [comment]
@lucifer-Hell, yes, that is correct. The project ID would be the project ID in which the team membership is being created in.

FYI, you can add a permalink on GitHub and it will render the code. For example:

https://github.com/appwrite/appwrite/blob/953485299a2a4040406cfec290a68f69187ec5e8/app/controllers/api/teams.php#L444

**Comment by lucifer-Hell** [comment]
Hi @stnguyen90 , i have proposal to fix this bug . Rather then relying on` project->getId() ` we can you use the header  `x-sdk-platform` which comes along the request to check whether the incoming request is from console or not. Following is the change that i am thinking of . Please let me know if this seems okay 

`  $platformType=  $request->header('x-sdk-platform', 'default');
            if ($limit !== 0 && $platformType !== 'console') { // check users limit, console invites are allways allowed.
                $total = $dbForProject->count('users', [], APP_LIMIT_USERS);`

Also thanks! for the permalink suggestion I will use the same in my prs from know onwards .

**Comment by stnguyen90** [comment]
> we can you use the header x-sdk-platform which comes along the request

@lucifer-Hell, it's typically not a good idea to rely on client-supplied data like that since the client can send any value it wants.

**Comment by safwanyp** [comment]
This is the current code
https://github.com/appwrite/appwrite/blob/953485299a2a4040406cfec290a68f69187ec5e8/app/controllers/api/teams.php#L441-L455

Can't we simply do something like this?
```php
if (empty($invitee)) { // Create new user if no user with same email found
  $limit = $project->getAttribute('auths', [])['limit'] ?? 0;

  $isPrivilegedUser ? $limit = 0 : null; // <----- I added this line

  if ($limit !== 0 && $project->getId() !== 'console') { // check users limit, console invites are allways allowed.
      $total = $dbForProject->count('users', [], APP_LIMIT_USERS);
      // rest of the code
```

**Comment by stnguyen90** [comment]
@safwanyp, I'd probably leave the limit number rather than modifying it based on `$isPrivilegedUser` for clarity.

**Comment by safwanyp** [comment]
@stnguyen90 Noted, and I did this instead:
```php
if (empty($invitee)) { // Create new user if no user with same email found
  $limit = $project->getAttribute('auths', [])['limit'] ?? 0;

  $shouldCheckLimit = !$isPrivilegedUser && $limit !== 0 && $project->getId() !== 'console';

  if ($shouldCheckLimit) { // check users limit, console invites are allways allowed.
      $total = $dbForProject->count('users', [], APP_LIMIT_USERS);

      if ($total >= $limit) {
          throw new Exception(Exception::USER_COUNT_EXCEEDED, 'Project registration is restricted. Contact your administrator for more information.');
      }
  }
  // rest of the code
```
Instead of modifying `$limit` directly, I created `$shouldCheckLimit` that checks whether the limit should be taken into account or not.

**Comment by stnguyen90** [comment]
@lucifer-Hell, how's your progress on this?

**Comment by ketanbaitule** [comment]
As the previous assignee is not working on it, can you assign it to me

**Comment by ketanbaitule** [comment]
Just realised @stnguyen90 had already got the solution

**Comment by nick2432** [comment]
can i work on this?

**Comment by stnguyen90** [comment]
Unassigning due to inactivity.

@ketanbaitule, @nick2432, are y'all still interested in working on this?

**Comment by ketanbaitule** [comment]
Hi @stnguyen90, I am interested to work on this issue. 

> Unassigning due to inactivity.
> 
> @ketanbaitule, @nick2432, are y'all still interested in working on this?

**Comment by stnguyen90** [comment]
@ketanbaitule, assigned! Thanks for your interest! 🙏
