### ISSUE TITLE
🐛 Bug Report: Users can see stale membership

### ISSUE THREAD

**Issue by singhbhaskar** [appwrite/appwrite#5517]
### 👟 Reproduction steps

* Create a user.
* Create a new team.
* Add the user as team member.
* Delete the Team.
* For the user view Membership.

### 👍 Expected behavior

The membership invite for the deleted team should not be present and the membership should be empty.

### 👎 Actual Behavior

The membership invite shows stale invite which can't be deleted as well.

Screenshot for stale invite:
<img width="1243" alt="Screenshot 2023-05-09 at 11 18 14 AM" src="https://user-images.githubusercontent.com/20492520/237006177-87fc1469-3630-4bab-90bd-dbfa5684f544.png">

Screenshot when deleting the stale invite:
<img width="1243" alt="Screenshot 2023-05-09 at 11 21 33 AM" src="https://user-images.githubusercontent.com/20492520/237006210-4bba4a46-d308-4b63-86c0-f96fdaeb6f39.png">

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Local Docker image.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Thank you for reporting this. I tried reproducing and it does seem like it is true.
