### ISSUE TITLE
🐛 Bug Report: Appwrite cli initializes dart function with old dart_appwrite version

### ISSUE THREAD

**Issue by IronRevelation** [appwrite/appwrite#5521]
### 👟 Reproduction steps

When I create a dart function using the cli, the dart_appwrite version is set to 7.1.0 instead of 8.0.0

### 👍 Expected behavior

It should set the dart_appwrite package version to 8.0.0

### 👎 Actual Behavior

It sets the dart_appwrite package version to 7.1.0

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@IronRevelation, thanks for creating this issue! 🙏🏼 Let me double-check with the team about this.

**Comment by stnguyen90** [comment]
All of our function starters are here: https://github.com/appwrite/functions-starter and it would be a good idea to bump the versions in them.

**Comment by PrinsonF77** [comment]
Hey @stnguyen90 . Can I take on this issue?

**Comment by PoorviShetty** [comment]
Hi, can I be assigned to this issue? I would like to work on it!

**Comment by Haimantika** [comment]
> Hi, can I be assigned to this issue? I would like to work on it!

Hi Poorvi, do you still want to work on it? Can assign this issue to you :)

**Comment by PoorviShetty** [comment]
> Hi Poorvi, do you still want to work on it? Can assign this issue to you :)

Yes, I'm interested

**Comment by Ronakkkkk** [comment]
Please assign if available.

**Comment by Haimantika** [comment]
> > Hi Poorvi, do you still want to work on it? Can assign this issue to you :)
> 
> Yes, I'm interested

Assigned

**Comment by Haimantika** [comment]
> Please assign if available.

Hi, this issue has been assigned to Poorvi since she asked for it before.

**Comment by PoorviShetty** [comment]
Hi, I've created a PR with the changes mentioned by @stnguyen90 
Please review

**Comment by eauw** [comment]
As with appwrite-cli version 4.2.0 the version of dart_appwrite is being set to 8.0.0 in a newly created function instead of 10.1.0

**Comment by stnguyen90** [comment]
Closed by https://github.com/appwrite/functions-starter/pull/64
