### ISSUE TITLE
🐛 Bug Report: query with empty list throws error

### ISSUE THREAD

**Issue by joscha0** [appwrite/appwrite#5522]
### 👟 Reproduction steps

```
await database.listDocuments(
  collectionId: "",
  databaseId: "",
  queries: [Query.equal(r'$id', ids)],
);
```

if `ids` is empty list `[]`-> `AppwriteException: general_unknown, Server Error (500)`

### 👍 Expected behavior

return empty list

### 👎 Actual Behavior

throws error: `AppwriteException: general_unknown, Server Error (500)`

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite Cloud

Flutter SDK `appwrite: ^8.2.2`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@joscha0, thanks for creating this issue! 🙏 Let me check with the team on this.

**Comment by ArslanYM** [comment]
Would love to try this issue. Please assign me

**Comment by stnguyen90** [comment]
We plan to throw 400 if an empty array is passed. This is actually already done and pending merge of https://github.com/utopia-php/database/pull/264. 

@ArslanYM, I suggest looking for issues labeled with "good first issue" if you're looking to contribute.
