### ISSUE TITLE
🐛 Bug Report: Collection-Id does not change if you switch the collection via Tab Bar 

### ISSUE THREAD

**Issue by Vedsaga** [appwrite/appwrite#5523]
### 👟 Reproduction steps

Deploy 1.3.4
Then create two collection and try to switch between the collection via side nav bar

### 👍 Expected behavior

Collection-id for both collection should be diff even when you switch the collection via side nav bar

### 👎 Actual Behavior

You will see the same collection-id for both collection, if you switch the collection via side nav bar.  Till you don't refresh the page

https://github.com/appwrite/appwrite/assets/59083528/aa8f7946-67c1-4d2b-b2d1-ebb027308d12

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

AWS EC2 instance 1.3.4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by yatharth1706** [comment]
Would love to debug and fix this

**Comment by abnegate** [comment]
Closing as fixed in 1.4.x
