### ISSUE TITLE
🐛 Bug Report: Functions are not triggered on file creation

### ISSUE THREAD

**Issue by acalatrava** [appwrite/appwrite#5524]
### 👟 Reproduction steps

Create a function with the `buckets.*.files.*.create` update event.

### 👍 Expected behavior

The function should be executed when a file is created on any bucket.

### 👎 Actual Behavior

Function is not being executed. However it works on other events like `buckets.*.files.*.delete` or `buckets.*.files.*.update`

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by acalatrava** [comment]
I found out what the problem was... It seems that if you have another function that is listening to the same event BUT that function does not have any deployment it will raise the error:
```
Exception: Deployment not found. Create deployment before trying to execute a function in /usr/src/code/app/workers/functions.php:215
Stack trace:
#0 /usr/src/code/app/workers/functions.php(86): FunctionsV1->execute(Object(Utopia\Database\Document), Object(Utopia\Database\Document), Object(Utopia\Database\Database), 'event', NULL, 'buckets.645cbd4...', '{"$id":"645e2ba...', NULL, Object(Utopia\Database\Document))
#1 /usr/src/code/src/Appwrite/Resque/Worker.php(122): FunctionsV1->run()
#2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#5 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('0.1', false)
#6 {main}
```

and therefore it will not continue iterating to the other functions that are listening to the same event.

**Comment by christyjacob4** [comment]
@acalatrava are you facing this issue on the cloud or your self-hosted instance ?

**Comment by acalatrava** [comment]
You're right... This is self hosted and it seems I was running 1.2.1 instead latest version as I thought (I've been messing around with the update)

sorry about that :(

**Comment by christyjacob4** [comment]
No worries @acalatrava Thanks for creating the issue though :) If you need help with the upgrade, feel free to drop us a message on our community discord
