### ISSUE TITLE
🐛 Bug Report:  Error: Query not valid: Attribute not found in schema: ​​$createdAt

### ISSUE THREAD

**Issue by nexmoe** [appwrite/appwrite#5527]
### 👟 Reproduction steps

Use queries like this 
```
[
	aw.Query.greaterThanEqual("​​$createdAt", beginOfDay.getTime()),
	aw.Query.equal("authorId", session.author.userId),
	aw.Query.equal("guildId", session.guildId),
]
```

### 👍 Expected behavior

Run well

### 👎 Actual Behavior

```
 Error: Query not valid: Attribute not found in schema: ​​$createdAt
  at Client.call (*\.pnpm\node-appwrite@9.0.0\node_modules\node-appwrite\lib\client.js:172:31)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Databases.listDocuments (*\.pnpm\node-appwrite@9.0.0\node_modules\node-appwrite\lib\services\databases.js:1613:16)
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by nexmoe** [comment]
![image](https://github.com/appwrite/appwrite/assets/16796652/c9386274-0be5-4a38-a032-d3bae2201477)

**Comment by abnegate** [comment]
Hey, thanks for your report! This looks like a bug, I will investigate and add any updates here :+1:

**Comment by Chinedu19** [comment]
Any updates on this?

**Comment by stnguyen90** [comment]
@nexmoe, it looks to be working as expected for me now on Cloud (1.4.13):

![image](https://github.com/appwrite/appwrite/assets/1477010/31c43889-c00b-4bb8-8dde-ceff6fe775c9)

Are you still seeing a problem?
