### ISSUE TITLE
🐛 Bug Report: migration fails with Allowed memory size exhausted php memory_limit hardcoded to 512

### ISSUE THREAD

**Issue by bfritscher** [appwrite/appwrite#5528]
### 👟 Reproduction steps

Run a migration fails upgrading audit data, with out of memory

### 👍 Expected behavior

Expect the migration to work.
Or at least be able to specify a higher php memory_limit via environnment without the need to edit the app/init.php hardcoded value: `ini_set('memory_limit', '512M'); `

### 👎 Actual Behavior

fails with php out of memory error

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

docker self hosted

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@bfritscher thanks for raising this issue! 🙏🏼 Interesting challenge... 🧐 

For now, I would suggest either modifying this:

https://github.com/appwrite/appwrite/blob/181741d7a2082f5c9d3ca727384601f3cf75e5bf/app/init.php#L15

before running the migrate command.

**Comment by stnguyen90** [comment]
@bfritscher, did the suggestion work for you?

**Comment by bfritscher** [comment]
@stnguyen90 Thanks for following up. Yes, it is the workaround I described (and used) in my initial report, as well as the possible solution which would be to replace the hardcoded value with an environment variable. Another would be to identify which part of the migration process uses too much memory.

**Comment by bfritscher** [comment]
Hi, @stnguyen90  the fix is only the workaround? Or do you plan to implement any of the above suggestions or any other fix?
