### ISSUE TITLE
🐛 Bug Report:  Cache issue on storage bucket

### ISSUE THREAD

**Issue by 2002Bishwajeet** [appwrite/appwrite#5529]
### 👟 Reproduction steps

 -  Upload an image to a bucket with a custom id (say test)
 -  Delete that image from the bucket and add a different image but with the same id (test),

### 👍 Expected behavior

Should show a different image now

### 👎 Actual Behavior

Shows the old image

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

nil

### 🧱 Your Environment

nil

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by 2002Bishwajeet** [comment]
cc @Meldiron

**Comment by stnguyen90** [comment]
@2002Bishwajeet, thanks for creating this issue! 🙏🏼 How are you testing this? Would you please make sure to clear your client side cache?

**Comment by 2002Bishwajeet** [comment]
Manual Testing
![appwrite_issue](https://github.com/appwrite/appwrite/assets/62933155/ad615f59-f688-426d-b79a-a9878a527003)

**Comment by stnguyen90** [comment]
@2002Bishwajeet, thanks for the gif! Would you please try to clear your cache after deleting the file and then see if the preview shows correctly after uploading the new file?

**Comment by 2002Bishwajeet** [comment]
@stnguyen90 Still the same issue. After deleting the file, I cleared my cache, and the issue was the the same as above.
