### ISSUE TITLE
🐛 Bug Report: Cannot set default value for ENUM atrribute, when set to required

### ISSUE THREAD

**Issue by safwanyp** [appwrite/appwrite#5533]
### 👟 Reproduction steps

- Create an attribute of type **_ENUM_** in any collection
- Enter the key and elements as needed
- Set the attribute to **_Required_**
- Select any value in the _**Default Value**_ dropdown
- 

### 👍 Expected behavior

The value of the dropdown item should be set to the selected item's value.

### 👎 Actual Behavior

Upon selecting an item in the dropdown, the dropdown closes and no value is selected. Since the _**Required**_ flag is checked, clicking _**Create**_  shows an error under the dropdown saying _**This field is required**_.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

- Appwrite v1.3.1
- Using the console to create an _**ENUM**_ attribute

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by safwanyp** [comment]
https://github.com/appwrite/appwrite/assets/19154530/d24dc074-dce7-4379-afaa-a1019a500c25

**Comment by Vedsaga** [comment]
Using `1.3.4` and can confirm it's not letting you set the default value if you marked required but, if you don't mark required then it does let you set the value.

**Comment by abnegate** [comment]
@Vedsaga Yep that is expected behaviour, when an attribute is required, you cannot set a default. The default is used when an attribute is not required, and is not included in the document

@safwanyp Yep this is fixed in 1.3.4 :grin:
