### ISSUE TITLE
🐛 Bug Report: Build Function Failed

### ISSUE THREAD

**Issue by whenSunSet** [appwrite/appwrite#5534]
### 👟 Reproduction steps

When i build function with appwrite CLI

### 👍 Expected behavior

build success

### 👎 Actual Behavior

i got an error like this: 

Docker Error: npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/proxy-from-env/-/proxy-from-env-1.1.0.tgz failed, reason: connect ETIMEDOUT 104.16.25.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-05-14T12_57_22_966Z-debug-0.log

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.1

Ubuntu 16

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by whenSunSet** [comment]
How can I package a Function for Appwrite and add a proxy to it?

**Comment by christyjacob4** [comment]
@whenSunSet what dependencies are you using in your function ? Also are you on Appwrite Cloud or a self-hosted instance of Appwrite ? 

To your second question, you can learn to setup a proxy for Appwrite functions here https://dev.to/appwrite/start-selling-online-using-appwrite-and-stripe-3l04

**Comment by Haimantika** [comment]
@whenSunSet did this help?

> @whenSunSet what dependencies are you using in your function ? Also are you on Appwrite Cloud or a self-hosted instance of Appwrite ?
> 
> To your second question, you can learn to setup a proxy for Appwrite functions here https://dev.to/appwrite/start-selling-online-using-appwrite-and-stripe-3l04

**Comment by stnguyen90** [comment]
Closing stale issue
