### ISSUE TITLE
🚀 Feature: Go language support for Functions

### ISSUE THREAD

**Issue by caevv** [appwrite/appwrite#5535]
### 🔖 Feature description

Support Functions for Golang.

### 🎤 Pitch

Go is one of the best server-side languages for building microservice applications and writing servers. With the support of Appwrite, Golang's service creation will become much more streamlined.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
@caevv We have a Go runtime ready here https://github.com/open-runtimes/open-runtimes/tree/main/runtimes/go-1.19

It will be activated in the next Appwrite version :)

**Comment by caevv** [comment]
That's awesome. Thanks!

**Comment by stnguyen90** [comment]
Looks like the go runtime needs to be:

* [ ] upgraded to the new version of open runtimes
* [ ] added to appwrite

**Comment by Tadjaur** [comment]
Hi @stnguyen90 i would like to do the first task but I'm pretty new. 
Can you give me a first step of where to start?

**Comment by 9cat** [comment]
golang  +1

**Comment by stnguyen90** [comment]
Closing this as a duplicate of https://github.com/appwrite/appwrite/issues/2784. Please make sure to add a 👍🏼 to https://github.com/appwrite/appwrite/issues/2784
