### ISSUE TITLE
🐛 Bug Report: x-appwrite-id should disallow unique()

### ISSUE THREAD

**Issue by Suven-p** [appwrite/appwrite#5542]
### 👟 Reproduction steps

When passing `unique()` to `x-appwrite-id` header with CreateFile endpoint, the request completes successfully but breaks stuff on appwrite's side.

### 👍 Expected behavior

Return an error.

### 👎 Actual Behavior

Request completes successfully. The uploaded file can't be accessed, modified or deleted.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Suven-p, thanks for raising this issue! 🙏🏼 It looks like we should add some validation to prevent malformed file ids passed in the x-appwrite-id header:

https://github.com/appwrite/appwrite/blob/953485299a2a4040406cfec290a68f69187ec5e8/app/controllers/api/storage.php#L447

**Comment by Suven-p** [comment]
@stnguyen90 Could you assign this to me?
