### ISSUE TITLE
🐛 Bug Report: Invalid evaluation of oauth redirect_uri protocol in case of reverse proxy/http client

### ISSUE THREAD

**Issue by NotNullDev** [appwrite/appwrite#5545]
### 👟 Reproduction steps

Create web app and install web sdk.

Access app via browser and invoke Account.createOAuth2Session("google", "...", "....") (make sure we are using http not https)

### 👍 Expected behavior

Evaluation of the protocol is based API Endpoint which is available in the Dashboard settings -> Overview -> API Credentials

### 👎 Actual Behavior

TLDR: redirect_uri passed to the provider starts with http:// instead of https://

After calling createOAuth2Session metod in web sdk, in the account.php file we are creating callback url with protocol of request host, which can differ from the protocol which is used by a server. 

I created web app which uses appwrite web sdk. My web application is running on **http**://localhost:5173.
I deployed appwrite on the VPS, and my domain support https protocol (I can connect via https to the dashboard, calls from sdk are returning 401 error codes).

My client configuration (replaced my domain with example.com):
`new Client().setEndpoint('https://appwrite.example.com/v1').setProject('12345');`

I suspect it can be due this line:
https://github.com/appwrite/appwrite/blob/953485299a2a4040406cfec290a68f69187ec5e8/app/controllers/api/account.php#L285

If application is deployed behind reverse proxy, the connection between reverse proxy and appwrite will be unencrypted, via http, so in this case the redirect_uri will be always invalid.

![400_google](https://github.com/appwrite/appwrite/assets/61083452/a76f8118-7347-4084-abab-28bed3c3e648)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@NotNullDev, thanks for creating this issue! 🙏🏼 

> If application is deployed behind reverse proxy, the connection between reverse proxy and appwrite will be unencrypted

I would actually recommend proxying to Appwrite using HTTPS to correct this problem.

**Comment by stnguyen90** [comment]
@NotNullDev, did you get a chance to try my recommendation? FYI, I'll need to close this soon due to inactivity.
