### ISSUE TITLE
 Bug Report: Search for a user by email which have underscore "_" with no results

### ISSUE THREAD

**Issue by hugebug4ever** [appwrite/appwrite#5546]
### 👟 Reproduction steps

When I search a user by email, the email name have underscore inside the name, there is no result returned.

![image](https://github.com/appwrite/appwrite/assets/846278/921e7912-1b7c-4320-ad4c-9fc8f2e6813b)

It's different with the non-bug issue [here](https://github.com/appwrite/appwrite/issues/3173)
The search is already quoted by "

### 👍 Expected behavior

the search should return the user with the specified email

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/846278/6423775d-0b9c-4382-b7ea-e88b8295ef65)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hey! Thanks for bringing this to our attention. I tried reproducing and looking into it and have passed on this to my team. I will get back to you, soon!

**Comment by joeyouss** [comment]
A PR is on the way for the fix! https://github.com/utopia-php/database/pull/279

**Comment by sunjianan9900** [comment]
Searching under fulltxt index, the problem still exists (1.3.7)

**Comment by sunjianan9900** [comment]
Can be tested on a running website "pubdev.top" , and search 'stack_art_board' and 'stack'

the des in this document is:

stack_art_board||*|A Flutter package consisting of stacks that allows adding any widgets, and enables editing, deleting, and changing the order of layers.

Query.search("des", "stack_art_board") ==> no this document
Query.search("des", "stack") ==> got this document

![image](https://github.com/appwrite/appwrite/assets/10936316/c9d0450e-63d6-4305-8e7b-7428008d194e)
![image](https://github.com/appwrite/appwrite/assets/10936316/dc71308c-c1c3-4a41-9bd8-fddb6a9a45de)
