### ISSUE TITLE
Bug Report: The To-do app does not seem to work  

### ISSUE THREAD

**Issue by djv03** [appwrite/appwrite#5548]
### 💭 Description: the demo to-do app in documentation is not working

the demo to-do app in documentation is not working
![image](https://github.com/appwrite/appwrite/assets/93385841/2779e6f7-6bcf-476a-b408-4f552c62f7dd)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi - the to-do list seems to work for me. Maybe you might have tried too many times and gotten rate limited? Can you try clearing browser cache history and then access the to-do app again?

**Comment by joeyouss** [comment]
Hi @djv03 , if this is resolved, shall I close this?

**Comment by djv03** [comment]
ok sure!
