### ISSUE TITLE
🚀 Feature: Allow resuming interrupted upload to CreateFile endpoint

### ISSUE THREAD

**Issue by Suven-p** [appwrite/appwrite#5549]
### 🔖 Feature description

Allow resuming upload when an upload of a file is interrupted due to network issues or user pressing cancel button. The existing implementation for Python SDK provides a possible implementation by using x-appwrite-id header.

### 🎤 Pitch

This would be used to restart a failed upload. Having incomplete uploads wastes storage space. For most cases using a random file id, retrying the upload is the solution.  This might be a problem when using a custom id derived from other values. For example, when using a user's ID as a file ID to store their profile picture, any subsequent upload fails and the response body is very cryptic.
```
<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchUpload</Code><BucketName>cloud-fra1-prd-storage-2</BucketName><RequestId>tx0000000000000191d7e7a-0064650242-9655fb53-fra1b</RequestId><HostId>9655fb53-fra1b-fra1-zg02</HostId></Error>
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Suven-p** [comment]
For reproduction, I manually interrupt the upload process with a debugger and use:

```python
from appwrite.client import Client
from appwrite.input_file import InputFile
from appwrite.services.storage import Storage

client = Client()

(client
  .set_endpoint('https://cloud.appwrite.io/v1') # Your API Endpoint
  .set_project('testsdk') # Your project ID
  .set_key('api_key') # Your secret API key
)

storage = Storage(client)

result = storage.create_file(
    "testBucket",
    "6464fcd0546c5acd6237",
    InputFile.from_path('8MBFile.txt'),
)
print(result)
```
to trigger the exception.

**Comment by joeyouss** [comment]
Thank you for opening this following our discord discussion, appreciate it!

**Comment by stnguyen90** [comment]
@Suven-p, this should actually be possible since [0.14](https://github.com/appwrite/sdk-generator/pull/402). You'll need to use the same file ID and file and it should resume from where it left off (based on the chunks).
