### ISSUE TITLE
🐛 Bug Report: Session Limit (Cloud)

### ISSUE THREAD

**Issue by akinabudu** [appwrite/appwrite#5555]
### 👟 Reproduction steps

When I clicked on the update button of the "Session limit" using the cloud server
![sessions_Limit_button](https://github.com/appwrite/appwrite/assets/89635879/51fa02e6-5529-41b9-9546-0b212316dc09)

### 👍 Expected behavior

It should accept a number/ integer and display success.

### 👎 Actual Behavior

It displays an
![Sessions Limit](https://github.com/appwrite/appwrite/assets/89635879/397348d6-0d69-43b6-ad32-714891b24422)
 Error alert: "Invalid method...". See Attachment

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi
This is a known bug and our team is working on fixing this internally. This should be fix when cloud is upgraded which shall happen soon enough.
Thanks for opening this!

**Comment by joeyouss** [comment]
Closing this issue since it is fixed for newer versions and shall be reflected in Cloud once updated.
