### ISSUE TITLE
Feature Request: Document change listener

### ISSUE THREAD

**Issue by offline-first** [appwrite/appwrite#556]
It would be great to have a snapshot listener for documents like in firebase

**Comment by drosa88** [comment]
Would this be possible? Seems like a very helpful feature.

By the way: thanks for your great work! I'm going to try appwrite for my current Flutter project and the first look is amazing 👍

**Comment by kodumbeats** [comment]
Our Realtime API is under development right now! :) You can check out the work on the feature branch: 
https://github.com/appwrite/appwrite/tree/feat-265-realtime

With this feature, you'll be able to subscribe to documents and receive realtime updates when they change.

**Comment by TorstenDittmann** [comment]
Gonna close this issue in favor of #265
