### ISSUE TITLE
🐛 Bug Report: Environment Variables Are Not Detected 

### ISSUE THREAD

**Issue by leotj** [appwrite/appwrite#5564]
### 👟 Reproduction steps

When a scheduled function with a set of environment variables is executed, the function does not detect the environment variables.

### 👍 Expected behavior

Environment variables should be detected on the manual and scheduled trigger event

### 👎 Actual Behavior

Environment variables are detected only on the manual trigger.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

cloud.appwrite.io

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi - thank you for opening this. We are aware of this issue and are working on a fix for this.
