### ISSUE TITLE
Links in "add-oauth2-provider.md" file aren't working

### ISSUE THREAD

**Issue by NidhxGupta** [appwrite/appwrite#557]
Hey!
So I was going through the add-oauth2-provider.md file to contribute by Adding a New OAuth2 Provider. 
![Screenshot 2020-09-25 at 2 37 51 PM](https://user-images.githubusercontent.com/56179878/94248882-b9e2f180-ff3c-11ea-9cf7-099095a8ca22.png)

I found out that the CODE OF CONDUCT link does not link to the right page.
![CodeOfConduct](https://user-images.githubusercontent.com/56179878/94247675-1513e480-ff3b-11ea-9a6d-a39be173bbe3.png)

Even the CONTRIBUTING GUIDE link doesn't link to the right page.
![ContributingGuide](https://user-images.githubusercontent.com/56179878/94247687-18a76b80-ff3b-11ea-8a20-f5d6802482ac.png)

I would like to take up this issue and correct the links to point to the right pages.
This will help the other contributors as well.

Can you please confirm if these are the right links for:-

1) CODE OF CONDUCT -> https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md

2) CONTRIBUTING GUIDE ->https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md

Thanks

**Comment by eldadfux** [comment]
Hey @NidhxGupta, I assigned you with the issue 👍🏻

**Comment by NidhxGupta** [comment]
Hey @eldadfux,
I have made the necessary changes and made a pull request #558 doc-577-corrected-links-in-"add-oauth2-provider.md"-file
