### ISSUE TITLE
📚 Documentation: Error in the  Python SDK Syntax In the docs

### ISSUE THREAD

**Issue by akashgreninja** [appwrite/appwrite#5581]
### 💭 Description

![appwrite one](https://github.com/appwrite/appwrite/assets/84433561/d89902fa-db92-432f-8b62-772a9b142c76)

There is an extra bracket at the end of the API key Section of the Appwrite Python SDK 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
👀 Good catch. That's definitely not right, assigning to myself.

Although it's actually missing a bracket in front, I'll open a PR.

**Comment by akashgreninja** [comment]
@gewenyu99 actually there is one more thing there exists no query docs for Python SDK right ? Or didn't I search properly 
because in many online forums its 
`from appwrite.queries import Query`

but when I went through the module files it is supposed to be 
`from appwrite.query import Query`

there are no use cases or examples as well if this does not exist and if its possible can you assign me the issue I would like to work on this issue in the documentation

**Comment by gewenyu99** [comment]
> there are no use cases or examples as well if this does not exist and if its possible can you assign me the issue I would like to work on this issue in the documentation

Yeah we don't include examples for the server SDKs at the moment, we just have too many and their signatures/use cases are similar enough we haven't gotten to them yet.

If you'd like to work on this issue, I'll assign it to you :)

**Comment by gewenyu99** [comment]
https://github.com/appwrite/docs/pull/373
