### ISSUE TITLE
📚 Documentation: Better Readability of the Python SDK create Database 

### ISSUE THREAD

**Issue by akashgreninja** [appwrite/appwrite#5582]
### 💭 Description

The syntax of the code you provided seems to have a minor error. Instead of using parentheses to wrap the client object and chaining the method calls, you can use backslashes "" to continue the lines for better readability. Here's the corrected code:
![better appwrite](https://github.com/appwrite/appwrite/assets/84433561/b6724446-3367-4ec8-8cd8-38386bba0760)

```
from appwrite.client import Client
from appwrite.services.databases import Databases

client = Client() \
    .set_endpoint('https://cloud.appwrite.io/v1')  # Your API Endpoint \
    .set_project('5df5acd0d48c2')  # Your project ID \
    .set_key('919c2d18fb5d4...a2ae413da83346ad2')  # Your secret API key

databases = Databases(client)

result = databases.create('[DATABASE_ID]', '[NAME]')

```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
Hi, what your suggesting will result in this:
```py
/*/PythonProject/venv/bin/python /*/test.py 
  File "/*/test.py", line 6
    .set_project('5df5acd0d48c2')  # Your project ID \
IndentationError: unexpected indent

Process finished with exit code 1
```

You can trail or append comments after or before backticks.

**Comment by akashgreninja** [comment]
```

from appwrite.client import Client
from appwrite.services.databases import Databases

client = Client() \
    .set_endpoint('https://cloud.appwrite.io/v1') \
    .set_project('5df5acd0d48c2') \
    .set_key('919c2d18fb5d4...a2ae413da83346ad2')  

databases = Databases(client)

result = databases.create('[DATABASE_ID]', '[NAME]')

```

sorry this is the better code

**Comment by gewenyu99** [comment]
> ```
> 
> from appwrite.client import Client
> from appwrite.services.databases import Databases
> 
> client = Client() \
>     .set_endpoint('https://cloud.appwrite.io/v1') \
>     .set_project('5df5acd0d48c2') \
>     .set_key('919c2d18fb5d4...a2ae413da83346ad2')  
> 
> databases = Databases(client)
> 
> result = databases.create('[DATABASE_ID]', '[NAME]')
> ```
> 
> sorry this is the better code

Comments are important here for us. While this is definitely better looking code, I think it's less useful for readers :)
