### ISSUE TITLE
🐛 Bug Report: Incompatibility with Google Fonts (Flutter)

### ISSUE THREAD

**Issue by riDuxd** [appwrite/appwrite#5583]
### 👟 Reproduction steps

Add the appwrite and google fonts dependency into the pubspec.yaml

### 👍 Expected behavior

It should get all the necessary dependencies required for appwrite

### 👎 Actual Behavior

However, I get a:

```
Because no versions of google_fonts match >4.0.5 <5.0.0 and google_fonts 4.0.5 depends on http ^1.0.0, google_fonts ^4.0.5 requires http ^1.0.0.
And because appwrite >=7.0.0 depends on http ^0.13.5, google_fonts ^4.0.5 is incompatible with appwrite >=7.0.0.
So, because login depends on both appwrite ^9.0.0 and google_fonts ^4.0.5, version solving failed.
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by SoumyadeepOSD** [comment]
Can I work on it?

**Comment by 2002Bishwajeet** [comment]
@riDuxd as a workaround, you can downgrade the google fonts package. According to their changelogs, there isn't any difference in the previous and the latest version (https://pub.dev/packages/google_fonts/changelog)

**Comment by riDuxd** [comment]
> @riDuxd as a workaround, you can downgrade the google fonts package. According to their changelogs, there isn't any difference in the previous and the latest version (https://pub.dev/packages/google_fonts/changelog)

I'll do that for now then.
