### ISSUE TITLE
Feature required: SHA certificate fingerprints for Appwrite Apps

### ISSUE THREAD

**Issue by TechComet** [appwrite/appwrite#5594]
### 🔖 Feature description

Hi,

SHA certificate fingerprints for Appwrite Apps

...

**Comment by joeyouss** [comment]
Hi
Can you please elaborate a bit more?

**Comment by TechComet** [comment]
https://developers.google.com/android/guides/client-auth

It's check if this your app or not

---------------------------------------

Obtaining the SHA hash of your signing certificate can be useful in several scenarios:

1. Android App Signing: When publishing an Android app on the Google Play Store, you need to generate a signing certificate and provide its SHA-1 hash to Google. This hash is used to verify the authenticity and integrity of your app. Google Play Services use this hash to ensure that future updates to your app are signed with the same certificate.

2. API Authentication: Some APIs or services require you to register your application and provide the SHA-1 or SHA-256 hash of your signing certificate as part of the authentication process. This ensures that only authorized applications can access the API or service.

3. Certificate Validation: The SHA hash of a certificate can be used to verify its authenticity. By comparing the hash obtained from the certificate with the one provided by the issuer or relying party, you can ensure that the certificate has not been tampered with or modified.

4. Troubleshooting: In certain situations, such as debugging or resolving certificate-related issues, you may need to examine the details of your signing certificate, including its SHA hash. This information can help you diagnose problems and ensure that the correct certificate is being used.

Remember that the specific use case for obtaining the SHA hash of your signing certificate may vary depending on the platform or service you are working with. It is always best to consult the documentation or guidelines provided by the platform or service provider to understand their requirements regarding certificate validation and authentication.

**Comment by TechComet** [comment]
see (5) and (7), (8)

**Comment by stnguyen90** [comment]
@TechComet, thanks for raising this, but this looks like a duplicate of https://github.com/appwrite/appwrite/issues/4791. As such, can you 👍🏼 the other issue and close this as a duplicate?

**Comment by TechComet** [comment]
yes it's duplicate .. but this for Android Devices .. I Close it.
