### ISSUE TITLE
📚 Documentation: Relationships not found as an attribute in console as mentioned in docs

### ISSUE THREAD

**Issue by HeadQuaters** [appwrite/appwrite#5599]
### 💭 Description

The relationship type cannot be found under the list of document attribute types as mentioned in the documentation

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi
Any chance you are using Cloud?

**Comment by jontstaz** [comment]
> Hi
> Any chance you are using Cloud? Cloud is still on 1.1.2 and needs updating. Relationships were introduced in 1.3, hence are not available in Cloud

Hi,

Do you know when Cloud will be updated to support relationships? Thanks in advance.

**Comment by joeyouss** [comment]
Hi @jontstaz , we do not have a date yet , but we are working on it

**Comment by stnguyen90** [comment]
@HeadQuaters, is there anything else you need? FYI, we'll need to close this soon due to inactivity.
