### ISSUE TITLE
🚀 Feature: Turn off Rate-Limiting for user auth in functions

### ISSUE THREAD

**Issue by manol-o** [appwrite/appwrite#5614]
### 🔖 Feature description

Hi, 
right now you can't use the email user auth in the users api for checking if a user is valid in a appwrite function, because you hit rate limiting very soon.
It  would be perfect if you can turn off the checking _internally_ for functions. this way you could still stay "safe", and know, that you need your own abuse checking if you use those functions. 
Right now it seems like I have to turn off rate limiting in general, which somehow feels bad.

Best,
manolo 

### 🎤 Pitch

Could be some setting in the api. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
> right now you can't use the email user auth in the users api for checking if a user is valid in a appwrite function, because you hit rate limiting very soon.

Could you please clarify what you're trying to do? 🧐

**Comment by manol-o** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}sorry you can delete this issue, when I wrote this I didn't know that you can turn of auth rate limiting in the settings file for dev reasons. 
Have a good day!
 

Steven wrote on 04.08.2023 17:53 (GMT +02:00):


right now you can't use the email user auth in the users api for checking if a user is valid in a appwrite function, because you hit rate limiting very soon.

Could you please clarify what you're trying to do? 🧐
