### ISSUE TITLE
Add Example Response in appwrite.io docs

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#562]
It would be really useful to have an example response along with the example request on appwrite.io 
![Screenshot 2020-09-27 at 2 48 08 AM](https://user-images.githubusercontent.com/20852629/94350429-e184a780-006b-11eb-8deb-4b4501feb1d5.png)

I'd like to take up this issue.

**Comment by eldadfux** [comment]
Duplicated with #381. Closing this one, and assigning you to the previous issue.

**Comment by christyjacob4** [comment]
Awesome @eldadfux 👍
