### ISSUE TITLE
🐛 Bug Report: After upgrading from v1.3.4 to v1.3.5, on refresh, I get 404 not found on the console.

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#5623]
### 👟 Reproduction steps

I get 404 not found on the console when I refresh the page.

```json
{
  "message": "Not Found",
  "code": 404,
  "type": "general_route_not_found",
  "version": "1.3.5"
}
```

### 👍 Expected behavior

The console should work fine after refreshing the page.

### 👎 Actual Behavior

It actually showed 404 not found after refreshing the page.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
Upvote+ 
When accessing the console in the base URL `https://slef-hosted.appwrite/console` then the SPA navigation works perfectly. 
But when trying to access any deep spa URL `console` like this for example
`https://slef-hosted.appwrite/console/organization-63e048deb2d5ae084a90` 
I get the 404 error.

From what I see the error could be here 
https://github.com/utopia-php/framework/commit/e8e12a880539679010b86576e843be9f4c7f3329
As this check can't be `true` in the console.
```php
if (\substr_count($routeUrl, '/') !== \substr_count($url, '/')) {
                continue;
            }
```

Here are values for example:
```php
<?php

$url = 'https://cloud.appwrite.io/console/organization-someId';
$routeUrl = 'https://cloud.appwrite.io/console';

var_dump(substr_count($routeUrl, '/')); // 3

var_dump(substr_count($url, '/')); // 4
```

**Comment by wilhantian** [comment]
> 点赞+ 在在基本中访问控制台时`https://slef-hosted.appwrite/console`，spa导航导航可以运行。 但是但是但是当尝试尝试访问访问任何任何`console`这样这样这样的的的的深层的深层深层深层深层深层深层深层 `https://slef-hosted.appwrite/console/organization-63e048deb2d5ae084a90` 深层的的
> 
> 据我所知，错误可能在这里 [utopia-php/framework@ e8e12a8](https://github.com/utopia-php/framework/commit/e8e12a880539679010b86576e843be9f4c7f3329) 因为这个检查不能`true`在控制台中。
> 
> ```
> if (\substr_count($routeUrl, '/') !== \substr_count($url, '/')) {
>                 continue;
>             }
> ```
> 
> 但是当开始时加载`console`路径自然后导航到 JS 并且它一直有效直接到页面刷新。
> 
> Ps 以下是值得说明的例子：
> 
> ```
> <?php
> 
> $url = 'https://cloud.appwrite.io/console/organization-someId';
> $routeUrl = 'https://cloud.appwrite.io/console';
> 
> var_dump(substr_count($routeUrl, '/')); // 3
> 
> var_dump(substr_count($url, '/')); // 4
> ```

You're right. When applying for an SSL certificate, there is the same issue here

**Comment by joeyouss** [comment]
The fix will be done today, thanks for opening this!

**Comment by byawitz** [comment]
> It was fixed in version `1.3.6` https://github.com/appwrite/appwrite/releases/tag/1.3.6
> Upgrade to version `1.3.6`

It was fixed in version 1.3.6 https://github.com/appwrite/appwrite/releases/tag/1.3.6
Upgrade to version 1.3.6

**Comment by byawitz** [comment]
> even im facing the same issue while using the oauth

It was fixed in version 1.3.6 https://github.com/appwrite/appwrite/releases/tag/1.3.6
Upgrade to version 1.3.6

**Comment by rohankm** [comment]
> > even im facing the same issue while using the oauth
> 
> It was fixed in version 1.3.6 https://github.com/appwrite/appwrite/releases/tag/1.3.6 Upgrade to version 1.3.6

even after upgrading I'm getting the same 404 error

**Comment by byawitz** [comment]
> How to use the fixed version for flutter SDK?

The fix is for the Appwrite server part. the flutter SDK stayed the same.

**Comment by shatanikmahanty** [comment]
> > How to use the fixed version for flutter SDK?
> 
> The fix is for the Appwrite server part. the flutter SDK stayed the same.

I am getting the same error in flutter client side while using appwrite cloud

**Comment by byawitz** [comment]
The real version on the cloud is `1.1.2` and I think they're going to be another quick fix that will fix that.

**Comment by shatanikmahanty** [comment]
> The real version on the cloud is `1.1.2` and I think they're going to be another quick fix that will fix that.

Alright. Thanks for the update.

**Comment by Haimantika** [comment]
Hi @usamashafiqs are you still facing this issue? We had a fix rolled out recently.
