### ISSUE TITLE
🐛 Bug Report: can't import certain python built-ins for functions 

### ISSUE THREAD

**Issue by Ananya2001-an** [appwrite/appwrite#5626]
### 👟 Reproduction steps

I did a manual deployment and this was my main.py file: (took from the docs)

If I remove the requests module it works else not :(

```python
import random
import requests

def main(req, res):
  payload = req.payload or 'No payload provided. Add custom data when executing function.'

  secretKey = req.variables.get(
    'SECRET_KEY',
    'SECRET_KEY variable not found. You can set it in Function settings.'
  )

  randomNumber = random.random()

  trigger = req.variables['APPWRITE_FUNCTION_TRIGGER']

  return res.json({
    'message': 'Hello from Appwrite!',
    'payload': payload,
    'randomNumber': randomNumber,
    'trigger': trigger
  })
```

### 👍 Expected behavior

I am trying to implement a function where on event trigger like collection update I will send some data to a server but I noticed that it's failing every time....on doing a bit of trial and error I realized that it's not allowing me to import 'requests' module....without it everything works fine...

### 👎 Actual Behavior

It's failing because of the requests import...  

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite cloud functions with Python runtime

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
Hi, requests is not a built in library/system library from Python.

You can use a `requirements.txt` to install it
https://pypi.org/project/requests/

**Comment by Ananya2001-an** [comment]
Thanks @gewenyu99 I actually resolved it from the official discord support channel and it works now :) thnx again...I will close it now
