### ISSUE TITLE
🚀 Feature: Ability to seperate ids from get, update, create, delete document methods [Flutter]

### ISSUE THREAD

**Issue by shatanikmahanty** [appwrite/appwrite#5627]
### 🔖 Feature description

The current method in flutter to getDocument

I have abstracted databases in my code. _apiClient.databases returnes `Databases(Client())`.

```dart
final document = await _apiClient?.databases.getDocument(
        databaseId: DataBaseIdHelper().getId(),
        collectionId: 'users',
        documentId: sessionInfo.userId,
      );
```

Although this works flawlessly, in a scenario where I need to call the user collection multiple time I lack the ability to create a reusable Collection object which could just take a documentId and work.

This can be done manually by the developer by creating a helper class that will provide a method to call getDocument with documentId while letting the user store databaseId and collectionId beforehand. But that will be writing additional boilerplate.

Eg: Firebase uses a similar structure -> `final userCollection = FirebaseFirestore.instance.collection('users');` -> This way the userCollection is reuasble

### 🎤 Pitch

This will be a big step towards helping developers writing DRY code by allowing them to seperate responsibility of setting database id, collection id and document id through a separate function.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @shatanikmahanty 

Thank you for sharing your thoughts.
We did experiment with a similar approach in the past. But, we found that it sometimes goes against some of our established patterns and can inadvertently introduce unexpected bugs. Given that experience, we're inclined to maintain the current structure for now.

That being said, I truly appreciate your insights and the depth of your suggestion. For the time being, I'll be closing this suggestion, but please continue to share any other ideas or feedback you have in the future!

Thank you for understanding!
