### ISSUE TITLE
🐛 Bug Report: AppwriteException: Not Found

### ISSUE THREAD

**Issue by iota-008** [appwrite/appwrite#5644]
### 👟 Reproduction steps

- Calling `createEmailSession` with email and password
- Also same error with `account.get()` method
![image](https://github.com/appwrite/appwrite/assets/46680697/58d2fa35-d512-477b-a1b4-5765c32590b7)
![image](https://github.com/appwrite/appwrite/assets/46680697/bc5aea27-1f84-4a4d-9529-b8e1bfc9a757)
![image](https://github.com/appwrite/appwrite/assets/46680697/7d5b9e77-dd74-49ef-b717-7fdba62c5258)
![image](https://github.com/appwrite/appwrite/assets/46680697/91aa63cf-8b1b-450c-95d5-5b19174cf8aa)

- It was working fine till yesterday evening, suddenly getting this error.
### 👍 Expected behavior

A new session should be created as the email and password are correct and the user is there in the project.

### 👎 Actual Behavior

AppwriteException: Not Found

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite version: 1.1.2
package version: "appwrite": "^11.0.0",
Not customized 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @iota-008 I looked into this - can you please try it once again and let me know if it works now?

**Comment by Haimantika** [comment]
Hi @iota-008 👋 is it working for you now?

**Comment by iota-008** [comment]
Yes working
