### ISSUE TITLE
🐛 Bug Report: Session Doesn't Persist on Flutter Web

### ISSUE THREAD

**Issue by teneon** [appwrite/appwrite#5645]
### 👟 Reproduction steps

Hi,

i am using Flutter SDK

I have email/pass authentication added, so i can login, logout etc. Everything works fine on Android emulator, but when i start the project in Web (Chrome) there is an issue. 

1. When app starts it points me to the LoginScreen
2. Open developer tools in Chrome and check for errors. There are none for now.
3. I login with correct credential and i am routed (go_router) to HomeScreen
4. Now two errors occur:
**1st error:** Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute
**2nd error:** Mark cross-site cookies as Secure to allow setting them in cross-site contexts

best regards,
Jim

### 👍 Expected behavior

I was searching issues and also docs on AppWrite, but i could not find a solution for this issue. Perhaps it is something simple that is either not yet well documented or i couldn't find it.

### 👎 Actual Behavior

On android emulator, i can restart the app (or even stop it and re-run it) and i get right back into HomeScreen as expected since i was already logged in and session is persistent as it should be.

But when i start the project on web device (chrome), then session is not 
persistent. It always positions me at the LoginScreen  when i stop and re-run the project (even though i am logged in). I guess it is not persistent, because of the cookie issues i have described above? 

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite: ^9.0.0
appwrite console is version 1.3.3 ,locally installed while in development (later will be cloud)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Thanks for bringing this up @teneon . @gewenyu99 can you look into this?

**Comment by gewenyu99** [comment]
If you're running this on localhost, might be related to how [Cross-Site Cookies Will Now Be Rejected on localhost Because of SameSite=None; Secure in Chrome 80](https://medium.com/swlh/how-the-new-chrome-80-cookie-rule-samesite-none-secure-affects-web-development-c06380220ced)

You'd only see this on a local development server.  Auth with Flutter should still work fine on web in other contexts.

@lohanidamodar Can you confirm my hunch?

**Comment by gewenyu99** [comment]
@lohanidamodar Any idea?

**Comment by lohanidamodar** [comment]
@teneon can you share the code? Some issue might occur if you are accessing appwrite server over `https://localhost` and Flutter web app is running over `http://localhost`. If that's the case ,set the appwrite endpoint also using `http://localhost`.

Also check localStorage to see if `fallbackCookie`	 is set or not. Please provide more details so that we can help

**Comment by teneon** [comment]
I was further testing this issue today. It turns out that the problem is when you launch Chrome (web device) via VSCode it always starts on a new port. So i tested it by specifying fixed port like this via CLI:
`flutter run -d chrome --web-port 8000`

And now the peristence works. Even if i close Chrome, restart it i am still logged in as expected. So i guess the problem i experienced is just that you have to use fixed port.

However those error messages in Chrome devel tools (under issues) still remain while i am testing this locally:

_Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute
Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being set in a cross-site context. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests._

I will test this on your cloud soon, where as someone said problem should not occur.

Best regards!

**Comment by gewenyu99** [comment]
> I was further testing this issue today. It turns out that the problem is when you launch Chrome (web device) via VSCode it always starts on a new port. So i tested it by specifying fixed port like this via CLI: `flutter run -d chrome --web-port 8000`
> 
> And now the peristence works. Even if i close Chrome, restart it i am still logged in as expected. So i guess the problem i experienced is just that you have to use fixed port.
> 
> However those error messages in Chrome devel tools (under issues) still remain while i am testing this locally:
> 
> _Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being set in a cross-site context. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery. Resolve this issue by updating the attributes of the cookie: Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute. Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests._
> 
> I will test this on your cloud soon, where as someone said problem should not occur.
> 
> Best regards!
Yeah this makes sense... We could add this to the self-hosting docs, but the experience is going to be poor regardless because of how Chrome handles cookies for localhost. 

Anyway, glad you figured it out.

**Comment by joeyouss** [comment]
I am closing this issue since it is now fixed.
