### ISSUE TITLE
🚀 Feature: SETTING CUSTOM SESSION EXPIRY TIME FOR USER LOGIN SESSIONS

### ISSUE THREAD

**Issue by rajdama** [appwrite/appwrite#5652]
### 🔖 Feature description

Currently appwrite has its default session expiry time of 1 year, and I couldn't find any method in documentation to set custom session expiry time. It would be great if we can manually set the session expiry as in the case of JWT.

### 🎤 Pitch

Currently appwrite has its default session expiry time of 1 year, and I couldn't find any method in documentation to set custom session expiry time. It would be great if we can manually set the session expiry as in the case of JWT.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by teneon** [comment]
Hi, i am not sure if this is what you are looking for, but there is an option in the admin panel. Navigate to "Auth" / "Security". You should see is a "Session Length" block where you can specify "length" (default: 365) and "time period" (default: days). 

Note,  i am using Appwrite 1.3.3.

best regards,
Jim

**Comment by rajdama** [comment]
Thanks @teneon for ur help, that's what I needed !
