### ISSUE TITLE
🐛 Bug Report: No app check

### ISSUE THREAD

**Issue by shatanikmahanty** [appwrite/appwrite#5653]
### 👟 Reproduction steps

- Create a flutter app in console and add package name for android
- Create android app using different package name in your preferred IDE
- It will still allow to access appwrite services

### 👍 Expected behavior

Should not allow access to appwrite if the package name is different from what is registered in console

### 👎 Actual Behavior

Allows access to cloud resources

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite Cloud

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Thanks for creating this issue @shatanikmahanty. Our team will look into it soon.

**Comment by Haimantika** [comment]
Hi @shatanikmahanty we checked internally, and it is working as expected. Can you recheck and let me know?

**Comment by shatanikmahanty** [comment]
Hi @Haimantika, was caught up in work, so could not check earlier. 

I am still facing the same issue on read data. Writing to database or deleting user session gives me error invalid origin, so they are working.

The current package name in the app: ```com.codeswipe.app```
Package name in cloud console registered app: ```com.codeswipe.client```
![image](https://github.com/appwrite/appwrite/assets/67138059/b73643f5-bd37-433f-9784-faae919d1787)


Reproducible code:
https://github.com/shatanikmahanty/codeswipe

Steps to reproduce:
run commands:
- ```flutter pub get```
- ```dart run build_runner build --delete-conflicting-outputs```
- ```flutter run```

Once app is launched:
- Go to login page, **long tap on CodeSwipe text to toggle env to dev**.
- Login using Google
- Go to **Discover** page from app bottom bar (Card icon)
- You'll see the profiles being listed, which means data is accessible from the database. (**But writing data is throwing error invalid origin, app not registered**)

**Comment by Haimantika** [comment]
> Hi @Haimantika, was caught up in work, so could not check earlier.
> 
> I am still facing the same issue on read data. Writing to database or deleting user session gives me error invalid origin, so they are working.
> 
> The current package name in the app: `com.codeswipe.app` Package name in cloud console registered app: `com.codeswipe.client` ![image](https://user-images.githubusercontent.com/67138059/258634121-b73643f5-bd37-433f-9784-faae919d1787.png)
> 
> Reproducible code: https://github.com/shatanikmahanty/codeswipe
> 
> Steps to reproduce: run commands:
> 
> * `flutter pub get`
> * `dart run build_runner build --delete-conflicting-outputs`
> * `flutter run`
> 
> Once app is launched:
> 
> * Go to login page, **long tap on CodeSwipe text to toggle env to dev**.
> * Login using Google
> * Go to **Discover** page from app bottom bar (Card icon)
> * You'll see the profiles being listed, which means data is accessible from the database. (**But writing data is throwing error invalid origin, app not registered**)

Hi, so this is an expected behaviour. We validate the origin like how CORS checks are done on the web. it's not meant to fully stop someone from accessing your Appwrite project.

**Comment by shatanikmahanty** [comment]
> > Hi @Haimantika, was caught up in work, so could not check earlier.
> > 
> > I am still facing the same issue on read data. Writing to database or deleting user session gives me error invalid origin, so they are working.
> > 
> > The current package name in the app: `com.codeswipe.app` Package name in cloud console registered app: `com.codeswipe.client` ![image](https://user-images.githubusercontent.com/67138059/258634121-b73643f5-bd37-433f-9784-faae919d1787.png)
> > 
> > Reproducible code: https://github.com/shatanikmahanty/codeswipe
> > 
> > Steps to reproduce: run commands:
> > 
> > * `flutter pub get`
> > * `dart run build_runner build --delete-conflicting-outputs`
> > * `flutter run`
> > 
> > Once app is launched:
> > 
> > * Go to login page, **long tap on CodeSwipe text to toggle env to dev**.
> > * Login using Google
> > * Go to **Discover** page from app bottom bar (Card icon)
> > * You'll see the profiles being listed, which means data is accessible from the database. (**But writing data is throwing error invalid origin, app not registered**)
> 
> Hi, so this is an expected behaviour. We validate the origin like how CORS checks are done on the web. it's not meant to fully stop someone from accessing your Appwrite project.

Is there a method by which we may secure data read?

**Comment by stnguyen90** [comment]
The best way to secure data is to set permissions to limit access to only authorized users. If you're looking for Play Integrety integration, please add a 👍🏼 to https://github.com/appwrite/appwrite/issues/4791
