### ISSUE TITLE
🐛 Bug Report: Partially uploaded file shown in console.

### ISSUE THREAD

**Issue by ajitsinghkaler** [appwrite/appwrite#5654]
### 👟 Reproduction steps

When i upload a file partially Using storage api it shows up in the console but if the file not uploaded properly it should not be shown in console. I get this when I list this file 

{
            "$id": "**",
            "bucketId": "**",
            "$createdAt": "2023-06-03T11:15:55.820+00:00",
            "$updatedAt": "2023-06-03T11:15:55.820+00:00",
            "$permissions": [
                "read(\"user:**\")",
                "delete(\"user:**\")"
            ],
            "name": "**.wav",
            "signature": "",
            "mimeType": "",
            "sizeOriginal": 6359578,
            "chunksTotal": 2,
            "chunksUploaded": 1
        },
        
        Total chinks are not equal to uploaded chinks so the file should not be in the console.
        
        Even if its shown ion console I could not delete it.

### 👍 Expected behavior

If a file is partially uploaded it should not be shown in appwrite console. If upload fails why is it shown in console.

### 👎 Actual Behavior

The file is shown in appwrite console and I am not even able to delete it.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite sdk version: 11.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Suven-p** [comment]
> I am not even able to delete it.

You should be able to delete the file from console.
File for testing:
![image](https://github.com/appwrite/appwrite/assets/47393058/d65cb761-1fda-497c-a230-b991f3407ea7)
After pressing the delete button:
![image](https://github.com/appwrite/appwrite/assets/47393058/ff7fd351-a628-430e-b4d5-d7ee230664a0)

**Comment by ajitsinghkaler** [comment]
No it does not work

https://www.loom.com/share/890fa34831e24de4a1c87872a87d6e5c

**Comment by Suven-p** [comment]
:thinking: I can't seem to trigger the error. Does the same error happen for all incomplete uploads? How did you create the incomplete upload and what bucket settings are you using?

**Comment by ajitsinghkaler** [comment]
To create the upload I started upload and before the upload completed I refreshed. 

As for bucket settings I have create for users in permissions. File Security encryption and Antivirus enabled

**Comment by Suven-p** [comment]
Does this happen for all partially uploaded files on the storage or just for some files?

**Comment by ajitsinghkaler** [comment]
this happens for partially uploaded file. think I have found the issue. If the user does not have write permissions. When the sdk tries to do chunked uploads the second upload fails as the user does not have write permissions and those files could not be deleted from dashboard

**Comment by Suven-p** [comment]
I don't think that user permissions affect the console. If you see my screenshot the permission array is empty.

**Comment by stnguyen90** [comment]
> To create the upload I started upload and before the upload completed I refreshed.

@ajitsinghkaler I'm also unable to reproduce this problem following these steps 🧐

**Comment by ajitsinghkaler** [comment]
@stnguyen90 


To recreate this follow the steps 
Create a logged in user 
Then in bucket in settings allow File Security
Then these should be no permissions in the bucket.
Then create a file using client js sdk using the createFile file in Appwrite storage 
In the permissions array give create and delete permissions don't give the update permissions
The upload a file greater than 5MB

This bug is created.

**Comment by Suven-p** [comment]
Appwrite should throw 401 or 403 with a bucket that doesn't have Create permission for user, users or any.

**Comment by Suven-p** [comment]
Could you try a different browser?
