### ISSUE TITLE
🐛 Bug Report: $permissions returns as object rather than array

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#5661]
### 👟 Reproduction steps

1. Create a document with permissions like:

   ```javascript
   [
        'read("any")',
        'read("user:642090ce0b988edac790")',
        'read("user:642090ce0b988edac790")',
        'write("user:642090ce0b988edac790")',
        'update("user:642090ce0b988edac790")',
        'delete("user:642090ce0b988edac790")'
   ]
   ```
2. Fetch the document using `databases.getDocument()` or `databases.listDocuments()`

### 👍 Expected behavior

The `$permissions` is an array like:

```javascript
[
        'read("any")',
        'read("user:642090ce0b988edac790")',
        'update("user:642090ce0b988edac790")',
        'delete("user:642090ce0b988edac790")'
]
```

### 👎 Actual Behavior

The $permissions is an object like:

```javascript
{
    '0': 'read("any")',
    '1': 'read("user:642090ce0b988edac790")',
    '3': 'update("user:642090ce0b988edac790")',
    '4': 'delete("user:642090ce0b988edac790")'
}
```

I believe the problem is due to `array_unique()` here: https://github.com/utopia-php/database/blob/d821d1f18dfe83b0350ed208be3658764aec99d7/src/Database/Document.php#L82. It removes the duplicates but doesn't re-organize the array.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

This problem also occurs on 1.3.4 (and probably 1.3.7).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by itsCheithanya** [comment]
@stnguyen90 
I would like to take up the issue

**Comment by stnguyen90** [comment]
@itsCheithanya, assigned! Thanks for your interest!

**Comment by stnguyen90** [comment]
@itsCheithanya, actually, sorry, we've already started working on this internally so it would be best if you picked up a different issue.

**Comment by 2002Bishwajeet** [comment]
I am taking this up

**Comment by itsCheithanya** [comment]
okay no problem @stnguyen90 @2002Bishwajeet
