### ISSUE TITLE
🐛 Bug Report: Can't edit Array of String

### ISSUE THREAD

**Issue by fliitor** [appwrite/appwrite#5674]
### 👟 Reproduction steps

1. Create String/Array attribute on collection
2. Create new document with value
3. Try to edit this attribute, Update button isn't available

![image](https://github.com/appwrite/appwrite/assets/117680686/72b5fe39-b4b6-4627-8e9a-94b4b31599e0)

Need to click on "Add item" and remove this newly item to be able to click on update

### 👍 Expected behavior

Update button should be enable when aditing attribute

### 👎 Actual Behavior

Update button stay disable

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hey
Thanks for opening this. Have passed this feedback to my team..will keep you posted about the updates here.

**Comment by joeyouss** [comment]
Hi, our team is working on a fix for this. Thank you again for opening this

**Comment by hortigado** [comment]
I am having the same problem

**Comment by hortigado** [comment]
It doesn't only happen from the console, but also when editing from any sdk you can't add more than one item

**Comment by hortigado** [comment]
@joeyouss Thank you, it is an error that needs to be solved urgently since it is delaying my development and others too I suppose

**Comment by stnguyen90** [comment]
> It doesn't only happen from the console, but also when editing from any sdk you can't add more than one item

@hortigado, your problem is something else. Please create a support post on our Discord server.

**Comment by hortigado** [comment]
@stnguyen90 Correct, it was my mistake. I was sending the **documentId** field when updating. So in order not to create confusion, this problem would only be from the console. Thanks

**Comment by stnguyen90** [comment]
Tested on 1.5 and this is no longer a problem.
