### ISSUE TITLE
🚀 Feature: Omit the requirement of the URL parameter in server createMembership function

### ISSUE THREAD

**Issue by byawitz** [appwrite/appwrite#5675]
### 🔖 Feature description

From the docs
> Invite a new member to join your team. Provide an ID for existing users, or invite unregistered users using an email or phone number. If initiated from a Client SDK, Appwrite will send an email or sms with a link to join the team to the invited user, and an account will be created for them if one doesn't exist. If initiated from a Server SDK, the new member will be added automatically to the team.

When using the teams `createMembership()` function in a Server side SDK it seems like there's no need for the URL parameter, or at least it shouldn't be required.

### 🎤 Pitch

As no email is being sent then no need for the `url` parameter.

P.s. maybe it can work that if the user is adding `url` to the server side function, then it will send email even from the server side implementation. but that's already another feature.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Thank you for opening this. Currently, the URL parameter plays a crucial role in safeguarding against possible open redirect attacks, particularly when involving user API interactions. If we were to remove this parameter, it would require careful internal handling, as other adjustments would likely need to be made as well. 
I will keep this feature request open for future consideration and gathering feedback.

**Comment by byawitz** [comment]
I've meant with Server side SDKs, in which the `URL` parameter is not in use.

**Comment by joeyouss** [comment]
Yes, I am talking about them as well

**Comment by stnguyen90** [comment]
Closing as url is no longer required
