### ISSUE TITLE
🐛 Bug Report: Wrong signature for createMembership server side implementation

### ISSUE THREAD

**Issue by byawitz** [appwrite/appwrite#5676]
### 👟 Reproduction steps

1. The docs for the `createMembership()` function doesn't match the function signature,
https://appwrite.io/docs/server/teams?sdk=nodejs-default#teamsCreateMembership

In languages that utilize named parameters, it's not that of a problem, But in others, it can cause confusion.

2. (Optional) Maybe it would be better to prioritize the required parameters over the optional ones.
So [this ](https://github.com/appwrite/appwrite/blob/master/app/controllers/api/teams.php#L381-L387)will become like this
```php
 ->param('teamId', '', new UID(), 'Team ID.')
 ->param('roles', [], new ArrayList(new Key(), APP_LIMIT_ARRAY_PARAMS_SIZE), 'Array of strings. Use this param to set the user roles in the team. A role can be any string. Learn more about [roles and permissions](/docs/permissions). Maximum of ' . APP_LIMIT_ARRAY_PARAMS_SIZE . ' roles are allowed, each 32 characters long.')
 ->param('url', '', fn($clients) => new Host($clients), 'URL to redirect the user back to your app from the invitation email.  Only URLs from hostnames in your project platform list are allowed. This requirement helps to prevent an [open redirect](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html) attack against your project API.', false, ['clients']) 
 ->param('email', '', new Email(), 'Email of the new team member.', true)
 ->param('userId', '', new UID(), 'ID of the user to be added to a team.', true)
 ->param('phone', '', new Phone(), 'Phone number. Format this number with a leading \'+\' and a country code, e.g., +16175551212.', true)
 ->param('name', '', new Text(128), 'Name of the new team member. Max length: 128 chars.', true)

```

3. (Optional) Omit the requirement of the URL parameter at all on the server side, see this https://github.com/appwrite/appwrite/issues/5675

### 👍 Expected behavior

Order in the docs and in the function should match.

### 👎 Actual Behavior

The order doesn't match and prioritizes optional fields over required ones.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by bhagn** [comment]
I'm trying to use the server side sdk to create a team membership. But I get this error:

```
[Error] Type: TypeError
[Error] Message: {closure}(): Argument #3 ($userId) must be of type string, null given, called in /usr/src/code/vendor/utopia-php/framework/src/App.php on line 577
[Error] File: /usr/src/code/app/controllers/api/teams.php
[Error] Line: 396
```

But the docs don't mention anything about `$userId` parameter. Is this related to the Github issue here? The same issue with `Phone` and a few other optional params. 

It accepts empty string but not `null`/`None`

**Comment by gewenyu99** [comment]
> I'm trying to use the server side sdk to create a team membership. But I get this error:
> 
> ```
> [Error] Type: TypeError
> [Error] Message: {closure}(): Argument #3 ($userId) must be of type string, null given, called in /usr/src/code/vendor/utopia-php/framework/src/App.php on line 577
> [Error] File: /usr/src/code/app/controllers/api/teams.php
> [Error] Line: 396
> ```
> 
> But the docs don't mention anything about `$userId` parameter. Is this related to the Github issue here? The same issue with `Phone` and a few other optional params.
> 
> It accepts empty string but not `null`/`None`

Which version are you running and which version of the docs are you looking at ;)
