### ISSUE TITLE
🐛 Bug Report: Relationships don't cascade delete properly with 2 relationships

### ISSUE THREAD

**Issue by Walrusking16** [appwrite/appwrite#5677]
### 👟 Reproduction steps

Create three collections

- The first collection has a relationship with collection two using cascade delete and one to many
- The second collection has a relationship with collection three using cascade delete and one to many
- Third collection attributes don't matter

Roadmap
 - Categories: Relationship on roadmap
   - Tasks: Relationship on categories

Create some random documents for each of the collections.

Delete a document from the first collection.

### 👍 Expected behavior

Deleting a document from the first collection will cause categories and tasks to be deleted

### 👎 Actual Behavior

Only the roadmap and categories are deleted. Tasks remain undeleted.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Node, 1.3.7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi
Thank you for reporting this. We have started looking into this and we will keep you updated.

**Comment by abnegate** [comment]
Hi @Walrusking16 this is fixed and will be released in the next version :+1:

**Comment by joeyouss** [comment]
Adding the PR here: https://github.com/utopia-php/database/pull/269

**Comment by abnegate** [comment]
Hi @Walrusking16 are you able to confirm is this issue is resolved for you in the latest version 1.4.2?

**Comment by abnegate** [comment]
Closing as tested fixed in 1.4.2
