### ISSUE TITLE
🚀 Feature: Automated Database Schema Import

### ISSUE THREAD

**Issue by sosensible** [appwrite/appwrite#5678]
### 🔖 Feature description

Import > Exported database schemas.

1. Pull existing schema for a database (store it anywhere the owner chooses on their system)
2. Create a new database
3. Either via API or UI, import the schema to automate all thing collection, attributes, and beyond

### 🎤 Pitch

This would allow for the initial setup of a database on an existing pattern. (Configuration as code) The manual UI is awesome, but only for doing manual things. Automation to avoid repetitive manual activity already done before would be Awesome 2.0 here.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Appreciate the feedback.
Thank you for opening this and we are going to keep it open.

**Comment by sergioponguta** [comment]
I dont know if it is useful for you for now, I have done this to help me migrating mysql schema to appwrite:

[Mysql DDL to Appwrite](https://github.com/sergioponguta/Mysql-ddl-to-Appwrite-Collections)

**Comment by safwanyp** [comment]
Been working on something to migrate a MySQL DB to Appwrite for my current job.

How would one go about implementing it inside of Appwrite's existing codebase?

**Comment by joeyouss** [comment]
Adding a related issue here:
- #2383

**Comment by joeyouss** [comment]
hi @safwanyp as we discussed over Discord, your issue is resolved.

As for @sosensible please let us know if migration tool and/or suggestion by Steven solved your problem

**Comment by stnguyen90** [comment]
@sosensible, is there anything else you need? FYI, we'll need to close this soon due to inactivity.
