### ISSUE TITLE
🚀 Feature: Disable realtime completly

### ISSUE THREAD

**Issue by fliitor** [appwrite/appwrite#5679]
### 🔖 Feature description

If realtime worker is disable, disable all realtime process

### 🎤 Pitch

[From Discord](https://discord.com/channels/564160730845151244/1116316923655901234)

Sometimes realtime is just not need, but Console call it (to got stats I thinks ?) that result of errors on logs each 60 seconds

Add and env variable to disable it ?
Or allow to disable it from project settings

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Thank you for converting this into an issue.

**Comment by eldadfux** [comment]
I think it could be a good idea to allow disabling the Realtime API, but as doing so on the console might create some weird and unexpected behaviors in some case. @TorstenDittmann what are your thoughts on this?

**Comment by stnguyen90** [comment]
> Sometimes realtime is just not need, but Console call it (to got stats I thinks ?)

@fliitor, realtime is also used to improve UX in cases where statuses are updated asynchronously without requiring the user to refresh the page. For example, databases attribute/index status and function build status.

**Comment by stnguyen90** [comment]
Related issue: https://github.com/appwrite/appwrite/issues/6193
