### ISSUE TITLE
🐛 Bug Report: new empty collections reported as not found by databases.listDocuments()

### ISSUE THREAD

**Issue by melnibon** [appwrite/appwrite#5687]
### 👟 Reproduction steps

1. Create a new (empty) collection in the AppWrite web console
2. In Flutter app, after login, call `Databases(client).listDocuments(databaseId: "[dbID]", collectionId: "[collID]"`
3. This call throws an exception:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: AppwriteException: collection_not_found, Collection with the requested ID could not be found. (404)
#0      ClientMixin.prepareResponse
#1      ClientIO.call
<asynchronous suspension>
#2      Databases.listDocuments
<asynchronous suspension>
#3      _MyHomePageState.loadItems
<asynchronous suspension>
#4      _MyHomePageState._initAppWrite
<asynchronous suspension>
Restarted application in 308ms.
```

### 👍 Expected behavior

- `Databases(client).listDocuments()` should return an empty List.
- The server should not return a 404 code.

I think the origin of the bug is the answer of the server. I suspect that the underlying table associated to the collection is not created in the same time than the collection, because it is also empty of attributes, but the low level table is not created even if I add attributes.

I suppose that because, after creating attributes, then adding documents in this collection, then deleting all of them, the collection is now listed by `listDocuments()` as empty without any exception.

So, to me, creating documents allows to create the collection (the low level SQL table), and brand new collections do not yet really exist, even if I add attributes to them (maybe this is the reason, adding attributes do not create/update the SQL table). The server should not answer 404 in such a case, but 200 and no data.

### 👎 Actual Behavior

- Databases(client).listDocuments actually throws an `AppwriteException: collection_not_found`
- The server returns a 404.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

"out of the box" self-hosted AppWrite install

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi
Can you please make sure you have the correct permissions assigned?

**Comment by melnibon** [comment]
Hello,
Sorry, I can't understand your question. What is the point of your question about the permissions? What permissions? This is a self-hosted docker installation. The permissions are defined into the container. As a user, I can't change anything to the configuration of the docker compose system.

Next, I explain that the first call to `listDocuments` fails until some data are created by another way. Then, even if these data are deleted, `listDocuments` will now succeed.

So I suspect that the console web application does not create the underlying tables properly, or `listDocuments` misses some check related to the new tables.

If there were a problem with permissions, the behaviour would not change like that.
Regards,

**Comment by melnibon** [comment]
Oh, my ... !

You are right, I forgot to edit the permissions to the collection.
(first, I believed it related to the permissions inside the docker containers).

Many thanks,
Best regards,
Pierre
