### ISSUE TITLE
🐛 Bug Report: 500 Internal Error on Appwrite Cloud

### ISSUE THREAD

**Issue by semroig** [appwrite/appwrite#5690]
### 👟 Reproduction steps

Enter into a project, and try to go databases or auth dasgboard.

### 👍 Expected behavior

Go to dashboards and see the database collections

### 👎 Actual Behavior

500 Internal Server Error.
<img width="1440" alt="Screen Shot 2023-06-12 at 10 50 27" src="https://github.com/appwrite/appwrite/assets/63104910/d2018fff-2b2c-4d82-89f8-377745f35514">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

Google Chrome.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by semroig** [comment]
> Hi, @semroig 👋 Appwrite Cloud is stable now. Are you still facing this error?

It is working fine now! Thanks again @Haimantika and @joeyouss ! 💪

**Comment by TusharVashishth** [comment]
<img width="1663" alt="image" src="https://github.com/appwrite/appwrite/assets/46848148/dda5a8eb-eee6-4282-8e1c-5c0471ae22a6">

Getting same 500 error all time during fetch and insert . I don't know what to do ?

**Comment by Myshkouski** [comment]
> <img alt="image" width="1663" src="https://user-images.githubusercontent.com/46848148/278231801-dda5a8eb-eee6-4282-8e1c-5c0471ae22a6.png">
> Getting same 500 error all time during fetch and insert . I don't know what to do ?

+1

**Comment by harryparkinson101** [comment]
I am getting the same 500 error

**Comment by harryparkinson101** [comment]
![Screenshot 2023-11-09 at 19-09-02 Organizations - Appwrite](https://github.com/appwrite/appwrite/assets/71083434/ec88c511-da00-44e6-a5ed-f029ea1f5221)

**Comment by Depender-Sethi** [comment]
Spent a couple of hours on this, and turns out it was a cache thing. Just cleared the site's data, signed in again, and all good now. Give it a shot, might work for you too!

**Comment by Depender-Sethi** [comment]
After a couple of hours of troubleshooting, I created a new project under a new organization. Additionally, I cleared the cache and signed in again. This combination did the trick for me. Give it a shot, might work for you too
