### ISSUE TITLE
🐛 Bug Report: Portuguese email template is missing a word

### ISSUE THREAD

**Issue by Miguelii** [appwrite/appwrite#5693]
### 👟 Reproduction steps

The "emails.recovery.body" template in Portuguese (pt-pt) is missing a word.

### 👍 Expected behavior

The "emails.recovery.body" field should be replace by: "Utilize este link para redefinir a palavra-passe do seu projecto {{project}}"

### 👎 Actual Behavior

The "emails.recovery.body" field value is "tilize este link para redefinir a palavra-passe do seu projecto {{project}}", its missing the first word "U".

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Miguelii** [comment]
PR created: [5694](https://github.com/appwrite/appwrite/pull/5694)

**Comment by joeyouss** [comment]
Thank you for making the PR, we are just waiting for it to merge.
