### ISSUE TITLE
🐛 Bug Report: Server Error when authenticating

### ISSUE THREAD

**Issue by falcon-Z** [appwrite/appwrite#5697]
### With Appwrite client Sdk 
```
account.deleteSession("current")
```

Error on Browser Console
```
DELETE https://cloud.appwrite.io/v1/users/64*****0affc 500
```

### On Appwrite Cloud Dashboard 
1.  Dashboard -> Auth -> Select a User
2.  Click `Delete` -> Confirm Delete
3.  Notice the error on Browser Console
```    
DELETE https://cloud.appwrite.io/v1/users/648******0affc 500
```

### When Trying to Create a new user
Auth -> Create New user -> Fill in some dummy Data -> Click Create

Notice the server error

### 👍 Expected behavior

- When attempting to Delete session I expected to be logged out
-  When attempting to delete user i expected the user to be removed
-  When attempting to create new user i expected a new user to be created

### 👎 Actual Behavior

- When attempting to log out server throws the following error
```
DELETE https://cloud.appwrite.io/v1/account/sessions/current 500
```

- When attempting to delete the user from Appwrite dashboard `Delete` button has no effect
```    
DELETE https://cloud.appwrite.io/v1/users/64*****0affc 500
```
- When attempting to create new user I get a server error (Screenshot attached)
![image](https://github.com/appwrite/appwrite/assets/28111283/f56611ec-11a6-40d2-ae63-4eb3f2a66a03)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite Web Client
```
"appwrite": "^11.0.0"
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Hi @falcon-Z 👋 this occurred due to an outage yesterday. Let me know if it works for you now.
