### ISSUE TITLE
🐛 Bug Report: Duplicate verification users API entry.

### ISSUE THREAD

**Issue by byawitz** [appwrite/appwrite#5717]
### 👟 Reproduction steps

I'm not sure - maybe it is purposely - but I've noticed that the `/v1/users/:userId/verification`  **PATCH** endpoint is written twice inside the file `app/controllers/api/users.php`.

- First occurrence - [Link](https://github.com/appwrite/appwrite/blob/master/app/controllers/api/users.php#L666-L700)
- Second occurrence - [Link ](https://github.com/appwrite/appwrite/blob/master/app/controllers/api/users.php#L930-L964)

The only difference is the first version also includes, this line
```php
    ->label('audits.userId', '{request.userId}')
```

### 👍 Expected behavior

To have just one, for easy maintaining process.

### 👎 Actual Behavior

There's two.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Edge version in Github.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hey there,

Yes, we're aware of this. It seems like there's some leftover code that needs fixing, and it will be taken care of.
