### ISSUE TITLE
🐛 Bug Report: Schedule function with minutes does not work

### ISSUE THREAD

**Issue by jbdujardin** [appwrite/appwrite#5719]
### 👟 Reproduction steps

I create and deploy a function with cron schedule 30 1 * * * : 
```json
{
            "$id": "update-fixtures",
            "name": "Update fixtures",
            "runtime": "dart-2.17",
            "path": "functions/update-fixtures",
            "entrypoint": "lib/main.dart",
            "ignore": [
                ".packages",
                ".dart_tool"
            ],
            "execute": [],
            "events": [],
            "schedule": "30 1 * * *",
            "timeout": 60
},
```
The function is deployed and build successfully but the schedule is not active despite the cron is visible on the function settings : 

![Capture d’écran 2023-06-16 à 23 55 35](https://github.com/appwrite/appwrite/assets/293027/8a552416-98a4-4a57-9fcb-817125a818bc)

If I try to modify the value on the console, there is an error : 

![Capture d’écran 2023-06-16 à 23 57 39](https://github.com/appwrite/appwrite/assets/293027/8428d6e1-3777-4b89-9f02-ec67d4965ed7)

I also try to edit the value on the json and redeploy the function but no schedule active ☹️ 

If I set `* * * * *` or `0 1 * * *` , there is no problem, only when minutes are other than `*` or `0`. 

### 👍 Expected behavior

The function is executed with the cron value on the Schedule part (with minutes on the cron value).

### 👎 Actual Behavior

The function is not executed and the schedule is not active (no clock on the bottom right).

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite version 1.3.7
CLI version 2.0.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sunjianan9900** [comment]
i got same problem 
The strange thing is that after I set up the json file, open the console to view, the clock icon did appear, but when I clicked into the FC to view the timing (no changes), and then return to the FC home page, the clock icon disappeared

**Comment by sunjianan9900** [comment]
This is Schrödinger's cat, you set up the json file, deploy function, and then do not enter the setting page of this function, other pages can be viewed (such as logs), the timing will not be canceled, but as long as you enter the setting page, the timing will expire

**Comment by sunjianan9900** [comment]
This should be a display bug, I just tested the setting to execute every 10 minutes (via json), although the page will have a clock for a while, and then not, but the methods are executed on time (check the log). You can set a more frequent timing to see what happens. (After the first automatic execution, the clock marker didn't disappear anymore)

**Comment by stnguyen90** [comment]
We're going to focus this issue on the incorrect validation error.

**Comment by Sachin24704** [comment]
Hi , so the incorrect validation is due to regex pattern.

**Comment by Sachin24704** [comment]
PR was created for this issue. Please review

**Comment by stnguyen90** [comment]
@Sachin24704 would you please link to this issue from the PR so it shows up here?

**Comment by Sachin24704** [comment]
the PR is in the console repo - [https://github.com/appwrite/console/pull/473](url) -hope this helps. I was not able to link it here in this repo. Thanks

**Comment by antonioorct** [comment]
Is there any work-around for this? The issue's open for a long time and I'm having huge issues on production due to this.

**Comment by stnguyen90** [comment]
Closing and unassigning due to inactivity.

**Comment by stnguyen90** [comment]
> Is there any work-around for this? The issue's open for a long time and I'm having huge issues on production due to this.

@sunjianan9900 the workaround is to use your browser dev tools to remove the client-side pattern validation.

**Comment by KanniShashankh** [comment]
@stnguyen90 Can i be assigned this issue?

**Comment by stnguyen90** [comment]
@KanniShashankh, assigned! Thanks for your interest! 🙏

**Comment by KanniShashankh** [comment]
> @KanniShashankh, assigned! Thanks for your interest! 🙏

Are we going to support all types of cron syntax? Because the regex pattern would be pretty verbose for covering all cases

**Comment by stnguyen90** [comment]
@KanniShashankh let's just focus on fixing the bugs and supporting standard syntax

**Comment by KanniShashankh** [comment]
@stnguyen90 Please review i have mentioned the PR here, Thank you
