### ISSUE TITLE
🐛 Bug Report: seach query throws server error 500 on Cloud

### ISSUE THREAD

**Issue by subhamX** [appwrite/appwrite#5729]
### 👟 Reproduction steps

Run the following query:
```
const projectIds=[]
const projects = (new Databases(appwriteClient)).listDocuments(
  appwriteDatabaseId,
  appwriteProjectsCollectionId,
  [Query.equal("$id", projectIds)]
);
```

### 👍 Expected behavior

The following should return an empty projects arr.

### 👎 Actual Behavior

It throws server error

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Using `node-appwrite@9.0.0`.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi, Yes we are aware of this problem and this is in plans to get fixed.

**Comment by subhamX** [comment]
Ah. That's great. Was doing some digging on the queries and filters in the codebase to find the source of the problem, but if it's already on the board I guess I can park my exploration. 

I wonder where are we making the actual DB calls? My idea was to not make any DB calls, and just return an empty array. I was tracing from `Request`, but couldn't reach anywhere. (Maybe I haven't yet spent enough time on it).
```
Request:getParams -> Filters:parse -> Filters:parseDocumentList -> ???
```

Anyways, thank you for taking care of it.

**Comment by joeyouss** [comment]
You might want to see https://github.com/utopia-php/database

**Comment by joeyouss** [comment]
Hi @subhamX , can I close this issue if this no longer happens for you?

**Comment by subhamX** [comment]
I haven't checked this recently, but if you feel it has been patched, please close it. Really appreciate you all for being actively building & shipping feat.

**Comment by stnguyen90** [comment]
Closing as this now returns a 400 error with an error of:

```json
{
    "message": "Invalid query: Equal queries require at least one value.",
    "code": 400,
    "type": "general_argument_invalid",
    "version": "0.11.46"
}
```
