### ISSUE TITLE
🐛 Bug Report: Inconsitency of Count for Auth

### ISSUE THREAD

**Issue by Abhishek-90** [appwrite/appwrite#5734]
### 👟 Reproduction steps

When I created a new account, In The overview tab for my project, I see `0` users (Screenshot 1), but when I go inside the Auth Tab, I get `1` (Screenshot 2) as the total number of users.

![Screenshot_1](https://github.com/appwrite/appwrite/assets/43419831/08ae5fa4-555d-4d45-a575-ff36b8ea4d81)
![Screenshot_2](https://github.com/appwrite/appwrite/assets/43419831/170e90fc-521b-42a2-8957-a347622a556c)

### 👍 Expected behavior

Both Count should be same.

### 👎 Actual Behavior

Inconsistent account of users.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite SDK 11.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hey!
Thank you for opening this. This is a known issue and we are working to fix this. I will update you once this is fixed and/or there are more updates.

**Comment by Abhishek-90** [comment]
Minor change, The change in the count is after a delay, it's not instant I think, now for me it's showing properly @joeyouss

**Comment by joeyouss** [comment]
Yes, can we close this issue for now @Abhishek-90 ? Since this is something we are internally working on.

**Comment by Abhishek-90** [comment]
Sure @joeyouss, as you see fit.

**Comment by Haimantika** [comment]
> Sure @joeyouss, as you see fit.

Thanks @Abhishek-90 , we are closing it for now.
