### ISSUE TITLE
🚀 Feature: Custom abuse control/rate limits

### ISSUE THREAD

**Issue by DHsoftw** [appwrite/appwrite#5737]
### 🔖 Feature description

Make all rate limits (requests per second limits) or potential abuse limits, like pagination or maximum number of fetched documents customizable

### 🎤 Pitch

By allowing users to customise their rate limits, that could make it more difficult to abuse an app. For example, if an app doesn't needs to make more than 10 requests, you could fine-tune to a smaller limit to prevent abuse and save resources in your server from bad requests.

Same with pagination and maximum amount of fetched documents. By allowing customizing it, you can prevent someone making a query with 1000 documents in an app that doesn't needs fetching more than 30 documents at once.

With pagination it could be great having custom limits too, since they're slower when the amount of pages increases.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @DHsoftw , as I can see there is another issue regarding the same feature request already open which is #2953 , can we please close this issue since it is a duplicate and we can carry the conversation there itself?

**Comment by DHsoftw** [comment]
Hmmm weird, searched and didn't found it
