### ISSUE TITLE
🚀 Feature: Please Add Multi Node Support

### ISSUE THREAD

**Issue by vaishakhpj** [appwrite/appwrite#5746]
### 🔖 Feature description

Hi, Please add two node support since if one server goes down the system will work using the second server, so we can reduce the down time and get 100 percent up time. Please add a feature in which one is a master node and the other is a secondary node and data will be synced regularly to the secondary node. And the ip address of both nodes will be added to the client application, so the sdk can determine if the primary server is down it will connect with the secondary server, and after maintanence work in primary server is finished, the data in secondary will be synced back to primary and the sdk in client can work as normally.

There can be a realtime connection with the secondary node, so everything will be synced, it is already possible by writing an application but if it comes by default then it will be a great boon.

### 🎤 Pitch

Use case:
This is very important since maintenance work is needed periodically in the primary server such as system upgrade, other applications are working on the server which needs down time for maintanence, security issues with the system need to be addressed, so constantly the primary server needed down time, so without changes in client application we need to manage the down time. It is very essential for every production application who are serious about their valuable business.So somehow down time should be managed.

Atleast two nodes in different clouds is essential for a business to run smoothly otherwise no serious business owner will consider the system robust enough.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by LyVanBong** [comment]
I also agree with you. I'm also trying to do cluster deployment but no success. Hopefully in the near future appwrite's team will add support for this. such as above declare docker swarm or k8s ... etc. Thank you very much appwrite team for creating a very good product for the developer community.

**Comment by stnguyen90** [comment]
We recommend scaling using docker swarm because Appwrite functions uses the Docker CLI to spin up containers and won't work on K8s. You can refer to the following community resources for help with this:

* https://book.appread.io/docker-swarm
*  https://dev.to/hackmamba/how-to-create-a-docker-swarm-of-appwrite-containers-and-ui-with-swarmpit-1nje
