### ISSUE TITLE
🐛 Bug Report: Deleting a file leads to error message "Invalid fileId" UID must contain at most 36 chars.

### ISSUE THREAD

**Issue by trashcoder** [appwrite/appwrite#5749]
### 👟 Reproduction steps

While deleting files i get an error message "Invalid fileId: UID must contain at most 36 Chars...."

I can't delete this file from Appwrite Web-Gui.
<img width="457" alt="Bildschirmfoto 2023-06-26 um 12 56 21" src="https://github.com/appwrite/appwrite/assets/2404165/57e65dad-8b3c-44b6-bcae-63f758cb0692">

### 👍 Expected behavior

Regardless of the fileId it should it be possible to delete it.
On the other hand appwrite should check the fileId when the file is beeing uploaded.

### 👎 Actual Behavior

File can be uploaded but not deleted.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite Server 1.3.7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by trashcoder** [comment]
The File has the fileId "unique()".
I made an error when i coded the Axios.post command to upload the file, but i can't delete it anyways.

In my opinion the Appwrite Server has to decline a file, when the fileId has invalid chars like ( )

Btw. the fileId gets checked when i want to delete it:
_Invalid fileId: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore_

**Comment by stnguyen90** [comment]
Closing as this should have been fixed as part of https://github.com/appwrite/appwrite/issues/5542
