### ISSUE TITLE
🐛 Bug Report: Adding an array-type attribute causes access issue to collection documents on the Appwrite Cloud Web UI

### ISSUE THREAD

**Issue by lxup** [appwrite/appwrite#5753]
### 👟 Reproduction steps

- Create a new attribute in a collection
- Select the "Array" type for the attribute (specify that this attribute should act as an array)
- Attempt to access a document from the Web UI
- Notice that nothing loads or displays

### 👍 Expected behavior

A new attribute should be created, and documents should remain accessible as they were before in the Web UI.

### 👎 Actual Behavior

After creating an Array-type attribute, it is not possible to access the documents on the Web UI. Nothing loads or displays.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @xmesky , I just reproduced this in the latest version and it seems that it is fixed in newer versions. Can you try once to see if this problem still occurs for you in latest version?

**Comment by joeyouss** [comment]
I think this is fixed on the newer version of Appwrite - Cloud is still on 1.1.2 and Appwrite is on 1.3.7 so the updates done to newer versions might not be reflected in the previous versions.

I found similar issue: #5241

**Comment by stnguyen90** [comment]
@xmesky, are you still facing this problem?

**Comment by stnguyen90** [comment]
Just tested on 1.5 and it shouldn't be a problem anymore.
