### ISSUE TITLE
🐛 Bug Report: queries with Relationship Attribute

### ISSUE THREAD

**Issue by TechComet** [appwrite/appwrite#5757]
### 👟 Reproduction steps

I Development with Flutter with appwrite package
categoryCollection have Relationship Attribute with forum name
Relationship Attribute with type oneToMany (forum attribute name to forum collection)

```
final response = await ApiClient.database.listDocuments(
    databaseId: appwriteDatabaseId,
    collectionId: categoryCollection,
    queries: [
      Query.isNotNull('forum'),
    ],
  );

```

### 👍 Expected behavior

show any forum if not have null in forum attribute

### 👎 Actual Behavior

AppwriteException: general_unknown, Server Error (500)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I tested with Appwrite 1.3.1 and 1.3.7

I tested with Appwrite SDK 9.0.0 and 9.0.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gepd** [comment]
Queries on relationship are currently not supported

**Comment by joeyouss** [comment]
Hi @TechComet I am closing this for now since queries currently are not supported in Relationships, we will keep you posted once they are : )
