### ISSUE TITLE
🚀 Feature: Purging collection

### ISSUE THREAD

**Issue by roxxel** [appwrite/appwrite#5767]
### 🔖 Feature description

Add ability to clear collection without having to delete it

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by roxxel** [comment]
I forgot to mention, this feature is meant to be in appwrite admin panel, not in public api

**Comment by stnguyen90** [comment]
@roxxel, thanks for raising this issue! 🙏🏼 It seems like this is the same as https://github.com/appwrite/appwrite/issues/3520. As such, I'm going to close this as a duplicate. I suggest you 👍🏼 the other issue.
