### ISSUE TITLE
🐛 Bug Report: Creating new team with existed teamId throws error 500

### ISSUE THREAD

**Issue by huy-lv** [appwrite/appwrite#5768]
### 👟 Reproduction steps

I create a new team with existed team id:
Method: Post
Url: `Host/v1/teams`
Body: 
```
{
    "teamId": "63fc4cbb567e0d7d7f7d", //this team id already existed
    "name": "admin"
}
```
Response: 
```
{
    "message": "Server Error",
    "code": 500,
    "type": "general_unknown",
    "version": "1.3.4"
}
```

### 👍 Expected behavior

This should throw error "Team ID already existed" or something like that, error code should not be 500

### 👎 Actual Behavior

Response Server Error code 500
Log from docker:
![image](https://github.com/appwrite/appwrite/assets/7688070/b4643442-17c8-4ed5-a567-fd6426ae5996)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.3.4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@huy-lv, thanks for creating this issue! 🙏 We should definitely return a clearer error here.

**Comment by Abhijnan-Bajpai** [comment]
Hey there! I would like to try working on this. Could I be assigned?

**Comment by jaivix** [comment]
@stnguyen90 would love to help with this, can you assign it to me?

**Comment by sahilrawat001** [comment]
@stnguyen90 just a check must be include to overcome this error .Can you assign this issue to me

**Comment by stnguyen90** [comment]
@jaivix, assigned! Thanks for your interest! 🙏🏼

**Comment by TheOjasSingh** [comment]
can I work on this issue
