### ISSUE TITLE
🐛 Bug Report: problem when deploy collection from cli

### ISSUE THREAD

**Issue by TechComet** [appwrite/appwrite#5772]
### 👟 Reproduction steps

I first create Database and Collection in appwrite console .. then
`appwrite init collection`
now I create new document in my collection from web console
after that I override this collection from cli with `appwrite deploy collection`

### 👍 Expected behavior

Delete all data and documents from collection
or accept changes

### 👎 Actual Behavior

lost all data **but not lost documents** from collection
it's view empty documents

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite 1.3.7
Appwrite CLI 2.0.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Thanks for opening this issue @TechComet . I feel this issue relates to this one - https://github.com/appwrite/appwrite/issues/3520 and it is currently being worked on

**Comment by TechComet** [comment]
No,

it's more relates to this
https://github.com/appwrite/appwrite/issues/5586

**Comment by stnguyen90** [comment]
> No,
> 
> it's more relates to this #5586

You're right. I'm going to close this as a duplicate.
