### ISSUE TITLE
🚀 Feature: sdk for setup single database of project by default

### ISSUE THREAD

**Issue by TechComet** [appwrite/appwrite#5773]
### 🔖 Feature description

Most projects use a single database

I write example for getDocument but I talk for all functions

and write class for call function direct with default client
samething like this class but inside appwrite package

https://pastebin.com/raw/txMGE7Bh

### 🎤 Pitch

example in Dart
```
Client client = Client();
client
    .setEndpoint(appwriteEndpoint)
    .setProject(appwriteProjectId)
    .setDefaultDatabase('defaultdb')
    .setSelfSigned(status: appwriteSelfSigned);
```

in get document if use default database `databaseId is null`
`database.getDocument(collectionId: 'collectionId', documentId: 'documentId');
`
in get document if use other database
`database.getDocument(databaseId: 'other databaseId', collectionId: 'collectionId', documentId: 'documentId')`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by safwanyp** [comment]
Trying to understand this concept. 

So you are suggesting that we should be able to set the default database in your project while initializing your client right? 

If that's the case, then I can see why this can be useful, but it seems like a not-so-necessary thing. You're absolutely right when saying that most projects use a single DB, but countless others use multiple as well. This can be countered by making the `setDefaultDatabase` call optional, but I still don't see much value in adding something like this. 

Might be completely wrong though. Just my opinion!

**Comment by TechComet** [comment]
Ease of use
Code abbreviation
It will be possible to select a database within the function as it is now so the old code will not be broken

**Comment by TechComet** [comment]
anyone can use single database or multi project but if not write databaseId in getDocument use default (see example in first comment)

**Comment by byawitz** [comment]
You can see that in an older version of Appwrite, [this](https://github.com/appwrite/sdk-for-flutter/blob/2.1.0/lib/services/database.dart#L13) for example

The Database layer was added in version [0.15](https://github.com/appwrite/appwrite/releases/tag/0.15.0), check [here](https://github.com/appwrite/appwrite/pull/3338) more about that.

What I think can be a way around it is to wrap those functions in some small helper. For example:
```dart
class ProjectDB {
  String databaseID;
  Databases database;

  ProjectDB({this.databaseID = '', Client client}) {
    database = Databases(client);
  }

  Future<models.DocumentList> listDocuments({required String collectionId, List<String>? queries}) async {
    
    return await databases.listDocuments(
        databaseId: databaseID,
        collectionId: collectionId,
        queries: queries
    );
  }
}
```

Although I agree that it would be nice to have something like you've suggested, like:
```dart
databases.setDefaultDB(databaseId);

// Use Default
await databases.listDocuments(
        collectionId: collectionId,
        queries: queries
    );

// Specify DB
await databases.listDocuments(
        databaseId: databaseID,
        collectionId: collectionId,
        queries: queries
    );

```

**Comment by stnguyen90** [comment]
@TechComet, thanks for raising this! 🙏🏼 

We actually had a way to set the databaseId for all requests in the past, but this lead to more confusion especially when trying to explain how creating databases worked (with a server SDK). That's why we changed the SDKs to explicitly require a databaseId parameter. This is a bit more repetitive, but being explicit avoids confusion.

As @byawitz mentioned in https://github.com/appwrite/appwrite/issues/5773#issuecomment-1624709618, you're more than welcome to create a wrapper in your code.
