### ISSUE TITLE
🐛 Bug Report: Selecting specefic segment in doc fall-back to Cloud as default

### ISSUE THREAD

**Issue by Vedsaga** [appwrite/appwrite#5779]
### 👟 Reproduction steps

Visit https://appwrite.io/docs/server/databases?sdk=python-default&v=1.3.x#databasesUpdateUrlAttribute
1. Switch the version from `Cloud` -> `1.3.0` 
2. Click on `Update String Attribute`

And, now we can see that Document switches from `1.3.0` -> `Cloud`

### 👍 Expected behavior

It should not switch the cloud, it should store the version which user have selected.

### 👎 Actual Behavior

Version is getting reset to cloud instead of staying at the version user selected.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Vedsaga** [comment]
btw, I saw using Firefox browser

**Comment by gewenyu99** [comment]
Thanks! Followed up on Discord, self assigning

**Comment by byawitz** [comment]
Also Cloud `REST` example are empty
![image](https://github.com/appwrite/appwrite/assets/316103/157c664e-b106-4335-8097-e8b3c096cda5)

**Comment by gewenyu99** [comment]
> Also Cloud `REST` example are empty ![image](https://user-images.githubusercontent.com/316103/251634431-157c664e-b106-4335-8097-e8b3c096cda5.png)

This is expected. In fact the bugs is that you shouldn't be able to select REST for cloud at all.

We didn't start generating examples for REST and GraphQL until 1.2.x 😅

**Comment by byawitz** [comment]
🆒 At some point it didn't let to choose REST. But, recently it did and show nothing so... 😉

**Comment by gewenyu99** [comment]
> 🆒 At some point it didn't let to choose REST. But, recently it did and show nothing so... 😉

The bug is that I missed a case in the if statements 😆

**Comment by eldadfux** [comment]
Closing this issue as we switched to a new docs website.
