### ISSUE TITLE
🐛 Bug Report:  使用苹果账户登录

### ISSUE THREAD

**Issue by peter100u** [appwrite/appwrite#5782]
### 👟 Reproduction steps

使用苹果账户登录， 出现了失败
1. 拉起web版的苹果账号授权
2. 上面显示： 使用Apple ID "email" 为 "null"创建账户
3. 点击继续： 出现- 未完成注册

我应该都配置正确了，但是不知道问题出现在哪里

代码：

  static const String endPoint = 'https://cloud.appwrite.io/v1';

 _account.createOAuth2Session(
        provider: 'apple',
        success: "${AppwriteConstants.endPoint}/auth/oauth2/success",
        failure: "${AppwriteConstants.endPoint}/auth/oauth2/failure");

### 👍 Expected behavior

可以正常使用apple账户授权注册，并获取相关用户信息

### 👎 Actual Behavior

https://github.com/appwrite/appwrite/assets/14010579/bd881254-2eb7-43d6-a392-23b7e9b9ac3b

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E772610a darwin-arm64, locale zh-Hans-CN)

appwrite: 9.0.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Discord thread: https://discord.com/channels/564160730845151244/1126843125931982949

**Comment by joeyouss** [comment]
Hi @peter100u , is this working for you now?

**Comment by stnguyen90** [comment]
@peter100u, are you still facing this problem or can this be closed now? FYI, I'll need to close this due to inactivity soon.
