### ISSUE TITLE
🚀 Feature: Standalone Edge Functions.

### ISSUE THREAD

**Issue by byawitz** [appwrite/appwrite#5787]
## 🖋️ The Idea

Add the option to deploy standalone functions, and make them edge ready.

Appwrite functions are meant to be used only **through** the Appwrite system. Meaning any execution of any function must go through `Treafik > Appwrite > Executor > Function` and each part is doing verification in the process.

For example:

- The Appwrite container is checking the permissions for the functions,
- The request goes through the Utopia-PHP initiation process.
- Usages are being saved to the database.

Of course, this method is a very good one, and this feature is not about improving that aspect, as it's great.

What I'm suggesting is to add the ability to deploy functions that will behave as small backends in the cloud (or in any self-hosted Appwrite out there).

Take for example:

- Cloudflare worker (on the edge)
- Netlify Edge Functions

The main advantage of using them - as I've in the past - is that you're not obligated to the whole platform product but you get an endpoint that you can add to your app.

To summarize the main idea is to have functions that when executing them, the path from the frontend user to the function it self will be the shortest possible.

Attached a table to show the difference between the Appwrite function and the hypothetical Appwrite Standalone-functions

| Feature                                        | Cloud Functions                               | Standalone Functions |
|------------------------------------------------|-----------------------------------------------|----------------------|
| Request type                                   | Through Appwrite middlewares                  | **Direct**           |
| Protect by Appwrite permissions & rate limiter | ✅                                             | ❌                    |
| Faster                                         | ❌                                             | ✅                    |
| Can access Appwrite resources                  | ✅                                             | ✅                    |
| Edge ready                                     | ✅ **Requires** other services to be edge-able | ✅                    |

## 📃Examples

A few examples may help to understand the benefits of having a standalone function.

<details>
<summary>Leads collecting.</summary>

Given a frontend form in which you want to gather leads and insert them into some Google Sheets.
You can go by creating a whole backend, or even a simple endpoint in some server to do that process.

For that, Appwrite functions are great as you can have an endpoint on demand for you online.
But, this function doesn't need to use Appwrite modules other than functions. so for this use case, a standalone function will be the right fit.

</details>

_____

<details>
<summary>YouTube comments checker</summary>

Running function every `X` minutes to check if there are new YouTube comments, if so, notify in Discord/Slack/Telegram.

This function would be great to have on the cloud. And, again, there's no need for all Appwrite architecture but to be able to have an online endpoint.

</details>

_____

<details>
<summary>Image resizer</summary>

A cloud function that can get an image from a user resize it and return the ready-to-use image.

</details>

_____

## 🌍Edge functionally

One of the hard parts to deliver computed resources over the edge is the fact that resources are dependent on other services, and then - for example - even if the function container is close to the user the database in question is still far, and so on, meaning the user won't enjoy the edge advantage.

But, for standalone functions when a user deployed a decentralized self-hosted Appwrite, then, any time a user will execute a standalone function you can be sure the execution will be 100% over the edge (by GeoDNS, [ClouDNS](https://www.cloudns.net/geodns/), [AWS Route53](https://aws.amazon.com/route53/pricing/) or other smart load balancers) and you will get the fastest execution times for a remote computation.

## 🏃‍♂️ Benchmark table

The benchmark (and load test) was done on a simple Appwrite function that fetches a document from the database by a slug.
Both tests were done through a local network in a six bucks DigitalOcean server with 1 CPU & 1 GB of RAM.

| Method               | Per second | Per minute |
|:---------------------|:----------:|:----------:|
| Through              |     16     |    1,005    | 
| Direct               |     69     |    4,158    |
| Direct - No Appwrite |    2,987    |   179,260   |

`Direct` is 4.1 times faster!
`Direct- No Appwrite` is 178 times faster!

<details>
<summary>How the benchmark was done?</summary>

Benchmark was done using [oha](https://github.com/hatoo/oha).

The function check was pretty straightforward and was done by loading the REST API for executing Appwrite functions, as such:

```sh
oha http://127.0.0.1/v1/functions/functionID/executions \
   -z 60s \
   -m POST \
   -H "Content-Type: application/json" \
   -H "x-appwrite-project: projectId" \
   -H "X-Appwrite-Key: APIKey" \
   -d '{"data":"function-data"}'
```

Then I've run

```
docker network inspect appwrite_runtimes
```

That gave me something like this

```json
"longId": {
 "Name": "functionID-deploymentId",
 "EndpointID": "longId",
 "MacAddress": "02:42:c0:a8:20:04",
 "IPv4Address": "192.168.32.4/20",
 "IPv6Address": ""
},
```

Now I ran

```
docker exec -it functionID-deploymentId env
```

And extracted the `INTERNAL_RUNTIME_KEY` value and had set is value as the `x-internal-challenge` header value. 

After all of that, I was able to run the tests directly to the assigned IP:

```sh
oha http://192.168.32.4:3000 \
   -m POST \
   -z 60s \
   -d '{"variables":{"APPWRITE_FUNCTION_DATA":"data"},"payload": "data"}' \
   -H "Content-Type: application/json" \
   -H "x-internal-challenge: 6a7d608dc453de2ffbc4648d750b568f" 
```

</details>

### 🎤 Pitch

The main idea in this feature request, like other features request I'm posting is to enlarge the biggest-picture aspect when using Appwrite.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
@eldadfux Thanks for your answer and your time 👍 👍 

I want to point out a few things.

What I'm referring is to the option to use Appwrite (and OpenRuntime) functions as an **independent** cloud endpoint. 

Meaning that some additional Appwrite container (or any other way) will redirect these function requests without any checking whatsoever.

In other words, using Appwrite to have a cloud endpoint just for day-to-day tasks. Instead of having the need to deploy a server, etc. I can just have a "few bucks Appwrite server" for many small tasks I have.

In the benchmarking parts, I meant to demonstrate the speed differences in case you execute the function directly without letting it go through Utopia-php initiation steps, permission, and rate limit checks.

So I didn't in this issue to point out any issue with Appwrite performance. But to point out the difference that can happen performance-wise when letting a function run on its own. 

I know this is not the most common case as Appwrite intends to be the **whole package**, and in the case of a project with Database, Auth, and other Appwrite goodies it sure will be best to run the function through Appwrite security and other layers. 

<details> <summary>p.s. </summary>

I'm tracking the next generation of Appwrite functions and already played with the new features - which are great!
![image](https://github.com/appwrite/appwrite/assets/316103/4e50122f-6260-4309-a92e-f47c4fe8fa86)

</details>

**Comment by eldadfux** [comment]
Got it.

if you mean that you’d like to use open runtimes as a standalone product, that is something we’d like to support, but obviously this is not as high priority as other Functions features. Allowing such a standalone functionality directly on Cloud might be risky as we’ll very little means to ensure it runs well in production.

Regarding Appwrite endpoint overhead, me and @Meldiron run some tests, and we’ve been able to reduce the overhead and improve performance by x2.5 + we found some areas where the server is blocking requests which we can avoid and fix. We don’t yet have exact numbers, but I believe the boost should be at the same scale or even bigger. I’ll keep you posted.

**Comment by byawitz** [comment]
Agreed, as Appwrite function is meant to be the "whole package" 👍 
I'm excited to see the new G4 function performances. 

Thanks.
