### ISSUE TITLE
🐛 Bug Report: Invalid argument (callbackUrlScheme): must be a valid URL scheme: "appwrite-callback-<project_id>"

### ISSUE THREAD

**Issue by bhagn** [appwrite/appwrite#5794]
### 👟 Reproduction steps

Create a project with identifier that contains upper case characters - ex: `MyProject`, the web oauth login fails in flutter. There's a `FluuterWebAuth2._assertCallbackScheme` that validates the callback scheme against this regex:

```
static final RegExp _schemeRegExp = RegExp(r'^[a-z][a-z\d+.-]*$');
```

### 👍 Expected behavior

Appwrite console should validate and prevent users from creating invalid project identifiers.

### 👎 Actual Behavior

Appwrite console allows any value for a `Project Id`

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
It seems like Appwrite ID are `case-insensitive` so you can try to just rename your project to all lower-case in your project files, you can read more details [here](https://discord.com/channels/564160730845151244/1120835483849724036/1120835483849724036).

Also, track this issue https://github.com/appwrite/appwrite/issues/5670

**Comment by Haimantika** [comment]
Thanks for raising this issue @bhagn, our team will look into it. Did you also try renaming as suggested by @byawitz ?

**Comment by bhagn** [comment]
@Haimantika Thanks. Yes, I tried using the same id in lower case and **it works**.

**Comment by Haimantika** [comment]
> @Haimantika Thanks. Yes, I tried using the same id in lower case and **it works**.

Great to know that! Can I go ahead and close this issue then?

**Comment by bhagn** [comment]
@Haimantika Yes, please.

**Comment by bhagn** [comment]
@Haimantika I think this issue needs to be re-opened - as the work-around is not a solution. (works only on web). 
This creates issues with mobile app oauth - where we set `CFBundleURLSchemes` to `appwrite-callback-[PROJECT_ID]`. `Account.get()` will always return 401. There needs to be a validation to check that users are not overriding the project ID with invalid characters.
