### ISSUE TITLE
🐛 Bug Report: Storage File deleted accidentally from digital ocean spaces on move

### ISSUE THREAD

**Issue by fogelito** [appwrite/appwrite#5814]
### 👟 Reproduction steps

Storage::setDevice('files', new DOSpaces('bla', params...);

$device = Storage::getDevice('files');
$device->move($from, $to);

in case 
$from === $to 
are accidentally the same, the file gets deleted.

### 👍 Expected behavior

An Exception should be thrown.

### 👎 Actual Behavior

The $from file gets DELETED 

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Putting this in backlog as of now

**Comment by joeyouss** [comment]
Here lies the PR: https://github.com/utopia-php/storage/pull/84

**Comment by fogelito** [comment]
This issue was fixed Here 
https://github.com/utopia-php/storage/pull/84

Closing it
