### ISSUE TITLE
🚀 Feature: Email OTP login

### ISSUE THREAD

**Issue by binaryfire** [appwrite/appwrite#5818]
### 🔖 Feature description

Hi all

Are there plans to add email OTP login? We've been using it with Supabase and it's been great.

Magic Links don't work well for PWAs. Apple are recommending against them for PWAs and suggest codes instead. See timestamp 7:40 in this video: https://developer.apple.com/videos/play/wwdc2023/10120/

### 🎤 Pitch

It's more secure than passwords because:

1. It eliminates the potential for phishing attacks 
2. It removes the problems associated with weak and reused passwords

And password security can be bypassed via email anyway (using "Forgot password").

It'll also bring Appwrite's auth up to feature-parity with Supabase: https://supabase.com/docs/reference/javascript/auth-signinwithotp

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Cvr421** [comment]
Hii @binaryfire Can I work on these issue . I am a full stack developer and also I am new to these community .

**Comment by binaryfire** [comment]
Hi @Cvr421. That sounds great, but I'm not a maintainer. Perhaps @eldadfux can let you know?

**Comment by Cvr421** [comment]
Ok thanks

**Comment by joeyouss** [comment]
Hi, we do have a pending PR for this: https://github.com/appwrite/appwrite/pull/3912

**Comment by binaryfire** [comment]
@joeyouss Thanks, didn't see that. I'll close this and add my comments there.

**Comment by stnguyen90** [comment]
Duplicate of https://github.com/appwrite/appwrite/issues/3893
