### ISSUE TITLE
🚀 Feature: Function active deployment label

### ISSUE THREAD

**Issue by mbos2** [appwrite/appwrite#5826]
### 🔖 Feature description

![image](https://github.com/appwrite/appwrite/assets/56090587/d5137ec2-d531-4bac-ae7f-1d3a8bd416f8)
Some label that labels currently active function deployment would be nice.

### 🎤 Pitch

Would like to know what is the currently active deployment in the function deployments page, because we can manually change them.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mbos2** [comment]
Oh, and sorting them by created date in descending order would also be nice so the latest deployment is on top

**Comment by joeyouss** [comment]
Hey @mbos2 , how will it be different from active and Inactive headings in Functions?

**Comment by mbos2** [comment]
> 

In case of pretty large amount of deployments, and since we can set active deployment manually, we won't need to search deployment ID.

Also, here's a bug

![image](https://github.com/appwrite/appwrite/assets/56090587/c71f2287-6cfd-4247-9ab9-6fe01c8d7339)

**Comment by eldadfux** [comment]
This bug was fixed. Fix will be available in Appwrite 1.4.
