### ISSUE TITLE
🚀 Feature: Allow to change the filename once it is uploaded or allow to add metadata to buckets

### ISSUE THREAD

**Issue by ajitsinghkaler** [appwrite/appwrite#5835]
### 🔖 Feature description

Once we upload a file we cannot change its name. As we cannot add metadata to the files the only way is to create a corresponding collection which holds data. But i thought I can add some data atleast to the name. 

I think the best solution is to allow to add metadata to files and allow queries on the metadata.

### 🎤 Pitch

I want to make my files archived for 30 days if someone delete any file so that they can recover that file in 30 days. SO I thought of adding archived as a prefix to any file that is deleted but I could not update a file name once uploaded. I think the best solution is to allow metadata with files. So that you can run queries using it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Thanks for the feature request @ajitsinghkaler , our Design team will look into this soon.

**Comment by Haimantika** [comment]
This issue has now been put in backlog and we will address it in the next release.

**Comment by d4rckh** [comment]
Great news!

**Comment by eldadfux** [comment]
The PR has been merged, and this feature will be available in Appwrite 1.4.
