### ISSUE TITLE
🚀 Feature: Make password optional for login via phone or magic url in client sdk

### ISSUE THREAD

**Issue by ajitsinghkaler** [appwrite/appwrite#5836]
### 🔖 Feature description

When someone logs in via phone or magic url. To update there email and phone they need to set a password but these users don't have a password so I can't give a password. I think password should be optional for users that login via phone or magic url.

### 🎤 Pitch

I want to allow people to login via phone and magic url. Once someone logs in via email or phone I want them to update the other part and after that they can use the other method for login too. But if I have logged in via phone or email I need a password to change the other.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ajitsinghkaler, btw, as of 1.4.0, Appwrite won't validate password for users without a password. Related PR:

* https://github.com/appwrite/appwrite/pull/5621

**Comment by ajitsinghkaler** [comment]
Thanks
