### ISSUE TITLE
🐛 Bug Report: AAC files have wrong Mime Type

### ISSUE THREAD

**Issue by egortabula** [appwrite/appwrite#5848]
### 👟 Reproduction steps

I uploaded an AAC audio file to a bucket using the Appwrite console.

Due to the incorrect MIME type detection of the file, I am unable to play it in the browser. Instead of the player, a blank page with gibberish characters is displayed.
<img width="1512" alt="Screenshot 2023-07-20 at 01 41 58" src="https://github.com/appwrite/appwrite/assets/64892468/854c5f02-21d1-46ec-bef9-dc1ffa15a5ce">
<img width="1204" alt="Screenshot 2023-07-20 at 01 41 49" src="https://github.com/appwrite/appwrite/assets/64892468/3b930f3a-ebb5-4183-8384-ec335a68c5e1">

### 👍 Expected behavior

The MIME type of the file should be **audio/aac**.

### 👎 Actual Behavior

The MIME type of the file is being detected as **audio/x-hx-aac-adts**.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Hi @egortabula thanks for raising this issue, our team will be looking into it soon. May I also ask which browser you are using?

**Comment by Haimantika** [comment]
> Hello! I use Safari and Google Chrome. For information, I have also tried to upload **.m4a** file and I have also the same problem.

We have worked on a fix for this issue - https://github.com/appwrite/appwrite/pull/5875 , just waiting for the release :)

**Comment by egortabula** [comment]
> > Hello! I use Safari and Google Chrome. For information, I have also tried to upload **.m4a** file and I have also the same problem.
> 
> We have worked on a fix for this issue - #5875 , just waiting for the release :)

Thank you very much:)

**Comment by JonR-lang** [comment]
I'm having the same issues. It looks like it has not been fixed. 

.m4a files cannot be streamed using getFileView, but it can be downloaded apparently.
