### ISSUE TITLE
🐛 Bug Report: adding a document with invalid data to a one-to-many relationship can 500 error

### ISSUE THREAD

**Issue by t0mm4rx** [appwrite/appwrite#5851]
### 👟 Reproduction steps

Hello,

I have collection A containing multiple documents from collection B using a one-to-many relationship attribute.

Sometimes, I can create a document Z with invalid data in collection B (for example a string longer than the allocated size).

When appending this invalid document to document X of collection A, it throws a 500 error.

Moreover, the invalid document seems to be kept in some sort of cache, because after that I can't update any fields of document X, or it throws a 500 error.

Here is a Discord forum post discussing this issue: https://ptb.discord.com/channels/564160730845151244/1130915010013565000

### 👍 Expected behavior

In the first place, we shouldn't be able to create a document with invalid attributes.
Appending an invalid document to a relationship should yield a proper exception, and not add the invalid document as a relationship.

### 👎 Actual Behavior

The server throws a 500 error and add the invalid document as a relationship.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Self-deployed 1.3.7.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Thanks @t0mm4rx for raising this issue, will check with my team to see how we can help you. Also, please note that relationship is still in beta, we hope to resolve most of the issues in the upcoming releases.

**Comment by fogelito** [comment]
@abnegate I am tryingto re-produce the steps to get the error on 1.4.x
I am getting 400 Errors not 500
https://github.com/appwrite/appwrite/pull/6507/files#diff-4080028c5686d63ad43da263af384bcf4e40e719533fd6aebc33bd151c8a6d88R42

@t0mm4rx Maybe in Version 1.3.7 This problem was an issue and it is fixed now

**Comment by abnegate** [comment]
@fogelito Thanks, will close this as potentially fixed in a later release. @t0mm4rx please re-open if you're able to reproduce in 1.4.x onwards
