### ISSUE TITLE
🐛 Bug Report: GitHub OAuth2 Not Working SvelteKit

### ISSUE THREAD

**Issue by bitlogist** [appwrite/appwrite#5858]
### 👟 Reproduction steps

```ts
import { ID, Permission, Role } from 'appwrite'
import type { Models } from 'appwrite'
import { get, writable } from 'svelte/store'
import { sdk, server } from '$lib/appwrite/appwrite'

export type State = {
  account: Models.User<Models.Preferences> | null
}

const createState = () => {
  const { subscribe, set, update } = writable<State>({
    account: null,
  })

  return {
    // ...
    oAuth: async (provider: string, redirectURL: string) => {
      sdk.account.createOAuth2Session(provider, redirectURL) // have no idea how to get user information

      const urlParams = new URLSearchParams(window.location.search)
      const code = urlParams.get('code')

      console.log(code) // nothing
    }
  }
}

export const state = createState()
```

```ts
// ...
<IconButton on:click={() => state.oAuth('github', `https://${data.hostname}`)}></IconButton>
// ...
```

### 👍 Expected behavior

I should be able to access the user's GitHub details. The `createOAuth2Session` function does not return anything. 

### 👎 Actual Behavior

OAuth and redirection was successful but no code parameter was passed onto my application.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

- TypeScript
- SvelteKit
- Web SDK
- Gitpod
- Vercel

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@bitlogist, thanks for raising this issue! 🙏🏼 

> OAuth and redirection was successful but no code parameter was passed onto my application.

This is expected. On the web, the flow is:

```
[ Your App ]  -> [ Appwrite ] -> [ OAuth2 Provider ] -> [ Appwrite ] -> [ Your App ]
```

The OAuth2 code is sent to Appwrite and Appwrite exchanges it for the access token to authenticate the user and create an Appwrite session. When the user is redirected from Appwrite to your app, a cookie is set for the session. At that point, if your app is able to make use of the cookie, it will be able to make the related API calls to Appwrite.

To ensure your app can use the cookie, you'll need to either

1. enable 3rd party cookies (can be done in your browser settings)
2. have your appwrite endpoint be a subdomain of your app (e.g. appwrite.example.com and example.com). For more information, refer to https://appwrite.io/docs/custom-domains.

Another thing to point out is the `sdk.account.createOAuth2Session(provider, redirectURL)` redirects the user to Appwrite, so the rest of your code:

```javascript
      const urlParams = new URLSearchParams(window.location.search)
      const code = urlParams.get('code')

      console.log(code) // nothing
```

never executes. When the user is redirected back to `redirectURL`, your app starts from scratch.

I hope that clarifies thigns.

**Comment by intfract** [comment]
Is it not possible to use OAuth without 3rd party cookies?

**Comment by intfract** [comment]
I'm not sure if I can make it a subdomain because my SvelteKit app is deployed on vercel. Thanks anyway, though.

**Comment by stnguyen90** [comment]
@bitlogist, do you need anything else or can this be closed?
