### ISSUE TITLE
Ensure cached resource from correct bucket is deleted

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#5861]
When a file is deleted, we also delete it from the cache, but it looks like we look for cached resources based on resource:

https://github.com/appwrite/appwrite/blob/0a5d53ec35dbf28ae4da9f01c39f763efaf0890b/app/workers/deletes.php#L138

which is just a file ID:

https://github.com/appwrite/appwrite/blob/0a5d53ec35dbf28ae4da9f01c39f763efaf0890b/app/controllers/api/storage.php#L802

The problem with this is if a file has the same ID in multiple buckets, they'll also be deleted.

_Originally posted by @stnguyen90 in https://github.com/appwrite/appwrite/pull/5698#discussion_r1269913474_

**Comment by eldadfux** [comment]
Fix was merged and will be released in the next Appwrite version.
