### ISSUE TITLE
🐛 Bug Report: Swift functions won't deploy with more than one dependency

### ISSUE THREAD

**Issue by zachspang** [appwrite/appwrite#5863]
### 👟 Reproduction steps

Deploy a function in the Swift 5.5 runtime with more than one dependency in the Package.swift
_example Package.swift_
```
// swift-tools-version:5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "send-message",
    dependencies: [
        .package(url: "https://github.com/apple/swift-crypto.git", from: "2.0.3"),
        .package(url: "https://github.com/swift-server/async-http-client.git", from: "1.9.0"),
    ],
    targets: [
        .target(
            name: "send-message",
            dependencies: [
                .product(name: "Crypto", package: "swift-crypto"),
                .product(name: "AsyncHTTPClient", package: "async-http-client"),
            ]
        )
    ]
)
```

### 👍 Expected behavior

The function deployment will build and the function can be executed.

### 👎 Actual Behavior

The deployment instantly fails with this error,
![image](https://github.com/appwrite/appwrite/assets/90374182/f36b6cd3-497d-4acf-8fb0-1434b4357e25)

Issue is possibly extra commas being added here,
https://github.com/open-runtimes/open-runtimes/blob/1088ca0a76939cb9d54b8ef34f5d7114485e8d24/runtimes/swift-5.5/dependencies.swift#L93
https://github.com/open-runtimes/open-runtimes/blob/1088ca0a76939cb9d54b8ef34f5d7114485e8d24/runtimes/swift-5.5/dependencies.swift#L127

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.3.7, Ubuntu 22.04

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@zachspang, thanks for raising this! We'll look into getting this fixed.
