### ISSUE TITLE
🐛 Bug Report: appwrite total results stuck on 5000

### ISSUE THREAD

**Issue by issasaleh** [appwrite/appwrite#5864]
### 👟 Reproduction steps

in the appwrite console, the total document count is stuck on 5,000 documents, I have 14k documents but the total result is stuck on 5000.

### 👍 Expected behavior

it should have the right total count

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/114824732/7188dc40-9af6-47cc-b3a2-a19870c0b4ad)

![image](https://github.com/appwrite/appwrite/assets/114824732/3e324a85-7ce9-4ad6-87b5-2211ccf9e713)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.3.7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by issasaleh** [comment]
Documents more than 5000 do not appear in the console.

the maximum is 96 Documents per page. 53 pages. anything more than that disappears.

Even when making an api call it shows the total number is 5000 documents.
![image](https://github.com/appwrite/appwrite/assets/114824732/ab32e0e0-8c8d-48de-b7af-cec207b3d3be)

Did this problem happen to me only or is it a general problem?

**Comment by Haimantika** [comment]
Hi @issasaleh thanks for opening this issue. Count queries can take a lot of time to run so we only count up to 5000. You can list documents beyond that using offset or cursor pagination

**Comment by Haimantika** [comment]
> Hi @issasaleh thanks for opening this issue. Count queries can take a lot of time to run so we only count up to 5000. You can list documents beyond that using offset or cursor pagination

@issasaleh closing this issue for now. If you have any additional questions feel free to reopen or ask us on discord - https://appwrite.io/discord
