### ISSUE TITLE
🐛 Bug Report: Swift and Deno Function error while deploying using Digital Ocean droplet

### ISSUE THREAD

**Issue by joeldrotleff** [appwrite/appwrite#5865]
### 👟 Reproduction steps

1. Create an AppWrite instance on Digital Ocean by creating a Droplet from the AppWrite template.
2. Set .env to _APP_FUNCTIONS_RUNTIMES=deno-1.24,swift-5.5,node-16.0
3. Initialize a Deno, Swift, and Node function via CLI (`appwrite init function`)
4. Deploy functions w/ `app write deploy function`

### 👍 Expected behavior

Functions should deploy correctly without errors

### 👎 Actual Behavior

The Node function deploys correctly and runs 

The Deno function errors out with:

```
0m[33mWarning[0m Implicitly using latest version (0.195.0) for https://deno.land/std/streams/conversion.ts
[0m[32mDownload[0m https://deno.land/std@0.195.0/streams/conversion.ts
[0m[1m[31merror[0m: Module not found "https://deno.land/std/streams/conversion.ts".
    at https://deno.land/x/appwrite@6.0.0/src/inputFile.ts:1:42
```

The Swift function errors out with:

```
Operation timed out after 900001 milliseconds with 0 bytes received with status code 0
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I created a Droplet on Digital Ocean w/ 2gb ram, Ubuntu 22.04 created from this template: https://marketplace.digitalocean.com/apps/appwrite

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeldrotleff** [comment]
To investigate the issue further I went looking in the open runtimes thing on docker, i.e. here: https://hub.docker.com/r/openruntimes/deno

In the sidebar it says to run `docker pull openruntimes/deno` but when I run that from my docker instance I get:
```manifest for openruntimes/node:latest not found: manifest unknown: manifest unknown```

Same for Node and Swift runtimes

**Comment by Haimantika** [comment]
Hi @joeldrotleff thanks for bringing this issue up. I will be checking with the team to understand why this is happening. Also, did you migrate to 1.3.8?

**Comment by joeldrotleff** [comment]
Re: migrate, on my droplet in my docker-compose.yml file, I see 'image: appwrite/appwrite:1.3.8'. So it looks like I'm on 1.3.8.

**Comment by Haimantika** [comment]
> Re: migrate, on my droplet in my docker-compose.yml file, I see 'image: appwrite/appwrite:1.3.8'. So it looks like I'm on 1.3.8.

Thanks for the response. I have notified my team, someone will look into it ASAP.

**Comment by Haimantika** [comment]
Also, @joeldrotleff it will be great if you can repost this question in our support channel in discord - https://appwrite.io/discord , our team will be assisting you there :)

**Comment by stnguyen90** [comment]
@joeldrotleff

> The Deno function errors out 

Would you please try updating the appwrite package in your deps.ts to 7.0.0?

**Comment by joeldrotleff** [comment]
@stnguyen90 Ok so that worked! My Deno deploy was successful now. 

I tried the same thing for a Swift function (Updating Package.swift file) but that doesn't seem to have worked, still errors out on deploy:

Here is what my Package.swift looks like:

let package = Package(
    name: "swift-5.5",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/appwrite/sdk-for-swift", .upToNextMajor(from: "2.0.0")),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .executableTarget(
            name: "swift-5.5",
            dependencies: [
                .product(name: "Appwrite", package: "sdk-for-swift")
            ]),
    ]
)

**Comment by joeldrotleff** [comment]
I also verified that Package.resolved is showing 2.0.0:

      {
        "package": "Appwrite",
        "repositoryURL": "https://github.com/appwrite/sdk-for-swift",
        "state": {
          "branch": null,
          "revision": "51f325b11ea10949cf12af363fc5fb4f652abbf2",
          "version": "2.0.0"
        }
      },

**Comment by joeldrotleff** [comment]
@stnguyen90 Any ideas on the Swift runtime issues?

**Comment by stnguyen90** [comment]
Swift takes a long time to compile. You probably need more CPU and memory to build the function so it doesn't time out.
