### ISSUE TITLE
🐛 Bug Report: Many-to-Many Relationship Updated with Non Existing Documents

### ISSUE THREAD

**Issue by noob8boi** [appwrite/appwrite#5871]
### 👟 Reproduction steps

1) Create a collection with a relationship attribute (many-to-many).

2) Create a normal document with no items in the relationship.

3) Update the document's relationship attribute by providing a list with one incorrect value and two or three correct values. For example, let's say `"light_attack"` and `"quick_dodge"` documents exist in another collection, and now you update with:
`{"relationAttribute": ["light_attack", "quick_dodge", "fake_id"]}`

4) You will realize that the updated document has the correct items, i.e., `"light_attack"` and `"quick_dodge"` but since the `"fake_id"` document never existed, it was replaced by an empty list.

### 👍 Expected behavior

There should be an error thrown because I am trying to update the document with a non-existing document ID inside the relation attribute (many-to-many)

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/91360152/e5dd8ef3-2110-45c7-a604-76ef79cf18cf)
An empty list or empty array is being added.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.3.4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by noob8boi** [comment]
Also if you will use listDocuments method then that empty array won't appear but if you use getDocument then the response body will contain that empty array 🤔

**Comment by joeyouss** [comment]
Hi @noob8boi , I have taken this up with my team for any feedback - please note, Relationships are still in Beta so there is scope for improvement and additions before the public release. I will keep you posted about this.

**Comment by noob8boi** [comment]
> Also if you will use listDocuments method then that empty array won't appear but if you use getDocument then the response body will contain that empty array 🤔

Another thing I noticed is that even the 'APPWRITE_FUNCTION_EVENT_DATA' variable in the cloud function ignores the empty array. Also, no type of document update fixes this issue. The only way I could find to resolve it was to delete and re-create the document with updated proper values.

**Comment by joeyouss** [comment]
@noob8boi A PR is in progress, thanks for bringing this up

**Comment by fanatic75** [comment]
This has been fixed in 1.4
