### ISSUE TITLE
📚 Documentation: Update Databases API Python SDK documentation for the "data" parameter in update_document function

### ISSUE THREAD

**Issue by versun** [appwrite/appwrite#5872]
### 💭 Description

Document: [Databases API update_document function](https://appwrite.io/docs/server/databases?sdk=python-default#databasesUpdateDocument)
Currently, the documentation states that the "data" parameter is optional in the update_document function. 
However, during my testing, I found that the "data" parameter is required. Without it, the error message "The document payload is missing." is returned. 
Therefore, I kindly request  to update the documentation accordingly.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @versun , out of permissions and data, one must be provided and other can be omitted. I agree, we need to specify this on our docs. Looping in @gewenyu99 for the same, thanks for bringing this up.

**Comment by gewenyu99** [comment]
FYI this is going to be released in a future version
