### ISSUE TITLE
🐛 Bug Report: Cloud Function change creation date after ends to deploy

### ISSUE THREAD

**Issue by gepd** [appwrite/appwrite#5883]
### 👟 Reproduction steps

When I deploy a new function, if the previous deploy was long time ago, when it finish to deploy he function, the console change the creation date as the gift shows:

![Appwrite Bug](https://github.com/appwrite/appwrite/assets/7091609/9329cc07-2d4f-4d0e-9326-eb4cc97a2b18)

### 👍 Expected behavior

Show the current creation date time

### 👎 Actual Behavior

created date time is old

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gepd, thanks for creating this issue! 🙏 The thing is, that 1st row is actually the 2nd deployment. The most recently **active** deployment is above.

**Comment by gepd** [comment]
Ok I think I got it. 

The problem seems to be, there two rows, one for **active** and a second one for **inactive**. 

When you deploy the function, the deploying funtion is in the inactive row with the status of "building" and then the UI updates the info of the active deployment which cause some confusion as your sight is in the building line, you just see it disappear

**Comment by stnguyen90** [comment]
@gepd, yes exactly. Can this be closed now since the behavior is expected?

**Comment by gepd** [comment]
I was expecting to have more feedback from other users, I don't know if is only me, but I think it's a little weird to have the building deployment in the inactive row. I now It's inactive, however is can of weird or confusing to be in that position.

Maybe would be good to have some indicator (green dot, a tag, etc) to inform the new deployment is in the active section, what do you think?

**Comment by stnguyen90** [comment]
I'll let our team know and we'll see if anyone else from the community 👍🏼 this issue.

**Comment by stnguyen90** [comment]
@gepd, looks like there was another issue for this: https://github.com/appwrite/appwrite/issues/5826. Can we close this and you can 👍🏼 the other issue?

**Comment by EVDOG4LIFE** [comment]
Resolving as related issue is fixed as of 1.4.
