### ISSUE TITLE
🐛 Bug Report: Alignment issues

### ISSUE THREAD

**Issue by dokgu** [appwrite/appwrite#5889]
### 👟 Reproduction steps

Go to `Project` > `Auth` > `Sessions` - on the table, you'll see something like:

![session](https://github.com/appwrite/appwrite/assets/959300/7bb8b9a4-6425-4bf5-b5f3-831b4e7a8cf5)

The alignments are off because of the browser icons.

### 👍 Expected behavior

The icons should have fixed widths or if they don't their wrapper should be. The light circle behind the icons should be perfect circles instead of ovals.

### 👎 Actual Behavior

The icons do not have fixed widths so it messes up the alignments on the table.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.3.8 - self-hosted on a Linux VM but using Windows to access the pages.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi, this was fixed here: https://github.com/appwrite/console/pull/436 
Not released yet I guess

**Comment by eldadfux** [comment]
Fixed and released a while back, thanks for reporting.
