### ISSUE TITLE
Adding pull request template and issue template

### ISSUE THREAD

**Issue by iamrajiv** [appwrite/appwrite#589]

**Comment by iamrajiv** [comment]
@eldadfux I want to work on this issue.

**Comment by OmkarPh** [comment]
Does this issue still open?
I can work on it if nobody is working :)

**Comment by iamrajiv** [comment]
@OmkarPh I am working on this and have already made PR #590.

**Comment by eldadfux** [comment]
@OmkarPh A PR has already submitted. I'm waiting for more community feedback before accepting it.
