### ISSUE TITLE
🚀 Feature: Unique Value for few selected attributes of a document

### ISSUE THREAD

**Issue by vlohar08** [appwrite/appwrite#5906]
### 🔖 Feature description

In cases where we need a unique value for an attribute in every document, this feature can be helpful. The entire logic will be handled by appwrite and we may not have to do anything to make sure the values are unique.

Now, there are other ways to make sure that the values are unique. You can try fetching a document with that value and if no document is found then the value is unique.

But I guess appwrite can add this feature for better data handling.

### 🎤 Pitch

I was building a linktree clone and realized the need for this feature. So on linktree, you have to set your username which has to be unique for every new linktree. If Appwrite had this feature then all I have to do is mark the attribute as unique using the Appwrite console. And I will not be writing any code to handle the logic to make sure the values are unique.

Examples where this feature can be used -

1. A document with user email and phone details.
2. Social media username
3. Order Id and other critical fields for e-commerce

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by safwanyp** [comment]
This would definitely be beneficial in a lot of use cases. What's Appwrite's take on this? If this is a feature that is being considered to be implemented, would love to work on it!

**Comment by djcali570** [comment]
This would be a great feature.

**Comment by stnguyen90** [comment]
@vlohar08, thanks for raising this issue! 🙏🏼 In Appwrite, you can create a unique [index](https://appwrite.io/docs/products/databases/collections#indexes) that includes N attributes. How is your feature request different from Appwrite's unique indexes? 🧐
