### ISSUE TITLE
🐛 Bug Report: Invalid name: Value must be a valid string and at least 1 chars and no longer than 128 chars

### ISSUE THREAD

**Issue by donywan** [appwrite/appwrite#5907]
### 👟 Reproduction steps

When i add document,i get 'Invalid name: Value must be a valid string and at least 1 chars and no longer than 128 chars'.
1. Click` f12`
2. Check `Network`
3. `http://10.0.0.107/v1/projects/64c51c0e3b68e8bfaf89/platforms`
Request:
```
{"type":"flutter-android","name":null,"key":null}
```
Response:
```
{
    "message": "Invalid name: Value must be a valid string and at least 1 chars and no longer than 128 chars",
    "code": 400,
    "type": "general_argument_invalid",
    "version": "1.3.8"
}
```

### 👍 Expected behavior

Request:
```
{"type":"flutter-android","name": "Some value","key": "Some value"}
```

### 👎 Actual Behavior

Request:
```
{"type":"flutter-android","name":null,"key":null}
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite: 1.3.8

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by iampranavdhar** [comment]
This is the same issue that I got when I am trying to add a document in the local environment, but strangely it got solved for me without doing anything [not even pulled the latest comments] the next day.

**Comment by donywan** [comment]
> This is the same issue that I got when I am trying to add a document in the local environment, but strangely it got solved for me without doing anything [not even pulled the latest commits] the next day.

Wow,I tried it just now.You are right.
