### ISSUE TITLE
🚀 Feature: Add the ability to modify email templates

### ISSUE THREAD

**Issue by dokgu** [appwrite/appwrite#5908]
### 🔖 Feature description

There should be a mechanism for us to personalize or modify the emails being sent by appwrite:

- Adding our logo
- Modifying the email text
- Changing links to buttons
- Setting headers and footers
- ...and whatever else we can think of

### 🎤 Pitch

This would immensely improve brand identity.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by iampranavdhar** [comment]
What is the current form of sending mail? Is it generated by appwrite by default?

**Comment by dokgu** [comment]
> What is the current form of sending mail? Is it generated by appwrite by default?

Yes, you can try this out by clicking on forgot password or sending a verification email when a user registers on your app.

**Comment by joeyouss** [comment]
Hi, can you add your comments here: https://github.com/appwrite/appwrite/issues/729
We are actually already working on this and we have a draft. If it makes sense, we can close this issue to avoid duplicates, thanks!

**Comment by safwanyp** [comment]
@iampranavdhar If you're using a self-hosted instance of Appwrite, you will need to setup the appropriate SMTP environment variables in the `.env` file. These variables are available when you sign up with any SMTP provider (e.g. SendGrid).

If you're using Appwrite Cloud, receiving emails shouldn't be an issue. If you aren't receiving emails via cloud, let us know so the team can look into it.

**Comment by eldadfux** [comment]
Starting with Appwrite 1.4 you can now customize the SMTP server and email templates of every project 🎉

<img width="1438" alt="image" src="https://github.com/appwrite/appwrite/assets/1297371/3f40ba62-d51a-45a3-8152-a6575fb317fd">
