### ISSUE TITLE
🐛 Bug Report: Documentation for Teams API has incorrect order of parameters

### ISSUE THREAD

**Issue by dokgu** [appwrite/appwrite#5910]
### 👟 Reproduction steps

Go to https://appwrite.io/docs/server/teams?sdk=nodejs-default#teamsCreateMembership and look at the example, the order of parameters are:

1. Team ID
2. Email
3. Roles
4. URL

But when using the SDK on my project, the order is actually

1. Team ID
2. Roles
3. URL
4. Email or User ID or Phone Number

### 👍 Expected behavior

I was expecting the documentation and the SDK to be consistent.

Actually - I would prefer if the functions just accept an object with the parameters as properties:

```javascript
await teams.createMembership({
  teamId: TEAM_ID,
  userId: USER_ID,
  email: EMAIL,
  url: URL,
  roles: []
});
```

This way, the order in which you provide the parameters do not matter at all.

### 👎 Actual Behavior

The SDK and the docs aren't consistent.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

`"node-appwrite": "^9.0.0",`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by shaikahmadnawaz** [comment]
Can I work on this issue?

**Comment by joeyouss** [comment]
This has been fixed, not released yet: https://github.com/appwrite/docs/pull/381

**Comment by shaikahmadnawaz** [comment]
Okay, thank you @joeyouss

**Comment by joeyouss** [comment]
Closing this issue in favor of PR https://github.com/appwrite/docs/pull/381
