### ISSUE TITLE
🚀 Feature: Add an auth setting to prevent users from creating a session until they verify their account

### ISSUE THREAD

**Issue by dokgu** [appwrite/appwrite#5911]
### 🔖 Feature description

On the project's auth security page, add the ability to prevent users from creating a session until they verify their account.

### 🎤 Pitch

I need to prevent users from logging into my app if they haven't verified their account either through email / SMS / oAuth / etc.

We should be able to control how we handle users logging in who haven't verified their accounts yet.

My current solution is:

1. Call `account.createEmailSession()` - user tries to log in
2. Call `account.get()` - this should return an object with the property `emailVerification` which is a boolean state of the user's email validation (if I sent an email verification link after they registered)

This is done on the client side though which is not secure.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by OshriAsulin** [comment]
Hey, can i take this issue?

**Comment by gewenyu99** [comment]
@dokgu Have you considered using the `Role.users([STATUS])` permissions on all your resources?

you can do `Permission.read(Role.users('verified'))` and that should make all resources not visible unless they're verified users. Then, if your frontend notices nothing is loading, you can prompt them to verify :)

**Comment by dokgu** [comment]
> @dokgu Have you considered using the `Role.users([STATUS])` permissions on all your resources?
> 
> you can do `Permission.read(Role.users('verified'))` and that should make all resources not visible unless they're verified users. Then, if your frontend notices nothing is loading, you can prompt them to verify :)

I've talked to Steven before about this request, I implemented custom permissions on my collections with `users/verified`. I believe that should prevent unverified users from reading any data from any of my collections. What I don't like about that is I'm basically letting unverified users to get past the door (login page) - but when they enter the house, the furnitures are all covered. My request was more about not even letting unverified users to get past the door.

**Comment by Susmita-Dey** [comment]
Hey, I'd like to try out and solve this issue to make my first contribution

**Comment by gewenyu99** [comment]
> > @dokgu Have you considered using the `Role.users([STATUS])` permissions on all your resources?
> > you can do `Permission.read(Role.users('verified'))` and that should make all resources not visible unless they're verified users. Then, if your frontend notices nothing is loading, you can prompt them to verify :)
> 
> I've talked to Steven before about this request, I implemented custom permissions on my collections with `users/verified`. I believe that should prevent unverified users from reading any data from any of my collections. What I don't like about that is I'm basically letting unverified users to get past the door (login page) - but when they enter the house, the furnitures are all covered. My request was more about not even letting unverified users to get past the door.

I feel like this is something you can do on the client side. You'd just have your app/website log them out if they aren't verified + prompt them to verify. 

Alternately, you can just let them log in and prompt them to verify their accounts in UI. 

But I am open to other opinions. I would leave this here for discussion and see if there's more demand for this.

@Susmita-Dey if you'd like to give it a go, please feel free :)

**Comment by joeyouss** [comment]
Hey @gewenyu99 , 

I think you missed it but @OshriAsulin wanted to give it a go first. @OshriAsulin , if you're still up for the task, let us know, we'll assign it to you. If not @Susmita-Dey please take up this task 🙂

Thanks!

**Comment by CordMemescape** [comment]
> I feel like this is something you can do on the client side. You'd just have your app/website log them out if they aren't verified + prompt them to verify.

I think the point of the OP is that, while this can be handled client side, it shouldn't be.

Given that access to the data is via REST, if the back-end hands over the keys to the data to a client app with the expectation that the client app manages the access to that data, then it would be pretty trivial to create a malicious client app that can access the data without any safeguards. This isn't good security practice.

All access to data should be managed server side to prevent malicious clients from leaking that data.

**Comment by Susmita-Dey** [comment]
Okay, waiting for @OshriAsulin to reply

**Comment by OshriAsulin** [comment]
Sorry, I forget about this but currently, I can't I can to work on this issue

**Comment by gewenyu99** [comment]
> > I feel like this is something you can do on the client side. You'd just have your app/website log them out if they aren't verified + prompt them to verify.
> 
> I think the point of the OP is that, while this can be handled client side, it shouldn't be.
> 
> Given that access to the data is via REST, if the back-end hands over the keys to the data to a client app with the expectation that the client app manages the access to that data, then it would be pretty trivial to create a malicious client app that can access the data without any safeguards. This isn't good security practice.
> 
> All access to data should be managed server side to prevent malicious clients from leaking that data.

I can see where you're coming from. If I were suggesting you to hide data on the client side, that is a horrible approach.

But I'm not. **Data is inaccessible with permission settings that prevent unverified users from accessing them.**

NOTHING is returned by the APIs.

This means with the right permissions, they **will not be able to access anything.**

What's handled on the client side is that: because no data is accessible, prompt the user to verify their accounts.

I strongly believe this is a valid and secure approach.

**Comment by eldadfux** [comment]
I think @gewenyu99 approach is legit and secure. This is exactly why we designed a dedicated permission to allow only verified users to access database or storage data.

I wonder if this feature suggestion is still required in other potential use cases.

**Comment by stnguyen90** [comment]
Closing as Appwrite is working as designed.
