### ISSUE TITLE
🐛 Bug Report: Phone authentication env variable not parsing slash 

### ISSUE THREAD

**Issue by Mr-Malomz** [appwrite/appwrite#5913]
### 👟 Reproduction steps

When I configure `_APP_SMS_PROVIDER` e.g. Telesign. Use the Create `CreatePhoneSession()` method in a web application.

### 👍 Expected behavior

Create a session for the inputted phone number and receive an OTP to complete registration.

### 👎 Actual Behavior

When the Create `CreatePhoneSession()` method is used, it returns an error. 

Because the `API Key` used has a slash as part of the value, the system returns an `InvalidArgumentException: Unable to parse DSN` error.

Full error below
```
sms://E3CE8D57-97AD-XXXXXXXXXX:CNaceK4pHreLA1+et9nBIL8QhRUWdoTa6pi/qzk0D4HWXEjBaMcr15DHeUzXXXXXXXXXXX@telesign in /usr/src/code/src/Appwrite/DSN/DSN.php:54
Stack trace:

#0 /usr/src/code/app/workers/messaging.php(33): Appwrite\DSN\DSN->__construct('sms://E3CE8D57-...')

#1 /usr/src/code/src/Appwrite/Resque/Worker.php(98): MessagingV1->init()

#2 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(198): Appwrite\Resque\Worker->setUp()

#3 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()

#4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))

#5 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('1', false)

#6 {main}
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Mr-Malomz thanks for opening this! 🙏 Let me bring this up to the team to see how we can fix this.

**Comment by joeyouss** [comment]
Hi @Mr-Malomz the PR made to fix this is linked, we will close this issue soon, thank you for opening this! Appreciate the feedback!
