### ISSUE TITLE
🐛 Bug Report: Unable to delete team membership from user profile if the team doesn't exist

### ISSUE THREAD

**Issue by vlohar08** [appwrite/appwrite#5914]
### 👟 Reproduction steps

1) Add any auth user to any team.
2) Now delete the team without removing the user from it.
3) Now go to the user teams page and try to delete the membership.
You will get this error - **The Requested Team Invitation Could not be found**.

### 👍 Expected behavior

- If a team is deleted then the membership of that team should be removed from the user profile of all the members of that team.
- Or at least, it should allow us to delete the membership even if it doesn't exist without any error.

### 👎 Actual Behavior

- If the team is deleted without removing the membership from the user profile then the team name is changed to **n/a** and the **thumbnail** stops loading.
- If you try to delete the membership manually then you will get an error - **The Requested Team Invitation Could not be found**.
 
 ![image](https://github.com/appwrite/appwrite/assets/89565983/d99aa463-5660-43b8-91d3-28451de36c6c)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite Version - 1.3.8
Self-hosted on Digital Ocean using Marketplace Image

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by safwanyp** [comment]
Never tried doing this and I can see why this happens. I was going to suggest a custom function that triggers when `teams.*.delete` occurs, but it would cause the same issue I think. 

Interesting to say the least. Gonna take a small look into the code.

**Comment by safwanyp** [comment]
Alright so looking at the calls being made, it's pretty clear why this happens. 

Deleting a membership makes a `DELETE` request to `/v1/teams/:teamId/memberships/:membershipId` which would instantly be a mistake if the team does not exist, as `:teamId` would be non-existent. A `TEAM_NOT_FOUND` exception is thrown in the code as well. 

I think the best way to fix this would be to implement deletion of all memberships in a team, when a team is deleted. But it seems like this is already being done. Now I'm even more intrigued lol

**Comment by christyjacob4** [comment]
@vlohar08 thank you for raising this. We'll investigate this and share some more details :)

**Comment by safwanyp** [comment]
Hi Appwrite team. Can I be assigned to make a PR for this issue? I have fixed it on a local dev environment by adding the `membership` attribute to the allowed attributes list, and running a small delete function on the user.

**Comment by christyjacob4** [comment]
@safwanyp sure go ahead 😄 I'll assign it to you

**Comment by safwanyp** [comment]
> @safwanyp sure go ahead 😄 I'll assign it to you

Appreciate it Christy! Making a PR now 😁
