### ISSUE TITLE
🐛 Bug Report: Incorrect Logs

### ISSUE THREAD

**Issue by gerbernoah** [appwrite/appwrite#5927]
### 👟 Reproduction steps

I created a function (Node 16.0) and deployed it. The function contains this

```js
const regexTest = new RegExp(".*");
console.log(regexTest);
```

### 👍 Expected behavior

The console should log
```js
/.*/
```

### 👎 Actual Behavior

it logs
```js
{}
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gerbernoah, thanks for creating this issue! 🙏🏼 What's your full code?

**Comment by gerbernoah** [comment]
We found a workaround since its just the console log which is broken and not the `RegExp()`
Function:
```js
const sdk = require("node-appwrite");

/*
  'req' variable has:
    'headers' - object with request headers
    'payload' - request body data as a string
    'variables' - object with function variables

  'res' variable has:
    'send(text, status)' - function to return text response. Status code defaults to 200
    'json(obj, status)' - function to return JSON response. Status code defaults to 200

  If an error is thrown, a response with code 500 will be returned.
*/

module.exports = async function (req, res) {
  const client = new sdk.Client();

  // You can remove services you don't use
  const account = new sdk.Account(client);
  const avatars = new sdk.Avatars(client);
  const database = new sdk.Databases(client);
  const functions = new sdk.Functions(client);
  const health = new sdk.Health(client);
  const locale = new sdk.Locale(client);
  const storage = new sdk.Storage(client);
  const teams = new sdk.Teams(client);
  const users = new sdk.Users(client);

  if (
    !req.variables['APPWRITE_FUNCTION_ENDPOINT'] ||
    !req.variables['APPWRITE_FUNCTION_API_KEY']
  ) {
    console.warn("Environment variables are not set. Function cannot use Appwrite SDK.");
  } else {
    client
      .setEndpoint(req.variables['APPWRITE_FUNCTION_ENDPOINT'])
      .setProject(req.variables['APPWRITE_FUNCTION_PROJECT_ID'])
      .setKey(req.variables['APPWRITE_FUNCTION_API_KEY'])
      .setSelfSigned(true);
  }

  const regexTest = new RegExp(".*");
  console.log(regexTest);

  res.json({
    areDevelopersAwesome: true,
  });
};

```

testing unit:
```js
import { client } from '../../src/appwrite';
import { Functions } from 'appwrite';

const functions = new Functions(client);

test.only('a test', () => {
  functions.createExecution('64c9894b1ec19aa4db57');
});
```

**Comment by stnguyen90** [comment]
@gerbernoah, ahh I see the problem. In order for us to pass the data back from open runtimes to appwrite, Open Runtimes needs to stringify the logs if it contains an object. When a RegExp is stringified, it results in `"{}"`

<img width="219" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/8a549812-0dd4-4d29-a80b-6a8f12aeab53">

So, it would be best to convert the object to a string before passing it to `console.log()`.

**Comment by gerbernoah** [comment]
Thanks a lot. I think we can close this now
