### ISSUE TITLE
bug Bug Report:memberships queries 500 error

### ISSUE THREAD

**Issue by zsj1029** [appwrite/appwrite#5945]
https://cloud.appwrite.io/v1/teams/64cdc2e25694bb85b0d1/memberships?queries=[Query.limit(25)]

https://imgur.com/RpCZWH1.png

**Comment by safwanyp** [comment]
**Please make sure your issue follows the posting structure.** 

Seems like you are using the **[Get Team Membership](https://appwrite.io/docs/client/teams?sdk=web-default#teamsGetMembership)** endpoint in the Teams API. This endpoint does not accept any queries. If you want to fetch a team based on a query, use the **[List Team Memberships](https://appwrite.io/docs/client/teams?sdk=web-default#teamsListMemberships)** instead.
