### ISSUE TITLE
🐛 Bug Report: Unable to rearrange the order of relationship documents

### ISSUE THREAD

**Issue by vlohar08** [appwrite/appwrite#5954]
### 👟 Reproduction steps

1. Create two database collections with any attributes or names.
2. Add a relationship with the second collection inside the first collection.
3. Try to add 4-5 new documents in the second collections
4. Now, rearrange the documents and pass them to the database via web SDK.

```
Example:
{
   name: "Vishal",
   links: [ //Relationship with links collection
     {
        name: "Link1",
        href: "Link",
     },
     {
        name: "Link2",
        href: "Link",
     },
     {
        name: "Link3",
        href: "Link",
     }
   ]
}

//Now pass the new order of links using the update document function
{
   name: "Vishal",
   links: [ //Relationship with links collection
     {
        name: "Link2",
        href: "Link",
     },
     {
        name: "Link3",
        href: "Link",
     },
     {
        name: "Link1",
        href: "Link",
     }
   ]
}
```

### 👍 Expected behavior

The order of relationship document items should change if a new document array is passed with updated order.

### 👎 Actual Behavior

The order of relationship documents is left unchanged when passed a new document array with updated order.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Localhost
Next.js
Appwrite 1.3.8 self hosted on Digital Ocean

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
While testing this, I also experienced some weird behavior. Even when creating the documents on my two-way one-to-many relationship, the resulting array did not have the same order as what I passed in. For me, the 1st document ended up being the last in the array.

**Comment by vlohar08** [comment]
Okay, @joeyouss Thank you!
When the new version will be released?

**Comment by joeyouss** [comment]
@vlohar08  Soon :)

**Comment by vlohar08** [comment]
@joeyouss  Hi, I upgraded to the Appwrite 1.4.0 version today. The fix is unavailable in the latest version of Appwrite. I am still facing the same update problem where the order of documents is not updated by Appwrite 1.4.0
