### ISSUE TITLE
🐛 Bug Report: GraphQL switch dont turn on in cloud version Appwrite

### ISSUE THREAD

**Issue by Leonich77** [appwrite/appwrite#5957]
### 👟 Reproduction steps

When I try to connect my cloud server project via graphql I get CORS error... Going into the settings of my Appwrite cloud project, I see that under Services toggle for GraphQL is off and grayed out. I get an error message when I try to turn it on: Invalid service: Value must be one of (account, avatars, databases, locale, health, storage, teams, users, functions). But the switch remains on. After I exit the settings and come back, the switch is off again.

### 👍 Expected behavior

The Appwrite server that I have installed locally in a docker container has no such problems: he's got it all turned on at once and I'm just plugging into it. In this case with the cloud, I expected the same behavior.

### 👎 Actual Behavior

I actually googled this topic until 2-3 months ago.... found nothing.... I hoped that soon the developers would notice it themselves but.... I hope it's not a bug but just something I don't understand, please explain)
![qlturnonerror](https://github.com/appwrite/appwrite/assets/32384695/0dc13785-79b6-4e81-a61e-3186537bf65e)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I use the Brave browser to access the cloud server console. My client is a React app, SDK, line from package.json: { "appwrite": "^11.0.0.0", the code used in my client is taken from here : https://appwrite.io/docs/graphql#sdk-usage

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi
Cloud is on 1.1.2 and GraphQL was added in later versions https://github.com/appwrite/appwrite/releases/tag/1.2.0

**Comment by Leonich77** [comment]
So at the moment Appwrite's cloud platform doesn't allow to work through qraphql? Am I hearing you right? And if so, are there plans to support it?

**Comment by joeyouss** [comment]
Yes, as soon as Cloud gets updated to newer versions, it will have the support! It is available in newer versions it is just that cloud is on previous version of Appwrite

**Comment by joeyouss** [comment]
Hi @Leonich77 , shall I close this if there is nothing else you want to discuss?

**Comment by Leonich77** [comment]
Hi! Yes, of course!
