### ISSUE TITLE
🚀 Feature: Bulk actions

### ISSUE THREAD

**Issue by dokgu** [appwrite/appwrite#5958]
### 🔖 Feature description

When displaying the list of collections, documents, users, etc. (tabular form) there should be a way to perform bulk actions by selecting multiple rows and then performing that action.

### 🎤 Pitch

Right now when I want to delete a bunch of documents inside a collection, I have to open each document and then delete them one by one. Having the ability to select multiple documents when on the tabular form and then deleting the ones I selected would be a better experience.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
> Hi, please see this: #4823 and #3051
> 
> would it be possible to close this issue and instead leave comments here for collaborative feedback ?

Hi @dokgu following up on this. Let me know if we can go ahead and close it :)

**Comment by dokgu** [comment]
> > Hi, please see this: #4823 and #3051
> 
> > 
> 
> > would it be possible to close this issue and instead leave comments here for collaborative feedback ?
> 
> 
> 
> Hi @dokgu following up on this. Let me know if we can go ahead and close it :)

Ah yes sorry I forgot to respond - really busy at work atm. Feel free to close in favor of the existing issue.

**Comment by joeyouss** [comment]
Thank you!
