### ISSUE TITLE
Why did Appwrite create its own docker images for InfluxDB, Telegraf and ClamAV?

### ISSUE THREAD

**Issue by philipehusani** [appwrite/appwrite#5962]
### Discussed in https://github.com/appwrite/appwrite/discussions/5944

<div type='discussions-op-text'>

<sup>Originally posted by **philipehusani** August  5, 2023</sup>
Why did Appwrite create its own docker images for InfluxDB, Telegraf and ClamAV?

Can I use a custom InfuxDB container with the official docker image? Or does it have to be the image in the Appwrite Docker repo?</div>

**Comment by joeyouss** [comment]
Hi @philipehusani , we should close this issue from here and rather keep the discussion on GH discussions for a centralized communication point : )
