### ISSUE TITLE
🐛 Bug Report: Overflow issue in appwrite console

### ISSUE THREAD

**Issue by Srinivasan-Akash** [appwrite/appwrite#5976]
### 👟 Reproduction steps

Create a database, collection and document while filling the input you could observe it
![bug (1)](https://github.com/appwrite/appwrite/assets/108281031/819b52e8-8ae1-470f-84e7-3f16cb845987)

### 👍 Expected behavior

![firefox_R7ZaANlwW9](https://github.com/appwrite/appwrite/assets/108281031/0168b31a-fcb9-4cff-875f-4f48e146cf09)

### 👎 Actual Behavior

![bug (1)](https://github.com/appwrite/appwrite/assets/108281031/3f004d8e-f7aa-4b23-9993-4d6c6f704dba)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by asenseofpradhyu** [comment]
I would like to work on this issue. Please assign me

**Comment by stnguyen90** [comment]
@Srinivasan-Akash, thanks for raising this! 🙏 what's the size of the string attribute?

**Comment by joeyouss** [comment]
Hi @Srinivasan-Akash ,  we checked this and it is fixed for newer versions. Once Cloud is updated to latest version, you will see the changes!

**Comment by Srinivasan-Akash** [comment]
Your welcome 😇
