### ISSUE TITLE
🐛 Bug Report: Error notification appears under modal

### ISSUE THREAD

**Issue by Srinivasan-Akash** [appwrite/appwrite#5977]
### 👟 Reproduction steps

While creating an attribute any error messages are displayed with less z-index
![image](https://github.com/appwrite/appwrite/assets/108281031/eff97e2f-af19-4f18-a55e-4f86cc6e81bc)

### 👍 Expected behavior

the error messages should have more z-index

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/108281031/eff97e2f-af19-4f18-a55e-4f86cc6e81bc)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by asenseofpradhyu** [comment]
I would like to work on this. Please /assign me

**Comment by stnguyen90** [comment]
Thanks for raising this issue! 🙏 this looks similar to https://github.com/appwrite/appwrite/issues/5098 🧐

Let me dig into this a bit

**Comment by stnguyen90** [comment]
We changed the error a bit for modals. It should show in the modal as of 1.3:

![image](https://github.com/appwrite/appwrite/assets/1477010/1af3efbf-b4f8-4a7e-ae41-f8cf2c855dda)

If you see this anywhere after 1.3, please create a new issue! 🙏🏼
