### ISSUE TITLE
🐛 Bug Report: API key name is passing as null while creating API key for server.

### ISSUE THREAD

**Issue by Akshay-Rana-Gujjar** [appwrite/appwrite#5978]
### 👟 Reproduction steps

- Create new project
- Click on API key button in Integrate With Your Server section
- Enter API key name
- Click in next button

### 👍 Expected behavior

Go to next page after entering API details.

### 👎 Actual Behavior

Not taking api key name and showing error 'Invalid name: Value must be a valid string and at least 1 chars and no longer than 128 chars' on clicking next button.

<img width="1624" alt="Screenshot 2023-08-12 at 5 38 16 PM" src="https://github.com/appwrite/appwrite/assets/24373771/0e8a4f1b-2831-4dba-a936-fc98ddece6ed">
<img width="1116" alt="Screenshot 2023-08-12 at 5 39 16 PM" src="https://github.com/appwrite/appwrite/assets/24373771/0be9145e-e03e-4abe-906a-7adf9de70608">

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite version: 1.3.8
Docker version: 23.0.5, build bc4487a
macOS: 13.4

Self-hosted Installation using Docker command

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for creating this issue! 🙏 this sounds like https://github.com/appwrite/appwrite/issues/4847 which will be resolved in 1.4.0. As such, I'm going to close this issue. Feel free to comment in the previous issue if the problem still persists in 1.4
