### ISSUE TITLE
🐛 Bug Report: [Console] Wrong message displayed on account verify / unverify

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#5981]
### 👟 Reproduction steps

See video for info.

https://github.com/appwrite/appwrite/assets/20625965/51ad3e14-a7e0-401d-b87b-47c2a9613ef2

### 👍 Expected behavior

Show correct message.

### 👎 Actual Behavior

If the account is verified, the message displays `Unverified` and vice-versa.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Env: `Localhost`.
Appwrite: `1.3.8`.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Akshay-Rana-Gujjar** [comment]
I tried this issue on appwrite's latest code and I confirm that this issue is fixed there as I am not able to replicate this issue. Appwrite 1.4.x will have this fix.



https://github.com/appwrite/appwrite/assets/24373771/f058efc2-657e-4dbb-84e9-0d528ac576ce

**Comment by stnguyen90** [comment]
PR: https://github.com/appwrite/console/pull/429
