### ISSUE TITLE
🐛 Bug Report: [Console] `Create New Database` grid item doesn't work.

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#5992]
### 👟 Reproduction steps

When using the `grid view` in `Databases` section, the last grid item is for creating a new database.
On licking the card or on the `+` icon, nothing happens. Clicking on `Create Database` button on top works.

See video for reference:

https://github.com/appwrite/appwrite/assets/20625965/5aa1ceae-b124-48e6-b5d0-dade22e5c186

### 👍 Expected behavior

The alert dialog to create a new database is shown.

### 👎 Actual Behavior

The alert dialog to create a new database is not shown.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Localhost.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by safwanyp** [comment]
Just tested in a dev environment of console, and it seems like it isn't fixed. Can I be assigned this issue?

**Comment by stnguyen90** [comment]
@ItzNotABug, thanks for raising this issue! 🙏🏼 

@safwanyp, I've assigned the issue to you. Thanks for your support! 🙏🏼

**Comment by abnegate** [comment]
Closing as resolved in 1.4.3
