### ISSUE TITLE
🚀 Feature: Add hover effect on icons

### ISSUE THREAD

**Issue by anubhav1206** [appwrite/appwrite#5997]
### 🔖 Feature description

The icons in the flexibility section could grow in size upon hover.

### 🎤 Pitch

![image](https://github.com/appwrite/appwrite/assets/53504460/3ecf4c5e-9d42-431e-9d77-5138821be85e)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by PrerakMathur20** [comment]
Hey, I would like to work on this. Kindly assign this to me.

**Comment by eldadfux** [comment]
Hey, thank you for the suggestion, but the website source code is not publicly open and contributions are not possible at the moment.
