### ISSUE TITLE
🐛 Bug Report: Cannot update hostname of Flutter Web App

### ISSUE THREAD

**Issue by safwanyp** [appwrite/appwrite#6003]
### 👟 Reproduction steps

1. Log in to your Appwrite Console
2. Create a Project called `test-project`
3. Add a **Platform**: Flutter App → Web
4. Input any **Name**
5. Input a hostname: `example.com`
6. Save changes and try to edit the platform details

### 👍 Expected behavior

Should be able to update the hostname

### 👎 Actual Behavior

Cannot update the hostname of Flutter Web platform as there is no input field for it.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

- Appwrite 1.3.x
- Hosted on a Red Hat VM with an nginx reverse proxy

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by safwanyp** [comment]
This issue seems like a frontend issue (haven't looked at the code yet), but I think #6004 should be looked at as well for this.

**Comment by stnguyen90** [comment]
@safwanyp, thanks for creating this issue! 🙏🏼 We should be using the same components/elements as the web platform for this...

**Comment by Suven-p** [comment]
@stnguyen90 Could you assign this to me?

**Comment by stnguyen90** [comment]
@Suven-p, assigned! Thanks for your interest! 🙏🏼

**Comment by Darshan018** [comment]
Hey @Suven-p, Are you still working on this issue?

**Comment by FreSauce** [comment]
@stnguyen90 Hey, I would like to work on this issue. Can you assign it to me?

**Comment by Suven-p** [comment]
@Darshan018 No. Feel free to take this up if you'd like.

**Comment by Haimantika** [comment]
@Darshan018 do you still want to work on this?

**Comment by stnguyen90** [comment]
@FreSauce, would you like to work on this issue?

**Comment by FreSauce** [comment]
@stnguyen90 yea, I would like to work on it
