### ISSUE TITLE
🐛 Bug Report: Query.between isn't parsed in the right format

### ISSUE THREAD

**Issue by gepd** [appwrite/appwrite#6006]
### 👟 Reproduction steps

1. create a query using between for example 

```js
const query = [Query.between("date", "2023-08-15T04:00:13.989Z", "2023-08-16T04:00:13.989Z")];
```

2. You'll see the output: `[between("date", ["2023-08-15T04:00:13.989Z","2023-08-15T07:00:21.100Z"])]`

Looking the SDK generator repo, it looks like it's the same for all SDK's https://github.com/appwrite/sdk-generator/blob/master/templates/node/lib/query.js.twig#L27

### 👍 Expected behavior

It should be: `[between("date", "2023-08-15T04:00:13.989Z","2023-08-15T07:00:21.100Z")]`

As workaround it's possible to manually write the query and you can work with it

### 👎 Actual Behavior

The output is: `[between("date", ["2023-08-15T04:00:13.989Z","2023-08-15T07:00:21.100Z"])]`

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gepd** [comment]
My first though was to change the `addQuery` method in the SDK generator

https://github.com/appwrite/sdk-generator/blob/master/templates/node/lib/query.js.twig#L59-L64

but seems like the solution isn't here as that query is valid for other cases when you send an array as value

**Comment by gepd** [comment]
I don't know if a change like this would be the best solution:

```js
static addQuery = (attribute: string, method: string, ...values: any[]) => {
    if (method === "between") {
        return `${method}("${attribute}", ${values.map((v) => Query.parseValues(v)).join(",")})`;
    }
    
    return value instanceof Array
        ? `${method}("${attribute}", [${value
          .map((v) => Query.parseValues(v))
            .join(",")}])`
        : `${method}("${attribute}", [${Query.parseValues(value)}])`;
  };
```

**Comment by stnguyen90** [comment]
@gepd, thanks for creating this issue! 🙏🏼 Is this the same as https://github.com/appwrite/appwrite/issues/5650? If so, maybe you can 👍🏼 that issue and close this one as a duplicate?
