### ISSUE TITLE
🐛 Bug Report: .NET 6.0 Function stuck on building

### ISSUE THREAD

**Issue by roxxel** [appwrite/appwrite#6007]
### 👟 Reproduction steps

Nothing super specific, clean function created by appwrite-cli

### 👍 Expected behavior

Well, it should build

### 👎 Actual Behavior

...but, it doesn't 

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.3.7 installed with Docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by roxxel** [comment]
![image](https://github.com/appwrite/appwrite/assets/64275777/bcca0f85-fcbb-43b0-a0f1-65595c97c687)
It shouldn't take that long. I checked docker logs for builder container, found nothing

**Comment by roxxel** [comment]
After further research I noticed that build at least fails without any PackageReference directives present in .csproj files.
I'd assume that the issue is related to Nuget

**Comment by roxxel** [comment]
```
appwrite-executor  | 
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 353
appwrite-executor  | Building container : 64910c95a97ca9b9dfff-64de8e17702d1c3b8db6
appwrite-executor  | Build failed: Docker Error: MSBuild version 17.3.2+561848881 for .NET
appwrite-executor  |   Determining projects to restore...
appwrite-executor  | 
appwrite-executor  | [Error] Type: Exception
appwrite-executor  | [Error] Message: Docker Error: MSBuild version 17.3.2+561848881 for .NET
appwrite-executor  |   Determining projects to restore...
appwrite-executor  | 
appwrite-executor  | [Error] File: /usr/src/code/app/executor.php
appwrite-executor  | [Error] Line: 353
```

**Comment by stnguyen90** [comment]
@roxxel, thanks for raising this issue! 🙏🏼 What commands did you run exactly using the Appwrite CLI? Also what version of the Appwrite CLI do you have (you can check by running `appwrite -v`)?

**Comment by roxxel** [comment]
Latest version installed from NPM
commands I ran:
appwrite init project
appwrite init function 
appwrite deploy function

**Comment by stnguyen90** [comment]
@roxxel, I just did the same thing and it built fine for me 🧐 I'm on 1.3.8, but that shouldn't make a difference.

Could you try increasing the memory env vars in your .env file?:

```
_APP_FUNCTIONS_MEMORY=2506
_APP_FUNCTIONS_MEMORY_SWAP=2506
```

**Comment by roxxel** [comment]
Memory limit is set to 4 gigabytes

**Comment by roxxel** [comment]
Also, existing deployments can't be ran. They're also stuck on processing

**Comment by stnguyen90** [comment]
@roxxel, what's the output of `docker ps -a`?

**Comment by roxxel** [comment]
@stnguyen90 Can't paste output here, every appwrite container is up and has port assigned to it. So containers are healthy

**Comment by stnguyen90** [comment]
@roxxel, 

1. Would you please share the output of the docker logs for the `appwrite-worker-builds` container
2. How did you install Appwrite?
3. What is the name of the folder the appwrite docker-compose.yml is in?
4. Does any other runtime work?

**Comment by roxxel** [comment]
1)
```
appwrite-worker-builds  | Creating build for deployment: 64de915e10a180ecb266
appwrite-worker-builds  | Docker Error: Microsoft (R) Build Engine version 16.7.3+2f374e28e for .NET
appwrite-worker-builds  | Copyright (C) Microsoft Corporation. All rights reserved.
appwrite-worker-builds  | 
appwrite-worker-builds  |   Determining projects to restore...
appwrite-worker-builds  | 
appwrite-worker-builds  | 
appwrite-worker-builds  | Warning: Undefined array key "projectInternalId" in /usr/src/code/src/Appwrite/Usage/Stats.php on line 85
appwrite-worker-builds  | [notice] (Job{v1-builds} | ID: b3bc0dbcae9e2f8ab444c92e1d818537 | BuildsV1 | <long_json_string> has finished
```
2) Docker
3) /home/ubuntu/appwrite
4) None of the runtimes work

**Comment by roxxel** [comment]
@stnguyen90

**Comment by stnguyen90** [comment]
@roxxel, 

If none of the runtimes work, something may be wrong with your instance/installation rather than dotnet. What happens with the starter node function? 

I believe you said you installed Appwrite via Docker. How exactly?

**Comment by roxxel** [comment]
I managed to fix this issue, Nuget couldn't connect to server because of DNS, changing docker's DNS settings helped. You may close this issue.
_And please move to something other than open-runtimes (it's awful) 😔_
