### ISSUE TITLE
🚀 Feature: want to Add Search Feature for Contributor

### ISSUE THREAD

**Issue by biplavmz** [appwrite/appwrite#6013]
### 🔖 Feature description

<img width="377" alt="image" src="https://github.com/appwrite/appwrite/assets/68702055/a6360a16-9745-435a-be04-f073d6bbc929">

I would like to add search feature for contributor page. with the help of this contributor can easily search there user profile 

### 🎤 Pitch

I would like to add search feature for contributor page. with the help of this contributor can easily search there user profile 

there are more than 700 contributors so it will help them to get there profile easily

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Thanks for the request @biplavmz. We will very soon work on updating this page, adding search is not planned for now. Will chat with the team to see if this is something that we plan to have in the future :)

**Comment by eldadfux** [comment]
Hey @biplavmz , unfortunately, due to work already being done on this page, this will not be needed. 

If you’d still like to contribute please search for one of our ‘good-first-issues’

**Comment by biplavmz** [comment]
ok @eldadfux @Haimantika
