### ISSUE TITLE
🐛 Bug Report: Unable to run Functions on Cloud

### ISSUE THREAD

**Issue by MohamedKamran** [appwrite/appwrite#6018]
### 👟 Reproduction steps

I just made a function Python 3.9 pretty simple one
`print("Hello Appwrite")`
and just executed

### 👍 Expected behavior

Give in The logs as
**Hello Appwrite**

### 👎 Actual Behavior

Execution > Failed >

No Response Recorded

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite Cloud

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Rithwik0480** [comment]
Could you please walk me through the steps followed by you for setting up the Appwrite cloud?

**Comment by MohamedKamran** [comment]
Yes,sure @Rithwik0480 

Appwrite>Project>Function>>>
Set Name, and Runtime as Python 3.9
Execute Access as All,No Events,No Schedule,No Variables
and hence Function created

Went to Function > Create Deployment
Now back to Python I just compressed to GZip File using `tar -czf folder_name.tar.gz folder_name/`
Uploaded GZip FIle and then builded it.

When Pressing `Execute Now` there is an item added on `Excecutions` as a Failed Log
![Error Screen](https://github.com/appwrite/appwrite/assets/96822969/2e15c161-716b-4ee9-b361-7b9668ca4f0f)

when i look into its Logs there are no Responses, Logs or even Errors.

**Comment by MohamedKamran** [comment]
@Rithwik0480 does this depend on version since it was just a `print` statememt

**Comment by stnguyen90** [comment]
> I just made a function Python 3.9 pretty simple one `print("Hello Appwrite")` and just executed

If that is your full function code, it won't run successfully. Please follow the [docs](https://appwrite.io/docs/functions) for functions for how your function should be written. Also, I highly recommend using the CLI (as mentioned in the docs) to initialize and deploy you function.

**Comment by ph1oneX** [comment]
Can u just share me a gzip template itll be a bit convinient

**Comment by tripolskypetr** [comment]
I think this is related to [this issue](https://github.com/appwrite/appwrite/issues/6051)

**Comment by stnguyen90** [comment]
@MohamedKamran, is your problem resolved yet? FYI, I'll need to close this due to inactivity soon.

**Comment by MohamedKamran** [comment]
Look, its not solved its better u provide me with a template btw i just figured alternative so its not actually solved but Yh we are good with closing this issue.

Just provide me a template
