### ISSUE TITLE
🐛 Bug Report: Functions Limited to Entrypoint Leading to Build Failures

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6035]
### 👟 Reproduction steps

I've observed that the scope of functions seems restricted to the `entrypoint` file. When attempting to upload that reference additional files, the build process fails.
This occurs regardless of whether the upload is done through the console or appwrite-cli.

The build process terminates with an error pointing to import statements and the subsequent usage of the referenced component. Here's an example:
```
Docker Error: Info: Compiling with sound null safety
user_code/lib/main.dart:3:8: Error: Error when reading 'user_code/lib/logger.dart': No such file or directory
import 'logger.dart';
       ^
user_code/lib/main.dart:21:3: Error: Undefined name 'Logger'.
  Logger.logd(dataContent);
  ^^^^^^
Error: AOT compilation failed
Generating AOT kernel dill failed!
Resolving dependencies...
    found user package import_issues
    added user package as dependency to server.
    Updated server import of user code
Resolving dependencies...
    + import_issues 0.0.4 from path user_code
Changed 13 dependencies!
Resolving dependencies...
Got dependencies!
```

Deployments via:
1. `tar -czf code.tar.gz --exclude code.tar.gz . `
2. `appwrite functions createDeployment --functionId=import_issues --entrypoint='working.dart' --code="." --activate=true`

---

To help reproduce this,
I've attached a sample project containing relevant files: [import_issues.zip](https://github.com/appwrite/appwrite/files/12439124/import_issues.zip)

I created 2 implementations to test this behaviour:
1. `working.dart`: This standalone file will successfully pass the build phase.
2. `problematic.dart`: This file imports `logger.dart`, and setting it as the entrypoint results in a build failure.

**Note: I tested using `Dart 2.17` runtime so I am not sure if other runtimes are also affected.**

### 👍 Expected behavior

Allow using files, classes outside the `entrypoint`.

### 👎 Actual Behavior

Function building fails.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I tested this on 3 different environments & the results were same:
1. Appwrite Cloud (version `1.1.2`)
2. Local machine (Mac) with Appwrite version `1.3.8`
3. Self-hosted setup on Ubuntu with Appwrite version `1.3.8`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
A suggestion by @stnguyen90  on Discord helped resolve this issue. I moved the `logger.dart` file into the `lib` folder and then used this import statement: `import 'package:import_issues/logger.dart';` and it worked perfectly.

I believe this might be beneficial to include in the documentation. I'll leave this issue open so the maintainers can review and decide.

**Comment by stnguyen90** [comment]
Docs: https://appwrite.io/docs/functions-develop#code-splitting
