### ISSUE TITLE
🚀 Feature: Better previews for video files

### ISSUE THREAD

**Issue by dokgu** [appwrite/appwrite#6040]
### 🔖 Feature description

Show an actual frame from the video when calling `getFilePreview()`. Perhaps add a movie icon to indicate that it is a video file.

### 🎤 Pitch

When uploading multiple files (images and videos) and then calling `getFilePreview()` for each file, the images show an actual image, but for video files, the preview image is a simple icon - it would be better if the previews for videos are actual frames from the file themselves with an icon to clearly indicate that the file is playable (or perhaps the icons can be left to the developers to be consistent with their design).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @dokgu , passed this to the team, will let you know any feedback we have soon.

**Comment by eldadfux** [comment]
As of now, the file preview endpoint is optimized for image transformation. If something this should support a video thumbnail and not a video player as the expected output of this endpoint is an image mime type. That said, this will require a much bigger solution for handling video transcoding. 

We could consider it in the future as part of a bigger effort to add wider video handling support in Appwrite Storage. Closing for now, but we will be referencing this again when doing more work around video support.
