### ISSUE TITLE
🐛 Bug Report: Unique phone number error returns "email already exits" error.

### ISSUE THREAD

**Issue by divanov11** [appwrite/appwrite#6041]
### 👟 Reproduction steps

When creating a new user (from a python backend) I kept running into the following error even though I new for a fact that the emails I was using to test were unique:

`Error: A user with the same email already exists in your project.`

I realized this was not due to a duplicate email, but a duplicate phone number since I accidentally hard coded the value when testing.

```python
users.create(
    appwrite_user_id,
    self.email,
    '+5552782908',
    self.password, 
    self.name,
)
```

The error can be duplicated by calling the function above more than once.

### 👍 Expected behavior

Error should return the following:

`Error: A user with the same phone number already exists in your project.`

### 👎 Actual Behavior

`Error: A user with the same email already exists in your project.`

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @divanov11 , I tried it on Cloud - yes, you're right 
But, on latest version this does not happen. This means it is fixed for newer versions and once Cloud is updated, it will reflect those changes.

**Comment by divanov11** [comment]
Ok great! 😄
