### ISSUE TITLE
🐛 Bug Report: Error deleting a file after adding delete permissions

### ISSUE THREAD

**Issue by dokgu** [appwrite/appwrite#6042]
### 👟 Reproduction steps

1. Create a team and give it `create`,  `read`, and `update` permissions to a bucket
2. Upload multiple files by using `storage.createFile()`
3. Delete one of those files by using `storage.deleteFile()` - you should get an error here about not having the permission to delete the file
4. Add the `delete` permission to the team you created on step 1
5. Try deleting the file again and you'll still get an error

### 👍 Expected behavior

After getting the permission to delete a file, I should be able to delete the file from the bucket.

### 👎 Actual Behavior

I keep getting an error when I attempt to delete a file after giving the team I belong to `delete` permissions.

If I delete the file from the console this is what I get:

```json
{
    "message": "Server Error",
    "code": 500,
    "type": "general_server_error",
    "version": "1.3.8"
}
```

If I attempt to open the file, this is what I get:

```json
{
    "message": "File not found in \/storage\/uploads\/app-<ID>\/<ID>\/<ID>.jpg",
    "code": 404,
    "type": "storage_file_not_found",
    "version":"1.3.8"
}
```

**NOTE:** This only happens to the file I had the error on when I didn't have the delete permission. I was able to successfully delete the other files that I didn't try to delete before adding the `delete` permission.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @dokgu , it seems the file got deleted and after you're trying to access it, it is no longer available. Are you able to see the file in your console?

**Comment by dokgu** [comment]
> Hi @dokgu , it seems the file got deleted and after you're trying to access it, it is no longer available. Are you able to see the file in your console?

Well it shouldn't have been deleted because I didn't have the permission to do so. The file shows up in the list of files when I open the bucket page but when I open the file itself, it says file not found.

**Comment by joeyouss** [comment]
I will try to reproduce this and get back to you @dokgu

**Comment by dokgu** [comment]
If it helps these are the logs:

```
[Error] Timestamp: 2023-08-27T01:25:41+00:00
[Error] Method: DELETE
[Error] URL: /v1/storage/buckets/:bucketId/files/:fileId
[Error] Type: Appwrite\Extend\Exception
[Error] Message: The current user is not authorized to perform the requested action.
[Error] File: /usr/src/code/app/controllers/api/storage.php
[Error] Line: 1426
[Error] Timestamp: 2023-08-27T01:26:40+00:00
[Error] Method: DELETE
[Error] URL: /v1/storage/buckets/:bucketId/files/:fileId
[Error] Type: Appwrite\Extend\Exception
[Error] Message: Failed to delete file from device
[Error] File: /usr/src/code/app/controllers/api/storage.php
[Error] Line: 1436
```

The first `DELETE` was when I attempted to delete the file using the client SDK (web) - this was back when I didn't have the `delete` permission granted to the team I belong to.

The second `DELETE` was after I added the permission to the team I belong to - but I only tried to delete the file from the console at this point.

**Comment by stnguyen90** [comment]
@dokgu is file security enabled on the bucket?

**Comment by dokgu** [comment]
> @dokgu is file security enabled on the bucket?

No, access is granted on the bucket level not the file level.
