### ISSUE TITLE
🐛 Bug Report: Signing key cannot be empty when creating an execution

### ISSUE THREAD

**Issue by SuperLanceur** [appwrite/appwrite#6043]
### 👟 Reproduction steps

I'm using a self-hosted docker instance of Appwrite, with the provided compose file. After deploying a function using the CLI (because the zip upload on the web interface does not work) and executing it, I receive a "Server Error".

### 👍 Expected behavior

It should execute the function without issue

### 👎 Actual Behavior

It throws an error, and the container has the following logs

```
[Error] Timestamp: 2023-08-27T05:02:39+00:00
[Error] Method: POST
[Error] URL: /v1/functions/:functionId/executions
[Error] Type: Ahc\Jwt\JWTException
[Error] Message: Signing key cannot be empty
[Error] File: /usr/src/code/vendor/adhocore/jwt/src/ValidatesJWT.php
[Error] Line: 34
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Something else

### 🧱 Your Environment

I'm running Appwrite 1.3.8 on Docker, and the function used Node 16.0 as the runtime. No client/server SDK is used, I create executions using the web interface/the CLI

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @SuperLanceur have you set your JWT secret / key when encoding your JWT token?

**Comment by SuperLanceur** [comment]
Hello @joeyouss ! I'm not sure, where am I supposed to set a JWT secret?

**Comment by joeyouss** [comment]
So, if you see, this line is throwing errors for you: https://github.com/adhocore/php-jwt/blob/main/src/ValidatesJWT.php#L31

Can I see your code by any chance that is causing this?

**Comment by SuperLanceur** [comment]
Thanks, that solved the issue! The wording at https://appwrite.io/docs/environment-variables did not make it seem that it was mandatory, but looks like it is.

**Comment by joeyouss** [comment]
@SuperLanceur glad it worked. Also, thanks for the feedback, will pass it to my team : ) Closing this issue!
