### ISSUE TITLE
🐛 Bug Report: Python 3.9 function res.json() empty dict serialized as an array

### ISSUE THREAD

**Issue by tripolskypetr** [appwrite/appwrite#6056]
### 👟 Reproduction steps

The following python code

```python
def main(req, res):
  return res.json({
    "rows": [],
    "total": 0,
    "filterData": {},
    "pagination": {
      "limit": 10,
      "offset": 0,
    },
    "sortModel": [],
    "chips": {},
    "search": "",
    "payload": {},
  })

```

should return these JSON structure

```json
{
  "rows": [],
  "total": 0,
  "filterData": {},
  "pagination": {
    "limit": 10,
    "offset": 0
  },
  "sortModel": [],
  "chips": {},
  "search": "",
  "payload": {}
}
```

### 👍 Expected behavior

It returns

```json
{
  "rows": [],
  "total": 0,
  "filterData": {},
  "pagination": {
    "limit": 10,
    "offset": 0
  },
  "sortModel": [],
  "chips": {},
  "search": "",
  "payload": {}
}
```

### 👎 Actual Behavior

But every `dict` without any properties was serialized as a `list`

```json
{
  "chips": [],
  "filterData": [],
  "pagination": { "limit": 10, "offset": 0 },
  "payload": [],
  "rows": [],
  "search": "",
  "sortModel": [],
  "total": 0
}
```

Proof

![image](https://github.com/appwrite/appwrite/assets/19227776/833d9eca-e881-4d87-87b1-c5542a8633dc)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite Cloud 1.1.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @tripolskypetr This is fixed in 1.4. Cloud is on 1.1.2 so it will be reflected when Cloud gets updated.
