### ISSUE TITLE
🐛 Bug Report: "Quick Start" Infinite loadings when creating a function

### ISSUE THREAD

**Issue by istornz** [appwrite/appwrite#6090]
### 👟 Reproduction steps

In the web dashboard go to:
- "Functions"
- "Create function"

### 👍 Expected behavior

Quick start loadings are not infinite & content should be showed

### 👎 Actual Behavior

All loadings are infinites & content not showing

Here is a [preview](https://i.ibb.co/MsvQGP3/Capture-d-cran-2023-08-31-14-12-18.png)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Hetzner to host Appwrite

- I migrated first to 1.4.0, then migrate.
- I migrate secondly to 1.4.1, then migrate (see a lot of warnings in the migration process, don't know if it's ok or not...).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @istornz , this will be fixed in next few hours.

CC @gewenyu99

**Comment by stnguyen90** [comment]
Found the problem! It looks like this happens when Appwrite doesn't have quickstart runtime enabled.
