### ISSUE TITLE
Feature: Support both uppercase Y and lowercase y in installation

### ISSUE THREAD

**Issue by byawitz** [appwrite/appwrite#6094]
### 👟 Reproduction steps

When upgrading to version `1.4.1` you are present with this question
```shell
Previous installation found, do you want to overwrite it (a backup will be created before overwriting)? (Y/n)
```
And you **must** insert uppercase [Y](https://github.com/appwrite/appwrite/blob/master/src/Appwrite/Platform/Tasks/Install.php#L73) to be considered as yes.

### 👍 Expected behavior

Lowercase should do

### 👎 Actual Behavior

Only uppercase

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hey @byawitz , changed the title because it was not a bug but intended. Having an enhancement to add support for both lowercase and uppercase makes more sense. I have passed this to my team and will keep you posted if we move forward to implementation.

**Comment by byawitz** [comment]
Makes sense
