### ISSUE TITLE
🐛 Bug Report: Error 500 on self hosted docker installation when pressing on "Functions" or "Settings" left menu

### ISSUE THREAD

**Issue by 032008** [appwrite/appwrite#6103]
### 👟 Reproduction steps

Steps to reproduce:
1. Install fresh instance - `docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.4.0`
2. add _APP_CONNECTIONS_MAX=512 to avoid another bug with "too many connections" to .env
3. verify _APP_DOMAIN is set to proper ip address
4. sign up and once logged in, attempt to press the "Functions" left menu option.

### 👍 Expected behavior

Display the Functions screen

### 👎 Actual Behavior

Displays error 500.

One of the network calls returns the following:
{
    "message": "ex@ex.com (role: users) missing scope (none)",
    "code": 401,
    "type": "general_unauthorized_scope",
    "version": "1.4.0",
    "file": "/usr/src/code/app/controllers/general.php",
    "line": 475
}

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Self hosting with docker on ubuntu server

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @032008 , is this error also occurring for 1.4.1 for you?

**Comment by 032008** [comment]
Hello @joeyouss,

You are indeed correct, v 1.4.1 works better.
I followed the following article, which suggested 1.4.0: https://appwrite.io/docs/self-hosting
It looks like the team is already aware of the _APP_CONNECTIONS_MAX issue:  #6075 

Thank you very much for your support!
