### ISSUE TITLE
🐛 Bug Report: Cloud Functions: cannot use import statement outside a module

### ISSUE THREAD

**Issue by JorensM** [appwrite/appwrite#6104]
### 👟 Reproduction steps

1. Create and deploy a basic Function with the Appwrite CLI
2. Execute the function from the console
3. See error in logs

### 👍 Expected behavior

It should execute the function without errors

### 👎 Actual Behavior

The logs of the function execution in the console show this:

```
/usr/code-start/stripePaymentIntent.js:1
import { Client } from 'node-appwrite';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at require (node:internal/modules/cjs/helpers:93:18)
    at /usr/local/src/server.js:55:28
```

Also if I remove the import statement, it gives me "unexpected token 'export' "

This is the code of my function:
```
import { Client } from 'node-appwrite';

// This is your Appwrite function
// It's executed each time we get a request
export default async ({ req, res, log, error }) => {
    
    log('test')

    return res.json('Success')


};
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I'm using Appwrite Cloud.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Does it work if you use below format?
```js
const {Client} = require('node-appwrite');
```

**Comment by JorensM** [comment]
@ItzNotABug Thanks, this solves the error. I'm guessing though that it should work with ESM syntax as well, because [the docs](https://appwrite.io/docs/functions-develop) use ESM syntax.

But now I have another error: `log is not a function` I tried investigating and found that what gets passed to the cloud function is the following:

```
{
   "variables":{
      "publishable_key_test":"..", //My own env var
      "APPWRITE_FUNCTION_ID":"stripe-payment-intent",
      "APPWRITE_FUNCTION_NAME":"Stripe payment intent",
      "APPWRITE_FUNCTION_DEPLOYMENT":"...",
      "APPWRITE_FUNCTION_TRIGGER":"http",
      "APPWRITE_FUNCTION_PROJECT_ID":"...",
      "APPWRITE_FUNCTION_RUNTIME_NAME":"Node.js",
      "APPWRITE_FUNCTION_RUNTIME_VERSION":"16.0",
      "APPWRITE_FUNCTION_EVENT":"",
      "APPWRITE_FUNCTION_EVENT_DATA":"",
      "APPWRITE_FUNCTION_DATA":"",
      "APPWRITE_FUNCTION_USER_ID":"...",
      "APPWRITE_FUNCTION_JWT":"...",
      "INERNAL_EXECUTOR_HOSTNAME":"exc1"
   },
   "headers":{
      
   },
   "payload":""
}
```

It doesn't pass `req, res, log, error` as the docs show.

**Comment by tripathi-g** [comment]
that is because doc refers latest appwrite 1.4 but appwrite cloud is running on 1.1.2. That me be the issue.

**Comment by ItzNotABug** [comment]
I believe your project must be a `module` in `package.json`.
That would support the syntax mentioned in the docs.

See: Check this: https://github.com/appwrite/templates/tree/main/node/starter
Also make sure to use the latest available Runtime version, see: https://appwrite.io/docs/functions-runtimes.

**Comment by JorensM** [comment]
@ItzNotABug I tried setting `type` to `module` in `package.json`, and now I'm getting this error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/code-start/createUser.js from /usr/local/src/server.js not supported.
Instead change the require of createUser.js in /usr/local/src/server.js to a dynamic import() which is available in all CommonJS modules.
    at Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at /usr/local/src/server.js:55:28
```

While running this code:

```
export default async (fns) => {
    console.log('aaa')
    console.log(fns)
}
```

@tripathi-g Thanks, Is there any place where I can see the docs for 1.1.2 ?

**Comment by stnguyen90** [comment]
@JorensM, not anymore. Cloud will be updated to 1.4 soon. For now, you can refer to [this](https://github.com/appwrite/functions-starter/blob/main/node-18.0/src/index.js) for reference.

**Comment by gewenyu99** [comment]
@JorensM This isn't an Appwrite bug. Please update your package.json to be a module:

``` json
{
  // ...
  "type": "module",
  // ...
}
```

https://stackoverflow.com/questions/58211880/uncaught-syntaxerror-cannot-use-import-statement-outside-a-module-when-import

**Comment by JorensM** [comment]
@gewenyu99 thanks, I figured that out. But see https://github.com/appwrite/appwrite/issues/6104#issuecomment-1702496406

**Comment by gewenyu99** [comment]
> @gewenyu99 thanks, I figured that out. But see [#6104 (comment)](https://github.com/appwrite/appwrite/issues/6104#issuecomment-1702496406)

Yes the documentation you're reading is for 1.4, not < 1.3 😅 The guide docs are always latest version.

Legacy docs, refer to references and select 1.3 or your version in the top right.

**Comment by JorensM** [comment]
@gewenyu99 I meant the first part of this comment: https://github.com/appwrite/appwrite/issues/6104#issuecomment-1702496406

I changed `type` to `module` but am now getting a different error.

**Comment by stnguyen90** [comment]
@JorensM , please use this for reference: https://github.com/appwrite/functions-starter/blob/main/node-18.0/src/index.js

**Comment by comuneoOrg** [comment]
For me, I'm using Remix.run, and I had this error. On Remix, by their documentation:

    Server-only code - **Remix will remove server-only code, but it can't if you have module side effects that use server-only code.**
    Browser-only code - Remix renders on the server so your modules can't have module side effects or first-rendering logic that call browser-only APIs

So in other words, to use it properly, I needed to create a new file `something.server.ts`, this way it's a server-side file, that I can use without any problem.
I hope it solves your problem as well.

**Comment by gewenyu99** [comment]
Closing this since there's no further activity and this is a caveat with Node.js imports.
