### ISSUE TITLE
🐛 Bug Report: Cloud Function deployment example for CMD shows invalid syntax

### ISSUE THREAD

**Issue by JorensM** [appwrite/appwrite#6105]
### 👟 Reproduction steps

1.Create and navigate to a Cloud Function in the Appwrite console
2.Click 'Create deployment'
3.Scroll down to 'CMD' section
4.See invalid syntax

### 👍 Expected behavior

It should show double quotes for the --entrypoint flag

### 👎 Actual Behavior

It shows single quotes.

![cmd-example-appwrite](https://github.com/appwrite/appwrite/assets/17122123/4adae391-1793-4adb-9f65-a595838b983f)

Single quotes are not supported in CMD and when running the command with single quotes, a literal `'index.js'` string gets passed instead of just `index.js`, and in effect the Cloud Function fails to execute because it looks for the file string `'index.js'` instead of `index.js`

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@JorensM, thanks for raising this issue! 🙏🏼

**Comment by JorensM** [comment]
@stnguyen90 can I go ahead and make a PR for this?

**Comment by gewenyu99** [comment]
@JorensM Of course!

**Comment by gewenyu99** [comment]
Although this is already fixed in 1.4 😓  Wait for Cloud to be on 1.4!
