### ISSUE TITLE
🚀 Feature: Disable Register Button

### ISSUE THREAD

**Issue by polataydinn** [appwrite/appwrite#6107]
### 🔖 Feature description

If we could be able to disable register button that could be great. 

### 🎤 Pitch

if someone find out our server domain they can use it by creating a new account.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @polataydinn what is your use case?

**Comment by polataydinn** [comment]
All I want is that the people who finds out my server's ip or domain, they can be able to register and use my server's resources. In this case there can be a option to disable register button.

**Comment by gewenyu99** [comment]
@polataydinn You can: https://appwrite.io/docs/production#limitConsoleAccess

**Comment by gewenyu99** [comment]
Use the `_APP_CONSOLE_WHITELIST_ROOT` variable
