### ISSUE TITLE
🐛 Bug Report: [Console/Auth] Unable to remove Phone Number or Email Address

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6108]
### 👟 Reproduction steps

1. Go to any user that has both email address or a phone number, erase any one & click on Update.
Errors:
    - Email: `Invalid email: Value must be a valid email address.`
    - Phone: `Invalid number: Phone number must start with a '+' can have a maximum of fifteen digits.`

2. The main issue is that if you use an invalid phone number, it will be accepted.
Example: Type in just country code like: `+91`, click update & it works!
This isn't good if the account **only** has phone number as a user identifier.

### 👍 Expected behavior

1. Allow removing of Phone numbers **if** there's an Email Address added to the account & vice-versa.
2. Check the length of the phone number, the minimum acceptable length is around 7/8 digits [Source: Google Search].

### 👎 Actual Behavior

1. Unable to remove any of the phone number or email address, if both exists!
2. Phone numbers less than 7/8 digits are accepted.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Self hosted on local machine and a Ubuntu server.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Thanks for opening this @ItzNotABug

**Comment by techwithsrikanth** [comment]
Guess this is something related to schema of the table that is causing the issue, required field and maxLength/minLength can be updated in the fields to ensure this error can be resolved

Let me know your opinion and how's the issue currently going on?

**Comment by stnguyen90** [comment]
Fixed as part of https://github.com/appwrite/appwrite/pull/7471
