### ISSUE TITLE
All Contributors

### ISSUE THREAD

**Issue by anushkrishnav** [appwrite/appwrite#611]
Contributors' help in building great Projects would be great if we can have them in Project Readme?
People are giving themselves and their free time to contribute to open source projects in so many ways, so we believe everyone should be praised for their contributions (code or not).

I wish to add allcontributors to this repository

Reference:https://github.com/all-contributors/all-contributors

**Comment by eldadfux** [comment]
We did have this kind of list when we started out, but with over +130 code contributors and hundreds more with non-code contribution its super hard to maintain such a list. Instead we built: https://appwrite.io/community in respect to all our amazing contributors.

Github also offers the https://github.com/appwrite/appwrite/graphs/contributors which has a list of all our contributors. At Appwrite w also invite all contributors to our GitHub org to allow them to have an Appwrite badge in their GitHub profile.
