### ISSUE TITLE
🐛 Bug Report: yaml.scanner.ScannerError - Appwrite 1.4 version

### ISSUE THREAD

**Issue by Mr-Malomz** [appwrite/appwrite#6118]
### 👟 Reproduction steps

When I modify the `.env` file in my self-hosted Appwrite instance and attempt to synchronize the changes using `docker-compose up -d`, I receive an error message indicating that the `docker-compose.yml` file employs tabs instead of spaces.

Full error description below:

`**ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./docker-compose.yml", line 85, column 24**`

### 👍 Expected behavior

It should restart docker and update settings

### 👎 Actual Behavior

Returns this error:

`**ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./docker-compose.yml", line 85, column 24**`

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Mr-Malomz, thanks for creating this issue! 🙏 there seems to be something wrong with your docker-compose.yml file. Would you please check the line it mentions? You can also share it here if you need help finding out what's wrong.

**Comment by Mr-Malomz** [comment]
Hi @stnguyen90 

I was able to resolve the issue by removing the tabs in various locations. However, I filed a bug report because even though I didn't modify the `docker-compose.yml` file, I received an error when I changed the environment variable and attempted to re-sync the settings.

**Comment by stnguyen90** [comment]
@Mr-Malomz can you provide more detail about what you changed?

Also, can you share the malformed docker-compose.yml file?

**Comment by Mr-Malomz** [comment]
@stnguyen90 I can't share the `docker-compose.yml` file with the error as I have modified it and removed the trailing tabs.

The file I edited is the `.env` file.

To reproduce the bug:
* Edit the `_APP_SMS_PROVIDER` or any environment variable inside the `.env` file
* Restart the server using the command `docker compose up -d`

The restart command fails and complains about tabs inside the `docker-compose.yml ` file.

**Comment by stnguyen90** [comment]
@Mr-Malomz, thanks for providing those steps. I (and other devs) have modified the .env file and ran `docker compose up -d` without any problems so there must have been something else that happened.

Are you still able to reproduce the problem again?

**Comment by Mr-Malomz** [comment]
@stnguyen90 Oh, okay. I guess my editor's auto-formatter might be playing tricks here.

I will close the issue then, thanks for your response!
