### ISSUE TITLE
🐛 Bug Report: ✗ Error Param "runtime" is not optional. while deploying new function

### ISSUE THREAD

**Issue by AlloryDante** [appwrite/appwrite#6120]
### 👟 Reproduction steps

I used apprite npm cli v2.0.2 (The new one doesnt work) to deploy a newly created function on my selfhosted appwrite
Steps:
appwrite init function
appwrite deploy function

output:

```
PS C:\Users\Cezar\Desktop\test> appwrite deploy function
? Which functions would you like to deploy? tester (tester)
ℹ Info Deploying function tester ( tester )
✗ Error Param "runtime" is not optional.
```

### 👍 Expected behavior

Deploy the function without any errors

### 👎 Actual Behavior

Function gets saved on the dashboard, but if I try to execute it manually, it errors out: `Deployment not found. Create a deployment before trying to execute a function`

I tried to make a manual deployment via CLI but also got this error:

```
PS C:\Users\Cezar\Desktop\test> appwrite functions createDeployment ,
    --functionId=tester ,
    --entrypoint='index.js' ,
    --code="." ,
    --activate=true
error: unknown command 'createDeployment --functionId=tester --entrypoint=index.js --code=. --activate=true'

```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I use oracle cloud vps server and Windows npm apprite-cli version 2.0.2. Apprwrite is selfhosted and the only params were changed:
Appwrite Port to 8082 (I use ngix)
Apprite domain and target domain -> point to my cloudflare DNS appwrite.smartydent.com
Functions Runtimes set only to accept all the node-XX versions
Everything else is set to normal. I used docker-compose to start everything.

Please note that this is my first time running Appwrite so I dont have much experience with it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@AlloryDante thanks for creating this issue! 🙏 looks like we need to update the API to make runtime optional.

In addition, there's also this error when creating a deployment:

![image-2](https://github.com/appwrite/appwrite/assets/1477010/72320424-b20f-4e96-892d-8faac5b9c8df)

We probably need to add it back to the create deployment endpoint.

**Comment by RehanGG** [comment]
![image](https://github.com/appwrite/appwrite/assets/35191555/ce371eca-0798-4144-8264-7e14b8b2b3bd)

Newly created function is fine but updating it reveals this issue.
