### ISSUE TITLE
🐛 Bug Report: List of Runtimes is not displayed in function settings

### ISSUE THREAD

**Issue by RehanGG** [appwrite/appwrite#6121]
### 👟 Reproduction steps

Steps:

- I have set up my __APP_FUNCTION_RUNTIMES=dart-2.17_ in docker-compose and .env files
- Opened Console
- Navigate to Functions 
- Click on a function
- Go to the Settings tab

### 👍 Expected behavior

It should display the list of **runtimes** (in my case only dart-2.17)

### 👎 Actual Behavior

Well, the list of runtimes is showing when I tried to create a new function from console

![image](https://github.com/appwrite/appwrite/assets/35191555/b80db171-bcc4-474d-bd42-f29110b4ddee)

but under settings of a function it is not displaying list and only showing blank

![image](https://github.com/appwrite/appwrite/assets/35191555/8d051b7a-39d1-4a2e-8067-0349c485752d)

I have inspected the console also,

![image](https://github.com/appwrite/appwrite/assets/35191555/bf57ae82-0f77-487b-9540-229135ee1c42)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite: 1.4.1
Ubuntu VPS Server
Everything is normal.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@RehanGG, thanks for creating this issue! 🙏🏼 We'll look into this as soon as we can!
