### ISSUE TITLE
🐛 Bug Report: Not found error (404) when attempting to set relationships

### ISSUE THREAD

**Issue by dwcarr** [appwrite/appwrite#6123]
### 👟 Reproduction steps

When I use the node api to set relationships, I am getting a not found error (404), with no additional explanation.  Here are the relevant options sent with axios inside of the appwrite API after I call  `databases.createRelationshipAttribute(...)`
```
{
  method: 'POST',
  url: 'https://cloud.appwrite.io/v1/databases/4e48e7a520/collections/dbc0c64ecc2b/attributes/relationship',
  params: {},
  headers: {
    'accept-encoding': '*',
    'content-type': 'application/json',
    'x-sdk-name': 'Node.js',
    'x-sdk-platform': 'server',
    'x-sdk-language': 'nodejs',
    'x-sdk-version': '9.0.0',
    'X-Appwrite-Response-Format': '1.0.0',
    'x-appwrite-project': '...',
    'x-appwrite-key': '...'
  }
```
This returns with a 404: 
```
code: 404,
  type: 'general_route_not_found',
  response: {
    message: 'Not Found',
    code: 404,
    type: 'general_route_not_found',
    version: '0.10.51'
  }
```
I have double and triple checked the values of the databaseId and collectionId, and the same databaseId and collectionId work fine for creating all other types of attributes.  In other words, with the same headers

https://cloud.appwrite.io/v1/databases/4e48e7a520/collections/dbc0c64ecc2b/attributes/relationship => 404

https://cloud.appwrite.io/v1/databases/4e48e7a520/collections/dbc0c64ecc2b/attributes/string => 202

Note that I can successfully do all other database creation functions that I have attempted: createDatabase, createCollection, create*Attribute.  

For completeness, here is my call to createRelationshipAttribute:
```
databases.createRelationshipAttribute(
      database.databaseId,
      collectionId,
      value.collectionID,
      value.type,
      value.twoWay,
      key, 
      value.twoWayKey,
      value.onDelete,
      );
// value is a RelationshipSpec type
type RelationshipSpec = {
  collectionID: string;
  type: "oneToOne" | "oneToMany" | "manyToMany";
  twoWay: boolean;
  twoWayKey?: string;
  onDelete: "cascade" | "restrict" | "setnull";
};
```
all inputs are validated.  This call produces the axios call inside the client code, the relevant options for which are shown above.

### 👍 Expected behavior

Create a relationship attribute on the collection.

### 👎 Actual Behavior

returns 404

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Using node-appwrite version 9.5.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@dwcarr thanks for raising this issue! 🙏🏼 Unfortunately, Cloud doesn't have Relationships yet since it's on Appwrite version 1.1.2, but Relationships were added in Appwrite 1.3.0. We plan to update Cloud in the next couple weeks.

Related: https://github.com/appwrite/appwrite/issues/5599
