### ISSUE TITLE
🐛 Bug Report: default OAuth on custom domain results in 404 error

### ISSUE THREAD

**Issue by rohankm** [appwrite/appwrite#6124]
### 👟 Reproduction steps

Hi, I'm self-hosted and have added the required domain in the custom domain section of the project .. but the default OAuth is redirected to the custom domain which results in the 404 error.

### 👍 Expected behavior

The default OAuth routes should be whitelisted so that the custom domain can be used for deep link purposes.

### 👎 Actual Behavior

```
Error 404
The requested route was not found. Please refer to the API docs and try again.

Type

general_route_not_found
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@rohankm, thanks for raising this issue! 🙏🏼 Let me bring it up with the team.
