### ISSUE TITLE
🐛 Bug Report: Python 3.11 on Appwrite Cloud

### ISSUE THREAD

**Issue by tripolskypetr** [appwrite/appwrite#6131]
### 👟 Reproduction steps

On a moment of 04.09.2023 AppWrite cloud supports the following openruntime environments

 - Node.js - 16.0
 - Node.js - 18.0 
 - Ruby - 3.0
 - Python - 3.9
 - Dart - 2.17

### 👍 Expected behavior

I think you should upgrade Python to 3.11 because It consumes less memory. Also, It released in 2022, I think python 3.9 is old

Also, Is there any roadmap for Functions runtime list upgrade? **I really want to see dotnet in the cloud** but you forcing me to use local installation. Can you tell me estimate date?

### 👎 Actual Behavior

Still seeing these outdated slow runtimes. Python runtime is 30x slower. No one compiled language is supported

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

AppWrite Cloud 1.1.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Arafatik** [comment]
👍🏻👍🏻👍🏻

**Comment by joeyouss** [comment]
Hello @tripolskypetr 

Thank you so much for pointing this out. Python 3.11 isn't available on the cloud, it's accessible in our self-hosted setup with version 3.11.

We truly wish we could update the cloud with every release immediately, but there are many considerations we must account for to ensure stable cloud performance. I wish I had a concrete timeline to share, but as of now, all I can promise is that we are doing our best to roll out updates as swiftly as possible. We are working on updating Cloud to 1.4.

Your patience and understanding mean a lot to us. If there are any other aspects you'd like to discuss or any feedback you'd like to share, please do let us know.

**Comment by stnguyen90** [comment]
It would be good to have separate issues for individual runtimes so we can specifically see which runtimes are in demand. For now, I'm going to have this one be for Python 3.11.

**Comment by stnguyen90** [comment]
We now have a ML optimized runtime that is python 3.11:![Image](https://github.com/user-attachments/assets/c309ef0f-01d6-400a-a9d0-e0487ef92ce3)
