### ISSUE TITLE
🐛 Bug Report: Error while migrating collections cache to 1.4.1

### ISSUE THREAD

**Issue by RehanGG** [appwrite/appwrite#6140]
### 👟 Reproduction steps

- Upgraded to 1.4.1
- Ran migration command as instructed in documentation
- **Important Note: This error only occurs when cache documents are more than 99, it stops the migration with error**

If the cache documents are less than 100 the migration will continue fine as usual. How I came to know this?

- Ran migration and it failed when migration cache with more than 99 documents
- I opened up the MariaDB using command line and deleted the documents preceding 99 to make cache documents in total to 99.
- Ran migration again and it worked.

So I think, migration more than 100 documents will generate error and less than 100 will go fine.
 

### 👍 Expected behavior

It should migrate successfully.

### 👎 Actual Behavior

It crashes while migrating to 1.4.1, specifically crashes at **Migration Collection 'cache'** and when they are more than 99.

![image](https://github.com/appwrite/appwrite/assets/35191555/06ce7202-462e-43f0-9972-8579759ba969)

I have not taken screenshot while migration less than 100 cache items, but I assure you it works. Problem only lies with more than it.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Ubuntu 22.04
Appwrite 1.4.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @RehanGG , we are aware of this and we are working on it. Thanks!
