### ISSUE TITLE
🐛 Bug Report: Message: User (role: guests) missing scope (assistant.read)

### ISSUE THREAD

**Issue by bfritscher** [appwrite/appwrite#6143]
### 👟 Reproduction steps

When I try to use the assistant in the console or via the cli I get "Message: User (role: guests) missing scope (assistant.read)"
I am logged in with the main user which was used to create the initial setup. Maybe a migration issue to 1.4?

### 👍 Expected behavior

AI Assistant to work

### 👎 Actual Behavior

No permissions

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@bfritscher, what version of Appwrite do you have? Was it a clean install or upgrade?

**Comment by bfritscher** [comment]
Thanks @stnguyen90 for your actif management of issues however it is the second time where you not fully read the issue description. Or maybe it is my English. "Maybe a migration issue to 1.4?" it was a migration from 1.3.8 to 1.4.1.

I also had to manually upgrade the database table and Metadata of multiple tables related to functions as you seem to have fixed for 1.4.3.. This compounded with the broken 3.0.0 cli. Makes me think your release of 1. 4 was unfortunately too rushed.

Hope you can fix everything soon and put in place better quality control overall.

Thanks for the time you put into this software.

**Comment by stnguyen90** [comment]
> it was a migration from 1.3.8 to 1.4.1.

Thanks! It's helpful to get confirmation that you're on 1.4.1 and not 1.4.1. We'll look into this ASAP!
