### ISSUE TITLE
🚀 Feature: Support Case Insensitive File Extensions in Storage

### ISSUE THREAD

**Issue by leejustin** [appwrite/appwrite#6149]
### 🔖 Feature description

Appwrite Storage has a setting where users specify valid extensions for files that land in the bucket. The file extensions are case sensitive, so specifying `jpg` as an approved extension will error out when you try uploading a file with the extension `JPG`.

### 🎤 Pitch

Set the `Allowed File Extensions` in Appwrite Stroage to be case insensitive.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
So it looks like we made a change here: https://github.com/utopia-php/storage/pull/79 which ended up in utopia-php/storage version [0.15.0](https://github.com/utopia-php/storage/releases/tag/0.15.0). Cloud might be using 0.11.0. We [bumped](https://github.com/appwrite/appwrite/commit/04fa436dca24a74fc3123b0d629c9d0aeeab0f3b) utopia-php/storage in Appwrite 1.2.1 so it should be good in Cloud once upgraded.
