### ISSUE TITLE
🐛 Bug Report: Cannot create function from Github VCS

### ISSUE THREAD

**Issue by istornz** [appwrite/appwrite#6151]
### 👟 Reproduction steps

- Connect a Github VCS to Appwrite (https://appwrite.io/docs/configuration#git)
- Create a function (from QuickStart for ex.)
- Create a new repository or connect to existing (both not work)
- Click on "Create"

I can see a "Server error" like this picture:

<img width="862" alt="Capture d’écran 2023-09-05 à 11 11 04" src="https://github.com/appwrite/appwrite/assets/16645312/dc799e5b-578c-41d4-a606-4e486807870f">

Here is the log from `docker-compose logs appwrite`:

```
appwrite  | [Error] Timestamp: 2023-09-05T09:07:26+00:00
appwrite  | [Error] Method: POST
appwrite  | [Error] URL: /v1/functions
appwrite  | [Error] Type: Utopia\Database\Exception\Structure
appwrite  | [Error] Message: Invalid document structure: Unknown attribute: "schedule"
appwrite  | [Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
appwrite  | [Error] Line: 2619
```

### 👍 Expected behavior

It should create function on my Github & on Appwrite

### 👎 Actual Behavior

It actually show a error message (see picture)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Hetzner

I migrated from 1.3.8 -> 1.4.0 then run migration
I migrated from 1.4.0 -> 1.4.1 then run migration

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@istornz, thanks for creating this! 🙏🏼 Looks like you'll need to wait for 1.4.2 which has this patch: https://github.com/appwrite/appwrite/pull/6095
