### ISSUE TITLE
🐛 Bug Report: Appwrite Users SDK: ECONNREFUSED 

### ISSUE THREAD

**Issue by JorensM** [appwrite/appwrite#6152]
### 👟 Reproduction steps

I'm trying to execute a cloud function with the following code:
```
//appwrite functions createDeployment --functionId=create-user --entrypoint="createUser.js" --code="." --activate=true
/*  
payload: 
{
    "email": "hhh@gmail.com",
    "name": "Hhh",
    "password": "helloworld123",
    "role": "recruiter"
} 
*/
const sdk = require('node-appwrite')
function hasKeys(obj, keys) {
    const obj_keys = Object.keys(obj)
    return keys.every(key => {
        return obj_keys.includes(key)
    })
}

module.exports = async (req, res) => {

    const client = new sdk.Client()

    const users = new sdk.Users(client)

    if (
        !req.variables['APPWRITE_FUNCTION_ENDPOINT'] ||
        !req.variables['APPWRITE_FUNCTION_API_KEY']
    ) {
        throw new Error("Environment variables are not set. Function cannot use Appwrite SDK.");
    } else {
        client
            .setEndpoint(req.variables['APPWRITE_FUNCTION_ENDPOINT'])
            .setProject(req.variables['APPWRITE_FUNCTION_PROJECT_ID'])
            .setKey(req.variables['APPWRITE_FUNCTION_API_KEY'])
    }

    let success = true
    let msg = '' 

    let data = null

    data = JSON.parse(req.payload)

    if(!hasKeys(data, ['email', 'password', 'name', 'role'])) {
        success = false
        msg = 'Payload must include: email, password, name, role'
    }

    if (!success) {
        res.json({
            success: false,
            msg: msg
        }, 400)
    } else {
        users.create(
            sdk.ID.unique(),
            data.email,
            null,
            data.password,
            data.name,
        )
            .then(usr_res => {
                res.json({
                    success: true,
                    msg: 'created user ' + data.email
                })
            })
            .catch(err => {
                res.json({
                    success: false,
                    msg: err.message
                }, 400) //Error is coming from here
            })
    }
}
```

### 👍 Expected behavior

It should create a user account and return a positive response

### 👎 Actual Behavior

Instead it returns a bad response with the error message `connect ECONNREFUSED 127.0.0.1:80`

![appwrite-error](https://github.com/appwrite/appwrite/assets/17122123/a574f133-60ac-4b55-96d9-4dcfaa6a8281)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

`node-appwrite`: `^9.0.0`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@JorensM, i see you're using Appwrite Cloud. As such, would you please make sure your endpoint is `https://cloud.appwrite.io/v1`? You can't use localhost/127.0.0.1 because the function will connect to itself rather than Appwrite.

**Comment by JorensM** [comment]
@stnguyen90 you mean the APPWRITE_FUNCTION_ENDPOINT env variable? I had thought that this is used to set a custom endpoint name for the endpoint of the function itself, to be called through REST API. My mistake!

**Comment by JorensM** [comment]
@stnguyen90 I changed `APPWRITE_FUNCTION_ENDPOINT` to `https://cloud.appwrite.io/v1` and now it's working. Thanks!
