### ISSUE TITLE
🚀 Feature: SMS login (and Magic link) is not consitent with Email login

### ISSUE THREAD

**Issue by Megamannen** [appwrite/appwrite#6154]
### 🔖 Feature description

Right now [Create Email Session](https://appwrite.io/docs/client/account?sdk=web-default#accountCreateEmailSession) is the odd duck. Since it doesn't create the user if it doesn't exist.

I'm mainly focusing on the [Create Phone session](https://appwrite.io/docs/client/account?sdk=web-default#accountCreatePhoneSession)

Possible solution is to accept a "null" userID which can mean "existing user only"

### 🎤 Pitch

I don't want user registration, but I want to allow signing in with phone or magic link.
Right now that is not possible since the API will create the user if the phone/email doesn't exist.

Probably a fairly common use case?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Megamannen, thanks for raising this issue! 🙏🏼 For your use case, I would suggest setting the Users Limit to 1:

![image](https://github.com/appwrite/appwrite/assets/1477010/1c69ff85-22a9-4b80-a24e-dd798f26cb3a)

This should prevent new accounts from being created. Then, you can use a server SDK and API Key to create users (which bypasses this limit).

**Comment by Megamannen** [comment]
It actually does!

**Comment by Megamannen** [comment]
No, since I don't have any way of knowing the ID/UserId, or am I missing something? Feels the current function can only be used for registration and not login

**Comment by ItzNotABug** [comment]
What the OP means is that createEmailSession doesn't create a new user if one doesn't exist with the provided email address. The OP needs the same behaviour for Phone and Magic-Url Sessions i.e. don't create a new user if the user does not exist in `Auth` database.

Something like: `account. account.createMagicURLSession('[USER_ID]', 'email@example.com', false);` where `false` means `Don't create an account if this value is false & the user doesn't exist`.

**Comment by Megamannen** [comment]
You are correct in my need. But also remember that it's impossible to provide the [userId] when logging in
so `account.createMagicURLSession(null, 'email@example.com')` and `account.createPhoneSession(null, '+3800000000')` also works :P

**Comment by stnguyen90** [comment]
@Megamannen, if you set the user limit to some low number and someone calls `createMagicURLSession()` or `createPhoneSession()`, but their account (match on email or phone respectively) doesn't exist, they will get an error.

`createMagicURLSession()` code:

https://github.com/appwrite/appwrite/blob/891099c7c3dc1fe86c4e64467f9249651991b603/app/controllers/api/account.php#L920

`createPhoneSession()` code:

https://github.com/appwrite/appwrite/blob/891099c7c3dc1fe86c4e64467f9249651991b603/app/controllers/api/account.php#L1258

> it's impossible to provide the matching [USER_ID] 

You don't need to provide a matching user id when just logging in. that user id parameter is only used during account creation. Otherwise, it's ignored.

**Comment by Megamannen** [comment]
> You don't need to provide a matching user id when just logging in. that user id parameter is only used during account creation. Otherwise, it's ignored.

In that case it will work in my use case, thank you!
