### ISSUE TITLE
🐛 Bug Report: Clarify error message when project ID is missing

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6166]
### 👟 Reproduction steps

Make an API call like list documents for a database and collection that exists, but don't set the project ID.

### 👍 Expected behavior

The error says project ID is missing

### 👎 Actual Behavior

The error says database not found.

This happens because we default to the console project if no project ID is supplied. [This PR](https://github.com/appwrite/appwrite/pull/5639) attempted to fix this, but it was [reverted in 1.4.1](https://github.com/appwrite/appwrite/commit/345df3f2cafce9d8b9d66562cb83860c5835653e) when trying to make sure the [VCS callback](https://github.com/appwrite/appwrite/blob/1.4.1/app/controllers/api/vcs.php#L262-L277) doesn't throw an error like:

![image](https://github.com/appwrite/appwrite/assets/1477010/32bb17cd-0124-48f1-a996-950ddfe4189d)

We need to make sure to not default the project to console, while ensuring the VCS callback still works.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite Version 1.4.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by KanniShashankh** [comment]
Can i be assigned this issue, also a small breif description about the issue @stnguyen90

**Comment by utsavbhattarai007** [comment]
Hi, Can you assign to me this issue?

**Comment by nick2432** [comment]
can i work on this issue?

**Comment by stnguyen90** [comment]
An example, when I create a document without a project ID:

```shell
$ curl 'https://localhost/v1/databases/default/collections/test/documents' -k \
  -H 'content-type: application/json' \
  --data-raw '{"documentId":"unique()","data":{"searchAttribute":"asdf"},"permissions":[]}'
```

I get a server error:

```json
{
    "message": "Server Error",
    "code": 500,
    "type": "general_unknown",
    "version": "dev"
}
```

The docker logs from the appwrite container shows:

```
appwrite  | [Error] Timestamp: 2024-04-08T20:00:03+00:00
appwrite  | [Error] Method: POST
appwrite  | [Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
appwrite  | [Error] Type: Utopia\Database\Exception
appwrite  | [Error] Message: Collection not found
appwrite  | [Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
appwrite  | [Error] Line: 2623
```

**Comment by stnguyen90** [comment]
The error now:

```
{
  "message": "No Appwrite project was specified. Please specify your project ID when initializing your Appwrite SDK.",
  "code": 401,
  "type": "general_access_forbidden",
  "version": "1.6.0"
}
```
