### ISSUE TITLE
🚀 Feature: Cloud: Is it possible to find the endpoint url of a cloud function in the current version of Cloud?

### ISSUE THREAD

**Issue by JorensM** [appwrite/appwrite#6170]
### 🔖 Feature description

I want to make it possible for my function to be called by a webhook from a third party. [The docs](https://appwrite.io/docs/functions-execute) say that you can find the endpoint url of a function in the Function's tab in the Appwrite console, but I'm assuming that this is for a newer version that Cloud doesn't use yet, because there is no information showing about the function's url. I wanted to know if there's some other way to find out the url of a function. Thanks

### 🎤 Pitch

Being able to get the endpoint urls of cloud functions would open a door to many possibilities, such as creating a public API or consuming webhook events.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
You can use the endpoints explicitly on `Cloud` as well like:
`https://cloud.appwrite.io/v1/functions/{functionID}/executions`. Although make sure to add `X-Appwrite-Project` header key with the value as your Project Id.

For this to work,
you may have to use `Any` or `All guests` persmission to allow executions from anywhere. Or if you can use Server Side SDK, you should instead use that.

Something like:
1. External provider sends a POST request to your server, say `hook.example.com/incoming`.
2. Process that request with verifications and other stuff.
3. Use `Server Side SDK` to execute function & handle the results.

**Comment by JorensM** [comment]
@ItzNotABug Thanks, this works! :)
