### ISSUE TITLE
🐛 Bug Report: Wrong Message if Verification requested on Magic Url Session

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6171]
### 👟 Reproduction steps

I’ve seen this #4797 but not sure if this was fixed in `1.4x`.
If not & if for some reason an email verification was requested for a user who signed in via magic url, the api returns a `Server Error` message which should probably be more descriptive.

### 👍 Expected behavior

Send an appropriate message like: `This user is already verified.`

### 👎 Actual Behavior

The server returns a `Server Error` message.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ItzNotABug, thanks for raising this! 🙏🏼 Would you be able to provide the docker logs from the appwrite container for the related server error?

**Comment by ItzNotABug** [comment]
No longer able to reproduce & works as expected. Closing.
