### ISSUE TITLE
🐛 Bug Report: Cannot upgrade to newer versions - Stuck on 1.3.4

### ISSUE THREAD

**Issue by maendamedia** [appwrite/appwrite#6181]
### 👟 Reproduction steps

When i run docker run -it --rm     --volume /var/run/docker.sock:/var/run/docker.sock     --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw     --entrypoint="install"     appwrite/appwrite:1.3.5 it starts updating and tells me  afterwards it is installed.

Starting Appwrite installation...
Compose file found, creating backup: docker-compose.yml.1694121709.backup
Env file found, creating backup: .env.1694121709.backup
Choose your server HTTP port: (default: 80)

Choose your server HTTPS port: (default: 443)

Choose a secret API key, make sure to make a backup of your key in a secure location (default: 'mykey')

Enter your Appwrite hostname (default: 'myhostname')

Enter a DNS A record hostname to serve as a CNAME for your custom domains.
You can use the same value as used for the Appwrite hostname. (default: 'myhostname')

If you haven't already done so, set the following record for cloud.mm-backend.nl on your DNS provider:

Type            Name       Value                         
A or AAAA       @          <YOUR PUBLIC IP>              

Use 'AAAA' if you're using an IPv6 address and 'A' if you're using an IPv4 address.

Running "docker compose -f /usr/src/code/appwrite/docker-compose.yml up -d --remove-orphans --renew-anon-volumes"
Appwrite installed successfully

### 👍 Expected behavior

It should be updated to given version. If i check it with doctor it says indeed 1.3.5

### 👎 Actual Behavior

After restarting the container it reverts to 1.3.4: 

<img width="2224" alt="Scherm_afbeelding 2023-09-07 om 23 28 18" src="https://github.com/appwrite/appwrite/assets/40370211/45ee7589-62bb-437d-85b1-165a5bc44f27">

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Ubuntu 22.04.3 LTS
Not customized

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@maendamedia, thanks for creating this issue! 🙏🏼 Would you please upgrade to 1.3.8 instead of 1.3.5? Please also run the migrate command after upgrading to 1.3.8.

**Comment by maendamedia** [comment]
Tried that also. Same problem.
In the meantime i found out the i need to manual set in the docker-compose.yaml the image version to the version i upgraded to. Then it seems to work.

Not sure if this is the way though and if everything then works as expected

image: appwrite/appwrite:1.4.2

**Comment by stnguyen90** [comment]
@maendamedia, where exactly did you run the install command and what's in your appwrite folder?

> In the meantime i found out the i need to manual set in the docker-compose.yaml the image version to the version i upgraded to. Then it seems to work.

I do not recommend doing this because, often times, there are updates to the compose file that you would miss.

**Comment by maendamedia** [comment]
Ok but how can we fix this then?

**Comment by maendamedia** [comment]
Any ideas?

**Comment by stnguyen90** [comment]
@maendamedia the best thing to do would be:

1. Restore from backup
2. Make sure you don't have a `[PARENT_DIR]/appwrite/appwrite` folder
3. Make sure your `docker-compose.yml` and `.env` files are inside `[PARENT_DIR]/appwrite`
4. Run the upgrade command **while inside the `[PARENT_DIR]` folder**
5. Run the migrate command **while inside the `[PARENT_DIR]/appwrite` folder**

**Comment by maendamedia** [comment]
Yes i had all of that. That still causes this issue :(
Will try on next update if it works

**Comment by stnguyen90** [comment]
@maendamedia what is the issue now?

Also, it would be best to troubleshoot this in a Support post on [Discord](https://appwrite.io/discord) rather than on GitHub so that you can get guidance synchronously.

**Comment by tripolskypetr** [comment]
For me, the best way to solve a problem of that kind is to make [the full json-per-document backup](https://github.com/react-declarative/appwrite-backup-tool) and restore documents to the new clear installation
