### ISSUE TITLE
🐛 Bug Report: Problems migrating from 1.4.1 to 1.4.2

### ISSUE THREAD

**Issue by Kriihz77** [appwrite/appwrite#6182]
### 👟 Reproduction steps

When executing the command: docker run -it --rm --volume /var/run/docker.sock:/var/run/docker.sock --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw --entrypoint="upgrade" appwrite/appwrite:1.4.2

### 👍 Expected behavior

Migration done correctly

### 👎 Actual Behavior

Error message:
Appwrite installation not found.
The command was not executed in the parent folder of your Appwrite installation.
Please navigate to the parent directory of the Appwrite installation and try again.
  parent_dir <= run the command in this directory.
  └── appwrite.
      └── docker-compose.yml

in this path is currently the docker compose file and in the previous migrations it worked correctly.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.4.1 To 1.4.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@criihz, thanks for creating this issue! 🙏🏼 Did you execute the command in your appwrite folder or in the parent folder of your appwrite folder?

**Comment by criihz** [comment]
I have my docker-compose.yml in the /opt/appwrite/ folder and in this folder I launch the indicated command.

to migrate from 1.3.8 to 1.4.0 I did it in that folder and it worked correctly.

**Comment by stnguyen90** [comment]
@Kriihz77, please run the upgrade command in the opt folder rather than appwrite.

If you ran the install command in the appwrite folder, you may have a nested appwrite folder now. Would you please share what's in your /opt/appwrite folder?

**Comment by Kriihz77** [comment]
Of course yes, in the /opt/appwrite folder I have the following structure, as indicated, if I execute from that location it creates the nested folder, remaining as follows: /opt/appwrite/appwrite, I will clarify, that I did an installation again from scratch.

```log

drwxrwxrwx  3 root root  4096 sep  8 13:23 .
drwxr-xr-x 13 root root  4096 ago 19 20:51 ..
drwxr-xr-x  2 root root  4096 sep  7 17:01 bkp
-rw-r--r--  1 root root 22173 sep  7 17:35 docker-compose.yml
-rw-r--r--  1 root root  5344 sep  8 13:23 .env

```

**Comment by stnguyen90** [comment]
> if I execute from that location it creates

Right, that's why you need to run the install command in your /opt folder and **not** in your /opt/appwrite folder. Are you saying you ran the upgrade command in the /opt folder but got the error below?

```
Appwrite installation not found.
The command was not executed in the parent folder of your Appwrite installation.
Please navigate to the parent directory of the Appwrite installation and try again.
parent_dir <= run the command in this directory.
└── appwrite.
└── docker-compose.yml
```

**Comment by Kriihz77** [comment]
No, I migrated it on /opt/appwrite, when I changed from version 1.3.8 to 1.4.0 it worked correctly on the directory /opt/appwrite, but when I moved from 1.4.1 to 1.4.2 it did not work on this directory and generated the error, it is possible that it is due to an error in the migration script of 1.4.0 and not of 1.4.2.

In addition to the above during the migration, the modified path of the volumes is not respected, making the migration a little more complex, example:

``` yml
Default
volume:
   - appwrite-config:/storage/config:ro

Modified
volume:
   - /Disc3/appwritedata/appwrite-config:/storage/config:ro
```

With the above I indicate that when I run the migration, it does not respect the modified paths and when migrating, it leaves all volumes by default.

**Comment by stnguyen90** [comment]
@Kriihz77, there are 2 steps to upgrading:

1. [Installing the Next Version](https://appwrite.io/docs/upgrade#install-new-version)
2. [Running the Migration](https://appwrite.io/docs/upgrade#migration)

Step 1 should have been done in your /opt folder. Step 2 should have been done in your /opt/appwrite folder.

> In addition to the above during the migration, the modified path of the volumes is not respected

I highly suggest not modifying the docker-compose.yml file generated by Appwrite during the install/upgrade because your changes would be wiped the next time you run the install/upgrade command. It is best to override things using a docker-compose.override.yml file. Alternatively, you would need to manually upgrade instead of running the upgrade command, but I do not recommend this because it is easy to make a mistake or miss something.

**Comment by EVDOG4LIFE** [comment]
Given the amount of time between responses here, I am closing this out. If you still have problems, I recommend raising a support thread on our [Discord](discord.gg/appwrite)
