### ISSUE TITLE
📚 Documentation: Download Deployment is missing description

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6183]
### 💭 Description

https://appwrite.io/docs/server/functions?sdk=nodejs-default&v=1.4.x#functionsDownloadDeployment

![image](https://github.com/appwrite/appwrite/assets/1477010/856911c6-0b36-42d7-bbca-2272c6ae9220)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by btme0011** [comment]
can i work on this?

**Comment by dcompanykrish** [comment]
Can you guide my what to do? I am new to open source 😄 , I'm available to work on it. Can I help?

**Comment by stnguyen90** [comment]
@dcompanykrish, I suggest looking for issues labeled "good first issue" or "help wanted"

**Comment by dcompanykrish** [comment]
Thank you for your suggestion, @stnguyen90. I appreciate your guidance and support. I will look for issues labeled “good first issue” or “help wanted” and try to contribute to the project.

**Comment by PineappleIOnic** [comment]
Fixed in #6268
