### ISSUE TITLE
Clarify _APP_VCS_GITHUB_PRIVATE_KEY env var

### ISSUE THREAD

**Issue by Kriihz77** [appwrite/appwrite#6190]
### 👟 Reproduction steps

Go to Functions> Create function> Connect with GITHUB> Install application.

Error 500 is generated

### 👍 Expected behavior

Successful connection and repository creation

### 👎 Actual Behavior

``` log

appwrite  | [Error] Timestamp: 2023-09-08T03:41:12+00:00
appwrite  | [Error] Method: GET
appwrite  | [Error] URL: /v1/vcs/github/callback
appwrite  | [Error] Type: Ahc\Jwt\JWTException
appwrite  | [Error] Message: Signing key cannot be empty
appwrite  | [Error] File: /usr/src/code/vendor/adhocore/jwt/src/ValidatesJWT.php
appwrite  | [Error] Line: 34
appwrite  | [Error] Timestamp: 2023-09-08T03:41:53+00:00
appwrite  | [Error] Method: GET
appwrite  | [Error] URL: /v1/vcs/github/callback
appwrite  | [Error] Type: Ahc\Jwt\JWTException
appwrite  | [Error] Message: Signing key cannot be empty
appwrite  | [Error] File: /usr/src/code/vendor/adhocore/jwt/src/ValidatesJWT.php
appwrite  | [Error] Line: 34

```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.4.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Kriihz77, did you configure GitHub integration following the [docs](https://appwrite.io/docs/configuration#git)? If not, please do so. If you need additional help, it would be best to create a support post on [discord](https://appwrite.io/discord) since it would be easier to troubleshoot over chat than on GitHub.

**Comment by Kriihz77** [comment]
Thanks @stnguyen90 , I already managed to solve the issue through Discord, but I consider that a little more clarity is necessary in the manual when indicating the private key, since it is necessary to replace all line breaks with \n and it must be in double quotes.

This bug can be changed by updating the documentation.

best regards

**Comment by stnguyen90** [comment]
@Kriihz77, that's great news! Yes, we plan on adding additional details to the docs as part of https://github.com/appwrite/docs/pull/429
