### ISSUE TITLE
🐛 Bug Report: Can't upgrade with long attributes

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6196]
### 👟 Reproduction steps

1. Create more than 100 attributes with key that is longer than 35 like `iam35characterslonggggggggggggggggg` on 1.3.8
3. Upgrade to 1.4.2
4. Run migrate command

### 👍 Expected behavior

Migration is successful

### 👎 Actual Behavior

Migration fails with:

```
Migrating Collection attributes:
100 / 574
200 / 574

Fatal error: Uncaught Utopia\Database\Exception\Query: Invalid query: Invalid cursor: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php:4061
Stack trace:
#0 /usr/src/code/src/Appwrite/Migration/Migration.php(198): Utopia\Database\Database->find(Object(Utopia\Database\Document), Array)
#1 /usr/src/code/src/Appwrite/Migration/Version/V19.php(798): Appwrite\Migration\Migration->documentsIterator('attributes')
#2 {main}
  thrown in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 4061
```

This is because we paginate using a cursor and the $id that is used for the cursor is the $id for an attribute:

https://github.com/appwrite/appwrite/blob/5717fbe28243a7616434d908554db51d28c4f35d/app/controllers/api/databases.php#L117

which means a valid key of length 35 can result in an $id greater than 36 due to the `$db->getInternalId() . '_' . $collection->getInternalId() . '_'` prefix. Because the $id is greater than 36 chars, UID validation fails.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Tested on 1.4.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by fogelito** [comment]
https://github.com/utopia-php/database/pull/322

**Comment by stnguyen90** [comment]
We'll revisit this if we see more demand for this

**Comment by stnguyen90** [comment]
Re-opening due to another case: https://discord.com/channels/564160730845151244/1249721750778806332

**Comment by stnguyen90** [comment]
We should be able to bypass this validation error by calling [`disableValidation()`](https://github.com/utopia-php/database/blob/main/src/Database/Database.php#L770) before the migration starts.
