### ISSUE TITLE
🐛 Bug Report: Realtime sends relationship attribute data as null

### ISSUE THREAD

**Issue by RehanGG** [appwrite/appwrite#6197]
### 👟 Reproduction steps

- Created a collection and attributes with one attribute as relationship type.
- Added data in it
- Retrieved using normal getDocument functions and it works.
- Created a realtime connection to that document
- Updated document from database and using a function.

### 👍 Expected behavior

It should send relationship attribute data as normal in realtime event payload as it did before in 1.3.8

### 👎 Actual Behavior

It actually sends **null** for the related attribute, other attributes are fine.

![image](https://github.com/appwrite/appwrite/assets/35191555/d1ad58cc-34f5-4969-b625-bf2026075b56)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Flutter SDK 10.0.1
Appwrite 1.4.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by RehanGG** [comment]
It does not send as null, the attribute just does not exist in the payload.

**Comment by fpaiva36834** [comment]
I think i have the same problem that happens when i'm getting the data from the relations and it returns null always and it has data in it
![imagem](https://github.com/appwrite/appwrite/assets/72525693/f824f974-1397-44d6-a3c4-561aaa5e6af4)
![imagem](https://github.com/appwrite/appwrite/assets/72525693/043a376e-3100-4595-bd25-7c908f4d0e92)

**Comment by stnguyen90** [comment]
Related: https://github.com/appwrite/appwrite/issues/5372
