### ISSUE TITLE
🐛 Bug Report: Dart Runtime expects the `entrypoint` file to be inside `lib` folder

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6202]
### 👟 Reproduction steps

This issue has been moved here from [open-runtimes#194](https://github.com/open-runtimes/open-runtimes/issues/194), as suggested by Steven on Discord.

---

Previously on `1.3x` the entry point file was allowed to be used in the root directory & it wasn't necessary that it should be inside `lib` directory.

However, on `1.4x` function building fails.
Even the default path for the entry point is `lib/main.dart` if `Platform.environment['OPEN_RUNTIMES_ENTRYPOINT']` is `null`.

If the entry point is in the root directory, the build fails with below error:
```bash
server.dart:5:8: Error: Error when reading 'lib/main.dart': No such file or directory
import 'package:packageName/main.dart' as user_code;
       ^
server.dart:107:25: Error: Method not found: 'main'.
              user_code.main(context)
                        ^^^^
server.dart:117:38: Error: Method not found: 'main'.
            output = await user_code.main(context);
```

Build works fine if the `main.dart` is inside the `lib` folder.

---

The error stems from here, I believe:
```dart
serv = serv.replaceAll('{entrypoint}', "package:$packageName/" + fileName);
```

Proposed solution:
1. Add relevant info to docs to follow the standard `Dart` file structure convention
2. Move the entry point inside the `lib` directory when building the function.

### 👍 Expected behavior

1. Like previous versions, allow using the `entrypoint` as mentioned while deploying the `Function`.
2. Use the `Dart`'s standard file structure convention and let the developer know about this via Docs.
3. Simply move the `entrypoint` file inside the `lib` folder when preparing for the build.

### 👎 Actual Behavior

Function build process fails with below error:
```bash
Error: Method not found: 'main'.
              user_code.main(context)
                        ^^^^
server.dart:117:38: Error: Method not found: 'main'.
            output = await user_code.main(context);
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Nothing fancy, just the same old `localhost`.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Heyy 👋
No final decision yet, but we are considering enforcing `lib` folder. It's a good practice, and trying to support functions without lib folder might be tricky. We cant simply move files in 1.4, as we now support rootDirectory and custom build commands.

**Comment by ItzNotABug** [comment]
Hmm, even I believe enforcing `lib` folder structure is a good way.
I suggest implementing standard structures for other languages as well, if common or standard conventions exist.

**Comment by JimWuerch** [comment]
This breaks having multiple dirs, and the entry point being in a lib dir not off of root, as in myproject/function/lib/main.dart

**Comment by stnguyen90** [comment]
> This breaks having multiple dirs, and the entry point being in a lib dir not off of root, as in myproject/function/lib/main.dart

@JimWuerch, I typically deploy using the root directory of `myproject/function` so that in the function, `lib` is still at the root.
