### ISSUE TITLE
🐛 Bug Report: [Console] Cannot disable `Custom SMTP Settings`

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6203]
### 👟 Reproduction steps

1. Enable `Custom SMTP server`
2. Click Update
3. Disable the `Custom SMTP server` checkbox 
4. Click Update

### 👍 Expected behavior

Disable Custom SMTP Settings.

### 👎 Actual Behavior

Following error shows up:

<img width="1398" alt="Screenshot 2023-09-09 at 4 52 01 PM" src="https://github.com/appwrite/appwrite/assets/20625965/9cd02b61-afaf-43f1-b618-a1762def2180">

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Localhost.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by TheOjasSingh** [comment]
can you explain more about this issue?

**Comment by stnguyen90** [comment]
@ItzNotABug, thanks for raising this issue! 🙏🏼 We probably should be setting enabled to false here:

https://github.com/appwrite/console/blob/ba877ef36f757a7d7c8a6e12783362024e5ceaca/src/routes/console/project-%5Bproject%5D/settings/smtp/%2Bpage.svelte#L49

**Comment by btme0011** [comment]
can i work on this?

**Comment by nick2432** [comment]
Can i work on this issue

**Comment by stnguyen90** [comment]
Tasks:

* [ ] https://github.com/appwrite/console/pull/542
* [ ] Bump console
