### ISSUE TITLE
📚 Documentation: Clarifying how to upgrade functions

### ISSUE THREAD

**Issue by eauw** [appwrite/appwrite#6204]
### 💭 Description

Some of my nodejs functions throw the following error on execution:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/code-start/src/index.js from /usr/local/src/server.js not supported.
Instead change the require of index.js in /usr/local/src/server.js to a dynamic import() which is available in all CommonJS modules.
    at Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at /usr/local/src/server.js:55:28
```

I turned out that I can't just add `"type": "module",` in the package.json of my existing functions while new created (cli > 3) functions have that. Also changing the function declaration to `export default async ({ req, res, log, error }) => {` doesn't work.

Please change/add this information in the docs https://appwrite.io/docs/functions-develop#upgrade

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@eauw, thanks for creating this issue! 🙏🏼 Yes, we'll need to update our docs, as you can't just create a new deployment with the new syntax. You'll need to create a new function or delete your old function and recreate it.

**Comment by stnguyen90** [comment]
Updated in https://github.com/appwrite/docs/pull/433
