### ISSUE TITLE
🐛 Bug Report: Console sudden routes to Storage

### ISSUE THREAD

**Issue by suleimanas** [appwrite/appwrite#6205]
### 👟 Reproduction steps

Hello, funny issue
In the console (select your project):
- Hold or double-press the arrow UP key on your keyboard you'll go to the Storage page
- double-press the arrow LEFT key on your keyboard you'll go out of the project to console/account page

### 👍 Expected behavior

route shouldn't change

### 👎 Actual Behavior

console routes changes

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by FreSauce** [comment]
Hey, I would like to try working on this issue. Can you assign it to me?

**Comment by stnguyen90** [comment]
Assigned! Thanks for your interest!

**Comment by stnguyen90** [comment]
@FreSauce, how's your progress on this?

**Comment by FreSauce** [comment]
Found the bug, 
![image](https://github.com/appwrite/appwrite/assets/34598383/6bbb1dcb-f492-490f-8973-20a028c09f3d)
this was causing an issue as hitting Arrow Up key two times is `[38, 38]` in `recentkeycodes`, and `commandKeycodes` has `[83]` key for `go to storage` command. so joining with empty separator was giving true as 3838 includes 83.

**Comment by FreSauce** [comment]
@stnguyen90, should i just change the separator to `,` instead of empty string, or should we think of a more robust approach to check if all keys are pressed?

**Comment by stnguyen90** [comment]
@TGlide, what do you think?

**Comment by TGlide** [comment]
> @stnguyen90, should i just change the separator to `,` instead of empty string, or should we think of a more robust approach to check if all keys are pressed?

I think that's a good approach!

**Comment by FreSauce** [comment]
Okay, I will go along with it

> > @stnguyen90, should i just change the separator to `,` instead of empty string, or should we think of a more robust approach to check if all keys are pressed?
> 
> I think that's a good approach!
