### ISSUE TITLE
🐛 Bug Report: Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by lalitkumawat1m** [appwrite/appwrite#6208]
### 👟 Reproduction steps

Scroll to footer section and see twitter old logo

### 👍 Expected behavior

Twitter logo should be changed to X

### 👎 Actual Behavior

Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

### Screenshot
<img width="960" alt="Screenshot 2023-09-10 084717" src="https://github.com/appwrite/appwrite/assets/91591901/dc07708b-42ac-4425-a768-5d8276903065">

@sesam 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@lalitkumawat1m, thanks for your interest! Unfortunately, the source code for this isn't open so you won't be able to contribute for this. I suggest looking for issues labeled with "good first issue" or "help wanted" if you're looking to contribute.

**Comment by HeetVekariya** [comment]
Is this issue is still open ? if it is then i would like work on this.

**Comment by stnguyen90** [comment]
Closing as this is no longer a problem.
