### ISSUE TITLE
🐛 Bug Report: `APPWRITE_FUNCTION_EVENT_DATA` Key Error

### ISSUE THREAD

**Issue by noob8boi** [appwrite/appwrite#6209]
### 👟 Reproduction steps

1) Migrate from 1.3.8 to 1.4.2
2) Redeploy an old function which automatically executes on an event
3) Use `APPWRITE_FUNCTION_EVENT_DATA` from variables

### 👍 Expected behavior

Old function should execute without any error

### 👎 Actual Behavior

I get `APPWRITE_FUNCTION_EVENT_DATA` key error when trying to access it from request.variables

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Python SDK Version - 1.1.0 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@noob8boi thanks for creating this issue! Well look into this ASAP!

**Comment by noob8boi** [comment]
Sure @stnguyen90 btw I just now got to know that this doesnt' exist in the new deployed functions as well..
