### ISSUE TITLE
🐛 Bug Report: Issues with LinkedIn OAuth 2.0

### ISSUE THREAD

**Issue by Ronitron007** [appwrite/appwrite#6212]
### 👟 Reproduction steps

So I am trying to using the OAuth2.0 for LinkedIn and the bug probably occurs when account.createOAuth2Session('LinkedIn') is used. 

While signIn with linkedIn initially used to have Oauth2.0 it uses OIDC now for SSO. 

<img width="781" alt="Screenshot 2023-09-10 at 6 10 04 PM" src="https://github.com/appwrite/appwrite/assets/26198593/24eb807b-b3d6-4733-b1ec-4f2be02fec44">

I think the name of scopes for linkedIn should be changed from
```
 'r_liteprofile',
 'r_emailaddress',
```

to 
```
'openid',
'profile',
'email'
```

### 👍 Expected behavior

I should be redirected to my success page. And there should be a new user logged in.

### 👎 Actual Behavior

I get an error on linkedIn's page and I am redirected to an appWrite url. 

The appWrite url is 
[https://cloud.appwrite.io/v1/account/sessions/oauth2/callback/linkedin/64fc38061af407cce741?error=unauthorized_scope_error&error_description=Scope+%26quot%3Br_liteprofile%26quot%3B+is+not+authorized+for+your+application&state=%7B%22success%22%3A%22http%3A%5C%2F%5C%2Flocalhost%3A3001%5C%2F%22%2C%22failure%22%3A%22http%3A%5C%2F%5C%2Flocalhost%3A3001%5C%2Ffail%22%7D](https://cloud.appwrite.io/v1/account/sessions/oauth2/callback/linkedin/64fc38061af407cce741?error=unauthorized_scope_error&error_description=Scope+%26quot%3Br_liteprofile%26quot%3B+is+not+authorized+for+your+application&state=%7B%22success%22%3A%22http%3A%5C%2F%5C%2Flocalhost%3A3001%5C%2F%22%2C%22failure%22%3A%22http%3A%5C%2F%5C%2Flocalhost%3A3001%5C%2Ffail%22%7D)

I pasted the url since the url does have the error in it 

> error: unauthorized_scope_error
> error_description: Scope &quot;r_liteprofile&quot; is not authorized for your application
> state: cfa970987c9a3c2178dddeda0d81dab3e00dce4c683098d6

<img width="1321" alt="Screenshot 2023-09-10 at 5 42 34 PM" src="https://github.com/appwrite/appwrite/assets/26198593/bd7ac70c-7c61-413d-9fd5-e24fc8704fc4">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Ronitron007, thanks for creating this issue! 🙏 For now, does it work if you pass the additional required scopes when calling the [Create OAuth2 Session](https://appwrite.io/docs/client/account?sdk=web-default#accountCreateOAuth2Session) API?

**Comment by Ronitron007** [comment]
Hey, I am afraid it doesn't work since the scopes for 'r_liteprofile' and 'r_emailadress' are also sent in the request.

**Comment by stnguyen90** [comment]
Ah! I'm sorry; I misunderstood the problem. [Sign in with LinkedIn has been deprecated](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin) and [Sign In with LinkedIn using OpenID Connect](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext) is the only option available now which doesn't use the 'r_liteprofile' and 'r_emailadress' scopes. This means we need to update our [LinkedIn OAuth2 Provider](https://github.com/appwrite/appwrite/blob/master/src/Appwrite/Auth/OAuth2/Linkedin.php).

**Comment by Ronitron007** [comment]
Yes, you got it correct. But I think there might be some caveats involved.

**Comment by btme0011** [comment]
can i work on this issue?

**Comment by stnguyen90** [comment]
@btme0011, assigned! Thanks for your interest! 🙏🏼

**Comment by poutkieran** [comment]
> Yes, you got it correct. But I think there might be some caveats involved.





https://klayoxidation.github.io/Cjb38dE0GZXt19rxkpMSzPyiJAXsXYNgmmi3tFUJ/
