### ISSUE TITLE
🐛 Bug Report: Function fails before timeout

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6234]
### 👟 Reproduction steps

1. Create a function that takes 120 seconds to complete and has a timeout of 240 seconds
2. Execute the function

### 👍 Expected behavior

The function executes successfully.

### 👎 Actual Behavior

The function fails after about 1 minute with:

```
An internal curl error has occurred within the executor! Error Msg: Connection reset by peer\nError Code: 500
```

<img width="1457" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/3e292450-af07-4516-8008-30210ba7c121">

`openruntimes-executor` logs shows:

```
openruntimes-executor  | 2023-09-13T21:50:57.710159636Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:50:57.712701536Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:51:57.709376166Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:51:57.710428756Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:52:57.708922472Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:52:57.710464182Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:53:57.710213540Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:53:57.711186120Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:54:57.708778609Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:54:57.709870409Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:55:50.853424759Z Skipping runtimes stats loop due to error: Docker Error: EOF
openruntimes-executor  | 2023-09-13T21:55:50.853927049Z 
openruntimes-executor  | 2023-09-13T21:55:57.709138899Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:55:57.711327889Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:55:57.768026941Z [Error] Type: Exception
openruntimes-executor  | 2023-09-13T21:55:57.768076261Z [Error] Message: An internal curl error has occurred within the executor! Error Msg: Connection reset by peer
openruntimes-executor  | 2023-09-13T21:55:57.768218691Z [Error] File: /usr/local/app/http.php
openruntimes-executor  | 2023-09-13T21:55:57.768254591Z [Error] Line: 1021
openruntimes-executor  | 2023-09-13T21:55:58.041696876Z Successfully removed test-65022f347071fb788afa
openruntimes-executor  | 2023-09-13T21:56:57.709221683Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:56:57.712822882Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:57:57.709210892Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:57:57.710165702Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:58:57.708959414Z Running maintenance task ...
openruntimes-executor  | 2023-09-13T21:58:57.710204513Z Maintanance task finished.
openruntimes-executor  | 2023-09-13T21:59:57.709086915Z Running maintenance task ...
```

Looking at the logs, it seems like the maintenance task is running way too often. It seems this value should be 1 hour instead of 60 seconds:

https://github.com/appwrite/appwrite/blob/5717fbe28243a7616434d908554db51d28c4f35d/app/config/variables.php#L847C7-L855

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Tested on 1.4.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sergeycherepanov** [comment]
hi @stnguyen90 
I still facing this issue on 1.4.3, could you please clarify is issue merged to this version.

**Comment by schnetzlerjoe** [comment]
I am experiencing the same @sergeycherepanov

**Comment by sergeycherepanov** [comment]
@schnetzlerjoe actually it looks like proxy timeout. Need to investigate the connection between the function http endpoint and Appwrite, if it goes via public internet it can be an issue. The similar issue is described here by me https://github.com/appwrite/appwrite/issues/6328.
