### ISSUE TITLE
🐛 Bug Report: [Console] Inconsistent Theme for Datetime Picker

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6236]
### 👟 Reproduction steps

See below:

<img width="635" alt="Screenshot 2023-09-14 at 1 16 25 PM" src="https://github.com/appwrite/appwrite/assets/20625965/f430993f-ea0a-4253-86ab-8867d03f9d68">

---

Suggestion:
1. Maybe a different UI for time selection as well.
2. Also change the blue colour for buttons with appwrite's pink accent colour.

### 👍 Expected behavior

Picker should use the console theme.

### 👎 Actual Behavior

Picker is always on light theme.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Faisalhs51** [comment]
assign this issue to me

**Comment by Pinaka-Pani-18** [comment]
Can I work on this issue?

**Comment by stnguyen90** [comment]
@Pinaka-Pani-18, I don't think so because our design team needs to be involved. I suggest you look for issues labeled with "good first issue" or "help wanted"

**Comment by eldadfux** [comment]
We're using the native OS date input for improved accessibility. We have no plans at the moment to move to a custom input element.
