### ISSUE TITLE
🐛 Bug Report: Inconsistent Build Logs

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6237]
### 👟 Reproduction steps

See video for reference:
Note: This happens with almost all function deployments, irrespective of the runtime.

https://github.com/appwrite/appwrite/assets/20625965/6c02a84f-c77b-4720-bdb5-400e9ba80628

Steps to reproduce:
1. Deploy a function manually
2. Click on the current deployment's settings (3 dots)
3. Click on `Logs` while the function starts processing, or is in build phase
4. Observe the build logs.

### 👍 Expected behavior

Print correct build log.
Example - 
1. `Error`: Build failed with so and so error.
6. `Ready`: Build successful!

### 👎 Actual Behavior

Build log shows `undefined`.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

`Localhost`.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ItzNotABug thanks for raising this issue! 🙏🏼 Are you deploying multiple functions at the same time?

**Comment by ItzNotABug** [comment]
@stnguyen90 Nope, one at a time.

**Comment by stnguyen90** [comment]
@ItzNotABug, My functions seem to show the logs fine 🧐 

![image](https://github.com/appwrite/appwrite/assets/1477010/da574cc8-bc6e-4cc9-8303-f1cb374c506e)

Do the logs show correctly if you close this and jump back in?

**Comment by dishwasher-detergent** [comment]
I've noticed this happening in my node 18 builds to. I'm on version 1.4.3 Appwrite. I get undefined when I'm monitoring the logs, I can go back after the build is complete and see a full set of the logs, but I cannot watch them live.

**Comment by stnguyen90** [comment]
Ahhh this might be related to realtime or our new live logs feature...

**Comment by MrSurana** [comment]
@stnguyen90 @ItzNotABug 

This change in the console repo is breaking it: https://github.com/appwrite/console/pull/520/files#diff-a8279811be19e4576c1a0ffa5795c00640684661183b0bab085e735a222ea3a7L37-R37

In the websocket payload we get `logs` instead of `buildLogs`

Not sure if it should be fixed in the backend or the console.


Console PR: https://github.com/appwrite/console/pull/520

<img width="559" alt="image" src="https://github.com/appwrite/appwrite/assets/17140551/cff7bf93-a511-49a7-a094-adeea47c8d95">

**Comment by ItzNotABug** [comment]
@stnguyen90 Where should the change be? Console SDK?
I locally tried -
```typescript
logs = message.payload['logs'];
``` 
and it works but there's no apparent `logs` in type `Deployment`.
The `build` table schema uses `logs` so I guess changing that would require a migration.

**Comment by stnguyen90** [comment]
> there's no apparent `logs` in type `Deployment`. The `build` table schema uses `logs` so I guess changing that would require a migration.

The final deployment build logs works fine, right? If so, only the realtime part needs to be updated.

**Comment by ItzNotABug** [comment]
@stnguyen90 You are correct, my bad!
So is it fine to move with using -
```ts
logs = message.payload['logs'];
```

or do you suggest something else?

**Comment by stnguyen90** [comment]
> So is it fine to move with using -
> ```
> logs = message.payload['logs'];
> ```

@ItzNotABug, ya, that's fine!

**Comment by ItzNotABug** [comment]
@stnguyen90 Can I work on this?

**Comment by stnguyen90** [comment]
Assigned!
