### ISSUE TITLE
🐛 Bug Report: Functions Timing Out During Build

### ISSUE THREAD

**Issue by dishwasher-detergent** [appwrite/appwrite#6245]
### 👟 Reproduction steps

Deploy function using Github integration

### 👍 Expected behavior

Function is deployed and usable.

### 👎 Actual Behavior

Function says building for 15 minutes before timing out.

![image](https://github.com/appwrite/appwrite/assets/33816169/6b0c16ca-bf6b-4923-b349-7378256dcdfd)
![image](https://github.com/appwrite/appwrite/assets/33816169/f217d43e-1abf-464c-9645-8b9ad99d802b)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Using Appwrite version 1.4.2 migrated from 1.3.8 -> 1.4.0 -> 1.4.1 -> 1.4.2. 

Self hosted in Digital Ocean 
![image](https://github.com/appwrite/appwrite/assets/33816169/b1b880ad-b089-4a10-8463-e741055a5b17)

GitHub Repo size is 475 MB.

[Discord Support Ticket](https://discord.com/channels/564160730845151244/1151513242074624140)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@dishwasher-detergent thanks for creating this issue! 🙏 to clarify, the repo is 475MB, but the function itself is just a single folder that doesn't use anything else in the repo and is how large?

**Comment by stnguyen90** [comment]
@dishwasher-detergent, also, in the git settings, did you set a Root directory?

<img width="1151" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/d6efe49f-a3e0-4305-a6e3-62ce89fd378c">

**Comment by dishwasher-detergent** [comment]
> @dishwasher-detergent thanks for creating this issue! 🙏 to clarify, the repo is 475MB, but the function itself is just a single folder that doesn't use anything else in the repo and is how large?

Below is the exact code from the function I'm trying to deploy.

```type Context = {
  req: any;
  res: any;
  log: (msg: any) => void;
  error: (msg: any) => void;
};

export default async ({ req, res, log, error }: Context) => {

  return res.send("test");
};
```

**Comment by dishwasher-detergent** [comment]
> @dishwasher-detergent, also, in the git settings, did you set a Root directory?
> <img alt="image" width="1151" src="https://user-images.githubusercontent.com/1477010/268329777-d6efe49f-a3e0-4305-a6e3-62ce89fd378c.png">

Here are my exact git settings
![image](https://github.com/appwrite/appwrite/assets/33816169/287d8c57-0288-4d5f-955a-08b6ad601516)
