### ISSUE TITLE
📚 Documentation: Manual execution JSON example in Cloud Functions is incorrect

### ISSUE THREAD

**Issue by JorensM** [appwrite/appwrite#6247]
### 💭 Description

Currently, in the Cloud Functions JSON example, the example has no quotes

![json-no-quotes](https://github.com/appwrite/appwrite/assets/17122123/7b55e91f-f535-4ab9-b9c1-6792b45b37b2)

As you can see in the image above, the JSON example doesn't have any quotes around the property name.

When I run my function and pass JSON without quotes around property names, I get an error:

![json-no-quotes-err](https://github.com/appwrite/appwrite/assets/17122123/75589d03-bc7a-4d63-9152-4ecf2d560a3b)

But when I run the function with quotes, like so:

![json-with-quotes](https://github.com/appwrite/appwrite/assets/17122123/b4cd3ac9-ede5-4839-a303-39b80aac5f99)

The function executed successfully.

So the JSON example is incorrect and it should show quotes around property names

I'm not sure if this is fixed in the newer versions or if newer versions support JSON without quotes, but in the current version that Cloud is using, I get an error.

 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
This was fixed on later versions, I believe (can confirm for `1.3.8`).
Cloud is soon going to be updated to `1.4x` which will anyway contain the fix.

**Comment by JorensM** [comment]
@ItzNotABug Ok thanks. For clarity, does the fix change the example to have quotes, or does the fix allow you to pass unquoted properties in the payload?

**Comment by ItzNotABug** [comment]
@JorensM 
The example is fixed.
You should always use the standard JSON format with double quotes for sending payloads.

**Comment by JorensM** [comment]
@ItzNotABug Ok, thanks. I will close this now.
