### ISSUE TITLE
🚀 Feature: [Self-Hosted, Console] Allow Changing, Updating T&Cs, Privacy Policies

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6254]
### 🔖 Feature description

Allow using custom or able to change, add T&C, Privacy Policies. I’m not sure on many pages this exists, but I’ve currently seen on Invite Page.

Adding `appwrite.io`’s T&C, Privacy Policy is understanble, but being an Org. on the console & inviting external members we should be able to show our T&C, Privacy Policy.

Maybe add 2 checkboxes like:
- [ ] I agree to `Org`’s T&Cs & Privacy Policy
- [ ] I agree to `appwrite.io`’s T&Cs & Privacy Policy

### 🎤 Pitch

As explained above.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
I hear you! This is a good suggestion! Thanks for bringing it up @ItzNotABug. Will discuss with the team and see what they have to say about it :)

**Comment by eldadfux** [comment]
Closing for now due to inactivity, we can consider this again in the future if proof to be valuable for an enterprise version.
