### ISSUE TITLE
🐛 Bug Report:  Digital Ocean Spaces and Upload a file

### ISSUE THREAD

**Issue by behicsakar** [appwrite/appwrite#6259]
### 👟 Reproduction steps

When i use Digital Ocean Spaces and upload any file i am getting an error when i tried to open uploaded link in digital ocean spaces.

Firstly it uploads private not a public but only manually i can change from digitalocean dashboard.

Secondly even if i make it public, i cant open my file because getting following error.

Thirdly, i cannot get any link from digitalocan spaces, im getting only local link.

`The image "https://************nge.ams3.digitaloceanspaces.com/storage/uploads/app-***************3f32a/****************e49/****************9348.png" cannot be displaved because it contains errors.`

Note: all .env file configured well, i can write Digital Ocean Spaces as well.

### 👍 Expected behavior

It has to work as expected, getting link and i can open link when i will have permission

### 👎 Actual Behavior

All images i can see with my local link.
But in Digital ocean spaces i see thi error message.

`The image "https://************nge.ams3.digitaloceanspaces.com/storage/uploads/app-***************3f32a/****************e49/****************9348.png" cannot be displaved because it contains errors.`

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use oneclick installed appwrite from marketplace of Digital Ocean 

Version 1.3.8
OS Ubuntu 22.04

No Firewall
No security rules
No filters

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@behicsakar, thanks for opening this issue! 🙏 it's expected that the file is private. You should be accessing the file through Appwrite since it may be encrypted and/or compressed.

**Comment by behicsakar** [comment]
@stnguyen90 Yeah, unfortunately it does not work as expected. i upgraded 1.4.2 by manually installing w/ docker container but it still does not work.

It uploads files to DO Spaces. However, i cannot open any file in DO or direct link or anywhere. Image link shows me that it cannot be displaved because it contains errors.

**Comment by stnguyen90** [comment]
@behicsakar How are you uploading the file? Can you see the file in the Appwrite Console?

**Comment by stnguyen90** [comment]
> i cant access a file in digitalocean

@behicsakar, as I mentioned before, this is expected. You should not be accessing the file outside of Appwrite because the file may be compressed and/or encrypted.

**Comment by behicsakar** [comment]
> > i cant access a file in digitalocean
> 
> @behicsakar, as I mentioned before, this is expected. You should not be accessing the file outside of Appwrite because the file may be compressed and/or encrypted.

To clear my mind, i am asking one last thing, then im gonna close this issue.
So, does it mean, the url that appwrite console giving to me, it uses Digital Ocean Spaces and this url fetches data from the DO storage. Is it right ?
