### ISSUE TITLE
🚀 Feature: Appwrite Cloud Bun Support

### ISSUE THREAD

**Issue by tripolskypetr** [appwrite/appwrite#6263]
### 🔖 Feature description

Hello! A week ago I discussed [AppWrite Cloud runtimes outdate issue](https://github.com/appwrite/appwrite/issues/6131). So, could you enable Bun runtime with cloud 1.4 update plz

P.S. I noticed a tweet about [Bun language support](https://twitter.com/appwrite/status/1702965686375530791)

### 🎤 Pitch

Bun runtime is 3x faster then NodeJS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Once Cloud is updated to `1.4x`, Bun will be supported.

**Comment by Haimantika** [comment]
We already have Bun on self-hosted now. For Cloud, the wait might be longer :)

**Comment by tripolskypetr** [comment]
Is there any estimate date for cloud update? Maybe todo list?

**Comment by christyjacob4** [comment]
@tripolskypetr Happy to report that Cloud has now been upgraded to 1.4.3 😄

**Comment by tripolskypetr** [comment]
@christyjacob4 That's great! The modern dark theme in console is amazing. Also I waited for date migration feature for a long time, will try it soon. But It looks like runtime list still not upgraded in the cloud(((
![image](https://github.com/appwrite/appwrite/assets/19227776/dc1ecb96-5402-4382-8643-d1384d3ba058)

**Comment by stnguyen90** [comment]
Bun has now been enabled on Appwrite Cloud:

![image](https://github.com/appwrite/appwrite/assets/1477010/437991b2-fc64-440c-aff9-5d28da35b6e7)
