### ISSUE TITLE
🐛 Bug Report: Create Function Overlay Wrong Color

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6264]
### 👟 Reproduction steps

1. Don't configure git integration
2. Use dark mode on the appwrite console
3. Start to create a function

### 👍 Expected behavior

The overlay is dark

### 👎 Actual Behavior

The overlay is light

![CleanShot_2023-09-16_at_08 56 342x](https://github.com/appwrite/appwrite/assets/1477010/a3f6ff8d-b311-43d5-a74c-48e9bb429f28)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.4.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by KSSaiTeja** [comment]
if the issue still open, i am interested to work on this issue
