### ISSUE TITLE
🐛 Bug Report: Java function created via cli can't be deployed

### ISSUE THREAD

**Issue by sergeycherepanov** [appwrite/appwrite#6274]
### 👟 Reproduction steps

Create new java-17.0 function via cli
```
appwrite init function
``` 
Deploy the function 
```
appwrite deploy function
```
Check the log

### 👍 Expected behavior

Successful build of the function

### 👎 Actual Behavior

Build failes with an error
```
Docker Error: /usr/local/src/src/main/java/io/openruntimes/java/Wrapper.java:8: error: illegal start of type
package io.openruntimes.java.src;
^
/usr/local/src/src/main/java/io/openruntimes/java/Wrapper.java:8: error: <identifier> expected
package io.openruntimes.java.src;
                                ^
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Downloading https://services.gradle.org/distributions/gradle-7.4.1-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.4.1!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava

> Task :compileJava FAILED
1 actionable task: 1 executed
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

`_APP_FUNCTIONS_RUNTIMES=node-16.0,php-8.1,python-3.9,ruby-3.0,java-17.0`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sergeycherepanov** [comment]
As I understand properly the issue in the wrong openruntime docker image version, the used version is v2 but the generated code is for v3.

**Comment by stnguyen90** [comment]
@sergeycherepanov, thanks for raising this issue! 🙏🏼 You noted you're on version 1.4.x of Appwrite. What version exactly? Also, what version of the Appwrite CLI do you have? You can check the version by running `appwrite -v`.

**Comment by sergeycherepanov** [comment]
hi @stnguyen90  I solved this: it was an outdated version of the appwrite server (I updated it from subfolder, the server remained in the old version). After re-deploying the latest version, the issue was resolved. I guess the client always generates the latest version of function implementation. It got me confused because.
