### ISSUE TITLE
📚 Documentation: Function Development Docs has Incorrect Dart Syntax for Environment Variables

### ISSUE THREAD

**Issue by sammichael25** [appwrite/appwrite#6275]
### 💭 Description

The dart example code at the undermentioned sections of [https://appwrite.io/docs/functions-develop#dependencies](https://appwrite.io/docs/functions-develop#dependencies) needs to be updated from process.env.KEY to Platform.environment['KEY']

Sections:

- **Using with API Key**

![image](https://github.com/appwrite/appwrite/assets/25930393/d59d5bff-4a8e-42d0-8607-62cf415206a0)

- **Using JWT**

![image](https://github.com/appwrite/appwrite/assets/25930393/aad3d262-fdf0-4b50-bb2c-759ac55820b9)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Kgkunal** [comment]
I would like to work on this issue , please assign it to me 🙏

**Comment by stnguyen90** [comment]
@Kgkunal, assigned! Thanks for your interest! 🙏🏼

**Comment by stnguyen90** [comment]
@Kgkunal, how's your progress on this?

**Comment by Kgkunal** [comment]
@stnguyen90  Trying to setup locally , almost done. its my first try thats why taking time

**Comment by stnguyen90** [comment]
@Kgkunal, FYI, you won't be able to render it locally as the Appwrite website is what renders that, but that's not open source.

**Comment by stnguyen90** [comment]
@Kgkunal, the docs have been moved to https://github.com/appwrite/website. When do you think you'll be able to submit a PR for the fix?

**Comment by stnguyen90** [comment]
Unassigning due to inactivity
