### ISSUE TITLE
🐛 Bug Report:  Create attributes not working

### ISSUE THREAD

**Issue by gladbhex** [appwrite/appwrite#6276]
### 👟 Reproduction steps

Create attributes through the dashboard and the SDK fails.

### 👍 Expected behavior

Add new attribute without fail

### 👎 Actual Behavior

Adding attributes through the dashboard gives a 'processing' status

![Screenshot 2023-09-18 182002](https://github.com/appwrite/appwrite/assets/61013843/03cd2bd5-6cbf-47f3-a75c-4aed0331fbcb)

Adding attributes with cloud functions using Node.js server SDK gives a timeout error.

![Screenshot 2023-09-18 182221](https://github.com/appwrite/appwrite/assets/61013843/b1cadeb0-5680-4265-9281-4a77c5ce12fb)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Something else

### 🧱 Your Environment

"node-appwrite": "^9.0.0"

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gladbhex, thanks for raising this! 🙏🏼 You may have been running into this because Appwrite Cloud was undergoing maintenance. Are the attributes still processing now?

**Comment by gladbhex** [comment]
> @gladbhex, thanks for raising this! 🙏🏼 You may have been running into this because Appwrite Cloud was undergoing maintenance. Are the attributes still processing now?

Thanks. Working now without issues. Is there a service status page for the cloud?

**Comment by yatharth1706** [comment]
> > @gladbhex, thanks for raising this! 🙏🏼 You may have been running into this because Appwrite Cloud was undergoing maintenance. Are the attributes still processing now?
> 
> Thanks. Working now without issues. Is there a service status page for the cloud?

https://status.appwrite.io/
