### ISSUE TITLE
🐛 Bug Report: Not able to Create Project with Project id not equal to (Contain at most 36 chars. Valid chars are a-z, 0-9, and hyphen. Can't start with a special char.)

### ISSUE THREAD

**Issue by btme0011** [appwrite/appwrite#6279]
### 👟 Reproduction steps

Try to Create a project with project id 123abc456DEf789ghij0klmnopqrs_tuv.wx

### 👍 Expected behavior

Project should be Created.

### 👎 Actual Behavior

GIving exception - ✗ Error Invalid `projectId` param: Project IDs must contain at most 36 chars. Valid chars are a-z, 0-9, and hyphen. Can't start with a special char.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by nick2432** [comment]
I would like to work on this issue , please assign it to me

**Comment by stnguyen90** [comment]
For this, we're going to want to update the [CustomId component](https://github.com/appwrite/console/blob/9b4bcb8140484669421685b4ba89fa1c4d331360/src/lib/components/customId.svelte) to expose a `isProject` flag. If the flag is true, it should use a new InputProjectId rather than [InputId](https://github.com/appwrite/console/blob/9b4bcb8140484669421685b4ba89fa1c4d331360/src/lib/elements/forms/inputId.svelte).

@nick2432, I've assigned the issue to you. Thanks for your interest! 🙏🏼

**Comment by MuskanLudhiyani** [comment]
@stnguyen90 is this still open as I see the PR was closed?

**Comment by stnguyen90** [comment]
@nick2432, are you still working on this?

**Comment by nick2432** [comment]
@stnguyen90  yes

**Comment by Mann-tech13** [comment]
Can I work on this issue, if it's still open? @stnguyen90

**Comment by priii-25** [comment]
assign this to me

**Comment by nick2432** [comment]
Can this issue be labeled as Hacktoberfest?

**Comment by stnguyen90** [comment]
@nick2432, unfortunately, this is a bit small to qualify for the Appwrite Hacktoberfest swag (even with the additional onboarding bugfix).

**Comment by nick2432** [comment]
@stnguyen90 Thanks for the feedback

**Comment by malay5** [comment]
Please assign this issue to me in case it is not picked up/solved @stnguyen90

**Comment by rishidyno** [comment]
I want to work on this issue. If not assigned/solved, please assign this to me.
