### ISSUE TITLE
🐛 Bug Report: Multiple many to one relations in a database fail 

### ISSUE THREAD

**Issue by hinnerkweiler** [appwrite/appwrite#6281]
### 👟 Reproduction steps

Create two Database collections and set a `many to one` or relation for a field from collection `a` to `b`. Now repeat the step for a second field. The second relation can not be created.

Tried this for `many to one` and `many to many`.

Originally raised and discussed this issue on Discord and was asked to file a bug report: https://discord.com/channels/564160730845151244/1152869638431068220

in depth sample: I have a collection `Ports` holding a list of available ports to travel to and from. I also have a collection `Reservations` where the user stores a travel plan. I need to reference `Ports`-Document two times in each `Reservation`, first for departure and than for destination. this seems to not be possible with the current relation management.  

### 👍 Expected behavior

Allow multiple references from one collection to another.

### 👎 Actual Behavior

The Reference is only set up once, more fields fail at creation.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Tried in 1.4.2 and 1.4.3 plain install according docs `docker run...` on Ubuntu 22.04

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by btme0011** [comment]
if ($attribute->getAttribute('type') === self::VAR_RELATIONSHIP
                && \strtolower($attribute->getAttribute('options')['twoWayKey']) === \strtolower($twoWayKey)
                && $attribute->getAttribute('options')['relatedCollection'] === $relatedCollection->getId()
            ) {
                throw new DuplicateException('Related attribute already exists');
            }
            
            As we can see from the code that if these three thing matched we throw DuplicateException. So if type is relationship , collecitonId is same and relatedColleciton id is also same it will throw this DuplicateException

**Comment by btme0011** [comment]
As we can see from the code that if these three thing matched we throw DuplicateException. So if type is relationship , collecitonId is same and relatedColleciton id is also same it will throw this DuplicateException

**Comment by btme0011** [comment]
@stnguyen90 can i work on this issue?

**Comment by stnguyen90** [comment]
@hinnerkweiler, thanks for raising this issue! 🙏🏼 Let me talk to the team about this.

**Comment by stnguyen90** [comment]
This might also apply to one to one relationships.

**Comment by moshOntong-IT** [comment]
any update on this issue?

**Comment by fogelito** [comment]
yes @moshOntong-IT  we are working on a fix for this issue 👍

**Comment by fogelito** [comment]
@hinnerkweiler  @moshOntong-IT 
Until we finish working on this issue, as a work-around  you can set twoWay = true and then you will have the option to set the twoWayKey with a unique name 👍

**Comment by rohankm** [comment]
> @hinnerkweiler @moshOntong-IT Until we finish working on this issue, as a work-around you can set twoWay = true and then you will have the option to set the twoWayKey with a unique name 👍

How to set that?

**Comment by fogelito** [comment]
In the 

> > @hinnerkweiler @moshOntong-IT Until we finish working on this issue, as a work-around you can set twoWay = true and then you will have the option to set the twoWayKey with a unique name 👍
> 
> How to set that?

Create a new Relation Two-way relationship, Since it is not editable, and you will see Attribute Key (related collection) 
You can give it a unique name that will not trigger the error.

**Comment by rohankm** [comment]
> > > @hinnerkweiler @moshOntong-IT Until we finish working on this issue, as a work-around you can set twoWay = true and then you will have the option to set the twoWayKey with a unique name 👍
> > 
> > 
> > How to set that?
> 
> Create a new Relation Two-way relationship, Since it is not editable, and you will see Attribute Key (related collection) You can give it a unique name that will not trigger the error.

Im still getting the error...

first relation ![Screenshot 2023-11-02 at 9 06 43 PM](https://github.com/appwrite/appwrite/assets/23615452/3fe3afe2-9aff-4107-873b-19cbe3477f4e)

2nd relation 
![Screenshot 2023-11-02 at 9 07 15 PM](https://github.com/appwrite/appwrite/assets/23615452/3bb36d2e-c34e-4824-bb90-e7485f20f2c2)

**Comment by fogelito** [comment]
With a OneToOne / OneToMany, it was working.
Looking At your screenshot , I tried out ManyToMany, and it seems to have a problem 👍 
We will look into this more deeply with our team

**Comment by DanielRiveraHQ** [comment]
Hey @stnguyen90 ,

I tried to create the following relationships combinations in the same document and between another document, and the second one is not going through.

![CleanShot 2024-05-18 at 19 40 36@2x](https://github.com/appwrite/appwrite/assets/20131939/8fe27e7f-332e-44b3-af63-e3837b0a2b72)

![CleanShot 2024-05-18 at 19 39 50@2x](https://github.com/appwrite/appwrite/assets/20131939/c3729e1e-9e54-441a-8ca5-c002f5f011ce)

**Comment by stnguyen90** [comment]
@DanielRiveraHQ, you can try again when 1.5.6 is released in the next week or so.

**Comment by DanielRiveraHQ** [comment]
Great, thank you @stnguyen90

**Comment by DanielRiveraHQ** [comment]
@stnguyen90, just to report, it is working now; thank you again.
