### ISSUE TITLE
🐛 Bug Report: Gettting 500 Internal Server Error When Accessing Database in from Appwrite console.

### ISSUE THREAD

**Issue by iamjunedkhan** [appwrite/appwrite#6284]
### 👟 Reproduction steps

When I accessed the documents, after loading some time I got the **AppwriteException: Network request failed**, I didn't understand the reason for the same because when I was accessing it before some time it was working fine 

![error](https://github.com/appwrite/appwrite/assets/70875186/ea96ac1f-90fa-4aae-8b28-84a30b897110)

### 👍 Expected behavior

It should show all the documents correctly

### 👎 Actual Behavior

but it actually throw an **AppwriteException: Network request failed**

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by akiif** [comment]
I'm also facing the same issues. Even the client api calls also throw a network error. And even when I try to create a new project it throws the server error. Im using the appwrite cloud console.
![image](https://github.com/appwrite/appwrite/assets/55696148/fb55b5a5-2210-4833-9fb4-da5f5f084655)

**Comment by btme0011** [comment]
Appwrite Cloud is under maintance. Appwrite team is working on the fix. It will be back soon
