### ISSUE TITLE
🚀 Feature: Change order of collection attributes on web UI

### ISSUE THREAD

**Issue by Schrolli91** [appwrite/appwrite#6286]
### 🔖 Feature description

For better overview it would be nice, if i can order the attributes of an collection in the backend web ui.

![image](https://github.com/appwrite/appwrite/assets/6043382/d90ac202-4e32-47b0-ad65-69729a5fc239)

### 🎤 Pitch

It will gain a lot more overview. Especially for collections with a lot of attributes.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Schrolli91, thanks for raising this issue! 🙏🏼 Related issue: https://github.com/appwrite/appwrite/issues/2787

**Comment by r0nz-29** [comment]
@stnguyen90  can I work on this?

**Comment by stnguyen90** [comment]
@r0nz-29, thanks but our design team will need to be involved in this. I would suggest looking for issues labeled https://github.com/appwrite/appwrite/labels/good%20first%20issue or https://github.com/appwrite/appwrite/labels/help%20wanted.

**Comment by nikhil-swamix** [comment]
Any update? it is a blocker for me, in early stages a lot of attributes would be CRUDed, and order is important as you cant have name changes to fullname, and its added somewhere in last, and migrations will be difficult.
