### ISSUE TITLE
🐛 Bug Report: Not able to Edit Attributes in the database.

### ISSUE THREAD

**Issue by btme0011** [appwrite/appwrite#6287]
### 👟 Reproduction steps

1) Create a Collection in database and Add Some Attributte
2) After Creating Collection go to the attribute section 
3) Click on the Right Side three dots
4) Go to edit option
5) Try to edit any attribute

### 👍 Expected behavior

Attribute should be updated

### 👎 Actual Behavior

Not able to update attribute

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ManishDait** [comment]
I would like to work on these issue.

**Comment by Haimantika** [comment]
Good catch @btme0011. Let me take this to the team!

**Comment by henrychea** [comment]
Hi all, has there been any updates for this issue

**Comment by Haimantika** [comment]
@btme0011 @henrychea You can only edit the required field or the default field (if required is not selected)

**Comment by henrychea** [comment]
@Haimantika would it be possible update a attribute that is no longer used or needs to be renamed? For example bookId -> old_bookId, I understand that attribute data type is a very complex to change but is it also true for renaming?

**Comment by Haimantika** [comment]
> @Haimantika would it be possible update a attribute that is no longer used or needs to be renamed? For example bookId -> old_bookId, I understand that attribute data type is a very complex to change but is it also true for renaming?

Yes, we do not allow it

**Comment by stnguyen90** [comment]
We don't allow updating attributes because changes like that on the collection can lock the collection and cause downtime. 

For now, I would recommend following typical recommended approaches to updating databases. This might give you some insight: https://teamplify.com/blog/zero-downtime-DB-migrations/.

**Comment by eldadfux** [comment]
We have recently added new options to update existing attributes. Thanks for raising this issue. ![Image](https://github.com/user-attachments/assets/6c26ac65-560e-4be2-9015-8b9e6c2a93ac)
