### ISSUE TITLE
🐛 Bug Report: Deleting deployment does not work for VCS deployments

### ISSUE THREAD

**Issue by JoshiJoshiJoshi** [appwrite/appwrite#6289]
### 👟 Reproduction steps

1. Setup S3 Storage (Digital Ocean Spaces)
2. Deploy any function
3. Go to that function and delete any deployments
4. Deployment does not get deleted

Logs from worker-deletes:
<img width="1312" alt="Screenshot 2023-09-21 at 03 17 20@2x" src="https://github.com/appwrite/appwrite/assets/49132782/7350fc4c-0158-4896-b45f-bc364be977cd">

### 👍 Expected behavior

Delete that specific deployment from storage

### 👎 Actual Behavior

It actually does not delete it

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Version 1.4.3 Self hosted

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@JoshiJoshiJoshi, thanks for creating this issue! 🙏🏼 It looks like the deployment path is empty for VCS deployments and so the delete throws an exception and then doesn't finish deleting the build.
