### ISSUE TITLE
🚀 Feature: Relating document to a user

### ISSUE THREAD

**Issue by jijkbird** [appwrite/appwrite#6306]
### 👟 Reproduction steps

Create a new collection, add fields, select foreign keys, and do not display the user's collection

### 👍 Expected behavior

Display user collection and associate user id

### 👎 Actual Behavior

Unable to display user collection

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.4.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@jijkbird, thanks for raising this issue! 🙏🏼 Are you trying to create a relationship attribute so that you can relate to a user?

**Comment by jijkbird** [comment]
@stnguyen90   yes

**Comment by stnguyen90** [comment]
@jijkbird, thanks for the clarification! This is currently the expected behavior. Users are not accessible via client SDKs since there may be a lot of sensitive data. We recommend creating a collection so that you can configure the data available, permissions, or even add additional attributes.

**Comment by jijkbird** [comment]
@stnguyen90  Are there any examples of creating user additional information tables that I want to automatically generate when a user is created and delete when a user is deleted? Are there any relevant examples available?

**Comment by stnguyen90** [comment]
You can create an [Appwrite Function](https://appwrite.io/docs/functions) to automatically create, update, or delete the document. I'm doing something similar [here](https://github.com/stnguyen90/places/blob/main/appwrite-functions/create-user/src/index.ts). If you want to handle updates and deletes, you'll have to configure your function to trigger on additional user [events](https://appwrite.io/docs/functions-execute#events). Then, your function can check which event it is and perform the necessary action.

**Comment by Megamannen** [comment]
I'm currently having a collection named `users` that has  the same ID as the user.
I also have document security turned on and restricted reading and writing to the user in question.
