### ISSUE TITLE
🚀 Feature: Uniqueness of Database Fields

### ISSUE THREAD

**Issue by jijkbird** [appwrite/appwrite#6320]
### 🔖 Feature description

In relational databases, the unique performance of fields avoids many errors

### 🎤 Pitch

In relational databases, the unique performance of fields avoids many errors

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@jijkbird, thanks for raising this issue! 🙏🏼 Would you please provide more details about what you're trying to do?

**Comment by jijkbird** [comment]
The data in the field cannot be duplicated, @stnguyen90  like PRIMARY KEY

**Comment by stnguyen90** [comment]
@jijkbird, sounds like the same as https://github.com/appwrite/appwrite/issues/5400. Please add a 👍🏼 to that issue to express your interest.
