### ISSUE TITLE
🐛 Bug Report: OAuth Login invalid success

### ISSUE THREAD

**Issue by gaurav-chandra** [appwrite/appwrite#6322]
### 👟 Reproduction steps

1. self-host v1.4.3
2. add a web platform
3. under hostname field, either put * or *.domain.com
4. under auth enable google and add all api keys for google
5. add a login with google button and call ```sdk.createOAuth2Session('google', success_url, error_url)```
6. for success_url = https://testing.domain.com
7. upload the code to testing subdomain
8. try the flow with google login

### 👍 Expected behavior

it should login and have success as the hostname is either * or *.domain.com

### 👎 Actual Behavior

appwrite shows an error:
<img width="775" alt="image" src="https://github.com/appwrite/appwrite/assets/3168243/72f3f6c8-5a51-4e94-8ac8-aede1ec6738c">

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

ubuntu v20 and appwrite v1.4.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gaurav-chandra** [comment]
I should add that if I hardcode the testing.domain.com in hostname field, it works but I cannot use a wildcard sub domain.

**Comment by btme0011** [comment]
I think this issue is common with all the OAuth services.

**Comment by gaurav-chandra** [comment]
No, the issue was not there in v1.3.7 and v1.3.8. I could use wildcard sub domain. It has started happening when I upgraded to v1.4.1

**Comment by stnguyen90** [comment]
@gaurav-chandra, thanks for raising this issue! 🙏🏼 

> No, the issue was not there in v1.3.7 and v1.3.8. I could use wildcard sub domain. It has started happening when I upgraded to v1.4.1

Are you sure you didn't have an additional web platform before?

I'm looking at the validation between [1.3.8](https://github.com/utopia-php/framework/blob/0.28.4/src/Validator/Host.php) and [1.4.3](https://github.com/utopia-php/framework/blob/0.31.0/src/Validator/Host.php) and they seem to be the same. 

I also tried testing on 1.3.8, but got the same error:

<img width="1143" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/4cba5c5c-b647-4d6f-81f0-f57c9bf548b4">

That said, I'll bring this up to the team.

**Comment by gaurav-chandra** [comment]
hey @stnguyen90 thanks for taking this up. Now that you mention it, I am wrong about v1.3.8. I realised that I was testing on localhost and it always works on localhost.

**Comment by PtradeLLC** [comment]
Great that this was discussed and closed. However, noone seem to talk about how it was solved so that others don't have the same issue.

**Comment by Marius555** [comment]
i dont understand how tis issue is closed, did anybody find solution to this???? i have the same problem: Invalid `success` param: URL host must be one of: localhost, cloud.appwrite.io, appwrite.io, *, how to solve it, i put * on hostname on web, but that didnt do anything...

**Comment by jiayouchongmingniao** [comment]
same error, self-host v1.6

**Comment by mahitechnologies259** [comment]
What I did for android app, sort of a custom solution, is I removed success parameter.
If Social Login is successful, awaited 1 second, and launch deep link url myself for the page.

Code for my flutter app, if it helps anyone:

        await _account.createOAuth2Session(
          provider: OAuthProvider.google,
        );
        await Future.delayed(const Duration(seconds: 1));
        final Uri url =
            Uri.parse(deep_link_custom_url_for_the_app);
        await launchUrl(url)
