### ISSUE TITLE
🚀 Feature: A Way to Check if the Error is Appwrite Exception

### ISSUE THREAD

**Issue by thevinitgupta** [appwrite/appwrite#6324]
### 🔖 Feature description

Just like Firebase provides the functionality to check if the `error` comes from Firebase side, Appwrite should have a method or function to check if the error in the `catch` block is an `AppwriteException`. 

### 🎤 Pitch

A response from Appwrite has a name property that specifies : `AppwriteException` but a direct checker would be nice to have. It would enhance the Developer Experience

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Can't we manually do that?
```kotlin
try {
    // appwrite operation
} catch (exception: AppwriteException) {
    // appwrite exception, do what you want here 
} catch (exception: Exception) {
    // other generic exceptions
}
```

**Comment by stnguyen90** [comment]
@thevinitgupta, thanks for raising this issue! 🙏🏼 Would you please provide more detail about what kind of exception you're trying to capture?

**Comment by iamabhiCH** [comment]
Hello, @thevinitgupta I want to check this issue and fix this issue. Please assign this task to me.

**Comment by eldadfux** [comment]
As @ItzNotABu mentioned, you can check for the Appwrite exception. If the status code is 500 its is most likely an Appwrite error, anything else is most likely in your request input or account status (blocked, payment, budget cap, etc)
