### ISSUE TITLE
🐛 Bug Report: Migrating from Cloud to Self-Hosted Doesn't Work

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6336]
### 👟 Reproduction steps

1. Go to a project on Appwrite Cloud
2. Click on Settings
3. Click on Migrations
4. Click on Export data
5. Click on Create a new project
6. Fill in a Project name
7. Click Next
8. Click Select all
9. Click Create

### 👍 Expected behavior

Migration starts

### 👎 Actual Behavior

Nothing happens

Related Discord thread: https://discord.com/channels/564160730845151244/1154656704231899176

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

I tested migrating from Cloud to Appwrite 1.4.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
As a workaround for now, you can go to your self-hosted instance of Appwrite and import data from Appwrite Cloud.

**Comment by versun** [comment]
> As a workaround for now, you can go to your self-hosted instance of Appwrite and import data from Appwrite Cloud.

For small project,  import data from Appwrite Cloud will be successful, but for large project, same errors will occur after a while.

**Comment by Tomic-Riedel** [comment]
I agree to @versun . It's not even big projects, it's for medium-sized too. I have 1 db with 6 collections, 3 storage buckets and 5 functions and migration is not working correctly.

**Comment by stnguyen90** [comment]
@Tomic-Riedel, @versun, it might be best to create a support post on [Discord](https://appwrite.io/discord) so we can discuss your problems further.
