### ISSUE TITLE
🐛 Bug Report: unable create or search storage file when filename include symbol

### ISSUE THREAD

**Issue by versun** [appwrite/appwrite#6337]
### 👟 Reproduction steps

get 500 error when a symbol is used in the filename to create or search a file
symbols : ~ <  >  @  %  *  (  )  -  + 

![image](https://github.com/appwrite/appwrite/assets/2398708/f1676071-76c3-4714-ad38-aedcbc8c574d)

![image](https://github.com/appwrite/appwrite/assets/2398708/10821a22-a9e1-4f37-aef0-16f6728fba73)

### 👍 Expected behavior

NA

### 👎 Actual Behavior

NA

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@versun thanks for raising this issue! 🙏🏼 

I tested this locally and noticed this error in the appwrite logs:

```
appwrite  | [Error] Timestamp: 2023-09-27T00:56:29+00:00
appwrite  | [Error] Method: GET
appwrite  | [Error] URL: /v1/users
appwrite  | [Error] Type: PDOException
appwrite  | [Error] Message: syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*'
appwrite  | [Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
appwrite  | [Error] Line: 62
```

I'll bring this up to the team.
