### ISSUE TITLE
🐛 Bug Report: Auth search is failing intermittently on console.

### ISSUE THREAD

**Issue by ashishdawale20** [appwrite/appwrite#6338]
### 👟 Reproduction steps

login to console, select project and go to Auth.
In the search text box  type the email address you want to search.

### 👍 Expected behavior

It should search the user with provided email address.

### 👎 Actual Behavior

It is not able to filter the user, screen get refreshed on key press but it is not filtering the correct user.
![image](https://github.com/appwrite/appwrite/assets/43884208/fd162fdb-c397-415e-a278-e40a881a7d06)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Our appwrite is hosted on digitalocean

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ashishdawale20** [comment]
My bad - it seems that it is already fixed in 1.4.3 - I am on 1.4.2
https://github.com/appwrite/console/pull/537

**Comment by stnguyen90** [comment]
@ashishdawale20 

> My bad - it seems that it is already fixed in 1.4.3 - I am on 1.4.2 [appwrite/console#537](https://github.com/appwrite/console/pull/537)

No, I don't think that issue is related to your problem.

I think you're seeing all users with "gmail" in their email as expected. To understand how the search works, see https://github.com/appwrite/appwrite/discussions/5005.

**Comment by aakashraj01** [comment]
@stnguyen90 If this issue is still not solved . Can you please assign me . I will look into it and solve this bug asap :)

**Comment by vhaashtechnologies** [comment]
After upgrading to 1.4.3 i don't see that problem.

**Comment by ashishdawale20** [comment]
after migrating to the 1.4.3 i dont see this issue, i am closing this.
