### ISSUE TITLE
🐛 Bug Report: Query.seach with 2letter

### ISSUE THREAD

**Issue by behicsakar** [appwrite/appwrite#6339]
### 👟 Reproduction steps

Create an atribute `string[]` with stringArray. 
Add some values like `['en', 'es', 'ar', 'tr']`

`Query.search('stringArray', 'en')`

It returns empty object.

What if i change the values with `['eng', 'esp', 'arb', 'tur']`
`Query.search('stringArray', 'eng')`

It returns related document.

I am not sure its a bug or limitation but when i am trying to search in array of  which contains only 2 letter such as country code/language code, search doesnt meet my desired output.

### 👍 Expected behavior

`Query.search('stringArray', 'en')`

It has to return related object(s).

### 👎 Actual Behavior

`Query.search('stringArray', 'en')`

It returns empty object.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Self-hosted appwrite 1.4.x in linux.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by MuskanLudhiyani** [comment]
Was able to reproduce the issue.
Will like to work on this.

**Comment by behicsakar** [comment]
Hello, @stnguyen90 
Please assign this issue to @MuskanLudhiyani of course if you dont mind.

**Comment by stnguyen90** [comment]
@behicsakar, thanks for raising this issue! 🙏🏼 A couple comments:

1. Searching on an array as you are doing is a hack that is unsupported. You should 👍🏼 [this](https://github.com/appwrite/appwrite/issues/2838) issue for adding support for array operations.
2. Words less than 3 characters are ignored by the full text index. To better understand how search works, see https://github.com/appwrite/appwrite/discussions/5005

**Comment by behicsakar** [comment]
This is an obvious answer : https://github.com/appwrite/appwrite/discussions/5005#discussioncomment-4681079
Big Thanks!
