### ISSUE TITLE
🚀 Feature: Add feature for getting data between specific date and time?

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [appwrite/appwrite#6340]
### 🔖 Feature description

I was trying to fetch data between time like this:
              `Query.greaterThanEqual('date_time', specifiDate),
              Query.lessThanEqual('date_time', new Date()),`
      but getting error like:
      Error: [AppwriteException: Server Error]
      Please add this feature as fast as possible please.

### 🎤 Pitch

Firebase offers this feature like:
`.where('date_time', '>=', specifiDate)
 .where('date_time', '<=', new Date())`
 
It will be very useful for users to find any items or posts between or before/after an specific time
Thanks

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by SMARTMICROWORLD** [comment]
> There is a query method named `between` due to [docs.](https://appwrite.io/docs/queries) However, it accepts only `number` or `string`. That is why there is an opened issue to add feature `float`and `datetime` to `Query.between` method.
> 
> <img alt="Screenshot 2023-09-27 at 19 45 46" width="755" src="https://user-images.githubusercontent.com/3280475/271054748-f5a3c040-0eb0-4f7f-a4e6-8a1a913bd7a4.png">
> Related issue: #5650 Related comment : [#5650 (comment)](https://github.com/appwrite/appwrite/issues/5650#issuecomment-1736915331)
> 
> I could not use `between`method for the same query with `datetime` so i solve my problem like that
> 
> ```ts
>     const queries: any[] = [];
> 
>     // Query for users with birthdates between the selected min and max ages
>     if (filterData?.minAge && filterData?.maxAge) {
>       const minDate = new Date();
>       minDate.setFullYear(minDate.getFullYear() - filterData?.maxAge);
>       const maxDate = new Date();
>       maxDate.setFullYear(maxDate.getFullYear() - filterData?.minAge);
> 
>       queries.push(Query.greaterThanEqual('birthdate', minDate.toISOString()));
>       queries.push(Query.lessThanEqual('birthdate', maxDate.toISOString()));
>     }
> 
> ...
> 
>     this.appwrite.listDocuments(
>       environment.appwrite.USERS_COLLECTION,
>       queries
>     );
> ```

What if I want to fetch posts between 1 week, 1 month or a year?
Beacuse I have leader board screen where I am counting each user's posts between a week, months or a year, based on numbers I am ranking them.

**Comment by stnguyen90** [comment]
@SMARTMICROWORLD, dates are ISO 8601 formatted strings in UTC timezone (like `2011-10-05T14:48:00.000Z`). You can build a greater than and less than query that filters for any range you want.

**Comment by rakesh-venkata** [comment]
Hey,Is this issue still open.I like to work on it.
