### ISSUE TITLE
🚀 Feature: Add google authentication feature for react native apps

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [appwrite/appwrite#6341]
### 🔖 Feature description

I was going to migrate my database from firebase to appwrite but I was unable to authenticate users like firebase google-signin.

### 🎤 Pitch

It is very useful for us react native app developers and also for appwrite platform because in this fast lifestyle no one want to fill the forms to register in an app. So implementing this feature will be booster dose for Appwrite.
Thanks

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@SMARTMICROWORLD, thanks for raising this issue! 🙏🏼 Appwrite supports dozens of [OAuth2](https://appwrite.io/docs/authentication-oauth) providers including Google: 

<img width="1445" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/559224c6-d76d-4ca8-9a29-8e175184ac63">

The only problem right now is the [Appwrite web sdk](https://github.com/appwrite/sdk-for-web) uses [`window.location.href`](https://github.com/appwrite/sdk-for-web/blob/ca4ef6dd0f8d7110db57f8b3b295ce62e629eec5/src/services/account.ts#L729-L733) to redirect the user to the OAuth2 provider to authenticate, but I don't think [React Native supports](https://github.com/appwrite/sdk-for-web/issues/41) that. So, as a workaround, you can manually build the URL yourself just like the SDK does and then send the user to that URL with whatever way React Native supports. Just make sure to set a success and failure URL that will redirect the user back into the app.

**Comment by SMARTMICROWORLD** [comment]
> @SMARTMICROWORLD, thanks for raising this issue! 🙏🏼 Appwrite supports dozens of [OAuth2](https://appwrite.io/docs/authentication-oauth) providers including Google:
> 
> <img alt="image" width="1445" src="https://user-images.githubusercontent.com/1477010/271111577-559224c6-d76d-4ca8-9a29-8e175184ac63.png">
> The only problem right now is the [Appwrite web sdk](https://github.com/appwrite/sdk-for-web) uses [`window.location.href`](https://github.com/appwrite/sdk-for-web/blob/ca4ef6dd0f8d7110db57f8b3b295ce62e629eec5/src/services/account.ts#L729-L733) to redirect the user to the OAuth2 provider to authenticate, but I don't think [React Native supports](https://github.com/appwrite/sdk-for-web/issues/41) that. So, as a workaround, you can manually build the URL yourself just like the SDK does and then send the user to that URL with whatever way React Native supports. Just make sure to set a success and failure URL that will redirect the user back into the app.

But again login to social accounts is boring and time consuming for users, It should be as much simple as firebase authentication. BTW thanks 👍

**Comment by SMARTMICROWORLD** [comment]
> @SMARTMICROWORLD, thanks for raising this issue! 🙏🏼 Appwrite supports dozens of [OAuth2](https://appwrite.io/docs/authentication-oauth) providers including Google:
> 
> <img alt="image" width="1445" src="https://user-images.githubusercontent.com/1477010/271111577-559224c6-d76d-4ca8-9a29-8e175184ac63.png">
> The only problem right now is the [Appwrite web sdk](https://github.com/appwrite/sdk-for-web) uses [`window.location.href`](https://github.com/appwrite/sdk-for-web/blob/ca4ef6dd0f8d7110db57f8b3b295ce62e629eec5/src/services/account.ts#L729-L733) to redirect the user to the OAuth2 provider to authenticate, but I don't think [React Native supports](https://github.com/appwrite/sdk-for-web/issues/41) that. So, as a workaround, you can manually build the URL yourself just like the SDK does and then send the user to that URL with whatever way React Native supports. Just make sure to set a success and failure URL that will redirect the user back into the app.

I am little bit confused also new in react native authentication, If you can provide me some code then it will be very helpful for me. 👍

**Comment by SMARTMICROWORLD** [comment]
> @SMARTMICROWORLD, thanks for raising this issue! 🙏🏼 Appwrite supports dozens of [OAuth2](https://appwrite.io/docs/authentication-oauth) providers including Google:
> 
> <img alt="image" width="1445" src="https://user-images.githubusercontent.com/1477010/271111577-559224c6-d76d-4ca8-9a29-8e175184ac63.png">
> The only problem right now is the [Appwrite web sdk](https://github.com/appwrite/sdk-for-web) uses [`window.location.href`](https://github.com/appwrite/sdk-for-web/blob/ca4ef6dd0f8d7110db57f8b3b295ce62e629eec5/src/services/account.ts#L729-L733) to redirect the user to the OAuth2 provider to authenticate, but I don't think [React Native supports](https://github.com/appwrite/sdk-for-web/issues/41) that. So, as a workaround, you can manually build the URL yourself just like the SDK does and then send the user to that URL with whatever way React Native supports. Just make sure to set a success and failure URL that will redirect the user back into the app.

I am getting error:
![WhatsApp Image 2023-10-02 at 9 34 26 AM](https://github.com/appwrite/appwrite/assets/25653690/623ab7ba-60d9-4046-8a4f-4b71802d741b)

**Comment by SMARTMICROWORLD** [comment]
> @SMARTMICROWORLD, thanks for raising this issue! 🙏🏼 Appwrite supports dozens of [OAuth2](https://appwrite.io/docs/authentication-oauth) providers including Google:
> 
> <img alt="image" width="1445" src="https://user-images.githubusercontent.com/1477010/271111577-559224c6-d76d-4ca8-9a29-8e175184ac63.png">
> The only problem right now is the [Appwrite web sdk](https://github.com/appwrite/sdk-for-web) uses [`window.location.href`](https://github.com/appwrite/sdk-for-web/blob/ca4ef6dd0f8d7110db57f8b3b295ce62e629eec5/src/services/account.ts#L729-L733) to redirect the user to the OAuth2 provider to authenticate, but I don't think [React Native supports](https://github.com/appwrite/sdk-for-web/issues/41) that. So, as a workaround, you can manually build the URL yourself just like the SDK does and then send the user to that URL with whatever way React Native supports. Just make sure to set a success and failure URL that will redirect the user back into the app.

reply me bro plzz

**Comment by rayanfer32** [comment]
Is Oauth2 Possible just with REST API's exposed by appwrite ?

**Comment by stnguyen90** [comment]
> I am getting error

@SMARTMICROWORLD, what are you doing that results in that error?

**Comment by stnguyen90** [comment]
I'm pretty sure native login should work now using [custom tokens](https://appwrite.io/docs/products/auth/custom-token).
