### ISSUE TITLE
🚀 Feature:  Permission Extension (Extend the Permission logic)

### ISSUE THREAD

**Issue by moshOntong-IT** [appwrite/appwrite#6361]
### 🔖 Feature description

Currently, there is a indeed limitation on setting a Permission on particular features such as collection/documents, functions and etc. We are set up a permission that is based on Roles, Teams, or User label.

### 🎤 Pitch

In this case, I would like to pitching that what if we are going to create a Permission extension. It is something like cloud function, it able us to extend the backend of the appwrite, that has not been implemented in the appwrite. That is why the cloud function exist in appwrite. How about in Permission, what if we have this too. In firebase, they have security rules to create a logic and they have their own template or format. But in this pitching we are going to use any programming language, so that the developer will not have additional study it is better that they are already familiar the template or format: for example in dart:

```
bool start(context){
   /// The context here is similar to the cloud function it contains information, but in this case we will have the user ID who are trying to read this document, or who have been try to trigger this function.
   
  final client = Client()
  .setEndpoint('https://cloud.appwrite.io/v1') // Your API Endpoint
  .setProject('[PROJECT_ID]') // Your project ID
  .setKey([API_KEY]);

  final databases =Datatabases(client);
  final result = await databases.listDocuments(
    databaseId: '[DATABASE_ID]',
    collectionId: '[COLLECTION_ID]',
    queries: [
        Query.limit(context.body["userID"]),
    ];

   if(result.isNotEmpty){
     return true;
   }
   return false;
}
```
When it returns true and then it will have permission, otherwise they are unaothirzed. This pitching will also have huge benefit when we are going to store a user and expiration date in the collection and then We can use this permission extension to determine if the user is still have time to have permission to read,write,update or delete on this particular document, collection or function. Now we can now deploy this permission extension to our console, it will now display the id of this Permission. We can use this ID to the Permission fill up. For example this one
<img width="351" alt="image" src="https://github.com/appwrite/appwrite/assets/57244338/6e951b8d-8f80-4fd1-b1fd-fffe95b5951f">

`permission:[PERMISSION_EXTENSION_ID]`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This sounds like one of these:

1. https://github.com/appwrite/appwrite/issues/2358
2. https://github.com/appwrite/appwrite/issues/5974

Maybe you can comment and 👍 one of those?
