### ISSUE TITLE
📚 Documentation: Files missing from manual installation docs

### ISSUE THREAD

**Issue by alpap** [appwrite/appwrite#6367]
### 💭 Description

[docker-compose.yml](https://appwrite.io/install/compose) not pointing to the right location 
content missing 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ankitkumar748846** [comment]
Can I work on this issue

**Comment by suleimanas** [comment]
@eldadfux @stnguyen90 docker-compose and env links not found!
https://appwrite.io/install/compose
https://appwrite.io/install/env

even in self-hosting docs under Manual not linked

**Comment by stnguyen90** [comment]
@alpap, thanks for raising this issue! 🙏🏼 We need to figure out how to get this working on our new website. For now, it would be best to use the [automatic Docker install](https://appwrite.io/docs/advanced/self-hosting#install-with-docker).

**Comment by stnguyen90** [comment]
@fatherofinvention, the best way to self-host is to [install with Docker](https://appwrite.io/docs/advanced/self-hosting#install-with-docker) which generates a docker-compose.yml and .env file for you.

**Comment by zdanl** [comment]
I tested the Cloud for a Coinbase.com scale project. I need to be in control of rate limitation and abuse limits, have low-level access to the containerized infrastructure and need to introduce features that were heavily discussed but won't be adopted or prioritized for @appwrite internal reasons.

Proper self-hosting needed.
