### ISSUE TITLE
📚 Documentation: Inconsistent bandwidth on Pricing page

### ISSUE THREAD

**Issue by versun** [appwrite/appwrite#6368]
### 💭 Description

I think it's a  typo
![2023-09-30](https://github.com/appwrite/appwrite/assets/2398708/e24cf1f3-ad82-45cd-b891-c0a9685a1f96)
![2023-09-30](https://github.com/appwrite/appwrite/assets/2398708/463c68b0-fc5b-40d6-85a4-e1601c3f6b79)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by aakashraj01** [comment]
Hey @stnguyen90 . Can you please assign me this issue ? I will fix it immediately :)

**Comment by stnguyen90** [comment]
@aakashraj01, sure please update it to 10GB 🙏

**Comment by sitamgithub-MSIT** [comment]
@stnguyen90 hey! can you tell me if this issue is still under work or not? So, that I can make contributions to it!

**Comment by stnguyen90** [comment]
@aakashraj01, how's your progress on this? Please be advised I'll have to unassign you due to inactivity soon.

**Comment by aakashraj01** [comment]
I will raise the PR for this by today . Issue is solved , just need to raise the PR :) . Will do it today

**Comment by aakashraj01** [comment]
@stnguyen90 Hey , I have solved this issue . Can you please review the PR :)
