### ISSUE TITLE
Appwrite sdk - android

### ISSUE THREAD

**Issue by root-ansh** [appwrite/appwrite#64]
Hi mobile app dev here.   

When i check appwrite.io , i couldn't find any docs for Android SDK . I wanted to contribute by adding tutorials and getting started by reading the code, but to me, it looks like there isn't the libraries/sdks available for android.  

Is this a case? If not, can you point me to some android code which could be used for implementing a server via this sdk for a sample mobile app?

**Comment by eldadfux** [comment]
Hey @root-ansh, All Appwrite SDKs are auto-generated using our [SDK Generator](https://github.com/appwrite/sdk-generator) project. We are looking for help creating new Kotlin templates for the SDK.

Actually, we have have an issue open exactly for this:
https://github.com/appwrite/sdk-generator/issues/5

Please take note that we might need a little extra help in this issue with creating a matching documentation to help users get started with the Android SDK.

The issue itself has an up-to-date step by step guide for adding support for new languages. If you wish to help with it, you could also contact me on Gitter for help and guidance.

Let me know what you think.

**Comment by alistairholmes** [comment]
Hi I'm also a mobile app dev and I was also wanting to try out AppWrite for android and didn't find an SDK, I'll contact you on gitter for some guidance :wink:

**Comment by root-ansh** [comment]
Sure, will contact you on gitter.
