### ISSUE TITLE
📚 Documentation: [Functions] Wrong Info. on Environment Variables

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6417]
### 💭 Description

The docs state below for accessing env. variables - 
```js
export default async ({ req, res, log }) => {
    return res.send(({}).MY_VAR);
}
```
Also - 
```js
const client = new Client()
      .setEndpoint('https://cloud.appwrite.io/v1')
      .setProject(({}).APPWRITE_FUNCTION_PROJECT_ID)
      .setKey(({}).APPWRITE_API_KEY);
```

Shouldn't it be `process.env.*`? Or is this something new?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Yasir761** [comment]
@ItzNotABug Yeah, it should be process.env. , Can I resolve this issue, if you are not working on this?

**Comment by Yasir761** [comment]
> @ItzNotABug Yeah, it should be process.env. , Can I resolve this issue, if you are not working on this?

Can you please elaborate more?

**Comment by asi309** [comment]
Hi,
Can I work on this issue?

**Comment by stnguyen90** [comment]
@ItzNotABug where exactly do you see this?

**Comment by ItzNotABug** [comment]
@stnguyen90 Here: https://appwrite.io/docs/products/functions/development#project-variables

**Comment by stnguyen90** [comment]
@ItzNotABug, these look fine to me now...

<img width="728" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/541358c5-6701-4016-9396-e945389b271e">

<img width="707" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/7f3f612e-a54c-4148-8825-5792b3268863">

Do you still see it after clearing your cache?

**Comment by ItzNotABug** [comment]
@stnguyen90 Seems to be working fine now. Closing!

**Comment by LDY681** [comment]
@stnguyen90 I also found this issue here https://appwrite.io/docs/products/functions/examples
