### ISSUE TITLE
🐛 Bug Report: Unable to delete collection's attribute

### ISSUE THREAD

**Issue by Giuliano1993** [appwrite/appwrite#6418]
### 👟 Reproduction steps

When i just created a database and I'm inserting the fields I need, I inserted a non-meant field so I click on delete (since I cannot delete the field name) 

### 👍 Expected behavior

it asks confirmation a if asked to delete, it actually delete it.

### 👎 Actual Behavior

At the moment though it gives the message that says that the field was deleted, but it isn't really

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ildar-in** [comment]
same

**Comment by stnguyen90** [comment]
> At the moment though it gives the message that says that the field was deleted, but it isn't really

@Giuliano1993, would you please clarify what you mean? I just tested deleting an attribute and it deleted fine.

**Comment by Giuliano1993** [comment]
Probably it was a momentaneous thing; i came back now to check and it was deleted in the end. Tried again to create and delete and it works fine now, don't know why last time didn't really deleted at the beginning but results as deleted now. But it do the work so guess we can close this! :)
