### ISSUE TITLE
🐛 Bug Report: Attributes Processing

### ISSUE THREAD

**Issue by ildar-in** [appwrite/appwrite#6419]
### 👟 Reproduction steps

Create new collection in existing database. Added several attributes: message :string(1000), email:string(255).

### 👍 Expected behavior

Able me to add new documents in collection.

### 👎 Actual Behavior

Another old collection I created before - works fine. 
But created new one (I tried several times) dont able me to add new documents. Attributes in status "processing". Several hours along.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I am using browser UI at cloud.appwrite.io/console. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rossanmol** [comment]
Same

**Comment by ItzNotABug** [comment]
@ildar-in Please add a relevant title to the issue.

**Comment by stnguyen90** [comment]
See https://github.com/appwrite/appwrite/discussions/6464#discussioncomment-7178972

**Comment by Jovaini1** [comment]
same issue

**Comment by tarun-kavipurapu** [comment]
same issue...

**Comment by edksam** [comment]
same here
![appwritebug](https://github.com/appwrite/appwrite/assets/62302678/6f38864d-04f3-4d8b-97ed-ad8169c27769)

**Comment by Jikolgit** [comment]
Same issue
any solution ?

**Comment by NestedGateway** [comment]
same is happening with me.

**Comment by samuelbushi** [comment]
Same here, been like this for almost an hour now. 

![Screenshot 2023-12-11 at 01-47-46 Databases - Appwrite](https://github.com/appwrite/appwrite/assets/43500751/ab1fe706-8c0e-41f0-9027-83207b2eb509)

**Comment by maendamedia** [comment]
Same here and also for deleting attributes

**Comment by Epic-R-R** [comment]
Same here
