### ISSUE TITLE
🐛 Bug Report: Attributes processing

### ISSUE THREAD

**Issue by AmrYasserSaber** [appwrite/appwrite#6420]
### 👟 Reproduction steps

I created a trip collection which has a one way relationship with planets_destinations and moons_distinations and the user_id

### 👍 Expected behavior

when I create these attributes it should be done processing 

### 👎 Actual Behavior

when I create these attributes it never finish processing 

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by thats-sarthak** [comment]
I'm quite interested in this issue please provide a pic of this issue and assign this issue to me

**Comment by ItzNotABug** [comment]
@AmrYasserSaber Please add a relevant title to the issue.

**Comment by stnguyen90** [comment]
See https://github.com/appwrite/appwrite/discussions/6464#discussioncomment-7178972
