### ISSUE TITLE
📚 Documentation: [Functions] Git Image Does Not Exist

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6425]
### 💭 Description

The `Git` image resource is `404`ed on https://appwrite.io/docs/products/functions/deployment.

<img width="731" alt="Screenshot 2023-10-02 at 11 23 37 AM" src="https://github.com/appwrite/appwrite/assets/20625965/15e6711b-ac3c-433c-8753-b5a8823d2ba8">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by suman-somu** [comment]
Are you fixing it ??

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by heysagnik** [comment]
I would love to work on this

**Comment by stnguyen90** [comment]
@ItzNotABug, thanks for raising this! 🙏🏼 This has already been addressed as part of https://github.com/appwrite/website/issues/146
