### ISSUE TITLE
🐛 Bug Report: Empty Emails Sent for Certificates

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6435]
### 👟 Reproduction steps

If the `appwrite-worker-certificates` fails, it sends an email with {{body}} as content.

---
Email content :

```
Subject: No Subject
From: Project <sec@xyz.com>
To: Appwrite Administrator <me@xyz.com>

Body: {{body}}
```
This happens on every manual appwrite starts as well (restarts via docker, or on server reboots).

### 👍 Expected behavior

Send actual info. in the email

### 👎 Actual Behavior

Sends {{body}} in the email.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

CloudPanel hooked with NGINX.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cp-Coder** [comment]
I would like to work on this issue

**Comment by heysagnik** [comment]
Can I work on this issue?

**Comment by shivanshu814** [comment]
Can I work on this issue? @ItzNotABug

**Comment by stnguyen90** [comment]
@cp-Coder, this won't qualify for Appwrite swag, but would you still like to work on this issue?

**Comment by stnguyen90** [comment]
@cp-Coder, actually, this is important for us to take care of. If you wish to contribute as part of Hacktoberfest, please look for issues labeled "hacktoberfest".

**Comment by balavamsi28** [comment]
Hello, I would like to look into this issue

**Comment by cp-Coder** [comment]
> @cp-Coder, actually, this is important for us to take care of. If you wish to contribute as part of Hacktoberfest, please look for issues labeled "hacktoberfest".

I was thinking of solving this issue as not a part of Hacktoberfest
