### ISSUE TITLE
🚀 Feature: Appwrite Sdk error in React Native

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [appwrite/appwrite#6436]
### 🔖 Feature description

When I use Appwrite Sdk in React Native it throws error like:
error: Error: Unable to resolve module os from ..\node_modules\node-appwrite\lib\client.js: os could not be found within the project or in these directories:
  node_modules\node-appwrite\node_modules
  node_modules
> 1 | const os = require('os');
                                        ^

### 🎤 Pitch

Because there are so much developers in react native and incompability of appwrite with react native makes it not worty for app dev.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
I think this is happening due to `os` module from `node` not being compatible or supported with `react`.

An alternative for `os` does exist for `react` though but I'm not sure how this will be fixed by the team.

**Comment by stnguyen90** [comment]
@SMARTMICROWORLD you should not be using the `node-appwrite` package in a react native app because it is a server SDK. For more information between our client vs server SDKs, see https://appwrite.io/docs/sdks.
