### ISSUE TITLE
🐛 Bug Report: Cannot deploy or execute functions on 1.4.4 when using external storage provider

### ISSUE THREAD

**Issue by Colton127** [appwrite/appwrite#6439]
### 👟 Reproduction steps

1. Install a fresh installation of 1.4.4
2. Set an external storage provider by modifying _APP_STORAGE_DEVICE and associated storage provider settings in .env
3. Attempt to (re)deploy or execute any function, new or existing.

### 👍 Expected behavior

I expected the function to deploy successfully and execute successfully

### 👎 Actual Behavior

Attempting to deploy a function (occurs both manual and from github):
![Screenshot 2023-10-02 at 11 50 26 AM](https://github.com/appwrite/appwrite/assets/20976940/6dfe4fad-4bd0-4c0c-851c-fd27ad968b72)

Attempting to execute an already-deployed function:
![Screenshot 2023-10-02 at 11 50 58 AM](https://github.com/appwrite/appwrite/assets/20976940/50987b4e-3362-47fa-8e3e-878cf32c1328)
Full error: `An internal curl error has occurred while starting runtime! Error Msg: File Not Found\nError Code: 500`

Output from docker logs openruntimes-executor:
```
Removing orphan runtimes...
Cleaning up containers...
No containers found to clean up.
Cleanup finished.
Orphan runtimes removal finished.
Pulling v3 images...
Warming up Node.js 16.0 environment...
Warming up PHP 8.0 environment...
Warming up Ruby 3.0 environment...
Warming up Python 3.9 environment...
Warming up Dart 2.17 environment...
Warming up Dart 2.18 environment...
Warming up Dart 3.0 environment...
Successfully Warmed up Dart 3.0!
Successfully Warmed up Dart 2.17!
Successfully Warmed up Dart 2.18!
Successfully Warmed up Python 3.9!
Successfully Warmed up Ruby 3.0!
Successfully Warmed up Node.js 16.0!
Successfully Warmed up PHP 8.0!
Image pulling finished.
Starting maintenance interval...
Maintenance interval started.
Starting stats interval...
Stats interval started.
Executor is ready.
[Error] Type: Exception
[Error] Message: File Not Found
[Error] File: /usr/local/app/http.php
[Error] Line: 603
[Error] Type: Exception
[Error] Message: Runtime not ready. Error Msg: []

Error: No such container: appwrite-executor-6482321089e7fc625f5f-651adfe3b2b6054f9e68

[Error] File: /usr/local/app/http.php
[Error] Line: 319
```

appwrite-worker-builds error:
```
File Not Found
/usr/src/code/src/Executor/Executor.php:96
#0 /usr/src/code/app/workers/builds.php(373): Executor\Executor->createRuntime('651ae2457d8768f...', '6482321089e7fc6...', '/storage/functi...', 'openruntimes/da...', 'v3', true, 'lib/main.dart', '/storage/builds...', Array, 'tar -zxf /tmp/c...')
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Ubuntu 23.04

### 🧱 Your Environment

I am using backblaze external storage provider. I can confirm that the storage configuration is correct because the functions are uploaded to backblaze, and because downgrading to appwrite 1.4.3 fixes the issue.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Discord thread: https://discord.com/channels/564160730845151244/1158106759328710696/1158446540747182100

**Comment by stnguyen90** [comment]
@Colton127, would you please try bumping the openruntimes-executor image to 0.4.3 and then deploy the changes with `docker compose up -d`?

**Comment by Colton127** [comment]
> @Colton127, would you please try bumping the openruntimes-executor image to 0.4.3 and then deploy the changes with `docker compose up -d`?

This resolved the issue! Everything is working fine. Thank you so much!
