### ISSUE TITLE
🐛 Bug Report: Support variables in email template subject

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6440]
### 👟 Reproduction steps

The variables from email templates do not work for Subject fields.

Consider a subject like -
`{{project}} : Verify Your Account`.

This should do something like -
`AppwriteAwesomeProject - Verify Your Account` but it doesn't map the value of `{{project}}`.

### 👍 Expected behavior

Variables should work.

### 👎 Actual Behavior

Variables do not work.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by heysagnik** [comment]
can you please give some more details?

**Comment by sahil9001** [comment]
Can you assign me this issue? @ItzNotABug

**Comment by shivanshu814** [comment]
Can you assign me this issue? @ItzNotABug
