### ISSUE TITLE
🐛 Bug Report: Executor does not start after reboot

### ISSUE THREAD

**Issue by istornz** [appwrite/appwrite#6442]
### 👟 Reproduction steps

- Install a fresh version of Appwrite 1.4.4 on a Ubuntu server (don't tested on another os)
- Deploy a function (it works perfectly)
- Reboot the server `sudo reboot` for exemple
- Trying to execute/deploy function throw an error `Could not resolve host: appwrite-executor with status code 0\nError Code: 0`

`docker compose up -d` after each reboot seems to fix the issue (temporary after a reboot)

### 👍 Expected behavior

Functions should deploy/execute

### 👎 Actual Behavior

Functions throw an error `Could not resolve host: appwrite-executor with status code 0\nError Code: 0`

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Hetzner

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@JoshiJoshiJoshi to make sure the openruntimes-executor restarts after a reboot, make sure to include `restart: unless-stopped` in the docker-compose.yml file just like the other services.
