### ISSUE TITLE
📚 Documentation: How to log in through a one-time credential

### ISSUE THREAD

**Issue by jijkbird** [appwrite/appwrite#6447]
### 💭 Description

I want to use the one click login function on my phone, and the backend provides account registration services. How to perform a one-time credential login account.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Susmita-Dey** [comment]
Hey @jijkbird Do you wanna take it up?

**Comment by jijkbird** [comment]
I don't know how to achieve it @Susmita-Dey

**Comment by stnguyen90** [comment]
@jijkbird would one of these work?

1. [Phone (SMS) login](https://appwrite.io/docs/products/auth/phone-sms)
2. [Magic URL login](https://appwrite.io/docs/products/auth/magic-url)
3. [OAuth 2 login](https://appwrite.io/docs/products/auth/oauth2)

**Comment by jijkbird** [comment]
I want to log in with my phone number, but there are currently no available SMS providers available. @stnguyen90

**Comment by jijkbird** [comment]
So I want to issue a one-time token directly from the server, is this feasible?

**Comment by stnguyen90** [comment]
> I want to log in with my phone number, but there are currently no available SMS providers available. @stnguyen90

The best thing to do would be to add a new supported provider.

**Comment by stnguyen90** [comment]
> So I want to issue a one-time token directly from the server, is this feasible?

We don't have support for a one time token at the moment.

**Comment by Abhisheksur123** [comment]
I would like  to work on this

**Comment by eldadfux** [comment]
You can just change the session time to something that is very short-lived or attempt to delete the user session if you have the relevant event when they left your app or website although this might work only some of the time.

Another option would be to set the session to something like 1 minutes and in that 1 minutes generate a JWT for the length of the session and store it in a session cookie or something like that.
