### ISSUE TITLE
🚀 Feature: Add Discord, Twitter logo and feature to count no. Of follower 

### ISSUE THREAD

**Issue by manzil-infinity180** [appwrite/appwrite#6450]
### 🔖 Feature description

![Screenshot_20231003_095725](https://github.com/appwrite/appwrite/assets/119070053/0e6f69d7-60a5-4a21-afd7-dc735c8b18c6)

### 🎤 Pitch
Outcome - (Count of followers on twitter) 
![Screenshot_20231003_095608](https://github.com/appwrite/appwrite/assets/119070053/6ea8ce98-6a04-4955-bea4-54440f475485)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by parmar-abhinav** [comment]
Hi, I would like to work on this issue. Please assign it to me.

**Comment by stnguyen90** [comment]
@manzil-infinity180, thanks for raising this issue! 🙏🏼 Unfortunately, we don't want to add this at the moment. If you wish to contribute as part of Hacktoberfest, please look for issues labeled "hacktoberfest".
