### ISSUE TITLE
🐛 Bug Report: Old compiler is not working properly its giving runtime and network error.

### ISSUE THREAD

**Issue by gaurav-0494** [appwrite/appwrite#6453]
### 👟 Reproduction steps

Just when working on your compiler or executed.

### 👍 Expected behavior

It should run my content or code.

### 👎 Actual Behavior

It doesn't execute because of some bugs.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Sorry, there's not enough detail here to provide any sort of support. It would be best if you created a support post on [Discord](https://appwrite.io/discord) or provided more details.

**Comment by abhay-raj19** [comment]
hey @stnguyen90 are you still working on this issue ??

**Comment by Haimantika** [comment]
Hi @gaurav-0494 as mentioned by @stnguyen90 please add more details and add a support post on [Discord](appwrite.io/discord). Closing this for now.

**Comment by gaurav-0494** [comment]
Yes I am working on it sir and I think it's working fine now sir. So thnks
sir for your concern and sir I am waiting for my swag of previous giveaway.
Pls tell any details about sir.
