### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by HARSHALJETHWA19** [appwrite/appwrite#6456]
### 💭 Description

Hacktoberfest 2023

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by salimcodes** [comment]
Hello, can you please assign this task to me?

**Comment by stnguyen90** [comment]
@HARSHALJETHWA19, please do not create extraneous issues like this. If you want to contribute for Hacktoberfest, please look for issues labeled "hacktoberfest".
