### ISSUE TITLE
📚 Documentation: A clear and concise description of what the issue is.

### ISSUE THREAD

**Issue by parthasarathy27** [appwrite/appwrite#6457]
### 💭 Description

The current documentation lacks clear and concise examples to illustrate the usage of certain features.

Documentation should not only provide a detailed explanation of how a feature works but also include practical examples to help users understand its application better.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sanketshevare** [comment]
I would like to work on this. Can you assign it to me?

**Comment by stnguyen90** [comment]
Closing due to lack of detail. If you're looking to contribute for Hacktoberfest, please look for issues labeled with "hacktoberfest".
