### ISSUE TITLE
🚀 Feature: 

### ISSUE THREAD

**Issue by Shu12388y** [appwrite/appwrite#6470]
### 🔖 Feature description

Adding hover effect in world-leading organization section in the frontend part

![Screenshot from 2023-10-04 07-40-03](https://github.com/appwrite/appwrite/assets/91714143/5ddeec16-982c-4a40-88e4-8144a44acad1)

There is no hover effect in this section

### 🎤 Pitch

When we hover over each icon/logo a glowing effect will be there on each icon
like this 
can you assign this issue to me under hacktoberfest'23
for example 
![glowing-social-icon-hover-effect](https://github.com/appwrite/appwrite/assets/91714143/7343969d-82db-4082-8e4d-627762125d0d)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Saifullah00** [comment]
Please assign me this under hactoberfest'23.

**Comment by shivanshu814** [comment]
please assign me this under hactoberfest'23

**Comment by AnonymousOddity** [comment]
Hello @Shu12388y, can you please assign me this under hactoberfest'23.

**Comment by stnguyen90** [comment]
@Shu12388y Unfortunately, we don't want to add this at the moment. If you wish to contribute as part of Hacktoberfest, please look for issues labeled "hacktoberfest".
