### ISSUE TITLE
🚀 Feature: Enhancement: Improve Code Quality and Maintainability for Amazon OAuth2 Integration

### ISSUE THREAD

**Issue by anupammaurya6767** [appwrite/appwrite#6471]
### 🔖 Feature description

This issue aims to enhance the existing Amazon OAuth2 integration in the codebase. The current implementation is functional but can benefit from improvements in terms of code quality, maintainability, and readability. The proposed changes include:

### 🎤 Pitch

- Defining constants for URLs to improve code readability.
- Consistent formatting and naming conventions for methods and variables.
- Better error handling for HTTP requests and JSON parsing.
- Documentation comments for methods and properties.
- Validation of input parameters and graceful error handling for edge cases.

## Proposed Changes:

- Define constants for URLs.
- Implement consistent formatting and naming conventions.
- Enhance error handling for HTTP requests and JSON parsing.
- Add documentation comments.
- Implement input parameter validation and error handling.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by anurawat01** [comment]
Could you please assign this issue to me ?
I will be happy to taken on this.

**Comment by deanurag** [comment]
I would like to work on this issue, please assign me this.

**Comment by AnonymousOddity** [comment]
I would like to work on this issue, can you please assign me on this?

**Comment by stnguyen90** [comment]
@AnonymousOddity Unfortunately, we don't want to add this at the moment. If you wish to contribute as part of Hacktoberfest, please look for issues labeled "hacktoberfest".
