### ISSUE TITLE
📚 Documentation: Enhance Appwrite Databases with SurrealDB Adapter

### ISSUE THREAD

**Issue by HARSHALJETHWA19** [appwrite/appwrite#6473]
### 💭 Description

Enhance Appwrite Databases with SurrealDB Adapter
Hello, can you please assign this task to me for Hacktoberfest 2023

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Description unclear
