### ISSUE TITLE
📚 Documentation: Rename Twitter to X in ReadMe.md

### ISSUE THREAD

**Issue by shivang17d** [appwrite/appwrite#6477]
### 💭 Description

Join our growing community around the world! Check out our official [Blog](https://medium.com/appwrite-io). Follow us on [X](https://twitter.com/appwrite), [Facebook Page](https://www.facebook.com/appwrite.io), [Facebook Group](https://www.facebook.com/groups/appwrite.developers/), [Dev Community](https://dev.to/appwrite) or join our live [Discord server](https://discord.gg/GSeTUeA) for more help, ideas, and discussions.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by shivang17d** [comment]
Can I work on this issue 🙏

**Comment by Spirizeon** [comment]
Suggesting that it would be best if we replace "Twitter" with "Twitter ( X )" instead of just "X" to avoid confusion for people who may be unfamiliar with the name change.

**Comment by Kota-Karthik** [comment]
Please assign me this issue!!

**Comment by DevCode-shreyas** [comment]
I'm new to open source can you assign me this issue please sir?

**Comment by heysagnik** [comment]
@Qypol342 @Spirizeon Don't create PR If not assigned

**Comment by Spirizeon** [comment]
As mentioned in https://github.com/Qypol342/appwrite/pull/1, there are a few possible changes that can better the README, I would request if this issue can be assigned to me.

Also, thanks to @heysagnik for reminder of following contribution rules.
