### ISSUE TITLE
🐛 Bug Report: Privacy policy link is invalid

### ISSUE THREAD

**Issue by AnishTiwari16** [appwrite/appwrite#6485]
### 👟 Reproduction steps

Go to signup then click on Privacy policy it is having invalid route so it is showing not found

### 👍 Expected behavior

there should be proper route 

### 👎 Actual Behavior

<img width="342" alt="Screenshot 2023-10-04 at 5 23 15 PM" src="https://github.com/appwrite/appwrite/assets/87610940/fe90c7ca-8474-4d76-8eb1-9f1d91bf705e">
<img width="1380" alt="Screenshot 2023-10-04 at 5 23 32 PM" src="https://github.com/appwrite/appwrite/assets/87610940/c6dbd158-ec3f-43a5-829f-d420e45c8a6c">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by AnishTiwari16** [comment]
i will fix it and provide valid route please assign it to me

**Comment by GouravKumar13** [comment]
@AnishTiwari16  can you add hacktober tag and assign this to me, please

**Comment by RamGoel** [comment]
@AnishTiwari16 same thing happening with General terms of Use page as well. 

Do we have exact info about the path of pages?

**Comment by RamGoel** [comment]
<img width="649" alt="image" src="https://github.com/appwrite/appwrite/assets/71088429/52fa9d52-630b-4cc0-9a3c-23c37b2d31fd">
I even tried searching the path in appwrite console repo but couldn't find the exact file from where the 404 page is rendering.

My guess -
There might be some json file from github and the response of that file is rendering on page, as the file on github not found, so it is showing 404.

**Comment by AnishTiwari16** [comment]
@RamGoel it is showing 404 as the path provided for privacy is not valid path hence it is not rendering the content we have to provide the path with valid route...

**Comment by RamGoel** [comment]
Do you know the valid path?

**Comment by RamGoel** [comment]
The pages of privacy and policy are not even part of this repo.

They are part of appwrite/website.

**Comment by AnishTiwari16** [comment]
that can be figured out from the routes section in app waiting for the maintainer to assign the task then we can fix it
