### ISSUE TITLE
📚 Documentation: Inconsistent function executions on Pricing page

### ISSUE THREAD

**Issue by barkhaaroraa** [appwrite/appwrite#6494]
### 💭 Description

<img width="1006" alt="image" src="https://github.com/appwrite/appwrite/assets/115429121/22e6feac-6d2c-41ee-b6b8-7c352889ee95">
<img width="1020" alt="image" src="https://github.com/appwrite/appwrite/assets/115429121/d918caa9-5646-4b3a-86e7-89a1969db501">
there are a few inconsistencies on the pricing page, like in the starter pack the bandwidth above is 10GB while below its 100GB, then in the pro pack the execution is 3M above and 3.5M below 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by heysagnik** [comment]
I would love to work on this issue

**Comment by barkhaaroraa** [comment]
Hi could you assign me this issue under hacktober fest tag?

**Comment by balavamsi28** [comment]
Hi could you assign me this issue under hacktober fest tag?
I would like to resolve this issue

**Comment by mesloubi2021** [comment]
نعم بالتوفيق
