### ISSUE TITLE
🐛 Bug Report: Document IDs Don't Update when Changing Collections

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6497]
### 👟 Reproduction steps

1. Have multiple collections with multiple documents
2. Have your view set up so the ID is truncated
3. Switch between Collections

### 👍 Expected behavior

The IDs update

### 👎 Actual Behavior

The IDs don't update:

https://github.com/appwrite/appwrite/assets/1477010/b55b99e8-81b3-416a-a32c-a348e95dfbd7

If you hover over the ID, you can also see the ID displayed doesn't match the ID in the link.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

The video was recorded on an older version, but the bug is still prevalent on Appwrite Cloud (1.4.4).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
The document IDs also don't change when going between the next and previous document pages.

**Comment by JayPokale** [comment]
The issue is in one of the submodules.
I fixed this issue on the submodule.
Can anyone help to change that from this repo, as this repo is in Hacktoberfest but not it's submodule.

**Comment by JayPokale** [comment]
The issue is in one of the submodules.
I fixed this issue on the submodule.
Can anyone help to change that from this repo, as this repo is in Hacktoberfest but not it's submodule.
