### ISSUE TITLE
📚 Documentation: Improvement and Enhancement of README-CN.md

### ISSUE THREAD

**Issue by debanath** [appwrite/appwrite#6498]
### 💭 Description

There are certain section missing in the [`README-CN.md`](https://github.com/appwrite/appwrite/blob/main/README-CN.md) like the `One-Click Setups`    

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by debanath** [comment]
Request to Be Assigned the Issue – Eager to Contribute!

**Comment by stnguyen90** [comment]
If you're eager to contribute, please read our [contributing guide](https://github.com/appwrite/appwrite/blob/main/CONTRIBUTING.md#here-for-hacktoberfest) and look for hacktoberfest labeled issues.
