### ISSUE TITLE
🚀 Feature: Alert Enhancement in Auth

### ISSUE THREAD

**Issue by tarunsinghofficial** [appwrite/appwrite#6502]
### 🔖 Feature description

In the Auth, when the user enables or disables any auth method, it shows the ALert with the updated message in it. Instead of always showing the same alert for enabling or disabling, we can add a Success color alert for enabling and a Danger color alert for disabling.

### 🎤 Pitch

This feature would enable the user to know if he has disabled or enabled the auth methods with the relevant color and message in the alert box. Below I have attached the screenshot for reference.

Thanks

![appwrite issue 1](https://github.com/appwrite/appwrite/assets/62840625/a3bb26e3-5925-4d86-9669-f26e871d689e)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by tarunsinghofficial** [comment]
Happy to work on this issue, so please assign it to me. Thanks

**Comment by ItzNotABug** [comment]
This isn't only for Auth.
This behaviour is all over console. Refactoring this would require complete changes across Console's notification logic which I don't think the Team has any plans as of now.

But I agree that this can be improved.

**Comment by Haimantika** [comment]
This is intentional and we do not plan to change this in the near future. Thank you for raising the feature request :)
