### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Samsursekh** [appwrite/appwrite#6505]
### 👟 Reproduction steps

i have created a database in appwrite in one browser its showing fine but for another its only showing the database name not all the data please help me to find out the way so that i can fix it 

### 👍 Expected behavior

it should show same thing for every browser

### 👎 Actual Behavior

it should show same thing for every browser

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by hasbullah-mughniy** [comment]
I would like to work on this. Can you assign it to me?

**Comment by Haimantika** [comment]
Hi @Samsursekh can you share screenshots of the same?

**Comment by Samsursekh** [comment]
I have attached screenshots of two browsers with different results even if
with the *same creden**tials.*
please check.

**Comment by Samsursekh** [comment]
In Brave, it works fine once I log in, but in Chrome, it's not.

**Comment by ItzNotABug** [comment]
Does it work in an incognito/private window on Chrome?

**Comment by Samsursekh** [comment]
No, it does not.

**Comment by ItzNotABug** [comment]
Also, I don't see any screenshots if you added.

**Comment by Samsursekh** [comment]
Here i have added in previous messages can you see this

**Comment by ItzNotABug** [comment]
Nope, not on app, not via browser.

**Comment by Samsursekh** [comment]
Now please check once again if you can see it or not

**Comment by Samsursekh** [comment]
![brave Database - Appwrite - Brave 06-10-2023 17_11_04](https://github.com/appwrite/appwrite/assets/101379073/01fc335d-2b5e-41bc-9e0c-a2822ef78c4a)
![chrome Databases - Appwrite - Google Chrome 06-10-2023 17_13_56](https://github.com/appwrite/appwrite/assets/101379073/6f2c9e9c-f4eb-44fb-a2ac-2447dc17836c)

**Comment by Samsursekh** [comment]
Actually i was sending in the email, not with github that's why it was causing issue

**Comment by ItzNotABug** [comment]
I don't think this is a bug, but I might be wrong.
The reason I say this is because I see 2 different project IDs from the shared screenshots.

1. project-65145bd88f881ce06e19
2. project-65145b29135d1f5cf07

**Comment by Samsursekh** [comment]
Can you please suggest me what i have to do?

**Comment by ItzNotABug** [comment]
Pl. check / compare the urls from both your screenshots i.e in Chrome & Brave.

You might have multiple projects with same name or you used multiple accounts & both have a project with same name.

**Comment by Samsursekh** [comment]
I think this is  not a bug
