### ISSUE TITLE
Support non-interactive setups

### ISSUE THREAD

**Issue by eldadfux** [appwrite/appwrite#681]
## 🚀 Feature

We need to add an option for non-interactive setup from the command line. This can be set using a flag passed to the command line indicating the setup process not to ask for any user input. When this flag is set the `install` script should use default setup values or fetch values passed as command line arguments.

Currently we have only 4 mandatory params:
* Server hostname
* HTTP port
* HTTPS port
* CNAME target

**Comment by SoftCreatR** [comment]
I'll try it.

**Comment by eldadfux** [comment]
Some small pointers to help out:

* Updated setup examples are located here: https://github.com/appwrite/appwrite/tree/0.7.x#unix
* You can add new command line args using the `param` method, like this: https://github.com/appwrite/appwrite/blob/0.7.x/app/tasks/install.php#L15
 * You can also use the `param` method to define a default param value and set it as required.
* A list of available param validators is available here: https://github.com/utopia-php/framework/tree/master/src/Validator
* There are also a few Validators available inside the Appwrite src folder
* The confirm method asking user input already knows how to detect non-interactive mode, but maybe it will be helpful to add to its signature a `default` param instead of returning null: https://github.com/utopia-php/cli/blob/master/src/CLI/Console.php#L93
* The script is asking the user for HTTP & HTTPS port values and also all the param values that are marked as required in this configuration file: https://github.com/appwrite/appwrite/blob/0.7.x/app/config/variables.php

**Comment by SoftCreatR** [comment]
I'll start working on this if I can make 0.7 work on my machine. The last time I tried, it didn't work, which makes testing difficult.

**Comment by eldadfux** [comment]
@SoftCreatR are you still interested in working on this issue?

**Comment by SoftCreatR** [comment]
I currently don't have the time, sorry.

**Comment by TorstenDittmann** [comment]
This got implemented 👍🏻
