### ISSUE TITLE
📚 Documentation: Missing Build Command for Bun

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6827]
### 💭 Description

The documentation for [Dependencies](https://appwrite.io/docs/products/functions/development#dependencies) is missing information for Bun.

Add `Bun : bun install`.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by hassansuhaib** [comment]
I would like to work on this.

**Comment by HeetVekariya** [comment]
I would like to work on this, as this is good first.

**Comment by Abhisheksur123** [comment]
I would like  to work on this

**Comment by emmanueldavids** [comment]
I would like to contribute to this work

**Comment by uozcan12** [comment]
I would like to contribute to this work
