### ISSUE TITLE
🐛 Bug Report: index creation stuck and processing for days

### ISSUE THREAD

**Issue by AgustinQuetto** [appwrite/appwrite#6830]
### 👟 Reproduction steps

Hello everyone,

Thanks for create this f** awesome product 🙌🏼

I'm using AppWrite Cloud. Two days ago I decided to create an index. After one day processing, the current status is "stuck".

When I removed it, an alert indicated "confirmed" but the index persists.

Yesterday I created a "fulltext" index with the message "processing" and it is still in the same state.

My collection only has 50 documents. The ID is 649b4ef3709f57d7f779.

Thanks ✨

<img width="1071" alt="Captura de Pantalla 2023-10-06 a la(s) 14 05 40" src="https://github.com/appwrite/appwrite/assets/15186148/4002b8e3-bc66-4bf6-a616-69864255d0df">

<img width="1207" alt="Captura de Pantalla 2023-10-06 a la(s) 14 02 00" src="https://github.com/appwrite/appwrite/assets/15186148/3962ee5e-1a20-4ff7-9554-8bb9e8cd0deb">

### 👍 Expected behavior

Create and delete index normally.

### 👎 Actual Behavior

Index creation stuck and processing for days.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Something else

### 🧱 Your Environment

A Next.js app directly to AppWrite Cloud.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Sshivam26** [comment]
i would like to work on this bug @AgustinQuetto

**Comment by stnguyen90** [comment]
Please see https://github.com/appwrite/appwrite/discussions/6464#discussioncomment-7178972
