### ISSUE TITLE
🐛 Bug Report: GitHub installation has old appwrite logo

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6831]
### 👟 Reproduction steps

1. Open a project in the Appwrite console
2. Click on Settings
3. Scroll down to Git configuration

### 👍 Expected behavior

The logo should be the new Appwrite logo.

### 👎 Actual Behavior

The logo is the old logo:

![image](https://github.com/appwrite/appwrite/assets/1477010/6514e2b6-50d9-4d2a-be84-3d1d63b92e01)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Since the PR isn't merged yet & this issue is still open, adding another finding here.

The old appwrite logo exists in the Functions Marketplace as well.

Open any template by clicking 'View Details', check 'Published by' section.
