### ISSUE TITLE
🐛 Bug Report: Enabling self signed certificates for Node SDK doesn't work

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6832]
### 👟 Reproduction steps

Run the following code with the correct endpoint, project, and API key.

```javascript
const sdk = require('node-appwrite');

let client = new sdk.Client();

client
    .setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2') // Your project ID
    .setKey('919c2d18fb5d4...a2ae413da83346ad2') // Your secret API key
    .setSelfSigned() // Use only on dev mode with a self-signed SSL cert
;

let users = new sdk.Users(client);

let promise = users.list();

promise.then(function (response) {
    console.log(response);
}, function (error) {
    console.log(error);
});
```

### 👍 Expected behavior

Assuming your Appwrite instance has a self signed certificate, the API call should work.

### 👎 Actual Behavior

The API call will fail with an error like:

> AppwriteException [Error]: self-signed certificate

The way we're handing [self-signed certificates](https://github.com/appwrite/sdk-for-node/blob/1390e2dea2d22b3b8944e72111bd1c1b49a3d8aa/lib/client.js#L122) is:

```javascript
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
```

However, Node does a [strict check](https://github.com/nodejs/node/blob/c5de3b49e8015b381008ac0428cbfed613ab53ed/lib/internal/options.js#L54):

```javascript
const allowUnauthorized = process.env.NODE_TLS_REJECT_UNAUTHORIZED === '0';
```

As such, the check fails.

Furthermore, we shouldn't be using this `NODE_TLS_REJECT_UNAUTHORIZED` environment variable because it disables TLS for all network requests, but we should only allow self-signed certificates for the Appwrite API calls. Instead of setting `NODE_TLS_REJECT_UNAUTHORIZED`, we should be passing an option to axios like we do in the [CLI](https://github.com/appwrite/sdk-for-cli/blob/b0b59eea974f5b77e88aaba72fd141587d6ce6f8/lib/client.js#L191):

```javasciprt:
options.httpsAgent = new https.Agent({ rejectUnauthorized: false });
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

This was seen in node-appwrite version 11.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by nick2432** [comment]
can i work on this issue?
