### ISSUE TITLE
🚀 Feature: Improve sign-in modes

### ISSUE THREAD

**Issue by yasawini143** [appwrite/appwrite#6835]
### 🔖 Feature description

Add more sign in ways to login. There are only two ways of sign-in.

### 🎤 Pitch

This feature is to create logins from different webs.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Yasir761** [comment]
Is anyone working on this issue?

**Comment by parthksingh1** [comment]
Please assign me this issue @yasawini143

**Comment by ItzNotABug** [comment]
> There are only two ways of sign-in.

Can you be a bit more specific as to which Sign-In modes you are talking about?

Appwrite Cloud's Sign In?

**Comment by eldadfux** [comment]
Appwrite has support for over 30 sign-in methods. We're always happy to add new ones. If anyone needs a specific sign-in method its better to open a dedicated issue for that.
