### ISSUE TITLE
Schema-less collections

### ISSUE THREAD

**Issue by Taha-Firoz** [appwrite/appwrite#684]
## 🚀 Feature

Make providing rules/schema for documents in a collection optional(like Mozilla Kinto).

## Have you spent some time to check if this issue has been raised before?

Yes, I was advised to make a feature request.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

I think providing a schema for our documents should be optional, this is important when you're just starting an application out and don't want to worry about how your schemas going to look like before hand. It's an important feature to have after a while but its frustrating when you're prototyping and don't know exactly what you're schemas going to look like. Also if we're trying to be a stronger Firestore alternative this is a must feature.

In many of the apps I've made with using Firestore we add a field and then decide not to include it in production that flexibility is key for prototyping. Also I acknowledge that this is a practice most larger apps don't do however, platforms like Appwrite and Firebase provide a great degree of ease of use which allow for faster development without worrying about the backend. Also larger apps will probably not prefer Appwrite or Firebase and would probably go for writing their own backend.

**Comment by TorstenDittmann** [comment]
I am not sure if we are going to follow that route.

This will basically disable features that make Appwrite secure. I will close this issue for now, if there is any interest in discussing it - we can open it again.
