### ISSUE TITLE
📚 Documentation: Install with script CLI url for Linux gives 404

### ISSUE THREAD

**Issue by rohanmohapatra** [appwrite/appwrite#6843]
### 💭 Description

On this documentation, https://appwrite.io/docs/tooling/command-line/installation

If I try to install the CLI on linux, 
```
curl -sL https://appwrite.io/cli/install.sh | bash
```
I get a 404 and the link says the page is broken.

Let me know where the actual script is and I make a contribution for it

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by HeetVekariya** [comment]
I would like to work on this issue if it is valid issue, can you please assign it to me ?
Also @stnguyen90 can you please provide the correct command/url which is to be updated.

**Comment by stnguyen90** [comment]
@rohanmohapatra, thanks for raising this! 🙏🏼 For now, I highly suggest [installing using NPM](https://appwrite.io/docs/tooling/command-line/installation#install-with-npm).

**Comment by bfritscher** [comment]
Github Action should also be updated or removed if no longer supported. https://github.com/appwrite/setup-for-actions/blob/main/action.yml

**Comment by EVDOG4LIFE** [comment]
![image](https://github.com/appwrite/appwrite/assets/23223867/8e834ff1-9be5-4258-a635-5870cbc4eb02)

URL is active, see above screenshot for verification on Ubuntu.
