### ISSUE TITLE
🐛 Bug Report: Browser Icons are Broken if User-Agent is Unknown

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6845]
### 👟 Reproduction steps

1. Create a session via Postman, or NodeJS' fetch like library
2. Navigate to Account > Sessions
3. An icon for the Browser doesn't exist & it'll show a broken image

<img width="532" alt="Screenshot 2023-10-08 at 1 08 36 PM" src="https://github.com/appwrite/appwrite/assets/20625965/ca3388c0-7337-44d4-a720-97b2fa2ec384">

### 👍 Expected behavior

Use a standard default browser or globe icon like - 🌐

### 👎 Actual Behavior

Shows broken image for unidentified User Agents.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ddevilz** [comment]
I intend to work on this; please assign me.

**Comment by beneyalraj** [comment]
i would like to work on this issue

**Comment by nick2432** [comment]
can i work on this issue?

**Comment by stnguyen90** [comment]
Fixed as part of https://github.com/appwrite/console/pull/771
