### ISSUE TITLE
🐛 Bug Report: Attributes processing

### ISSUE THREAD

**Issue by DominatorVbN** [appwrite/appwrite#6846]
### 👟 Reproduction steps

- Go to dashboard 
    - Go to database
       - Create Database
          - Create Collection
             - Create Attrubutes   

### 👍 Expected behavior

- Should be finished processing under 20-20 minutes

### 👎 Actual Behavior

- Still showing processing

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

i use swift and iOS 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by MrAshwin2142** [comment]
facing same problem

**Comment by stnguyen90** [comment]
Please see https://github.com/appwrite/appwrite/discussions/6464#discussioncomment-7178972
