### ISSUE TITLE
🐛 Bug Report: database attribute creation

### ISSUE THREAD

**Issue by vectorkovacspeter** [appwrite/appwrite#6847]
### 👟 Reproduction steps

 - create a new database, with autogenerated id
 - create a collection with autogenerated id
 - create attribute on the collection ( types I tried: string, enum)

### 👍 Expected behavior

The attributes creating within a few second, and then I can add data to the collection

### 👎 Actual Behavior

The attributes stuck in 'processing' state

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I use it in the cloud, via Chrome browser on Windows 11, it's Independent from the client (Its a tutorial NextJs app)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by YogeshBisht2307** [comment]
Having same issue any solution please?

**Comment by Philip-Nwabuwa** [comment]
facing this Issue

**Comment by vectorkovacspeter** [comment]
UPDATE: Abaut a day later, the attributes are created

**Comment by stnguyen90** [comment]
See:

* https://github.com/appwrite/appwrite/discussions/6464#discussioncomment-7178972
