### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by MrAshwin2142** [appwrite/appwrite#6852]
### 👟 Reproduction steps

when i tried to create new attribute in collection

### 👍 Expected behavior

it shows processing for a long time

### 👎 Actual Behavior

![Screenshot 2023-10-08 101347](https://github.com/appwrite/appwrite/assets/89156541/ec34303d-124a-4edf-80d0-17d96d3d10c7)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by MrAshwin2142** [comment]
duplicate

**Comment by sc231997** [comment]
Duplicate #6847
