### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Somdelie** [appwrite/appwrite#6853]
### 👟 Reproduction steps

trying to access from deployed app on vecel but i get this error ' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://localhost' that is not equal to the supplied origin.'
and i created the new project with my deployed origin but it seems like it still get the localhost only can't be accessed by deployed app on  vercel tryed many times to set it to vercel but it doesn't work

### 👍 Expected behavior

it should connect to the deployed version

### 👎 Actual Behavior

it gives me the cors error

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

i use appwrite console

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
You'll need to add a web platform. Please see:

* https://github.com/appwrite/sdk-for-web#add-your-web-platform
* https://github.com/appwrite/appwrite/discussions/1239#discussioncomment-822836

If you need additional help, feel free to create a support post on [Discord](https://appwrite.io/discord).
