### ISSUE TITLE
🐛 Bug Report: Icons are not clear on docs page of website in light mode

### ISSUE THREAD

**Issue by AditiSingh2003** [appwrite/appwrite#6857]
### 👟 Reproduction steps

When Going on the [Docs page](https://appwrite.io/docs) in the Light mode the icon is very light and same goes for the other pages.
![image](https://github.com/appwrite/appwrite/assets/97729662/07c4bace-76fd-4d2f-9572-4e09bf2d2702)

### 👍 Expected behavior

In light mode the color will be darker, and in the dark mode the color will be lighter.

### 👎 Actual Behavior

The icon color is light in lighter mode.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DhairyaMajmudar** [comment]
@stnguyen90 @AditiSingh2003 I would like to work on this. Can you assign it to me? 🙏

**Comment by Haimantika** [comment]
Hi @AditiSingh2003 thanks for raising this issue, our team is working on a fix for this :)

**Comment by DhairyaMajmudar** [comment]
> Hi @AditiSingh2003 thanks for raising this issue, our team is working on a fix for this :)

Ma'am if you don't mind I can contribute in this issue pls. 🙏🏻

**Comment by Haimantika** [comment]
> > Hi @AditiSingh2003 thanks for raising this issue, our team is working on a fix for this :)
> 
> Ma'am if you don't mind I can contribute in this issue pls. 🙏🏻

I fear that is not possible, since it will require our team to work on it

**Comment by DhairyaMajmudar** [comment]
> > > Hi @AditiSingh2003 thanks for raising this issue, our team is working on a fix for this :)
> > 
> > 
> > Ma'am if you don't mind I can contribute in this issue pls. 🙏🏻
> 
> I fear that is not possible, since it will require our team to work on it

Just give me one chance to fix the issue if I failed to do so I will let you know
