### ISSUE TITLE
🐛 Bug Report: Duplicate Message on Delete Document Alert

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6860]
### 👟 Reproduction steps

1. Go to any collection that has documents
2. Click on any document
3. Scroll down & click Delete
4. Below confirmation shows up

![duplicate_message](https://github.com/appwrite/appwrite/assets/20625965/d01cfc24-33b5-4aa9-90c4-7f67cafb694f)

### 👍 Expected behavior

Show the confirmation message just once.

### 👎 Actual Behavior

Confirmation message is shown twice.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite `1.4.4`, Cloud & Self-Hosted.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by brantheeman** [comment]
I would like to be assigned this bug fix

**Comment by Salonikansal2** [comment]
Assign please @stnguyen90 .

**Comment by kunalvirk** [comment]
I have resolved it and raised a PR, sorry for continuing without getting assigned.
Thanks

**Comment by nick2432** [comment]
can i work on this issue?
