### ISSUE TITLE
📚 Documentation: README translation

### ISSUE THREAD

**Issue by jakaya123** [appwrite/appwrite#6880]
### 💭 Description

Hi there.

It would be very helpful for developers if we add translations to the README.md file.

There is a Chinese translation of the README.md file. But I think it would be better if we could add more translations.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jakaya123** [comment]
I also like to add translations.Can i work on translations

**Comment by Shruti700** [comment]
Hey I would like to work on translations. Can you assign this to me?

**Comment by CharithaCS** [comment]
Hello! I'd love to contribute my part too. It would enable a better reach.

**Comment by stnguyen90** [comment]
We probably don't want to have more translations at this time, but what language do you think is crucial to have?

**Comment by Haimantika** [comment]
Hi @jakaya123 thanks for bringing this up to us. As Steven mentioned, we do not want to add more translations for now. Will be closing the issue for now, you can reach out to us on [Discord](https://appwrite.io/discord) anytime.
