### ISSUE TITLE
🐛 Bug Report: Adding multiple many to many relationship attributes to the same collection gets stuck at processing status 

### ISSUE THREAD

**Issue by nikkyeya** [appwrite/appwrite#6887]
### 👟 Reproduction steps

When I created multiple relationship attributes within the same collection, I observed that the second attribute became stuck in a 'failed' status, while the other side of the relationship remained in a 'processing' status. 

Also, adding relationship attributes with custom key names within the same collection sometimes failed.
Recording: https://www.awesomescreenshot.com/video/21552043?key=c3c8dde9e73f0bc09a0fdc67499d2bfa

Please

### 👍 Expected behavior

It should display a 'failed' status on both ends and automatically remove the attribute from the list. Alternatively, consider preventing users from adding multiple many-to-many relationship fields within the same collection if full support is not available at the moment.

### 👎 Actual Behavior

I actually was able to add the second many-to-many relationship, but it remained stuck in a 'failed/processing' status. The 'processing' status misled me into thinking I should wait for it to be resolved.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite ^13.0.0
Client SDK
Cloud Console

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@nikkyeya, thanks for raising this issue! 🙏🏼 

FYI, the problem is a many-to-many relationship attribute creates a junction collection (extra table) with the name:

```php
'_' . $collection->getInternalId() . '_' . $relatedCollection->getInternalId()
```
[source](<https://github.com/utopia-php/database/blob/5f7b05189cfbcc0506090498c580c5765375a00a/src/Database/Database.php#L1600>)

This causes problems if you want multiple relationships on the same collections.

**Comment by johnschatner** [comment]
This happened to me yesterday and the ominous part is that the backend completely stopped working, I couldn't access the data from any documents within a collection that had the "failed" and or "processing" status. I couldn't delete the attribute either. This led to me having to create three seperate collections and add the data all over. The logs were very misleading, it said that the attribute ID didn't exist when trying to delete the attribute, but when trying to re add the same attribute it would say that it already exists.

**Comment by spencer237** [comment]
This also happened to me, but unlike @johnschatner , the backend was still working and I was able to remove the attribute without a problem.
