### ISSUE TITLE
🐛 Bug Report: Functions' Execution Body is Missing

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#6889]
### 👟 Reproduction steps

The `Execute` button on the deployments tab will show the `body` data in Advance Settings if you added data for execution previously.

This behaviour is missing in the Advance Settings if the `Execute` button is clicked in the `Executions` tab.

### 👍 Expected behavior

Consistent data in the Advance Settings when trying to execute a function from the Console.

### 👎 Actual Behavior

Body data exists in Deployment tab, not in Executions tab.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite `1.4.5`.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ItzNotABug, thanks for raising this! 🙏🏼 I just tried this and it looks like the data will show in whichever modal you input in last...

That said, I think we typically clear the data after executing so if anything, we might update it to make sure to clear the data after submission.

**Comment by ItzNotABug** [comment]
@stnguyen90 Hmm, makes sense to clear the data post submission.
