### ISSUE TITLE
🐛 Bug Report: Multiple internal curl errors has occurred within the executor! Error Number: 111.

### ISSUE THREAD

**Issue by JakeAi** [appwrite/appwrite#6902]
### 👟 Reproduction steps

The first execution after deployment/restart. When you're testing a function, and you have to keep deploying it and running it, and constantly get the CURL error.. it's a pain in the arse.
Deploy a (node?) function and execute it.

https://discord.com/channels/564160730845151244/1162099630494973982
(Wasn't actually solved) https://discord.com/channels/564160730845151244/1151439270041628763

### 👍 Expected behavior

It should run normally

### 👎 Actual Behavior

Multiple internal curl errors has occurred within the executor! Error Number: 111. Error Msg: Connection refused\nError Code: 500

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite: 1.4.5
Linux docker-01 5.15.0-73-generic #80-Ubuntu SMP

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by behicsakar** [comment]
Same issue after upgrading 1.4.5 from 1.4.4

function runs `node-20`
<img width="1775" alt="Screenshot 2023-10-14 at 10 44 25" src="https://github.com/appwrite/appwrite/assets/3280475/4ad1846f-142e-45f6-865e-d079650090a0">

**Comment by chakshumraval** [comment]
I am facing same issue. Any update ?

**Comment by nikitakofman** [comment]
I am also encountering the same issue. Multiple internal curl errors on first time, then have to re execute for it to go away.

**Comment by maks-io** [comment]
Question to all the others who are having similar issues here: 
are you also using a very "limited set of resources" maybe? I am currently using https://marketplace.digitalocean.com/apps/appwrite and when setting it up, i chose the cheapest droplet variant they're offering (since it is for testing purposes only anyhow).
I am asking, because to me it feels like some things just "go to sleep" after some time and therefore my first few function calls fail if i haven't been using them for some time. Could be that this is only the case due to limited resources maybe? Just thinking out loud, didn't have time to investigate further yet.

**Comment by JakeAi** [comment]
> Question to all the others who are having similar issues here: are you also using a very "limited set of resources" maybe? I am currently using https://marketplace.digitalocean.com/apps/appwrite and when setting it up, i chose the cheapest droplet variant they're offering (since it is for testing purposes only anyhow). I am asking, because to me it feels like some things just "go to sleep" after some time and therefore my first few function calls fail if i haven't been using them for some time. Could be that this is only the case due to limited resources maybe? Just thinking out loud, didn't have time to investigate further yet.

The thing is, it never used to happen. And now it's been present for like 6 months.

**Comment by maks-io** [comment]
> > Question to all the others who are having similar issues here: are you also using a very "limited set of resources" maybe? I am currently using https://marketplace.digitalocean.com/apps/appwrite and when setting it up, i chose the cheapest droplet variant they're offering (since it is for testing purposes only anyhow). I am asking, because to me it feels like some things just "go to sleep" after some time and therefore my first few function calls fail if i haven't been using them for some time. Could be that this is only the case due to limited resources maybe? Just thinking out loud, didn't have time to investigate further yet.
> 
> The thing is, it never used to happen. And now it's been present for like 6 months.

Okay that's quite a long time, I wasn't aware of that since I only recently started using appwrite.

**Comment by chakshumraval** [comment]
It's been since 6 month now. i am still facing same issue.  Any update on this ? 

It is stopping us to make apps live. so it's blocker for us

**Comment by JakeAi** [comment]
> It's been since 6 month now. i am still facing same issue. Any update on this ?
> 
> It is stopping us to make apps live. so it's blocker for us

It doesn't happen on the paid version, so they probably won't fix it.

**Comment by maks-io** [comment]
> > It's been since 6 month now. i am still facing same issue. Any update on this ?
> > It is stopping us to make apps live. so it's blocker for us
> 
> It doesn't happen on the paid version, so they probably won't fix it.

I really hope you are wrong, but yeah... which way are you guys going, Supabase? Firebase? Anything else?

**Comment by JakeAi** [comment]
> > > It's been since 6 month now. i am still facing same issue. Any update on this ?
> > > It is stopping us to make apps live. so it's blocker for us
> > 
> > 
> > It doesn't happen on the paid version, so they probably won't fix it.
> 
> I really hope you are wrong, but yeah... which way are you guys going, Supabase? Firebase? Anything else?

Literally struggle busing through it and making snarky remarks in discord until it gets addressed.

**Comment by maks-io** [comment]
I just upgraded my DigitalOcean Appwrite instance to the new `1.5.1` version - upgrade itself was flawless but this bug is still existing.

For now i am thinking about staying with Appwrite but using a separate express app for some additional backend logic and skipping functions completely.

**Comment by EVDOG4LIFE** [comment]
I can successfully reproduce this on Cloud consistently. This seems to occur during the cold start of the functions container, and subsequent executions succeed. 
![image](https://github.com/appwrite/appwrite/assets/23223867/8c156bb2-94d8-44c9-b43e-1bc62a5d43d1)

**Comment by lawipac** [comment]
I got the same error, and re-executing the same function immediately seems to solve the problem.  It's looks more like a bug in Appwrite.

![Snag_13c6a693](https://github.com/appwrite/appwrite/assets/10069433/f0e82b0b-be29-4b0a-965f-2d0685873ba5)

**Comment by lawipac** [comment]
> Question to all the others who are having similar issues here: are you also using a very "limited set of resources" maybe? I am currently using https://marketplace.digitalocean.com/apps/appwrite and when setting it up, i chose the cheapest droplet variant they're offering (since it is for testing purposes only anyhow). I am asking, because to me it feels like some things just "go to sleep" after some time and therefore my first few function calls fail if i haven't been using them for some time. Could be that this is only the case due to limited resources maybe? Just thinking out loud, didn't have time to investigate further yet.

I'm on plenty of resources using a dedicated test bed, but I still have the same error.

**Comment by JakeAi** [comment]
> > Question to all the others who are having similar issues here: are you also using a very "limited set of resources" maybe? I am currently using https://marketplace.digitalocean.com/apps/appwrite and when setting it up, i chose the cheapest droplet variant they're offering (since it is for testing purposes only anyhow). I am asking, because to me it feels like some things just "go to sleep" after some time and therefore my first few function calls fail if i haven't been using them for some time. Could be that this is only the case due to limited resources maybe? Just thinking out loud, didn't have time to investigate further yet.
> 
> I'm on plenty of resources using a dedicated test bed, with version 1.5.3, the same problem still exists.

Yeah it doesn’t matter and shouldn’t matter. It never used to happen prior to 1.4. I’ve been using the same VM since 0.6.

**Comment by eldadfux** [comment]
We're looking into this problem. Feel free to share any logs that you think might be relevant or steps to reproduce.

**Comment by Inovvia** [comment]
Hi, we used to experience this using WSL and docker, we were able to fix it by switching to linux and having more memory available for appwrite executor/containers.

**Comment by LDY681** [comment]
I am having the same issue and daily CRON jobs are inconsistent due to frequent fails.

**Comment by EVDOG4LIFE** [comment]
We've made some improvements to functions in Cloud and `1.5.7` and the error rate for this specific error has gone down.

The reproduction case I created previously no longer throws this error so this is looking good. 

If you are still experiencing this error in your self-hosted setup, please ensure that you've upgraded to `1.5.7`, for Cloud users - this is currently live.
