### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by trishan9** [appwrite/appwrite#6906]
### 💭 Description

Typo related to space after comma, there needs to be space after comma, which is not there in one of the documentation, so it would be great if this issue is considered and assigned to me!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by letscodedanish** [comment]
I would like to work on this issue.

**Comment by Haimantika** [comment]
> ### 💭 Description
> Typo related to space after comma, there needs to be space after comma, which is not there in one of the documentation, so it would be great if this issue is considered and assigned to me!
> 
> ### 👀 Have you spent some time to check if this issue has been raised before?
> * [x]  I checked and didn't find similar issue
> 
> ### 🏢 Have you read the Code of Conduct?
> * [x]  I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

Hi @trishan9 thank you so much for bringing it up. Our team will look into it and fix it. Will be closing this issue for now. If you have any questions, you can reach out to us on [Discord](https://appwrite.io/discord)

**Comment by Muhammad-Saleem-Ch** [comment]
That was a correct issues
