### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Anjali-Git-Hub** [appwrite/appwrite#6911]
### 👟 Reproduction steps

While scrolling through the company's mobile page, I noticed that the angel investor section looks messy.

### 👍 Expected behavior

There should be borders or some form of separation to make it look less messy

### 👎 Actual Behavior

![WhatsApp Image 2023-10-15 at 10 05 08 AM](https://github.com/appwrite/appwrite/assets/122084921/e8803c42-014b-4c28-bc02-1977c9063f53)

not looking  good as you can see.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Anjali-Git-Hub** [comment]
i want to work on this issue

**Comment by Anjali-Git-Hub** [comment]
![border](https://github.com/appwrite/appwrite/assets/122084921/37a39729-34ad-4cf4-a032-9cb9a8898945)

**Comment by saurabhraj123** [comment]
Have you contributed to any hactoberfest projects?

**Comment by codeslayed** [comment]
i want to work on this issue

**Comment by codeslayed** [comment]
this is my first hacktober fest issue

**Comment by codeslayed** [comment]
> Have you contributed to any hactoberfest projects?

no but this will be my first project

**Comment by codeslayed** [comment]
how can i pull this code

**Comment by codeslayed** [comment]
Please assign this to me

**Comment by Anjali-Git-Hub** [comment]
@saurabhraj123 , yes  . Please assign this issue to me , i want to handel it .

**Comment by stnguyen90** [comment]
Hi, thank you for your interest in participating in Hacktoberfest!

We really appreciate your enthusiasm.

So this year, we’re focused on quality contributions. This doesn’t just mean we want quality code from contributors; we also want to foster a quality relationship with the contributors through extensive reviews and support so they can tackle more meaningful and difficult projects.

With that said, we have a small team with limited capacity. So we’re careful about how many active issues we post for Hacktoberfest, so we can review and support each contributor adequately. 

That said, if you find a reasonably sized issue on the Appwrite repo that you’d like to tackle, you can pitch your solution to the problem, and we will review and label the issue Hacktoberfest if it makes sense.

We also have community rewards every month for everything from cool projects, helpful community members, and even just sick memes. If you’re interested in contributing, being an active community member is also a good way to go.
