### ISSUE TITLE
📚 Documentation:  Add Shield badges to README.md

### ISSUE THREAD

**Issue by BandhiyaHardik** [appwrite/appwrite#6917]
### 💭 Description

Appwrite is trending on GitHub and receiving a lot of contributions during Hacktoberfest. Adding some shield badges to the README.md would help showcase some key project statistics and metrics in an eye-catching way.

Suggested Shield Badges :
<li> Open Issues
<li> Pull Requests
<li> Stars
<li> Forks
<li> Commit Activity
<li> Version
<li> License

Before Suggested Shield Badges :- 
![image](https://github.com/appwrite/appwrite/assets/110784317/bf9b3a0b-0ae0-43a0-9d91-8ada44740ba5)

By Adding Suggested Shield Badges :-
![image](https://github.com/appwrite/appwrite/assets/110784317/a14ac296-05cd-4ddc-afa0-bfcb94893afc)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by BandhiyaHardik** [comment]
Can anyone please assign this issue to me ?

**Comment by HeetVekariya** [comment]
I would like to work on this issue, can you please assign this issue to me.

**Comment by stnguyen90** [comment]
Hi, thank you for your interest in participating in Hacktoberfest!

We really appreciate your enthusiasm.

So this year, we’re focused on quality contributions. This doesn’t just mean we want quality code from contributors; we also want to foster a quality relationship with the contributors through extensive reviews and support so they can tackle more meaningful and difficult projects.

With that said, we have a small team with limited capacity. So we’re careful about how many active issues we post for Hacktoberfest, so we can review and support each contributor adequately. 

That said, if you find a reasonably sized issue on the Appwrite repo that you’d like to tackle, you can pitch your solution to the problem, and we will review and label the issue Hacktoberfest if it makes sense.

We also have community rewards every month for everything from cool projects, helpful community members, and even just sick memes. If you’re interested in contributing, being an active community member is also a good way to go.
