### ISSUE TITLE
🐛 Bug Report: Feedback form not working (CORS issue)

### ISSUE THREAD

**Issue by minecrawler** [appwrite/appwrite#6922]
### 👟 Reproduction steps

1. Login to Console
2. Press Feedback in top right corner
3. Fill in form
4. Click "Submit"
5. ERROR

### 👍 Expected behavior

Form submits successfully

### 👎 Actual Behavior

Network error message pops up

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Firefox

![image](https://github.com/appwrite/appwrite/assets/1130708/e46b816b-b8e6-495a-9a81-da97743677f0)

![image](https://github.com/appwrite/appwrite/assets/1130708/340bf80d-92cd-4ba5-94c5-3e3784b1ab1d)

![image](https://github.com/appwrite/appwrite/assets/1130708/8143f036-95dd-4ef9-a906-a8bc72158c23)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by PineappleIOnic** [comment]
Hey There, I'm struggling to reproduce this as it appears to be working now, at least on my end. Could you please send me what browser you were using and could you try again, I think some certs went a little weird on the server.

**Comment by minecrawler** [comment]
I was using Firefox 118.0.2 (x64) on Windows 11.

I just sent test feedback (sorry team!) and it went through successfully :)
