### ISSUE TITLE
🐛 Bug Report: text not visible in select menu

### ISSUE THREAD

**Issue by PankajKumar1947** [appwrite/appwrite#6925]
### 👟 Reproduction steps

During reading documentation, I noticed it.
please visit this link and check select menu.
https://appwrite.io/docs/products/auth/quick-start

### 👍 Expected behavior

Text color should be different so that it becomes visible.

Similar issues is there in any select menu option in another routes

### 👎 Actual Behavior

Refer this screenshot
![Screenshot (49)_LI](https://github.com/appwrite/appwrite/assets/130830370/c168c06d-0830-4b53-ab9e-1322fc0fc28f)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by AAKASHBANSAL96** [comment]
@PankajKumar1947 Could you please assign this to me?

**Comment by AbhinayPoloju** [comment]
Assign this to me , this wil be my first issue.I will fix it.

**Comment by saswatdas121** [comment]
I want to work on it. Can you assign it to me?

**Comment by Haimantika** [comment]
Hi @PankajKumar1947 I just tried replicating the issue and it looks fine to me
<img width="1510" alt="Screenshot 2023-10-16 at 2 57 27 PM" src="https://github.com/appwrite/appwrite/assets/32809211/db8da9ba-08f0-407c-a25d-cf0e0798a3a0">

**Comment by PankajKumar1947** [comment]
> Hi @PankajKumar1947 I just tried replicating the issue and it looks fine to me
> <img width="1510" alt="Screenshot 2023-10-16 at 2 57 27 PM" src="https://github.com/appwrite/appwrite/assets/32809211/db8da9ba-08f0-407c-a25d-cf0e0798a3a0">
> 

i think your browser default is in dark mode please check by changing default

**Comment by PankajKumar1947** [comment]
Now, it is improved.
