### ISSUE TITLE
Add the ability to have management front end served on separate port.

### ISSUE THREAD

**Issue by ardevd** [appwrite/appwrite#693]
Would be very useful to have the management front end listening on a different port than the user facing APIs. I don't want to expose the login to the internet. :)

**Comment by eldadfux** [comment]
I would love to get more community feedback on this feature. Currently the API and dashboard are bundled together, and it would require some work to separate them.

For the meantime you can take a look here: https://medium.com/appwrite-io/you-can-now-restrict-access-to-your-appwrite-console-b8b447885289 we have covered in this post some methods to restrict access to your Appwrite console.

**Comment by ardevd** [comment]
Absolutely!

**Comment by eldadfux** [comment]
This can be achieved today by hosting the Appwrite console on a different container and blocking the default path. Not ideal solution but will still work. For now, due to lack of activity here, closing the issue.
