### ISSUE TITLE
🐛 Bug Report: Impossible to delete a project

### ISSUE THREAD

**Issue by davidizac** [appwrite/appwrite#6931]
### 👟 Reproduction steps

When I click on the delete project button, the project is not deleted

### 👍 Expected behavior

Project should be deleted

### 👎 Actual Behavior

The delete button is stuck in a disabled mode with no user interaction

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Hi @davidizac I just tried replicating the issue on my Cloud instance, and it worked perfectly. Can you try again?

**Comment by hariomch1** [comment]
@Haimantika can i work on this issue

**Comment by Haimantika** [comment]
> @Haimantika can i work on this issue

I don't think it is an issue. Since it works perfectly for me
