### ISSUE TITLE
📚 Documentation: There are no more issues in this repository

### ISSUE THREAD

**Issue by craigouma** [appwrite/appwrite#6933]
### 💭 Description

Please add more issues. Thanks!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Hi, thank you for your interest in participating in Hacktoberfest!

We really appreciate your enthusiasm.

So this year, Appwrite is focused on quality contributions. This doesn’t just mean we want quality code from contributors; we also want to foster a quality relationship with the contributors through extensive reviews and support so they can tackle more meaningful and difficult projects.

With that said, Appwrite has a small team with limited capacity. So we’re careful about how many active issues we post for Hacktoberfest, so we can review and support each contributor adequately. 

That said, if you find a reasonably sized issue on the Appwrite repo that you’d like to tackle, you can pitch your solution to the problem, and we will review and label the issue Hacktoberfest if it makes sense.

We also have community rewards here in [Discord](https://appwrite.io/discord) and GitHub every month for everything from cool projects, helpful community members, and even just sick memes. If you’re interested in contributing, being an active community member is also a good way to go.
