### ISSUE TITLE
🐛 Bug Report: CLOSE_WAIT state persists in Appwrite's Docker container with MariaDB on non-existent documentId calls.

### ISSUE THREAD

**Issue by t-hashimoto223** [appwrite/appwrite#6937]
### 👟 Reproduction steps

1. Start Appwrite server with its Docker container.
2. Invoke deleteDocument() with a non-existent documentId multiple times, preferably in the thousands.
3. After several operations, observe that Appwrite begins to hang.
4. Check for a 404 response.
5. Inspect MariaDB's port 3306 connections within the Appwrite container.
6. Identify numerous lingering CLOSE_WAIT connections.

### 👍 Expected behavior

Multiple delete operations should be handled gracefully with a 404 response and without causing Appwrite to hang or leaving CLOSE_WAIT connections to MariaDB.

### 👎 Actual Behavior

After several delete operations on non-existent documentId, Appwrite starts hanging. While 404 responses are received, multiple CLOSE_WAIT connections can be seen lingering in MariaDB's port 3306 within the Appwrite container.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite SDK: 1.4.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@t-hashimoto223, thanks for creating this issue! 🙏🏼 

@fogelito, what do you think?

**Comment by fogelito** [comment]
This sounds like a network problem rather than a bug, I will try to reproduce it 👍

**Comment by fogelito** [comment]
Hey, @t-hashimoto223,
Are you still facing this issue?
I am trying to reproduce using a 10,000-document delete 
[issues-6937](https://github.com/appwrite/appwrite/tree/issues-6937)
Did not run into this issue, I guess there are more parameters involved  , Perhaps you can add

**Comment by t-hashimoto223** [comment]
Hi @fogelito 
Thanks, try it.
i will try again tomorrow.

**Comment by t-hashimoto223** [comment]
Sorry, Not happen in my current environemnts v1.4.7
Nothing CLOSE_WAIT

@fogelito 
Please close this issue.

**Comment by fogelito** [comment]
@t-hashimoto223 Glad to hear this 👍
