### ISSUE TITLE
🐛 Bug Report: Create function overlay has wrong shade

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#6941]
### 👟 Reproduction steps

1. self host appwrite
2. switch to dark mode
3. start to create a function

### 👍 Expected behavior

The overlay color should match the new brand colors

### 👎 Actual Behavior

The overlay uses the old colors:

![image](https://github.com/appwrite/appwrite/assets/1477010/e0aee3b6-1ad0-43d2-b431-0dabf0190144)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by adarsh-jha-dev** [comment]
Hey @stnguyen90 can you please assign this issue to me too?
