### ISSUE TITLE
🐛 Bug Report: AppwriteException: null, Connection failed (0) - Function execution -server sdk access

### ISSUE THREAD

**Issue by mokamhawy** [appwrite/appwrite#6943]
### 👟 Reproduction steps

- I am self hosting using docker desktop win10
- I created a simple function that list users.
- I get error  AppwriteException: null, Connection failed (0)
```
Future<dynamic> main(final context) async {
  // Why not try the Appwrite SDK?
 
  final asd = await NetworkInterface.list();
  for (var interface in asd) {
    for (var addr in interface.addresses) {
      if (addr.type == InternetAddressType.IPv4) {
        context.log('looping...');
        context
            .log('Interface: ${interface.name}, IP address: ${addr.address}');
      }
    }
  }

  final client = Client()
      .setEndpoint('http://localhost/v1')
      .setProject(Platform.environment['APPWRITE_PROJECT_ID'])
      .setKey(Platform.environment['APPWRITE_API_KEY'])
      .setSelfSigned(status: true);
  final users = Users(client);
```

I suspect the error is from setEndpoint.

my vars:
_APP_ENV=production
_APP_DOMAIN=localhost
_APP_DOMAIN_FUNCTIONS=localhost
_APP_DOMAIN_TARGET=localhost

_APP_FUNCTIONS_RUNTIMES=node-16.0,php-8.0,python-3.9,ruby-3.0,dart-3.0
_APP_EXECUTOR_SECRET=your-secret-key
_APP_EXECUTOR_HOST=http://appwrite-executor/v1
_APP_EXECUTOR_RUNTIME_NETWORK=runtimes
OPEN_RUNTIMES_NETWORK=runtimes
_APP_FUNCTIONS_RUNTIMES_NETWORK=runtimes

### 👍 Expected behavior

get users list

### 👎 Actual Behavior

AppwriteException: null, Connection failed (0)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 🧱 Your Environment

1.4.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@mokamhawy, thanks for raising this issue! 🙏🏼 This usually happens if something is wrong with the endpoint value. Looking at your code, it looks like you're using localhost for the endpoint. This won't work because the runtime container will try to connect to itself rather than Appwrite. One option is to use the IP of your host machine on your LAN instead of localhost.

**Comment by mokamhawy** [comment]
@stnguyen90 Thank you so much. Problem solved. for those who come later.

- appwrite 1.4.5
- in dart
```dart
```

**Comment by mokamhawy** [comment]
@stnguyen90 Thank you so much. Problem solved. for those who come later.

- appwrite 1.4.5
- in dart, in function code/src
```dart
 final client = Client()
      .setEndpoint(endpoint) // http://192.168.10.38/v1 NOT http://localhost/v1
      .setProject(projectId)
      .setKey(apiKey) // this should be generated with scope of what you need to do next
      .setSelfSigned(status: true);
```
api keys from: http://localhost/console/project-888888.../overview/keys

**Comment by gvdevx** [comment]
Any chance you could add an error that detects localhost and displays this to the user. I just spent 5 hours trying to work out why my functions kept getting a ''fetch failed" error. Until I found the above telling me not to use localhost. Also your ENV variables use localhost so it isn't an error that was easily found as surely you wouldn't pass in a variable into your examples that doesn't work. ;)
