### ISSUE TITLE
🐛 Bug Report: Content accessability from Restricted Storage Buckets

### ISSUE THREAD

**Issue by mhkrvrchko** [appwrite/appwrite#6955]
### 👟 Reproduction steps

1. Create bucket in storage and fill it with video assets
2. Set the permissions of bucket that "Users" can access the content
2. Insert direct url like "https://domain/v1/storage/buckets/bucketId/files/fileId/view?project=projectId" to "src" attribute of "video" tag
3. Try to run video

### 👍 Expected behavior

The video should be playable by "logged in" users

### 👎 Actual Behavior

The video can't be played due to the 401 response, the Appwrite can't stream video by restricted permission.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I'm using Appwrite SDK for Web.

A brief description of problem: we need to have restricted access to our resources which served by Appwrite.
But actually I can't pass direct links as it isn't provide any authorization headers then.

I have 2 solutions of this issue on my side, but they have pitfalls.

**Solution 1**
```
try {
    if (!this.jwt) {
        const {
            jwt
        } = await this.account.createJWT();
        this.jwt = jwt;
    }

    if (this.blobUrls.length > 5) {
        this.blobUrls = this.blobUrls.reduce((acc, blobUrl) => {
            if (blobUrl) URL.revokeObjectURL(blobUrl);
            return acc;
        }, [] as string[]);
    }

    const response = await fetch(url, {
        headers: {
            'X-Appwrite-JWT': this.jwt,
        },
    });

    const blobUrl = URL.createObjectURL(await response.blob());

    this.blobUrls.push(blobUrl);

    return blobUrl;
} catch (e) {
    return null;
}
```

In this scenario I generate a Blob URL which can be passed to "src" attribute of "video" tag by generating of JWT token and it's usage in "X-Appwrite-JWT" header. The pitfall: file size can be large, and the end user should wait until resource would be downloaded (it doesn't streams for UI).

**Solution 2**

Service worker:

```
self.addEventListener('fetch', event => {
    const url = new URL(event.request.url);
    const searchParams = url.searchParams;
    const jwt = searchParams.get('jwt');

    // Catch our Range request from "video" tag
    if (jwt) {
        try {

            const request = event.request.clone();

            const headers = new Headers(request.headers);
            headers.append('X-Appwrite-JWT', jwt); // Add generate Token to our modified request
            headers.delete('X-Playback-Session-Id'); // Prevent bug in Safari, somewhy Appwrite doesn't accept this Header

            // Create request with removal of sensetive info like Token from GET params
            const modifiedRequest = new Request(request.url, {
                method: request.method,
                headers: headers,
                mode: 'cors',
            });

            event.respondWith(
                fetch(modifiedRequest)
            );
        } catch (e) {
            console.error(e);
        }
    }
});

```
React component: 

```
const Example = () => {
    const [videoUrl, setVideoUrl] = useState(null);

    useEffect(() => {
        generateJWTTokenByAppwriteSDK().then((jwt) => {
            // Pass the jwt to GET params of our Request which will be catched by our Service Worker
            setVideoUrl(`https://<domain>/v1/storage/buckets/<bucketId>/files/<fileId>/view?project=<projectId>**&jwt=${jwt}**`);
        })
    }, [])

    return videoUrl ? ( < video src = {
        videoUrl
    } > < /video>) : (<div>Fallback content</div > )
}
```

The solution is great, but the Firefox didn't have support yet. 
Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1465074

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
> Insert direct url like "https://domain/v1/storage/buckets/bucketId/files/fileId/view?project=projectId" to "src" attribute of "video" tag

@mhkrvrchko, the browser must send the Appwrite session cookie to the server for this to work. However, the browser is probably not sending the Appwrite session cookie because it is considered a 3rd party cookie. You can either:

1. Update your browser settings to allow 3rd party cookies
2. Set up a [custom domain](https://appwrite.io/docs/custom-domains) that is a sub-domain of your app

**Comment by mhkrvrchko** [comment]
@stnguyen90 thank you for respond, it's clarify the problem. I just checked and see that the problem then with our setup. The cookies sets to the subdomain and the other subdomain can't access them, so we will work on that on our end.
