### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by Sameercode660** [appwrite/appwrite#6962]
some day ago i create the react app with appwrite and i joined the db with it and today i add .env file with it and using the env variable for db_id and collection but it is giving me the error 500 internal error

**Comment by stnguyen90** [comment]
@Sameercode660, thanks for raising this issue! 🙏🏼 Some questions for you:

1. Is this on Appwrite Cloud?
2. Are you still experiencing this problem?
3. Do you see a 500 error when viewing the database or collection in the Appwrite console?
4. Would you please share your project ID?

**Comment by mvrec** [comment]
Always showing 500 Internal Error in dashboard Auth, database, storage, settings

**Comment by Sameercode660** [comment]
Yes, It showing in database and storage section of my project then I
switched , the. I logged in with another account now created another
project now it is working and also meanwhile many time , it shows the the
internal server error while creating the db , and and collection

**Comment by Sameercode660** [comment]
> @Sameercode660, thanks for raising this issue! 🙏🏼 Some questions for you:
> 
> 1. Is this on Appwrite Cloud?
> 2. Are you still experiencing this problem?
> 3. Do you see a 500 error when viewing the database or collection in the Appwrite console?
> 4. Would you please share your project ID?

1. Yes
2. Now, sometimes it shows
3.yes, absolutely
4. I deleted that and created new one in that error is showing rarely but showing while creating new db and collection

**Comment by stnguyen90** [comment]
@Sameercode660, you were probably experiencing this:

* https://github.com/appwrite/appwrite/discussions/6464#discussioncomment-7178972

I'm going to close this for now, but if you have a project that sometimes shows the 500 error, creating a support post on [Discord](https://appwrite.io/discord) with your project ID would be good so we can troubleshoot further.
