### ISSUE TITLE
500 internal eror

### ISSUE THREAD

**Issue by rizkiagustina33** [appwrite/appwrite#6963]
500 internal eror
![Screenshot 2023-10-20 145554](https://github.com/appwrite/appwrite/assets/107843089/78dba51e-01a5-496e-b62b-d567fd5dfc35)

**Comment by DerrickML** [comment]
My friends and I are also experiencing the same issue, specifically on Appwrite Cloud.

**Comment by rizkiagustina33** [comment]
yes sir, are you experiencing the same thing? Is this an application bug or is my code wrong?

**Comment by DerrickML** [comment]
It's not your code but it is an application bug. 
It's actually a general problem

**Comment by rizkiagustina33** [comment]
OK sir, because I'm new to using this database, is it possible that in the next few hours it will be better?

**Comment by rizkiagustina33** [comment]
Now it can run well, thank you my brother

**Comment by DerrickML** [comment]
> Now it can run well, thank you my brother

you're welcome

**Comment by stnguyen90** [comment]
@rizkiagustina33, thanks for raising this issue! 🙏🏼 It looks like you were trying to access your project before it was ready. It's related to https://github.com/appwrite/appwrite/discussions/6464#discussioncomment-7178972. As such, I'm going to close this for now.
