### ISSUE TITLE
🐛 Bug Report: Hitting MariaDB max connections limit stops attributes being created

### ISSUE THREAD

**Issue by oconr** [appwrite/appwrite#6968]
### 👟 Reproduction steps

I have recently started to hit the limit of the default MariaDB connections limit and found that when I reached that point, any new attributes or any changes to collections that I wanted to make through the console were stuck as `processing`. I am self-hosting and am hitting about 29M requests/month so not sure if this is something that has been discovered yet.

### 👍 Expected behavior

There should be the option inside `.env` to set the max connections that then gets passed through to the `docker-compose.yml` where it'll be used to set the max connections in the startup command for MariaDB.

### 👎 Actual Behavior

My newly created attributes would remain `processing` indefinitely. They do not appear in the metadata tables or in the actual table for the collection inside MariaDB so I'm kinda stuck on how to clear them.

Logs from the `appwrite-worker-databases` container show:

```
Exception: Failed to create connection: SQLSTATE[HY000] [1040] Too many connections in /usr/src/code/vendor/utopia-php/pools/src/Pools/Pool.php:193
Stack trace:
#0 /usr/src/code/src/Appwrite/Resque/Worker.php(232): Utopia\Pools\Pool->pop()
#1 /usr/src/code/app/workers/databases.php(72): Appwrite\Resque\Worker->getConsoleDB()
#2 /usr/src/code/app/workers/databases.php(41): DatabaseV1->createAttribute(Object(Utopia\Database\Document), Object(Utopia\Database\Document), Object(Utopia\Database\Document), Object(Utopia\Database\Document))
#3 /usr/src/code/src/Appwrite/Resque/Worker.php(125): DatabaseV1->run()
#4 /usr/src/code/vendor/resque/php-resque/lib/Resque/Job.php(201): Appwrite\Resque\Worker->perform()
#5 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(303): Resque_Job->perform()
#6 /usr/src/code/vendor/resque/php-resque/lib/Resque/Worker.php(242): Resque_Worker->perform(Object(Resque_Job))
#7 /usr/src/code/vendor/resque/php-resque/bin/resque(185): Resque_Worker->work('0.1', false)
#8 {main}
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I'm hosting on DigitalOcean using the one-click installer originally. I am running Appwrite 1.4.5 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Related Discord thread: https://discord.com/channels/564160730845151244/1163587248088940635

**Comment by stnguyen90** [comment]
@oconr, thanks for raising this issue! 🙏🏼 Copying your solution from Discord:

> I changed this line to add `--max-connections=500` and then just did `docker-compose restart` and it seems to have worked

https://github.com/appwrite/appwrite/blob/fc35e0f6ffd5ce7dab863515983e1495027e410c/docker-compose.yml#L808

**Comment by eldadfux** [comment]
Closing as the issue seemed to be solved.
