### ISSUE TITLE
📚 Documentation: change the twitter domain to x domain

### ISSUE THREAD

**Issue by aviiciii** [appwrite/appwrite#6972]
### 💭 Description

The twitter domain `twitter.com` in the website shoud be migrated to `x.com` to avoid future redirections.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by adarsh-jha-dev** [comment]
Hey @aviiciii , could you please assign this issue to me?

**Comment by aviiciii** [comment]
it seems that the source code for the website are not publically available yet.

**Comment by sudhanshugautam2911** [comment]
I would like to work on this issue so could you please assign me.

**Comment by AnanyaJindal1145** [comment]
Hi @aviiciii ! Can this issue be assigned to me if changes can be done?

**Comment by lalitkumawat1m** [comment]
Hey Team, I want to work on this issue please assign to me

**Comment by deanurag** [comment]
I would like to work on this issue.

**Comment by Haimantika** [comment]
Hi @aviiciii thanks for raising the issue. I just typed "x.com/appwrite" and it redirected me to "twitter.com/appwrite", as show in the picture below. So I think we are good with it :)
<img width="1442" alt="Screenshot 2023-10-26 at 8 01 58 PM" src="https://github.com/appwrite/appwrite/assets/32809211/8397a1c4-1c5c-4570-ae00-76bfc3f0f0a6">

Will be closing the issue now.
