### ISSUE TITLE
🐛 Bug Report: Cannot apply filters with value of 0 in console

### ISSUE THREAD

**Issue by sierra-hotel** [appwrite/appwrite#6979]
### 👟 Reproduction steps

Attempt to add a filter with a value of zero. The "add filter" button will be disabled as shown in this screenshot:

![image](https://github.com/appwrite/appwrite/assets/48251556/d892ce57-ab0f-4c5c-9f4a-89c613436c52)

### 👍 Expected behavior

The add filter button should add the filter

### 👎 Actual Behavior

The add filter button is not clickable. Probably because zero is falsy in Typescript and there is an "if <value>" statement somewhere that should be "if <value> == null"

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@sierra-hotel, thanks for creating this! 🙏🏼 you're right, it looks like this is happening because 0 is falsy. While fixing this, we should probably also make sure to allow passing empty string too 🧐

**Comment by nkumawat34** [comment]
I would like to work on this. Can you assign it to me.
