### ISSUE TITLE
🚀 Feature: project prefs

### ISSUE THREAD

**Issue by kaazedev** [appwrite/appwrite#6981]
### 🔖 Feature description

At the moment there is additional kv-storage for teams and users, I would like to see similar for the project.

### 🎤 Pitch

I would like to be able to store the current version of the application to check for updates (I use web technologies to develop my desktop application).

They can be accessed by any user. You can change them either through the console or through the API key with associated permissions.

```typescript
client
    .setEndpoint('https://cloud.appwrite.io/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2') // Your project ID

const promise = client.getPrefs() // will return same object like in teams api.
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This sounds similar to:

* https://github.com/appwrite/appwrite/issues/323

Can you 👍🏼 that issue and close this one as a duplicate?
