### ISSUE TITLE
🐛 Bug Report: 500 error setting relationship to empty array

### ISSUE THREAD

**Issue by Kunalgoel9** [appwrite/appwrite#6989]
### 👟 Reproduction steps

I have two collections in my servers one is users and other is leads

I created a Relationship between them as many to one like this
![image](https://github.com/appwrite/appwrite/assets/67458176/7afed8f4-52d2-4396-9b37-2fb296062d00)

Now the issue i am facing is while creating a new account of user Server 500 error occurs 
Code:

```javascript
 async createAccount({
    email,
    password,
    name,
  }: {
    email: string;
    password: string;
    name: string;
  }): Promise<any> {
    try {
      const userAccount = await this.account.create(
        ID.unique(),
        email,
        password,
        name
      );
      const data = JSON.stringify({
        userid: userAccount.$id,
        name: name,
        email: email,
        leads:[ ]<-------------  I think i am not able to send the empty leads relationship field
      });

      const usersdata = await database.createDocument(
        conf.appwriteDatabaseId,
        conf.appwriteUsersCollectionId,
        ID.unique(),
        data
      );
      await this.account.createEmailSession(email, password);

      const res = await this.account.createVerification(
        `${conf.appwriteclientURL}/verify`
      );

      if (userAccount && res) {
        return { userAccount: userAccount, res: res };
      }
    } catch (error: any) {
      console.log(error.message);

           throw error;
    }
  }
```

The main issue i think is i am adding users after authentication and i am not sendings the leads attribute relationship in data but i want the leads to be empty annd not bieng able to send the leads attribute as empty array 

### 👍 Expected behavior

It Should Create a new Document white empty leads

### 👎 Actual Behavior

It Gives Server error 500

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

    
Appwrite verision in console-->4.1.0
Appwrite library version in package.json
"appwrite": "^13.0.0"
    
i am using appwrite web SDK and i am currently using ReactJS as my frontend development  

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Kunalgoel9, thanks for creating this issue! 🙏🏼 A couple things to try:

1. No need to `JSON.stringify()` the data
2. You have a Many to One, which means a single user has a single lead. In the description of the attribute you can see "users can contain one leads". As such, please try passing null instead of an empty array. Otherwise, you may want to recreate the attribute as either a Many to Many or a One to Many depending on your requirements.

**Comment by stnguyen90** [comment]
Closing stale issue
