### ISSUE TITLE
🐛 Bug Report: Getting 500 error when accessing prop on third-party response object.

### ISSUE THREAD

**Issue by logan-waite** [appwrite/appwrite#6999]
### 👟 Reproduction steps

In an Appwrite function, I'm trying to access data from a third-party SDK, which works in other instances. However, when I try to access the data in this call, I'm getting a 500 error `An internal curl error has occurred within the executor! Error Msg: Http invalid protocol\nError Code: 500`. The error might make sense if it happened when I await the `plaid.transactionsSync` (which is the actual http call), but I know I'm getting valid data from that through logging. However, as soon as I try to access the `data` prop on that response (which I know exists), I get that 500 error.

```js
  const databases = new Databases(appwrite);

  const items = await databases.listDocuments(
    DatabaseId,
    Collection.PlaidItems,
    [Query.equal('user_id', [userId])]
  );

  const firstItem = items.documents[0];
  const request = {
    access_token: firstItem.access_token,
    cursor: null,
  };
  const response = await plaid.transactionsSync(request); // --> no error
  log(response.data); // --> error happens 
``` 

### 👍 Expected behavior

I should be able to access the property without having a 500 error.

### 👎 Actual Behavior

Attempting to access the `response.data` prop gives a `An internal curl error has occurred within the executor! Error Msg: Http invalid protocol\nError Code: 500` error.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite Node SDK v^13.0.0,

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Hi @logan-waite appreciate you bringing this up and having patience. My wild guess is, this is due to some DB issues that we had in Cloud and might have affected other services. I have asked the team for more details, will keep you updated here.

**Comment by Haimantika** [comment]
@logan-waite what endpoint have you set for the SDK inside of his function? It should be `https://cloud`

**Comment by logan-waite** [comment]
This is what I call at the top of the main body of my function:
```javascript
function createAppwriteSdk({ jwt } = { jwt: false }) {
  const client = new Client()
    .setEndpoint('https://cloud.appwrite.io/v1')
    .setProject(process.env.APPWRITE_FUNCTION_PROJECT_ID);

  if (jwt) {
    return client.setJWT(process.env.APPWRITE_USER_JWT);
  } else {
    return client.setKey(process.env.APPWRITE_API_KEY);
  }
}
```

What is odd to me is that I call similar third-party endpoints in different parts of the function, and I don't have a problem with those.

**Comment by stnguyen90** [comment]
@logan-waite, maybe there's a circular reference or something. Could you try making sure to pass a string to `log()`?

**Comment by logan-waite** [comment]
When I run the object through `JSON.stringify`, the function just silently fails.

**Comment by logan-waite** [comment]
Looks like if I remove all my log statements, I'm able to get the data back. Do you know if there are plans to make the log function more robust than just taking strings?

**Comment by stnguyen90** [comment]
@logan-waite, 

> When I run the object through `JSON.stringify`, the function just silently fails.

This will also have a problem with circular references. 

> Do you know if there are plans to make the log function more robust than just taking strings?

It's safest to only pass strings, but technically, you can pass other things. I would have expected the log call to throw an exception and then the function would return 500 failed.

**Comment by stnguyen90** [comment]
So, I just tested a function like this:

```javascript
export default async ({ req, res, log, error }) => {
  const a = {};
  const b = {a: a};
  a.b = b;

  log(a);

  // `res.json()` is a handy helper for sending JSON
  return res.json({
    motto: 'Build like a team of hundreds_',
    learn: 'https://appwrite.io/docs',
    connect: 'https://appwrite.io/discord',
    getInspired: 'https://builtwith.appwrite.io',
  });
};
```

and it did throw an error:

<img width="1472" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/5fa1e39c-6e7f-450a-98db-6a1ad5646fde">

Maybe there's something else with that `response.data` of yours. Or maybe there's too much data to log (all the logs are limited to less than 1 million characters)?
