### ISSUE TITLE
🐛 Bug Report: Enhance "Quickstart" Section with Icons/Logos

### ISSUE THREAD

**Issue by moheyt** [appwrite/appwrite#7001]
### 👟 Reproduction steps

1. Go to our website's homepage.
2. Navigate to the "Quickstart" section.
3. Observe the text-based links without icons or logos.

### 👍 Expected behavior

The expected behavior involves the integration of icons or logos that represent each link's purpose next to the corresponding links in the "Quickstart" section. This approach enhances the overall user experience and reinforces our brand identity, making it easier for users to access the resources they need.

### 👎 Actual Behavior

In the current website, the "Quickstart" section provides important links to resources, documents, and actions to help users get started quickly. However, these links are text-based, which may not be the most user-friendly approach. Users often process visual information more quickly and accurately than text, and the use of icons or logos alongside these links can significantly improve user engagement and recognition.

We need to enhance the "Quickstart" section by integrating icons or logos representing each link's purpose. This will not only make it easier for users to identify and access the resources they need but also contribute to a more cohesive and visually appealing website.

![Screenshot 2023-10-24 211544](https://github.com/appwrite/appwrite/assets/85775976/7842c14e-1a38-41c8-8698-9a8b249c0f43)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by moheyt** [comment]
I would like to work on this. Can you assign it to me?

**Comment by itsayopapi** [comment]
@abnegate can i work on this issue?

**Comment by Haimantika** [comment]
Hi @moheyt thanks for raising this issue. This is not a bug and has been designed that way. We have text-based links there and icon-based links in the homepage like this 👇 
<img width="1512" alt="Screenshot 2023-10-26 at 5 17 33 PM" src="https://github.com/appwrite/appwrite/assets/32809211/fc40a7ef-fb38-4957-a37c-e9eda07b493e">

**Comment by nick2432** [comment]
can i work on this?

**Comment by sara-k-48** [comment]
@moheyt thank you for your suggestion. While I understand your reasoning, we prefer to keep the logos out of the footer, to keep the footer clean. So, this is not a bug; this was how it was intended to be.
