### ISSUE TITLE
🐛 Bug Report: Nullable Date cant be set back to null in web ui

### ISSUE THREAD

**Issue by Schrolli91** [appwrite/appwrite#7004]
### 👟 Reproduction steps

I have a DateTime attribute in a collection which is nullable.
After i set a date, its not possible to reset the date to null.
![image](https://github.com/appwrite/appwrite/assets/6043382/b407075e-abf2-4a89-8377-7d862878d204)
I can reset and update the date, but the Button will be active an the date will be available after the tap.

### 👍 Expected behavior

Date should be nullable on web ui backend

### 👎 Actual Behavior

Date is never reset to null

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sahalsaad** [comment]
Hi, can I work on this issue? Thank you

**Comment by sahalsaad** [comment]
Hi @Haimantika , I created a PR to solve this issue. Can you label it for hacktoberfest? Thank you
