### ISSUE TITLE
🚀 Feature: The Buttons in the Header Section Lacks Transition

### ISSUE THREAD

**Issue by DeepRahangdale** [appwrite/appwrite#7012]
### 🔖 Feature description

When hovering over an element, apply a smooth transition effect with a scale change from 95% to 105% to create a subtle zoom-in and out effect, enhancing the user interaction and visual feedback.

### 🎤 Pitch

Similar to this site.
https://drive.google.com/file/d/1Gm2KpWL_40dTaTYSwiTKyI3HPI0nPcQw/view?usp=sharing
Assign me if Needed.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by adarsh-jha-dev** [comment]
Hey @DeepRahangdale , could you please assign me this issue?

**Comment by Haimantika** [comment]
Hi @DeepRahangdale thanks for the raising the feature request. Tagging @TGlide, he can add better about animation.

**Comment by TGlide** [comment]
At first glance, I'd say this is not needed, as we already have hover states for interactible elements.

https://github.com/appwrite/appwrite/assets/26071571/c825ef88-6feb-4239-b37c-a4daccef5920

**Comment by uttampun44** [comment]
I think the hover transition is smooth. There is no need to add more transitions. Still, if you want to add a transition, assign it to me.

**Comment by DeepRahangdale** [comment]
https://drive.google.com/file/d/1QBzUzMiCLIFzs152A9nvHpUspr5xYKmp/view?usp=sharing
@TGlide was talking about this, transition is quite simple!!

**Comment by TGlide** [comment]
> [drive.google.com/file/d/1QBzUzMiCLIFzs152A9nvHpUspr5xYKmp/view?usp=sharing](https://drive.google.com/file/d/1QBzUzMiCLIFzs152A9nvHpUspr5xYKmp/view?usp=sharing) @TGlide was talking about this, transition is quite simple!!

We also already have hover states there, which is a color transition. Replacing it with a scale transition would not be ideal, as it would exclude people who have `prefers-reduced-motion` set. 

The only possibility would be adding the scale transition together with the color transition, but in my opinion that would be quite distracting and detrimental to user experience.

**Comment by DeepRahangdale** [comment]
yeah Correct!!
