### ISSUE TITLE
🐛 Bug Report: How can we use updateLabels?

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [appwrite/appwrite#7029]
### 👟 Reproduction steps

As mentioned in appwrite docs to use updateLabeles:

```javascript
const sdk = require('node-appwrite');

const client = new sdk.Client()
    .setEndpoint('https://cloud.appwrite.io/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2')                 // Your project ID
    .setKey('98fd4...a2ad2');                    // Your secret API key

const users = new sdk.Users(client);

const promise = users.updateLabels(
    '[USER_ID]',
    [ 'subscriber' ]
);

promise.then(function (response) {
    console.log(response); // Success
}, function (error) {
    console.log(error); // Failure
});
```

### 👍 Expected behavior

It should update user labels

### 👎 Actual Behavior

It is not updating user labels

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@SMARTMICROWORLD, thanks for raising this issue! 🙏🏼 Would you please share the logged result, whether it was the response or error?

**Comment by SMARTMICROWORLD** [comment]
> @SMARTMICROWORLD, thanks for raising this issue! 🙏🏼 Would you please share the logged result, whether it was the response or error?

not getting any log also not getting suggestion of updateLabels after (users.suggestion Of UpdateLabeles) getting all other suggestions. Actually it is cloud function:

import {
  Client,
  Databases,
  Account,
  Functions,
  ID,
  Permission,
  Query,
  Users,
} from "node-appwrite";

const appwriteUsers = new Users(appwriteClient);

appwriteUsers.updateLabels(requestData.data.$id, "Premium");

**Comment by stnguyen90** [comment]
Glad you figured it out!
