### ISSUE TITLE
🚀 Feature: Add AVIF on image transformations

### ISSUE THREAD

**Issue by katriellucas** [appwrite/appwrite#7043]
### 🔖 Feature description

Add AVIF as an output on image transformations for **Storage** product.

### 🎤 Pitch

AVIF is already supported by major browsers, [caniuse](https://caniuse.com/avif), it has better compression with a superior image quality and uses less space than WebP, consequently using less bandwidth when serving. It would be nice to have this option when uploading images.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
We already have a few pending PRs for this. If everything works well, it might make it into 1.5 release 👍
