### ISSUE TITLE
🐛 Bug Report:  "Utopia\\Migration\\Resources\\Auth\\User::__construct(): Argument #11 ($disabled) must be of type bool, null given, called in /usr/src/code/vendor/utopia-php/migration/src/Migration/Sources/Firebase.php on line 217"   ]

### ISSUE THREAD

**Issue by cloudoftg0** [appwrite/appwrite#7052]
### 👟 Reproduction steps

When I tried to migrate from firebase to appwrite cloud
There are step mentioned in migration process to upload json file to appwrite, but there is no way to upload json file service account, so i just pasted the json file text and I selected users and database to migrate  then it failed and this is the error log 
" "Utopia\\Migration\\Resources\\Auth\\User::__construct(): Argument #11 ($disabled) must be of type bool, null given, called in /usr/src/code/vendor/utopia-php/migration/src/Migration/Sources/Firebase.php on line 217"
  ]"

Appwrite version 
Version 1.4.7

### 👍 Expected behavior

It should migrated successfully but it failed

### 👎 Actual Behavior

It failed with this error 
"Utopia\\Migration\\Resources\\Auth\\User::__construct(): Argument #11 ($disabled) must be of type bool, null given, called in /usr/src/code/vendor/utopia-php/migration/src/Migration/Sources/Firebase.php on line 217"
  ]"

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Something else

### 🧱 Your Environment

[Version 1.4.7](https://github.com/appwrite/appwrite/releases)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
@PineappleIOnic can you help here?

**Comment by PineappleIOnic** [comment]
Hey There 👋, We have a PR for this issue here: https://github.com/utopia-php/migration/pull/22 which will be merged soon.

**Comment by cloudoftg0** [comment]
that PR solved the previous issue but now it is giving another error     "Failed to transfer resource 'zyjCn2PQbYNg5VNfp85Bw47J17I2:user' with message 'Invalid `passwordSalt` param: Value must be a valid string and at least 1 chars and no longer than 128 chars'"" 
where "zyjCn2PQbYNg5VNfp85Bw47J17I2:user" is different for each user. Any workaround?

**Comment by stnguyen90** [comment]
@cloudoftg0 feel free to comment in https://github.com/appwrite/appwrite/issues/8376 about your new error.
