### ISSUE TITLE
🐛 Bug Report: Server Error, already existed ID, using relationships, create document

### ISSUE THREAD

**Issue by mokamhawy** [appwrite/appwrite#7054]
### 👟 Reproduction steps

- Create a collection A with an attribute relationship to collection B
- Then create a doc of Collection A with attribute to id1 in collection B
- Then create another doc of Collection A with attribute to also id1 in collection B
- error
![image](https://github.com/appwrite/appwrite/assets/82515166/7cadff08-c05c-4b48-9c59-4c2eabbc0166)

### 👍 Expected behavior

To add the new document normally with its unique id

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/82515166/7cadff08-c05c-4b48-9c59-4c2eabbc0166)

logs
```
appwrite  | [Error] Method: POST
appwrite  | [Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
appwrite  | [Error] Type: Appwrite\Extend\Exception
appwrite  | [Error] Message: Document with the requested ID already exists. Try again with a different ID or use ID.unique() to generate a unique ID.
appwrite  | [Error] File: /usr/src/code/app/controllers/api/databases.php
appwrite  | [Error] Line: 2913
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Selfhosted
Permissions all any 
appwrite Version 1.4.8

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by mokamhawy** [comment]
## Workaround solution for now:
- Use CLI instead of Console.
- example
```powershell
appwrite databases createDocument --databaseId 653dfc1e56191105cdae --collectionId collectionFormula --documentId 'unique()' --data '{"name": "super name"}'
```

**Comment by mokamhawy** [comment]
The issue was the relation type
Wrong ❌❌❌ => one to one
Correct ✅✅✅ => many to one

**Comment by UniverseVG** [comment]
> The issue was the relation type Wrong ❌❌❌ => one to one Correct ✅✅✅ => many to one

thanks a lot, I was able to find the solution in my project
