### ISSUE TITLE
🐛 Bug Report: Could not resolve host: appwrite-executor with status code 0

### ISSUE THREAD

**Issue by egortabula** [appwrite/appwrite#7064]
### 👟 Reproduction steps

1. I created a new default dart function with Appwrite CLI (appwrite init function)
2. I deployed this function with Appwrite Cli (appwrite deploy function)
![code](https://github.com/appwrite/appwrite/assets/64892468/792a3223-1c51-4851-95b3-85004f8989d5)

### 👍 Expected behavior

It should have deployment status "Ok" in appwrite console

### 👎 Actual Behavior

My deployment status is **Failed**. 
in function logs: Could not resolve host: appwrite-executor with status code 0
<img width="1322" alt="Screenshot 2023-11-01 at 01 01 07" src="https://github.com/appwrite/appwrite/assets/64892468/525e5b91-c41c-4bee-a422-c8f48477cd17">

`docker logs appwrite-worker-builds` result:
<img width="1034" alt="Screenshot 2023-11-01 at 01 02 38" src="https://github.com/appwrite/appwrite/assets/64892468/8ad70436-c802-4842-a084-f93f0edde5a5">

`docker logs openruntimes-executor` result:
<img width="452" alt="Screenshot 2023-11-01 at 01 10 33" src="https://github.com/appwrite/appwrite/assets/64892468/65155f90-c744-4571-bbf0-a7ad8990c2fc">

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

- Appwrite 1.4.8

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Thanks for raising this issue! 🙏🏼 Some questions for you:

1. Was this a clean install of 1.4.8 or did you upgrade to it?
2. Were you ever able to execute any functions?
3. Would you please share your docker-compose.yml file?

**Comment by mokamhawy** [comment]
in you appwrite folder, you will find docker-compose.yml

**Comment by egortabula** [comment]
> in you appwrite folder, you will find docker-compose.yml

[docker-compose.txt](https://github.com/appwrite/appwrite/files/13224732/docker-compose.txt)

**Comment by stnguyen90** [comment]
@egortabula did you copy and paste manually or something? There seems to be a lot missing and some things are invalid 🧐

**Comment by egortabula** [comment]
yes i copy paste docker-compose manualy

> @egortabula did you copy and paste manually or something? There seems to be a lot missing and some things are invalid 🧐

Yes, i copy paste docker-compose manualy.

**Comment by stnguyen90** [comment]
@egortabula would you please try again, making sure to copy all the data exactly?

**Comment by egortabula** [comment]
I completely reinstalled appwrite (1.4.9) and everything worked for me. Probably somehow I didn't update correctly. Thanks for the help!
