### ISSUE TITLE
🐛 Bug Report: Throwing 500 error on all the pages for projects

### ISSUE THREAD

**Issue by Utkarshn10** [appwrite/appwrite#7065]
### 👟 Reproduction steps

Open a project and go to Auth or any other section except Overview

### 👍 Expected behavior

It should show data. 

### 👎 Actual Behavior

APIs are failing for all the pages of a project.

![image](https://github.com/appwrite/appwrite/assets/58587256/c34b0b9b-9a02-4030-a1e3-46b1bcb67251)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Utkarshn10** [comment]
After 15 mins of inactivity, it seems to be working. Keeping the issue open so that we can take a look and find out where the problem occurred.

**Comment by skyface753** [comment]
Same error here.

Logs from appwrite container:
```bash
[Error] Timestamp: 2023-11-01T09:46:16+00:00
[Error] Method: GET
[Error] URL: /v1/account
[Error] Type: Appwrite\Extend\Exception
[Error] Message: User (role: guests) missing scope (account)
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 556
[Error] Timestamp: 2023-11-01T09:46:17+00:00
[Error] Method: GET
[Error] URL: /v1/account
[Error] Type: Appwrite\Extend\Exception
[Error] Message: User (role: guests) missing scope (account)
[Error] File: /usr/src/code/app/controllers/general.php
[Error] Line: 556
[Error] Timestamp: 2023-11-01T09:46:34+00:00
[Error] Method: GET
[Error] URL: /v1/projects
[Error] Type: Utopia\Database\Exception
[Error] Message: Filter not found
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 4643
```

**Comment by Utkarshn10** [comment]
I don't think this is a related error. The error you are facing is because of the permissions of the user.

**Comment by Haimantika** [comment]
Hi @Utkarshn10 hopefully this is solved now? We had some ongoing issues in Cloud.

**Comment by Utkarshn10** [comment]
Hey @Haimantika yes its working now. Thanks

**Comment by Haimantika** [comment]
Thanks for the confirmation @Utkarshn10 . Will be closing it then.
