### ISSUE TITLE
🐛 Bug Report: Appwrite manual installation throwing "Failed to connect to database" error

### ISSUE THREAD

**Issue by patrickc-sb** [appwrite/appwrite#7068]
### 👟 Reproduction steps

Hello,
I'm having some trouble with the manual installation steps on Ubuntu22.04. I've made my changes in the .env file and ran `docker compose up -d --remove-orphans`. After that, judging from the output, everything looks fine. But when I look in the Appwrite container logs I find a database connection error and appwrite also doesnt start properly. I checked in the mariadb container, the credentials I set in the .env file are valid and I can connect to the database. 

### 👍 Expected behavior

It should install with docker-compose properly with all the changes from the .env file and be reachable over the configured domain.

### 👎 Actual Behavior

Database connection not working. Appwrite container logs showing error:
```
Database not ready. Retrying connection (1)...
Database not ready. Retrying connection (2)...
Database not ready. Retrying connection (3)...
Database not ready. Retrying connection (4)...
Database not ready. Retrying connection (5)...
Database not ready. Retrying connection (6)...
Database not ready. Retrying connection (7)...
Database not ready. Retrying connection (8)...
Database not ready. Retrying connection (9)...
Database not ready. Retrying connection (10)...

Fatal error: Uncaught Exception: Failed to connect to database: Failed to create connection: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? in /usr/src/code/app/http.php:82
Stack trace:
#0 {main}
  thrown in /usr/src/code/app/http.php on line 82
[2023-11-01 23:19:49 *97.0]	ERROR	php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Exception: Failed to connect to database: Failed to create connection: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? in /usr/src/code/app/http.php:82
Stack trace:
#0 {main}
  thrown in /usr/src/code/app/http.php on line 82
```

Checked mariadb container, shows no error. Verified database credentials from .env file are working with mariadb container.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use a Hetzner Cloud server (CPX21) with Ubuntu 22.04 and am trying to install AppWrite 1.4.8. I always create a separate user for all the docker stuff and run the docker compose command with this user.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by patrickc-sb** [comment]
I've also found that the containers `appwrite-schedule`, `appwrite-maintenance` and `appwrite-usage` are throwing errors and keep restarting. Error in the logs:

`Failed to create connection: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?`

I guess this is because the database connection has a problem.

**Comment by stnguyen90** [comment]
@patrickc-sb, thanks for creating this issue! 🙏🏼 

> I've made my changes in the .env file and ran docker compose up -d --remove-orphans

Did you already have Appwrite running before you did this? If so, updating the database password in the .env file doesn't actually change the database password. You'll need to follow the usual mysql/mariadb steps to update the password in the database.

**Comment by patrickc-sb** [comment]
Hey @stnguyen90,
thanks for your reply! Yeah, so first I just ran the docker-compose command but got a bunch of failures. Then I ran the docker run command first and then the docker-compose command (with the changed .env-file). Ok, if the password wont be changed then that makes sense.
I'd just like to outline this here really quick for my understanding. So the steps for the manual installation would be:

1. Run the `docker run` command
2. Change mariadb password
3. Adjust the .env file
4. Run `docker compose` command

What do you think, does that cover it?

**Comment by patrickc-sb** [comment]
@stnguyen90 
So I reinstalled Appwrite with the described steps but am still getting the same error (I changed the mariadb root pw and user + pw). However, I checked the mariadb logs again and found the following error:
```
2023-11-02 16:55:59 288 [Warning] Access denied for user '$MYUSER'@'172.25.0.19' (using password: YES)
```

This error also appears from other containers. In this case this is `appwrite-realtime`. When I try to connect to the mariadb container using the normal mysql-client I can connect. It seems though that the containers cant connect.

**Comment by stnguyen90** [comment]
@patrickc-sb 

> Run the `docker run` command

I assume you're referring to the [Installing with Docker](https://appwrite.io/docs/advanced/self-hosting#install-with-docker)? (Btw, this isn't the manual installation approach. Our manual installation approach is actually unavailable at the moment).

> What do you think, does that cover it?

Sure, that works. 

To give more context/background, mariadb initializes the database on first start using the various env vars for the root password, database, etc. After that, those env vars aren't used. As such, an alternative is to use the Docker install method to generate the files, but then wipe your Appwrite instance with `docker compose down -v`. Then, when you start the entire stack, mariadb is recreated with the new values you set in the .env file.

**Comment by stnguyen90** [comment]
@patrickc-sb,

> ```
> 2023-11-02 16:55:59 288 [Warning] Access denied for user '$MYUSER'@'172.25.0.19' (using password: YES)
> ```

Maybe $MYUSER is being passed in instead of your actual user?

**Comment by patrickc-sb** [comment]
@stnguyen90 
Sorry, $MYUSER stands for the username I gave the db user, it's not acutally the username.

> I assume you're referring to the [Installing with Docker](https://appwrite.io/docs/advanced/self-hosting#install-with-docker)? (Btw, this isn't the manual installation approach. Our manual installation approach is actually unavailable at the moment).

Yeah basically. More specifically the manual part below using docker-compose.

> To give more context/background, mariadb initializes the database on first start using the various env vars for the root password, database, etc. After that, those env vars aren't used. As such, an alternative is to use the Docker install method to generate the files, but then wipe your Appwrite instance with docker compose down -v. Then, when you start the entire stack, mariadb is recreated with the new values you set in the .env file.

Thats what I initally figured. It didnt work for me though unfortunately. I also tried again, I wiped down my installation and started the stack with `docker compose up -d --remove-orphans` with the adjusted .env file in the same directory as the docker-compose.yml. The values seem to be set but I can only connect to the database from within the `appwrite-mariadb` container.

**Comment by stnguyen90** [comment]
@patrickc-sb,

> I wiped down my installation

How did you do that?

> The values seem to be set

How did you verify that?

**Comment by patrickc-sb** [comment]
@stnguyen90 

> How did you do that?
I did the wipe using the command you mentioned in your previous post `docker compose down -v`.

> How did you verify that?
I did a `docker exec` into the `appwrite-mariadb` container and connected to the database from within the container with the mysql-client. This worked and I could connect with both accounts, normal user account and root account with the adjusted credentials from the .env-file.
If I try to connect with the mysql-client from outside of the container none of the accounts work.

**Comment by stnguyen90** [comment]
@patrickc-sb, does your password have a `$` in it?

**Comment by patrickc-sb** [comment]
@stnguyen90 
Just checked, unfortunately no the passwords are alpha-numerical.

**Comment by stnguyen90** [comment]
@patrickc-sb,

Did you say everything looks fine if you check the value via `docker compose exec appwrite vars`?

Also, is the user just alpha-numeric too?

**Comment by patrickc-sb** [comment]
@stnguyen90 

Sure the `docker compose exec appwrite vars` output looks fine, I'd say. db user, password and root password are alpha-numerical values. Though there is some other env var secrets that are not alpha-numerical. Specifically `_APP_OPENSSL_KEY_V1`, `_APP_REDIS_PASS`, `_APP_SMTP_PASSWORD` and `_APP_EXECUTOR_SECRET`. They also have special characters but no `$`. I usually wrap values with special characters in \'\', so far I havent had a problem with that.

**Comment by patrickc-sb** [comment]
@stnguyen90 
So I ran some more tests this morning & I did another wipe down with `docker compose up -d --remove-orphans` and removed all the docker images. I ran the `docker run` install command again and with the default .env file & AppWrite came up successfully.

After that I switched all the relevant and set secrets and passwords in the .env file to alpha-numiercal values to remove any special characters that could break the setup. There is only `_APP_SMTP_PASSWORD` remaining that has special characters in it. But I also removed the SMTP values from the .env file. 
Unfortunately I'm still having the same issue, `docker logs appwrite` is still showing `Failed to connect to database` as described in the posts above. Containers `appwrite-schedule`, `appwrite-usage` & `appwrite-maintenance` keep restarting every couple of seconds showing the following error:

```
Failed to create connection: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
```

However, after the last wipe down `appwrite-mariadb` got recreated properly and I can access the database from "outside" with my set db username and password. `mariadb` logs also dont show any failing connection attempts. Now I'm wondering if the problem even is with the `mariadb` connection ... 

Did you have any success reproducing the issue or does it work normally for you?

**Comment by stnguyen90** [comment]
@patrickc-sb,

> However, after the last wipe down appwrite-mariadb got recreated properly

Do you mean you updated the .env file and then ran this?

```
docker compose down -v
docker compose up -d
```

> `mariadb` logs also dont show any failing connection attempts

But Appwrite still doesn't work? Can you try forcing the containers to retry connecting again? The easiest way to do this is to run `docker compose restart`. Or you can individually restart the appwrite containers.

**Comment by patrickc-sb** [comment]
@stnguyen90 

> Do you mean you updated the .env file and then ran this?

Yes, first `docker compose down -v` and then `docker compose up -d --remove-orphans`.
Just tried restarting the individual containers as you said with `docker compose restart` but the three mentioned containers are still restarting and throwing the same errors. The `appwrite` container also still has the same error.

Is it maybe necessary to install Appwrite on the root user of the server? I execute the docker commands from a dedicated user that I wanted to use for the docker stuff. Maybe I'll try that out, I dont really know what to do anymore...

**Comment by stnguyen90** [comment]
@patrickc-sb,

FYI, here's an update to my .env file and the result of running:

```
docker compose down -v
docker compose up -d
```

<img width="1246" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/3f2bc8e8-5535-4671-9072-16e0621a2dd3">

> Is it maybe necessary to install Appwrite on the root user of the server?

The user just needs to have access to use docker which usually includes adding the user to the docker group.

> I dont really know what to do anymore...

Would you be able to share a .env file and docker-compose.yml file that has the problem so I can try and reproduce?

**Comment by patrickc-sb** [comment]
@stnguyen90 
Great news, I have it up and running. I reduced my .env file to the vars that you have set, wiped down the installation and tried again. After doing some trial and error I think the problem was that I set the `_APP_REDIS_USER` & `_APP_REDIS_PASS` vars.

Thanks so much for your help and effort! Really appreciate it!

**Comment by stnguyen90** [comment]
> After doing some trial and error I think the problem was that I set the `_APP_REDIS_USER` & `_APP_REDIS_PASS` vars.

Ahh yes. That is probably related to https://github.com/appwrite/appwrite/issues/3309. The library we are/were using doesn't support passing a user and password. We are moving off of that library, though, so, hopefully, we can get the related issue fixed in the near future.

For now, I'm going to close this as resolved. Thanks for your patience!

**Comment by DivyakantSwarnkar01** [comment]
> ### 👟 Reproduction steps
> Hello, I'm having some trouble with the manual installation steps on Ubuntu22.04. I've made my changes in the .env file and ran `docker compose up -d --remove-orphans`. After that, judging from the output, everything looks fine. But when I look in the Appwrite container logs I find a database connection error and appwrite also doesnt start properly. I checked in the mariadb container, the credentials I set in the .env file are valid and I can connect to the database.
> 
> ### 👍 Expected behavior
> It should install with docker-compose properly with all the changes from the .env file and be reachable over the configured domain.
> 
> ### 👎 Actual Behavior
> Database connection not working. Appwrite container logs showing error:
> 
> ```
> Database not ready. Retrying connection (1)...
> Database not ready. Retrying connection (2)...
> Database not ready. Retrying connection (3)...
> Database not ready. Retrying connection (4)...
> Database not ready. Retrying connection (5)...
> Database not ready. Retrying connection (6)...
> Database not ready. Retrying connection (7)...
> Database not ready. Retrying connection (8)...
> Database not ready. Retrying connection (9)...
> Database not ready. Retrying connection (10)...
> 
> Fatal error: Uncaught Exception: Failed to connect to database: Failed to create connection: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? in /usr/src/code/app/http.php:82
> Stack trace:
> #0 {main}
>   thrown in /usr/src/code/app/http.php on line 82
> [2023-11-01 23:19:49 *97.0]	ERROR	php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught Exception: Failed to connect to database: Failed to create connection: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? in /usr/src/code/app/http.php:82
> Stack trace:
> #0 {main}
>   thrown in /usr/src/code/app/http.php on line 82
> ```
> 
> Checked mariadb container, shows no error. Verified database credentials from .env file are working with mariadb container.
> 
> ### 🎲 Appwrite version
> Version 1.4.x
> 
> ### 💻 Operating system
> Linux
> 
> ### 🧱 Your Environment
> I use a Hetzner Cloud server (CPX21) with Ubuntu 22.04 and am trying to install AppWrite 1.4.8. I always create a separate user for all the docker stuff and run the docker compose command with this user.
> 
> ### 👀 Have you spent some time to check if this issue has been raised before?
> * [x]  I checked and didn't find similar issue
> 
> ### 🏢 Have you read the Code of Conduct?
> * [x]  I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

How to solve as I am also having same trouble?

**Comment by patrickc-sb** [comment]
Hey @DivyakantSwarnkar01,

for me it it worked to set only the .env-vars in the screenshot of @stnguyen90's post below in the .env-file.

> @patrickc-sb,
> 
> FYI, here's an update to my .env file and the result of running:
> 
> ```
> docker compose down -v
> docker compose up -d
> ```
> 
> <img alt="image" width="1246" src="https://private-user-images.githubusercontent.com/1477010/281839749-3f2bc8e8-5535-4671-9072-16e0621a2dd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzMwMTIsIm5iZiI6MTcxMzc3MjcxMiwicGF0aCI6Ii8xNDc3MDEwLzI4MTgzOTc0OS0zZjJiYzhlOC01NTM1LTQ2NzEtOTA3Mi0xNmUwNjIxYTJkZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMDc1ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ViNmQ0NmI3NTk0YjViODI2NzczN2ExODM1OWY3MWU4ZDExNmMyYThmNTkxMjc5ZjViMmMwZmIzOGYyN2U0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NBACLaarcikKkFDlifkKb1wB9sDSyQCXsRswDLcpBnk">
> 
> > Is it maybe necessary to install Appwrite on the root user of the server?
> 
> The user just needs to have access to use docker which usually includes adding the user to the docker group.
> 
> > I dont really know what to do anymore...
> 
> Would you be able to share a .env file and docker-compose.yml file that has the problem so I can try and reproduce?

Then wipe down the installation with `docker compose down -v` and after that reinstall with `docker compose up -d --remove-orphans`. After that the error disapeared and AppWrite was installed properly.

Hope that helps!

**Comment by lerminou** [comment]
I have the same error but with a mysql 8 server, is it compatible ? @stnguyen90

**Comment by Ahmedsaed** [comment]
> > After doing some trial and error I think the problem was that I set the `_APP_REDIS_USER` & `_APP_REDIS_PASS` vars.
> 
> Ahh yes. That is probably related to [#3309](https://github.com/appwrite/appwrite/issues/3309). The library we are/were using doesn't support passing a user and password. We are moving off of that library, though, so, hopefully, we can get the related issue fixed in the near future.
> 
> For now, I'm going to close this as resolved. Thanks for your patience!

I have just wasted hours trying to understand why the production deployment is not working. Why do we even have env variables for the redis user and password if we are not going to use them? Even if the project doesn't support passing a user yet, The deployment shoudn't fail or at least display a good error message.
