### ISSUE TITLE
🐛 Bug Report: Bug regarding create_executions in Python

### ISSUE THREAD

**Issue by sgaabdu4** [appwrite/appwrite#7079]
### 👟 Reproduction steps
Hello,
I'm getting this error when running `https://cloud.appwrite.io/v1/functions/[FUNCTION_ID]/executions`

Output:
`{"message":"Server Error","code":500,"type":"general_unknown","version":"0.11.25"}
`

My python code snippet is as follows:
```
    client = Client()
    functions = Functions(client)
    client.set_endpoint('ENDPOINT').set_project('PROJECT_ID').set_key(
        'API_KEY').set_self_signed(True)
    functions.create_execution(
        function_id='FUNCTION_ID')
```

For some reason, using python, I'm not able to create executions of the cloud function. Could you please look into why?

### 👍 Expected behavior
It should be able to execute the cloud function

### 👎 Actual Behavior
Getting this error
Output:
`{"message":"Server Error","code":500,"type":"general_unknown","version":"0.11.25"}
`

### 🎲 Appwrite version
Version 1.4.x /Appwrite cloud

### 💻 Operating system
Mac M1 Sonoma 14.1

### 🧱 Your Environment
I'm using Appwrite Cloud

### 👀 Have you spent some time to check if this issue has been raised before?
 I checked and didn't find similar issue
 
### 🏢 Have you read the Code of Conduct?
 I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sgaabdu4** [comment]
Apologies, I realised cloud functions don't work the same as before. It's been a few months since I worked on my current project. Updates are here:
https://appwrite.io/docs/products/functions/development#request

```
[Upgrade](https://appwrite.io/docs/products/functions/development#upgrade)
Appwrite Functions received major updates in Appwrite version 1.4. Your old function from 1.3 will continue to work, but it can't be updated directly to a 1.4 function. You need to create a new function following 1.4 syntax. After you've created your new function, point your application code to the new function and delete the old function.

Here's a checklist of things you need to know.

The parameter passed into functions has changed. req and res has been replaced by context, which contains new logger methods. [Learn about context](https://appwrite.io/docs/products/functions/development#context-object).

To improve privacy and logging reliability, we provide new context.log() and context.error() functions. You can no longer use native logging methods. [Learn about logging](https://appwrite.io/docs/products/functions/development#logging).

The old way of req.variables has been deprecated. You can now access variables passed into each function as environment variables. [Learn about environment variables](https://appwrite.io/docs/products/functions/development#environment-variables).

The req object has been updated to use terminology consistent with typical HTTP concepts. You'll now find familiar concepts like headers, body, HTTP methods, and others. [Learn about request](https://appwrite.io/docs/products/functions/development#request).

The response object has been updated. You can now specify headers, as well as use new methods like return redirects or empty responses. [Learn about response](https://appwrite.io/docs/products/functions/development#response).

Now, you must return a response such as return context.res.send(""). This prevents confusing errors when functions are terminated prematurely before a response is sent. [Learn about response](https://appwrite.io/docs/products/functions/development#response).

Some variables about how a function was triggered are now found in the context.req object as headers.
```

**Comment by Haimantika** [comment]
> Apologies, I realised cloud functions don't work the same as before. It's been a few months since I worked on my current project. Updates are here: https://appwrite.io/docs/products/functions/development#request
> 
> ```
> [Upgrade](https://appwrite.io/docs/products/functions/development#upgrade)
> Appwrite Functions received major updates in Appwrite version 1.4. Your old function from 1.3 will continue to work, but it can't be updated directly to a 1.4 function. You need to create a new function following 1.4 syntax. After you've created your new function, point your application code to the new function and delete the old function.
> 
> Here's a checklist of things you need to know.
> 
> The parameter passed into functions has changed. req and res has been replaced by context, which contains new logger methods. [Learn about context](https://appwrite.io/docs/products/functions/development#context-object).
> 
> To improve privacy and logging reliability, we provide new context.log() and context.error() functions. You can no longer use native logging methods. [Learn about logging](https://appwrite.io/docs/products/functions/development#logging).
> 
> The old way of req.variables has been deprecated. You can now access variables passed into each function as environment variables. [Learn about environment variables](https://appwrite.io/docs/products/functions/development#environment-variables).
> 
> The req object has been updated to use terminology consistent with typical HTTP concepts. You'll now find familiar concepts like headers, body, HTTP methods, and others. [Learn about request](https://appwrite.io/docs/products/functions/development#request).
> 
> The response object has been updated. You can now specify headers, as well as use new methods like return redirects or empty responses. [Learn about response](https://appwrite.io/docs/products/functions/development#response).
> 
> Now, you must return a response such as return context.res.send(""). This prevents confusing errors when functions are terminated prematurely before a response is sent. [Learn about response](https://appwrite.io/docs/products/functions/development#response).
> 
> Some variables about how a function was triggered are now found in the context.req object as headers.
> ```

Yes. Hopefully things are working for you now? And we can go ahead and close this issue?

**Comment by sgaabdu4** [comment]
Hi, please do!
