### ISSUE TITLE
🐛 Bug Report: Total documents count on web ui is wrong

### ISSUE THREAD

**Issue by Schrolli91** [appwrite/appwrite#7081]
### 👟 Reproduction steps

The sum on the web ui dashboard is wrong in my opinion.
There is only one database, with one collection. Why differ these values?

Take a look at this screenshots:
![image](https://github.com/appwrite/appwrite/assets/6043382/ac6166ce-7875-4db0-a8a3-a28b662a8d5c)

![image](https://github.com/appwrite/appwrite/assets/6043382/d3418e60-6b9a-468d-b68f-a1d947ceb608)

![image](https://github.com/appwrite/appwrite/assets/6043382/389548aa-df9a-4350-a8f4-64e323e93b3d)

Is there any reason for this?

### 👍 Expected behavior

Correct document count number

### 👎 Actual Behavior

See above

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Hi @Schrolli91 thanks for raising this issue. I tried recreating this on my end, I did see some differences. Have taken it up to the team, will keep you updated on it.

**Comment by Haimantika** [comment]
Hi @Schrolli91 our team is aware that the usage data is not accurate and we are working on it. You can refer to the issue here - https://github.com/appwrite/appwrite/issues/4751
