### ISSUE TITLE
🐛 Bug Report: Create Execution with a cloud function leading to Operation timed out error

### ISSUE THREAD

**Issue by sgaabdu4** [appwrite/appwrite#7088]
### 👟 Reproduction steps

I have 2 cloud functions (using python). When one cloud function runs, it creates an execution for another cloud function and wait to see whether it's executed. The second cloud function takes around 10 minutes to run. Before the 10 minutes is up, the 2nd cloud function times out. That shouldn't be the case as I've given both cloud functions a timeout of 900. I'm not sure why this is happening. When I run the 2nd cloud function on its own, there are no issues i.e. timeout. Only when the 2nd cloud function is called from the 1st, does the 2nd one time out. I tried to call the 2nd cloud function from the CLI and I'm getting the same error.

Example code for cloud function 1
```
from appwrite.client import Client
import os
from appwrite.services.functions import Functions

def main(context):
    client = Client().set_endpoint(os.environ['ENDPOINT']).set_project(
        os.environ['PROJECT_ID']).set_key(os.environ['API_KEY'])
    functions = Functions(client)
    cloudfunctionid = os.environ[
        'CLOUD_FUNCTION_ID_FOR_2']
    phone = str(context.req.body_raw)
    run_execution = functions.create_execution(
        function_id=cloudfunctionid, body=phone)
```

Example code for cloud function 2
```
from appwrite.client import Client
import os

def main(context):
    try:
        client = Client().set_endpoint(os.environ['ENDPOINT']).set_project(
            os.environ['PROJECT_ID']).set_key(os.environ['API_KEY'])
        time.sleep(40000)
        context.log('cloud_function 2 has run')
```

Error on cloud function 2
`Operation timed out after 30001 milliseconds with 0 bytes received with status code 0\\nError Code: 0`

### 👍 Expected behavior

Should execute the 2nd cloud function and not error out after a few milliseconds.

### 👎 Actual Behavior

The 2nd cloud function times out after a few milliseconds.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

AppWrite Cloud

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Thanks for raising this issue @sgaabdu4 🙏 . I have taken it up to the team and will get back to you with more details

**Comment by sgaabdu4** [comment]
Hi @Haimantika , for some reason, I can run the execution for cloud function 2 perfectly within the console but when I run it through my app or through cloud function 1, it times out. I'm not sure why. Do you have any updates regarding this issue?

**Comment by sgaabdu4** [comment]
Hi @Haimantika , I resolved the issue. For cloud function 1, its imperative that the xasync parameter is set to True and the Method is set to 'GET', otherwise it doesn't work. For e.g

from appwrite.client import Client
import os
from appwrite.services.functions import Functions

```
def main(context):
    client = Client().set_endpoint(os.environ['ENDPOINT']).set_project(
        os.environ['PROJECT_ID']).set_key(os.environ['API_KEY'])
    functions = Functions(client)
    cloudfunctionid = os.environ[
        'CLOUD_FUNCTION_ID_FOR_2']
    phone = str(context.req.body_raw)
    run_execution = functions.create_execution(
        function_id=cloudfunctionid, body=phone, method='GET', xasync=True)
```

**Comment by nbehler13** [comment]
Hi @sgaabdu4, I had the same issue in dart 2.17 but it did not make a difference to use `xasync: true` and since in the dart sdk I cannot set the Method to GET there are no other settings I could change. Is this known in dart?
