### ISSUE TITLE
appwrite 500 error

### ISSUE THREAD

**Issue by dwicaksono** [appwrite/appwrite#7090]
![Screenshot 2023-11-07 at 15 00 13](https://github.com/appwrite/appwrite/assets/20668022/c726d3f8-c39f-4470-a2fe-3449d644165e)
version:
	appwrite: "^13.0.0",

**Comment by pankaj-2503** [comment]
I am not getting this error after as after creating new project , clicked auth and i am getting this
![image](https://github.com/appwrite/appwrite/assets/90036864/77aa6e07-faae-4f1e-8499-bd1031ab3b1e)

**Comment by pankaj-2503** [comment]
If there is any problem with this you can assign this to me

**Comment by Haimantika** [comment]
> ![Screenshot 2023-11-07 at 15 00 13](https://user-images.githubusercontent.com/20668022/280962547-c726d3f8-c39f-4470-a2fe-3449d644165e.png) version: appwrite: "^13.0.0",

Hi, are you creating a new project?

**Comment by Haimantika** [comment]
> ![Screenshot 2023-11-07 at 15 00 13](https://user-images.githubusercontent.com/20668022/280962547-c726d3f8-c39f-4470-a2fe-3449d644165e.png) version: appwrite: "^13.0.0",

Hi @dwicaksono our team has found the issue, will share details to solve it soon.

**Comment by Haimantika** [comment]
Hi @dwicaksono did the project ever work for you? Also, can you create a new project?

**Comment by dwicaksono** [comment]
Thanks All, solved by create new project

**Comment by SMARTMICROWORLD** [comment]
I also get this error many times, I think it is server error, after some time it disappears

**Comment by Haimantika** [comment]
> I also get this error many times, I think it is server error, after some time it disappears

This happens due to database backups or other incidents. If you face such errors, feel free to reach out to us on discord - appwrite.io/discord.

**Comment by Haimantika** [comment]
> Thanks All, solved by create new project

Thanks. Closing this now
