### ISSUE TITLE
500 Internal Error appwrite ?

### ISSUE THREAD

**Issue by Zaim211** [appwrite/appwrite#7099]

**Comment by DH-555** [comment]
Is this with Appwrite cloud? If so, there was a small issue with cloud, that should be solved now. Does it work now for you?

**Comment by Haimantika** [comment]
@Zaim211 are you still facing this issue? If yes, can you raise a new issue with all the details? Also, you can reach out to us on discord - appwrite.io/discord.

Closing this on for now, please open a new one with all the details if you are still facing it.
