### ISSUE TITLE
🐛 Bug Report: Trigger a function users.*.create when a user is created with phone

### ISSUE THREAD

**Issue by silentmado** [appwrite/appwrite#7101]
### 👟 Reproduction steps

1. create a function and set triggers on users.*.create
2. create a user using phone

### 👍 Expected behavior

function should be executed

### 👎 Actual Behavior

function is not executed

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite 1.4.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by loks0n** [comment]
Phone session does not trigger a `user.*.create` event, it triggers `users.*.sessions.*.create` event.

**Comment by mdmohsin7** [comment]
> Phone session does not trigger a `user.*.create` event, it triggers `users.*.sessions.*.create` event.

It still doesn't get triggered for me. Tried on both Appwrite Cloud and Self Hosted instance (1.4.9).  For both I have added the `users.*.sessions.*.create` event.

**Comment by loks0n** [comment]
> It still doesn't get triggered for me. Tried on both Appwrite Cloud and Self Hosted instance (1.4.9). For both I have added the `users.*.sessions.*.create` event. Tried with just the `users.*` event as well, still isn't triggered.

Has the user called the `Create phone session (confirmation)` endpoint? This is when the session is created and the event should be triggered

**Comment by mdmohsin7** [comment]
> Has the user called the `Create phone session (confirmation)` endpoint? This is when the session is created and the event should be triggered

Yes I am calling the create phone session endpoint. 
To make sure I'm doing it right, I am attaching the code snippet below in Dart:
```
final client = Client()
    .setEndpoint('endpoint')
    .setProject('some_id');

final account = Account(client);
final sessionToken = await account.createPhoneSession(
    userId: ID.unique(),
    phone: '+14255550123'
);
```

**Comment by loks0n** [comment]
> Yes I am calling the create phone session endpoint. To make sure I'm doing it right, I am attaching the code snippet below in Dart:
> 
> ```
> final client = Client()
>     .setEndpoint('endpoint')
>     .setProject('some_id');
> 
> final account = Account(client);
> final sessionToken = await account.createPhoneSession(
>     userId: ID.unique(),
>     phone: '+14255550123'
> );
> ```

The session is not created until the user receives the code, and uses it to call `account.updatePhoneSession`. Please see https://appwrite.io/docs/references/cloud/client-web/account#updatePhoneSession

**Comment by mdmohsin7** [comment]
> The session is not created until the user receives the code, and uses it to call `account.updatePhoneSession`. Please see https://appwrite.io/docs/references/cloud/client-web/account#updatePhoneSession

Oh okay got it.
I just now came across [this](https://discord.com/channels/564160730845151244/1127756741715701821/1127756741715701821) thread on Discord where Steven has mentioned that no event gets triggered for the createPhoneSession endpoint.
 I actually want to get that code (which is sent to the user). Is there any way to get that code before actually the user enters it?

**Comment by mdmohsin7** [comment]
I went through the codebase and I saw that the generated code is stored in a collection named "tokens". 
```
        $secret = Auth::codeGenerator();
        $expire = DateTime::formatTz(DateTime::addSeconds(new \DateTime(), Auth::TOKEN_EXPIRATION_PHONE));

        $token = new Document([
            '$id' => ID::unique(),
            'userId' => $user->getId(),
            'userInternalId' => $user->getInternalId(),
            'type' => Auth::TOKEN_TYPE_PHONE,
            'secret' => Auth::hash($secret),
            'expire' => $expire,
            'userAgent' => $request->getUserAgent('UNKNOWN'),
            'ip' => $request->getIP(),
        ]);

        Authorization::setRole(Role::user($user->getId())->toString());

        $token = $dbForProject->createDocument('tokens', $token
            ->setAttribute('$permissions', [
                Permission::read(Role::user($user->getId())),
                Permission::update(Role::user($user->getId())),
                Permission::delete(Role::user($user->getId())),
            ]));
```

I tried adding the event `databases.*.collections.tokens.documents.*` and `databases.*.collections.tokens`, but none of them seems to cause the function to be triggered. Is there a way to access the `tokens` collection?

**Comment by silentmado** [comment]
@loks0n why it doesn't create a `user.*.create` event while we have really a user created in appwrite, doesn't it make sense to have that event ?
I have noticed that the session creation takes 2 steps:
1. first step where the code is sent to mobile phone number: and here we have a user being created in appwrite (not verified but created) and then we should have `user.*.create` event triggered. not ?
2. second step Create phone session (confirmation): and here we have a session being created and then we should have `users.*.sessions.*.create` triggered.

**Comment by stnguyen90** [comment]
This is a long-standing issue we have with our event system in which only 1 event is triggered per endpoint. We plan to rewrite the event system to fix this problem. 

Related issues:
* https://github.com/appwrite/appwrite/issues/2406
* https://github.com/appwrite/appwrite/issues/5198
