### ISSUE TITLE
gateway timeout

### ISSUE THREAD

**Issue by MohammadHarish52** [appwrite/appwrite#7102]
i have been trying to access app write from early morning and all i can see is "gateway timeout"

**Comment by stnguyen90** [comment]
@MohammadHarish52, thanks for raising this issue! Were you trying to access Appwrite Cloud? There was an incident, but it's resolved now. Are you able to access Appwrite Cloud now?

FYI, you can keep an eye on the status of Appwrite Cloud [here](https://appwrite.online/).

**Comment by MohammadHarish52** [comment]
> @MohammadHarish52, thanks for raising this issue! Were you trying to access Appwrite Cloud? There was an incident, but it's resolved now. Are you able to access Appwrite Cloud now?
> 
> FYI, you can keep an eye on the status of Appwrite Cloud [here](https://appwrite.online/).

Thanks its resolved now
