### ISSUE TITLE
🐛 Bug Report: Deploying via CLI disconnects function from GitHub

### ISSUE THREAD

**Issue by moshOntong-IT** [appwrite/appwrite#7107]
### 👟 Reproduction steps

Since there is a bug on not reflecting on the Git push trigger [ISSUE](https://github.com/appwrite/appwrite/issues/7108). I decide to use the cli. Just to deploy my new code to my function in console.

### 👍 Expected behavior

The Git connection on my function should still connected.

### 👎 Actual Behavior

After trigger deploying my function from cli. The Git connection is disconnected.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by moshOntong-IT** [comment]
https://github.com/appwrite/appwrite/issues/7108#issuecomment-1805920910

**Comment by stnguyen90** [comment]
This should be fixed as part of https://github.com/appwrite/appwrite/pull/8500
