### ISSUE TITLE
🐛 Bug Report: User activity is empty

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#7109]
### 👟 Reproduction steps

1. Create a user in a project
2. Create an email session

### 👍 Expected behavior

The activity tab shows session create activity.

### 👎 Actual Behavior

It doesn't show up.

<img width="1502" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/b97090c3-eced-43bd-b32a-c165be53959c">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Schrolli91** [comment]
Related: https://github.com/appwrite/appwrite/discussions/7100

**Comment by moshOntong-IT** [comment]
Finally, I thought I was the only one experiencing this issue.

**Comment by feschaffa** [comment]
Having the same issue here, zero activity, using 1.4.11

**Comment by nick2432** [comment]
can i work on this?

**Comment by stnguyen90** [comment]
Looking at the network logs, I can see data is returned:

![image](https://github.com/appwrite/appwrite/assets/1477010/75476ecb-6721-4c67-9576-0a3a69dcaf32)

However:

1. total is 0
2. userId is blank
3. userEmail is blank
4. userName is blank

Compared to collection activity:

![image](https://github.com/appwrite/appwrite/assets/1477010/2c0a0b6d-bfa9-46cc-a456-0e6758cb0652)

The 0 total is probably [preventing anything from being displayed](https://github.com/appwrite/console/blob/ac50ffb6ffb56544cb57ace266ae4bbf0a1ef028/src/lib/layout/activity.svelte#L40).

**Comment by stnguyen90** [comment]
@nick2432, would you like to work on this?

**Comment by stnguyen90** [comment]
@nick2432, actually, I think we'll take care of this ourselves. Assigning to @TorstenDittmann to prioritize.

**Comment by Souptik2001** [comment]
Hi @stnguyen90 @TorstenDittmann,
Saw that this fix has not yet been done, therefore raised a PR for this.

If it has already been fixed please ignore and close the PR. :slightly_smiling_face: 

Thanks!
