### ISSUE TITLE
🐛 Bug Report:  dart-3.1 runtime throws exception when creating function

### ISSUE THREAD

**Issue by arrowxpr** [appwrite/appwrite#7116]
### 👟 Reproduction steps

1. Add dart-3.1 to the env variable
```
_APP_FUNCTIONS_RUNTIMES=node-16.0,php-8.0,python-3.9,ruby-3.0,dart-2.17,dart-3.0,dart-3.1,node-18.0,node-20.0
```
2. Create a function and choose the new runtime
```
appwrite init function
```

In my case, I get
```
arrow ~/Developer/Mify-Appwrite-Server-CLI$ appwrite init function
? What would you like to name your function? tester
? What ID would you like to have for your function? unique()

? What runtime would you like to use? Dart (dart-3.1)
✗ Error ENOENT: no such file or directory, copyfile '/Users/arrow/Developer/Mify-Appwrite-Server-CLI/functions/tester/dart-3.1' -> '/Users/arrow/Developer/Mify-Appwrite-Server-CLI/functions/tester'
```

I noticed my dart-3.0 also having the same issue. Only the 2.17 works for me as of now.

### 👍 Expected behavior

Function should be initialized without problem.

### 👎 Actual Behavior

Function does not get initialized.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

version 1.4.9 Self hosting

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@arrowxpr, thanks for creating this issue! 🙏🏼 What version of the Appwrite CLI do you have?

**Comment by arrowxpr** [comment]
> @arrowxpr, thanks for creating this issue! 🙏🏼 What version of the Appwrite CLI do you have?

thank you Steven for bringing this to my attention, I upgraded my cli to latest and the issue has been solved on my part ✌️
