### ISSUE TITLE
🐛 Bug Report: Cloud functions not executing new updated code.

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [appwrite/appwrite#7122]
### 👟 Reproduction steps

I am getting old code execution since morning, I also redeployed but still getting old code execution logs. Also many time build fails.

### 👍 Expected behavior

Unable to update function 

### 👎 Actual Behavior

It happens to all functions not with only one.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by SEED-Foundation** [comment]
I Also have this problem which is the function is just running the old code not the one I pushed to my repo , I'm self hosting version 1.4.11

**Comment by SMARTMICROWORLD** [comment]
> I Also have this problem which is the function is just running the old code not the one I pushed to my repo , I'm self hosting version 1.4.11

I think, they were maintaining the server that's why we got bugs. Not is is working

**Comment by stnguyen90** [comment]
@SMARTMICROWORLD, is your function connected to GitHub? How are you redeploying?

**Comment by SMARTMICROWORLD** [comment]
> @SMARTMICROWORLD, is your function connected to GitHub? How are you redeploying?

Now it is working, I think that was server issue

**Comment by Haimantika** [comment]
> > @SMARTMICROWORLD, is your function connected to GitHub? How are you redeploying?
> 
> Now it is working, I think that was server issue

Thanks for letting us know. Will close this issue, since it is solved.
