### ISSUE TITLE
🐛 Bug Report: Error disconnecting from GitHub

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#7137]
### 👟 Reproduction steps

1. Open project in Appwrite Console
2. Open project settings
3. Go to Git configuration
4. Click the menu icon next to a GitHub installation
5. Click Disconnect

### 👍 Expected behavior

The installation is removed

### 👎 Actual Behavior

500 error:

```json
 {
    "message": "Server Error",
    "code": 500,
    "type": "general_unknown",
    "version": "0.11.28"
}
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by popperro-001** [comment]
Same response error when trying to PATCH existing records. Git is not connected, I am in development mode
