### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by LegendaryPCSor** [appwrite/appwrite#7141]
while adding data to post I face this issue.

![image](https://github.com/appwrite/appwrite/assets/44223573/1806c7d2-1e43-45fc-aa3b-633b77fcd540)

![image](https://github.com/appwrite/appwrite/assets/44223573/b69c2f14-b0b6-479b-aa82-346f9e5e15ea)

**Comment by yung-slime** [comment]
im getting the same error while using the server sdk.

task: storage.get_file_view() in appwrite sdk for python.
error message: An internal curl error has occurred within the executor! Error Msg: Http invalid protocol
Error Code: 500

**Comment by Haimantika** [comment]
Hi @LegendaryPCSor I hope this is solved for you now in [Discord](https://discord.com/channels/564160730845151244/1174245844682297354)? @yung-slime can you open a support thread about this on our [Discord server](https://appwrite.io/discord)?

**Comment by yung-slime** [comment]
@Haimantika i hope i could if i know how to do that? im just a lil boy messing around this bitch btw. give me some ref for that plz.

**Comment by Haimantika** [comment]
> @Haimantika i hope i could if i know how to do that? im just a lil boy messing around this bitch btw. give me some ref for that plz.

Hi, join our [Discord server](https://appwrite.io/discord) now, say hi and tag me in the introductions channel. I can help you with the next step.

**Comment by Haimantika** [comment]
Will be closing this now, since it is solved. @yung-slime you are always welcome to open a new issue or ping us on Discord for help.
