### ISSUE TITLE
🐛 Bug Report: Create string attribute from API with empty key

### ISSUE THREAD

**Issue by fliitor** [appwrite/appwrite#7143]
### 👟 Reproduction steps

From [this doc](https://appwrite.io/docs/references/cloud/server-rest/databases#createStringAttribute)
Call api with `key: ""`
Result in blank failed attribute on console
It's also exported when used `appwrite init collection`

And now it's impossible to delete cause this one hasn't key

### 👍 Expected behavior

Block insert with error message from API

### 👎 Actual Behavior

Attribute is inserted

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@fliitor, thanks for raising this issue! 🙏🏼 Looks like we need to make sure to check for empty strings in the validator.
