### ISSUE TITLE
🚀 Feature:  Add Description on Attribute

### ISSUE THREAD

**Issue by moshOntong-IT** [appwrite/appwrite#7145]
### 🔖 Feature description

I would like to request a description for each attribute. Description something like you have to describe or document what is the purpose of this attribute. It means this may be another parameter of creating an attribute of collection.

### 🎤 Pitch

In my case, this will be useful when we have more than 5 developer and manage our database, so then our new employee, will be not hard to understand the purpose of the attribute.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@moshOntong-IT, thanks for creating this issue! 🙏🏼 This seems like the same thing as https://github.com/appwrite/appwrite/issues/5493. As such, I'm going to close this and I suggest you 👍🏼 the other issue.
