### ISSUE TITLE
🚀 Feature: User Presence for Javascript 

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7159]
### 🔖 Feature description

There should be a way to monitor who is online and in the case when user loses connection, he should be marked as offline.

### 🎤 Pitch

User presence is basic feature already offered at Firebase and Supabase.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
Thanks for the feature request @step135. I have started a discussion with our team, will update you when I know more.

**Comment by stnguyen90** [comment]
@step135, this looks the same as [this feature request](https://github.com/appwrite/appwrite/issues/2418). As such, I'm going to close this and I would suggest you 👍🏼 the original issue.
