### ISSUE TITLE
🐛 Bug Report: Unable to upload file from react native

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [appwrite/appwrite#7166]
### 👟 Reproduction steps

When I am uploading file from react native app to appwrite storage I am getting error like:

[AppwriteException: Parameter "file" has to be a File.]

`  const choosePhotoFromGallery = async () => {
    ImagePicker.openPicker({
      mediaType: 'photo',
      cropping: false,
    })
      .then(async data => {
        await ImagePicker.openCropper({
          path: data.path,
          width: 1000,
          height: 1000,
          cropperCircleOverlay: true,
          //freeStyleCropEnabled: true,
        })
          .then(async image => {
            console.log(image.path);
            await appwriteStorage.createFile(
              PROFILE_PICS_BUCKET_ID,
              ID.unique(),
              image.path,
            );
            setUserImage(image.path);
          })
          .catch(err => console.log('error image crop', err));
      })
      .catch(err => console.log('image selection err', err));
  };`

### 👍 Expected behavior

It should upload to storage bucket.

### 👎 Actual Behavior

But getting error?

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@SMARTMICROWORLD, thanks for raising this issue! 🙏🏼 There's a problem with how React Native handles files which is incompatible with our SDK. Please see and 👍🏼 [this](https://github.com/appwrite/sdk-for-web/issues/27) issue.
