### ISSUE TITLE
[FEATURE] Guard collection

### ISSUE THREAD

**Issue by moshOntong-IT** [appwrite/appwrite#7173]
I am thinking that what if we have Guard in setting tab of each collection:
<img width="632" alt="image" src="https://github.com/appwrite/appwrite/assets/57244338/f8d0b51c-1342-49a6-a389-6f8f56ef051e">

## So what is Guard?

Guard is a middleware that always returns boolean. If returns true, then it can be proceed to next process. Otherwise it throws an error. 

## So what is the process of creating Guard?

It will utilize the cloud function. It means we can attach a cloud function in Guard or ID reference from any function. Below picture is will be the UI of how to attach functions. Yes it could be a list of function. So that it will be scalable or flexible I think? 😉

<img width="157" alt="image" src="https://github.com/appwrite/appwrite/assets/57244338/e4454f11-1320-42e5-869a-69047c03b435">

## Why Cloud Functions?

- Firstly, we can use various programming language. So then it will also a good developer experience, so we should not have to learn another syntax on how to create a middleware plugin codes.

- Second, security since we cloud function needs an API key or jwt session.

- Thirdly, since this is about preprocessing, we can take advantage of the cloud function because cloud function is we can access some of API of appwrite like, fetching documents, fetching users, fetching storage, etc. 

- Fourthly,  the cloud function provide res,req,log and error, So it not hassle to how to get the req.body. 

## What we need feature to add in cloud function

- I am thinking right now that we should add method of res.resolver(true) or res.resolver(false). This is a response that we can proceed to next process/post process.

## What should be the disadvantage of using cloud function?

- It will takes more time (but it depends on how the developer create guard function).

**Comment by moshOntong-IT** [comment]
Issue relate:

- https://github.com/appwrite/appwrite/issues/2358
- https://github.com/appwrite/appwrite/issues/6361

**Comment by stnguyen90** [comment]
@moshOntong-IT, as you've pointed out, there are related issues. Instead of creating new issues, it would be better to 👍 the original issue and comment with what functionality/use-case you need. The details on the implementation will be determined by the core team.

**Comment by eldadfux** [comment]
@moshOntong-IT thanks for pitching this, I'll close in favor of #2358 so we have all discussions in one place, feel free to jump in there.
