### ISSUE TITLE
🐛 Bug Report: Logging Large Objects Triggers 500

### ISSUE THREAD

**Issue by Exponential-Workload** [appwrite/appwrite#7178]
### 👟 Reproduction steps

When I log a `59824` character long string (the value i happened to get when serializing an object) in a function, i get an HTTP 500 from Appwrite - `An internal curl error has occurred within the executor! Error Msg: Http invalid protocol\nError Code: 500` is shown in the log of the function.

### 👍 Expected behavior

The entire string should get logged - or worst-case, truncated.

### 👎 Actual Behavior

The function shouldn't crash

Execution Log:
![image](https://github.com/appwrite/appwrite/assets/90570076/60d4e72e-d73f-4912-929a-f795efe33c4a)

Openruntimes Executor Log:
![image](https://github.com/appwrite/appwrite/assets/90570076/63e299ed-4a74-4e73-8bef-a625fd5eef0d)

Host Appwrite Container Log (localhost warnings are irrelevant):
![image](https://github.com/appwrite/appwrite/assets/90570076/31063cc0-d96e-41c7-badd-8e89cdae3b30)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Distribution Information:
```
$: neofetch
                   -`                    arch@archlinux 
                  .o+`                   -------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: MS-7B86 3.0 
               `+oooooo:                 Kernel: 6.6.1-zen1-1-zen 
               -+oooooo+:                Uptime: 2 hours, 13 mins 
             `/:-:++oooo+:               Packages: 1709 (pacman), 1 (pkg), 14 (flatpak) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: GNOME 45.1 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Adwaita 
       -osssssso.      :ssssssso.        Theme: Adwaita-dark [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Adwaita [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: kgx 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT 
 `++:.                           `-/+/   Memory: 11740MiB / 64224MiB 
 .`                                 `/                                   
```

Docker Information:
```
$ docker --version
Docker version 24.0.7, build afdd53b4e3
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Haimantika** [comment]
@Meldiron can you take a look here?

**Comment by Haimantika** [comment]
Hi @Exponential-Workload it is similar to this issue - https://github.com/appwrite/appwrite/issues/7144
@Meldiron is working on it currently. It will be nice if you can 👍 the issue and we can close this one.
