### ISSUE TITLE
📚 Documentation: Change fetching methods

### ISSUE THREAD

**Issue by R0N1n-dev** [appwrite/appwrite#7179]
### 💭 Description

The documentation for Storage Should probably be changed to async/await fashion.

The docs for listing files in storage is as follows:
```js
const promise = storage.listFiles(bucketId);

      promise.then(
        function (response) {
          console.log(response); // Success
        },
        function (error) {
          console.log(error); // Failure
        }
      );
```
In the above example, no matter where i Put the images assignment (this.images = response) ,  i Got 
```js
[promise, object]
```
This presented me with various errors when attempting to use it in pinia.
Did not work till i adjusted to 
```js
try {
        const response = await storage.listFiles(bucketId);
        console.log(response); // Success
        this.images = response;
      } catch (error) {
        console.log(error); // Failure
      }
```
The docs all use the promise style which has caused me issues in actually getting the values back in the responses.

This function, from the docs on getting a single item from database actually did not return anything :
```js
const promise = await databases.getDocument(dbID, collectionId, docId).then(
        function (response) {
          console.log(response)
        },
        function (error) {
          console.log(error); // Failure
        }
      );
      this.specificBook = promise;
```

Till It was modified . I had to ask chatGPT for help (not joking, i was stuck at trying to read the response but got nothing) and it solved the issue for me by editing the function to this
```js
const promise = await databases.getDocument(dbID, collectionId, docId).then(
        function (response) {
          console.log(response);
          return response; // Success
        },
        function (error) {
          console.log(error); // Failure
        }
      );
      this.specificBook = promise;
```
Simply adding  'return response'
The response had to be returned as you can see.
I believe either the docs need to be updated or provide the async/await alternative which is definitely simpler from my experience in this short time

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
Hi there~

So typically, you'd use async awaits and use something like a [react use state hook](https://react.dev/learn/state-a-components-memory) or something like [pinia store](https://pinia.vuejs.org/) to trigger components updates.

Especially for files, awaiting a file synchronously is unreliable and will block your code for excessive amounts of time.

Imagine loading 20 images, all in async await, your app will be stuck loading (and unresponsive) for a few seconds.

Promises don't do this, and we intend you to do something with the response through something like a state store. This is pretty typical in JavaScript.

If you need synchronous execution, of course, you can use async-await.

Here's more you can read about.
https://betterprogramming.pub/should-i-use-promises-or-async-await-126ab5c98789

I'll keep this issue for further discussions. Hope this helps!

**Comment by TechSis01** [comment]
Hello,
please may I suggest edits to the documentation that explains use-cases for async await and promises, so developers can be better informed on which approach to use right there in the Appwrite documentation to avoid any form of confusion and frustration while using Appwrite. I think this would really help emerging developers who have little experience.

**Comment by R0N1n-dev** [comment]
> Hello, please may I suggest edits to the documentation that explains use-cases for async await and promises, so developers can be better informed on which approach to use right there in the Appwrite documentation to avoid any form of confusion and frustration while using Appwrite. I think this would really help emerging developers who have little experience.

True.
