### ISSUE TITLE
🐛 Bug Report: Storage swapped over to other project

### ISSUE THREAD

**Issue by vontdeux** [appwrite/appwrite#7200]
### 👟 Reproduction steps

im running a self hosted version 1.3.8 in a docker container

i have project A and project B
both have own storageA and storageB

and somehow after server got stuck/hang (after i set files per page to 96)
the storageB is gone, and is displaying storageA from project A

when i try to create another bucket in project B, "network request failed" error is displayed
when i try to create another database in project B, "network request failed" error is displayed
when i try to execute function (which now displaying project A's function) - "Runtime "" is not supported" error is displayed
basically my whole project B now is corrupted and cant be used.

### 👍 Expected behavior

i should be able to recover from the corrupted project

### 👎 Actual Behavior

it is unrecoverable via web console

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

i use 1.3.8 docker image
with just web console purely and with flutter SDK
no customization

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Related Discord thread: https://discord.com/channels/564160730845151244/1177541017675780197
