### ISSUE TITLE
🐛 Bug Report: project has exceeded the maximum number of users

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#7208]
### 👟 Reproduction steps

1. Install Appwrite
2. Create 1 console user
3. Create a second console user

### 👍 Expected behavior

A helpful error message

### 👎 Actual Behavior

The error message is not helpful:

![image](https://github.com/appwrite/appwrite/assets/1477010/7298895f-ecf4-4b06-83e2-9cb5b6c732cd)

This error message applies when creating a user in a project that has a limit of users set. When this errors when creating a console user, the problem is due to the `_APP_CONSOLE_WHITELIST_ROOT` env var being set to enabled. The error should make that clear.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by misterneo** [comment]
This is the line that needs to be updated
https://github.com/appwrite/appwrite/blob/fbd277f6aa0ff161838a60e79b950e5a3f58e3f6/app/config/errors.php#L110

@stnguyen90 @nick2432

**Comment by gewenyu99** [comment]
@nick2432 if you've began on a PR, please tag this issue!

**Comment by stnguyen90** [comment]
@nick2432, since we haven't heard from you in a while, we're going to reassign this so we can try to get this changed sooner. Thanks for your interest, though!
