### ISSUE TITLE
📚 Documentation: Link for Cron syntax should go to schedule section of docs

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#7209]
### 💭 Description

The links about the cron syntax on:

1. [Function settings](https://github.com/appwrite/console/blob/855163a1ec51823851a48bed971a545750de3cba/src/routes/console/project-%5Bproject%5D/functions/function-%5Bfunction%5D/settings/updateSchedule.svelte#L60-L65)
2. [Function wizard](https://github.com/appwrite/console/blob/855163a1ec51823851a48bed971a545750de3cba/src/routes/console/project-%5Bproject%5D/functions/wizard/step4.svelte#L10-L15)

should link to the [Schedule](https://appwrite.io/docs/products/functions/execution#schedule) section of the docs.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by trottiemcqueen** [comment]
Great evening. If not resolved, wouldn't mind working on this :)  @stnguyen90

**Comment by nick2432** [comment]
can i work on this?

**Comment by stnguyen90** [comment]
@programmingwithrp, in the future, please be mindful of others who have asked to work on an issue.
