### ISSUE TITLE
🐛 Bug Report: sample code for dart functions is incorrect

### ISSUE THREAD

**Issue by eauw** [appwrite/appwrite#7210]
### 👟 Reproduction steps

Using `appwrite init function --verbose` to create a new cloud function with dart sdk generates the following code:
```
import 'dart:async';
import 'package:dart_appwrite/dart_appwrite.dart';

// This is your Appwrite function
// It's executed each time we get a request
Future<dynamic> main(final context) async {
  // Why not try the Appwrite SDK?
  //
  // final client = Client()
  //   .setEndpoint('https://cloud.appwrite.io/v1')
  //   .setProject(process.env.APPWRITE_FUNCTION_PROJECT_ID)
  //   .setKey(process.env.APPWRITE_API_KEY);

  // You can log messages to the console
  context.log('Hello, Logs!');

  // If something goes wrong, log an error
  context.error('Hello, Errors!');

  // The `req` object contains the request data
  if (context.req.method == 'GET') {
    // Send a response with the res object helpers
    // `res.send()` dispatches a string back to the client
    return context.res.send('Hello, World!');
  }

  // `res.json()` is a handy helper for sending JSON
  return context.res.json({
    'motto': 'Build like a team of hundreds_',
    'learn': 'https://appwrite.io/docs',
    'connect': 'https://appwrite.io/discord',
    'getInspired': 'https://builtwith.appwrite.io',
  });
}
```

### 👍 Expected behavior

The created sample code should work out of the box.

### 👎 Actual Behavior

The commented lines cause errors if I uncomment them because "process" is unknown.
```
  // final client = Client()
  //   .setEndpoint('https://cloud.appwrite.io/v1')
  //   .setProject(process.env.APPWRITE_FUNCTION_PROJECT_ID)
  //   .setKey(process.env.APPWRITE_API_KEY);
```

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@eauw, thanks for creating this issue! 🙏🏼 Looks like the commented out code is incorrect. For the right syntax, see our [docs](https://appwrite.io/docs/products/functions/development#environment-variables).

**Comment by stnguyen90** [comment]
We now use the appwrite/templates repo and it looks correct in there: https://github.com/appwrite/templates/blob/1a0b67f2dc4a849e90a75998f257476c81acee65/dart/starter/lib/main.dart#L10-L12
