### ISSUE TITLE
🐛 Bug Report: Allowed memory exhausted 

### ISSUE THREAD

**Issue by CannonPhelps** [appwrite/appwrite#7212]
### 👟 Reproduction steps

Change max file side to 900mb
upload a 400mb file/video
try to access file using the view link

### 👍 Expected behavior

The file should open and you should be able to view it.

### 👎 Actual Behavior

you should get a 502 bad gateway error that will show up and when you look into the error logs you get this error

```
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 448676210 bytes) in /usr/src/code/vendor/utopia-php/storage/src/Storage/Compression/Algorithms/GZIP.php on line 41
[2023-11-27 01:49:45 *1723.5]   ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 448676210 bytes) in /usr/src/code/vendor/utopia-php/storage/src/Storage/Compression/Algorithms/GZIP.php on line 41
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Version 1.4.6 
Web SDK/ Node.JS SDK
only customization is the max file size for buckets it was increased to 900mb

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@CannonPhelps, thanks for creating this issue! 🙏🏼 It looks like there are some problems with the view and preview endpoints:

1. Files are decompressed even though they may not need to be (which would load big files into memory and cause this memory exhaustion error)
2. Thew view endpoint needs to [return after sending data back](https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/app/controllers/api/storage.php#L1218) to prevent further execution.

**Comment by eldadfux** [comment]
This was fixed here: https://github.com/appwrite/appwrite/pull/7351 and will be available on the next Appwrite version.
