### ISSUE TITLE
🐛 Bug Report: WEBP quality image compression

### ISSUE THREAD

**Issue by Andree98** [appwrite/appwrite#7213]
### 👟 Reproduction steps

The quality parameter on the file preview endpoint doesn't seem to have an affect on the size of webp images.

I added a JPEG image to a bucket and requested it as WEBP with `quality=100` and then with `quality=50`. if you check the network request in the debug console you can verify both images are the same size.

https://cloud.appwrite.io/v1/storage/buckets/6565a07a7aa848f1fceb/files/6565a234aa631a6f4488/preview?quality=100&output=webp&project=6565a03a863ce51bd917

https://cloud.appwrite.io/v1/storage/buckets/6565a07a7aa848f1fceb/files/6565a234aa631a6f4488/preview?quality=50&output=webp&project=6565a03a863ce51bd917

### 👍 Expected behavior

quality=50 should be a smaller size than quality=100

### 👎 Actual Behavior

Both images are the same size

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Andree98, thanks for creating this issue! 🙏🏼 I tested the 2 you shared and they do look like sizes are different:

<img width="659" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/0556d3df-2446-4ba9-b17e-9411c0418ad1">

One odd thing, though, is the images are jpeg instead of webp 🧐

**Comment by Andree98** [comment]
@stnguyen90 They were different sizes because quality compression works for jpeg but not for webp

I just tried in Firefox and the images are webp and the same size

<img width="834" alt="Screenshot 2023-12-16 at 07 12 25" src="https://github.com/appwrite/appwrite/assets/34305925/b3576f28-3c91-4b9c-9ff9-1e7fdc485186">
<img width="833" alt="Screenshot 2023-12-16 at 07 12 43" src="https://github.com/appwrite/appwrite/assets/34305925/0a34b587-2f5c-4a29-bb6a-ca1495bf175b">

**Comment by eldadfux** [comment]
Which browser are you using to make the requests?

**Comment by Andree98** [comment]
I have reproduced it in Firefox, Chrome and Flutter SDK so It's reproducible from anywhere. But make sure the response image is WebP (there's another issue where the images come as JPEG instead of WebP and in that case quality compression works)

**Comment by eldadfux** [comment]
Checking the source code. The endpoint is falling back to JPG when the client doesn't support webp. Client that support webp, would send the accept header with the value `image/webp`, if this doesn't happen we change the format back to avoid the image not loading at all. 

Depending on your browser and version we can understand if this is a bug in the check, or we shouldn't expect all supporting browsers to report the header.

More info on webp support here: https://caniuse.com/webp

**Comment by Andree98** [comment]
You're right, but what you're describing is more relevant to #6976. 

This issue described here is about the fact that WebP images are always the same size no matter what quality level you include in the arguments.

I have included links to a preview request of a jpeg image with `output=webp&quality=100` and `output=webp&quality=50`. Opening these links in a browser with a dev console it is possible to confirm that both response images have the same size of 38.61kB

**Comment by eldadfux** [comment]
I see... checking the source code, I see in our old fallback implementation quality was set, and in the new one it isn't. Let me see if I can patch this.
