### ISSUE TITLE
🐛 Bug Report: Inside storage -> media , delete feature is not working

### ISSUE THREAD

**Issue by SaunakNandi** [appwrite/appwrite#7218]
### 👟 Reproduction steps

Storage > Media > FILENAME, when trying to click the 3 dots then selecting the delete option and then while clicking on DELETE button as shown below, nothing is happening.

<img width="960" alt="image" src="https://github.com/appwrite/appwrite/assets/63156949/403eafb2-9e5d-4dd2-ab71-5a3cc5226645">

### 👍 Expected behavior

The file should get deleted after clickng the delete option

### 👎 Actual Behavior

The file stays as it is and is not getting deleted.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

1.4.13. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@SaunakNandi, thanks for creating this issue! 🙏🏼 I tried the steps you mentioned, but wasn't able to reproduce. Would you please try opening the browser dev tools and reproducing again to see if there are any console or network logs related to the delete?

**Comment by stnguyen90** [comment]
@SaunakNandi, have you had a chance to check the logs? FYI, I'll need to close this due to inactivity soon.
