### ISSUE TITLE
SSL certificate renewal failed due to permissions

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#722]
## 🐛 Bug Report

SSL certificate renewal failed du to permission.

## Have you spent some time to check if this issue has been raised before?

Yes ✔️ 

## To Reproduce

I guess wait for a certificate to expire and have v1-certificates jobs fail.

## Expected behavior

Renew certificate.

## Actual Behavior

Certificate expired for a domain, with following error message on resque:

```
Arguments
---
document: []
domain: ***.omniawrite.com
validateTarget: true
validateCNAME: true
Exception
Exception
Error
Failed to rename certificate cert.pem: "IMPORTANT NOTES:\n - Congratulations! Your certificate and chain have been saved at:\n \/etc\/letsencrypt\/live\/***.omniawrite.com-0001\/fullchain.pem\n Your key file has been saved at:\n \/etc\/letsencrypt\/live\/***.omniawrite.com-0001\/privkey.pem\n Your cert will expire on 2020-12-31. To obtain a new or tweaked\n version of this certificate in the future, simply run certbot\n again. To non-interactively renew *all* of your certificates, run\n \"certbot renew\"\n - If you like Certbot, please consider supporting our work by:\n\n Donating to ISRG \/ Let's Encrypt: https:\/\/letsencrypt.org\/donate\n Donating to EFF: https:\/\/eff.org\/donate-le\n\n"
```

## Your Environment

version 0.6.2.125

**Comment by eldadfux** [comment]
I'll look into it, I might make some adjustments in the certificates worker to solve the issue. Anyway a workaround for this would be to restart your main Appwrite API container. It should take about ~30 seconds for a new certificate to be generated.

`docker-compose restart appwrite`
