### ISSUE TITLE
🐛 Bug Report: createFile Method Returns 500 Status Code during File Upload

### ISSUE THREAD

**Issue by Rondev9** [appwrite/appwrite#7222]
### 👟 Reproduction steps

Hello, When attempting to upload a file using the createFile method in Appwrite, I encountered an error with status code 500.

**Code:**
```typescript
export async function uploadFile(file: File) {
  try {
    console.log("file:", file);
    const uploadedFile = await storage.createFile(
      appwriteConfig.storageId,
      ID.unique(),
      file
    );
    console.log("uploadedFile:", uploadedFile);
    return uploadedFile;
  } catch (error) {
    console.log(error);
  }
}
```

### 👍 Expected behavior

The file should be uploaded successfully.

### 👎 Actual Behavior

The file isn't uploading and giving 500 in return.

**Screenshots of the issue:**

![Screenshot (128)](https://github.com/appwrite/appwrite/assets/65064521/a2958f29-00cb-4a8a-b5d0-2fc187164d94)
![Screenshot (129)](https://github.com/appwrite/appwrite/assets/65064521/c3af5ed0-b4b9-423f-a5ec-6cc8cb7867fb)
![Screenshot (130)](https://github.com/appwrite/appwrite/assets/65064521/0e4fbc84-532d-4e40-9bea-f18915d6a789)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Rondev9, thanks for creating this issue! 🙏🏼 Some questions:

1. Would you please share your project ID? 
2. How big is the file?
3. Is the user authenticated?

**Comment by Rondev9** [comment]
Hey @stnguyen90, Sorry for the delayed response. It was AppWrite server issue I guess. Now everything is working fine.
Thank you.
