### ISSUE TITLE
🚀 Feature: Update the install command to allow not starting Appwrite

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#7223]
### 🔖 Feature description

It would be nice to be able to run the install command to generate the files, but not start Appwrite.

### 🎤 Pitch

This is useful for cases where a developer only wants the files.

For the core team, it can also be used to generate the files for the website.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by zdanl** [comment]
Yes that.
