### ISSUE TITLE
🚀 Feature: A request for transparency

### ISSUE THREAD

**Issue by zdanl** [appwrite/appwrite#7224]
### 🔖 Feature description

It's really unclear, especially to those of us who are not super fond of Docker and only remember the times when the official website requested you to paste a curl .sh pipe | to bash as root for install, what 

```bash
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.4.12
```

is actually doing. It looks to the untrained eye such as if Docker had a registry like npm (oh, the security nightmares), and is gonna pull appwrite/appwrite:1.4.12 

Then it's a tangled web of microservices that hopefully turn up a powerful BaaS, but editing the code and understanding it, is very different.

I am advocating for a cleaner self-hosted process  with proper documentation and best-practices for multi-core and server farms, to realize big projects with Appwrite and improve it back and forth.

### 🎤 Pitch

See above.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by zdanl** [comment]
> Thank you for submitting this. We will move forward internally with how we can improve, make things clearer, and make the necessary changes.

Could we start with documentation on how to package Docker containers oneself, to verify its contents, and perhaps realize a Docker Swarm horizontal (scaling) setup?

I realize you are busy with Appwrite Cloud and are aiming to monetize on the open source project, but the current state of self-hosted documentation is really bad.

Just doing 

```bash
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:1.4.12
```

On a freshly set up Ubuntu 23.10 Bare Metal Server doesn't work. See Video.

https://github.com/appwrite/appwrite/assets/114028070/e84551c8-70f4-4ed3-b124-f6b65dd4e597

Thanks in advance!

**Comment by zdanl** [comment]
Could we start with some level of explanation of how this compilation of Docker images is created and what is the purpose of each one?

https://hub.docker.com/u/appwrite

I can build appwrite:dev meanwhile, by executing the multi-core build line outlined in the CONTRIBUTING.md file 

`docker buildx build --platform linux/amd64 -t zdanl/cryptwrite:prod --push .`

But not the other ones. What's the relationship between `appwrite-base` and `appwrite` ?

**Comment by eldadfux** [comment]
We've add a manual installation section in the docs to allow devs to imitate the steps of the script for more transparency and trust in case you don't want to install the automated installation script. More info here: https://appwrite.io/docs/advanced/self-hosting#manual
