### ISSUE TITLE
Doctor CLI: `_APP_OPTIONS_FORCE_HTTPS=disabled` not correctly evaluated

### ISSUE THREAD

**Issue by Gustl22** [appwrite/appwrite#723]
## 🐛 Bug Report

Doctor CLI shows `🟢 HTTP force option is enabled`, although it is disabled.

## Have you spent some time to check if this issue has been raised before?

I searched the issues for "doctor" and didn't find a similar bug. Also discussed on Discord.

## To Reproduce

1. Set [`environment` variable](https://appwrite.io/docs/environment-variables) in `docker-compose.yml` to `disabled`:
   ` - _APP_OPTIONS_FORCE_HTTPS=disabled`
2. Apply configuration with `docker-compose up -d`
3. Run doctor `docker-compose exec appwrite doctor`

## Expected behavior

Show this: 
🔴 HTTP force option is disabled

## Actual Behavior

![Screenshot from 2020-11-01 21-45-12_2](https://user-images.githubusercontent.com/18537755/97818097-a562e900-1ca0-11eb-86d7-6098f30114e4.png)

Shown:
🟢 HTTP force option is enabled

## Your Environment

- Appwrite Dev branch 0.7.x db7d7dd89ed7d82d45f0f3a14990de02291abfd1
- Ubuntu Server 20.04 arm64

## Solution

Check for string `enabled` instead of `empty`, see [doctor.php](https://github.com/appwrite/appwrite/blob/564c1f03814528cdbb7bdd584ca8309b7ea5e5a4/app/tasks/doctor.php#L78)

```
if (App::getEnv('_APP_OPTIONS_FORCE_HTTPS', 'disabled') === 'enabled')
```

If you confirm, I'd happy to start a Merge-Request :smile:

**Comment by eldadfux** [comment]
Fix has been merged to `0.7.x` branch 🚀 Thanks for reporting!
