### ISSUE TITLE
Doctor CLI: Harmonize negative check result descriptions 🔴

### ISSUE THREAD

**Issue by Gustl22** [appwrite/appwrite#724]
## 🚀 Feature

At the moment, the doctor tool has irregular result descriptions, which should be harmonized:

- Provide always actual state of the check result, not the "to be"-state on negative result.
- May add prompt, if state is not fulfilled on negative result [marked as optionally]
- Ensure that users with color weakness, get the right info.
- Ensure that you can copy / paste the result description and does not confuse without the emoji.

## Have you spent some time to check if this issue has been raised before?

I searched the issues for "doctor" and didn't find a similar issue. Also discussed on Discord.

## To Reproduce

1. Set some [`environment` variables](https://appwrite.io/docs/environment-variables) in `docker-compose.yml`, which lead to negative feedback such as `_APP_OPENSSL_KEY_V1`.
2. Apply configuration with `docker-compose up -d`
3. Run doctor `docker-compose exec appwrite doctor`

## Expected behavior

Show this descriptions accordingly to the checks: 
🟢 Hostname has a public suffix
🔴 Hostname has no public suffix [. Add a public suffix to make it accessible.]

🟢 CNAME target has a public suffix
🔴 CNAME target has no public suffix [. Add a public suffix to make it accessible.]

🟢 Using a unique secret key for encryption
🔴 Not using a unique secret key for encryption [. Change `_APP_OPENSSL_KEY_V1` to encrypt your data.]

🟢 App environment is set for production -> typo: **enviornment**
🔴 App environment is set for development [. Set it to production.]

🟢 Abuse protection is enabled
🔴 Abuse protection is disabled [. Please enable.]

## Actual Behavior

The negative result description is the same like the positive, and therefore not distinguishable in above cases :-1: .

These cases already have a distinguishable feedback :+1: :

🟢 Console access limits are enabled
🔴 Console access limits are disabled

🟢 HTTP force option is enabled
🔴 HTTP force option is disabled

🟢  [Volume] Volume is readable
🔴  [Volume] Volume is unreadable

🟢  [Volume] Volume is writeable
🔴  [Volume] Volume is unwriteable

## Your Environment

- Appwrite Dev branch 0.7.x db7d7dd89ed7d82d45f0f3a14990de02291abfd1
- Ubuntu Server 20.04 arm64

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes, I have :)

## Pitch

On running Doctor client, the result description isn't in contrast to the emoji and is more understandable and harmonizes with the other reusults. The prompt is optionally, but would help the user even more, what has to be done.

If you confirm, I'd happy to start a Merge-Request :smile:  Any suggestions for improvement are welcomed.

Related: #723, #415

**Comment by eldadfux** [comment]
I am totally fine with descriptions you suggested. I think a prompt would be a bit too much and may be very difficult to achieve as it requires a server restart to update new env vars, not very suitable for work in a cluster, and other issues that would probably pop up.

@Gustl22 would you like to submit a PR for the new descriptions?
