### ISSUE TITLE
🐛 Bug Report: Error with account.get() and no persistent login

### ISSUE THREAD

**Issue by sgaabdu4** [appwrite/appwrite#7253]
### 👟 Reproduction steps

I've created an email session and then tried to get the currently logged in User but I'm not able to login successfully. I'm not sure what the problem is.

```
    await account.createEmailSession(email: email, password: password);
    await account.get();
```

This is the error I'm getting while logging in. It was working a couple of months ago but when I came back to the app, it hasn't worked since.

`AppwriteException: general_unauthorized_scope, User (role: guests) missing scope (account) (401)`

I am creating an emailSession and logging in so I don't understand why its saying its a guest

### 👍 Expected behavior

Login successfully

### 👎 Actual Behavior

Not logging in

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

The latest flutter and latest appwrite package

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by vijaykumar1710** [comment]
I am also facing the issue since yesterday. account.get fails with 401 Unauthorized immediately after creating session.

**Comment by vijaykumar1710** [comment]
I was able to fix this by clearing browser history - cookie, cache etc

**Comment by sgaabdu4** [comment]
@vijaykumar1710 how did you do it? I'm using the iOS and android simulator.

**Comment by vijaykumar1710** [comment]
you can clear app cache and app data on android. Which will ask you login again.

**Comment by sgaabdu4** [comment]
I've deleted, deleted cache and app data and ran it again but the issue still persists for me.

**Comment by sgaabdu4** [comment]
@vijaykumar1710 thank you! This is what I tried.

1. I've tried deleting the local storage and cache for google chrome, did the same thing on the app. Ran it - same issue
2. Untoggled and toggled back the email/password login feature, deleted local storage and cache for google chrome, did the same thing on the app. Ran it - same issue

I'm not sure what's going on :(

**Comment by sgaabdu4** [comment]
Okay so I created a dummy database and it worked perfectly. I'm not sure why it wasn't working from the initial database.

**Comment by auzhye** [comment]
Im getting the same error D:

**Comment by stnguyen90** [comment]
@sgaabdu4, are you still experiencing this problem? If not, this is probably due to a problem with a 3rd party library we upgraded to which has been reverted on Cloud.

**Comment by stnguyen90** [comment]
Related issue: https://github.com/swoole/swoole-src/issues/5214

**Comment by sgaabdu4** [comment]
Hi @stnguyen90, I had to create another project and database for it to work. I've deleted the old one now.

**Comment by Mohammad-engineer** [comment]
for resolve this bug you must write you're **signInAccount** function like Below:

`
import { Account, Client} from "appwrite";

const client = new Client()
        .setEndpoint('https://cloud.appwrite.io/v1') // Your API Endpoint
        .setProject(appwriteConfig.projectId);   // Your PROJECT ID
        const account = new Account(client);
        const promise = account.createEmailSession(user.email,user.password)
        promise.then(function (response) {
            console.log(response); // Success
            const session = response
            return session
        }, function (error) {
            console.log(error); // Failure
        });`

**Comment by Mohammad-engineer** [comment]
simple way is bellow code 👍 

```javascript
function signInAccount(user: { email: string; password: string }) {
    try {
      const session = await account.createEmailSession(user.email, user.password);
  
      return session;
    } catch (error) {
      console.log(error);
    }
}
```
