### ISSUE TITLE
📚 Documentation: README mentions docker-compose.yml that doesn't exist

### ISSUE THREAD

**Issue by luke-hagar-sp** [appwrite/appwrite#7259]
### 💭 Description

The [documentation](https://github.com/appwrite/appwrite?tab=readme-ov-file#installation) mentions public docker-compose.yaml, and .env files, but the links seem to be dead with the site refresh

> For advanced production and custom installation, check out our Docker [environment variables](https://appwrite.io/docs/environment-variables) docs. You can also use our public [docker-compose.yml](https://appwrite.io/install/compose) and [.env](https://appwrite.io/install/env) files to manually set up an environment.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Oh, I see you're referring to the README at the bottom of the [Installation](https://github.com/appwrite/appwrite?tab=readme-ov-file#installation) section. Once we fix https://github.com/appwrite/appwrite/issues/6367, we can update the README to use the same path.

**Comment by eldadfux** [comment]
This is now fixed on the official docs and the repo readme file. Thanks!
