### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by binhthai167** [appwrite/appwrite#7269]
why i go to database and have this error

**Comment by stnguyen90** [comment]
@binhthai167, thanks for creating this issue! 🙏🏼 Are you still having a problem? Would you please provide more information including:

1. What were you doing before this happened?
2. Is this on Appwrite Cloud or self-hosted?
3. If on Appwrite Cloud, what's your project ID?

**Comment by stnguyen90** [comment]
@binhthai167 would you please provide more information? FYI, I'll have to close this due to inactivity soon.
