### ISSUE TITLE
Support Firebase OTP authentication

### ISSUE THREAD

**Issue by illuminated** [appwrite/appwrite#728]
## 🚀 Feature

Ability to create new users in AppWrite and authenticate them afterwards with a token issued by an external service such as Firebase.

Firebase offers authentication methods not available in AppWrite, like OTP, and there is trend of moving towards passwordless authentiocation of users. Apps with such a method implemented cannot use AppWrite for backend due to inability to authenticate those users through external authentication tokens.

## Have you spent some time to check if this issue has been raised before?

The only similar issue I have found is #511 but it's "reverse" from what I'm describing, it's for being able to authenticate AppWrite users on Firebase.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

## Pitch

Within a client mobile app I have a sign-in / sign-up flow which uses Firebase Phone auth (passwordless) flow.

I would like to be able to create new AppWrite account based on user's Firebase authentication token and from then on to use the Firebase's authentication token to authenticate the user in AppWrite API calls.

Alternatively, I could use AppWrite's token for API authentication, but the server would be able to verify the validity of the last submitted Firebase authentication token and if not valid to return a failure (error) that the Firebase auth token needs to be updated and resubmitted to AppWrite.

**Comment by illuminated** [comment]
@eldadfux I've been researching a bit how this can be achieved and I have found that Firebase Auth PHP SDK supports verification of their ID token. Explanation with some sample code can be found here: https://firebase-php.readthedocs.io/en/stable/authentication.html#verify-a-firebase-id-token

Seems like a straightforward way to do it.

The only thing missing would be AppWrite's create user and create session  API calls which support passing the Firebase ID token.

**Comment by TorstenDittmann** [comment]
I am not too confident this should be part of the product, since this can be achieved with existing features.

Gonna close this for now, can be re-opened if necessary 👍🏻

**Comment by afzl-wtu** [comment]
> 

How to make it possible? I want to use firebase phone authentication. As it provides a lot of smses free. So I can first authenticate a user with firebase SDK with flutter which is easy. But how to authenticate that user with appwrite?

**Comment by quibenefacit** [comment]
> > 
> 
> How to make it possible? I want to use firebase phone authentication. As it provides a lot of smses free. So I can first authenticate a user with firebase SDK with flutter which is easy. But how to authenticate that user with appwrite?

I second that.  This would a very useful feature for mobile apps.  Lack of it is what stops me from using Appwrite.

**Comment by quibenefacit** [comment]
> I am not too confident this should be part of the product, since this can be achieved with existing features.
> 
> Gonna close this for now, can be re-opened if necessary 👍🏻

Sure, sweep it under the rug.  If Appwrite doesn't take user requests seriously, users won't take Appwrite seriosuly either. 

The request is clearly to allow phone OTP for mobile apps.  Yet one response points to a PHP solution (hello, 2005 called and what's its slippers back), the other just says there are other solutions without mentioning them.  What a joke.
