### ISSUE TITLE
🐛 Bug Report:  github callback url 

### ISSUE THREAD

**Issue by hellomyheart** [appwrite/appwrite#7283]
### 👟 Reproduction steps

我使用docker compose 部署在本地， 按照官方教程配置的，我也注意到_APP_VCS_GITHUB_PRIVATE_KEY 要使用 \n替换换行，外面使用", 配置好重启之后， appwrite可以连接到github app， 登陆也是正常的，问题在登陆完成后，
没有回到我的appwrite, 而是还在github app， 我的appwrite使用的是 https部署， 外部是 nginx, nginx到本地的 appwrite是 http, 
比较令人在意的错误是在github, 第一个回调地址报错了， 第二个回调地址正常，但是这个配置我是按照官方文档配置的，我不知道哪里出现了问题
![image](https://github.com/appwrite/appwrite/assets/31239692/6c71addd-a4e6-4b8b-9f2a-1b0289e3309d)

### 👍 Expected behavior

github的配置页面不再报错，并且回调正常

### 👎 Actual Behavior

停留在github app

### 🎲 Appwrite version

Appwrite 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

ununtu 22.04 
docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@hellomyheart, thanks for creating this issue! 🙏🏼 Would you be able to translate to English so others can better follow along?

From what I gather, it looks like you're having a problem setting the callback URLs. Do you own the domain you entered?

**Comment by hellomyheart** [comment]
I deployed using Docker Compose locally, following the official tutorial. I also noticed that _APP_VCS_GITHUB_PRIVATE_KEY needs to use "\n" to replace line breaks, enclosed in double quotes. After configuring and restarting, Appwrite can connect to the GitHub app, and logging in works fine. The issue arises after logging in, as it doesn't return to my Appwrite; instead, it remains in the GitHub app. My Appwrite is deployed using HTTPS, with Nginx as the external-facing server, while Nginx to the local Appwrite is using HTTP. An intriguing error occurs in GitHub, where the first callback URL throws an error, while the second callback URL works fine. However, I configured this according to the official documentation. I'm not sure where the problem lies.

![290453883-6c71addd-a4e6-4b8b-9f2a-1b0289e3309d](https://github.com/appwrite/appwrite/assets/31239692/29d69fdd-3a63-46f0-8a6b-1d90ed6c58fc)


Appwrite 1.4.13
ubuntu 22.04
docker deploy

**Comment by hellomyheart** [comment]
> ，感谢您创建此问题！🙏🏼 你能翻译成英文，以便其他人可以更好地跟上吗？
> 
> 从我收集到的信息来看，您在设置回调 URL 时遇到了问题。您拥有您输入的域名吗？

Yes, the domain name I entered is mine.

**Comment by hellomyheart** [comment]
> @hellomyheart, thanks for creating this issue! 🙏🏼 Would you be able to translate to English so others can better follow along?
> 
> From what I gather, it looks like you're having a problem setting the callback URLs. Do you own the domain you entered?

Yes, the domain name I entered is mine.

**Comment by stnguyen90** [comment]
Perhaps you have another GitHub app using the same domain? Otherwise, you may need to reach out to GitHub.

**Comment by hellomyheart** [comment]
> Perhaps you have another GitHub app using the same domain? Otherwise, you may need to reach out to GitHub.

The hosts of these two callback addresses are the same. The first callback address returns an invalid response from GitHub, while the second one returns an error.

https://XXX/v1/vcs/github/callback
https://XXX/v1/account/sessions/oauth2/callback/github/console

When I directly accessed these two addresses in the browser, the second one returned a 400 error:

Error 400
Invalid `state` param: Value must be a valid string and at least 1 char and no longer than 2048 chars

Type
general_argument_invalid

However, the first one returned a 404 error:

{
    "message": "The requested route was not found. Please refer to the API docs and try again.",
    "code": 404,
    "type": "general_route_not_found",
    "version": "1.4.13"
}

So, I suspect the issue lies with Appwrite, not GitHub.

**Comment by stnguyen90** [comment]
> When I directly accessed these two addresses in the browser, the second one returned a 400 error:

This is expected because these are meant to be used as part of the GitHub integration. What happens when you try to link a repository in your project?

**Comment by hellomyheart** [comment]
When linking to a GitHub app within the app I deployed, the first step involves logging in and authentication. After successful validation, it remains on the GitHub app page without redirecting back to Appwrite. This results in a callback exception. Simultaneously, the configuration page of the GitHub app also indicates that the initial callback URL is invalid.

**Comment by stnguyen90** [comment]
> within the app I deployed, the first step involves logging in and authentication

App you deployed? This configuration you're setting up is not for an app that an end user logs into...it's for integrating Appwrite and GitHub for Appwrite Functions. Would you please clarify what you're trying to do?

**Comment by hellomyheart** [comment]
@stnguyen90 
The application I deployed refers to the GitHub app I configured according to the instructions at https://appwrite.io/docs/advanced/self-hosting/functions. After following the instructions on the website, within my self-hosted Appwrite environment, there are configurations for linking to GitHub in both the function creation and settings sections. Clicking on these links in both places redirects to the GitHub app for login verification. Based on my previous experience with login verification, after logging in, I expected to be redirected back to my self-hosted Appwrite application. However, this did not happen, and I remained within the GitHub app. Additionally, I noticed that in the GitHub app's callback URL configuration, the first callback URL was flagged as invalid, while the second callback URL was marked as valid.

You can consider it this way: I followed the instructions at https://appwrite.io/docs/advanced/self-hosting/functions for self-hosting and configuring the GitHub app. The occurrence of callback exceptions is most likely due to missing configurations in the tutorial or issues with the code related to self-hosted Appwrite and GitHub app in the current version of Appwrite (as of v1.4.13 as of December 10, 2023).

You can investigate in these three directions:

The tutorial at https://appwrite.io/docs/advanced/self-hosting/functions might have missing or incorrect configurations.
The code in Appwrite (as of v1.4.13 as of December 10, 2023) might have issues in the GitHub app's callback.
There might be incompatibility between the documentation at https://appwrite.io/docs/advanced/self-hosting/functions and the self-hosted code in Appwrite (as of v1.4.13 as of December 10, 2023). This could be due to outdated documentation, incomplete code implementation, or other reasons.
As time goes on, more self-hosted Appwrite instances may encounter similar issues. I am no longer using Appwrite. If Appwrite addresses the GitHub app's callback issue, or adds support for new code hosting platforms such as self-hosted GitLab or Gogs, or provides an open API to allow other developers to adapt to other code hosting platforms, it would be beneficial.

**Comment by stnguyen90** [comment]
Sorry to see you go. If you ever want to try it again, feel free to join our [Discord](https://appwrite.io/discord) as it would be easier to troubleshoot on there.
