### ISSUE TITLE
🐛 Bug Report: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by kazi331** [appwrite/appwrite#7284]
### 👟 Reproduction steps

I tried to login/register users following [this doc](https://appwrite.io/docs/quick-starts/react) and I'm getting this error all the time.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at Client.setEndpoint (appwrite.js?v=03a17f90:707:89)
    at appwrite.js:6:6
```

![Screenshot from 2023-12-14 15-42-00](https://github.com/appwrite/appwrite/assets/96835101/51008bec-9941-49bf-98fe-04d5a5112e9a)

### 👍 Expected behavior

a new account should be logged in

### 👎 Actual Behavior

```
 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at Client.setEndpoint (appwrite.js?v=03a17f90:707:89)
    at appwrite.js:6:6
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

"appwrite": "^13.0.1",

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@kazi331, thanks for creating this issue! 🙏🏼 Please double check your endpoint is set. Perhaps you can `console.log(client.config.endpoint)` to make sure.

**Comment by sameermakwana19** [comment]
I had same problem in one of my projects .
solution : Check where you have created the  '.env.local' file , if it's inside src folder just move it out of src .

**Comment by naganikshith04** [comment]
Did you solve the problem?

**Comment by kazi331** [comment]
> Did you solve the problem?

Yes,

**Comment by Samrudh713** [comment]
May I know how you solved the error, in case you have

**Comment by edrickalema** [comment]
Facing the same error here!

**Comment by Akchhya** [comment]
facing the same problem , but placing it out of src aint working @sameermakwana19 any other solutions??
