### ISSUE TITLE
🐛 Bug Report: Setting session length to 0 makes security tab unusable

### ISSUE THREAD

**Issue by DH-555** [appwrite/appwrite#7289]
### 👟 Reproduction steps

Go to console, Auth, Security, Session length, set it to 0 and click update.

![Screenshot_20231214-221052](https://github.com/appwrite/appwrite/assets/86196556/31220f60-45a0-4e8b-808b-0b6e2a0a3c6a)

### 👍 Expected behavior

It should not allow you to set it to 0 or if it allows you to, nothing should happen

### 👎 Actual Behavior

After setting it to 0, it's impossible to go to security tab if you reload the page

![Screenshot_20231214-221134](https://github.com/appwrite/appwrite/assets/86196556/b938a217-3d5e-4e66-8ee3-d0bb91115bbc)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Happens in all browsers and OS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@DH-555, thanks for creating this issue! 🙏🏼 I think there's a bug with [`createValueUnitPair()`](https://github.com/appwrite/console/blob/1b0c48e93baf0eed35cf6d2590c4d7a8e2e152b6/src/lib/helpers/unit.ts#L19) when `initialValue` is 0).

**Comment by Bilal-Gujjar** [comment]
@stnguyen90  I want to work on it will you assign me this issue?

**Comment by stnguyen90** [comment]
@Bilal-Gujjar, assigned! Thanks for your interest! 🙏🏼

**Comment by stnguyen90** [comment]
@Bilal-Gujjar, actually, it looks like we need to take care of this sooner. Apologies for the troubles!.

**Comment by stnguyen90** [comment]
@Bilal-Gujjar. would you like to add test cases for this in the [dev-1.4.x](https://github.com/appwrite/console/tree/dev-1.4.x) branch?

**Comment by ArmanNik** [comment]
@DH-555 we released a fix for it so now it should work :+1: Let me know if you are still having issues 

@Bilal-Gujjar thank you for your interest. I'm sorry we had to reassign it :pray:  as @stnguyen90 we would still love to have your contribution, and having some will make sure we don't run into similar issues in the future :blush:

**Comment by DH-555** [comment]
@ArmanNik Yes, solved. 
Thanks so much for the quick fix!
