### ISSUE TITLE
🐛 Bug Report: Error Creating Document

### ISSUE THREAD

**Issue by Onunkwor** [appwrite/appwrite#7297]
### 👟 Reproduction steps

When i try to create a document witnin my following collection I get the error shown below 
<img width="414" alt="Screenshot 2023-12-17 234250" src="https://github.com/appwrite/appwrite/assets/126721072/79bf81ad-8fe0-4706-8ce4-da2c5a1b4c2e">
The Function responsible for creating this document is
<img width="441" alt="Screenshot 2023-12-17 234635" src="https://github.com/appwrite/appwrite/assets/126721072/ba5a6148-455d-46a1-b68d-4b1f5ee9a33d">
I ids are logged In the console so I'm sure they are getting to the function with

### 👍 Expected behavior

It should add a document to my collection 

### 👎 Actual Behavior

nothing happens and I get the 500 (Internal Server Error)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

app write version is 13.0.0,

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Onunkwor** [comment]
@stnguyen90

**Comment by stnguyen90** [comment]
@Onunkwor, thanks for creating this issue! 🙏🏼 Would you please provide your project ID?

**Comment by kurtreicel03** [comment]
> @Onunkwor, thanks for creating this issue! 🙏🏼
> 
> 1. Would you please provide your project ID?
> 2. Are you using relationships?

I have exactly same issue with him
here's my project ID '657d9312c6cefd038f14'
i'm using relationship with two collection

![Screenshot 2023-12-19 at 11 35 48 AM](https://github.com/appwrite/appwrite/assets/71879807/fa6671f6-d5c2-42bf-88d7-57dbb430a910)
![Screenshot 2023-12-19 at 11 35 29 AM](https://github.com/appwrite/appwrite/assets/71879807/2c251ef8-04fb-4dbc-9597-38fc96ec716a)

**Comment by stnguyen90** [comment]
@Onunkwor, would you please share the details about your collection? It seems like `username` is not a valid attribute.

**Comment by Onunkwor** [comment]
@stnguyen90 I have a users collection and a following collection the following collection has a relationship with the users collection and I pass the id of the user into the collection. i fixed the user name attribute by the way thank you. my project id is 655222a9f32b9149584f. 
<img width="378" alt="Screenshot 2023-12-19 190115" src="https://github.com/appwrite/appwrite/assets/126721072/fb9285c2-c0f4-45df-99c1-bccfd2248f5d">
<img width="434" alt="Screenshot 2023-12-19 190227" src="https://github.com/appwrite/appwrite/assets/126721072/a7e8c219-dab2-459d-a892-c78f9ab03cf6">

**Comment by Onunkwor** [comment]
@kurtreicel03  i think the issue is because the user isn't in a curly bracket

**Comment by Onunkwor** [comment]
@stnguyen90 At first, I thought the error was from Appwrite. So, whenever I made any changes to the relationship or my code, I would delete the entire collection and start over. I've done that 10 times or more (I make a lot of mistakes 😂).

Additionally, when creating the function to add a document to the collection, I initially passed userId and accountId instead of just user. This was because, at that time, I had only one attribute in my 'Following' collection, which is a relationship with my 'User' collection with the attribute key set to 'user'.
<img width="839" alt="Screenshot 2023-12-19 203237" src="https://github.com/appwrite/appwrite/assets/126721072/024a5203-b552-4d0e-8b32-8b4255256b5c">

**Comment by stnguyen90** [comment]
@Onunkwor, I'm seeing multiple errors about incorrect attribute keys being passed to Appwrite. Please make sure you're passing the correct attribute key.

Since there isn't anything wrong with Appwrite, I'm going to close this issue.

If you need additional help, please join us on [Discord](https://appwrite.io/discord) and create a support post there.
