### ISSUE TITLE
🐛 Bug Report: Wrong error message on createEmailSession

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7299]
### 👟 Reproduction steps

When user doesn't exist it throws Error message: **AppwriteException: Invalid credentials. Please check the email and password.**

### 👍 Expected behavior

The error message should be that user doesn't exist.

### 👎 Actual Behavior

It is not possible to distinguish from situation when user exists, but entered wrong password.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@step135, thanks for creating this issue! 🙏🏼 This is the expected behavior because we don't want to leak information about whether a user exists or not.

**Comment by step135** [comment]
Firebase has an option to allow leaking that information. This can be a new feature here too.

**Comment by stnguyen90** [comment]
For now, we'd rather not.
