### ISSUE TITLE
Getting General Unknown Error Everytime I create my datatbase using databases.createDocument()

### ISSUE THREAD

**Issue by sshntpdl** [appwrite/appwrite#7309]
argument #0:

  'Appwrite service :: createAccount() :: '
 error:

  AppwriteException {
    name: 'AppwriteException',
    code: 500,
    type: 'general_unknown',
    response: {
      message: 'Server Error',
      code: 500,
      type: 'general_unknown',
      version: '0.11.59'
    },
    fileName: 'http://localhost:5173/node_modules/.vite/deps/appwrite.js,
    lineNumber: 550,
    columnNumber: 5,
    message: 'Server Error'
  }

**Comment by stnguyen90** [comment]
@sshntpdl thanks for raising this issue! 🙏🏼 Would you please share your:

1. code for `createAccount()`
2. your payload send to Appwrite
3. project id

By the way, it would be best to create a support post on our [Discord](https://appwrite.io/discord) server as it would be easier to troubleshoot there than on GitHub.

**Comment by sshntpdl** [comment]
//Code

async createAccount({email, password, name}){
        try {
            const avatars = new Avatars(this.client);
            const avatarUrl = avatars.getInitials(name);
            const userAccount = await this.account.create(ID.unique(), email, password, name)
            if(!userAccount){
                throw Error
            }
            const userId = userAccount.$id
            const newUser =await this.databases.createDocument(
                conf.appwriteDatabaseId,
                conf.appwriteUsersCollectionId,
                ID.unique(),
                {
                    UserId : userId,
                    Username : name,
                    Password : password,
                    Email : email,
                    ImageUrl : avatarUrl
            })
            console.log(newUser)
            if(!newUser){
                console.log('newUser Error')
                throw Error
            }else{
                console.log('login')
                return this.login({email, password})
            }
        } catch (error) {
            console.log("Appwrite service :: createAccount() :: ", error)
        }
    }

Project Id: 658007509e9aafc29f2c

**Comment by sshntpdl** [comment]
https://discord.com/channels/564160730845151244/1187244183107420261
