### ISSUE TITLE
🐛 Bug Report: cant use relationship attr in a collection. encountered a server side issue [error code: 500]

### ISSUE THREAD

**Issue by birdiegyal** [appwrite/appwrite#7324]
### 👟 Reproduction steps

 try to create a document in a collection with the relationship attr defined.
![Screenshot from 2023-12-24 18-38-06](https://github.com/appwrite/appwrite/assets/149292478/aca95199-74c7-4248-b8e7-f180fb6bb2e5)

code thats responsible for creating a document.

```javascript
export async function createOffer(offer: OfferTyp) {

    try {
        const uploadedBanner = await uploadFile(offer.offerBanner[0]) as OfferTyp4Tsinference
        
        if (!uploadedBanner) throw Error

        const offerBannerUrl = await getFilePreview(uploadedBanner.$id, 1000, 1000) as any
        
        if (!offerBannerUrl) {
            await deleteFile(uploadedBanner.$id)
            throw Error
        }

        const offerDoc = await databases.createDocument(
            appwriteConfig.dbId,
            appwriteConfig.offersColl,
            ID.unique(),
            {
                offerCreator: offer.creator,
                offerBanner: offerBannerUrl,
                offerDescription: offer.offerDescription,
                offerBannerID: uploadedBanner.$id,
            },

        )

        console.log(offerDoc)

        if (!offerDoc) {
            await deleteFile(uploadedBanner.$id)
            throw Error
        }

        return offerDoc   
    } catch (error) {
        console.error(error)
        return null
    }

    /* 
     WORKFLOW: 
     ✅ upload the offerBanner from the offer.
     ✅ get the uploaded file preview to be included inside the document thats gon be created raft.
     ✅ create a document in the offersColl and return.
    */
}
```

### 👍 Expected behavior

i think it has got to do some with the relationship attr because when im creating a document in users collection while signing up the user everything is good [i didnt use relationship attr in there].
in offers collection, where im using the relationship attr for pointing towards the offer creator, it returns the error with code 500.

### 👎 Actual Behavior

im supposed to get the application/json result with code 200. 
all im getting is application/json result with code 500.

![Screenshot from 2023-12-24 18-31-14](https://github.com/appwrite/appwrite/assets/149292478/4adc4c9b-f6ee-4b88-b061-996e06a13a95)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite sdk for web v13.0.1
os: ubuntu 22.04 lts

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@birdiegyal, thanks for raising this issue! 🙏🏼 The problem might be with permissions on the related collections. Would it be possible for you to create a support post on our [Discord](https://appwrite.io/discord)? It would be much easier to troubleshoot on there than on GitHub.
