### ISSUE TITLE
On fresh install, clamav container fills up the disk

### ISSUE THREAD

**Issue by akago-dev** [appwrite/appwrite#733]
## 🐛 Bug Report

After a fresh install, appwrite is unusable after a few minutes due to a full disk (25 gb)

## Have you spent some time to check if this issue has been raised before?

yes

## To Reproduce

On a brand new digitalocean droplet (ubuntu 20.04 LTS) : 
1. install appwrite with the docs command. 
2. No custom options
3. Create an account, a project, and a collection (not sure if necessary to reproduce)
4. Check the disk usage with : `docker system df -v`

The disk should start to fill

## Expected behavior

Appwrite should run without fills the disk if no files were uploaded

## Actual Behavior

The disk started to fill because of the clamav container 

After a few minutes, with no uploaded files : 
![image](https://user-images.githubusercontent.com/56194420/98796114-538e3180-240b-11eb-995a-d89e3e7ba768.png)

## Your Environment

DigitalOcean droplet 
1 GB Memory / 25 GB Disk / FRA1 - Ubuntu 20.04 (LTS) x64
No specific configuration
Commands ran by root user

**Comment by akago-dev** [comment]
@eldadfux told me to try those two solutions : 
1. Disable ClamAV using our env var, available here: https://appwrite.io/docs/environment-variables check the `_APP_STORAGE_ANTIVIRUS` option. This will make sure you can still use the storage API with clamav container stopped.

2. Update the ClamAV container to version 1.2.0 from you docker-compose.yml file and recreate it using `docker-compose up -d`


I tried to update the clamav container to 1.2.0 but got an issue on clamav startup : 
![image](https://user-images.githubusercontent.com/56194420/98796604-dca56880-240b-11eb-9756-714c4e291d18.png)

**Comment by eldadfux** [comment]
Should be fixed in v0.7. Make sure to have enough free memory/cpu on your system or disable clamav.
