### ISSUE TITLE
🚀 Feature: exporting emails of all users

### ISSUE THREAD

**Issue by AidenY69** [appwrite/appwrite#7337]
### 🔖 Feature description

The ability to export the users contact info, primarily name and email into a standard format such as CSV

### 🎤 Pitch

When sending newsletters, or product updates etc, there is currently no way of actually exporting the users and adding them to existing communication channels. Right now I use a banner on my webpage to announce new features etc, but it would be very very useful to be able to export the emails so I can import to my newsletter software and send product updates (features, bugs, etc)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@AidenY69, thanks for raising this issue! 🙏🏼 I would suggest using a [server SDK](https://appwrite.io/docs/sdks#server) to call the [List users](https://appwrite.io/docs/references/cloud/server-nodejs/users#list) API to dump all the data. Better yet, you can create an Appwrite function that does this regularly, [uploading](https://appwrite.io/docs/products/storage/upload-download) a CSV to a bucket.

**Comment by AidenY69** [comment]
> @AidenY69, thanks for raising this issue! 🙏🏼 I would suggest using a [server SDK](https://appwrite.io/docs/sdks#server) to call the [List users](https://appwrite.io/docs/references/cloud/server-nodejs/users#list) API to dump all the data. Better yet, you can create an Appwrite function that does this regularly, [uploading](https://appwrite.io/docs/products/storage/upload-download) a CSV to a bucket.

I was hoping to make something easy and intuitive that an SEO marketer could login to the appwrite admin dashboard and just export the list then do their newsletter stuff, but that's actually a good idea about the functions and just creating an automatic schedule of accounts to exports that the marketer can use.
