### ISSUE TITLE
🐛 Bug Report: create file button issue

### ISSUE THREAD

**Issue by ar-mohanty** [appwrite/appwrite#7338]
### 👟 Reproduction steps

When I am trying to create file in bucket  suddenly the button got disabled in state and I've not reached limit yet.
<img width="934" alt="Screenshot_20231226_092613" src="https://github.com/appwrite/appwrite/assets/68963714/5df03901-c803-4ef0-8945-1873e2aea8df">
<img width="936" alt="Screenshot_20231226_092757" src="https://github.com/appwrite/appwrite/assets/68963714/7bdf1557-ace2-4b86-81c9-6f16a3fd5413">

### 👍 Expected behavior

It should allow me to add new files or in my case images.

### 👎 Actual Behavior

I am not allowed to add new files

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I am using appwrite cloud 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ar-mohanty, thanks for raising this issue! 🙏 We'll look into this soon.

**Comment by ArmanNik** [comment]
Thanks for the feedback :+1: 
Should be fixed once this is merged https://github.com/appwrite/console/pull/690 and a new version is released :blush:

**Comment by ar-mohanty** [comment]
Thank you guys for your prompt response and fixes. Now I can continue my project have a great day!👍
