### ISSUE TITLE
Error 500 in Storage

### ISSUE THREAD

**Issue by abel-banze** [appwrite/appwrite#7342]
### 👟 Reproduction steps

I've been facing serious issues when it comes to access my storage buckets. 
I want to change the permissions and I can't access my buckets. It always returns error 500.

### 👍 Expected behavior

Open the stogare buckets to manipulate the content.

### 👎 Actual Behavior

![Captura de Ecrã (467)](https://github.com/appwrite/appwrite/assets/72819474/a2f21acf-eae3-42a4-8911-215d07fccebc)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

AppWrite Cloud 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Related discord thread: https://discord.com/channels/564160730845151244/1189260313665740862

**Comment by cbum-dev** [comment]
Refreshing the page will do your job for now.

**Comment by stnguyen90** [comment]
As we discussed on Discord, it looks like one of your projects is malformed causing the usage calculation to fail with a 500 error. We'll need to clean up your malformed project before this will work.
