### ISSUE TITLE
🚀 Feature: After login with email and password no information if email is verified 

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7343]
### 🔖 Feature description

`createEmailSession` doesn't return the information if email is verified, so i need to get it by another call by method `get`, Both calls are also very slow, around 700 ms to get the response.

### 🎤 Pitch

Slow REST API needs to minimize the requests for better user experience.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@step135, thanks for creating this issue! 🙏🏼 It is expected there is no information about whether the user is verified in the session. `account.get()` is the correct way to get information about the user. We are also working to improve the performance on Cloud to reduce the response time.

**Comment by step135** [comment]
Why don't you add the result of `account.get()` into information about session? It would also simplify the code.
