### ISSUE TITLE
🐛 Bug Report: Verification email not sending

### ISSUE THREAD

**Issue by satnamalhan** [appwrite/appwrite#7363]
### 👟 Reproduction steps

session not create email sending

### 👍 Expected behavior

when login session create after verification 

### 👎 Actual Behavior

tcp

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@satnamalhan, thanks for creating this issue! 🙏🏼 Are you saying you expect an email to be sent to a user to verify their account automatically? If so, that's not the case. You'll need to call the [Create email verification](https://appwrite.io/docs/references/cloud/client-web/account#createVerification) API. 

I typically check the [user](https://appwrite.io/docs/references/cloud/models/user) `emailVerification` attribute after authenticating and calling [`account.get()`](https://appwrite.io/docs/references/cloud/client-web/account#get) and if they aren't verified, show a banner that prompts them to click a button to send the email.
