### ISSUE TITLE
🚀 Feature: Zoho OAuth Provider

### ISSUE THREAD

**Issue by UtkarshAhuja2003** [appwrite/appwrite#7364]
### 🔖 Feature description

Adds Zoho OAuth provider

### 🎤 Pitch

This will allow users to add Zoho as auth using Appwrite.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
The PR was merged and the OAuth adapter will be available in Appwrite 1.5
