### ISSUE TITLE
🐛 Bug Report: Query.search does not search properly when there are two or more sentences 

### ISSUE THREAD

**Issue by KomengTech** [appwrite/appwrite#7370]
### 👟 Reproduction steps

When I search “new soya” for the attribute “name”. e.g: Query.search(“name”, “new soya bean”)

### 👍 Expected behavior

The data should return the value that starts or contains with the words “new soya bean” in that specific order.

### 👎 Actual Behavior

The data returned is all the data that starts or contain with the words  “new”, then the data that starts or contains with the words “soya”, and lastly the data that starts or contains with the words “bean”.

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

I use flutter to call the database with the query search.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@KomengTech, thanks for raising this issue! 🙏🏼 It looks like this is behaving as expected. It works the same as if you went to Google and searched for `new soya bean`. If you want to return matches in that order, wrap the query with double quotes like `Query.search("name", '"new soya bean"')`.

For more info on how search works, see https://github.com/appwrite/appwrite/discussions/5005#discussioncomment-4681079
