### ISSUE TITLE
🐛 Bug Report: My Database is corrupted on Cloud - cannot continue to work

### ISSUE THREAD

**Issue by minecrawler** [appwrite/appwrite#7389]
### 👟 Reproduction steps

1. Create DB in Console
2. Create 2 collections in Console
3. Create attributes in Console
4. Create relationship attribute in Console
5. Delete relationship attribute in Console (stuck with status "deleting")

At this point I tried to create a new string attribute in Console, but it was stuck at "processing". I tried deleting it in Console, but nothing happened.

6. Delete broken collection in Console (it disappears from the Console)
7. Try to create a new collection in Console <- It will just hang without a server reply

I'm at a loss what to do, since I cannot continue to work on my app without being able to create collections at all.

### 👍 Expected behavior

Creation and deletion is successful

### 👎 Actual Behavior

Broken DB. I didn't try to delete the DB, but I honestly don't want to try that as long as someone might be able to go take a look at the cloud DB. At least I want to wait a bit longer and see if it fixes itself...

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Something else

### 🧱 Your Environment

Using Cloud Console in FF 121.0 on Windows 11

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sourabpramanik** [comment]
@minecrawler trying to reproduce this issue following the steps. Just a question which delete method did you selected when creating the relationship attribute?

**Comment by minecrawler** [comment]
@sourabpramanik I selected the following. However it seems like waiting did indeed fix the issue of at least being able to create a new collection. Maybe there's a problem in the code, though, which causes this kind of delay...

![image](https://github.com/appwrite/appwrite/assets/1130708/b7f67903-9fd6-4dd9-9a9e-0c3232c847ce)

**Comment by sourabpramanik** [comment]
Thank you for providing the details. And yes sometimes it takes a bit of time to set up. 

It's great that your issue got resolved 🚀

**Comment by stnguyen90** [comment]
@minecrawler can this be closed now?

**Comment by minecrawler** [comment]
@stnguyen90 I dunno. I had to stop working for several hours (which means monetary loss depending on the contract in a normal development environment). In my opinion, that's a big issue, and it's not fixed, yet.

My personal problem _this time_ is solved.

**Comment by stnguyen90** [comment]
@minecrawler, you may have been facing https://github.com/appwrite/appwrite/discussions/6464#discussioncomment-7178972. That said, we are working on improving this.
