### ISSUE TITLE
🚀 Feature: Allow login, disable creating account

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7393]
### 🔖 Feature description

It is impossible to disable creating password/email accounts on client side and allow only login and change of password.

### 🎤 Pitch

It is important for security reasons that developers can restrict creation of accounts only to server side, not enable it in JavaScript.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@step135, thanks for creating this issue! 🙏🏼 How about [this](https://github.com/appwrite/appwrite/discussions/6049#discussioncomment-8017588)?

**Comment by eldadfux** [comment]
Closing for now, can reopen if more valuable feedback pops up.
