### ISSUE TITLE
🐛 Bug Report: Verification email after signup

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7399]
### 👟 Reproduction steps

Appwrite should automatically send confirmation email when a new account is created. Also Appwrtite should handle the link and manage confirmation on its own.

It is not possible to achieve it neither manually as the function call to send verification email fails.

### 👍 Expected behavior

Standard and simple solution as it exists for more than 20 years and all other auth providers work that way.

### 👎 Actual Behavior

Very complicated without any logic behind and forcing developers to do workarounds and create dirty codes.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@step135, thanks for raising this issue! 🙏🏼 It's expected for Appwrite to not send an email for verification automatically as it is the responsibility of the developer to decide whether they need email verification or not and where/how they will handle the verification.

I typically check the [user](https://appwrite.io/docs/references/cloud/models/user) `emailVerification` attribute after authenticating and calling [`account.get()`](https://appwrite.io/docs/references/cloud/client-web/account#get) and if they aren't verified, show a banner that prompts them to click a button to send the email.

That said, there is a [feature request](https://github.com/appwrite/appwrite/issues/1030) for having a page that handles the verification out of the box. If that is something you're interested in, make sure to add a 👍🏼 to the issue.
