### ISSUE TITLE
🚀 Feature: Missing support for callback function

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7407]
### 👟 Reproduction steps

Make a call at `https://cloud.appwrite.io/v1/databases/{dbId}/collections/{calId}/documents/{docId}?project=657e22639d821dd86de4&callback=load`

### 👍 Expected behavior

It should return `load({...});`

### 👎 Actual Behavior

Returns only '{...}'

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@step135, thanks for creating this issue! 🙏What do you mean by this?

> It should return `load({...});`

We don't support passing a callback param so I'm not sure what you're expecting. 🧐

**Comment by step135** [comment]
It is standard behaviour that other databases in their REST API have.

**Comment by stnguyen90** [comment]
Would you please provide more detail about what this standard behavior is and why you need it?

**Comment by step135** [comment]
You have never heard about JSONP, haven't you?

**Comment by step135** [comment]
You have never heard about JSONP, have you?

**Comment by stnguyen90** [comment]
@step135, It might be better to handle that outside of Appwrite with maybe an API gateway/proxy or maybe with a function. I don't think we want to include this into Appwrite itself so I'm going to close this for now.
