### ISSUE TITLE
🚀 Feature: Verification email after signup

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7413]
### 🔖 Feature description

Appwrite should automatically send confirmation email when a new account is created. Also Appwrite should handle the link and manage confirmation on its own.

It is not possible to achieve it neither manually as the function call to send verification email fails.

👍 Expected behavior
Standard and simple solution as it exists for more than 20 years and all other auth providers work that way.

👎 Actual Behavior
Very complicated without any logic behind and forcing developers to do workarounds and create dirty codes.

### 🎤 Pitch

Don't overcomplicate always everything. Who want to manage fake accounts and not existing emails? At least, make possible on automatic basis what you disallow manually!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by step135** [comment]
@notsarv Why won't be handy?

**Comment by step135** [comment]
@notsarv Why won't it be handy?

**Comment by step135** [comment]
@notsarv 

1) Why are you forcing developers to implement your logic as the only one possible solution? 

2) Why won't it be handy?

**Comment by eldadfux** [comment]
The code exampled shared @notsarv is the intended way to use account verification. As @notsarv mentioned we intentionally separated this flow from the main signup as it might not be the desired auth flow for every application.

A good example is the Appwrite console which is also built on top of Appwrite Auth, where we didn't want to add this as a mandatory step for all developers.

**Comment by eldadfux** [comment]
Closing this issue for now, happy to reopen if needed.
