### ISSUE TITLE
Better UX when adding an new unavailable platform in the console

### ISSUE THREAD

**Issue by Glide7** [appwrite/appwrite#742]
## 🚀 Feature

(A clear and concise description of what the feature is.)

## Have you spent some time to check if this issue has been raised before?

(Have you googled for a similar issue or checked our older issues for a similar bug)

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

When adding a new platform that's not available (IOS/Android/Unity) at the moment, it just greys out. As suggested by [Nils](https://github.com/AndroidNils), it will be more clear if we will add "Coming soon" after the platform name.

**Comment by eldadfux** [comment]
@AndroidNils better?
![image](https://user-images.githubusercontent.com/1297371/101292775-3f76fd80-381a-11eb-9345-3fe3c47d6e99.png)

**Comment by AndroidNils** [comment]
Yes, great!

**Comment by eldadfux** [comment]
@AndroidNils awesome! Gonna submit a PR.

**Comment by eldadfux** [comment]
Version 0.7 is out with the update 🚀
