### ISSUE TITLE
Inavlid Origin. Register your new client (<domain>) as a new Web platform on your project console using appwrite/install and custom domain

### ISSUE THREAD

**Issue by saibotma** [appwrite/appwrite#743]
I'm using `appwrite/install` to install my appwrite instance. During the installation I enter localhost for host, `8004` for HTTP and `8005` for HTTPS and my domain for CNAME.

```
docker run -it --rm     
--volume /var/run/docker.sock:/var/run/docker.sock     
--volume "$(pwd)"/appwrite:/install/appwrite:rw     
-e version=0.6.2     
appwrite/install
```

All the containers start and run without any issues and I can access the login and signup pages of appwrite.

I also use a separate nginx instance to proxy all the requests of my domain to appwrite. I can also post this config in case this has to do with the issue.

When I create a new account I get the error message `Registration Failed. Please try again later in the user interface and 403 Inavlid Origin. Register your new client (<domain>) as a new Web platform on your project console in the browser console`.

Same issue on StackOverflow: https://stackoverflow.com/questions/65088440/appwrite-error-inavlid-origin-register-your-new-client-domain-as-a-new-web

**Comment by eldadfux** [comment]
403 error means Appwrite does not recognize this web client and protects you from a [CSRF][1] attack.

A few things, set _APP_DOMAIN and _APP_DOMAIN_TARGET both to your actual domain name and not localhost.

That should get you going without a proxy, with a proxy you should make sure it passes the host name to the Appwrite server. This might help when using Nginx as a proxy: https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#passing-request-headers

[1]: https://owasp.org/www-community/attacks/csrf#:~:text=Cross%2DSite%20Request%20Forgery%20(CSRF,which%20they're%20currently%20authenticated.

**Comment by eldadfux** [comment]
@saibotma would be great if you could share your final nginx settings that worked well for you, we can also use that for the official docs.

**Comment by TorstenDittmann** [comment]
I am going to close this for now. If this gets relevant again, we can re-open it 👍🏻

**Comment by rumbis** [comment]
i have that issue  by proxying with apache 2.4

**Comment by rumbis** [comment]
I just found the solution for proxying correctly  from Apache2.4  you can find it [here](https://github.com/appwrite/appwrite/discussions/4056)

**Comment by Raj007to8** [comment]
Hi All.....
In Appwrite self-hosted whenever try to Create user using the flutter sdk getting the below issue. Already both android and flutter platform is added in the project.

message: Invalid Origin. Register your new client (<DOMAIN>) as a new Android platform on your project console dashboard, code: 403, type: general_unknown_origin, version: 1.1.2

**Comment by Raj007to8** [comment]
Hi All.....
In Appwrite self-hosted whenever try to Create user using the flutter sdk getting the below issue. Already both android and flutter platform is added in the project.

message: Invalid Origin. Register your new client (<DOMAIN>) as a new Android platform on your project console dashboard, code: 403, type: general_unknown_origin, version: 1.1.2
