### ISSUE TITLE
There should be a single authentication header required per authentication method (not x-api-key + x-api-project)

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [appwrite/appwrite#7433]
### 👟 Reproduction steps

I checked the swagger 1.4.x json in postman. E.g. the endpoint to list users (`{{baseUrl}}/users?search=`) automatically sets the authorization header as follows:

  Key: X-Appwrite-Project
  Value: {{apiKey}}

The X-Appwrite-Key however is not set by default.

### 👍 Expected behavior

I think these two variables and headers predefined in the swagger definition would reflect what should actually be done if I'm not mistaken:

  Key: X-Appwrite-Project
  Value: {{apiProject}}

  Key: X-Appwrite-Key
  Value: {{apiKey}}

At least when setting these it works as expected.

### 👎 Actual Behavior

It works as long as you set the environment variable `apiKey` to be the Project ID and add another variable for the api key.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

postman

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by HerrMuellerluedenscheid** [comment]
This is an issue of postman which cannot handle multiple authorization header fields.

**Comment by HerrMuellerluedenscheid** [comment]
> This is an issue of postman which cannot handle multiple authorization header fields.

Actually, postman is following the convention that there can be only one authentication header field:
https://greenbytes.de/tech/webdav/rfc7235.html#header.authorization

It could be worth considering to move the `X-Appwrite-Project` field out of the authenticaiton scope and providing it as a standard header field as this would then be picked up e.g. by swagger.

**Comment by eldadfux** [comment]
This shouldn't block you from using postman. I also use it and just add the headers to my requests. 
<img width="608" alt="image" src="https://github.com/appwrite/appwrite/assets/1297371/f6f9d00b-7472-4cdd-b599-769be02c845f">
