### ISSUE TITLE
🐛 Bug Report: Not able to preview image files from storage bucket

### ISSUE THREAD

**Issue by nakshjajoo** [appwrite/appwrite#7438]
### 👟 Reproduction steps

I am creating a social media application, and wanted to store images that the user posts. Whenever the app adds new images to the bucket, the image preview displays it as a blank white image placeholder. When I try to download the file, it downloads in the original format, implying that it is being uploaded but not being able to preview correctly. I am not able to figure out how to display the actual images instead of these blank images.

![preview](https://github.com/appwrite/appwrite/assets/148020796/e82026dc-65da-40bd-b68f-eacf5c880f23)

### 👍 Expected behavior

I want to get the preview in my codebase and display it on the home page of the application, so that the users can scroll through the images. 

### 👎 Actual Behavior

All the images are being rendered as the same white placeholder image. Even on the Appwrite website, the bucket storage displays the blank placeholder for the preview. 

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite Version - 13.0.1
I am using it in a react project

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
What image format are you trying to use? Can you share the source file here?

**Comment by nakshjajoo** [comment]
I have tried using jpg, jpeg, and png files, but none of them are working.

**Comment by eldadfux** [comment]
This are the supported [file formats](https://github.com/appwrite/appwrite/blob/main/app/config/storage/inputs.php). If you could attach the files that caused the issues we could farther investigate.

**Comment by nakshjajoo** [comment]
I don't know how, but somehow it has started working automatically. Thank
you very much for your help!
