### ISSUE TITLE
🐛 Bug Report: metadata error uploading large file

### ISSUE THREAD

**Issue by LatterDev** [appwrite/appwrite#7439]
### 👟 Reproduction steps

Open the console and upload a large (1GB+) zip file from the storage tab.

### 👍 Expected behavior

File would successfully upload.

### 👎 Actual Behavior

File stopped downloading at 45% and an error message would display stating "Invalid document structure: Attribute "metadata" has invalid type. Value must be a valid string
![appwriteerror1](https://github.com/appwrite/console/assets/138204855/bdae2f8c-5bae-44c0-aed4-fbf64d9fcd7f)
![appwriteerror2](https://github.com/appwrite/console/assets/138204855/b27a7b78-9640-4435-b06e-d81b2dc1a9d2)
![appwriteerror3](https://github.com/appwrite/console/assets/138204855/db96e85d-e3b4-4b7e-988f-5a979523255c)
"

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite is self hosted on digital ocean using digital ocean spaces as 3rd party storage.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@LatterDev, thanks for creating this issue! 🙏 Looks like the problem is the metadata is too large for such a big file:

https://github.com/utopia-php/storage/blob/faa0279519ac14f3501e8b138e0865ad9d12bff6/src/Storage/Device/S3.php#L260

We probably need to increase the size of the metadata attribute.

**Comment by stnguyen90** [comment]
Discord thread: https://discord.com/channels/564160730845151244/1195218402726379530
