### ISSUE TITLE
CORS Error when trying to access API on a locally deployed Appwrite running on a Docker Container

### ISSUE THREAD

**Issue by moazzam-qureshi** [appwrite/appwrite#7445]
I have set the hostname as 'localhost' as mentioned in the docs. 
Furthermore, I have implemented an Angular SPA locally as a front-end.

Access to XMLHttpRequest at 'http://localhost/v1/account/sessions/current' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field x-sdk-name is not allowed by Access-Control-Allow-Headers in preflight response.

I keep getting the above error regardless of which end point I am trying to access

**Comment by eldadfux** [comment]
Which SDK and Appwrite versions are you using?

**Comment by EVDOG4LIFE** [comment]
Closing as stale due to no user response.

@moazzam-qureshi - please see https://appwrite.io/blog/post/cors-error for common solutions to this. 

If you need further help, I recommend joining our Discord server at https://discord.gg/appwrite.
