### ISSUE TITLE
🚀 Feature: Disable webhook

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7446]
### 🔖 Feature description

Missing possibility to disable/activate webhook.

### 🎤 Pitch

It is possible to delete webhook, but it is not enough.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Hey, this change is already in work and might make it to the next release.
![image](https://github.com/appwrite/appwrite/assets/1297371/8475bbc1-41d3-4243-bab7-db4883814729)

**Comment by stnguyen90** [comment]
Released in 1.5.0
