### ISSUE TITLE
Add Repo-rater badge 

### ISSUE THREAD

**Issue by amanr-dev** [appwrite/appwrite#7448]
Add Repo-rater badge in README.md

**Comment by eldadfux** [comment]
@amanr-dev sorry, but we try to reduce the clutter, and seems like we can skip this one. I'll be closing the issue.

**Comment by amanr-dev** [comment]
> @amanr-dev sorry, but we try to reduce the clutter, and seems like we can skip this one. I'll be closing the issue.

I understood, thanks for the review😊.
