### ISSUE TITLE
Missing hint to remove the smtp dependency from appwrite when connection a custom SMTP server

### ISSUE THREAD

**Issue by saibotma** [appwrite/appwrite#745]
## 📚 Documentation

The documentation is missing the hint to remove the SMTP dependency from appwrite in `docker-compose.yml` when connecting a custom SMTP server. It just tells the user to remove the `smtp` part.

<img width="799" alt="Screenshot 2020-12-01 at 16 29 49" src="https://user-images.githubusercontent.com/26022902/100761105-cc711f80-33f2-11eb-8ea8-d923dd572be0.png">

**Comment by eldadfux** [comment]
I'll take this issue.

**Comment by eldadfux** [comment]
Fixed, deploying a new version now.

![image](https://user-images.githubusercontent.com/1297371/100853406-65a24380-3490-11eb-9954-0253a0422f97.png)

**Comment by eldadfux** [comment]
Forgot to mention this is already live for a few hours :)
