### ISSUE TITLE
🐛 Bug Report: Error in initializing auth2 login using Web SDK

### ISSUE THREAD

**Issue by vishantbatta** [appwrite/appwrite#7456]
### 👟 Reproduction steps

Initializing auth2 login using Web SDK using this: https://appwrite.io/docs/products/auth/oauth2#init

### 👍 Expected behavior

It should take the user to the Google account selection screen

### 👎 Actual Behavior

Getting:  "Cannot set property href of [object WorkerLocation] which has only a getter." error

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@vishantbatta, thanks for creating this issue! 🙏🏼 Your error message mentions [`WorkerLocation`](https://developer.mozilla.org/en-US/docs/Web/API/WorkerLocation) which seems to indicate this is being executed in a [Worker](https://developer.mozilla.org/en-US/docs/Web/API/Worker) which doesn't support setting the `location`. Would you please provide more detail/context around your code?

**Comment by vishantbatta** [comment]
Hey, thanks for looking this up, yes I figured, this was happening due to the constraints on the worker. It was happening due to the following condition: https://github.com/appwrite/appwrite/blob/bd920ead40b50b8be1cec32fcc8299ec2e5454a3/public/sdk-web/services/account.ts#L673

However, now I am trying to construct the auth URL using the same function rather than using the SDK: https://github.com/appwrite/appwrite/blob/bd920ead40b50b8be1cec32fcc8299ec2e5454a3/public/sdk-web/services/account.ts#L646C9-L646C33
