### ISSUE TITLE
UI Bug in API key (select all)

### ISSUE THREAD

**Issue by Glide7** [appwrite/appwrite#746]
## 🐛 Bug Report

Selection is going a bit crazy after toggling the "Select All" button a few times in v0.7 (dev branch)

## Have you spent some time to check if this issue has been raised before?

No similar issue reported

## To Reproduce

Click the UI in the console that displays "Select all" 

## Expected behavior

UI will highlight all options.

(Write what you thought would happen.)

UI is going a bit crazy after toggling the "Select All" button a few times

(Write what happened. Add screenshots, if applicable.)

v0.7 (dev branch)

All

**Comment by eldadfux** [comment]
Fixed and released on v0.7
