### ISSUE TITLE
unable to add platform to appwrite cloud

### ISSUE THREAD

**Issue by elevateup** [appwrite/appwrite#7488]
Recently I deleted all projects from my account. And now I have only two projects. and I am unable to add any platform to my project.
Everytime I got is  "The maximum number of platforms allowed for the selected plan has reached. Upgrade to increase the limit.".
even when I have 0 platforms added. 

please give it a check  :)

**Comment by elevateup** [comment]
Oh I forgot to mention the project id.
Here it is: elevate-up

**Comment by gewenyu99** [comment]
Hey, @elevateup this limit is per organization, not project. Do you have other projects in your org?

**Comment by elevateup** [comment]
@gewenyu99 No,
I just have 2 projects. One of them is just empty and i can add platforms to that project.But i can't add platforms to this ( elevate-up ) project.
I think it is a cache issue ?

**Comment by elevateup** [comment]
Any Updates on this ???

**Comment by elevateup** [comment]
@stnguyen90  Thanks for responding,
I just deleted my org. And recreated one. 
Then again created the projects with same id. Still same issue :(

**Comment by stnguyen90** [comment]
@elevateup, sorry for the delay. I've cleaned up some orphaned data. Are you able to create the platform now?
