### ISSUE TITLE
🚀 Feature: Appwrite CLI should have a command for checking if you're logged in

### ISSUE THREAD

**Issue by Exponential-Workload** [appwrite/appwrite#7492]
### 🔖 Feature description

A simple subcommand for checking if the user is logged into an Appwrite instance within the CLI.

E.g.
```
$ appwrite is-logged-in
You're not logged in.
$ echo $?
1
$ appwrite login
...
$ appwrite is-logged-in
You're logged into http://localhost/v1 as example@example.com!
$ echo $?
0
```

Ideally, the command should have a non-zero exit code if the user isn't logged in, for programmatic checks.

### 🎤 Pitch

I'm working on an [Appwrite Utility Metaframework](https://codeberg.org/Expo/Written)-thingy (not sure how to describe it), and need my templating tool to be able to figure out if the user is already logged in or not. I could just read `~/.appwrite/perfs.json`, however that could break between Appwrite CLI updates, and isn't a cross-platform solution.
This should be a relatively easy feature to implement, as it just requires checking if the user is authenticated, and if so, outputting that they are.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Exponential-Workload** [comment]
`appwrite account get` does appear to do this (thanks @PineappleIOnic for informing me), however it requires you to already have a project for some reason:
![image](https://github.com/appwrite/appwrite/assets/90570076/dea99568-65e6-47ea-b64d-5a0c35e36fde)

As I'm making a templating tool, I need to check if the user is logged in before I run `appwrite init project`, meaning I need this to work without a project existing at the time of checking if an account exists.

**Comment by stnguyen90** [comment]
@Exponential-Workload, `appwrite projects list` would be a good one to check if you're logged in.

**Comment by Exponential-Workload** [comment]
> @Exponential-Workload, `appwrite projects list` would be a good one to check if you're logged in.

This appears to work just fine for me - thanks!
