### ISSUE TITLE
🐛 Bug Report: compression of the database

### ISSUE THREAD

**Issue by AidenY69** [appwrite/appwrite#7493]
### 👟 Reproduction steps

Create an AppWrite instance (self-hosted), fill it with content so the database grows, ensure it's very large to see the effects, a few million row equivalent.

### 👍 Expected behavior

The database should be compressed (with an industry standard like ZStandard) so the database storage is being optimized

### 👎 Actual Behavior

What I'm noticing is that the size of the database does not look like it's actively being compressed. I know the underlying system is MariaDB, which does offer compression: https://mariadb.com/kb/en/innodb-page-compression/ and https://mariadb.com/kb/en/optimization-and-tuning-compression/

Can someone confirm if AppWrite has compression in its use of MariaDB, or is there something/a way I can enable compression for my AppWrite? It feels like the database is uncompressed as comparable database size in MongoDB takes significantly less space with ZTSD enabled. I don't think the difference of MariaDb vs MongoDB would make that big of a difference, and the overhead of everything else in AppWrite also wouldn't affect it (I don't have user uploads or anything like that. It's pure database items)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
If this is possible with MariaDB, you can configure it to your liking, there is really nothing we can do on the Appwrite side for this as we use MariaDB / MySQL as a drop in solution. As this doesn't seem like a very common request I would also not suggest spending time in changing the default Appwrite setup. 

This can always be reconsidered if we see more support from the community for such default configuration.
