### ISSUE TITLE
🐛 Bug Report: CORS error

### ISSUE THREAD

**Issue by Januariesjm** [appwrite/appwrite#7508]
### 👟 Reproduction steps

When I try to sign up this is the error I get..  sign-up:1 Access to XMLHttpRequest at 'https://cloud.appwrite.io/v1/account/sessions/email' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### 👍 Expected behavior

The  user should be signed in without any error

### 👎 Actual Behavior

The user was not signed in 

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 🧱 Your Environment

13.0.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by step135** [comment]
It is not a bug, but missing feature as localhost should be supported automatically as in other databases. For each URL  you need to create a new 'Platform' and set hostname to corresponding URL.

**Comment by docimin** [comment]
> It is not a bug, but missing feature as localhost should be supported automatically as in other databases. For each URL you need to create a new 'Platform' and set hostname to corresponding URL.

Hey.

I don't really see the point of adding localhost as default. It's not needed everywhere like for me.
Just add localhost as a platform and it should be fine.

**Comment by stnguyen90** [comment]
@Januariesjm, thanks for creating this issue! 🙏🏼 I would suggest checking out [this video](https://www.youtube.com/watch?v=oEpRh9H5l5g) for some tips about what the problem might be. Let us know if you still have the problem after looking at the video. 

Also, it might be better to troubleshoot this on [Discord](https://appwrite.io/discord) so we can talk synchronously and try things quicker.

**Comment by Januariesjm** [comment]
thank you I resolved my issue
