### ISSUE TITLE
🐛 Bug Report: insert/update fails when string is longer

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7522]
### 👟 Reproduction steps

Define a string field with its length of 10 in DB and try to insert/update that field with string of length>10.

### 👍 Expected behavior

It should cut off the end and the database should be updated.

### 👎 Actual Behavior

The error prevents any updates and all data are lost.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
This sounds like the expected behavior. The attribute definitions in Appwrite are also used for API validation and the expected outcome here, might not be the expected outcome in use cases where data integrity is much more important. I would suggest to truncate the value in your application code.
