### ISSUE TITLE
🚀 Feature: Login with passkey

### ISSUE THREAD

**Issue by unknoxn** [appwrite/appwrite#7528]
### 🔖 Feature description

Passkeys allow users to log in to their accounts using passkeys, offering a passwordless authentication method.

Passkeys provide users with a convenient and secure way to access their accounts without the need for traditional passwords. For more detailed information on passkeys, please refer to the following videos:

[Info Video 1](https://youtu.be/2xdV-xut7EQ)
[Infotext](https://developers.google.com/identity/passkeys)

### 🎤 Pitch

To provide the user to use a login via passkey

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Niklas2290** [comment]
+1

**Comment by nove1398** [comment]
This would be a nice addition

**Comment by CannonPhelps** [comment]
+1

**Comment by eldadfux** [comment]
Version 1.5 is expected to introduce custom auth token which will allow this use case as well. Here is an example:

https://github.com/appwrite/appwrite/assets/1297371/9ce283c7-03a0-493b-8f93-b5d891d05741

**Comment by nove1398** [comment]
@eldadfux I am so looking forward to this update. Ever since my friend recommended, I try this product.

**Comment by EVDOG4LIFE** [comment]
With the release of `1.5.x` this feature is now available. For a detailed blog outlying out to implement, check out @Meldiron's post here: https://dev.to/meldiron/biometric-authentication-with-passkeys-3e1
