### ISSUE TITLE
Support ANAME verification for LetsEncrypt Certificates

### ISSUE THREAD

**Issue by abovethewater** [appwrite/appwrite#755]
## 🚀 Feature

Support ANAME verification for HTTPS certificate generation

## Have you spent some time to check if this issue has been raised before?

Issue created after discord discussion.
Only CNAME is allowed, but ANAME shouldn't be a major issue to add.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

A CNAME must point to an existing name, never an IP.
In the instance that a subdomain is created purely for AppWrite (e.g. api.mydomain.com), then a CNAME will not exist.
An ANAME can point to an IP address.

My personal workflow when installing AppWrite for the first time was to:

* Read the documentation.
* Create a DO Docker droplet (1CPU / 2GB)
* Install AppWrite following the installation instructions

* When prompted for the hostname (default localhost), I relaised I would need to choose a relevant name.
* I then created a DNS entry for api.mydomain.com as an ANAME referencing the DO droplet created earlier.
* Returned to installer and added that as the host.
* Continued through setup until complete.

Upon completion of installation, I was able to access api.mydomain.com via a web browser, and AppWrite was fully working (fantastic result! No idea how often the first time install fails on many projects!)

The page however was not available via HTTPS via the browser as it uses a self-signed cert.

Following documentation for custom domains, I then created an extra CNAME for app.mydomain.com, which pointed to api.mydomain.com. Adding and verifying this in the console resulted in HTTPS being available for app.mydomain.com.

My suggestion would be to:

* Document the hostname requirement in the installation documentation (what is it, what relevance does it have?)
* Support ANAME DNS verification for Certificate Generation
* Provide an option to auto verify on first start (or add the option to verify current domain in custom domains), allowing for out of the box HTTPS.

Notes:
* Completely new to this, so there may be some confusion in terminology 🙂
* I presumed the hostname was tied to the DNS name, but this may well not be the case

Thanks, and keep up the good work.

**Comment by rhengles** [comment]
@brandonroberts Yes, exactly what Pastajello said. Does appwrite support requesting wildcard certificates from Letsencrypt ?

**Comment by Pastajello** [comment]
@rhengles I'm not sure about wildcards, but its possible to get a subdomain working:
![image](https://user-images.githubusercontent.com/28345098/219055260-c68a8e05-9a4a-4f0e-991e-0809b935c051.png)

And then on vps a command where you put image:
docker compose exec appwrite ssl domain="www.appwrite.mydomain.com"
