### ISSUE TITLE
🐛 Bug Report: Account SDK Client Request in Render

### ISSUE THREAD

**Issue by dwissaaj** [appwrite/appwrite#7562]
### 👟 Reproduction steps

In client component with Next event it's an async function and onClick event Appwrite always post request  `create account` immediatly when render make appwrite trigger rate limit. This code almost identical to  [appwrite docs] refer this (https://appwrite.io/docs/quick-starts/nextjs) which kinda confusing. 

### 👍 Expected behavior

Only make post request after click button
![app1](https://github.com/appwrite/appwrite/assets/71976179/3863cafe-dd21-4d04-8d99-204f1d1b21ba)

### 👎 Actual Behavior

Make request after rendering

![app2](https://github.com/appwrite/appwrite/assets/71976179/e8e204ab-4fce-49b2-a1f4-b6b7a3fe07bb)
3831a0ed3c8)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

All config in here [appwrite docs ](https://appwrite.io/docs/quick-starts/nextjs)
I also push it in a git branch please refer to [my github](https://github.com/dwissaaj/kisetsu-tech/tree/appwrite-bug-account)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by LukeHagar** [comment]
Hey @dwissaaj,

This is a common implementation issue

OnClick={register}

Should be changed to

OnClick={()=>register()}

**Comment by dwissaaj** [comment]
Actually after debugging it's not a bug in onclick but handlechange in next ui. Thanks
