### ISSUE TITLE
🐛 Bug Report: AppwriteException [Error]: Server Error when accessing database from appwrite function by schedule

### ISSUE THREAD

**Issue by nikita-mityagin** [appwrite/appwrite#7586]
### 👟 Reproduction steps

I created database and straightforward appwrite function to request and store currency rates by schedule.
Project ID is 65b965f86aa7fccae805
Database ID is 65b966227699819e10f9
Collection ID is 65b9662e703d34c46726
Function ID is 65b967c865aa2e7b9e6c

Linked github repository: https://github.com/nikita-mityagin/fiat-rates-cron

### 👍 Expected behavior

I expect to be able to read/write to database inside the function.
Currently exactly I expect to be able to list all documents at line [24](https://github.com/nikita-mityagin/fiat-rates-cron/blob/master/src/main.js#L24) 

### 👎 Actual Behavior

I tried several requests to database (read/write) and they all always fail with 500 Server error without additional details.
For reference you can check execution ID 65ccc81547062887597f

```
Failed getting all docs:  AppwriteException [Error]: Server Error
    at Client.call (/usr/local/server/src/function/node_modules/node-appwrite/lib/client.js:174:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.listDocuments (/usr/local/server/src/function/node_modules/node-appwrite/lib/services/databases.js:1638:16)
    at async Module.fetchAndSaveRates (file:///usr/local/server/src/function/src/main.js:24:39)
    at async execute (/usr/local/server/src/server.js:141:22)
    at async /usr/local/server/src/server.js:158:13 {
  code: 500,
  type: 'general_unknown',
  response: {
    message: 'Server Error',
    code: 500,
    type: 'general_unknown',
    version: '0.12.83'
  }
}
``` 

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

"node-appwrite": "11.1.0"

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@nikita-mityagin, thanks for creating this issue! 🙏🏼 I tried looking for your failed request, but I couldn't find it. 

I see you're setting your project ID like [`client.setProject(process.env.PROJECT_ID)`](https://github.com/nikita-mityagin/fiat-rates-cron/blob/fbe79bfe0b492489145c680fbfb54b00309d20f2/src/main.js#L9C27-L9C49). Would you please double check that's correct?

**Comment by nikita-mityagin** [comment]
@stnguyen90 Steven, thanks for your prompt response!
For some reason I had an expectation that the PROJECT_ID is being provided by appwrite in the runtime (I thought I saw this somewhere in the docs). Sorry for my inattentiveness.
Added PROJECT_ID to the list of function env variables and the error has gone. Thank you!

**Comment by stnguyen90** [comment]
> For some reason I had an expectation that the PROJECT_ID is being provided by appwrite in the runtime

@nikita-mityagin, the out-of-the-box env variable would be `APPWRITE_FUNCTION_PROJECT_ID`. For more info, see https://appwrite.io/docs/products/functions/development#environment-variables.

Glad you got is working, though!

**Comment by nikita-mityagin** [comment]
@stnguyen90 Oh, thank you!
