### ISSUE TITLE
🐛 Bug Report: Query select returns not explicitly requested fields

### ISSUE THREAD

**Issue by ohbob** [appwrite/appwrite#7587]
### 👟 Reproduction steps

```
await databases.listDocuments("dashboard", "jobs", Query.select(["status"]))
```

### 👍 Expected behavior

```
{
    total: 7,
    documents: [
        { status: "active" },
        { status: "active" },
        { status: "active" },
        { status: "active" },
        { status: "active" },
        { status: null },
        { status: "active" }
    ]
}
```

### 👎 Actual Behavior

```
{
  total: 7,
  documents: [
    {
      status: "active",
      $databaseId: "dashboard",
      $collectionId: "jobs"
    }, {
      status: "active",
      $databaseId: "dashboard",
      $collectionId: "jobs"
    }, {
      status: "active",
      $databaseId: "dashboard",
      $collectionId: "jobs"
    }, {
      status: "active",
      $databaseId: "dashboard",
      $collectionId: "jobs"
    }, {
      status: "active",
      $databaseId: "dashboard",
      $collectionId: "jobs"
    }, {
      status: null,
      $databaseId: "dashboard",
      $collectionId: "jobs"
    }, {
      status: "active",
      $databaseId: "dashboard",
      $collectionId: "jobs"
    }
  ]
}
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite: 1.4.13,
node-appwrite: 9.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ohbob, thanks for creating this issue! 🙏🏼 Looks like we're forcing `$databaseId` and `$collectionId` to be added:

https://github.com/appwrite/appwrite/blob/cbf1085850354c6d16296e764e9c64abea067be0/app/controllers/api/databases.php#L2955-L2956

This is kind of related to https://github.com/appwrite/appwrite/issues/6944

**Comment by Meldiron** [comment]
Following up on communication from Discord, Jake decided this is a good first issue as it should only require changes in Appwrite APIs. It might be a little complex, so please feel free to let us know if you need any further assistance. ✨

**Comment by stnguyen90** [comment]
As part of this, we also need to make sure if you select $collectionId or $databaseId, it's returned as expected.
