### ISSUE TITLE
🐛 Bug Report: Duplicate Executions of Cloud Functions

### ISSUE THREAD

**Issue by elevateup** [appwrite/appwrite#7590]
### 👟 Reproduction steps

I deployed a Dart starter function. And when I open the domain in my Browser it shows 2 executions. 1 is of the actual execution of the function and 1 is of a GET request to /favicon.ico ( mostly all browser looks for a icon )

### 👍 Expected behavior

It should ignore the duplicate executions caused by the default browser request for icon.

### 👎 Actual Behavior

![duplicate executions of function](https://github.com/appwrite/appwrite/assets/96453180/ec5a5cdf-f1d7-4965-a827-2fbb57d1e660)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ohbob** [comment]
yes noticed that on self hosted as well

**Comment by stnguyen90** [comment]
@elevateup, thanks for raising this issue! 🙏🏼 This is the expected behavior because the browser is making an additional request to your function domain.
