### ISSUE TITLE
🐛 Bug Report: Display Name settings aren't saving

### ISSUE THREAD

**Issue by danverbs** [appwrite/appwrite#7593]
### 👟 Reproduction steps

Go to Settings of a database collection and remove the ID field in the Display Settings and hit Save

### 👍 Expected behavior

The removed field shouldn't be seen in linked tables

### 👎 Actual Behavior

The removed field reappears each time I visit the settings page

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@danverbs, thanks for raising this issue! 🙏🏼 So, I tried to reproduce your problem, but it seems to work fine for me.

I have an attribute with 3 display names:

![image](https://github.com/appwrite/appwrite/assets/1477010/11f49e4b-bd0c-431b-922c-01cdb03a90d3)

Here, you can see the relationship with the 3 display names;

![image](https://github.com/appwrite/appwrite/assets/1477010/a37d5f44-8d70-4592-8050-0f28e9f945da)

If I update the display names:

![image](https://github.com/appwrite/appwrite/assets/1477010/b9bb1ece-be30-4135-850f-f14a7ec85438)

and go back to the collection:

![image](https://github.com/appwrite/appwrite/assets/1477010/c4dde394-d341-49b6-9b15-90b339d1a489)

I see the 2 display names as expected.

Also, if I remove the ID display name, it only shows the 1 left:

![image](https://github.com/appwrite/appwrite/assets/1477010/a557cd91-695b-423a-95c1-2dc98112c991)

Could you provide some more context or reproduction steps?

**Comment by danverbs** [comment]
Thanks for the reply - it's odd as it seems to be working fine now. The steps you illustrated above were the steps I was taking but when I went back to the collection I had just updated it didn't save my changes, removing the display name but now it is. I'll keep an eye on it
