### ISSUE TITLE
🐛 Bug Report: Proxy pass Apache

### ISSUE THREAD

**Issue by RedYara** [appwrite/appwrite#7596]
### 👟 Reproduction steps

I have an Appwrite application, running on 8000-8001->8000-8001/tcp, on Ubuntu server, which has many other projects that I can access with Apache. But I can't access the Appwrite console with this configuration:
```
<Location "/appwrite">
        ProxyPass http://192.168.100.101:8000
        ProxyPassReverse http://192.168.100.101:8000
</Location>
```
I didn't change docker-compose.yml and .env files, it's similar to public [docker-compose.yml](https://appwrite.io/install/compose) and [.env](https://appwrite.io/install/env)

### 👍 Expected behavior

Access to the console with no problems.

### 👎 Actual Behavior

When I make a request to API, it works perfect
![image](https://github.com/appwrite/appwrite/assets/81422682/55275267-4369-42c1-8518-80e0dce72183)
But when I try to access console, I face the problem:
![image](https://github.com/appwrite/appwrite/assets/81422682/9be82097-3682-4060-a8c8-d4ad3a7719f1)
And white screen. HTML code loads as it should, but I can't access the assets.
I can't access http://192.168.100.101/fonts/inter/inter-v8-latin-600.woff2, but I can access http://192.168.100.101/appwrite/fonts/inter/inter-v8-latin-600.woff2
Maybe something is missing in my configuration?

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite/appwrite:1.4.13
Apache/2.4.52
Docker version 24.0.6
Docker Compose version v2.20.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by RedYara** [comment]
UPD:
In docker-compose.yml I've set 8000 and 8001 ports for Traefik
Traefik:
```
      - --entrypoints.appwrite_web.address=:8000
      - --entrypoints.appwrite_websecure.address=:8001
    restart: unless-stopped
    ports:
      - 8000:8000
      - 8001:8001
```

**Comment by stnguyen90** [comment]
@RedYara, thanks for creating this issue! 🙏🏼 

First, you cannot run Appwrite on a different path. If you're interested in that, you can add a 👍🏼 to [this](https://github.com/appwrite/appwrite/issues/5430) issue.

Typically, people run multiple apps on a server by separating them with (sub)domains. I would suggest doing that.

As for how to configure apache (or any other reverse proxy), the important thing is to make sure to pass the host header. Perhaps [this](https://github.com/appwrite/appwrite/discussions/4056) discussion will give you some insight.
