### ISSUE TITLE
🐛 Bug Report: account.createRecovery returns 500 general_unknown if the user doesn't have a name

### ISSUE THREAD

**Issue by erlenddahl** [appwrite/appwrite#7597]
### 👟 Reproduction steps

Create a new user with account.create(ID.unique(), email, password).
We now have a user that can log in, and everything works.

Now try to run account.createRecovery(email, url) on this user.

### 👍 Expected behavior

The user gets an e-mail to reset the password, but without a name if it doesn't have one, I guess.

### 👎 Actual Behavior

Since the user has no name set, the server returns 500 general_unknown (when manually setting a name on the user in the Appwrite settings, it works).

docker compose logs appwrite shows:
Argument #1 ($name) must be of type string, null given, called in /usr/src/code/app/controllers/api/account.php

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Server: Appwrite version 1.4.13
Client: SvelteKit, with appwrite@13.0.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@erlenddahl, thanks for creating this issue and providing some logs! 🙏🏼 This is probably where it's failing:

https://github.com/appwrite/appwrite/blob/c3ddc6a05dae5ce8c64025f1c31130b1cd126644/app/controllers/api/account.php#L2529

**Comment by navjotNSK** [comment]
Hi @stnguyen90 @erlenddahl @EVDOG4LIFE Please review my pull request as I have fixed the bug. I am new to open source and php so if any changes required do let me know.
PR - https://github.com/appwrite/appwrite/pull/7651/files
