### ISSUE TITLE
500 error returned if string data provided when creating new Document in Collection

### ISSUE THREAD

**Issue by abovethewater** [appwrite/appwrite#760]
## 🐛 Bug Report

Performing a post to /v1/database/collections/{collectionid}/documents returns a 500 error if a string is used instead of an object

`--data-raw '{"data":"test","read":["*"],"write":["*"],"parentPropertyType":"assign"}'`

Switching appwrite to development mode changes this error to a 200, but the CORS headers are not set, and the following error is seen:

`< HTTP/2 200
< content-encoding: gzip
< content-type: text/html; charset=UTF-8
< date: Wed, 09 Dec 2020 16:15:17 GMT
< server: nginx
< vary: Accept-Encoding
< content-length: 521
<
<br />
<b>Warning</b>:  Illegal string offset '$collection' in <b>/usr/share/nginx/html/app/controllers/api/database.php</b> on line <b>378</b><br />
<br />
<b>Warning</b>:  Illegal string offset '$permissions' in <b>/usr/share/nginx/html/app/controllers/api/database.php</b> on line <b>379</b><br />
<br />
<b>Notice</b>:  Array to string conversion in <b>/usr/share/nginx/html/app/controllers/api/database.php</b> on line <b>379</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/usr/share/nginx/html/app/controllers/api/database.php</b> on line <b>423</b><br />
<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Appwrite\Database\Database::createDocument() must be of the type array, string given, called in /usr/share/nginx/html/app/controllers/api/database.php on line 433 and defined in /usr/share/nginx/html/src/Appwrite/Database/Database.php:185
Stack trace:
#0 /usr/share/nginx/html/app/controllers/api/database.php(433): Appwrite\Database\Database-&gt;createDocument()
#1 [internal function]: {closure}()
#2 /usr/share/nginx/html/vendor/utopia-php/framework/src/App.php(401): call_user_func_array()
#3 /usr/share/nginx/html/app/app.php(430): Utopia\App-&gt;run()
#4 /usr/share/nginx/html/public/index.php(27): include('/usr/share/ngin...')
#5 {main}
  thrown in <b>/usr/share/nginx/html/src/Appwrite/Database/Database.php</b> on line <b>185</b><br />`

## Have you spent some time to check if this issue has been raised before?

Yes. Feedback on discord is that this may have already been fixed in dev, but to raise it to check

## To Reproduce

(Write your steps here:)

Using js sdk

`let sdk = new Appwrite();

sdk
    .setEndpoint('https://[HOSTNAME_OR_IP]/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2') // Your project ID
;

let promise = sdk.database.createDocument('[COLLECTION_ID]', 'test', ['*'], ['*']);

promise.then(function (response) {
    console.log(response); // Success
}, function (error) {
    console.log(error); // Failure
});`

## Expected behavior

I would expect a 400 bad request
I would also expect production and development to behave the same 

## Actual Behavior

500 internal error received in production

200 OK in development, but then error in stack trace and no CORS headers set

## Your Environment

Digital Ocean Docker 1-click 2GB 1CPU 

` 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

`x-sdk-version | appwrite:javascript:1.1.0`

Appwrite v:0.6.2.125

**Comment by eldadfux** [comment]
I can confirm this is throwing the correct 400 error on the 0.7.x branch 👍

**Comment by eldadfux** [comment]
Version 0.7 is out with the fix 🚀
