### ISSUE TITLE
🚀 Feature: Introduce Custom JWT Expiration Date Support

### ISSUE THREAD

**Issue by Edijae** [appwrite/appwrite#7602]
### 🔖 Feature description

I have my own API server that communicates with the Appwrite Node.js server. When a user logs in, I use the `createEmailSession` method provided by Appwrite to authenticate the user and then generate a JWT token using the `createJWTToken` method. This JWT token is included in the response sent back to the user. Subsequently, when the user makes another API call, I authenticate them on their behalf in the backend and grant access to the resources they request. 

However, a challenge arises because the JWT token expires quickly, forcing users to frequently log in. Is there a way to extend the expiration time of the JWT token to improve the user experience?

### 🎤 Pitch

It would help increase jwt session period without user having to keep login in.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Swinkid** [comment]
Assuming you're using one of the login methods (In your case createEmailSession), Can you not store the session/token/jwt in browser and get the session ID and use:
https://appwrite.io/docs/references/cloud/client-web/account#updateSession

Also see https://appwrite.io/docs/references/cloud/models/session

Not tried this personally so apologies if you've tried already.

**Comment by stnguyen90** [comment]
If you're looking for configurable JWT durations, please add a 👍🏼 to https://github.com/appwrite/appwrite/issues/5263.

Btw, we're working on some changes that allow better session handling in custom backends. Stay tuned for that. 

For now, I'm going to close this as a duplicate.
