### ISSUE TITLE
🐛 Bug Report: Phone Auth Verification

### ISSUE THREAD

**Issue by RivaanRanawat** [appwrite/appwrite#7623]
### 👟 Reproduction steps

I am using Appwrite Cloud. I implemented the phone authentication steps as mentioned in the docs, it worked fine in the beginning. I was receiving the OTP correctly and the entire authentication process was smooth. Next day, I stopped receiving the secret (OTP). No changes made to the console or the code.

### 👍 Expected behavior

I should be receiving the OTP (secret). There's no error.

### 👎 Actual Behavior

I didn't receive OTP. I thought it might be in the spam but it isn't. In fact, when I print the following:
```dart
try {
      final userId = ID.unique();
      final session = await account.createPhoneSession(
        userId: userId,
        phone: phoneNumber,
      );
      print(session.userId);
      print(session.$createdAt);
      print(session.$id);
      print(session.secret);
      return right(session.userId);
    } on AppwriteException catch (e) {
      return left(Failure(e.message ?? ''));
    } catch (e) {
      return left(Failure(e.toString()));
    }
```

It is able to print the userId, createdAt, id successfully however secret prints out an empty string.

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
There was a problem with our service provider, but it's been resolved now.

**Comment by anomihe** [comment]
@stnguyen90  am still having similar issue where by i can not receive otp
