### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by AbdallaElgali** [appwrite/appwrite#7634]
### 👟 Reproduction steps

UPDATE: It's resolved, but I would still like to know how to be able to handle such errors in the future in case the project goes into production. Thank you.

When I try to sign in to my account to view my project, I get the error code 500, internal error. Now I am getting a Gateway Timeout error. 

### 👍 Expected behavior

It should sign me in and let me view my project. 

### 👎 Actual Behavior

It actually keeps giving me gateway timeout errors.  Also I would get "Bad Gateway" errors when trying to access appwrite cloud using the API from code.
![image](https://github.com/appwrite/appwrite/assets/103468713/838b4ffd-a44c-41c7-ba17-2eccd1b60271)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by hdhaliwa** [comment]
![Screenshot 2024-02-22 082937](https://github.com/appwrite/appwrite/assets/27665205/e510a71c-efa5-45f8-941f-47b43ec5b78e)


@AbdallaElgali i did not get Gateway Timeout, for me the page opened. Please see screenshot. Are you using appwrite beta ?

**Comment by stnguyen90** [comment]
@AbdallaElgali, there was a maintenance window announced that mentioned possible downtime: https://status.appwrite.online/maintenance/330333
