### ISSUE TITLE
Missing setEndpoint() in Deno SDK examples

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#764]
## 🐛 Bug Report
The Deno SDK example codes in the docs are missing the `setEndpoint()` method 

## Have you spent some time to check if this issue has been raised before?
No this hasn't been raised before 

## To Reproduce
Check the code examples for deno
https://appwrite.io/docs/server/storage?sdk=deno

## Expected behavior
The examples should have a `client.setEndpoint()` method

## Actual Behavior
The examples are missing the `client.setEndpoint()` method
 
![Screenshot 2020-12-13 at 8 50 28 PM](https://user-images.githubusercontent.com/20852629/102016036-d72d9c00-3d84-11eb-82f1-347c8cbb4986.png)

## Your Environment
N/A

**Comment by eldadfux** [comment]
Fixed on master, will release a new Deno version on 0.7 release

**Comment by eldadfux** [comment]
Version 0.7 is out with the fix 🚀
