### ISSUE TITLE
🚀 Feature: Updating documents over realtime connection

### ISSUE THREAD

**Issue by Sirius3615** [appwrite/appwrite#7675]
### 🔖 Feature description

Support for updating documents over the established realtime (websocket) connection.

### 🎤 Pitch

My use case would be in IOT devices such as smart switches or sensors, for instant document updates without the need for separate patch http requests. Same applies for apps of similar use case. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Sirius3615, thanks for creating this issue! 🙏🏼 It would be best to add a 👍🏼 to https://github.com/appwrite/appwrite/issues/6321.
