### ISSUE TITLE
🐛 Wrong error message when changing bucket settings

### ISSUE THREAD

**Issue by str0tta-salesmart** [appwrite/appwrite#7682]
### 👟 Reproduction steps

1. Create an account and a project if you already didn't.
2. Create a bucket.
3. Go to its settings page.
4. Change ANY setting to a different value.

### 👍 Expected behavior

The bucket settings change.

### 👎 Actual Behavior

An error message pops out saying "The file you are trying to upload is above the limit allowed for your plan. Upgrade to higher plan to increase the limit."

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite version: 0.12.102

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### Additional Info

Error message:
![image](https://github.com/appwrite/appwrite/assets/151525241/a9256413-2eec-4052-a024-39b5c8b4ada5)

Sniffed HTTP request:
```bash
curl 'https://cloud.appwrite.io/v1/storage/buckets/65de2e1b397683ff4f4a' \
  -X 'PUT' \
  -H 'authority: cloud.appwrite.io' \
  -H 'accept: */*' \
  -H 'accept-language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'content-type: application/json' \
  -H 'cookie: a_session_console_legacy=eyJpZCI6IjY1ZGUyYmUwNjZmODYwMTAzZjc1Iiwic2VjcmV0IjoiYzk4ZjFlNGQzMTQzZGQ2ZTRlODM4ZGQzZjkyNmJkMDgzNjA4ZGE4MjcxN2JiZGI5YmU0YWNhNmMwYmZkNzUzZTg1ODIzZWQzZTJjYTQ1NjVkOGJmZjk2MDU5YzM1NTk5NTExZmY5MDA0YWVkZWIxZmI4NDMwYjliNGYzZmNiZjM4YzRmYWFiNWVmNDkyOTA2ZDY2NDhiMWJjMzg4OGY5YzExZTI2NThiYzc0ZTUwNjhiMWI5YWZkZGQwOGVkNTdhYzBiOGRhYjQzOTY4Y2QxOWYyYWNkNjY2NzdlNjRlNmQzZjBhZWQ1YjFkNWFmYjQ4Mjk4Mzc5MzBkZGQ0OGRmMyJ9; a_session_console=eyJpZCI6IjY1ZGUyYmUwNjZmODYwMTAzZjc1Iiwic2VjcmV0IjoiYzk4ZjFlNGQzMTQzZGQ2ZTRlODM4ZGQzZjkyNmJkMDgzNjA4ZGE4MjcxN2JiZGI5YmU0YWNhNmMwYmZkNzUzZTg1ODIzZWQzZTJjYTQ1NjVkOGJmZjk2MDU5YzM1NTk5NTExZmY5MDA0YWVkZWIxZmI4NDMwYjliNGYzZmNiZjM4YzRmYWFiNWVmNDkyOTA2ZDY2NDhiMWJjMzg4OGY5YzExZTI2NThiYzc0ZTUwNjhiMWI5YWZkZGQwOGVkNTdhYzBiOGRhYjQzOTY4Y2QxOWYyYWNkNjY2NzdlNjRlNmQzZjBhZWQ1YjFkNWFmYjQ4Mjk4Mzc5MzBkZGQ0OGRmMyJ9; __stripe_mid=c6ec7542-21dc-4f11-83cf-b191cbbb5336ce6972; __stripe_sid=813e98c4-4e2d-4d52-b28e-c89578ad3aa5f1027a' \
  -H 'origin: https://cloud.appwrite.io' \
  -H 'referer: https://cloud.appwrite.io/console/project-65de2c0780e0192f5b7d/storage/bucket-65de2e1b397683ff4f4a/settings' \
  -H 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
  -H 'x-appwrite-mode: admin' \
  -H 'x-appwrite-project: 65de2c0780e0192f5b7d' \
  -H 'x-appwrite-response-format: 1.4.0' \
  -H 'x-fallback-cookies;' \
  -H 'x-sdk-language: web' \
  -H 'x-sdk-name: Console' \
  -H 'x-sdk-platform: console' \
  -H 'x-sdk-version: 0.5.0' \
  --data-raw '{"name":"patatae","permissions":[],"fileSecurity":false,"enabled":false,"maximumFileSize":5000000000,"allowedFileExtensions":[],"compression":"none","encryption":true,"antivirus":true}' \
  --compressed
```

Response:
![image](https://github.com/appwrite/appwrite/assets/151525241/0f43992a-e3d9-40fb-875c-a130b1192e10)

**Comment by daveprayag** [comment]
Facing precisely the same issue.

**Comment by EVDOG4LIFE** [comment]
Hi all,

We're aware of this and are actively pursuing a way to improve this experience for folks on the free tier of Cloud. 

The current workaround is to change the `Maximum file size` from 5 GB down to a value lower than 50 MB and updating. That will unblock you while we work on the improvements here. 

CC: @daveprayag , @str0tta-salesmart

**Comment by priyankuhazarika** [comment]
This issue is still not fixed

https://github.com/appwrite/appwrite/assets/35552170/0cd123f9-2bce-4559-87fb-be4173887b77

**Comment by daveprayag** [comment]
> This issue is still not fixed
> 
>  Screen.Recording.2024-05-05.at.11.10.09.PM.mov

Change the "Maximum file size limit" to 49mb and it will start working.

**Comment by stnguyen90** [comment]
This should be fixed not

**Comment by stnguyen90** [comment]
Buckets are created with the correct max file size now: ![Image](https://github.com/user-attachments/assets/f9b19dc1-4457-467c-8481-fe7e4833fd89)
