### ISSUE TITLE
🚀 Feature: Other storage providers

### ISSUE THREAD

**Issue by orelvis15** [appwrite/appwrite#7690]
### 🔖 Feature description

It would be great to have other storage providers such as Google Drive, Microsoft SharePoint, Mega, Dropbox, etc., for the Appwrite storage module.

### 🎤 Pitch

Many of these providers offer free plans that we could take advantage of and on the other hand, many of the organizations where we could use appwrite are already paying for plans for those providers. In my case, I am trying to install appwrite in my company so that it can be used as a backend service for several of the apps and services that we have, but they pay for a Microsoft SharePoint plan.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
I don't think SharePoint has or supports an S3 compatible structure.

Appwrite's storage adapter currently has a tight `S3` based implementation which makes it easier to extend and manage.
See here - https://github.com/utopia-php/storage for more info.

Alternatively, you can always move around the files via Cloud Functions to your provider after they are uploaded to storage & maintain a separate collection & documents.

---
I'll keep an eye on this for future references.
