### ISSUE TITLE
🐛 Bug Report: Attempt to delete a document using JWT token is failing

### ISSUE THREAD

**Issue by Edijae** [appwrite/appwrite#7693]
### 👟 Reproduction steps

Users communicates directly with my own custom server which  in turn communicate with the appwrite server.
when user logins in, i create an email session and send back a token which is created using the createJWTToken method.

this token is the one i use to perform  actions on behave of the user. creating and updating documents work successfully but when i try to delete the document, i get an error

`AppwriteException: The current user is not authorized to perform the requested action `

I have already enabled document security in my collection and when creating or updating document, i assign the permissions below

```
import { Permission, Role } from "appwrite";

export function createPermissions(userId:string):string[]{
    let permissions = Array<string>()
    permissions.push(Permission.read(Role.any()));
    permissions.push(Permission.update(Role.user(userId)));
    permissions.push(Permission.delete(Role.user(userId)));

    return permissions
}

let document = await db.createDocument(dbId, collectionId, uniqueKey, item,createPermissions(userId));
    

```

This is how i try to delete the document
```
import {Client, Account, Databases, Storage} from 'appwrite';

let webC = new Client();
        webC.setEndpoint(serverEndpoint)
        .setProject(serverProject)
        .setJWT(token);

let db = new Databases(webC);

await db.deleteDocument(dbId, collectionId, documentId);
```

Please note the token is always active and not expired. All of this happens on the server side.

### 👍 Expected behavior

Deleting a document should work if creating and updating is working

### 👎 Actual Behavior

Deleting a document is failing

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Edijae** [comment]
@stnguyen90 Kindly assist here

**Comment by stnguyen90** [comment]
@Edijae, thanks for creating this issue! 🙏🏼. Are there relationships on your document?
