### ISSUE TITLE
🐛 Bug Report: Cannot install opencv library on python 3.9 runtime

### ISSUE THREAD

**Issue by Adityaupadhye** [appwrite/appwrite#7694]
### 👟 Reproduction steps

1. Create a starter project on appwrite functions
2. Choose python as the runtime
3. Add opencv-python in the requirements.txt

### 👍 Expected behavior

All libraries should be installed on the python runtime for appwrite funtions.
Python 3.9 is a bit unstable runtime version. Please switch to 3.10 or higher.

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/55782622/28a15334-c22b-4edc-9d3a-bf13c5ec4956)

the screenshot shows error when installing opencv

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite functions python 3.9 runtime

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Hey, @Adityaupadhye thanks for raising this issue. For max performance, we use light alpine images for majority or our runtimes. While they are great for most use cases, the Python one is not well optimized for more advanced cases.

For this we plan to introduce an AI optimized runtime for Python in next releases. Later on, we also plan to research the possibility of adding GPU enhanced runtimes to Cloud.

**Comment by mr-v-v-v** [comment]
I am tired to wait when you create normal python runtime! 3 years of waiting

**Comment by stnguyen90** [comment]
Closing as you can now install opencv using the `python-ml-3.11` runtime:

<img width="1132" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/be1cf8fe-47c6-44ec-872b-65e09260292f">
