### ISSUE TITLE
UI Bug - impossible to add more than one Rule of Type Document via Backend

### ISSUE THREAD

**Issue by RingoRohe** [appwrite/appwrite#770]
## 🐛 Bug Report

When adding Rules to a Collection via the Appwrite Backend, it is not possible to store more than one Rule with Type of Document. When setting the Collection Type for the rule ("Allowed Collection"), all other Collection Types for all other Rules get deselected. So the List property for all Rules with type Document gets null.

It is possible to edit and resend the Request manually with Browser Dev Tools. Therefore it is just an UI Bug.

## Have you spent some time to check if this issue has been raised before?

Had a short Conversation at the Discord Chat.

## To Reproduce

- create a Project in Backend
- create at least two collections (one to add rules, one to select as allowed collection in the other one)
- add more than 1 Rule with type Document
- select a collection for one Rule under "allowed Collections"
- do the same for the second Document Rule

## Expected behavior

Selection for every single Rule should stay as selected

## Actual Behavior

Selection for every other Rule with Type Document disappears

## Your Environment

Tested in Firefox 84 and Chrome 87

**Comment by TorstenDittmann** [comment]
Closing this issue in favor on #1065
