### ISSUE TITLE
🐛 Bug Report: heic images not supported

### ISSUE THREAD

**Issue by step135** [appwrite/appwrite#7712]
### 👟 Reproduction steps

Upload heic image

### 👍 Expected behavior

It should create preview

### 👎 Actual Behavior

Default image preview

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Another Issue: The file itself is recognised as `image/heif` on the console but the actual file is rendered as `text/plain` if you try to open the Image by its full URL.

**Comment by eldadfux** [comment]
@ItzNotABug for every image format we need to handle a specific handler in our image transformation library. HEIC is currently not supported, once supported the correct header will be returned.

Appwrite only allow recognized image file to be shown with the correct header as a security measurement. For example, we don't allow html files to be rendered from your storage to prevent against cookie hijacking and other attacks. This is also why functions for example use a different domain called `appwrite.global`. Once support for HEIC is introduced this should be solved.

**Comment by eldadfux** [comment]
We have a pending PR for this. All seems to work but we get some warning logs that we're still trying to solve.
