### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by anurag1802** [appwrite/appwrite#7719]
### 👟 Reproduction steps

When I open my project storage it shows 500 internal error.
<img width="960" alt="image" src="https://github.com/appwrite/appwrite/assets/65758376/84451aa3-fac1-4544-8690-b79e2762844c">

### 👍 Expected behavior

It should show my images and let me upload new one's.

### 👎 Actual Behavior

It actually crashes every time I am opening storage route.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
There seems to be an open incident here - https://status.appwrite.online/incidents.

**Comment by docimin** [comment]
Hey @anurag1802 @fakkreddine 

This issue should be resolved, could you check again? Thanks!

**Comment by stnguyen90** [comment]
@anurag1802 , thanks for raising this issue! 🙏🏼 As mentioned, there was an incident that probably affected you. If you created the project during that time, it wouldn't have created successfully, but you should be able to create a project now. We'll probably have to do a sweep of Appwrite Cloud to delete all of the broken projects.

If you still need help, feel free to create a [support](https://discord.com/channels/564160730845151244/1072905050399191082) post on our [Discord](https://appwrite.io/discord).
