### ISSUE TITLE
🐛 Bug Report: 401 error

### ISSUE THREAD

**Issue by thegrimkiller22** [appwrite/appwrite#7722]
### 👟 Reproduction steps

Failed to load resource: the server responded with a status of 401 ()

how to solve this

### 👍 Expected behavior

help

### 👎 Actual Behavior

help 

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@thegrimkiller22, thanks for creating this issue! 🙏🏼 401 usually occurs when you're making an API call that you're not authorized to do so. For example, you may be trying to do an `account.get()`, but you're not logged in. Or you're trying to do `databases.listDocuments()`, but the user doesn't have permissions to access the collection.

If you still need help, feel free to create a [support](https://discord.com/channels/564160730845151244/1072905050399191082) post on our [Discord](https://appwrite.io/discord) with details about what you're trying to do.
