### ISSUE TITLE
🐛 Bug Report: 500 Internal error

### ISSUE THREAD

**Issue by farisasif7** [appwrite/appwrite#7724]
### 👟 Reproduction steps

When I try to open auth, database or storage of a project, it gives the following error.

### 👍 Expected behavior

It should open the relevant tabs so I can work on my project.

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/108169416/daf52a19-afc5-47e1-8e62-aca8d2121f02)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by codesofpreeti** [comment]
any resolution yet?

**Comment by farisasif7** [comment]
> any resolution yet?

nopes, I haven't found any solution yet.

**Comment by stnguyen90** [comment]
@farisasif7, thanks for raising this issue! 🙏🏼 There was an [incident](https://status.appwrite.online/incident/335537) that probably affected you. If you created the project during that time, it wouldn't have created successfully. You should be able to create a project now, though.

If you still need help, feel free to create a [support](https://discord.com/channels/564160730845151244/1072905050399191082) post on our [Discord](https://appwrite.io/discord).
