### ISSUE TITLE
Linkedin Provider is not working(Flutter)

### ISSUE THREAD

**Issue by udcode** [appwrite/appwrite#773]
Getting Error 500 - provider is not supported 
When trying to log in with LinkedIn.

Basic setup(flutter):
   Client _client = new Client();
    _client.setEndpoint(...).setProject(...):
   Account _account = new Account(_client)
   ....
    var result = _account.createOAuth2Session(provider:'linkedIn');

**Comment by christyjacob4** [comment]
Hey @udcode thanks for raising this. We are working on this and will be out with a fix soon on the 0.7.x branch

Let me know if you need help setting up the development version of appwrite and I'd be happy to assist.

**Comment by eldadfux** [comment]
@christyjacob4 we should probably also check why this is raising error 500 and not 400

**Comment by christyjacob4** [comment]
Sure @eldadfux I'm testing the entire flow just to be sure

**Comment by christyjacob4** [comment]
@udcode  Your error appears to be different from the fix that we have provided. 
Consider replacing your code with this and try again. I think it's got to do with the uppercase I in `linkedIn`

```dart
var result = _account.createOAuth2Session(provider:'linkedin');
```

**Comment by udcode** [comment]
i tried with lower vase

**Comment by christyjacob4** [comment]
@udcode We have merged the fix to the 0.7.x branch. Do you need help setting it up?

**Comment by udcode** [comment]
Tnx!!
Help would be greatly appreciated 🙏

**Comment by christyjacob4** [comment]
Okay you can follow these steps

```bash
$ git clone https://github.com/appwrite/appwrite/tree/master
$ cd appwrite 
$ git checkout 0.7.x

# Assuming you're coming from a previous version of appwrite and you are just testing the new version
# We recommend deleting the volumes from 0.6.x or prior 
$ docker volume rm $(docker volume ls -q)  

$ docker-compose up -d
```

Once the containers are up and running, head over to your dashboard at localhost (default). 
Create a project and head over to the users section 

![Screenshot 2020-12-24 at 8 00 39 PM](https://user-images.githubusercontent.com/20852629/103094193-b423a780-4622-11eb-93e3-65b52bdfdc97.png)

Head over to OAuth providers and enable Linkedin
![Screenshot 2020-12-24 at 8 00 57 PM](https://user-images.githubusercontent.com/20852629/103094199-bede3c80-4622-11eb-8306-9ed672cd7e50.png)

Create a project on [Linkedin](http://linkedin.com/developers) and get the appID and appSecret from Linkedin's console. 
Enter them here 
![Screenshot 2020-12-24 at 8 02 14 PM](https://user-images.githubusercontent.com/20852629/103094257-ecc38100-4622-11eb-8270-17bae3ffbc28.png)

Copy the redirect URL and paste it in Linkedin's console over here 
![Screenshot 2020-12-24 at 8 02 58 PM](https://user-images.githubusercontent.com/20852629/103094298-0664c880-4623-11eb-80b8-2bc6dc9075e1.png)

Then head over to the Products tab in linkedin developer console and enable "Sign in with Linkedin"
![Screenshot 2020-12-24 at 8 03 10 PM](https://user-images.githubusercontent.com/20852629/103094306-0cf34000-4623-11eb-8cdc-02adab54059a.png)

Now you can consume the SDK on flutter. Let us know how it goes and we'll be here to help

**Comment by udcode** [comment]
hi do i need to use the dev sdk for flutter?
tnx

**Comment by eldadfux** [comment]
@udcode you can use this one: https://pub.dev/packages/appwrite/versions/0.3.0-dev.2

**Comment by udcode** [comment]
getting these errors

Creating appwrite-clamav ...
Creating appwrite-telegraf ...
Creating appwrite-mariadb         ... error
...
ERROR: for appwrite-mariadb  Cannot start service mariadb: Ports are not
available: listen tcp 0.0.0.0:3306: bind: Only one usage of each socket
address (protocol/network address/port) is normally permitted.

**Comment by christyjacob4** [comment]
Looks like you already have a container running. Can you share the output of `docker ps `

**Comment by udcode** [comment]
C:\Users\yudi\Documents\GitHub\kikero\appwrite>docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

**Comment by udcode** [comment]
ok, found the issue, i had a mysql server running on that port
