### ISSUE TITLE
🚀 Feature: Deno support to Appwrite Cloud

### ISSUE THREAD

**Issue by schnetzlerjoe** [appwrite/appwrite#7734]
### 🔖 Feature description

Add Deno runtime support to Appwrite cloud.

### 🎤 Pitch

Deno is used heavily for edge computing and is used widely across various serverless cloud providers. It would help for transitions and building to add it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Deno 2.0 should be available on Cloud now.

**Comment by Shadowfita** [comment]
@stnguyen90 is there an expected lead-time for runtimes to become available on the self-hosted version? I don't seem to have success adding deno-2.0 to the list of runtimes in "_APP_FUNCTIONS_RUNTIMES", doesn't show up as an option.
