### ISSUE TITLE
🐛 Bug Report: Error 500 on Organization Deletion

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#7736]
### 👟 Reproduction steps

1. Assuming you already have an Org. on Cloud, Go to Settings and click Delete
2. The Page shows 500: Internal Error for a brief second and then loads the cached page of the org.
3. Refresh the page and you'll see an Internal Error
4. Whats surprising is that all attempts to go to the console's main page redirect to this deleted org.

See the issue in action -

https://github.com/appwrite/appwrite/assets/20625965/7ffe20f3-cfc3-423a-abe4-109dda310763

### 👍 Expected behavior

Navigate to Onboarding if there are no existing organisations else navigate to the one existing or just navigate to user profile > organisations tab.

### 👎 Actual Behavior

Redirected to deleted organisation resulting in an Internal Error. For non-existing organisation, use Org. Not Found instead.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ItzNotABug, thanks for creating this issue! 🙏🏼 

> Whats surprising is that all attempts to go to the console's main page redirect to this deleted org.

I'm pretty sure the org is stored in local/session/prefs or something and needs to be cleared. We'll look into this.
