### ISSUE TITLE
When the 1.5 version will be available on the docker hub ?

### ISSUE THREAD

**Issue by Splinteer** [appwrite/appwrite#7742]
Hello,
I want to implement the new SSR Auth, but my infra is orchestrated with docker swarm and the last version is still not available in the docker hub.
I can use the @next versions for the clients, it's the only thing missing, no @next and no @1.5 on docker hub

Do you plan to still have every versions available ?

**Comment by ItzNotABug** [comment]
As per the **init_** event and a lot of discussions on Discord, afaik `1.5x` will most probably be available by the end of March.

**Comment by stnguyen90** [comment]
Appwrite 1.5.1 has been released: https://hub.docker.com/layers/appwrite/appwrite/1.5.1/images/sha256-c30819e9795c512984a33d894dd7ca1d79c8f73b826cc68ebe10f23157df7e65?context=explore
