### ISSUE TITLE
📚 Documentation: how can I get creat user session？

### ISSUE THREAD

**Issue by Zydzzb** [appwrite/appwrite#7748]
### 💭 Description

Erro:404，appwrite 1.5 support , but when i create ( https://cloud.appwrite.io/v1/users/{userId}/sessions )，return 404，Can anyone answer this question? Thank you.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Cloud has not been upgraded to 1.5 yet. If you look at the bottom right of the page, you'll see Cloud is still on 1.4.13.

<img width="184" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/f387619f-cf31-47c4-a645-4a55678c68e3">
