### ISSUE TITLE
🚀 Feature: Add Push and Pull Operators for Array Updates

### ISSUE THREAD

**Issue by traditionalwears** [appwrite/appwrite#7750]
### Feature Request Details:
1. **$push Operator:** This operator allows users to add elements to an array within a document. It's essential for scenarios where new elements need to be appended to existing arrays without having to retrieve and modify the entire document externally.

2. **$pull Operator:** Similarly, the $pull operator is crucial for removing elements from an array based on a specified condition. This functionality is essential for maintaining data integrity and efficiently managing arrays within documents.

### 🎤 Pitch

As an Appwrite user, I would like to request the addition of the push and pull operators for array updates in the Appwrite API. Currently, these operators are not available, making it difficult to efficiently update arrays within documents.

### Impact:
- Enhances the usability and flexibility of the Appwrite API for developers working with array data structures.
- Streamlines array updates, reducing the need for manual document retrieval and modification.
- Aligns with industry-standard practices, particularly for users transitioning from MongoDB to Appwrite.

### Additional Context:
The inclusion of push and pull operators will significantly improve the developer experience when working with arrays in Appwrite, making it easier to manage and manipulate array data within documents. This feature aligns with Appwrite's goal of providing a robust and developer-friendly backend solution.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@traditionalwears, thanks for creating this issue! 🙏🏼 This looks the same as https://github.com/appwrite/appwrite/issues/2531. As such, I'm going to close this one and it would be good if you add a 👍🏼 to the other issue.
