### ISSUE TITLE
🐛 Bug Report: Storage Permissions not working

### ISSUE THREAD

**Issue by aadish-rahman** [appwrite/appwrite#7754]
###  Storage Issue

In the starter plan while i was trying to create permissions for my storage bucket it is giving an error "Maximum file size limit you are trying to set is above the limit allowed for your plan"
I know there is 2gb limit in starter plan but i haven't uploaded any files in my storage yet 
I cant even upload anything since i cant setup my permissions
Also whatever settings i try to change in my storage bucket I'm getting the same error even if I'm trying to change the storage bucket name!!!!

### 👍 Expected behavior

The error should only come when u exceed the storage limit of 2gb in starter plan
You should be able to setup permissions and stuff

### 👎 Actual Behavior

It is giving the same error for whatever settings you try to add or change in storage bucket

<img width="943" alt="Screenshot 2024-03-08 205440" src="https://github.com/appwrite/appwrite/assets/152465910/2564f379-43e6-4638-926b-05a03e5dd1c2">

As you can see there are no files in my bucket and yet I'm getting this error

<img width="932" alt="image" src="https://github.com/appwrite/appwrite/assets/152465910/94044825-8b26-45aa-bd24-77a1ecb35a8a">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

im using appwrite 13.0.2 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by oznerta** [comment]
im actually having the same issue were able to resolve this?

**Comment by aadish-rahman** [comment]
@oznerta Yes i solved it

<img width="656" alt="image" src="https://github.com/appwrite/appwrite/assets/152465910/7c53d5bc-50fa-4fde-aaf0-4a259d1edd62">

You need to change this settings in ur storage bucket settings and set it to 50mb
Then it will be fixed

**Comment by aadish-rahman** [comment]
Replied in github :)

**Comment by oznerta** [comment]
> Author

i actually just recently found out about this too and was gonna comment the same thing here but i guess you were already able to solve it and that's good!
