### ISSUE TITLE
🐛 Bug Report: GraphQL Account params

### ISSUE THREAD

**Issue by EniXoo** [appwrite/appwrite#7758]
### 👟 Reproduction steps

When I'm using GraphQL, with Cloud Appwrite, in order to retrieve information from a user from prefs field I'm facing an issue.
Here's the query :
```GraphQL
query {
    usersList {
        total
        users {
            _id
            name
            prefs {
                data
            }
        }
    }
}
```
![image](https://github.com/appwrite/appwrite/assets/39122671/fdb04db1-02da-4e35-94b9-6bc342b0edd4)

### 👍 Expected behavior

It should return : 
```JSON
{
    "data": {
        "usersList": {
            "total": 1,
            "users": [
                {
                    "_id": "65eb064279c82abf12ee",
                    "name": "EniXo",
                    "prefs": {
                        "firstName": "Valentin",
                        "lastName": "Lebarbanchon"
                    }
                }
            ]
        }
    }
}
```

In fact, it is actually working with REST query :
**https://cloud.appwrite.io/v1/users**
Here's the partial response :
```JSON
{
    "total": 1,
    "users": [
        {
            "$id": "65eb064279c82abf12ee",
            "name": "EniXo",
            "prefs": {
                "firstName": "Valentin",
                "lastName": "Lebarbanchon"
            }
        }
    ]
}
```

### 👎 Actual Behavior

It actually returns :
```JSON
{
    "data": {
        "usersList": {
            "total": 1,
            "users": [
                {
                    "_id": "65eb064279c82abf12ee",
                    "name": "EniXo",
                    "prefs": null
                }
            ]
        }
    }
}
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

I used Postman ;)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@EniXoo, thanks for creating this issue! 🙏🏼 This is currently the expected behavior. From my understanding, GraphQL requires registering the schema of things before it can work and so it doesn't work well with dynamic data like our Preferences. As such, dynamic data is returned in the `data` field as a JSON string.

**Comment by EniXoo** [comment]
Hello @stnguyen90, hope you're doing great 🫡
I wanted to investigate on this yesterday, so I forked the project, runned it through docker-compose and it was working 🧐
![image](https://github.com/appwrite/appwrite/assets/39122671/fb05d6a4-8b1d-4b6f-abdd-7b5c8551e853)

But it doesn't work either while running this command 😅
```
docker run -it --rm ^
    --volume //var/run/docker.sock:/var/run/docker.sock ^
    --volume "%cd%"/appwrite:/usr/src/code/appwrite:rw ^
    --entrypoint="install" ^
    appwrite/appwrite:1.5.4
```

I think this issue only occurs while working packaged appwrite:1.5.4 from dockerhub + cloud instance 
![CharlieDayItsAlwaysSunnyInPhiladelphiaGIF](https://github.com/appwrite/appwrite/assets/39122671/909bff31-34dc-47b6-b0b5-659307b4deb1)

**Comment by stnguyen90** [comment]
@EniXoo, 

Oooh. Looks like it's because of the max depth:

https://github.com/appwrite/appwrite/blob/2d8694baea9cc997ef0ace6a51d215849b46f11d/app/controllers/api/graphql.php#L183

If you use the usersGet() method so that data is not nested as deep, you'll get the results:

<img width="1440" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/cf0c7bcd-591c-4ee5-bf6e-5871f0ac0149">
