### ISSUE TITLE
🐛 Bug Report: Email OTP template not available

### ISSUE THREAD

**Issue by DH-555** [appwrite/appwrite#7766]
### 👟 Reproduction steps

Go to Auth section, select email templates

### 👍 Expected behavior

There should be a section to customise the new email OTP

### 👎 Actual Behavior

2FA section and other are available but not that one

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite 1.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@DH-555, thanks for creating this issue! 🙏🏼 Looks like we got the MFA one, but missed the OTP login one. We'll get on it!

**Comment by samuelbushi** [comment]
⬆️
