### ISSUE TITLE
🐛 Bug Report: Secret is empty when creating an email/password on server

### ISSUE THREAD

**Issue by Splinteer** [appwrite/appwrite#7779]
### 👟 Reproduction steps

When I create an email/password session on my server using the SSR login flow. I get a session with an empty secret

### 👍 Expected behavior

It should have a value in it

### 👎 Actual Behavior

It actually get this:
```ts
{
  '$id': '65ee0c23dfa2c1988f01',
  '$createdAt': '2024-03-10T19:38:54.720+00:00',
  userId: '65edbb864080b63450e9',
  expire: '2025-03-10T19:38:11.916+00:00',
  provider: 'email',
  providerUid: 'email@hot.fr',
  providerAccessToken: '',
  providerAccessTokenExpiry: '',
  providerRefreshToken: '',
  ip: '10.0.0.2',
  osCode: 'MAC',
  osName: 'Mac',
  osVersion: '',
  clientType: '',
  clientCode: '',
  clientName: '',
  clientVersion: '',
  clientEngine: '',
  clientEngineVersion: '',
  deviceName: 'desktop',
  deviceBrand: 'Apple',
  deviceModel: '',
  countryCode: '--',
  countryName: 'Inconnu',
  current: true,
  factors: [ 'password' ],
  secret: '',
  mfaUpdatedAt: ''
}
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

In a self hosted docker swarm using the 1.5.2 version and node-appwrite@12

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

Here is my actual code:
```ts
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Client, Account, ID, Users } from 'node-appwrite';
import { CreateUserDto } from '../dto/create-user.dto';
import { LoginUserDto } from '../dto/login-user.dto';

@Injectable()
export class AppwriteService  {
  constructor(readonly configService: ConfigService) {  }

  getId(): string {
    return ID.unique();
  }

  getBaseClient() {
    const client = new Client();
    client
      .setEndpoint(this.configService.get('APPWRITE_URL'))
      .setProject(this.configService.get('APPWRITE_PROJECT_ID'));

    return client;
  }

  createAdminClient() {
    const client = this.getBaseClient();
    client.setKey(this.configService.get('APPWRITE_USER_API_KEY'));

    return {
      get account() {
        return new Account(client);
      },

      get users() {
        return new Users(client);
      },
    };
  }

  createSessionClient(session?: string) {
    const client = this.getBaseClient();

    if (session) {
      client.setSession(session);
    }

    return {
      get account() {
        return new Account(client);
      },
    };
  }

  async register({ email, password }: CreateUserDto) {
    const { account } = this.createSessionClient();

    const newUser = await account.create(this.getId(), email, password);

    return newUser;
  }

  async login(loginUserDto: LoginUserDto) {
    const { account } = this.createSessionClient();
    const { email, password } = loginUserDto;

    return account.createEmailPasswordSession(email, password);
  }
}
```

**Comment by stnguyen90** [comment]
@Splinteer, thanks for creating this issue! 🙏🏼 Which SDK are you using? The [node SDK is required](https://appwrite.io/docs/products/auth/server-side-rendering#initialize-clients) for this.

**Comment by Splinteer** [comment]
> @Splinteer, thanks for creating this issue! 🙏🏼 Which SDK are you using? The [node SDK is required](https://appwrite.io/docs/products/auth/server-side-rendering#initialize-clients) for this.

Hello, I'm using the latest version of the server SDK. I followed your link and [this video](**https://youtu.be/7LN05c-ov_0?si=3DY6edHD3rCFcORb**) to achieve it.
I also updated my post with my actual code

**Comment by stnguyen90** [comment]
@Splinteer, thanks for sharing your code. Would you please try to call createEmailPasswordSession() using the admin client instead of the session client?

**Comment by Splinteer** [comment]
> @Splinteer, thanks for sharing your code. Would you please try to call createEmailPasswordSession() using the admin client instead of the session client?

It was it, thanks for your help 🙏 @stnguyen90 
Is it possible to remove the secret property from the base client ? I think it'll help to avoid confusion
