### ISSUE TITLE
🐛 Bug Report: Undefined array key "templateld" msg91

### ISSUE THREAD

**Issue by rvndsngwn** [appwrite/appwrite#7785]
### 👟 Reproduction steps

Appwrite throws the following error when I try to use the msg91 service for messaging:-
```
   
appwrite-worker-messaging     | Warning: Undefined array key "templateId" in /usr/src/code/src/Appwrite/Platform/Workers/Messaging.php on line 461
appwrite-worker-messaging     | 
appwrite-worker-messaging     | Fatal error: Uncaught TypeError: Utopia\Messaging\Adapter\SMS\Msg91::__construct(): Argument #3 ($templateId) must be of type string, null given, called in /usr/src/code/src/Appwrite/Platform/Workers/Messaging.php on line 461 and defined in /usr/src/code/vendor/utopia-php/messaging/src/Utopia/Messaging/Adapter/SMS/Msg91.php:21
appwrite-worker-messaging     | Stack trace:
appwrite-worker-messaging     | #0 /usr/src/code/src/Appwrite/Platform/Workers/Messaging.php(461): Utopia\Messaging\Adapter\SMS\Msg91->__construct('MOHESU', '390713A5p9NDmG7...', NULL)
appwrite-worker-messaging     | #1 /usr/src/code/src/Appwrite/Platform/Workers/Messaging.php(236): Appwrite\Platform\Workers\Messaging->getSmsAdapter(Object(Utopia\Database\Document))
appwrite-worker-messaging     | #2 @swoole/library/core/Coroutine/functions.php(43): Appwrite\Platform\Workers\Messaging->Appwrite\Platform\Workers\{closure}()
appwrite-worker-messaging     | #3 [internal function]: Swoole\Coroutine\{closure}()
appwrite-worker-messaging     | #4 {main}
appwrite-worker-messaging     |   thrown in /usr/src/code/vendor/utopia-php/messaging/src/Utopia/Messaging/Adapter/SMS/Msg91.php on line 21
```

### 👍 Expected behavior

Appwrite should handle the Msg91 service for messaging without encountering any errors and should not produce warnings or fatal errors.

### 👎 Actual Behavior

The error mentioned above is thrown, indicating an issue with the handling of the Msg91 service in the messaging component of Appwrite.

![Screenshot 2024-03-11 at 3 29 00 PM](https://github.com/appwrite/appwrite/assets/59143934/40e3a0bd-5d23-4893-8551-ade5c4780c4c)

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite version: 1.5.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@rvndsngwn, thanks for creating this issue! 🙏🏼 Let me dig into this.

**Comment by stnguyen90** [comment]
Related to https://github.com/appwrite/appwrite/issues/7823
