### ISSUE TITLE
🐛 Bug Report: Getting Internal server error 500 while using listDocuments 

### ISSUE THREAD

**Issue by ribhugautam** [appwrite/appwrite#7792]
### 👟 Reproduction steps

Was creating a basic Todo list application which was working fine
until i added this function to get data from data base it did worked for a single time 
 
```javascript
const getTodos = async() => {
    try {
      console.log(email);
      const response = await database.listDocuments(
        import.meta.env.VITE_APP_APPWRITE_DATABASE_ID,
        import.meta.env.VITE_APP_APPWRITE_COLLECTION_ID,
        [
        Query.equal('email',email)
      ]);
      console.log(response);
      setAlltodos(response.documents);
    } 

    catch (error) {
      console.log(error);
    }
  }
```
### 👍 Expected behavior

It should return an array with documents list

### 👎 Actual Behavior

But it is giving an error message 

```
Dashboard.jsx:53 
 
 GET https://cloud.appwrite.io/v1/databases/65eee45…/collections/65e…2equal%22%2C%22attribute%22%3A%22email%22%2C%22values%22%3A%5B%22%22%5D%7D 500 (Internal Server Error)
Dashboard.jsx:64 AppwriteException: Server Error
    at Client.<anonymous> (http://localhost:5173/node_modules/.vite/deps/appwrite.js?v=f9cbd450:883:17)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:5173/node_modules/.vite/deps/appwrite.js?v=f9cbd450:488:24)
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ribhugautam, thanks for raising this issue! 🙏🏼 This is probably due to the incident that occurred. For the latest information on the status of Appwrite Cloud, check https://status.appwrite.online/. You can also subscribe to get notifications about incidents on that status page.

Are you still experiencing this problem? If so, what's your project ID?

**Comment by ribhugautam** [comment]
Yes, I am still facing this issue my project id is "65eea82ccfb0a49d1fe5"

**Comment by stnguyen90** [comment]
@ribhugautam, weird...I don't see any errors when calling list documents for project `65eea82ccfb0a49d1fe5` 🧐 That said, it looks like you're using an SDK meant for Appwrite 1.5, but Cloud is on 1.4. Please try downgrading the SDK version. You can always see what version the SDK is meant for in the readme of the SDK.

<img width="1495" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/541f8fff-dddd-4c31-881c-fe8c153d4404">

**Comment by ribhugautam** [comment]
Resolved, Thank you
