### ISSUE TITLE
🐛 Bug Report: Pref returned as List instead of Map for User & Account Model in Realtime

### ISSUE THREAD

**Issue by JoshiJoshiJoshi** [appwrite/appwrite#7797]
### 👟 Reproduction steps

When trying to convert the payload in realtime of the account channel to the "User" model it throws an error. 
Same for the teams channel when trying to convert to the "Teams" model. Apparently realtime returns a list for preferences for the User and Team model instead of a map. Retrieving the models from the REST api work as expected but not from realtime.

This has already been mentioned in a comment here:
https://github.com/appwrite/sdk-for-flutter/issues/33

I'm using Appwrite 1.5.2 selfhosted and appwrite 12.0.1 for flutter. 

### 👍 Expected behavior

Listen to "account" channel.
Change user account.
Realtime returns RealtimeMessage.
=> Convert RealtimeMessage.payload to User model successfully

### 👎 Actual Behavior

Does not convert to User model successfully due to the prefs being in a wrong format.
It is being returned as a list and not a map.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@JoshiJoshiJoshi, thanks for creating this issue! 🙏🏼 This looks the same as https://github.com/appwrite/appwrite/issues/6360 so I'm going to close this and you can 👍🏼 the other issue.
