### ISSUE TITLE
🐛 Bug Report:   Issue with Image Loading on Vercel Deployment

### ISSUE THREAD

**Issue by anuragino** [appwrite/appwrite#7801]
### 👟 Reproduction steps

I've been working on my React app locally using Appwrite storage to store images and generate previews, and everything has been functioning smoothly on local host. However, upon deploying the app to Vercel, I encountered an issue where the images are not loading.
I've taken steps to troubleshoot the problem, including attempting to add a custom domain, but the issue persists. 
Here, is the link of my website [BlogHub]( https://blogspot-vert.vercel.app/).

### 👍 Expected behavior

![image](https://github.com/appwrite/appwrite/assets/125788570/62761c7d-b6f0-403d-9279-ca9a5ea8617d)

### 👎 Actual Behavior

![Screenshot 2024-03-12 130159](https://github.com/appwrite/appwrite/assets/125788570/afe0ede2-0adc-43b5-985a-98b08b2a7e61)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@anuragino, you might be running into a 3rd party cookie problem and will need to set up a [custom domain](https://appwrite.io/docs/advanced/platform/custom-domains). To confirm, you can try to enable 3rd party cookies in your browser and test.

**Comment by anuragino** [comment]
I am trying to add a custom domain, but it is showing that the domain is verified. The certificate generation will begin after domain verification.

![Screenshot 2024-03-13 222827](https://github.com/appwrite/appwrite/assets/125788570/0e26125d-9811-46a4-819b-5e182c8f4c7c)

**Comment by stnguyen90** [comment]
> I have tried enabling 3rd party cookies but it didn't worked for me.

How did you enable 3rd party cookies? Would you please share the network logs from the browser for the request for the image? There should be a tab for the cookies included in the request.

> I am trying to add a custom domain, but it is showing that the domain is verified.

The domain should be an endpoint you're using in `client.setEndpoint()` that is a sub-domain of your app. Please make sure you thoroughly read the [custom domain docs](https://appwrite.io/docs/advanced/platform/custom-domains).

**Comment by anuragino** [comment]
These are the network log of the site.
![Screenshot 2024-03-21 155228](https://github.com/appwrite/appwrite/assets/125788570/0847ef3c-9061-421d-a45d-c99ac87953f6)

**Comment by stnguyen90** [comment]
@anuragino, please double check your project ID does not have any additional characters before it (like a plus or space).

**Comment by anuragino** [comment]
Yes, there was a space at the beginning of the project ID.

**Comment by anuragino** [comment]
Thank you very much for your assistance! The problem has been resolved, and the site is now working perfectly.
