### ISSUE TITLE
🐛 Bug Report: Unable to regenerate MFA recovery codes

### ISSUE THREAD

**Issue by kevinbarrionuevo** [appwrite/appwrite#7803]
### 👟 Reproduction steps

When I try to regenerate MFA recovery codes with `account.updateMfaRecoveryCodes()`, I get a 500 server error:

```
[Error] Timestamp: 2024-03-12T12:54:37+00:00
[Error] Method: PATCH
[Error] URL: /v1/account/mfa/recovery-codes
[Error] Type: TypeError
[Error] Message: Utopia\Database\DateTime::addSeconds(): Argument #1 ($date) must be of type DateTime, string given, called in /usr/src/code/app/controllers/shared/api/auth.php on line 21
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/DateTime.php
[Error] Line: 40
```

### 👍 Expected behavior

Generate and return new MFA recovery codes.

### 👎 Actual Behavior

Return a 500 server error.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

1.5.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Looks like something is wrong here:

https://github.com/appwrite/appwrite/blob/97261762e75a7e179f0996afc9b3e00327eb4657/app/controllers/shared/api/auth.php#L21
