### ISSUE TITLE
🚀 Feature: unique constraint on multiple attributes

### ISSUE THREAD

**Issue by pierroo** [appwrite/appwrite#7807]
### 🔖 Feature description

As of now we can only check "unique" on a single attribute at a time.

But there are many use cases where we have to make sure two attributes are unique "together"

### 🎤 Pitch

For example, a chatting app, I wanna make sure I cannot create twice the same "conversation".
A 1:1 conversation having attributes "from_id" (my user id) and "friend_id" for example.

Instead of having to do first a query to make sure it doesn't exist yet, I would like the insert to be rejected by the database itself if the duo "from_id"/"friend_id" already exists

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@pierroo, thanks for creating this issue! 🙏 Looks like you want to be able to create unique indexes on relationships. As such, it would be best to add a 👍 to https://github.com/appwrite/appwrite/issues/5400.
