### ISSUE TITLE
🐛 Bug Report: The Msg91 OTP isn't working after the 1.5 upgrade

### ISSUE THREAD

**Issue by rohankm** [appwrite/appwrite#7823]
### 👟 Reproduction steps

Hi,
I have set it up according to the docs https://appwrite.io/docs/advanced/self-hosting/sms
the OTP for login was working before the upgrade to 1.5

here are the appwrite-worker-messaging logs

```
Warning: Undefined array key "templateId" in /usr/src/code/src/Appwrite/Platform/Workers/Messaging.php on line 461
[Job] (65f19b7b27cfc0.65895609) failed to run.
[Job] (65f19b7b27cfc0.65895609) Utopia\Messaging\Adapter\SMS\Msg91::__construct(): Argument #3 ($templateId) must be of type string, null given, called in /usr/src/code/src/Appwrite/Platform/Workers/Messaging.php on line 461
[Error] Type: TypeError
[Error] Message: Utopia\Messaging\Adapter\SMS\Msg91::__construct(): Argument #3 ($templateId) must be of type string, null given, called in /usr/src/code/src/Appwrite/Platform/Workers/Messaging.php on line 461
[Error] File: /usr/src/code/vendor/utopia-php/messaging/src/Utopia/Messaging/Adapter/SMS/Msg91.php
[Error] Line: 21
```

### 👍 Expected behavior

it should send the otp

### 👎 Actual Behavior

```
Warning: Undefined array key "templateId" in /usr/src/code/src/Appwrite/Platform/Workers/Messaging.php on line 461
[Job] (65f19b7b27cfc0.65895609) failed to run.
[Job] (65f19b7b27cfc0.65895609) Utopia\Messaging\Adapter\SMS\Msg91::__construct(): Argument #3 ($templateId) must be of type string, null given, called in /usr/src/code/src/Appwrite/Platform/Workers/Messaging.php on line 461
[Error] Type: TypeError
[Error] Message: Utopia\Messaging\Adapter\SMS\Msg91::__construct(): Argument #3 ($templateId) must be of type string, null given, called in /usr/src/code/src/Appwrite/Platform/Workers/Messaging.php on line 461
[Error] File: /usr/src/code/vendor/utopia-php/messaging/src/Utopia/Messaging/Adapter/SMS/Msg91.php
[Error] Line: 21
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@rohankm, thanks for creating this! 🙏🏼 Looks like we need to:

1. [ ] extract the templateId from the env var and set it [here](https://github.com/appwrite/appwrite/blob/536c67f54d767bce4cc60d358c09519cbd023f3f/src/Appwrite/Platform/Workers/Messaging.php#L410-L413)

MSG91 in the Messaging Providers is also broken. For that, we'll need to:

1. [ ] Update the [Create MSG91](https://github.com/appwrite/appwrite/blob/536c67f54d767bce4cc60d358c09519cbd023f3f/app/controllers/api/messaging.php#L300-L375) endpoint to:
   * accept templateId as a param
   * add templateId to credentials
   * remove the from param
2. [ ] Update the [Update MSG91](https://github.com/appwrite/appwrite/blob/536c67f54d767bce4cc60d358c09519cbd023f3f/app/controllers/api/messaging.php#L1316-L1396) endpoint to:
   * accept templateId as a param
   * add templateId to credentials
   * remove the from param
3. [ ] Update the Console

**Comment by rohankm** [comment]
@stnguyen90 for temporary i manually set the keys here https://github.com/appwrite/appwrite/blob/536c67f54d767bce4cc60d358c09519cbd023f3f/src/Appwrite/Platform/Workers/Messaging.php#L461

I logged the messages being sent and it's like this `596853 is your myProject verification code.`

for Msg91 especially India there are specific variables set which cannot be changed on the go

here is the error message from Msg91 
 ```
DLT Template variable exceeded max length
 ```

**Comment by rohankm** [comment]
as a workaround for this i had to modify this line of code

https://github.com/appwrite/appwrite/blob/f7e6d516efe3afbf6ee2343fd99a9d5692379076/app/controllers/api/account.php#L2301
`$message = $message->setParam('{{token}}', $secret);`
