### ISSUE TITLE
🐛 Bug Report: Continuously jump to the verify page after enabling MFA

### ISSUE THREAD

**Issue by nexmoe** [appwrite/appwrite#7845]
### 👟 Reproduction steps

When I enable MFA at the console, then it will Continuously jump to the verify page after enabling MFA

<img width="1275" alt="Snipaste_2024-03-20_00-16-09" src="https://github.com/appwrite/appwrite/assets/16796652/c301cac5-a240-4938-accf-afa640c379bb">

### 👍 Expected behavior

Appwrite should let me initialize my MFA first.
But I can go into the console now.
Is there a way to disable MFA so I can get into the console?

### 👎 Actual Behavior

Continuously jump to the verify page after enabling MFA.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.5.3

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@nexmoe, you're supposed to be able to add an authenticator after enabling...Do you happen to have a verified email address? This could happen if you did a password reset.

> Is there a way to disable MFA so I can get into the console?

To disable, you'll have to go into the database and look at the `_console_users` table for your user. There should be a column for `mfa` which you can set to 0 (for false). You may also need to look in the cache (redis) for an entry with your user ID (`_uid` column) and delete it from the cache.

**Comment by nexmoe** [comment]
I solved this problem by operating the database.
I found that authenticators are NULL, which may be the cause of the problem.
<img width="1069" alt="Snipaste_2024-03-20_10-16-06" src="https://github.com/appwrite/appwrite/assets/16796652/5fd22adc-f699-4440-9c27-44c675760a15">
