### ISSUE TITLE
🐛 Bug Report: Posts not getting created

### ISSUE THREAD

**Issue by viditpagi123** [appwrite/appwrite#7862]
### 👟 Reproduction steps

When i was creating a post it wasn't getting created

### 👍 Expected behavior

Its not getting displayed

### 👎 Actual Behavior

its not displaying post 
![Screenshot 2024-03-25 121859](https://github.com/appwrite/appwrite/assets/82284774/78778306-aec7-4cd6-beb2-835d31dfff38)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by EVDOG4LIFE** [comment]
Hello @viditpagi123, thank you for opening this.

This seems to be more along the line of a misconfiguration on your side, I'm going to go ahead and close this out and suggest that you create a post in the Support channel on our official [Discord](https://appwrite.io/appwrite). 

If you still feel that this is a defect with the platform, please reopen this with as much detail as you can - be mindful that this is an open source project with community contributors so you should be as detailed as possible so any contributor can potentially make improvements to the source code.
