### ISSUE TITLE
🐛 Bug Report: Creation of collection attribute is not being awaited correctly in self hosted function using dart.

### ISSUE THREAD

**Issue by eauw** [appwrite/appwrite#7867]
### 👟 Reproduction steps

The code of my function:

```
    final databases = Databases(client);

    await databases.create(databaseId: id, name: id);
    context.log('Event database created.');

    const collectionId = 'tokens';

    await databases.createCollection(
      databaseId: id,
      collectionId: collectionId,
      name: collectionId,
      enabled: true,
    );

    context.log('Event collection tokens created.');

    await databases.createStringAttribute(
      databaseId: id,
      collectionId: collectionId,
      key: 'name',
      size: 255,
      xrequired: true,
    );

    context.log('tokens collection name attribute added.');

    await databases.createStringAttribute(
      databaseId: id,
      collectionId: collectionId,
      key: 'value',
      size: 255,
      xrequired: true,
    );

    await Future.delayed(Duration(seconds: 2)); // artificial delay for debugging

    context.log('tokens collection value attribute added.');

    final uploadToken = _generateToken();
    context.log(uploadToken);
    await databases.createDocument(
      databaseId: id,
      collectionId: collectionId,
      documentId: ID.unique(),
      data: {'name': 'upload', 'value': uploadToken},
    );

    context.log('Event upload token document created.');

    final downloadToken = _generateToken();

    await databases.createDocument(
      databaseId: id,
      collectionId: collectionId,
      documentId: ID.unique(),
      data: {'name': 'download', 'value': downloadToken},
    );
```

### 👍 Expected behavior

It should work straight forward creating a database with a collection called "tokens" with two string attributes.
But it only works with the artificial delay `await Future.delayed(Duration(seconds: 2));` which I don't want for obvious reasons.

### 👎 Actual Behavior

If I remove the delay I get the following exceptoin:
```
AppwriteException: document_invalid_structure, Invalid document structure: Unknown attribute: "value" (400)
Converting object to an encodable object failed: Instance of 'AppwriteException'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:793)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:874)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:829)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:784)
#4      _JsonStringStringifier.printOn (dart:convert/json.dart:982)
#5      _JsonStringStringifier.stringify (dart:convert/json.dart:967)
#6      JsonEncoder.convert (dart:convert/json.dart:345)
#7      JsonCodec.encode (dart:convert/json.dart:231)
#8      jsonEncode (dart:convert/json.dart:114)
#9      RuntimeResponse.json (file:///usr/local/server/src/function_types.dart:54)
#10     main (package:starter_template/main.dart:100)
<asynchronous suspension>
#11     Future.any.onValue (dart:async/future.dart:608)
<asynchronous suspension>
```

It seems to me that the call of createStringAttribute is not awaiting correctly. In the beginning I got the same error for the attribute "name". I can't tell why that exception is gone and it only complains about the second one now.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I self host via Docker on several Linux machines.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@eauw, thanks for creating this issue! 🙏🏼 The SDK is behaving as expected. When creating an attribute or index, the creation is done asynchronously by a background worker. If you check the status of the attribute that is returned from the API call, you'll see the status is `processing`. It is not ready until the status is updated to `available`.

**Comment by eauw** [comment]
> @eauw, thanks for creating this issue! 🙏🏼 The SDK is behaving as expected. When creating an attribute or index, the creation is done asynchronously by a background worker. If you check the status of the attribute that is returned from the API call, you'll see the status is `processing`. It is not ready until the status is updated to `available`.

Thank you for the explaination. I will fix my code.
But how is the `future ` implemented then? What is `await` waiting for when its finishing doesn't mean it's done?
