### ISSUE TITLE
🚀 Enhancement: Missing Country for Locale endpoint -- User Inquiry Regarding Addition of Taiwan to Countries List

### ISSUE THREAD

**Issue by xuelink** [appwrite/appwrite#7868]
### 🔖 Enhancement description

Adding a new country "Taiwan"

### 🎤 Pitch

Hey everyone

One of our users has recently raised an issue regarding the selection of their country within the app. They have expressed a desire to see Taiwan added to the list of available countries.

As per the conversation provided by the user, they have expressed their concern about not being able to select Taiwan and instead having to choose China as an alternative. They have also mentioned that they understand the complexities involved in adding a new country to the app and have kindly requested any updates or insights into the progress of this issue.

Our user's satisfaction is of utmost importance to us, and we strive to address their concerns promptly. Therefore, I would like to inquire if there are any plans or timelines in place for the addition of Taiwan to the countries list. Additionally, if there are any updates or progress regarding this matter, we would appreciate being kept informed so that we can provide our user with the necessary information.

Thank you for your attention to this matter and for your commitment to improving the user experience of the app. We look forward to your response and the potential inclusion of Taiwan in the countries list.

Best

Discord Thread: https://discord.com/channels/564160730845151244/1215561933550518342

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by xuelink** [comment]
Linked with external issue: https://github.com/languageXchange/languageXchange/issues/534

**Comment by stnguyen90** [comment]
@xuelink, thanks for raising this issue! 🙏 You're referring to [this](https://appwrite.io/docs/references/cloud/client-web/locale#listCountries) API, right? And you'd like there to be a TW code and Taiwan name like:

```json
{
  "name": "Taiwan",
  "code": "TW"
}
```

**Comment by xuelink** [comment]
Yes exactly what i mean.

**Comment by xuelink** [comment]
Can you please assign to me ? @stnguyen90

**Comment by stnguyen90** [comment]
@xuelink, assigned! 

Adding TW into the list of countries is easy:

https://github.com/appwrite/appwrite/blob/7316a2da0abd6e711de54b9e92ce5d2bf69d85d1/app/config/locale/countries.php#L178-L187

The thing that will take more time is that it needs to be added for every language too. For example, english:

https://github.com/appwrite/appwrite/blob/7316a2da0abd6e711de54b9e92ce5d2bf69d85d1/app/config/locale/translations/en.json#L223-L231

**Comment by xuelink** [comment]
Got it, no worries, let me do!  @stnguyen90

**Comment by xuelink** [comment]
@stnguyen90 Can you please check this PR is suitable for this issue or not? https://github.com/appwrite/appwrite/pull/7873

**Comment by stnguyen90** [comment]
Adding Taiwan since it's part of [ISO 3166](https://www.iso.org/obp/ui/#iso:code:3166:TW)
