### ISSUE TITLE
🐛 Bug Report: C# Functions are not working with SqlClient (System.PlatformNotSupportedException)

### ISSUE THREAD

**Issue by Kuromory** [appwrite/appwrite#7869]
### 👟 Reproduction steps

I created a function from the appwrite template (npm install appwrite)
I changed the StarterTemplate.csprj to:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<!-- <RuntimeIdentifier>ubuntu.22.04-x64</RuntimeIdentifier> -->
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Appwrite" Version="0.8.1" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
	</ItemGroup>
</Project>
```
I tried from Microsoft and System to use the SqlClient:
```c#
using var connection = new SqlConnection(connectionString);
```

### 👍 Expected behavior

I open a connection to my SQL server

### 👎 Actual Behavior

I get this exception when the function is run (depending what I use it is System or Microsoft):
```
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
```

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I use docker with the provided docker-compose.yml file

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Kuromory, thanks for raising this issue! Some questions:

1. What version of the dotnet runtime are you using?
2. Are there any other OS level dependencies required to use the package? 
3. How would you use that package in an alpine-based docker container?

**Comment by Kuromory** [comment]
> @Kuromory, thanks for raising this issue! Some questions:
> 
>     1. What version of the dotnet runtime are you using?
> 
>     2. Are there any other OS level dependencies required to use the package?
> 
>     3. How would you use that package in an alpine-based docker container?

thanks for the reply :)

1. I use dotnet 6.0 sdk what appwrite said it supports.
2. not that I know of...
3. As far as I know I can just use it... but I am not really an expert in this :X

But a little of googleing I've got following links:
[https://stackoverflow.com/questions/74748162/docker-api-not-connecting-to-sql-server-in-docker](https://stackoverflow.com/questions/74748162/docker-api-not-connecting-to-sql-server-in-docker) (not my problem but It seems to be working in docker)
The package doc and alpine doc from MS:
[https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient?view=dotnet-plat-ext-8.0](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient?view=dotnet-plat-ext-8.0)
[https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine](https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine)

**Comment by adityaoberai** [comment]
> @adityaoberai, do you have any ideas about this?

This error might have to with the target OS set for the function 

Noticed this in a couple of other spots

- https://github.com/dotnet/SqlClient/issues/2030
- https://stackoverflow.com/questions/72559921/microsoft-data-sqlclient-is-not-supported-on-this-platform-in-net-6-0-c-sharp-l

cc: @abnegate

**Comment by abnegate** [comment]
@adityaoberai We likely need to explicitly set the `RuntimeIdentifier` to `linux-musl-x64` in the runtime csproj, please test it

**Comment by Kuromory** [comment]
@abnegate @adityaoberai is there any update to this?
