### ISSUE TITLE
🐛 Bug Report: CLI Not Synchronised

### ISSUE THREAD

**Issue by erotic-ops** [appwrite/appwrite#7871]
### Description
I've encountered an issue where functions created via the Appwrite CLI are not visible in the Appwrite console. Additionally, deploying functions through the CLI does not seem to reflect on the platform either. 

### Steps
1. Install the latest version of the Appwrite CLI following the official documentation.
2. Create a new function using the CLI with the following command: `appwrite login`, `appwrite init function`.
3. Check the Appwrite console to see if the function appears.
4. Attempt to deploy a function to the platform using CLI with the command: `appwrite deploy function`
5. Check the Appwrite console for the deployment status.

### 👍 Expected behavior

Functions created or deployed using the Appwrite CLI should appear and be manageable within the Appwrite console.

### 👎 Actual Behavior

Functions and deployments initiated through the CLI are not visible or reflected in the Appwrite console, indicating a possible synchronization issue between the CLI and the platform.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

- Appwrite CLI version: 1.2.1
- Operating System: Windows 11

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@erotic-ops, thanks for raising this issue! 🙏🏼 I can't seem to reproduce your problem as deploying functions works fine for me 🧐 

You mentioned you're using:

> Appwrite CLI version: 1.2.1

That is extremely old. Would you please try using version 4.2 as that is meant for Appwrite Cloud?

**Comment by erotic-ops** [comment]
Ok, thank you very much.

**Comment by stnguyen90** [comment]
I'm going to close this for now, but feel free to create a support post on our [Discord](https://appwrite.io/discord) if you still need any assistance.

**Comment by erotic-ops** [comment]
Thanks, I will.
