### ISSUE TITLE
🐛 Bug Report: Google auth `Appwriteexception: user (role: guests) missing scope`

### ISSUE THREAD

**Issue by kamit-transient** [appwrite/appwrite#7875]
### 👟 Reproduction steps

I am following the [official docs](https://appwrite.io/docs/products/auth/oauth2) to create a google OAuth login flow using the AppWrite 1.5.4 version.

once the user is logged in using google sign-in page, the flow redirects to appwrite's callback URL with token etc and it remains there and throws `there is error: AppwriteException: User (role: guests) missing scope (account)`

### 👍 Expected behavior

It should do below:
1. Allow login  using google
2. should redirect back the front-end client
3. It should create the browser session on client side.

### 👎 Actual Behavior

once the user is logged in using Google sign-in page, the flow redirects to appwrite's callback URL with token, etc and it remains there and throws `there is error: AppwriteException: User (role: guests) missing scope (account)`

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite version: 1.5.4
front-end: Next.Js

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by nimakarimi97** [comment]
I have the same issue as well.
```
[unhandledRejection] User (role: guests) missing scope (account)
```

**Comment by gepd** [comment]
Are you using the node sdk?

**Comment by kamit-transient** [comment]
no. Its normal client-side next.js call

**Comment by gepd** [comment]
Can you create a new topic in discord? I don't think this is a bug, but it's easier and faster to check in discord
