### ISSUE TITLE
🐛 Bug Report: 429 Too Many Requests at high upload speeds

### ISSUE THREAD

**Issue by WuGGu** [appwrite/appwrite#7879]
### 👟 Reproduction steps

Upload big file like 1GB. Use a Internet connection with 200Mbit Upload.

### 👍 Expected behavior

Should just upload quicker to the storage.

### 👎 Actual Behavior

Returns 429 after a view seconds because of Too Many Requests in under 60 seconds.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Hetzner Machine with Rocky Linux and Docker.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@WuGGu, thanks for creating this issue! 🙏🏼 Would you please share the exact full error?

**Comment by WuGGu** [comment]
I'll be back in the office on Tuesday due to the Easter vacation and will reproduce it. 😊

**Comment by WuGGu** [comment]
@stnguyen90 
I hope this helps =) In my company we have 1Gbit Up and Downstream. 

```json
{
    "message": "Rate limit for the current endpoint has been exceeded. Please try again after some time.",
    "code": 429,
    "type": "general_rate_limit_exceeded",
    "version": "1.5.4"
}
```
payload:
```
fileId: unique()
file: (binary)
permissions[]: read("team:65fd90808a4607e5755e")
permissions[]: write("team:65fd90808a4607e5755e/owner")
```

**Comment by stnguyen90** [comment]
@WuGGu, thanks for this! Also, what are you using to create the file? If you're using one of our SDKs, would you please provide the version?
