### ISSUE TITLE
🐛 Bug Report: Location does not seem to be compatible with the Chinese region

### ISSUE THREAD

**Issue by BingZi-233** [appwrite/appwrite#7880]
### 👟 Reproduction steps

Access using IP of [China-Hong Kong], shows unknown

### 👍 Expected behavior

The Location field displays [China Hong Kong]

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/54745251/ff71a412-9590-435a-839d-706ba273d3ca)

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

[Version 1.5.3](https://github.com/appwrite/appwrite/releases)
Using console operations and Kotlin SDK 5.0.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@BingZi-233, thanks for creating this issue! 🙏🏼 we use maxmind for the data and it seems the IP works in their demo:

![image](https://github.com/appwrite/appwrite/assets/1477010/a876efed-a851-426d-b84e-63725a725406)

Our db is only a month or so old so I'm surprised it wasn't able to pick it up 🧐

**Comment by stnguyen90** [comment]
So I manually tested with the IP country database and it was able to pick up 18.162.44.186 is in HK....buuuut looks like the problem is we don't have HK as a country:

https://github.com/appwrite/appwrite/blob/ffbf3c0058572b1d930bc76b240980203ecd4126/app/config/locale/countries.php#L72-L83

**Comment by BingZi-233** [comment]
It is true that Hong Kong is not a country, it is a region, which belongs to China.
I'm a little curious that I didn't find the ZH in the list of regions, which should be a bug

**Comment by Rohit-Singh-Rawat** [comment]
Hey @stnguyen90, is the issue only related to adding 'HK' to Database or anything else?

**Comment by stnguyen90** [comment]
@Rohit-Singh-Rawat, yes, but let me discuss with the team about this.

**Comment by deanurag** [comment]
I would like to work, on this. Please assign me this issue.

**Comment by stnguyen90** [comment]
@deanurag, assigned! Thanks for your interest! 🙏🏼

**Comment by Andree98** [comment]
@stnguyen90 The country name is wrong

<img width="255" alt="Screenshot 2024-04-26 at 09 14 33" src="https://github.com/appwrite/appwrite/assets/34305925/2a8a3bc1-e733-4941-9a1a-85edb87829e2">

**Comment by stnguyen90** [comment]
Doh! Looks like we need to add `countries.hk` for all the translations 😕 . For example, here:

https://github.com/appwrite/appwrite/blob/644704155a2491ccd2432c46ec4fa97989e48303/app/config/locale/translations/en.json#L119-L124

**Comment by deanurag** [comment]
I would like to work on this.

**Comment by navjotNSK** [comment]
@stnguyen90 I would like to work, on this. Please assign me this issue.

**Comment by navjotNSK** [comment]
@stnguyen90 I have raised this PR and I will be keep on adding into all the translations files , Meanwhile can you please review the PR once -  https://github.com/appwrite/appwrite/pull/8179

**Comment by navjotNSK** [comment]
@stnguyen90 Added the translations in all the files , Can you please review once

**Comment by navjotNSK** [comment]
@stnguyen90 Any update on the PR - https://github.com/appwrite/appwrite/pull/8179

**Comment by stnguyen90** [comment]
@navjotNSK it's in my list to review 🙏🏼

**Comment by BingZi-233** [comment]
In **Version 1.5.7** the problem persists, and the IP address **103.151.173.102** is identified as **Unknown**

**Comment by stnguyen90** [comment]
@BingZi-233, yes, this issue is still open and [this](https://github.com/appwrite/appwrite/pull/8179) is still in progress.
