### ISSUE TITLE
🚀 Enhancement:  [FEATURE] Can we have endpoint for generating ID.uniquie() it will return a result of uniquie id

### ISSUE THREAD

**Issue by moshOntong-IT** [appwrite/appwrite#7886]
### 🔖 Enhancement description

We can use nanoid or uuid for generating a unique ID, but I love how the appwrite generating an unique ID. I hope that like under avatar api, we have also endpoint for generating unique id like the result of ID.unique()

### 🎤 Pitch

In my case I want to use the uniqueness generated by the Appwrite ID instead of using the nanoid or uuid.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
TBH, a separate endpoint seems like an overkill to create a random identifier that can easily be created on the client side.
There's nothing fancy in Appwrite's ID generation, see source [here](https://github.com/utopia-php/database/blob/main/src/Database/Helpers/ID.php#L14).

**Comment by moshOntong-IT** [comment]
> TBH, a separate endpoint seems like an overkill to create a random identifier that can easily be created on the client side. There's nothing fancy in Appwrite's ID generation logic, see source [here](https://github.com/utopia-php/database/blob/main/src/Database/Helpers/ID.php#L14).

I try to convert it into javascript

![image](https://github.com/appwrite/appwrite/assets/57244338/96758b2c-2dab-467d-98ce-52defdfd1acd)
But cannot get the same result of appwrite id

**Comment by ItzNotABug** [comment]
Haven't played with `Date`s much but something like this gives a similar result  - 
```js
function unique(padding = 7) {
  const now = Date.now();
  
  const seconds = Math.floor(now / 1000).toString(16);
  const microseconds = ((now % 1000) / 1000).toFixed(5).substring(2, 7);
  
  let baseID = seconds + microseconds;

  let extraPadding = '';
  if (padding > 0) {
    const bytesNeeded = Math.ceil(padding / 2);
    extraPadding = crypto.randomBytes(bytesNeeded).toString('hex').substring(0, padding);
  }

  return baseID + extraPadding;
}
```

Output -
```bash
660a8d5f35800f3e24dc << Node
660a8d65c3a694a19ddc << PHP
```

---
Tested on https://www.programiz.com/javascript/online-compiler.

**Comment by stnguyen90** [comment]
The implementation for this was done as part of https://github.com/appwrite/sdk-generator/pull/779. It's been released for some server SDKs already like [dart sdk](https://github.com/appwrite/sdk-for-dart/blob/11.0.2/lib/id.dart). The rest will be released soon.
