### ISSUE TITLE
🐛 Bug Report: problem migrating cache collection

### ISSUE THREAD

**Issue by Emilien-Lambert** [appwrite/appwrite#7887]
### 👟 Reproduction steps

I wanted to update my Appwrite server to version 1.5.4 and when I run the `migrate` command to execute the migration script I get an error when processing the `cache` collection. (from version 1.4.2)

I looked in mariadb and it seems that all my UUIDs in the cache collection are this shape `b64e17d8fbcf3f37801eafd369a29e16*509` I don't know if this is normal or not. 

What can I do in the meantime? Delete the *509 at the end of the UUID? Or could I drop the whole `_1_cache` and `_1_cache_perms` collection? If it's cache, it shouldn't matter, should it? 

Thank you for your help

### 👍 Expected behavior

The migration script runs smoothly and error-free.

### 👎 Actual Behavior

Error executing migration from version 1.4.2

```
Migrating Collection cache:
100 / 587

Fatal error: Uncaught Utopia\Database\Exception\Query: Invalid query: Invalid cursor: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php:4694
Stack trace:
#0 /usr/src/code/src/Appwrite/Migration/Migration.php(221): Utopia\Database\Database->find(Object(Utopia\Database\Document), Array)
#1 /usr/src/code/src/Appwrite/Migration/Migration.php(171): Appwrite\Migration\Migration->documentsIterator('cache')
#2 [internal function]: Appwrite\Migration\Migration->Appwrite\Migration\{closure}(Array, Array)
#3 {main}
  thrown in /usr/src/code/vendor/utopia-php/database/src/Database/Database.php on line 4694
```

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Application Appwrite deployed with CapRover
OS Ubuntu 23.10

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Ya it looks like the ID violates the constraint we have...The best thing to do right now would be to delete everything in that cache table and then run the migrate command again.

**Comment by stnguyen90** [comment]
@mkay-42069, do you have any other cache tables?

**Comment by xuelink** [comment]
> > @mkay-42069, do you have any other cache tables?
> 
> Ah, yes I have. My bad, just removed the second cache, migration was successful!
> 
> For future reference and just to be clear I currently have two projects, would I need to delete the cache for each project individually?

Do you mean that? @mkay-42069 

```mysql
DELETE FROM _console_cache;
DELETE FROM _console_cache_perms;
```

**Comment by xuelink** [comment]
@mkay-42069 i dont have only `_3`  instead of `_1` and `_2`  and when i run following it worked for me, thank you !

```sql
DELETE FROM _console_cache;
DELETE FROM _console_cache_perms;
DELETE FROM _3_cache;
DELETE FROM _3_cache_perms;
```

**Comment by stnguyen90** [comment]
Ohhh...the length isn't the problem...it's the * in it...

**Comment by Emilien-Lambert** [comment]
> > b64e17d8fbcf3f37801eafd369a29e16*509
> 
> Ohhh...the length isn't the problem...it's the `*` in it...Looks like this should only be a problem for projects with data before [1.4.3](https://github.com/appwrite/appwrite/commit/a46879f1cba0973367d78f0cf549168888e5595d) and shouldn't be a problem moving forward.

I was careful to mention the following in the issue  🙄

"I looked in mariadb and it seems that all my UUIDs in the cache collection are this shape b64e17d8fbcf3f37801eafd369a29e16*509 I don't know if this is normal or not."

**Comment by DevJCrystal** [comment]
I had to delete everything up to _7_cache and _7_cache_perms. Thanks for the help!
