### ISSUE TITLE
🐛 Bug Report: Topic Shows 0 Subscribers

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#7892]
### 👟 Reproduction steps

Pre-requisite: Assuming you have a few messaging targets [email, push, etc.] in a project.

---
1. Go to Console > Select a Project
2. Go to Messaging Dashboard
3. Select Topics Tab & Create a Topic
4. You are navigated to the Topic Dashboard, Click on "Add subscriber"
5. Select the Targets to add as Subscribers
6. Go Back to Topics Page
7. You'll see the Subscriber count is `0`

---
### Screenshots

1. Subscribers

![topic-subscribers](https://github.com/appwrite/appwrite/assets/20625965/367088ef-9453-4569-82a9-8d6cf2b1b374)

2. Topic Table

![topics](https://github.com/appwrite/appwrite/assets/20625965/652d8d8d-5427-4f8a-96e8-bac9281af98f)

### 👍 Expected behavior

Show correct subscribers count.

### 👎 Actual Behavior

Subscribers count is always 0.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ItzNotABug, thanks for creating this issue! 🙏🏼 I can't seem to reproduce 🧐 I added 2 subscribers:

<img width="1270" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/3ca163e0-1eb1-478f-80e6-e0fe8cc6399a">

And the subscribers count shows 2:

<img width="1244" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/fe9c7ec6-1f46-4726-b484-20227fa40b51">

Some questions:

1. Which 1.5 version are you on?
2. What's the JSON for the get topic api call? Mine is:

```json
{
  "$id": "topic-1",
  "$createdAt": "2024-03-12T13:55:45.097+00:00",
  "$updatedAt": "2024-03-12T13:55:45.097+00:00",
  "name": "Topic 1",
  "emailTotal": 1,
  "smsTotal": 0,
  "pushTotal": 1,
  "subscribe": [
    "users"
  ]
}
```

**Comment by ItzNotABug** [comment]
Tried recreating a topic. Same result.

Appwrite: `1.5.4`
`JSON` for the get topic api call -

```json
{
  "total":1,
  "topics":[
    {
      "$id":"general",
      "$createdAt":"2024-04-02T05:56:26.034+00:00",
      "$updatedAt":"2024-04-02T05:56:26.034+00:00",
      "name":"General",
      "emailTotal":0,
      "smsTotal":0,
      "pushTotal":0,
      "subscribe":[
        "users"
      ]
    }
  ]
}
```

**Comment by ItzNotABug** [comment]
Update: I tried in an incognito tab on Chrome, seems to work fine now. It was probably the cache.
Although now there's a different issue, something with the state I guess. I'll file another issue for that.

Closing this one.

**Comment by ItzNotABug** [comment]
Reopening this as I can again reproduce this on a `1.5.7`, self-hosted instance.

**Comment by ItzNotABug** [comment]
Updated specs -

Topic shows 0 -

![topic-shows-no-subscribers](https://github.com/appwrite/appwrite/assets/20625965/6147e2c7-5d1b-4d56-a0a6-351ff6eefb84)

Topic has 2 subs -

![topic-has-subcribers](https://github.com/appwrite/appwrite/assets/20625965/8c784bfa-e43b-41db-a176-bc5f58a28c49)

---
JSON Responses -

1. Topic Call
```json
{
  "$id":"test",
  "$createdAt":"2024-06-10T08:06:29.493+00:00",
  "$updatedAt":"2024-06-10T08:06:29.493+00:00",
  "name":"Test Topic",
  "emailTotal":0,
  "smsTotal":0,
  "pushTotal":0,
  "subscribe":[
    "users"
  ]
}
```

2. Subscribers Call
```json
{
  "total":2,
  "subscribers":[
    {
      "$id":"6666b40f001e1d1d7bac",
      "$createdAt":"2024-06-10T08:06:39.727+00:00",
      "$updatedAt":"2024-06-10T08:06:39.727+00:00",
      "targetId":"6666b3e5e64f0eda3f00",
      "target":{
        "$id":"6666b3e5e64f0eda3f00",
        "$createdAt":"2024-06-10T08:05:58.191+00:00",
        "$updatedAt":"2024-06-10T08:05:58.191+00:00",
        "name":"Apple iPhone",
        "userId":"6666b3de7c95b8045713",
        "providerId":null,
        "providerType":"push",
        "identifier":"bbca71e6249223938d5c815fc793eb65247e5f57cbcf4b5913207ac00fc41257"
      },
      "userId":"6666b3de7c95b8045713",
      "userName":"",
      "topicId":"test",
      "providerType":"push"
    },
    {
      "$id":"6666b40f001e07efa34c",
      "$createdAt":"2024-06-10T08:06:39.722+00:00",
      "$updatedAt":"2024-06-10T08:06:39.722+00:00",
      "targetId":"6666b1bbe691424290b3",
      "target":{
        "$id":"6666b1bbe691424290b3",
        "$createdAt":"2024-06-10T07:56:44.161+00:00",
        "$updatedAt":"2024-06-10T07:56:44.161+00:00",
        "name":"Apple iPhone 15 Pro",
        "userId":"6666b1b760ab54a347dd",
        "providerId":null,
        "providerType":"push",
        "identifier":"8038bbdb6efb2eb8ad5d39aabc336a9d78eb8fe541ede49971aa4943461beab1c1d59f6936f91d34c31cf9db855e559f166e10909cbc8e400ea666c2a488b0fecc4c01a958e16e6a63d9452019f387f4"
      },
      "userId":"6666b1b760ab54a347dd",
      "userName":"",
      "topicId":"test",
      "providerType":"push"
    }
  ]
}
```

**Comment by ItzNotABug** [comment]
Update -
The issue lies in the migration script where no `default` is provided so it resorts to `NULL` which doesn't really perform an increment on the attribute.

Source - https://github.com/appwrite/appwrite/blob/f91a8a91359310400726139bf8ee39424f76b465/src/Appwrite/Migration/Migration.php#L268

**Comment by ItzNotABug** [comment]
@Steven, can I work on this?
I see that the `config/collections.php` includes the default values, just not the migration.

A quick fix like below suffices?
```php
'default' => $attribute['default'] ?? null,
```

**Comment by stnguyen90** [comment]
We also need to fix the topics collection for people already on 1.5.x. So, the V20.php migration would need to be updated to update the topics collection and set the default after the webhook one:

https://github.com/appwrite/appwrite/blob/868e57a9a34f522fa549b45f381cde03ae15cc45/src/Appwrite/Migration/Version/V20.php#L311-L340
