### ISSUE TITLE
🐛 Bug Report: SDKs Missing Classes

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#7898]
### 👟 Reproduction steps

Appwrite SDKs for Mobile i.e. `sdk-for-android` & `sdk-for-apple` seem to be missing a few classes after the Messaging product was introduced.

---
Missing Classes -
1. **OS.requestPermission(...)** mentioned [here](https://appwrite.io/docs/products/messaging/send-push-notifications).
2. **io.appwrite.NotificationHandler** Messaging Service for Android, mentioned [here](https://appwrite.io/docs/products/messaging/fcm).

### 👍 Expected behavior

Either update docs or add classes/methods.

### 👎 Actual Behavior

Classes are missing from SDKs.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
@stnguyen90 
Maybe update the docs to provide an example on how to request for permission & an example on sdk repo for the NotificationHandler?

**Comment by gewenyu99** [comment]
Related: https://github.com/appwrite/website/pull/856

**Comment by stnguyen90** [comment]
@gewenyu99, there are some other references still:

1. https://github.com/appwrite/website/blob/b4db3f85c6f3bbb7b719a98d55985da5d249ec5f/src/routes/docs/products/messaging/targets/%2Bpage.markdoc#L76
2. https://github.com/appwrite/website/blob/b4db3f85c6f3bbb7b719a98d55985da5d249ec5f/src/routes/docs/products/messaging/send-push-notifications/%2Bpage.markdoc#L238
