### ISSUE TITLE
🚀 Enhancement: Allow Selecting Provider When Sending a Message

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#7903]
### 🔖 Enhancement description

This issue is a mix of a Request for an Enhancement & a Demo of an underlying Bug in Messaging.

---
Currently, whatever provider is added the first time is used for all future operations for messaging.
This can cause inconsistencies and confusion when sending fails due to using a wrong provider for the op.

Note: This enhancement can be applied to all Providers.

---
Problematic Scenario in case of Push Notifications - 
1. Add APNS as a Provider for iOS
2. Add FCM as a Provider for Android
3. Register an Android and an iOS App as Push Targets
4. Compose a Push Notification & Send
5. The Message is sent to the iOS App but not the Android
6. The status of the Message is marked as `Failed` with an error like -
    `Failed sending to target ID:TARGET with error: Expired device token.`

See - 

https://github.com/appwrite/appwrite/assets/20625965/de963e27-fc1d-4d55-b776-99d0a0d58de1

Received Push Notification on iOS - 
![Apple Push Notification](https://github.com/appwrite/appwrite/assets/20625965/269a261a-5e9f-4507-aa61-0d566fd2eae1)

### 🎤 Pitch

It would be great if we could target separate platforms when sending push notifications or selecting providers for other message types i.e. Emails or SMS.
Example: Push notifications targeted only for an iOS App or Android only.

Example Idea -
1. Push Notifications -

![select-message-provider-push](https://github.com/appwrite/appwrite/assets/20625965/4a658a9d-bc30-4c9e-8dd2-1d71d99ce497)

2. Emails -
![select-message-provider-emails](https://github.com/appwrite/appwrite/assets/20625965/eb2efeef-3df5-474e-b712-c6a5b67c667a)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ItzNotABug, thanks for creating this issue! 

When you create a push target, you must specify the provider. When a push message is sent, the provider associated with the push target is used. 

If you want to only send to FCM recipients, it might be best to create a Topic with those targets.
