### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by prexoft** [appwrite/appwrite#7918]
### 👟 Reproduction steps

When I try to implement the Appwrite SDK in my Android app (kotlin)

### 👍 Expected behavior

It throws errors while building,

### 👎 Actual Behavior

On removing the SDK it starts working fine.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

I'm using this library "io.appwrite:sdk-for-android:5.0.0"

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@prexoft, thanks for creating this issue! 🙏🏼 There's not enough information here to troubleshoot and troubleshooting over GitHub would be difficult. It would be best if you created a support post on our [Discord](https://appwrite.io/discord) and include the error logs you're seeing.
