### ISSUE TITLE
🐛 Bug Report: How to access the trafeik dashboard. 

### ISSUE THREAD

**Issue by seczoid** [appwrite/appwrite#7922]
### 👟 Reproduction steps

It installs sucessfully, i see its using trafeik as its proxy manager, how to access its dashboard. 

### 👍 Expected behavior

see the dashboard

### 👎 Actual Behavior

cant see the dashboard

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

i am selfhosting

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by EVDOG4LIFE** [comment]
Hi @seczoid, thanks for submitting!

By default, Traefik stands in the stack to assist with networking. Running the Appwrite install command builds a Docker-Compose file. You can edit that in your installation directory to enable, just keep in mind that if you upgrade Appwrite that you will need to modify the compose file again as it is overwritten.

I recommend reviewing Traefiks documentation on enabling the dashboard here - https://doc.traefik.io/traefik/operations/dashboard/.
