### ISSUE TITLE
Spotify doesn't actually pass scopes to API?

### ISSUE THREAD

**Issue by arodebaugh** [appwrite/appwrite#793]
## 🐛 Bug Report

I was using the Spotify Auth and I passed a few scopes to allow me to get user playback. But I was getting unauthorized errors from the Spotify API. Looking at my network connections the only thing actually passed to the Spotify API scope wise is user-read-email.

## Have you spent some time to check if this issue has been raised before?

Yes I have

## To Reproduce

```
const scopesArray = ['user-read-private', 'user-read-currently-playing', 'user-read-playback-state', 'user-modify-playback-state'];
sdk.account.createOAuth2Session('spotify', redirect_uri, redirect_uri, scopesArray);
```

## Expected behavior

The scopes would pass to the Spotify API.

## Actual Behavior
![Screen Shot 2021-01-01 at 10 43 00 AM](https://user-images.githubusercontent.com/43209194/103441814-79230480-4c1e-11eb-99e4-c98771f97dc2.png)

But it successfully passed to Appwrite with the scopes I wanted:
`http://localhost/v1/account/sessions/oauth2/spotify?success=http://127.0.0.1:5501/suggest.html&failure=http://127.0.0.1:5501/suggest.html&scopes[]=user-read-private,user-read-currently-playing,user-read-playback-state,user-modify-playback-state&project=[redacted]`

## Your Environment

HTML5 + JS connected to a custom Node.js server to get auth key. MacOS Big Sur for running the server. Firefox. Docker AppWrite v:0.6.2.125

**Comment by eldadfux** [comment]
@christyjacob4 this might also be a good time to do some planned refactoring on how custom scopes and OAuth token are working. I was thinking of storing the access token and provider name as part of the session object, and maybe also have a graphic to indicate the session was created using OAuth.

**Comment by christyjacob4** [comment]
![Screenshot 2021-01-02 at 10 36 37 PM](https://user-images.githubusercontent.com/20852629/103462409-fba8e280-4d4a-11eb-933d-9b50c64ace89.png)

@eldadfux @arodebaugh  
I have tried to reproduce this on the 0.7.x branch and I was able to get the requested scopes.
There appears to be some issue in the 0.6.2 branch. I will look into it in depth later.

**Comment by christyjacob4** [comment]
@arodebaugh Can you confirm if this works on the current master branch ? 
If yes let's close this

**Comment by eldadfux** [comment]
Closing for now, we'll re-open if still relevant.
