### ISSUE TITLE
🐛Appwrite URL ERROR: TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by atmikshetty** [appwrite/appwrite#7931]
### 👟 Reproduction steps

I am trying to connect to Appwrite using the URL and ProjectID: 
![image](https://github.com/appwrite/appwrite/assets/109427822/ad3835e7-8157-4796-b04e-ac07ed9bb951)

My .env.local file is also setup correctly On running my application this is the error the console shows: 
![image](https://github.com/appwrite/appwrite/assets/109427822/13acc193-7035-46bd-8f48-b787dc90d5f5)

### 👍 Expected behavior

Should have connected successfully and returned a the New User

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/109427822/13acc193-7035-46bd-8f48-b787dc90d5f5)
Shows that the url is undefined

url used: https://cloud.appwrite.io/v1

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I am using Appwrite 14.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by atmikshetty** [comment]
Thank you and grateful in advance to the ones helping.

**Comment by Satyansh-07** [comment]
i'm working on it. Will return with the solution ASAP.

**Comment by atmikshetty** [comment]
I fixed it. Thanks a lot.
