### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Apoorvgarg-creator** [appwrite/appwrite#7943]
### 👟 Reproduction steps

I simply created a account.
What I did -
1. Logged In with Github
2. Create a project
3. Edited the Project Name
4. Left the Project id as it is
5. Chose Frankfurt as the Region

### 👍 Expected behavior

It showed "null" got created

### 👎 Actual Behavior

I am not sure what should be the actual behaviour but "null" got created can't be the actual behaviour.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Apoorvgarg-creator** [comment]
https://github.com/appwrite/console/issues/1023

I found this issue on appwrite console.

**Comment by ItzNotABug** [comment]
Did you by any chance, pressed the close icon (x) at the top or Back button after clicking on **Create** button?

---
I was able to reproduce it like this -

https://github.com/appwrite/appwrite/assets/20625965/b5577e0c-7f1c-4752-a693-f1c303bd37d8
