### ISSUE TITLE
🐛 Bug Report:  Queries are not working

### ISSUE THREAD

**Issue by BHAVADEEP123** [appwrite/appwrite#7944]
### 👟 Reproduction steps

When I tried to write a equal query it gives me an exception
Here is the snippet:
```
const response = await databases.listDocuments(
      DATABASEID,
      COLLECTIONID_MESSAGES,
      [
        Query.equal('from_user',user.$id),
      ]
    );
```

### 👍 Expected behavior

I should recive some documents but it is not happening

### 👎 Actual Behavior

```
Uncaught (in promise) AppwriteException: Invalid query: {"method":"equal","attribute":"from_user","values":["6615616bc019b68f002b"]}
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

I am using appwrite@13.0.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Hmm, I cannot reproduce this.

---
Also did you by any chance first installed the latest version of the SDK & then rolledback to `13.0.2`? Try deleting the `node_modules` folder & reinstalling the dependencies via `npm install`.

**Comment by ItzNotABug** [comment]
> Hey there 👋
> 
> Appwrite SDK 13.x is meant for Appwrite 1.5.x. You are using Appwite Cloud, which is currently running Appwrite 1.4.
> 
> 
> 
> For now, you can use SDK version 12.x instead to resolve this problem. Once Cloud is upgraded to 1.5, you can start using new features and new SDK version.

Don't the docs for Client SDK say that `13.x` is for `1.4.x` & `14.x` is for `1.5.x`?

**Comment by BHAVADEEP123** [comment]
Btw, everything else is working correctly only with the latest version. Why are these ```queries``` only an issue here?

**Comment by ItzNotABug** [comment]
Can you maybe open a thread on the Appwrite's Discord Server in the **#support** channel? It would be much more quicker to discuss this there.

**Comment by BHAVADEEP123** [comment]
This issue is cleared when I changed my re installed node modules after changing the version to ```13.0.2``` and then cleared npm cache and relaunced my localhost.
Thanks @ItzNotABug  and @Meldiron for reaching out
