### ISSUE TITLE
Can someone help me to solve my error 

### ISSUE THREAD

**Issue by Nihal1203** [appwrite/appwrite#7957]
I am facing Error in my Authentication Service .

<img width="960" alt="e2" src="https://github.com/appwrite/appwrite/assets/118458326/ff82b5ee-4885-44fc-a246-858b610b6ab5">

**Comment by stnguyen90** [comment]
@Nihal1203, thanks for creating this issue! 🙏🏼 If you have not logged in, the error is expected. If you need any additional, feel free to create a support post on [Discord](https://appwrite.io/discord)
