### ISSUE TITLE
🐛 Bug Report: Appwrite console "Client Closed Request" when Create new Project

### ISSUE THREAD

**Issue by TechComet** [appwrite/appwrite#7963]
### 👟 Reproduction steps

login to Appwrite console -> Create new Project

### 👍 Expected behavior

Create new Project without message problem "Client Closed Request"

### 👎 Actual Behavior

Create new Project with message problem "Client Closed Request" !

Appwrite Version 1.5.4

![Screenshot from 2024-04-12 10-05-26](https://github.com/appwrite/appwrite/assets/5288136/6d2d4870-7061-4ac3-b5cb-3c6cc0124909)

install it on fedora 39(with latest update) with docker (localhost) I made old pc as server for Appwrite development and access from ip

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

My Problem when create new project from Appwrite console

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Can't reproduce this on a localhost with `1.5.4`.
What do the network and the docker logs show?

**Comment by TechComet** [comment]
I tried reinstall = same thing
I do delete all Containers and Images and Volumes and try again = all thing work now without problem
Some files may have been corrupted during the first download or due to a weak device

![image](https://github.com/appwrite/appwrite/assets/5288136/2c917dbc-6780-47bd-812c-8db56a87e137)
