### ISSUE TITLE
🐛 Appwrite Storage: Misleading Error Message During Role Permission Update

### ISSUE THREAD

**Issue by Sthabiraj** [appwrite/appwrite#7964]
### 👟 Reproduction steps

1. Log in to an Appwrite project with a user account.
2. Navigate to the "Storage" section and attempt to edit the permissions for a role.
3. Try to modify any role permission (e.g., grant "read" access).
4. Save the permission changes.

### 👍 Expected behavior

The permission update for the selected role should be successful, regardless of any file size limits associated with the current plan.

### 👎 Actual Behavior

An error message appears stating: "Maximum file size limit you are trying to set is above the limit allowed for your plan. Upgrade to a higher plan to increase the limit." This message is misleading as it suggests a connection between permission updates and file size limits, which shouldn't be the case.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
Duplicate - #7682.
Please 👍 the linked issue.

**Comment by priyankuhazarika** [comment]
I encountered this issue too
