### ISSUE TITLE
📚 Documentation: JWT doesn't work

### ISSUE THREAD

**Issue by suntochukwu** [appwrite/appwrite#7965]
### 💭 Description

Back end api for sign in using email and password. I'm trying to add in JWTs but i get error:  
[1] User (role: guests) missing scope (account) 

the api is below.
I saw a similar issue that just didnt bother to explain a solution; they mention curl and closed the request. I feel like what im doing should be very simple.
```

@app.post("/api/login", status_code=status.HTTP_200_OK)
async def login( credentials : logincred ):
  try: 
   email, password = credentials.email, credentials.password
   response = account.create_email_password_session(email, password)
   token= account.create_jwt()
   print(response)
   print(token)

   
   return {'response': response } 

  except Exception as e:   
     print(e)
     
     raise HTTPException(status_code= status.HTTP_403_FORBIDDEN , detail='invalid username or password')  # Return an appropriate error status code
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@stnguyen90, thanks for creating this issue! 🙏🏼 Are you using Appwrite Cloud? If so, these methods are for Appwrite 1.5, but Appwrite Cloud is on version 1.4.13 (You can see the version of Appwrite at the bottom right of the Appwrite Console. In addition, it's best to always check the [README](https://github.com/appwrite/sdk-for-python/blob/5.0.2/README.md?plain=1#L9) for the version of the SDK you're installing to see what version of Appwrite it's for.). If your Appwrite instance is version 1.5.0 or above. refer to the [SSR docs](https://appwrite.io/docs/products/auth/server-side-rendering) for how to authenticate a user
