### ISSUE TITLE
ClamAV network path is currently harcoded

### ISSUE THREAD

**Issue by silentworks** [appwrite/appwrite#797]
## 🐛 Bug Report

Currently if you should change the value of your clamav services in the docker-compose.yml to anything other than clamav it will break the file uploading mechanism. This is because the clamav value is hardcoded inside of [storage.php](https://github.com/appwrite/appwrite/blob/master/app/controllers/api/storage.php#L201), this should be setup as an environment variable so that it can be changed. In my instance of using Appwrite with [caprover](https://github.com/caprover/one-click-apps/pull/340), it is recommended that you namespace the services with the appname as you can have multiple instances setup on a single caprover install.

## Have you spent some time to check if this issue has been raised before?

Yes I have and there is none.

## To Reproduce

Rename clamav service in the docker-compose.yml to anything else then try to upload a file from inside the Appwrite UI.

## Expected behavior

File upload to be successful

## Actual Behavior

Got hit with an error and the following output when development mode is turned on.

```
{
    "message": "Unable to connect to ClamAV server",
    "code": 0,
    "file": "\/usr\/share\/nginx\/html\/vendor\/appwrite\/php-clamav\/src\/ClamAV\/Network.php",
    "line": 44,
    "trace": [
        {
            "file": "\/usr\/share\/nginx\/html\/vendor\/appwrite\/php-clamav\/src\/ClamAV\/ClamAV.php",
            "line": 25,
            "function": "getSocket",
            "class": "Appwrite\\ClamAV\\Network",
            "type": "->"
        },
        {
            "file": "\/usr\/share\/nginx\/html\/vendor\/appwrite\/php-clamav\/src\/ClamAV\/ClamAV.php",
            "line": 86,
            "function": "sendCommand",
            "class": "Appwrite\\ClamAV\\ClamAV",
            "type": "->"
        },
        {
            "file": "\/usr\/share\/nginx\/html\/app\/controllers\/api\/storage.php",
            "line": 205,
            "function": "fileScan",
            "class": "Appwrite\\ClamAV\\ClamAV",
            "type": "->"
        },
        {
            "function": "{closure}"
        },
        {
            "file": "\/usr\/share\/nginx\/html\/vendor\/utopia-php\/framework\/src\/App.php",
            "line": 401,
            "function": "call_user_func_array"
        },
        {
            "file": "\/usr\/share\/nginx\/html\/app\/app.php",
            "line": 430,
            "function": "run",
            "class": "Utopia\\App",
            "type": "->"
        },
        {
            "file": "\/usr\/share\/nginx\/html\/public\/index.php",
            "line": 27,
            "args": [
                "\/usr\/share\/nginx\/html\/app\/app.php"
            ],
            "function": "include"
        }
    ],
    "version": "0.6.2"
}
```

**Comment by eldadfux** [comment]
This is now fixed on `0.7.x` branch and will be released with v0.7.0

**Comment by silentworks** [comment]
This feels like it should have been a 0.6.3 release since its a non-breaking change and could have been released sooner than waiting on 0.7.0.

**Comment by eldadfux** [comment]
@silentworks you're 100% right, due to capacity on the team we might be able to release only 0.7 or 0.7 and 0.6.3 at the same time 😞.

**Comment by eldadfux** [comment]
Version 0.7 has been released with new ENV vars to support changing the ClamAV host and port: https://appwrite.io/docs/environment-variables#storage

> @silentworks there is a minor bug we found after release, and beside updating the values in the .env file you also have to add the var keys in the docker-compose.yml -> this is already fixed on the master setup script.
