### ISSUE TITLE
🐛 Bug Report: Pending migration when migrating to Appwrite Cloud

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#7974]
### 👟 Reproduction steps

1. Go to Appwrite Cloud
2. Create a project
3. Got Settings > Migrations > Import Data
4. Fill in the details and start the import/migration

### 👍 Expected behavior

The data is imported

### 👎 Actual Behavior

Migration is stuck at pending:

<img width="1478" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/0e4dbc30-f761-48ca-a897-9c83b4ad2e57">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Tomic-Riedel** [comment]
I have the exact same problem.

**Comment by tripolskypetr** [comment]
The only way to solve that problem is` json-per-document` backup of the cloud, then restore to self-hosted instance. The [appwrite-backup-tool](https://github.com/react-declarative/appwrite-backup-tool) will solve your problem

**Comment by stnguyen90** [comment]
Migrations are no longer pending on Cloud. You may need to recreate a migration, though.
