### ISSUE TITLE
🐛 Bug Report: I can't add an attribute or delete..

### ISSUE THREAD

**Issue by subhaschandrashow** [appwrite/appwrite#7988]
### 👟 Reproduction steps

I can't add an attribute to any table..I read other issue in github similar, where it seemed to be it would be fixed automatically. But it now more than 2 days..
![appwrite-issue](https://github.com/appwrite/appwrite/assets/11705894/933a0c99-3e81-43f6-bedc-cc59aff2fb4a)

### 👍 Expected behavior

is it some limitation in my account?

### 👎 Actual Behavior

It should add attributes

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Something else

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by prateekcode** [comment]
I'm facing the same issue. I was adding a new feature to my app with Appwrite, and now this issue has halted my development.

**Comment by stnguyen90** [comment]
@prateekcode, thanks for creating this issue! 🙏🏼 There's an ongoing [incident](https://status.appwrite.online/incident/356801) for attributes and functions. Please follow the incident for updates.
