### ISSUE TITLE
🐛 Bug Report: Queries don't accept empty string

### ISSUE THREAD

**Issue by mauricev** [appwrite/appwrite#7994]
### 👟 Reproduction steps

The following query throws an exception
```
List<String>? genoTypeQuery = [
      Query.notEqual("genotype", [""]) // empty string brings back all genotypes
    ];
```
genotype is a string attribute

### 👍 Expected behavior

It worked in 1.4.x.

### 👎 Actual Behavior

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: AppwriteException: general_query_invalid, Invalid query: Query value is invalid for attribute "genotype" (400)
```

Discord thread: https://discord.com/channels/564160730845151244/1226743448292294656

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.5.4, SDK is 12.0.1.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@mauricev, thanks for creating this issue! 🙏🏼 I think returning all genotypes may have been a bug. I think the correct behavior should be that it returns everything where genotype is not an empty string.

**Comment by abnegate** [comment]
@mauricev Please try with `Query.notEqual("genotype", "")`, not equal queries only accept a single value

**Comment by mauricev** [comment]
I suggest documenting changes in a dedicated release notes for new versions.

The current documentation still reflects 1.4.x's way of using an array: https://appwrite.io/docs/products/databases/queries.

Also, why was this changed? Why can't we no longer use an array?
