### ISSUE TITLE
createEmailSession has been superseded 

### ISSUE THREAD

**Issue by mauricev** [appwrite/appwrite#7995]
### 👟 Reproduction steps

Attempt to use the function createEmailSession under 1.5.4/12.0.1. The documentation at https://appwrite.io/docs/references/cloud/client-web/account#createEmailSession should be updated to reflect the new name for this function, createEmailPasswordSession.

### 👍 Expected behavior

It should be recognized.

### 👎 Actual Behavior

It isn't recognized.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@mauricev, thanks for creating this issue! 🙏🏼 It depends on the version of Appwrite you're working with. The docs you linked are for Appwrite Cloud which is on 1.4.13. If you're on Appwrite 1.4, you should look at the 1.5 docs, where you'll find the [`createEmailPasswordSession()` method](https://appwrite.io/docs/references/1.5.x/client-web/account#createEmailPasswordSession).

**Comment by mauricev** [comment]
This then ought to be addressed. The main docs page brings up the outdated cloud docs. and there is no mention there are version-specific docs. I have been using Appwrite for a year and I didn't know this. Nor do I see it mentioned anywhere that there was this change in the API in any release note.
