### ISSUE TITLE
🐛 Bug Report:  500 Internal Error

### ISSUE THREAD

**Issue by rhyno3117** [appwrite/appwrite#7998]
### 👟 Reproduction steps

When I go into my app and into the Storage, when I try to get into one of my files, I get this 500 internal error. I have restarted, refreshed constantly and still am getting this error.

### 👍 Expected behavior

Open my file so I can go into its settings.

### 👎 Actual Behavior

500 Internal Error

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Please share more information, your projects ID, or problematic file.
