### ISSUE TITLE
🐛 Bug Report: Function Not Deleted Instantly Causing a Restore

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#7999]
### 👟 Reproduction steps

Assuming you have a Function in your Project.

---
1. Go to your Function > Copy the Function ID
2. Go to Settings Tab > Scroll Down to Delete
3. Confirm Function Deletion & Proceed to Click `Delete`

---
1. Create a New Function > Manual
2. Add any name you like > Paste the `ID` of the deleted function
3. Upload a `code.tar.gz`, configure entrypoint, build commands same as the deleted one
4. Click `Next` & set the Execution permissions
5. Click `Create`, you will be navigated to the functions screen with previous data like deployments, etc.

---
See -

https://github.com/appwrite/appwrite/assets/20625965/82dc1653-b63d-4bf7-b4cf-e924e7e02902

---
Note that this doesn't happen all the time.

### 👍 Expected behavior

No previous data is restored.

### 👎 Actual Behavior

Previous data is restored

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ItzNotABug, thanks for creating this issue! 🙏🏼 It looks like we're looking up the deployments using the function id:

https://github.com/appwrite/appwrite/blob/c7bdcda59371f2b4db92a45ef0f7ba430a150792/app/controllers/api/functions.php#L1285-L1286

However, we should be using the internal id:

https://github.com/appwrite/appwrite/blob/c7bdcda59371f2b4db92a45ef0f7ba430a150792/app/config/collections.php#L3133-L3139

**Comment by stnguyen90** [comment]
@ItzNotABug, assigned! Thanks for your interest!
