### ISSUE TITLE
🚀 Enhancement: Missing Country for Locale endpoint -- `Palestine`

### ISSUE THREAD

**Issue by xuelink** [appwrite/appwrite#8003]
### 🔖 Enhancement description

Adding a new country "Palestine" according to https://www.iso.org/obp/ui/#iso:code:3166:PS

### 🎤 Pitch

Hey everyone

One of our users has recently raised an issue regarding the selection of their country within the app. They have expressed a desire to see Palestine added to the list of available countries.

As per the conversation provided by the user, they have expressed their concern about not being able to select Palestine. They have also mentioned that they understand the complexities involved in adding a new country to the app and have kindly requested any updates or insights into the progress of this issue.

Our user's satisfaction is of utmost importance to us, and we strive to address their concerns promptly. Therefore, I would like to inquire if there are any plans or timelines in place for the addition of Palestine to the countries list. Additionally, if there are any updates or progress regarding this matter, we would appreciate being kept informed so that we can provide our user with the necessary information.

Thank you for your attention to this matter and for your commitment to improving the user experience of the app. We look forward to your response and the potential inclusion of Palestine in the countries list.

Best

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by xuelink** [comment]
Could you please assign this issue to me? I intend to address it in a similar manner to how I handled the `Taiwan` with this PR https://github.com/appwrite/appwrite/pull/7873

**Comment by stnguyen90** [comment]
@xuelink, assigned! Thanks for your interest! 🙏🏼
