### ISSUE TITLE
DioError [DioErrorType.RESPONSE]: Http status error [401], but I am authorized

### ISSUE THREAD

**Issue by klnfreedom** [appwrite/appwrite#801]
Hello, I have some problem with create a document on appwrite (flutter web), when I start the process for creation, I have an error: DioError [DioErrorType.RESPONSE]: Http status error [401].
But I am authorized.
And I can read a document from appwrite, but I can't create a document to appwrite
Thats a part of code of creation document:

Future uploadDataToAppwrite(GasStationFromTransnet data) async {
var qwert = jsonEncode(data.toJson());
try {
Response response = await database.createDocument(
collectionId: AppConstants.collection,
data: data.toJson(),
read: [""],
write: [""],
);
print(response);
return true;
} catch (e) {
print(e);
return false;
}
}
Response is null.

Please help

---
Appwrite Version: 0.6.2.125

**Comment by eldadfux** [comment]
Before creating documents you need to authenticate your user by creating an account, and then an account session.

**Comment by klnfreedom** [comment]
{"$id":"5ff46a34a631f","type":1,"expire":1641389492}
[GETX] "GetMaterialController" has been initialized
[GETX] GOING TO ROUTE /home
[GETX] "HomeController" has been initialized
DioError [DioErrorType.RESPONSE]: Http status error [401]
false

I made it, but not working, how can I fix it?

**Comment by klnfreedom** [comment]
The same error

**Comment by klnfreedom** [comment]
I'm authenticated, but the same error

**Comment by eldadfux** [comment]
Make sure your collection has write permissions for that user, `*` can be a good value for testing

**Comment by klnfreedom** [comment]
When I want to create document, I need to take json code from collection or from the document?

**Comment by eldadfux** [comment]
@klnfreedom not sure I understand the question. Do you have a wildcard permission in your collection settings?

![image](https://user-images.githubusercontent.com/1297371/103653040-9cc2b380-4f6c-11eb-98c5-ee2fb1c6c8a4.png)

**Comment by klnfreedom** [comment]
Yes, I have a wildcard permission in write access and read accsess too

**Comment by klnfreedom** [comment]
When I want read document from appwrite, I can do it, but when I want to create document to appwrite, I can't do it. What I need to do? Create session is success but I can' to write.

**Comment by klnfreedom** [comment]
try {
      Response response = await database.createDocument(
        collectionId: AppConstants.collection,
        data: data.toJson(),
        read: ["*"],
        write: ["*"],
      );
      print(response);
      return true;
    } catch (e) {
      print(e);
      return false;
    }
  }
It's a part of my code for creating

**Comment by klnfreedom** [comment]
what am I doing wrong?

**Comment by klnfreedom** [comment]
I can't get session, because I get the same error
[GETX] "GetMaterialController" has been initialized
[GETX] GOING TO ROUTE /home
[GETX] "HomeController" has been initialized
{"$id":"5ff48213a6a04","type":1,"expire":1641395603} - init client()
DioError [DioErrorType.RESPONSE]: Http status error [401] - getSession
DioError [DioErrorType.RESPONSE]: Http status error [401] - try to create document

**Comment by eldadfux** [comment]
@klnfreedom you need to use createSession not getSession

**Comment by klnfreedom** [comment]
initClient it is a method which is included createSession();

It is very interesting, I can create session and I get id of client, but when I want to getSession, I give DioException Http 401

And when I want to create document I get the same problem

**Comment by eldadfux** [comment]
@klnfreedom are you testing this on Flutter Web?

**Comment by klnfreedom** [comment]
Yes, I tested, but I have the same error

**Comment by eldadfux** [comment]
@klnfreedom sorry for all the questions, but I just want to be sure I understand the problem scope. This error happens to your only on web or web+ios+android?

**Comment by klnfreedom** [comment]
Everythhing is cool, thank you for support

**Comment by Macdeo** [comment]
How did you fixed this issue @klnfreedom

**Comment by klnfreedom** [comment]
> How did you fixed this issue @klnfreedom 

https://github.com/appwrite/sdk-for-flutter/issues/5

**Comment by Macdeo** [comment]
Thanks

**Comment by lohanidamodar** [comment]
I think it's safe to close this issue as it is for now resolved by 
https://github.com/appwrite/sdk-for-flutter/issues/5
Feel free to reopen if it is not resolved for you, or continue discussion in https://github.com/appwrite/sdk-for-flutter/issues/5.
