### ISSUE TITLE
[ Feature Request ] Adjacency List Relationships

### ISSUE THREAD

**Issue by mlaradji** [appwrite/appwrite#803]
## 🚀 Feature

One of the database field types is `document[]`, which allows a document to have a reference or list of references to documents in other collections. As far as I can tell, documents can only refer to documents in other collections. It would useful to allow a document to reference a document in the same collection; this is sometimes called an adjacency list relationship (https://docs.sqlalchemy.org/en/14/orm/self_referential.html).

## Have you spent some time to check if this issue has been raised before?

This issue does not seem to have been raised before. Through curl, I inserted into an existing collection with id A a new field of type document[] with allowed collection id A. The PUT request was successful. However, attempting to insert or update documents in the collection now fails, whether done through the Admin UI or through curl.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes, I have.

## Pitch

Self-reference is useful when there is a need to have relationships between documents of the same type. For example, say I'm making an online grocery store. I have two categories, drinks and food, each food can be either dry food or wet food, and dry food can be cereal or rice. I want my category database to look something like this:
- cereal
- rice
- wet food
- dry food
  | various fields
  |
  -- children:
     - reference to 'cereal'
     - reference to 'rice'
- drinks
- food
  | various fields
  |
  -- children:
     - reference to 'dry food'
     - reference to 'wet food'

**Comment by eldadfux** [comment]
@mlaradji how would you approach a recursion where one document is referencing itself directly or indirectly from another nested document of the same type? My fear is that this can result in an endless loop that will eventually crash the server.

**Comment by mlaradji** [comment]
@eldadfux Hmm. When adding a new reference field, we could attempt to detect cycles in the new resulting json schema before accepting the change. Or we could have a recursion limit but that may lead to more problems.

How is it currently handled for different collections? Is it possible to have collection A reference collection B which references collection A?

**Comment by eldadfux** [comment]
Closing in favor of #2735
