### ISSUE TITLE
🐛 Bug Report: Realtime got disconnected

### ISSUE THREAD

**Issue by dj-fiorex** [appwrite/appwrite#8037]
### 👟 Reproduction steps

When i use realtime to listen to database i get this error:
```
WebSocket connection to 'wss://cloud.appwrite.io/v1/realtime?project=<project>&channels%5B%5D=databases.6623e3aa881153ccd832.collections.orders.documents.662b7dbd6748895df4a6' failed: 
Realtime got disconnected. Reconnect will be attempted in 1 seconds. 
```
The same code was working till two days ago. 
I'm connected to AppWrite Cloud with starter free plan.
The project is a simple vite + react project, the interesting parti is this:
```
FILE Test.tsx

import { useEffect } from 'react';
import { subscribeToOrder } from '../backend';

export const TestCmp = () => {
  useEffect(() => {
    const unsubOrder = subscribeToOrder('662b7dbd6748895df4a6', (order) => {
      console.log('order changed: ', order);
    });
    return () => {
      console.log('Unmounted Home');

      if (unsubOrder) {
        console.log('unsub');
        unsubOrder();
      }
    };
  }, []);

  return (
    <div>
      <h1>Test</h1>
    </div>
  );
};



FILE backend.ts

import { Client, Storage, Account, Databases, Models, ID, Permission, Role, Query } from 'appwrite';

export const client = new Client();

client.setEndpoint('https://cloud.appwrite.io/v1').setProject('<projectID>'); // Replace with your project ID

export const account = new Account(client);
export const db = new Databases(client);
export const storage = new Storage(client);

const databaseID = '<dbID>';
const bucketID = '<bucketID>';
const excelFileID = 'template-excel';
export { ID } from 'appwrite';

type OrderDocument = Order & Models.Document;
type OperatorDocument = Operator & Models.Document;
type TestDocument = Test & Models.Document;

export const subscribeToOrder = (orderId: string, callback: (order: Order) => void) => {
  return client.subscribe<OrderDocument>(
    `databases.${databaseID}.collections.orders.documents.${orderId}`,
    (response) => {
      // Callback will be executed on changes for documents A and all files.
      console.log('collections.orders.documents', response);
      callback({ ...response.payload, id: response.payload.$id });
    }
  );
};

```

### 👍 Expected behavior

Connect and listen to realtime events from the server.

### 👎 Actual Behavior

```
WebSocket connection to 'wss://cloud.appwrite.io/v1/realtime?project=<project>&channels%5B%5D=databases.6623e3aa881153ccd832.collections.orders.documents.662b7dbd6748895df4a6' failed: 
Realtime got disconnected. Reconnect will be attempted in 1 seconds. 
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

"appwrite": "^13.0.2",
"react": "^18.2.0",

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

One issue that i found is this #1640 but it talks about a self hosted instance of AppWrite, so this is not my use case

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
If this was working around 2 days ago, its possible this is due to Cloud's update to `1.5.5`.
Can you try using the latest sdk version for web `14.0.1`?

**Comment by stnguyen90** [comment]
@dj-fiorex, thanks for raising this issue! 🙏🏼 I have seen some instability with realtime lately. I don't think it's a Cloud-only problem, but I think it's more apparent on Cloud due to the load. I think it's due to the concurrent connections causing conflicts/problems and improving that is going to take significant changes 😕

**Comment by cwwngwphqn** [comment]
@stnguyen90 Do you have any news regarding that by chance? By now, the realtime connections always fail in my project hosted on cloud.

**Comment by stnguyen90** [comment]
@cwwngwphqn, we're still working on it.

**Comment by cwwngwphqn** [comment]
It is working for me again 🙏

**Comment by cwwngwphqn** [comment]
Unfortunately now not anymore 😢

**Comment by stnguyen90** [comment]
@dj-fiorex what exactly is happening now?

**Comment by dj-fiorex** [comment]
Same thing of the first post, 
Realtime got disconnected

Is there a way to know in my code that websocket disconnected? So I could reload the page?

Now I'm trying to self-host Appwrite to check if it will do the same thing or is the cloud instance the problem

**Comment by dj-fiorex** [comment]
Guys i can confirm that with a self-hosted instance of AppWrite Realtime works like a charm!
