### ISSUE TITLE
🐛 Bug Report: Wrong version number in response (Appwrite v1.5.5)

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#8039]
### 👟 Reproduction steps

Wrong version number in response.

### 👍 Expected behavior

The response should have a correct version number.

![Screenshot 2024-04-29 at 6 22 56 PM](https://github.com/appwrite/appwrite/assets/18592683/e78d8f12-2ebf-4acd-8f09-8b8bc1dfd2c1)

### 👎 Actual Behavior

The response had the wrong version number.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@usamashafiqs, thanks for raising this issue! 🙏🏼 The version in that API response is Cloud's version, but I can see how that can be confusing for developers. Let me talk to the team about this.
