### ISSUE TITLE
📚 Documentation: Getting Started Links in Readme not valid

### ISSUE THREAD

**Issue by BtheGit** [appwrite/appwrite#8040]
### 💭 Description

Looks like the getting started links in the readme are linking to non-existent folders in the main repo (eg, https://github.com/appwrite/appwrite/blob/main/docs/quick-starts/web) because they are using relative URLs instead of linking to the hosted docs pages. None of the links work anymore.

Change was introduced in this commit https://github.com/appwrite/appwrite/commit/ba7fefc9641d2459619a49474bffdae1a9925cb8 .

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@BtheGit thanks for creating this issue! 🙏🏼 Ya, these should definitely be absolute URLs pointing to our website like `https://appwrite.io/docs/quick-starts/web`.

**Comment by stnguyen90** [comment]
@BtheGit, assigned! Thanks for your interest! 🙏🏼
