### ISSUE TITLE
🐛 Bug Report: File status counter not updating

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#8043]
### 👟 Reproduction steps

1. Create a [migration](https://appwrite.io/docs/advanced/migrations) that includes multiple files where 1 is bigger than 5MB (not sure if the file size matters

### 👍 Expected behavior

After the migration is complete, the files processing count should be 0

### 👎 Actual Behavior

The processing count stays at 1:

<img width="950" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/1c3205b6-d3bc-4a30-9176-b7b4ee4e2e29">

Discord thread: https://discord.com/channels/564160730845151244/1233808207055552563/1234548836832378950

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by raman04-byte** [comment]
I have experienced this

**Comment by stnguyen90** [comment]
Pending migration version bump

**Comment by stnguyen90** [comment]
Bumped as part of https://github.com/appwrite/appwrite/pull/8167
