### ISSUE TITLE
My Usage is 0%, but I get an error for Limit exceeded. Could you repair and open my limitations?

### ISSUE THREAD

**Issue by mehmetakar17** [appwrite/appwrite#8053]
Hi,

My Usage is 0%, but I get an error for Limit exceeded. Could you repair and open my limitations?

I get en error while trying to log in with the first and only user which I created for my react native tutorial Aora app from jsmastery.pro channel (Youtube)

The error says:

AppwriteExxception: Bandwith limit for your organization has exceeded. Please upgrade to higher plan or update budget.

But as you see below, bandwith and other usage is %0 :) How can it be possible? Could you repair my limitation issue?

![Screenshot-appwrite-limit-3](https://github.com/appwrite/appwrite/assets/166406477/c0de91b8-7cd4-46cb-b029-b9f26a41ce80)
![Screenshot-appwrite-limit-2](https://github.com/appwrite/appwrite/assets/166406477/a0095f57-3b32-4417-bb95-441bf3b9c524)
![Screenshot-appwrite-limit-1](https://github.com/appwrite/appwrite/assets/166406477/8affa0d2-4003-4a8b-8e2b-742e2a03712b)

**Comment by stnguyen90** [comment]
@mehmetakar17, thanks for raising this issue! 🙏🏼 Would you please provide your project ID or organization iD?

**Comment by mehmetakar17** [comment]
Thanks for the reply:

My user url: https://cloud.appwrite.io/console/organization-171717

My user or organization id : 171717 (I manually set up while signing up)

The recent project id is : 662bc24e001bfee15e49

My user email:  mehmetakar17@gmail.com

**Comment by stnguyen90** [comment]
@mehmetakar17, I checked your org and I don't see any limits. Would you please share more details about the error you're receiving. Exact request and response and/or screenshots would be helpful.
