### ISSUE TITLE
Combining whitelist strategies

### ISSUE THREAD

**Issue by silentworks** [appwrite/appwrite#806]
## 🚀 Feature

Combine whitelist strategies.

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

Sometimes in a company, you want to have the strategy set to domain, but you might also want to allow certain email addresses from a different domain to be able to sign up. Being able to combine DOMAIN/EMAIL and IP/EMAIL strategy would allow for this.

**Comment by TorstenDittmann** [comment]
Since we have removed the DOMAIN env variable for security reasons - this is not relevant anymore 👍🏻
