### ISSUE TITLE
🐛 Bug Report: Double typo in credit card enum

### ISSUE THREAD

**Issue by iron3oxide** [appwrite/appwrite#8062]
### 👟 Reproduction steps

Looking at the OpenAPI / Swagger specs and the code generated with it, I noticed that "cencosud" was misspelled as "censosud", which was then again misspelled as "consosud". I'd put a PR in myself but unfortunately I don't yet understand how the specs are generated.

### 👍 Expected behavior

It should say "cencosud" everywhere

### 👎 Actual Behavior

See above

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@iron3oxide, thanks for creating this issue! 🙏🏼 There are a couple places where this needs to be updated:

1. https://github.com/appwrite/appwrite/blob/a30d06bc585390658f2ef6677267756852c9a44e/app/config/avatars/credit-cards/censosud.png
2. https://github.com/appwrite/appwrite/blob/a30d06bc585390658f2ef6677267756852c9a44e/app/config/avatars/credit-cards.php#L7
