### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by tharunc** [appwrite/appwrite#808]
Hello there,
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of **DWOC**. Please assign me this issue. 
For reference, kindly check out: https://github.com/apps/welcome
THANK YOU

**Comment by Glide7** [comment]
Hey @tharunc , 
Thanks for this suggestion! 

For now, we want to keep Appwrite "bot free" especially when it comes to communicating with people :) 
It's something that we are looking forward to do in the future though, so we'll keep you posted!
