### ISSUE TITLE
AppwriteException: Database not found

### ISSUE THREAD

**Issue by rudransh61** [appwrite/appwrite#8115]
### 👟 Reproduction steps

```js
const client = new Client();

  client
    .setEndpoint('https://cloud.appwrite.io/v1')
    .setProject('PROJECT_ID');

  const databases = new Databases(client);

....

const promise = databases.createDocument(
        'DATABASE_ID', // databaseId
        'COLLECTION_ID', // collectionId
        ID.unique(),
        {
          "name": nickname,
          "score": guessedCountries.size,
        }
      );
      
      promise.then(response => {
        console.log('Document created:', response);
      }).catch(error => {
        console.error('Error creating document:', error);
      });
```

its not working ? 
I had checked everywhere ?
whats the error ?

in permissions , i have permitted everyone for create and read ...

ERROR :

![image](https://github.com/appwrite/appwrite/assets/115872354/a6885cca-7a67-43e6-baf1-c428e54014a6)

### 👍 Expected behavior

it should work

add a document in my collection

### 👎 Actual Behavior

throwing some error

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

```json
{
  "name": "app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "appwrite": "^14.0.1",
    "axios": "^1.6.8",
    "dotenv": "^16.4.5",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@vitejs/plugin-react": "^4.2.1",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.57.0",
    "eslint-plugin-react": "^7.34.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.6",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.3",
    "vite": "^5.2.0"
  }
}
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by SafakB** [comment]
I think, this is not a bug

Are you using Server SDK? If so, are you doing it without defining API key?
For Server SDK side operations, you need to define the “setKey” parameter to the client object. I did not see it in your code.

**Like this**

```javascript
const client = new sdk.Client()
    .setEndpoint('https://cloud.appwrite.io/v1') // Your API Endpoint
    .setProject('5df5acd0d48c2') // Your project ID
    .setKey('919c2d18fb5d4...a2ae413da83346ad2'); // Your secret API key
```

You are using Client SDK 
Client SDK Method List 
https://appwrite.io/docs/references/cloud/client-web/databases

Server SDK Method List
https://appwrite.io/docs/references/cloud/server-nodejs/databases

Someone correct me if I am wrong :)

**Comment by Tanu1201** [comment]
Hey, I am Tanu sharma I have 2+ year exp in software development field, I am starting my open source journey, I have gone through this can I take this?

**Comment by rudransh61** [comment]
ok , but pls help me

**Comment by stnguyen90** [comment]
@rudransh61, thanks for creating this issue! 🙏🏼 Please make sure your project, database, and collection IDs are correct. If you're still having troubles, please create a support post on our [Discord](https://appwrite.io/discord) with all the details as that is a better place to troubleshoot.
