### ISSUE TITLE
🐛 Bug Report: SMS Sending via TextMagic stuck at "processing" status

### ISSUE THREAD

**Issue by nikkyeya-jsm** [appwrite/appwrite#8131]
### 👟 Reproduction steps

Im using cloud with node-sdk.
- Add TextMagic as the SMS provider.
- Add userId to identify which phone to send to.
- Use the createSms function to send an SMS.

` const message = await messaging.createSms(
      ID.unique(),
      content,
      [],
      [userId]
    );`

I also reported this in discord, tested some scenario with Steven and he was able to confirm that this is a bug with Textmagic.

### 👍 Expected behavior

The SMS should be marked as "Sent" and I should be able to receive it.

### 👎 Actual Behavior

It gut stuck at "processing" in appwrite console and I did not receive the sms.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

node-appwrite: "^12.0.1"

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This should be fixed on cloud now.
