### ISSUE TITLE
🐛 Bug Report: Expired targets not automatically deleted

### ISSUE THREAD

**Issue by ayushpathak-48** [appwrite/appwrite#8159]
### 👟 Reproduction steps

Go to console 

Create  FCM provider for push messaging 

Create a token of a device and save it into appwrite

Then re create the token and again save it to appwrite

Then send notification to the web target 

Then you will get an error for the expired device token

Again after 1 day th same error occurs.

But appwrite says it should be removed after a days if it's expired

### 👍 Expected behavior

It should be removed

### 👎 Actual Behavior

It's giving same errror everyday

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I am using node-appwrite to create push target and for creating push notification 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Related thread: https://discord.com/channels/564160730845151244/1241034854922063954

**Comment by ItzNotABug** [comment]
@stnguyen90 is this issue open for assignment?

**Comment by stnguyen90** [comment]
@ItzNotABug, sure, ya. Assigned!
