### ISSUE TITLE
RactNative--500 error

### ISSUE THREAD

**Issue by ITGMyang** [appwrite/appwrite#8160]
**ReactNative Problem**
Error response: {"code": 500, "message": "Server Error", "type": "general_protocol_unsupported", "version": "0.13.26"}

**Comment by stnguyen90** [comment]
@ITGMyang, thanks for creating this issue. Unfortunately, this is very little for us to go off of. Please create a support post on our [Discord](https://appwrite.io/discord) as it would be easier to troubleshoot their and provide additional context/detail like:

1. Project ID
2. Code
