### ISSUE TITLE
📚 Documentation: Support manual deployment

### ISSUE THREAD

**Issue by jack9603301** [appwrite/appwrite#8181]
### 💭 Description

Yesterday, I officially started to provide appwrite deployment services to customers. At the beginning, I chose 1-minute deployment (using docker) because it was the fastest and I was busy at the time. Later, the customer asked how to do database backup of this thing, whether it was convenient and safe. Then I thought about the following, I am still used to lxd (I have been providing lxd-based deployment for customers before, and the customer and I think it is easy to use), and the maintenance of lxd , The backup migration program is quite easy, and can easily perform data backup and migration of stateful containers. I reviewed Docker and docker-compose.yaml and thought it would work, so I decided to start this new deployment today. Just after I did everything, I found that port 80 could not return data. I didn't know what I did wrong. I saw a line of instructions from Docker - copy app/console/build to console. I think I made a mistake. Make corrections. This deployment took relatively longer than expected. I worked for the customer for a full 4 hours, although it was still within the normal range. I think it's worth sinking this experience now and maybe we can improve the documentation to guide others on how to deploy them manually?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@jack9603301, thanks for raising this issue! 🙏🏼 We document a more manual approach [here](https://appwrite.io/docs/advanced/self-hosting#manual). What else were you looking for?
