### ISSUE TITLE
🚀 Enhancement: Add "unique" option for (integer) attributes

### ISSUE THREAD

**Issue by iron3oxide** [appwrite/appwrite#8208]
### 🔖 Enhancement description

I propose to add an option to the creation of attributes that ensures that each value in its column is unique or even (in the case of integers, which would be my use case) auto-incrementing.

### 🎤 Pitch

While not needed for primary keys here, it can be very helpful to have the database ensure that there can never be two identical values in a column. In my use case, I need to add a user-friendly "ID" to my collection.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
No worries! We appreciate the feedback! 🙏🏼
