### ISSUE TITLE
🐛 Bug Report: File preview endpoint flips image

### ISSUE THREAD

**Issue by Andree98** [appwrite/appwrite#8209]
### 👟 Reproduction steps

I have this image that is normal when using the file view endpoint and flipped when using the file preview endpoint

File view:
https://cloud.appwrite.io/v1/storage/buckets/6603d55cba54c384dd55/files/6603d565014591781c7a/view?project=65fae85dcbef6b0998bf

File preview:
https://cloud.appwrite.io/v1/storage/buckets/6603d55cba54c384dd55/files/6603d565014591781c7a/preview?project=65fae85dcbef6b0998bf

Some info:

- I can only reproduce with this specific image, other images are ok
- This only started happening to this image in version 1.5, this specific image is ok in previous versions

### 👍 Expected behavior

It should not flip the image in the preview endpoint unless specified

### 👎 Actual Behavior

The image is flipped

Related thread:

 https://discord.com/channels/564160730845151244/1220007527626964992

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Uploading here just in case: 
![Uploading image_picker_B62D9407-C846-4815-956F-177FEF289B8F-25625-00000060BB59EDAA.jpg…]()

**Comment by stnguyen90** [comment]
Hmm this might be an iOS bug 🧐

https://discussions.apple.com/thread/255553292?sortBy=best

**Comment by Andree98** [comment]
What's confusing me is the fact that this is not reproducible in versions prior to 1.5. So something must have changed in regards to how Appwrite handles images?

**Comment by puntiz** [comment]
I can see in Appwrite code where it check the Orientation Exif and it only deals with rotation (left, right and down) and ignores other kinds of Exif orientations like mirrored up, Mirrored down etc (Code here --> https://github.com/utopia-php/image/pull/19/files) .. Below link provides all JPG Exif orientation scenarios. Odd thing even the scenarios Appwrite checks for don't work. So preview API endpoint is doesn't work if JPG has any orientation Exif. 

Storage Preview API endpoint hopefully, if it fully addresses this issue, should also introduce additional image manipulation i.e., flip vertical/ flip horizontal which the, currently, un-tackled Exif orientation requires.

https://www.galloway.me.uk/2012/01/uiimageorientation-exif-orientation-sample-images/

**Comment by stnguyen90** [comment]
> What's confusing me is the fact that this is not reproducible in versions prior to 1.5. So something must have changed in regards to how Appwrite handles images?

ya, i can confirm the image isn't flipped in 1.4.4: 
<img width="1171" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/3fbd154d-6ad3-44d3-b744-71023ed74369">

> So something must have changed in regards to how Appwrite handles images?

Logically, not much has changed between [0.5.4 and 0.6.1](https://github.com/utopia-php/image/compare/0.5.4...0.6.1). 😵‍💫

**Comment by stnguyen90** [comment]
I just tested Appwrite 1.4.14 and the image still looks okay: 

<img width="1129" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/e9d6fd29-e741-4e00-9181-dbbb4fe7c696">

Appwrite 1.4.14 uses utopia-php/image version [0.6.1](https://github.com/appwrite/appwrite/blob/5cfaee42976a4f3796964414763546538803a7a4/composer.lock#L2116-L2117) so the image library isn't the problem 😕

**Comment by stnguyen90** [comment]
@byawitz, did some tests and it seems like the version of imagemagick in our base image had a bug and upgrading it should fix the problem. On our end, looksl ike we just need to generate a new image.

**Comment by stnguyen90** [comment]
This should be fixed on cloud now: 
<img width="610" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/95510629-f5e6-4b87-8e5d-7868f9c324d8">
