### ISSUE TITLE
🐛 Bug Report: Unable to verify identity

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#8211]
### 👟 Reproduction steps

1. Log in to the Appwrite Console using GitHub
2. Click on email verification
3. Enter code from email

### 👍 Expected behavior

I'm logged in

### 👎 Actual Behavior

Nothing happens

Related discord threads:

* https://discord.com/channels/564160730845151244/1244309975401234523
* https://discord.com/channels/564160730845151244/1244908394209480746

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by theatulgupta** [comment]
I am unable to log in after entering the correct code from the email. Please assist in resolving this issue, as it is hindering my development progress.
<img width="1394" alt="Screenshot 2024-06-04 at 10 00 23 AM" src="https://github.com/appwrite/appwrite/assets/100276578/d5487513-b5eb-4edb-b1fe-0567546c6daf">

**Comment by stnguyen90** [comment]
@theatulgupta, for now, the quickest workaround is to log in with your password (go through the forgot password flow if you don't have one) and then verify with email.

**Comment by theatulgupta** [comment]
I made a forgot password request and successfully logged in. Then I turned off Multi-Factor Authentication. Now it's their responsibility to fix the issue.

**Comment by stnguyen90** [comment]
The plan for this is to skip MFA if authenticating with OAuth2 because OAuth2 relies on the auth provider for authentication and the resource provider (Appwrite) should trust the OAuth2 provider's response that the user is authenticated and that's who they are. Doing this will also reduce friction for users, simplify which email users must check, and prevents multiple MFA checks (from the auth provider AND Appwrite).
