### ISSUE TITLE
Can't see documents

### ISSUE THREAD

**Issue by thesmartrenovation** [appwrite/appwrite#822]
Hello, 

I'm new to AppWrite.

I did a clean installation on a clean server. Everything works fine, except I can't see the documents on the dashboard and I can't see the create button, to add documents directly from the dashboard.

look:

![image](https://user-images.githubusercontent.com/57076657/104497256-14659380-55a8-11eb-89c8-fa695e92bdef.png)

I think that's a nug, but maybe I made a mistake in the installation or configuration

**Comment by eldadfux** [comment]
@thesmartrenovation  Please check if you get any network error in the browser console. If yes please post the errors response payloads you find.

**Comment by thesmartrenovation** [comment]
> @thesmartrenovation Please check if you get any network error in the browser console. If yes please post the errors response payloads you find.

Hello, 

No network or console errors

![image](https://user-images.githubusercontent.com/57076657/104510638-72e73d80-55b9-11eb-8fe4-e71313fa0943.png)

**Comment by eldadfux** [comment]
Check the payload of this 2 requests:

![Uploading image.png…]()

**Comment by thesmartrenovation** [comment]
> Check the payload of this 2 requests:
> 
> ![image](https://user-images.githubusercontent.com/1297371/104510888-8bc11480-55f4-11eb-99ec-e64b9fc83c3b.png)

![image](https://user-images.githubusercontent.com/57076657/104513786-3702a700-55be-11eb-9656-f6826a57862f.png)

![image](https://user-images.githubusercontent.com/57076657/104513907-687b7280-55be-11eb-9e67-a6468e04320b.png)

**Comment by eldadfux** [comment]
Try to add a rule to the specific collection in the collection settings and see if the problem persist

**Comment by thesmartrenovation** [comment]
> Try to add a rule to the specific collection in the collection settings and see if the problem persist

If i added rules, the botton to create document appear, but not the documents created with SDK....if i create a document through the dashboard this is shown

![image](https://user-images.githubusercontent.com/57076657/104520974-06c10580-55ca-11eb-9916-813d5f6a358f.png)

The board says "2 documents" but only one is available for viewing

**Comment by eldadfux** [comment]
This seems like a UI specific bug when no rules have been set, I'll try and debug it on my system.

**Comment by thesmartrenovation** [comment]
> This seems like a UI specific bug when no rules have been set, I'll try and debug it on my system.

Thanks, I will wait

**Comment by TorstenDittmann** [comment]
iirc this got solved. Closing it for now, will be re-opened if necessary 🙂

**Comment by PavanSN** [comment]
this bug still persits in version 1.3.8
