### ISSUE TITLE
🐛 Bug Report: New database creation blocked after deleting one

### ISSUE THREAD

**Issue by gammelu** [appwrite/appwrite#8221]
### 👟 Reproduction steps

Create two databases. Delete a database (on free plan) because I made an error. I have one left and tried to creat a replacement for the one I did wrong.

### 👍 Expected behavior

Allow me to open a 2nd Database which was promised during sign-up.

### 👎 Actual Behavior

Force me to upgrade. As if the system can't recognize that I now only have one database. 2-3 is bare minimum for new devs trying to learn and if you cant delete a database when exploring It doesnt feel good.

<img width="1205" alt="Screenshot 2024-05-30 at 15 12 43" src="https://github.com/appwrite/appwrite/assets/150397128/357e56e6-3f97-446f-9e5c-bffad949a6ba">

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gammelu, thanks for creating this issue! 🙏🏼 As shown on the Console and our [pricing page](https://appwrite.io/pricing#:~:text=Databases-,1%20per%20project,-Unlimited), the Starter plan is limited to 1 Database. Most projects don't require more than 1 Database. What's your use case?
