### ISSUE TITLE
📚 Documentation: Fix CONTRIBUTION.md Instructions

### ISSUE THREAD

**Issue by dianapham** [appwrite/appwrite#8227]
### 💭 Description

**Rearrange paragraphs to make it easier to follow:**
The flow of the Submit a Pull Request section could be improved by moving the details ("Branch naming convention..." under the 2nd point ("Create a new branch from master like: doc-548-submit-a-pull-request-section-to-contribution-guide.") about branch naming.

This section would easier to follow...
![branch naming](https://github.com/appwrite/appwrite/assets/56854081/48e4be5b-948b-4dcb-8545-729e606f5e2c)

if it was under this section.
![new branch](https://github.com/appwrite/appwrite/assets/56854081/71b19090-8f36-4b9c-a7e7-80b329b209a0)

**Fix spelling and grammar:**
I noticed a few spelling and grammar issues and gave it a run-through Grammarly. Here's a markdown file with my suggested changes:

[Contributing.md](https://github.com/user-attachments/files/15519696/Contributing.md)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by keerthinannepamula1** [comment]
May I work on this issue?

**Comment by stnguyen90** [comment]
@keerthinannepamula1, thanks, but I'll take care of this. If you're looking to contribute, please look for issues labeled "good first issue" or "help wanted".

**Comment by keerthinannepamula1** [comment]
@stnguyen90 hey! sure. Thanks
