### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [appwrite/appwrite#824]
Hi there 

I would like to contribute to this project by adding a welcome and greeting bot which will comment up when any user will open up with an issue or pull-request for the first time
Kindly do assign me this issue 
( config file having a proper message)

For reference, kindly check out: https://github.com/apps/welcome

**Comment by Glide7** [comment]
Hey there @akrish4 , welcome to the community! 
While we do appreciate your wanting to help, for the time being we prefer to not use welcome and message bots in Appwrite!
This is something that we want to do in the future, but not for now! 

I will contact you in the future when the time is right to do so :)

**Comment by akrish4** [comment]
sure @Glide7 
I will always be glad to contribute , kindly contact me through this issue whenever you require it and also contact when you need anything to be documented now
