### ISSUE TITLE
Indian Region server not available

### ISSUE THREAD

**Issue by AmbreeshSrivastava25** [appwrite/appwrite#8241]
I am unable to access Indian region server for creating my project. How long will it take to notify me?

**Comment by ItzNotABug** [comment]
The team is currently working on expanding the regions as Cloud Beta is Live and looks pretty stable!
You can opt. to get notified once the region is available. No ETA on it though. Make sure to check on the discord server too!

**Comment by EVDOG4LIFE** [comment]
Hi @AmbreeshSrivastava25,

Thanks for opening this up. We only offer one location in Germany at this time. We are hoping to open more regions up as we get closer to moving out of Beta. 

We will be publicly sharing when we have an exact launch time for these, and are hoping for the end of the year if all goes well.

**Comment by Nebula-Developer** [comment]
When these locations become available, will it be possible to migrate to closer locations in the future? Or are all Appwrite projects created now locked to Germany?
