### ISSUE TITLE
Automating the webapp

### ISSUE THREAD

**Issue by himanshu007-creator** [appwrite/appwrite#825]
I would like to work on this issue.I will create a script that will enable opening website from CLI.
Please add DWOC label to it and assign me this issue.

**Comment by Glide7** [comment]
Hey @himanshu007-creator - done and done! please feel free to ask questions here or in our discord :) appwrite.io/discord

**Comment by himanshu007-creator** [comment]
> Hey @himanshu007-creator - done and done! please feel free to ask questions here or in our discord :) appwrite.io/discord

https://github.com/appwrite/appwrite/pull/828
Job done.

**Comment by Glide7** [comment]
Hey @himanshu007-creator - thanks for this pull request - we feel like this is irrelevant pull. Please feel free to browse other dwoc issues, and help us there! thanks!
