### ISSUE TITLE
Is it possible to filter based on array values?

### ISSUE THREAD

**Issue by ardevd** [appwrite/appwrite#826]
I can't seem to figure out whether it's possible to filter on array values. Say you have a document with a numerical array field and you want to filter based on that to give you records that contain the supplied filter value in the array.

I dont think the comparison operators (=, !=, >, <, <=, >=) work in this case. If your numeric array for a given record contains [1,5,10,12] and you want to filter based on the value `5` then the comparison operators do not make sense. filters[my_array=5] doesnt work and returns an empty result set. Seems like you need the equivalent of an `IN` keyword.

Please advise.

**Comment by ardevd** [comment]
Any update on this? I realize arrays are broken in multiple ways currently, but is there any way to filter based on array values yet?

**Comment by eldadfux** [comment]
@ardevd we're working on fixing that, I'll share updates here and on Discord 👍🏻

**Comment by TorstenDittmann** [comment]
Closing this in favor of #1174

**Comment by superseby2** [comment]
Hello @TorstenDittmann, 

I may be mistaken but #1174  does not seem to take care of IN operator. 
Is there any ETA for IN or any operator allowing to check if a value exits in an array ?

Thx !
