### ISSUE TITLE
🐛 Bug Report:  Did not delete the collection's attribute totally.

### ISSUE THREAD

**Issue by moshOntong-IT** [appwrite/appwrite#8265]
### 👟 Reproduction steps

I was deleted a specific attribute in my collection. But then when I tried to update some documents. There was an error occur in my screen. It shows "Unknown attribute: members"

### 👍 Expected behavior

It should update the document.

### 👎 Actual Behavior

It did not update the document because of "Unknown attribute members"

https://github.com/appwrite/appwrite/assets/57244338/98343f31-4829-47c7-9322-1876629bf819

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
There's a good chance that the deletion worker hasn't run yet or the fix has already landed as this is not really reproducible on local or a self hosted instance.

**Comment by moshOntong-IT** [comment]
> There's a good chance that the deletion worker hasn't run yet or the fix has already landed as this is not really reproducible on local or a self hosted instance.

I deleted the attributed. Then I wait for 2 to 3 hours so that the deletion worker maybe fully delete attribute. But it still the problem occurs

**Comment by moshOntong-IT** [comment]
This is the conversation about this error:

**Comment by fogelito** [comment]
@stnguyen90 @moshOntong-IT please try if the issue is fixed

PR https://github.com/utopia-php/database/pull/428
merged

**Comment by moshOntong-IT** [comment]
> @stnguyen90 @moshOntong-IT please try if the issue is fixed
> 
> PR [utopia-php/database#428](https://github.com/utopia-php/database/pull/428) merged

The issue is fixed thank you sir.
