### ISSUE TITLE
🐛 Bug Report: Impossible to restore 1.5.7 backup

### ISSUE THREAD

**Issue by istornz** [appwrite/appwrite#8279]
### 👟 Reproduction steps

- I use theses scripts to backup my 1.5.7 instance: [https://gist.github.com/stnguyen90/fee636ff652b8ecbf761935b2aa254fb/](https://gist.github.com/stnguyen90/fee636ff652b8ecbf761935b2aa254fb/)
- I installed a fresh 1.5.7 instance
- I restored from backup and got this error when I execute ```docker logs appwrite```
```
[Error] Timestamp: 2024-06-14T10:04:21+00:00
[Error] Method: GET
[Error] URL: /v1/account/prefs
[Error] Type: TypeError
[Error] Message: Utopia\Database\Document::__construct(): Argument #1 ($input) must be of type array, Utopia\Database\Document given, called in /usr/src/code/app/controllers/api/account.php on line 2409
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Document.php
[Error] Line: 27
```

**WORKAROUND** (thanks to @ItzNotABug, I copy-pasted his solution which works on my side too)
- I searched the forums and found that there's probably a migration issue as seen in the migrate errors and the docker appwrite logs.
- I removed everything, installed appwrite 1.4.13, played a little bit here and there on console.
- Bumped appwrite to 1.5.4 & did a docker exec appwrite migrate
- After the succesfull migration, I stopped traefik and executed ./restore.sh
- Restarted appwrite stack like docker compose up -d
- I can finally see all of the data, from accounts, to functions, to stats and everything else.

Sources:
- https://discord.com/channels/564160730845151244/1228630098241126401
- https://discord.com/channels/564160730845151244/1251115554992033812

### 👍 Expected behavior

It should restore backup without any issues.

### 👎 Actual Behavior

It show an error 500.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Hello! 
Did you had any previous version installed on that machine prior to installing 1.5.4?

**Comment by istornz** [comment]
Hello @DH-555, Yes the first version was 1.3.X, I upgraded normally since 1.5.4.

**Comment by stnguyen90** [comment]
@istornz, did you wipe all volumes before installing the fresh 1.5.7?

**Comment by istornz** [comment]
> @istornz, did you wipe all volumes before installing the fresh 1.5.7?

Sorry for late reply, yes I ran the following command : `docker compose down -v`
