### ISSUE TITLE
🐛 Bug Report: Invalid document structure: Missing required attribute "expire" on `users.createSession()`

### ISSUE THREAD

**Issue by oconr** [appwrite/appwrite#8280]
### 👟 Reproduction steps

This bug happens when I try to use `createSession(userId)` from the Node SDK, but it appears to also be happening in the PHP SDK when using `$users->createSession($userId)`.

### 👍 Expected behavior

A session should be created for the user ID that is provided.

### 👎 Actual Behavior

The following errors gets thrown and logged
```
[Error] Timestamp: 2024-06-14T12:44:49+00:00
[Error] Method: POST
[Error] URL: /v1/users/:userId/sessions
[Error] Type: Utopia\Database\Exception\Structure
[Error] Message: Invalid document structure: Missing required attribute "expire"
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 3070
```

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I have tried this on both Appwrite 1.5.4 and 1.5.7, both running on a DigitalOcean droplet. I'm using the latest version of the Node SDK

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by oconr** [comment]
Related Discord discussions:
https://discord.com/channels/564160730845151244/1251156254479618128
https://discord.com/channels/564160730845151244/1228169560583311453

**Comment by stnguyen90** [comment]
ideclon's [investigation](https://discord.com/channels/564160730845151244/1228169560583311453/1228174208777982004):

> My guess as to why this is happening - I see in `POST /v1/account/sessions/token` (`$account->createSession()`), `expire` is in the `new Document()` declaration: 
> https://github.com/appwrite/appwrite/blob/505637d1190881d131fbe2eb003e6b27676a4387/app/controllers/api/account.php#L106
> whereas in `POST /v1/users/:userId/sessions` (`$users->createSession()`, `expire` is added after the Document is created:
> https://github.com/appwrite/appwrite/blob/505637d1190881d131fbe2eb003e6b27676a4387/app/controllers/api/users.php#L1811
