### ISSUE TITLE
🐛 Bug Report:  User login 

### ISSUE THREAD

**Issue by Jedidiah-Solomon** [appwrite/appwrite#8284]
### 👟 Reproduction steps

After sign up, I tried to login but it says ```Error logging in: Invalid `userId` param: Parameter must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can't start with a special char```

### 👍 Expected behavior

login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Log In</title>
    <link rel="stylesheet" href="../styles/login.css" />
    <script src="../dist/login.bundle.js" defer></script>
  </head>
  <body>
    <h1>Log In</h1>
    <form id="login-form">
      <label for="email">Email:</label>
      <input type="email" id="email" name="email" required /><br />
      <label for="password">Password:</label>
      <input type="password" id="password" name="password" required /><br />
      <button type="submit">Log In</button>
    </form>
  </body>
</html>

login.js
import { Client, Account } from "appwrite";

const client = new Client();
client
  .setEndpoint("https://cloud.appwrite.io/v1")
  .setProject("6670bced001681b60586");

const account = new Account(client);

document
  .getElementById("login-form")
  .addEventListener("submit", function (event) {
    event.preventDefault();

    const email = document.getElementById("email").value;
    const password = document.getElementById("password").value;

    account
      .createSession(email, password)
      .then((response) => {
        console.log("User logged in:", response);
        alert("Login successful!");

        document.getElementById("login-form").reset();

        window.location.href = "/pages/news-today.html";
      })
      .catch((error) => {
        console.error("Error logging in:", error);
        alert("Error logging in: " + error.message);
      });
  });

FROM BROWSER NETWORK TAB: 

```
Request URL:
https://cloud.appwrite.io/v1/account/sessions/token
Request Method:
POST
Status Code:
400 Bad Request
```

```
signup.html -- this was successful and user can be added to the dashboad
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Sign Up</title>
    <link rel="stylesheet" href="/styles/signup.css" />
    <!-- Adjust path if necessary -->
    <script src="/dist/signup.bundle.js" defer></script>
    <!-- Correct path to the bundle -->
  </head>
  <body>
    <h1>Sign Up</h1>
    <form id="signup-form">
      <label for="username">Username:</label>
      <input type="text" id="username" name="username" required /><br />
      <label for="email">Email:</label>
      <input type="email" id="email" name="email" required /><br />
      <label for="password">Password:</label>
      <input type="password" id="password" name="password" required /><br />
      <button type="submit">Sign Up</button>
    </form>
  </body>
</html>

signup.js

import { Client, Account, ID } from "appwrite";

// Initialize the Appwrite client
const client = new Client();
client
  .setEndpoint("https://cloud.appwrite.io/v1") // Set the endpoint of your Appwrite server
  .setProject("6670bced001681b60586"); // Set your project ID

// Create an Account instance
const account = new Account(client);

// Add an event listener to the signup form submission
document
  .getElementById("signup-form")
  .addEventListener("submit", function (event) {
    event.preventDefault();

    // Get the user input values
    const username = document.getElementById("username").value;
    const email = document.getElementById("email").value;
    const password = document.getElementById("password").value;

    // Create a new user account
    account
      .create(ID.unique(), email, password, username)
      .then((response) => {
        console.log("User created:", response);
        alert("User created successfully!");

        // Inform the user to check their email for verification
        alert("Please check your email for a verification link.");
        document.getElementById("signup-form").reset();
        setTimeout(() => {
          window.location.href = "/pages/login.html";
        }, 2000); // 2-second delay
      })
      .catch((error) => {
        console.error("Error creating user:", error);
        alert("Error creating user: " + error.message);
      });
  });

```

### 👎 Actual Behavior

I need to log in

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Web

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ebenezerdon** [comment]
Hey @Jedidiah-Solomon, the correct login method for email and password is `account.createEmailPasswordSession('email@example.com', 'password')`

You're getting an error message because `account.createSession()` expects a `USER_ID` and `SECRET` argument. You'd typically use it when working with Magic URL, phone auth, email OTP, and custom token auth.

**Comment by BHAVADEEP123** [comment]
> Hey @Jedidiah-Solomon, the correct login method for email and password is `account.createEmailPasswordSession('email@example.com', 'password')`
> 
> You're getting an error message because `account.createSession()` expects a `USER_ID` and `SECRET` argument. You'd typically use it when working with Magic URL, phone auth, email OTP, and custom token auth.

yes createSession is used in an older version for email password authentication

**Comment by Jedidiah-Solomon** [comment]
Ok thank, It is working now.

**Comment by Jedidiah-Solomon** [comment]
But I have an another issue, If am using appwrite cloud cos am just learning it as a great BaaS, the email verification is not working with cloud why?

**Comment by BHAVADEEP123** [comment]
Can you show me your code?

**Comment by BHAVADEEP123** [comment]
Like once check before calling create verification, you need to create a session. 
Then you can call create verification method from account

**Comment by Jedidiah-Solomon** [comment]
> Closing as the original problem is resolved and there was no bug with Appwrite. If you need help, feel free to create a support post on [Discord](https://appwrite.io/discord).

Ok, I will use Discord.

**Comment by raiashpanda007** [comment]
> createEmailPasswordSession

Bro saved my day thank you so much

**Comment by sumeshp09** [comment]
I am facing the same issue but am not able to solve

**Comment by BHAVADEEP123** [comment]
> I am facing the same issue but am not able to solve

What error? can you brief it please.

**Comment by Jedidiah-Solomon** [comment]
Hey BHAVADEEP BHUKYA,


*Kindly check my github, I resolved it.*

**Comment by BHAVADEEP123** [comment]
Hi @Jedidiah-Solomon, mb I should have tagged @sumeshp09

**Comment by sumeshp09** [comment]
Thanks for helping 
Issue solved 👍

**Comment by Jedidiah-Solomon** [comment]
My pleasure!
