### ISSUE TITLE
🐛 Bug Report: Errors in Messaging service

### ISSUE THREAD

**Issue by vule20** [appwrite/appwrite#8291]
### 👟 Reproduction steps

I have my own SMTP mail server hosted at smtp.my_domain.com and it works perfectly fine. However, when I integrated it to Appwrite by setting _APP_SMTP_HOST to smtp.my_domain.com and tried messaging my users, I got the following error in the backend.
<img width="1280" alt="image" src="https://github.com/appwrite/appwrite/assets/63137043/d2ee17ae-484b-44f7-a83e-b0bd37e28b98">

In addition, the messaging console in my current project appears like this 
<img width="534" alt="image" src="https://github.com/appwrite/appwrite/assets/63137043/fff4cbdd-ecaf-4cd4-8e6d-a1e5af84406b">

### 👍 Expected behavior

It should works fine

### 👎 Actual Behavior

.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by vule20** [comment]
My SMTP encryption type is starttls on port 587

**Comment by stnguyen90** [comment]
@vule20, thanks for raising this issue! 🙏🏼 Do you have `tls` set for the `_APP_SMTP_SECURE` [environment variable](https://appwrite.io/docs/advanced/self-hosting/environment-variables#smtp)? If not, please try that.

**Comment by vule20** [comment]
Yeap. I did. My config is here
<img width="496" alt="Screenshot 2024-06-21 at 16 46 31" src="https://github.com/appwrite/appwrite/assets/63137043/b9ac8024-573e-43f4-a7b0-c6a381079eab">

When I run doctor, it shows that SMTP is disconnected.
<img width="581" alt="image" src="https://github.com/appwrite/appwrite/assets/63137043/b2ad6a74-f809-4d04-9e16-7b9c50779ab4">

And when I run your smpt test script (in your gist), I got this error. I can still use my smtp mail server on port 587 with Python and it works perfectly fine.
<img width="1060" alt="image" src="https://github.com/appwrite/appwrite/assets/63137043/6a376a67-e5fc-4e02-97ad-bedc383d4456">

**Comment by stnguyen90** [comment]
@vule20, what version of Appwrite do you have running?

**Comment by vule20** [comment]
@stnguyen90 As I mentioned above, I'm using Appwrite 1.5.7

**Comment by stnguyen90** [comment]
@vule20, what happens if you set the `_APP_SMTP_SECURE` env var to `ssl`?

**Comment by vule20** [comment]
@stnguyen90 SMTP sill not connected and the logs from the email test script remain unchanged
<img width="1061" alt="image" src="https://github.com/appwrite/appwrite/assets/63137043/3e6a0ed8-8cce-4e5a-be47-aa4a6bfd6bab">

**Comment by stnguyen90** [comment]
@vule20, does `docker compose exec appwrite vars` show the same env var values?
