### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [appwrite/appwrite#830]
## 📚 Documentation

To make README.md file beautiful and give credit to contributors
Like this
![image](https://user-images.githubusercontent.com/68433936/104682313-61697700-571a-11eb-8f92-5060042d9263.png)

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by Glide7** [comment]
Hey @samir-0711 - thank you so much for this idea! Sadly, we've had it already some time back, yet the list became too big, so we removed it! 

Feel free to browse any existing issue and working on then :)

**Comment by samir-0711** [comment]
I can add "CONTRIBUTORS.md" file link in README.md which will show contributors in new file. (Also this will not clog up our README)
Like this
![image](https://user-images.githubusercontent.com/68433936/104702549-28da9500-573c-11eb-8a40-9ec382edd554.png)

**Comment by eldadfux** [comment]
Hey @samir-0711, it would probably not be very different from the Github's built-in contributors page, and will just create more commit/PR noise for the team.
