### ISSUE TITLE
🚀 Enhancement: Subcollection Support

### ISSUE THREAD

**Issue by Rizzist** [appwrite/appwrite#8300]
### 🔖 Enhancement description

Create subcollection & have appwrite automatically handle it under document such as:
- deleting doc w/ subcollections deletes all subcollections
- reading subcollection by going through doc

### 🎤 Pitch

Capture Market making it Easier to migrate from ###### Firebase

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Rizzist, thanks for creating this issue! 🙏🏼 Appwrite's collections are flat so we typically handle related data via a separate collection. We also support [relationships](https://appwrite.io/docs/products/databases/relationships), but they are experimental and should be used with caution as they can lead to performance problems.
