### ISSUE TITLE
🐛 Bug Report: unable to retrieve any data from collections

### ISSUE THREAD

**Issue by BHAVADEEP123** [appwrite/appwrite#8302]
### 👟 Reproduction steps

yesterday I was able to create a document from sdk. but today I am not able to and I am not even able to get any document from any collection. I am always getting appwrite error

### 👍 Expected behavior

get documents 

### 👎 Actual Behavior

appwrite exception

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@BHAVADEEP123, thanks for raising this issue! 🙏🏼 What's the error you're receiving?
