### ISSUE TITLE
🐛 Bug Report: REALTIME DOESN'T WORK

### ISSUE THREAD

**Issue by Dgobabi** [appwrite/appwrite#8303]
### 👟 Reproduction steps

When i make my subscription , i het the socket link which means the subscription was success , but when i update an document i don't receive anything in response payload.
I verified my collections and documents id everything is correct but nothing works . I'm in PRO version , doesn't PRO version have access to Realtime ? Need support

### 👍 Expected behavior

Get response payload of my update in databases

### 👎 Actual Behavior

Nothing

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

I use Flutter and [appwrite](appwrite: 12.0.2) package

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Dgobabi, thanks for raising this issue! 🙏🏼 Would you please share your code and the permissions on the related collection?
