### ISSUE TITLE
🐛 Bug Report: Push notifications sent with FCM are missing fields for Android

### ISSUE THREAD

**Issue by MHEien** [appwrite/appwrite#8310]
### 👟 Reproduction steps

Send a message in Appwrite Console to an Android app.
Keep the app in foreground, and take a look at the received notification.

This is tested on Expo managed applications using the expo-notifications package.

### 👍 Expected behavior

I've been troubleshooting this for a bit, and found that the payload sent to FCM services is missing a data field in the object.
While taking a brief look through the UTOPIA PHP adapter used for messaging in Appwrite, specifically in the FCM class, I noticed this is indeed the case.
The class is found here: https://github.com/utopia-php/messaging/blob/main/src/Utopia/Messaging/Adapter/Push/FCM.php

Take a look at the bare example of the expected payload below, to see which fields are mapped to which Application state.
```json
{
  "message": {
    "token": "some-token",
    "notification": {
        "title": "Works in background",
        "body": "This message is successfully received while app is in background."
      },
    "android": {
      "priority": "high",
      "data": {
        "title": "This title is visible while the app is in foreground.",
        "message": "This message will be seen in the push notification while the app is in foreground."
      }
    },
    "data": {
      "href": "chat"
    }
  }
}
```

### 👎 Actual Behavior

When sending a Push notification to Android devices, the push notification is received, but will not contain any content while the app is in foreground. Including `android.data` will fix this.

Discord thread: https://discord.com/channels/564160730845151244/1254059230751625217

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.5.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@MHEien, thanks for creating this issue! 🙏🏼 

As mentioned on [Discord](https://discord.com/channels/564160730845151244/1254059230751625217/1254925265382146060), this seems like a bug either client-side or with react native. Here's my test on Android (Flutter) with the app in the foreground:

![image](https://github.com/appwrite/appwrite/assets/1477010/9cf82e54-73bb-4778-954e-ff7b360b427d)

![image](https://github.com/appwrite/appwrite/assets/1477010/a3750208-e367-4a90-96f1-dfb69fc330a9)

the code i tested with: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example

**Comment by MHEien** [comment]
Ok thanks, I've read up on how push notifications works on the device, and found that messages received while the app is in foreground is indeed controlled by the app. I suppose I'll have to wait for Expo to have this fixed then. However, if anybody else encounter this issue aswell, atleast the example payload above would solve the issue completely.

**Comment by obiwanzenobi** [comment]
I would not agree with closing that one, indeed appwrite messaging is missing some fields for Android like ttl or priority
(ref: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidconfig)

But utopia-messaging allows only a few fields from a referenced doc:
https://github.com/utopia-php/messaging/blob/main/src/Utopia/Messaging/Adapter/Push/FCM.php#L115

Maybe it would be a good idea to pass a json/map for a specific platform, so it will be also future prof when new parameters needed by new version of operating systems will be added by FCM team?
