### ISSUE TITLE
📚 Documentation: All vars `console.log` has to be `result` instead of `response`

### ISSUE THREAD

**Issue by xuelink** [appwrite/appwrite#8328]
### 💭 Description

Check the following pages
- https://appwrite.io/docs/references/cloud/client-web/storage#listFiles
- https://appwrite.io/docs/references/cloud/client-web/storage#createFile
- https://appwrite.io/docs/references/cloud/client-web/storage#getFile
- https://appwrite.io/docs/references/cloud/client-web/storage#updateFile
- https://appwrite.io/docs/references/cloud/client-web/storage#deleteFile
- https://appwrite.io/docs/references/cloud/client-react-native/storage#listFiles
- https://appwrite.io/docs/references/cloud/client-react-native/storage#createFile
- https://appwrite.io/docs/references/cloud/client-react-native/storage#getFile
- https://appwrite.io/docs/references/cloud/client-react-native/storage#updateFile
- https://appwrite.io/docs/references/cloud/client-react-native/storage#deleteFile

In these examples that i found in docs, variables has to be updated. 

<img width="627" alt="Screenshot 2024-06-26 at 3 22 36 AM" src="https://github.com/appwrite/appwrite/assets/3280475/75396a72-298b-4845-891b-6ff52672fbe2">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@xuelink, thanks for raising this! 🙏🏼 Looks like we need to fix our templates:

* https://github.com/appwrite/sdk-generator/blob/d382c1f14607cef8819b70d4a1fb3cf6b0880255/templates/web/docs/example.md.twig#L25
* https://github.com/appwrite/sdk-generator/blob/d382c1f14607cef8819b70d4a1fb3cf6b0880255/templates/react-native/docs/example.md.twig#L25

**Comment by kunalArya1** [comment]
Hi @stnguyen90,

Thank you for identifying the issue and providing the necessary information. I want to contribute to fixing the templates for the Appwrite documentation.

I have reviewed the relevant template files:

[Web Docs Template](https://github.com/appwrite/sdk-generator/blob/d382c1f14607cef8819b70d4a1fb3cf6b0880255/templates/web/docs/example.md.twig#L25)
[React Native Docs Template](https://github.com/appwrite/sdk-generator/blob/d382c1f14607cef8819b70d4a1fb3cf6b0880255/templates/react-native/docs/example.md.twig#L25)

I believe I can help resolve this issue by updating the variable names to ensure they align with the current API conventions. I will fork the repository, make the necessary changes, and submit a pull request.

Please let me know if there are any specific guidelines or additional details I should be aware of before proceeding.

**Comment by ayushDatacode** [comment]
can you assigned me this

**Comment by ayush-maddhesiya** [comment]
I have started working on it

**Comment by kartik1112** [comment]
is it done or can i work on this?

**Comment by ParagGhatage** [comment]
I want to work on this. Will you assign me this?

**Comment by ParagGhatage** [comment]
I have fixed this issue.
 Looking forward to getting it merged.

**Comment by stnguyen90** [comment]
@ParagGhatage, there was someone else already assigned on this and they already submitted a PR. Please do not work on issues assigned to others because we don't want people's work wasted.

**Comment by ParagGhatage** [comment]
Got it. My apologies for the mix-up. I'll be more careful next time.

**Comment by stnguyen90** [comment]
Re-opening as the examples need to be updated.

**Comment by prashant235913** [comment]
Please assign me
