### ISSUE TITLE
🚀 Enhancement: add typescript types for cloud functions context argument

### ISSUE THREAD

**Issue by liudonghua123** [appwrite/appwrite#8329]
### 🔖 Enhancement description

I write a cloud function using typescript, for the entrypoint function declaration, the types for the context is missing, I couldn't find in node-appwrite or appwrite package.

### 🎤 Pitch

n.a.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Jaishree2310** [comment]
Hey @liudonghua123 Can you please assign this issue to me?
Thanks!!

**Comment by liudonghua123** [comment]
@Jaishree2310 Well, how to assign? I am not a member of the appwrite team.

**Comment by liudonghua123** [comment]
I read the doc on https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users, but I could not find the setting icon button.

![image](https://github.com/appwrite/appwrite/assets/2276718/ae34a1af-6b12-480a-8baa-817cf569ed9b)


![image](https://github.com/appwrite/appwrite/assets/2276718/1b67f961-6a5e-41c7-8dde-409b96a87b3c)

**Comment by stnguyen90** [comment]
@liudonghua123, thanks for raising this issue. This looks like the same request as https://github.com/appwrite/appwrite/issues/7146, but for node. To consolidate, it would be best if you added a 👍🏼 to that issue.

And for the meantime, you can see the details of what's in the context [here](https://github.com/open-runtimes/open-runtimes/blob/2c4e95e3cee1fe4254910329333ea1ace52fdf08/runtimes/node-18.0/src/server.js#L73-L121). Then you can define the types yourself.

**Comment by hadnet** [comment]
Getting something like this:

```ts
type Context<T = any> = {
  req: {
    bodyRaw: any;
    bodyJson: T;
    bodyText: any;
    bodyBinary: any;
    body: any;
    headers: Record<string, string>;
    method: string;
    host: string;
    scheme: string;
    query: Record<string, string | string[]>;
    queryString: string;
    port: number;
    url: string;
    path: string;
  };
  res: {
    send: (
      body: any,
      statusCode?: number,
      headers?: Record<string, string>
    ) => {
      body: any;
      statusCode: number;
      headers: Record<string, string>;
    };
    text: (
      obj: any,
      statusCode?: number,
      headers?: Record<string, string>
    ) => {
      body: string;
      statusCode: number;
      headers: Record<string, string>;
    };
    json: (
      obj: any,
      statusCode?: number,
      headers?: Record<string, string>
    ) => {
      body: string;
      statusCode: number;
      headers: Record<string, string>;
    };
    empty: () => {
      body: string;
      statusCode: number;
      headers: Record<string, string>;
    };
    redirect: (
      url: string,
      statusCode?: number,
      headers?: Record<string, string>
    ) => {
      body: string;
      statusCode: number;
      headers: Record<string, string>;
    };
  };
  log: (message: any) => void;
  error: (message: any) => void;
};
```
