### ISSUE TITLE
🐛 Bug Report: Deploy a starter function from github failed

### ISSUE THREAD

**Issue by archichen** [appwrite/appwrite#8331]
### 👟 Reproduction steps

1. Click template tab
2. select python starter template
3. set function name and select github repository
4. start deployment

### 👍 Expected behavior

Function deploy success

### 👎 Actual Behavior

Function deploy failed.

Log:
```
/usr/src/code/src/Executor/Executor.php:97
#0 /usr/src/code/src/Appwrite/Platform/Workers/Builds.php(407): Executor\Executor->createRuntime('667c48517de8e5e...', '667a8c9b000ef54...', '/storage/functi...', 'openruntimes/py...', 'v3', true, 'src/main.py', '/storage/builds...', Array, 'tar -zxf /tmp/c...')
#1 [internal function]: Appwrite\Platform\Workers\Builds->Appwrite\Platform\Workers\{closure}()
#2 {main}

```
Here is screenshot: 
![image](https://github.com/appwrite/appwrite/assets/18643080/24ef3943-467a-4fdf-b8c1-aec5d72e758a)

Here is my function structure, it's generated by appwrite, I don't do the any changes:
![image](https://github.com/appwrite/appwrite/assets/18643080/63b6274b-c1f8-4a90-94da-3c7dcfacb10b)

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Cloudflare for DNS record.
Appwrite version is `1.5.7`
Have http_proxy and https_proxy in `~/.docker/config.json`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@archichen, thanks for raising this issue! 🙏🏼 Would you please check the docker logs from the `openruntimes-executor` container and share the errors if there are any?

**Comment by archichen** [comment]
> @archichen, thanks for raising this issue! 🙏🏼 Would you please check the docker logs from the `openruntimes-executor` container and share the errors if there are any?

@stnguyen90 very glad to see your reply, here is my `openruntimes-executor` logs:
```
cxx@server:~/composes/appwrite_setup$ docker logs  openruntimes-executor
Removing orphan runtimes...
Cleaning up containers...
No containers found to clean up.
Cleanup finished.
Orphan runtimes removal finished.
Pulling v3 images...
Warming up Node.js 16.0 environment...
Warming up PHP 8.0 environment...
Warming up Ruby 3.0 environment...
Warming up Python 3.9 environment...
Successfully Warmed up Python 3.9!
Successfully Warmed up PHP 8.0!
Successfully Warmed up Node.js 16.0!
Successfully Warmed up Ruby 3.0!
Image pulling finished.
Starting maintenance interval...
Maintenance interval started.
Starting stats interval...
Stats interval started.
Executor is ready.
Running maintenance task ...
Maintanance task finished.
Running maintenance task ...
Maintanance task finished.
Running maintenance task ...
Maintanance task finished.
Running maintenance task ...
Maintanance task finished.
Running maintenance task ...
Maintanance task finished.
Running maintenance task ...
Maintanance task finished.
Running maintenance task ...
Maintanance task finished.
Running maintenance task ...
Maintanance task finished.
Running maintenance task ...
Maintanance task finished.
```

It's looks ok...I have tried to re-deploy function, but no new logs print out, functon deployed failed as well.
