### ISSUE TITLE
The flutter SDK does not automatically reconnect.

### ISSUE THREAD

**Issue by Hopheylalal** [appwrite/appwrite#8338]
### 🔖 Enhancement description

Please add it 

### 🎤 Pitch

If the application is not used for a long time, realtime disconnected.
2.if the application goes into the background, the connection is interrupted.
3.never reconnects. you need to restart the application.

on the other hand, in the same application, socket io works perfectly. no breaks. if a break occurs, the connection is restored. for several months there is no error.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by moshOntong-IT** [comment]
I encountered this issue. https://discord.com/channels/564160730845151244/1256922603306745956

**Comment by moshOntong-IT** [comment]
Maybe the core team must implement something like ping/pong on websocket. According to this

[What is Ping/Pong](https://discord.com/channels/564160730845151244/1256922603306745956)

> The WebSocket specification defines [ping](https://tools.ietf.org/html/rfc6455#section-5.5.2) and [pong](https://tools.ietf.org/html/rfc6455#section-5.5.3) message opcodes as part of the protocol. These can serve as a way to keep a connection active even if data is not being transmitted.
> Pings may be sent in either direction. If the client receives a ping, a pong reply will be automatically sent.
