### ISSUE TITLE
🚀 Enhancement: Function code viewer online

### ISSUE THREAD

**Issue by liudonghua123** [appwrite/appwrite#8344]
### 🔖 Enhancement description

Hi, it would be convenient if the deployed code could view on the admin dashboard.

### 🎤 Pitch

In my user-case, I want to check the deployed and running function code. But now it seems impossible. I used cloud function of other venders like [tencent](https://www.tencentcloud.com/zh/products/scf), they provide this feature.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Closing in favor of https://github.com/appwrite/console/issues/1445
