### ISSUE TITLE
🚀 Enhancement: Disable/Remove Stripe on Self Hosted Instances

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#8349]
### 🔖 Enhancement description

First suggested on Discord - https://discord.com/channels/564160730845151244/870534256324124692/1225699725907333200

---
Cloud uses Stripe for managing payments which is understandable however thats not the case on a self hosted instance. Plus, stripe logs & fetches quite of info as well while browsing the console which isn't really necessary.

---
`GET`
```text
https://js.stripe.com/v3
```

`POST`
```text
https://m.stripe.com/6
```

### 🎤 Pitch

Disable Stripe.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Closing as a duplciate of https://github.com/appwrite/console/issues/1168
