### ISSUE TITLE
🐛 Bug Report: Creating team membership from Client has parameteres messed up | invite with email

### ISSUE THREAD

**Issue by sikandarchishty** [appwrite/appwrite#8351]
### 👟 Reproduction steps

```
const promise = await teams.createMembership(
    'teachers',
    ["maths"],
    "david@example.com"
);
```

### 👍 Expected behavior

parameters should be able to accept or identify what is required when using client sdk.
below code should create a team

### 👎 Actual Behavior

```
const promise = await teams.createMembership(
    'teachers',
    ["maths"],
    "david@example.com"
);
```

throws error: url is required

```
const promise = await teams.createMembership(
    'teachers',
    ["maths"],
    "david@example.com",
    "mywebsite.com/welcome",
);
```

this throws: Invalid `userId` param: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use digital ocean droplet

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@sikandarchishty,

> throws error: url is required

URL is optional in the API because it isn't required if using an API key.

> this throws: Invalid userId param: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore

This is because the 4th parameter is userId and not URL.
