### ISSUE TITLE
Hire Matt Vaccaro as a Product Engineer!

### ISSUE THREAD

**Issue by MatthewVaccaro** [appwrite/appwrite#8362]
### 🔖 Enhancement description

Appwrite is looking for a strong new [Product Engineer](https://www.appwrite.careers/product-engineer/en) to join the team. I believe I am that engineer! My background as a full stack engineer and product designer, mixed with senior-level communication, can be a huge asset for the Appwrite team.

A few weeks ago, I got to meet Eldad and the team at Render. I knew then and there this was the team I wanted to be on. He encouraged me to apply for the role, and I told him, "I would do one better, I'll learn your product and build something cool with it."

### 🎤 Pitch

I spent 12 hours designing, building, and deploying this project that leverages Appwrite as the backend. I did this to serve as a preview of what I can and will bring to the table when working at Appwrite! I know how to take ownership, collaborate across organizations, and bring the highest level of quality and thoughtfulness. 

### Additional Context
I reached out to a few members of the team on Linked In, but haven't heard back. Since Appwrite loves Github, I decided to try reaching out here.

I'm available for interviews immediately and can start anytime!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Hey @MatthewVaccaro. Thanks for your interest. Applying via the careers page is the best approach. No need to add clutter to the repo.
