### ISSUE TITLE
🐛 Bug Report: "Invalid `passwordSalt` param" when migrating users from Firebase

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#8376]
> that PR solved the previous issue but now it is giving another error
> ```
> "Failed to transfer resource 'zyjCn2PQbYNg5VNfp85Bw47J17I2:user' with message 'Invalid `passwordSalt` param: Value must be a valid string and at least 1 chars and no longer than 128 chars'"" 
> ```
> where "zyjCn2PQbYNg5VNfp85Bw47J17I2:user" is different for each user. Any workaround?

_Originally posted by @cloudoftg0 in https://github.com/appwrite/appwrite/issues/7052#issuecomment-1805419958_

**Comment by PineappleIOnic** [comment]
The fix for this has been merged and implemented, it should arrive in the next patch version of 1.5
