### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by founder-amar-amrouz** [appwrite/appwrite#8386]
### 👟 Reproduction steps

When I wanted to retreive some attribute from a collection so I used **Query.select(['attr-1', 'attr-2', 'attr-3']),** and among its attributes there is a relationships. so the API returns an **AppwriteException**.

- The issue is: when one attribute in **Query.select(['attr-1', 'attr-2', 'attr-3'])** is a relationship attibute the API return an **AppwriteException**.
- Tthe AppwriteException says: ERROR AppwriteException: Invalid query: Attribute not found in schema at Client.

### 👍 Expected behavior

It should retreive even the relashipship attribute since it belong to the collection schema

### 👎 Actual Behavior

...

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Googe cloud machine engine

### 👀 Have you spent some time to check if this issue has been raised before?

- [ ] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ItzNotABug** [comment]
`Query` isn't supported against relationship attributes at the moment.
