### ISSUE TITLE
Swipe back and forward gestures on Firefox for Mac do not work

### ISSUE THREAD

**Issue by saibotma** [appwrite/appwrite#840]
## 🐛 Bug Report

Swipe back and forward gestures on Firefox for Mac do not work when in the appwrite dashboard.

## To Reproduce

Open the dashboard on Firefox for Mac and try to swipe back (to go back) and forward (to go forward).

## Expected behavior

Should go back when swiping back and forward when swiping forward.

## Actual Behavior

Does nothing.

## Your Environment

Firefox 84.0.2 for Mac
Appwrite 0.7.x build from source

**Comment by stnguyen90** [comment]
Thanks for raising this issue! 🙏 We are actually rewriting the Console and the new Console will support back swipe on Firefox. Stay tuned!

**Comment by stnguyen90** [comment]
Closing as this is resolved with our [1.1.0](https://github.com/appwrite/appwrite/releases/tag/1.1.0) release.
