### ISSUE TITLE
🐛 Bug Report: Server Error using Query.limit without Query.cursorAfter/Query.cursorBefore 

### ISSUE THREAD

**Issue by hej2010** [appwrite/appwrite#8419]
### 👟 Reproduction steps

Querying with listDocuments e.g.:

```
const docs = await databases.listDocuments(
   database,
   collection,
   [
      Query.equal("key", "value"),
      Query.limit(5)
   ]
);
```

### 👍 Expected behavior

The query returns at most 5 documents

### 👎 Actual Behavior

Function execution fails with Server Error, general_unknown

Full error:
`{"code":500,"type":"general_unknown","response":{"message":"Server Error","code":500,"type":"general_unknown","version":"1.5.7","file":"/usr/src/code/vendor/utopia-php/database/src/Database/Database.php","line":2621,"trace":[{"file":"/usr/src/code/app/controllers/api/databases.php","line":3011,"function":"getDocument","class":"Utopia\\Database\\Database","type":"->","args":["database_1_collection_8",null]},{"file":"/usr/src/code/vendor/utopia-php/database/src/Database/Validator/Authorization.php","line":166,"function":"{closure}","args":[]},{"file":"/usr/src/code/app/controllers/api/databases.php","line":3011,"function":"skip","class":"Utopia\\Database\\Validator\\Authorization","type":"::","args":[{}]},{"file":"/usr/src/code/vendor/utopia-php/framework/src/App.php","line":531,"function":"{closure}","args":["database","collection",[{},{},{},{}],{},{},"default"]},{"file":"/usr/src/code/vendor/utopia-php/framework/src/App.php","line":705,"function":"execute","class":"Utopia\\App","type":"->","args":[{},{},{}]},{"file":"/usr/src/code/app/http.php","line":257,"function":"run","class":"Utopia\\App","type":"->","args":[{},{}]}]}}`

Docker logs:
```
[Error] Method: GET
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
[Error] Type: TypeError
[Error] Message: Utopia\Database\Database::getDocument(): Argument #2 ($id) must be of type string, null given, called in /usr/src/code/app/controllers/api/databases.php on line 3011
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 2621
```

Added all necessary indexes but it only works if I remove `Query.limit` or add `Query.cursorAfter`/`Query.cursorBefore`.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.5.7, default Docker setup, node-18.0 runtime.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
Hi @hej2010 thanks for the issue

What version of `node-appwrite` you're using?

**Comment by hej2010** [comment]
This is in a function on the server executed from the console, it's not using the node-appwrite SDK (I think).
Using the node-18.0 runtime

**Comment by hej2010** [comment]
Updated to 13.0.0 but it also fails

**Comment by byawitz** [comment]
How many document you have on that collection?

**Comment by hej2010** [comment]
Was a code bug on my end, it has been fixed now :) Was not an issue with Appwrite
