### ISSUE TITLE
🐛 Bug Report: Invite Modal Freezing

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#8437]
### 👟 Reproduction steps

Open any wizard that ends with Submit/Create action.

This is usually for almost all of the modals that make an api request. The problem is that there are visually no progress bar [across console] that show something is already being queued/loaded in the background. 

A frozen UI would usually give a doubt or false scare, take a look below -

https://github.com/user-attachments/assets/17c3a126-bc07-4bcb-843c-1caa66725695

---
Originally raised here - https://discord.com/channels/564160730845151244/1258393263530967120.

### 👍 Expected behavior

Should show a progress bar.

### 👎 Actual Behavior

Does not show a progress bar and makes it look like it froze.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ishuboi07** [comment]
@ItzNotABug working on this issue

**Comment by ItzNotABug** [comment]
> @ItzNotABug working on this issue

Pl. ask the team for assignment on this issue first.

**Comment by Ishuboi07** [comment]
Please assign me this issue

**Comment by asmit27rai** [comment]
@ItzNotABug I want to work on this issue please assign it to me
