### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by anhtaw** [appwrite/appwrite#8457]
### 💭 Description

Questions about the documentation page, Hi everyone, I'm quite impressed with the documentation page, it clearly divides the code language version, can you tell me the code language used for https://appwrite.io/docs/ and the design board, etc. I hope to get help from you guys. I just need the schematic architecture of the website.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
The website is open source: https://github.com/appwrite/website
