### ISSUE TITLE
🐛 Bug Report: Redis takes up to +90% CPU

### ISSUE THREAD

**Issue by ibaraki-douji** [appwrite/appwrite#8464]
### 👟 Reproduction steps

Recreate the redis container with the same settings (for me it's done with WatchTower automaticly or from the Portainer GUI) and recreate ONLY the redis container.

### 👍 Expected behavior

The redis container and the realtime container should be near 1% CPU.

     ID     |     Container Name            | CPU % |    MEM usage    | mem% |   net I/O   |  Storage  | PID
![image](https://github.com/user-attachments/assets/b404f79d-0a64-424e-88d2-ebdd57d2055c)

### 👎 Actual Behavior

The redis container have a high amount of CPU usage as well as the realtime one

     ID     |     Container Name            | CPU % |    MEM usage    | mem% |   net I/O   |  Storage  | PID
![image](https://github.com/user-attachments/assets/f78aca1c-6d7c-4b55-9711-a248cf66b9a1)

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

What usualy trigger the issue is `WatchTower` who will automaticly update the outdated containers.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Related discord thread: https://discord.com/channels/564160730845151244/1268244477454188644

**Comment by ibaraki-douji** [comment]
Resolved with version 1.5.10
