### ISSUE TITLE
🐛 Bug Report: my documents in a collection not found

### ISSUE THREAD

**Issue by mrobeidat** [appwrite/appwrite#8468]
### 👟 Reproduction steps

--

### 👍 Expected behavior

--

### 👎 Actual Behavior

i found my documents deleted at once not even a single doc found, although the related docs are still exist, the posts documents deleted i don't know how and the comments still exist. don't know what really happened!

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Would you please provide details including your project ID, database ID, collection ID, and how many documents you had?
