### ISSUE TITLE
🐛 Bug Report: Unauthorized User GET Request Despite Correct Configuration

### ISSUE THREAD

**Issue by KartikTotlani** [appwrite/appwrite#8469]
### 👟 Reproduction steps

I'm experiencing an issue where a user receives a 401 Unauthorized error when attempting to fetch account details, despite having correct storage, database, project IDs, and URLs. This happens even after the user is authenticated successfully using createEmailSession.
![Screenshot 2024-08-02 213909](https://github.com/user-attachments/assets/063dacbe-5f87-49e1-ab5d-376f39b6dcf1)
![Screenshot 2024-08-02 214016](https://github.com/user-attachments/assets/80e6bd0c-854c-41f7-89d4-573172ca0c64)
![Screenshot 2024-08-02 222955](https://github.com/user-attachments/assets/cfb0df6b-e54e-4c09-9cb5-147943e5a3af)

Error message - 
api.ts:75 
 GET https://cloud.appwrite.io/v1/account 401 (Unauthorized)

api.ts:79 AppwriteException: User (role: guests) missing scope (account)
    at Client.<anonymous> (http://localhost:5173/node_modules/.vite/deps/appwrite.js?v=bb2e0a61:419:17)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:5173/node_modules/.vite/deps/appwrite.js?v=bb2e0a61:13:24)

### 👍 Expected behavior

A 401 Unauthorized error is returned, with the message: "User (role: guests) missing scope (account)".

### 👎 Actual Behavior

The user's account details should be retrieved successfully without a 401 Unauthorized error.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
Hi @KartikTotlani Thanks for opening the issue.

Is this run in the browser?
Where is the error? I can't see the `account.get` method

**Comment by KartikTotlani** [comment]
> Hi @KartikTotlani Thanks for opening the issue.
> 
> Is this run in the browser? Where is the error? I can't see the `account.get` method
Hi @byawitz, thanks for your support! 
Yes this is being run in chrome on my localhost and appwrite configuration is set free to take requests from any address (*).
Just in updated the issue and attached codelet of get account method.

**Comment by Theo-ijoma** [comment]
How do we solve this issues

**Comment by Theo-ijoma** [comment]
Been experiencing this lately how do we solve this issue

**Comment by stnguyen90** [comment]
This error occurs if you're not logged in. Please make sure you have a session before calling `account.get()`. Otherwise, this error is expected. If you still need help, please create a support post on [Discord](https://appwrite.io/discord).

**Comment by KartikTotlani** [comment]
Hi @stnguyen90,
Could you please review the codelet attached in the screenshot above? Specifically, I have called the 'signInAccount()' function, which internally uses 'account.createEmailPasswordSession()' to create a session. Despite following the documentation, I am encountering a 401 Unauthorized error when trying to retrieve the account using 'account.get()'.

Could you help clarify what steps I need to follow or what changes I should make to ensure that the session is created successfully and maintained across requests?
Thank you for your assistance!

**Comment by meoawww** [comment]
Getting the same errors



>  GET https://cloud.appwrite.io/v1/account 401 (Unauthorized)

>  AppwriteException: User (role: guests) missing scope (account)



Despite every details being correct, on email and password auth it works fine on the front end despite the error but when I switch to google OAuth it redirects to success page but only for a split second and comes back to auth/login page.


The error seems to occur in place where we use account.get()


Here's how I have implemented, on sveltekit
```
async function getUserId() {
        try {
            const user = await account.get();
            return user.$id;
        } catch (error) {
            console.error('Error getting current user:', error);
            return null;
        }
    }

  
  onMount(async () => {
    if (browser) {
      try {
        userId = await getUserId();
    } catch (error) {
      console.error('Error during authentication from dashboard/+layout.svelte:', error);
          goto('/auth');
          }
    }
  });

```

**Comment by meoawww** [comment]
for some reason this seems to only not work on brave browser and safari(not sure about the other browsers firefox....). I tried it with edge and chrome it works fine over there.
