### ISSUE TITLE
🐛 Bug Report: Fetching Wrong Documents

### ISSUE THREAD

**Issue by salmansheri** [appwrite/appwrite#8471]
### 👟 Reproduction steps

When I try to fetch my appointments documents, it shows some incorrect counts even though the collection is empty

![appointmentcollection](https://github.com/user-attachments/assets/34c1677f-3f07-4573-8df2-bff76658d7a8)

My Appointment Collection is empty 

My Code: 

```js
 const appointments = await databases.listDocuments(
      DATABASE_ID as string, 
      APPOINTMENT_COLLECTION_ID as string, 
      [Query.orderDesc("$createdAt")]
     
    )
```

Here I am Fetching my appoitments data but it is showing a fake document 

Here I am Logging the count of the document 

```js
// Logging the documents length 
    console.log(appointments.documents.length
```

output: 

![admin](https://github.com/user-attachments/assets/1dc7df23-5369-44d4-8af4-a8cd6a49fe0e)

instead fetching the new documents it fetches and gives old document 

  

### 👍 Expected behavior

I Need to fetch new document 

### 👎 Actual Behavior

It fetches old document

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Nextjs 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@salmansheri, thanks for raising this issue! 🙏🏼 Some questions:

1. Are you using Next.js? Next.js does some caching so maybe the data is being cached.
2. Would you please log the endpoint, project ID, database id, and collection ID and share screenshots from the Appwrite Console for validation?

**Comment by JAWAD018** [comment]
i also face this issue but i understand this happen because of caching the data is being cached

**Comment by docimin** [comment]
> @salmansheri i also face this issue but i understand this happen because of caching the data is being cached

In case you are using Next.js: I recommend fetching data via client side. Not only does this fix your caching issue, but is more recommended. Unless you specifically need it on the server, you could add this to the page/function: https://nextjs.org/docs/app/api-reference/functions/unstable_noStore
