### ISSUE TITLE
How can I delete a user?

### ISSUE THREAD

**Issue by ClimenteA** [appwrite/appwrite#848]
I'm trying appwrite, just installed it added the python sdk from pypi and I'm at the part where I'm trying to delete a user.
I didn't saw in the documentation din option (only delete user session).

Do you have some repo examples of appwrite + python?

![image](https://user-images.githubusercontent.com/9250009/105736368-61008580-5f3d-11eb-8a4e-403f0e697406.png)

---
Appwrite Version: 0.6.2.125

**Comment by eldadfux** [comment]
@ClimenteA please check: #538 #378
