### ISSUE TITLE
Running the docker command on the homepage fails on clamav...

### ISSUE THREAD

**Issue by jeffmikels** [appwrite/appwrite#849]
## 🐛 Bug Report

Attempting to run the docker install command on the appwrite homepage leads to this error:

```
ERROR: for clamav  Cannot start service clamav: failed to create endpoint appwrite_clamav_1 on network appwrite_appwrite: failed to add the host (vetheeb8eef) <=> sandbox (veth8a11fb7) pair interfaces: operation not permitted
```

I'm running `Docker version 19.03.13-ce, build 4484c46d9d` on Arch Linux.

## Have you spent some time to check if this issue has been raised before?

Yes... searched google and searched these issues

**Comment by jeffmikels** [comment]
Running the command a second time appears to successfully complete.

**Comment by eldadfux** [comment]
Seems like the ClamAV team had some network issues, closing this for now.
