### ISSUE TITLE
Upgrade documentation confusing

### ISSUE THREAD

**Issue by pspierce** [appwrite/appwrite#850]
## 📚 Documentation

Upgrade documentation says:
`Upgrade
If you are upgrading your Appwrite server from an older version, you should use the Appwrite migration tool once your setup is completed. Make sure to run this tool after you already finished setting up the new version, `**as mentioned above.**

There is no "above" as this is the first paragraph on the page and therefore there are no clear instructions on setting up a new version.  I understand the migrate script; however, that does not specify how you go about upgrading the installation, just migrating the data after you do so.  I believe this assumes you are using a git clone and would use git pull to update your docker-compose file?  That wouldn't be the case for most people as that is not the installation instructions, which have you run a docker command to pull the images.

I still don't know how I'm supposed to update my install?

## Have you spent some time to check if this issue has been raised before?

yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

yes

**Comment by TorstenDittmann** [comment]
Hey @pspierce 👋🏻 

You're right, there's a bit of catching up to do on that page.

The migration script takes the current database structure & co and adapts it to a new version. Meaning it is supposed to be run, once you installed the new version with the commands found [here](https://appwrite.io/docs/installation). The `above` is targeted to the previous sentence and doesn't really makes that much sense 😄 

So the upgrade workflow is like this:
- shutdown the Appwrite instance
- overwrite current docker-compose.yml file with the install commands
- start Appwrite
- run the migration script
- done 🙂 

We will revise the page before the next release 👍🏻

**Comment by eldadfux** [comment]
Version 0.7 has been released and docs on the homepage are now up-to-date: https://appwrite.io/docs/upgrade
