### ISSUE TITLE
🐛 Bug Report: Creating new function with new Repo results in error - Unable to clone code repository: fatal: invalid refspec '0.1.*'

### ISSUE THREAD

**Issue by Re-Shard** [appwrite/appwrite#8512]
### 👟 Reproduction steps

I am trying to create a new function for Node 18, with a new repo on my github. What ever i try to do, i keep getting an error on the build log

### 👍 Expected behavior

Create the function, with the repo.

### 👎 Actual Behavior

In the build log of the function.

Unable to clone code repository: fatal: invalid refspec '0.1.*'

/usr/src/code/vendor/appwrite/server-ce/src/Appwrite/Platform/Workers/Builds.php:247
#0 /usr/src/code/vendor/appwrite/server-ce/src/Appwrite/Platform/Workers/Builds.php(93): Appwrite\Platform\Workers\Builds->buildDeployment(Object(Utopia\Storage\Device\DOSpaces), Object(Appwrite\Event\Func), Object(Appwrite\Event\Event), Object(Appwrite\Event\Usage), Object(Appwrite\Cloud\Database\ProxyDatabase), Object(Appwrite\Cloud\Database\ProxyDatabase), Object(Utopia\VCS\Adapter\Git\GitHub), Object(Utopia\Database\Document), Object(Utopia\Database\Document), Object(Utopia\Database\Document), Object(Utopia\Database\Document), Object(Utopia\Logger\Log))
#1 /usr/src/code/vendor/appwrite/server-ce/src/Appwrite/Platform/Workers/Builds.php(55): Appwrite\Platform\Workers\Builds->action(Object(Utopia\Queue\Message), Object(Appwrite\Cloud\Database\ProxyDatabase), Object(Appwrite\Event\Event), Object(Appwrite\Event\Func), Object(Appwrite\Event\Usage), Object(Utopia\Cache\Cache), Object(Appwrite\Cloud\Database\ProxyDatabase), Object(Utopia\Storage\Device\DOSpaces), Object(Utopia\Logger\Log))
#2 /usr/src/code/vendor/utopia-php/queue/src/Queue/Server.php(248): Appwrite\Platform\Workers\Builds->Appwrite\Platform\Workers\{closure}(Object(Utopia\Queue\Message), Object(Appwrite\Cloud\Database\ProxyDatabase), Object(Appwrite\Event\Event), Object(Appwrite\Event\Func), Object(Appwrite\Event\Usage), Object(Utopia\Cache\Cache), Object(Appwrite\Cloud\Database\ProxyDatabase), Object(Utopia\Storage\Device\DOSpaces), Object(Utopia\Logger\Log))
#3 [internal function]: Utopia\Queue\Server->Utopia\Queue\{closure}('0')
#4 /usr/src/code/vendor/utopia-php/queue/src/Queue/Adapter/Swoole.php(37): call_user_func(Object(Closure), '0')
#5 [internal function]: Utopia\Queue\Adapter\Swoole->Utopia\Queue\Adapter\{closure}(Object(Swoole\Process\Pool), '0')
#6 {main}

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eliuddyn** [comment]
I am getting the same error 😭😭

**Comment by onlineselfbusiness** [comment]
I too facing the same error, tried many times but same error message,  please help us how to proceed further.

**Comment by stnguyen90** [comment]
You can follow https://github.com/appwrite/console/issues/1279 for updates.

Closing this as a duplciate.
