### ISSUE TITLE
📚 Documentation: About Building

### ISSUE THREAD

**Issue by anthony-china** [appwrite/appwrite#8513]
### 💭 Description

May I ask if there is a self-hosted local deployment document?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
Hi @anthony-china 
Check 
- https://appwrite.io/docs/advanced/self-hosting
- https://github.com/appwrite/appwrite/blob/main/CONTRIBUTING.md#setup-from-source
