### ISSUE TITLE
🐛 Bug Report: Github function doesn't work anymore 

### ISSUE THREAD

**Issue by bourvill** [appwrite/appwrite#8534]
### 👟 Reproduction steps

After https://github.com/appwrite/appwrite/issues/8510
Upgrade to 1.5.10

Deploying function is broken.

I remove and reinstall following this https://appwrite.io/docs/advanced/self-hosting/functions

But I Got this error

![Capture d’écran 2024-08-13 à 22 18 11](https://github.com/user-attachments/assets/6fbc9878-ca0d-48ac-be54-086f7cc96798)

And on my server

appwrite                           | [Error] Timestamp: 2024-08-13T20:14:06+00:00
appwrite                           | [Error] Method: GET
appwrite                           | [Error] URL: /v1/vcs/github/callback
appwrite                           | [Error] Type: Ahc\Jwt\JWTException
appwrite                           | [Error] Message: Signing key cannot be empty
appwrite                           | [Error] File: /usr/src/code/vendor/adhocore/jwt/src/ValidatesJWT.php
appwrite                           | [Error] Line: 34

### 👍 Expected behavior

Github deploys function work 

### 👎 Actual Behavior

Link between Github and Function seem to be broken

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Would you please compare the github private key between your current .env file and the previous one to see if there's a difference?

**Comment by bourvill** [comment]
Look like private key was altered during upgrade or migration.

it's work again.

thank for your quick response
