### ISSUE TITLE
🐛 Bug Report: images is not getting previewed in smartphone browser like safari and chrome

### ISSUE THREAD

**Issue by JAWAD018** [appwrite/appwrite#8536]
### 👟 Reproduction steps

its getting previewed in windows and not getting previewed in mobile browser

### 👍 Expected behavior

image should previewed in smart phone browser 

### 👎 Actual Behavior

image is not showing 

![aea11647-25d9-4178-9509-60197330ca23](https://github.com/user-attachments/assets/2b97c39c-ffe6-4066-857d-3c2d0dffd78b)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@JAWAD018, thanks for raising this issue! 🙏🏼 You're probably facing a 3rd party cookie problem. To solve that, you'll need a [custom domain](https://appwrite.io/docs/advanced/platform/custom-domains). Do you have one set up yet?

**Comment by JAWAD018** [comment]
@stnguyen90 not yet

**Comment by byawitz** [comment]
@JAWAD018 You'll need to add that one as well.
After deployment you can then replace or delete it.

**Comment by stnguyen90** [comment]
> @stnguyen90 not yet i using vercel default domain

@JAWAD018, you need your own custom domain to get it to work in production. Otherwise, you can try looking into updating your browser to enable third party cookies.

**Comment by JAWAD018** [comment]
@stnguyen90 Thanks i am closing this issue
