### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by lcy101u** [appwrite/appwrite#8559]
### 👟 Reproduction steps

When I try messaging function, but did not get any email

### 👍 Expected behavior

Should get email

### 👎 Actual Behavior

never get email

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I use appwrite platfrom to send.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by GhoulKingR** [comment]
What SMTP service did you use for sending the email

**Comment by lcy101u** [comment]
sendGrid

**Comment by stnguyen90** [comment]
@lcy101u, thanks for creating this issue! 🙏🏼 Did you [set up domain authentication](https://www.twilio.com/docs/sendgrid/ui/account-and-settings/how-to-set-up-domain-authentication) or [verify the sender](https://www.twilio.com/docs/sendgrid/ui/sending-email/sender-verification)? 

Besides that, make sure to check your spam folder to make sure it's not getting added in there.
