### ISSUE TITLE
🐛 Bug Report: The requested route was not found. Please refer to the API docs and try again.

### ISSUE THREAD

**Issue by Shiba-Kar** [appwrite/appwrite#8566]
### 👟 Reproduction steps

Running `appwrite run functions`

### 👍 Expected behavior

run local fuction development 

### 👎 Actual Behavior

CLI Error:
```
Error: The requested route was not found. Please refer to the API docs and try again.
    at Client.call (/snapshot/sdk-for-cli/lib/client.js:211:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async projectsCreateJWT (/snapshot/sdk-for-cli/lib/commands/projects.js:738:16)
    at async Object.setup (/snapshot/sdk-for-cli/lib/emulation/utils.js:124:34)
    at async runFunction (/snapshot/sdk-for-cli/lib/commands/run.js:146:5)
```

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

CLI version: 6.0.0-rc.1
Operation System: Darwin
Appwrite version: 1.5.10
Is Cloud: No

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
Hey @Shiba-Kar, Thanks for opening the issue.

You're using the `rc` version of the CLI, which has some features that have yet to be integrated into the latest stable Appwrite version.

Ensure that the latest stable version of the CLI is installed by following the [installation instructions ](https://appwrite.io/docs/tooling/command-line/installation) here.
