### ISSUE TITLE
🐛 Bug Report: "Users.createSession()" returns invalid session secret

### ISSUE THREAD

**Issue by JoshiJoshiJoshi** [appwrite/appwrite#8569]
### 👟 Reproduction steps

1. Create a session via "Users.createSession()"
2. Set the session secret in "Client.setSession()"
3. Call "Accounts.get()"

### 👍 Expected behavior

No error.
Get a valid user object response back.

### 👎 Actual Behavior

**Error => "User (role: guests) missing scope (account)"**

Session secret when creating one  via "Users.createSession()"
![image](https://github.com/user-attachments/assets/d709d297-07b4-4961-b2db-5fc1e9a90a24)

Session secret when creating one via "Account.createEmailPasswordSession()"
![image](https://github.com/user-attachments/assets/519a9cb7-cc2a-4bf4-9f64-02711e37fb17)

The one from "Users.createSession()" is not properly encoded and therefore not returned as JWT.

Users.createSession()
https://github.com/appwrite/appwrite/blob/9301bddd8b161e6f4207e4b86d9908cacbdf9ef0/app/controllers/api/users.php#L1815

Account.createEmailPasswordSession()
https://github.com/appwrite/appwrite/blob/9301bddd8b161e6f4207e4b86d9908cacbdf9ef0/app/controllers/api/account.php#L808

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@JoshiJoshiJoshi, thanks for creating this issue! 🙏

For reference, our related thread: https://discord.com/channels/564160730845151244/1275767033576947742

**Comment by pingu2k4** [comment]
Interested to see the fix (#9019) in live - as I was also witnessing that sessions would not be attributed to a user but would be created, and would show up when a session is later created using a different method for that user.
