### ISSUE TITLE
🐛 Bug Report: Google OAuth2 verification process

### ISSUE THREAD

**Issue by maxselladvisor** [appwrite/appwrite#8578]
### 👟 Reproduction steps

When I go to my google Oauth consent screen, it tells me that the app appwrite has not conclude the google verification process, how can I solve this

### 👍 Expected behavior

.

### 👎 Actual Behavior

.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@maxselladvisor, thanks for creating this issue! 🙏🏼 Perhaps [this](https://appwrite.io/integrations/oauth-google) guide will be helpful for you.
