### ISSUE TITLE
🐛 Bug Report: Invalid 'userId' param

### ISSUE THREAD

**Issue by Sanjay-2004** [appwrite/appwrite#8579]
### 👟 Reproduction steps

I'm trying to use Appwrite in React-Native and this is the code:
```import { Account, Avatars, Client, Databases, ID } from "react-native-appwrite";

export const appwriteConfig = {
  endpoint: "https://your-endpoint-url/v1", // Replace with your endpoint URL
  platform: "com.yourapp.identifier", // Replace with your platform identifier
  projectId: "your-project-id", // Replace with your project ID
  databaseId: "your-database-id", // Replace with your database ID
  userCollectionId: "your-user-collection-id", // Replace with your user collection ID
  videoCollectionId: "your-video-collection-id", // Replace with your video collection ID
  storageId: "your-storage-id", // Replace with your storage ID
};

const client = new Client();

client
  .setEndpoint(appwriteConfig.endpoint)
  .setProject(appwriteConfig.projectId)
  .setPlatform(appwriteConfig.platform);

const account = new Account(client);
const avatars = new Avatars(client);
const databases = new Databases(client);

export const signIn = async (email, password) => {
  try {
    const session = await account.createSession(email, password);
    if (!session) {
      throw new Error("Sign in failed");
    }
    return session;
  } catch (error) {
    console.log(error);
    throw new Error(error);
  }
};

export const createUser = async (email, password, username) => {
  try {
    const userId = ID.unique();
    console.log(userId);
    const newAccount = await account.create(userId, email, password, username);

    if (!newAccount) {
      throw new Error("Account creation failed");
    }

    const avatarUrl = avatars.getInitials(username);

    await signIn(email, password);

    const newUser = await databases.createDocument(
      appwriteConfig.databaseId,
      appwriteConfig.userCollectionId,
      ID.unique(),
      {
        accountId: newAccount.$id,
        email,
        username,
        avatar: avatarUrl,
      }
    );

    return newUser;
  } catch (error) {
    console.log("Error here");
    console.log(error);
    throw new Error(error);
  }
};
```

### 👍 Expected behavior

The account would be created and user would be signed in.

### 👎 Actual Behavior

Gives this error:

 LOG  {"email": "temp@gmail.com", "password": "12345678", "username": "tempuser"}
 LOG  66caf49c001766f82d02
 LOG  [AppwriteException: Invalid `userId` param: Parameter must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can't start with a special char]

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Sanjay-2004, thanks for creating this issue! 🙏🏼 It looks like you're passing `email` and `password` to `account.createSession()` when that method is supposed to accept `userId` and `secret`. To log in with email and password, you should be using the [`account.createEmailPasswordSession()`](https://appwrite.io/docs/references/cloud/client-web/account#createEmailPasswordSession).

BTW, the best place to get support is [Discord](https://appwrite.io/discord).
