### ISSUE TITLE
🚀 Enhancement: Set Custom Cookie Name 

### ISSUE THREAD

**Issue by gtrabanco** [appwrite/appwrite#8588]
### 🔖 Enhancement description

I suggest a way to set the custom cookie name when using client side appwrite package. This would be useful to use authenticated sessions against our server using SSR without sending and exposing the token in the client code.

### 🎤 Pitch

This would be very useful also to avoid bandwidth consumption in both sides, our hosting provider and our backend on Appwrite (cloud or self hosted).

Another possibility it is to not make private pages code available without being authenticated in our server but keeping client side capabilities of Appwrite. This means less work while switching between SSR & CRS whenever it is more interesting for you.

Example: Deploy code based on Feature Flags, a new feature you do not want to send render based on client side only authentication because the code will be sended to the client. So you can redirect and use SSR to redirect and serve the page but not if the user is not auth but maybe you want that component to read directly stuff from the backend, create documents or whatever...

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by barart** [comment]
You can set the cookie name whatever you want, this is not a feature of appwrite, so you can lead them the way you want
