### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by terrencehlabane** [appwrite/appwrite#8591]
### 👟 Reproduction steps

Hi can you please help with the following error AppwriteException: User (role: guests) missing scope (account)]

### 👍 Expected behavior

It happens when I press the button SignIn
Should create:  const session = await account.createEmailPasswordSession(email, password);

### 👎 Actual Behavior

 LOG  [Error: AppwriteException: User (role: guests) missing scope (account)]

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

"react-native-appwrite": "^0.4.0",

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@terrencehlabane, thanks for raising this issue! 🙏🏼

> User (role: guests) missing scope (account)]

This error is not thrown when you call `account.createEmailPasswordSession(email, password)`. It is thrown by something else that requires a session, but one does not exist.

If you need help, please search [Discord](https://appwrite.io/discord) and create a support post if you're still stuck.
