### ISSUE TITLE
Documents inherit or default to Collection Permissions

### ISSUE THREAD

**Issue by pspierce** [appwrite/appwrite#861]
## 🚀 Feature

Document permissions, unless changed, hold the permissions of the Collection they are under.  

## Have you spent some time to check if this issue has been raised before?

Similar to #371, but not exactly.  

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch
For many of my use cases, I won't need separate permissions for each Document under a Collection  If the permissions on a Document are null, then the permissions of the Collection should be applied.  I see the need for row-level permissions; however, they seem more an exception.  If you are using the UI to build out things like page navigation, it adds a lot of busy work to set each Document's permissions.

**Comment by eldadfux** [comment]
With the release of the new database in Appwrite 0.12 we have introduced the concept of permission models. This should make the difference between collection-level permissions to document-level permission much simpler. You can learn more about it here: https://appwrite.io/docs/database#permissions

You can learn more about the new version here: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
