### ISSUE TITLE
🚀 Enhancement: Databases, NoSQL DB

### ISSUE THREAD

**Issue by yairyairyair** [appwrite/appwrite#8612]
### 🔖 Enhancement description

I want to be able to store documents in my database same as now but these are JSON documents. want a no-sql database.

### 🎤 Pitch

In my use case i just need to store JSONs, currently storing as string and encoding and decoding to json in my functions.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@yairyairyair, thanks for raising this issue! 🙏🏼 I'm going to close this in favor of https://github.com/appwrite/appwrite/issues/909. It would be best if you added a 👍🏼 to the other issue and comment with your exact use case that requires a NoSQL database.
