### ISSUE TITLE
i dont see add bucket option

### ISSUE THREAD

**Issue by AyUsHh66** [appwrite/appwrite#8621]
![image](https://github.com/user-attachments/assets/b8018afe-3410-4d36-b2a7-7e29a7d317c4)
i am getting missing bucket id error but i dont see a add bucket id option in the storage section!
please help

---
Appwrite Version: 0.12.0.200

**Comment by byawitz** [comment]
Hey @AyUsHh66 Thanks for opening the issue

This is an old version of Appwrite, please consult the official docs for up-to-date installation [instruction](https://appwrite.io/docs/advanced/self-hosting)
