### ISSUE TITLE
🐛 Bug Report: Getting 502 Bad gateway always while trying to create file/upload in storage using appwrite cloud in React project 

### ISSUE THREAD

**Issue by Mani1211** [appwrite/appwrite#8644]
### 👟 Reproduction steps

When i try to upload image using appwrite cloud sdk in my react project always getting 502 bad gateway error even i tried to upload directly using the appwrite cloud dashboard getting the same issue

### 👍 Expected behavior

File upload should happen

### 👎 Actual Behavior

Getting 502 gateway  error

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Mani1211, thanks for creating this issue! 🙏🏼, What's your upload speed when you use https://speedtest.net against Frankfurt?
