### ISSUE TITLE
🐛 Bug Report: network error on uploading file larger than 3 mb

### ISSUE THREAD

**Issue by Magar0** [appwrite/appwrite#8645]
### 👟 Reproduction steps

when I try uploading any file like jpg or mp4 bigger than 3 mb , I get bad request error. Small file less than 2 mb gets uploaded easily. I am not using any API. I am trying to upload directly through appwrite website. Please solve it. I even tried changing the permission , but didn't work.

### 👍 Expected behavior

It should upload without any problem upto  the size limit we set.

### 👎 Actual Behavior

Got Error showing Bad request on uploading file bigger than 3 mb

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I am trying uploading through appwrite website.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by tessamero** [comment]
@Magar0 can you send me the file you are trying to upload on Discord? (My username is @tessa.a). I just want to test further. 

I tried to replicate this on free tier appwrite cloud with 4mb files/larger files and it works fine on my end. I’m also on very slow hotel WiFi at the moment.

**Comment by Magar0** [comment]
Thanx for checking, there was some issue with appwrite when trying to upload any file( jpg,mp4, etc.) larger than 3mb, showed Bad request error. But now it has been resolved, now its working. I am able to upload larger file now.

**Comment by Magar0** [comment]
Thanx for checking, there was some issue with appwrite when trying to upload any file( jpg,mp4, etc.) larger than 3mb, showed Bad request error. But now it has been resolved, now its working. I am able to upload larger file now.
