### ISSUE TITLE
🐛 Bug Report: trying to connect GitHub to functions

### ISSUE THREAD

**Issue by AidenY69** [appwrite/appwrite#8650]
### 👟 Reproduction steps

Try to connect an organization GitHub to the functions on a self hosted AppWrite (1.5.10)

### 👍 Expected behavior

Able to install the GitHub App to be able to connect to the Appwrite

### 👎 Actual Behavior

an error comes up that says: 

```
Error 500
Server Error

Type

general_unknown

```

after clicking accept installation on github and the page redirects back to the appwrite console

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@AidenY69, would you please check the docker logs for your `appwrite` container and share the details around the 500 error?

**Comment by tiberiu89** [comment]
I have the same issue, tried with a fresh setup via docker-compose. Version is 1.6.0. Setup github app according to docs. Callback URLs in the right order

I'm running on localhost with ngrok. I've changed _APP_DOMAIN to point to ngrok endpoint. Application works fine otherwise, github app is installed, but it seems it cannot complete the setup due to this error

![Image](https://github.com/user-attachments/assets/4b7c05b5-f4fd-4846-bfbe-cf4f5182ced8)

**Comment by KevinRohn** [comment]
I have the same issue. I also double checked the key, secret etc.

**Comment by erykkruk** [comment]
I have the same issues, nothing has changed since 15th Dec 2024?

**Comment by vltmedia** [comment]
We still have the same problem

**Comment by ddenev** [comment]
Still having the same problem in v1.6.2.

@eldadfux , is anyone from Appwrite team going to review this issue? It was reported almost a year ago.

thank you in advance!

**Comment by ddenev** [comment]
Update:

It turned out the private key in .env was not correctly formatted. running `docker compose up -d` fixed it. See this thread for more info: https://discord.com/channels/564160730845151244/1376891094054469772/1376891094054469772
