### ISSUE TITLE
🐛 Bug Report: Support ticket not working on appwrite 

### ISSUE THREAD

**Issue by meal777** [appwrite/appwrite#8654]
### 👟 Reproduction steps

Receive an error every time I try to submit a support ticket

### 👍 Expected behavior

Receive an error every time I try to submit a support ticket

### 👎 Actual Behavior

Receive an error every time I try to submit a support ticket

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@meal777, thanks for creating this issue! 🙏🏼 Do you have your name set for your Appwrite account? If not, please set one.
