### ISSUE TITLE
🐛 Bug Report: Function timed out during cold start

### ISSUE THREAD

**Issue by Y055EF** [appwrite/appwrite#8655]
### 👟 Reproduction steps

run an execution to my function

### 👍 Expected behavior

it return the expected result

### 👎 Actual Behavior

but it always returns this error: Function timed out during cold start.\nError Code: 400

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

hosting functions

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
Hi @Y055EF, thanks for opening the issue.

Can you please elaborate more by sharing your function code?

Also, you might want to post a support ticket in our Discord channel at https://appwrite.io/discord
