### ISSUE TITLE
🐛 Bug Report: Unexpected Behavior in Appwrite Bucket Permissions

### ISSUE THREAD

**Issue by sozenstrapi** [appwrite/appwrite#8656]
### 👟 Reproduction steps

Dear Appwrite Team,

I've encountered an unexpected behavior with bucket permissions in Appwrite. Here's a detailed description of the issue:
1. Issue Description:
   When setting bucket permissions, I've noticed that granting READ access to "Users" and a specific user is not sufficient for file access. The files remain inaccessible (401 Unauthorized error) until I also grant READ permission to "Any" (public access).
-- Security Concerns:
   This behavior forces the exposure of files to public access, which may not be desirable in many use cases and could pose security risks.

I would greatly appreciate your insights into this issue. Is this the intended behavior, or could it be a bug in the permission system?

Thank you for your attention to this matter.

Best regards,

### 👍 Expected behavior

2. Expected Behavior:
   I expected that granting READ permission to "Users" and a specific user would be sufficient for authenticated users to access the files.

### 👎 Actual Behavior

3. Actual Behavior:
   Files are only accessible when READ permission is granted to "Any", even when "Users" and specific user permissions are set.
4. Steps to Reproduce:
   a. Create a new bucket or use an existing one
   b. Set READ permission for "Users" and a specific user
   c. Attempt to access a file in the bucket as an authenticated user
   d. Observe 401 Unauthorized error
   e. Add READ permission for "Any"
   f. File becomes accessible

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

5. Environment:
   - Appwrite Version: [Your Appwrite version]
   - Deployment: [Self-hosted/Cloud]
   - Frontend Framework: [If applicable]
   - Appwrite SDK Version: [If using SDK]

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@sozenstrapi, thanks for creating this issue! 🙏🏼 How exactly are you accessing the file? If you're doing it via the web, the problem could be due to 3rd party cookies. Since Appwrite uses cookies for session handling, if the browser doesn't send the cookie in the request for the image, the request is made as an unauthenticated user, so they wouldn't be able to access files restricted to "Users".

**Comment by sergioponguta** [comment]
I'm having this same issue on 1.6. Have to put everything with "any" permissions. 

I did enable 3rd party cookies but even with that is not working
