### ISSUE TITLE
🐛 Bug Report: Session Secret not Passed without API key

### ISSUE THREAD

**Issue by RyanBaig** [appwrite/appwrite#8673]
### 👟 Reproduction steps

1. Code:
```js
const client = new Appwrite.Client()
    .setEndpoint('https://cloud.appwrite.io/v1') // Your API Endpoint
    .setProject('project-id'); // Your project ID 

const account = new Appwrite.Account(client);

const email = document.getElementById('email').value; // Get the email value
const password = document.getElementById('password').value; // Get the password value
const result = await account.createEmailPasswordSession(email, password);
console.log(result);
```

### 👍 Expected behavior

(copied from Docs):
```json
{
    "$id": "5e5ea5c16897e",
    "$createdAt": "2020-10-15T06:38:00.000+00:00",
    "$updatedAt": "2020-10-15T06:38:00.000+00:00",
    "userId": "5e5bb8c16897e",
    "expire": "2020-10-15T06:38:00.000+00:00",
    "provider": "email",
    "providerUid": "user@example.com",
    "providerAccessToken": "MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3",
    "providerAccessTokenExpiry": "2020-10-15T06:38:00.000+00:00",
    "providerRefreshToken": "MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3",
    "ip": "127.0.0.1",
    "osCode": "Mac",
    "osName": "Mac",
    "osVersion": "Mac",
    "clientType": "browser",
    "clientCode": "CM",
    "clientName": "Chrome Mobile iOS",
    "clientVersion": "84.0",
    "clientEngine": "WebKit",
    "clientEngineVersion": "605.1.15",
    "deviceName": "smartphone",
    "deviceBrand": "Google",
    "deviceModel": "Nexus 5",
    "countryCode": "US",
    "countryName": "United States",
    "current": true,
    "factors": [
        "email"
    ],
    "secret": "5e5bb8c16897e",
    "mfaUpdatedAt": "2020-10-15T06:38:00.000+00:00"
}
```

### 👎 Actual Behavior

```json
{
    "$id": "66e81dad54a7867717f0",
    "$createdAt": "2024-09-16T11:59:41.356+00:00",
    "$updatedAt": "2024-09-16T11:59:41.356+00:00",
    "userId": "66e68b2600195618e60d",
    "expire": "2024-09-19T11:59:41.346+00:00",
    "provider": "email",
    "providerUid": "my_email@gmail.com",
    "providerAccessToken": "",
    "providerAccessTokenExpiry": "",
    "providerRefreshToken": "",
    "ip": "11.11.111.111",
    "osCode": "LIN",
    "osName": "GNU/Linux",
    "osVersion": "",
    "clientType": "browser",
    "clientCode": "CH",
    "clientName": "Chrome",
    "clientVersion": "128.0",
    "clientEngine": "Blink",
    "clientEngineVersion": "128.0.0.0",
    "deviceName": "desktop",
    "deviceBrand": "",
    "deviceModel": "",
    "countryCode": "pk",
    "countryName": "Pakistan",
    "current": true,
    "factors": [
        "password"
    ],
    "secret": "",
    "mfaUpdatedAt": ""
}
```
the `secret` key **IS EMPTY**, along with some other keys.

A person told me it's because it "only returns a secret when it is being request by an api key".
But that seems a bit hard, considering you **cannot** put an API key in the client web SDK.
I would also like to mention that the secret is included in the `X-Fallback-Cookies` Header, so why not include it in the SDK as well? (see screenshot)
![image](https://github.com/user-attachments/assets/0f187343-194c-4aff-af6f-438759d0cafa)

It would make sense that the secrets are not returned when using endpoints like `listSessions` but it should be returned for endpoint where the user creates a session (e.g `createEmailPasswordSession`)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

```
VERSION: 16.0.0
SDK VERSION: 16.0.0
ENVIRONMENT: VERCEL
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@RyanBaig, thanks for creating this issue! 🙏🏼 This is the expected behavior. Appwrite primarily uses cookies for the session so there is no need for the client to have the secret in javascript code.

The fallback header is used during development when cookies may not work properly because of 3rd party cookie problems. In production, a [custom domain](https://appwrite.io/docs/advanced/platform/custom-domains) should be used.

**Comment by hej2010** [comment]
Returning the session secret using client SDKs would be very helpful when using SSR since you can't get the session by ID using an API key, and using an admin client with `createEmailPasswordSession` bypasses the rate limits:
```js
const account = new Account(clientSession);
const accountAdmin = new Account(clientAdmin);
let session = await account.createEmailPasswordSession(body.email, body.password); // no secret is returned here
session = await accountAdmin.getSession(session.$id); // this doesn't work, returns "AppwriteException: app.X@domain.com (role: applications) missing scope (account)
session = await accountAdmin.createEmailPasswordSession(body.email, body.password); // this works but bypasses the rate limits

setCookie(event, SESSION_COOKIE, session.secret, {
   expires: new Date(session.expire),
   path: "/",
   httpOnly: true,
   secure: true,
   sameSite: "lax",
 });
```
And there is no `getSession('sessionID')` method available in the `Users` service.
