### ISSUE TITLE
🐛 Bug Report: Appwrite 1.6.0 Internal curl errors has occurred within the executor Number: 28

### ISSUE THREAD

**Issue by VTFLAB** [appwrite/appwrite#8698]
### 👟 Reproduction steps

Self-hosting Appwrite: Upgrade from 1.5.11 to 1.6.0

Executing any function from self-hosted Appwrite

### 👍 Expected behavior

Success Execute Function

### 👎 Actual Behavior

```
Internal curl errors has occurred within the executor! Error Number: 28. Error Msg: Failed to connect to 66ed3799485a2 port 3000 after 5001 ms: Timeout was reached\nError Code: 500
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Network:

Client ⇔ CloudFlare ⇔ Router ⇔ NginxProxyManager ⇔ Appwrite Traefik(add trust npm ip 80 443)

I am self-hosting Appwrite with Docker. Functions that were working correctly in version 1.5.11 are now all returning the following error in version 1.6.0:

```
Internal curl errors have occurred within the executor! Error Number: 28. Error Msg: Failed to connect to 66ed3a87e3680 port 3000 after 5000 ms: Timeout was reached\nError Code: 500
```

What is this error, and how can I resolve it? Even the simplest function source code results in the same error. Below is one of the function codes:

---

### node-21.0
```javascript
export default async ({ req, res, log, error }: any) => {
  log(`req: ${JSON.stringify(req)}`);
  log(`res: ${JSON.stringify(res)}`);

  // ! test
  return res.empty();
};
```

### openruntimes-executor Logs

```log
Removing orphan runtimes and networks...

Cleaning up containers and networks...

No containers found to clean up.

Cleanup finished.

Orphan runtimes and networks removal finished.

Creating networks...

Network runtimes already exists

No matching executor found. Please check the value of OPR_EXECUTOR_IMAGE. Executor will need to be connected to the runtime network manually.

Pulling v4 images...

Warming up Node.js 21.0 environment...

Warming up Ruby 3.3 environment...

Warming up Python 3.12 environment...

Warming up Deno 1.40 environment...

Warming up Dart 3.3 environment...

Warming up .NET 7.0 environment...

Warming up C++ 20 environment...

Warming up Bun 1.0 environment...

Successfully Warmed up Python 3.12!

Successfully Warmed up .NET 7.0!

Successfully Warmed up Bun 1.0!

Successfully Warmed up Deno 1.40!

Successfully Warmed up Ruby 3.3!

Successfully Warmed up C++ 20!

Successfully Warmed up Node.js 21.0!

Successfully Warmed up Dart 3.3!

Image pulling finished.

Starting maintenance interval...

Maintenance interval started.

Starting stats interval...

Stats interval started.

Executor is ready.

[Error] Type: Exception

[Error] Message: Internal curl errors has occurred within the executor! Error Number: 28. Error Msg: Failed to connect to 66ed3a87e3680 port 3000 after 5000 ms: Timeout was reached

[Error] File: /usr/local/app/http.php

[Error] Line: 1262
```
  

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@VTFLAB, thanks for creating this issue! 🙏🏼 Some questions:

1. What docker networks is the `openruntimes-executor` in? 
2. What is your `_APP_FUNCTIONS_RUNTIMES_NETWORK` env var set to?
3. Are containers being created for your functions when you try to execute (you might have to check fast before it exits)?
4. If the containers for your functions are being created, what networks are they in?
5. Does `docker ps -a` show the function containers?

**Comment by TechnoDD** [comment]
Good morning @stnguyen90, I have the same problem... will there be a fix for this bug?

**Comment by Cow-Level** [comment]
This issue seems to still be present. I didn't see it when I was on 1.5.11 but since 1.6.0 and 1.6.1, the issue occurs quite often during the day.

Would be great if we can open this issue.
