### ISSUE TITLE
🐛 Bug Report: `databases.createDocument()` returns a list of documents

### ISSUE THREAD

**Issue by hej2010** [appwrite/appwrite#8701]
### 👟 Reproduction steps

Upgraded from 1.5.10 to 1.6.0 and now all `databases.createDocument(...)` calls from functions return a list of documents (like when you call `databases.listDocuments(...)`). No new document is created.

```js
const client = new Client()
    .setEndpoint(process.env.APPWRITE_FUNCTION_API_ENDPOINT)
    .setProject(process.env.APPWRITE_FUNCTION_PROJECT_ID)
    .setKey(req.headers['x-appwrite-key']);
const databases = new Databases(client);

let shop = await databases.createDocument(
      DATABASE_ID,
      COLLECTIONS.Shop,
      ID.unique(),
      {
        name: "test",
      },
      [Permission.read(Role.any())]
    );
log("Created shop " + JSON.stringify(shop))
```

And the output is a list of documents that already exist in the database:
```
{
  "total": 5,
  "documents": [{"name": "old document"}, ...]
}
```

### 👍 Expected behavior

Create a new document.

### 👎 Actual Behavior

Returns a list of documents.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Self-hosted 1.6.0 using the default docker-compose setup and Nginx in front.
node-appwrite 14.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by hej2010** [comment]
I found the issue, when creating the client with 
```js
const client = new Client()
    .setEndpoint(process.env.APPWRITE_FUNCTION_API_ENDPOINT)
    .setProject(process.env.APPWRITE_FUNCTION_PROJECT_ID)
    .setKey(req.headers['x-appwrite-key']);
```
the `process.env.APPWRITE_FUNCTION_API_ENDPOINT` returns the correct endpoint but it uses `http://my.domain/v1` instead of `https://my.domain/v1`. I use nginx in front of the server with https.

If I set it to `.setEndpoint("https://my.domain/v1")` everything works as it should.

I tried setting
```
_APP_OPTIONS_FORCE_HTTPS=enabled
_APP_OPTIONS_FUNCTIONS_FORCE_HTTPS=enabled
```
but executing a function gives the error `general_protocol_unsupported`.

**Comment by feschaffa** [comment]
Got the same problem!

The function works as expected when developing locally using the cli (`appwrite run functions`) and using the endpoint provided by `process.env.APPWRITE_FUNCTION_API_ENDPOINT`, but when deployed the `createDocument` keeps returning a list of documents with that endpoint.

Manually setting the API Endpoint with https did indeed solve the problem.

I'm also using nginx as a reverse proxy and Appwrite 1.6.0. The function environment is node-18.0.

**Comment by stnguyen90** [comment]
@hej2010, @feschaffa, are y'all proxying to Appwrite using HTTPS or HTTP? Can you try proxying using HTTPS and enabling the FORCE_HTTPS env vars?

```
_APP_OPTIONS_FORCE_HTTPS=enabled
_APP_OPTIONS_FUNCTIONS_FORCE_HTTPS=enabled
```

**Comment by hej2010** [comment]
I proxy using HTTP: `proxy_pass http://127.0.0.1:80/;`

Changing it to `proxy_pass https://127.0.0.1:443/;` and enabling FORCE_HTTPS worked :)

**Comment by onrdmr** [comment]
we have also same issue. it is like our user.create method in our appwrite function calls GET /user request instead of POST/user .

**Comment by onrdmr** [comment]
I think it is about new scope feature, we have restarted our container with forcing https enabled and then disabled. Afterward, it is fixed

**Comment by feschaffa** [comment]
I was proxying using HTTP internally just like @hej2010 
Changing it to HTTPS and enabling the environment variables worked here as well. 

Thank you!

**Comment by Stanjae** [comment]
i am getting this error from the functions console- 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/a9b4ffff-a64c-4b8a-a5dc-54ab4cf6f086" />

code - 
`
import { Client, Databases } from 'node-appwrite';

export default async ({ req, res, log, error }) => {
  // Initialize Appwrite client
  const client = new Client()
    .setEndpoint('https://fra.cloud.appwrite.io/v1')
    .setProject(process.env.APPWRITE_FUNCTION_PROJECT_ID)
    .setKey(req.headers['x-appwrite-key']);

  const databases = new Databases(client);

  try {
    log('Starting cleanup of pending appointments...', req, databases);

    // Calculate timestamp for 1 hour ago
    const oneHourAgo = new Date();
    oneHourAgo.setHours(oneHourAgo.getHours() - 1);
    const oneHourAgoISO = oneHourAgo.toISOString();

    log(`Looking for appointments created before: ${oneHourAgoISO}`);

    // Query pending appointments created more than 1 hour ago
   /*  const response = await databases.listDocuments(
      process.env.APPWRITE_DATABASE_CLUSTER_ID,
      process.env.APPWRITE_DATABASE_COLLECTION_APPOINTMENT_ID,
      [
        Query.equal('status', 'pending'),
        Query.lessThan('$createdAt', oneHourAgoISO),
        Query.limit(100), // Process in batches of 100
      ]
    );

    const appointmentsToDelete = response.documents;
    log(`Found ${appointmentsToDelete.length} pending appointments to delete`); */

   /*  if (appointmentsToDelete.length === 0) {
      log('No pending appointments to delete');
      return res.json({
        success: true,
        message: 'No pending appointments found',
        deleted: 0,
      });
    }

    // Delete each appointment
    const deletionPromises = appointmentsToDelete.map(async (appointment) => {
      try {
        await databases.deleteDocument(
          process.env.APPWRITE_DATABASE_CLUSTER_ID,
          process.env.APPWRITE_DATABASE_COLLECTION_APPOINTMENT_ID,
          appointment.$id
        );
        log(`Deleted appointment: ${appointment.$id}`);
        return { id: appointment.$id, success: true };
      } catch (err) {
        error(
          `Failed to delete appointment ${appointment.$id}: ${err.message}`
        );
        return { id: appointment.$id, success: false, error: err.message };
      }
    });

    await Promise.all(deletionPromises);
      const successCount = results.filter((r) => r.success).length;
    const failureCount = results.filter((r) => !r.success).length;
 */
    log(`Cleanup completed:  deleted, failed`);

    return res.json({
      success: true,
      message: 'Cleanup completed',
    });
  } catch (err) {
    error(`Error during cleanup: ${err.message}`);
    return res.json(
      {
        success: false,
        error: err.message,
      },
      500
    );
  }
};
`
