### ISSUE TITLE
🐛 Bug Report: Not able to login to appwrite after creating new instance from back of digitalocean droplet

### ISSUE THREAD

**Issue by abhidev54** [appwrite/appwrite#8708]
### 👟 Reproduction steps

Appwrite was running fine on dev environment, its in digital ocean droplet.

I wanted to setup my production so that i created new digitalocean droplet using the backup of digitalOcean dev environment, everything seems okay but not able to login.

In logs, I see below
```
[Error] Timestamp: 2024-09-22T04:55:14+00:00
[Error] Type: Utopia\Exception
[Error] Message: Not Found
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 803
[Error] Timestamp: 2024-09-22T04:56:50+00:00
[Error] Method: POST
[Error] URL: /v1/account/sessions/email
[Error] Type: Exception
[Error] Message: Filter not found
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 4221
```
On browser, I see below response
**endpoint** : https://xxxx.xxxxx.com.cy/v1/account/sessions/email
**response** : {"message":"Server Error","code":500,"type":"general_unknown","version":"1.3.8"}

### 👍 Expected behavior

I should be able to login

### 👎 Actual Behavior

It is not allowing me to login, saying "Server error", below are some logs
```
[Error] Timestamp: 2024-09-22T04:55:14+00:00
[Error] Type: Utopia\Exception
[Error] Message: Not Found
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
[Error] Line: 803
[Error] Timestamp: 2024-09-22T04:56:50+00:00
[Error] Method: POST
[Error] URL: /v1/account/sessions/email
[Error] Type: Exception
[Error] Message: Filter not found
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 4221
```
On browser, I see below response
**endpoint** : https://xxxx.xxxxx.com.cy/v1/account/sessions/email
**response** : {"message":"Server Error","code":500,"type":"general_unknown","version":"1.3.8"}

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.3.8

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@abhidev54, how did you install Appwrite?

**Comment by abhidev54** [comment]
It got resolved now, I was trying to upgrade from 3.x.x version to 1.6.0, I followed the steps to first upgrade to 1.4.0 and 1.5.11 and then 1.6.0 , it worked after that
