### ISSUE TITLE
🐛 Bug Report: Error while upgrading appwrite from version 1.3.8 to 1.6.0

### ISSUE THREAD

**Issue by abhidev54** [appwrite/appwrite#8709]
### 👟 Reproduction steps

**command**: docker compose exec appwrite migrate

**Getting below error on migration:**

Migrating Collection authenticators:

```
Failed to update project ("6500c81aece37ec7e147") version with error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._1_' doesn't exist

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._1_' doesn't exist in @swoole/library/core/Database/PDOStatementProxy.php:49
Stack trace:
#0 @swoole/library/core/Database/PDOStatementProxy.php(49): PDOStatement->execute()
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(1905): Swoole\Database\PDOStatementProxy->__call('execute', Array)
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(5202): Utopia\Database\Adapter\MariaDB->count('', Array, NULL)
#3 /usr/src/code/vendor/utopia-php/database/src/Database/Validator/Authorization.php(166): Utopia\Database\Database->Utopia\Database\{closure}()
#4 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(5203): Utopia\Database\Validator\Authorization::skip(Object(Closure))
#5 /usr/src/code/src/Appwrite/Migration/Migration.php(213): Utopia\Database\Database->count(Object(Utopia\Database\Document))
#6 /usr/src/code/src/Appwrite/Migration/Migration.php(178): Appwrite\Migration\Migration->documentsIterator('authenticators')
#7 /usr/src/code/src/Appwrite/Migration/Version/V21.php(43): Appwrite\Migration\Migration->forEachDocument(Array)
#8 /usr/src/code/src/Appwrite/Platform/Tasks/Migrate.php(125): Appwrite\Migration\Version\V21->execute()
#9 /usr/src/code/src/Appwrite/Platform/Tasks/Migrate.php(38): Appwrite\Platform\Tasks\Migrate->action('1.6.0', Object(Utopia\Database\Database), Object(Closure), Object(Utopia\Registry\Registry))
#10 [internal function]: Appwrite\Platform\Tasks\Migrate->Appwrite\Platform\Tasks\{closure}()
#11 {main}
  thrown in @swoole/library/core/Database/PDOStatementProxy.php on line 49
```
**On appwrite console, I am getting below error, may be because migration didn't complete.**
Request URL:
https://xxx.xxx.com/v1/account/sessions/email
Request Method:
POST
Status Code:
400 Bad Request

{
    "message": "Invalid document structure: Unknown attribute: \"factors\"",
    "code": 400,
    "type": "document_invalid_structure",
    "version": "1.6.0"
}

### 👍 Expected behavior

Migration should work smoothly

### 👎 Actual Behavior

Migration not working.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

1.6.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by feschaffa** [comment]
Good evening!

As stated in the docs (https://appwrite.io/docs/advanced/self-hosting/update), migration unfortunately only supports upgrading to immediately higher versions.

Your version is 1.3.8, so you should first upgrade to 1.4.x and run the migration, then to 1.5.x and run the migration again and finally to 1.6.0 and run the migration once more.

That way it should work. Hope it helps!

**Comment by abhidev54** [comment]
It worked after I moved to 1.4.x -> 1.5.x and 1.6.x
