### ISSUE TITLE
🐛 Bug Report: Google OAuth invalid redirect on 1.6.0

### ISSUE THREAD

**Issue by johnstack94** [appwrite/appwrite#8712]
### 👟 Reproduction steps

Pass valid redirect params to account.createOAuth2Session and it will throw the invalid redirect exception.

### 👍 Expected behavior

Navigate to Google provider login and redirect back to app

### 👎 Actual Behavior

It throws above exception. This wasn't an issue on 1.5.10.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Self host Appwrite instance running 1.6.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@johnstack01, thanks for creating this issue! 🙏🏼 I tried testing this locally, but couldn't reproduce your problem.

I tested with `myapp.com` added as a web platform:

![image](https://github.com/user-attachments/assets/879133c2-8faa-4512-8825-46b8b03cfb5e)

When I used an invalid success, I got an error, as expected:

![image](https://github.com/user-attachments/assets/cb200db7-cac1-46e3-8727-24e36ff439b0)

However, passing the correct success param, resulted in the redirect, as expected:

![image](https://github.com/user-attachments/assets/8ac84fca-4010-4bdf-af1d-3d80b1c024a3)

Can you provide details so I can reproduce the problem?

**Comment by stnguyen90** [comment]
> ![image](https://private-user-images.githubusercontent.com/177103880/370191398-f059cc86-1c59-4265-8285-b4aaa09015e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMzY3MjcsIm5iZiI6MTcyNzIzNjQyNywicGF0aCI6Ii8xNzcxMDM4ODAvMzcwMTkxMzk4LWYwNTljYzg2LTFjNTktNDI2NS04Mjg1LWI0YWFhMDkwMTVlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMzUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmQ1NjlmMmRjOGY2ZGUxOTNmZWUwNTY2YWYxYjJjYTZmN2M1ZTY3MmEzNTVlOWYyNDE3MDg4NWQ4MjRmNDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T62fqw5zra2cSbwYx6qe67zg92MK1kwcVEeVN5ikwJc)

Status 301 indicates all the params were correct and you were successfully redirected. Perhaps something is incorrect with what you configured for OAuth2 which is why you received an error when reaching Google.
 
> Using localhost as success param and using server prod domain (https://serverdomain.xyz/v1/account/sessions/oauth2/google?project=MYPROJECTID&success=localhost:5173): ![image](https://private-user-images.githubusercontent.com/177103880/370195286-1cc0925c-cd75-495e-bbcd-9e6390923196.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMzY3MjcsIm5iZiI6MTcyNzIzNjQyNywicGF0aCI6Ii8xNzcxMDM4ODAvMzcwMTk1Mjg2LTFjYzA5MjVjLWNkNzUtNDk1ZS1iYmNkLTllNjM5MDkyMzE5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMzUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTUwM2NmOWEyMDczMGI0YWRhZmYwYzU3OTdmNWJkYjYxMmRhMGE0MDEzNWZmNmI5YWMxYWE5ZDYzMmNkNGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A39I7vzWyZru-lAdSxCOalIV8I0femfuxTbuX8pLzIU)
> 
> Using actual prod domain as success param and visiting server prod domain (https://serverdomain.xyz/v1/account/sessions/oauth2/google?project=MYPROJECTID&success=proddomain.xyz): ![image](https://private-user-images.githubusercontent.com/177103880/370196872-33a01002-203d-4058-9d26-2d45b3cb2e49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMzY3MjcsIm5iZiI6MTcyNzIzNjQyNywicGF0aCI6Ii8xNzcxMDM4ODAvMzcwMTk2ODcyLTMzYTAxMDAyLTIwM2QtNDA1OC05ZDI2LTJkNDViM2NiMmU0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMzUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTY3YTFmMmQ5NTk1YmU0YmUyZmI3NGRkNmNkNDgzODQ2NDY3NzNhYjYzMDU4ZmRmYjVjYTljYjE1MTg5MDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EU6DpHUWuB9pQ1yrBWC64UID28VL6TtU5vRme7Iwe7I)

These URLs are invalid as there is no scheme (https:// or http://).

**Comment by stnguyen90** [comment]
@johnstack94, what are you being redirected to using version 16 vs 15?

I just tested using v16.0.0 with this code:

```javascript
            const location = window.location.origin;
            const successUrl = `${location}/`;
            const failureUrl = `${location}/login`;
            console.log('successUrl', successUrl)
            console.log('failureUrl', failureUrl)
            account.createOAuth2Session(
                "google",
                successUrl, // Callback URL for success
                failureUrl, // Callback URL for failure
                []
            );
```

and this was the result:

![image](https://github.com/user-attachments/assets/dfeb9187-297f-4c4d-81e8-c63f9a392fa2)

As you can see, the successUrls include the http:// scheme and the URL I was redirected to had a valid success and failure.

**Comment by stnguyen90** [comment]
For the screenshots you're sharing, it looks like things are working fine from the Appwrite side since you're being redirected to Google successfully. If you're seeing "Error 401: invalid_client" still, I would double check the client id you have in Appwrite matches the client ID in Google.

**Comment by ddenev** [comment]
@stnguyen90, please reopen. I am on 16.0.2 and this issue still persists.

The problem comes from the fact that when configuring OAuth2 in the Console, the callback URI that the Appwrite gives me contains "https" (so this is what I put in "Authorized redirect URIs" in Google Cloud Console, but when the request is sent from the app it contains "http".

Again, this is still a problem on 16.0.2
