### ISSUE TITLE
🚀 Enhancement: A option to select and delete files from storage.

### ISSUE THREAD

**Issue by Shadyx6** [appwrite/appwrite#8715]
### 🔖 Enhancement description

A feature to delete multiple files from the storage or buckets will be so much helpful to developers

### 🎤 Pitch

I was working for my blog app and found this during developmental stage that there is no option to delete duplicated images all at once, since its very time consuming to delete every file one by one, this feature needs to be implemented.
I hope you let me add this feature!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Shadyx6, thanks for creating this issue! 🙏🏼 This looks like the same as https://github.com/appwrite/appwrite/issues/8541 so I'm going to close this as a duplicate. I suggest you add a 👍🏼 to the other issue.

As a workaround, for now, I suggest creating a function that you can trigger that will iterate over all files and delete.
