### ISSUE TITLE
🐛 Bug Report: Email verification link giving error for appwrite custom domain

### ISSUE THREAD

**Issue by abhidev54** [appwrite/appwrite#8723]
### 👟 Reproduction steps

Email verification link: https://appwrite.example.com/verify-email?userId=65be7b62bf9790ab8908&secret=370d9950b25b400ac8630dad9dcb77e239f5966845d430df196e33ce5d7c13a4d517fd7fe355f1298cade79d127a332635e09a74df920ac918449f5b340003569ea72acae9acb2f5e5c515ba52d46effbfcc29b2ace2c05681da6cddcb39f6ba1998bf915806ed180ebb53d5621a86e93f8ed348acb6227db96cd817fdccacc2&expire=2024-02-10+17%3A44%3A03.825

Getting below error: "Error 404
The requested route was not found. Please refer to the API docs and try again.

Type
general_route_not_found"

### 👍 Expected behavior

Email verification link should work.

### 👎 Actual Behavior

Email verification link not working

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

1.3.8

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@abhidev54, thanks for creating this issue! 🙏🏼 The URL you provide is supposed to be of a page you built to handle the verification, not your Appwrite Console/endpoint. Did you implement that page you specified for the URL?

For more info, see https://appwrite.io/docs/products/auth/email-password#verification

**Comment by abhidev54** [comment]
@stnguyen90 Even I tried adding my website url in account.createVerification but it is throwing below error.

const promise = account.createVerification('https://dev.example.com');

**Invalid 'url' param: URL host must be one of : localhost, appwrite.example.com**

** Please note when I tried to add custom domain (https://dev.example.com) on appwrite console, it is failing with below error

In order to continue, set the following record on your DNS provider. DNS records may take up to 48 hours to propagate. Please retry over the next 48 hours, but if verification still fails, please [contact support](https://appwrite.io/discord).


Type	Name	Value	
CNAME
dev
appwrite.example.com


- https://appwrite.example.com and https://dev.example.com are on different server, how to map CNAME is that case? do you have proper documentation on this ?

can you please suggest some solution on this ?

**Comment by byawitz** [comment]
Hi @abhidev54 
The URL for the `account.createVerification` must be either verified in the console or you can add it as a web platform in the console, which doesn't require verification.

**Comment by abhidev54** [comment]
It worked @byawitz , thanks a lot for your help.

I add it as a web platform in the console, which doesn't require verification to solve this.
