### ISSUE TITLE
🐛 Bug Report: No webhook when user.*.created via OAuth2 social login

### ISSUE THREAD

**Issue by yairyairyair** [appwrite/appwrite#8726]
### 👟 Reproduction steps

- Create a webhook for user.*.created
- Do some social login (i am using refine dev + appwrite integration + oauth2 of discord,github,google)
- I expect to get a webhook but it is not sending a webhook but user is indeed created

### 👍 Expected behavior

getting a webhook when user is created

### 👎 Actual Behavior

no webhook is sent

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite Cloud

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by byawitz** [comment]
Hi @yairyairyair, thanks for opening the issue.

This issue looks like this: https://github.com/appwrite/appwrite/issues/2406 for when the event is not being triggered for OAuth2's first login.

I'll close this one as a duplicate, make sure to upvote that one.
