### ISSUE TITLE
🐛 Bug Report: after migration the database from self-hosted instance one collection brings server error 500

### ISSUE THREAD

**Issue by xpediteur** [appwrite/appwrite#8733]
### 👟 Reproduction steps

when i migrate my the database from self-hosted instance to appwrite cloud, all collection are fine. One collection brings server error 500.

### 👍 Expected behavior

It shoud show my collection correctly with all data

### 👎 Actual Behavior

error message: {"message":"Server Error","code":500,"type":"general_unknown","version":"1.6.0"}

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

i use  "appwrite": "^10.1.0" in my vue.js project, all is working fine.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Suvendu-UI** [comment]
can i solve this issue ?

**Comment by Suvendu-UI** [comment]
can you just tell what was the type of file which gave this error?

**Comment by xpediteur** [comment]
The type is a database table. I had to remove the table (collection) and rebuild it manually.

**Comment by stnguyen90** [comment]
@xpediteur, do you need help with this or can it be closed?

**Comment by xpediteur** [comment]
Issue can be closed.
