### ISSUE TITLE
🐛 Bug Report: general_route_not_found after updating from 1.5.x to 1.6.0

### ISSUE THREAD

**Issue by Splinteer** [appwrite/appwrite#8734]
### 👟 Reproduction steps

I'm deploying my appwrite service using docker swarm.
I udpated my compose file to use the 1.6 version instead of the 1.5 one.
Running `docker exec -it e45ff1a4a3c0 migrate` to migrate old data to the latest version.

### 👍 Expected behavior

Run the appwrite webapp

### 👎 Actual Behavior

It actually redirect me to /console and show this json:
`{"message":"The requested route was not found. Please refer to the API docs and try again.","code":404,"type":"general_route_not_found","version":"1.6.0"}`

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

I'm using docker swarm on a debian vps

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Splinteer** [comment]
I needed to add appwrite console to my docker swarm stack

**Comment by maendamedia** [comment]
> I needed to add appwrite console to my docker swarm stack

What do you mean with that? As i have same problem?

**Comment by Splinteer** [comment]
> > I needed to add appwrite console to my docker swarm stack
> 
> What do you mean with that? As i have same problem?

You need to add the console service. Check the docker compose, it got new services inside
