### ISSUE TITLE
🐛 Bug Report: getDocuments not getting all the documents

### ISSUE THREAD

**Issue by jamminuesa** [appwrite/appwrite#8736]
### 👟 Reproduction steps

I am doing the following call from an android device
` val response = getDocuments(
            databaseId,
            paymentCollectionId,
            listOf(
                Query.equal(teamId, "value")
            )
        )`
I have checked and permissions are correct and the user has access to all documents

### 👍 Expected behavior

Get the same number in response.total and response. documents.size

### 👎 Actual Behavior

The server is returning the following response:
![image](https://github.com/user-attachments/assets/9505e584-63df-4192-a795-bf200e4655a9)
I check in the console and the total number is 38 so the value of response.total is correct but the List is incomplete

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Version 1.6.0, 
android sdk 5.1.0 as sdk 6.0.0 is not in maven

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@jamminuesa, thanks for creating this issue! 🙏🏼 It looks like the list documents API is responding as expected. The `total` is the number of documents in the collection that matches your filter (`Query.equal(teamId, "value")`). However, by default, all responses have a limit of 25 to prevent you from fetching too many items unnecessarily. For reference, see the docs for [List documents](https://appwrite.io/docs/products/databases/documents#list-documents).

<img width="686" alt="image" src="https://github.com/user-attachments/assets/da703759-f7c5-452d-8f47-24417f48a7d0">

As suggested by the docs, look into [pagination](https://appwrite.io/docs/products/databases/pagination).

**Comment by jamminuesa** [comment]
My apologies, I miss that part. I thought it was because I am using server version 1.6.0 and the android sdk is version 5.1.0, although the documentation suggest 6.0.0, this one is not in maven.
Thank you for your quick reply Steve
