### ISSUE TITLE
🐛 Bug Report: Error 404 when trying to createFile in storage

### ISSUE THREAD

**Issue by jamminuesa** [appwrite/appwrite#8748]
### 👟 Reproduction steps

I have just came across this error, I am doing a migration using an android app. I successfully manage to create other files but with this one I am getting this error:
Code is the following:
```
 suspend fun uploadAttachment(
      file: InputFile,
      fileId: String,
      permissions: List<String>,
      ignoreAlreadyExists: Boolean = false
  ): File? {
      try {
          return storage.createFile(
              bucketId = ATTACHMENTS_BUCKET_ID,
              fileId = fileId,
              file = file,
              permissions = permissions
          )
      } catch (e: AppwriteException){
          if (e.type == "general_unauthorized_scope"){
              // User is not log in or not enough permission
              onAutomaticLogin()
              return uploadAttachment(
                  file,
                  fileId,
                  permissions
              )
          // In case the document exists and ignore is true: do not throw
          // Throw on the rest of the cases
          } else if (e.type != "document_already_exists" || !ignoreAlreadyExists){
              throw e
          } else {
              //The file already exists so return null
              return null
          }
      }
  } 
```
This is the file that gives me the error
![image](https://github.com/user-attachments/assets/a2bf79aa-fa74-4fa5-9f89-52393f6f9efa)

I thought that it can be because the file does not exist, I check the path and it is there, I can open it  and see its content
![image](https://github.com/user-attachments/assets/46a78f7f-b8d4-42fc-985d-5032f5df62cc)
![image](https://github.com/user-attachments/assets/765cb4f5-f30c-4810-bb8e-39b72461d8e0)

I think that the problem is because of the file because the code is working for other files, but I do not see any clear error

### 👍 Expected behavior

The file should be created

### 👎 Actual Behavior

io.appwrite.exceptions.AppwriteException: The requested file could not be found. Error 404

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite version 1.6.0
Android sdk 5.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
If you're getting 404 when trying to access or create a file it can be a permission issues or you might be using the wrong IDs. I'd recommend checking if the ID are correct. Also, try to set both bucket and file permissions to public for testing purpose.
