### ISSUE TITLE
🚀 Enhancement: Bulk delete

### ISSUE THREAD

**Issue by Aarush-Acharya** [appwrite/appwrite#8758]
### 🔖 Enhancement description

There should be a function inside the Database Class in client side sdks, that takes in the databaseID, collectionID and a query then will delete all the documents in the collection that matches the query. 

Right now to achieve this functionality requests are sent to different endpoint of the server from client. One request to listAllDocuments with the query and then running a for loop on the list and making request to deleteDocument endpoint for each document in the list

the input parameter structure of this function is similar to that of the listAllDocuments function, listallDocuments just lists the documents that match the query while, deleteAllDocuments() will delete the documents that match the query

### 🎤 Pitch

I believe just to delete documents based on a query should not cost one request just to fetch the documents that satisfy the query, then individually make requests to delete a particular document 

This heavy methodology could easily be lightened, if there were to exist an endpoint that deletes documents based on a query. So the extra time that the request takes to reach the server for deletion of a document will be saved 

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by asmit27rai** [comment]
@sesam i want to work on this issue.
Please Assign it to me.

**Comment by stnguyen90** [comment]
@asmit27rai, if you're looking to contribute, please look for issues labeled with "good first issue" or "help wanted". Those will be the best ones to pick up.

**Comment by stnguyen90** [comment]
@Aarush-Acharya, thanks for creating this issue! 🙏🏼 This is very similar to https://github.com/appwrite/appwrite/issues/3520 so I think it would be best if you added a 👍🏼 in that issue and commented with your use case.

**Comment by JayeshVelivela** [comment]
Hey! I’m working on this issue as part of a course project — just confirming: is the goal to add bulk deletion for documents via the API, or also to expose that in the Console UI?
