### ISSUE TITLE
🐛 Bug Report:Server Error

### ISSUE THREAD

**Issue by SSAA-ux** [appwrite/appwrite#8759]
### 👟 Reproduction steps

I can't visit my database and functions in console. And I can't use apis too. Every thing I do returns server error. What happened to my project?

### 👍 Expected behavior

do everything right.

### 👎 Actual Behavior

Every thing I do returns server error.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by tessamero** [comment]
Hi @SSAA-ux , I do not think this is a bug, but our support team would love to troubleshoot and see what is causing it. Have you joined our Discord community? Our support team is there and can help resolve this. https://appwrite.io/discord and you can join the support channel :)
