### ISSUE TITLE
🐛 Bug Report: Error creating user in Appwrite Console

### ISSUE THREAD

**Issue by museposta** [appwrite/appwrite#8774]
### 👟 Reproduction steps

When I try to create a user, I always get the message Allowed characters: leading '+' and maximum of -1 digits. my pass is aq1wsXZa What is wrong with it? could you give me a sample password please?

### 👍 Expected behavior

I should create a user.

### 👎 Actual Behavior

give errror: Allowed characters: leading '+' and maximum of -1 digits

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gepd** [comment]
Can you post the code you're using to create the user?

**Comment by docimin** [comment]
Please add a proper bug issue title.

**Comment by museposta** [comment]
Hello. I am trying to create a user from your dashboard manually. Best
wishes. Mustafa

Faye ***@***.***>, 18 Eki 2024 Cum, 04:03 tarihinde şunu
yazdı:

**Comment by stnguyen90** [comment]
@museposta, I wasn't able to reproduce your problem. Could you please share a screenshot of what you entered before you pressed submit?
