### ISSUE TITLE
OAuth support for Native SDKs

### ISSUE THREAD

**Issue by mlucas-NU** [appwrite/appwrite#879]
## 🚀 Feature

Add an endpoint that accepts active Oauth tokens that were previously obtained by authenticating with an OAuth provider (specifically, tokens obtained without the use of the existing appwrite OAuth endpoint).

Future feature request for other appwrite projects:
Add authentication functions to the python/ruby/flutter/etc appwrite SDKs that facilitate use of the above appwrite endpoint.

## Have you spent some time to check if this issue has been raised before?

I searched existing auth Issues and didn't find anything. Also spoke to @eldadfux briefly on Discord to verify that this feature doesn't currently exist.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

## Pitch

OAuth is currently performed by opening a separate web browser, regardless of the app type or OAuth provider. This is a great general solution and works well for the Web SDK, but "installed apps" (especially iOS/Android) can utilize Native SDKs.

**Advantages:**

- Native SDKs provide up-to-date OAuth methods that meet modern UI/UX/security standards.
- The new endpoint can provide OAuth without requiring a Client Secret. OAuth for installed apps appears to be moving away from Client Secrets (e.g. Google has stopped displaying Client Secrets in the developer console entirely unless the registered app is for the Web/other). Currently, adding OAuth for installed apps within Appwrite is a challenge since it requires a Client Secret that may not be available.

**Comment by eldadfux** [comment]
Update 25.03.21: we've got an internal draft testing how we can reuse current functionality in the best way. If this will not work out well, we don't mind having minor duplications in our controller layers. I'll keep this issue up-to-date with any developments.

**Comment by eldadfux** [comment]
Closing in favor of #2611
