### ISSUE TITLE
🐛 Bug Report:  Cannot update document from a  functions

### ISSUE THREAD

**Issue by Zia-Ch** [appwrite/appwrite#8794]
### 👟 Reproduction steps

Hey Appwrite team :wave:,

I’m working on a Python function.
this function first get data from user collection, decrease their credits and try to update it.
Apparently it should work fine but unexpectedly it is failing in updating the document.

It throws this error:
`[ERROR] Error saving updated credits: The document data and permissions are missing. You must provide either document data or permissions to be updated.`

Reproduction steps:
-- Create a simple python function with provided code.
-- Create a User_Collection that has only one attribute credits (int).
-- create a document and put some value here
-- run your function 

##Code
```
import os
from appwrite.client import Client
from appwrite.services.databases import Databases


def main(context):
    
    #get required values from headers
    user_id = context.req.headers['x-appwrite-user-id']
    api_key=context.req.headers['x-appwrite-key']
    
    #get required values from environment variables
    endpoint=os.environ['APPWRITE_FUNCTION_API_ENDPOINT']
    project_id=os.environ['APPWRITE_FUNCTION_PROJECT_ID']
    db_id=os.environ['DB_ID']
    user_collection_id=os.environ['USER_COLLECTION_ID']
    
    #setup appwrite client
    client = Client()
    client.set_endpoint(endpoint)
    client.set_project(project_id)
    client.set_key(api_key)
    database = Databases(client)
    
    #get user details
    try:
        user = database.get_document(db_id, user_collection_id, user_id)
        context.log(f'User details: {user}')
    except Exception as e:
        context.log(f'Error getting user details: {e}')
        
    #reduce user credits by 1
    updated_credits = user['credits'] - 1
    context.log(f'Updated credits: {updated_credits}')
    
    try:
        #save updated credits to user document
        save = database.update_document(
            database_id=db_id,
            collection_id=user_collection_id,
            document_id= user_id, 
            data={'credits': updated_credits}
        )
        context.log(f'saved: {save}')
        return context.res.json({'ok': True,'credits': updated_credits},200)
    except Exception as e:
        context.log(f'Error saving updated credits: {e}')
        return context.res.json({'ok': False,'error': str(e)},400)
    
      
```

What I’ve Tried:
1. Ensured that data is a dictionary with the credits field.
2. Attempted to pass permissions correctly.
3. Printed and verified the data and permissions before calling update_document
Despite these efforts, the error persists. :smiling_face_with_tear:

### 👍 Expected behavior

Document will get updated and document should have the updated values

### 👎 Actual Behavior

It is not saving data instead showing error:
[ERROR] Error saving updated credits: The document data and permissions are missing. You must provide either document data or permissions to be updated.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.6.0
Linux server with Ubuntu 22.04
python runtime 3.11
using dynamic API from functions that has all database access.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Zia-Ch** [comment]
I tried the same setup usng node and surprisingly it worked as expected:
Here is my code snippts:
 ```import { Client, Databases } from 'node-appwrite';

// This Appwrite function will be executed every time your function is triggered
export default async ({ req, res, log, error }) => {
  //get required values from headers
  const userId =
      '6709f2d000358e2c41f7'; //context.req.headers['x-appwrite-user-id'];
  const apiKey = req.headers['x-appwrite-key'];

  //get required values from environment variables
  const endpoint = process.env.APPWRITE_FUNCTION_API_ENDPOINT ?? '';
  const projectId = process.env.APPWRITE_FUNCTION_PROJECT_ID ?? '';
  const dbId = process.env.DB_ID ?? '';
  const userCollectionId = process.env.USER_COLLECTION_ID ?? '';

  const client = new Client()
    .setEndpoint(endpoint)
    .setProject(projectId)
    .setKey(apiKey);
  

  const db = new Databases(client);
  var user = await db.getDocument(
    dbId,
    userCollectionId,
    userId

  );

  var credits = user['credits'];
  var updatedCredits = credits - 1;
  log('credits: ' + credits + 'updatedCredits: ' + updatedCredits);

  log(user);

  var update = await db.updateDocument(
    dbId,
    userCollectionId,
    userId,
    {
      'credits': updatedCredits
    }
  );

  log(update);

  return res.json({"data":user});

};```

**Comment by EVDOG4LIFE** [comment]
Hey @Zia-Ch 

The error you're encountering happens because the `update_document` method requires the `data` parameter to have at least one valid field. In your code, if `updated_credits` is `None` or invalid, you're effectively passing `data={'credits': None}` to `update_document`, which causes the error you're seeing.

To try to fix this issue, please ensure the following:

- **Validate the User Document**: Confirm that the `user` object retrieved from `get_document` is not `None` and contains the `credits` field.
- **Check the `credits` Field**: Ensure that `user['credits']` is a valid number before performing the subtraction.
- **Validate `updated_credits`**: After computing `updated_credits = user['credits'] - 1`, make sure it holds a valid numeric value and meets any business logic requirements (e.g., not negative).
- **Log the Data Being Passed**: Before calling `update_document`, log the `data` you're passing to verify it's correctly formed.

With additional validation steps, you should be able to prevent `None` or invalid data from being passed to `update_document` which will hopefully alleviate this error for you.

**Comment by stnguyen90** [comment]
@Zia-Ch, as mentioned, we were unable to reproduce the problem. If you'd like to troubleshoot further, please continue in your [Discord thread](https://discord.com/channels/564160730845151244/1294569793067679817).

**Comment by inversionclimbing** [comment]
Just made a set of comments in the discord thread with a similar issue. Posted code (Python 3.12), log and error from execution
`https://discord.com/channels/564160730845151244/1294569793067679817`
