### ISSUE TITLE
🐛 Bug Report: Issue in creating user from a admin panel

### ISSUE THREAD

**Issue by WhiteDevil8821** [appwrite/appwrite#8795]
### 👟 Reproduction steps

My project having 2 application in flutter in which 1 user admin app and other is user app. 
From the admin app I need to create users with the auths. 
When I am creating a new user it is showing me error as "User with this email already exists" but I have checked in the auth there no such email registered.

My code for the registration is below 

```dart
import 'package:dice_game_admin/main.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:appwrite/appwrite.dart';

class CreateUserScreen extends StatefulWidget {
  @override
  _CreateUserScreenState createState() => _CreateUserScreenState();
}

class _CreateUserScreenState extends State<CreateUserScreen> {
  final _formKey = GlobalKey<FormState>();
  String name = '';
  String email = '';
  String password = '';
  int coins = 0;

  @override
  Widget build(BuildContext context) {
    final appwrite = Provider.of<AppwriteProvider>(context);
    return Scaffold(
      appBar: AppBar(
        title: Text('Create User'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                decoration: InputDecoration(labelText: 'Name'),
                onChanged: (value) {
                  name = value;
                },
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a name';
                  }
                  return null;
                },
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Email'),
                onChanged: (value) {
                  email = value;
                },
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter an email';
                  }
                  return null;
                },
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Password'),
                obscureText: true,
                onChanged: (value) {
                  password = value;
                },
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a password';
                  }
                  return null;
                },
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Coins'),
                keyboardType: TextInputType.number,
                onChanged: (value) {
                  coins = int.tryParse(value) ?? 0;
                },
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter coins';
                  }
                  return null;
                },
              ),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: () async {
                  if (_formKey.currentState!.validate()) {
                    try {
                      // Attempt to create the new user
                      final user = await appwrite.account.create(
                        userId: ID.unique(),
                        email: email,
                        password: password,
                      );

                      // Create a document in the database for the new user
                      await appwrite.databases.createDocument(
                        databaseId: '',
                        collectionId: 'users',
                        documentId: user.$id,
                        data: {
                          'name': name,
                          'email': email,
                          'coins': coins,
                          'active': true,
                        },
                      );

                      // Navigate back or show success message
                      Navigator.pop(context);
                    } catch (e) {
                      // Handle specific errors
                      if (e is AppwriteException) {
                        if (e.code == 409) {
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(content: Text('User with this email already exists.')),
                          );
                        } else {
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(content: Text('Error creating user: ${e.message}')),
                          );
                        }
                      } else {
                        // Log the error in case it's not an AppwriteException
                        ScaffoldMessenger.of(context).showSnackBar(
                          SnackBar(content: Text('An unexpected error occurred: ${e.toString()}')),
                        );
                      }
                    }
                  }
                },
                child: Text('Create User'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

### 👍 Expected behavior

It should create a new user in the database with the filled user credentials in the form.

### 👎 Actual Behavior

Getting error of User with this email already exist

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Hello! Do you have added this user previously and then deleted it?

**Comment by WhiteDevil8821** [comment]
Nope I haven't did that even i am getting the same error message when I am doing it with nextjs app

`"use client";

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { databases, account } from '../../appwrite';

export default function CreateUserPage() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [coins, setCoins] = useState(0);
  const router = useRouter();

  const handleCreateUser = async (e) => {
    e.preventDefault();
    console.log(name, email, password, coins); // Log user details

    try {
      // Create user
      console.log('Attempting to create user with email:', email); // Log email
      const user = await account.create('unique()', email, password, name);
      console.log('User created:', user);

      // Create a document in the database for the user
      await databases.createDocument(
        process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID, // Use env variable directly
        process.env.NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID, // Use env variable directly
        user.$id,
        {
          name,
          email,
          coins,
          active: true,
        }
      );

      // Redirect to dashboard or show success message
      router.push('/dashboard');
    } catch (error) {
      // Check for specific error codes
      if (error.code === 409) { // Conflict error: user already exists
        alert('A user with this email already exists. Please use a different email.');
      } else {
        console.error('Error creating user:', error);
        alert('Error creating user. Please try again.');
      }
    }
  };

  return (
    <div>
      <h1>Create New User</h1>
      <form onSubmit={handleCreateUser}>
        <div>
          <label>Name:</label>
          <input 
            type="text" 
            value={name} 
            onChange={(e) => setName(e.target.value)} 
            required 
          />
        </div>
        <div>
          <label>Email:</label>
          <input 
            type="email" 
            value={email} 
            onChange={(e) => setEmail(e.target.value)} 
            required 
          />
        </div>
        <div>
          <label>Password:</label>
          <input 
            type="password" 
            value={password} 
            onChange={(e) => setPassword(e.target.value)} 
            required 
          />
        </div>
        <div>
          <label>Coins:</label>
          <input 
            type="number" 
            value={coins} 
            onChange={(e) => setCoins(Number(e.target.value))} 
            required 
          />
        </div>
        <button type="submit">Create User</button>
      </form>
    </div>
  );
}
`

**Comment by DH-555** [comment]
If you try to create a new user with a different email, are you able to create it?
Are you using Appwrite cloud or self-hosting? If you're self-hosting, what's the Appwrite version you have installed?

**Comment by WhiteDevil8821** [comment]
I have used multiple emails but still getting same issue.

In my next app I am using "appwrite": "^16.0.2"

**Comment by DH-555** [comment]
Are you using Appwrite Cloud?
I think that the error could be related to this?

```                await appwrite.databases.createDocument(
                    databaseId: '',
                    collectionId: 'users',
                    documentId: user.$id,
                    data: {
                      'name': name,
                      'email': email,
                      'coins': coins,
                      'active': true,
                    },
                  );
```

The database ID seems to be empty. I suppose that you removed it due to privicy reasons, right?
Are you sure that the user has write access for that collection in the Appwrite console?


Also, I recommend changing this to log the entire error to have more details:

```
  // Check for specific error codes
  if (error.code === 409) { // Conflict error: user already exists
    alert('A user with this email already exists. Please use a different email.');
  } else {
    console.error('Error creating user:', error);
    alert('Error creating user. Please try again.');
  }
```

Change it to something like this:
```
    console.error('Error creating user:', error);
    alert('Error creating user. Please try again.');
  
```

That way apart from the error code we can have the full error message. Do you can send it?

**Comment by WhiteDevil8821** [comment]
Yes I did the same 

I have tried logging the error.
Error logged - Error creating user: AppwriteException: A user with the same id, email, or phone already exists in this project.
    at Client.eval (webpack-internal:///(app-pages-browser)/./node_modules/appwrite/dist/esm/sdk.js:662:23)
    at Generator.next (<anonymous>)
    at fulfilled (webpack-internal:///(app-pages-browser)/./node_modules/appwrite/dist/esm/sdk.js:46:58)



Also now I am working on the nextJs App and getting same error again and again

**Comment by DH-555** [comment]
Is this happening in Appwrite cloud?
(https://cloud.appwrite.io)

**Comment by WhiteDevil8821** [comment]
When I created the account on the cloud it got created successfully.

**Comment by DH-555** [comment]
Are you sure that the endpoint is correctly pointing to your instance?

What are the logs for the appwrite container?

You can get them with ```docker compose logs appwrire```

Also what appwrite version are you using?
