### ISSUE TITLE
🚀 Enhancement: Per Project Backup and Restore System

### ISSUE THREAD

**Issue by Abhijith4124** [appwrite/appwrite#8800]
### 🔖 Enhancement description

Add the ability to set up project-specific backups through the Appwrite console. Users can schedule automated backups or manually export projects, saving to local storage or S3. Automated backups can have customizable retention periods, allowing users to define how many daily, weekly, or monthly backups to keep. This feature ensures better data management and recovery options per project.

### 🎤 Pitch

Backups are a fundamental aspect of any backend system, especially when dealing with critical applications. While Appwrite provides a wide range of modern backend features, it currently falls short in one key area—granular backup and restore functionality.

At present, it’s possible to back up an entire Appwrite instance, but the platform lacks the ability to restore individual projects. If a single project requires restoration, the entire instance is rolled back, which inadvertently affects all other projects. This is not a viable solution for developers managing multiple projects with different data sets and requirements. Such a limitation introduces unnecessary risks and downtime, which can be particularly problematic for production environments.

### How It Would Be Used:

Automated Project Backups: Developers would be able to schedule backups on a per-project basis, ensuring that each project’s data is stored independently of the rest of the Appwrite instance.

Selective Project Restore: In the event of an issue, developers would have the option to restore a specific project to a previous backup state without reverting or affecting other ongoing projects.

Backup Strategy Flexibility: This would allow developers to adopt a more strategic approach to backups—perhaps performing frequent backups for high-priority projects, while less critical ones follow a different schedule.

By implementing a project-based backup and restore system, Appwrite can significantly increase its appeal to developers working on critical applications. Such a feature would offer peace of mind, enhance data safety, and make Appwrite a more reliable platform for modern, production-grade applications. We believe this feature should be prioritized in future releases to solidify Appwrite’s place as a go-to backend solution for developers who require both flexibility and reliability.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Abhijith4124, thanks for creating this issue! 🙏🏼 This looks like the same ask as https://github.com/appwrite/appwrite/issues/390 which has been closed as Appwrite Cloud now has [database backups](https://appwrite.io/docs/products/databases/backups). As such, I'm going to close this as a duplicate.

Feel free to comment if you have any other questions.
