### ISSUE TITLE
Add Raygun support to the Raygun.com documentation site

### ISSUE THREAD

**Issue by sumitramanga** [appwrite/appwrite#8805]
Hi there,

I wanted to let you know that I stumbled upon this and thought it was awesome what a platform you are providing and that it's integrated Raygun 🤩

I work at Raygun as a Team Lead, Senior Engineer and would love to put the instructions for how to set up AppWrite with Raygun into our public documentation - raygun.com/documentation

This is my starting point to get the ball rolling. Can't wait to see this platform in public docs!

Kind regards,
Sumitra

**Comment by sumitramanga** [comment]
@Meldiron I believe this may interest you :)

**Comment by tessamero** [comment]
Hi @sumitramanga , I am Tessa from the Appwrite team and lead the Developer Relations team. I'd love to get connected. can you email me at tessa@appwrite.io so we can move forward with this discussion?

**Comment by sumitramanga** [comment]
Hi @tessamero Thank you for the email address, I've gone ahead and flicked you an email!

**Comment by tessamero** [comment]
Closing this as we moved forward via email :)
