### ISSUE TITLE
🐛 Bug Report: Custom Domain TLS Certificate Does Not Renew

### ISSUE THREAD

**Issue by leejustin** [appwrite/appwrite#8807]
### 👟 Reproduction steps

I use a Custom Domain in Appwrite Cloud in order to get Google OAuth working. It had been working fine until recently without any changes made on my end. This caused my users to be unable to log in. When I checked the custom domain page in Appwrite Cloud, it showed this:
![Image](https://github.com/user-attachments/assets/2de70fdd-4619-4114-a2ad-96e6f1a4d432)

It says "Auto-renewal: Aug 27, 2024" but today is already Oct 15, 2024.

The fix was for me to delete the Custom Domain and create a new one, forcing a new certificate generation process.

### 👍 Expected behavior

I expected Appwrite to auto-renew its TLS certificate.

### 👎 Actual Behavior

It did not renew.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@leejustin, thanks for creating this issue! 🙏🏼 We did fix a bug recently with certificates not renewing on Cloud, but there may be some jobs in the backlog. As a workaround, you can try to delete the custom domain from Appwrite and then recreate it.

**Comment by eldadfux** [comment]
Fixed and live.

**Comment by apposophy** [comment]
hello everybody, my issue is that the generated certificate gives a weird auto renewal date

Auto-renewal: Dec 2, 1969

i tried to remove the custom domain and recreate it but I got the same thing
