### ISSUE TITLE
User (role: guests) missing scope (account)

### ISSUE THREAD

**Issue by JohnMathew-tech** [appwrite/appwrite#8808]
I am new to Appwrite.  I have written a react app and I am getting the following error when the web application loads for the first time.  My project id is correct.  I am able to login directly from the appwrite console.  The issue comes when I try to get the current user from react.  Please help

account.js

import { Client, Account } from 'appwrite';

const client = new Client();
client
    .setEndpoint("https://cloud.appwrite.io/v1") // Your API Endpoint
    .setProject(PROJECTID); // Your project ID

const account = new Account(client);

export { account };

App.jsx
useEffect(() => {
    try {
      account.get()
      .then((userData) => {
        if (userData) {
          dispatch(login({userData}))
        } else {
          dispatch(logout())
        }
      })
      .finally(() => setLoading(false))
    } catch (error) {
      dispatch(logout());
      setLoading(false);
    }

**Comment by ebenezerdon** [comment]
Hey @JohnMathew-tech, can you share the error message you're getting?

**Comment by eldadfux** [comment]
This error means you’re trying to access a protected endpoint without a valid user session. Before trying to get the user account, you need to create a valid session. When you get this error your app would usually need to redirect the user to your login page.

Once you create the user session on your login page, Appwrite will store it for you in a secure cookie, making it available for any subsequent requests. Once you have that session set, your request to get the user account will work.

You can learn more about Appwrite’s state management here: https://appwrite.io/docs/products/auth/quick-start#check-authentication-state

**Comment by JohnMathew-tech** [comment]
Please close it. The error is gone

**Comment by Sokratesli** [comment]
Same here (like @newathnow problems).
Version: 1.6.0 and Nextjs 15.0.3 with appwrite: ^16.0.2

**Comment by newathnow** [comment]
> Same here (like [@newathnow](https://github.com/newathnow) problems). Version: 1.6.0 and Nextjs 15.0.3 with appwrite: ^16.0.2

i switched to supabase cause didnt get any answer

**Comment by HarshitSaini0** [comment]
I am using react and I getting this error , and I am tring to solve it for like a week now how can fix it

**Comment by Saadwarraich7223** [comment]
i am having the same error

**Comment by riyamittal009** [comment]
same here!

**Comment by NicoAvanzDev** [comment]
For default SSR applications you should follow the guide here:

https://appwrite.io/docs/tutorials

![Image](https://github.com/user-attachments/assets/622b3100-b1fe-4eb8-8a63-c264c0799ff1)

**Comment by Dev-Salem** [comment]
I have the same error with my Flutter app.
```AppwriteException: general_unauthorized_scope, User (role: guests) missing scope (account) (401)```
User logs in successfully, and I direct them to the home page, when they try to use a protected function they get this error. it only goes if they close and open the app again. Seems like Appwrite doesn't refresh the user status right away, even after a successful login.
