### ISSUE TITLE
🐛 Bug Report: Appwrite Environment Variables Breaking Document Creation? Need Help!

### ISSUE THREAD

**Issue by Zia-Ch** [appwrite/appwrite#8813]
### 👟 Reproduction steps

# Problem Statement: Inconsistent Document Creation with Appwrite Environment Variables in Node.js Function

I'm encountering an issue while creating documents using a Node.js function with Appwrite version 1.6.0. The problem occurs when using environment variables to set the endpoint and project ID, as introduced in Appwrite 1.6.0.

## Steps 

1. Set up a self-hosted Appwrite instance (version 1.6.0) on Ubuntu 22.04.
2. Create a new Node.js function in your Appwrite project.
3. Install the required dependencies:
   ```
   npm install node-appwrite
   ```
4. Copy the following code into your function:
 ```javascript
import { Client, Databases, ID } from 'node-appwrite';
export default async ({ req, res, log, error }) => {

    try{
    // Initialize the client SDK as clientX
    let clientX = new Client();
    clientX
        .setEndpoint('http://localhost/v1') 
        .setProject('6709f2886E6A86w8') 
        .setKey(req.headers['x-appwrite-key']);

    // Initialize the database SDK as databaseX
    const databaseX = new Databases(clientX);

    //initialize the client SDK as clientY
    let clientY = new Client();
    clientY
        .setEndpoint(process.env.APPWRITE_FUNCTION_API_ENDPOINT)
        .setProject(process.env.APPWRITE_FUNCTION_PROJECT_ID)
        .setKey(req.headers['x-appwrite-key']);
    
    // Initialize the database SDK as databaseY
    const databaseY = new Databases(clientY);
    
    //initialize some common IDs
    const collectionId = '6710f9b5000395f9d3f0';
    const databaseId = '6709f300000a8e07a263';

    
    //data to be added to the documentX using databseX
    const dataX = {
        "name": "John Doe",
        "age": 30
    };

    //data to be added to the documentY using databseY
    const dataY = {
        "name": "Jack williams",
        "age": 23
    };


    //create a new document in the collection using the databaseX 
    const documentX = await databaseX.createDocument(
        databaseId,
        collectionId,
        ID.unique(),
        dataX
    );

    log(`documentX created with ID: ${documentX.$id} and data: ${JSON.stringify(documentX)}`);

    //create a new document in the collection using the databaseY
    const documentY = await databaseY.createDocument(
        databaseId,
        collectionId,
        ID.unique(),
        dataY
    );

    log(`documentY created with ID: ${documentY.$id} and data: ${JSON.stringify(documentY)}`);


    return res.json({
        "documentX": documentX,
        "documentY": documentY
    });

    }catch(e){
        error(e.message);
        return res.json({"error": e});
    }
};
```

5. Deploy the function to your Appwrite instance.
6. Execute the function and observe the logs.

## Questions
1. Is there any difference in permissions or settings between the hardcoded client (`clientX`) and the environment variable-based client (`clientY`)?
2. Are there any known issues or limitations with using environment variables for endpoint and project ID in Appwrite 1.6.0?

Any insights or suggestions to resolve this issue would be greatly appreciated. Thank you for your help!

### 👍 Expected behavior

Both `documentX` and `documentY` should be created successfully, with valid IDs and correct data structures returned.

### 👎 Actual Behavior

- When using hardcoded values for the endpoint and project ID, document creation works as expected.
- When using environment variables (`process.env.APPWRITE_FUNCTION_API_ENDPOINT` and `process.env.APPWRITE_FUNCTION_PROJECT_ID`), document creation fails silently.

## Error Logs
```
documentX created with ID: 6710ffc800129bb4cfaf and data: {"name":"John Doe","age":30,"$id":"6710ffc800129bb4cfaf","$permissions":[],"$createdAt":"2024-10-17T12:15:04.549+00:00","$updatedAt":"2024-10-17T12:15:04.549+00:00","$databaseId":"6709f300000a8e07a263","$collectionId":"6710f9b5000395f9d3f0"}

documentY created with ID: undefined and data: {"total":1,"documents":[{"name":"John Doe","age":30,"$id":"6710ffc800129bb4cfaf","$createdAt":"2024-10-17T12:15:04.549+00:00","$updatedAt":"2024-10-17T12:15:04.549+00:00","$permissions":[],"$databaseId":"6709f300000a8e07a263","$collectionId":"6710f9b5000395f9d3f0"}]}
```

Note that `documentY` has an undefined ID and returns a list of documents instead of the created document.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

- Appwrite version: 1.6.0
- Server: Self-hosted on Ubuntu 22.04
- Node.js version: 18.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by SakkyOP** [comment]
Did you setup dotenv for your project correctly?

**Comment by stnguyen90** [comment]
Troubleshooting on Discord: https://discord.com/channels/564160730845151244/1296452918169567262
