### ISSUE TITLE
🐛 Bug Report: Update Team Membership Status doesn't work with Server SDK's

### ISSUE THREAD

**Issue by pingu2k4** [appwrite/appwrite#8828]
### 👟 Reproduction steps

Call's to [Update Team Membership Status](https://appwrite.io/docs/references/1.6.x/server-rest/teams#updateMembershipStatus) will always fail. It is listed however as being accessible with server SDK's.

### 👍 Expected behavior

Work correctly, or docs should unlist this as a server endpoint.

### 👎 Actual Behavior

Response:
```
{
    "message": "app.6649523d000d7884ae74@service.cloud.appwrite.io (role: applications) missing scope (public)",
    "code": 401,
    "type": "general_unauthorized_scope",
    "version": "1.6.0"
}
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@pingu2k4, would you please try executing the method without an API key?

**Comment by pingu2k4** [comment]
@stnguyen90 No API Key works fine, but that is essentially the same as the client request at that point? Is this intended?

**Comment by stnguyen90** [comment]
@pingu2k4, yes, it's intended because `teams.updateMembershipStatus()` is meant to be called by the client/user to accept an invitation using the provided secret from the email.

When `teams.createMembership()` is called with a server SDK, the user is automatically added and no email is sent so there is no need to call `teams.updateMembershipStatus()`.

**Comment by pingu2k4** [comment]
OK no worries. I kind of feel like this doesn't belong in the server SDK then, as it isn't intended to work with the secret.

I am building .net SDK's (for client and server) and have removed it from the server SDK, as the server SDK by default will send the api key with each request. Disabling the sending of the api key for some requests would be a weird sort of additional hassle to introduce.

I do, however, support running the client SDK on either the client or the server, and have different dependency injection routes depending on what you need. (If you inject client SDK for server usage, it won't hang onto cookies from past requests, for example). So the intended usage with my SDK's is that if you need to call a client endpoint from the server, you would inject the client SDK using the "for server" route which I feel works better than only sometimes sending API key with server SDK.
