### ISSUE TITLE
🐛 Bug Report: .wav audio files on buckets have wrong mimetype

### ISSUE THREAD

**Issue by djimonlee** [appwrite/appwrite#8829]
### 👟 Reproduction steps

- upload .wav file to any bucket
- try to open the file via the from appwrite provided URL

### 👍 Expected behavior

- file should be interpreted as audio file and a audio player should appear in the browser like it does with .mp3 (audio/mpeg) files

### 👎 Actual Behavior

- the browser is interpreting the file as a txt file displaying the binary
![Image](https://github.com/user-attachments/assets/1ac7ab21-b4f0-4d54-9ea9-6c936f305ab1)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by djimonlee** [comment]
it is important for audio streaming since the stream wont work when the mimetype is wrong and not an audio file

**Comment by eldadfux** [comment]
we originally limited the allowed mime-types to protect against any malicious attempts executing malicious code in the browser. For example, this is true for files like PDF or SVG which require careful sanitization. From what I can see this should be fine for common audio and video files. I asked the team to do some research and confirm, if all good we can add them.

**Comment by christyjacob4** [comment]
@djimonlee thanks for the bug report. We've gone ahead and added support for it here https://github.com/appwrite/appwrite/pull/8846
This will be deployed to cloud soon 👍

**Comment by djimonlee** [comment]
@eldadfux @christyjacob4 thank you so much for the quick fix! 🙏
