### ISSUE TITLE
🐛 Bug Report: Invalid translations in Swedish templates

### ISSUE THREAD

**Issue by Megamannen** [appwrite/appwrite#8835]
### 👟 Reproduction steps

Look at the translation file, notice these.
https://github.com/appwrite/appwrite/blob/a49c3a33f0fd831423afa7a0b53df2c5d709fc2b/app/config/locale/translations/sv.json#L242
Template already contains ,
https://github.com/appwrite/appwrite/blob/a49c3a33f0fd831423afa7a0b53df2c5d709fc2b/app/config/locale/templates/email-otp.tpl#L1

This probably shouldn't have ,
https://github.com/appwrite/appwrite/blob/a49c3a33f0fd831423afa7a0b53df2c5d709fc2b/app/config/locale/translations/sv.json#L246

![Image](https://github.com/user-attachments/assets/e17a7a71-9b21-4bf7-9d31-56e7bc31bb24)

### 👍 Expected behavior

That the translation doesn't contain commas

### 👎 Actual Behavior

It contains commas

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

v1.6.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
@Megamannen thanks for raising this issue. We have merged the fix here 
https://github.com/appwrite/appwrite/pull/8892
