### ISSUE TITLE
🐛 Bug Report: Multiple deployments triggered

### ISSUE THREAD

**Issue by gemini-gen-ai** [appwrite/appwrite#8837]
### 👟 Reproduction steps

I have implemented two appwrite function with different branches in the same repository, while deploy the one branch code, i m expected to deploy in the respective branch function instead of that, Both the functions in the same repository deployment happening.

### 👍 Expected behavior

i m expected to deploy in the respective branch function instead of that, Both the functions in the same repository deployment happening.

### 👎 Actual Behavior

It should deploy only to the branch specific function

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gemini-gen-ai, thanks for creating this issue! 🙏🏼 This looks like the same as https://github.com/appwrite/appwrite/issues/7473 so I'm going to close this as a duplicate. I suggest you add a 👍🏼 to https://github.com/appwrite/appwrite/issues/7473.
