### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by M7MMAD-OMAR** [appwrite/appwrite#8847]
### 👟 Reproduction steps

Welcome,

I am facing the following issue: I have a server running Ubuntu with Virtualmin as the control panel, and it has several websites hosted. 

Now, I want to add the AppWrite service to my server using Docker.

When selecting the ports, I choose 81 and 8443 to avoid conflicts because port 80 is already in use. Then, I assign my domain and configure it.

Everything is working now. However, when I go to my domain, AppWrite doesn’t load. It only works when I access the IP:81 directly, without any issues.

What do you think the solution is?

### 👍 Expected behavior

I was expecting it to work on the domain as well as the IP without any issues on port 81.

### 👎 Actual Behavior

when I go to my domain, AppWrite doesn’t load. It only works when I access the IP:81 directly, without any issues.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by M7MMAD-OMAR** [comment]
I'm using Apache2

**Comment by eldadfux** [comment]
For your domain to work without adding port `:81` you need another proxy in front of Appwrite and your other app on port 80 that will listen to port 80 and 433 and forward requests by hostname to the relevant service/container. You can use something like nginx or traefik to achieve this.

This is not an Appwrite specific issue.

**Comment by M7MMAD-OMAR** [comment]
Sorry for opening it in an unrelated place, but I couldn't access the Discord server.

Thank you; you have helped me a lot and guided me in the right direction. I set up a Reverse Proxy using Apache2 since I was using it before. Thank you!

**Comment by M7MMAD-OMAR** [comment]
> For your domain to work without adding port `:81` you need another proxy in front of Appwrite and your other app on port 80 that will listen to port 80 and 433 and forward requests by hostname to the relevant service/container. You can use something like nginx or traefik to achieve this.
> 
> This is not an Appwrite specific issue.

Sorry for opening it in an unrelated place, but I couldn't access the Discord server.

Thank you; you have helped me a lot and guided me in the right direction. I set up a Reverse Proxy using Apache2 since I was using it before. Thank you!
