### ISSUE TITLE
🐛 Bug Report: Hashing does not match when migrating users from Firebase to Appwrite

### ISSUE THREAD

**Issue by cynthiachanky** [appwrite/appwrite#8881]
### 👟 Reproduction steps

1. Retrieve `hash_config` from Firebase console
2. Export all the users with `passwordHash` and `passwordSalt` using Firebase Admin SDK
3. Create users with Scrypt modified password on Appwrite using REST API
4. Fail to log in with the original password

### 👍 Expected behavior

Users shall be able to log in with the original password after migrating to Appwrite.

### 👎 Actual Behavior

When logging in with the original password, "Invalid credentials. Please check the email and password." will be thrown.

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Self-hosted Appwrite instance running on v1.6.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@cynthiachanky, thanks for creating this issue! 🙏🏼 Can you share some code? Did you look at [this tutorial](https://dev.to/appwrite/migrate-firebase-users-to-appwrite-5aia) for reference? I was able to successfully migrate users from Firebase to Appwrite when I tried this a year or so ago.

**Comment by cynthiachanky** [comment]
@stnguyen90 Here is how I migrate the data from Firebase. The hashing config is directly copied from Firebase console and stored in the .env file.

```typescript
import { initializeApp, cert, type App } from 'firebase-admin/app'
import { getAuth, type Auth, type ListUsersResult, type UserRecord } from 'firebase-admin/auth'
import serviceAccount from './config.json'

const createUser = async (
    uid: string,
    email: string,
    passwordHash: string,
    passwordSalt: string,
) => {
    const res = await fetch(`${process.env.APPWRITE_HOST}/v1/users/scrypt-modified`, {
        method: 'POST',
        headers: {
            'X-Appwrite-Project': process.env.APPWRITE_PROJECT as string,
            'X-Appwrite-Key': process.env.APPWRITE_KEY as string,
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            userId: uid,
            email,
            password: passwordHash,
            passwordSalt,
            passwordSaltSeparator: process.env.SALT_SEPARATOR as string,
            passwordSignerKey: process.env.SIGNER_KEY as string,
        }),
    })
    return await res.json()
}

;(async () => {
    const app: App = initializeApp({ credential: cert(serviceAccount) })
    const auth: Auth = getAuth(app)
    let token
    do {
        const { pageToken, users }: ListUsersResult = await auth.listUsers(undefined, token)
        await Promise.all(
            users.map(({ uid, email, passwordHash, passwordSalt }: UserRecord) =>
                createUser(uid, email, passwordHash, passwordSalt),
            ),
        )
        token = pageToken
    } while (token)
})()
```

**Comment by stnguyen90** [comment]
@cynthiachanky, your code seems fine. Maybe you can log the `password`, `passwordSalt`, `passwordSaltSeparator`, and `passwordSignerKey` to validate they are correct.

I just ran my script that I used to migrate and it worked successfully and I was able to log in with my old firebase user email and password.

**Comment by cynthiachanky** [comment]
@stnguyen90 I noticed that the base64 strings (both the hash and the salt) exported from CLI and Admin SDK are slightly different.

https://github.com/xeewi/firebase-scrypt/blob/c2339651d8d306926492b2346be1505467ee18a6/src/firebaseScrypt.js#L29
```javascript
/**
 * base64decode - Decodes a base64 encoded string into a Buffer
 *
 * The hashes exported via the firebase CLI's auth:export command use the
 * standard base64 alphabet with + and / being used in addition to the 62
 * alphanumeric characters.
 *
 * The hashes exported via the Admin SDK's
 * listUsers command use the URL safe base64 alphabet which uses - and _
 * instead.
 *
 * This function allows this library to be compatible with hashes in either
 * format.
 *
 * @param {string} encoded Base64 encoded string
 * @returns {Buffer} decoded
 */
function base64decode (encoded) {
  return Buffer.from(encoded.replace(/-/g, '+').replace(/_/g, '/'), 'base64')
}
```

After replacing the characters, I can use the original password to log in. I am not sure if this is the issue from the Javascript SDK only or across all other languages. Would it be better to support both formats in Appwrite?
