### ISSUE TITLE
🚀 Enhancement: Schedule time for cron

### ISSUE THREAD

**Issue by spyshow** [appwrite/appwrite#8898]
### 🔖 Enhancement description

 the Schedule time for cron can be set dynamically  

### 🎤 Pitch

As I can see there is no way to set the cron Schedule time dynamically.
if we can add the API a parameter so we can set the Schedule time to run with the passed time when creating the function. 
if we can add this also for cloud and local functions

thanks 

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@spyshow, thanks for creating this issue! 🙏🏼 It's possible to execute a function at a certain time in the future via [delayed executions](https://appwrite.io/docs/products/functions/execute#delayed-executions). Is that what you're looking to do? Otherwise, would you please clarify what you need to do?

**Comment by spyshow** [comment]
no , in delayed executions it will run once only. i want to add time to run every 1 or 5 min ( * 5 * * * )

**Comment by stnguyen90** [comment]
You can also [schedule](https://appwrite.io/docs/products/functions/execute#schedule). What's the difference between our scheduling vs what you're asking for?

**Comment by stnguyen90** [comment]
Who do you mean by website user? Console user or user using your app?

**Comment by spyshow** [comment]
My website

**Comment by stnguyen90** [comment]
And your website will have multiple users that may want to schedule different execution times?

**Comment by stnguyen90** [comment]
Do you need multiple schedules? Otherwise, you can update it in the Appwrite Console or use a server SDK and call [`functions.update()`](https://appwrite.io/docs/references/cloud/server-nodejs/functions#update).

**Comment by spyshow** [comment]
yeah that will work , thanks.
