### ISSUE TITLE
🐛 Bug Report: Invalid Argument : 502 Bad Gateway

### ISSUE THREAD

**Issue by sbhatm1213** [appwrite/appwrite#8906]
### 👟 Reproduction steps

**_[Invalid Argument : 502 Bad Gateway]_**
I keep getting 502 Bad Gateway many times on cloud appwrite .
DB, Auth, Functions, etc everything stops working. 
Why does Appwrite keep going down like this ? Please tell me if there will be a fix soon ? 

![Image](https://github.com/user-attachments/assets/232b74e4-5454-46b5-8dbf-c725fab81336)

### 👍 Expected behavior

Expected Cloud Appwrite to be a proper functional BaaS platform

### 👎 Actual Behavior

This keeps happening so many times - 502 bad gateway on Appwrite home 
Even Database queries, Auth, etc stops working .
**_Invalid Argument : 502 Bad Gateway_**

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
The team is looking into this issue as we speak.

**Comment by eldadfux** [comment]
Is this error consistent? any steps that can help reproduce it?
Are you seeing the same issue across different browsers?

**Comment by sbhatm1213** [comment]
@eldadfux 
Experiencing multiple times a day. 
Reproduction - 502 screen comes on the Appwrite Dashboard itself 
Even DB, Auth, other services throw this error at that time

**Comment by stnguyen90** [comment]
@sbhatm1213, we've recently made some improvements to reduce the 502 errors. Have you noticed an improvement? If it happens again, please take note of the timestamp (including timezone) and source IP address and share it with us so we can troubleshoot further.
