### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by leaderfrank** [appwrite/appwrite#8908]
### 👟 Reproduction steps

I made a function execution event users.*.create

It works fine when signing up for a new user manually, but when I use login by Google or GitHub it does not trigger.

### 👍 Expected behavior

Get triggered by creating user event when using login by provider.

### 👎 Actual Behavior

Not triggered by creating user event when using login by provider.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Duplicated: https://github.com/appwrite/appwrite/issues/2406
