### ISSUE TITLE
Github aouth not working

### ISSUE THREAD

**Issue by shemaikuzwe** [appwrite/appwrite#8914]
### 👟 Reproduction steps

Github  authentication not working

### 👍 Expected behavior

it shoud work as expected  the account.create,.createOAuth2Session()  TS2551: Property createOAuth2Session does not exist on type Account. Did you mean createSession?
i think you need to view it

### 👎 Actual Behavior

   const session = await account.createOAuth2Session(
        "github",
        "http://localhost:3000/dashboard", // Success URL
        "http://localhost:3000", // Failure URL
      );

this property should exist its alternative i was thinking it works the same is  createOAuth2Token() but it just returning the url of github authenctication but not redirecting there

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
What SDK version are you using? And what platform?

**Comment by shemaikuzwe** [comment]
I am using node appwrite and ubuntu

**Comment by DH-555** [comment]
@shemaikuzwe What version specifically of the appwrire node SDK?

**Comment by DH-555** [comment]
@shemaikuzwe What version specifically of the appwrire node SDK?

**Comment by shemaikuzwe** [comment]
@DH-555   v12.2.1

**Comment by DH-555** [comment]
Server sided and with node SDK you can't use create/use oauth2 session server side. Instead, you need/can create an oauth token this way:

```await account.createOAuth2Token(
    sdk.OAuthProvider.Amazon, // provider
    'https://example.com', // success (optional)
    'https://example.com', // failure (optional)
    [] // scopes (optional)
);```

**Comment by shemaikuzwe** [comment]
@DH-555  after creating the token then use redirect to go to that authorize page

**Comment by DH-555** [comment]
@shemaikuzwe Yes, you should redirect there.

Once you get the URL, you need to manually route/redirect the user. 
It's something that will depend on the framework or technology you're using.

I recommend creating a post in our Discord support channel with the code if you're still stuck for a better assistance 😄
https://discord.com/channels/564160730845151244/1072905050399191082

**Comment by shemaikuzwe** [comment]
@DH-555  k thanks
