### ISSUE TITLE
🐛 Bug Report: Failure(io.appwrite.exceptions.AppwriteException: Storage bucket with the requested ID could not be found.)

### ISSUE THREAD

**Issue by pranayansaikia** [appwrite/appwrite#8918]
### 👟 Reproduction steps

Failure(io.appwrite.exceptions.AppwriteException: Storage bucket with the requested ID could not be found.)

### 👍 Expected behavior

 it should work

### 👎 Actual Behavior

Failure(io.appwrite.exceptions.AppwriteException: Storage bucket with the requested ID could not be found.)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by aditya000099** [comment]
did you try the solutions mentioned in this thread: https://appwrite.io/threads/1092655569531326554

**Comment by pranayansaikia** [comment]
Solved
