### ISSUE TITLE
🐛 Bug Report: Redis exception - MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk.

### ISSUE THREAD

**Issue by abhidev54** [appwrite/appwrite#8921]
### 👟 Reproduction steps

My appwrite is throwing 500 internal server error on login or any other options, seems like it is crashed or corrupted.

When i checked logs, i see these errors in logs, not sure if its related to main issue but this is concerning me.

[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
[Error] Type: RedisException
[Error] Message: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[Error] File: /usr/src/code/vendor/utopia-php/queue/src/Queue/Connection/Redis.php
[Error] Line: 55
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php

### 👍 Expected behavior

Appwrite should run smoothly.

### 👎 Actual Behavior

My appwrite is throwing 500 internal server error on login or any other options, seems like it is crashed or corrupted.

When i checked logs, i see these errors in logs, not sure if its related to main issue but this is concerning me.

[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
[Error] Type: RedisException
[Error] Message: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[Error] File: /usr/src/code/vendor/utopia-php/queue/src/Queue/Connection/Redis.php
[Error] Line: 55
[Error] Type: Utopia\Exception
[Error] Message: Error handler had an error: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Linux

### 🧱 Your Environment

1.6.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
What are the server specs? RAM, cores, etc?

**Comment by fidelix** [comment]
Sounds like you were out of storage.
