### ISSUE TITLE
🚀 Enhancement: Center the content in the footer

### ISSUE THREAD

**Issue by MohcineDev** [appwrite/appwrite#8936]
### 🔖 Enhancement description

I noticed that the content in the footer on mobile devices, including the social media links and the privacy/cookie policy links, is not centered. 

### 🎤 Pitch

It would improve the layout and make the design more aesthetically pleasing if these items could be centered in the footer.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
If this is happening in the appwrite website, create an issue in the website repo instead: https://github.com/appwrite/website
