### ISSUE TITLE
🐛 Bug Report: Not receiving SMS OTP

### ISSUE THREAD

**Issue by nahidhasan-dev** [appwrite/appwrite#8945]
### 👟 Reproduction steps

did not receive the OTP (One-Time Password) via SMS

### 👍 Expected behavior

All code is clear. It's showing code has been sent but didn't get received OTP.

### 👎 Actual Behavior

code has been sent i didn't get sms......

```dart
Future<String?> createPhoneToken(String phone) async {
  final client = Client().setEndpoint(endpoint).setProject(projectId);

  final account = Account(client);

  try {
    final token = await account.createPhoneToken(
      userId: ID.unique(),
      phone: phone,
    );
    final createdUserId = token.userId;
    print('Token created for user ID: $createdUserId');
    return createdUserId;
  } catch (e) {
    print('Error creating phone token: $e');
    return null; // Indicate failure
  }
}




Future<void> createUserSession(
    String userId, String otp, String number, context) async {
  final client = Client().setEndpoint(endpoint).setProject(projectId);
  final account = Account(client);
  final databases = Databases(client);
  try {
    final session = await account.createSession(
      userId: userId,
      secret: otp,
    );

    String sessionId = session.$id;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('sessionId', sessionId);
    await prefs.setString('userId', userId);

    account
        .updatePhoneVerification(userId: userId, secret: otp)
        .whenComplete(() async {
      showtoast(context, 'Logged in successful');
      
      
    });
    print('Session created for user ID: ${session.userId}');
  } catch (e) {
    print('Error creating session: $e');
    showtoast(context, 'OTP is not correct!');
    codeController.setOtpFilled(false);
  }
}
```
### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite 13.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Hello! 
This issue is probably project-specific or even phone-specific.

Consequently I recommend creating a support post in our Discord server or through the Appwrite support email if you have Appwrite pro so the team can get all the needed info that could be confidential such as phone numbers, country, project IDs or timestamps.

You can join here: https://discord.gg/kDD4vbTy

**Comment by mberrezak** [comment]
Same problem here using Twilio as provider. The messaging service of the appwrite UI is working, so the Twilio config seems to be valid. But the createPhoneToken() logic is not sending any SMS nor does it create logs or exceptions. The response is 201 a user is created but the secret field is empty an no SMS sending attempts happened on the Twilio logs.
