### ISSUE TITLE
🚀 Enhancement: Improve `CONTRIBUTING.md` and `README.md` Files

### ISSUE THREAD

**Issue by anchalchaturvedi08** [appwrite/appwrite#8953]
### 🔖 Enhancement description

I would like to improve the `CONTRIBUTING.md` and `README.md` files by adding clear contribution guidelines, detailed setup instructions, and a project overview. Please assign this issue to me, Anchal Chaturvedi.

Thank You.

### 🎤 Pitch

Improving the `CONTRIBUTING.md` and `README.md` files is essential for several reasons:

1. **Enhanced Contributor Experience**: Clear guidelines and instructions help new contributors understand how to set up the project, adhere to coding standards, and follow the contribution process. This reduces the entry barrier for new contributors and encourages more people to contribute.

2. **Consistency and Quality**: Detailed contribution guidelines ensure that all contributions follow the same standards, maintaining the quality and consistency of the codebase. This is particularly important as the project grows and more contributors join.

3. **Better Understanding of the Project**: A comprehensive `README.md` file provides users and potential contributors with a clear understanding of the project's purpose, how to install and use it, and how they can contribute. This transparency fosters a more engaged and active community around the project.

### Examples:
- **Contribution Guidelines**: The `CONTRIBUTING.md` file can include sections like:
  - **Introduction**: Welcoming new contributors.
  - **Setup Instructions**: Step-by-step guide to setting up the development environment.
  - **Coding Standards**: Guidelines on code style and commit messages.
  - **Pull Request Process**: Steps to submit a pull request.

- **README.md**:
  - **Project Overview**: Briefly describe what the project does and its goals.
  - **Installation Instructions**: Commands and steps to install the project.
  - **Usage Instructions**: Examples of how to run and use the project.
  - **Contributing**: A link to the `CONTRIBUTING.md` file for detailed guidelines.

By implementing these changes, we can ensure that the project is more accessible, easier to contribute, and more attractive to new contributors. This ultimately leads to a more robust and well-maintained project.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by myreplywillbeshort** [comment]
Very good solution!

**Comment by stnguyen90** [comment]
@anchalchaturvedi08, thanks for raising this issue! 🙏🏼 We already have a [readme](https://github.com/appwrite/appwrite/blob/main/README.md) and [contributing guide](https://github.com/appwrite/appwrite/blob/main/CONTRIBUTING.md). What exactly is wrong that needs updating?
