### ISSUE TITLE
Appwrite for Flutter Windows Not Working - Invalid Origin Error (403)

### ISSUE THREAD

**Issue by anmol-me** [appwrite/appwrite#8954]
**Issue Description:**

I'm trying to integrate Appwrite with my Flutter app on Windows, but I'm facing an issue with origin validation. Here is the error message I am receiving:

```
AppwriteException: general_unknown_origin, Invalid Origin. Register your new client (app_1_appwrite) as a new Windows platform on your project console dashboard (403)
```

**Steps Taken:**
1. I added the `projectId` and `apiEndpoint` in my Flutter application according to my Appwrite project settings.
2. I attempted to add my application ID as directed in the documentation.
   - I got the `applicationId` in `defaultConfig` located at `android/app/build.gradle` which looks like `"com.example.app_1_appwrite"`.
3. I then added this application ID in the Appwrite console under **Platform > Windows (Flutter)** with my package name.

**Expected Result:**
The Flutter app should connect to Appwrite successfully on Windows.

**Actual Result:**
The app is still blocked with an `Invalid Origin` error (403).

**Additional Information:**
- Appwrite SDK version: 13.0.0
- Flutter version:  Channel stable, 3.24.4
- Windows OS version:   10.0.19045.5011

I would appreciate any guidance on how to get Appwrite working with Flutter on Windows.

---

**Attachments:**
![Image](https://github.com/user-attachments/assets/6ba70eaa-0ebd-4762-929f-cec895aacb66)
![Image](https://github.com/user-attachments/assets/45b1a8c8-cc81-4fe2-9ade-8e45e99d3c0b)

**Comment by DH-555** [comment]
Hello! I think it should be only app_1_appwrite without the com.example.
