### ISSUE TITLE
📚 Documentation: Please Clarify Flutter Windows & Linux Setup for OAuth (success / failure)

### ISSUE THREAD

**Issue by drexhacker** [appwrite/appwrite#8967]
### 💭 Description

Hey Team thanks for the good work I really appreciate but for now I would like to get clear instructions for OAuth session create on Windows & Linux, atleast for web and mobile so far so good.

Thanks in advance.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Hello! I'm continuing with your support request in our discord server:
https://discord.com/channels/564160730845151244/1306030032434761849

**Comment by DH-555** [comment]
Update on this, It's not possible as the flutter package that appwrite uses is not supporting it:

**Comment by drexhacker** [comment]
Okay That's noted

**Comment by DH-555** [comment]
Update on this for future users:
Appwrite uses a fork of that package: https://pub.dev/packages/flutter_web_auth_2

So the SDK will have support soon in future releases
