### ISSUE TITLE
🐛 Bug Report:  All AUTH Users and Database Data Removed Unexpectedly

### ISSUE THREAD

**Issue by amjarmed** [appwrite/appwrite#8979]
### 👟 Reproduction steps

I encountered a serious issue where all authentication users and database records were deleted without any apparent reason or warning. This unexpected data loss occurred while I was working on my project, and I could not identify the cause. 

### 👍 Expected behavior

All users and database data should remain intact unless explicitly deleted.

### 👎 Actual Behavior

All users in authentication and database records were deleted simultaneously without any action or command to delete them.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Hello! Looks like there is an issue with the connection to a database in Appwrite Cloud. The team is currently working on restoring the data of the affected database: https://status.appwrite.online/incident/461590?mp=true
