### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by code-with-divyanshu** [appwrite/appwrite#8980]
### 👟 Reproduction steps

All Auth , Users, Client and Database deleted automatically and unexpectally.

### 👍 Expected behavior

No Database and Auth Show on Console.

### 👎 Actual Behavior

Database and Auth Show on Console.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Hello! Looks like there is an issue with the connection to a database in Appwrite Cloud.
The team is currently working on restoring the data of the affected database: https://status.appwrite.online/incident/461590?mp=true

Avoid creating duplicated issues: https://github.com/appwrite/appwrite/issues/8979
