### ISSUE TITLE
🚀 Enhancement: Support for Critical Alerts in Messaging

### ISSUE THREAD

**Issue by DH-555** [appwrite/appwrite#8981]
### Discussed in https://github.com/appwrite/appwrite/discussions/8977

<div type='discussions-op-text'>

<sup>Originally posted by **afonsoingles** November 14, 2024</sup>
Hi! Does appwrite support critical alerts for apple devices? If yes, where can i find documentation about it?</div>

**Comment by stnguyen90** [comment]
@DH-555, would this be the same as https://github.com/appwrite/appwrite/issues/8086?
