### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by arcmotion** [appwrite/appwrite#8982]
### 👟 Reproduction steps

Login, go to console page https://cloud.appwrite.io/console 

### 👍 Expected behavior

All pages are working as they used to.

### 👎 Actual Behavior

All the pages under https://cloud.appwrite.io/console are returning 500 error.: Databases, Functions, Messaging, Storage
![Image](https://github.com/user-attachments/assets/a0607781-0ee7-4720-9232-bfa3b7d16f49)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by vinrain-coder** [comment]
i also noticed the same. I went to the database and it returns 500 error.

**Comment by stnguyen90** [comment]
@arcmotion, thanks for creating this issue! 🙏🏼 

We are aware of some service disruptions for some projects and are investigating the issue. For the latest update, please keep an eye on our [status page](https://status.appwrite.online/).

Thanks for your understanding and patience. Please let me know if you have any questions.
