### ISSUE TITLE
🐛 Bug Report: App Write Console - Existing Platform and Database Not Showing, and encountering 500 internel server error on app write console -> project -> database

### ISSUE THREAD

**Issue by m-dot-dev** [appwrite/appwrite#8983]
### 👟 Reproduction steps

1. Login to app write console
2. Select Project:
    2.1. Existing Platforms are missings / not visible
3. Click Database
    3.1 Getting 500 Internel Server Error

### 👍 Expected behavior

2.1. Existing Platforms should be shown

3.1 Existing Database should be shown

### 👎 Actual Behavior

2.1. Existing Platforms are missings / not visible

3.1 Getting 500 Internel Server Error

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

App write cloud console 

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Yashraj0888** [comment]
`Same issue `

**Comment by DH-555** [comment]
Hello! Looks like there is an issue with a database in Appwrite Cloud.
The team is currently working on restoring the data of the affected database: https://status.appwrite.online/incident/461590?mp=true
