### ISSUE TITLE
🐛 Bug Report:  Getting 500 Server Error on Database Access

### ISSUE THREAD

**Issue by Yashraj0888** [appwrite/appwrite#8984]
### 👟 Reproduction steps

 Getting 500 Server Error on Database Access

Description: I'm encountering a 500 Server Error whenever I try to access my database in Appwrite. This error occurs when I attempt to view my database or collections directly through the Appwrite console and also when I try to list documents or perform any database-related operations through the API.

**Steps to Reproduce:**

1. Open the Appwrite console.
2. Navigate to the database section and select a database or collection.
3. Attempt to view, add, or edit documents.
4. Alternatively, run a Databases.listDocuments call from the API to access any documents.
5. Expected Behavior: The database and collections should load without any issues, allowing me to view and manage documents.

**Actual Behavior:** A 500 Server Error is displayed, and I am unable to access or modify any database content.

Error Details: Here’s the stack trace and error message I’m seeing when attempting to access the database via the API:

Copy code
```
⨯ AppwriteException: Server Error
    at _Client.call
    at async Databases.listDocuments
    at async getUserByEmail
    at async createAccount
digest: "3831477463"
POST /sign-up 500 in 1451ms
```

**Additional Information:** I've verified that my API keys and permissions are set correctly, and other parts of the Appwrite console work as expected. This issue seems isolated to the database section.

### 👍 Expected behavior

1. Accessing the database in the Appwrite console should load the database dashboard, allowing me to view, add, or edit documents without errors.
2. API calls (e.g., Databases.listDocuments) should successfully retrieve data from the database and collections without returning a server error.

### 👎 Actual Behavior

1. Accessing the database via the Appwrite console results in a  `500 Server Error` , preventing me from viewing or managing any database content.
2. API calls to interact with the database also return a 500 Server Error, making it impossible to retrieve or modify documents programmatically.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Hello! Looks like there is an issue with the connection to a database in Appwrite Cloud.
The team is currently working on restoring the data/connection of the affected database: https://status.appwrite.online/incident/461590?mp=true
