### ISSUE TITLE
🐛 Bug Report: Continue to get 500 Server Error.  Tired of recreating entire database!

### ISSUE THREAD

**Issue by TyByers21** [appwrite/appwrite#8985]
### 👟 Reproduction steps

I created a database with Users, Saves, Posts and media.  None of the side bar attributes are working (Auth, Database, Functions, Storage) Everything is returning 500 Server Error.  

So I RECREATED the entire thing.  Sounded like a workaround, and everything was fine, but I created a media file within Storage.  Whenever I try to access this file I'm greeted with "500 Server Error" again.  

### 👍 Expected behavior

I created a database with Users, Saves, Posts and media.  None of the side bar attributes are working (Auth, Database, Functions, Storage) Everything is returning 500 Server Error.  

So I RECREATED the entire thing.  Sounded like a workaround, and everything was fine, but I created a media file within Storage.  Whenever I try to access this file I'm greeted with "500 Server Error" again.  

### 👎 Actual Behavior

I created a database with Users, Saves, Posts and media.  None of the side bar attributes are working (Auth, Database, Functions, Storage) Everything is returning 500 Server Error.  

So I RECREATED the entire thing.  Sounded like a workaround, and everything was fine, but I created a media file within Storage.  Whenever I try to access this file I'm greeted with "500 Server Error" again.  

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by fredtinotenda3** [comment]
I'm also facing 500 server error to access database

**Comment by DH-555** [comment]
Hello! You don't need to recreate anything.

There is an issue with a database in Appwrite Cloud.
The team is currently working on restoring the data of the affected database and making it work again: https://status.appwrite.online/incident/461590?mp=true

**Comment by fredtinotenda3** [comment]
Thank you for getting in touch.
So by tomorrow it will be sorted out ?

**Comment by eldadfux** [comment]
Yes, it should be sorted in the next few hours.

**Comment by fredtinotenda3** [comment]
Awesome thank you so much
I was just worried about the error.

I get to know appwrite through Javascript mastery

**Comment by fredtinotenda3** [comment]
Thank you for the restoration of data
