### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by MartGelo** [appwrite/appwrite#8986]
### 👟 Reproduction steps

I am experiencing a 500 Server Error when trying to create an attribute for the backend of my system project. However, I have been unable to resolve the issue.

Steps to Reproduce:
Open the Appwrite console.
Navigate to the "Backend" section.
Click on the "Attributes" tab.
Click on the "Create Attribute" button.
Enter the attribute name and type.
Click on the "Create" button.

### 👍 Expected behavior

The attribute should be created successfully.

### 👎 Actual Behavior

A 500 Server Error is displayed. ![Image](https://github.com/user-attachments/assets/bb12871b-cc07-4cbc-a0f8-9ce140e73eef)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

version  1.6.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by prashantsinha123** [comment]
I am also experiencing the same issue
![Image](https://github.com/user-attachments/assets/f689a3e3-d61f-43f0-ad3f-3135e22cffa7)

Please help me also

**Comment by DH-555** [comment]
@prashantsinha123 @MartGelo 
There is an issue with a database in Appwrite Cloud.
The team is currently working on restoring the data of the affected database and making it work again: https://status.appwrite.online/incident/461590?mp=true

The estimated ETA given by the team is about an hour
