### ISSUE TITLE
🐛 Bug Report: 500 Internal Server Error

### ISSUE THREAD

**Issue by kanewick** [appwrite/appwrite#8987]
### 👟 Reproduction steps

Whenever I open up my intergration, IE Databases, Auth ect. I am recieving a 500 internal server error. Is there any ongoing maintenance?

### 👍 Expected behavior

It should load my data stored on the cloud

### 👎 Actual Behavior

500 server error

![Image](https://github.com/user-attachments/assets/df8bb154-58ed-4dc7-b7a7-c217c6fe2b13)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Is this still persisting for you?
@kanewick

**Comment by kanewick** [comment]
Hey!

So I managed to fix this issue somewhat. From what I have seen Expo have recently updated to SDK 52? If you do the upgrade and don't match the package dependencies then AppWrite causes a massive fuss, not in the IDE, just in the actual cloud environment.

As soon as I revered back my package.json and rolled back, it all cleaned up.

So yeah something fishy going on with the versioning and how AppWrite behaves, but for now it's okay

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DH-555** [comment]
There was an incident with a database that Appwrite cloud uses.

The team solved it: https://status.appwrite.online/incident/461590?mp=true
