### ISSUE TITLE
🐛 Bug Report: setting preferences in appwrite console breaks the type

### ISSUE THREAD

**Issue by Megamannen** [appwrite/appwrite#8989]
### 👟 Reproduction steps

1. Set some number preference programatically, for example `{ yearBorn: 1986 }`
2. Use the preference, like `const age = yearNow - yearBorn`, age is now `38`
3. Update the yearBorn in admin console, it's no longer a number, it's a string `{ yearBorn: "1987" }`
4. Cry

### 👍 Expected behavior

Somehow keep the type or have an explicit type as a column

### 👎 Actual Behavior

Everything becomes a string

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
The step 4 is very accurate 😆

**Comment by stnguyen90** [comment]
The current preferences card in the Console doesn't quite work well considering the dynamic nature of user preferences. We'll be using https://github.com/appwrite/console/issues/1468 to track updates to the user preferences so it might be good to add a comment about your problem and add a 👍🏼 to the issue.

**Comment by Megamannen** [comment]
> The current preferences card in the Console doesn't quite work well considering the dynamic nature of user preferences. We'll be using [appwrite/console#1468](https://github.com/appwrite/console/issues/1468) to track updates to the user preferences so it might be good to add a comment about your problem and add a 👍🏼 to the issue.

Why not link to this issue from that grouped issue? Very high risk of you missing stuff with this way of working, closing an issue and hope that the reporter notices this with your comment to add the issue to another issue
