### ISSUE TITLE
Sign up error

### ISSUE THREAD

**Issue by smallishjoe** [appwrite/appwrite#899]
Can not sign up in version 0.7.0

**Comment by lohanidamodar** [comment]
Hi @smallishjoe Please provide more details, as what error message you receive. Open up developer tools of the browser and look for the error message you are receiving there

**Comment by eldadfux** [comment]
@smallishjoe you can also use the new Appwrite Doctor to check the status of your server:

```bash
docker-compose exec appwrite doctor
```

**Comment by smallishjoe** [comment]
The error message is "Registration failed, please try again later" on http://localhost:81/auth/signup. same error message if I try from https://appwrite.io/auth/signup. 

Details of error from chrome console.

//http://localhost:81/auth/signup//

:81/v1/account:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
app-all.js?v=125.0.6.2:21 POST http://localhost:81/v1/account 500 (Internal Server Error)
(anonymous) @ app-all.js?v=125.0.6.2:21
call @ app-all.js?v=125.0.6.2:16
post @ app-all.js?v=125.0.6.2:21
create @ app-all.js?v=125.0.6.2:27
resolve @ app-all.js?v=125.0.6.2:2599
exec @ app-all.js?v=125.0.6.2:2605
app-all.js?v=125.0.6.2:21 POST http://localhost:81/v1/account 500 (Internal Server Error)
(anonymous) @ app-all.js?v=125.0.6.2:21
call @ app-all.js?v=125.0.6.2:16
post @ app-all.js?v=125.0.6.2:21
create @ app-all.js?v=125.0.6.2:27
resolve @ app-all.js?v=125.0.6.2:2599
exec @ app-all.js?v=125.0.6.2:2605


//https://appwrite.io/auth/signup//

signup:1 Unchecked runtime.lastError: The message port closed before a response was received.
signup:1 Unchecked runtime.lastError: The message port closed before a response was received.
app-all.js?v=143.0.7.0:2410 EE Version 2
/v1/account:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by eldadfux** [comment]
@smallishjoe the only way for us to understand why you got that error is to see some of the server logs. If I had to guess I would tell it looks a database connection issue.

To get the right logs type this commands at the location of your Appwrite installation (where the appwirte/docker-compose.yml file is located):

```bash
docker-compose exec appwrite doctor
```

and specific logs from the Appwrite server:

```bash
docker-compose logs appwrite
```

**Comment by eldadfux** [comment]
Closing for now, I'll re-open if needed.

**Comment by dimm0** [comment]
Getting this too, and there's nothing in logs... I'm running in kubernetes. Trying to debug
