### ISSUE TITLE
🐛 Bug Report: 404 when creating database

### ISSUE THREAD

**Issue by sohansingh-blaze** [appwrite/appwrite#8993]
### 👟 Reproduction steps

When I try to create a database it says it already exists and 404 error when I create a new project or DB

### 👍 Expected behavior

It should show database name in list
and 
It should show setting tab

### 👎 Actual Behavior

But it shows 0/1 created databases
and 
shows 404 error when going to storage or setting tab or creating new db

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I use windows pc wiht optic fibre internet and  no background tasks

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@sohansingh-blaze., thanks for creating this issue! 🙏🏼 Are you still having this issue? Btw, it might be best to troubleshoot this on [Discord](https://appwrite.io/discord) rather than GitHub.
