### ISSUE TITLE
🚀 Enhancement: Skip Build Process for Non-Deployment Branch Commits

### ISSUE THREAD

**Issue by harshvardhan-anand** [appwrite/appwrite#9000]
### 🔖 Enhancement description

**Skip Build Process for Non-Deployment Branch Commits and ability to pause auto deploy on git commit directly from Appwrite web console in settings**

_I noticed that the build process is triggered for all branches, including those not designated for deployment. This behavior can result in unnecessary builds and increased resource consumption._

Deployment Log Image - 
![Image](https://github.com/user-attachments/assets/179afe22-0701-4110-bab7-149365f8a5d7)

Git Settings - 
![Image](https://github.com/user-attachments/assets/9028946b-c828-428b-bde9-cc144fda3d0f)

### Why the Ability to Pause Auto-Deployment is Needed
When I update the `README.md` or make other minor changes, the function auto-deploys unnecessarily.

1. If my job scheduler is running the function at the same time, the deployment causes a conflict, and the function fails with a 500 status code.
2. This disrupts the workflow and could lead to missed or delayed processing of tasks.

### 🎤 Pitch

I’m building a SaaS to track top tech companies' career pages, saving users from manual checks. I absolutely love Appwrite's seamless integration with GitHub, especially how functions auto-deploy with every commit! 🚀

However, I noticed that the build process is triggered for all branches, even those not designated for deployment. This can lead to unnecessary builds and increased resource consumption.

**Proposed Enhancement**

1. It would be great to have an option to skip the build process for commits made to non-deployment branches. 
2. And can pause auto-deployment on git commit

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@harshvardhan-anand, thanks for creating this issue! 🙏🏼 Is this the same as https://github.com/appwrite/appwrite/issues/7473? If so, it would be good to add a 👍🏼 and comment on that issue and close this as a duplicate.

**Comment by stnguyen90** [comment]
@harshvardhan-anand, thanks for the analysis. The overall goal of https://github.com/appwrite/appwrite/issues/7473 is to prevent builds triggering from triggering when changes to a non-deployment branch is made so let's use that issue for that request.

It seems like you have 2 additional feature requests:
1. pause auto-deployment
2. skipping builds if a file outside of the function folder is updated

It would be best to use this issue for one of those and then a separate issue for the other.

**Comment by harshvardhan-anand** [comment]
Hi @stnguyen90, it will be helpful if we remove question label, if there is no open question for me.🙂
