### ISSUE TITLE
🐛 Bug Report: 500 Server error - Database is not working

### ISSUE THREAD

**Issue by Kunsh23** [appwrite/appwrite#9051]
### 👟 Reproduction steps

when I opened my account database is not working, showing 500 error.

### 👍 Expected behavior

Database should work properly.

### 👎 Actual Behavior

Database is not working, shows 500 server error.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Please create a support ticket in the Appwrite Console or a support post on [Discord](https://appwrite.io/discord).
