### ISSUE TITLE
Database is not working - Shows 500 Server error

### ISSUE THREAD

**Issue by Kunsh23** [appwrite/appwrite#9054]
![Image](https://github.com/user-attachments/assets/8c3fd4e4-fb25-4862-8ccb-e136fdbe4a87)
When i am going into database collection, it shows 500 server error in collection of database.

**Comment by AmritCoder2003** [comment]
I am also getting the same error.
![Image](https://github.com/user-attachments/assets/36f4dbed-c79e-46fc-b0b7-0e1ee8c53fcc)

**Comment by DH-555** [comment]
Hello! There was an issue with cloud as it was shown in the status page: https://status.appwrite.online
If it still persists for you, create a support ticket through the console or in our Discord community.

Thanks, and apologies for the disruption.
