### ISSUE TITLE
🐛 Bug Report: Unexpected text rendering when inviting user

### ISSUE THREAD

**Issue by ARYPROGRAMMER** [appwrite/appwrite#9059]
### 👟 Reproduction steps

Attempting to send email to invite user to a team results in unexpected text rendering. Only when the SMTP service is not specified.

### 👍 Expected behavior

It should provide a hyperlink to the email setup docs

### 👎 Actual Behavior

It rather renders the anchor tag itself in the dialog view: 
![Image](https://github.com/user-attachments/assets/2e879daf-d08a-42f7-a795-4c3c66fc845b)

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I used local setup and docker build for windows via git clone and docker build command specified in docs.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ARYPROGRAMMER, thanks for raising this issue! 🙏🏼 This looks like the same as https://github.com/appwrite/console/issues/443 so it would be best if you add a 👍🏼 to that issue as I'll be closing this one.
