### ISSUE TITLE
🚀 Enhancement: Retries in Appwrite Functions

### ISSUE THREAD

**Issue by leejustin** [appwrite/appwrite#9074]
### 🔖 Enhancement description

During development, a developer expects to rewrite and test a function many times. Just getting a function to work properly to run without path issues takes a few tries. Then, I have to run it a few times to make sure I have the correct logic set up.

This means I rerun a function a lot. If it's a function that has a request body, I will need to store this somewhere in another Notepad and paste it back in every single invocation.

### 🎤 Pitch

So I understand that the request body is not saved. But if there's a workaround, I'd love a retry button in Appwrite functions in the Appwrite UI so I don't have to keep re-pasting a test JSON body over and over again to debug.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@leejustin, thanks for creating this issue! 🙏🏼 It looks like this is the same as https://github.com/appwrite/appwrite/issues/6369. As such, it would be good to comment with your use-case and add a 👍🏼 that issue as I'll be closing this as a duplicate.
