### ISSUE TITLE
🐛 Bug Report: Function gets wrong datatype from the Appwrite SDK (create User)

### ISSUE THREAD

**Issue by Kuromory** [appwrite/appwrite#9075]
### 👟 Reproduction steps

I created on my self-hosted appwrite (1.5.11) a function that is trigged by an event (document.create) that runs following code:

I use dart_appwrite: ^12.1.0

```dart
var user = await users.create(
        userId: userId,
        email: payload['email'],
        name: payload['name'],
      );
```
It worked on it but now I upgraded it to version 1.6.0 and it gives following exception:
```dart
type 'String' is not a subtype of type 'Map<String, dynamic>'
#0      Users.create (package:dart_appwrite/services/users.dart:55)
<asynchronous suspension>
```

### 👍 Expected behavior

It creates a new User

### 👎 Actual Behavior

I get this exception
```dart
type 'String' is not a subtype of type 'Map<String, dynamic>'
#0      Users.create (package:dart_appwrite/services/users.dart:55)
<asynchronous suspension>
```

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Kuromory, thanks for creating this issue! 🙏🏼

Would you please try using the debugger to see what is `res.data` on the [line](https://github.com/appwrite/sdk-for-dart/blob/f1ba4a51d4fbbc2db3945e55879a189a8ea98613/lib/services/users.dart#L55) mentioned in the stacktrace?

**Comment by Kuromory** [comment]
@stnguyen90 

Well, how do I use the Debugger on a Appwrite Function? the code works when I run it locally so I can't use the debugger there...

**Comment by Kuromory** [comment]
hey @stnguyen90 
I created the API call by hand and got this as an response:
```html
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by Kuromory** [comment]
Found Solution:
the endPoint was the problem:

```dart
Platform.environment['APPWRITE_FUNCTION_API_ENDPOINT']
```

If you use a reverse proxy with https I had to enable in the `.env`

```ini
_APP_OPTIONS_FORCE_HTTPS=enabled
_APP_OPTIONS_FUNCTIONS_FORCE_HTTPS=enabled
```

like https://appwrite.example.com/

if you have the problem locally, and you have different ports in the `docker-compose.yml` you have to change the endpoint from `localhost` to `host.docker.internal` and in the function code give the port as well:
```dart
   if (endPoint.contains('internal')) {
      if (endPoint.contains('https')) {
        endPoint = endPoint.replaceFirst('internal', 'internal:8443');
      } else {
        endPoint = endPoint.replaceFirst('internal', 'internal:8080');
      }
    }
```

I hope in future releases we can have the Ports included in the environment variable :)
