### ISSUE TITLE
User (role: guests) missing scope (account)

### ISSUE THREAD

**Issue by yeabsira-gashaw** [appwrite/appwrite#9078]
Hello,

I have been trying to integrate appwrite to nodejs backend. But I am getting `User (role: guests) missing scope (account)` error . Here's the code below.

index.js 
```

const { Client, Account, ID } = require("appwrite");

const APPWRITE_PROJECT_ID = process.env.PROJ_ID;

const client = new Client()
  .setEndpoint("https://cloud.appwrite.io/v1")
  .setProject(APPWRITE_PROJECT_ID);

const account = new Account(client);

#Signup 
const newUserPromise = account.create(
  "customerID",
  "email",
  "Password"
);

newUserPromise.then(
  function (response) {
    console.log(response); // Success
  },
  function (error) {
    console.log(error); // Failure
  }
);

const promise = account.createEmailPasswordSession(
  "email",
  "password"
);

promise.then(
  async function (response) {
    // console.log(response); // Success
    try {
      const user = await account.get();
      
      // Logged in
    } catch (err) {
      // Not logged in
      console.log(err);
    }
  },
  function (error) {
    console.log(error); // Failure
  }
);

```

The error happens when i try `const user = await account.get()` after getting session / login. I have checked the api key I used and every permission is given to the api. 

Anything I missed please ?

**Comment by Policorp-io** [comment]
try {
      const user = await account.get();
      
      // Logged in
    } catch (err) {
      // Not logged in
      console.log(err);
    }
  },

can you try return and log the user after   // Logged in

**Comment by Policorp-io** [comment]
try {
    // Create email session
    const session = await account.createEmailSession(email, password);
    
    // Verify session by getting user data
    const user = await account.get();
    
    return {
      session,
      user
    };
  } catch (error) {
    console.error('Login error:', error);
    throw error;
  }

**Comment by yeabsira-gashaw** [comment]
Yes @Policorp-io  , it throws an error

`{
  err: AppwriteException: User (role: guests) missing scope (account)
     {
    code: 401,
    type: 'general_unauthorized_scope',
    response: {
      message: 'User (role: guests) missing scope (account)',
      code: 401,
      type: 'general_unauthorized_scope',
      version: '1.6.1'
    }
  }
}`

**Comment by ChiragAgg5k** [comment]
@yeabsira-gashaw i tried running your exact code, and the error i got was `general_argument_invalid` for failing email validation...

how did you get past that?

**Comment by yeabsira-gashaw** [comment]
@ChiragAgg5k Could you share the full error ? From my end , I used the correct project ID and it went through except the scope error .

**Comment by yeabsira-gashaw** [comment]
@ChiragAgg5k I have got it working now. I have prepared a starter script to simulate some auth flows. 

```
const { Client, Account, Users } = require("node-appwrite");
const chalk = require("chalk");
const path = require("path");

// Config
const client = new Client()
  .setEndpoint(process.env.APPWRITE_ENDPOINT) // Replace with your endpoint
  .setProject(process.env.PROJECT_ID) // Replace with your project ID
  .setKey(process.env.API_KEY);

const users = new Users(client);
const account = new Account(client);

const createUser = async (payload) => {
  const response = await users.create(
    payload.userId,
    payload.email,
    payload.phone,
    payload.password,
    payload.name
  );
  userId = response.$id;

  return userId;
};

const login = async (payload) => {
  const session = await account.createEmailPasswordSession(
    payload.email,
    payload.password
  );

  return session;
};

const createJwt = async (payload, sessionId) => {
  const jtwResult = await users.createJWT(payload.userId, sessionId);
  return jtwResult;
};

const changePassword = async (payload) => {
  const changePasswordResult = await users.updatePassword(
    payload.userId,
    payload.password
  );
  return changePasswordResult;
};

const runAllTasks = async () => {
  /*
   * 1. Create a new user
   * 2. Login with the user
   * 3. Create a JWT for the user
   * 4. Change the password of the user
   * 5. Login with the new password
   */

  //Provide your init details
  const userId = "0001";
  const email = "sample@gmail.com";
  const password = "Password123";
  const phone = "+14912712625";
  const name = "Sample Name";

  const signupDetail = {
    userId,
    email,
    password,
    phone,
    name,
  };

  // 1. Create a new user
  //   const signupResult = await createUser(signupDetail);
  //   console.log("signup result ", signupResult);

  const loginDetail = {
    userId,
    password,
    email,
  };

  //2. Login with the user
  const loginResult = await login(loginDetail);
  console.log({ loginResult });

  //3. Create a JWT for the user
  const jwtResult = await createJwt(loginDetail, loginResult.$id);
  console.log({ jwtResult });

  const changePasswordDetail = {
    userId: loginDetail.userId,
    password: "Password1234",
    email,
  };

  //4. Change the password of the user
  const changePasswordResult = await changePassword(changePasswordDetail);
  console.log({ changePasswordResult });

  //5. Login with the new password
  const reLoginResult = await login(changePasswordDetail);
  console.log({ reLoginResult });
};

runAllTasks()
  .then(() => {
    console.log(chalk.green.bold("Successfully ran playground!"));
  })
  .catch((err) => {
    console.error(err);
  });


```

**Comment by ChiragAgg5k** [comment]
nicee that it worked out

**Comment by yeabsira-gashaw** [comment]
Glad it worked . I will close the issue now.

**Comment by paulustimothy** [comment]
💡 If you're stuck with account.get() throwing an error even after successful OAuth login (e.g., Google), read this!

I spent hours checking my code, auth flow, and permissions thinking something was wrong. Everything looked perfect—but the issue turned out to be my browser (Brave) blocking third-party cookies by default, which prevents the session cookie from being set.

✅ So if your code looks correct and you’re still getting errors like:
``
AppwriteException: User (role: guests) missing scope (account)
``

➡️ Check your browser settings!
Make sure cookies (especially third-party or cross-site cookies) aren’t blocked. Try using a different browser (like Chrome) or allow all cookies temporarily to test.

Hope this helps save someone hours of debugging!
