### ISSUE TITLE
What Type of database is available in appwrite Mongodb type or MySql type

### ISSUE THREAD

**Issue by rupamking1** [appwrite/appwrite#908]
What Type of database is available in appwrite Mongodb type or MySql type?
I have another question why you are using PHP, you are using PHP for backend or frontend?

**Comment by lohanidamodar** [comment]
@rupamking1 Appwrite currently supports MySQL/MariaDB but we are planning to support more database engines. 

Appwrite is based on Microservice Architecture. PHP is just a small part of Appwrite in the Backend.

**Comment by rupamking1** [comment]
PHP is synchronous language it makes slow our request.

**Comment by eldadfux** [comment]
Actually PHP is not only synchronous anymore. We use PHP with Swoole to get async & multithreading capabilities which make Appwrite way faster. Actually Swoole benchmarks shows its way faster then either Node or Python and just slightly behind Go

**Comment by eldadfux** [comment]
![image](https://user-images.githubusercontent.com/1297371/107870004-5b8fbe80-6e9d-11eb-8279-bbc76c7f1e50.png)
