### ISSUE TITLE
🐛 Bug Report: Still processing label in one of my collection in appwrite database

### ISSUE THREAD

**Issue by gaurav0909-max** [appwrite/appwrite#9088]
### 👟 Reproduction steps

![Image](https://github.com/user-attachments/assets/2168c748-0399-476e-ad2a-3da5a24eb74f)

### 👍 Expected behavior

I want here the required title as others
but not get what I want

![Image](https://github.com/user-attachments/assets/6f80bf26-09ad-4554-93df-30d06f5f7fe7)

### 👎 Actual Behavior

As you can see in image that
one label is shown in the table of collection named as patients
how can I resolve this issue I can't able to delete this table 

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Windows
Chrome
Visual Studio Code

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Hello! Is it still processing?

**Comment by gaurav0909-max** [comment]
No @DH-555 ,
I deleted the collection and recreated then it works good 
I don't know what the issue is but the issue remains the same for more than 24 hours

**Comment by DH-555** [comment]
@gaurav0909-max That should not be happening. If it happens again, create a post in our Discord support channel or in the support section inside the appwrite console with your project ID so the team investigates the cause and works on a fix.

Here you have the invite: https://discord.gg/aRVYmKZc

Thanks, and apologies for it.
