### ISSUE TITLE
🐛 Bug Report: Activity Logs is not real time.

### ISSUE THREAD

**Issue by meoawww** [appwrite/appwrite#9089]
### 👟 Reproduction steps

when I check my activity logs they are showing after much delay not sure after how many minutes or hours but there is certainly a huge delay

### 👍 Expected behavior

Activity Logs are usually supposed to be real time

### 👎 Actual Behavior

Delay for more than 30 minutes upto an hour or maybe more for displaying those activity logs.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

appwrite cloud

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Hello @meoawww, thanks for creating this issue! 🙏🏼 Yes, there may be a delay as the activity logs are processed by a background worker. Closing as this is expected.
