### ISSUE TITLE
🚀 Enhancement:

### ISSUE THREAD

**Issue by amjarmed** [appwrite/appwrite#9091]
### 🔖 Enhancement description

**Feature Suggestion: SQL-Based Database Creation in Appwrite**

It would be a great addition if Appwrite allowed users to create and manage databases programmatically using SQL-like syntax. This feature would enhance the learning experience for developers and simplify the process of sharing database schemas. It could be especially useful for those transitioning from traditional SQL environments or wanting to share predefined database structures.

### Example Use Case:
A user could define a database and its collections using a script instead of manually setting them up via the UI. For instance:

```sql
CREATE DATABASE `databaseName`;

CREATE COLLECTION `collectionName` (
  name VARCHAR(1000) NOT NULL,
  email EMAIL NOT NULL
);
```

### Benefits:
1. **Ease of Learning**: Provides a familiar interface for developers with SQL experience.
2. **Reusability**: Facilitates sharing and importing of database schemas among users or projects.
3. **Automation**: Enables faster setup for projects by scripting database and collection creation.
4. **Collaboration**: Simplifies onboarding for teams by sharing predefined schemas.

### Implementation Suggestions:
- **Schema Parser**: Appwrite could include a parser to convert SQL-like syntax into its internal collection and attribute structures.
- **Export/Import Feature**: Allow users to export an existing database schema into SQL-like scripts and import them into new or existing projects.
- **Validation**: Ensure schema validity at runtime with detailed error feedback.

This approach could significantly improve the developer experience, bridging the gap between traditional database management and Appwrite's modern features.

### 🎤 Pitch

- **Note**: I explaind above why this should be implemented and how it would be used with a sample example 

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Hello! Please, use a descriptive title.
Thanks!

**Comment by DH-555** [comment]
I think this goes against appwrite's vision that is not needing to know SQL commands or similar.
Also, it's going to be difficult to implement due to security as that's going to require having dedicated databases instead of shared, but still possible.

Thanks for your request!
