### ISSUE TITLE
Help required in setting up the environment.

### ISSUE THREAD

**Issue by rahulatrkm** [appwrite/appwrite#91]
git clone not working with the provided command in bash shell.

> root@18e92e5c793d:/home/workspace# git clone git@github.com:appwrite/appwrite.git
> Cloning into 'appwrite'...
> error: cannot run ssh: No such file or directory
> fatal: unable to fork

However, it is working with `git clone https://github.com/appwrite/appwrite.git`
By the way, can you please provide what are the permissions to run the above command.
![Screenshot from 2019-10-02 08-58-47](https://user-images.githubusercontent.com/25795515/66016714-68548200-e4f5-11e9-8ea3-305f197695ce.png)
![Screenshot from 2019-10-02 09-17-18](https://user-images.githubusercontent.com/25795515/66016730-786c6180-e4f5-11e9-8243-c0b8f315e717.png)

**Comment by ShivamRawat0l** [comment]
Maybe you have setup ssh key but dont have it in your computer. 
https://help.github.com/en/enterprise/2.15/user/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
                                                                  **OR**
https://stackoverflow.com/questions/15589682/ssh-connect-to-host-github-com-port-22-connection-timed-out

Check if ssh is working with other repos

**Comment by Taminoful** [comment]
You need to fork the repository first and then clone your fork. It's part of the fundementals how [GitHub does Pull Requests](https://guides.github.com/introduction/flow/).

**Comment by eldadfux** [comment]
I will update the docs to make it more obvious that you need to clone your fork of the repo

**Comment by eldadfux** [comment]
I have updated the docs to make the fork part more clear. https://github.com/appwrite/appwrite/commit/c6f6cdca0a65dfa86cc387d82a766a3ce39c51c7
