### ISSUE TITLE
🐛 Bug Report: User still "exists" after deletion.

### ISSUE THREAD

**Issue by LIFETAB** [appwrite/appwrite#9110]
### 👟 Reproduction steps

You need:
Basic setup of a project with, in my case discord OAuth. Can be any OAuth provider.
A node js environment with the node js appwrite sdk. Im using next.js for my Project.

The basic next.js SSR OAuth setup from the docs.

To reproduce:
1. Signup with a new user using Oauth.
2. Delete the user using the sdk and a admin client with an api key. (I also used the cli for testing)
3. Try to signup again with the same user.

This produces this bug.

### 👍 Expected behavior

It should create a new user. Then when i delete the user and make sure his identities are removed, and sign up again it should create the new user without any problems.

### 👎 Actual Behavior

I get an error that is being shown in the url and also i found it in the docker logs.

Error in the URL:
`http://localhost:3000/?error=%7B%22message%22%3A%22A+user+with+the+same+id%2C+email%2C+or+phone+already+exists+in+this+project.%22%2C%22type%22%3A%22user_already_exists%22%2C%22code%22%3A409%7D`

Error in the Logs:
<img width="1167" alt="Image" src="https://github.com/user-attachments/assets/d88459dc-94b8-42df-8cef-6d25ea8bc229" />

This itself is concerning, but actually a user is being created before the error happens, with an verified Email, no password, and weirdly no Identity.
Below is a screenshot of the new User. Also the screenshot above shows 2 Jobs that have been created and executed before the error, this jobs may create the user, but im not sure about this.

<img width="896" alt="Image" src="https://github.com/user-attachments/assets/d3e7ef2d-7930-4307-b731-dcf3424979e2" />

If someone asks I made sure that when the user gets deleted, there are no identities left that are linked to that user.
See following screenshot:
<img width="1277" alt="Image" src="https://github.com/user-attachments/assets/0d6e7f7d-70fe-43de-9595-3f7336bde8eb" />

Also the logs of the deletion seem fine it goes through with no errors, below a look on them as well:
<img width="1167" alt="Image" src="https://github.com/user-attachments/assets/3f0cbc91-6b9d-4cf4-a229-55f7426079d6" />

 
I also let it sit overnight with no user signed up to try again because maybe some jobs didn't run, but it didn't fix it.

After this error, if the user signs up with discord again, it goes though without any errors and the identity is being linked, but its still a bug that could potentially happen to a user, and is annoying when developing, because I and maybe some others need to have a certain behavior or code ran when a new user is being created.

With that said i hope its not a all to complicated bug to fix :)

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite version: [1.6.1-RC1](https://github.com/appwrite/appwrite/releases/tag/1.6.1-RC1)
node-appwrite: 14.1.0

My appwrite is self hosted on a Ubuntu 24.04.1 LTS VPS and is running behind a proxy managed by the Nginx Proxy Manager.

My appwrite installation is not modified in any other way.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by DH-555** [comment]
Hello! The RC (Release Candidate) is not stable yet as it's not a released version and can contain bugs.

Is this happening too in the latest stable release? (1.6.0)

**Comment by LIFETAB** [comment]
I will test it and let you know

**Comment by LIFETAB** [comment]
This bug does not appear on the stable 1.6.0 release. Only on the 1.6.1-RC1 @DH-555

**Comment by LIFETAB** [comment]
No im sorry, it was my fault this error occured. I had a bug with my project, i have created a new project to test it again on the 1.6.1-RC1 and its working fine now. I don't know what the problem with the old project was. I will close this issue and sorry again for opening this issue :) 

Merry Christmas 🎄
