### ISSUE TITLE
🐛 Bug Report: type List<dynamic>' is not a subtype of type 'List<String>

### ISSUE THREAD

**Issue by develocode777** [appwrite/appwrite#9116]
### 👟 Reproduction steps

When I try this portion of code:

`
    DocumentList listGeneralInfo = await globals.appwriteDB.listDocuments(
      collectionId: Env.appwriteGeneralInfoCollection,
      databaseId: Env.appwriteGeneralInfo,
    );
`

I get the error `List<dynamic>' is not a subtype of type 'List<String>`

### 👍 Expected behavior

There should be no errors.

### 👎 Actual Behavior

I get the error `List<dynamic>' is not a subtype of type 'List<String>`

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

I use appwrite self-hosted version 1.6.0 with flutter appwrite version 13.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by MarDit** [comment]
I got the same error since yesterday when logging the user in with `account.get()`. Maybe these issues are related?
I am also using appwrite self hosted 1.6.0 and flutter appwrite 13.0.0. Updating to 13.1.0 didn't help.

According to the stack trace, the error is located in the User.fromMap constructor in the line for the labels list.

**Comment by develocode777** [comment]
> I got the same error since yesterday when logging the user in with `account.get()`. Maybe these issues are related? I am also using appwrite self hosted 1.6.0 and flutter appwrite 13.0.0. Updating to 13.1.0 didn't help.
> 
> According to the stack trace, the error is located in the User.fromMap constructor in the line for the labels list.

Hi, I'm going to create a new issue in the flutter repository and delete this one, I think it's more appropriate to have it there since it's about the flutter sdk, so please post your comment there. Thanks

**Comment by arrowxpr** [comment]
This is a bug, only throws when calling listDocuments. 
```
Appwrite 1.6.0
Flutter 3.27.0
appwrite 13.1.0
```


```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<String>'
#0      new Document.fromMap (package:appwrite/src/models/document.dart:41:42)
#1      new DocumentList.fromMap.<anonymous closure> (package:appwrite/src/models/document_list.dart:20:68)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:435:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:364:26)
#4      new List.from (dart:core-patch/array_patch.dart:29:17)
#5      new DocumentList.fromMap (package:appwrite/src/models/document_list.dart:20:11)
#6      Databases.listDocuments (package:appwrite/services/databases.dart:33:32)```
