### ISSUE TITLE
Add a contributors table in readme

### ISSUE THREAD

**Issue by himanshu007-creator** [appwrite/appwrite#912]
## 📚 Documentation

I wish to Add a contributors table in readme. Please assign me this issue and add dwoc and level tags

## Have you spent some time to check if this issue has been raised before?

(Have you googled for a similar issue or checked our older issues for a similar bug)

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

(Write your answer here.)

**Comment by eldadfux** [comment]
@himanshu007-creator this has already been discussed several times here. We use to have a list and it was hard to maintain and slow to load with +130 contributors only on this repo. You can view full list of contributors on: https://github.com/appwrite/appwrite/graphs/contributors and top contributors across all our repos on: https://appwrite.io/community
