### ISSUE TITLE
Custom Domain pattern check is not working

### ISSUE THREAD

**Issue by devcat-net** [appwrite/appwrite#915]
## 🐛 Bug Report

I want to add a custom domain but the input field check gives me the notification that the pattern of the domain is not correct.

## To Reproduce
You can check it by entering a domain with a - (hyphen) sign.

## Your Environment
I run the application with the _APP_ENV=production flag

![appwrite](https://user-images.githubusercontent.com/36440352/108079655-55e9d280-706f-11eb-9b9a-605ef6df0fa9.png)

Is it possible to adjust this rule?

**Comment by TorstenDittmann** [comment]
Thanks for creating an issue 👋🏻 

What version of Appwrite and Browser are you using? 🙂

**Comment by devcat-net** [comment]
Hi @TorstenDittmann,

I used this command for creating my appwrite container:
```docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.7.0
```

And I checked this behaviour on Chrome and Safari.

**Comment by TorstenDittmann** [comment]
https://user-images.githubusercontent.com/1759475/108220081-a5470600-7136-11eb-9031-b6eec3ebc9cf.mov

I can't reproduce it on Chrome & Safari 🤔 Did you paste it into the field or type?

**Comment by eldadfux** [comment]
I can't seem to be able to reproduce as well. I know there was an issue with that prior to 0.7, but we added a fix. (#470 #471)

![image](https://user-images.githubusercontent.com/1297371/108222443-78e4b700-7141-11eb-8794-7aaee882ecc0.png)

**Comment by devcat-net** [comment]
Hi guys, 

I was wrong about the version number. I tried several times to install appwrite and my last install was done by this file: `https://appwrite.io/docker-compose.yml` 
And from what I can see in the file it takes the image with the latest tag. But when I check in the running application I see the following version number:
![image](https://user-images.githubusercontent.com/36440352/108223145-c9581680-7139-11eb-943c-48420f34cd3a.png)

Should I change the tag in the docker-compose file to version: 0.7.0?
