### ISSUE TITLE
Create new banner GIF for readme 

### ISSUE THREAD

**Issue by himanshu007-creator** [appwrite/appwrite#918]
## 📚 Documentation

At present, app-write displays its logo on readme's top. It can be replaced by an animated  header. 

## Have you spent some time to check if this issue has been raised before?

yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

**Comment by christyjacob4** [comment]
@himanshu007-creator Are you going to work on this ?

**Comment by himanshu007-creator** [comment]
Yes sir, i will work on this under DWOC.

**Comment by himanshu007-creator** [comment]
Please assign me this issue, so that i can start working on it
