### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by Swastik1710** [appwrite/appwrite#919]
## 📚 Documentation

Adding a new separate column in the readme.md file showcasing the list of open source events this project has been a part of. 
Also adding some GIFs to give the readme file a more representative and attractive look. 

## Have you spent some time to check if this issue has been raised before?
Yes, I have. 

(Have you googled for a similar issue or checked our older issues for a similar bug)
Yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

**Comment by Swastik1710** [comment]
I would like to work on this issue. 
Please assign it to me. 
Thanks.

**Comment by anirudhsai20** [comment]
Hi @Swastik1710 . Can I please work on this issue under DWOC?

**Comment by Swastik1710** [comment]
Hey @anirudhsai20, I've already requested them to assign this issue to me.
Though they haven't replied yet.

**Comment by eldadfux** [comment]
@Swastik1710 any relevant events can be listed on the https://github.com/appwrite/appwrite-awesome repo
