### ISSUE TITLE
Lazy-loading for child documents

### ISSUE THREAD

**Issue by mlucas-NU** [appwrite/appwrite#924]
## 🚀 Feature

The ability to GET a document where the response body does not include any child documents. In this case, allow the client to request the child document(s) at a later date.

## Have you spent some time to check if this issue has been raised before?

Yes. Torsten Dittman and I spoke about this briefly on Discord and we believe this is a new request.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

## Pitch

When documents have a large list of child documents, there are scenarios where it does not make sense to return the entire parent document body + all child document bodies in one request. One example is a User Preferences document that contains a list of Favorite Articles. When the list is long enough or the articles are large enough, returning all of the children may delay the initial request and increase client storage requirements. This isn't necessary if a user isn't expected to interact with all children in the list.

A basic idea is to add an optional field to GET endpoints that indicates whether children should be returned immediately. The functionality could be:
* Request contains `"get_children": "yes"` -> return parent + child documents. (default)
* Request contains `"get_children": "no"` -> return parent.
* Request contains `"get_children": "ids"` -> return parent + child ids.

Alternatively:
* Request contains `"get_children": true` -> return parent + child documents. (default)
* Request contains `"get_children": false` -> return parent + child ids.

With the list of IDs, the client could individually request the children as they're needed.

**Comment by TorstenDittmann** [comment]
Due to the removal of nested documents this is not really relevant anymore 👍🏻
