### ISSUE TITLE
Add a GitHub action to auto-assign Mentors for every PR 

### ISSUE THREAD

**Issue by m-code12** [appwrite/appwrite#932]
I would like to add a GitHub action to auto-assign mentors for every PR. It sometimes becomes hectic for the mentors to take a look at all the Projects for the PRs made by the Contributors. This action would give a nice notification about reviewing the pr and make things pretty easy for the mentor. It would automatically ask for reviews by the mentors on every pr created.

Demo :
<img src="https://user-images.githubusercontent.com/1641039/78471193-71573200-776a-11ea-9b40-810c2d63270e.png">

**Comment by m-code12** [comment]
@eldadfux I would like to work on this.

**Comment by eldadfux** [comment]
@m-code12 thanks fo the suggestion. Right now we do not have enough scale to have the need or time to maintain extra automations that might have little benefit and add complexity to the project.
