### ISSUE TITLE
Country Name unknown on sessions endpoint

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#933]
## 🐛 Bug Report

Country Name on GET Sessions request doesn't return country name - even though it has a valid country code.

## Have you spent some time to check if this issue has been raised before?

✅ 

## To Reproduce

Get sessions.

## Expected behavior

Countryname the actual Country Name.

## Actual Behavior

Countryname is "--".

<img width="569" alt="Bildschirmfoto_2021-02-22_um_13 55 53" src="https://user-images.githubusercontent.com/1759475/108717934-267b1000-751e-11eb-92c2-1c1bf1c2bf58.png">

## Your Environment

0.7

**Comment by kodumbeats** [comment]
Fixed in [Appwrite 0.7.1](https://github.com/appwrite/appwrite/releases/tag/0.7.1)
