### ISSUE TITLE
Error with creating file in the storage

### ISSUE THREAD

**Issue by klnfreedom** [appwrite/appwrite#934]
Hello everyone, I have some problem with creating of file to the storage of appwrite. When I want to create a file I get a 500 error code in the app. And when I want to create a file via the site, I get this message "Failed to upload a file".
Thanks.
I'm looking forward for your reply.

**Comment by eldadfux** [comment]
@klnfreedom would be great if you could share the payload of the 500 requests and the server logs of this 2 commands: 

1. `docker-compose logs appwrite`
2. `docker-compose exec appwrite doctor`

**Comment by klnfreedom** [comment]
👩‍⚕️ Running Appwrite Doctor for version 0.7.0 ...

Checking for production best practices...
🟢 Hostname has a public suffix (104-225-142-211.cloud-xip.io)
🟢 CNAME target has a public suffix (104-225-142-211.cloud-xip.io)
🔴 Not using a unique secret key for encryption
🟢 App environment is set for production
🟢 Abuse protection is enabled
🔴 Console access limits are disabled
🟢 HTTPS force option is enabled

Checking connectivity...
Database............connected 👍
Queue...............connected 👍
Cache...............connected 👍
AntiVirus........disconnected 👎
SMTP................connected 👍
StatsD..............connected 👍
InfluxDB............connected 👍

Checking volumes...
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

Checking disk space usage...
🟢 Uploads Volume has 6.73GB free space (67.76% used)
🟢 Cache Volume has 6.73GB free space (67.76% used)
🟢 Config Volume has 6.73GB free space (67.76% used)
🟢 Certs Volume has 6.73GB free space (67.76% used)

You are running the latest version of Appwrite! 🥳

**Comment by klnfreedom** [comment]
/ _\ (  _ \(  _ \/ )( \(  _ \(  )(_  _)(  __)   (  )/  \ 
/    \ ) __/ ) __/\ /\ / )   / )(   )(   ) _)  _  )((  O )
\_/\_/(__)  (__)  (_/\_)(__\_)(__) (__) (____)(_)(__)\__/ 

👩‍⚕️ Running Appwrite Doctor for version 0.7.0 ...

Checking for production best practices...
🟢 Hostname has a public suffix (104-225-142-211.cloud-xip.io)
🟢 CNAME target has a public suffix (104-225-142-211.cloud-xip.io)
🔴 Not using a unique secret key for encryption
🟢 App environment is set for production
🟢 Abuse protection is enabled
🔴 Console access limits are disabled
🟢 HTTPS force option is enabled

Checking connectivity...
Database............connected 👍
Queue...............connected 👍
Cache...............connected 👍
SMTP................connected 👍
StatsD..............connected 👍
InfluxDB............connected 👍

Checking volumes...
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

Checking disk space usage...
🟢 Uploads Volume has 4.71GB free space (77.46% used)
🟢 Cache Volume has 4.71GB free space (77.46% used)
🟢 Config Volume has 4.71GB free space (77.46% used)
🟢 Certs Volume has 4.71GB free space (77.46% used)

You are running the latest version of Appwrite! 🥳


Attaching to appwrite
appwrite                        | [Static Files] Loadded 92 files
appwrite                        | Issuing a TLS certificate for the master domain (104-225-142-211.cloud-xip.io) in 30 seconds.
appwrite                        |     Make sure your domain points to your server IP or restart your Appwrite server to try again.
appwrite                        | Server started succefully (max payload is 10,000,000 bytes)
appwrite                        | Master pid 1, manager pid 8
appwrite                        | Worker 1 started succefully
appwrite                        | [Error] Method: POST
appwrite                        | [Error] URL: /v1/storage/files
appwrite                        | [Error] Type: Appwrite\Database\Exception\Authorization
appwrite                        | [Error] Message: Missing "write" permission for role "". Only this scopes "["*","user:6033e195a1b6e","role:member"]" are given and only this are allowed "[]".
appwrite                        | [Error] File: /usr/src/code/src/Appwrite/Database/Database.php
appwrite                        | [Error] Line: 234

**Comment by eldadfux** [comment]
Are you trying to upload the files from the console or using an SDK? Which read&write permissions are you using?

If you use an SDK, please share your code.

**Comment by klnfreedom** [comment]
Sorry for disturbing, the problem was solving.

**Comment by eldadfux** [comment]
@klnfreedom that's great. Please feel free to share the solution if it might help other who reach this page from search engines.

**Comment by klnfreedom** [comment]
I didn't allowed a permission of writing on the server side. It was a problem and the problem is solved

**Comment by thesmartrenovation** [comment]
> I didn't allowed a permission of writing on the server side. It was a problem and the problem is solved

Hello, I have the same problem today, could you tell me how you solved it? I have a default installation of AppWrite

**Comment by klnfreedom** [comment]
> > I didn't allowed a permission of writing on the server side. It was a problem and the problem is solved
> 
> Hello, I have the same problem today, could you tell me how you solved it? I have a default installation of AppWrite

Turn off anti-virus

**Comment by designlook** [comment]
Also I had to set the permission when uploading the file.  Like so.

```
let promise = appwrite.storage.createFile(
          this.photo_file,
          **[`user:${window.uid}`],
          [`user:${window.uid}`]**
          )

    promise.then(function (response) {
        console.log(response); // Success
    }, function (error) {
        console.log(error); // Failure
    });
```
