### ISSUE TITLE
Function containers remain running after function is deleted

### ISSUE THREAD

**Issue by kodumbeats** [appwrite/appwrite#938]
A function container is started when a cloud function is created. However, when the function is removed, the container remains running. 

## Have you spent some time to check if this issue has been raised before?

Yes

## To Reproduce

- Create a cloud function of any language
- Remove the cloud function

## Expected behavior

The function container is stopped and removed

## Actual Behavior

Container continues to run even after its origin function was removed.

## Your Environment
<details><summary>~> neofetch --off</summary>
OS: Ubuntu 20.04.2 LTS x86_64

Host: KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q35-4.1)
Kernel: 5.4.0-65-generic
Uptime: 3 days, 18 hours, 58 mins
Packages: 632 (dpkg), 4 (snap)
Shell: fish 3.1.0
Resolution: 1024x768
Terminal: /dev/pts/0
CPU: AMD EPYC 7601 (1) @ 2.199GHz
GPU: 00:01.0 Vendor 1234 Device 1111
Memory: 1593MiB / 1987MiB

</details>
<details>
<summary>~> docker exec appwrite doctor</summary>

👩‍⚕️ Running Appwrite Doctor for version 0.7.0 ...

Checking for production best practices...
🟢 Hostname has a public suffix (xxxxxxxxxxxxxx)
🟢 CNAME target has a public suffix (xxxxxxxxxxxxxxx)
🟢 Using a unique secret key for encryption
🟢 App environment is set for production
🟢 Abuse protection is enabled
🟢 Console access limits are enabled
🟢 HTTPS force option is enabled

Checking connectivity...
Database............connected 👍
Queue...............connected 👍
Cache...............connected 👍
AntiVirus...........connected 👍
SMTP.............disconnected 👎
StatsD..............connected 👍
InfluxDB............connected 👍

Checking volumes...
🟢 Uploads Volume is readable
🟢 Uploads Volume is writeable
🟢 Cache Volume is readable
🟢 Cache Volume is writeable
🟢 Config Volume is readable
🟢 Config Volume is writeable
🟢 Certs Volume is readable
🟢 Certs Volume is writeable

Checking disk space usage...
🟢 Uploads Volume has 40.46GB free space (22.59% used)
🟢 Cache Volume has 40.46GB free space (22.59% used)
🟢 Config Volume has 40.46GB free space (22.59% used)
🟢 Certs Volume has 40.46GB free space (22.59% used)

You are running the latest version of Appwrite! 🥳
</details>

**Comment by eldadfux** [comment]
I guess we can add a new `delete` trigger [here](https://github.com/appwrite/appwrite/blob/master/app/workers/functions.php#L157) to kill the function container, this can also apply to tag update where the old container is not relevant anymore. The should be handled by the `functions` worker and not the `deletes` one, because this operation requires access to the host machine docker socket.

**Comment by doricci** [comment]
Hello @eldadfux and @kodumbeats do You think that the issues #1100 and #1232 are linked to this bug?

**Comment by kodumbeats** [comment]
@doricci Those are separate issues, but 👍🏻 for looking through our open tickets. This issue specifically pertains to `functions.delete()` not issuing calls to Docker to stop/remove the associated execution containers.

**Comment by DiegoBM** [comment]
A delete function webhook would be really useful for people implementing functionality based on functions. An equivalent event in the new realtime would be equally useful (any of both could do). In my particular case I could use the webhook to notify my own docker nodes for changes in nodes, since at the moment I can't know realtime when a function has ceased to exist until the next execution attempt (not ideal).

**Comment by TorstenDittmann** [comment]
@eldadfux is this resolved now with 0.9.0?

**Comment by vasani-arpit** [comment]
I don't think so @TorstenDittmann. I am using version  v:0.9.1.149 and I am seeing containers after execution is completed. 
![image](https://user-images.githubusercontent.com/6497827/128626259-37232f88-b046-4812-81da-7c715ffca69c.png)

**Comment by eldadfux** [comment]
This should be tackled in 0.13 and is addressed here: #2467

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻
