### ISSUE TITLE
No DWOC labels in any of the issues.

### ISSUE THREAD

**Issue by anirudhsai20** [appwrite/appwrite#943]
## 📚 Documentation

(A clear and concise description of what the issue is.)

## Have you spent some time to check if this issue has been raised before?
Yes

(Have you googled for a similar issue or checked our older issues for a similar bug)
Yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?
Yes

(Write your answer here.)
DWOC or any other open source programs that this project has been listed in should be labelled beside the issues.

**Comment by anirudhsai20** [comment]
Hi @appwrite. Can I please work on this issue under DWOC?

**Comment by eldadfux** [comment]
If you have any specific issue that you'd like to work on, let us know and we can add the tag.
