### ISSUE TITLE
Function return data

### ISSUE THREAD

**Issue by adailsonjnr** [appwrite/appwrite#950]
It's possible to functions return data by api request like Firebase Cloud Functions and Parse Server Cloud Code?

**Comment by eldadfux** [comment]
Hey @adailsonjnr do you want the function to provide you with the user request payload when triggered from a client app or API?

**Comment by adailsonjnr** [comment]
Yes @eldadfux. A function do some work and return data to client app.

**Comment by eldadfux** [comment]
This will be available soon with our work on realtime API and our new functions evens. Please view #948 and #971 for more information.
