### ISSUE TITLE
Running functions aren't labeled as aborted if the appwrite server restarts

### ISSUE THREAD

**Issue by TJennerjahn** [appwrite/appwrite#953]
## 🐛 Bug Report

I accidentally executed a function with an infinite loop and had to restart appwrite via `docker-compose restart`.
The function logs still show these executions as 'processing', even though they clearly aren't running anymore.

## Have you spent some time to check if this issue has been raised before?
Yes, I have.

## To Reproduce

1. Create a function that takes a while to execute or contains an infinite loop
2. Run it and restart the appwrite docker containers while it's still processing

## Expected behavior

The logs should show that the function was aborted, or at least that it failed

## Actual Behavior

The log entries retain the processing status indefinitely with no way to look at their outputs/errors.
![Screenshot from 2021-03-04 14-33-36](https://user-images.githubusercontent.com/20514141/109973414-a5c7cb00-7cf8-11eb-8d62-910a9433dbc4.png)

## Your Environment

Appwrite runs on an Ubuntu 20.04 server, the function in question used the nodejs 14.5 environment.

**Comment by eldadfux** [comment]
@TJennerjahn thanks for reporting this issue, the team will look into a proper way to try and detect aborted functions.

**Comment by eldadfux** [comment]
@TorstenDittmann @kodumbeats please let me know your thought about this issue. Not sure what would be the most effective way to mark the execution log as aborted.

We could have used the `start + timeout < time` but the timeout could be set to hours and that won't help much. Maybe we can check running functions before containers and sync all execution marked as `processing`?

**Comment by TorstenDittmann** [comment]
Are there any other possibilities of a function being in this state - without restarting Appwrite? 🤔

**Comment by kodumbeats** [comment]
I think this should be addressed two-fold:
1. Provide a way to kill a running function without `docker-compose restart`.
2. Abort all functions marked as `processing` on startup. I can't think of a strong case where I'd want to restart the stack _without_ aborting everything.
