### ISSUE TITLE
OpenID connect authentication gateway

### ISSUE THREAD

**Issue by mehrdad-shokri** [appwrite/appwrite#968]
## 🚀 Feature

Hi, I've checked the documentation for the authentication service, and seems this feature hasn't been implemented.  Is it possible to add OpenID connect to authentication service?  Then user management(in general) gets handled by an authentication server(like KeyCloak).   

## Have you spent some time to check if this issue has been raised before?
as far as I've seen Oauth implementation is already in process(https://github.com/appwrite/appwrite/issues/410) but no openID connect

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

No

**Comment by eldadfux** [comment]
@mehrdad-shokri please add this auth provider suggestion to this discussion: #907

**Comment by eldadfux** [comment]
I have added OpenID to our lists on #907
