### ISSUE TITLE
Unable to remove all permissions on a document.

### ISSUE THREAD

**Issue by damascenaluiz** [appwrite/appwrite#977]
## 🐛 Bug Report

I cannot remove all permissions on a document through the administrative interface.

## Have you spent some time to check if this issue has been raised before?

Yes.
## To Reproduce
1 - Add a group, team, role or wildcard to a document that does not contain any read or write permission.
2 - Update the document.
3 - Try to remove all permissions.
4 - Update the document again.
5 - The document is updated, but the permissions remain unchanged.

## Expected behavior

The document should be updated and contain no permissions, this should be treated as an empty array.

## Actual Behavior

The document is updated with the previous permissions, if I try to remove all.

## Your Environment

Appwrite 0.7.0

**Comment by eldadfux** [comment]
I can't seem to be able to reproduce this issue. @christyjacob4 / @TorstenDittmann does this happen for you?

**Comment by damascenaluiz** [comment]
My screenshots:
Steps: 1-2 OK:
![step1-2-ok](https://user-images.githubusercontent.com/677552/111082628-184e5d00-84e8-11eb-8e4b-60cc7bcbd6c0.png)

Step: 3 - Unset all permissions.
![step3-clear-permissions](https://user-images.githubusercontent.com/677552/111082630-197f8a00-84e8-11eb-8f5e-0b40dd7767f5.png)
Steps: 4-5 Document updated, but fails to permissions.
![step4-5-document-updated-fails-to-permissions](https://user-images.githubusercontent.com/677552/111082631-1a182080-84e8-11eb-88ef-cdee7e706054.png)

**Comment by eldadfux** [comment]
@damascenaluiz found the issue! Just submitted a PR with a fix.

**Comment by eldadfux** [comment]
Fixed and released in 0.7.1
