### ISSUE TITLE
Keep getting TLSSocket error: unable to verify the first certificate

### ISSUE THREAD

**Issue by LeBraveLittleToaster** [appwrite/appwrite#980]
## 🐛 Bug Report

When using node-appwrite (version: 2.0.0, node: 14.15.1) , I cannot pass even the hello world example from the docs. Keep getting.
```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
```
In my angular app, the "normal" appwrite package is working flawless. 

## Have you spent some time to check if this issue has been raised before?

Most articles suggest to use "rejectUnauthorized", which is quiet sketchy even if it would work (which it doesn´t for me).
https://stackoverflow.com/questions/36194326/request-error-unable-to-verify-the-first-certificate

## To Reproduce

Since I started today with a fresh install, I have the current appwrite docker and the above mentioned node and library version.

```
const sdk = require("node-appwrite");
require("process")

let client = new sdk.Client();

client.setEndpoint("https://localhost/v1")
client.setProject("604e45936f374")
client.setKey(process.env["APPWRITE_STREAM_API_KEY"])

let users = new sdk.Users(client);

let promise = users.create("dev2@dev.de", "123456", "Dev2 Account")

promise.then(function (response) {
    console.log(response)
}, function(error){
    console.log(error)
})
```

With this very basic example I could reproduce the error consistent even after recreating the node project.

## Your Environment

Windows 10
Node: 14.15.1
node-appwrite: 2.0.0

**Comment by eldadfux** [comment]
Hey @LeBraveLittleToaster, you can use the `client.setSelfSigned()` method to make the Node client accept your self-signed Appwrite certificate. This is perfectly fine for dev mode or when using localhost, but should not used when working in production.

https://github.com/appwrite/sdk-for-node/blob/master/lib/client.js#L63

**Comment by LeBraveLittleToaster** [comment]
Thanks! Worked fine! I only need it for setup/dev, so thats enough for my use case :)
