### ISSUE TITLE
Request hanging sometimes

### ISSUE THREAD

**Issue by LeBraveLittleToaster** [appwrite/appwrite#982]
## 🐛 Bug Report

In an angular app, I use a table together with a paginator to show stream announcements. With local data everything is working like a charm, but when I use remote data a strange behaviour occurs. Some of the requests (around 3/10) hanging, but are immediately terminating when the next request is done. Sometimes the request flies in after a long time when waiting (~20-30sec). All other requests regarding login/logout are working perfect without any hanging, even when login in and out really fast, multiple times. The request before also response with the correct data. Due to being new to appwrite, I don´t really know how to debug that correctly. 

## Have you spent some time to check if this issue has been raised before?

Found nothing related

## To Reproduce

```
public getStreams(offset: number) {
    return new Promise<[Stream[], number]>((resolve, reject) => {
      this.sdk.database.listDocuments(environment.streamsColId, undefined, undefined, offset)
        .then((response: any) => {
          resolve([JSON.parse(JSON.stringify(response.documents)), response.sum])
        }).catch((error) => {
          console.log(error)
          reject()
        })
    });
  }

```
## Expected behavior

I expect that the request is done immediately and is not "on hold"

## Actual Behavior

Request is either not send (the code is running and working 70% of the time) or the server is not responding.

## Your Environment

Windows 10
Node 14.15.1
client Appwrite 2.0.0
server Appwrite 0.7.0

**Comment by TorstenDittmann** [comment]
Can you share the details of the network request that takes too long?

**Comment by TorstenDittmann** [comment]
I am gonna close this issue for now. If you are still having trouble with this issue, we can re-open it again 🙏🏻
