### ISSUE TITLE
401: Permission error on document creation

### ISSUE THREAD

**Issue by iSplasher** [appwrite/appwrite#983]
## 🐛 Bug Report

Hello, I'm getting a 401 error no matter what combinations of permissions and accounts i test with.
I have read access but not write access.
One thing to note is that the account is unverified. But I'm pretty sure this shouldn't be an issue.

## Have you spent some time to check if this issue has been raised before?

The only other issue I could find was #801, but that seemed resolved already?

## To Reproduce

I set permissions on my collection
> ![billede](https://user-images.githubusercontent.com/9113348/111214492-4740fd80-85d2-11eb-98f6-2c0670214224.png)

Notice that I've even tried with the user id and put the user into a team to no avail.
In my client, I create 

> ![billede](https://user-images.githubusercontent.com/9113348/111214621-6dff3400-85d2-11eb-8523-8c5adb6b68dc.png)

The account is created like it should. I can find it in Console under Users also.
I login successfully. I retrieve the session

> ![billede](https://user-images.githubusercontent.com/9113348/111214772-9be47880-85d2-11eb-9184-bb8a7d4c990f.png)
> ![billede](https://user-images.githubusercontent.com/9113348/111214872-c20a1880-85d2-11eb-9b11-3f00bdf52b89.png)

I can even get the session again

> ![billede](https://user-images.githubusercontent.com/9113348/111214905-ccc4ad80-85d2-11eb-983f-773d155ee747.png)

But as soon as I try to create a document I get
> ![billede](https://user-images.githubusercontent.com/9113348/111215615-9dfb0700-85d3-11eb-9231-fc7dd6a6523d.png)

> ![billede](https://user-images.githubusercontent.com/9113348/111215003-e960e580-85d2-11eb-861f-a859d2c20232.png)

## Expected behavior

That account should have write access as specified.

## Your Environment

I'm using NextJS.

![billede](https://user-images.githubusercontent.com/9113348/111215708-bb2fd580-85d3-11eb-9933-b0d93d4f3d10.png)

**Comment by christyjacob4** [comment]
@iSplasher  in your `createDocument()` function can you also add wildcard permissions to the `write` permissions like this

 ` write : ['*'] `

**Comment by iSplasher** [comment]
Oh wow, that worked.
![billede](https://user-images.githubusercontent.com/9113348/111218878-a0f7f680-85d7-11eb-8abf-0177a98f9a39.png)

I must admit that these permissions are a bit confusing.
Wouldn't it make sense to give the owner of the document write permission automatically?
Either way, thank you for the help.

**Comment by christyjacob4** [comment]
Thanks for the feedback @iSplasher . We are in the process of a DB refactoring and during that we will address this issue :) 
You can follow the discussion here https://github.com/appwrite/rfc/pull/21

**Comment by christyjacob4** [comment]
Please close this issue if you don't have any more doubts 😄
