### ISSUE TITLE
More friendly getting started command

### ISSUE THREAD

**Issue by eladcandroid** [appwrite/appwrite#995]
Hi, 
The first installation command - 
```
docker run -it --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
    --entrypoint="install" \
    appwrite/appwrite:0.7.1
```
Looks too "scary" for a new user. 
Can we make it looks nicer?

**Comment by eldadfux** [comment]
Hey @eladcandroid, we actually thought this would be more transparent and allow more confidence for devs who already feel comfortable with Docker.

We did had another idea by asking to install the Appwrite CLI first (which already has a nice install command, you should also check the [source-code](https://appwrite.io/cli/install.sh) - trust me 😅), and then to expose a setup command from the CLI like:

Install CLI:
```bash
curl -sL https://appwrite.io/cli/install.sh | bash
```

Install Server:
```bash
appwrite server setup
```

@christyjacob4 - I would love to get your thoughts as well

**Comment by eladcandroid** [comment]
@eldadfux That sounds like a great idea

**Comment by christyjacob4** [comment]
@eldadfux that sounds like a great plan. But as part of 
'''
appwrite server setup
'''
We also need to be able to specify the params that the current installation command takes in namely the appwrite mount ( in case the user wants to install it somewhere else ) as well as the Appwrite image version ( in case the user wants to install a version other than the latest one )

But yes this is a great idea. I'm all up for it 😎

**Comment by christyjacob4** [comment]
As part of making the installation of Appwrite more friendly, we're planning to add the following commands to the Appwrite CLI 

1. Install Appwrite (Pulls the docker images and starts the server)
```sh
$ appwrite server install
```

2. Start the Appwrite Server
```sh
$ appwrite server start 
```

3. Stop the Appwrite Server
```sh
$ appwrite server stop
```

4. Remove Appwrite server (Stops the server and removes the docker images) 
```sh
$ appwrite server remove
```

5. Appwrite server status (health check)
```sh
$ appwrite server status
```

Let me know what you think

**Comment by eladcandroid** [comment]
@christyjacob4 Looks great!

**Comment by eldadfux** [comment]
Just a quick update. We found it hard to prioritize the Appwrite CLI command for setup, but we are actively working on 1-click setups. We've also upgraded the installation docs to include more manual docker-compose steps for more advanced Docker users.

https://appwrite.io/docs/installation

**Comment by eldadfux** [comment]
Due to lack of community interest and ability to prioritize this issue, I'm closing it for now.
